<h1 style="text-align: center;">HEISENBERG-BASED FAULT LOCALIZATION (HBFL)</h1>

<h2 style="text-align: center;">Download Initial Dependencies</h2>

In [8]:
import numpy as np
import pandas as pd
import json
import math
from tqdm import tqdm
from qiskit.quantum_info import SparsePauliOp, Operator, Pauli, Clifford
import qiskit.qasm2 as q2
from qiskit import QuantumCircuit
from IPython.display import display

from heisenbergUtilities import *

In [9]:
# from qiskit_aer import AerSimulator
# simulator = AerSimulator()

# print(simulator.available_devices())

<h2 style="text-align: center;">CONTROL PANEL</h2>

In [10]:
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
#-------------------------------------------------------------------------GENERAL PARAMETERS---------------------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
ALG_NAME = "qpeexact"
ORIGINAL_QASM = f"{ALG_NAME}_5_qubits.qasm"                                                 #| The original algorithm QASM circuit file name.                           
ORIGINAL_QASM_FOLDER = "SBFL_circuits/MQTBench/"                                            #| The folder containing the original QASM circuit file.                    
QASM_MUTANT_FOLDER = f"SBFL_circuits/QMutBenchMutants/Mutants_{ALG_NAME}_5_qubits/"         #| The folder containing all mutants related to the original QASM circuit.  
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
#-------------------------------------------------------------------------SB-QOPS PARAMETERS---------------------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
RUNS = 10                                                                                   #| Number of times SB-QOPS will run to find a failing or passing test case.            
SHOTS = 20000                                                                               #| Number of shots for SB-QOPS to use to create the compact program specification.     
EPOCH = 80                                                                                  #| Number of epochs SB-QOPS will run to navigate the search space of test cases.       
SBQOPS_TOL = 0.1                                                                            #| Tolerance value SB-QOPS uses to determine if a test case is failing or passing.     
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
#---------------------------------------------------------------------HEISENBERG SBFL PARAMETERS-----------------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
LAMBDA_PHASE = 2                                                                        #| The hyperparameter used to weight the phase change of the Pauli propagation
LAMBDA_CHANGE = 1                                                                         #| The hyperparameter used to weight the change of string of the Pauli propagation
LAMBDA_SIMILARITY = 1                                                                       #| The hyperparameter used to weight the similarity difference between current and target Pauli
ATOL = 1e-4                                                                                 #| The tolerance value used to prune negligible magnitudes during Pauli propagation.   
MAX_TERMS = 100                                                                             #| The maximum number of terms to keep during Pauli propagation. If None, use all.     
SEARCH_STEP = 3                                                                             #| The search step size used during Pauli propagation. If None, pauli-prop uses 4.     
VERBOSE = 1                                                                                 #| A boolean value to determine if the program should print out detailed information.  
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#

Generate the linked list of all operations that take place in the inverse circuit

In [11]:
"""
LinkedListNode: A class that holds information related to a gate in a quantum circuit. 

PROPERTIES:
    - value (String): The name of the quantum gate
    - depth (int): The depth of the gate in the circuit
    - count (Int): The probability that the gate will meaningfully change the Pauli string.
    - next (LinkedListNode): The next gate in the circuit

"""

class LinkedListNode:
    def __init__(self, name="Initial", depth=0, count=0,  next=None):
        self.value = name
        self.depth = depth
        self.next = next
        self.count = count

class LinkedList:
    def __init__(self):
        self.head = None

    def append(self, name, depth):
        new_node = LinkedListNode(name, depth)
        if not self.head:
            self.head = new_node
            return
        last_node = self.head
        while last_node.next:
            last_node = last_node.next
        last_node.next = new_node

    def mark(self, depth):
        current_node = self.head
        while current_node:
            if current_node.depth == depth:
                current_node.count += 1
                return
            current_node = current_node.next

    def reset(self):
        current_node = self.head
        while current_node:
            current_node.count = 0
            current_node = current_node.next

<h3>Download MQT Benchmark circuits.</h3>

We'll start with DJ, RealAmpRandom, and GHZ since SB-QOPS caught those mutants 100% of the time for 5 qubit circuits

<h3>Generate mutants.</h3>

We'll start with mutants that add an unnecessary gate, then add mutants that replace a certain gate later.

The mutants were downloaded from QMutBench, choosing specifically mutants that added a gate anywhere with 0-10% survival scores

In [12]:
correct_circuit = load_program(ORIGINAL_QASM, ORIGINAL_QASM_FOLDER).copy()
correct_list = LinkedList()
correct_list = construct_list(correct_list, correct_circuit, inverse=False)

<h2 style="text-align: center;"> SB-QOPS </h2>

This is where we will use SB-QOPS on a provided circuit and its mutants

For a single mutant, it took about 2 minutes to generate a 20 test suite (10 fail, 10 pass) on an RTX 4090 SUPER. It can only be run on a Linux environment since the AER Simulator does not support Windows

There are 113 mutants for the DJ algorithm in use: 226 minutes or 3 3/4 hours

There are 89 mutants for the GHZ algorithm in use: 178 minutes or about 3 hours

There are 125 mutants for the RealAmpRandom algorithm in use: 250 minutes or just over 4 hours

BUT this cell should only need to be run once per algorithm with mutants under test. After it saves to the csv file at the end, this cell can be commented out as to not accidentally run it again. 

In the future if we want to test this methodology on higher qubit circuits or other algorithms, we'll likely either want to reduce the number of tests in the suite or the number of mutants we're analyzing

In [13]:
# import QOPS as qops
# from QOPS_test import get_compact_program_specification_Z
# from pathlib import Path

# ga_result = pd.DataFrame(columns=['Program',"path_to_mutant",'catch_avg','avg_fitness','failing_testcases', 'passing_testcases'])
# program_history = {}

# #program_specification = The compact program specification. SB-QOPS needs this to generate failing test cases.
# # In a public-use environment, this would be provided by the user.
# program_specification = get_compact_program_specification_Z(correct_circuit, shots=SHOTS)

# #mutants = A python list of qiskit QuantumCircuit variables with a mutation in them
# mutants = []
# mutants_names = []
# root = Path(QASM_MUTANT_FOLDER)
# for qasm_mutant in root.rglob("*.qasm"):
#     mutants.append(load_program(qasm_mutant.name, QASM_MUTANT_FOLDER))
#     mutants_names.append(qasm_mutant.name)

# for mutant_index,mutant in enumerate(mutants):
#     tester = qops.Circuit_Tester(CUT=mutant)
#     tester.set_applicable_families_Z(program_specification)
#     mutants_per_run = []
#     fitness_per_run = []
#     failing_testcases_per_run = []
#     history_per_run = []

#     print("NOW RUNNING TO FIND FAILING TESTS")
#     #For a predefined number of attempts, try to find a set of failing test cases (output is above predefined tolerance)
#     for runs in range(RUNS):
#         killed = 0
#         pauli = {}
#         fitness = 0
#         for i in range(len(tester.applicable_families)):
#             best_function,testcase, history = tester.run_mealoneplusone(i, EPOCH)
#             if best_function > SBQOPS_TOL:
#                 killed = 1
#                 pauli = testcase
#                 fitness = best_function
#                 break
#         mutants_per_run.append(killed)
#         failing_testcases_per_run.append(pauli)
#         fitness_per_run.append(fitness)
#         history_per_run.append(history)

#     avg_score = np.mean(mutants_per_run)
#     avg_fitness = np.mean(fitness_per_run)

#     #Here is our new, modified algorithm from the SB-QOPS method that attempts to find passing test cases as well. We'll need them for SBFL
#     passing_testcases_per_run = []

#     print("NOW RUNNING TO FIND PASSING TESTS")
#     for runs in range(RUNS):
#         pauli = {}
#         fitness = 0
#         for i in range(len(tester.applicable_families)):
#             best_function, testcase, history = tester.run_reverse_mealoneplusone(i,EPOCH)
#             if best_function < SBQOPS_TOL:
#                 pauli = testcase
#                 break
#         passing_testcases_per_run.append(pauli)

#     #Replace static program file with "program_name" when ready to test fully
#     """
#     ga_result: A pandas dataframe with the following columns
#         Program: Name of the mutant quantum circuit file
#         Path_To_Mutant: Path to the mutant file
#         Catch_Avg: The average number of times the mutant was identified by SB-QOPS
#         Avg_Fitness: The average fitness of the search algorithm used. Higher usually indicates higher Catch_Avg
#         Failing_Testcases: A list of dicts indicating the set of Pauli strings and the weights that should be applied to generate a failing test case
#         Passing_Testcases: A list of dicts indicating the set of Pauli strings and the weights that should be applied to generate a passing test case
#     """
#     ga_result = pd.concat([pd.DataFrame([[mutants_names[mutant_index],QASM_MUTANT_FOLDER,avg_score,avg_fitness,json.dumps(failing_testcases_per_run), json.dumps(passing_testcases_per_run)]],columns=ga_result.columns),ga_result],ignore_index=True)
#     ga_result.to_csv(f'realamprandom_ga_result', index=False)

ga_result is a slightly altered pandas Dataframe with similar structure found in SB-QOPS's results folder. The differences are changing the column "Program" to be the name of the mutant file instead of the original quantum circuit, changing "Mutant" to be the path to the mutant file instead of being an arbitrary index value, and adding a passing_testcases column that returns Pauli strings and coefficients that generate passing tests.

Now we want to run SBFL using Heisenberg evolution trees on each circuit placed in ga_result

Evolution analysis tends to take about 5 minutes for 10 failing tests on a very complex algorithm such as QNN, so about 10 minutes for 20 total tests

DJ was a relatively small algorithm with few to no branching gates, so it only ended up taking about 5-6 minutes to evolve and analyze all 113 DJ mutants

About 890 minutes for GHZ, or 14.8 hours to evolve and analyze all 89 GHZ mutants

About 1250 minutes for RealAmpRandom, or 20.8 hours to evolve and analyze all 125 RealAmpRandom mutants

The runtime of this code segment is directly tied to the depth of the circuit being analyzed and the number of 2-branching gates such as rotation or phase gates that exist in the circuit.

This is something to note in the final paper. Regardless of accuracy this methodology takes a long time to run. If results are promising, then we'll want to look into the tradeoffs between EXAM and hyperparameters to speed this up. Primarily the atol, max_terms, and search_step parameters in the evolve_pauli_exact method in HeisenbergUtilities.py

<h2 style="text-align: center;">HEISENBERG EVOLUTIONS (PAULI PROPAGATION)</h2>

In [14]:
from heisenbergTree import *

ga_result = pd.read_csv(f'{ALG_NAME}_ga_result.csv')
tarantula_sbfl_result = pd.DataFrame(columns=['Program','path_to_mutant','exam_score'])
barinel_sbfl_result = pd.DataFrame(columns=['Program','path_to_mutant','exam_score'])
mutant_num = 0

#For each mutant of a circuit, run the SBFL implementation
for mutant, path in zip(ga_result.loc[:,"Program"], ga_result.loc[:,"path_to_mutant"]):
    print("Now evolving the following mutant: ", mutant)

    #Extract the raw test cases found for each mutant
    desired_failing_testcases = ga_result.loc[(ga_result["Program"] == mutant), ["failing_testcases"]]
    desired_passing_testcases = ga_result.loc[(ga_result["Program"] == mutant), ["passing_testcases"]]

    dict_failing_testcases = desired_failing_testcases.to_dict()
    dict_passing_testcases = desired_passing_testcases.to_dict()

    string_failing_testcases = dict_failing_testcases['failing_testcases'][mutant_num]
    string_passing_testcases = dict_passing_testcases['passing_testcases'][mutant_num]

    list_failing_testcases = json.loads(string_failing_testcases)
    list_passing_testcases = json.loads(string_passing_testcases)

    #Remove empty tests
    raw_failing_testcases = remove_null_tests(list_failing_testcases)
    raw_passing_testcases = remove_null_tests(list_passing_testcases)

    circuit_inverse = load_program(mutant,path).copy().inverse()  # Invert to track backward evolution of the operator
    forward_mutant = load_program(mutant, path).copy()

    #Create the linked list of operations in the inverse circuit
    operation_list = LinkedList()
    operation_list = construct_list(operation_list, circuit_inverse, True)

    forward_list = LinkedList()
    forward_list = construct_list(forward_list, forward_mutant, False)

    #Create list of nodes in linked list. Somewhere down the road remove the linked list implementation. It's unnecessary and giving me a headache
    node_list = []
    node = operation_list.head
    while node:
        node_list.append(node)
        node = node.next

    #Perform Pauli propagation (Heisenberg evolution) for all test cases. Returns a dataframe with all counts for all operations
    global_frame_fail = heisenberg_evolve(circuit_inverse, 
                                          operation_list, 
                                          raw_failing_testcases, 
                                          "fail", 
                                          LAMBDA_PHASE, 
                                          LAMBDA_CHANGE, 
                                          LAMBDA_SIMILARITY, 
                                          atol = ATOL, 
                                          max_terms = MAX_TERMS, 
                                          search_step = SEARCH_STEP)
    
    global_frame_pass = heisenberg_evolve(circuit_inverse, 
                                          operation_list, 
                                          raw_passing_testcases, 
                                          "pass", 
                                          LAMBDA_PHASE, 
                                          LAMBDA_CHANGE, 
                                          LAMBDA_SIMILARITY, 
                                          atol = ATOL, 
                                          max_terms = MAX_TERMS, 
                                          search_step = SEARCH_STEP)

    global_frame = pd.concat([global_frame_fail, global_frame_pass], ignore_index=True)

    global_frame = global_frame.drop(["Initial"],axis=1)
    if VERBOSE:
        display(global_frame)

    tarantula_scores = tarantula(global_frame)
    barinel_scores = barinel(global_frame)

    if VERBOSE:
        print("BARINEL SCORES")
        display(barinel_scores)
        print("TARANTULA SCORES")
        display(tarantula_scores)
    
    # Here is where analysis of the methodology begins. 
    # We first extract the position of the erroneous gate by comparing it to the original MQT gate
    # NOTE: This method is intended for single-added gates for now. Other types of mutants will require other methods later
    error_gate_location = find_erroneous_gate(forward_mutant, correct_circuit)

    if VERBOSE:
        print("ERROR GATE LOCATION:")
        print(error_gate_location)

    # Calculate the EXAM score for Barinel by counting the number of gates we would have to observe before we reach the erroneous gate.
    gates_observed = 0
    barinel_exam_score = 0
    for col_name, col_date in barinel_scores.items():
        gates_observed += 1

        #Extract depth from column name
        gate_depth = int(col_name.split()[1])

        if gate_depth == error_gate_location:
            barinel_exam_score = gates_observed/(circuit_inverse.size())
            break

    # Calculate the EXAM score for Tarantula by counting the number of gates we would have to observe before we reach the erroneous gate.
    gates_observed = 0
    tarantula_exam_score = 0
    for col_name, col_date in tarantula_scores.items():
        gates_observed += 1

        #Extract depth from column name
        gate_depth = int(col_name.split()[1])

        if gate_depth == error_gate_location:
            tarantula_exam_score = gates_observed/(circuit_inverse.size())
            break

    # Here we store the results from the HBFL analysis for both barinel and tarantula into a csv file for later analysis.
    barinel_sbfl_result = pd.concat([pd.DataFrame([[mutant,QASM_MUTANT_FOLDER,barinel_exam_score]],columns=barinel_sbfl_result.columns),barinel_sbfl_result],ignore_index=True)
    barinel_sbfl_result.sort_values(by=['exam_score'], ascending=False)
    barinel_sbfl_result.to_csv(f'{ALG_NAME}_barinel_sbfl_result.csv', index=False)

    tarantula_sbfl_result = pd.concat([pd.DataFrame([[mutant,QASM_MUTANT_FOLDER,tarantula_exam_score]],columns=tarantula_sbfl_result.columns),tarantula_sbfl_result],ignore_index=True)
    tarantula_sbfl_result.sort_values(by=['exam_score'], ascending=False)
    tarantula_sbfl_result.to_csv(f'{ALG_NAME}_tarantula_sbfl_result.csv', index=False)

    mutant_num += 1

if VERBOSE:
    display(barinel_sbfl_result)
    display(tarantula_sbfl_result)

Now evolving the following mutant:  AddGate_y_inGap_9_.qasm

  0%|          | 0/10 [00:00<?, ?it/s]

100%|██████████| 10/10 [00:39<00:00,  3.99s/it]
100%|██████████| 10/10 [00:41<00:00,  4.14s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,y 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.539234,0.791537,0.401934,0.111636,0.760402,1.017375,0.488838,0.977856,0.355861,1.226513,...,0.387754,1.078502,0.300790,1.156294,0.152645,0.495605,0.293450,0.258724,0.263727,fail
1,0.586147,0.871685,0.418678,0.121474,0.698199,0.961836,0.457415,0.887303,0.334486,1.161036,...,0.340350,1.007323,0.277582,1.185145,0.145437,0.421422,0.268147,0.238052,0.258499,fail
2,0.472807,0.734793,0.316530,0.092475,0.599763,0.747743,0.355460,0.682064,0.270455,0.895294,...,0.313248,0.806797,0.215508,0.912850,0.115231,0.344795,0.207687,0.189896,0.201115,fail
3,0.504371,0.735491,0.364344,0.107342,0.648379,0.885665,0.429787,0.871451,0.329923,1.142263,...,0.314227,0.929933,0.250460,1.056675,0.143818,0.427162,0.258149,0.219827,0.234315,fail
4,0.432447,0.654748,0.298943,0.098716,0.576863,0.763969,0.385656,0.709691,0.261371,0.935523,...,0.289235,0.843344,0.239736,0.936957,0.116851,0.425163,0.227242,0.208937,0.213006,fail
5,0.605406,0.877627,0.412200,0.125801,0.726220,1.014731,0.485417,0.837148,0.329255,1.125963,...,0.327589,0.978322,0.294748,1.178977,0.152918,0.423211,0.257963,0.246852,0.255088,fail
6,0.615256,0.921742,0.395683,0.130843,0.676089,0.931106,0.429381,0.692124,0.265414,0.935276,...,0.207725,0.762909,0.248028,1.093910,0.129434,0.376548,0.213405,0.223205,0.238793,fail
7,0.636323,0.913075,0.422326,0.134188,0.858247,1.138007,0.551507,0.997655,0.357717,1.246209,...,0.340076,1.103151,0.346629,1.311917,0.160662,0.568685,0.311847,0.297509,0.298932,fail
8,0.388406,0.568526,0.270751,0.086752,0.489046,0.699970,0.337203,0.636689,0.258765,0.905054,...,0.272678,0.774920,0.193964,0.825845,0.108964,0.350883,0.204592,0.173543,0.186263,fail
9,0.527898,0.804508,0.361309,0.109378,0.722811,0.939093,0.476183,0.902636,0.346323,1.186340,...,0.390863,1.026363,0.296756,1.078834,0.141452,0.459972,0.273251,0.246718,0.240065,fail
10,0.581324,0.891945,0.411542,0.124204,0.720350,0.959707,0.445781,0.789947,0.311412,1.043098,...,0.329870,0.886441,0.270269,1.096136,0.149304,0.418293,0.236942,0.234027,0.237118,pass
11,0.496230,0.751722,0.331404,0.107041,0.570108,0.753747,0.374169,0.658991,0.275697,0.933503,...,0.330703,0.815915,0.225139,0.956514,0.124153,0.359136,0.210615,0.197120,0.207403,pass
12,0.340974,0.514669,0.222906,0.067200,0.458082,0.609787,0.297326,0.513478,0.202414,0.668439,...,0.210348,0.578422,0.186099,0.630321,0.090385,0.255958,0.144816,0.145933,0.137371,pass
13,0.370183,0.564815,0.242227,0.078495,0.424364,0.547731,0.274104,0.538953,0.225690,0.761046,...,0.281481,0.649368,0.163306,0.700424,0.094465,0.280510,0.162812,0.145713,0.153426,pass
14,0.458403,0.700336,0.309419,0.098470,0.632847,0.869866,0.425162,0.686471,0.262136,0.921681,...,0.259919,0.804566,0.254466,0.906382,0.127543,0.383881,0.209921,0.205764,0.197886,pass
15,0.574038,0.862101,0.436040,0.115966,0.612294,0.800320,0.364717,0.866771,0.302076,1.080047,...,0.257465,0.930018,0.219606,1.213934,0.136340,0.412614,0.274407,0.218930,0.270412,pass
16,0.545959,0.836630,0.361566,0.114451,0.727445,0.873777,0.434337,0.911487,0.330918,1.142953,...,0.325760,0.987620,0.271244,1.191492,0.140094,0.509053,0.291897,0.251955,0.274001,pass
17,0.565942,0.837408,0.397166,0.116357,0.776567,0.976141,0.486432,0.928326,0.337418,1.151237,...,0.349772,1.022093,0.306308,1.183212,0.142421,0.479954,0.283450,0.263905,0.268599,pass
18,0.466245,0.677260,0.326110,0.098824,0.631049,0.842192,0.411221,0.796234,0.304333,1.026124,...,0.325353,0.900180,0.264670,0.992087,0.135744,0.428332,0.242631,0.220797,0.219071,pass
19,0.402075,0.539647,0.250423,0.080981,0.599197,0.818134,0.401431,0.737587,0.295449,0.960526,...,0.311361,0.808464,0.244466,0.782954,0.122659,0.364558,0.205868,0.188699,0.176299,pass

BARINEL SCORES

,cp 16,cp 15,cp 18,h 0,cp 19,cp 5,h 2,h 1,cp 7,cp 12,...,h 14,h 3,h 17,cp 20,y 13,x 4,h 11,cp 9,swap 10,swap 8
sum,0.530555,0.529006,0.527496,0.527389,0.526893,0.526579,0.526404,0.526327,0.526236,0.526184,...,0.524527,0.524503,0.523385,0.523162,0.521993,0.519826,0.519715,0.517896,0.51639,0.516357

TARANTULA SCORES

,cp 16,cp 15,cp 18,h 0,cp 19,cp 5,h 2,h 1,cp 7,cp 12,...,h 14,h 3,h 17,cp 20,y 13,x 4,h 11,cp 9,swap 10,swap 8
sum,0.530555,0.529006,0.527496,0.527389,0.526893,0.526579,0.526404,0.526327,0.526236,0.526184,...,0.524527,0.524503,0.523385,0.523162,0.521993,0.519826,0.519715,0.517896,0.51639,0.516357

ERROR GATE LOCATION:
13
Now evolving the following mutant:  AddGate_y_inGap_10_.qasm

100%|██████████| 10/10 [00:41<00:00,  4.14s/it]
100%|██████████| 10/10 [00:41<00:00,  4.19s/it]

,h 21,cp 20,cp 19,cp 18,h 17,y 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.613064,0.914287,0.421502,0.127442,0.713636,0.362009,0.977409,0.477594,0.886860,1.153807,...,0.305042,0.971593,0.281762,1.197707,0.141645,0.436043,0.264295,0.239738,0.258562,fail
1,0.518744,0.769256,0.339283,0.106378,0.627104,0.317630,0.846170,0.402455,0.704211,0.932163,...,0.228191,0.778416,0.238342,1.006234,0.128472,0.375771,0.217578,0.209437,0.222666,fail
2,0.656560,0.965907,0.450841,0.132468,0.715907,0.352036,0.933052,0.432988,0.811306,1.031076,...,0.280711,0.902807,0.266905,1.232715,0.154254,0.428022,0.256681,0.245038,0.273118,fail
3,0.508766,0.724202,0.332432,0.107360,0.610406,0.339655,0.889640,0.423098,0.702436,0.981086,...,0.282809,0.834758,0.252144,0.943290,0.130044,0.368060,0.209933,0.206004,0.204824,fail
4,0.512304,0.746311,0.376864,0.107927,0.689968,0.375998,0.997944,0.459026,0.811562,1.068223,...,0.334078,0.926664,0.276423,1.006545,0.131301,0.388783,0.236429,0.224950,0.218420,fail
5,0.455457,0.704814,0.314795,0.087756,0.660271,0.343487,0.902722,0.406890,0.752600,0.954446,...,0.324406,0.858725,0.260619,0.865015,0.123762,0.350974,0.211491,0.205011,0.188763,fail
6,0.640399,0.889818,0.426708,0.128680,0.723766,0.366145,0.945819,0.457558,0.958229,1.229574,...,0.366535,1.112991,0.290923,1.282926,0.163702,0.524451,0.306286,0.260236,0.295289,fail
7,0.610396,0.947512,0.396099,0.127104,0.835166,0.413303,1.071052,0.528659,0.917738,1.176962,...,0.325145,1.040439,0.325529,1.231103,0.150738,0.513770,0.286236,0.280571,0.278571,fail
8,0.425316,0.648945,0.296653,0.086404,0.619907,0.327035,0.850048,0.396945,0.719778,0.941946,...,0.315690,0.818213,0.252140,0.811714,0.120396,0.330073,0.198073,0.192709,0.172125,fail
9,0.614875,0.931915,0.396277,0.129819,0.807869,0.419161,1.056026,0.529132,0.915117,1.197254,...,0.381607,1.046621,0.327763,1.205710,0.162088,0.484393,0.274133,0.269698,0.263191,fail
10,0.549431,0.832249,0.371362,0.116074,0.657342,0.326967,0.878930,0.423111,0.771203,1.027874,...,0.264218,0.897714,0.253584,1.135134,0.133389,0.430125,0.257178,0.232953,0.254978,pass
11,0.414242,0.622577,0.278606,0.093093,0.557421,0.281747,0.722052,0.376230,0.680321,0.901502,...,0.277856,0.798626,0.233063,0.927804,0.119142,0.405132,0.218307,0.202599,0.206313,pass
12,0.432368,0.644412,0.284465,0.087397,0.604800,0.317008,0.800722,0.392921,0.705072,0.889667,...,0.260466,0.750227,0.242815,0.830077,0.114859,0.351679,0.201866,0.195603,0.183782,pass
13,0.495838,0.724415,0.357823,0.104051,0.630456,0.326567,0.867117,0.411875,0.744986,0.958908,...,0.277249,0.843832,0.264153,1.012616,0.127574,0.413131,0.236690,0.224870,0.225859,pass
14,0.513891,0.822834,0.335738,0.108203,0.610060,0.299946,0.764908,0.395748,0.679654,0.917183,...,0.325967,0.803990,0.242920,1.004629,0.128076,0.347300,0.206931,0.206612,0.210788,pass
15,0.443911,0.679640,0.273689,0.095160,0.624760,0.313748,0.777628,0.398839,0.676776,0.832356,...,0.239574,0.720733,0.260327,0.879506,0.119185,0.412864,0.202734,0.211494,0.197417,pass
16,0.528187,0.809505,0.362553,0.114492,0.672558,0.329789,0.855217,0.442358,0.820059,1.117449,...,0.304452,0.923516,0.259530,1.170646,0.136180,0.432779,0.257675,0.227330,0.253560,pass
17,0.403005,0.627051,0.255459,0.079407,0.526195,0.265811,0.688021,0.328932,0.598277,0.824884,...,0.229513,0.710242,0.196855,0.800588,0.106085,0.310066,0.188409,0.170155,0.176725,pass
18,0.726521,1.063024,0.484639,0.150125,0.884955,0.439446,1.154985,0.553696,0.950868,1.175241,...,0.249447,0.982943,0.331462,1.366006,0.158801,0.531656,0.296978,0.300059,0.310720,pass
19,0.535529,0.846617,0.366445,0.109955,0.725047,0.354329,0.900813,0.449277,0.789041,0.991289,...,0.268411,0.836668,0.275854,1.077484,0.130691,0.404502,0.243515,0.238724,0.236883,pass

BARINEL SCORES

,swap 8,cp 15,cp 7,cp 19,y 16,cp 12,x 4,swap 10,h 13,h 21,...,cp 14,cp 18,h 17,cp 20,h 11,h 2,cp 5,h 1,h 0,h 3
sum,0.538267,0.529627,0.529122,0.526724,0.526274,0.52537,0.524702,0.524618,0.52448,0.524199,...,0.519647,0.518957,0.518907,0.517927,0.517551,0.515808,0.513781,0.513534,0.51279,0.509776

TARANTULA SCORES

,swap 8,cp 15,cp 7,cp 19,y 16,cp 12,x 4,swap 10,h 13,h 21,...,cp 14,cp 18,h 17,cp 20,h 11,h 2,cp 5,h 1,h 0,h 3
sum,0.538267,0.529627,0.529122,0.526724,0.526274,0.52537,0.524702,0.524618,0.52448,0.524199,...,0.519647,0.518957,0.518907,0.517927,0.517551,0.515808,0.513781,0.513534,0.51279,0.509776

ERROR GATE LOCATION:
16
Now evolving the following mutant:  AddGate_x_inGap_4_.qasm

100%|██████████| 10/10 [00:47<00:00,  4.78s/it]
100%|██████████| 10/10 [00:40<00:00,  4.05s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,cp 8,cp 7,cp 6,x 5,h 4,x 3,h 2,h 1,h 0,pass/fail
0,0.589494,0.849707,0.405060,0.119459,0.629245,0.799873,0.405609,0.839805,1.104306,1.037811,...,0.947708,0.253307,1.159474,0.145104,0.439388,0.194565,0.263553,0.227203,0.258764,fail
1,0.472889,0.695053,0.318345,0.096416,0.632129,0.848516,0.400845,0.702032,0.887790,0.894890,...,0.805619,0.254469,0.907709,0.124365,0.392060,0.163365,0.217382,0.217026,0.209021,fail
2,0.661108,1.016034,0.427332,0.138983,0.750828,0.943159,0.458795,0.819891,1.087294,1.046559,...,0.914696,0.268184,1.298880,0.151304,0.462554,0.192862,0.265025,0.252803,0.285377,fail
3,0.606936,0.889262,0.410161,0.130681,0.742804,0.921767,0.470762,0.888768,1.136387,1.217839,...,0.997663,0.297251,1.228623,0.148957,0.528616,0.215403,0.282841,0.267875,0.281936,fail
4,0.473643,0.675875,0.315654,0.094915,0.524851,0.720462,0.352495,0.661578,0.899896,0.785048,...,0.764023,0.215930,0.884012,0.116777,0.325566,0.152558,0.201058,0.181272,0.195731,fail
5,0.537156,0.758203,0.344151,0.114940,0.639348,0.849412,0.432937,0.848433,1.120571,1.121024,...,0.986152,0.266046,1.067135,0.148614,0.476377,0.200984,0.259499,0.225079,0.238260,fail
6,0.557371,0.776029,0.350818,0.113692,0.610722,0.796152,0.379315,0.716889,0.907419,0.965492,...,0.772702,0.229985,1.063093,0.131421,0.415554,0.178337,0.231509,0.212695,0.238998,fail
7,0.515478,0.783856,0.352256,0.106572,0.628981,0.866055,0.410483,0.768372,1.004787,0.915908,...,0.879871,0.253919,1.006250,0.140976,0.380284,0.169306,0.225780,0.211140,0.213827,fail
8,0.446548,0.628630,0.305762,0.086766,0.568417,0.780420,0.359122,0.768167,0.953270,0.852653,...,0.875037,0.233801,0.920565,0.121567,0.370561,0.160040,0.233084,0.200510,0.208844,fail
9,0.555183,0.863065,0.388426,0.114983,0.729380,0.925647,0.461651,0.837639,1.076928,0.955416,...,0.964129,0.287568,1.157486,0.144797,0.427275,0.176284,0.255949,0.244863,0.249669,fail
10,0.557873,0.865206,0.388571,0.112812,0.648191,0.799623,0.381896,0.849566,1.066170,0.928418,...,0.924317,0.239949,1.189590,0.133697,0.435526,0.169594,0.269543,0.226283,0.264087,pass
11,0.392023,0.547572,0.254251,0.079838,0.398350,0.531561,0.274227,0.524679,0.703058,0.631871,...,0.613248,0.167330,0.804606,0.090461,0.295803,0.118640,0.176351,0.152384,0.180572,pass
12,0.392773,0.628218,0.273946,0.080744,0.560120,0.729255,0.329893,0.654486,0.795713,0.742786,...,0.669003,0.201828,0.780856,0.105749,0.292774,0.133036,0.177446,0.170868,0.167327,pass
13,0.654932,1.000743,0.442448,0.136446,0.774926,1.024274,0.478702,0.918127,1.170197,1.066122,...,0.978880,0.290157,1.246954,0.147643,0.465495,0.195650,0.276391,0.259898,0.275266,pass
14,0.544784,0.784565,0.394961,0.109184,0.649723,0.825954,0.401143,0.925883,1.189924,0.987203,...,1.045589,0.244227,1.200754,0.142018,0.458881,0.183098,0.293393,0.229649,0.271429,pass
15,0.472655,0.716495,0.344205,0.098233,0.492891,0.656025,0.304208,0.569421,0.729171,0.672027,...,0.632090,0.184527,1.001515,0.107896,0.319777,0.126648,0.197511,0.179970,0.218992,pass
16,0.482657,0.765059,0.307866,0.103144,0.661060,0.835403,0.414099,0.730727,0.957620,0.994795,...,0.840142,0.257180,0.950081,0.131055,0.419432,0.174121,0.221685,0.222391,0.213698,pass
17,0.619792,0.955779,0.418730,0.139732,0.699979,0.907367,0.443044,0.828018,1.143740,1.099293,...,1.006598,0.270247,1.207491,0.155208,0.475578,0.203442,0.262448,0.243722,0.263202,pass
18,0.186236,0.293865,0.131371,0.044698,0.498417,0.743152,0.378793,0.544258,0.779067,0.732320,...,0.704939,0.234063,0.375930,0.098314,0.261975,0.128191,0.134035,0.148761,0.078871,pass
19,0.664879,0.961149,0.460908,0.132170,0.760065,1.060779,0.503841,0.969173,1.264775,1.011619,...,1.087528,0.298045,1.295024,0.165096,0.441917,0.194821,0.290521,0.255977,0.279962,pass

BARINEL SCORES

,swap 11,x 3,h 12,cp 10,h 4,h 21,cp 18,x 5,h 0,cp 7,...,h 2,cp 19,cp 15,cp 20,h 17,swap 9,cp 8,h 14,cp 16,cp 13
sum,0.526321,0.525716,0.524819,0.522678,0.52171,0.521532,0.518661,0.518247,0.518179,0.517472,...,0.514399,0.514264,0.513813,0.513493,0.51242,0.5124,0.511639,0.510974,0.510204,0.509491

TARANTULA SCORES

,swap 11,x 3,h 12,cp 10,h 4,h 21,cp 18,x 5,h 0,cp 7,...,h 2,cp 19,cp 15,cp 20,h 17,swap 9,cp 8,h 14,cp 16,cp 13
sum,0.526321,0.525716,0.524819,0.522678,0.52171,0.521532,0.518661,0.518247,0.518179,0.517472,...,0.514399,0.514264,0.513813,0.513493,0.51242,0.5124,0.511639,0.510974,0.510204,0.509491

ERROR GATE LOCATION:
3
Now evolving the following mutant:  AddGate_x_inGap_5_.qasm

100%|██████████| 10/10 [00:48<00:00,  4.80s/it]
100%|██████████| 10/10 [00:44<00:00,  4.41s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,cp 8,cp 7,cp 6,x 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.656489,0.957733,0.419988,0.134662,0.727890,0.863661,0.435045,0.830482,1.010383,1.107858,...,0.864245,0.265733,1.316118,0.159565,0.159565,0.495668,0.274240,0.254074,0.293656,fail
1,0.665395,0.995934,0.453216,0.138148,0.796644,0.989226,0.481051,0.884969,1.113206,1.043535,...,0.991082,0.293505,1.345933,0.162749,0.162749,0.481111,0.288474,0.270615,0.296344,fail
2,0.630305,0.924459,0.433093,0.131166,0.624630,0.839725,0.398913,0.773852,1.030529,0.950445,...,0.879576,0.236767,1.169955,0.144009,0.144009,0.407494,0.242197,0.220014,0.256444,fail
3,0.575374,0.865497,0.406911,0.119593,0.762645,0.999791,0.496733,0.939474,1.168026,1.097791,...,0.973679,0.307569,1.232513,0.156223,0.156223,0.461310,0.275833,0.255666,0.264743,fail
4,0.432629,0.612021,0.297525,0.087266,0.553117,0.720398,0.344036,0.801310,1.012733,0.979183,...,0.884507,0.212543,0.952648,0.126333,0.126333,0.424744,0.249378,0.194051,0.222385,fail
5,0.638744,0.989765,0.507726,0.131832,0.803178,1.084602,0.506395,0.963834,1.213822,0.908164,...,1.036386,0.294182,1.383549,0.159272,0.159272,0.431668,0.301470,0.269488,0.299746,fail
6,0.602196,0.915662,0.385328,0.121715,0.766702,0.963323,0.473418,0.837319,1.022638,1.048500,...,0.860194,0.291873,1.135783,0.147970,0.147970,0.436252,0.245084,0.248002,0.247680,fail
7,0.502823,0.737280,0.343000,0.104967,0.572980,0.796640,0.399133,0.762663,1.025436,0.881410,...,0.863727,0.243592,1.027655,0.128998,0.128998,0.389962,0.234946,0.202844,0.222427,fail
8,0.549321,0.817085,0.374090,0.118180,0.656283,0.805761,0.411317,0.838806,1.066457,1.100319,...,0.923483,0.247393,1.182944,0.149956,0.149956,0.480808,0.270514,0.233057,0.264534,fail
9,0.663590,1.015385,0.476007,0.135918,0.786875,1.072229,0.498666,0.942985,1.220471,0.993748,...,1.020267,0.294205,1.320636,0.160560,0.160560,0.429355,0.283729,0.259529,0.283458,fail
10,0.645769,0.933075,0.427279,0.126356,0.765688,0.939245,0.457455,0.911336,1.092641,1.071000,...,0.964738,0.288207,1.287887,0.149384,0.149384,0.477108,0.285097,0.259854,0.289220,pass
11,0.458726,0.658439,0.310572,0.094567,0.472160,0.608145,0.293389,0.594712,0.765432,0.714692,...,0.693392,0.185005,0.923992,0.105544,0.105544,0.335042,0.198872,0.174892,0.208025,pass
12,0.512861,0.773888,0.366621,0.107085,0.608808,0.777730,0.385478,0.766898,0.979435,0.936951,...,0.844315,0.244600,1.061582,0.135142,0.135142,0.412610,0.242968,0.217648,0.235336,pass
13,0.546804,0.807441,0.354118,0.111269,0.708571,0.944542,0.463732,0.825994,1.078386,0.937464,...,0.869737,0.270246,1.088991,0.129968,0.129968,0.403566,0.247728,0.230200,0.243052,pass
14,0.322672,0.452842,0.207318,0.063746,0.423026,0.552968,0.272267,0.492007,0.627092,0.604015,...,0.555203,0.171845,0.638245,0.090160,0.090160,0.259962,0.151876,0.140721,0.140649,pass
15,0.517220,0.766448,0.377691,0.103927,0.540847,0.721636,0.348635,0.786147,1.043121,0.862195,...,0.944103,0.224661,1.093651,0.136346,0.136346,0.374079,0.246916,0.202100,0.237705,pass
16,0.576668,0.913656,0.387498,0.124705,0.680015,0.867545,0.438203,0.723947,0.970718,0.961823,...,0.805061,0.254213,1.103867,0.123680,0.123680,0.406664,0.224411,0.225699,0.242249,pass
17,0.547145,0.810192,0.355910,0.112985,0.687540,0.876544,0.420484,0.821990,1.020332,1.030808,...,0.909151,0.266817,1.122657,0.147642,0.147642,0.468614,0.259223,0.236549,0.250578,pass
18,0.562348,0.877698,0.379675,0.117685,0.749847,0.939315,0.472791,0.792281,1.005316,1.011805,...,0.844474,0.282610,1.157445,0.133786,0.133786,0.452205,0.254525,0.254191,0.260913,pass
19,0.481389,0.739754,0.309862,0.104663,0.523354,0.636905,0.316974,0.532133,0.699649,0.765678,...,0.605070,0.184856,0.904027,0.104152,0.104152,0.343173,0.181423,0.183287,0.204040,pass

BARINEL SCORES

,x 4,x 5,h 14,cp 19,cp 13,h 2,cp 6,cp 16,cp 8,cp 15,...,h 17,h 21,cp 20,h 12,h 1,cp 7,h 3,cp 10,swap 9,swap 11
sum,0.543583,0.543583,0.541972,0.540955,0.53971,0.537591,0.537536,0.537376,0.536403,0.534598,...,0.533726,0.533605,0.533125,0.531949,0.531131,0.531055,0.530183,0.52916,0.528157,0.526579

TARANTULA SCORES

,x 4,x 5,h 14,cp 19,cp 13,h 2,cp 6,cp 16,cp 8,cp 15,...,h 17,h 21,cp 20,h 12,h 1,cp 7,h 3,cp 10,swap 9,swap 11
sum,0.543583,0.543583,0.541972,0.540955,0.53971,0.537591,0.537536,0.537376,0.536403,0.534598,...,0.533726,0.533605,0.533125,0.531949,0.531131,0.531055,0.530183,0.52916,0.528157,0.526579

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_x_inGap_16_.qasm

100%|██████████| 10/10 [00:37<00:00,  3.72s/it]
100%|██████████| 10/10 [00:34<00:00,  3.48s/it]

,x 21,h 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.493741,0.637849,0.915689,0.427090,0.125994,0.760919,1.000788,0.472639,0.942917,1.136809,...,0.308410,1.009205,0.307416,1.226410,0.152684,0.503734,0.285470,0.264085,0.277890,fail
1,0.423518,0.730648,1.087694,0.491011,0.153489,0.791005,0.980978,0.488598,0.906367,1.173054,...,0.329621,1.033798,0.300888,1.457032,0.162826,0.528316,0.305528,0.285329,0.327640,fail
2,0.501531,0.651145,0.952918,0.429023,0.133064,0.739926,0.944420,0.457477,0.889922,1.120731,...,0.314447,0.980402,0.282879,1.252570,0.146393,0.492377,0.278966,0.255983,0.284973,fail
3,0.336017,0.641796,0.997579,0.451021,0.134691,0.755774,0.975092,0.463393,0.915818,1.168849,...,0.264907,0.955314,0.271758,1.304931,0.152845,0.470111,0.286067,0.257784,0.291572,fail
4,0.390043,0.436061,0.630906,0.297519,0.091541,0.744418,0.998987,0.491732,0.904942,1.161197,...,0.364311,0.987046,0.300772,0.899838,0.145491,0.457484,0.255576,0.237649,0.206222,fail
5,0.402445,0.583403,0.822190,0.361208,0.119954,0.635278,0.834069,0.418149,0.774646,1.032386,...,0.344864,0.915197,0.256912,1.043495,0.135564,0.420101,0.237662,0.223527,0.234972,fail
6,0.492012,0.403088,0.654776,0.297444,0.080303,0.625576,0.836825,0.402532,0.775241,1.025119,...,0.319440,0.891556,0.239475,0.876145,0.117676,0.341210,0.222142,0.196862,0.191231,fail
7,0.459787,0.859742,1.267466,0.563728,0.177487,0.912569,1.094732,0.549120,1.093822,1.357201,...,0.349792,1.187112,0.341196,1.688969,0.185232,0.631716,0.352854,0.326595,0.379506,fail
8,0.314974,0.412543,0.642784,0.270617,0.084088,0.540917,0.711610,0.334216,0.614120,0.855138,...,0.320829,0.728937,0.200095,0.762119,0.114796,0.305907,0.176979,0.169680,0.166101,fail
9,0.376358,0.646379,0.970466,0.451933,0.129911,0.781473,1.041445,0.511115,0.939822,1.221900,...,0.314061,1.039523,0.305211,1.336422,0.156490,0.457426,0.289787,0.262239,0.288900,fail
10,0.319073,0.377320,0.568369,0.251742,0.086714,0.503764,0.690043,0.334112,0.567579,0.757530,...,0.225551,0.660429,0.198229,0.764725,0.105700,0.325832,0.175048,0.171238,0.169602,pass
11,0.387390,0.686937,1.049035,0.465639,0.139282,0.814835,1.046713,0.493834,0.887738,1.093164,...,0.257340,0.932084,0.291762,1.300379,0.158870,0.445604,0.269577,0.264533,0.286164,pass
12,0.292810,0.253666,0.386375,0.180147,0.050170,0.359198,0.459644,0.230562,0.493689,0.639787,...,0.197014,0.577145,0.150297,0.588917,0.077679,0.256665,0.157921,0.129300,0.133897,pass
13,0.313862,0.305103,0.483352,0.193718,0.064829,0.428333,0.565592,0.269907,0.487564,0.639136,...,0.187112,0.554826,0.168643,0.618197,0.085066,0.269758,0.146391,0.141716,0.135840,pass
14,0.286800,0.391573,0.590960,0.254401,0.080679,0.598489,0.786246,0.376817,0.652372,0.785545,...,0.209543,0.656976,0.237123,0.768529,0.109291,0.338826,0.182701,0.186172,0.167687,pass
15,0.279037,0.451504,0.662592,0.340227,0.095068,0.527905,0.688130,0.344558,0.742159,0.964219,...,0.310411,0.853846,0.222803,1.011484,0.121818,0.392760,0.237231,0.198182,0.225512,pass
16,0.418546,0.623930,0.923669,0.437525,0.125732,0.817977,1.035424,0.508856,1.110736,1.343015,...,0.303100,1.128982,0.312982,1.360424,0.163617,0.566389,0.337872,0.282868,0.311244,pass
17,0.294543,0.506181,0.797166,0.359233,0.111642,0.686753,0.931101,0.482641,0.728912,0.990921,...,0.304328,0.804132,0.297752,0.987573,0.135153,0.387081,0.212380,0.232086,0.209774,pass
18,0.351524,0.533304,0.814018,0.352752,0.107946,0.686881,0.908364,0.448264,0.770071,1.008747,...,0.255449,0.826723,0.275194,1.045548,0.132286,0.405714,0.233324,0.228228,0.226513,pass
19,0.433753,0.318195,0.428748,0.184749,0.066041,0.421784,0.573681,0.279895,0.572096,0.785571,...,0.340557,0.730664,0.188311,0.585051,0.112468,0.335193,0.169804,0.150765,0.134474,pass

BARINEL SCORES

,h 20,cp 18,cp 19,cp 17,h 0,cp 5,h 2,cp 7,cp 12,h 1,...,h 16,x 21,h 3,cp 15,x 4,cp 14,h 11,cp 6,cp 9,swap 10
sum,0.574396,0.572263,0.571522,0.570049,0.569714,0.567463,0.559084,0.557359,0.555398,0.555394,...,0.554894,0.553721,0.553081,0.550691,0.55016,0.549024,0.548139,0.545003,0.539608,0.532859

TARANTULA SCORES

,h 20,cp 18,cp 19,cp 17,h 0,cp 5,h 2,cp 7,cp 12,h 1,...,h 16,x 21,h 3,cp 15,x 4,cp 14,h 11,cp 6,cp 9,swap 10
sum,0.574396,0.572263,0.571522,0.570049,0.569714,0.567463,0.559084,0.557359,0.555398,0.555394,...,0.554894,0.553721,0.553081,0.550691,0.55016,0.549024,0.548139,0.545003,0.539608,0.532859

ERROR GATE LOCATION:
21
Now evolving the following mutant:  AddGate_h_inGap_11_.qasm

100%|██████████| 10/10 [00:14<00:00,  1.47s/it]
100%|██████████| 10/10 [00:14<00:00,  1.49s/it]

,h 21,h 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.677822,0.0,0.0,1.058454e-18,5.217530e-19,0.445004,0.729716,0.344517,0.472872,0.698658,...,0.207957,0.679541,0.224521,0.027945,0.076087,0.196735,0.112787,0.122587,0.254499,fail
1,0.496472,0.0,0.0,1.005868e-18,4.958310e-19,0.381848,0.625461,0.284409,0.455355,0.658372,...,0.276228,0.633520,0.186188,0.027826,0.076313,0.162413,0.104705,0.101818,0.163709,fail
2,0.697930,0.0,0.0,1.093599e-18,5.390773e-19,0.366205,0.537151,0.273607,0.482806,0.720235,...,0.295752,0.744776,0.197175,0.033377,0.086094,0.230637,0.123951,0.111687,0.250008,fail
3,0.565685,0.0,0.0,1.130746e-18,5.573885e-19,0.491734,0.751593,0.386451,0.538575,0.789285,...,0.285353,0.719331,0.259418,0.038275,0.091132,0.248603,0.127044,0.133537,0.217654,fail
4,0.586119,0.0,0.0,1.110136e-18,5.472291e-19,0.343144,0.537801,0.265402,0.422443,0.652531,...,0.256848,0.629350,0.176483,0.031870,0.075583,0.202498,0.104186,0.097655,0.187273,fail
5,0.521791,0.0,0.0,8.832253e-19,4.353759e-19,0.245839,0.405929,0.198181,0.403489,0.570029,...,0.229633,0.573142,0.149767,0.025092,0.058462,0.172239,0.095778,0.079007,0.164719,fail
6,0.698679,0.0,0.0,1.109264e-18,5.467993e-19,0.461444,0.777326,0.356960,0.637997,0.869917,...,0.285844,0.839979,0.256734,0.035765,0.090005,0.258796,0.147077,0.135979,0.274372,fail
7,0.569188,0.0,0.0,9.882770e-19,4.871599e-19,0.330197,0.499630,0.250711,0.408269,0.616540,...,0.284815,0.639412,0.171055,0.028517,0.078039,0.178139,0.101373,0.091285,0.185936,fail
8,0.591908,0.0,0.0,1.032024e-18,5.087244e-19,0.388706,0.629478,0.282129,0.504117,0.742634,...,0.296357,0.741403,0.195613,0.033253,0.082633,0.205335,0.124185,0.110383,0.219648,fail
9,0.619752,0.0,0.0,1.043096e-18,5.141825e-19,0.339343,0.491784,0.254275,0.477141,0.704195,...,0.272241,0.691558,0.180393,0.031628,0.087625,0.217540,0.119489,0.101305,0.236037,fail
10,0.552733,0.0,0.0,9.595510e-19,4.729998e-19,0.388245,0.601616,0.318036,0.514054,0.722498,...,0.248961,0.684317,0.227534,0.034823,0.078495,0.235218,0.125391,0.122480,0.230424,pass
11,0.354685,0.0,0.0,9.742139e-19,4.802277e-19,0.501220,0.832213,0.380815,0.602985,0.848908,...,0.324633,0.750709,0.248194,0.034633,0.085459,0.227037,0.127838,0.129103,0.155936,pass
12,0.388274,0.0,0.0,7.398956e-19,3.647231e-19,0.271932,0.445730,0.213519,0.307603,0.440244,...,0.104368,0.386675,0.127591,0.018472,0.052491,0.121446,0.068630,0.066693,0.125885,pass
13,0.394646,0.0,0.0,9.076396e-19,4.474106e-19,0.273495,0.464860,0.209868,0.390189,0.575047,...,0.200896,0.539764,0.128638,0.022866,0.062070,0.136491,0.088248,0.066215,0.113461,pass
14,0.628049,0.0,0.0,8.945988e-19,4.409823e-19,0.411879,0.675297,0.306356,0.438615,0.572689,...,0.123917,0.549568,0.211167,0.026931,0.065885,0.194653,0.101712,0.116598,0.234677,pass
15,0.217501,0.0,0.0,6.769202e-19,3.336801e-19,0.197101,0.337668,0.146418,0.269507,0.379412,...,0.173421,0.372648,0.097601,0.017025,0.039631,0.107413,0.056829,0.051275,0.065871,pass
16,0.677789,0.0,0.0,1.191850e-18,5.875087e-19,0.483493,0.790779,0.370931,0.555516,0.784710,...,0.230224,0.732193,0.246237,0.035654,0.090196,0.236125,0.125137,0.132115,0.237874,pass
17,0.258401,0.0,0.0,7.319065e-19,3.607850e-19,0.285406,0.453971,0.226295,0.332817,0.504138,...,0.209284,0.458129,0.145882,0.022782,0.056973,0.141084,0.075727,0.077770,0.088498,pass
18,0.456150,0.0,0.0,9.039022e-19,4.455683e-19,0.281498,0.441060,0.233846,0.333554,0.528673,...,0.206944,0.474661,0.147669,0.025209,0.060522,0.161512,0.078593,0.077330,0.140894,pass
19,0.439698,0.0,0.0,7.581876e-19,3.737400e-19,0.235011,0.366952,0.170281,0.337573,0.468110,...,0.187146,0.478601,0.130076,0.021926,0.056234,0.147922,0.079345,0.066575,0.160735,pass

BARINEL SCORES

,h 0,h 21,swap 8,swap 10,cp 7,h 2,x 4,h 3,cp 12,cp 5,...,cp 18,cp 9,h 13,h 11,cp 6,h 16,cp 14,cp 15,h 20,cp 19
sum,0.58085,0.579735,0.572459,0.562465,0.559449,0.555824,0.553112,0.548129,0.546625,0.546375,...,0.544704,0.544509,0.540552,0.539516,0.538668,0.532585,0.52926,0.52526,NaN,NaN

TARANTULA SCORES

,h 0,h 21,swap 8,swap 10,cp 7,h 2,x 4,h 3,cp 12,cp 5,...,cp 18,cp 9,h 13,h 11,cp 6,h 16,cp 14,cp 15,h 20,cp 19
sum,0.58085,0.579735,0.572459,0.562465,0.559449,0.555824,0.553112,0.548129,0.546625,0.546375,...,0.544704,0.544509,0.540552,0.539516,0.538668,0.532585,0.52926,0.52526,NaN,NaN

ERROR GATE LOCATION:
21
Now evolving the following mutant:  AddGate_rz_inGap_11_.qasm

100%|██████████| 10/10 [00:39<00:00,  3.93s/it]
100%|██████████| 10/10 [00:39<00:00,  3.91s/it]

,h 21,rz 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.608898,1.039453,0.900145,0.388595,0.128420,0.661878,0.834272,0.409212,0.798339,1.023079,...,0.246582,0.864455,0.243113,1.176485,0.139487,0.458776,0.258370,0.231368,0.263644,fail
1,0.566933,0.967815,0.884198,0.382835,0.118582,0.644914,0.804895,0.399949,0.828500,1.105151,...,0.391881,0.984293,0.252956,1.191061,0.145192,0.435616,0.263701,0.228894,0.253600,fail
2,0.521252,0.889833,0.778167,0.369629,0.106949,0.662761,0.886471,0.433469,0.800124,1.052120,...,0.308467,0.914906,0.269427,1.103687,0.142440,0.418545,0.250042,0.232210,0.238530,fail
3,0.590686,1.008364,0.883898,0.397854,0.119264,0.665740,0.816924,0.399106,0.699888,0.858353,...,0.237543,0.776103,0.257728,1.151334,0.135831,0.402775,0.227659,0.231827,0.251078,fail
4,0.671218,1.145842,1.004730,0.455396,0.140604,0.865099,1.104694,0.558489,0.993565,1.289886,...,0.372292,1.112364,0.342586,1.410689,0.186776,0.528352,0.307959,0.292377,0.302510,fail
5,0.679464,1.159917,1.034247,0.468028,0.148116,0.727660,0.923693,0.458530,0.848167,1.129083,...,0.330247,0.989181,0.274247,1.388025,0.155467,0.490754,0.282532,0.262932,0.301115,fail
6,0.526841,0.899374,0.775702,0.339061,0.109048,0.572069,0.739919,0.365120,0.615022,0.786653,...,0.207875,0.696467,0.234227,1.012322,0.121780,0.361943,0.202918,0.208145,0.219948,fail
7,0.645415,1.101792,0.996110,0.448309,0.134263,0.748669,0.948470,0.454410,0.818896,1.055926,...,0.303748,0.954623,0.276009,1.278481,0.152382,0.448041,0.265246,0.255635,0.278304,fail
8,0.638935,1.090730,0.994342,0.449536,0.128232,0.754407,1.004945,0.473935,0.847536,1.083805,...,0.294811,0.948695,0.293252,1.273727,0.147289,0.406495,0.263460,0.254719,0.270732,fail
9,0.479205,0.818054,0.647615,0.321821,0.090497,0.578922,0.743403,0.356013,0.821472,1.002790,...,0.334801,0.898835,0.239260,0.971151,0.136888,0.430382,0.250487,0.206759,0.221909,fail
10,0.417868,0.713346,0.638286,0.284822,0.084896,0.515767,0.630419,0.310691,0.597404,0.741335,...,0.220792,0.640387,0.197706,0.843277,0.103335,0.328492,0.186820,0.174747,0.183937,pass
11,0.635047,1.084093,0.962808,0.450458,0.133016,0.725635,0.960910,0.454241,0.897887,1.190848,...,0.366267,1.065993,0.285253,1.334717,0.155851,0.488304,0.292561,0.265333,0.294665,pass
12,0.653195,1.115074,0.971532,0.444774,0.133204,0.727828,0.918103,0.426541,0.880999,1.073149,...,0.208803,0.932684,0.260807,1.358213,0.140687,0.493510,0.294582,0.260626,0.307884,pass
13,0.341070,0.582243,0.490705,0.231733,0.072476,0.347476,0.477013,0.235491,0.450724,0.650045,...,0.203248,0.553286,0.136834,0.669332,0.086332,0.229784,0.146171,0.125313,0.144549,pass
14,0.529491,0.903898,0.758303,0.336365,0.114459,0.664193,0.827101,0.433298,0.774759,1.031904,...,0.308799,0.865803,0.262224,1.040062,0.139331,0.464561,0.250225,0.232811,0.236254,pass
15,0.376202,0.642217,0.521384,0.263244,0.070708,0.514558,0.708943,0.329293,0.693807,0.845443,...,0.245220,0.758754,0.206056,0.786218,0.111877,0.315615,0.200300,0.170117,0.174656,pass
16,0.211009,0.360214,0.318381,0.145913,0.041758,0.386589,0.559449,0.279027,0.486183,0.667232,...,0.250347,0.588792,0.173837,0.465306,0.085831,0.234109,0.137809,0.126230,0.099642,pass
17,0.390022,0.665809,0.588098,0.299847,0.080798,0.556193,0.772759,0.362390,0.679740,0.876259,...,0.271373,0.791759,0.219657,0.838133,0.109990,0.338060,0.209173,0.187789,0.183924,pass
18,0.240000,0.409706,0.340407,0.151386,0.049081,0.325042,0.445511,0.212076,0.407733,0.547562,...,0.156286,0.461475,0.129094,0.491450,0.071441,0.207099,0.120007,0.107239,0.109290,pass
19,0.559674,0.955424,0.852125,0.377804,0.124991,0.608804,0.849160,0.400200,0.657218,0.910681,...,0.206507,0.731465,0.235437,1.031689,0.120240,0.390736,0.209920,0.218437,0.230827,pass

BARINEL SCORES

,cp 19,h 21,rz 20,cp 17,cp 5,cp 18,h 0,x 4,h 1,h 16,...,h 2,h 3,cp 14,swap 8,h 11,cp 9,h 13,cp 7,cp 15,cp 12
sum,0.580083,0.5766,0.5766,0.574809,0.57443,0.57383,0.569602,0.56541,0.562738,0.561613,...,0.556798,0.556619,0.555795,0.554026,0.553805,0.553005,0.55292,0.552919,0.551962,0.54895

TARANTULA SCORES

,cp 19,h 21,rz 20,cp 17,cp 5,cp 18,h 0,x 4,h 1,h 16,...,h 2,h 3,cp 14,swap 8,h 11,cp 9,h 13,cp 7,cp 15,cp 12
sum,0.580083,0.5766,0.5766,0.574809,0.57443,0.57383,0.569602,0.56541,0.562738,0.561613,...,0.556798,0.556619,0.555795,0.554026,0.553805,0.553005,0.55292,0.552919,0.551962,0.54895

ERROR GATE LOCATION:
20
Now evolving the following mutant:  AddGate_rzz_inGap_11_.qasm

100%|██████████| 10/10 [00:44<00:00,  4.44s/it]
100%|██████████| 10/10 [00:34<00:00,  3.42s/it]

,h 21,rzz 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.712118,2.467227,1.207517,0.539967,0.174955,0.980527,1.251352,0.621782,1.103475,1.472403,...,0.383804,1.168311,0.363452,1.502823,0.177948,0.602833,0.336670,0.319024,0.326509,fail
1,0.574021,1.958273,1.012695,0.432275,0.113283,0.875164,1.154748,0.528808,0.960066,1.133299,...,0.333413,0.994025,0.341981,1.157263,0.163844,0.522699,0.282233,0.278035,0.259042,fail
2,0.587122,1.935163,0.886781,0.445520,0.142566,0.779019,1.145644,0.557350,0.921430,1.317206,...,0.368479,1.055953,0.328001,1.196142,0.153360,0.478103,0.277784,0.268673,0.260639,fail
3,0.577729,1.880944,0.803025,0.397831,0.109382,0.649213,0.905507,0.406766,0.892150,1.158170,...,0.314304,1.024689,0.265117,1.211246,0.155778,0.459205,0.282811,0.233678,0.264295,fail
4,0.667293,2.216645,1.068606,0.500512,0.161494,0.835348,1.165053,0.565404,1.008754,1.407230,...,0.336058,1.136740,0.332425,1.415621,0.157099,0.527536,0.318984,0.292811,0.307009,fail
5,0.600469,2.020061,0.948814,0.424531,0.139581,0.734519,0.969800,0.491132,0.836168,1.170357,...,0.292935,0.961546,0.291978,1.241187,0.140572,0.472318,0.270153,0.253846,0.265473,fail
6,0.935239,3.135159,1.630418,0.695586,0.210438,0.977418,1.245517,0.596496,1.167206,1.533493,...,0.409549,1.327249,0.377096,1.929713,0.205089,0.691814,0.392516,0.359347,0.421425,fail
7,0.739612,2.525674,1.149947,0.527074,0.181927,0.929845,1.167208,0.596360,1.087007,1.485030,...,0.405658,1.220729,0.346095,1.559752,0.177080,0.606437,0.341670,0.318659,0.337952,fail
8,0.712530,2.362975,1.161922,0.488190,0.155591,0.812781,1.064919,0.519833,0.909416,1.183870,...,0.235598,0.997414,0.326169,1.466303,0.161669,0.535210,0.299001,0.289190,0.318106,fail
9,0.569558,1.878732,1.034905,0.437845,0.124104,0.781909,1.064659,0.497718,0.858784,1.137907,...,0.339200,0.980057,0.298006,1.161266,0.153084,0.450569,0.263748,0.256457,0.254165,fail
10,0.444219,1.430682,0.698370,0.328345,0.089279,0.463401,0.671654,0.322804,0.640292,0.862589,...,0.277749,0.768911,0.206495,0.907976,0.124728,0.342262,0.203278,0.177077,0.199490,pass
11,0.544528,1.856853,0.807021,0.388936,0.141978,0.689180,0.963020,0.479601,0.808794,1.144169,...,0.212930,0.867451,0.273149,1.155533,0.129726,0.429097,0.249518,0.236343,0.248008,pass
12,0.559977,1.942285,0.960080,0.461361,0.135281,0.643403,0.831372,0.393716,0.825166,1.098445,...,0.310852,0.866815,0.232358,1.152613,0.128624,0.428027,0.251764,0.222814,0.253208,pass
13,0.377574,1.295221,0.673098,0.277723,0.095449,0.647965,0.889328,0.445245,0.744609,1.008890,...,0.329620,0.832862,0.267587,0.802384,0.121425,0.403027,0.209685,0.207699,0.180316,pass
14,0.572654,1.859722,0.984714,0.400976,0.128836,0.656085,0.867844,0.447944,0.761752,1.045607,...,0.299372,0.897667,0.271722,1.141965,0.138464,0.424320,0.245843,0.235019,0.244776,pass
15,0.416658,1.391799,0.707686,0.304764,0.108145,0.507129,0.610952,0.328003,0.526308,0.713972,...,0.120957,0.557810,0.186691,0.933549,0.092196,0.346731,0.180531,0.185436,0.202759,pass
16,0.448384,1.445065,0.671728,0.346358,0.089846,0.678937,0.982239,0.464020,0.847768,1.112769,...,0.311866,0.952778,0.285386,0.995034,0.142114,0.442171,0.257355,0.235375,0.222248,pass
17,0.386128,1.351084,0.761150,0.390464,0.100131,0.637952,0.943129,0.431842,0.818560,1.118929,...,0.397983,0.900137,0.241272,0.839722,0.123708,0.364103,0.226598,0.198439,0.185142,pass
18,0.481702,1.623094,0.686052,0.377869,0.113752,0.636097,0.821634,0.417573,0.799991,1.020126,...,0.249086,0.814648,0.247352,1.056911,0.122743,0.439142,0.245499,0.221493,0.232938,pass
19,0.540236,1.820252,0.826983,0.411580,0.126108,0.622158,0.865934,0.416883,0.733998,1.025712,...,0.268590,0.838894,0.244713,1.104230,0.124977,0.402048,0.233744,0.218785,0.240523,pass

BARINEL SCORES

,cp 19,h 21,rzz 20,cp 5,h 0,h 16,h 1,cp 17,cp 6,h 2,...,cp 15,x 4,cp 7,h 13,cp 14,h 11,cp 12,cp 9,swap 8,swap 10
sum,0.583712,0.583144,0.582882,0.578379,0.577068,0.57475,0.573004,0.572766,0.571031,0.570935,...,0.568618,0.568553,0.567018,0.564841,0.564749,0.562623,0.561506,0.560154,0.551629,0.549627

TARANTULA SCORES

,cp 19,h 21,rzz 20,cp 5,h 0,h 16,h 1,cp 17,cp 6,h 2,...,cp 15,x 4,cp 7,h 13,cp 14,h 11,cp 12,cp 9,swap 8,swap 10
sum,0.583712,0.583144,0.582882,0.578379,0.577068,0.57475,0.573004,0.572766,0.571031,0.570935,...,0.568618,0.568553,0.567018,0.564841,0.564749,0.562623,0.561506,0.560154,0.551629,0.549627

ERROR GATE LOCATION:
20
Now evolving the following mutant:  AddGate_y_inGap_4_.qasm

100%|██████████| 10/10 [00:40<00:00,  4.08s/it]
100%|██████████| 10/10 [00:37<00:00,  3.74s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,cp 8,cp 7,cp 6,x 5,h 4,y 3,h 2,h 1,h 0,pass/fail
0,0.457662,0.718560,0.324334,0.097699,0.713220,0.959569,0.465442,0.738720,0.939005,0.973686,...,0.802072,0.290928,0.892322,0.135939,0.391630,0.166829,0.211247,0.224389,0.191689,fail
1,0.589055,0.873804,0.410699,0.122227,0.670628,0.887998,0.418564,0.818445,1.042626,0.990765,...,0.939247,0.265834,1.150692,0.142371,0.425675,0.177653,0.252485,0.240465,0.255867,fail
2,0.720747,0.996813,0.486055,0.144237,0.713478,0.870224,0.428149,0.953545,1.147416,1.172598,...,1.034875,0.275378,1.450171,0.157234,0.549075,0.204707,0.317738,0.272516,0.333718,fail
3,0.567730,0.832812,0.377902,0.124155,0.651339,0.899218,0.444236,0.740100,1.021095,1.062984,...,0.881260,0.274379,1.121325,0.143722,0.460686,0.186599,0.245516,0.244103,0.251571,fail
4,0.448043,0.622696,0.320768,0.084671,0.670294,0.909930,0.418250,0.808869,0.969702,1.040476,...,0.892235,0.281582,0.862169,0.136601,0.399779,0.181828,0.223259,0.216011,0.194049,fail
5,0.644207,0.953162,0.451162,0.132867,0.767056,1.013438,0.493135,0.861573,1.068370,1.032195,...,0.891575,0.299448,1.249676,0.147675,0.432082,0.182206,0.258453,0.253717,0.270237,fail
6,0.553070,0.894328,0.400419,0.120180,0.721018,0.942902,0.469799,0.721955,0.940555,0.933107,...,0.792255,0.281728,1.096876,0.136164,0.395967,0.161825,0.221737,0.237340,0.234285,fail
7,0.537924,0.803039,0.363290,0.111844,0.766577,0.997117,0.492253,1.017080,1.287031,1.198423,...,1.082884,0.300313,1.163700,0.157757,0.513471,0.204694,0.300350,0.255162,0.259568,fail
8,0.490879,0.726215,0.344804,0.099101,0.648126,0.875411,0.402282,0.815990,1.021712,0.956068,...,0.880381,0.243407,1.003428,0.131135,0.411429,0.166159,0.242984,0.213648,0.227803,fail
9,0.658752,1.018457,0.449772,0.139150,0.830184,1.076259,0.506953,0.948049,1.191551,1.156789,...,1.042004,0.315021,1.324636,0.164992,0.504074,0.200154,0.288636,0.281051,0.291556,fail
10,0.401789,0.570166,0.269354,0.083583,0.386595,0.503855,0.234769,0.433876,0.540661,0.581190,...,0.487122,0.146471,0.734881,0.082950,0.260972,0.104057,0.144897,0.142032,0.166767,pass
11,0.556204,0.780917,0.344126,0.117555,0.665333,0.814566,0.409534,0.833058,1.045106,1.130653,...,0.878702,0.255236,1.165835,0.140562,0.517628,0.192317,0.273578,0.237126,0.269579,pass
12,0.568426,0.879066,0.407446,0.123852,0.668359,0.902374,0.444402,0.731999,0.987137,0.940611,...,0.875937,0.269452,1.144851,0.147388,0.416606,0.165967,0.241722,0.239696,0.250219,pass
13,0.411380,0.609646,0.299856,0.083040,0.682390,0.938469,0.441713,0.949909,1.206780,1.068358,...,1.059188,0.279263,0.932424,0.140848,0.467287,0.181411,0.276328,0.228549,0.215500,pass
14,0.475344,0.737435,0.324424,0.096979,0.694601,0.931195,0.452918,0.736554,0.934064,0.913050,...,0.794755,0.283525,0.888280,0.121955,0.375463,0.159560,0.210378,0.223719,0.197489,pass
15,0.499231,0.755700,0.349247,0.102435,0.699984,0.944829,0.436246,0.777927,0.941330,0.849708,...,0.814833,0.269815,0.972989,0.121813,0.376016,0.147482,0.222741,0.221981,0.214783,pass
16,0.629083,0.909451,0.426265,0.125857,0.680495,0.936781,0.448620,0.852743,1.109412,0.996675,...,0.969641,0.278577,1.201236,0.142981,0.447115,0.178378,0.268895,0.246392,0.269449,pass
17,0.518354,0.733752,0.328653,0.106571,0.592439,0.771970,0.373179,0.748947,0.992294,1.012104,...,0.875641,0.237519,0.981081,0.135052,0.412470,0.182546,0.228159,0.203871,0.218364,pass
18,0.307678,0.459153,0.195467,0.065354,0.620975,0.855429,0.426308,0.680699,0.885601,0.898163,...,0.748050,0.263292,0.624565,0.110574,0.343531,0.152142,0.180697,0.188397,0.139517,pass
19,0.475751,0.698514,0.322974,0.096393,0.610802,0.805340,0.399723,0.791644,1.049979,0.936393,...,0.885640,0.233622,1.020897,0.126742,0.418262,0.162549,0.251087,0.210685,0.234745,pass

BARINEL SCORES

,cp 19,cp 20,cp 18,cp 6,h 21,swap 11,h 0,cp 10,x 5,h 1,...,y 3,cp 7,cp 16,h 14,cp 15,h 2,h 4,cp 8,cp 13,swap 9
sum,0.545949,0.541932,0.540067,0.539271,0.539235,0.538101,0.535625,0.533702,0.533535,0.532303,...,0.529812,0.529117,0.528796,0.527784,0.527401,0.527148,0.526324,0.524088,0.523047,0.522582

TARANTULA SCORES

,cp 19,cp 20,cp 18,cp 6,h 21,swap 11,h 0,cp 10,x 5,h 1,...,y 3,cp 7,cp 16,h 14,cp 15,h 2,h 4,cp 8,cp 13,swap 9
sum,0.545949,0.541932,0.540067,0.539271,0.539235,0.538101,0.535625,0.533702,0.533535,0.532303,...,0.529812,0.529117,0.528796,0.527784,0.527401,0.527148,0.526324,0.524088,0.523047,0.522582

ERROR GATE LOCATION:
3
Now evolving the following mutant:  AddGate_y_inGap_1_.qasm

100%|██████████| 10/10 [00:40<00:00,  4.08s/it]
100%|██████████| 9/9 [00:37<00:00,  4.20s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,cp 8,cp 7,cp 6,x 5,h 4,h 3,h 2,h 1,y 0,pass/fail
0,0.512027,0.743535,0.323653,0.113020,0.763491,1.023322,0.513771,0.933615,1.218392,1.286485,...,1.046109,0.320991,1.083981,0.154011,0.539622,0.279233,0.260558,0.246875,0.092000,fail
1,0.858207,1.327870,0.562040,0.184275,0.814798,0.998899,0.506533,0.947314,1.283994,1.129597,...,1.124487,0.296923,1.715453,0.179498,0.547666,0.332619,0.301040,0.374160,0.142330,fail
2,0.532435,0.770130,0.364605,0.115591,0.698707,0.981043,0.473642,0.816533,1.092241,1.024025,...,0.916713,0.273478,1.082769,0.141192,0.442228,0.254623,0.238441,0.244124,0.091659,fail
3,0.595185,0.844232,0.424204,0.120772,0.603758,0.841454,0.399152,0.814034,1.083737,0.958368,...,0.921895,0.237655,1.152410,0.147656,0.396764,0.248197,0.212773,0.250395,0.100235,fail
4,0.602241,0.873042,0.397412,0.121969,0.615001,0.763781,0.381934,0.778652,0.986062,0.997193,...,0.862640,0.234185,1.186067,0.140466,0.431314,0.252376,0.222062,0.264623,0.103495,fail
5,0.683620,1.054264,0.486616,0.142836,0.791538,1.004130,0.496970,0.969715,1.241590,1.179607,...,1.065963,0.305924,1.416524,0.163449,0.532853,0.308925,0.279035,0.313941,0.118789,fail
6,0.525840,0.754322,0.382919,0.106594,0.656641,0.891655,0.408835,0.823913,1.011176,0.886553,...,0.907470,0.258587,1.048999,0.140890,0.398001,0.250186,0.226418,0.233887,0.091876,fail
7,0.845533,1.269326,0.576202,0.170515,0.922090,1.199869,0.558156,1.068244,1.316003,1.231162,...,1.125654,0.339211,1.699842,0.188121,0.569381,0.344113,0.318281,0.374226,0.143124,fail
8,0.644065,1.046782,0.489000,0.137260,0.918997,1.242107,0.603308,0.999438,1.292471,1.080742,...,1.042267,0.352844,1.361179,0.158993,0.480839,0.300346,0.297010,0.293044,0.111252,fail
9,0.691407,1.032765,0.462744,0.144591,0.727767,0.940089,0.456996,0.901564,1.176707,1.043300,...,0.995701,0.265643,1.365457,0.155510,0.464116,0.283251,0.250493,0.297613,0.118314,fail
10,0.564665,0.884700,0.386947,0.122338,0.713460,0.895603,0.441413,0.785218,0.956422,1.047112,...,0.807780,0.274732,1.158364,0.134263,0.451169,0.241035,0.242584,0.254998,0.097331,pass
11,0.348426,0.523889,0.232583,0.074759,0.407361,0.549327,0.267603,0.445256,0.608743,0.559400,...,0.541754,0.161630,0.684733,0.080805,0.256482,0.145648,0.139792,0.150545,0.057444,pass
12,0.412444,0.643462,0.296174,0.086136,0.486723,0.667490,0.313685,0.533251,0.684778,0.561558,...,0.571110,0.180878,0.817550,0.092308,0.260804,0.169723,0.163741,0.178249,0.068124,pass
13,0.496242,0.732291,0.365023,0.101251,0.551716,0.718647,0.339278,0.732745,0.910456,0.825737,...,0.791627,0.205262,1.097459,0.125346,0.392220,0.244834,0.200639,0.244782,0.088984,pass
14,0.651543,0.997600,0.446283,0.137675,0.659008,0.770919,0.380621,0.773964,0.933035,0.949041,...,0.837781,0.235191,1.325872,0.135587,0.458067,0.265304,0.241194,0.294407,0.112632,pass
15,0.212778,0.300786,0.134745,0.045930,0.313069,0.422302,0.198602,0.424866,0.560674,0.541387,...,0.492965,0.124279,0.463789,0.072640,0.229176,0.128123,0.109083,0.107563,0.039526,pass
16,0.590234,0.894016,0.423364,0.126882,0.760484,1.021481,0.497385,0.866650,1.104732,1.030025,...,0.928248,0.296526,1.223460,0.147855,0.452191,0.265188,0.259786,0.268712,0.101733,pass
17,0.591710,0.898493,0.405779,0.122198,0.722858,0.930994,0.465404,0.827159,1.079729,0.962180,...,0.927927,0.276722,1.184456,0.144960,0.431092,0.258262,0.245493,0.260478,0.102281,pass
18,0.567068,0.807723,0.402114,0.116505,0.573081,0.731318,0.361469,0.779356,0.970002,0.942356,...,0.871291,0.238297,1.196041,0.132354,0.450079,0.260756,0.222364,0.266857,0.100108,pass

BARINEL SCORES

,swap 9,swap 11,cp 13,cp 8,cp 16,x 5,cp 15,h 14,h 21,h 12,...,y 0,h 17,cp 7,cp 10,cp 19,h 3,cp 6,h 2,h 1,h 4
sum,0.611804,0.605837,0.599785,0.5965,0.595763,0.59554,0.595095,0.594753,0.594065,0.593175,...,0.591671,0.591533,0.591405,0.591013,0.591002,0.590528,0.588953,0.588182,0.588048,0.586846

TARANTULA SCORES

,swap 9,swap 11,cp 13,cp 8,cp 16,x 5,cp 15,h 14,h 21,h 12,...,y 0,h 17,cp 7,cp 10,cp 19,h 3,cp 6,h 2,h 1,h 4
sum,0.586507,0.580417,0.574249,0.570904,0.570155,0.569927,0.569475,0.569126,0.568427,0.567521,...,0.565992,0.565851,0.565722,0.565324,0.565312,0.56483,0.563229,0.562446,0.562309,0.561089

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_x_inGap_13_.qasm

100%|██████████| 10/10 [00:37<00:00,  3.71s/it]
100%|██████████| 10/10 [00:35<00:00,  3.54s/it]

,h 21,cp 20,x 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.503475,0.731378,0.479207,0.344156,0.098596,0.592300,0.766419,0.377470,0.845893,1.067880,...,0.302846,0.958217,0.231185,1.086103,0.132581,0.410982,0.264510,0.211876,0.246226,fail
1,0.440177,0.689838,0.388569,0.337956,0.094681,0.670812,0.935674,0.459816,0.813226,1.062379,...,0.370926,0.919608,0.283507,0.930298,0.128612,0.386675,0.230004,0.220182,0.198559,fail
2,0.631159,0.937757,0.504339,0.437505,0.130952,0.767691,0.945674,0.459676,0.992434,1.158733,...,0.279403,1.029860,0.293677,1.351966,0.158869,0.548748,0.308557,0.270009,0.304973,fail
3,0.706423,0.997009,0.475849,0.465515,0.151891,0.797993,1.095046,0.546152,1.002104,1.343060,...,0.354964,1.138586,0.322787,1.399979,0.168349,0.572772,0.321514,0.287678,0.316783,fail
4,0.562962,0.851027,0.446642,0.409828,0.114511,0.703232,0.929435,0.436690,0.897254,1.147128,...,0.379268,0.992360,0.264593,1.091758,0.138185,0.416035,0.260329,0.229050,0.243184,fail
5,0.514942,0.728998,0.481853,0.360690,0.097380,0.683917,0.955871,0.439177,0.891281,1.086840,...,0.269093,0.945262,0.272920,1.021426,0.137294,0.417535,0.258250,0.226208,0.232272,fail
6,0.715642,1.013117,0.466365,0.484936,0.142093,0.759992,0.995143,0.487520,0.973041,1.214032,...,0.287865,1.036386,0.308105,1.401837,0.166139,0.519429,0.307782,0.270369,0.309891,fail
7,0.541569,0.757090,0.409390,0.355189,0.106424,0.692100,0.858198,0.423908,0.860916,1.029506,...,0.326174,0.944066,0.278251,1.081908,0.141795,0.471050,0.265206,0.240158,0.248075,fail
8,0.522871,0.779016,0.475364,0.359550,0.109816,0.678038,0.900863,0.436861,0.903336,1.137771,...,0.320226,0.986319,0.275217,1.144411,0.144924,0.479546,0.279644,0.242860,0.257044,fail
9,0.552013,0.848677,0.408504,0.393627,0.108726,0.674650,0.888773,0.423735,0.840545,1.044720,...,0.293561,0.910986,0.269583,1.145998,0.130729,0.406481,0.256633,0.230435,0.247511,fail
10,0.434516,0.624747,0.348678,0.303829,0.089240,0.478806,0.648197,0.295869,0.652230,0.829759,...,0.193546,0.708995,0.177576,0.913107,0.106700,0.310664,0.204322,0.165653,0.199666,pass
11,0.651422,0.965519,0.404801,0.446526,0.130314,0.801352,1.014774,0.488490,0.923808,1.122643,...,0.290299,0.963738,0.298227,1.252054,0.160570,0.455378,0.274032,0.262807,0.276752,pass
12,0.527951,0.813805,0.370344,0.369093,0.104915,0.631310,0.827006,0.407415,0.787713,1.068601,...,0.394964,0.938010,0.251381,1.048852,0.134471,0.365935,0.233189,0.208682,0.221893,pass
13,0.478412,0.732551,0.291367,0.326722,0.094680,0.596495,0.816908,0.376564,0.676028,0.911249,...,0.241764,0.772302,0.220106,0.913524,0.122557,0.307873,0.206831,0.192758,0.198978,pass
14,0.394013,0.546162,0.382432,0.282215,0.074512,0.431075,0.525953,0.249209,0.664091,0.789388,...,0.203987,0.682548,0.160657,0.854520,0.101024,0.312796,0.205689,0.154132,0.192853,pass
15,0.489228,0.764136,0.360249,0.314070,0.100694,0.590107,0.709723,0.369381,0.744841,1.002109,...,0.329532,0.861059,0.222289,1.013568,0.129838,0.385672,0.230447,0.198904,0.222853,pass
16,0.564301,0.866177,0.299833,0.384566,0.120310,0.643633,0.858490,0.412365,0.723485,0.966110,...,0.353446,0.861146,0.262693,1.046796,0.136085,0.385718,0.217855,0.219094,0.219655,pass
17,0.509785,0.792575,0.238116,0.351804,0.114754,0.649927,0.843854,0.434609,0.679555,0.889423,...,0.211373,0.735080,0.261178,1.068844,0.119062,0.403205,0.216106,0.223580,0.233731,pass
18,0.614248,0.887626,0.434397,0.395232,0.131150,0.664563,0.823049,0.433085,0.881707,1.165640,...,0.364657,1.027811,0.262694,1.271943,0.158816,0.496693,0.286984,0.244052,0.282256,pass
19,0.547052,0.831607,0.370963,0.370251,0.116544,0.652713,0.818581,0.405781,0.802471,1.008286,...,0.229197,0.854090,0.250459,1.190148,0.134347,0.450877,0.259903,0.231703,0.264323,pass

BARINEL SCORES

,x 19,h 13,h 3,h 11,cp 6,h 2,cp 15,cp 7,cp 14,cp 12,...,cp 9,h 16,swap 8,h 0,cp 18,x 4,cp 5,h 21,cp 17,cp 20
sum,0.564382,0.544821,0.544358,0.542437,0.541858,0.540987,0.540348,0.539878,0.536959,0.53656,...,0.534416,0.533461,0.530979,0.529645,0.527001,0.526174,0.524345,0.522028,0.517462,0.51575

TARANTULA SCORES

,x 19,h 13,h 3,h 11,cp 6,h 2,cp 15,cp 7,cp 14,cp 12,...,cp 9,h 16,swap 8,h 0,cp 18,x 4,cp 5,h 21,cp 17,cp 20
sum,0.564382,0.544821,0.544358,0.542437,0.541858,0.540987,0.540348,0.539878,0.536959,0.53656,...,0.534416,0.533461,0.530979,0.529645,0.527001,0.526174,0.524345,0.522028,0.517462,0.51575

ERROR GATE LOCATION:
19
Now evolving the following mutant:  AddGate_y_inGap_5_.qasm

100%|██████████| 10/10 [00:38<00:00,  3.84s/it]
100%|██████████| 10/10 [00:40<00:00,  4.01s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,cp 8,cp 7,cp 6,x 5,y 4,h 3,h 2,h 1,h 0,pass/fail
0,0.673824,0.989285,0.452016,0.142434,0.719673,0.925151,0.453601,0.827093,1.047849,1.107021,...,0.918988,0.285276,1.380019,0.158746,0.158746,0.497654,0.278021,0.264598,0.304912,fail
1,0.458461,0.690159,0.304994,0.092923,0.633617,0.854095,0.416642,0.803035,1.056463,0.963494,...,0.910574,0.255204,0.952896,0.146719,0.146719,0.385916,0.230775,0.203691,0.200791,fail
2,0.485030,0.749251,0.362274,0.101156,0.634847,0.841990,0.428755,0.766274,0.988345,0.856607,...,0.806674,0.255587,1.016224,0.132098,0.132098,0.363860,0.226084,0.211456,0.216432,fail
3,0.499744,0.784626,0.347087,0.106316,0.698886,0.942114,0.446341,0.808954,1.040688,0.977232,...,0.901523,0.270967,1.050638,0.149357,0.149357,0.400674,0.234400,0.226450,0.222576,fail
4,0.424654,0.661250,0.307921,0.088444,0.616798,0.866318,0.420320,0.742045,1.013963,0.750094,...,0.872676,0.257787,0.931491,0.123586,0.123586,0.334557,0.218926,0.201305,0.196368,fail
5,0.534860,0.731983,0.326039,0.110355,0.685710,0.912845,0.452940,0.793871,1.019331,1.132215,...,0.910650,0.282816,0.983139,0.150432,0.150432,0.452199,0.237007,0.231211,0.222591,fail
6,0.575091,0.831286,0.402315,0.120767,0.609252,0.793154,0.381197,0.877489,1.119598,1.047104,...,0.967969,0.234625,1.220318,0.144399,0.144399,0.462698,0.277946,0.222817,0.272499,fail
7,0.669848,1.007656,0.488708,0.136653,0.758315,1.033474,0.473279,0.918478,1.185271,0.894190,...,1.041558,0.281255,1.391317,0.161758,0.161758,0.443320,0.298533,0.260193,0.301234,fail
8,0.576436,0.840138,0.371413,0.118713,0.606400,0.747483,0.366221,0.707913,0.883264,0.951697,...,0.756766,0.228009,1.100640,0.129963,0.129963,0.409976,0.226958,0.216158,0.246257,fail
9,0.380306,0.589913,0.244075,0.084540,0.596899,0.743451,0.359361,0.663073,0.814694,0.913399,...,0.701911,0.226036,0.823991,0.112983,0.112983,0.391172,0.203293,0.196970,0.188402,fail
10,0.571237,0.877790,0.377855,0.116819,0.764746,1.006397,0.491215,0.822488,1.068242,1.002832,...,0.881016,0.293865,1.152893,0.148444,0.148444,0.423744,0.248422,0.244219,0.247255,pass
11,0.487105,0.699301,0.305637,0.098064,0.647914,0.851021,0.419961,0.779160,1.005293,0.960313,...,0.900023,0.270493,0.938691,0.126385,0.126385,0.398871,0.229429,0.213614,0.207120,pass
12,0.639885,0.949460,0.411435,0.136227,0.743901,0.961736,0.468157,0.890155,1.171806,1.145169,...,1.025080,0.284155,1.271057,0.160951,0.160951,0.499378,0.280374,0.257665,0.281866,pass
13,0.639458,0.950606,0.454739,0.131200,0.828352,1.095308,0.530114,0.953492,1.182621,1.128779,...,1.055172,0.337904,1.306814,0.159098,0.159098,0.509643,0.295960,0.288164,0.293267,pass
14,0.538148,0.801319,0.363802,0.111136,0.637202,0.826268,0.404752,0.803719,1.021831,0.931494,...,0.871820,0.253671,1.128098,0.130822,0.130822,0.420966,0.253976,0.226883,0.250705,pass
15,0.552476,0.803163,0.351677,0.112729,0.530209,0.645767,0.315819,0.676554,0.843614,0.803797,...,0.735607,0.190637,1.080374,0.114346,0.114346,0.367581,0.220237,0.190447,0.239899,pass
16,0.569103,0.833361,0.408381,0.109427,0.587886,0.765729,0.360706,0.768064,0.971320,0.798337,...,0.861332,0.224532,1.124340,0.126871,0.126871,0.357142,0.242552,0.204585,0.245340,pass
17,0.663978,1.009741,0.450023,0.132586,0.757701,0.943086,0.461117,0.852665,1.091711,0.938408,...,0.928846,0.271948,1.356611,0.155700,0.155700,0.433558,0.278573,0.256211,0.295227,pass
18,0.527100,0.817028,0.356967,0.106404,0.641867,0.828279,0.416791,0.740573,0.963583,0.833258,...,0.848489,0.256046,1.061282,0.141699,0.141699,0.354809,0.225783,0.214390,0.223010,pass
19,0.491709,0.750484,0.331403,0.102414,0.581332,0.757515,0.361749,0.644234,0.798371,0.848097,...,0.657437,0.222900,0.962576,0.109588,0.109588,0.375315,0.204470,0.202500,0.218599,pass

BARINEL SCORES

,swap 9,x 5,y 4,h 12,cp 10,cp 13,cp 8,h 3,cp 16,h 14,...,h 2,h 17,h 1,cp 6,cp 18,h 0,cp 19,h 21,cp 20,swap 11
sum,0.512398,0.50649,0.50649,0.505335,0.503457,0.501259,0.500697,0.500061,0.499394,0.499278,...,0.495131,0.49395,0.492961,0.488035,0.487893,0.486642,0.486179,0.481661,0.481161,0.472611

TARANTULA SCORES

,swap 9,x 5,y 4,h 12,cp 10,cp 13,cp 8,h 3,cp 16,h 14,...,h 2,h 17,h 1,cp 6,cp 18,h 0,cp 19,h 21,cp 20,swap 11
sum,0.512398,0.50649,0.50649,0.505335,0.503457,0.501259,0.500697,0.500061,0.499394,0.499278,...,0.495131,0.49395,0.492961,0.488035,0.487893,0.486642,0.486179,0.481661,0.481161,0.472611

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_rz_inGap_6_.qasm

100%|██████████| 10/10 [00:38<00:00,  3.81s/it]
100%|██████████| 9/9 [00:33<00:00,  3.67s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.689584,1.036414,0.464094,0.142628,0.802449,1.016466,0.499006,0.912471,1.131413,1.133072,...,0.293642,0.957288,0.310044,1.357540,0.170864,0.480014,0.279821,0.269223,0.291226,fail
1,0.740331,1.149420,0.510764,0.153461,0.908307,1.046877,0.523542,1.077585,1.308773,1.299283,...,0.374763,1.159830,0.322785,1.559851,0.178707,0.596794,0.346534,0.311625,0.351031,fail
2,0.650789,0.984575,0.452786,0.138060,0.762559,0.998552,0.477163,0.934405,1.224776,1.031939,...,0.353906,1.071068,0.287197,1.319826,0.160635,0.465070,0.290663,0.257298,0.287115,fail
3,0.570472,0.855278,0.404042,0.113567,0.724719,0.982091,0.457300,0.836971,1.055420,0.969473,...,0.264889,0.877943,0.278194,1.114059,0.140400,0.413836,0.252578,0.238026,0.247212,fail
4,0.485594,0.752243,0.347192,0.110787,0.630768,0.857244,0.402992,0.710307,0.903653,0.929547,...,0.265645,0.804242,0.253793,0.980758,0.117279,0.413707,0.219308,0.220118,0.219138,fail
5,0.562876,0.865374,0.411912,0.118517,0.761253,1.005458,0.478324,0.880993,1.083807,1.018804,...,0.271186,0.932609,0.299065,1.164429,0.144134,0.456547,0.266912,0.255336,0.258094,fail
6,0.470488,0.715676,0.337247,0.103542,0.726468,0.940803,0.460437,0.858612,1.077888,1.104888,...,0.350709,0.933626,0.281244,1.010425,0.139447,0.461471,0.254802,0.237831,0.228600,fail
7,0.525856,0.801298,0.376741,0.108427,0.660960,0.897307,0.417123,0.803322,1.036320,0.873985,...,0.283692,0.896548,0.256162,1.098501,0.133131,0.388955,0.248707,0.224181,0.239008,fail
8,0.450303,0.635636,0.289503,0.093046,0.551490,0.695195,0.332092,0.639534,0.788741,0.905742,...,0.242877,0.734075,0.213778,0.891432,0.112565,0.398887,0.205749,0.191459,0.205790,fail
9,0.358477,0.562863,0.231987,0.075916,0.564267,0.732423,0.351134,0.605452,0.783058,0.850930,...,0.299408,0.702965,0.217894,0.680524,0.101050,0.331406,0.171935,0.177780,0.157088,fail
10,0.521721,0.849694,0.376222,0.109461,0.752555,0.973394,0.478549,0.908802,1.170653,1.014346,...,0.301800,0.982034,0.290278,1.167853,0.148526,0.457094,0.275709,0.252056,0.254119,pass
11,0.633769,0.906759,0.435520,0.130402,0.666278,0.861659,0.432272,0.844911,1.086634,0.989197,...,0.290625,0.948320,0.272113,1.274878,0.147571,0.453055,0.277986,0.250621,0.283655,pass
12,0.474516,0.734237,0.345259,0.100665,0.615963,0.801049,0.405420,0.764351,1.026781,0.854426,...,0.406046,0.949745,0.256871,0.990950,0.135273,0.384401,0.234540,0.213428,0.213692,pass
13,0.570492,0.903583,0.396264,0.120935,0.710999,0.887991,0.429398,0.800084,0.995778,0.937651,...,0.255579,0.853688,0.258793,1.154345,0.137562,0.414468,0.248360,0.238305,0.254985,pass
14,0.577585,0.862371,0.385025,0.117839,0.694826,0.898747,0.440098,0.854925,1.097911,1.045320,...,0.362930,0.991109,0.286723,1.139365,0.142635,0.456257,0.263716,0.241586,0.249916,pass
15,0.642721,0.952782,0.434089,0.132658,0.662936,0.801744,0.401439,0.848871,1.046823,0.937723,...,0.216196,0.886284,0.242355,1.343526,0.141712,0.443867,0.274641,0.237096,0.294623,pass
16,0.443045,0.641383,0.310862,0.090312,0.482425,0.636786,0.301865,0.653046,0.837749,0.709456,...,0.249968,0.735671,0.187048,0.914543,0.113902,0.311833,0.201595,0.169954,0.197433,pass
17,0.553082,0.874022,0.419763,0.115654,0.620496,0.811098,0.388202,0.808324,1.072063,0.903723,...,0.394441,0.944024,0.234170,1.086485,0.137473,0.371992,0.244694,0.215478,0.235414,pass
18,0.570072,0.904852,0.361439,0.124770,0.716216,0.914630,0.457636,0.717736,0.939443,0.921617,...,0.183785,0.754956,0.263411,1.121523,0.123030,0.415355,0.226672,0.236860,0.246204,pass

BARINEL SCORES

,rz 10,h 12,cp 16,cp 9,h 17,h 3,cp 6,cp 15,h 1,h 14,...,swap 8,cp 7,cp 13,swap 11,h 0,cp 18,cp 19,h 21,cp 5,cp 20
sum,0.552002,0.548945,0.547296,0.546892,0.544966,0.543029,0.542738,0.540831,0.536894,0.534235,...,0.529967,0.529924,0.528474,0.527588,0.526967,0.526187,0.524814,0.524675,0.523019,0.522801

TARANTULA SCORES

,rz 10,h 12,cp 16,cp 9,h 17,h 3,cp 6,cp 15,h 1,h 14,...,swap 8,cp 7,cp 13,swap 11,h 0,cp 18,cp 19,h 21,cp 5,cp 20
sum,0.525828,0.522746,0.521085,0.520678,0.518739,0.516789,0.516496,0.514578,0.51062,0.507948,...,0.503662,0.50362,0.502164,0.501276,0.500653,0.499871,0.498494,0.498355,0.496695,0.496476

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_rz_inGap_10_.qasm

100%|██████████| 10/10 [00:34<00:00,  3.45s/it]
100%|██████████| 10/10 [00:36<00:00,  3.61s/it]

,h 21,cp 20,cp 19,cp 18,h 17,rz 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.634236,0.969185,0.441992,0.132320,0.801347,0.409224,1.061152,0.525349,0.891852,1.163292,...,0.272351,0.955040,0.310680,1.278723,0.147537,0.449759,0.276396,0.266335,0.280892,fail
1,0.527954,0.783805,0.371327,0.109736,0.695505,0.359584,0.970458,0.452576,0.871856,1.137796,...,0.339891,0.989691,0.268274,1.034885,0.133782,0.412893,0.253313,0.225523,0.227150,fail
2,0.532221,0.777967,0.378223,0.110579,0.643163,0.314996,0.851065,0.395314,0.748025,0.922228,...,0.204148,0.819302,0.248825,1.139665,0.129866,0.415073,0.247332,0.230228,0.255518,fail
3,0.372687,0.561235,0.273426,0.073329,0.618605,0.328640,0.805535,0.405228,0.787174,1.040612,...,0.389879,0.927180,0.254118,0.821899,0.125659,0.367021,0.229284,0.200657,0.182097,fail
4,0.479438,0.750520,0.326295,0.101031,0.665704,0.327440,0.854085,0.432383,0.807514,1.048967,...,0.329676,0.877545,0.261462,0.961905,0.132620,0.423346,0.233839,0.221697,0.213735,fail
5,0.449645,0.682963,0.323728,0.095553,0.575356,0.304328,0.784883,0.391175,0.651878,0.886124,...,0.311897,0.763450,0.241516,0.862334,0.122372,0.326170,0.192747,0.193041,0.184081,fail
6,0.526373,0.792129,0.363977,0.104024,0.793155,0.420491,1.086457,0.505401,0.898796,1.135094,...,0.359877,0.993422,0.307262,1.012838,0.146745,0.415598,0.249256,0.245784,0.222026,fail
7,0.547788,0.817800,0.398987,0.114769,0.784424,0.408703,1.102281,0.520993,1.035161,1.323523,...,0.398339,1.133111,0.321032,1.140615,0.153192,0.493307,0.295055,0.259872,0.252320,fail
8,0.490028,0.705442,0.338988,0.097539,0.773240,0.434155,1.089817,0.515547,0.902242,1.150220,...,0.380340,1.000737,0.325400,0.919323,0.140723,0.433078,0.248857,0.245820,0.205674,fail
9,0.548456,0.823876,0.362405,0.109740,0.747259,0.381319,0.991279,0.470820,0.874905,1.118737,...,0.307372,0.977686,0.283733,1.084562,0.148499,0.428687,0.256246,0.238176,0.237574,fail
10,0.478383,0.693755,0.310013,0.094656,0.534187,0.264027,0.669664,0.326953,0.700413,0.893940,...,0.319018,0.829056,0.217090,0.947065,0.115231,0.370575,0.218439,0.189916,0.210326,pass
11,0.751610,1.101754,0.504899,0.151697,0.786089,0.372806,0.979759,0.480688,0.954149,1.197818,...,0.352027,1.065321,0.298931,1.446877,0.165129,0.504691,0.305156,0.273299,0.318597,pass
12,0.448052,0.699623,0.317159,0.093513,0.598351,0.303075,0.813441,0.375743,0.678639,0.889234,...,0.233837,0.749305,0.219286,0.922046,0.118004,0.306432,0.200188,0.190752,0.196485,pass
13,0.436709,0.627955,0.264892,0.088808,0.645380,0.365955,0.907611,0.434753,0.704040,0.946838,...,0.323219,0.826069,0.266191,0.781174,0.125884,0.367635,0.199479,0.207771,0.175837,pass
14,0.480491,0.695344,0.325097,0.097396,0.677623,0.343939,0.871522,0.427906,0.812975,0.977170,...,0.219782,0.857889,0.268108,1.042906,0.127183,0.439750,0.256432,0.235730,0.242004,pass
15,0.467305,0.737015,0.306813,0.097582,0.586550,0.280282,0.723896,0.360645,0.682743,0.919887,...,0.311080,0.799154,0.223162,0.929327,0.124832,0.354830,0.209522,0.193562,0.203133,pass
16,0.656314,1.005169,0.445404,0.136762,0.780062,0.366932,0.978154,0.477806,0.953841,1.248136,...,0.343834,1.044757,0.278733,1.333775,0.161627,0.477420,0.295428,0.261875,0.292919,pass
17,0.310914,0.412234,0.201370,0.061783,0.370173,0.197138,0.475897,0.245845,0.475900,0.604394,...,0.179175,0.526960,0.154259,0.614042,0.085578,0.266931,0.148339,0.131111,0.140550,pass
18,0.442331,0.652579,0.310627,0.093465,0.479880,0.226156,0.611476,0.298149,0.622564,0.796760,...,0.225419,0.712058,0.191208,0.951105,0.103436,0.366934,0.211292,0.182826,0.215522,pass
19,0.434229,0.675396,0.322279,0.087805,0.723745,0.371874,0.957251,0.471853,0.886526,1.090562,...,0.293316,0.904836,0.293378,0.960776,0.130615,0.423532,0.250163,0.227979,0.212906,pass

BARINEL SCORES

,swap 10,cp 15,rz 16,cp 14,swap 8,cp 6,h 17,cp 12,cp 7,h 13,...,h 11,x 4,h 2,cp 19,h 3,cp 20,cp 18,h 21,cp 5,h 0
sum,0.55112,0.545729,0.543997,0.541951,0.540451,0.539364,0.534478,0.53323,0.531594,0.53129,...,0.523729,0.523399,0.519667,0.519657,0.517791,0.512164,0.511002,0.510109,0.508116,0.505905

TARANTULA SCORES

,swap 10,cp 15,rz 16,cp 14,swap 8,cp 6,h 17,cp 12,cp 7,h 13,...,h 11,x 4,h 2,cp 19,h 3,cp 20,cp 18,h 21,cp 5,h 0
sum,0.55112,0.545729,0.543997,0.541951,0.540451,0.539364,0.534478,0.53323,0.531594,0.53129,...,0.523729,0.523399,0.519667,0.519657,0.517791,0.512164,0.511002,0.510109,0.508116,0.505905

ERROR GATE LOCATION:
16
Now evolving the following mutant:  AddGate_rzz_inGap_6_.qasm

100%|██████████| 10/10 [00:34<00:00,  3.43s/it]
100%|██████████| 10/10 [00:38<00:00,  3.82s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.507455,0.808801,0.351490,0.107182,0.675997,0.893777,0.441874,0.648732,0.834576,0.906774,...,0.206839,0.689880,0.265488,0.933595,0.118016,0.366323,0.197906,0.222447,0.207467,fail
1,0.602092,0.938813,0.422127,0.132667,0.729531,0.891385,0.443370,0.803497,0.995540,1.060111,...,0.253695,0.848416,0.270034,1.213745,0.143747,0.461738,0.254138,0.249296,0.267799,fail
2,0.467319,0.682538,0.331717,0.097947,0.614850,0.810835,0.405556,0.870565,1.100094,1.049035,...,0.344765,0.977612,0.269201,1.067972,0.139365,0.464805,0.267623,0.225322,0.239690,fail
3,0.492573,0.742773,0.337927,0.102422,0.666521,0.873821,0.435100,0.768091,1.005417,0.889156,...,0.277407,0.864980,0.267716,1.044954,0.131060,0.389198,0.237788,0.222261,0.225723,fail
4,0.550636,0.781059,0.357445,0.110069,0.597041,0.805176,0.393311,0.750960,0.972741,0.938476,...,0.244135,0.837321,0.245094,1.075804,0.134277,0.410663,0.237759,0.211009,0.236309,fail
5,0.508738,0.787012,0.340116,0.111628,0.749627,0.923994,0.447791,0.777727,0.957796,1.097193,...,0.264573,0.823359,0.280429,1.044090,0.142050,0.462275,0.237250,0.245044,0.233402,fail
6,0.363037,0.594686,0.253443,0.075032,0.520751,0.631979,0.316237,0.590714,0.768670,0.730560,...,0.302912,0.688359,0.200711,0.722875,0.106037,0.303154,0.170122,0.165962,0.154686,fail
7,0.637478,0.914838,0.427975,0.132566,0.602561,0.746420,0.383514,0.805738,1.046569,0.967104,...,0.270770,0.922844,0.241213,1.335627,0.146562,0.461703,0.275216,0.231870,0.293256,fail
8,0.476823,0.739175,0.351892,0.100116,0.671766,0.926916,0.430462,0.819938,1.056885,0.883024,...,0.298693,0.908405,0.259283,1.032034,0.132478,0.393997,0.248349,0.221729,0.224456,fail
9,0.548117,0.836768,0.387514,0.124742,0.764182,1.029465,0.528422,0.787376,1.075110,1.082985,...,0.295610,0.885146,0.304061,1.108404,0.140682,0.450644,0.244540,0.253634,0.245574,fail
10,0.324146,0.466047,0.216092,0.070927,0.342739,0.445136,0.228660,0.426423,0.549580,0.655357,...,0.150228,0.472577,0.143822,0.639542,0.077958,0.280698,0.139021,0.130710,0.145737,pass
11,0.619218,0.894096,0.423803,0.125445,0.681286,0.869360,0.426189,0.919240,1.166888,1.125609,...,0.332578,1.023308,0.277638,1.278794,0.155697,0.504359,0.296028,0.253396,0.288269,pass
12,0.450229,0.655940,0.308276,0.095056,0.615467,0.837133,0.395413,0.749432,0.943613,0.882823,...,0.283185,0.827375,0.244940,0.920404,0.124109,0.375410,0.214898,0.201549,0.200158,pass
13,0.332708,0.566470,0.236294,0.071226,0.548459,0.772213,0.386463,0.607395,0.838284,0.666980,...,0.253242,0.672587,0.229230,0.643379,0.095446,0.271169,0.165286,0.167804,0.135397,pass
14,0.658418,1.022961,0.471440,0.135533,0.717153,0.967610,0.441363,0.753949,0.971682,0.823995,...,0.223461,0.823543,0.265231,1.232462,0.142026,0.368943,0.239150,0.244598,0.264142,pass
15,0.488611,0.737098,0.323136,0.101211,0.538210,0.693423,0.336440,0.598632,0.755880,0.793592,...,0.210142,0.631394,0.206577,0.865304,0.106799,0.328916,0.178246,0.182179,0.192200,pass
16,0.522764,0.783475,0.359170,0.105626,0.636018,0.871025,0.393193,0.701803,0.843976,0.833734,...,0.178452,0.715751,0.243149,0.959192,0.109526,0.355774,0.209229,0.213220,0.216215,pass
17,0.553873,0.849914,0.373106,0.109371,0.652193,0.815468,0.385972,0.753300,0.917490,0.902419,...,0.228648,0.779828,0.245952,1.099894,0.132251,0.382283,0.228140,0.217749,0.240676,pass
18,0.534104,0.759828,0.363382,0.110445,0.636157,0.810939,0.389779,0.801193,0.978834,1.032556,...,0.285492,0.892703,0.249435,1.091019,0.136665,0.458003,0.253251,0.224822,0.250508,pass
19,0.325690,0.488732,0.229862,0.072305,0.353114,0.496727,0.229833,0.435888,0.586178,0.537719,...,0.180187,0.505438,0.132216,0.622238,0.075602,0.225112,0.134283,0.122414,0.135775,pass

BARINEL SCORES

,cp 9,swap 8,h 3,cp 15,h 12,cp 6,rzz 10,x 4,h 17,h 2,...,cp 13,cp 5,h 14,cp 16,h 0,cp 18,swap 11,cp 20,cp 19,h 21
sum,0.544784,0.542653,0.539781,0.539057,0.537785,0.5377,0.536684,0.535777,0.535409,0.535359,...,0.53433,0.530777,0.530482,0.529627,0.529481,0.523243,0.522489,0.519995,0.518721,0.517287

TARANTULA SCORES

,cp 9,swap 8,h 3,cp 15,h 12,cp 6,rzz 10,x 4,h 17,h 2,...,cp 13,cp 5,h 14,cp 16,h 0,cp 18,swap 11,cp 20,cp 19,h 21
sum,0.544784,0.542653,0.539781,0.539057,0.537785,0.5377,0.536684,0.535777,0.535409,0.535359,...,0.53433,0.530777,0.530482,0.529627,0.529481,0.523243,0.522489,0.519995,0.518721,0.517287

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_cswap_inGap_6_.qasm

100%|██████████| 10/10 [00:50<00:00,  5.08s/it]
100%|██████████| 10/10 [00:55<00:00,  5.59s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,swap 12,...,cp 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.632433,0.903044,0.409926,0.125914,0.654473,0.836344,0.397250,0.941336,1.171810,0.340878,...,1.139053,0.755908,0.203969,1.103932,0.121299,0.358541,0.290107,0.211512,0.262735,fail
1,0.518942,0.792671,0.359819,0.107396,0.633388,0.815676,0.392862,0.663272,0.869586,0.270175,...,0.964671,0.605167,0.192505,0.874153,0.093908,0.296006,0.236981,0.195948,0.211170,fail
2,0.708574,1.069704,0.487964,0.149911,0.809152,1.035689,0.487110,1.018024,1.284084,0.360209,...,1.308791,0.853188,0.241409,1.246969,0.138293,0.394413,0.321559,0.248457,0.291197,fail
3,0.423048,0.643497,0.277395,0.094855,0.563239,0.758802,0.382015,0.526408,0.751484,0.281542,...,0.922717,0.546403,0.186001,0.659261,0.089503,0.222854,0.173816,0.156358,0.143459,fail
4,0.580683,0.890897,0.412484,0.118531,0.709914,0.893982,0.443265,0.860030,1.075618,0.334645,...,1.118911,0.724040,0.222768,1.043046,0.120122,0.323736,0.269502,0.215282,0.239429,fail
5,0.625158,1.003344,0.445662,0.137225,0.741318,0.950965,0.451957,0.760515,0.984988,0.320592,...,1.139375,0.716972,0.231226,1.093647,0.115520,0.319774,0.264455,0.225314,0.246649,fail
6,0.407147,0.573358,0.267593,0.079620,0.500764,0.694655,0.340843,0.579148,0.819846,0.314409,...,0.919920,0.584381,0.172378,0.658971,0.088372,0.214182,0.182437,0.147946,0.146959,fail
7,0.606038,0.860651,0.431298,0.125138,0.639326,0.869085,0.425660,0.870402,1.163698,0.423712,...,1.242740,0.791351,0.210240,1.054598,0.125273,0.328390,0.270026,0.202792,0.238640,fail
8,0.389386,0.537029,0.285620,0.070966,0.610719,0.841185,0.381650,0.833026,1.001196,0.310769,...,1.034578,0.680609,0.201996,0.707971,0.099141,0.280581,0.233539,0.177184,0.172119,fail
9,0.499639,0.700516,0.349871,0.101045,0.596808,0.810462,0.384285,0.859608,1.111146,0.372237,...,1.182843,0.762317,0.207522,0.863533,0.111636,0.312153,0.253450,0.187913,0.201944,fail
10,0.265008,0.369586,0.181139,0.055362,0.454779,0.641093,0.335086,0.625441,0.850283,0.280905,...,0.888203,0.551020,0.164913,0.463782,0.079023,0.204704,0.163683,0.126911,0.106973,pass
11,0.402055,0.650410,0.275716,0.086694,0.635318,0.876461,0.420881,0.621697,0.822421,0.231160,...,0.950089,0.585415,0.210758,0.718501,0.088668,0.243299,0.201116,0.178854,0.163315,pass
12,0.319266,0.474331,0.250095,0.064457,0.348009,0.488666,0.206552,0.465659,0.574707,0.184897,...,0.631410,0.406009,0.111300,0.572984,0.063203,0.168495,0.143964,0.111208,0.131455,pass
13,0.342164,0.509727,0.223163,0.072681,0.442578,0.552437,0.286710,0.511571,0.659026,0.200883,...,0.718505,0.451339,0.145038,0.592776,0.072601,0.199301,0.157265,0.129472,0.135288,pass
14,0.453576,0.661048,0.315756,0.095896,0.499820,0.648832,0.313055,0.655549,0.845934,0.273499,...,0.924019,0.581206,0.159287,0.761357,0.093522,0.257199,0.205723,0.151731,0.174878,pass
15,0.593074,0.883497,0.367394,0.122093,0.632516,0.786849,0.379762,0.713303,0.920877,0.268742,...,0.943523,0.601748,0.184265,0.929537,0.106903,0.287591,0.229730,0.186656,0.215984,pass
16,0.507631,0.748050,0.343535,0.101539,0.722628,0.952495,0.460884,0.911827,1.150483,0.359983,...,1.199063,0.774126,0.235228,0.878945,0.116098,0.326153,0.264724,0.209738,0.209828,pass
17,0.296573,0.453492,0.203468,0.063205,0.374069,0.474492,0.234050,0.529150,0.687915,0.220139,...,0.728572,0.466434,0.121036,0.523207,0.068346,0.195773,0.154943,0.114853,0.124309,pass
18,0.511126,0.786962,0.358799,0.108820,0.686083,0.913128,0.423740,0.773313,0.987919,0.292515,...,1.073938,0.681969,0.217463,0.868758,0.108039,0.288380,0.234010,0.194603,0.195857,pass
19,0.559507,0.877730,0.393138,0.123707,0.646663,0.816277,0.415468,0.761685,0.998320,0.323259,...,1.097744,0.697166,0.210044,1.002837,0.107477,0.314699,0.251907,0.202024,0.226698,pass

BARINEL SCORES

,cp 19,h 0,cp 5,h 21,swap 12,h 2,cp 20,cp 18,h 3,h 1,...,x 4,cp 7,h 14,cp 13,cp 8,cp 16,h 17,cp 6,cp 15,h 11
sum,0.561404,0.561179,0.559974,0.559178,0.558103,0.554277,0.554202,0.553901,0.551031,0.550725,...,0.549624,0.547746,0.546357,0.546328,0.545173,0.543305,0.54271,0.540566,0.540374,0.536282

TARANTULA SCORES

,cp 19,h 0,cp 5,h 21,swap 12,h 2,cp 20,cp 18,h 3,h 1,...,x 4,cp 7,h 14,cp 13,cp 8,cp 16,h 17,cp 6,cp 15,h 11
sum,0.561404,0.561179,0.559974,0.559178,0.558103,0.554277,0.554202,0.553901,0.551031,0.550725,...,0.549624,0.547746,0.546357,0.546328,0.545173,0.543305,0.54271,0.540566,0.540374,0.536282

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_y_inGap_12_.qasm

100%|██████████| 10/10 [00:41<00:00,  4.17s/it]
100%|██████████| 10/10 [00:38<00:00,  3.81s/it]

,h 21,cp 20,cp 19,y 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.485387,0.682456,0.312663,0.411836,0.094277,0.608336,0.801208,0.415744,0.769840,1.013048,...,0.339702,0.871582,0.267847,0.938438,0.136200,0.399006,0.227327,0.208156,0.204360,fail
1,0.467644,0.700602,0.310865,0.355606,0.099316,0.598279,0.781587,0.383228,0.704747,0.915956,...,0.279153,0.807831,0.244686,0.927448,0.123040,0.396154,0.217149,0.207603,0.206392,fail
2,0.661695,0.997658,0.446286,0.511134,0.140938,0.821314,1.083799,0.539811,0.960647,1.274251,...,0.341485,1.087474,0.327510,1.362114,0.174241,0.555254,0.303633,0.285674,0.300954,fail
3,0.669027,1.017968,0.435884,0.446511,0.140523,0.763189,0.895685,0.458909,0.940682,1.236173,...,0.379430,1.081341,0.280846,1.375843,0.156559,0.540395,0.313231,0.273063,0.312225,fail
4,0.536911,0.760467,0.375507,0.345166,0.111124,0.631321,0.870060,0.425134,0.736589,0.958659,...,0.247837,0.797363,0.256360,1.040070,0.134547,0.391091,0.227952,0.217515,0.228913,fail
5,0.651488,1.001623,0.454898,0.348074,0.141397,0.819152,1.102542,0.545966,0.893288,1.212983,...,0.325851,1.032701,0.317464,1.309311,0.166363,0.472247,0.280467,0.275388,0.285165,fail
6,0.650599,0.910656,0.423759,0.445767,0.128529,0.778573,0.979679,0.475985,0.962396,1.177667,...,0.309513,1.031679,0.304623,1.311326,0.161873,0.523092,0.304412,0.272967,0.299318,fail
7,0.434238,0.633319,0.291000,0.348859,0.087542,0.640537,0.875683,0.431964,0.765138,1.014191,...,0.301656,0.857166,0.264232,0.865024,0.117264,0.398563,0.226869,0.211981,0.197533,fail
8,0.684126,1.006460,0.437606,0.436708,0.140970,0.622531,0.758917,0.376200,0.766103,1.021686,...,0.339054,0.891787,0.225176,1.241158,0.147716,0.430711,0.249276,0.225546,0.275352,fail
9,0.683557,0.993411,0.431694,0.548384,0.144260,0.773289,0.939813,0.469003,0.968258,1.214997,...,0.379032,1.067119,0.295093,1.340615,0.166302,0.568009,0.303140,0.273627,0.307415,fail
10,0.286504,0.432598,0.206627,0.225221,0.059907,0.438062,0.615057,0.279710,0.527845,0.683933,...,0.235620,0.592535,0.173225,0.587584,0.085118,0.254081,0.148769,0.136654,0.128186,pass
11,0.601761,0.890732,0.402670,0.314706,0.125442,0.699252,0.890540,0.449008,0.861677,1.094350,...,0.251725,0.921276,0.271107,1.241602,0.139902,0.464293,0.277336,0.245503,0.279066,pass
12,0.629817,0.938011,0.419696,0.322338,0.136164,0.613130,0.763730,0.380508,0.681822,0.904192,...,0.194328,0.777305,0.224114,1.255875,0.131811,0.425089,0.239952,0.227320,0.279478,pass
13,0.321795,0.426287,0.212275,0.337598,0.063753,0.455306,0.673763,0.329662,0.588695,0.821166,...,0.323914,0.729188,0.208902,0.586134,0.103561,0.291984,0.163893,0.147625,0.128339,pass
14,0.606879,0.931743,0.413580,0.362468,0.131963,0.729830,0.933811,0.458735,0.807894,1.026773,...,0.227972,0.859236,0.275048,1.231539,0.144298,0.471084,0.262364,0.253518,0.273255,pass
15,0.669502,0.988870,0.454853,0.329095,0.141197,0.629513,0.870126,0.413433,0.757820,1.051848,...,0.233537,0.860019,0.241060,1.291279,0.142712,0.412362,0.254798,0.232996,0.283857,pass
16,0.323734,0.479081,0.225051,0.240513,0.065791,0.437655,0.636815,0.307185,0.511677,0.696552,...,0.278869,0.631780,0.199986,0.582609,0.091007,0.253216,0.143885,0.143682,0.124550,pass
17,0.308927,0.477017,0.196963,0.208216,0.066095,0.386856,0.507327,0.253129,0.404184,0.576799,...,0.172946,0.463302,0.143445,0.555827,0.076271,0.219802,0.123867,0.126691,0.122902,pass
18,0.467827,0.711563,0.340285,0.245182,0.096968,0.563954,0.757798,0.365305,0.724962,0.967059,...,0.310611,0.853375,0.222348,0.996370,0.119288,0.343527,0.225232,0.194750,0.215744,pass
19,0.669013,0.976532,0.433103,0.427174,0.133048,0.689780,0.866909,0.423564,0.800229,1.015873,...,0.275323,0.912038,0.272088,1.329527,0.153922,0.458790,0.266677,0.249924,0.291758,pass

BARINEL SCORES

,y 18,h 11,h 3,swap 8,h 13,h 2,cp 9,cp 7,h 1,h 16,...,cp 6,cp 14,h 0,h 21,cp 5,cp 15,cp 17,cp 20,cp 19,swap 10
sum,0.582208,0.569304,0.565324,0.56419,0.559496,0.557422,0.556552,0.55623,0.555877,0.555638,...,0.555084,0.552657,0.551688,0.548051,0.548035,0.547369,0.546361,0.545503,0.542563,0.530702

TARANTULA SCORES

,y 18,h 11,h 3,swap 8,h 13,h 2,cp 9,cp 7,h 1,h 16,...,cp 6,cp 14,h 0,h 21,cp 5,cp 15,cp 17,cp 20,cp 19,swap 10
sum,0.582208,0.569304,0.565324,0.56419,0.559496,0.557422,0.556552,0.55623,0.555877,0.555638,...,0.555084,0.552657,0.551688,0.548051,0.548035,0.547369,0.546361,0.545503,0.542563,0.530702

ERROR GATE LOCATION:
18
Now evolving the following mutant:  AddGate_y_inGap_3_.qasm

100%|██████████| 10/10 [00:42<00:00,  4.30s/it]
100%|██████████| 10/10 [00:42<00:00,  4.20s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,cp 8,cp 7,cp 6,x 5,h 4,h 3,y 2,h 1,h 0,pass/fail
0,0.538196,0.787508,0.373378,0.107928,0.688653,0.934701,0.451495,0.878859,1.103130,0.936242,...,0.908750,0.276761,1.093378,0.139516,0.392911,0.250900,0.092288,0.225922,0.233642,fail
1,0.506687,0.772664,0.355779,0.106090,0.584837,0.772833,0.379635,0.786443,1.060276,0.878049,...,0.917159,0.228029,1.073228,0.128103,0.392222,0.243447,0.086342,0.206295,0.235472,fail
2,0.533183,0.768292,0.361659,0.109509,0.680866,0.879164,0.435597,0.919997,1.142466,1.096224,...,0.973335,0.274381,1.135858,0.138728,0.494754,0.283967,0.095239,0.243363,0.262594,fail
3,0.531570,0.813719,0.386734,0.112366,0.816932,1.112673,0.548018,0.973705,1.278622,1.132872,...,1.115496,0.334050,1.119023,0.152138,0.487104,0.286126,0.099444,0.266179,0.248785,fail
4,0.542927,0.849476,0.368849,0.110899,0.681944,0.891617,0.430439,0.788744,1.043564,0.944358,...,0.910773,0.265152,1.023751,0.139036,0.378891,0.228278,0.087889,0.219754,0.220329,fail
5,0.609191,0.875924,0.401243,0.125042,0.665645,0.800228,0.403045,0.936300,1.158590,1.090480,...,1.012149,0.257176,1.297399,0.146455,0.510961,0.303919,0.102013,0.249625,0.296467,fail
6,0.506366,0.792384,0.381184,0.106002,0.698551,0.906061,0.448174,0.818898,1.072826,0.982843,...,0.915447,0.269817,1.048754,0.136129,0.420016,0.251165,0.087077,0.234688,0.237601,fail
7,0.531682,0.800269,0.394754,0.107772,0.676691,0.940275,0.428255,0.826555,1.021918,0.915164,...,0.902190,0.269237,1.098653,0.132922,0.405189,0.248167,0.084294,0.231558,0.241603,fail
8,0.562113,0.882096,0.407257,0.115937,0.734899,0.921485,0.449973,0.886319,1.095740,0.988522,...,0.973327,0.287127,1.225254,0.141344,0.462837,0.276603,0.091948,0.254024,0.270944,fail
9,0.520361,0.809704,0.350827,0.111835,0.646221,0.884216,0.416980,0.710980,0.976557,0.845300,...,0.853109,0.253240,1.016821,0.130517,0.372444,0.220977,0.078544,0.217648,0.220145,fail
10,0.401437,0.608543,0.279062,0.082927,0.468324,0.665970,0.338805,0.520255,0.753040,0.590163,...,0.630285,0.197422,0.763215,0.098999,0.256790,0.164724,0.060117,0.157924,0.161967,pass
11,0.537387,0.862482,0.366597,0.119611,0.712787,0.922289,0.455706,0.769450,1.027404,0.979639,...,0.891778,0.277457,1.107824,0.133400,0.428571,0.239640,0.081631,0.239458,0.241570,pass
12,0.583865,0.911895,0.432476,0.123904,0.759816,1.006923,0.470739,0.816665,0.996306,0.970713,...,0.853991,0.290705,1.142710,0.130316,0.425217,0.247379,0.083528,0.254830,0.254007,pass
13,0.417310,0.621319,0.279470,0.085253,0.519506,0.704042,0.336148,0.568468,0.737146,0.713943,...,0.629291,0.201780,0.741938,0.100313,0.288708,0.167601,0.061895,0.170009,0.166571,pass
14,0.541082,0.771810,0.357671,0.104766,0.594800,0.792218,0.384228,0.699400,0.885348,0.809600,...,0.750148,0.233669,1.051923,0.123929,0.354627,0.218260,0.077645,0.202539,0.227204,pass
15,0.527373,0.780413,0.368233,0.105770,0.665292,0.919005,0.421408,0.766846,1.010736,0.811316,...,0.856103,0.243529,0.991088,0.125920,0.326312,0.222017,0.085342,0.209705,0.215672,pass
16,0.671993,1.015708,0.481991,0.143130,0.812374,1.114131,0.524169,0.979494,1.265346,1.107591,...,1.060680,0.319977,1.374703,0.167673,0.502783,0.299817,0.103744,0.276752,0.296989,pass
17,0.515092,0.790165,0.346584,0.108706,0.696168,0.911490,0.445437,0.800896,1.059100,0.988447,...,0.900536,0.261463,1.049131,0.140536,0.416101,0.240447,0.085387,0.228028,0.231810,pass
18,0.398739,0.620897,0.269434,0.083168,0.537069,0.684477,0.342743,0.542193,0.692021,0.701688,...,0.561105,0.201657,0.765223,0.094423,0.299972,0.162676,0.056331,0.169490,0.168231,pass
19,0.189782,0.306982,0.131284,0.044696,0.489711,0.727075,0.358520,0.530203,0.734322,0.715210,...,0.612125,0.216590,0.341526,0.083236,0.240070,0.126229,0.051692,0.140821,0.072997,pass

BARINEL SCORES

,swap 9,h 3,cp 8,h 4,h 14,h 0,y 2,cp 13,cp 6,h 12,...,cp 10,cp 19,h 21,cp 20,cp 18,cp 7,h 17,cp 15,cp 16,swap 11
sum,0.55554,0.5539,0.550375,0.549525,0.549383,0.547791,0.547739,0.544568,0.544055,0.539062,...,0.533823,0.533044,0.529421,0.527905,0.526343,0.526237,0.523585,0.51852,0.517027,0.510204

TARANTULA SCORES

,swap 9,h 3,cp 8,h 4,h 14,h 0,y 2,cp 13,cp 6,h 12,...,cp 10,cp 19,h 21,cp 20,cp 18,cp 7,h 17,cp 15,cp 16,swap 11
sum,0.55554,0.5539,0.550375,0.549525,0.549383,0.547791,0.547739,0.544568,0.544055,0.539062,...,0.533823,0.533044,0.529421,0.527905,0.526343,0.526237,0.523585,0.51852,0.517027,0.510204

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_cz_inGap_10_.qasm

100%|██████████| 10/10 [00:57<00:00,  5.77s/it]
100%|██████████| 10/10 [00:49<00:00,  4.92s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cz 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.800933,1.183263,0.572542,0.163600,0.848722,1.660176,1.152340,0.547498,0.948114,1.251993,...,0.240418,1.132175,0.371090,1.705031,0.196432,0.558900,0.353988,0.652504,0.531138,fail
1,0.520937,0.796325,0.365536,0.109104,0.714055,1.347364,0.979835,0.481634,0.740338,1.034702,...,0.235832,0.960990,0.326395,1.174859,0.153177,0.434566,0.271312,0.481007,0.409076,fail
2,0.605276,0.887259,0.440687,0.128090,0.727137,1.368681,0.956234,0.492287,0.861624,1.158572,...,0.188281,1.027166,0.319623,1.356423,0.162403,0.486584,0.316596,0.548193,0.442870,fail
3,0.484527,0.714940,0.319124,0.104131,0.679086,1.280223,0.963012,0.483120,0.657846,0.962759,...,0.175946,0.860424,0.304398,1.070559,0.151457,0.410228,0.250724,0.459491,0.373921,fail
4,0.515300,0.831693,0.352944,0.113155,0.683050,1.196786,0.921776,0.465084,0.678867,0.953071,...,0.219341,0.844666,0.298737,1.163383,0.155566,0.412317,0.246834,0.445013,0.373382,fail
5,0.616016,0.907905,0.431850,0.127255,0.659605,1.275835,0.900042,0.439331,0.782984,1.057280,...,0.192271,0.949146,0.288467,1.362900,0.162500,0.452896,0.296266,0.528204,0.409188,fail
6,0.524730,0.783751,0.370978,0.108398,0.648057,1.144577,0.907191,0.432071,0.732160,0.995298,...,0.235757,0.918234,0.276841,1.128519,0.154762,0.439472,0.268627,0.470417,0.372861,fail
7,0.375714,0.566116,0.279817,0.076027,0.643307,1.175332,0.914046,0.435767,0.665706,0.917223,...,0.207236,0.877162,0.294949,0.858877,0.134592,0.356534,0.231865,0.394685,0.366066,fail
8,0.549049,0.791067,0.357108,0.119695,0.700983,1.318344,0.946157,0.465526,0.750371,0.991645,...,0.217815,0.930050,0.321649,1.220111,0.159218,0.520382,0.283359,0.518397,0.429317,fail
9,0.700296,1.027898,0.497581,0.140334,0.853824,1.576360,1.188941,0.550839,0.967013,1.246658,...,0.178039,1.125821,0.368369,1.526617,0.184293,0.561610,0.363194,0.652154,0.504053,fail
10,0.469877,0.705240,0.334063,0.093206,0.582350,1.089638,0.809080,0.377038,0.667314,0.908892,...,0.196174,0.808292,0.251203,1.019225,0.127616,0.359695,0.240845,0.423217,0.328505,pass
11,0.324757,0.510050,0.212467,0.069375,0.632107,1.136105,0.858083,0.422368,0.574217,0.789595,...,0.202576,0.770649,0.294333,0.680581,0.122155,0.341560,0.189946,0.335931,0.330361,pass
12,0.404988,0.625859,0.304416,0.087713,0.532072,0.994809,0.721679,0.368145,0.638254,0.871235,...,0.172539,0.775576,0.240425,0.977439,0.124007,0.370648,0.236653,0.404197,0.310077,pass
13,0.561784,0.882059,0.384311,0.119558,0.662754,1.136490,0.862280,0.414466,0.678931,0.909130,...,0.208884,0.832397,0.273274,1.244653,0.157607,0.430287,0.256054,0.475531,0.363090,pass
14,0.474999,0.754309,0.339785,0.103385,0.620986,1.216922,0.854474,0.444119,0.666210,0.962196,...,0.254532,0.898424,0.283938,1.050923,0.139058,0.365899,0.238890,0.411846,0.346839,pass
15,0.561232,0.812708,0.355719,0.113813,0.628124,1.116329,0.887984,0.414896,0.687832,0.951649,...,0.248198,0.866655,0.257507,1.175307,0.156062,0.427291,0.257521,0.459840,0.346216,pass
16,0.624589,0.909643,0.426258,0.126582,0.782286,1.374485,1.042264,0.501893,0.877369,1.150884,...,0.167974,1.027938,0.334699,1.413630,0.184301,0.526921,0.331045,0.589330,0.451823,pass
17,0.549852,0.783155,0.359054,0.114762,0.640809,1.292716,0.926263,0.479191,0.699585,1.047156,...,0.198352,0.899363,0.288526,1.200705,0.142468,0.420498,0.270210,0.483015,0.384434,pass
18,0.582818,0.849165,0.373908,0.124211,0.734853,1.365973,1.006855,0.526438,0.758514,1.088626,...,0.200779,0.969612,0.327478,1.264683,0.158997,0.491261,0.292337,0.533676,0.434786,pass
19,0.497203,0.735531,0.310193,0.106139,0.612083,1.034415,0.767550,0.390724,0.639410,0.835086,...,0.182965,0.752840,0.261560,1.038199,0.129231,0.456214,0.236366,0.440403,0.366047,pass

BARINEL SCORES

,cp 19,swap 10,h 0,cp 5,cz 16,h 2,h 13,h 1,cp 6,h 21,...,cp 20,x 4,cp 7,h 17,cp 12,h 3,cp 14,h 11,cp 9,swap 8
sum,0.539792,0.539214,0.534905,0.531777,0.531588,0.530639,0.53058,0.530549,0.52988,0.529813,...,0.528724,0.528289,0.528092,0.526843,0.526259,0.525115,0.52485,0.522632,0.517972,0.507027

TARANTULA SCORES

,cp 19,swap 10,h 0,cp 5,cz 16,h 2,h 13,h 1,cp 6,h 21,...,cp 20,x 4,cp 7,h 17,cp 12,h 3,cp 14,h 11,cp 9,swap 8
sum,0.539792,0.539214,0.534905,0.531777,0.531588,0.530639,0.53058,0.530549,0.52988,0.529813,...,0.528724,0.528289,0.528092,0.526843,0.526259,0.525115,0.52485,0.522632,0.517972,0.507027

ERROR GATE LOCATION:
16
Now evolving the following mutant:  AddGate_y_inGap_6_.qasm

100%|██████████| 10/10 [00:41<00:00,  4.10s/it]
100%|██████████| 10/10 [00:38<00:00,  3.86s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.577913,0.860354,0.389340,0.121440,0.661901,0.842576,0.419281,0.746019,0.963616,1.002997,...,0.301219,0.860654,0.262457,1.140704,0.138957,0.434107,0.239642,0.229791,0.250275,fail
1,0.452684,0.718976,0.328294,0.097771,0.590504,0.730658,0.366919,0.718748,0.943997,0.891422,...,0.340393,0.822706,0.225600,0.913038,0.121461,0.379541,0.222608,0.203686,0.207107,fail
2,0.568955,0.835859,0.387625,0.115996,0.648411,0.866742,0.420627,0.807658,1.021066,0.982769,...,0.274485,0.866659,0.257847,1.124030,0.136853,0.413332,0.240841,0.221304,0.242503,fail
3,0.580740,0.861282,0.416016,0.123662,0.643392,0.892926,0.406603,0.754474,0.960347,0.866248,...,0.180368,0.782721,0.232306,1.148769,0.127772,0.382150,0.235664,0.217527,0.251668,fail
4,0.429810,0.624785,0.292846,0.087415,0.601127,0.781373,0.377482,0.750522,0.966500,0.946118,...,0.350913,0.867878,0.242375,0.876372,0.131193,0.387758,0.220033,0.198930,0.194910,fail
5,0.608004,0.867929,0.383754,0.125599,0.772968,1.028077,0.489629,0.908965,1.114300,1.253605,...,0.224141,0.944715,0.309041,1.213054,0.154251,0.539920,0.283511,0.268947,0.279976,fail
6,0.292792,0.437472,0.188012,0.064294,0.443741,0.643144,0.306656,0.455725,0.625801,0.642765,...,0.206983,0.548017,0.183081,0.536290,0.080115,0.250456,0.130429,0.137281,0.117521,fail
7,0.583146,0.860119,0.432251,0.118984,0.649743,0.879494,0.427432,0.799408,1.021307,0.919313,...,0.260810,0.883697,0.259227,1.210216,0.139346,0.407619,0.254441,0.227949,0.263820,fail
8,0.639766,0.930177,0.443421,0.129221,0.728208,0.939499,0.446639,0.943630,1.185994,1.107993,...,0.339533,1.081998,0.289853,1.336558,0.152695,0.525797,0.311158,0.266599,0.303777,fail
9,0.587550,0.891199,0.398049,0.114577,0.800095,1.011547,0.489929,0.911620,1.115894,1.074924,...,0.322045,0.958685,0.307042,1.148895,0.157395,0.437529,0.261822,0.254262,0.250345,fail
10,0.418583,0.602545,0.260016,0.087319,0.525484,0.646905,0.325936,0.676234,0.866137,0.843553,...,0.280699,0.773363,0.207546,0.855626,0.115851,0.368977,0.205633,0.178155,0.191675,pass
11,0.465798,0.697052,0.335348,0.095344,0.633119,0.849878,0.425560,0.694076,0.891794,0.882859,...,0.259292,0.759877,0.265102,0.901801,0.123921,0.372208,0.211489,0.213547,0.200460,pass
12,0.805661,1.213242,0.577201,0.167324,0.800557,0.989655,0.469125,1.015893,1.225471,1.090631,...,0.249838,1.043613,0.287271,1.665390,0.170437,0.518890,0.331231,0.289179,0.364828,pass
13,0.632626,0.932725,0.424001,0.121726,0.754341,0.987571,0.477779,0.909863,1.111870,1.014395,...,0.209749,0.921357,0.289772,1.259606,0.151136,0.440237,0.273765,0.249798,0.274613,pass
14,0.515832,0.827197,0.374916,0.108172,0.619847,0.828962,0.390385,0.794039,1.046787,0.861420,...,0.369738,0.919254,0.245423,1.033953,0.130581,0.370784,0.232965,0.208374,0.218710,pass
15,0.445066,0.620662,0.296350,0.093016,0.500050,0.668249,0.354141,0.736732,0.966991,0.899853,...,0.258515,0.816022,0.216217,0.958518,0.124292,0.399162,0.232761,0.187140,0.213543,pass
16,0.417999,0.596588,0.285338,0.087588,0.399153,0.559830,0.270876,0.538060,0.778922,0.684150,...,0.299057,0.695076,0.157980,0.782820,0.109464,0.281566,0.171855,0.144686,0.167387,pass
17,0.357088,0.554951,0.226657,0.074142,0.499651,0.634772,0.331988,0.603691,0.780886,0.731771,...,0.257572,0.695142,0.217267,0.747256,0.098683,0.320171,0.180653,0.169579,0.162451,pass
18,0.491876,0.726956,0.328689,0.105750,0.711146,0.939487,0.466165,0.787562,1.002972,1.015617,...,0.218173,0.820149,0.273101,1.009736,0.123103,0.441387,0.241625,0.235370,0.234926,pass
19,0.300650,0.487868,0.210035,0.066167,0.452142,0.579072,0.290351,0.581361,0.791685,0.693050,...,0.302742,0.696798,0.177938,0.656100,0.098817,0.286594,0.166918,0.150266,0.141846,pass

BARINEL SCORES

,y 10,swap 11,cp 9,cp 16,h 12,h 17,cp 19,cp 6,h 1,h 21,...,cp 15,h 0,cp 20,cp 5,x 4,h 2,h 14,cp 7,cp 13,swap 8
sum,0.532283,0.531121,0.529545,0.528578,0.526374,0.525918,0.524437,0.523562,0.523538,0.52311,...,0.521933,0.521122,0.520741,0.518937,0.518125,0.516267,0.515173,0.514234,0.511745,0.508674

TARANTULA SCORES

,y 10,swap 11,cp 9,cp 16,h 12,h 17,cp 19,cp 6,h 1,h 21,...,cp 15,h 0,cp 20,cp 5,x 4,h 2,h 14,cp 7,cp 13,swap 8
sum,0.532283,0.531121,0.529545,0.528578,0.526374,0.525918,0.524437,0.523562,0.523538,0.52311,...,0.521933,0.521122,0.520741,0.518937,0.518125,0.516267,0.515173,0.514234,0.511745,0.508674

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_ry_inGap_6_.qasm

100%|██████████| 10/10 [00:41<00:00,  4.11s/it]
100%|██████████| 10/10 [00:40<00:00,  4.01s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.457337,0.684160,0.350464,0.099226,0.616952,0.896788,0.431526,0.791242,1.071241,0.951579,...,0.356011,0.914569,0.262640,0.938791,0.133648,0.390575,0.226559,0.207355,0.201519,fail
1,0.587810,0.824180,0.398118,0.120576,0.645374,0.829060,0.397360,0.810291,1.017594,1.014821,...,0.286697,0.888814,0.249280,1.148647,0.144577,0.445545,0.257482,0.229042,0.258717,fail
2,0.573481,0.883788,0.384529,0.124970,0.688612,0.838995,0.422137,0.735068,0.933404,1.031188,...,0.256481,0.818313,0.264720,1.180171,0.141534,0.459881,0.246817,0.243904,0.260444,fail
3,0.622170,0.869808,0.415285,0.127739,0.746693,0.988630,0.489895,0.961287,1.217597,1.224677,...,0.316469,1.023707,0.305958,1.242134,0.155155,0.528858,0.295324,0.261285,0.281714,fail
4,0.449986,0.666845,0.308478,0.098749,0.611605,0.823044,0.384606,0.744526,0.974152,0.919276,...,0.341825,0.866237,0.240216,0.887841,0.124936,0.392325,0.218124,0.203275,0.198752,fail
5,0.606558,0.913150,0.423583,0.126250,0.738273,0.949379,0.457840,0.923686,1.177793,1.044186,...,0.311424,1.024583,0.274546,1.290874,0.156550,0.486733,0.296649,0.258248,0.288882,fail
6,0.519566,0.709220,0.329920,0.105936,0.638657,0.816644,0.398262,0.856232,1.086175,1.165589,...,0.412007,0.986957,0.270390,0.991666,0.141150,0.487936,0.254394,0.230264,0.230298,fail
7,0.776695,1.172477,0.544993,0.161867,0.933210,1.246790,0.593888,1.081835,1.386050,1.213183,...,0.350758,1.219072,0.352294,1.535229,0.182408,0.564301,0.341463,0.318535,0.342346,fail
8,0.449806,0.666643,0.292970,0.091989,0.709165,0.912111,0.462595,0.816631,1.046765,0.992468,...,0.281083,0.901761,0.283756,0.992364,0.140207,0.427108,0.248708,0.230869,0.221706,fail
9,0.457340,0.671613,0.297756,0.095095,0.709658,0.969318,0.461642,0.820667,1.070554,1.044334,...,0.317446,0.919882,0.280279,0.927555,0.129651,0.446246,0.241630,0.232650,0.214608,fail
10,0.545224,0.844992,0.366098,0.117347,0.666417,0.861828,0.415317,0.785781,1.049494,0.994486,...,0.325631,0.898091,0.251451,1.068985,0.131186,0.434626,0.242470,0.226995,0.239543,pass
11,0.437580,0.657655,0.313177,0.096055,0.533910,0.748098,0.352356,0.633319,0.843075,0.714996,...,0.245337,0.718412,0.207928,0.855051,0.110989,0.308601,0.186355,0.177779,0.184694,pass
12,0.619611,1.001145,0.467262,0.130226,0.756233,0.978291,0.473393,0.860485,1.063707,0.937082,...,0.281281,0.920971,0.296505,1.289031,0.143549,0.425121,0.266843,0.257358,0.276757,pass
13,0.410261,0.602361,0.269945,0.084911,0.484229,0.657853,0.319400,0.654449,0.861083,0.749780,...,0.218454,0.713301,0.197092,0.824619,0.109288,0.330900,0.199821,0.168621,0.181336,pass
14,0.537528,0.781584,0.338345,0.116111,0.661225,0.890500,0.441653,0.759388,1.024487,1.009014,...,0.281770,0.892016,0.257949,1.083444,0.138026,0.433891,0.239449,0.224300,0.240256,pass
15,0.525310,0.795725,0.349910,0.107564,0.728635,0.960951,0.498592,0.903789,1.237805,1.053800,...,0.366320,1.039078,0.296729,1.131729,0.146191,0.463115,0.276825,0.240366,0.246426,pass
16,0.584962,0.838424,0.412625,0.120031,0.668310,0.846414,0.417193,0.876457,1.130911,1.005233,...,0.371436,1.039116,0.266905,1.248579,0.152912,0.467360,0.288592,0.245162,0.279590,pass
17,0.568227,0.869773,0.417610,0.118076,0.642219,0.870415,0.424431,0.792092,1.061418,0.915807,...,0.321747,0.929540,0.255312,1.130188,0.140405,0.403268,0.249404,0.225977,0.246561,pass
18,0.539456,0.811615,0.399103,0.105137,0.779052,1.074964,0.506426,0.871478,1.077118,0.907803,...,0.300655,0.915656,0.310391,1.021461,0.133652,0.374085,0.244768,0.244584,0.224400,pass
19,0.297132,0.439207,0.203454,0.062063,0.318598,0.410657,0.197069,0.396568,0.505284,0.458904,...,0.132573,0.434696,0.116119,0.590419,0.064707,0.201636,0.122730,0.109363,0.130072,pass

BARINEL SCORES

,h 12,h 3,ry 10,cp 9,x 4,h 1,swap 8,h 14,h 2,cp 6,...,cp 16,cp 13,cp 15,h 0,cp 18,cp 5,h 21,cp 19,cp 20,swap 11
sum,0.547922,0.546441,0.544716,0.541292,0.532879,0.53251,0.531685,0.531342,0.531338,0.531266,...,0.527625,0.527044,0.526559,0.526255,0.521466,0.520856,0.520607,0.514318,0.513353,0.494346

TARANTULA SCORES

,h 12,h 3,ry 10,cp 9,x 4,h 1,swap 8,h 14,h 2,cp 6,...,cp 16,cp 13,cp 15,h 0,cp 18,cp 5,h 21,cp 19,cp 20,swap 11
sum,0.547922,0.546441,0.544716,0.541292,0.532879,0.53251,0.531685,0.531342,0.531338,0.531266,...,0.527625,0.527044,0.526559,0.526255,0.521466,0.520856,0.520607,0.514318,0.513353,0.494346

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_y_inGap_16_.qasm

100%|██████████| 10/10 [00:37<00:00,  3.79s/it]
100%|██████████| 10/10 [00:39<00:00,  3.97s/it]

,y 21,h 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.420232,0.525134,0.811394,0.379100,0.112729,0.732834,0.968519,0.472024,0.853521,1.103743,...,0.337460,0.966359,0.299063,1.137455,0.144144,0.449495,0.262500,0.250895,0.249869,fail
1,0.448163,0.610454,0.883828,0.413318,0.129825,0.612715,0.795961,0.375899,0.760372,0.976407,...,0.291235,0.878810,0.233762,1.163161,0.130664,0.439997,0.250678,0.224282,0.262050,fail
2,0.466298,0.563362,0.847923,0.383945,0.115437,0.687876,0.963041,0.467610,0.776710,1.047531,...,0.233641,0.842147,0.275896,1.054033,0.136528,0.386004,0.229249,0.226328,0.230051,fail
3,0.465486,0.550767,0.856749,0.372919,0.117870,0.780147,1.047981,0.501842,0.859688,1.123632,...,0.307687,0.949215,0.302732,1.086146,0.143131,0.436266,0.250354,0.249268,0.237642,fail
4,0.408241,0.520230,0.749823,0.385355,0.105630,0.618301,0.862661,0.426249,0.845433,1.125491,...,0.357681,0.999230,0.257545,1.096940,0.142261,0.398262,0.263881,0.222282,0.242452,fail
5,0.474306,0.516204,0.753935,0.340194,0.103881,0.567835,0.773186,0.370305,0.712853,0.965071,...,0.330751,0.830313,0.229133,0.929459,0.124387,0.360756,0.208590,0.189825,0.202673,fail
6,0.428837,0.468425,0.695896,0.352054,0.096297,0.599506,0.835344,0.394114,0.723339,0.964800,...,0.327539,0.850114,0.238215,0.920284,0.123286,0.341614,0.215239,0.197252,0.199821,fail
7,0.502033,0.540524,0.823703,0.390432,0.112614,0.699773,0.955663,0.467779,0.854697,1.111030,...,0.280276,0.946078,0.279265,1.127353,0.141756,0.404194,0.258287,0.235452,0.244790,fail
8,0.374564,0.558276,0.801695,0.380700,0.115172,0.788840,1.068687,0.511053,0.907566,1.153863,...,0.358020,1.008501,0.312322,1.116568,0.151321,0.482737,0.270429,0.257460,0.250989,fail
9,0.361297,0.486151,0.755207,0.345099,0.104752,0.583381,0.771446,0.364511,0.644154,0.820293,...,0.175495,0.710768,0.215435,0.990547,0.115009,0.335371,0.204460,0.196576,0.214212,fail
10,0.299639,0.451226,0.634401,0.305373,0.085523,0.604418,0.777674,0.368924,0.790329,0.945571,...,0.263394,0.837214,0.228185,0.924870,0.121032,0.371776,0.232922,0.196202,0.208871,pass
11,0.282635,0.518048,0.783230,0.366973,0.106179,0.542829,0.726975,0.341781,0.593447,0.747893,...,0.171907,0.658519,0.210525,0.996703,0.106507,0.304848,0.189116,0.189739,0.214291,pass
12,0.543343,0.462298,0.675244,0.302261,0.092660,0.692547,0.939096,0.446228,0.826862,1.036514,...,0.318283,0.934626,0.288496,0.937063,0.130459,0.457745,0.248311,0.232680,0.218886,pass
13,0.421053,0.841885,1.245381,0.588515,0.178214,0.873645,1.175826,0.557123,1.037400,1.383415,...,0.337334,1.164148,0.316966,1.637626,0.174915,0.539665,0.334919,0.304888,0.361169,pass
14,0.258506,0.527932,0.758743,0.400809,0.107466,0.531310,0.698822,0.323693,0.733757,0.908999,...,0.192595,0.779859,0.197981,1.121983,0.120512,0.359872,0.237597,0.196078,0.248990,pass
15,0.252191,0.441282,0.615957,0.295351,0.091522,0.467597,0.619324,0.313301,0.591854,0.783784,...,0.196146,0.680158,0.192307,0.920077,0.109013,0.338934,0.199578,0.174591,0.204508,pass
16,0.224276,0.391110,0.582185,0.273544,0.076948,0.468424,0.626984,0.299331,0.576339,0.715898,...,0.178642,0.606891,0.183303,0.784628,0.094086,0.259474,0.170990,0.157358,0.168123,pass
17,0.352826,0.330804,0.507767,0.256462,0.069252,0.536974,0.774276,0.356535,0.671212,0.885662,...,0.271480,0.761516,0.219290,0.731085,0.098529,0.303783,0.194431,0.174210,0.161070,pass
18,0.286260,0.532328,0.781354,0.367198,0.107918,0.751609,0.945641,0.465961,0.926448,1.101987,...,0.266667,0.936113,0.290731,1.108754,0.143183,0.474928,0.275922,0.251994,0.252288,pass
19,0.275327,0.284400,0.419583,0.184428,0.059401,0.334056,0.447768,0.217768,0.422734,0.568126,...,0.178094,0.504570,0.133883,0.553213,0.072545,0.225262,0.134917,0.119462,0.125533,pass

BARINEL SCORES

,y 21,swap 10,swap 8,cp 14,cp 9,cp 15,cp 6,x 4,h 16,cp 12,...,h 11,cp 19,h 1,cp 18,h 20,h 3,h 13,cp 5,h 2,h 0
sum,0.57643,0.563704,0.55817,0.54108,0.53916,0.53905,0.538909,0.536006,0.534783,0.533745,...,0.532589,0.532578,0.529719,0.528388,0.527577,0.525968,0.525414,0.522272,0.521043,0.518987

TARANTULA SCORES

,y 21,swap 10,swap 8,cp 14,cp 9,cp 15,cp 6,x 4,h 16,cp 12,...,h 11,cp 19,h 1,cp 18,h 20,h 3,h 13,cp 5,h 2,h 0
sum,0.57643,0.563704,0.55817,0.54108,0.53916,0.53905,0.538909,0.536006,0.534783,0.533745,...,0.532589,0.532578,0.529719,0.528388,0.527577,0.525968,0.525414,0.522272,0.521043,0.518987

ERROR GATE LOCATION:
21
Now evolving the following mutant:  AddGate_cswap_inGap_11_.qasm

100%|██████████| 10/10 [01:29<00:00,  8.98s/it]
100%|██████████| 10/10 [01:30<00:00,  9.01s/it]

,h 21,cswap 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.380403,1.343986,0.522125,0.197538,0.058154,0.424924,0.604355,0.272854,0.475940,0.675646,...,0.190175,0.577175,0.162433,0.524494,0.083483,0.229013,0.139310,0.159399,0.166099,fail
1,0.423433,1.503298,0.530006,0.182594,0.058647,0.404878,0.541451,0.261841,0.529951,0.792699,...,0.181018,0.663317,0.158412,0.582540,0.087764,0.238708,0.160915,0.159788,0.180122,fail
2,0.523620,1.350351,0.650660,0.250135,0.070667,0.454774,0.651340,0.289249,0.566882,0.738128,...,0.162960,0.631756,0.177656,0.699827,0.092644,0.305669,0.174641,0.186320,0.210143,fail
3,0.471224,1.546881,0.618910,0.246504,0.069574,0.465015,0.643314,0.295382,0.546810,0.778058,...,0.184979,0.663968,0.183388,0.711612,0.094321,0.280466,0.172017,0.187565,0.205746,fail
4,0.673125,1.637223,0.794887,0.281727,0.091975,0.527782,0.699764,0.340295,0.579694,0.797034,...,0.188253,0.684299,0.211322,0.839205,0.108873,0.362370,0.185560,0.217358,0.244733,fail
5,0.616725,1.945397,0.852792,0.332819,0.092770,0.577792,0.797042,0.365665,0.656404,0.949530,...,0.235863,0.809289,0.221778,0.917097,0.117146,0.324674,0.207953,0.236966,0.254910,fail
6,0.543359,1.748525,0.702577,0.268219,0.076890,0.500003,0.704107,0.337556,0.573649,0.861714,...,0.209194,0.704737,0.194000,0.718541,0.100975,0.260590,0.172511,0.190100,0.209569,fail
7,0.504075,1.617629,0.664930,0.224107,0.073216,0.483521,0.673090,0.332991,0.555359,0.829685,...,0.216925,0.706767,0.196242,0.657864,0.099546,0.293512,0.168842,0.187024,0.205788,fail
8,0.510904,1.564058,0.629826,0.259038,0.074430,0.476309,0.702714,0.327505,0.549283,0.806530,...,0.183357,0.664758,0.188893,0.701006,0.096765,0.256519,0.169252,0.182799,0.204169,fail
9,0.653857,1.485666,0.775670,0.284907,0.075281,0.476461,0.704973,0.307204,0.538843,0.712262,...,0.147238,0.602158,0.184639,0.732191,0.091927,0.280852,0.165241,0.178809,0.212194,fail
10,0.522103,1.188841,0.635945,0.222350,0.065902,0.373251,0.542553,0.253360,0.384495,0.589112,...,0.114671,0.472049,0.145407,0.595364,0.072006,0.203335,0.122737,0.141741,0.166509,pass
11,0.365985,0.957809,0.461069,0.158147,0.053557,0.278095,0.376709,0.186837,0.298674,0.450859,...,0.105740,0.372686,0.107936,0.453983,0.059462,0.166766,0.097572,0.115090,0.129615,pass
12,0.684790,1.931786,0.932056,0.328452,0.106689,0.550730,0.721001,0.356087,0.568680,0.863647,...,0.210670,0.713469,0.207103,0.933363,0.114016,0.325433,0.188167,0.232894,0.249116,pass
13,0.446666,1.683624,0.569463,0.243048,0.069828,0.461795,0.663776,0.303982,0.508889,0.755503,...,0.200452,0.647936,0.183745,0.680927,0.096675,0.259707,0.159522,0.189070,0.198337,pass
14,0.378363,1.007038,0.407578,0.148903,0.042863,0.297180,0.427369,0.201768,0.356369,0.517310,...,0.101456,0.418738,0.118405,0.422607,0.060041,0.163658,0.105527,0.109135,0.129614,pass
15,0.448126,1.196509,0.526213,0.204581,0.056051,0.331197,0.466927,0.212741,0.374720,0.530191,...,0.115436,0.441287,0.130324,0.561766,0.069736,0.188405,0.118401,0.133860,0.152617,pass
16,0.541141,1.690444,0.713031,0.244421,0.079122,0.477447,0.658055,0.323948,0.544753,0.825427,...,0.203064,0.688306,0.186010,0.707739,0.098284,0.275925,0.172435,0.189527,0.206535,pass
17,0.446553,1.403223,0.525864,0.198509,0.057431,0.383486,0.556499,0.260401,0.441006,0.658341,...,0.142229,0.539452,0.153775,0.553214,0.079265,0.205641,0.132536,0.144894,0.162877,pass
18,0.438989,1.774417,0.558184,0.240488,0.070245,0.448532,0.682679,0.311065,0.513175,0.777184,...,0.177999,0.654899,0.188783,0.682091,0.096818,0.267590,0.159921,0.184015,0.204220,pass
19,0.610382,1.312306,0.729097,0.251480,0.070868,0.477330,0.634272,0.301404,0.631959,0.813777,...,0.206100,0.714508,0.191930,0.711594,0.100310,0.329249,0.190198,0.189460,0.220111,pass

BARINEL SCORES

,h 13,swap 8,h 3,h 11,h 2,cp 7,h 16,cp 15,cp 12,cp 6,...,cp 14,h 0,x 4,cp 18,cp 5,cswap 20,cp 19,swap 10,cp 17,h 21
sum,0.546594,0.546314,0.5428,0.542636,0.542555,0.54223,0.540156,0.539845,0.539393,0.537991,...,0.535856,0.535001,0.534843,0.530119,0.529197,0.526716,0.526712,0.525312,0.524413,0.520504

TARANTULA SCORES

,h 13,swap 8,h 3,h 11,h 2,cp 7,h 16,cp 15,cp 12,cp 6,...,cp 14,h 0,x 4,cp 18,cp 5,cswap 20,cp 19,swap 10,cp 17,h 21
sum,0.546594,0.546314,0.5428,0.542636,0.542555,0.54223,0.540156,0.539845,0.539393,0.537991,...,0.535856,0.535001,0.534843,0.530119,0.529197,0.526716,0.526712,0.525312,0.524413,0.520504

ERROR GATE LOCATION:
20
Now evolving the following mutant:  AddGate_y_inGap_13_.qasm

100%|██████████| 10/10 [00:40<00:00,  4.03s/it]
100%|██████████| 10/10 [00:39<00:00,  3.90s/it]

,h 21,cp 20,y 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.407948,0.626381,0.394269,0.294632,0.083065,0.553090,0.754532,0.355997,0.729094,0.930069,...,0.286079,0.823972,0.221217,0.888723,0.115813,0.344458,0.218337,0.189410,0.196931,fail
1,0.709917,1.093722,0.405557,0.493862,0.145562,0.786481,0.988383,0.461714,0.933420,1.168297,...,0.252033,0.992196,0.276449,1.425979,0.160965,0.480596,0.301365,0.268916,0.314979,fail
2,0.330729,0.493935,0.333284,0.223602,0.067774,0.526807,0.779993,0.377843,0.639763,0.887403,...,0.342676,0.785298,0.233854,0.621883,0.107996,0.296117,0.176911,0.168396,0.134635,fail
3,0.632848,0.997334,0.408999,0.446098,0.134447,0.781959,1.053930,0.503105,0.899332,1.172587,...,0.270581,1.008572,0.299344,1.296269,0.148489,0.447293,0.279472,0.265306,0.283067,fail
4,0.517086,0.816499,0.360436,0.362220,0.110278,0.648234,0.838623,0.413151,0.777921,0.996395,...,0.278322,0.869297,0.263717,1.094915,0.133682,0.415699,0.241506,0.226424,0.236435,fail
5,0.634246,0.944557,0.355015,0.403629,0.136322,0.712856,0.906611,0.444943,0.835936,1.137472,...,0.358358,0.990155,0.265528,1.200200,0.147926,0.479049,0.266260,0.245676,0.271102,fail
6,0.539646,0.760410,0.457727,0.368660,0.110160,0.702943,0.922649,0.459424,0.919137,1.177230,...,0.327270,1.017916,0.288329,1.171117,0.148796,0.501684,0.285239,0.245979,0.262614,fail
7,0.693019,1.004670,0.551358,0.480339,0.138911,0.808781,1.056824,0.507771,1.066069,1.294855,...,0.310999,1.101393,0.316667,1.420523,0.174684,0.535364,0.322653,0.277373,0.312842,fail
8,0.587340,0.859968,0.525324,0.398955,0.115128,0.795480,1.037458,0.499606,1.018574,1.255695,...,0.341894,1.084052,0.318857,1.220150,0.161341,0.504514,0.302997,0.266898,0.271631,fail
9,0.497068,0.681392,0.451146,0.351226,0.096000,0.634064,0.873543,0.401270,0.853111,1.063008,...,0.300932,0.945718,0.254730,1.036177,0.135410,0.401133,0.260063,0.219487,0.235343,fail
10,0.606401,0.968190,0.279262,0.435290,0.132974,0.744059,0.991858,0.468631,0.773814,0.980669,...,0.158426,0.795081,0.272137,1.243986,0.123887,0.425609,0.249223,0.254041,0.276991,pass
11,0.428218,0.674195,0.275498,0.289439,0.087119,0.552135,0.702586,0.353997,0.635307,0.826424,...,0.299294,0.750333,0.224983,0.880631,0.117703,0.323743,0.196928,0.187536,0.189314,pass
12,0.587092,0.869675,0.347121,0.439117,0.124365,0.653628,0.925083,0.427178,0.793184,1.040800,...,0.242411,0.897106,0.263164,1.233611,0.136166,0.437391,0.263729,0.238861,0.273585,pass
13,0.753678,1.135759,0.246959,0.490146,0.155691,0.742365,0.912653,0.447975,0.764912,0.957561,...,0.224798,0.825272,0.276561,1.365120,0.150062,0.456322,0.251665,0.259822,0.297405,pass
14,0.370790,0.549541,0.202241,0.260229,0.080592,0.456824,0.615962,0.298192,0.507351,0.675453,...,0.231877,0.612789,0.179363,0.710921,0.095060,0.278255,0.157552,0.156704,0.156466,pass
15,0.471663,0.708671,0.364613,0.324841,0.097502,0.615283,0.801197,0.396562,0.751227,0.931420,...,0.252532,0.835573,0.259313,0.995406,0.126444,0.414791,0.239269,0.220238,0.223655,pass
16,0.313944,0.469088,0.209366,0.199598,0.062641,0.447552,0.551308,0.281437,0.504367,0.649075,...,0.222500,0.564489,0.170590,0.620491,0.088953,0.254578,0.148483,0.140129,0.136357,pass
17,0.527304,0.823411,0.305281,0.370571,0.108651,0.667752,0.820205,0.404258,0.757238,0.917672,...,0.175772,0.784031,0.247473,1.137998,0.123738,0.419571,0.249624,0.234640,0.257484,pass
18,0.468584,0.690282,0.365425,0.326581,0.098882,0.642295,0.864905,0.421698,0.775255,0.972194,...,0.236066,0.800527,0.250184,1.007920,0.131952,0.385545,0.230674,0.212802,0.219301,pass
19,0.447761,0.686084,0.231774,0.315738,0.093624,0.507795,0.682113,0.325424,0.572238,0.728118,...,0.132803,0.596729,0.192255,0.890345,0.098908,0.305347,0.183692,0.177142,0.195402,pass

BARINEL SCORES

,y 19,swap 8,cp 7,cp 12,h 13,h 2,cp 9,x 4,h 11,swap 10,...,cp 15,cp 14,h 16,h 1,h 0,cp 5,h 21,cp 18,cp 20,cp 17
sum,0.600102,0.585087,0.563132,0.560813,0.559245,0.550145,0.548902,0.546087,0.543781,0.543568,...,0.539363,0.536331,0.535477,0.532761,0.530937,0.530041,0.527287,0.525545,0.522202,0.521931

TARANTULA SCORES

,y 19,swap 8,cp 7,cp 12,h 13,h 2,cp 9,x 4,h 11,swap 10,...,cp 15,cp 14,h 16,h 1,h 0,cp 5,h 21,cp 18,cp 20,cp 17
sum,0.600102,0.585087,0.563132,0.560813,0.559245,0.550145,0.548902,0.546087,0.543781,0.543568,...,0.539363,0.536331,0.535477,0.532761,0.530937,0.530041,0.527287,0.525545,0.522202,0.521931

ERROR GATE LOCATION:
19
Now evolving the following mutant:  AddGate_z_inGap_10_.qasm

100%|██████████| 10/10 [00:41<00:00,  4.19s/it]
100%|██████████| 10/10 [00:38<00:00,  3.88s/it]

,h 21,cp 20,cp 19,cp 18,h 17,z 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.467475,0.715202,0.325261,0.101000,0.649572,0.327037,0.835480,0.412195,0.767123,0.970057,...,0.343203,0.859108,0.256641,0.914878,0.131287,0.403734,0.224206,0.215252,0.204298,fail
1,0.427859,0.615611,0.294857,0.089244,0.558748,0.271739,0.695313,0.339446,0.670356,0.803363,...,0.212815,0.700774,0.212514,0.883896,0.107254,0.365349,0.205477,0.189431,0.202872,fail
2,0.497004,0.698646,0.318936,0.096245,0.616054,0.313463,0.784085,0.375502,0.801623,0.971732,...,0.274761,0.866690,0.249475,1.000124,0.126740,0.410201,0.244256,0.212334,0.225761,fail
3,0.530045,0.790344,0.372668,0.109117,0.721262,0.370222,0.995152,0.471149,0.886166,1.126029,...,0.275015,0.940396,0.286431,1.086401,0.144159,0.420990,0.254424,0.235476,0.236941,fail
4,0.569909,0.819174,0.389713,0.118340,0.679591,0.339202,0.894844,0.429136,0.844023,1.091207,...,0.261617,0.901255,0.248037,1.124740,0.134975,0.433923,0.261961,0.232149,0.257619,fail
5,0.711259,1.047907,0.481229,0.150348,0.801227,0.392815,1.054334,0.518368,0.949029,1.222723,...,0.297900,1.035074,0.319385,1.422229,0.168018,0.535889,0.300981,0.282412,0.312870,fail
6,0.686025,1.025422,0.442940,0.143445,0.740827,0.347411,0.928823,0.456993,0.846009,1.072319,...,0.190886,0.876150,0.267832,1.340708,0.153565,0.475613,0.272749,0.255342,0.298333,fail
7,0.542151,0.769154,0.362841,0.103442,0.695312,0.378327,0.961064,0.465013,0.783236,0.986213,...,0.241175,0.845812,0.292805,1.034423,0.135705,0.402543,0.234238,0.230306,0.227994,fail
8,0.621134,0.946111,0.432460,0.124296,0.768936,0.375655,1.023192,0.474803,0.923709,1.148948,...,0.287302,1.000412,0.294944,1.233153,0.144987,0.463696,0.281184,0.257999,0.272400,fail
9,0.592667,0.881146,0.398396,0.125093,0.662186,0.343131,0.896675,0.438479,0.818455,1.149457,...,0.402791,1.009843,0.268199,1.181074,0.147254,0.426604,0.259380,0.234607,0.255721,fail
10,0.350570,0.510863,0.221018,0.070333,0.363271,0.190904,0.499310,0.237230,0.525976,0.744677,...,0.295793,0.672233,0.150787,0.699325,0.100295,0.264409,0.162121,0.130288,0.149070,pass
11,0.451552,0.651699,0.320630,0.090410,0.634866,0.344308,0.870329,0.417697,0.750406,0.962514,...,0.303118,0.858410,0.258406,0.918334,0.129443,0.363316,0.226058,0.208169,0.201224,pass
12,0.433137,0.656896,0.276519,0.088446,0.444286,0.220891,0.590791,0.296018,0.563833,0.765898,...,0.197331,0.644280,0.180088,0.837489,0.105833,0.308560,0.181576,0.160519,0.182196,pass
13,0.477665,0.731730,0.327385,0.103304,0.682952,0.353265,0.888575,0.452903,0.751139,1.006191,...,0.369131,0.867723,0.281016,0.912599,0.140790,0.427333,0.218337,0.224180,0.201442,pass
14,0.385893,0.568637,0.265876,0.079085,0.501697,0.244583,0.628804,0.310348,0.578505,0.729856,...,0.192583,0.623197,0.186866,0.778494,0.100949,0.306432,0.179337,0.167713,0.174300,pass
15,0.684784,1.020825,0.452889,0.142984,0.705973,0.338464,0.898760,0.451319,0.778460,1.005698,...,0.216015,0.846513,0.274804,1.322815,0.146990,0.453443,0.258299,0.256623,0.291630,pass
16,0.610266,0.899376,0.403677,0.125932,0.712507,0.351203,0.914014,0.450757,0.821616,1.034018,...,0.233694,0.859500,0.270014,1.181026,0.137026,0.444285,0.256050,0.244147,0.264772,pass
17,0.278090,0.388243,0.198025,0.055023,0.519687,0.297376,0.751794,0.348846,0.631116,0.796059,...,0.245443,0.699707,0.224212,0.593502,0.092973,0.306013,0.172620,0.163751,0.135166,pass
18,0.290407,0.447953,0.191044,0.065357,0.370676,0.195934,0.493195,0.250597,0.380671,0.563466,...,0.201886,0.458312,0.145674,0.516652,0.075417,0.222412,0.118528,0.123587,0.113573,pass
19,0.433773,0.657352,0.287829,0.093992,0.487600,0.258424,0.691863,0.324553,0.515709,0.735295,...,0.256013,0.651012,0.198074,0.800703,0.106078,0.291509,0.161926,0.165162,0.169707,pass

BARINEL SCORES

,h 0,h 13,h 2,cp 5,cp 19,h 21,h 3,h 1,cp 20,h 17,...,cp 7,cp 15,h 11,cp 6,cp 14,z 16,x 4,cp 9,swap 10,swap 8
sum,0.569866,0.568289,0.567506,0.567248,0.564635,0.56221,0.561532,0.559813,0.5598,0.559681,...,0.557184,0.556501,0.555681,0.554079,0.553073,0.553055,0.551023,0.547131,0.54643,0.526088

TARANTULA SCORES

,h 0,h 13,h 2,cp 5,cp 19,h 21,h 3,h 1,cp 20,h 17,...,cp 7,cp 15,h 11,cp 6,cp 14,z 16,x 4,cp 9,swap 10,swap 8
sum,0.569866,0.568289,0.567506,0.567248,0.564635,0.56221,0.561532,0.559813,0.5598,0.559681,...,0.557184,0.556501,0.555681,0.554079,0.553073,0.553055,0.551023,0.547131,0.54643,0.526088

ERROR GATE LOCATION:
16
Now evolving the following mutant:  AddGate_s_inGap_11_.qasm

100%|██████████| 10/10 [00:41<00:00,  4.11s/it]
100%|██████████| 10/10 [00:41<00:00,  4.11s/it]

,h 21,sdg 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.588131,0.588131,0.891765,0.413083,0.123341,0.722107,0.960888,0.452233,0.838782,1.034104,...,0.285410,0.944891,0.298445,1.223428,0.145530,0.500438,0.271351,0.264637,0.273730,fail
1,0.471389,0.471389,0.733038,0.343552,0.097156,0.585945,0.737427,0.336781,0.738970,0.895977,...,0.263651,0.789379,0.217189,0.994903,0.122762,0.364608,0.222657,0.198300,0.214853,fail
2,0.486362,0.486362,0.765515,0.317742,0.105530,0.637189,0.895245,0.426144,0.727117,1.009884,...,0.317747,0.868010,0.257226,0.937816,0.134906,0.392828,0.217854,0.214703,0.204699,fail
3,0.651360,0.651360,1.004394,0.462783,0.141000,0.736425,0.982640,0.475883,0.837875,1.119168,...,0.303127,0.957048,0.288125,1.314071,0.156254,0.475918,0.272878,0.268248,0.289038,fail
4,0.535724,0.535724,0.793534,0.386578,0.107686,0.708778,0.967975,0.477967,0.877748,1.183151,...,0.381839,1.017354,0.291155,1.115655,0.150101,0.412585,0.263023,0.235849,0.238424,fail
5,0.611683,0.611683,0.854242,0.443065,0.119992,0.669116,0.893931,0.414723,0.849186,1.025509,...,0.250394,0.922313,0.269132,1.239561,0.144207,0.456349,0.276035,0.244326,0.278930,fail
6,0.510876,0.510876,0.693756,0.325200,0.101409,0.641684,0.864379,0.405723,0.887034,1.138691,...,0.380928,1.018524,0.263881,1.021930,0.147594,0.468699,0.264281,0.221689,0.231126,fail
7,0.594398,0.594398,0.881489,0.411727,0.120645,0.763281,1.013522,0.500610,0.964448,1.250898,...,0.420126,1.121917,0.328181,1.256425,0.167077,0.497872,0.297800,0.270322,0.272358,fail
8,0.782147,0.782147,1.164308,0.543563,0.159877,0.855770,1.101256,0.504589,1.100795,1.342395,...,0.320963,1.176765,0.323204,1.640766,0.177178,0.581022,0.351854,0.306605,0.359042,fail
9,0.646108,0.646108,0.941316,0.446952,0.134355,0.697288,0.906480,0.409342,0.860532,1.048533,...,0.272541,0.924722,0.259486,1.247772,0.149204,0.468950,0.267701,0.249131,0.279798,fail
10,0.525083,0.525083,0.794747,0.355809,0.111189,0.612189,0.797172,0.400142,0.687051,0.893954,...,0.274411,0.775200,0.252068,1.028221,0.130976,0.377303,0.214494,0.215568,0.222272,pass
11,0.375433,0.375433,0.616270,0.250335,0.086292,0.454143,0.587770,0.287587,0.394431,0.532313,...,0.136923,0.450112,0.166965,0.731326,0.091126,0.233253,0.124979,0.150328,0.149933,pass
12,0.283289,0.283289,0.393016,0.170116,0.053977,0.321008,0.385029,0.205558,0.410893,0.510493,...,0.141674,0.447719,0.128060,0.581569,0.080169,0.228710,0.131690,0.112278,0.128174,pass
13,0.436800,0.436800,0.641530,0.293551,0.090340,0.500217,0.646004,0.329818,0.695833,0.937832,...,0.327187,0.830169,0.209101,0.945299,0.119430,0.369209,0.223905,0.185926,0.207913,pass
14,0.430532,0.430532,0.704541,0.318058,0.089070,0.490790,0.623500,0.285722,0.540806,0.655414,...,0.147706,0.571569,0.176515,0.894610,0.096379,0.268257,0.172705,0.169246,0.188962,pass
15,0.634649,0.634649,0.927861,0.399869,0.138170,0.715952,0.873260,0.455079,0.793029,1.024009,...,0.297051,0.920329,0.288742,1.270571,0.151039,0.546553,0.274643,0.270153,0.290400,pass
16,0.304590,0.304590,0.474428,0.217347,0.063108,0.444759,0.601014,0.307412,0.495190,0.679738,...,0.251029,0.592706,0.183204,0.632323,0.091399,0.236172,0.146633,0.140772,0.130131,pass
17,0.496776,0.496776,0.714718,0.336292,0.105850,0.585118,0.833244,0.404825,0.660445,0.883862,...,0.221086,0.750730,0.246207,0.952612,0.120813,0.377048,0.212387,0.210002,0.211468,pass
18,0.526747,0.526747,0.812074,0.352607,0.106157,0.634911,0.804141,0.404440,0.712496,0.942696,...,0.314379,0.847348,0.251805,1.056659,0.133257,0.375217,0.225218,0.214948,0.222520,pass
19,0.663620,0.663620,0.989118,0.443991,0.136014,0.679152,0.866081,0.432789,0.847255,1.107441,...,0.267610,0.957565,0.263615,1.343328,0.154588,0.467835,0.283474,0.250112,0.293902,pass

BARINEL SCORES

,h 13,cp 7,cp 12,h 2,swap 8,cp 15,h 3,h 11,cp 18,h 0,...,h 1,x 4,cp 9,cp 5,h 21,sdg 20,cp 14,cp 17,cp 19,swap 10
sum,0.581939,0.57692,0.574952,0.573725,0.573323,0.570575,0.570363,0.566843,0.566112,0.563605,...,0.563107,0.561118,0.561107,0.559635,0.556873,0.556873,0.556245,0.552672,0.552403,0.534155

TARANTULA SCORES

,h 13,cp 7,cp 12,h 2,swap 8,cp 15,h 3,h 11,cp 18,h 0,...,h 1,x 4,cp 9,cp 5,h 21,sdg 20,cp 14,cp 17,cp 19,swap 10
sum,0.581939,0.57692,0.574952,0.573725,0.573323,0.570575,0.570363,0.566843,0.566112,0.563605,...,0.563107,0.561118,0.561107,0.559635,0.556873,0.556873,0.556245,0.552672,0.552403,0.534155

ERROR GATE LOCATION:
20
Now evolving the following mutant:  AddGate_x_inGap_12_.qasm

100%|██████████| 10/10 [00:39<00:00,  3.95s/it]
100%|██████████| 10/10 [00:37<00:00,  3.76s/it]

,h 21,cp 20,cp 19,x 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.510577,0.811937,0.367436,0.365951,0.111690,0.711232,0.986288,0.477296,0.864194,1.136099,...,0.395453,1.006661,0.300732,1.063131,0.148674,0.436114,0.249809,0.236857,0.224717,fail
1,0.547783,0.836118,0.366555,0.441406,0.116890,0.765354,1.012440,0.513619,0.842981,1.137883,...,0.355363,0.984489,0.315274,1.145043,0.151056,0.474572,0.262714,0.259760,0.251203,fail
2,0.498328,0.729928,0.361466,0.364735,0.102169,0.645773,0.872665,0.416193,0.825107,1.024251,...,0.294042,0.852425,0.257674,1.000783,0.129134,0.398174,0.237210,0.217401,0.221068,fail
3,0.494781,0.732094,0.310883,0.433619,0.102148,0.616043,0.768935,0.379470,0.851317,1.086302,...,0.319345,0.950169,0.232623,1.063421,0.143105,0.450253,0.257326,0.207715,0.236934,fail
4,0.623462,0.958988,0.419419,0.522241,0.139242,0.808115,1.035486,0.535935,0.886303,1.171258,...,0.317926,1.002233,0.322713,1.284580,0.161168,0.551796,0.289383,0.287559,0.290594,fail
5,0.588317,0.840492,0.388797,0.473219,0.124590,0.735215,0.952475,0.456677,0.832194,1.039531,...,0.280917,0.921233,0.288928,1.134832,0.146109,0.497927,0.261976,0.257380,0.259925,fail
6,0.509332,0.749168,0.368862,0.398878,0.103567,0.755835,0.989653,0.474177,0.917550,1.127307,...,0.349830,0.992172,0.300917,1.053945,0.139833,0.472856,0.269409,0.251785,0.242129,fail
7,0.635102,0.926717,0.438421,0.386499,0.127960,0.678305,0.882120,0.428586,0.839794,1.046400,...,0.265814,0.921556,0.268640,1.240848,0.145492,0.456834,0.268233,0.245919,0.279414,fail
8,0.536813,0.811533,0.379094,0.370397,0.109478,0.688532,0.945480,0.456568,0.803922,1.027336,...,0.250475,0.812517,0.275290,1.011412,0.129918,0.389337,0.226722,0.225459,0.219159,fail
9,0.688921,1.012158,0.457688,0.390939,0.142741,0.732389,0.965549,0.476606,0.890042,1.149758,...,0.297031,0.996582,0.303783,1.347006,0.156240,0.498927,0.287314,0.269556,0.299326,fail
10,0.370179,0.525268,0.263856,0.292158,0.072826,0.542119,0.751204,0.357551,0.792383,1.014244,...,0.294848,0.865607,0.218151,0.848647,0.129282,0.354907,0.230352,0.179564,0.187117,pass
11,0.266350,0.372797,0.174557,0.183999,0.052146,0.381413,0.525037,0.257476,0.461067,0.639007,...,0.229101,0.550358,0.158524,0.500315,0.076479,0.216387,0.135294,0.124697,0.113011,pass
12,0.428950,0.619961,0.328662,0.269193,0.087231,0.547117,0.835129,0.373322,0.647336,0.853175,...,0.285054,0.759485,0.226809,0.806090,0.115718,0.277087,0.178786,0.177824,0.169184,pass
13,0.414267,0.627067,0.255597,0.367697,0.088240,0.491689,0.586861,0.298285,0.621373,0.812481,...,0.272144,0.720583,0.187708,0.837005,0.112227,0.361292,0.193106,0.173548,0.188959,pass
14,0.650407,0.946838,0.445273,0.336831,0.128012,0.708092,0.881755,0.414357,0.837436,0.995875,...,0.256369,0.887693,0.264872,1.281067,0.141734,0.427215,0.263686,0.244191,0.281760,pass
15,0.255051,0.375274,0.159739,0.202252,0.051179,0.374034,0.488170,0.244450,0.452869,0.591196,...,0.182899,0.500763,0.151619,0.519401,0.075180,0.222612,0.131826,0.118696,0.112819,pass
16,0.407343,0.558422,0.244812,0.329798,0.082458,0.500560,0.681522,0.322006,0.600353,0.783992,...,0.217199,0.647605,0.193209,0.715672,0.105725,0.315214,0.169430,0.160661,0.162097,pass
17,0.410596,0.627274,0.264732,0.302067,0.085279,0.571844,0.709049,0.346136,0.617069,0.753075,...,0.234767,0.662447,0.218218,0.797590,0.101627,0.342519,0.184917,0.188207,0.180597,pass
18,0.632094,0.937560,0.409767,0.423343,0.125232,0.731267,0.895846,0.460401,0.869113,1.109773,...,0.271390,0.979370,0.291271,1.315324,0.149697,0.512136,0.293841,0.263637,0.295823,pass
19,0.577954,0.891378,0.393746,0.444927,0.129484,0.758092,0.974719,0.477727,0.815335,1.051046,...,0.254496,0.873721,0.291438,1.213023,0.144753,0.485552,0.261323,0.261332,0.268974,pass

BARINEL SCORES

,h 3,x 18,cp 19,cp 17,cp 6,h 11,h 1,cp 14,cp 20,h 0,...,cp 9,h 2,h 21,h 13,h 16,swap 10,cp 12,cp 7,x 4,swap 8
sum,0.568282,0.568192,0.567498,0.566838,0.565579,0.565475,0.56515,0.565106,0.564713,0.562893,...,0.56149,0.56099,0.560728,0.560227,0.560055,0.559946,0.559904,0.55899,0.557297,0.555821

TARANTULA SCORES

,h 3,x 18,cp 19,cp 17,cp 6,h 11,h 1,cp 14,cp 20,h 0,...,cp 9,h 2,h 21,h 13,h 16,swap 10,cp 12,cp 7,x 4,swap 8
sum,0.568282,0.568192,0.567498,0.566838,0.565579,0.565475,0.56515,0.565106,0.564713,0.562893,...,0.56149,0.56099,0.560728,0.560227,0.560055,0.559946,0.559904,0.55899,0.557297,0.555821

ERROR GATE LOCATION:
18
Now evolving the following mutant:  AddGate_x_inGap_15_.qasm

100%|██████████| 10/10 [00:43<00:00,  4.34s/it]
100%|██████████| 10/10 [00:38<00:00,  3.86s/it]

,x 21,h 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.377588,0.533990,0.791328,0.367068,0.110013,0.640338,0.856447,0.406675,0.707903,0.918162,...,0.255515,0.782053,0.247177,0.975598,0.131181,0.347070,0.209286,0.212177,0.211557,fail
1,0.414917,0.586781,0.868228,0.407729,0.123662,0.738118,0.946890,0.442855,0.951808,1.192143,...,0.333836,1.032747,0.269490,1.220186,0.154603,0.513997,0.296901,0.253772,0.278753,fail
2,0.463152,0.654995,0.992510,0.430996,0.136804,0.687471,0.880762,0.428210,0.843790,1.095750,...,0.305211,0.958158,0.271811,1.317957,0.146752,0.495181,0.277833,0.253913,0.291655,fail
3,0.540081,0.763790,1.175110,0.546066,0.162219,0.853555,1.149506,0.541222,0.919455,1.166130,...,0.196306,0.952425,0.315413,1.513693,0.162801,0.480475,0.292802,0.291037,0.329161,fail
4,0.415077,0.587008,0.836290,0.363836,0.118691,0.655912,0.884555,0.424468,0.748964,0.971774,...,0.262160,0.846263,0.258660,1.063477,0.135732,0.402339,0.227489,0.218462,0.234664,fail
5,0.554519,0.784209,1.100662,0.538926,0.156251,0.796025,1.018642,0.467752,1.043144,1.252946,...,0.307200,1.126798,0.292148,1.542315,0.170720,0.556545,0.339392,0.291719,0.351956,fail
6,0.375840,0.531517,0.791257,0.371432,0.105799,0.675151,0.875456,0.399826,0.830021,0.990735,...,0.245624,0.879966,0.250067,1.108382,0.135341,0.413195,0.251673,0.223378,0.244915,fail
7,0.474639,0.671240,0.981126,0.444913,0.139101,0.692634,0.838481,0.424768,0.911901,1.154375,...,0.297621,1.007831,0.258708,1.384801,0.154291,0.514957,0.301886,0.257469,0.315460,fail
8,0.429483,0.607381,0.890147,0.431830,0.126329,0.768174,1.034198,0.498249,0.921570,1.189158,...,0.351696,1.066298,0.299071,1.234495,0.156569,0.457304,0.282370,0.255203,0.271261,fail
9,0.545825,0.771914,1.172793,0.493366,0.167584,0.850127,1.035967,0.547571,0.977154,1.247162,...,0.311975,1.061702,0.337905,1.562600,0.175408,0.602681,0.321671,0.313058,0.348587,fail
10,0.476190,0.673435,0.996859,0.452282,0.140294,0.785648,1.039960,0.485856,0.896663,1.123165,...,0.224205,0.967498,0.290601,1.358705,0.156065,0.477003,0.287034,0.267973,0.301443,pass
11,0.299697,0.423835,0.678949,0.257890,0.091225,0.612030,0.781487,0.378445,0.585871,0.771092,...,0.179640,0.649131,0.221136,0.831599,0.114425,0.343709,0.183202,0.193612,0.184206,pass
12,0.555438,0.785509,1.181345,0.549318,0.153954,0.872859,1.077276,0.509315,1.094947,1.318877,...,0.269007,1.142914,0.313544,1.665916,0.185196,0.569812,0.356719,0.307010,0.370071,pass
13,0.294413,0.416362,0.628696,0.302668,0.082312,0.491189,0.626266,0.289651,0.628281,0.822931,...,0.285286,0.735504,0.174400,0.829942,0.109054,0.281220,0.190430,0.159579,0.179516,pass
14,0.377077,0.533267,0.775489,0.362122,0.109534,0.772404,1.016100,0.504285,0.904002,1.131805,...,0.296385,0.985239,0.307071,1.107855,0.143147,0.482611,0.275214,0.261082,0.256625,pass
15,0.307429,0.434770,0.643827,0.299449,0.094051,0.640582,0.882313,0.429399,0.716788,0.911948,...,0.234108,0.767416,0.261305,0.870934,0.117300,0.392826,0.210642,0.213351,0.196271,pass
16,0.283780,0.401325,0.565690,0.250248,0.085255,0.528797,0.649872,0.346800,0.664860,0.875534,...,0.238094,0.740933,0.209540,0.856957,0.111745,0.397582,0.217462,0.184550,0.198405,pass
17,0.273315,0.386525,0.574284,0.292515,0.079280,0.580306,0.756457,0.365089,0.790378,0.938578,...,0.245997,0.802291,0.228521,0.883607,0.114830,0.385664,0.232192,0.198041,0.202964,pass
18,0.288381,0.407833,0.603830,0.269868,0.081216,0.514208,0.649480,0.329969,0.675717,0.883146,...,0.285677,0.743879,0.197313,0.845069,0.123093,0.342129,0.202749,0.169805,0.182850,pass
19,0.459865,0.650347,0.955605,0.451063,0.135203,0.774154,1.053063,0.511905,0.923396,1.200456,...,0.312803,1.020684,0.306077,1.295788,0.162086,0.488186,0.283553,0.263586,0.282905,pass

BARINEL SCORES

,cp 17,x 21,h 20,cp 19,cp 18,cp 5,h 0,swap 10,h 1,h 3,...,cp 7,h 11,h 13,cp 12,h 16,cp 6,cp 15,swap 8,cp 14,cp 9
sum,0.561308,0.559435,0.559435,0.557977,0.557635,0.550642,0.549941,0.540558,0.536711,0.534826,...,0.531712,0.529891,0.529122,0.52838,0.528189,0.527396,0.527381,0.527209,0.524672,0.521932

TARANTULA SCORES

,cp 17,x 21,h 20,cp 19,cp 18,cp 5,h 0,swap 10,h 1,h 3,...,cp 7,h 11,h 13,cp 12,h 16,cp 6,cp 15,swap 8,cp 14,cp 9
sum,0.561308,0.559435,0.559435,0.557977,0.557635,0.550642,0.549941,0.540558,0.536711,0.534826,...,0.531712,0.529891,0.529122,0.52838,0.528189,0.527396,0.527381,0.527209,0.524672,0.521932

ERROR GATE LOCATION:
21
Now evolving the following mutant:  AddGate_cx_inGap_6_.qasm

100%|██████████| 10/10 [00:42<00:00,  4.23s/it]
100%|██████████| 10/10 [00:39<00:00,  3.96s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.799434,1.206277,0.582244,0.168037,0.803926,1.029828,0.501409,1.027814,1.309275,1.154485,...,0.279835,1.190697,0.334391,2.025657,0.184747,0.690747,0.358763,0.325074,0.430963,fail
1,0.611078,0.903132,0.433151,0.133590,0.735097,0.972971,0.474053,0.854250,1.135640,1.041601,...,0.268657,0.956784,0.278462,1.505310,0.146896,0.512842,0.272326,0.257680,0.320254,fail
2,0.625859,0.946823,0.449139,0.131794,0.770650,1.017578,0.486319,0.897800,1.128523,1.024173,...,0.207693,0.940208,0.284002,1.544645,0.154347,0.540452,0.289788,0.266107,0.329843,fail
3,0.589718,0.864205,0.388815,0.120936,0.697736,0.878941,0.432730,0.858746,1.102973,1.057749,...,0.263024,0.913734,0.257005,1.388083,0.145717,0.494995,0.262117,0.235794,0.297596,fail
4,0.680382,1.036196,0.479269,0.141718,0.691746,0.834890,0.397804,0.835365,1.024324,1.031145,...,0.235727,0.942928,0.275052,1.653694,0.154282,0.568089,0.291098,0.269394,0.349346,fail
5,0.419467,0.610515,0.286708,0.090760,0.516255,0.686009,0.329131,0.651285,0.858617,0.851720,...,0.197724,0.671310,0.192134,0.996643,0.103911,0.356964,0.199229,0.178139,0.213996,fail
6,0.548358,0.833214,0.403337,0.118930,0.695314,0.940729,0.456910,0.795601,1.024495,0.903924,...,0.205592,0.843555,0.266421,1.421658,0.135236,0.482069,0.246833,0.238801,0.297538,fail
7,0.794256,1.191800,0.535423,0.164326,0.811939,1.014214,0.492870,1.044761,1.318656,1.199967,...,0.258987,1.145023,0.321572,1.954424,0.179193,0.659706,0.353317,0.312150,0.413198,fail
8,0.629072,0.938570,0.434793,0.135412,0.671192,0.932019,0.451581,0.778534,1.061513,0.941985,...,0.235004,0.855790,0.262945,1.480164,0.149048,0.466379,0.241952,0.237050,0.311794,fail
9,0.632553,0.919976,0.436817,0.126118,0.648781,0.794009,0.385761,0.905372,1.124341,1.086857,...,0.244204,0.971879,0.256655,1.558656,0.147301,0.549300,0.303459,0.250818,0.336572,fail
10,0.333421,0.473317,0.234273,0.070351,0.521047,0.754175,0.365896,0.697102,0.946369,0.834916,...,0.212514,0.718920,0.195835,0.919829,0.102466,0.364591,0.198864,0.169578,0.201741,pass
11,0.251519,0.347379,0.171385,0.049221,0.364545,0.511581,0.239733,0.547078,0.720821,0.603985,...,0.175488,0.526513,0.127005,0.623536,0.073810,0.253500,0.145331,0.109876,0.135312,pass
12,0.349607,0.545648,0.262388,0.068940,0.586221,0.814843,0.368436,0.646428,0.764320,0.756247,...,0.172323,0.605236,0.212334,0.884368,0.105237,0.373899,0.170381,0.175032,0.185245,pass
13,0.460431,0.694457,0.318112,0.093272,0.691532,0.887948,0.449217,0.929274,1.239014,1.071252,...,0.308691,0.932248,0.248515,1.174514,0.132284,0.485965,0.265345,0.220309,0.251727,pass
14,0.361282,0.520813,0.223388,0.076756,0.545188,0.719272,0.347900,0.631054,0.810381,0.858634,...,0.166434,0.566045,0.171368,0.754758,0.092791,0.295687,0.168422,0.153962,0.166339,pass
15,0.662191,1.044879,0.467341,0.143785,0.803503,1.032952,0.526676,0.909382,1.211233,1.102592,...,0.222635,0.984306,0.307504,1.727856,0.166311,0.587001,0.305068,0.287496,0.365300,pass
16,0.551927,0.811484,0.364396,0.112694,0.703548,0.909313,0.429386,0.829098,1.002672,1.026103,...,0.190337,0.854284,0.262346,1.352393,0.129729,0.493145,0.264600,0.241996,0.288129,pass
17,0.331714,0.506657,0.230331,0.071930,0.469334,0.630410,0.309073,0.530425,0.703941,0.662595,...,0.167890,0.551229,0.171712,0.810630,0.089318,0.305284,0.158764,0.152183,0.173676,pass
18,0.461427,0.718484,0.306196,0.103539,0.630008,0.788404,0.413075,0.718621,0.944336,0.959593,...,0.193640,0.737808,0.225778,1.160878,0.115993,0.410482,0.227976,0.210120,0.250016,pass
19,0.560295,0.914779,0.427740,0.116778,0.675155,0.898255,0.423599,0.801813,1.063864,0.848851,...,0.264791,0.881976,0.273332,1.458112,0.140874,0.525584,0.245400,0.244218,0.297114,pass

BARINEL SCORES

,cp 19,cp 18,h 21,cp 20,cx 10,cp 5,h 0,h 2,h 1,x 4,...,cp 9,cp 6,h 14,h 12,cp 13,h 17,swap 11,swap 8,cp 16,cp 15
sum,0.59577,0.594769,0.59416,0.589615,0.589306,0.588311,0.587834,0.56729,0.566828,0.566402,...,0.560318,0.554109,0.544345,0.541245,0.541019,0.540381,0.539253,0.535975,0.533846,0.532336

TARANTULA SCORES

,cp 19,cp 18,h 21,cp 20,cx 10,cp 5,h 0,h 2,h 1,x 4,...,cp 9,cp 6,h 14,h 12,cp 13,h 17,swap 11,swap 8,cp 16,cp 15
sum,0.59577,0.594769,0.59416,0.589615,0.589306,0.588311,0.587834,0.56729,0.566828,0.566402,...,0.560318,0.554109,0.544345,0.541245,0.541019,0.540381,0.539253,0.535975,0.533846,0.532336

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_cz_inGap_11_.qasm

100%|██████████| 10/10 [00:48<00:00,  4.83s/it]
100%|██████████| 10/10 [00:46<00:00,  4.61s/it]

,h 21,cz 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.563240,1.513582,1.014559,0.436773,0.132402,0.693086,0.871465,0.392939,0.691228,0.839197,...,0.197593,0.731426,0.235625,1.147038,0.123652,0.402778,0.222766,0.225589,0.251341,fail
1,0.574731,1.543390,0.938849,0.526749,0.136695,0.672017,0.988903,0.429974,0.836986,1.067537,...,0.219465,0.854012,0.246878,1.247142,0.133004,0.396239,0.257945,0.229558,0.272381,fail
2,0.709599,1.888093,1.229519,0.555578,0.165570,0.809667,1.054757,0.489903,0.845865,1.089235,...,0.223651,0.926531,0.292643,1.489106,0.154390,0.494684,0.281976,0.280256,0.323757,fail
3,0.552259,1.528234,1.060616,0.436853,0.140313,0.695745,0.813429,0.390108,0.752910,0.934332,...,0.227430,0.768971,0.225755,1.198066,0.126749,0.443037,0.240681,0.228463,0.268578,fail
4,0.614812,1.659348,0.986866,0.522230,0.145292,0.712918,0.965448,0.435935,0.848192,1.047856,...,0.249749,0.868547,0.253429,1.289909,0.139491,0.442307,0.264284,0.241988,0.284128,fail
5,0.705176,1.926089,1.256110,0.557085,0.175285,0.803750,1.019636,0.493652,0.958739,1.238974,...,0.248823,0.975236,0.276126,1.508826,0.154722,0.507665,0.302974,0.272489,0.335543,fail
6,0.568307,1.520733,0.881758,0.421828,0.119510,0.694728,0.887023,0.413083,0.821227,1.032429,...,0.267357,0.885190,0.252295,1.187619,0.142796,0.434299,0.258561,0.229356,0.259317,fail
7,0.593063,1.586473,1.068661,0.462967,0.140751,0.659706,0.855539,0.410525,0.788882,1.033661,...,0.240130,0.855217,0.241445,1.251864,0.130922,0.397527,0.254737,0.227601,0.270738,fail
8,0.503658,1.416062,0.877487,0.422009,0.136224,0.609359,0.764993,0.377728,0.693587,0.916435,...,0.204067,0.691245,0.200742,1.059759,0.108478,0.365191,0.211790,0.197453,0.232134,fail
9,0.531588,1.493312,1.106282,0.405794,0.129199,0.663018,0.784009,0.397965,0.753084,0.981503,...,0.234850,0.792107,0.233231,1.154654,0.127534,0.398758,0.237692,0.217368,0.251531,fail
10,0.607799,1.663943,0.948161,0.487154,0.148417,0.731761,0.942293,0.446114,0.769543,0.964965,...,0.204668,0.791233,0.260163,1.282305,0.135635,0.476394,0.249499,0.250601,0.284985,pass
11,0.364711,1.040589,0.627802,0.266320,0.092144,0.429571,0.534801,0.272487,0.457617,0.598629,...,0.132057,0.473919,0.162767,0.733949,0.081327,0.281848,0.141471,0.142874,0.159648,pass
12,0.678726,1.866875,1.094348,0.501448,0.170417,0.827508,0.966103,0.506277,0.881384,1.146309,...,0.246631,0.920530,0.291907,1.465271,0.150602,0.530550,0.286829,0.279300,0.318846,pass
13,0.621387,1.622054,0.978155,0.467018,0.135066,0.751591,1.015812,0.462983,0.853528,1.046026,...,0.219990,0.893911,0.282999,1.294885,0.150726,0.470937,0.269869,0.258051,0.288766,pass
14,0.225432,0.671494,0.413775,0.184813,0.069112,0.394215,0.484452,0.255577,0.440782,0.584788,...,0.174243,0.456900,0.144750,0.516418,0.061628,0.252688,0.125501,0.122134,0.116507,pass
15,0.384822,1.024656,0.566936,0.299494,0.088027,0.414417,0.536413,0.260189,0.505572,0.660344,...,0.154508,0.550478,0.152465,0.820324,0.090869,0.265487,0.163715,0.146439,0.176657,pass
16,0.491558,1.329874,0.804609,0.403560,0.117396,0.538731,0.738896,0.359307,0.671398,0.911690,...,0.186449,0.729997,0.198350,1.067936,0.108878,0.329054,0.218071,0.189584,0.231726,pass
17,0.455640,1.340335,0.818884,0.434038,0.109816,0.608352,0.772398,0.342388,0.713960,0.829853,...,0.260630,0.680622,0.197607,0.950901,0.111989,0.330504,0.201831,0.184817,0.208797,pass
18,0.529950,1.418539,0.832809,0.416725,0.118411,0.641496,0.869243,0.400083,0.762043,0.986299,...,0.256666,0.852674,0.243614,1.131899,0.131408,0.420261,0.241807,0.221403,0.249377,pass
19,0.509947,1.362192,0.882765,0.412501,0.114924,0.574024,0.776618,0.353422,0.615192,0.808736,...,0.187820,0.681332,0.207044,1.040850,0.112320,0.305084,0.201029,0.194675,0.223051,pass

BARINEL SCORES

,cp 19,cp 18,cp 17,h 0,cp 5,h 21,swap 10,h 2,cz 20,h 13,...,h 16,x 4,h 1,cp 15,h 3,cp 14,cp 6,h 11,swap 8,cp 9
sum,0.566683,0.550737,0.549809,0.549032,0.548804,0.548508,0.547492,0.546814,0.546485,0.545004,...,0.542641,0.541653,0.541503,0.541105,0.538997,0.536308,0.534404,0.534042,0.533372,0.525171

TARANTULA SCORES

,cp 19,cp 18,cp 17,h 0,cp 5,h 21,swap 10,h 2,cz 20,h 13,...,h 16,x 4,h 1,cp 15,h 3,cp 14,cp 6,h 11,swap 8,cp 9
sum,0.566683,0.550737,0.549809,0.549032,0.548804,0.548508,0.547492,0.546814,0.546485,0.545004,...,0.542641,0.541653,0.541503,0.541105,0.538997,0.536308,0.534404,0.534042,0.533372,0.525171

ERROR GATE LOCATION:
20
Now evolving the following mutant:  AddGate_x_inGap_14_.qasm

100%|██████████| 10/10 [00:40<00:00,  4.08s/it]
100%|██████████| 9/9 [00:36<00:00,  4.03s/it]

,h 21,x 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.595746,0.554214,0.936352,0.413663,0.124672,0.831582,1.040285,0.529936,0.949156,1.213789,...,0.316953,0.995996,0.318759,1.222545,0.161657,0.498407,0.287026,0.274238,0.270074,fail
1,0.420167,0.338097,0.679370,0.325028,0.083778,0.543043,0.792701,0.326745,0.577742,0.727249,...,0.151675,0.607786,0.190752,0.817552,0.098544,0.233560,0.165486,0.165852,0.172164,fail
2,0.725098,0.446820,1.100448,0.485892,0.151666,0.825891,1.084933,0.532010,0.932226,1.185633,...,0.242035,0.996783,0.325417,1.433530,0.158881,0.535095,0.305049,0.293726,0.321238,fail
3,0.619593,0.489620,0.894453,0.447101,0.124585,0.815528,1.036206,0.496695,1.094661,1.307808,...,0.338547,1.122771,0.309192,1.344238,0.167951,0.544552,0.328995,0.272808,0.304764,fail
4,0.539928,0.317707,0.787443,0.346042,0.115958,0.608414,0.798836,0.386353,0.664566,0.898478,...,0.228828,0.734174,0.226711,1.010087,0.123348,0.377529,0.209898,0.204137,0.222401,fail
5,0.529228,0.452717,0.838498,0.373406,0.112844,0.707071,0.912124,0.440474,0.725158,0.907819,...,0.245685,0.784007,0.273216,1.063384,0.128464,0.383564,0.220330,0.232221,0.226662,fail
6,0.444352,0.397938,0.689570,0.306434,0.096472,0.618548,0.832376,0.393222,0.635215,0.821596,...,0.235666,0.700599,0.235624,0.884079,0.113095,0.351731,0.192355,0.201140,0.195948,fail
7,0.560131,0.495728,0.852818,0.366924,0.123608,0.780895,1.004315,0.514417,0.871495,1.145839,...,0.329730,0.984585,0.309818,1.164293,0.144863,0.501687,0.272422,0.265634,0.261365,fail
8,0.792673,0.438071,1.155624,0.530434,0.165229,0.859844,1.066421,0.532925,0.956870,1.179803,...,0.226133,0.991997,0.317910,1.548247,0.180493,0.552427,0.313068,0.300247,0.344665,fail
9,0.616779,0.482135,0.936556,0.436805,0.128852,0.789022,1.024300,0.475792,0.922786,1.169865,...,0.345338,1.041855,0.293342,1.278337,0.156718,0.500442,0.289200,0.264798,0.285144,fail
10,0.560624,0.304170,0.891623,0.412479,0.118430,0.591626,0.791357,0.380610,0.672474,0.890190,...,0.203203,0.746863,0.227900,1.125371,0.122965,0.342911,0.217099,0.207913,0.237903,pass
11,0.457134,0.360135,0.696566,0.327810,0.090794,0.587656,0.759326,0.354257,0.698343,0.897676,...,0.271501,0.783161,0.210261,0.909061,0.122618,0.315872,0.207910,0.190211,0.199829,pass
12,0.553340,0.319170,0.854732,0.402455,0.118731,0.613738,0.818328,0.406124,0.788659,1.042361,...,0.288952,0.887176,0.241435,1.146471,0.129571,0.400795,0.245704,0.219398,0.249988,pass
13,0.390304,0.198095,0.547403,0.250133,0.082983,0.422887,0.538770,0.280457,0.567433,0.749553,...,0.246120,0.640562,0.178697,0.737745,0.092898,0.330906,0.176992,0.155317,0.167505,pass
14,0.313334,0.186302,0.453965,0.221076,0.064512,0.353778,0.449335,0.215191,0.419635,0.509201,...,0.145757,0.465491,0.136290,0.602535,0.072332,0.224484,0.133021,0.126205,0.136646,pass
15,0.458996,0.316910,0.674125,0.286811,0.096635,0.551151,0.674457,0.336447,0.599633,0.756055,...,0.154842,0.637627,0.198593,0.929673,0.110119,0.367572,0.199181,0.189876,0.211277,pass
16,0.588720,0.278725,0.902256,0.407957,0.121446,0.602000,0.803676,0.391953,0.667310,0.922141,...,0.280565,0.787221,0.239980,1.105196,0.130013,0.363719,0.213452,0.210629,0.234376,pass
17,0.534486,0.319752,0.787541,0.351024,0.113172,0.604788,0.782979,0.381545,0.765622,0.997920,...,0.267657,0.858213,0.229150,1.076434,0.134004,0.426011,0.244930,0.212991,0.243490,pass
18,0.608919,0.457846,0.886275,0.397347,0.120960,0.770383,1.012454,0.477877,0.888890,1.119039,...,0.313130,0.962127,0.294701,1.134144,0.154515,0.451569,0.257746,0.247207,0.250691,pass

BARINEL SCORES

,x 20,h 16,cp 15,cp 14,cp 6,h 1,h 3,h 13,h 11,h 2,...,x 4,cp 12,cp 19,cp 7,cp 17,cp 18,h 21,cp 9,swap 8,swap 10
sum,0.616851,0.591435,0.591283,0.589399,0.588669,0.584431,0.581473,0.578549,0.577639,0.576765,...,0.572907,0.57249,0.569918,0.569684,0.569595,0.568745,0.566823,0.56309,0.550582,0.525226

TARANTULA SCORES

,x 20,h 16,cp 15,cp 14,cp 6,h 1,h 3,h 13,h 11,h 2,...,x 4,cp 12,cp 19,cp 7,cp 17,cp 18,h 21,cp 9,swap 8,swap 10
sum,0.591663,0.565752,0.565598,0.563683,0.562941,0.558636,0.555635,0.552669,0.551746,0.55086,...,0.546951,0.54653,0.543926,0.543689,0.543598,0.542738,0.540795,0.53702,0.524397,0.498908

ERROR GATE LOCATION:
20
Now evolving the following mutant:  AddGate_x_inGap_3_.qasm

100%|██████████| 10/10 [00:44<00:00,  4.49s/it]
100%|██████████| 10/10 [00:42<00:00,  4.26s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,cp 8,cp 7,cp 6,x 5,h 4,h 3,x 2,h 1,h 0,pass/fail
0,0.479880,0.726650,0.362892,0.099416,0.689319,0.957893,0.455153,0.913251,1.177272,0.956446,...,1.018275,0.275737,1.070911,0.142557,0.422155,0.270967,0.190617,0.232664,0.236285,fail
1,0.319421,0.471162,0.218864,0.061754,0.507628,0.702066,0.330160,0.581567,0.739593,0.695412,...,0.653298,0.211524,0.583618,0.095720,0.274472,0.157877,0.121325,0.157570,0.129242,fail
2,0.413793,0.633649,0.312556,0.083534,0.583118,0.736404,0.357858,0.732760,0.902533,0.835180,...,0.749342,0.220177,0.867827,0.107907,0.345444,0.211431,0.153297,0.185781,0.192134,fail
3,0.517635,0.770560,0.351069,0.104312,0.753832,0.993852,0.476768,0.873522,1.093240,1.064007,...,0.959040,0.303179,1.084197,0.145014,0.474882,0.266740,0.182278,0.250711,0.243270,fail
4,0.642872,0.939528,0.489418,0.133347,0.719052,1.013506,0.459197,0.934623,1.152196,1.029962,...,0.962170,0.281044,1.333972,0.150035,0.460162,0.288738,0.196784,0.255637,0.295619,fail
5,0.546115,0.797727,0.368005,0.112766,0.614627,0.804893,0.388519,0.806492,1.046152,0.963778,...,0.913708,0.233276,1.115605,0.133652,0.417621,0.250660,0.180365,0.214462,0.250162,fail
6,0.348907,0.525052,0.220507,0.080253,0.613748,0.792076,0.407380,0.724023,0.960887,1.013902,...,0.828871,0.250949,0.745674,0.116693,0.426197,0.211767,0.149413,0.199223,0.173543,fail
7,0.551600,0.837276,0.398134,0.115806,0.725027,0.971230,0.458171,0.847493,1.064538,0.962311,...,0.925628,0.280145,1.158809,0.140839,0.427189,0.257380,0.177704,0.243598,0.252301,fail
8,0.550017,0.840407,0.415936,0.113042,0.539144,0.719759,0.330534,0.679686,0.880005,0.696597,...,0.759622,0.198960,1.112307,0.113831,0.329247,0.224174,0.154567,0.197851,0.243833,fail
9,0.565685,0.871278,0.400960,0.114837,0.733948,0.997702,0.463522,0.833714,1.106710,0.965774,...,0.962375,0.288137,1.104862,0.146323,0.410312,0.253525,0.184189,0.243877,0.244048,fail
10,0.573481,0.872536,0.403126,0.119988,0.664411,0.905895,0.426618,0.722333,0.950695,0.845934,...,0.783517,0.245568,1.047934,0.125494,0.351833,0.217657,0.160003,0.218752,0.229714,pass
11,0.629909,0.912048,0.422576,0.137700,0.656447,0.849214,0.432561,0.868355,1.144073,1.132815,...,0.994667,0.276208,1.285276,0.149944,0.519049,0.286636,0.196686,0.252622,0.288821,pass
12,0.515634,0.791204,0.378433,0.111013,0.630485,0.817267,0.395881,0.740392,0.929555,0.871243,...,0.818742,0.240968,1.112222,0.120411,0.419106,0.244054,0.156838,0.221783,0.248082,pass
13,0.521758,0.812979,0.366602,0.112235,0.579673,0.753967,0.360678,0.676614,0.903135,0.833708,...,0.828624,0.216495,1.099339,0.123944,0.386969,0.229551,0.152487,0.206113,0.241060,pass
14,0.618703,0.921478,0.458853,0.129887,0.712931,0.999908,0.448927,0.920799,1.171626,1.007978,...,1.014395,0.275129,1.233387,0.147095,0.442865,0.274667,0.198477,0.243939,0.268475,pass
15,0.628147,0.920178,0.402681,0.129872,0.685643,0.817463,0.411052,0.778818,0.955639,1.098092,...,0.824537,0.261687,1.194657,0.141265,0.475562,0.250836,0.174810,0.242203,0.272428,pass
16,0.289440,0.442701,0.198382,0.059484,0.441972,0.576717,0.282053,0.543922,0.704939,0.656307,...,0.637556,0.183346,0.592802,0.087480,0.274200,0.159544,0.117817,0.147598,0.131431,pass
17,0.441477,0.661063,0.308183,0.092375,0.598973,0.837589,0.401779,0.681075,0.903340,0.747992,...,0.768196,0.238381,0.885586,0.116455,0.336751,0.207942,0.145733,0.197625,0.196851,pass
18,0.677910,1.044647,0.495261,0.136643,0.766067,1.006321,0.492673,0.912914,1.149909,0.978053,...,0.996699,0.298615,1.337884,0.156299,0.421563,0.274143,0.200293,0.257669,0.282626,pass
19,0.282069,0.448525,0.180315,0.060655,0.399980,0.515238,0.257228,0.434828,0.621898,0.581738,...,0.557648,0.157491,0.526713,0.081347,0.231431,0.126431,0.101133,0.127010,0.115326,pass

BARINEL SCORES

,h 14,cp 10,cp 16,cp 13,cp 7,cp 8,h 17,cp 15,x 2,h 3,...,h 4,h 1,swap 9,swap 11,h 0,cp 6,cp 19,h 21,cp 20,cp 18
sum,0.521276,0.51911,0.518182,0.517597,0.515115,0.514972,0.513588,0.513551,0.513091,0.513055,...,0.508178,0.507687,0.507364,0.501355,0.498415,0.496633,0.494682,0.488007,0.486416,0.483217

TARANTULA SCORES

,h 14,cp 10,cp 16,cp 13,cp 7,cp 8,h 17,cp 15,x 2,h 3,...,h 4,h 1,swap 9,swap 11,h 0,cp 6,cp 19,h 21,cp 20,cp 18
sum,0.521276,0.51911,0.518182,0.517597,0.515115,0.514972,0.513588,0.513551,0.513091,0.513055,...,0.508178,0.507687,0.507364,0.501355,0.498415,0.496633,0.494682,0.488007,0.486416,0.483217

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_z_inGap_8_.qasm

100%|██████████| 10/10 [00:42<00:00,  4.29s/it]
100%|██████████| 10/10 [00:39<00:00,  3.98s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,z 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.612854,0.913921,0.408634,0.131614,0.651521,0.879418,0.411273,0.790518,1.030489,0.968885,...,0.217987,0.865389,0.251716,1.213573,0.135905,0.450514,0.256319,0.235959,0.270368,fail
1,0.411574,0.609803,0.276039,0.085435,0.530270,0.659199,0.339930,0.746294,0.965712,0.927436,...,0.217475,0.846772,0.216578,0.911874,0.124843,0.406489,0.234133,0.192521,0.205874,fail
2,0.609388,0.927388,0.414251,0.120588,0.808001,1.031212,0.507022,1.031068,1.286936,1.148258,...,0.286462,1.160129,0.327715,1.282795,0.163568,0.526743,0.315693,0.277446,0.285815,fail
3,0.472417,0.714366,0.326223,0.097379,0.680469,0.896382,0.448281,0.841678,1.071070,0.983573,...,0.234911,0.877659,0.269856,0.955041,0.134860,0.389589,0.231744,0.216013,0.205476,fail
4,0.346659,0.521752,0.220010,0.073525,0.450575,0.577336,0.287848,0.624283,0.827136,0.766070,...,0.194126,0.717770,0.176804,0.712315,0.104859,0.309953,0.180495,0.149096,0.155636,fail
5,0.477763,0.691699,0.331869,0.095667,0.565465,0.777308,0.367702,0.706491,0.922342,0.823784,...,0.202114,0.831665,0.233369,0.960034,0.123822,0.360999,0.217804,0.195201,0.208250,fail
6,0.634183,1.005302,0.448238,0.134656,0.763458,0.932571,0.449204,0.917890,1.165377,1.035004,...,0.255923,1.017357,0.270945,1.339636,0.155182,0.479303,0.292584,0.262444,0.295470,fail
7,0.625974,0.908635,0.436768,0.126285,0.816324,1.078823,0.534591,1.032354,1.288274,1.188480,...,0.276983,1.111207,0.338040,1.315867,0.167805,0.536456,0.319867,0.284053,0.294836,fail
8,0.483755,0.726697,0.340395,0.099101,0.602997,0.812778,0.389447,0.754973,0.945784,0.897765,...,0.205124,0.821885,0.243458,0.982211,0.118171,0.399572,0.235539,0.213502,0.225142,fail
9,0.408815,0.600857,0.288898,0.083483,0.547784,0.762128,0.355115,0.695120,0.921105,0.873496,...,0.212925,0.790718,0.219551,0.753624,0.113471,0.342750,0.191777,0.174864,0.168581,fail
10,0.257933,0.427297,0.183871,0.056274,0.434337,0.613641,0.303589,0.407714,0.586254,0.513679,...,0.116956,0.458330,0.167837,0.506893,0.074609,0.192185,0.113518,0.127705,0.105862,pass
11,0.351506,0.528701,0.224403,0.069753,0.573324,0.739364,0.362135,0.684211,0.896407,0.804601,...,0.208321,0.815815,0.224921,0.741411,0.110232,0.340738,0.202400,0.181079,0.165113,pass
12,0.484916,0.722904,0.316778,0.101516,0.659765,0.837365,0.409852,0.806104,1.039722,1.013516,...,0.241281,0.911100,0.260132,0.935737,0.131568,0.425368,0.232633,0.214842,0.209856,pass
13,0.477154,0.678897,0.311759,0.096735,0.603828,0.800155,0.372641,0.747300,0.957308,0.950033,...,0.217510,0.815740,0.229958,0.929377,0.123681,0.392491,0.221040,0.200328,0.212405,pass
14,0.568544,0.859029,0.395206,0.113975,0.543938,0.695537,0.325426,0.643928,0.824606,0.701733,...,0.183024,0.720448,0.205751,1.092716,0.117967,0.312181,0.204569,0.188367,0.230509,pass
15,0.640486,0.977134,0.434615,0.134405,0.691905,0.919336,0.430273,0.833391,1.099049,0.942587,...,0.236839,0.962078,0.256234,1.274922,0.148554,0.431708,0.266723,0.240196,0.275678,pass
16,0.467884,0.699260,0.335359,0.097017,0.576093,0.775570,0.353933,0.736692,0.943646,0.866356,...,0.214016,0.833123,0.222626,0.941657,0.124095,0.386804,0.230652,0.201223,0.213265,pass
17,0.568334,0.887078,0.389054,0.123572,0.613501,0.818332,0.395630,0.741834,1.020882,0.897940,...,0.214602,0.855912,0.232567,1.153403,0.136087,0.405412,0.242077,0.220473,0.250041,pass
18,0.310867,0.445584,0.228730,0.059457,0.532589,0.763043,0.371890,0.686271,0.879503,0.754345,...,0.196545,0.782496,0.237368,0.671713,0.101653,0.315137,0.191016,0.172706,0.149125,pass
19,0.429287,0.686263,0.286515,0.088692,0.641106,0.879994,0.414475,0.663051,0.861795,0.837206,...,0.187078,0.717293,0.251584,0.805952,0.116334,0.321743,0.181493,0.196223,0.171082,pass

BARINEL SCORES

,h 3,h 2,h 14,h 0,h 12,cp 5,cp 7,cp 13,z 8,x 4,...,h 21,cp 6,cp 18,cp 10,cp 20,swap 9,cp 15,h 17,cp 16,swap 11
sum,0.543916,0.542726,0.539433,0.538679,0.537183,0.535245,0.534536,0.533662,0.533315,0.531201,...,0.527306,0.526778,0.52673,0.526087,0.524368,0.524102,0.522386,0.522238,0.51738,0.514269

TARANTULA SCORES

,h 3,h 2,h 14,h 0,h 12,cp 5,cp 7,cp 13,z 8,x 4,...,h 21,cp 6,cp 18,cp 10,cp 20,swap 9,cp 15,h 17,cp 16,swap 11
sum,0.543916,0.542726,0.539433,0.538679,0.537183,0.535245,0.534536,0.533662,0.533315,0.531201,...,0.527306,0.526778,0.52673,0.526087,0.524368,0.524102,0.522386,0.522238,0.51738,0.514269

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_p_inGap_10_.qasm

100%|██████████| 10/10 [00:41<00:00,  4.18s/it]
100%|██████████| 10/10 [00:35<00:00,  3.58s/it]

,h 21,cp 20,cp 19,cp 18,h 17,p 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.647941,1.007830,0.442944,0.135461,0.887308,0.428165,1.138136,0.532681,0.979414,1.210935,...,0.306038,1.020911,0.328759,1.277586,0.160008,0.512719,0.292814,0.289356,0.285329,fail
1,0.473097,0.671671,0.323506,0.098068,0.614819,0.322139,0.829294,0.396042,0.746788,0.907414,...,0.221348,0.771667,0.247162,0.947341,0.124676,0.387808,0.219168,0.204839,0.211345,fail
2,0.555901,0.795074,0.358213,0.114827,0.730151,0.389214,0.964486,0.480434,0.867967,1.108595,...,0.317674,0.953853,0.291845,1.091545,0.146132,0.454398,0.258200,0.240897,0.243362,fail
3,0.700719,0.996707,0.487872,0.142924,0.835148,0.410118,1.092862,0.528408,1.051860,1.274673,...,0.275264,1.081721,0.328252,1.461635,0.170116,0.567476,0.332666,0.298285,0.329994,fail
4,0.394302,0.605757,0.260906,0.079981,0.619354,0.325453,0.823226,0.395051,0.759779,0.966147,...,0.324273,0.826821,0.245389,0.780232,0.119364,0.353288,0.208144,0.194411,0.171112,fail
5,0.560452,0.784142,0.371507,0.115109,0.719419,0.384430,0.963917,0.463863,0.818289,1.041730,...,0.307066,0.913145,0.294474,1.037191,0.139422,0.461374,0.252383,0.247731,0.239236,fail
6,0.468729,0.681900,0.338136,0.098142,0.681490,0.367287,0.941975,0.470173,0.824076,1.065842,...,0.311789,0.903146,0.281742,0.955592,0.124582,0.405619,0.240232,0.226046,0.213575,fail
7,0.582968,0.861151,0.404295,0.119137,0.808660,0.425257,1.085584,0.542099,0.950443,1.199539,...,0.299756,1.042234,0.338787,1.253490,0.159435,0.481999,0.288388,0.269562,0.270597,fail
8,0.798333,1.141039,0.551568,0.165153,0.936116,0.461056,1.237338,0.587667,1.131718,1.387546,...,0.297499,1.188223,0.357729,1.609391,0.187336,0.613557,0.356488,0.323609,0.364132,fail
9,0.382708,0.568436,0.270847,0.075867,0.505429,0.280886,0.720999,0.345957,0.578049,0.779536,...,0.272884,0.705268,0.219462,0.744696,0.104092,0.265591,0.165696,0.161569,0.152802,fail
10,0.483597,0.699493,0.308557,0.099224,0.564903,0.284521,0.738540,0.364749,0.650854,0.840042,...,0.254708,0.760517,0.230583,0.913057,0.121171,0.378635,0.203590,0.197541,0.205044,pass
11,0.514374,0.784250,0.358672,0.107002,0.759538,0.383585,0.991267,0.477999,0.812825,1.009919,...,0.238653,0.876208,0.293476,1.067394,0.133793,0.453209,0.255877,0.256775,0.247226,pass
12,0.288110,0.411245,0.190191,0.059911,0.373961,0.198693,0.511150,0.252424,0.486411,0.648244,...,0.203848,0.593113,0.156686,0.604456,0.086382,0.272679,0.155607,0.135492,0.139197,pass
13,0.302487,0.426455,0.205667,0.060156,0.311861,0.150581,0.404892,0.190495,0.457573,0.586141,...,0.167935,0.501021,0.112348,0.597943,0.079213,0.207687,0.136960,0.105432,0.130334,pass
14,0.539004,0.828738,0.380806,0.112118,0.734262,0.364738,0.944724,0.487841,0.938046,1.235442,...,0.364481,1.063650,0.291244,1.188128,0.154360,0.496458,0.295324,0.255037,0.267324,pass
15,0.232219,0.320404,0.155338,0.045084,0.297823,0.161338,0.410980,0.193408,0.403656,0.529703,...,0.187003,0.484978,0.121555,0.470326,0.068203,0.196530,0.122211,0.099058,0.104260,pass
16,0.579829,0.847857,0.370752,0.116858,0.627670,0.291353,0.760155,0.389052,0.841879,1.073352,...,0.306942,0.942521,0.239659,1.192611,0.138548,0.462621,0.272432,0.227573,0.270864,pass
17,0.438312,0.666368,0.286511,0.094600,0.468663,0.228935,0.622628,0.299582,0.558925,0.755292,...,0.201355,0.621876,0.181504,0.857441,0.110544,0.315949,0.176577,0.169569,0.187849,pass
18,0.316356,0.452075,0.211544,0.067156,0.574424,0.315513,0.768015,0.383985,0.676618,0.851879,...,0.239814,0.760444,0.240733,0.721580,0.107586,0.362203,0.202554,0.192158,0.166276,pass
19,0.404341,0.580478,0.262895,0.078765,0.521442,0.289784,0.750052,0.362954,0.737918,0.966661,...,0.283781,0.833571,0.228517,0.831341,0.117834,0.331979,0.209928,0.174843,0.177666,pass

BARINEL SCORES

,p 16,cp 15,h 17,cp 6,cp 19,cp 14,cp 18,h 21,h 1,cp 20,...,cp 5,h 11,h 0,h 3,cp 12,h 2,x 4,cp 9,cp 7,swap 8
sum,0.58703,0.586688,0.583649,0.583232,0.582473,0.582253,0.576502,0.575877,0.575276,0.574175,...,0.569235,0.568091,0.566869,0.564264,0.562897,0.562765,0.562192,0.559402,0.558448,0.545063

TARANTULA SCORES

,p 16,cp 15,h 17,cp 6,cp 19,cp 14,cp 18,h 21,h 1,cp 20,...,cp 5,h 11,h 0,h 3,cp 12,h 2,x 4,cp 9,cp 7,swap 8
sum,0.58703,0.586688,0.583649,0.583232,0.582473,0.582253,0.576502,0.575877,0.575276,0.574175,...,0.569235,0.568091,0.566869,0.564264,0.562897,0.562765,0.562192,0.559402,0.558448,0.545063

ERROR GATE LOCATION:
16
Now evolving the following mutant:  AddGate_ry_inGap_11_.qasm

100%|██████████| 10/10 [00:16<00:00,  1.64s/it]
100%|██████████| 10/10 [00:15<00:00,  1.57s/it]

,h 21,ry 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.473600,0.334886,0.0,1.014505e-18,5.000889e-19,0.426821,0.709044,0.331979,0.497819,0.674510,...,0.219369,0.621394,0.229312,0.030110,0.079717,0.199588,0.108092,0.120929,0.175169,fail
1,0.647892,0.458129,0.0,1.208204e-18,5.955703e-19,0.431636,0.681850,0.345448,0.523114,0.774172,...,0.279372,0.709030,0.217270,0.034075,0.090733,0.225286,0.119837,0.118184,0.231199,fail
2,0.689093,0.487262,0.0,1.092354e-18,5.384634e-19,0.442391,0.699490,0.352830,0.523892,0.727956,...,0.227485,0.674485,0.241483,0.034183,0.082298,0.234366,0.120440,0.129075,0.238349,fail
3,0.647793,0.458059,0.0,9.316161e-19,4.592295e-19,0.383561,0.604892,0.295667,0.456821,0.648974,...,0.216159,0.635803,0.210837,0.030485,0.074028,0.210131,0.111974,0.114461,0.227134,fail
4,0.579655,0.409878,0.0,9.698931e-19,4.780978e-19,0.247044,0.394253,0.198318,0.398033,0.618794,...,0.229429,0.580012,0.132125,0.026108,0.067245,0.170542,0.095562,0.071503,0.187369,fail
5,0.508730,0.359726,0.0,1.088861e-18,5.367418e-19,0.436607,0.677450,0.338793,0.537696,0.754464,...,0.340609,0.737971,0.241561,0.038752,0.087171,0.256309,0.123883,0.129186,0.193213,fail
6,0.686305,0.485291,0.0,1.099721e-18,5.420950e-19,0.399641,0.630645,0.312249,0.527939,0.748581,...,0.306688,0.695684,0.216438,0.034372,0.086111,0.230788,0.117592,0.120388,0.207173,fail
7,0.549012,0.388210,0.0,1.102041e-18,5.432387e-19,0.464725,0.741690,0.373734,0.490206,0.698173,...,0.202162,0.626712,0.236421,0.032200,0.083032,0.211112,0.109690,0.128691,0.193578,fail
8,0.610722,0.431846,0.0,1.064310e-18,5.246397e-19,0.331416,0.538315,0.258511,0.504354,0.732626,...,0.274619,0.699064,0.175965,0.030785,0.086064,0.214087,0.117643,0.093366,0.218213,fail
9,0.670661,0.474229,0.0,1.209328e-18,5.961244e-19,0.310214,0.458003,0.247255,0.433799,0.703626,...,0.312203,0.702085,0.159741,0.033434,0.084814,0.207876,0.114522,0.090353,0.217353,fail
10,0.535952,0.378975,0.0,1.010797e-18,4.982609e-19,0.322868,0.524929,0.238172,0.422578,0.576575,...,0.245539,0.591137,0.172708,0.026508,0.070409,0.172508,0.096464,0.092684,0.163931,pass
11,0.552914,0.390969,0.0,1.131466e-18,5.577432e-19,0.444697,0.699244,0.346848,0.561968,0.775134,...,0.304021,0.723814,0.237074,0.036385,0.095145,0.242324,0.125372,0.127979,0.228134,pass
12,0.365020,0.258108,0.0,8.170209e-19,4.027412e-19,0.235372,0.373667,0.177291,0.347329,0.552580,...,0.252376,0.523050,0.109761,0.021382,0.057042,0.127302,0.080711,0.057801,0.106310,pass
13,0.697285,0.493055,0.0,1.210072e-18,5.964913e-19,0.551458,0.865655,0.429079,0.651475,0.892417,...,0.271855,0.810492,0.285733,0.041723,0.103644,0.282638,0.148893,0.155447,0.266883,pass
14,0.479213,0.338855,0.0,1.102229e-18,5.433310e-19,0.383621,0.568817,0.303788,0.486306,0.725860,...,0.370173,0.711507,0.201128,0.037413,0.087626,0.224527,0.113537,0.105952,0.135437,pass
15,0.504353,0.356631,0.0,1.040940e-18,5.131195e-19,0.357293,0.593631,0.269389,0.498719,0.753377,...,0.298631,0.711454,0.168940,0.029360,0.077275,0.178912,0.114492,0.093340,0.180686,pass
16,0.300789,0.212690,0.0,7.446974e-19,3.670901e-19,0.323926,0.489751,0.253663,0.368543,0.534321,...,0.231430,0.490350,0.169999,0.026533,0.060635,0.165097,0.084221,0.089027,0.088483,pass
17,0.404354,0.285922,0.0,8.797507e-19,4.336631e-19,0.328281,0.491402,0.264898,0.335301,0.516250,...,0.169980,0.472773,0.168898,0.026807,0.060782,0.166388,0.083458,0.095791,0.175708,pass
18,0.492845,0.348494,0.0,8.680606e-19,4.279006e-19,0.238681,0.356458,0.200471,0.335126,0.516033,...,0.171809,0.455193,0.125613,0.022820,0.065751,0.149973,0.078257,0.064905,0.169990,pass
19,0.475603,0.336302,0.0,8.541689e-19,4.210528e-19,0.374015,0.573078,0.295709,0.445564,0.623853,...,0.218044,0.566027,0.206736,0.031503,0.077360,0.204614,0.104906,0.113252,0.173963,pass

BARINEL SCORES

,h 21,ry 20,h 0,h 3,h 1,cp 6,cp 18,cp 17,cp 15,h 2,...,h 13,h 11,cp 12,cp 9,h 16,swap 10,x 4,cp 5,swap 8,cp 19
sum,0.557724,0.557724,0.552832,0.530165,0.528395,0.527454,0.527437,0.527437,0.525659,0.525103,...,0.523579,0.523217,0.522714,0.522702,0.521108,0.520923,0.520783,0.519256,0.507219,NaN

TARANTULA SCORES

,h 21,ry 20,h 0,h 3,h 1,cp 6,cp 17,cp 18,cp 15,h 2,...,h 13,h 11,cp 12,cp 9,h 16,swap 10,x 4,cp 5,swap 8,cp 19
sum,0.557724,0.557724,0.552832,0.530165,0.528395,0.527454,0.527437,0.527437,0.525659,0.525103,...,0.523579,0.523217,0.522714,0.522702,0.521108,0.520923,0.520783,0.519256,0.507219,NaN

ERROR GATE LOCATION:
20
Now evolving the following mutant:  AddGate_ccx_inGap_6_.qasm

100%|██████████| 10/10 [00:53<00:00,  5.38s/it]
100%|██████████| 10/10 [00:50<00:00,  5.10s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,swap 12,...,cp 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.474493,0.731529,0.312398,0.103970,0.595460,0.769146,0.377765,0.798676,1.090452,0.409615,...,1.040444,0.671973,0.181000,0.828417,0.106154,0.322850,0.231605,0.172321,0.185146,fail
1,0.651141,1.005484,0.478759,0.136460,0.814267,1.122856,0.532397,0.998437,1.271295,0.349920,...,1.241012,0.766260,0.259792,1.123774,0.126769,0.401052,0.296827,0.236956,0.247906,fail
2,0.437187,0.634144,0.292048,0.088798,0.603807,0.757887,0.374055,0.846201,1.084360,0.378550,...,1.012240,0.692593,0.190486,0.763855,0.103400,0.337223,0.239918,0.175635,0.178200,fail
3,0.540955,0.800208,0.355737,0.108343,0.720075,0.966110,0.459289,0.899551,1.164311,0.379557,...,1.142384,0.710546,0.226870,0.877879,0.118065,0.338084,0.245275,0.190412,0.189462,fail
4,0.597213,0.889514,0.414865,0.131404,0.704464,0.963574,0.455609,0.879193,1.161556,0.355070,...,1.205233,0.718481,0.218332,0.999125,0.122401,0.371212,0.260981,0.204108,0.221104,fail
5,0.666649,0.993004,0.481554,0.141433,0.863845,1.132254,0.532939,1.029924,1.251861,0.349086,...,1.254825,0.775827,0.265394,1.124678,0.132677,0.414063,0.298574,0.244884,0.251660,fail
6,0.392026,0.575980,0.268905,0.074470,0.574382,0.790201,0.374229,0.695283,0.920522,0.316421,...,0.914153,0.558826,0.183474,0.667290,0.096109,0.256798,0.192170,0.152646,0.145797,fail
7,0.629485,0.867148,0.417964,0.123731,0.716648,0.881534,0.421746,0.909373,1.097187,0.331279,...,1.074593,0.694906,0.215355,0.998663,0.120289,0.388369,0.275189,0.209650,0.232412,fail
8,0.557156,0.846867,0.374450,0.113125,0.693556,0.891666,0.424448,0.852575,1.081445,0.310811,...,1.086613,0.669319,0.210369,0.947342,0.111761,0.346541,0.252785,0.195524,0.211526,fail
9,0.526766,0.743868,0.372213,0.103144,0.602955,0.787714,0.366983,0.855732,1.057675,0.328297,...,0.999947,0.673831,0.182858,0.873123,0.105177,0.338320,0.245608,0.178658,0.201773,fail
10,0.561561,0.854285,0.374481,0.117419,0.625745,0.771592,0.403879,0.831189,1.104897,0.376927,...,1.148197,0.696792,0.205145,0.973448,0.113588,0.339595,0.247166,0.189457,0.211164,pass
11,0.486648,0.715168,0.321345,0.100239,0.559603,0.738031,0.366974,0.694964,0.963711,0.343320,...,1.024043,0.605058,0.177514,0.791327,0.096214,0.290032,0.214193,0.161564,0.176053,pass
12,0.215904,0.315471,0.167878,0.042848,0.443910,0.669851,0.304576,0.585001,0.789141,0.290654,...,0.736229,0.478398,0.143243,0.385539,0.069606,0.185087,0.142866,0.109969,0.086349,pass
13,0.470549,0.659959,0.293359,0.095739,0.517246,0.725087,0.348064,0.614478,0.838137,0.289418,...,0.867193,0.496020,0.164397,0.702710,0.091889,0.248761,0.181545,0.144463,0.155391,pass
14,0.476694,0.715080,0.324622,0.104299,0.574073,0.736259,0.351612,0.662062,0.828850,0.255288,...,0.898356,0.498000,0.164005,0.767118,0.092132,0.278747,0.199947,0.157989,0.170212,pass
15,0.369786,0.536868,0.262158,0.073951,0.540052,0.744533,0.338017,0.665107,0.809917,0.216050,...,0.782843,0.496342,0.171771,0.624450,0.080302,0.242768,0.177690,0.143806,0.138042,pass
16,0.593917,0.883984,0.417861,0.125799,0.778401,1.061024,0.519465,0.839570,1.057430,0.266077,...,1.138358,0.625677,0.252739,0.973083,0.117273,0.356110,0.250443,0.215082,0.212371,pass
17,0.585340,0.849096,0.445097,0.118701,0.733923,0.962726,0.453283,1.006080,1.258890,0.390024,...,1.132034,0.777561,0.219863,0.985212,0.122965,0.384813,0.279176,0.209780,0.225873,pass
18,0.693856,0.968450,0.450554,0.140619,0.797293,1.045724,0.511852,1.011499,1.278467,0.398584,...,1.262860,0.787548,0.255207,1.106228,0.135543,0.407174,0.293698,0.233422,0.249975,pass
19,0.499060,0.745921,0.340203,0.106621,0.625904,0.841296,0.416804,0.677292,0.884125,0.222457,...,0.989128,0.544579,0.209236,0.842139,0.097499,0.303815,0.216086,0.184648,0.186903,pass

BARINEL SCORES

,h 3,h 14,cp 7,h 2,swap 12,h 0,cp 13,h 11,cp 5,x 4,...,cp 20,h 17,cp 19,h 21,cp 8,cp 18,cp 16,cp 6,cp 15,swap 10
sum,0.536451,0.536011,0.535807,0.535443,0.53506,0.532581,0.532559,0.531557,0.530333,0.529121,...,0.527507,0.526491,0.525908,0.524925,0.523679,0.522928,0.522087,0.520845,0.518295,0.507792

TARANTULA SCORES

,h 3,h 14,cp 7,h 2,swap 12,h 0,cp 13,h 11,cp 5,x 4,...,cp 20,h 17,cp 19,h 21,cp 8,cp 18,cp 16,cp 6,cp 15,swap 10
sum,0.536451,0.536011,0.535807,0.535443,0.53506,0.532581,0.532559,0.531557,0.530333,0.529121,...,0.527507,0.526491,0.525908,0.524925,0.523679,0.522928,0.522087,0.520845,0.518295,0.507792

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_y_inGap_2_.qasm

100%|██████████| 10/10 [00:43<00:00,  4.36s/it]
100%|██████████| 10/10 [00:39<00:00,  3.98s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,cp 8,cp 7,cp 6,x 5,h 4,h 3,h 2,y 1,h 0,pass/fail
0,0.485969,0.733555,0.351962,0.103215,0.659202,0.901272,0.437832,0.785089,1.021059,0.884874,...,0.868301,0.260700,0.993587,0.130849,0.374834,0.230203,0.217566,0.087277,0.217406,fail
1,0.452121,0.666866,0.332965,0.097496,0.605723,0.841496,0.402666,0.733982,0.959491,0.868808,...,0.831328,0.242379,0.983141,0.122032,0.383305,0.227443,0.207591,0.080589,0.217720,fail
2,0.457501,0.712691,0.324920,0.095438,0.649216,0.830276,0.390391,0.759384,0.952325,0.880088,...,0.848258,0.248683,0.906596,0.120784,0.380475,0.222144,0.209651,0.082700,0.201760,fail
3,0.472798,0.662243,0.293713,0.099907,0.646138,0.850266,0.412967,0.721281,0.917552,0.960764,...,0.800752,0.255461,0.963093,0.131899,0.420159,0.228192,0.216903,0.085192,0.218976,fail
4,0.366194,0.565100,0.250683,0.074624,0.595729,0.793619,0.371958,0.653465,0.802916,0.795222,...,0.689996,0.233050,0.762819,0.108023,0.343734,0.193352,0.189451,0.074252,0.172100,fail
5,0.578884,0.868339,0.399138,0.121445,0.694825,0.884981,0.426813,0.852031,1.052148,1.022045,...,0.883317,0.259273,1.210029,0.147325,0.446899,0.262744,0.240241,0.091849,0.266970,fail
6,0.476250,0.721903,0.339558,0.104439,0.751698,1.051674,0.513826,0.813138,1.067391,0.964259,...,0.914525,0.313121,1.008767,0.135786,0.427117,0.248681,0.250724,0.096916,0.223722,fail
7,0.632418,0.970897,0.446605,0.128277,0.870286,1.110889,0.530888,0.981558,1.208170,1.098485,...,1.047584,0.329146,1.299807,0.155390,0.491563,0.299735,0.286640,0.109669,0.290400,fail
8,0.557688,0.832660,0.354176,0.117290,0.731540,0.970306,0.464653,0.865245,1.129444,1.102854,...,0.996085,0.294561,1.109407,0.150914,0.467915,0.258312,0.241714,0.097604,0.241653,fail
9,0.521539,0.738956,0.359426,0.105965,0.633449,0.838385,0.397588,0.789283,0.991110,0.966835,...,0.838045,0.239306,1.038200,0.139432,0.392243,0.236048,0.210566,0.085067,0.230582,fail
10,0.385452,0.519228,0.253303,0.076639,0.453569,0.613472,0.279505,0.547872,0.672383,0.695174,...,0.595298,0.179487,0.742244,0.096957,0.291461,0.166413,0.155405,0.062050,0.168439,pass
11,0.455091,0.691951,0.325621,0.094641,0.653375,0.860768,0.422002,0.849150,1.102540,0.971976,...,0.967117,0.264540,1.005307,0.133076,0.427333,0.258132,0.224666,0.084978,0.223100,pass
12,0.305393,0.438060,0.186427,0.063112,0.617500,0.847845,0.426499,0.738530,0.939147,0.912475,...,0.788866,0.263369,0.639711,0.117924,0.351311,0.192417,0.186894,0.080942,0.142017,pass
13,0.651442,0.930934,0.450680,0.129659,0.625240,0.828548,0.381879,0.807245,1.021821,0.905545,...,0.922426,0.237209,1.278263,0.141429,0.426240,0.267492,0.229901,0.086732,0.285571,pass
14,0.420103,0.639311,0.297512,0.085619,0.631321,0.860345,0.403837,0.735937,0.943833,0.831557,...,0.801595,0.246690,0.888943,0.119480,0.358132,0.219101,0.204959,0.080770,0.197133,pass
15,0.653677,0.949615,0.435788,0.133722,0.706427,0.902389,0.440235,0.797549,1.004947,0.989103,...,0.847339,0.265891,1.248258,0.147182,0.422803,0.252508,0.243864,0.096963,0.273980,pass
16,0.337988,0.511390,0.233442,0.067206,0.389661,0.490348,0.242118,0.484325,0.615279,0.611238,...,0.539637,0.155739,0.642359,0.088536,0.248983,0.141048,0.129647,0.054065,0.137180,pass
17,0.542815,0.790977,0.359961,0.115942,0.639590,0.829807,0.394501,0.760398,0.949965,1.033564,...,0.870701,0.248660,1.017929,0.137985,0.439874,0.233086,0.222823,0.088103,0.230034,pass
18,0.429317,0.651667,0.303150,0.097170,0.590096,0.830081,0.404996,0.679108,0.951984,0.855141,...,0.812642,0.233583,0.880701,0.112211,0.373214,0.208751,0.196896,0.076475,0.197943,pass
19,0.556155,0.927731,0.417681,0.116434,0.648622,0.877792,0.425218,0.706556,1.002477,0.688600,...,0.837899,0.248998,1.091071,0.127764,0.310755,0.213395,0.207935,0.083900,0.220567,pass

BARINEL SCORES

,h 17,cp 16,cp 7,cp 15,h 2,h 4,h 12,y 1,h 14,h 3,...,x 5,cp 13,cp 8,cp 6,cp 18,cp 20,cp 19,h 21,swap 9,swap 11
sum,0.534487,0.533259,0.533021,0.53236,0.531359,0.530735,0.5291,0.52851,0.528145,0.527912,...,0.523371,0.523237,0.521994,0.521325,0.516752,0.514539,0.514113,0.51355,0.506653,0.500142

TARANTULA SCORES

,h 17,cp 16,cp 7,cp 15,h 2,h 4,h 12,y 1,h 14,h 3,...,x 5,cp 13,cp 8,cp 6,cp 18,cp 20,cp 19,h 21,swap 9,swap 11
sum,0.534487,0.533259,0.533021,0.53236,0.531359,0.530735,0.5291,0.52851,0.528145,0.527912,...,0.523371,0.523237,0.521994,0.521325,0.516752,0.514539,0.514113,0.51355,0.506653,0.500142

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_y_inGap_15_.qasm

100%|██████████| 10/10 [00:39<00:00,  3.94s/it]
100%|██████████| 8/8 [00:30<00:00,  3.76s/it]

,y 21,h 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.374399,0.529480,0.743305,0.385922,0.105121,0.680869,0.900250,0.429644,0.882997,1.059358,...,0.245210,0.936154,0.275253,1.141252,0.142134,0.462939,0.279359,0.244033,0.260591,fail
1,0.392415,0.554959,0.871718,0.407343,0.114622,0.727074,0.990281,0.457744,0.878900,1.110266,...,0.286084,0.935503,0.265433,1.131578,0.137826,0.374185,0.249692,0.227348,0.242027,fail
2,0.377036,0.533209,0.828026,0.395500,0.111413,0.776031,1.015031,0.494067,0.914849,1.137236,...,0.250223,0.935762,0.291997,1.175993,0.145459,0.452712,0.275925,0.254559,0.261846,fail
3,0.523192,0.739906,1.081204,0.514170,0.141721,0.649089,0.793573,0.371881,0.914091,1.129302,...,0.296817,1.027950,0.238551,1.500109,0.158438,0.458910,0.308782,0.246697,0.329863,fail
4,0.546478,0.772837,1.144948,0.500646,0.168370,0.757325,0.915533,0.463567,0.864907,1.143865,...,0.321654,0.980879,0.284386,1.466109,0.158286,0.560172,0.295296,0.283231,0.332966,fail
5,0.535406,0.757178,1.171728,0.541730,0.154793,0.945422,1.236827,0.584503,1.074863,1.315631,...,0.270702,1.114874,0.360171,1.572724,0.173747,0.531013,0.332439,0.318452,0.341737,fail
6,0.486898,0.688578,1.051716,0.493896,0.146654,0.743397,0.974310,0.486357,0.930324,1.242739,...,0.357988,1.092318,0.296438,1.423951,0.154671,0.512187,0.310251,0.276011,0.317098,fail
7,0.528173,0.746950,1.103521,0.503788,0.157023,0.839398,1.091682,0.536517,1.000599,1.289217,...,0.244277,1.082621,0.312922,1.527729,0.169944,0.562406,0.334775,0.301242,0.346466,fail
8,0.440532,0.623007,0.968061,0.441578,0.131363,0.745966,1.029448,0.478083,0.817024,1.078649,...,0.272854,0.905974,0.278950,1.192780,0.141506,0.401889,0.248885,0.245979,0.258968,fail
9,0.448542,0.634334,0.974614,0.435684,0.137762,0.726744,0.903519,0.453781,0.807909,1.029742,...,0.259572,0.869711,0.266508,1.269142,0.149137,0.483744,0.262596,0.253408,0.282853,fail
10,0.332598,0.470365,0.684378,0.321206,0.091547,0.620714,0.801026,0.404223,0.819479,1.060667,...,0.286606,0.886880,0.248258,1.002602,0.134414,0.402780,0.246875,0.205842,0.218365,pass
11,0.361068,0.510627,0.760952,0.339905,0.106428,0.656565,0.831088,0.436347,0.808266,1.033312,...,0.284227,0.872783,0.266943,1.047633,0.130782,0.443014,0.252354,0.230846,0.237421,pass
12,0.265570,0.375573,0.558747,0.266121,0.076830,0.464966,0.599711,0.289390,0.532682,0.667176,...,0.113280,0.585336,0.169294,0.828080,0.094674,0.285854,0.181204,0.161778,0.186921,pass
13,0.336594,0.476016,0.692523,0.343009,0.099841,0.591413,0.809933,0.375528,0.823041,1.072582,...,0.313678,0.939086,0.233584,1.040396,0.133153,0.426925,0.258472,0.211237,0.235156,pass
14,0.359546,0.508475,0.809647,0.375490,0.112105,0.696525,0.958623,0.447466,0.813789,1.069221,...,0.266855,0.894661,0.255590,1.100683,0.133491,0.392992,0.245461,0.226117,0.236279,pass
15,0.372424,0.526687,0.767973,0.369577,0.115212,0.734500,0.990650,0.502803,0.863556,1.128871,...,0.287436,0.932642,0.296147,1.114883,0.145155,0.449440,0.265526,0.248553,0.248866,pass
16,0.476823,0.674330,1.030574,0.486914,0.139465,0.743783,1.025062,0.476020,0.846980,1.115040,...,0.198717,0.934082,0.274956,1.372559,0.153565,0.432358,0.281236,0.256325,0.296813,pass
17,0.295584,0.418018,0.579553,0.288374,0.079380,0.563106,0.767429,0.346429,0.814394,1.014070,...,0.271562,0.895910,0.207468,0.900794,0.116306,0.364994,0.241805,0.185151,0.205777,pass

BARINEL SCORES

,cp 19,cp 17,y 21,h 20,cp 18,swap 10,h 0,cp 5,h 1,h 3,...,cp 6,x 4,h 2,cp 15,cp 14,h 13,cp 9,cp 7,cp 12,swap 8
sum,0.628119,0.625142,0.624299,0.624299,0.623445,0.61935,0.614547,0.614488,0.605683,0.600131,...,0.59521,0.595156,0.594958,0.592189,0.591976,0.589699,0.588352,0.587391,0.585675,0.581096

TARANTULA SCORES

,cp 19,cp 17,y 21,h 20,cp 18,swap 10,h 0,cp 5,h 1,h 3,...,cp 6,x 4,h 2,cp 15,cp 14,h 13,cp 9,cp 7,cp 12,swap 8
sum,0.57469,0.571577,0.570696,0.570696,0.569804,0.565532,0.560532,0.560471,0.551333,0.54559,...,0.540512,0.540456,0.540251,0.537399,0.537181,0.534838,0.533454,0.532466,0.530704,0.526009

ERROR GATE LOCATION:
21
Now evolving the following mutant:  AddGate_z_inGap_11_.qasm

100%|██████████| 10/10 [00:43<00:00,  4.31s/it]
100%|██████████| 9/9 [00:33<00:00,  3.76s/it]

,h 21,z 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.636433,0.450026,0.911193,0.440770,0.135283,0.678397,0.945522,0.457274,0.893634,1.195519,...,0.337058,1.025575,0.265152,1.266778,0.156861,0.448208,0.277671,0.237671,0.277249,fail
1,0.770959,0.545150,1.107038,0.510683,0.154367,0.759887,0.944754,0.445556,0.982882,1.195247,...,0.262671,1.054842,0.287848,1.560781,0.170144,0.547361,0.328751,0.280498,0.348824,fail
2,0.733243,0.518481,1.068024,0.506089,0.147150,0.909213,1.201715,0.564551,1.017134,1.221393,...,0.253094,1.043976,0.349702,1.431727,0.174385,0.542703,0.316236,0.307670,0.324157,fail
3,0.624457,0.441558,0.935645,0.419174,0.126569,0.715909,0.878024,0.422247,0.929172,1.162386,...,0.314677,1.015809,0.254816,1.298867,0.155797,0.482645,0.293092,0.244390,0.289267,fail
4,0.549921,0.388853,0.857939,0.380452,0.121634,0.701863,0.943039,0.464780,0.785557,1.033597,...,0.236063,0.860749,0.280315,1.147524,0.135134,0.433009,0.248846,0.242681,0.250488,fail
5,0.520369,0.367956,0.730078,0.370294,0.104921,0.535197,0.711642,0.335093,0.766148,0.957305,...,0.224179,0.837589,0.210865,1.100397,0.124951,0.391614,0.253797,0.205919,0.249027,fail
6,0.513150,0.362852,0.759125,0.359057,0.105479,0.533620,0.696374,0.340289,0.652915,0.875103,...,0.254277,0.782085,0.212006,1.031338,0.118567,0.364166,0.218287,0.193748,0.226135,fail
7,0.692017,0.489330,1.000857,0.473540,0.140171,0.746126,0.950561,0.469067,0.953239,1.199073,...,0.312011,1.061263,0.287372,1.408718,0.161009,0.506851,0.309167,0.267133,0.314069,fail
8,0.679015,0.480136,1.020403,0.479334,0.144751,0.782881,1.036359,0.511400,0.919699,1.184719,...,0.292121,1.022494,0.308347,1.398894,0.167036,0.508031,0.293756,0.275524,0.305168,fail
9,0.709179,0.501465,1.016493,0.485334,0.150084,0.723405,0.962710,0.474887,0.961072,1.227606,...,0.280646,1.035262,0.299617,1.434578,0.163022,0.563560,0.318278,0.280097,0.325362,fail
10,0.670821,0.474342,0.983617,0.418661,0.140348,0.706899,0.923029,0.432321,0.774902,0.985886,...,0.204461,0.854110,0.265406,1.247017,0.141517,0.455000,0.253313,0.247501,0.279296,pass
11,0.418456,0.295893,0.622038,0.302145,0.087135,0.512514,0.707509,0.331795,0.619767,0.838097,...,0.205793,0.706812,0.191893,0.839706,0.106889,0.306062,0.198139,0.174307,0.187371,pass
12,0.528131,0.373445,0.806161,0.350326,0.107115,0.696009,0.934978,0.426046,0.810979,1.033176,...,0.293370,0.902105,0.260324,1.050217,0.143711,0.411276,0.240573,0.225976,0.230896,pass
13,0.365048,0.258128,0.554796,0.236711,0.075596,0.583093,0.769875,0.392430,0.651358,0.860975,...,0.257683,0.712358,0.229859,0.733428,0.109713,0.317525,0.186353,0.183650,0.163534,pass
14,0.505937,0.357751,0.797706,0.332906,0.107327,0.603573,0.760782,0.367244,0.705683,0.941616,...,0.333954,0.863240,0.232524,1.025104,0.131655,0.396707,0.225910,0.207146,0.222911,pass
15,0.369325,0.261153,0.559768,0.274404,0.073020,0.500451,0.639904,0.318898,0.582313,0.731485,...,0.208723,0.639617,0.197178,0.780669,0.093435,0.270906,0.178988,0.166143,0.169632,pass
16,0.308808,0.218360,0.476588,0.218619,0.060452,0.442557,0.593489,0.276667,0.573839,0.737552,...,0.244213,0.632824,0.170955,0.625178,0.093468,0.248609,0.159081,0.139489,0.133862,pass
17,0.539021,0.381145,0.826584,0.389260,0.115311,0.677292,0.953479,0.452189,0.773324,1.011598,...,0.231074,0.822213,0.264505,1.072436,0.131499,0.382836,0.237611,0.229103,0.233836,pass
18,0.526343,0.372181,0.832173,0.373897,0.112390,0.748578,1.023996,0.510582,0.824772,1.124836,...,0.320269,0.973916,0.308182,1.118198,0.138040,0.433329,0.258876,0.251840,0.241899,pass

BARINEL SCORES

,h 0,cp 5,cp 18,z 20,h 21,cp 17,h 3,h 2,cp 19,h 11,...,x 4,h 1,cp 7,cp 12,swap 10,cp 6,h 16,cp 14,cp 15,swap 8
sum,0.609629,0.606336,0.604334,0.603036,0.603036,0.602239,0.597742,0.595798,0.592882,0.589878,...,0.583494,0.581433,0.578129,0.576515,0.570276,0.565125,0.564326,0.561112,0.559226,0.546114

TARANTULA SCORES

,h 0,cp 5,cp 18,z 20,h 21,cp 17,h 3,h 2,cp 19,h 11,...,x 4,h 1,cp 7,cp 12,swap 10,cp 6,h 16,cp 14,cp 15,swap 8
sum,0.584285,0.580926,0.578885,0.577561,0.577561,0.57675,0.572168,0.57019,0.567223,0.564169,...,0.557685,0.555594,0.552243,0.550607,0.544288,0.539077,0.538269,0.535021,0.533116,0.519895

ERROR GATE LOCATION:
20
Now evolving the following mutant:  AddGate_rxx_inGap_11_.qasm

100%|██████████| 10/10 [01:01<00:00,  6.12s/it]
100%|██████████| 10/10 [01:00<00:00,  6.02s/it]

,h 21,rxx 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.567074,2.181905,1.169075,0.533988,0.153112,0.973763,1.276616,0.577249,1.028495,1.313482,...,0.261865,1.366998,0.549322,1.705619,0.246786,1.100453,0.860227,0.681779,1.059717,fail
1,0.631094,1.712893,0.825691,0.369544,0.102466,0.789373,1.064943,0.462909,0.910517,1.166397,...,0.270851,1.109296,0.410988,1.536950,0.195389,0.759439,0.619499,0.485954,0.888926,fail
2,0.666988,2.019680,0.771169,0.326132,0.104923,0.846555,1.023622,0.459753,0.823716,0.954361,...,0.170595,1.051554,0.431320,1.607752,0.197305,0.813745,0.683880,0.555915,0.980640,fail
3,0.574428,2.249894,0.989193,0.499183,0.136340,0.973762,1.237315,0.554880,0.984290,1.206047,...,0.251766,1.346163,0.521775,1.759770,0.240985,1.038798,0.889280,0.718986,1.168678,fail
4,0.578036,2.435440,0.990442,0.475747,0.140991,0.957738,1.229533,0.565056,1.030146,1.258168,...,0.231306,1.382908,0.559620,1.765400,0.253782,1.194291,0.944566,0.751149,1.212902,fail
5,0.674400,2.045109,0.813730,0.358624,0.106549,0.933019,1.116760,0.525047,1.041083,1.252523,...,0.277046,1.277493,0.498890,1.702667,0.224967,0.941749,0.777974,0.601223,1.067798,fail
6,0.347796,1.613764,0.666614,0.308404,0.090811,0.571750,0.734443,0.337076,0.701994,0.882052,...,0.221634,0.905552,0.366545,1.098590,0.168331,0.767616,0.586561,0.439191,0.711120,fail
7,0.631295,1.845314,0.740866,0.322711,0.104183,0.861450,1.074541,0.498189,0.806999,0.994834,...,0.227823,1.075417,0.443129,1.531061,0.193878,0.815419,0.662145,0.551848,0.964855,fail
8,0.644913,1.533874,0.676660,0.333436,0.094628,0.987287,1.257518,0.588902,1.135321,1.375201,...,0.348425,1.272238,0.489569,1.701032,0.220236,0.869118,0.705018,0.567486,1.000704,fail
9,0.656059,1.815347,0.966270,0.449411,0.133759,0.839579,0.975881,0.489499,1.006515,1.251271,...,0.300419,1.261103,0.483232,1.766313,0.232162,0.990018,0.771087,0.590458,0.958203,fail
10,0.498160,1.455116,0.519758,0.246600,0.073360,0.827013,1.020258,0.481464,0.969700,1.197050,...,0.309794,1.131591,0.445521,1.376011,0.188796,0.809673,0.678392,0.536746,0.951008,pass
11,0.572630,1.171518,0.794005,0.361101,0.109676,0.804414,0.989332,0.466256,0.844434,1.065318,...,0.285298,0.978044,0.383360,1.405339,0.181941,0.713370,0.524376,0.432081,0.704559,pass
12,0.477293,1.165930,0.949017,0.394544,0.130965,0.680734,0.799697,0.384006,0.749734,0.990391,...,0.236953,0.948756,0.363120,1.351503,0.182344,0.769180,0.573554,0.454058,0.648738,pass
13,0.250846,1.512938,0.591430,0.265496,0.075743,0.717662,0.895369,0.408431,0.782686,0.938214,...,0.217836,1.003851,0.413846,1.102840,0.184691,0.849331,0.689959,0.540271,0.835630,pass
14,0.464071,1.694149,1.021649,0.465422,0.134025,0.750427,0.972546,0.447927,0.849708,1.090413,...,0.257657,1.144772,0.439751,1.309493,0.209637,0.871786,0.663117,0.513114,0.749599,pass
15,0.382644,1.119792,0.431397,0.185825,0.058846,0.537208,0.648247,0.316490,0.554409,0.671729,...,0.187241,0.692198,0.267479,0.936969,0.126615,0.524215,0.405996,0.338378,0.597755,pass
16,0.733073,1.774369,0.739266,0.314332,0.096376,0.904108,1.148401,0.540836,0.949754,1.133566,...,0.246299,1.138876,0.460489,1.664104,0.208056,0.785088,0.644678,0.531751,0.950104,pass
17,0.662438,1.696194,1.193529,0.514978,0.157022,0.902396,1.104935,0.534449,0.996767,1.285962,...,0.293245,1.246096,0.497153,1.842802,0.233805,1.004616,0.765266,0.606202,1.026250,pass
18,0.540756,1.037549,0.951141,0.439094,0.128544,0.640815,0.796080,0.372635,0.878976,1.079029,...,0.226216,1.027450,0.346742,1.312908,0.179162,0.695574,0.521535,0.389632,0.553640,pass
19,0.454534,1.016228,0.841489,0.412997,0.115064,0.809740,1.060414,0.495635,0.845970,1.090352,...,0.283202,1.095967,0.387577,1.284318,0.189674,0.706292,0.578141,0.496620,0.699188,pass

BARINEL SCORES

,rxx 20,h 0,h 2,h 1,h 3,cp 5,cp 6,h 21,cp 15,cp 7,...,cp 14,h 13,h 11,cp 12,cp 18,cp 17,cp 19,swap 10,cp 9,swap 8
sum,0.587764,0.564779,0.553717,0.551245,0.545874,0.543494,0.542774,0.542496,0.538085,0.53654,...,0.532105,0.529258,0.525337,0.525056,0.524862,0.519609,0.517336,0.507831,0.50463,0.501762

TARANTULA SCORES

,rxx 20,h 0,h 2,h 1,h 3,cp 5,cp 6,h 21,cp 15,cp 7,...,cp 14,h 13,h 11,cp 12,cp 18,cp 17,cp 19,swap 10,cp 9,swap 8
sum,0.587764,0.564779,0.553717,0.551245,0.545874,0.543494,0.542774,0.542496,0.538085,0.53654,...,0.532105,0.529258,0.525337,0.525056,0.524862,0.519609,0.517336,0.507831,0.50463,0.501762

ERROR GATE LOCATION:
20
Now evolving the following mutant:  AddGate_swap_inGap_11_.qasm

100%|██████████| 10/10 [00:54<00:00,  5.40s/it]
100%|██████████| 10/10 [00:50<00:00,  5.10s/it]

,h 21,swap 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.482646,0.571746,0.044274,0.023183,0.006236,0.444238,0.607927,0.262952,0.647652,0.795551,...,0.226177,0.775269,0.309665,1.171756,0.142545,0.553959,0.458015,0.334056,0.463166,fail
1,0.615496,0.608297,0.055880,0.026600,0.008046,0.530660,0.697442,0.313142,0.618641,0.761635,...,0.210309,0.859322,0.357918,1.432573,0.162900,0.620445,0.527748,0.392628,0.512663,fail
2,0.564873,0.602337,0.049997,0.024750,0.007049,0.377741,0.465213,0.207603,0.506328,0.607749,...,0.191772,0.694847,0.271643,1.148469,0.140492,0.522559,0.418498,0.289823,0.460598,fail
3,0.432632,0.622073,0.038945,0.018900,0.005595,0.336262,0.388321,0.212843,0.505383,0.654093,...,0.207051,0.678703,0.241573,0.985403,0.128410,0.448325,0.374587,0.256494,0.376362,fail
4,0.701832,0.820664,0.065474,0.030456,0.009365,0.670017,0.839166,0.401954,0.687065,0.856415,...,0.255357,0.927858,0.391930,1.722206,0.180493,0.621632,0.562065,0.467335,0.673685,fail
5,0.525546,0.490572,0.048134,0.020059,0.006632,0.557632,0.676585,0.318777,0.611104,0.764597,...,0.241327,0.772117,0.321759,1.530521,0.154655,0.549191,0.486124,0.368278,0.536225,fail
6,0.580692,0.605403,0.056252,0.025599,0.007171,0.789588,0.986683,0.443048,0.876266,1.104716,...,0.325919,1.083774,0.409401,1.822544,0.207614,0.846576,0.702550,0.555786,0.573374,fail
7,0.615227,0.638908,0.057070,0.025431,0.008136,0.544314,0.694523,0.319783,0.620360,0.750146,...,0.215207,0.868674,0.356635,1.578317,0.176153,0.667241,0.574563,0.435175,0.429608,fail
8,0.635947,0.678135,0.058791,0.026851,0.008152,0.587340,0.732041,0.351215,0.670605,0.792348,...,0.213646,0.879104,0.379478,1.637050,0.182255,0.709781,0.589521,0.463480,0.564522,fail
9,0.596569,0.715744,0.055549,0.026789,0.006800,0.580117,0.708547,0.325605,0.745972,0.967935,...,0.301038,0.882789,0.355055,1.621839,0.179985,0.756966,0.579663,0.430596,0.590941,fail
10,0.576722,0.553165,0.052623,0.024055,0.007350,0.563480,0.717339,0.342116,0.681065,0.826623,...,0.206239,0.865995,0.365341,1.552365,0.170440,0.671220,0.579961,0.458874,0.492447,pass
11,0.443760,0.722084,0.041888,0.019925,0.006085,0.447963,0.551450,0.271413,0.499541,0.604355,...,0.192467,0.664882,0.280602,0.987047,0.129622,0.443539,0.363715,0.291532,0.544325,pass
12,0.431223,0.311954,0.040357,0.020058,0.005632,0.478240,0.566170,0.261492,0.468628,0.538175,...,0.119423,0.627536,0.247132,1.131094,0.124327,0.508339,0.450991,0.378319,0.296209,pass
13,0.530716,0.520993,0.049971,0.022680,0.006776,0.641358,0.739680,0.372171,0.646608,0.809738,...,0.189050,0.813041,0.351353,1.671523,0.166045,0.639181,0.557124,0.453795,0.591020,pass
14,0.546941,0.406209,0.053203,0.025090,0.007148,0.590883,0.675898,0.313521,0.561363,0.680741,...,0.177257,0.781084,0.285336,1.480657,0.151182,0.640346,0.543359,0.470428,0.437109,pass
15,0.588317,0.593608,0.054972,0.026963,0.007476,0.594345,0.712069,0.347735,0.713577,0.851308,...,0.202711,0.873925,0.363019,1.609213,0.176032,0.723233,0.608432,0.484779,0.509048,pass
16,0.606258,0.576466,0.054706,0.023599,0.008028,0.462450,0.554331,0.283577,0.540622,0.668447,...,0.211781,0.790926,0.333789,1.444530,0.159076,0.554735,0.492475,0.354872,0.466545,pass
17,0.392782,0.628302,0.036360,0.018679,0.005242,0.367285,0.458852,0.255067,0.518683,0.671928,...,0.150208,0.623186,0.263468,1.069255,0.122254,0.443973,0.372079,0.281118,0.393722,pass
18,0.309136,0.273811,0.030384,0.013116,0.004227,0.302950,0.328997,0.155593,0.281007,0.349723,...,0.103896,0.416172,0.163332,0.799303,0.088148,0.328546,0.275121,0.233797,0.255447,pass
19,0.385898,0.635485,0.039253,0.016357,0.004964,0.658686,0.827080,0.407447,0.592567,0.812744,...,0.269322,0.855376,0.298411,1.039126,0.161451,0.599881,0.469962,0.422312,0.291538,pass

BARINEL SCORES

,swap 8,swap 20,h 0,h 21,swap 10,cp 12,cp 18,h 13,cp 19,cp 17,...,cp 5,x 4,h 3,cp 9,h 2,cp 15,h 11,h 16,cp 14,h 1
sum,0.567153,0.548886,0.547773,0.54448,0.544261,0.541745,0.541485,0.541095,0.538944,0.537671,...,0.534018,0.533331,0.53138,0.528325,0.528044,0.525703,0.52393,0.514739,0.511901,0.51047

TARANTULA SCORES

,swap 8,swap 20,h 0,h 21,swap 10,cp 12,cp 18,h 13,cp 19,cp 17,...,cp 5,x 4,h 3,cp 9,h 2,cp 15,h 11,h 16,cp 14,h 1
sum,0.567153,0.548886,0.547773,0.54448,0.544261,0.541745,0.541485,0.541095,0.538944,0.537671,...,0.534018,0.533331,0.53138,0.528325,0.528044,0.525703,0.52393,0.514739,0.511901,0.51047

ERROR GATE LOCATION:
20
Now evolving the following mutant:  AddGate_p_inGap_11_.qasm

100%|██████████| 10/10 [00:45<00:00,  4.50s/it]
100%|██████████| 10/10 [00:37<00:00,  3.75s/it]

,h 21,p 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.711589,0.503169,1.042438,0.494044,0.144762,0.741144,0.952946,0.444672,0.898046,1.103417,...,0.272488,0.980056,0.284244,1.417495,0.156095,0.474224,0.287556,0.262394,0.311389,fail
1,0.552153,0.390431,0.871179,0.396969,0.115341,0.774691,1.031030,0.500575,0.863421,1.111995,...,0.329506,0.966611,0.305056,1.132706,0.147648,0.433915,0.253647,0.248408,0.243796,fail
2,0.610807,0.431906,0.872660,0.392255,0.120951,0.755432,0.970669,0.463076,0.798668,0.984044,...,0.229939,0.864936,0.287863,1.176010,0.143971,0.462498,0.258256,0.254769,0.269789,fail
3,0.588432,0.416084,0.860784,0.405064,0.116590,0.725207,0.915240,0.445001,0.969056,1.225673,...,0.404646,1.119617,0.285024,1.235442,0.163607,0.484058,0.299417,0.254637,0.276916,fail
4,0.626960,0.443328,0.965641,0.414350,0.130221,0.736436,0.956030,0.460702,0.854619,1.134480,...,0.312008,0.954629,0.270368,1.195672,0.147926,0.440302,0.263132,0.243454,0.263834,fail
5,0.751323,0.531266,1.105151,0.521032,0.154521,0.762387,0.994423,0.486884,0.920905,1.199828,...,0.301430,1.053290,0.299193,1.520131,0.164560,0.516017,0.312447,0.283905,0.337199,fail
6,0.643256,0.454851,1.002702,0.426096,0.136890,0.654975,0.800529,0.393032,0.722014,0.947115,...,0.257910,0.840049,0.244263,1.236041,0.141629,0.441406,0.249475,0.240675,0.274986,fail
7,0.736787,0.520987,1.110245,0.487860,0.159088,0.804644,1.049906,0.506585,0.845975,1.096437,...,0.226727,0.953893,0.305300,1.437647,0.155858,0.507334,0.287689,0.284655,0.319226,fail
8,0.724092,0.512010,1.115614,0.496705,0.153077,0.814051,1.078656,0.510709,0.925117,1.174407,...,0.309717,1.041718,0.317109,1.412466,0.162682,0.494172,0.288151,0.284076,0.309168,fail
9,0.585907,0.414299,0.926044,0.413994,0.126455,0.724406,0.942176,0.462135,0.821715,1.067437,...,0.257272,0.920495,0.284793,1.229113,0.134475,0.459267,0.269145,0.257304,0.272743,fail
10,0.462814,0.327259,0.744829,0.311364,0.097324,0.503266,0.630959,0.295759,0.629872,0.840534,...,0.287552,0.746460,0.177119,0.920949,0.107927,0.294739,0.193230,0.169897,0.196942,pass
11,0.402166,0.284374,0.635812,0.271083,0.086106,0.517011,0.673007,0.328713,0.549732,0.707107,...,0.170493,0.595104,0.198777,0.779956,0.095425,0.300020,0.167498,0.170294,0.171736,pass
12,0.665557,0.470620,0.964407,0.485432,0.137116,0.671552,0.911725,0.416284,0.974063,1.246618,...,0.375000,1.122790,0.260108,1.362784,0.156957,0.468012,0.306011,0.246584,0.301727,pass
13,0.533760,0.377425,0.756649,0.357424,0.112121,0.638604,0.866100,0.403560,0.751845,0.918914,...,0.183951,0.778888,0.248001,1.051096,0.130506,0.410619,0.230621,0.216721,0.235556,pass
14,0.387466,0.273980,0.587042,0.273560,0.077480,0.577837,0.860444,0.395362,0.665535,0.907094,...,0.270223,0.778222,0.235452,0.740199,0.115143,0.300447,0.185792,0.178786,0.157217,pass
15,0.418721,0.296080,0.637007,0.276088,0.087334,0.589369,0.730570,0.380504,0.769540,0.972592,...,0.312226,0.857066,0.245010,0.919957,0.116484,0.439458,0.236440,0.206866,0.210551,pass
16,0.362175,0.256096,0.588946,0.275798,0.070740,0.539125,0.770142,0.357151,0.614550,0.828924,...,0.232759,0.681115,0.199059,0.709235,0.095524,0.227860,0.167131,0.157218,0.148919,pass
17,0.385267,0.272425,0.582330,0.278365,0.075401,0.486496,0.660792,0.307616,0.611929,0.806630,...,0.243099,0.693732,0.182404,0.761799,0.098879,0.257642,0.180468,0.159171,0.167172,pass
18,0.557450,0.394177,0.817499,0.377975,0.111816,0.577050,0.729758,0.358992,0.713897,0.923558,...,0.230834,0.821780,0.215663,1.145653,0.131378,0.366597,0.234573,0.202306,0.246963,pass
19,0.535485,0.378645,0.803661,0.351326,0.109915,0.691529,0.859922,0.417496,0.737197,0.884256,...,0.213595,0.749232,0.260557,1.027714,0.120595,0.402108,0.221124,0.225308,0.228900,pass

BARINEL SCORES

,cp 17,h 0,cp 19,p 20,h 21,cp 5,cp 18,h 3,h 1,h 11,...,cp 6,cp 9,h 16,swap 10,cp 14,cp 15,cp 7,h 13,cp 12,swap 8
sum,0.584481,0.582246,0.581053,0.580965,0.580965,0.57972,0.577202,0.576136,0.574891,0.568698,...,0.564742,0.56427,0.564039,0.561908,0.560705,0.557469,0.553394,0.551202,0.550012,0.535223

TARANTULA SCORES

,cp 17,h 0,cp 19,h 21,p 20,cp 5,cp 18,h 3,h 1,h 11,...,cp 6,cp 9,h 16,swap 10,cp 14,cp 15,cp 7,h 13,cp 12,swap 8
sum,0.584481,0.582246,0.581053,0.580965,0.580965,0.57972,0.577202,0.576136,0.574891,0.568698,...,0.564742,0.56427,0.564039,0.561908,0.560705,0.557469,0.553394,0.551202,0.550012,0.535223

ERROR GATE LOCATION:
20
Now evolving the following mutant:  AddGate_z_inGap_7_.qasm

100%|██████████| 10/10 [00:43<00:00,  4.37s/it]
100%|██████████| 10/10 [00:38<00:00,  3.88s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.359997,0.546446,0.264496,0.075820,0.517968,0.731818,0.338732,0.711820,0.948638,0.844625,...,0.386792,0.833817,0.218042,0.744137,0.119131,0.330254,0.194910,0.169533,0.156618,fail
1,0.404268,0.586312,0.253102,0.083649,0.544583,0.730276,0.361968,0.657394,0.918054,0.806017,...,0.360633,0.834185,0.224753,0.807353,0.125330,0.340485,0.198918,0.180790,0.175770,fail
2,0.576166,0.840890,0.396715,0.114199,0.683185,0.819233,0.403931,0.856033,1.013760,1.059943,...,0.288478,0.905384,0.265868,1.173554,0.140863,0.466608,0.267257,0.242147,0.266490,fail
3,0.537178,0.787568,0.358399,0.112190,0.635705,0.848546,0.408646,0.766422,0.972157,0.976007,...,0.232826,0.793520,0.248292,1.058495,0.135310,0.398678,0.228168,0.217127,0.232702,fail
4,0.445367,0.630954,0.296331,0.091651,0.638630,0.825899,0.406157,0.775381,0.964066,1.003705,...,0.320429,0.886659,0.265917,0.924066,0.131608,0.441019,0.239843,0.222090,0.210966,fail
5,0.674789,1.036306,0.474504,0.138315,0.822895,1.077646,0.513490,0.935980,1.171346,1.024755,...,0.264878,0.997640,0.312097,1.406665,0.156876,0.475719,0.295343,0.278047,0.305896,fail
6,0.522622,0.795277,0.347974,0.109240,0.721908,0.958799,0.479017,0.831801,1.065227,1.081561,...,0.268278,0.893919,0.300064,1.108243,0.142638,0.461095,0.252075,0.241116,0.240362,fail
7,0.611635,0.906604,0.418559,0.123788,0.598272,0.789906,0.362232,0.665339,0.834189,0.812744,...,0.188296,0.709934,0.216342,1.128748,0.126724,0.343786,0.211334,0.207702,0.244977,fail
8,0.548045,0.840620,0.362657,0.121038,0.720078,0.973696,0.479250,0.814084,1.087518,1.056520,...,0.270822,0.904733,0.284191,1.097161,0.143463,0.456231,0.250483,0.242343,0.242042,fail
9,0.479123,0.735932,0.331358,0.099309,0.614735,0.798563,0.378909,0.676427,0.835905,0.830937,...,0.196057,0.688878,0.233351,0.919684,0.116450,0.354760,0.201799,0.200910,0.203827,fail
10,0.427159,0.617440,0.292005,0.086509,0.618725,0.826349,0.400567,0.762368,0.955875,0.910640,...,0.296709,0.859945,0.256116,0.871864,0.120318,0.403016,0.229667,0.205688,0.197967,pass
11,0.341989,0.526400,0.269920,0.070187,0.565336,0.747939,0.345916,0.792485,0.994880,0.826331,...,0.314364,0.860906,0.210221,0.798548,0.112974,0.367532,0.230799,0.182123,0.183025,pass
12,0.567792,0.854707,0.409655,0.118370,0.786166,1.061127,0.513452,0.900108,1.147551,1.112149,...,0.304443,0.961250,0.316468,1.183372,0.149487,0.473944,0.275744,0.268149,0.266892,pass
13,0.320300,0.508167,0.224031,0.072036,0.405398,0.569362,0.280146,0.436848,0.628048,0.575995,...,0.206916,0.532597,0.165102,0.612771,0.083444,0.238747,0.133005,0.138319,0.131833,pass
14,0.438494,0.662656,0.305160,0.085619,0.487307,0.670779,0.301907,0.616045,0.801995,0.575791,...,0.172694,0.654764,0.176794,0.853159,0.100318,0.256116,0.181799,0.157425,0.182745,pass
15,0.378461,0.561618,0.257107,0.081418,0.419437,0.563468,0.289049,0.489660,0.675711,0.631727,...,0.147400,0.528030,0.161600,0.725709,0.093334,0.262302,0.151381,0.141169,0.158738,pass
16,0.255351,0.399376,0.191290,0.055004,0.417673,0.554075,0.270196,0.523582,0.676429,0.638018,...,0.272581,0.610899,0.181020,0.561632,0.085727,0.266478,0.152166,0.143653,0.124076,pass
17,0.333510,0.435879,0.206711,0.062328,0.472187,0.646829,0.321074,0.650526,0.845132,0.760950,...,0.236075,0.719365,0.200021,0.695130,0.107947,0.313660,0.189873,0.153355,0.156180,pass
18,0.519923,0.700167,0.335829,0.099270,0.529580,0.693611,0.324041,0.724445,0.926079,0.846667,...,0.238762,0.800431,0.198726,1.008861,0.131117,0.366356,0.228803,0.185340,0.225018,pass
19,0.410981,0.607352,0.272463,0.093306,0.652542,0.921526,0.448680,0.754262,0.997391,0.991950,...,0.299003,0.864362,0.268666,0.873541,0.128225,0.419412,0.222660,0.215740,0.196086,pass

BARINEL SCORES

,cp 20,cp 18,h 21,cp 19,cp 5,swap 10,h 0,cp 9,h 1,h 17,...,h 12,cp 6,x 4,cp 15,cp 16,h 2,h 14,cp 7,cp 13,swap 8
sum,0.567491,0.564744,0.563652,0.559021,0.558846,0.556358,0.555713,0.551774,0.551449,0.548244,...,0.54683,0.546154,0.545997,0.541778,0.541093,0.539695,0.536272,0.533335,0.531467,0.527394

TARANTULA SCORES

,cp 20,cp 18,h 21,cp 19,cp 5,swap 10,h 0,cp 9,h 1,h 17,...,h 12,cp 6,x 4,cp 15,cp 16,h 2,h 14,cp 7,cp 13,swap 8
sum,0.567491,0.564744,0.563652,0.559021,0.558846,0.556358,0.555713,0.551774,0.551449,0.548244,...,0.54683,0.546154,0.545997,0.541778,0.541093,0.539695,0.536272,0.533335,0.531467,0.527394

ERROR GATE LOCATION:
11
Now evolving the following mutant:  AddGate_x_inGap_2_.qasm

100%|██████████| 10/10 [00:45<00:00,  4.55s/it]
100%|██████████| 10/10 [00:38<00:00,  3.89s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,cp 8,cp 7,cp 6,x 5,h 4,h 3,h 2,x 1,h 0,pass/fail
0,0.615577,0.907155,0.432846,0.130633,0.707957,0.917034,0.427542,0.828233,1.004232,1.042956,...,0.872758,0.265176,1.220724,0.144898,0.460689,0.261829,0.248373,0.185221,0.273851,fail
1,0.587266,0.864974,0.406022,0.120240,0.648710,0.820476,0.417848,0.878144,1.128820,1.006888,...,0.957224,0.254398,1.222043,0.144420,0.461246,0.281842,0.235015,0.173292,0.273933,fail
2,0.505079,0.754844,0.346025,0.104552,0.654612,0.858577,0.413457,0.753239,0.977321,0.909467,...,0.841829,0.257680,0.979592,0.131739,0.394421,0.232725,0.223609,0.170674,0.220770,fail
3,0.636219,0.928277,0.423279,0.129688,0.807216,1.086302,0.518605,0.952288,1.191985,1.172163,...,1.027763,0.316083,1.301185,0.167881,0.510762,0.294779,0.275179,0.211472,0.290104,fail
4,0.419377,0.634142,0.278583,0.088959,0.644735,0.917060,0.442674,0.682703,0.906726,0.845464,...,0.751616,0.269991,0.822830,0.112407,0.349050,0.194578,0.203269,0.165245,0.178361,fail
5,0.406126,0.588052,0.295176,0.077889,0.681935,0.926799,0.433779,0.855058,1.020646,0.909839,...,0.858413,0.262912,0.930707,0.130229,0.396396,0.250570,0.217303,0.167753,0.211929,fail
6,0.506040,0.788695,0.374968,0.101983,0.680011,0.915637,0.435134,0.784985,1.035104,0.781111,...,0.907187,0.264784,1.084072,0.137754,0.350360,0.243354,0.225319,0.170533,0.232768,fail
7,0.476632,0.747775,0.341468,0.100772,0.833345,1.093093,0.524021,0.974024,1.208814,1.136555,...,1.069364,0.325625,1.049778,0.145078,0.493672,0.279803,0.265381,0.201763,0.238434,fail
8,0.585894,0.927430,0.393607,0.127723,0.758867,1.039130,0.510535,0.742976,1.034989,0.988520,...,0.875739,0.295631,1.119968,0.141737,0.420157,0.232611,0.249993,0.193446,0.239897,fail
9,0.613810,0.925647,0.414337,0.127054,0.781639,1.001660,0.482123,0.908906,1.124924,1.061549,...,0.935776,0.286291,1.260464,0.152485,0.480102,0.283004,0.257079,0.195384,0.279130,fail
10,0.504488,0.726220,0.317432,0.101108,0.631200,0.828347,0.404154,0.748091,0.974931,0.914798,...,0.848650,0.243770,0.984938,0.136185,0.396260,0.231117,0.208651,0.165667,0.218230,pass
11,0.401201,0.631459,0.277065,0.092502,0.589468,0.773820,0.370591,0.703735,0.893538,0.884440,...,0.739797,0.220664,0.864524,0.111035,0.380123,0.208060,0.193442,0.143871,0.193781,pass
12,0.563108,0.790820,0.367681,0.111638,0.598272,0.749366,0.391785,0.870554,1.146619,0.992387,...,1.051077,0.253871,1.179807,0.153051,0.460377,0.282857,0.227865,0.168477,0.261454,pass
13,0.408842,0.610061,0.271484,0.088256,0.557656,0.681062,0.354982,0.712134,0.921567,0.898952,...,0.783035,0.219471,0.919539,0.118115,0.397036,0.224655,0.190076,0.143079,0.207472,pass
14,0.346362,0.505631,0.258132,0.071346,0.609617,0.816718,0.386422,0.744694,0.949706,0.913830,...,0.819751,0.234571,0.783677,0.121668,0.380999,0.219844,0.194716,0.148436,0.178879,pass
15,0.582643,0.871109,0.431911,0.116196,0.727797,0.967596,0.449430,0.886871,1.069612,1.033437,...,0.951003,0.290580,1.215356,0.143072,0.465169,0.280451,0.259977,0.190685,0.275530,pass
16,0.400255,0.589483,0.272592,0.080796,0.483360,0.613998,0.302866,0.577807,0.739691,0.702856,...,0.636873,0.183591,0.849019,0.100988,0.310127,0.189371,0.170306,0.125693,0.190522,pass
17,0.632755,0.878858,0.416220,0.126726,0.824346,1.051804,0.531441,1.106327,1.371136,1.317865,...,1.182521,0.342818,1.342141,0.181595,0.588461,0.339899,0.290490,0.220959,0.303836,pass
18,0.358892,0.578380,0.237756,0.073642,0.562562,0.736453,0.355467,0.595239,0.739647,0.687864,...,0.617039,0.215205,0.687397,0.102760,0.279189,0.164138,0.167164,0.137497,0.146993,pass
19,0.480676,0.731016,0.330357,0.100761,0.552443,0.769820,0.349545,0.608993,0.793343,0.726847,...,0.652888,0.206596,0.912613,0.110216,0.293173,0.179138,0.178103,0.142290,0.193201,pass

BARINEL SCORES

,cp 16,cp 15,h 17,cp 20,cp 19,cp 7,swap 11,x 1,h 2,cp 18,...,h 0,cp 13,h 14,x 5,h 3,cp 8,h 4,h 12,cp 10,swap 9
sum,0.54517,0.541696,0.539829,0.538516,0.538165,0.537184,0.536747,0.536261,0.535674,0.53535,...,0.529212,0.525546,0.525326,0.524177,0.524162,0.523447,0.522131,0.520637,0.514972,0.512132

TARANTULA SCORES

,cp 16,cp 15,h 17,cp 20,cp 19,cp 7,swap 11,x 1,h 2,cp 18,...,h 0,cp 13,h 14,x 5,h 3,cp 8,h 4,h 12,cp 10,swap 9
sum,0.54517,0.541696,0.539829,0.538516,0.538165,0.537184,0.536747,0.536261,0.535674,0.53535,...,0.529212,0.525546,0.525326,0.524177,0.524162,0.523447,0.522131,0.520637,0.514972,0.512132

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_y_inGap_11_.qasm

100%|██████████| 10/10 [00:43<00:00,  4.31s/it]
100%|██████████| 9/9 [00:43<00:00,  4.79s/it]

,h 21,y 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.566206,0.400368,0.866692,0.395702,0.125638,0.639989,0.907756,0.429499,0.756053,1.053132,...,0.306417,0.902263,0.257508,1.101831,0.135466,0.417432,0.234902,0.227140,0.242142,fail
1,0.547645,0.387244,0.845034,0.374441,0.113194,0.662588,0.887168,0.416483,0.827330,1.087315,...,0.311329,0.934888,0.253054,1.122982,0.140282,0.403690,0.252172,0.225588,0.246810,fail
2,0.627556,0.443749,0.971661,0.422666,0.130737,0.765375,0.940413,0.482280,0.861732,1.087607,...,0.285189,0.929037,0.288255,1.255964,0.151539,0.453574,0.266642,0.257269,0.274615,fail
3,0.533907,0.377529,0.805651,0.371811,0.109109,0.693288,0.922899,0.451182,0.734181,0.963200,...,0.273816,0.806389,0.274573,1.006000,0.131459,0.375583,0.220929,0.226213,0.218652,fail
4,0.541825,0.383128,0.828930,0.381476,0.114617,0.675265,0.931106,0.430862,0.805887,1.070045,...,0.290714,0.931081,0.252219,1.106259,0.134007,0.395179,0.254086,0.230523,0.245947,fail
5,0.460010,0.325276,0.734739,0.313649,0.099671,0.626439,0.781315,0.383902,0.728261,0.941024,...,0.338217,0.825723,0.235497,0.912881,0.124191,0.376508,0.211719,0.203309,0.196867,fail
6,0.510727,0.361139,0.800051,0.364311,0.105849,0.609983,0.830555,0.388870,0.687480,0.922820,...,0.238808,0.776882,0.227509,1.000941,0.122849,0.334185,0.214766,0.203083,0.215365,fail
7,0.691570,0.489014,1.063666,0.517092,0.145922,0.793585,1.009721,0.488787,1.016737,1.269919,...,0.336117,1.107943,0.298978,1.482236,0.172771,0.525561,0.325653,0.285237,0.329143,fail
8,0.761591,0.538526,1.119489,0.502297,0.160635,0.788634,0.988918,0.494228,0.902847,1.151419,...,0.284768,1.008761,0.304864,1.487354,0.160782,0.556513,0.304045,0.288963,0.333034,fail
9,0.661566,0.467798,1.005373,0.465508,0.135881,0.817405,1.042810,0.513486,0.981522,1.196915,...,0.269091,1.029356,0.318959,1.376800,0.151002,0.510698,0.305888,0.281087,0.306593,fail
10,0.512556,0.362432,0.775324,0.370705,0.103760,0.593227,0.767282,0.367569,0.770620,0.998588,...,0.298548,0.875332,0.219464,1.067104,0.125722,0.358192,0.239296,0.201073,0.233363,pass
11,0.547244,0.386960,0.789118,0.366584,0.105972,0.746068,0.999304,0.462215,0.837247,1.009051,...,0.266623,0.902981,0.299968,1.051213,0.142780,0.431056,0.250575,0.243373,0.233773,pass
12,0.508452,0.359530,0.779688,0.365960,0.102065,0.693005,0.902403,0.426033,0.811248,1.026250,...,0.284510,0.863153,0.263241,1.048935,0.128553,0.398628,0.247854,0.230909,0.234603,pass
13,0.422503,0.298755,0.654652,0.283739,0.088120,0.572747,0.771158,0.357852,0.598660,0.774211,...,0.272899,0.686258,0.224989,0.779972,0.105923,0.310590,0.170158,0.180453,0.166237,pass
14,0.503695,0.356166,0.737244,0.308249,0.103158,0.571585,0.742913,0.351774,0.629337,0.810074,...,0.179777,0.688277,0.216800,0.972237,0.119803,0.369957,0.204645,0.197906,0.217422,pass
15,0.405728,0.286893,0.628181,0.260274,0.088862,0.601780,0.832436,0.407655,0.582097,0.774471,...,0.202819,0.654265,0.245796,0.734991,0.102276,0.335652,0.173014,0.196819,0.165180,pass
16,0.364341,0.257628,0.561830,0.250268,0.080741,0.497333,0.671904,0.332518,0.509269,0.680144,...,0.189717,0.576493,0.202465,0.704762,0.089948,0.293969,0.160688,0.167898,0.157264,pass
17,0.435935,0.308253,0.626651,0.295689,0.091239,0.531703,0.769255,0.346305,0.644968,0.824678,...,0.216795,0.691058,0.212853,0.801536,0.108461,0.337992,0.185944,0.178951,0.180401,pass
18,0.506841,0.358390,0.724897,0.356236,0.097906,0.611019,0.770276,0.351876,0.807835,0.960521,...,0.270053,0.858788,0.216172,1.036547,0.120130,0.387477,0.243797,0.201201,0.233535,pass

BARINEL SCORES

,cp 5,cp 17,cp 19,cp 18,h 0,y 20,h 21,swap 10,h 2,cp 12,...,h 1,h 3,swap 8,h 13,cp 14,h 16,h 11,cp 6,cp 15,cp 9
sum,0.591168,0.590208,0.590206,0.589803,0.588851,0.583844,0.583844,0.580221,0.580017,0.577559,...,0.574501,0.57431,0.573563,0.572818,0.568231,0.566211,0.564623,0.563334,0.561196,0.560082

TARANTULA SCORES

,cp 5,cp 17,cp 19,cp 18,h 0,y 20,h 21,swap 10,h 2,cp 12,...,h 1,h 3,swap 8,h 13,cp 14,h 16,h 11,cp 6,cp 15,cp 9
sum,0.565481,0.564505,0.564502,0.564093,0.563126,0.55804,0.55804,0.554364,0.554157,0.551665,...,0.548566,0.548372,0.547616,0.546861,0.542218,0.540175,0.538569,0.537266,0.535106,0.533981

ERROR GATE LOCATION:
20
Now evolving the following mutant:  AddGate_x_inGap_1_.qasm

100%|██████████| 10/10 [00:48<00:00,  4.82s/it]
100%|██████████| 10/10 [00:41<00:00,  4.20s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,cp 8,cp 7,cp 6,x 5,h 4,h 3,h 2,h 1,x 0,pass/fail
0,0.606723,0.875631,0.400710,0.122532,0.667666,0.835405,0.416567,0.815686,1.049948,0.952648,...,0.910259,0.249508,1.201051,0.142759,0.436598,0.265865,0.232474,0.270623,0.227260,fail
1,0.698276,1.084264,0.502567,0.141944,0.878216,1.108485,0.535365,1.084620,1.334873,1.167734,...,1.186931,0.338138,1.505356,0.169030,0.544893,0.341032,0.302541,0.331246,0.266761,fail
2,0.617554,0.957682,0.436638,0.129857,0.682865,0.900935,0.437444,0.724659,0.952793,0.888865,...,0.790648,0.258283,1.225444,0.134205,0.410254,0.243349,0.241965,0.269527,0.217480,fail
3,0.660751,0.960398,0.439004,0.142018,0.846878,1.116313,0.563232,0.989969,1.266222,1.277533,...,1.056246,0.340914,1.344256,0.165007,0.561275,0.308479,0.291487,0.302978,0.250644,fail
4,0.757750,1.114779,0.539335,0.152521,0.851043,1.105554,0.525888,0.966977,1.178873,1.094287,...,1.006098,0.320971,1.440120,0.161492,0.495922,0.302534,0.290820,0.322530,0.275744,fail
5,0.608710,0.881945,0.389418,0.126862,0.666818,0.847024,0.443794,0.860357,1.144266,1.090927,...,0.989158,0.268854,1.209457,0.147243,0.491415,0.281407,0.245765,0.274585,0.228395,fail
6,0.572990,0.861048,0.397013,0.118525,0.773424,1.046924,0.500683,0.892123,1.132737,1.052389,...,0.973855,0.311816,1.188895,0.154975,0.460625,0.270150,0.259896,0.260545,0.212135,fail
7,0.677295,0.953879,0.443957,0.142187,0.686730,0.925178,0.434715,0.891609,1.188097,1.078591,...,1.025799,0.258712,1.311289,0.157289,0.480784,0.285295,0.244815,0.291737,0.248996,fail
8,0.585355,0.893371,0.412033,0.117719,0.588759,0.735679,0.340494,0.659442,0.806470,0.770742,...,0.670992,0.200129,1.110508,0.114246,0.335551,0.212293,0.201233,0.243794,0.211121,fail
9,0.622282,0.930644,0.424073,0.127044,0.801657,1.069896,0.512357,0.967394,1.240342,1.140646,...,1.080907,0.318878,1.267077,0.159222,0.510543,0.297223,0.273270,0.281536,0.234288,fail
10,0.411616,0.608012,0.280445,0.089553,0.613825,0.858836,0.394880,0.691310,0.909703,0.913619,...,0.768604,0.231420,0.775126,0.119441,0.357450,0.195349,0.192044,0.175167,0.149742,pass
11,0.502381,0.722232,0.329933,0.100900,0.631365,0.830319,0.398685,0.801464,1.036264,0.973780,...,0.883410,0.243525,0.940643,0.136984,0.386604,0.226430,0.201236,0.207036,0.186775,pass
12,0.582243,0.901414,0.407908,0.124980,0.652985,0.804115,0.400586,0.785722,1.014191,0.997458,...,0.880917,0.249993,1.171811,0.138905,0.429414,0.242107,0.226345,0.254986,0.212302,pass
13,0.692257,1.062179,0.465474,0.146244,0.857157,1.136820,0.559517,0.997588,1.303257,1.219027,...,1.074816,0.335606,1.414337,0.175131,0.547305,0.310779,0.292998,0.310414,0.254915,pass
14,0.409309,0.653708,0.297363,0.078808,0.638946,0.865313,0.417707,0.701780,0.892185,0.793736,...,0.747709,0.262339,0.796792,0.119276,0.311104,0.193255,0.195887,0.167192,0.146246,pass
15,0.512181,0.752067,0.322789,0.107372,0.625810,0.844784,0.408260,0.630114,0.832251,0.932141,...,0.704114,0.253574,0.868283,0.130190,0.358122,0.184819,0.206400,0.193749,0.172799,pass
16,0.309243,0.420046,0.181137,0.059446,0.384216,0.514985,0.248765,0.538403,0.715325,0.624669,...,0.639731,0.151794,0.620813,0.094382,0.265571,0.162317,0.126661,0.137863,0.121475,pass
17,0.693431,1.057283,0.456124,0.143591,0.815618,1.042954,0.529771,0.920448,1.194357,1.149323,...,1.048070,0.330515,1.390422,0.162451,0.522132,0.294652,0.282536,0.302842,0.252489,pass
18,0.672929,1.008182,0.433925,0.139206,0.827879,1.020110,0.501910,0.926524,1.129497,1.190020,...,0.948446,0.301809,1.331723,0.162577,0.516313,0.287107,0.275988,0.298468,0.253585,pass
19,0.607635,0.926492,0.433702,0.122249,0.741443,1.017022,0.459541,0.844808,1.066309,0.938749,...,0.900824,0.279839,1.193999,0.142225,0.415281,0.256107,0.246043,0.260387,0.218560,pass

BARINEL SCORES

,h 1,cp 6,cp 19,x 0,h 3,h 21,cp 18,cp 20,h 2,h 4,...,cp 13,h 17,swap 11,cp 15,x 5,cp 7,cp 16,h 12,cp 10,swap 9
sum,0.55245,0.54933,0.548536,0.546518,0.544056,0.542982,0.542913,0.539773,0.535,0.534998,...,0.528083,0.523003,0.521831,0.521645,0.521459,0.520502,0.520297,0.519308,0.51764,0.499551

TARANTULA SCORES

,h 1,cp 6,cp 19,x 0,h 3,h 21,cp 18,cp 20,h 2,h 4,...,cp 13,h 17,swap 11,cp 15,x 5,cp 7,cp 16,h 12,cp 10,swap 9
sum,0.55245,0.54933,0.548536,0.546518,0.544056,0.542982,0.542913,0.539773,0.535,0.534998,...,0.528083,0.523003,0.521831,0.521645,0.521459,0.520502,0.520297,0.519308,0.51764,0.499551

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_y_inGap_14_.qasm

100%|██████████| 10/10 [00:41<00:00,  4.14s/it]
100%|██████████| 10/10 [00:40<00:00,  4.08s/it]

,h 21,y 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.747639,0.338215,1.094576,0.508109,0.155421,0.755256,0.969201,0.466787,0.916288,1.160020,...,0.300490,1.047728,0.292346,1.498375,0.160393,0.512251,0.308699,0.281832,0.335605,fail
1,0.536932,0.577726,0.848080,0.372159,0.118543,0.828306,1.084496,0.541760,0.852066,1.095356,...,0.291683,0.909334,0.329335,1.111413,0.148871,0.472737,0.254000,0.267527,0.242086,fail
2,0.628240,0.377178,0.934031,0.448180,0.130263,0.716224,0.954225,0.467778,0.842689,1.083828,...,0.269111,0.954704,0.280174,1.293277,0.147860,0.454708,0.272634,0.250765,0.284571,fail
3,0.640866,0.490339,0.969540,0.427407,0.128588,0.809257,1.012387,0.498098,0.892895,1.137286,...,0.349893,0.979483,0.299454,1.218297,0.152310,0.473221,0.269525,0.260843,0.271767,fail
4,0.383381,0.398063,0.590345,0.257858,0.078617,0.600771,0.811528,0.407160,0.756257,1.027427,...,0.360266,0.885061,0.242721,0.831148,0.122706,0.369433,0.221832,0.190971,0.181683,fail
5,0.720370,0.629863,1.115008,0.486732,0.149672,0.970275,1.222998,0.590989,1.046118,1.245016,...,0.240634,1.046867,0.360998,1.477366,0.173403,0.571878,0.321084,0.321738,0.331940,fail
6,0.572414,0.498932,0.876765,0.362219,0.121269,0.788595,1.023416,0.508977,0.852081,1.102384,...,0.289424,0.957405,0.309985,1.154208,0.147426,0.476382,0.264281,0.261494,0.256333,fail
7,0.535869,0.482918,0.843259,0.375683,0.120505,0.740346,0.991817,0.475816,0.899824,1.170003,...,0.329296,0.986626,0.280361,1.108976,0.139673,0.473115,0.267025,0.246044,0.247234,fail
8,0.567406,0.542517,0.845836,0.364859,0.118171,0.826914,1.041563,0.528862,0.944726,1.190474,...,0.346128,1.038812,0.327119,1.174646,0.153782,0.531076,0.288410,0.276415,0.267658,fail
9,0.586928,0.424428,0.898446,0.410488,0.125635,0.719630,0.965330,0.458467,0.868412,1.131943,...,0.358289,0.988541,0.278930,1.121650,0.138937,0.464112,0.260561,0.243789,0.252110,fail
10,0.461001,0.472655,0.686575,0.322548,0.093283,0.714109,0.993905,0.461313,0.809402,1.051785,...,0.335195,0.900501,0.283891,0.911942,0.137771,0.391017,0.225926,0.220606,0.198873,pass
11,0.299257,0.285256,0.440219,0.209111,0.058012,0.446941,0.631583,0.282066,0.523793,0.642125,...,0.175766,0.546786,0.175153,0.573306,0.083288,0.240208,0.145295,0.140490,0.128358,pass
12,0.276180,0.249014,0.424923,0.187547,0.060439,0.388389,0.514462,0.254076,0.458387,0.619251,...,0.170783,0.533400,0.145239,0.590556,0.072275,0.251377,0.144863,0.130453,0.135153,pass
13,0.548087,0.453594,0.813301,0.374904,0.112792,0.740620,0.971457,0.481196,0.847215,1.091002,...,0.319185,0.961222,0.295854,1.092582,0.146357,0.433587,0.257379,0.246109,0.241445,pass
14,0.379682,0.392185,0.601942,0.266823,0.078965,0.569579,0.731148,0.365828,0.629373,0.794775,...,0.230665,0.683680,0.235418,0.795675,0.105794,0.317172,0.184191,0.186742,0.171799,pass
15,0.318233,0.228018,0.444548,0.201672,0.066341,0.413218,0.542597,0.274582,0.511492,0.650572,...,0.182295,0.577891,0.180696,0.681839,0.088466,0.315489,0.165761,0.153522,0.155729,pass
16,0.451734,0.390883,0.667211,0.310368,0.089325,0.626625,0.870778,0.402907,0.720121,0.893906,...,0.214570,0.787018,0.254804,0.900257,0.114909,0.373179,0.216844,0.210647,0.205129,pass
17,0.480966,0.322468,0.716367,0.366380,0.102562,0.594443,0.809162,0.397231,0.712399,0.903927,...,0.218632,0.794724,0.251366,1.046667,0.116748,0.387192,0.234743,0.219546,0.232791,pass
18,0.540045,0.204426,0.812300,0.378539,0.110463,0.510123,0.691279,0.335249,0.619667,0.861656,...,0.239509,0.742391,0.191149,1.040032,0.113523,0.296763,0.201238,0.180996,0.222300,pass
19,0.420525,0.245337,0.624747,0.290899,0.088193,0.464527,0.629844,0.282966,0.529077,0.704989,...,0.242677,0.638303,0.167065,0.766252,0.097594,0.264676,0.161031,0.152753,0.166253,pass

BARINEL SCORES

,y 20,h 3,h 11,cp 17,cp 19,h 0,cp 5,h 16,h 21,cp 9,...,cp 14,h 13,cp 12,cp 18,x 4,cp 6,cp 7,cp 15,swap 10,swap 8
sum,0.594724,0.594693,0.593819,0.59167,0.591282,0.589776,0.588046,0.586471,0.58639,0.586368,...,0.582956,0.582405,0.580013,0.579806,0.579747,0.579195,0.577493,0.577041,0.574883,0.573743

TARANTULA SCORES

,y 20,h 3,h 11,cp 17,cp 19,h 0,cp 5,h 16,h 21,cp 9,...,cp 14,h 13,cp 12,cp 18,x 4,cp 6,cp 7,cp 15,swap 10,swap 8
sum,0.594724,0.594693,0.593819,0.59167,0.591282,0.589776,0.588046,0.586471,0.58639,0.586368,...,0.582956,0.582405,0.580013,0.579806,0.579747,0.579195,0.577493,0.577041,0.574883,0.573743

ERROR GATE LOCATION:
20
Now evolving the following mutant:  AddGate_swap_inGap_10_.qasm

100%|██████████| 10/10 [00:33<00:00,  3.39s/it]
100%|██████████| 10/10 [00:33<00:00,  3.37s/it]

,h 21,cp 20,cp 19,cp 18,h 17,swap 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.482689,0.767307,0.339323,0.104519,0.579830,0.314235,0.895857,0.451444,0.670801,0.885377,...,0.183774,0.650926,0.229538,0.645688,0.096765,0.271273,0.164843,0.168726,0.157519,fail
1,0.520634,0.789896,0.351961,0.113305,0.725241,0.430169,0.961636,0.481565,0.744888,0.924388,...,0.196709,0.695636,0.265833,0.751773,0.110289,0.327078,0.180746,0.194156,0.175497,fail
2,0.394123,0.541311,0.259170,0.078376,0.626018,0.453283,0.757460,0.378968,0.757275,0.898173,...,0.170136,0.685303,0.216001,0.683586,0.100695,0.303336,0.179073,0.155733,0.158153,fail
3,0.427583,0.669814,0.309165,0.096161,0.719017,0.372507,0.847134,0.411251,0.781369,0.946359,...,0.233150,0.749382,0.234583,0.741908,0.104556,0.342204,0.196454,0.173299,0.179330,fail
4,0.497713,0.735705,0.360099,0.102443,0.678561,0.427015,0.986880,0.469141,0.858628,1.090828,...,0.242870,0.823762,0.253161,0.756111,0.112414,0.336317,0.209311,0.187487,0.183097,fail
5,0.566572,0.894984,0.385885,0.119764,0.804741,0.384037,1.048568,0.536283,0.938103,1.155430,...,0.227936,0.875634,0.290063,0.883928,0.126675,0.383123,0.230358,0.215107,0.215843,fail
6,0.474789,0.731158,0.314315,0.094904,0.749574,0.450884,0.850651,0.396644,0.777556,0.952706,...,0.210487,0.745419,0.227382,0.796380,0.109106,0.299437,0.191219,0.167403,0.184766,fail
7,0.469312,0.723664,0.317591,0.107016,0.697397,0.453145,0.874590,0.448407,0.793786,1.039653,...,0.232974,0.797905,0.237582,0.822484,0.111472,0.311478,0.201117,0.172263,0.194368,fail
8,0.392481,0.567476,0.246661,0.086753,0.537985,0.314115,0.692888,0.374888,0.567707,0.735981,...,0.221157,0.578956,0.211392,0.509620,0.086117,0.279739,0.141244,0.149561,0.121826,fail
9,0.317667,0.459056,0.226863,0.063884,0.644191,0.416867,0.641229,0.313220,0.699386,0.842449,...,0.189124,0.669009,0.182860,0.669019,0.087896,0.288065,0.173719,0.134864,0.157240,fail
10,0.505414,0.738540,0.329615,0.104543,0.518533,0.282009,0.894123,0.436971,0.695450,0.899430,...,0.222458,0.685516,0.237132,0.598836,0.098284,0.289661,0.171366,0.168152,0.148055,pass
11,0.332354,0.498448,0.227697,0.067900,0.377272,0.235173,0.620628,0.304517,0.493242,0.637341,...,0.158501,0.481326,0.164339,0.427038,0.070067,0.197598,0.116836,0.118026,0.099435,pass
12,0.353057,0.527356,0.235215,0.073536,0.348094,0.211750,0.616482,0.290624,0.379892,0.506769,...,0.131438,0.388420,0.157135,0.377666,0.062533,0.150143,0.089257,0.109908,0.085456,pass
13,0.490665,0.740199,0.347643,0.105153,0.646991,0.423758,0.947708,0.475058,0.768003,1.043410,...,0.230418,0.783337,0.244717,0.734778,0.105766,0.309515,0.195280,0.175975,0.173629,pass
14,0.673748,1.030806,0.474018,0.135470,0.779524,0.347082,1.259790,0.594400,0.932182,1.122445,...,0.209776,0.854854,0.336854,0.859965,0.119366,0.371168,0.226861,0.248048,0.210041,pass
15,0.511805,0.723114,0.353606,0.100250,0.660036,0.434018,0.973441,0.446347,0.714927,0.870715,...,0.173990,0.660699,0.249871,0.672813,0.105146,0.297933,0.171569,0.178659,0.159645,pass
16,0.410450,0.605124,0.242368,0.087099,0.577591,0.335785,0.680578,0.368509,0.560089,0.740230,...,0.226458,0.590270,0.207379,0.553691,0.088201,0.271831,0.142927,0.143161,0.128685,pass
17,0.444390,0.640858,0.317247,0.094135,0.447181,0.198290,0.850949,0.405641,0.580530,0.730338,...,0.179187,0.555047,0.227420,0.467668,0.075689,0.257885,0.140109,0.167250,0.120808,pass
18,0.684099,1.056020,0.452901,0.144808,0.758787,0.369279,1.199059,0.581002,0.794491,1.024959,...,0.254147,0.777130,0.320501,0.798101,0.119837,0.324979,0.190437,0.230423,0.183486,pass
19,0.702829,0.989138,0.463427,0.140605,0.711429,0.425701,1.248261,0.596544,0.879984,1.104731,...,0.297480,0.870571,0.347003,0.766193,0.128882,0.383305,0.207750,0.248096,0.181545,pass

BARINEL SCORES

,swap 16,h 17,cp 5,h 0,h 2,h 13,h 11,h 3,cp 7,cp 12,...,cp 9,swap 8,h 1,cp 14,cp 6,cp 15,cp 18,cp 20,cp 19,h 21
sum,0.551752,0.537223,0.537128,0.536797,0.530634,0.527477,0.525584,0.524018,0.522443,0.521788,...,0.510143,0.502918,0.490146,0.486429,0.485131,0.479434,0.478627,0.476811,0.474621,0.47072

TARANTULA SCORES

,swap 16,h 17,cp 5,h 0,h 2,h 13,h 11,h 3,cp 7,cp 12,...,cp 9,swap 8,h 1,cp 14,cp 6,cp 15,cp 18,cp 20,cp 19,h 21
sum,0.551752,0.537223,0.537128,0.536797,0.530634,0.527477,0.525584,0.524018,0.522443,0.521788,...,0.510143,0.502918,0.490146,0.486429,0.485131,0.479434,0.478627,0.476811,0.474621,0.47072

ERROR GATE LOCATION:
16
Now evolving the following mutant:  AddGate_z_inGap_9_.qasm

100%|██████████| 10/10 [00:37<00:00,  3.72s/it]
100%|██████████| 10/10 [00:37<00:00,  3.79s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,z 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.522452,0.740134,0.358335,0.102698,0.649316,0.859906,0.391349,0.844837,0.314077,1.031507,...,0.276629,0.911276,0.251112,1.046001,0.131938,0.425770,0.254589,0.221320,0.238851,fail
1,0.561882,0.795095,0.342135,0.114031,0.745520,0.973546,0.492068,0.855943,0.318097,1.111269,...,0.279893,0.916987,0.301675,1.090645,0.143890,0.481495,0.258436,0.246134,0.244810,fail
2,0.634258,0.936583,0.414082,0.126452,0.704965,0.888056,0.428675,0.903855,0.325779,1.135854,...,0.288548,0.986379,0.259506,1.284806,0.158126,0.477471,0.285776,0.240345,0.285262,fail
3,0.461741,0.670513,0.302091,0.095510,0.573828,0.725654,0.367957,0.731412,0.284419,0.987344,...,0.291488,0.856262,0.224320,0.989537,0.124397,0.406585,0.235484,0.198890,0.223098,fail
4,0.541947,0.766585,0.350722,0.116511,0.608119,0.789084,0.401349,0.817933,0.319364,1.063133,...,0.319336,0.931442,0.256183,1.067977,0.136527,0.462714,0.256892,0.226207,0.244989,fail
5,0.698010,1.026645,0.496867,0.143186,0.782443,1.029273,0.493483,1.047724,0.392082,1.362890,...,0.380554,1.170521,0.288691,1.439579,0.167127,0.495853,0.326016,0.272215,0.318809,fail
6,0.566928,0.856964,0.375829,0.112765,0.561350,0.764417,0.362717,0.729383,0.285945,0.986386,...,0.285094,0.859718,0.227720,1.075909,0.127731,0.373832,0.230180,0.203779,0.234027,fail
7,0.477794,0.676060,0.323751,0.101480,0.593577,0.778050,0.398264,0.766737,0.290440,0.999428,...,0.301828,0.878447,0.243929,0.968063,0.135153,0.419007,0.239190,0.212296,0.219430,fail
8,0.504519,0.738973,0.353283,0.108793,0.686509,0.958778,0.445631,0.845972,0.308998,1.104910,...,0.272394,0.934316,0.262810,1.079451,0.142276,0.455726,0.259057,0.229783,0.241687,fail
9,0.566633,0.836674,0.412998,0.110008,0.619839,0.804346,0.359223,0.832124,0.305788,1.026674,...,0.299874,0.929720,0.227336,1.151194,0.135246,0.409704,0.266865,0.223589,0.261135,fail
10,0.609358,0.915620,0.434707,0.122625,0.660145,0.874034,0.403572,0.729316,0.265144,0.905302,...,0.255289,0.806268,0.253296,1.149312,0.134119,0.387557,0.232269,0.229727,0.252541,pass
11,0.346179,0.554637,0.229034,0.076142,0.421227,0.531669,0.255608,0.431795,0.157172,0.562837,...,0.151003,0.488033,0.161560,0.692045,0.083994,0.270026,0.142237,0.146462,0.153186,pass
12,0.605055,0.888191,0.427182,0.118153,0.664297,0.869047,0.407614,0.866825,0.299918,1.058014,...,0.264502,0.920947,0.254966,1.201796,0.138139,0.424013,0.265934,0.230184,0.265346,pass
13,0.618126,0.936782,0.439034,0.128508,0.619476,0.737415,0.355784,0.776076,0.260926,0.943750,...,0.235722,0.820780,0.213871,1.232283,0.127354,0.406990,0.250508,0.219360,0.273014,pass
14,0.282939,0.422363,0.189509,0.057305,0.468993,0.642297,0.302387,0.546807,0.216768,0.729285,...,0.230345,0.639007,0.182350,0.593233,0.091165,0.279267,0.160660,0.144773,0.132699,pass
15,0.627934,0.974081,0.463964,0.130560,0.769110,1.033344,0.475688,0.949248,0.301100,1.135067,...,0.198207,0.944551,0.297528,1.360246,0.141376,0.481321,0.293898,0.271168,0.300087,pass
16,0.493546,0.756681,0.345834,0.108277,0.550339,0.752093,0.356646,0.581790,0.235503,0.824458,...,0.236585,0.684037,0.199609,0.924823,0.107591,0.317471,0.189419,0.187858,0.204080,pass
17,0.396161,0.563322,0.265872,0.084395,0.597611,0.846660,0.413604,0.741657,0.290457,0.984280,...,0.271880,0.842513,0.255870,0.861710,0.124655,0.390785,0.226106,0.206714,0.193536,pass
18,0.625080,0.927668,0.443953,0.127586,0.802159,1.073257,0.491687,0.945848,0.339172,1.155801,...,0.300111,1.015274,0.310655,1.232944,0.145597,0.473748,0.283775,0.268674,0.276325,pass
19,0.569256,0.795742,0.389259,0.109856,0.672459,0.928514,0.417963,0.852758,0.306055,1.048826,...,0.226197,0.906669,0.256961,1.119095,0.141699,0.401887,0.253685,0.222692,0.246584,pass

BARINEL SCORES

,swap 8,z 13,cp 7,h 11,cp 12,h 3,cp 9,h 2,x 4,h 14,...,h 21,h 1,cp 15,cp 6,cp 18,h 17,swap 10,cp 20,cp 16,cp 19
sum,0.558317,0.540636,0.537464,0.5366,0.53626,0.534891,0.534432,0.531968,0.531599,0.530187,...,0.516925,0.51669,0.516217,0.515884,0.515498,0.51175,0.51113,0.509796,0.508386,0.506913

TARANTULA SCORES

,swap 8,z 13,cp 7,h 11,cp 12,h 3,cp 9,h 2,x 4,h 14,...,h 21,h 1,cp 15,cp 6,cp 18,h 17,swap 10,cp 20,cp 16,cp 19
sum,0.558317,0.540636,0.537464,0.5366,0.53626,0.534891,0.534432,0.531968,0.531599,0.530187,...,0.516925,0.51669,0.516217,0.515884,0.515498,0.51175,0.51113,0.509796,0.508386,0.506913

ERROR GATE LOCATION:
13
Now evolving the following mutant:  AddGate_z_inGap_6_.qasm

100%|██████████| 10/10 [00:38<00:00,  3.87s/it]
100%|██████████| 10/10 [00:39<00:00,  3.94s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.452477,0.681024,0.310927,0.094635,0.631165,0.829797,0.405839,0.722100,0.922736,0.912165,...,0.253945,0.815072,0.248910,0.947829,0.124390,0.399702,0.227237,0.213798,0.215211,fail
1,0.765956,1.153268,0.508951,0.159103,0.773542,0.963490,0.471562,0.945183,1.194420,1.134244,...,0.301433,1.044530,0.288387,1.523489,0.162975,0.517560,0.308341,0.279018,0.337043,fail
2,0.560234,0.878740,0.362618,0.121785,0.789129,1.011998,0.505313,0.769243,1.003183,1.093730,...,0.277332,0.869396,0.320854,1.106180,0.148408,0.468360,0.242030,0.265537,0.243299,fail
3,0.552575,0.813202,0.366196,0.110194,0.624510,0.791951,0.381922,0.764299,0.942435,0.852528,...,0.230676,0.816194,0.236985,1.078850,0.127337,0.393310,0.243773,0.216402,0.243083,fail
4,0.790554,1.111715,0.530986,0.159898,0.858807,1.092427,0.526925,1.106633,1.330332,1.381904,...,0.325628,1.170817,0.339305,1.592823,0.190295,0.607755,0.350172,0.314039,0.358991,fail
5,0.609992,0.935887,0.416400,0.133613,0.642712,0.854278,0.398371,0.714804,0.975678,0.946508,...,0.289104,0.853355,0.235393,1.167158,0.139785,0.405258,0.228483,0.222723,0.252012,fail
6,0.439258,0.621916,0.276676,0.087298,0.638753,0.845877,0.422988,0.782109,1.011952,0.948020,...,0.298225,0.880518,0.259488,0.921693,0.130434,0.399797,0.236808,0.210134,0.207395,fail
7,0.571704,0.817184,0.382433,0.119449,0.647812,0.822131,0.400515,0.765559,0.987683,1.040017,...,0.304298,0.871088,0.243119,1.100723,0.146854,0.435338,0.241461,0.224653,0.246757,fail
8,0.655103,0.990815,0.422850,0.137425,0.754433,0.953848,0.484281,0.855059,1.104666,1.085989,...,0.255199,0.931552,0.290870,1.306888,0.148007,0.484101,0.276156,0.265328,0.290630,fail
9,0.436872,0.591006,0.275094,0.087981,0.562840,0.721782,0.367468,0.817370,1.040639,0.980769,...,0.306301,0.896232,0.231020,0.941091,0.129826,0.418718,0.247648,0.194968,0.214803,fail
10,0.609582,0.884868,0.397555,0.126838,0.760281,0.981820,0.489218,0.906554,1.196767,1.164538,...,0.360881,1.046911,0.302894,1.206700,0.155583,0.508014,0.284128,0.264122,0.274183,pass
11,0.490008,0.661117,0.340567,0.091692,0.687645,0.940001,0.456127,1.042787,1.324769,1.033073,...,0.386634,1.136427,0.273402,1.065059,0.149953,0.451112,0.297234,0.224003,0.239060,pass
12,0.732686,1.143341,0.511684,0.154991,0.878484,1.138738,0.567523,1.016860,1.297179,1.170034,...,0.287555,1.063206,0.341798,1.488888,0.172116,0.530355,0.316892,0.303309,0.322937,pass
13,0.615941,0.836504,0.398429,0.122746,0.748756,0.943740,0.482144,1.001277,1.246886,1.277723,...,0.396637,1.115958,0.310380,1.246856,0.161614,0.557156,0.310720,0.267589,0.288799,pass
14,0.440200,0.664074,0.290641,0.088978,0.655278,0.875044,0.430026,0.778396,1.033594,0.944562,...,0.313465,0.869583,0.250184,0.893733,0.137503,0.379251,0.223500,0.202143,0.192985,pass
15,0.609931,0.876759,0.437185,0.122694,0.684315,0.949795,0.444549,0.926897,1.193612,1.032717,...,0.335228,1.052688,0.279255,1.260924,0.150826,0.468081,0.292326,0.246662,0.281779,pass
16,0.562070,0.912591,0.363383,0.124940,0.758957,0.980347,0.487474,0.683213,0.888855,0.958314,...,0.215556,0.755387,0.300943,1.093037,0.126813,0.418505,0.214969,0.251803,0.236630,pass
17,0.514742,0.776082,0.356509,0.107758,0.625637,0.774738,0.360660,0.716925,0.826289,0.897617,...,0.171167,0.709561,0.228663,1.050138,0.114650,0.408044,0.225909,0.212908,0.236716,pass
18,0.595072,0.876325,0.408200,0.122625,0.697938,0.886071,0.427653,0.840328,1.039462,1.001513,...,0.217323,0.888771,0.255948,1.248910,0.137320,0.457542,0.275181,0.247473,0.284786,pass
19,0.509478,0.738237,0.343067,0.106609,0.615938,0.788681,0.375897,0.757878,0.910109,0.925999,...,0.224182,0.794882,0.238992,1.032825,0.118127,0.415436,0.234373,0.215849,0.234977,pass

BARINEL SCORES

,swap 11,cp 18,z 10,cp 9,h 21,cp 20,x 4,cp 5,h 0,cp 19,...,h 3,swap 8,h 17,h 2,cp 7,cp 6,cp 15,cp 16,cp 13,h 14
sum,0.510731,0.508716,0.508636,0.507396,0.506731,0.506627,0.504143,0.502141,0.501573,0.500384,...,0.496515,0.494219,0.493249,0.493072,0.492342,0.491955,0.491218,0.489767,0.489665,0.487325

TARANTULA SCORES

,swap 11,cp 18,z 10,cp 9,h 21,cp 20,x 4,cp 5,h 0,cp 19,...,h 3,swap 8,h 17,h 2,cp 7,cp 6,cp 15,cp 16,cp 13,h 14
sum,0.510731,0.508716,0.508636,0.507396,0.506731,0.506627,0.504143,0.502141,0.501573,0.500384,...,0.496515,0.494219,0.493249,0.493072,0.492342,0.491955,0.491218,0.489767,0.489665,0.487325

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_rzz_inGap_10_.qasm

100%|██████████| 10/10 [00:35<00:00,  3.55s/it]
100%|██████████| 10/10 [00:35<00:00,  3.59s/it]

,h 21,cp 20,cp 19,cp 18,h 17,rzz 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.468455,0.691998,0.325115,0.100829,0.679747,0.392736,0.961708,0.467488,0.726277,0.976729,...,0.327691,0.833163,0.283346,0.881380,0.129879,0.383447,0.207598,0.217225,0.190599,fail
1,0.474514,0.729943,0.348196,0.097059,0.672832,0.345548,0.928870,0.437521,0.774894,1.014091,...,0.324325,0.866493,0.262852,0.959487,0.127264,0.376831,0.227190,0.215678,0.210926,fail
2,0.426875,0.629272,0.276931,0.083364,0.704265,0.391156,0.936168,0.470130,0.799839,1.003950,...,0.300859,0.860340,0.290613,0.866587,0.130508,0.385870,0.222180,0.216373,0.188428,fail
3,0.606735,0.872177,0.422398,0.121421,0.674538,0.381333,0.938738,0.446676,0.794213,1.062099,...,0.282380,0.940550,0.267241,1.200467,0.146236,0.399465,0.256544,0.234240,0.261772,fail
4,0.537993,0.772241,0.386977,0.108251,0.736460,0.389116,0.987942,0.479086,0.988580,1.231066,...,0.371389,1.090572,0.309077,1.178972,0.152267,0.475985,0.292619,0.254192,0.260135,fail
5,0.444544,0.608453,0.308483,0.090713,0.634750,0.425258,0.948879,0.471998,0.770356,1.073878,...,0.388454,0.946507,0.288945,0.856307,0.135828,0.360955,0.222228,0.209589,0.183419,fail
6,0.630942,0.938128,0.442575,0.132890,0.698784,0.360897,0.971577,0.461840,0.770391,0.991356,...,0.198915,0.814680,0.273597,1.186586,0.135467,0.410899,0.237610,0.236389,0.256097,fail
7,0.628010,0.930009,0.434536,0.130195,0.814697,0.403531,1.053629,0.520562,0.949515,1.197499,...,0.297073,1.060316,0.319655,1.321428,0.160185,0.513319,0.303747,0.280344,0.295701,fail
8,0.442833,0.669918,0.280759,0.096669,0.661011,0.317405,0.822551,0.425286,0.811949,1.063702,...,0.347907,0.935787,0.263287,0.961672,0.136406,0.482668,0.253115,0.226319,0.224731,fail
9,0.494789,0.736776,0.336094,0.101626,0.739893,0.391507,0.983995,0.487090,0.862008,1.114281,...,0.355402,0.944106,0.300903,0.977777,0.148177,0.434731,0.247731,0.238604,0.215292,fail
10,0.561101,0.815593,0.364369,0.116618,0.728141,0.410286,0.978694,0.504360,0.807791,1.097940,...,0.358028,0.963687,0.313506,1.081911,0.145883,0.467297,0.254058,0.252102,0.241067,pass
11,0.474814,0.734779,0.317314,0.105624,0.574012,0.289910,0.780410,0.373109,0.563664,0.780886,...,0.221148,0.660264,0.211563,0.861559,0.114860,0.319802,0.172386,0.184030,0.184078,pass
12,0.699424,1.010511,0.474257,0.141427,0.715056,0.356983,0.915786,0.439350,0.856971,1.093586,...,0.270429,0.937467,0.264499,1.336630,0.157722,0.459291,0.278990,0.252935,0.298799,pass
13,0.564008,0.807845,0.371328,0.113720,0.664234,0.328299,0.822386,0.412877,0.904404,1.119587,...,0.312576,0.996869,0.271153,1.213496,0.144659,0.490273,0.287807,0.243073,0.274501,pass
14,0.584734,0.907592,0.415812,0.124521,0.640709,0.278004,0.811293,0.379262,0.674876,0.864529,...,0.284994,0.800619,0.235003,1.123838,0.128116,0.385525,0.220150,0.221668,0.246602,pass
15,0.556863,0.868273,0.390022,0.116185,0.653867,0.298918,0.859288,0.405786,0.811291,1.055785,...,0.268202,0.909940,0.251470,1.180618,0.137535,0.416715,0.260261,0.232107,0.258122,pass
16,0.428958,0.655963,0.286143,0.087969,0.623544,0.301013,0.826343,0.377389,0.695299,0.881686,...,0.265024,0.766082,0.228793,0.827635,0.116268,0.348055,0.197583,0.191981,0.185838,pass
17,0.586666,0.874938,0.423170,0.120987,0.703958,0.320783,0.928489,0.435396,0.877968,1.067512,...,0.216270,0.929315,0.270379,1.239587,0.135485,0.468798,0.280880,0.250943,0.280580,pass
18,0.411079,0.623615,0.291886,0.084896,0.499768,0.255254,0.686574,0.310428,0.571305,0.742741,...,0.232690,0.648946,0.182958,0.780829,0.102511,0.257439,0.165405,0.158135,0.164208,pass
19,0.390570,0.581254,0.261574,0.083124,0.478663,0.241923,0.614679,0.313029,0.590171,0.799630,...,0.250644,0.689599,0.184689,0.793275,0.101350,0.334998,0.187771,0.162247,0.176723,pass

BARINEL SCORES

,rzz 16,swap 8,cp 6,cp 14,cp 15,swap 10,cp 12,cp 9,h 13,cp 7,...,x 4,h 1,h 2,h 3,cp 5,cp 19,h 0,h 21,cp 18,cp 20
sum,0.552117,0.543782,0.54224,0.541578,0.536888,0.531156,0.530267,0.529748,0.52866,0.528125,...,0.521929,0.520068,0.517303,0.516885,0.498831,0.497638,0.497453,0.495077,0.492574,0.49025

TARANTULA SCORES

,rzz 16,swap 8,cp 6,cp 14,cp 15,swap 10,cp 12,cp 9,h 13,cp 7,...,x 4,h 1,h 2,h 3,cp 5,cp 19,h 0,h 21,cp 18,cp 20
sum,0.552117,0.543782,0.54224,0.541578,0.536888,0.531156,0.530267,0.529748,0.52866,0.528125,...,0.521929,0.520068,0.517303,0.516885,0.498831,0.497638,0.497453,0.495077,0.492574,0.49025

ERROR GATE LOCATION:
16

,Program,path_to_mutant,exam_score
0,AddGate_rzz_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.045455
1,AddGate_z_inGap_6_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.136364
2,AddGate_z_inGap_9_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.090909
3,AddGate_swap_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.045455
4,AddGate_y_inGap_14_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.045455
5,AddGate_x_inGap_1_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.181818
6,AddGate_y_inGap_11_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.272727
7,AddGate_x_inGap_2_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.363636
8,AddGate_z_inGap_7_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.5
9,AddGate_p_inGap_11_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.181818
10,AddGate_swap_inGap_11_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.090909
11,AddGate_rxx_inGap_11_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.045455
12,AddGate_z_inGap_11_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.181818
13,AddGate_y_inGap_15_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.136364
14,AddGate_y_inGap_2_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.363636
15,AddGate_ccx_inGap_6_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.772727
16,AddGate_ry_inGap_11_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.090909
17,AddGate_p_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.045455
18,AddGate_z_inGap_8_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.409091
19,AddGate_x_inGap_3_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.409091
20,AddGate_x_inGap_14_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.045455
21,AddGate_cz_inGap_11_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.409091
22,AddGate_cx_inGap_6_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.227273
23,AddGate_x_inGap_15_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.090909
24,AddGate_x_inGap_12_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.090909
25,AddGate_s_inGap_11_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.818182
26,AddGate_z_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.818182
27,AddGate_y_inGap_13_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.045455
28,AddGate_cswap_inGap_11_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.818182
29,AddGate_y_inGap_16_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.045455
30,AddGate_ry_inGap_6_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.136364
31,AddGate_y_inGap_6_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.045455
32,AddGate_cz_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.227273
33,AddGate_y_inGap_3_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.318182
34,AddGate_y_inGap_12_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.045455
35,AddGate_cswap_inGap_6_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.772727
36,AddGate_rzz_inGap_6_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.318182
37,AddGate_rz_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.136364
38,AddGate_rz_inGap_6_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.045455
39,AddGate_y_inGap_5_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.136364
40,AddGate_x_inGap_13_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.045455
41,AddGate_y_inGap_1_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.590909
42,AddGate_y_inGap_4_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.590909
43,AddGate_rzz_inGap_11_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.136364
44,AddGate_rz_inGap_11_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.136364
45,AddGate_h_inGap_11_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.090909
46,AddGate_x_inGap_16_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.636364
47,AddGate_x_inGap_5_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.090909
48,AddGate_x_inGap_4_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.090909
49,AddGate_y_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.227273
50,AddGate_y_inGap_9_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.772727

,Program,path_to_mutant,exam_score
0,AddGate_rzz_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.045455
1,AddGate_z_inGap_6_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.136364
2,AddGate_z_inGap_9_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.090909
3,AddGate_swap_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.045455
4,AddGate_y_inGap_14_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.045455
5,AddGate_x_inGap_1_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.181818
6,AddGate_y_inGap_11_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.272727
7,AddGate_x_inGap_2_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.363636
8,AddGate_z_inGap_7_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.5
9,AddGate_p_inGap_11_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.227273
10,AddGate_swap_inGap_11_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.090909
11,AddGate_rxx_inGap_11_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.045455
12,AddGate_z_inGap_11_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.181818
13,AddGate_y_inGap_15_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.136364
14,AddGate_y_inGap_2_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.363636
15,AddGate_ccx_inGap_6_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.772727
16,AddGate_ry_inGap_11_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.090909
17,AddGate_p_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.045455
18,AddGate_z_inGap_8_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.409091
19,AddGate_x_inGap_3_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.409091
20,AddGate_x_inGap_14_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.045455
21,AddGate_cz_inGap_11_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.409091
22,AddGate_cx_inGap_6_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.227273
23,AddGate_x_inGap_15_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.090909
24,AddGate_x_inGap_12_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.090909
25,AddGate_s_inGap_11_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.818182
26,AddGate_z_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.818182
27,AddGate_y_inGap_13_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.045455
28,AddGate_cswap_inGap_11_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.818182
29,AddGate_y_inGap_16_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.045455
30,AddGate_ry_inGap_6_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.136364
31,AddGate_y_inGap_6_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.045455
32,AddGate_cz_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.227273
33,AddGate_y_inGap_3_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.318182
34,AddGate_y_inGap_12_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.045455
35,AddGate_cswap_inGap_6_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.772727
36,AddGate_rzz_inGap_6_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.318182
37,AddGate_rz_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.136364
38,AddGate_rz_inGap_6_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.045455
39,AddGate_y_inGap_5_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.136364
40,AddGate_x_inGap_13_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.045455
41,AddGate_y_inGap_1_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.590909
42,AddGate_y_inGap_4_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.590909
43,AddGate_rzz_inGap_11_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.136364
44,AddGate_rz_inGap_11_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.136364
45,AddGate_h_inGap_11_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.090909
46,AddGate_x_inGap_16_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.636364
47,AddGate_x_inGap_5_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.090909
48,AddGate_x_inGap_4_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.090909
49,AddGate_y_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.227273
50,AddGate_y_inGap_9_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeexac...,0.772727