<h2>Download Initial Dependencies</h2>

In [1]:
import numpy as np
import pandas as pd
import json
import math
from tqdm import tqdm
from qiskit.quantum_info import SparsePauliOp, Operator, Pauli, Clifford
import qiskit.qasm2 as q2
from qiskit import QuantumCircuit
from IPython.display import display

from heisenbergUtilities import *

In [2]:
from qiskit_aer import AerSimulator
simulator = AerSimulator()

print(simulator.available_devices())

('CPU',)

Generate the linked list of all operations that take place in the inverse circuit

In [2]:
"""
LinkedListNode: A class that holds information related to a gate in a quantum circuit. 

PROPERTIES:
    - value (String): The name of the quantum gate
    - depth (int): The depth of the gate in the circuit
    - count (Int): The probability that the gate will meaningfully change the Pauli string.
    - next (LinkedListNode): The next gate in the circuit

"""

class LinkedListNode:
    def __init__(self, name="Initial", depth=0, count=0,  next=None):
        self.value = name
        self.depth = depth
        self.next = next
        self.count = count

class LinkedList:
    def __init__(self):
        self.head = None

    def append(self, name, depth):
        new_node = LinkedListNode(name, depth)
        if not self.head:
            self.head = new_node
            return
        last_node = self.head
        while last_node.next:
            last_node = last_node.next
        last_node.next = new_node

    def mark(self, depth):
        current_node = self.head
        while current_node:
            if current_node.depth == depth:
                current_node.count += 1
                return
            current_node = current_node.next

    def reset(self):
        current_node = self.head
        while current_node:
            current_node.count = 0
            current_node = current_node.next

<h2>Download MQT Benchmark circuits.</h2>

We'll start with DJ, RealAmpRandom, and GHZ since SB-QOPS caught those mutants 100% of the time for 5 qubit circuits

<h2>Generate mutants.</h2>

We'll start with mutants that add an unnecessary gate, then add mutants that replace a certain gate later

<h2> Define our CUT </h2>

This is where we will use SB-QOPS on a provided circuit and its mutants

For a single mutant, it took about 2 minutes to generate a 20 test suite (10 fail, 10 pass) on an RTX 4090 SUPER. 

There are 113 mutants for the DJ algorithm in use: 226 minutes or 3 3/4 hours

There are 89 mutants for the GHZ algorithm in use: 178 minutes or about 3 hours

There are 125 mutants for the RealAmpRandom algorithm in use: 250 minutes or just over 4 hours

BUT this cell should only need to be run once per algorithm with mutants under test. After it saves to the csv file at the end, this cell can be commented out as to not accidentally run it again. 

In the future if we want to test this methodology on higher qubit circuits or other algorithms, we'll likely either want to reduce the number of tests in the suite or the number of mutants we're analyzing

In [3]:
ORIGINAL_QASM = "dj_5_qubits.qasm"
ORIGINAL_QASM_FOLDER = "SBFL_circuits/MQTBench/"
QASM_MUTANT_FOLDER = "SBFL_circuits/QMutBenchMutants/Mutants_dj_5_qubits/"
QUBITS = 5
Runs = 10
algo = "1+1"

correct_circuit = load_program(ORIGINAL_QASM, ORIGINAL_QASM_FOLDER).copy()
correct_list = LinkedList()
depth = 1

#Append each gate to the linked list
for instruction in correct_circuit.data:
    correct_list.append(instruction.name + " " + str(depth), depth)
    depth += 1

In [ ]:
import QOPS as qops
from QOPS_test import get_compact_program_specification_Z, get_mutants
from pathlib import Path

ga_result = pd.DataFrame(columns=['Program',"path_to_mutant",'catch_avg','avg_fitness','failing_testcases', 'passing_testcases'])
program_history = {}


# program_list = [x for x in os.listdir('benchmarkFilteration/benchmark2/') if x.split(".")[0].split("_")[-1] == QUBITS]
# for program_name in tqdm(program_list):

#program_specification = The compact program specification. SB-QOPS needs this to generate failing test cases
program_specification = get_compact_program_specification_Z(correct_circuit, shots=20000)

#mutants = A python list of qiskit QuantumCircuit variables with a mutation in them
mutants = []
mutants_names = []
root = Path(QASM_MUTANT_FOLDER)
for qasm_mutant in root.rglob("*.qasm"):
    mutants.append(load_program(qasm_mutant.name, QASM_MUTANT_FOLDER))
    mutants_names.append(qasm_mutant.name)

for mutant_index,mutant in enumerate(mutants):
    tester = qops.Circuit_Tester(CUT=mutant)
    tester.set_applicable_families_Z(program_specification)
    mutants_per_run = []
    fitness_per_run = []
    failing_testcases_per_run = []
    history_per_run = []

    print("NOW RUNNING TO FIND FAILING TESTS")
    #For a predefined number of attempts, try to find a set of failing test cases (output is above predefined tolerance)
    for runs in range(Runs):
        killed = 0
        pauli = {}
        fitness = 0
        for i in range(len(tester.applicable_families)):
            best_function,testcase, history = tester.run_mealoneplusone(i, 80)
            if best_function >0.1:
                killed = 1
                pauli = testcase
                fitness = best_function
                break
        mutants_per_run.append(killed)
        failing_testcases_per_run.append(pauli)
        fitness_per_run.append(fitness)
        history_per_run.append(history)

    avg_score = np.mean(mutants_per_run)
    avg_fitness = np.mean(fitness_per_run)

    #Here is our new, modified algorithm from the SB-QOPS method that attempts to find passing test cases as well. We'll need them for SBFL
    passing_testcases_per_run = []

    print("NOW RUNNING TO FIND PASSING TESTS")
    for runs in range(Runs):
        pauli = {}
        fitness = 0
        for i in range(len(tester.applicable_families)):
            best_function, testcase, history = tester.run_reverse_mealoneplusone(i,80)
            if best_function < 0.1:
                pauli = testcase
                break
        passing_testcases_per_run.append(pauli)

    #Replace static program file with "program_name" when ready to test fully
    """
    ga_result: A pandas dataframe with the following columns
        Program: Name of the mutant quantum circuit file
        Path_To_Mutant: Path to the mutant file
        Catch_Avg: The average number of times the mutant was identified by SB-QOPS
        Avg_Fitness: The average fitness of the search algorithm used. Higher usually indicates higher Catch_Avg
        Failing_Testcases: A list of dicts indicating the set of Pauli strings and the weights that should be applied to generate a failing test case
        Passing_Testcases: A list of dicts indicating the set of Pauli strings and the weights that should be applied to generate a passing test case
    """
    ga_result = pd.concat([pd.DataFrame([[mutants_names[mutant_index],QASM_MUTANT_FOLDER,avg_score,avg_fitness,json.dumps(failing_testcases_per_run), json.dumps(passing_testcases_per_run)]],columns=ga_result.columns),ga_result],ignore_index=True)
    ga_result.to_csv(f'dj_ga_result', index=False)

ga_result is a slightly altered pandas Dataframe with similar structure found in SB-QOPS's results folder. The only differences are changing the column "Program" to be the name of the mutant file instead of the original quantum circuit and changing "Mutant" to be the path to the mutant file instead of being an arbitrary index value

Now we want to run SBFL using Heisenberg evolution trees on each circuit placed in ga_result

Evolution analysis tends to take about 5 minutes for 10 failing tests, so about 10 minutes for 20 total tests

So about 1130 minutes for DJ, or 18.8 hours to evolve and analyze all 113 DJ mutants

About 890 minutes for GHZ, or 14.8 hours to evolve and analyze all 89 GHZ mutants

About 1250 minutes for RealAmpRandom, or 20.8 hours to evolve and analyze all 125 RealAmpRandom mutants

This is something to note in the final paper. Regardless of accuracy this methodology takes a long time to run. If results are promising, then we'll want to look into the tradeoffs between EXAM and hyperparameters to speed this up. Primarily the atol, max_terms, and search_step parameters in the evolve_pauli_exact method in HeisenbergUtilities.py

<h2>Heisenberg Evolutions</h2>

In [5]:
from heisenbergTree import *

ga_result = pd.read_csv("dj_ga_result")
tarantula_sbfl_result = pd.DataFrame(columns=['Program','path_to_mutant','exam_score'])
barinel_sbfl_result = pd.DataFrame(columns=['Program','path_to_mutant','exam_score'])

#For each mutant of a circuit, run the SBFL implementation
for mutant, path in zip(ga_result.loc[:,"Program"], ga_result.loc[:,"path_to_mutant"]):
    print("Now evolving the following mutant: ", mutant)

    #Extract the raw test cases found for each mutant
    desired_failing_testcases = ga_result.loc[(ga_result["Program"] == mutant), ["failing_testcases"]]
    desired_passing_testcases = ga_result.loc[(ga_result["Program"] == mutant), ["passing_testcases"]]
    raw_failing_testcases = desired_failing_testcases["failing_testcases"].values[0].split("}")
    raw_passing_testcases = desired_passing_testcases["passing_testcases"].values[0].split("}")

    #Remove empty tests
    raw_failing_testcases = remove_null_tests(raw_failing_testcases)
    raw_passing_testcases = remove_null_tests(raw_passing_testcases)

    circuit_inverse = load_program(mutant,path).copy().inverse()  # Invert to track backward evolution of the operator
    forward_mutant = load_program(mutant, path).copy()

    #Create the linked list of operations in the inverse circuit
    operation_list = LinkedList()
    depth = 0

    #Append each gate to the linked list
    operation_list.append("Initial", depth)
    for instruction in circuit_inverse.data:
        depth += 1
        operation_list.append(instruction.name + " " + str((circuit_inverse.size()-depth)), depth)

    forward_list = LinkedList()
    depth = 1
    for instruction in forward_mutant.data:
        forward_list.append(instruction.name + " " + str(depth), depth)
        depth += 1

    #Create list of nodes in linked list. Somewhere down the road remove the linked list implementation. It's unnecessary and giving me a headache
    node_list = []
    node = operation_list.head
    while node:
        node_list.append(node)
        node = node.next

    #Perform Pauli propagation (Heisenberg evolution) for all test cases. Returns a dataframe with all counts for all operations
    global_frame_fail = heisenberg_evolve(circuit_inverse, operation_list, raw_failing_testcases, pass_fail = "fail")
    global_frame_pass = heisenberg_evolve(circuit_inverse, operation_list, raw_passing_testcases, pass_fail = "pass")

    global_frame = pd.concat([global_frame_fail, global_frame_pass], ignore_index=True)

    global_frame = global_frame.drop(["Initial"],axis=1)

    tarantula_scores = tarantula(global_frame)
    barinel_scores = barinel(global_frame)

    display(tarantula_scores)
    
    # Here is where analysis of the methodology begins. 
    # We first extract the position of the erroneous gate by comparing it to the original MQT gate
    # NOTE: This method is intended for single-added gates for now. Other types of mutants will require other methods later
    error_gate_location = find_erroneous_gate(forward_list, correct_list)

    print(error_gate_location)
    
    gates_observed = 0
    barinel_exam_score = 0
    for col_name, col_date in barinel_scores.items():
        gates_observed += 1

        #Extract depth from column name
        gate_depth = int(col_name.split()[1])

        if gate_depth == error_gate_location:
            barinel_exam_score = gates_observed/(circuit_inverse.size()+1)
            break

    gates_observed = 0
    tarantula_exam_score = 0
    for col_name, col_date in tarantula_scores.items():
        gates_observed += 1

        #Extract depth from column name
        gate_depth = int(col_name.split()[1])

        if gate_depth == error_gate_location:
            tarantula_exam_score = gates_observed/(circuit_inverse.size()+1)
            break

    barinel_sbfl_result = pd.concat([pd.DataFrame([[mutant,QASM_MUTANT_FOLDER,barinel_exam_score]],columns=barinel_sbfl_result.columns),barinel_sbfl_result],ignore_index=True)
    barinel_sbfl_result.sort_values(by=['exam_score'], ascending=False)
    barinel_sbfl_result.to_csv(f'dj_barinel_sbfl_result.csv', index=False)

    tarantula_sbfl_result = pd.concat([pd.DataFrame([[mutant,QASM_MUTANT_FOLDER,tarantula_exam_score]],columns=tarantula_sbfl_result.columns),tarantula_sbfl_result],ignore_index=True)
    tarantula_sbfl_result.sort_values(by=['exam_score'], ascending=False)
    tarantula_sbfl_result.to_csv(f'dj_tarantula_sbfl_result.csv', index=False)

barinel_sbfl_result

Now evolving the following mutant:  AddGate_p_inGap_7_.qasm

  0%|          | 0/10 [00:00<?, ?it/s]

100%|██████████| 10/10 [00:01<00:00,  9.20it/s]
100%|██████████| 10/10 [00:00<00:00, 10.37it/s]

,u 13,u 11,cx 10,p 9,h 6,cx 5,u 3,u 2,h 1,cx 12,h 8,cx 7,u 4,h 0
sum,0.614021,0.580587,0.580587,0.580587,0.580587,0.580587,0.580587,0.580587,0.580587,0.580587,0.580587,0.580587,0.580587,0.580587

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 p 10
10
Now evolving the following mutant:  AddGate_sx_inGap_1_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.79it/s]
100%|██████████| 10/10 [00:00<00:00, 10.72it/s]

,cx 12,u 11,cx 10,h 9,cx 8,u 5,u 4,u 3,h 2,h 1,sxdg 0,h 7,cx 6,u 13
sum,0.599153,0.599153,0.599153,0.599153,0.599153,0.599153,0.599153,0.599153,0.599153,0.599153,0.599153,0.599153,0.599153,0.573288

h 1 sx 1
1
Now evolving the following mutant:  AddGate_y_inGap_9_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.64it/s]
100%|██████████| 10/10 [00:00<00:00, 10.34it/s]

,barrier 12,u 11,cx 10,u 9,cx 8,h 7,cx 6,h 5,cx 4,u 3,u 2,u 1,h 0,h -1,y 13
sum,0.547776,0.547776,0.547776,0.547776,0.547776,0.547776,0.547776,0.547776,0.547776,0.547776,0.547776,0.547776,0.547776,0.547776,NaN

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 cx 10
u 11 u 11
cx 12 cx 12
u 13 u 13
0
Now evolving the following mutant:  AddGate_cx_inGap_3_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.95it/s]
100%|██████████| 10/10 [00:00<00:00, 10.99it/s]

,h 7,cx 6,cx 5,u 2,cx 12,u 11,cx 10,h 9,cx 8,u 4,u 3,h 1,h 0,u 13
sum,0.65625,0.65625,0.65625,0.65625,0.65625,0.65625,0.65625,0.65625,0.65625,0.65625,0.65625,0.65625,0.65625,0.567652

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 cx 7
7
Now evolving the following mutant:  AddGate_x_inGap_9_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.70it/s]
100%|██████████| 10/10 [00:00<00:00, 10.03it/s]

,u 1,barrier 12,u 11,cx 10,u 9,cx 8,h 7,cx 6,h 5,cx 4,u 3,u 2,h 0,h -1,x 13
sum,0.620559,0.620559,0.620559,0.620559,0.620559,0.620559,0.620559,0.620559,0.620559,0.620559,0.620559,0.620559,0.620559,0.620559,NaN

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 cx 10
u 11 u 11
cx 12 cx 12
u 13 u 13
0
Now evolving the following mutant:  AddGate_h_inGap_13_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.40it/s]
100%|██████████| 10/10 [00:01<00:00,  9.61it/s]

,barrier 12,u 11,cx 10,u 9,cx 8,h 7,cx 6,h 5,cx 4,u 3,u 2,u 1,h 0,h -1,h 13
sum,0.510704,0.510704,0.510704,0.510704,0.510704,0.510704,0.510704,0.510704,0.510704,0.510704,0.510704,0.510704,0.510704,0.510704,0.42488

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 cx 10
u 11 u 11
cx 12 cx 12
u 13 u 13
0
Now evolving the following mutant:  AddGate_cswap_inGap_8_.qasm

100%|██████████| 10/10 [00:02<00:00,  4.34it/s]
100%|██████████| 10/10 [00:02<00:00,  4.25it/s]

,u 13,cswap 11,h 8,cx 7,h 6,cx 5,u 4,h 0,cx 12,u 10,cx 9,u 3,u 2,h 1
sum,0.720766,0.710207,0.710207,0.710207,0.710207,0.710207,0.710207,0.710207,0.710207,0.710207,0.710207,0.710207,0.710207,0.710207

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 cx 10
u 11 u 11
cx 12 cswap 12
12
Now evolving the following mutant:  AddGate_sx_inGap_2_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.52it/s]
100%|██████████| 10/10 [00:00<00:00, 11.04it/s]

,u 11,cx 10,u 4,h 2,sxdg 1,h 7,cx 6,u 3,cx 12,h 9,cx 8,u 5,h 0,u 13
sum,0.52789,0.52789,0.52789,0.52789,0.52789,0.52789,0.52789,0.52789,0.52789,0.52789,0.52789,0.52789,0.52789,0.432719

h 1 h 1
h 2 sx 2
2
Now evolving the following mutant:  AddGate_rz_inGap_3_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.51it/s]
100%|██████████| 10/10 [00:00<00:00, 10.38it/s]

,u 13,cx 12,h 9,cx 8,u 4,u 2,h 0,u 11,cx 10,h 7,cx 6,rz 5,u 3,h 1
sum,0.682389,0.592975,0.592975,0.592975,0.592975,0.592975,0.592975,0.592975,0.592975,0.592975,0.592975,0.592975,0.592975,0.592975

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 rz 6
6
Now evolving the following mutant:  AddGate_h_inGap_11_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.41it/s]
100%|██████████| 10/10 [00:00<00:00, 10.22it/s]

,h 13,u 9,cx 8,u 2,h 0,barrier 12,u 11,cx 10,h 7,cx 6,h 5,cx 4,u 3,u 1,h -1
sum,0.486585,0.441201,0.441201,0.441201,0.441201,0.441201,0.441201,0.441201,0.441201,0.441201,0.441201,0.441201,0.441201,0.441201,0.441201

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 cx 10
u 11 u 11
cx 12 cx 12
u 13 u 13
0
Now evolving the following mutant:  AddGate_rx_inGap_1_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.36it/s]
100%|██████████| 10/10 [00:00<00:00, 10.44it/s]

,u 13,cx 12,u 11,cx 10,h 9,cx 8,u 5,u 4,u 3,h 2,h 1,rx 0,h 7,cx 6
sum,0.720858,0.673939,0.673939,0.673939,0.673939,0.673939,0.673939,0.673939,0.673939,0.673939,0.673939,0.673939,0.673939,0.673939

h 1 rx 1
1
Now evolving the following mutant:  AddGate_cswap_inGap_7_.qasm

100%|██████████| 10/10 [00:01<00:00,  5.83it/s]
100%|██████████| 10/10 [00:01<00:00,  5.88it/s]

,cswap 9,u 3,h 1,h 6,cx 5,cx 12,u 11,cx 10,h 8,cx 7,u 4,u 2,h 0,u 13
sum,0.699288,0.699288,0.699288,0.699288,0.699288,0.699288,0.699288,0.699288,0.699288,0.699288,0.699288,0.699288,0.699288,0.68241

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 cswap 10
10
Now evolving the following mutant:  AddGate_ry_inGap_5_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.65it/s]
100%|██████████| 10/10 [00:00<00:00, 10.65it/s]

,h 6,cx 5,cx 12,u 11,cx 10,h 9,cx 8,ry 7,u 4,u 3,u 2,h 1,h 0,u 13
sum,0.47564,0.47564,0.47564,0.47564,0.47564,0.47564,0.47564,0.47564,0.47564,0.47564,0.47564,0.47564,0.47564,0.468245

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 ry 8
8
Now evolving the following mutant:  AddGate_ccx_inGap_3_.qasm

100%|██████████| 10/10 [00:01<00:00,  5.61it/s]
100%|██████████| 10/10 [00:01<00:00,  6.09it/s]

,u 13,u 11,cx 10,h 7,cx 6,ccx 5,cx 12,h 9,cx 8,u 4,u 3,u 2,h 1,h 0
sum,0.736677,0.726532,0.726532,0.726532,0.726532,0.726532,0.726532,0.726532,0.726532,0.726532,0.726532,0.726532,0.726532,0.726532

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 ccx 6
6
Now evolving the following mutant:  AddGate_h_inGap_2_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.77it/s]
100%|██████████| 10/10 [00:00<00:00, 11.38it/s]

,u 13,cx 12,h 9,cx 8,h 7,cx 6,u 5,h 1,h 0,u 11,cx 10,u 4,u 3,h 2
sum,0.517787,0.507888,0.507888,0.507888,0.507888,0.507888,0.507888,0.507888,0.507888,0.507888,0.507888,0.507888,0.507888,0.507888

h 1 h 1
h 2 h 2
u 3 h 3
3
Now evolving the following mutant:  AddGate_t_inGap_8_.qasm

100%|██████████| 10/10 [00:01<00:00,  7.70it/s]
100%|██████████| 10/10 [00:01<00:00,  8.09it/s]

,u 13,tdg 11,h 8,cx 7,u 4,h 0,cx 12,u 10,cx 9,h 6,cx 5,u 3,u 2,h 1
sum,0.57814,0.501928,0.501928,0.501928,0.501928,0.501928,0.501928,0.501928,0.501928,0.501928,0.501928,0.501928,0.501928,0.501928

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 cx 10
u 11 u 11
cx 12 t 12
12
Now evolving the following mutant:  AddGate_ccx_inGap_5_.qasm

100%|██████████| 10/10 [00:02<00:00,  4.92it/s]
100%|██████████| 10/10 [00:01<00:00,  5.01it/s]

,cx 12,u 11,cx 10,h 9,cx 8,h 6,cx 5,ccx 7,u 4,u 3,h 1,h 0,u 2,u 13
sum,0.605945,0.605945,0.605945,0.605945,0.605945,0.605945,0.605945,0.605945,0.605945,0.605945,0.605945,0.605945,0.605945,0.537579

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 ccx 8
8
Now evolving the following mutant:  AddGate_y_inGap_4_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.80it/s]
100%|██████████| 10/10 [00:00<00:00, 10.32it/s]

,u 13,h 7,y 6,cx 5,cx 12,u 11,cx 10,h 9,cx 8,u 4,u 3,u 2,h 1,h 0
sum,0.61112,0.601017,0.601017,0.601017,0.601017,0.601017,0.601017,0.601017,0.601017,0.601017,0.601017,0.601017,0.601017,0.601017

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 y 7
7
Now evolving the following mutant:  AddGate_y_inGap_1_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.11it/s]
100%|██████████| 10/10 [00:00<00:00, 11.03it/s]

,cx 12,u 11,cx 10,h 9,cx 8,h 7,cx 6,u 5,u 4,u 3,h 2,h 1,y 0,u 13
sum,0.622227,0.622227,0.622227,0.622227,0.622227,0.622227,0.622227,0.622227,0.622227,0.622227,0.622227,0.622227,0.622227,0.610413

h 1 y 1
1
Now evolving the following mutant:  AddGate_cz_inGap_4_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.25it/s]
100%|██████████| 10/10 [00:00<00:00, 10.87it/s]

,cx 12,u 11,cx 10,h 9,cx 8,h 7,cz 6,cx 5,u 4,u 3,u 2,h 1,h 0,u 13
sum,0.602007,0.602007,0.602007,0.602007,0.602007,0.602007,0.602007,0.602007,0.602007,0.602007,0.602007,0.602007,0.602007,0.521032

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 cz 7
7
Now evolving the following mutant:  AddGate_h_inGap_3_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.72it/s]
100%|██████████| 10/10 [00:00<00:00, 11.12it/s]

,h 5,u 11,cx 10,u 2,h 7,cx 6,u 4,h 0,cx 12,h 9,cx 8,u 3,h 1,u 13
sum,0.465625,0.465625,0.465625,0.465625,0.465625,0.465625,0.465625,0.465625,0.465625,0.465625,0.465625,0.465625,0.465625,0.398647

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 h 6
6
Now evolving the following mutant:  AddGate_s_inGap_7_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.82it/s]
100%|██████████| 10/10 [00:00<00:00, 10.76it/s]

,u 13,cx 12,h 8,cx 7,u 4,h 0,u 11,cx 10,sdg 9,u 3,h 1,h 6,cx 5,u 2
sum,0.513151,0.498433,0.498433,0.498433,0.498433,0.498433,0.498433,0.498433,0.498433,0.498433,0.498433,0.498433,0.498433,0.498433

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 s 10
10
Now evolving the following mutant:  AddGate_swap_inGap_6_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.43it/s]
100%|██████████| 10/10 [00:00<00:00, 10.84it/s]

,cx 12,h 9,swap 8,cx 7,u 4,h 0,h 6,cx 5,u 2,u 11,cx 10,u 3,h 1,u 13
sum,0.577463,0.577463,0.577463,0.577463,0.577463,0.577463,0.577463,0.577463,0.577463,0.577463,0.577463,0.577463,0.577463,0.526783

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 swap 9
9
Now evolving the following mutant:  AddGate_y_inGap_5_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.07it/s]
100%|██████████| 10/10 [00:00<00:00, 11.11it/s]

,u 13,h 6,cx 5,cx 12,u 11,cx 10,h 9,cx 8,y 7,u 4,u 3,u 2,h 1,h 0
sum,0.645572,0.609131,0.609131,0.609131,0.609131,0.609131,0.609131,0.609131,0.609131,0.609131,0.609131,0.609131,0.609131,0.609131

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 y 8
8
Now evolving the following mutant:  AddGate_rz_inGap_6_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.94it/s]
100%|██████████| 10/10 [00:00<00:00, 10.46it/s]

,u 11,cx 10,rz 8,cx 7,u 4,u 3,h 1,h 0,cx 12,h 9,h 6,cx 5,u 2,u 13
sum,0.583435,0.583435,0.583435,0.583435,0.583435,0.583435,0.583435,0.583435,0.583435,0.583435,0.583435,0.583435,0.583435,0.578161

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 rz 9
9
Now evolving the following mutant:  AddGate_cx_inGap_5_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.71it/s]
100%|██████████| 10/10 [00:00<00:00, 11.17it/s]

,u 2,cx 12,u 11,cx 10,h 9,cx 8,cx 7,h 6,cx 5,u 4,u 3,h 1,h 0,u 13
sum,0.658638,0.658638,0.658638,0.658638,0.658638,0.658638,0.658638,0.658638,0.658638,0.658638,0.658638,0.658638,0.658638,0.585671

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 cx 9
9
Now evolving the following mutant:  AddGate_rzz_inGap_5_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.58it/s]
100%|██████████| 10/10 [00:00<00:00, 10.84it/s]

,u 13,cx 12,h 9,cx 8,rzz 7,u 4,h 0,h 6,cx 5,u 11,cx 10,u 3,h 1,u 2
sum,0.480872,0.405158,0.405158,0.405158,0.405158,0.405158,0.405158,0.405158,0.405158,0.405158,0.405158,0.405158,0.405158,0.405158

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 rzz 8
8
Now evolving the following mutant:  AddGate_h_inGap_10_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.38it/s]
100%|██████████| 10/10 [00:00<00:00, 10.34it/s]

,h 13,u 9,cx 8,u 2,u 1,h 0,barrier 12,u 11,cx 10,h 7,cx 6,h 5,cx 4,u 3,h -1
sum,0.652709,0.609223,0.609223,0.609223,0.609223,0.609223,0.609223,0.609223,0.609223,0.609223,0.609223,0.609223,0.609223,0.609223,0.609223

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 cx 10
u 11 u 11
cx 12 cx 12
u 13 u 13
0
Now evolving the following mutant:  AddGate_cz_inGap_8_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.06it/s]
100%|██████████| 10/10 [00:00<00:00, 10.59it/s]

,u 13,cx 12,cz 11,h 8,cx 7,u 4,h 0,u 10,cx 9,h 6,cx 5,u 3,u 2,h 1
sum,0.687337,0.639934,0.639934,0.639934,0.639934,0.639934,0.639934,0.639934,0.639934,0.639934,0.639934,0.639934,0.639934,0.639934

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 cx 10
u 11 u 11
cx 12 cz 12
12
Now evolving the following mutant:  AddGate_rzz_inGap_6_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.14it/s]
100%|██████████| 10/10 [00:00<00:00, 11.12it/s]

,cx 12,u 11,cx 10,h 9,rzz 8,cx 7,h 6,cx 5,u 4,u 3,u 2,h 1,h 0,u 13
sum,0.639016,0.639016,0.639016,0.639016,0.639016,0.639016,0.639016,0.639016,0.639016,0.639016,0.639016,0.639016,0.639016,0.589478

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 rzz 9
9
Now evolving the following mutant:  AddGate_ccx_inGap_8_.qasm

100%|██████████| 10/10 [00:02<00:00,  3.90it/s]
100%|██████████| 10/10 [00:02<00:00,  4.69it/s]

,cx 12,ccx 11,u 10,cx 9,h 8,cx 7,h 6,cx 5,u 4,u 3,h 1,h 0,u 2,u 13
sum,0.559799,0.559799,0.559799,0.559799,0.559799,0.559799,0.559799,0.559799,0.559799,0.559799,0.559799,0.559799,0.559799,0.548095

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 cx 10
u 11 u 11
cx 12 ccx 12
12
Now evolving the following mutant:  AddGate_ccx_inGap_9_.qasm

100%|██████████| 10/10 [00:02<00:00,  4.08it/s]
100%|██████████| 10/10 [00:02<00:00,  4.49it/s]

,ccx 13,barrier 12,u 11,cx 10,u 9,cx 8,h 7,cx 6,h 5,cx 4,u 3,u 2,u 1,h 0,h -1
sum,0.608325,0.585544,0.585544,0.585544,0.585544,0.585544,0.585544,0.585544,0.585544,0.585544,0.585544,0.585544,0.585544,0.585544,0.585544

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 cx 10
u 11 u 11
cx 12 cx 12
u 13 u 13
0
Now evolving the following mutant:  AddGate_z_inGap_5_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.22it/s]
100%|██████████| 10/10 [00:00<00:00, 10.83it/s]

,u 13,cx 12,u 11,cx 10,h 9,cx 8,z 7,h 6,cx 5,u 4,u 3,u 2,h 1,h 0
sum,0.570284,0.552089,0.552089,0.552089,0.552089,0.552089,0.552089,0.552089,0.552089,0.552089,0.552089,0.552089,0.552089,0.552089

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 z 8
8
Now evolving the following mutant:  AddGate_s_inGap_8_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.24it/s]
100%|██████████| 10/10 [00:00<00:00, 11.34it/s]

,u 13,cx 12,sdg 11,h 8,cx 7,h 6,cx 5,u 4,u 2,h 0,u 10,cx 9,u 3,h 1
sum,0.72107,0.686143,0.686143,0.686143,0.686143,0.686143,0.686143,0.686143,0.686143,0.686143,0.686143,0.686143,0.686143,0.686143

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 cx 10
u 11 u 11
cx 12 s 12
12
Now evolving the following mutant:  AddGate_s_inGap_5_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.40it/s]
100%|██████████| 10/10 [00:00<00:00, 10.97it/s]

,cx 12,h 9,cx 8,sdg 7,h 6,cx 5,u 4,u 2,h 0,u 11,cx 10,u 3,h 1,u 13
sum,0.562781,0.562781,0.562781,0.562781,0.562781,0.562781,0.562781,0.562781,0.562781,0.562781,0.562781,0.562781,0.562781,0.489324

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 s 8
8
Now evolving the following mutant:  AddGate_swap_inGap_5_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.29it/s]
100%|██████████| 10/10 [00:00<00:00, 10.68it/s]

,u 13,cx 12,u 11,cx 10,h 9,cx 8,swap 7,h 6,cx 5,u 4,u 3,u 2,h 1,h 0
sum,0.571246,0.529106,0.529106,0.529106,0.529106,0.529106,0.529106,0.529106,0.529106,0.529106,0.529106,0.529106,0.529106,0.529106

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 swap 8
8
Now evolving the following mutant:  AddGate_ry_inGap_3_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.02it/s]
100%|██████████| 10/10 [00:00<00:00, 10.74it/s]

,u 13,h 7,cx 6,ry 5,u 2,cx 12,u 11,cx 10,h 9,cx 8,u 4,u 3,h 1,h 0
sum,0.6783,0.657098,0.657098,0.657098,0.657098,0.657098,0.657098,0.657098,0.657098,0.657098,0.657098,0.657098,0.657098,0.657098

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 ry 6
6
Now evolving the following mutant:  AddGate_h_inGap_1_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.20it/s]
100%|██████████| 10/10 [00:00<00:00, 10.75it/s]

,u 13,cx 12,h 9,cx 8,u 5,h 1,h 7,cx 6,u 3,h 0,u 11,cx 10,u 4,h 2
sum,0.598143,0.585155,0.585155,0.585155,0.585155,0.585155,0.585155,0.585155,0.585155,0.585155,0.585155,0.585155,0.585155,0.585155

h 1 h 1
h 2 h 2
u 3 h 3
3
Now evolving the following mutant:  AddGate_h_inGap_8_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.55it/s]
100%|██████████| 10/10 [00:00<00:00, 11.00it/s]

,cx 12,h 11,u 10,cx 9,h 8,cx 7,h 6,cx 5,u 4,u 3,u 2,h 1,h 0,u 13
sum,0.617964,0.617964,0.617964,0.617964,0.617964,0.617964,0.617964,0.617964,0.617964,0.617964,0.617964,0.617964,0.617964,0.593487

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 cx 10
u 11 u 11
cx 12 h 12
12
Now evolving the following mutant:  AddGate_cswap_inGap_6_.qasm

100%|██████████| 10/10 [00:02<00:00,  4.47it/s]
100%|██████████| 10/10 [00:02<00:00,  4.72it/s]

,u 13,u 11,cx 10,cswap 8,cx 7,h 6,cx 5,u 4,u 2,h 0,cx 12,h 9,u 3,h 1
sum,0.633406,0.582996,0.582996,0.582996,0.582996,0.582996,0.582996,0.582996,0.582996,0.582996,0.582996,0.582996,0.582996,0.582996

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 cswap 9
9
Now evolving the following mutant:  AddGate_t_inGap_3_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.55it/s]
100%|██████████| 10/10 [00:01<00:00,  9.20it/s]

,u 11,cx 10,h 7,cx 6,tdg 5,u 4,u 3,u 2,h 1,h 0,cx 12,h 9,cx 8,u 13
sum,0.605663,0.605663,0.605663,0.605663,0.605663,0.605663,0.605663,0.605663,0.605663,0.605663,0.605663,0.605663,0.605663,0.444863

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 t 6
6
Now evolving the following mutant:  AddGate_cz_inGap_3_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.34it/s]
100%|██████████| 10/10 [00:00<00:00, 10.26it/s]

,u 11,cx 10,u 3,h 1,cx 12,h 9,cx 8,u 4,u 2,h 0,h 7,cx 6,cz 5,u 13
sum,0.545983,0.545983,0.545983,0.545983,0.545983,0.545983,0.545983,0.545983,0.545983,0.545983,0.545983,0.545983,0.545983,0.495319

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cz 6
6
Now evolving the following mutant:  AddGate_y_inGap_8_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.48it/s]
100%|██████████| 10/10 [00:00<00:00, 10.86it/s]

,u 13,h 6,cx 5,cx 12,y 11,h 8,cx 7,u 4,u 2,h 0,u 10,cx 9,u 3,h 1
sum,0.599715,0.536952,0.536952,0.536952,0.536952,0.536952,0.536952,0.536952,0.536952,0.536952,0.536952,0.536952,0.536952,0.536952

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 cx 10
u 11 u 11
cx 12 y 12
12
Now evolving the following mutant:  AddGate_cz_inGap_7_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.07it/s]
100%|██████████| 10/10 [00:00<00:00, 10.29it/s]

,u 13,u 11,cx 10,cz 9,u 3,u 2,h 1,cx 12,h 8,cx 7,h 6,cx 5,u 4,h 0
sum,0.674891,0.671504,0.671504,0.671504,0.671504,0.671504,0.671504,0.671504,0.671504,0.671504,0.671504,0.671504,0.671504,0.671504

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 cz 10
10
Now evolving the following mutant:  AddGate_h_inGap_5_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.89it/s]
100%|██████████| 10/10 [00:00<00:00, 10.78it/s]

,u 13,cx 12,u 11,cx 10,h 9,cx 8,h 7,h 6,cx 5,u 4,u 3,u 2,h 1,h 0
sum,0.550456,0.503314,0.503314,0.503314,0.503314,0.503314,0.503314,0.503314,0.503314,0.503314,0.503314,0.503314,0.503314,0.503314

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 h 8
8
Now evolving the following mutant:  AddGate_y_inGap_3_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.86it/s]
100%|██████████| 10/10 [00:00<00:00, 10.96it/s]

,u 13,cx 12,h 9,cx 8,u 4,h 0,u 11,cx 10,u 3,u 2,h 1,h 7,cx 6,y 5
sum,0.486314,0.446042,0.446042,0.446042,0.446042,0.446042,0.446042,0.446042,0.446042,0.446042,0.446042,0.446042,0.446042,0.446042

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 y 6
6
Now evolving the following mutant:  AddGate_p_inGap_8_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.66it/s]
100%|██████████| 10/10 [00:00<00:00, 11.63it/s]

,u 13,u 2,cx 12,p 11,u 10,cx 9,h 8,cx 7,u 4,u 3,h 1,h 0,h 6,cx 5
sum,0.599995,0.596832,0.596832,0.596832,0.596832,0.596832,0.596832,0.596832,0.596832,0.596832,0.596832,0.596832,0.596832,0.596832

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 cx 10
u 11 u 11
cx 12 p 12
12
Now evolving the following mutant:  AddGate_rz_inGap_5_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.56it/s]
100%|██████████| 10/10 [00:00<00:00, 10.45it/s]

,cx 12,h 9,cx 8,rz 7,h 6,cx 5,u 4,h 0,u 11,cx 10,u 3,u 2,h 1,u 13
sum,0.521584,0.521584,0.521584,0.521584,0.521584,0.521584,0.521584,0.521584,0.521584,0.521584,0.521584,0.521584,0.521584,0.413614

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 rz 8
8
Now evolving the following mutant:  AddGate_swap_inGap_7_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.85it/s]
100%|██████████| 10/10 [00:00<00:00, 10.86it/s]

,u 13,cx 12,h 8,cx 7,h 6,cx 5,u 4,u 2,h 0,u 11,cx 10,swap 9,u 3,h 1
sum,0.608542,0.552134,0.552134,0.552134,0.552134,0.552134,0.552134,0.552134,0.552134,0.552134,0.552134,0.552134,0.552134,0.552134

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 swap 10
10
Now evolving the following mutant:  AddGate_y_inGap_6_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.50it/s]
100%|██████████| 10/10 [00:00<00:00, 11.18it/s]

,cx 12,h 9,y 8,cx 7,u 4,u 2,h 0,u 11,cx 10,h 6,cx 5,u 3,h 1,u 13
sum,0.639212,0.639212,0.639212,0.639212,0.639212,0.639212,0.639212,0.639212,0.639212,0.639212,0.639212,0.639212,0.639212,0.609242

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 y 9
9
Now evolving the following mutant:  AddGate_ry_inGap_6_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.48it/s]
100%|██████████| 10/10 [00:00<00:00, 10.76it/s]

,u 13,u 11,cx 10,u 3,u 2,h 1,cx 12,h 9,ry 8,cx 7,h 6,cx 5,u 4,h 0
sum,0.597188,0.569048,0.569048,0.569048,0.569048,0.569048,0.569048,0.569048,0.569048,0.569048,0.569048,0.569048,0.569048,0.569048

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 ry 9
9
Now evolving the following mutant:  AddGate_h_inGap_4_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.58it/s]
100%|██████████| 10/10 [00:00<00:00, 10.73it/s]

,u 13,cx 12,u 11,cx 10,h 9,cx 8,h 7,h 6,cx 5,u 4,u 3,u 2,h 1,h 0
sum,0.659655,0.604322,0.604322,0.604322,0.604322,0.604322,0.604322,0.604322,0.604322,0.604322,0.604322,0.604322,0.604322,0.604322

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 h 8
8
Now evolving the following mutant:  AddGate_rxx_inGap_12_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.29it/s]
100%|██████████| 10/10 [00:01<00:00,  9.43it/s]

,u 11,cx 10,h 7,cx 6,u 3,u 1,h -1,barrier 12,u 9,cx 8,h 5,cx 4,u 2,h 0,rxx 13
sum,0.654318,0.654318,0.654318,0.654318,0.654318,0.654318,0.654318,0.654318,0.654318,0.654318,0.654318,0.654318,0.654318,0.654318,0.653502

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 cx 10
u 11 u 11
cx 12 cx 12
u 13 u 13
0
Now evolving the following mutant:  AddGate_rz_inGap_8_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.12it/s]
100%|██████████| 10/10 [00:00<00:00, 10.47it/s]

,u 13,cx 12,rz 11,u 10,cx 9,h 8,cx 7,h 6,cx 5,u 4,u 3,u 2,h 1,h 0
sum,0.60953,0.555627,0.555627,0.555627,0.555627,0.555627,0.555627,0.555627,0.555627,0.555627,0.555627,0.555627,0.555627,0.555627

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 cx 10
u 11 u 11
cx 12 rz 12
12
Now evolving the following mutant:  AddGate_z_inGap_4_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.54it/s]
100%|██████████| 10/10 [00:00<00:00, 10.65it/s]

,u 13,cx 12,h 9,cx 8,u 4,u 2,h 0,u 11,cx 10,h 7,z 6,cx 5,u 3,h 1
sum,0.636582,0.619648,0.619648,0.619648,0.619648,0.619648,0.619648,0.619648,0.619648,0.619648,0.619648,0.619648,0.619648,0.619648

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 z 7
7
Now evolving the following mutant:  AddGate_rxx_inGap_9_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.69it/s]
100%|██████████| 10/10 [00:00<00:00, 10.38it/s]

,rxx 13,barrier 12,u 11,cx 10,h 7,cx 6,h 5,cx 4,u 3,u 1,h -1,u 9,cx 8,u 2,h 0
sum,0.598157,0.417985,0.417985,0.417985,0.417985,0.417985,0.417985,0.417985,0.417985,0.417985,0.417985,0.417985,0.417985,0.417985,0.417985

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 cx 10
u 11 u 11
cx 12 cx 12
u 13 u 13
0
Now evolving the following mutant:  AddGate_rzz_inGap_7_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.59it/s]
100%|██████████| 10/10 [00:00<00:00, 11.02it/s]

,rzz 9,u 3,h 1,cx 12,u 11,cx 10,h 8,cx 7,h 6,cx 5,u 4,u 2,h 0,u 13
sum,0.652803,0.652803,0.652803,0.652803,0.652803,0.652803,0.652803,0.652803,0.652803,0.652803,0.652803,0.652803,0.652803,0.62116

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 rzz 10
10
Now evolving the following mutant:  AddGate_t_inGap_6_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.05it/s]
100%|██████████| 10/10 [00:01<00:00,  8.76it/s]

,u 3,h 1,cx 12,u 11,cx 10,h 9,tdg 8,cx 7,h 6,cx 5,u 4,u 2,h 0,u 13
sum,0.48571,0.48571,0.48571,0.48571,0.48571,0.48571,0.48571,0.48571,0.48571,0.48571,0.48571,0.48571,0.48571,0.481577

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 t 9
9
Now evolving the following mutant:  AddGate_ry_inGap_7_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.96it/s]
100%|██████████| 10/10 [00:00<00:00, 10.68it/s]

,u 13,u 11,cx 10,h 8,cx 7,u 4,u 2,h 0,cx 12,ry 9,h 6,cx 5,u 3,h 1
sum,0.70568,0.640829,0.640829,0.640829,0.640829,0.640829,0.640829,0.640829,0.640829,0.640829,0.640829,0.640829,0.640829,0.640829

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 ry 10
10
Now evolving the following mutant:  AddGate_z_inGap_3_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.46it/s]
100%|██████████| 10/10 [00:00<00:00, 11.09it/s]

,u 2,h 7,cx 6,z 5,cx 12,u 11,cx 10,h 9,cx 8,u 4,u 3,h 1,h 0,u 13
sum,0.677866,0.677866,0.677866,0.677866,0.677866,0.677866,0.677866,0.677866,0.677866,0.677866,0.677866,0.677866,0.677866,0.651806

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 z 6
6
Now evolving the following mutant:  AddGate_cz_inGap_6_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.15it/s]
100%|██████████| 10/10 [00:00<00:00, 10.36it/s]

,u 11,cx 10,u 3,h 1,cx 12,h 9,cz 8,cx 7,h 6,cx 5,u 4,u 2,h 0,u 13
sum,0.500521,0.500521,0.500521,0.500521,0.500521,0.500521,0.500521,0.500521,0.500521,0.500521,0.500521,0.500521,0.500521,0.480824

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 cz 9
9
Now evolving the following mutant:  AddGate_t_inGap_5_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.27it/s]
100%|██████████| 10/10 [00:01<00:00,  8.98it/s]

,tdg 7,u 4,h 0,cx 12,h 9,cx 8,h 6,cx 5,u 2,u 11,cx 10,u 3,h 1,u 13
sum,0.656423,0.656423,0.656423,0.656423,0.656423,0.656423,0.656423,0.656423,0.656423,0.656423,0.656423,0.656423,0.656423,0.614009

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 t 8
8
Now evolving the following mutant:  AddGate_ccx_inGap_7_.qasm

100%|██████████| 10/10 [00:02<00:00,  4.29it/s]
100%|██████████| 10/10 [00:02<00:00,  4.55it/s]

,cx 12,u 11,cx 10,h 8,cx 7,u 4,u 2,h 0,ccx 9,h 6,cx 5,u 3,h 1,u 13
sum,0.630312,0.630312,0.630312,0.630312,0.630312,0.630312,0.630312,0.630312,0.630312,0.630312,0.630312,0.630312,0.630312,0.597433

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 ccx 10
10
Now evolving the following mutant:  AddGate_ry_inGap_1_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.88it/s]
100%|██████████| 10/10 [00:00<00:00, 10.58it/s]

,u 13,cx 12,u 11,cx 10,h 9,cx 8,h 7,cx 6,u 5,u 4,u 3,h 2,h 1,ry 0
sum,0.424595,0.421202,0.421202,0.421202,0.421202,0.421202,0.421202,0.421202,0.421202,0.421202,0.421202,0.421202,0.421202,0.421202

h 1 ry 1
1
Now evolving the following mutant:  AddGate_t_inGap_4_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.23it/s]
100%|██████████| 10/10 [00:01<00:00,  9.49it/s]

,cx 12,u 11,cx 10,h 9,cx 8,tdg 6,cx 5,u 3,u 2,h 1,h 7,u 4,h 0,u 13
sum,0.695652,0.695652,0.695652,0.695652,0.695652,0.695652,0.695652,0.695652,0.695652,0.695652,0.695652,0.695652,0.695652,0.638687

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 t 7
7
Now evolving the following mutant:  AddGate_cx_inGap_6_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.93it/s]
100%|██████████| 10/10 [00:00<00:00, 11.26it/s]

,u 13,u 11,cx 10,u 3,h 1,cx 12,h 9,cx 8,cx 7,h 6,cx 5,u 4,u 2,h 0
sum,0.564166,0.541192,0.541192,0.541192,0.541192,0.541192,0.541192,0.541192,0.541192,0.541192,0.541192,0.541192,0.541192,0.541192

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 cx 9
9
Now evolving the following mutant:  AddGate_t_inGap_7_.qasm

100%|██████████| 10/10 [00:01<00:00,  7.76it/s]
100%|██████████| 10/10 [00:01<00:00,  8.13it/s]

,cx 12,u 11,cx 10,tdg 9,h 8,cx 7,h 6,cx 5,u 4,u 3,u 2,h 1,h 0,u 13
sum,0.626489,0.626489,0.626489,0.626489,0.626489,0.626489,0.626489,0.626489,0.626489,0.626489,0.626489,0.626489,0.626489,0.597163

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 t 10
10
Now evolving the following mutant:  AddGate_h_inGap_7_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.67it/s]
100%|██████████| 10/10 [00:00<00:00, 10.82it/s]

,u 11,cx 10,u 2,cx 12,h 9,h 8,cx 7,h 6,cx 5,u 4,u 3,h 1,h 0,u 13
sum,0.696227,0.696227,0.696227,0.696227,0.696227,0.696227,0.696227,0.696227,0.696227,0.696227,0.696227,0.696227,0.696227,0.673419

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 h 10
10
Now evolving the following mutant:  AddGate_h_inGap_12_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.56it/s]
100%|██████████| 10/10 [00:01<00:00,  9.43it/s]

,u 11,cx 10,h 7,cx 6,u 3,h -1,barrier 12,u 9,cx 8,h 5,cx 4,u 2,u 1,h 0,h 13
sum,0.625746,0.625746,0.625746,0.625746,0.625746,0.625746,0.625746,0.625746,0.625746,0.625746,0.625746,0.625746,0.625746,0.625746,0.57158

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 cx 10
u 11 u 11
cx 12 cx 12
u 13 u 13
0
Now evolving the following mutant:  AddGate_rz_inGap_4_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.30it/s]
100%|██████████| 10/10 [00:00<00:00, 10.75it/s]

,cx 12,u 11,cx 10,h 9,cx 8,u 4,u 3,u 2,h 1,h 0,h 7,rz 6,cx 5,u 13
sum,0.62028,0.62028,0.62028,0.62028,0.62028,0.62028,0.62028,0.62028,0.62028,0.62028,0.62028,0.62028,0.62028,0.591781

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 rz 7
7
Now evolving the following mutant:  AddGate_sx_inGap_9_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.64it/s]
100%|██████████| 10/10 [00:01<00:00,  9.83it/s]

,sxdg 13,u 9,cx 8,u 2,h 0,barrier 12,h 5,cx 4,u 1,u 11,cx 10,h 7,cx 6,u 3,h -1
sum,0.456495,0.425062,0.425062,0.425062,0.425062,0.425062,0.425062,0.425062,0.425062,0.425062,0.425062,0.425062,0.425062,0.425062,0.425062

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 cx 10
u 11 u 11
cx 12 cx 12
u 13 u 13
0
Now evolving the following mutant:  AddGate_cswap_inGap_5_.qasm

100%|██████████| 10/10 [00:01<00:00,  5.55it/s]
100%|██████████| 10/10 [00:01<00:00,  5.66it/s]

,u 13,u 3,h 1,u 11,cx 10,cx 12,h 9,cx 8,cswap 7,h 6,cx 5,u 4,h 0,u 2
sum,0.476906,0.470192,0.470192,0.470192,0.470192,0.470192,0.470192,0.470192,0.470192,0.470192,0.470192,0.470192,0.470192,0.470192

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cswap 8
8
Now evolving the following mutant:  AddGate_ry_inGap_8_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.19it/s]
100%|██████████| 10/10 [00:00<00:00, 11.34it/s]

,u 13,u 2,cx 12,ry 11,u 10,cx 9,h 8,cx 7,h 6,cx 5,u 4,u 3,h 1,h 0
sum,0.626425,0.567168,0.567168,0.567168,0.567168,0.567168,0.567168,0.567168,0.567168,0.567168,0.567168,0.567168,0.567168,0.567168

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 cx 10
u 11 u 11
cx 12 ry 12
12
Now evolving the following mutant:  AddGate_p_inGap_4_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.47it/s]
100%|██████████| 10/10 [00:00<00:00, 10.59it/s]

,h 7,p 6,cx 5,u 2,cx 12,u 11,cx 10,h 9,cx 8,u 4,u 3,h 1,h 0,u 13
sum,0.675645,0.675645,0.675645,0.675645,0.675645,0.675645,0.675645,0.675645,0.675645,0.675645,0.675645,0.675645,0.675645,0.595924

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 p 7
7
Now evolving the following mutant:  AddGate_cx_inGap_4_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.11it/s]
100%|██████████| 10/10 [00:00<00:00, 11.25it/s]

,u 2,cx 12,u 11,cx 10,h 9,cx 8,h 7,cx 6,cx 5,u 4,u 3,h 1,h 0,u 13
sum,0.602855,0.602855,0.602855,0.602855,0.602855,0.602855,0.602855,0.602855,0.602855,0.602855,0.602855,0.602855,0.602855,0.559587

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 cx 7
7
Now evolving the following mutant:  AddGate_rzz_inGap_4_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.57it/s]
100%|██████████| 10/10 [00:00<00:00, 10.27it/s]

,u 13,cx 12,u 11,cx 10,h 9,cx 8,h 7,rzz 6,cx 5,u 4,u 3,u 2,h 1,h 0
sum,0.646943,0.631772,0.631772,0.631772,0.631772,0.631772,0.631772,0.631772,0.631772,0.631772,0.631772,0.631772,0.631772,0.631772

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 rzz 7
7
Now evolving the following mutant:  AddGate_s_inGap_6_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.15it/s]
100%|██████████| 10/10 [00:00<00:00, 10.42it/s]

,u 2,cx 12,u 11,cx 10,h 9,sdg 8,cx 7,h 6,cx 5,u 4,u 3,h 1,h 0,u 13
sum,0.706962,0.706962,0.706962,0.706962,0.706962,0.706962,0.706962,0.706962,0.706962,0.706962,0.706962,0.706962,0.706962,0.674379

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 s 9
9
Now evolving the following mutant:  AddGate_z_inGap_8_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.92it/s]
100%|██████████| 10/10 [00:00<00:00, 10.61it/s]

,u 13,u 10,cx 9,u 3,h 1,u 2,cx 12,z 11,h 8,cx 7,h 6,cx 5,u 4,h 0
sum,0.708548,0.688027,0.688027,0.688027,0.688027,0.688027,0.688027,0.688027,0.688027,0.688027,0.688027,0.688027,0.688027,0.688027

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 cx 10
u 11 u 11
cx 12 z 12
12
Now evolving the following mutant:  AddGate_ccx_inGap_6_.qasm

100%|██████████| 10/10 [00:02<00:00,  4.93it/s]
100%|██████████| 10/10 [00:01<00:00,  5.65it/s]

,u 13,cx 12,h 9,ccx 8,cx 7,u 4,u 3,h 1,h 0,u 11,cx 10,h 6,cx 5,u 2
sum,0.559056,0.551243,0.551243,0.551243,0.551243,0.551243,0.551243,0.551243,0.551243,0.551243,0.551243,0.551243,0.551243,0.551243

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 ccx 9
9
Now evolving the following mutant:  AddGate_y_inGap_2_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.72it/s]
100%|██████████| 10/10 [00:00<00:00, 10.76it/s]

,u 13,cx 12,h 9,cx 8,h 7,cx 6,u 5,h 0,u 11,cx 10,u 4,u 3,h 2,y 1
sum,0.580383,0.480363,0.480363,0.480363,0.480363,0.480363,0.480363,0.480363,0.480363,0.480363,0.480363,0.480363,0.480363,0.480363

h 1 h 1
h 2 y 2
2
Now evolving the following mutant:  AddGate_swap_inGap_4_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.96it/s]
100%|██████████| 10/10 [00:00<00:00, 10.91it/s]

,u 13,cx 12,u 11,cx 10,h 9,cx 8,u 4,u 3,u 2,h 1,h 0,h 7,swap 6,cx 5
sum,0.396382,0.371292,0.371292,0.371292,0.371292,0.371292,0.371292,0.371292,0.371292,0.371292,0.371292,0.371292,0.371292,0.371292

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 swap 7
7
Now evolving the following mutant:  AddGate_rxx_inGap_2_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.02it/s]
100%|██████████| 10/10 [00:00<00:00, 11.32it/s]

,u 11,cx 10,u 4,u 3,h 2,rxx 1,cx 12,h 9,cx 8,h 7,cx 6,u 5,h 0,u 13
sum,0.662466,0.662466,0.662466,0.662466,0.662466,0.662466,0.662466,0.662466,0.662466,0.662466,0.662466,0.662466,0.662466,0.639832

h 1 h 1
h 2 rxx 2
2
Now evolving the following mutant:  AddGate_rz_inGap_7_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.12it/s]
100%|██████████| 10/10 [00:00<00:00, 10.06it/s]

,rz 9,u 3,h 1,cx 12,u 11,cx 10,h 8,cx 7,h 6,cx 5,u 4,u 2,h 0,u 13
sum,0.662063,0.662063,0.662063,0.662063,0.662063,0.662063,0.662063,0.662063,0.662063,0.662063,0.662063,0.662063,0.662063,0.655567

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 rz 10
10
Now evolving the following mutant:  AddGate_ry_inGap_4_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.34it/s]
100%|██████████| 10/10 [00:00<00:00, 10.91it/s]

,u 13,cx 12,u 11,cx 10,h 9,cx 8,h 7,ry 6,cx 5,u 4,u 3,u 2,h 1,h 0
sum,0.636611,0.530902,0.530902,0.530902,0.530902,0.530902,0.530902,0.530902,0.530902,0.530902,0.530902,0.530902,0.530902,0.530902

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 ry 7
7
Now evolving the following mutant:  AddGate_rx_inGap_2_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.92it/s]
100%|██████████| 10/10 [00:00<00:00, 11.53it/s]

,u 11,cx 10,h 7,cx 6,u 4,u 3,h 2,rx 1,cx 12,h 9,cx 8,u 5,h 0,u 13
sum,0.641957,0.641957,0.641957,0.641957,0.641957,0.641957,0.641957,0.641957,0.641957,0.641957,0.641957,0.641957,0.641957,0.579523

h 1 h 1
h 2 rx 2
2
Now evolving the following mutant:  AddGate_cswap_inGap_4_.qasm

100%|██████████| 10/10 [00:01<00:00,  5.35it/s]
100%|██████████| 10/10 [00:01<00:00,  6.22it/s]

,cx 12,h 9,cx 8,u 11,cx 10,h 7,cswap 6,cx 5,u 4,u 2,h 0,u 3,h 1,u 13
sum,0.623383,0.623383,0.623383,0.623383,0.623383,0.623383,0.623383,0.623383,0.623383,0.623383,0.623383,0.623383,0.623383,0.606257

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 cswap 7
7
Now evolving the following mutant:  AddGate_rxx_inGap_11_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.44it/s]
100%|██████████| 10/10 [00:00<00:00, 10.01it/s]

,rxx 13,barrier 12,u 11,cx 10,u 9,cx 8,h 7,cx 6,h 5,cx 4,u 3,u 2,h 0,h -1,u 1
sum,0.636121,0.54516,0.54516,0.54516,0.54516,0.54516,0.54516,0.54516,0.54516,0.54516,0.54516,0.54516,0.54516,0.54516,0.54516

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 cx 10
u 11 u 11
cx 12 cx 12
u 13 u 13
0
Now evolving the following mutant:  AddGate_s_inGap_3_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.41it/s]
100%|██████████| 10/10 [00:00<00:00, 10.94it/s]

,cx 12,h 9,cx 8,h 7,cx 6,sdg 5,u 4,h 0,u 11,cx 10,u 3,u 2,h 1,u 13
sum,0.582447,0.582447,0.582447,0.582447,0.582447,0.582447,0.582447,0.582447,0.582447,0.582447,0.582447,0.582447,0.582447,0.521944

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 s 6
6
Now evolving the following mutant:  AddGate_ry_inGap_2_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.24it/s]
100%|██████████| 10/10 [00:00<00:00, 10.83it/s]

,u 11,cx 10,u 4,u 3,h 2,ry 1,cx 12,h 9,cx 8,h 7,cx 6,u 5,h 0,u 13
sum,0.628913,0.628913,0.628913,0.628913,0.628913,0.628913,0.628913,0.628913,0.628913,0.628913,0.628913,0.628913,0.628913,0.582708

h 1 h 1
h 2 ry 2
2
Now evolving the following mutant:  AddGate_rxx_inGap_10_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.41it/s]
100%|██████████| 10/10 [00:01<00:00,  9.51it/s]

,u 9,cx 8,u 2,u 1,h 0,barrier 12,u 11,cx 10,h 7,cx 6,h 5,cx 4,u 3,h -1,rxx 13
sum,0.429978,0.429978,0.429978,0.429978,0.429978,0.429978,0.429978,0.429978,0.429978,0.429978,0.429978,0.429978,0.429978,0.429978,NaN

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 cx 10
u 11 u 11
cx 12 cx 12
u 13 u 13
0
Now evolving the following mutant:  AddGate_cz_inGap_5_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.83it/s]
100%|██████████| 10/10 [00:00<00:00, 11.00it/s]

,u 11,cx 10,u 3,h 1,cx 12,h 9,cx 8,cz 7,h 6,cx 5,u 4,u 2,h 0,u 13
sum,0.41354,0.41354,0.41354,0.41354,0.41354,0.41354,0.41354,0.41354,0.41354,0.41354,0.41354,0.41354,0.41354,0.379483

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cz 8
8
Now evolving the following mutant:  AddGate_rxx_inGap_1_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.21it/s]
100%|██████████| 10/10 [00:00<00:00, 10.40it/s]

,cx 12,h 9,cx 8,u 5,u 3,h 1,u 11,cx 10,h 7,cx 6,u 4,h 2,rxx 0,u 13
sum,0.544465,0.544465,0.544465,0.544465,0.544465,0.544465,0.544465,0.544465,0.544465,0.544465,0.544465,0.544465,0.544465,0.464597

h 1 rxx 1
1
Now evolving the following mutant:  AddGate_swap_inGap_3_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.88it/s]
100%|██████████| 10/10 [00:00<00:00, 10.52it/s]

,u 13,u 2,cx 12,u 11,cx 10,h 9,cx 8,h 7,cx 6,swap 5,u 4,u 3,h 1,h 0
sum,0.687885,0.647882,0.647882,0.647882,0.647882,0.647882,0.647882,0.647882,0.647882,0.647882,0.647882,0.647882,0.647882,0.647882

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 swap 6
6
Now evolving the following mutant:  AddGate_cswap_inGap_3_.qasm

100%|██████████| 10/10 [00:01<00:00,  6.01it/s]
100%|██████████| 10/10 [00:01<00:00,  6.61it/s]

,u 11,cx 10,cx 12,h 9,cx 8,h 7,cx 6,cswap 5,u 4,u 3,u 2,h 1,h 0,u 13
sum,0.537192,0.537192,0.537192,0.537192,0.537192,0.537192,0.537192,0.537192,0.537192,0.537192,0.537192,0.537192,0.537192,0.528473

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cswap 6
6
Now evolving the following mutant:  AddGate_rx_inGap_9_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.37it/s]
100%|██████████| 10/10 [00:00<00:00, 10.44it/s]

,rx 13,barrier 12,u 11,cx 10,u 9,cx 8,h 7,cx 6,h 5,cx 4,u 3,u 2,u 1,h 0,h -1
sum,0.652296,0.61566,0.61566,0.61566,0.61566,0.61566,0.61566,0.61566,0.61566,0.61566,0.61566,0.61566,0.61566,0.61566,0.61566

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 cx 10
u 11 u 11
cx 12 cx 12
u 13 u 13
0
Now evolving the following mutant:  AddGate_p_inGap_6_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.60it/s]
100%|██████████| 10/10 [00:00<00:00, 11.02it/s]

,u 13,cx 12,u 11,cx 10,h 9,p 8,cx 7,u 4,u 3,h 1,h 0,h 6,cx 5,u 2
sum,0.467785,0.451837,0.451837,0.451837,0.451837,0.451837,0.451837,0.451837,0.451837,0.451837,0.451837,0.451837,0.451837,0.451837

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 p 9
9
Now evolving the following mutant:  AddGate_cx_inGap_7_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.42it/s]
100%|██████████| 10/10 [00:00<00:00, 10.84it/s]

,u 13,cx 12,u 11,cx 10,cx 9,h 8,cx 7,h 6,cx 5,u 4,u 3,u 2,h 1,h 0
sum,0.558505,0.550115,0.550115,0.550115,0.550115,0.550115,0.550115,0.550115,0.550115,0.550115,0.550115,0.550115,0.550115,0.550115

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 cx 10
u 11 cx 11
11
Now evolving the following mutant:  AddGate_z_inGap_7_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.29it/s]
100%|██████████| 10/10 [00:00<00:00, 11.01it/s]

,u 13,u 11,cx 10,z 9,u 3,u 2,h 1,cx 12,h 8,cx 7,h 6,cx 5,u 4,h 0
sum,0.692283,0.564194,0.564194,0.564194,0.564194,0.564194,0.564194,0.564194,0.564194,0.564194,0.564194,0.564194,0.564194,0.564194

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 z 10
10
Now evolving the following mutant:  AddGate_rzz_inGap_3_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.19it/s]
100%|██████████| 10/10 [00:00<00:00, 11.06it/s]

,u 11,cx 10,u 4,u 3,u 2,h 1,h 0,cx 12,h 9,cx 8,h 7,cx 6,rzz 5,u 13
sum,0.63649,0.63649,0.63649,0.63649,0.63649,0.63649,0.63649,0.63649,0.63649,0.63649,0.63649,0.63649,0.63649,0.549395

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 rzz 6
6
Now evolving the following mutant:  AddGate_x_inGap_2_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.11it/s]
100%|██████████| 10/10 [00:00<00:00, 10.50it/s]

,u 13,cx 12,u 11,cx 10,h 9,cx 8,h 7,cx 6,u 5,u 4,u 3,h 2,x 1,h 0
sum,0.663051,0.558718,0.558718,0.558718,0.558718,0.558718,0.558718,0.558718,0.558718,0.558718,0.558718,0.558718,0.558718,0.558718

h 1 h 1
h 2 x 2
2
Now evolving the following mutant:  AddGate_p_inGap_5_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.56it/s]
100%|██████████| 10/10 [00:00<00:00, 10.93it/s]

,u 13,cx 12,u 11,cx 10,h 9,cx 8,p 7,h 6,cx 5,u 4,u 3,u 2,h 1,h 0
sum,0.660127,0.621769,0.621769,0.621769,0.621769,0.621769,0.621769,0.621769,0.621769,0.621769,0.621769,0.621769,0.621769,0.621769

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 p 8
8
Now evolving the following mutant:  AddGate_x_inGap_1_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.07it/s]
100%|██████████| 10/10 [00:00<00:00, 10.83it/s]

,u 13,u 11,cx 10,h 7,cx 6,u 4,u 3,h 2,cx 12,h 9,cx 8,u 5,h 1,x 0
sum,0.413088,0.402774,0.402774,0.402774,0.402774,0.402774,0.402774,0.402774,0.402774,0.402774,0.402774,0.402774,0.402774,0.402774

h 1 x 1
1
Now evolving the following mutant:  AddGate_y_inGap_7_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.04it/s]
100%|██████████| 10/10 [00:00<00:00, 11.34it/s]

,cx 12,h 8,cx 7,u 4,h 0,u 11,cx 10,y 9,h 6,cx 5,u 3,u 2,h 1,u 13
sum,0.529257,0.529257,0.529257,0.529257,0.529257,0.529257,0.529257,0.529257,0.529257,0.529257,0.529257,0.529257,0.529257,0.5082

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 y 10
10
Now evolving the following mutant:  AddGate_cx_inGap_9_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.22it/s]
100%|██████████| 10/10 [00:00<00:00, 10.44it/s]

,cx 13,u 11,cx 10,u 9,cx 8,h 7,cx 6,u 3,u 2,h 0,h -1,barrier 12,h 5,cx 4,u 1
sum,0.66658,0.596709,0.596709,0.596709,0.596709,0.596709,0.596709,0.596709,0.596709,0.596709,0.596709,0.596709,0.596709,0.596709,0.596709

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 cx 10
u 11 u 11
cx 12 cx 12
u 13 u 13
0
Now evolving the following mutant:  AddGate_rxx_inGap_13_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.03it/s]
100%|██████████| 10/10 [00:01<00:00,  9.32it/s]

,rxx 13,u 11,cx 10,h 7,cx 6,u 3,h -1,barrier 12,u 9,cx 8,h 5,cx 4,u 2,u 1,h 0
sum,0.673453,0.609921,0.609921,0.609921,0.609921,0.609921,0.609921,0.609921,0.609921,0.609921,0.609921,0.609921,0.609921,0.609921,0.609921

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 cx 10
u 11 u 11
cx 12 cx 12
u 13 u 13
0
Now evolving the following mutant:  AddGate_ry_inGap_9_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.61it/s]
100%|██████████| 10/10 [00:01<00:00,  9.91it/s]

,ry 13,barrier 12,u 9,cx 8,h 5,cx 4,u 2,u 1,h 0,u 11,cx 10,h 7,cx 6,u 3,h -1
sum,0.832405,0.783298,0.783298,0.783298,0.783298,0.783298,0.783298,0.783298,0.783298,0.783298,0.783298,0.783298,0.783298,0.783298,0.783298

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 cx 10
u 11 u 11
cx 12 cx 12
u 13 u 13
0
Now evolving the following mutant:  AddGate_cx_inGap_8_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.35it/s]
100%|██████████| 10/10 [00:00<00:00, 10.98it/s]

,u 2,u 10,cx 9,h 6,cx 5,u 3,h 1,cx 12,cx 11,h 8,cx 7,u 4,h 0,u 13
sum,0.509237,0.509237,0.509237,0.509237,0.509237,0.509237,0.509237,0.509237,0.509237,0.509237,0.509237,0.509237,0.509237,0.451582

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 cx 10
u 11 u 11
cx 12 cx 12
u 13 cx 13
13
Now evolving the following mutant:  AddGate_z_inGap_6_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.13it/s]
100%|██████████| 10/10 [00:00<00:00, 10.59it/s]

,cx 12,u 11,cx 10,h 9,z 8,cx 7,u 4,u 3,u 2,h 1,h 0,h 6,cx 5,u 13
sum,0.605999,0.605999,0.605999,0.605999,0.605999,0.605999,0.605999,0.605999,0.605999,0.605999,0.605999,0.605999,0.605999,0.557788

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 z 9
9
Now evolving the following mutant:  AddGate_h_inGap_9_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.22it/s]
100%|██████████| 10/10 [00:01<00:00,  9.69it/s]

,h 13,u 11,cx 10,u 9,cx 8,h 7,cx 6,u 3,u 2,h 0,h -1,barrier 12,h 5,cx 4,u 1
sum,0.5937,0.567917,0.567917,0.567917,0.567917,0.567917,0.567917,0.567917,0.567917,0.567917,0.567917,0.567917,0.567917,0.567917,0.567917

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 cx 10
u 11 u 11
cx 12 cx 12
u 13 u 13
0
Now evolving the following mutant:  AddGate_h_inGap_6_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.01it/s]
100%|██████████| 10/10 [00:00<00:00, 10.74it/s]

,h 6,cx 5,u 11,cx 10,h 8,cx 7,u 4,u 2,h 0,cx 12,h 9,u 3,h 1,u 13
sum,0.591923,0.591923,0.591923,0.591923,0.591923,0.591923,0.591923,0.591923,0.591923,0.591923,0.591923,0.591923,0.591923,0.559387

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 h 7
cx 8 cx 8
h 9 h 9
cx 10 h 10
10
Now evolving the following mutant:  AddGate_s_inGap_4_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.16it/s]
100%|██████████| 10/10 [00:00<00:00, 10.16it/s]

,u 13,cx 12,h 9,cx 8,u 4,h 0,u 11,cx 10,h 7,sdg 6,cx 5,u 3,u 2,h 1
sum,0.614186,0.603052,0.603052,0.603052,0.603052,0.603052,0.603052,0.603052,0.603052,0.603052,0.603052,0.603052,0.603052,0.603052

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 s 7
7
Now evolving the following mutant:  AddGate_p_inGap_3_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.80it/s]
100%|██████████| 10/10 [00:00<00:00, 10.95it/s]

,h 7,cx 6,p 5,cx 12,u 11,cx 10,h 9,cx 8,u 4,u 3,u 2,h 1,h 0,u 13
sum,0.65313,0.65313,0.65313,0.65313,0.65313,0.65313,0.65313,0.65313,0.65313,0.65313,0.65313,0.65313,0.65313,0.629817

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 p 6
6
Now evolving the following mutant:  AddGate_ccx_inGap_4_.qasm

100%|██████████| 10/10 [00:01<00:00,  5.18it/s]
100%|██████████| 10/10 [00:01<00:00,  5.93it/s]

,u 13,cx 12,h 9,cx 8,h 7,ccx 6,cx 5,u 4,u 3,u 2,h 1,h 0,u 11,cx 10
sum,0.662976,0.612934,0.612934,0.612934,0.612934,0.612934,0.612934,0.612934,0.612934,0.612934,0.612934,0.612934,0.612934,0.612934

h 1 h 1
h 2 h 2
u 3 u 3
u 4 u 4
u 5 u 5
cx 6 cx 6
h 7 ccx 7
7

,Program,path_to_mutant,exam_score
0,AddGate_ccx_inGap_4_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_dj_5_qu...,0.6
1,AddGate_p_inGap_3_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_dj_5_qu...,0.533333
2,AddGate_s_inGap_4_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_dj_5_qu...,0.333333
3,AddGate_h_inGap_6_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_dj_5_qu...,0.133333
4,AddGate_h_inGap_9_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_dj_5_qu...,0.666667
...,...,...,...
108,AddGate_x_inGap_9_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_dj_5_qu...,0.866667
109,AddGate_cx_inGap_3_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_dj_5_qu...,0.466667
110,AddGate_y_inGap_9_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_dj_5_qu...,0.533333
111,AddGate_sx_inGap_1_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_dj_5_qu...,0.8
112,AddGate_p_inGap_7_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_dj_5_qu...,0.733333

In [7]:
tarantula_sbfl_result

,Program,path_to_mutant,exam_score
0,AddGate_ccx_inGap_4_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_dj_5_qu...,0.785714
1,AddGate_p_inGap_3_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_dj_5_qu...,0.857143
2,AddGate_s_inGap_4_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_dj_5_qu...,1.0
3,AddGate_h_inGap_6_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_dj_5_qu...,0.928571
4,AddGate_h_inGap_9_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_dj_5_qu...,1.071429
...,...,...,...
108,AddGate_x_inGap_9_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_dj_5_qu...,0.071429
109,AddGate_cx_inGap_3_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_dj_5_qu...,0.857143
110,AddGate_y_inGap_9_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_dj_5_qu...,0.857143
111,AddGate_sx_inGap_1_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_dj_5_qu...,0.714286
112,AddGate_p_inGap_7_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_dj_5_qu...,0.642857

<h2>Optimization Test and One-Shot Example</h2>

Using the pauli_prop package with marginally small atol and including max_terms/search_step yielded the same results in Ochiai as the old implementation, but ran twice as fast

In [ ]:
from pauli_prop import propagate_through_operator

MUTANT = "AddGate_p_inGap_7_.qasm"
MUTANT_PATH = "SBFL_circuits/QMutBenchMutants/Mutants_dj_5_qubits/"

def evolve_pauli_exact(pauli_label, gate):
    """Return exact Pauli expansion after conjugation"""
    evolution = propagate_through_operator(pauli_label, gate, atol=1e-4, frame='h', max_terms = 80, search_step=3)

    return {
        p.to_label(): c for p, c in zip(evolution.paulis, evolution.coeffs)
    }

def load_program(name,path):
    qc = QuantumCircuit.from_qasm_file("{}/{}".format(path,name))
    qc.remove_final_measurements()
    if len(qc.clbits) > 0:
        for i in range(len(qc.clbits)):
            qc.measure(i, i)
    else:
        qc.measure_all()
    qc.remove_final_measurements()
    return qc.copy()

circuit_under_test = load_program(MUTANT, MUTANT_PATH)
circuit_inverse = circuit_under_test.copy().inverse()
output_from_csv = pd.read_csv("dj_ga_results.csv")
desired_testcases = output_from_csv.loc[(output_from_csv["Program"] == MUTANT), ["failing_testcases"]]
raw_testcases = desired_testcases["failing_testcases"].values[0].split("}")

for raw_idx, raw in enumerate(raw_testcases):
    if raw == ']':
        print("Caught one!", raw)
        raw_testcases.pop(raw_idx)

first = True

operation_list = LinkedList()
depth = 0
operation_list.append("Initial", depth)
for instruction in circuit_inverse.data:
    depth += 1
    operation_list.append(instruction.name + " " + str((circuit_inverse.size()-depth)), depth)


node_list = []
node = operation_list.head
while node:
    node_list.append(node)
    node = node.next

global_circuit_frame = pd.DataFrame({}, columns = [node.value for node in node_list] + ["pass/fail"], dtype=np.float64)

#For every provided test case, clean the string, convert it into a dictionary, and perform Pauli propagation
for test in tqdm(raw_testcases):

    #Cleaning up the test case string from the csv file to convert it into a dictionary
    test = test.replace("{", "")
    test = test.replace("]", "")
    test = test.replace("[", "")
    if not first:
        test = test[2:]
    test = "{" +test + "}"
    test = json.loads(test)

    #We want to keep track of the number of strings are in a specific test case and weight the results so that SBFL isn't biased by tests with more strings in them
    num_strings = 0
    
    #For each string specified in the test case, perform Pauli propagation through the circuit and store the results
    for pauli_string, pauli_coeff in zip(test.keys(), test.values()):

        #print("The coefficient related to string ", pauli_string, " is ", pauli_coeff)
        num_strings += 1

        # Define the initial Pauli operator to track
        # Qiskit layout is right-to-left: 'IX' means X acts on Qubit 0, I acts on Qubit 1
        initial_pauli = SparsePauliOp(pauli_string)  
        prev_pauli = initial_pauli
        num_qubits = circuit_inverse.num_qubits

        transition_graph = {}  # step -> list of (from, to, coeff)

        #Define the current layer of the evolution tree, starting with the initial Pauli having a probability of 100% to appear
        current_layer = {
            initial_pauli.paulis[0].to_label(): 1.0  # Start with the initial Pauli having probability 1
        }

        #For each gate in the quantum circuit, propagate backwards. The circuit is already inversed 
        for step_idx, (instruction, qargs, cargs) in enumerate(circuit_inverse.data, start=1):

            #Define operation being performed
            gate_type = instruction.name 
            gate_op = Operator(instruction)

            #Create a do-nothing operator, then add the desired gate to the do-nothing to only act on the desired qubits
            q_indices = [qarg._index for qarg in qargs]
            full_gate_op = Operator.from_label("I" * num_qubits).compose(gate_op, q_indices)

            new_layer = {}
            edges = []

            #For each Pauli in the current layer of the evolution tree, apply the desired operator to the desired qubits
            for pauli_in, prob_in in current_layer.items():

                evolved_dict = evolve_pauli_exact(SparsePauliOp(pauli_in), SparsePauliOp.from_operator(full_gate_op))

                #For each resulting Pauli string, calculate the probability of the inverse circuit reaching this state
                #This will be used later to weight the counts for SBFL
                for pauli_out, coeff_out in evolved_dict.items():

                    total_prob = prob_in * ((coeff_out.real)**2)

                    # accumulate node weights
                    new_layer[pauli_out] = (new_layer.get(pauli_out, 0) + total_prob)

                    # store exact edge
                    edges.append({
                        "from": pauli_in,
                        "to": pauli_out,
                        "weight": coeff_out,
                        "probability": total_prob
                    })

            #Simplify numerical noise, we don't care about states that have such a low chance of occuring that it's negligible
            current_layer = {
                pauli: prob for pauli, prob in new_layer.items() if abs(prob) > 1e-4
            }

            transition_graph[step_idx] = {
                "gate_type": gate_type,
                "edges": edges
            }

        #Start at first gate in the inverse circuit
        checked_gate = operation_list.head.next
        idx = 1

        #For each gate in the circuit
        while checked_gate:

            #For each transition through that gate
            for edge in transition_graph[idx]["edges"]:
                
                #If the previous Pauli string evolved into a new Pauli string, 
                #add the probability of that new string occuring to that gate's count
                if edge["from"] != edge["to"]:
                    checked_gate.count += edge["probability"]
            
            #We weight the count by the coefficient related to the Pauli string that SB-QOPS provides
            checked_gate.count *= abs(pauli_coeff)
            idx += 1
            checked_gate = checked_gate.next

    first = False
    node = operation_list.head
    gate_list = []
    while node:
        gate_list.append(node.count/num_strings)
        node = node.next
    gate_list.append("fail")
    global_circuit_frame = pd.concat([global_circuit_frame, pd.DataFrame([gate_list], columns=global_circuit_frame.columns)], ignore_index=True)
    operation_list.reset()

global_circuit_frame

In [ ]:
global_circuit_frame = global_circuit_frame.drop(["Initial"],axis=1)
global_circuit_frame

<h2>Tarantula Algorithm</h2>

NOTE: This algorithm will not run correctly until SB-QOPS is configured to return a selection of passing tests on top of the failing tests it already provides

In [ ]:
num_fail_tests = len(global_circuit_frame[global_circuit_frame["pass/fail"] == "fail"])
num_pass_tests = len(global_circuit_frame[global_circuit_frame["pass/fail"] == "pass"])
fail_counts = global_circuit_frame[global_circuit_frame["pass/fail"] == "fail"].agg(["sum"]).drop(["pass/fail"], axis=1)
pass_counts = global_circuit_frame[global_circuit_frame["pass/fail"] == "pass"].agg(["sum"]).drop(["pass/fail"], axis=1)

tarantula_scores = (fail_counts/num_fail_tests)/((fail_counts/num_fail_tests)+(pass_counts/num_pass_tests))
tarantula_scores

<h2>Ochiai Algorithm</h2>

NOTE: This algorithms performance is also degraded until SB-QOPS also returns a selection of passing tests

In [ ]:
pass_counts = global_circuit_frame[global_circuit_frame["pass/fail"] == "pass"].agg(["sum"]).drop(["pass/fail"], axis=1)
fail_counts = global_circuit_frame[global_circuit_frame["pass/fail"] == "fail"].agg(["sum"]).drop(["pass/fail"], axis=1)
num_fail_tests = len(global_circuit_frame[global_circuit_frame["pass/fail"] == "fail"])

ochiai_scores = fail_counts/np.sqrt(num_fail_tests*(fail_counts+pass_counts))
ochiai_scores = ochiai_scores[ochiai_scores.iloc[0].sort_values(ascending=False).index]
ochiai_scores