<h1 style="text-align: center;">HEISENBERG-BASED FAULT LOCALIZATION (HBFL)</h1>

<h2 style="text-align: center;">Download Initial Dependencies</h2>

In [1]:
import numpy as np
import pandas as pd
import json
import math
from tqdm import tqdm
from qiskit.quantum_info import SparsePauliOp, Operator, Pauli, Clifford
import qiskit.qasm2 as q2
from qiskit import QuantumCircuit
from IPython.display import display

from heisenbergUtilities import *

In [2]:
from qiskit_aer import AerSimulator
simulator = AerSimulator()

print(simulator.available_devices())

('CPU',)

<h2 style="text-align: center;">CONTROL PANEL</h2>

In [2]:
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
#-------------------------------------------------------------------------GENERAL PARAMETERS---------------------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
ALG_NAME = "ghz"
ORIGINAL_QASM = f"{ALG_NAME}_5_qubits.qasm"                                     #| The original algorithm QASM circuit file name.                           #
ORIGINAL_QASM_FOLDER = "SBFL_circuits/MQTBench/"                                           #| The folder containing the original QASM circuit file.                    #
QASM_MUTANT_FOLDER = f"SBFL_circuits/QMutBenchMutants/Mutants_{ALG_NAME}_5_qubits/"      #| The folder containing all mutants related to the original QASM circuit.  #
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
#-------------------------------------------------------------------------SB-QOPS PARAMETERS---------------------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
RUNS = 10                                                                       #| Number of times SB-QOPS will run to find a failing or passing test case.            #
SHOTS = 20000                                                                   #| Number of shots for SB-QOPS to use to create the compact program specification.     #
EPOCH = 80                                                                      #| Number of epochs SB-QOPS will run to navigate the search space of test cases.       #
SBQOPS_TOL = 0.1                                                                #| Tolerance value SB-QOPS uses to determine if a test case is failing or passing.     #
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
#---------------------------------------------------------------------HEISENBERG SBFL PARAMETERS-----------------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
LAMBDA_PHASE = 0.5                                                              #| The hyperparameter used to weight the phase change of the Pauli propagation
LAMBDA_CHANGE = 0.5                                                              #| The hyperparameter used to weight the change of string of the Pauli propagation
ATOL = 1e-4                                                                     #| The tolerance value used to prune negligible magnitudes during Pauli propagation.   #
MAX_TERMS = 100                                                                 #| The maximum number of terms to keep during Pauli propagation. If None, use all.     #
SEARCH_STEP = 3                                                                 #| The search step size used during Pauli propagation. If None, pauli-prop uses 4.     #
VERBOSE = 1                                                                     #| A boolean value to determine if the program should print out detailed information.  #
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#

Generate the linked list of all operations that take place in the inverse circuit

In [3]:
"""
LinkedListNode: A class that holds information related to a gate in a quantum circuit. 

PROPERTIES:
    - value (String): The name of the quantum gate
    - depth (int): The depth of the gate in the circuit
    - count (Int): The probability that the gate will meaningfully change the Pauli string.
    - next (LinkedListNode): The next gate in the circuit

"""

class LinkedListNode:
    def __init__(self, name="Initial", depth=0, count=0,  next=None):
        self.value = name
        self.depth = depth
        self.next = next
        self.count = count

class LinkedList:
    def __init__(self):
        self.head = None

    def append(self, name, depth):
        new_node = LinkedListNode(name, depth)
        if not self.head:
            self.head = new_node
            return
        last_node = self.head
        while last_node.next:
            last_node = last_node.next
        last_node.next = new_node

    def mark(self, depth):
        current_node = self.head
        while current_node:
            if current_node.depth == depth:
                current_node.count += 1
                return
            current_node = current_node.next

    def reset(self):
        current_node = self.head
        while current_node:
            current_node.count = 0
            current_node = current_node.next

<h3>Download MQT Benchmark circuits.</h3>

We'll start with DJ, RealAmpRandom, and GHZ since SB-QOPS caught those mutants 100% of the time for 5 qubit circuits

<h3>Generate mutants.</h3>

We'll start with mutants that add an unnecessary gate, then add mutants that replace a certain gate later.

The mutants were downloaded from QMutBench, choosing specifically mutants that added a gate anywhere with 0-10% survival scores

In [4]:
correct_circuit = load_program(ORIGINAL_QASM, ORIGINAL_QASM_FOLDER).copy()
correct_list = LinkedList()
correct_list = construct_list(correct_list, correct_circuit, inverse=False)

<h2 style="text-align: center;"> SB-QOPS </h2>

This is where we will use SB-QOPS on a provided circuit and its mutants

For a single mutant, it took about 2 minutes to generate a 20 test suite (10 fail, 10 pass) on an RTX 4090 SUPER. It can only be run on a Linux environment since the AER Simulator does not support Windows

There are 113 mutants for the DJ algorithm in use: 226 minutes or 3 3/4 hours

There are 89 mutants for the GHZ algorithm in use: 178 minutes or about 3 hours

There are 125 mutants for the RealAmpRandom algorithm in use: 250 minutes or just over 4 hours

BUT this cell should only need to be run once per algorithm with mutants under test. After it saves to the csv file at the end, this cell can be commented out as to not accidentally run it again. 

In the future if we want to test this methodology on higher qubit circuits or other algorithms, we'll likely either want to reduce the number of tests in the suite or the number of mutants we're analyzing

In [ ]:
import QOPS as qops
from QOPS_test import get_compact_program_specification_Z
from pathlib import Path

ga_result = pd.DataFrame(columns=['Program',"path_to_mutant",'catch_avg','avg_fitness','failing_testcases', 'passing_testcases'])
program_history = {}

#program_specification = The compact program specification. SB-QOPS needs this to generate failing test cases.
# In a public-use environment, this would be provided by the user.
program_specification = get_compact_program_specification_Z(correct_circuit, shots=SHOTS)

#mutants = A python list of qiskit QuantumCircuit variables with a mutation in them
mutants = []
mutants_names = []
root = Path(QASM_MUTANT_FOLDER)
for qasm_mutant in root.rglob("*.qasm"):
    mutants.append(load_program(qasm_mutant.name, QASM_MUTANT_FOLDER))
    mutants_names.append(qasm_mutant.name)

for mutant_index,mutant in enumerate(mutants):
    tester = qops.Circuit_Tester(CUT=mutant)
    tester.set_applicable_families_Z(program_specification)
    mutants_per_run = []
    fitness_per_run = []
    failing_testcases_per_run = []
    history_per_run = []

    print("NOW RUNNING TO FIND FAILING TESTS")
    #For a predefined number of attempts, try to find a set of failing test cases (output is above predefined tolerance)
    for runs in range(RUNS):
        killed = 0
        pauli = {}
        fitness = 0
        for i in range(len(tester.applicable_families)):
            best_function,testcase, history = tester.run_mealoneplusone(i, EPOCH)
            if best_function > SBQOPS_TOL:
                killed = 1
                pauli = testcase
                fitness = best_function
                break
        mutants_per_run.append(killed)
        failing_testcases_per_run.append(pauli)
        fitness_per_run.append(fitness)
        history_per_run.append(history)

    avg_score = np.mean(mutants_per_run)
    avg_fitness = np.mean(fitness_per_run)

    #Here is our new, modified algorithm from the SB-QOPS method that attempts to find passing test cases as well. We'll need them for SBFL
    passing_testcases_per_run = []

    print("NOW RUNNING TO FIND PASSING TESTS")
    for runs in range(RUNS):
        pauli = {}
        fitness = 0
        for i in range(len(tester.applicable_families)):
            best_function, testcase, history = tester.run_reverse_mealoneplusone(i,EPOCH)
            if best_function < SBQOPS_TOL:
                pauli = testcase
                break
        passing_testcases_per_run.append(pauli)

    #Replace static program file with "program_name" when ready to test fully
    """
    ga_result: A pandas dataframe with the following columns
        Program: Name of the mutant quantum circuit file
        Path_To_Mutant: Path to the mutant file
        Catch_Avg: The average number of times the mutant was identified by SB-QOPS
        Avg_Fitness: The average fitness of the search algorithm used. Higher usually indicates higher Catch_Avg
        Failing_Testcases: A list of dicts indicating the set of Pauli strings and the weights that should be applied to generate a failing test case
        Passing_Testcases: A list of dicts indicating the set of Pauli strings and the weights that should be applied to generate a passing test case
    """
    ga_result = pd.concat([pd.DataFrame([[mutants_names[mutant_index],QASM_MUTANT_FOLDER,avg_score,avg_fitness,json.dumps(failing_testcases_per_run), json.dumps(passing_testcases_per_run)]],columns=ga_result.columns),ga_result],ignore_index=True)
    ga_result.to_csv(f'realamprandom_ga_result', index=False)

ga_result is a slightly altered pandas Dataframe with similar structure found in SB-QOPS's results folder. The differences are changing the column "Program" to be the name of the mutant file instead of the original quantum circuit, changing "Mutant" to be the path to the mutant file instead of being an arbitrary index value, and adding a passing_testcases column that returns Pauli strings and coefficients that generate passing tests.

Now we want to run SBFL using Heisenberg evolution trees on each circuit placed in ga_result

Evolution analysis tends to take about 5 minutes for 10 failing tests on a very complex algorithm such as QNN, so about 10 minutes for 20 total tests

DJ was a relatively small algorithm with few to no branching gates, so it only ended up taking about 5-6 minutes to evolve and analyze all 113 DJ mutants

About 890 minutes for GHZ, or 14.8 hours to evolve and analyze all 89 GHZ mutants

About 1250 minutes for RealAmpRandom, or 20.8 hours to evolve and analyze all 125 RealAmpRandom mutants

The runtime of this code segment is directly tied to the depth of the circuit being analyzed and the number of 2-branching gates such as rotation or phase gates that exist in the circuit.

This is something to note in the final paper. Regardless of accuracy this methodology takes a long time to run. If results are promising, then we'll want to look into the tradeoffs between EXAM and hyperparameters to speed this up. Primarily the atol, max_terms, and search_step parameters in the evolve_pauli_exact method in HeisenbergUtilities.py

<h2 style="text-align: center;">HEISENBERG EVOLUTIONS (PAULI PROPAGATION)</h2>

In [5]:
from heisenbergTree import *

ga_result = pd.read_csv(f'{ALG_NAME}_ga_result.csv')
tarantula_sbfl_result = pd.DataFrame(columns=['Program','path_to_mutant','exam_score'])
barinel_sbfl_result = pd.DataFrame(columns=['Program','path_to_mutant','exam_score'])

#For each mutant of a circuit, run the SBFL implementation
for mutant, path in zip(ga_result.loc[:,"Program"], ga_result.loc[:,"path_to_mutant"]):
    print("Now evolving the following mutant: ", mutant)

    #Extract the raw test cases found for each mutant
    desired_failing_testcases = ga_result.loc[(ga_result["Program"] == mutant), ["failing_testcases"]]
    desired_passing_testcases = ga_result.loc[(ga_result["Program"] == mutant), ["passing_testcases"]]
    raw_failing_testcases = desired_failing_testcases["failing_testcases"].values[0].split("}")
    raw_passing_testcases = desired_passing_testcases["passing_testcases"].values[0].split("}")

    #Remove empty tests
    raw_failing_testcases = remove_null_tests(raw_failing_testcases)
    raw_passing_testcases = remove_null_tests(raw_passing_testcases)

    circuit_inverse = load_program(mutant,path).copy().inverse()  # Invert to track backward evolution of the operator
    forward_mutant = load_program(mutant, path).copy()

    #Create the linked list of operations in the inverse circuit
    operation_list = LinkedList()
    operation_list = construct_list(operation_list, circuit_inverse, True)

    forward_list = LinkedList()
    forward_list = construct_list(forward_list, forward_mutant, False)

    #Create list of nodes in linked list. Somewhere down the road remove the linked list implementation. It's unnecessary and giving me a headache
    node_list = []
    node = operation_list.head
    while node:
        node_list.append(node)
        node = node.next

    #Perform Pauli propagation (Heisenberg evolution) for all test cases. Returns a dataframe with all counts for all operations
    global_frame_fail = heisenberg_evolve(circuit_inverse, operation_list, raw_failing_testcases, "fail", LAMBDA_PHASE, LAMBDA_CHANGE, atol = ATOL, max_terms = MAX_TERMS, search_step = SEARCH_STEP)
    global_frame_pass = heisenberg_evolve(circuit_inverse, operation_list, raw_passing_testcases, "pass", LAMBDA_PHASE, LAMBDA_CHANGE, atol = ATOL, max_terms = MAX_TERMS, search_step = SEARCH_STEP)

    global_frame = pd.concat([global_frame_fail, global_frame_pass], ignore_index=True)

    global_frame = global_frame.drop(["Initial"],axis=1)
    if VERBOSE:
        display(global_frame)

    tarantula_scores = tarantula(global_frame)
    barinel_scores = barinel(global_frame)

    if VERBOSE:
        print("BARINEL SCORES")
        display(barinel_scores)
        print("TARANTULA SCORES")
        display(tarantula_scores)
    
    # Here is where analysis of the methodology begins. 
    # We first extract the position of the erroneous gate by comparing it to the original MQT gate
    # NOTE: This method is intended for single-added gates for now. Other types of mutants will require other methods later
    error_gate_location = find_erroneous_gate(forward_list, correct_list)

    if VERBOSE:
        print("ERROR GATE LOCATION:")
        print(error_gate_location)

    # Calculate the EXAM score for Barinel by counting the number of gates we would have to observe before we reach the erroneous gate.
    gates_observed = 0
    barinel_exam_score = 0
    for col_name, col_date in barinel_scores.items():
        gates_observed += 1

        #Extract depth from column name
        gate_depth = int(col_name.split()[1])

        if gate_depth == error_gate_location:
            barinel_exam_score = gates_observed/(circuit_inverse.size()+1)
            break

    # Calculate the EXAM score for Tarantula by counting the number of gates we would have to observe before we reach the erroneous gate.
    gates_observed = 0
    tarantula_exam_score = 0
    for col_name, col_date in tarantula_scores.items():
        gates_observed += 1

        #Extract depth from column name
        gate_depth = int(col_name.split()[1])

        if gate_depth == error_gate_location:
            tarantula_exam_score = gates_observed/(circuit_inverse.size()+1)
            break

    # Here we store the results from the HBFL analysis for both barinel and tarantula into a csv file for later analysis.
    barinel_sbfl_result = pd.concat([pd.DataFrame([[mutant,QASM_MUTANT_FOLDER,barinel_exam_score]],columns=barinel_sbfl_result.columns),barinel_sbfl_result],ignore_index=True)
    barinel_sbfl_result.sort_values(by=['exam_score'], ascending=False)
    barinel_sbfl_result.to_csv(f'{ALG_NAME}_barinel_sbfl_result.csv', index=False)

    tarantula_sbfl_result = pd.concat([pd.DataFrame([[mutant,QASM_MUTANT_FOLDER,tarantula_exam_score]],columns=tarantula_sbfl_result.columns),tarantula_sbfl_result],ignore_index=True)
    tarantula_sbfl_result.sort_values(by=['exam_score'], ascending=False)
    tarantula_sbfl_result.to_csv(f'{ALG_NAME}_tarantula_sbfl_result.csv', index=False)

if VERBOSE:
    display(barinel_sbfl_result)
    display(tarantula_sbfl_result)

Now evolving the following mutant:  AddGate_y_inGap_9_.qasm

  0%|          | 0/10 [00:00<?, ?it/s]

100%|██████████| 10/10 [00:00<00:00, 11.27it/s]
100%|██████████| 10/10 [00:00<00:00, 12.31it/s]

         y 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.214286  1.120536  0.801823  0.584396  0.428946  0.412170      fail
1   0.194444  1.166667  0.838194  0.648149  0.479770  0.457911      fail
2   0.318182  1.187216  0.894762  0.687922  0.501248  0.471848      fail
3   0.326087  1.121739  0.821960  0.611277  0.437246  0.413362      fail
4   0.295455  1.107955  0.822035  0.605731  0.427182  0.405764      fail
5   0.285714  1.120536  0.838579  0.613105  0.441522  0.419535      fail
6   0.272727  1.160795  0.893910  0.652171  0.472656  0.441479      fail
7   0.222222  1.069792  0.767470  0.554435  0.431584  0.407820      fail
8   0.250000  1.134375  0.846328  0.603822  0.445361  0.423993      fail
9   0.295455  1.134375  0.837749  0.622935  0.466330  0.438533      fail
10  0.289474  1.027303  0.797903  0.622207  0.462734  0.433881      pass
11  0.210526  1.119079  0.858697  0.673416  0.463163  0.435676      pass
12  0.250000  1.134375  0.872834  0.639298  0.465095  0.438912      pass
13  0.263158  1.180263  0.843462  0.622480  0.438541  0.414474      pass
14  0.250000  1.105313  0.800898  0.590538  0.424844  0.399822      pass
15  0.261905  1.175893  0.877121  0.634070  0.465616  0.444267      pass
16  0.318182  1.134375  0.843111  0.626963  0.460324  0.437982      pass
17  0.222222  1.166667  0.881076  0.636736  0.466265  0.438280      pass
18  0.261905  1.175893  0.892690  0.625815  0.441659  0.414868      pass
19  0.214286  1.120536  0.817392  0.605573  0.436815  0.406064      pass

BARINEL SCORES

         y 5       h 0      cx 1      cx 4      cx 3      cx 2
sum  0.51274  0.501647  0.500375  0.499653  0.496368  0.496262

TARANTULA SCORES

         y 5       h 0      cx 1      cx 4      cx 3      cx 2
sum  0.51274  0.501647  0.500375  0.499653  0.496368  0.496262

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_y_inGap_10_.qasm

100%|██████████| 10/10 [00:00<00:00, 12.35it/s]
100%|██████████| 10/10 [00:00<00:00, 12.25it/s]

         y 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.260870  1.121739  0.807745  0.599937  0.460207  0.434547      fail
1   0.272727  1.107955  0.857120  0.626125  0.450650  0.422066      fail
2   0.261905  1.148214  0.876228  0.647417  0.493431  0.467575      fail
3   0.250000  1.134375  0.822887  0.610706  0.440571  0.416994      fail
4   0.263158  1.119079  0.794655  0.548175  0.414182  0.394853      fail
5   0.342105  1.149671  0.842475  0.615899  0.466253  0.435132      fail
6   0.305556  1.166667  0.881076  0.673485  0.485549  0.456866      fail
7   0.250000  1.160795  0.879048  0.651691  0.480667  0.452321      fail
8   0.250000  1.192500  0.848203  0.651570  0.485972  0.459876      fail
9   0.275000  1.134375  0.856777  0.622701  0.476824  0.452972      fail
10  0.235294  1.185662  0.871875  0.658209  0.474033  0.448053      pass
11  0.238095  1.175893  0.898307  0.653168  0.464290  0.435335      pass
12  0.225000  1.105313  0.878086  0.634701  0.467867  0.440497      pass
13  0.225000  1.163438  0.857715  0.602810  0.444568  0.420475      pass
14  0.204545  1.134375  0.837749  0.581118  0.430277  0.410140      pass
15  0.325000  1.221563  0.904082  0.654640  0.467094  0.435338      pass
16  0.250000  1.187216  0.894762  0.641777  0.463162  0.434726      pass
17  0.275000  1.134375  0.818184  0.616804  0.425906  0.396574      pass
18  0.282609  1.172283  0.842935  0.632526  0.468749  0.438838      pass
19  0.205882  1.151471  0.820014  0.588887  0.435114  0.412121      pass

BARINEL SCORES

          y 5       h 0      cx 1      cx 2      cx 4      cx 3
sum  0.525482  0.506988  0.506158  0.499323  0.495747  0.495392

TARANTULA SCORES

          y 5       h 0      cx 1      cx 2      cx 4      cx 3
sum  0.525482  0.506988  0.506158  0.499323  0.495747  0.495392

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_x_inGap_4_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.49it/s]
100%|██████████| 10/10 [00:00<00:00, 10.12it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       x 0 pass/fail
0   0.189286  0.877121  0.657906  0.481588  0.457869  0.626205      fail
1   0.173512  0.855041  0.619561  0.445822  0.423422  0.556784      fail
2   0.165625  0.843111  0.626963  0.470859  0.449802  0.608525      fail
3   0.205060  0.893583  0.654160  0.475152  0.446148  0.598403      fail
4   0.139474  0.863919  0.654091  0.473274  0.446896  0.631165      fail
5   0.189286  0.892690  0.673806  0.504048  0.470610  0.646692      fail
6   0.150568  0.842259  0.613629  0.447315  0.421018  0.570949      fail
7   0.165625  0.872591  0.667093  0.474870  0.445500  0.605324      fail
8   0.198750  0.891348  0.660508  0.474639  0.448015  0.584106      fail
9   0.191776  0.884087  0.658446  0.491527  0.464758  0.636502      fail
10  0.198750  0.891348  0.639167  0.487533  0.456731  0.614694      pass
11  0.180682  0.853462  0.624731  0.452575  0.429090  0.563704      pass
12  0.176667  0.799427  0.609103  0.450822  0.416974  0.527893      pass
13  0.182188  0.863613  0.614994  0.447150  0.426005  0.566575      pass
14  0.174342  0.883100  0.661977  0.478670  0.449321  0.612233      pass
15  0.165625  0.843111  0.638004  0.454651  0.432256  0.579442      pass
16  0.202431  0.888672  0.612992  0.450932  0.425999  0.560711      pass
17  0.180682  0.873686  0.651656  0.461524  0.433755  0.589781      pass
18  0.132500  0.799961  0.613748  0.435303  0.407109  0.542950      pass
19  0.150568  0.801811  0.617233  0.436590  0.409824  0.539902      pass

BARINEL SCORES

          x 0       h 1      cx 2      cx 3      cx 4      cx 5
sum  0.515591  0.510671  0.509863  0.507931  0.506319  0.503491

TARANTULA SCORES

          x 0       h 1      cx 2      cx 3      cx 4      cx 5
sum  0.515591  0.510671  0.509863  0.507931  0.506319  0.503491

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_cx_inGap_3_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.27it/s]
100%|██████████| 10/10 [00:00<00:00, 10.28it/s]

        cx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.158424  0.841304  0.615626  0.594472  0.421835  0.403035      fail
1   0.198750  0.842305  0.632045  0.632420  0.454890  0.433293      fail
2   0.115217  0.805299  0.596799  0.588994  0.439077  0.417402      fail
3   0.173512  0.912984  0.680700  0.679918  0.499616  0.477844      fail
4   0.182188  0.885859  0.651583  0.642453  0.434529  0.410246      fail
5   0.165625  0.857972  0.638483  0.633880  0.471126  0.448197      fail
6   0.157738  0.838579  0.633429  0.640251  0.450544  0.426917      fail
7   0.122039  0.798890  0.602832  0.605438  0.457646  0.436487      fail
8   0.141964  0.800930  0.626432  0.661315  0.476884  0.450040      fail
9   0.165625  0.846328  0.649041  0.671218  0.472563  0.446149      fail
10  0.214338  0.886857  0.638765  0.606180  0.436701  0.416135      pass
11  0.214338  0.886857  0.672942  0.685469  0.476170  0.450399      pass
12  0.165625  0.843111  0.618604  0.603060  0.469987  0.443185      pass
13  0.151823  0.826025  0.615494  0.610522  0.471440  0.450114      pass
14  0.173512  0.823903  0.614374  0.603770  0.448142  0.426628      pass
15  0.195739  0.909624  0.661992  0.640108  0.479146  0.456649      pass
16  0.182188  0.857715  0.599492  0.544441  0.388667  0.368412      pass
17  0.173512  0.860658  0.639180  0.635897  0.487589  0.466146      pass
18  0.149063  0.855840  0.600281  0.550314  0.416828  0.401367      pass
19  0.165625  0.861871  0.647168  0.651923  0.463037  0.441890      pass

BARINEL SCORES

        cx 2      cx 1       h 0      cx 3     cx 4      cx 5
sum  0.50876  0.502249  0.501654  0.500739  0.49466  0.469604

TARANTULA SCORES

        cx 2      cx 1       h 0      cx 3     cx 4      cx 5
sum  0.50876  0.502249  0.501654  0.500739  0.49466  0.469604

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_x_inGap_9_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.83it/s]
100%|██████████| 10/10 [00:00<00:00, 12.81it/s]

         x 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.250000  1.134375  0.854053  0.656807  0.467215  0.441091      fail
1   0.204545  1.134375  0.867472  0.635269  0.454310  0.429399      fail
2   0.217391  1.147011  0.836990  0.610111  0.439403  0.418754      fail
3   0.315789  1.149671  0.859683  0.653220  0.465541  0.434838      fail
4   0.261905  1.175893  0.855934  0.664007  0.488623  0.461930      fail
5   0.275000  1.076250  0.761367  0.599435  0.449150  0.423952      fail
6   0.227273  1.134375  0.893058  0.659213  0.485072  0.463875      fail
7   0.263158  1.149671  0.876891  0.688280  0.508398  0.486175      fail
8   0.300000  1.163438  0.863613  0.638872  0.476287  0.448460      fail
9   0.250000  1.107955  0.836896  0.621618  0.449997  0.428537      fail
10  0.166667  1.134375  0.812435  0.614450  0.473414  0.449246      pass
11  0.315789  1.180263  0.843462  0.630208  0.442907  0.421943      pass
12  0.194444  1.166667  0.862912  0.653248  0.473050  0.442776      pass
13  0.200000  1.192500  0.897246  0.671912  0.480421  0.455492      pass
14  0.263158  1.210855  0.925699  0.666179  0.495098  0.468979      pass
15  0.300000  1.163438  0.879961  0.669935  0.481356  0.452712      pass
16  0.289474  1.119079  0.841488  0.642281  0.459488  0.435575      pass
17  0.236842  1.119079  0.824280  0.587862  0.425215  0.394622      pass
18  0.238095  1.148214  0.876228  0.647417  0.467422  0.441009      pass
19  0.272727  1.187216  0.844815  0.646977  0.464307  0.439342      pass

BARINEL SCORES

          x 5       h 0     cx 1      cx 2      cx 3      cx 4
sum  0.508713  0.501998  0.50114  0.499859  0.497003  0.494593

TARANTULA SCORES

          x 5       h 0     cx 1      cx 2      cx 3      cx 4
sum  0.508713  0.501998  0.50114  0.499859  0.497003  0.494593

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_x_inGap_5_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.52it/s]
100%|██████████| 10/10 [00:00<00:00, 10.44it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       x 0 pass/fail
0   0.209211  0.942907  0.679518  0.512742  0.488471  0.680418      fail
1   0.220833  0.915662  0.672571  0.489301  0.465165  0.660005      fail
2   0.191776  0.884087  0.653823  0.476516  0.449644  0.621934      fail
3   0.198750  0.880898  0.645652  0.440356  0.413093  0.570878      fail
4   0.173512  0.818285  0.595036  0.432872  0.404926  0.548251      fail
5   0.210795  0.875391  0.627546  0.460256  0.435378  0.611374      fail
6   0.189286  0.861551  0.647943  0.486377  0.467137  0.645991      fail
7   0.173512  0.897414  0.627281  0.447280  0.418641  0.563432      fail
8   0.165625  0.884922  0.671843  0.496378  0.469199  0.638855      fail
9   0.209211  0.878865  0.657259  0.486488  0.461631  0.638130      fail
10  0.172826  0.836990  0.606612  0.443669  0.414647  0.550244      pass
11  0.165625  0.837153  0.657575  0.485148  0.460712  0.614169      pass
12  0.157738  0.844196  0.612791  0.454601  0.429580  0.570188      pass
13  0.175368  0.820014  0.631701  0.462026  0.439602  0.606371      pass
14  0.155882  0.857376  0.633852  0.455737  0.426713  0.553881      pass
15  0.202431  0.906836  0.669568  0.493894  0.463663  0.654955      pass
16  0.182188  0.879961  0.644572  0.474700  0.449325  0.608304      pass
17  0.180682  0.928995  0.698639  0.503724  0.473721  0.646527      pass
18  0.149063  0.861738  0.641146  0.463648  0.436183  0.583825      pass
19  0.141964  0.800930  0.591102  0.426304  0.403394  0.515039      pass

BARINEL SCORES

         cx 5       x 0      cx 4       h 1      cx 3      cx 2
sum  0.535676  0.511412  0.507632  0.504269  0.503533  0.503466

TARANTULA SCORES

         cx 5       x 0      cx 4       h 1      cx 3      cx 2
sum  0.535676  0.511412  0.507632  0.504269  0.503533  0.503466

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_swap_inGap_2_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.95it/s]
100%|██████████| 10/10 [00:01<00:00,  9.10it/s]

        cx 5      cx 4      cx 3      cx 2    swap 1       h 0 pass/fail
0   0.180682  0.853462  0.624731  0.453438  0.395447  0.357243      fail
1   0.182188  0.841367  0.662964  0.483809  0.444782  0.401293      fail
2   0.174342  0.848684  0.612447  0.461742  0.407082  0.364665      fail
3   0.165625  0.785488  0.577872  0.419521  0.424476  0.374463      fail
4   0.182188  0.896309  0.649122  0.483822  0.465835  0.411888      fail
5   0.165625  0.856777  0.616824  0.437190  0.334043  0.314089      fail
6   0.165625  0.879023  0.647515  0.466030  0.433277  0.385972      fail
7   0.180682  0.838601  0.634919  0.465044  0.385251  0.350371      fail
8   0.189286  0.877121  0.657554  0.472283  0.405745  0.368466      fail
9   0.210795  0.895614  0.669168  0.490411  0.427880  0.386123      fail
10  0.141964  0.827734  0.611260  0.461495  0.434607  0.386814      pass
11  0.157738  0.859766  0.637128  0.473156  0.405991  0.367449      pass
12  0.165625  0.879023  0.652318  0.471849  0.398883  0.359994      pass
13  0.157738  0.880952  0.622590  0.474287  0.410959  0.368738      pass
14  0.158424  0.841304  0.619445  0.450293  0.407113  0.363197      pass
15  0.179427  0.827588  0.606866  0.455209  0.393815  0.356491      pass
16  0.156908  0.818072  0.636629  0.462317  0.388287  0.353662      pass
17  0.165625  0.878196  0.634296  0.457246  0.372886  0.339062      pass
18  0.182188  0.841367  0.602283  0.441333  0.385892  0.344756      pass
19  0.126190  0.773233  0.566012  0.410890  0.376967  0.339439      pass

BARINEL SCORES

         cx 5       h 0    swap 1     cx 3      cx 4      cx 2
sum  0.530277  0.509252  0.509163  0.50655  0.504271  0.504091

TARANTULA SCORES

         cx 5       h 0    swap 1     cx 3      cx 4      cx 2
sum  0.530277  0.509252  0.509163  0.50655  0.504271  0.504091

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_sx_inGap_2_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.53it/s]
100%|██████████| 10/10 [00:01<00:00,  9.61it/s]

        cx 5      cx 4      cx 3      cx 2       h 1    sxdg 0 pass/fail
0   0.172826  0.875679  0.660363  0.491316  0.461797  0.612584      fail
1   0.157738  0.811775  0.586978  0.421727  0.394515  0.488734      fail
2   0.132500  0.822207  0.614314  0.454654  0.431655  0.575809      fail
3   0.165625  0.845345  0.626987  0.461530  0.438359  0.573597      fail
4   0.198750  0.876719  0.657378  0.476124  0.447301  0.576051      fail
5   0.139474  0.799877  0.594678  0.440100  0.412482  0.546679      fail
6   0.165625  0.840430  0.629515  0.465479  0.437871  0.573199      fail
7   0.141964  0.816499  0.573046  0.429974  0.409095  0.526466      fail
8   0.201630  0.905740  0.671476  0.474417  0.444432  0.568650      fail
9   0.157738  0.838579  0.617679  0.470958  0.440895  0.582632      fail
10  0.156908  0.858697  0.650564  0.468794  0.438548  0.575660      pass
11  0.180682  0.873686  0.628904  0.439651  0.414008  0.509550      pass
12  0.182188  0.841367  0.630964  0.467141  0.435610  0.579781      pass
13  0.141964  0.858873  0.614030  0.429345  0.402460  0.499933      pass
14  0.180682  0.868324  0.644237  0.458735  0.431619  0.555518      pass
15  0.156908  0.864905  0.637821  0.457159  0.428663  0.549761      pass
16  0.187228  0.862279  0.622137  0.446858  0.423521  0.532681      pass
17  0.165625  0.856777  0.613506  0.462634  0.438132  0.578302      pass
18  0.141964  0.779743  0.575836  0.434372  0.412912  0.528762      pass
19  0.180682  0.853462  0.633091  0.450371  0.422359  0.533698      pass

BARINEL SCORES

       sxdg 0       h 1      cx 2      cx 3      cx 4     cx 5
sum  0.508166  0.504119  0.503913  0.499252  0.497485  0.49381

TARANTULA SCORES

       sxdg 0       h 1      cx 2      cx 3      cx 4     cx 5
sum  0.508166  0.504119  0.503913  0.499252  0.497485  0.49381

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_ry_inGap_5_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.06it/s]
100%|██████████| 10/10 [00:01<00:00,  9.82it/s]

        cx 5      cx 4      cx 3      cx 2       h 1      ry 0 pass/fail
0   0.189286  0.871503  0.621444  0.458586  0.432052  0.527641      fail
1   0.215312  0.875938  0.627207  0.457622  0.432357  0.538628      fail
2   0.198750  0.897246  0.662716  0.483011  0.459465  0.564711      fail
3   0.191776  0.877878  0.654170  0.486089  0.462412  0.563010      fail
4   0.189286  0.824795  0.614660  0.425037  0.397437  0.490713      fail
5   0.187228  0.842935  0.639230  0.465773  0.439517  0.542269      fail
6   0.173512  0.855041  0.635662  0.487827  0.467507  0.564604      fail
7   0.172826  0.884766  0.654404  0.485333  0.458214  0.556194      fail
8   0.180682  0.873686  0.643938  0.467024  0.439966  0.539025      fail
9   0.173512  0.849423  0.623707  0.438783  0.413200  0.496658      fail
10  0.182188  0.863613  0.652871  0.488885  0.465820  0.565975      pass
11  0.180682  0.879048  0.648340  0.473931  0.444043  0.541733      pass
12  0.220833  0.878906  0.659963  0.485399  0.454521  0.562609      pass
13  0.182188  0.902207  0.660232  0.474721  0.443198  0.542090      pass
14  0.165625  0.837749  0.618903  0.448112  0.423200  0.506080      pass
15  0.174342  0.889309  0.674802  0.506068  0.479718  0.579902      pass
16  0.174342  0.836266  0.638321  0.451836  0.422139  0.519548      pass
17  0.189286  0.877121  0.625313  0.454253  0.425386  0.522230      pass
18  0.175368  0.865418  0.664613  0.468767  0.436325  0.521962      pass
19  0.173512  0.818285  0.609762  0.446468  0.422661  0.509059      pass

BARINEL SCORES

        cx 5     ry 0      cx 4       h 1      cx 2      cx 3
sum  0.50729  0.50057  0.500153  0.499156  0.497682  0.497039

TARANTULA SCORES

        cx 5     ry 0      cx 4       h 1      cx 2      cx 3
sum  0.50729  0.50057  0.500153  0.499156  0.497682  0.497039

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_ccx_inGap_3_.qasm

100%|██████████| 10/10 [00:02<00:00,  4.93it/s]
100%|██████████| 10/10 [00:01<00:00,  5.15it/s]

        cx 5      cx 4      cx 3     ccx 2      cx 1       h 0 pass/fail
0   0.182188  0.857715  0.614955  0.498430  0.363876  0.338760      fail
1   0.165625  0.856777  0.626019  0.501810  0.377976  0.354370      fail
2   0.195739  0.869176  0.652937  0.513036  0.377512  0.354960      fail
3   0.182188  0.819121  0.623057  0.487980  0.362491  0.342040      fail
4   0.195739  0.859677  0.644440  0.507529  0.382223  0.359286      fail
5   0.202431  0.888672  0.679199  0.528496  0.389547  0.359598      fail
6   0.173512  0.876228  0.663166  0.518826  0.381428  0.351524      fail
7   0.158424  0.841304  0.630327  0.497595  0.368626  0.349923      fail
8   0.149063  0.811348  0.620857  0.483779  0.356802  0.332784      fail
9   0.165625  0.826807  0.616701  0.486976  0.357539  0.331405      fail
10  0.182188  0.874062  0.644532  0.512227  0.378597  0.356558      pass
11  0.165625  0.824082  0.587793  0.478384  0.352174  0.326066      pass
12  0.149063  0.878086  0.641674  0.513760  0.381248  0.351697      pass
13  0.182188  0.879961  0.644203  0.515094  0.386927  0.365930      pass
14  0.191776  0.866879  0.645107  0.508493  0.372886  0.351766      pass
15  0.184028  0.862912  0.630404  0.505252  0.374502  0.343327      pass
16  0.209211  0.902282  0.665583  0.529353  0.392215  0.367051      pass
17  0.214338  0.925322  0.631803  0.528027  0.395288  0.368069      pass
18  0.184028  0.862912  0.635284  0.505124  0.365733  0.336424      pass
19  0.173512  0.891797  0.633544  0.515100  0.384476  0.358249      pass

BARINEL SCORES

         cx 3       h 0    ccx 2    cx 1      cx 4     cx 5
sum  0.500461  0.496394  0.49574  0.4956  0.492432  0.49093

TARANTULA SCORES

         cx 3       h 0    ccx 2    cx 1      cx 4     cx 5
sum  0.500461  0.496394  0.49574  0.4956  0.492432  0.49093

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_h_inGap_2_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.61it/s]
100%|██████████| 10/10 [00:00<00:00, 10.11it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       h 0 pass/fail
0   0.180682  0.823739  0.605014  0.446377  0.421032  0.406088      fail
1   0.205060  0.878013  0.661743  0.488072  0.454638  0.427018      fail
2   0.198750  0.842305  0.606681  0.474986  0.452697  0.431886      fail
3   0.198750  0.825957  0.660568  0.488571  0.461372  0.439697      fail
4   0.209211  0.942907  0.689197  0.503528  0.482453  0.455274      fail
5   0.129620  0.820329  0.627635  0.454969  0.433032  0.414400      fail
6   0.139474  0.793668  0.588428  0.460584  0.441436  0.417689      fail
7   0.158424  0.855520  0.620224  0.468869  0.442745  0.416464      fail
8   0.182188  0.835469  0.598220  0.455417  0.431258  0.405502      fail
9   0.149063  0.817246  0.594795  0.439541  0.415581  0.390028      fail
10  0.182188  0.802773  0.604138  0.444175  0.420586  0.396774      pass
11  0.156908  0.818072  0.583198  0.427187  0.407411  0.383399      pass
12  0.195739  0.869176  0.637904  0.453360  0.426639  0.399744      pass
13  0.165625  0.779590  0.602491  0.443141  0.415967  0.401833      pass
14  0.141964  0.853255  0.605586  0.435330  0.411647  0.387904      pass
15  0.198750  0.887865  0.675179  0.473455  0.443719  0.426011      pass
16  0.191776  0.820045  0.599032  0.453292  0.430132  0.399149      pass
17  0.182188  0.908105  0.673121  0.498327  0.470492  0.443652      pass
18  0.173512  0.860658  0.623782  0.446612  0.416481  0.393961      pass
19  0.187228  0.904925  0.653271  0.468143  0.442235  0.417197      pass

BARINEL SCORES

          h 0       h 1      cx 2      cx 3      cx 4      cx 5
sum  0.509355  0.508653  0.507475  0.499792  0.497954  0.496504

TARANTULA SCORES

          h 0       h 1      cx 2      cx 3      cx 4      cx 5
sum  0.509355  0.508653  0.507475  0.499792  0.497954  0.496504

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_ccx_inGap_5_.qasm

100%|██████████| 10/10 [00:01<00:00,  5.43it/s]
100%|██████████| 10/10 [00:02<00:00,  4.90it/s]

        cx 5     ccx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.182188  0.908174  0.701990  0.516414  0.377103  0.353004      fail
1   0.198750  0.918765  0.686405  0.508037  0.373282  0.349493      fail
2   0.182188  0.908174  0.671201  0.493646  0.356302  0.334296      fail
3   0.207031  0.924060  0.699514  0.532749  0.391325  0.370927      fail
4   0.205060  0.922799  0.689571  0.510380  0.379198  0.355412      fail
5   0.216033  0.929816  0.716458  0.528573  0.382440  0.362718      fail
6   0.205060  0.922799  0.693440  0.511902  0.374516  0.353172      fail
7   0.194853  0.916273  0.706650  0.515357  0.373319  0.349369      fail
8   0.198750  0.918765  0.700731  0.533713  0.387343  0.365932      fail
9   0.173512  0.902626  0.654908  0.476109  0.346086  0.327756      fail
10  0.173512  0.902626  0.682195  0.499269  0.364451  0.344832      pass
11  0.173512  0.902626  0.684231  0.522425  0.380506  0.360344      pass
12  0.128819  0.874048  0.676327  0.500277  0.356634  0.334751      pass
13  0.189286  0.912713  0.704414  0.518358  0.377218  0.354797      pass
14  0.184028  0.909351  0.685672  0.505634  0.365303  0.340996      pass
15  0.150568  0.887955  0.665538  0.491850  0.356214  0.335395      pass
16  0.165625  0.897583  0.671780  0.490721  0.353809  0.336282      pass
17  0.184028  0.909351  0.658351  0.483102  0.346524  0.325522      pass
18  0.157738  0.892540  0.677692  0.505533  0.363213  0.342457      pass
19  0.174342  0.903157  0.697062  0.510072  0.374068  0.356357      pass

BARINEL SCORES

        cx 5      cx 1       h 0     ccx 4      cx 2      cx 3
sum  0.53868  0.506978  0.506496  0.504963  0.504906  0.504285

TARANTULA SCORES

        cx 5      cx 1       h 0     ccx 4      cx 2      cx 3
sum  0.53868  0.506978  0.506496  0.504963  0.504906  0.504285

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_y_inGap_4_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.44it/s]
100%|██████████| 10/10 [00:01<00:00,  9.84it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       y 0 pass/fail
0   0.165625  0.886589  0.634303  0.452859  0.424007  0.581651      fail
1   0.172826  0.822775  0.612537  0.448610  0.429323  0.563861      fail
2   0.150568  0.877344  0.652714  0.463817  0.433958  0.607501      fail
3   0.174342  0.894100  0.632688  0.462707  0.433227  0.596796      fail
4   0.165625  0.884922  0.659698  0.484034  0.459137  0.648041      fail
5   0.180682  0.893910  0.675229  0.485905  0.459254  0.635494      fail
6   0.173512  0.876228  0.658983  0.486345  0.460831  0.620392      fail
7   0.201630  0.896654  0.670731  0.481759  0.453268  0.611681      fail
8   0.165625  0.857972  0.638483  0.469891  0.445068  0.600039      fail
9   0.215312  0.898184  0.673361  0.486126  0.459508  0.618712      fail
10  0.194853  0.801884  0.583887  0.418194  0.392917  0.494356      pass
11  0.179427  0.841211  0.628162  0.460436  0.431597  0.571426      pass
12  0.189286  0.845982  0.630949  0.443195  0.415191  0.549811      pass
13  0.180682  0.853462  0.651141  0.462631  0.434239  0.578841      pass
14  0.198750  0.919492  0.687941  0.479542  0.448778  0.628044      pass
15  0.165625  0.852610  0.612373  0.460003  0.434370  0.586835      pass
16  0.182188  0.885859  0.673292  0.497973  0.466923  0.645420      pass
17  0.165625  0.837153  0.610200  0.452809  0.424968  0.556394      pass
18  0.220833  0.883160  0.644017  0.476556  0.449994  0.585336      pass
19  0.182188  0.819121  0.621202  0.447035  0.420437  0.544085      pass

BARINEL SCORES

         y 0       h 1      cx 4      cx 2      cx 3      cx 5
sum  0.51453  0.507871  0.507177  0.506635  0.506441  0.487076

TARANTULA SCORES

         y 0       h 1      cx 4      cx 2      cx 3      cx 5
sum  0.51453  0.507871  0.507177  0.506635  0.506441  0.487076

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_h_inGap_3_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.22it/s]
100%|██████████| 10/10 [00:01<00:00,  9.73it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       h 0 pass/fail
0   0.172826  0.856335  0.657306  0.463089  0.435628  0.413864      fail
1   0.210795  0.915838  0.692100  0.491772  0.460783  0.436118      fail
2   0.182188  0.857715  0.653201  0.455646  0.432724  0.409472      fail
3   0.195739  0.879901  0.652338  0.489235  0.466386  0.437014      fail
4   0.195739  0.854315  0.629706  0.469255  0.443064  0.416683      fail
5   0.157738  0.854148  0.654606  0.487190  0.459969  0.433830      fail
6   0.189286  0.919494  0.665625  0.489574  0.461082  0.448697      fail
7   0.191776  0.860670  0.662906  0.457085  0.426937  0.395608      fail
8   0.172826  0.875679  0.664540  0.469802  0.439196  0.410815      fail
9   0.135511  0.841406  0.635704  0.467482  0.444956  0.422873      fail
10  0.157738  0.859766  0.613293  0.426821  0.402083  0.386312      pass
11  0.149063  0.833594  0.628765  0.477333  0.459978  0.440181      pass
12  0.165625  0.818184  0.615730  0.474019  0.450643  0.423787      pass
13  0.165625  0.854053  0.631704  0.457135  0.435179  0.409032      pass
14  0.189286  0.867169  0.615739  0.444421  0.422187  0.400416      pass
15  0.156908  0.841488  0.636837  0.455910  0.425595  0.400578      pass
16  0.165625  0.817525  0.611379  0.451239  0.428224  0.399885      pass
17  0.165625  0.887695  0.633103  0.451428  0.422001  0.406389      pass
18  0.139474  0.810876  0.587464  0.424871  0.395025  0.369383      pass
19  0.198750  0.935840  0.681127  0.500825  0.473789  0.451438      pass

BARINEL SCORES

        cx 5    cx 3      cx 2       h 1       h 0     cx 4
sum  0.52179  0.5122  0.509465  0.508879  0.508275  0.50549

TARANTULA SCORES

        cx 5    cx 3      cx 2       h 1       h 0     cx 4
sum  0.52179  0.5122  0.509465  0.508879  0.508275  0.50549

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_rxx_inGap_4_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.18it/s]
100%|██████████| 10/10 [00:00<00:00, 11.88it/s]

        cx 5      cx 4     rxx 3      cx 2      cx 1       h 0 pass/fail
0   0.182188  0.857715  0.990273  0.577496  0.423067  0.400372      fail
1   0.150568  0.807173  0.891140  0.565355  0.422064  0.395387      fail
2   0.150568  0.822035  0.918945  0.555178  0.390594  0.360516      fail
3   0.157738  0.780636  0.877046  0.527667  0.388379  0.366761      fail
4   0.165625  0.835514  0.925863  0.587586  0.422432  0.397368      fail
5   0.182188  0.841367  0.947656  0.559216  0.412498  0.390813      fail
6   0.215312  0.875937  1.014141  0.557686  0.409061  0.380541      fail
7   0.182188  0.857715  0.979336  0.569164  0.419591  0.390579      fail
8   0.173512  0.860658  0.983780  0.577537  0.424008  0.400273      fail
9   0.174342  0.865892  1.012644  0.581693  0.419662  0.389843      fail
10  0.184028  0.831641  0.912457  0.560946  0.397010  0.369780      pass
11  0.173512  0.855041  0.947117  0.591700  0.429505  0.405983      pass
12  0.173512  0.839472  0.948940  0.571682  0.435387  0.411454      pass
13  0.175368  0.839246  0.915947  0.569513  0.403837  0.376731      pass
14  0.191776  0.901295  1.028742  0.615532  0.441618  0.417834      pass
15  0.189286  0.877121  0.984487  0.607488  0.445379  0.417898      pass
16  0.165625  0.898199  0.992860  0.636103  0.460434  0.429914      pass
17  0.165625  0.879023  0.965879  0.619889  0.446974  0.414519      pass
18  0.173512  0.897414  1.002623  0.625117  0.455787  0.425555      pass
19  0.165625  0.828249  0.935316  0.585753  0.440042  0.408877      pass

BARINEL SCORES

        rxx 3      cx 5      cx 4      h 0      cx 1      cx 2
sum  0.497561  0.496615  0.492902  0.48704  0.486768  0.486036

TARANTULA SCORES

        rxx 3      cx 5      cx 4      h 0      cx 1      cx 2
sum  0.497561  0.496615  0.492902  0.48704  0.486768  0.486036

ERROR GATE LOCATION:
3
Now evolving the following mutant:  AddGate_y_inGap_5_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.46it/s]
100%|██████████| 10/10 [00:00<00:00, 10.02it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       y 0 pass/fail
0   0.215312  0.904082  0.676349  0.491046  0.464460  0.656346      fail
1   0.182188  0.825020  0.592191  0.429251  0.407729  0.554532      fail
2   0.216033  0.954331  0.692702  0.504283  0.477025  0.667037      fail
3   0.210795  0.915838  0.681059  0.485691  0.457209  0.646914      fail
4   0.180682  0.823739  0.592996  0.428988  0.405015  0.541423      fail
5   0.173512  0.818285  0.622352  0.456774  0.428647  0.587624      fail
6   0.201630  0.877310  0.646232  0.484977  0.462299  0.642760      fail
7   0.165625  0.830599  0.625254  0.461391  0.427283  0.559977      fail
8   0.198750  0.858652  0.628549  0.439529  0.409395  0.566037      fail
9   0.182188  0.869512  0.634519  0.447205  0.421613  0.579841      fail
10  0.147222  0.817947  0.585486  0.440413  0.417738  0.545704      pass
11  0.182188  0.879961  0.636862  0.460330  0.434220  0.588355      pass
12  0.198750  0.825957  0.606859  0.442084  0.414055  0.570697      pass
13  0.189286  0.898307  0.652145  0.476802  0.449651  0.626125      pass
14  0.158424  0.802615  0.597339  0.438469  0.410826  0.547421      pass
15  0.128819  0.798741  0.596784  0.433210  0.409976  0.529737      pass
16  0.205060  0.930339  0.660478  0.482580  0.458165  0.629658      pass
17  0.158424  0.889079  0.646437  0.469166  0.440067  0.582131      pass
18  0.139474  0.817085  0.617696  0.435106  0.413060  0.527256      pass
19  0.173512  0.845089  0.618002  0.459332  0.434227  0.600615      pass

BARINEL SCORES

         cx 5       y 0      cx 3      cx 4      cx 2       h 1
sum  0.534031  0.510842  0.506904  0.505012  0.504999  0.504552

TARANTULA SCORES

         cx 5       y 0      cx 3      cx 4      cx 2       h 1
sum  0.534031  0.510842  0.506904  0.505012  0.504999  0.504552

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_cx_inGap_5_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.22it/s]
100%|██████████| 10/10 [00:00<00:00, 12.03it/s]

        cx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.220833  1.292578  0.978693  0.680375  0.484116  0.458621      fail
1   0.202431  1.224414  0.929405  0.674684  0.494601  0.466255      fail
2   0.210795  1.255398  0.949240  0.685751  0.483484  0.455251      fail
3   0.165625  1.088086  0.817270  0.638561  0.466160  0.444515      fail
4   0.182188  1.149434  0.881553  0.627245  0.470661  0.448260      fail
5   0.198750  1.210781  0.916716  0.710193  0.532988  0.508667      fail
6   0.179427  1.139209  0.832429  0.612531  0.433638  0.410511      fail
7   0.195739  1.199627  0.899264  0.683203  0.505499  0.480668      fail
8   0.174342  1.120374  0.856033  0.637344  0.475339  0.451928      fail
9   0.195739  1.199627  0.883835  0.621134  0.453079  0.427223      fail
10  0.191776  1.184951  0.876674  0.671543  0.480107  0.451803      pass
11  0.173512  1.117299  0.786278  0.604168  0.440689  0.413529      pass
12  0.150568  1.032315  0.744846  0.558013  0.419531  0.397936      pass
13  0.139474  0.991221  0.733607  0.546819  0.406875  0.393890      pass
14  0.132500  0.965391  0.728666  0.528880  0.377136  0.352238      pass
15  0.175368  1.124173  0.842361  0.614630  0.444549  0.416247      pass
16  0.174342  1.120374  0.847846  0.655212  0.475193  0.444335      pass
17  0.226645  1.314104  0.934330  0.702837  0.512874  0.484971      pass
18  0.156908  1.055798  0.781794  0.549456  0.381447  0.357572      pass
19  0.198750  1.210781  0.935107  0.688139  0.509821  0.487926      pass

BARINEL SCORES

         cx 5      cx 3       h 0      cx 1      cx 2      cx 4
sum  0.528256  0.521361  0.520078  0.518996  0.517782  0.516593

TARANTULA SCORES

         cx 5      cx 3       h 0      cx 1      cx 2      cx 4
sum  0.528256  0.521361  0.520078  0.518996  0.517782  0.516593

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_h_inGap_10_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.19it/s]
100%|██████████| 10/10 [00:00<00:00, 12.62it/s]

         h 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.189474  0.985855  0.710280  0.512496  0.575172  0.596642      fail
1   0.143478  1.041848  0.789385  0.579063  0.562518  0.570439      fail
2   0.169565  1.052989  0.794803  0.587172  0.605316  0.626152      fail
3   0.180000  1.065937  0.742715  0.540515  0.555237  0.570842      fail
4   0.163636  1.019318  0.773899  0.583497  0.581598  0.599284      fail
5   0.177273  1.057955  0.809073  0.590402  0.611443  0.632625      fail
6   0.150000  1.053125  0.769453  0.569999  0.555424  0.568423      fail
7   0.157143  1.143750  0.830339  0.611033  0.592850  0.611277      fail
8   0.157143  1.111310  0.793545  0.596505  0.607925  0.620506      fail
9   0.171429  1.027679  0.764286  0.614930  0.623614  0.646981      fail
10  0.105000  1.075000  0.824687  0.586744  0.503223  0.522168      pass
11  0.093750  1.086719  0.813013  0.606622  0.580140  0.579447      pass
12  0.150000  1.053125  0.799746  0.603619  0.592876  0.607317      pass
13  0.142105  1.050000  0.782895  0.613692  0.544462  0.569083      pass
14  0.133333  1.035417  0.743229  0.568244  0.527126  0.543753      pass
15  0.157895  1.008224  0.770354  0.575950  0.585587  0.598574      pass
16  0.122727  1.043750  0.783452  0.566290  0.518040  0.538099      pass
17  0.165000  1.105625  0.803945  0.571666  0.545770  0.566940      pass
18  0.110526  1.061842  0.792516  0.595721  0.536787  0.549504      pass
19  0.150000  1.141667  0.837999  0.635053  0.618158  0.635685      pass

BARINEL SCORES

          h 5       h 0     cx 1      cx 4      cx 3      cx 2
sum  0.554993  0.514149  0.51396  0.497606  0.494467  0.494108

TARANTULA SCORES

          h 5       h 0     cx 1      cx 4      cx 3      cx 2
sum  0.554993  0.514149  0.51396  0.497606  0.494467  0.494108

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_sx_inGap_6_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.84it/s]
100%|██████████| 10/10 [00:00<00:00, 12.33it/s]

      sxdg 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.400000  1.028125  0.804355  0.569700  0.407886  0.383464      fail
1   0.417391  1.036141  0.736770  0.541792  0.382439  0.361000      fail
2   0.436364  1.044886  0.765749  0.540300  0.392505  0.369952      fail
3   0.472727  1.061648  0.805469  0.559291  0.407037  0.377044      fail
4   0.457143  1.054464  0.779613  0.568337  0.405147  0.377188      fail
5   0.419048  1.036905  0.782403  0.558893  0.411673  0.377816      fail
6   0.400000  1.028125  0.735265  0.533964  0.391049  0.367809      fail
7   0.452174  1.052174  0.761600  0.564711  0.399398  0.374880      fail
8   0.363636  1.011364  0.712731  0.518468  0.365820  0.339690      fail
9   0.457143  1.054464  0.747321  0.537323  0.398202  0.371548      fail
10  0.320000  0.991250  0.764805  0.573174  0.416567  0.385709      pass
11  0.417391  1.036141  0.766253  0.567648  0.402459  0.375720      pass
12  0.329412  0.995588  0.743957  0.533062  0.385899  0.366292      pass
13  0.421053  1.037829  0.787294  0.561671  0.409152  0.385387      pass
14  0.520000  1.083438  0.804648  0.569331  0.398839  0.373182      pass
15  0.400000  1.028125  0.753551  0.576592  0.414639  0.389035      pass
16  0.382609  1.020109  0.741423  0.520455  0.368984  0.340649      pass
17  0.382609  1.020109  0.741423  0.551876  0.398597  0.376427      pass
18  0.266667  0.966667  0.715430  0.506805  0.366755  0.343987      pass
19  0.440000  1.046563  0.800215  0.564156  0.401974  0.374045      pass

BARINEL SCORES

       sxdg 5      cx 4      cx 3      cx 1       h 0      cx 2
sum  0.524272  0.504422  0.500403  0.499829  0.499322  0.498548

TARANTULA SCORES

       sxdg 5      cx 4      cx 3      cx 1       h 0      cx 2
sum  0.524272  0.504422  0.500403  0.499829  0.499322  0.498548

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_ccx_inGap_8_.qasm

100%|██████████| 10/10 [00:03<00:00,  3.33it/s]
100%|██████████| 10/10 [00:03<00:00,  3.31it/s]

       ccx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.176953  0.819714  0.651432  0.516374  0.418197  0.390891      fail
1   0.174256  0.810000  0.634351  0.467509  0.381748  0.351828      fail
2   0.176953  0.796447  0.634641  0.476735  0.387890  0.365472      fail
3   0.178057  0.793040  0.624939  0.474479  0.382614  0.361277      fail
4   0.172962  0.822034  0.611929  0.446048  0.362334  0.335308      fail
5   0.175000  0.787877  0.602388  0.438559  0.357932  0.336426      fail
6   0.176359  0.810496  0.659813  0.481614  0.388798  0.365653      fail
7   0.175355  0.767954  0.628855  0.483583  0.392613  0.363624      fail
8   0.175355  0.826525  0.672081  0.510891  0.416578  0.388937      fail
9   0.178906  0.830727  0.656874  0.501114  0.402465  0.383954      fail
10  0.177878  0.810113  0.638094  0.517525  0.416874  0.392128      pass
11  0.178906  0.830727  0.687102  0.525466  0.427293  0.399872      pass
12  0.183557  0.832087  0.692998  0.536478  0.432473  0.402711      pass
13  0.177976  0.797363  0.645036  0.486554  0.398714  0.376116      pass
14  0.181076  0.834819  0.671709  0.493176  0.408830  0.383458      pass
15  0.172396  0.823999  0.658902  0.487192  0.395917  0.367926      pass
16  0.178057  0.797715  0.618089  0.458384  0.369827  0.344348      pass
17  0.179934  0.849284  0.667848  0.482980  0.393296  0.362312      pass
18  0.178906  0.805016  0.614720  0.446085  0.360494  0.337363      pass
19  0.177976  0.875763  0.688388  0.492218  0.398096  0.370047      pass

BARINEL SCORES

        ccx 5      cx 4       h 0      cx 2      cx 1      cx 3
sum  0.496263  0.494116  0.493705  0.493359  0.492991  0.492069

TARANTULA SCORES

        ccx 5      cx 4       h 0      cx 2      cx 1      cx 3
sum  0.496263  0.494116  0.493705  0.493359  0.492991  0.492069

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_ccx_inGap_9_.qasm

100%|██████████| 10/10 [00:02<00:00,  3.48it/s]
100%|██████████| 10/10 [00:02<00:00,  3.61it/s]

       ccx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.213383  0.807694  0.621077  0.516500  0.395151  0.371657      fail
1   0.217783  0.785865  0.593616  0.468855  0.358331  0.339307      fail
2   0.214063  0.842681  0.683509  0.548818  0.415375  0.385933      fail
3   0.218750  0.766482  0.613293  0.481812  0.370295  0.346396      fail
4   0.215625  0.856061  0.651416  0.534640  0.407980  0.382717      fail
5   0.217783  0.785865  0.605419  0.486871  0.374286  0.345256      fail
6   0.215625  0.752817  0.569855  0.459546  0.348908  0.325483      fail
7   0.215625  0.832793  0.656602  0.533570  0.409591  0.381992      fail
8   0.216295  0.785595  0.625006  0.520468  0.398834  0.369410      fail
9   0.216903  0.788287  0.633180  0.522087  0.402041  0.374632      fail
10  0.214885  0.832160  0.629840  0.515383  0.395539  0.367858      pass
11  0.214885  0.856652  0.682363  0.561784  0.427199  0.399349      pass
12  0.214062  0.824181  0.588333  0.470283  0.361135  0.335611      pass
13  0.217783  0.808025  0.630537  0.500866  0.385659  0.357641      pass
14  0.215799  0.813194  0.631860  0.507385  0.384642  0.359650      pass
15  0.213318  0.804428  0.613943  0.507298  0.387053  0.360281      pass
16  0.215483  0.818428  0.645836  0.532011  0.409458  0.383305      pass
17  0.212500  0.842396  0.649885  0.540263  0.410088  0.381485      pass
18  0.218174  0.769251  0.593659  0.467529  0.354847  0.335156      pass
19  0.214063  0.785973  0.631194  0.525804  0.407691  0.383302      pass

BARINEL SCORES

        ccx 5      cx 3      cx 2      cx 1       h 0      cx 4
sum  0.501262  0.498228  0.497283  0.497276  0.497196  0.495342

TARANTULA SCORES

        ccx 5      cx 3      cx 2      cx 1       h 0      cx 4
sum  0.501262  0.498228  0.497283  0.497276  0.497196  0.495342

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_cx_inGap_10_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.72it/s]
100%|██████████| 10/10 [00:00<00:00, 10.43it/s]

        cx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.198750  0.949004  0.666495  0.575727  0.427408  0.398161      fail
1   0.165625  0.821236  0.576200  0.485705  0.355374  0.332839      fail
2   0.209211  0.902282  0.603969  0.548947  0.409498  0.383618      fail
3   0.173512  0.862388  0.665368  0.539211  0.394372  0.367478      fail
4   0.175368  0.856342  0.669665  0.571453  0.424995  0.401638      fail
5   0.173512  0.902604  0.677225  0.582762  0.421975  0.392823      fail
6   0.226645  0.901357  0.689510  0.575434  0.418516  0.387146      fail
7   0.205060  0.900930  0.650421  0.598519  0.432747  0.401491      fail
8   0.149063  0.815430  0.574449  0.470454  0.338100  0.319038      fail
9   0.165625  0.836764  0.613719  0.523021  0.382325  0.358270      fail
10  0.141964  0.774554  0.598410  0.500107  0.356605  0.333583      pass
11  0.182188  0.898125  0.654353  0.544498  0.381220  0.352717      pass
12  0.147222  0.825521  0.606146  0.501978  0.367126  0.345131      pass
13  0.184028  0.834158  0.639861  0.551296  0.403171  0.371605      pass
14  0.180682  0.867489  0.646674  0.543562  0.379439  0.350536      pass
15  0.174342  0.914165  0.704509  0.616405  0.445424  0.413962      pass
16  0.132500  0.790430  0.590619  0.444526  0.326204  0.309592      pass
17  0.165625  0.830898  0.615171  0.499008  0.376437  0.355814      pass
18  0.198750  0.890430  0.642490  0.546638  0.394507  0.365881      pass
19  0.132500  0.816309  0.573986  0.451759  0.342943  0.325368      pass

BARINEL SCORES

         cx 5       h 0      cx 1      cx 2      cx 4      cx 3
sum  0.529086  0.515021  0.514928  0.512719  0.508908  0.504534

TARANTULA SCORES

         cx 5       h 0      cx 1      cx 2      cx 4      cx 3
sum  0.529086  0.515021  0.514928  0.512719  0.508908  0.504534

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_swap_inGap_5_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.00it/s]
100%|██████████| 10/10 [00:01<00:00,  9.19it/s]

        cx 5    swap 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.139474  0.866920  0.665256  0.470419  0.345727  0.317349      fail
1   0.189286  0.935212  0.759802  0.538353  0.403450  0.376057      fail
2   0.191776  0.920271  0.749968  0.560476  0.406675  0.386749      fail
3   0.172826  0.847317  0.673913  0.473327  0.334303  0.317736      fail
4   0.173512  0.908464  0.722707  0.537977  0.384061  0.355358      fail
5   0.172826  0.885224  0.703985  0.496379  0.346757  0.324743      fail
6   0.173512  0.888039  0.710214  0.517589  0.364172  0.341447      fail
7   0.180682  0.924023  0.743363  0.540777  0.388086  0.363146      fail
8   0.165625  0.888743  0.701992  0.491323  0.341679  0.319242      fail
9   0.144022  0.836990  0.643506  0.465947  0.344442  0.321826      fail
10  0.174342  0.833532  0.665662  0.453386  0.326078  0.306267      pass
11  0.165625  0.815586  0.645728  0.467965  0.322915  0.300193      pass
12  0.141964  0.814118  0.623533  0.457220  0.348968  0.327927      pass
13  0.149063  0.842520  0.656267  0.469898  0.351165  0.330826      pass
14  0.149063  0.787500  0.606779  0.428764  0.311538  0.292850      pass
15  0.157738  0.872173  0.687316  0.495733  0.364164  0.342268      pass
16  0.141964  0.741295  0.563908  0.409320  0.297535  0.279701      pass
17  0.195739  0.889790  0.727819  0.534785  0.383428  0.358021      pass
18  0.124219  0.763037  0.576974  0.387133  0.292029  0.273231      pass
19  0.194853  0.863143  0.704851  0.492080  0.345105  0.321024      pass

BARINEL SCORES

         cx 2      cx 3      cx 1      h 0    swap 4     cx 5
sum  0.525611  0.522753  0.522594  0.52222  0.519812  0.51652

TARANTULA SCORES

         cx 2      cx 3      cx 1      h 0    swap 4     cx 5
sum  0.525611  0.522753  0.522594  0.52222  0.519812  0.51652

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_x_inGap_6_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.97it/s]
100%|██████████| 10/10 [00:00<00:00, 12.77it/s]

         x 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.333333  1.231250  0.946801  0.673576  0.493050  0.467112      fail
1   0.238095  1.120536  0.849814  0.588993  0.434848  0.413266      fail
2   0.325000  1.221563  0.904082  0.625958  0.443499  0.413840      fail
3   0.318182  1.213636  0.860529  0.648774  0.488976  0.460300      fail
4   0.285714  1.175893  0.913876  0.670163  0.470184  0.442474      fail
5   0.272727  1.160795  0.893910  0.655828  0.493387  0.472547      fail
6   0.300000  1.192500  0.909043  0.662426  0.484672  0.457317      fail
7   0.238095  1.120536  0.844196  0.624708  0.456973  0.432980      fail
8   0.250000  1.134375  0.838161  0.615619  0.444427  0.418358      fail
9   0.250000  1.134375  0.822887  0.617753  0.460992  0.436290      fail
10  0.200000  1.076250  0.844453  0.601293  0.434224  0.409713      pass
11  0.239130  1.121739  0.860649  0.637203  0.441617  0.415405      pass
12  0.275000  1.163438  0.857715  0.624519  0.431772  0.409254      pass
13  0.238095  1.120536  0.859766  0.629785  0.467729  0.440614      pass
14  0.275000  1.163438  0.835469  0.623953  0.461127  0.441742      pass
15  0.217391  1.096467  0.840489  0.625568  0.450029  0.421443      pass
16  0.166667  1.037500  0.772982  0.563086  0.420725  0.396488      pass
17  0.250000  1.134375  0.916479  0.681436  0.505878  0.483301      pass
18  0.277778  1.166667  0.862912  0.635284  0.480711  0.458337      pass
19  0.289474  1.180263  0.941920  0.708960  0.509121  0.482408      pass

BARINEL SCORES

          x 5      cx 4      cx 3     cx 1       h 0      cx 2
sum  0.536511  0.509684  0.505481  0.50367  0.503179  0.502073

TARANTULA SCORES

          x 5      cx 4      cx 3     cx 1       h 0      cx 2
sum  0.536511  0.509684  0.505481  0.50367  0.503179  0.502073

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_ry_inGap_3_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.75it/s]
100%|██████████| 10/10 [00:01<00:00,  9.87it/s]

        cx 5      cx 4      cx 3      cx 2       h 1      ry 0 pass/fail
0   0.210795  0.925337  0.681838  0.506892  0.481426  0.634510      fail
1   0.182188  0.835469  0.627607  0.455507  0.434137  0.563437      fail
2   0.158424  0.788400  0.588564  0.427165  0.403243  0.507486      fail
3   0.173512  0.839472  0.614133  0.437921  0.413488  0.526889      fail
4   0.165625  0.825543  0.635779  0.446879  0.423438  0.555586      fail
5   0.182188  0.885859  0.660410  0.477899  0.447595  0.586472      fail
6   0.189286  0.898307  0.685059  0.497406  0.469329  0.618898      fail
7   0.150568  0.822035  0.629124  0.463053  0.436031  0.588632      fail
8   0.180682  0.868324  0.636587  0.476436  0.450241  0.584588      fail
9   0.184028  0.869466  0.656978  0.487904  0.465997  0.622407      fail
10  0.174342  0.853475  0.631537  0.451415  0.422332  0.540940      pass
11  0.195739  0.879901  0.629922  0.450865  0.421792  0.531673      pass
12  0.198750  0.919492  0.631283  0.439761  0.413402  0.504720      pass
13  0.184028  0.881076  0.663268  0.448798  0.419387  0.554755      pass
14  0.220833  0.957313  0.723546  0.521523  0.492800  0.659632      pass
15  0.165625  0.843111  0.633302  0.458197  0.432456  0.573463      pass
16  0.165625  0.837749  0.611894  0.437751  0.408301  0.520904      pass
17  0.174342  0.859683  0.643929  0.467390  0.438016  0.587954      pass
18  0.191776  0.884087  0.641039  0.484566  0.454377  0.594449      pass
19  0.157738  0.796205  0.608194  0.431658  0.408161  0.526467      pass

BARINEL SCORES

         ry 0       h 1      cx 2      cx 3      cx 4      cx 5
sum  0.508519  0.506519  0.504593  0.499929  0.495545  0.492859

TARANTULA SCORES

         ry 0       h 1      cx 2      cx 3      cx 4      cx 5
sum  0.508519  0.506519  0.504593  0.499929  0.495545  0.492859

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_h_inGap_1_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.72it/s]
100%|██████████| 10/10 [00:00<00:00, 10.42it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       h 0 pass/fail
0   0.182188  0.896309  0.645099  0.476923  0.446835  0.467095      fail
1   0.157738  0.838579  0.624671  0.439362  0.411130  0.432000      fail
2   0.165625  0.857972  0.638818  0.482802  0.450014  0.472441      fail
3   0.201630  0.877310  0.641121  0.450413  0.421720  0.442758      fail
4   0.182188  0.857715  0.602810  0.422039  0.396650  0.415298      fail
5   0.144022  0.840489  0.621391  0.465542  0.441516  0.456162      fail
6   0.182188  0.885859  0.643873  0.457432  0.424175  0.449471      fail
7   0.182188  0.863613  0.622335  0.458544  0.433228  0.449341      fail
8   0.147222  0.793229  0.589737  0.424448  0.400976  0.416694      fail
9   0.179427  0.873372  0.650517  0.469594  0.440119  0.460738      fail
10  0.191776  0.884087  0.663502  0.475225  0.452052  0.466232      pass
11  0.156908  0.818072  0.588642  0.418538  0.392358  0.411286      pass
12  0.175368  0.956227  0.705663  0.520788  0.489526  0.509916      pass
13  0.174342  0.819058  0.581619  0.431619  0.403640  0.423515      pass
14  0.184028  0.881076  0.627303  0.451105  0.427884  0.443272      pass
15  0.165625  0.840430  0.617371  0.461951  0.438476  0.452351      pass
16  0.187228  0.852021  0.641267  0.465218  0.439219  0.456041      pass
17  0.149063  0.845391  0.587279  0.421611  0.397993  0.414182      pass
18  0.182188  0.879961  0.666281  0.483762  0.450447  0.474154      pass
19  0.165625  0.880035  0.629789  0.456947  0.431618  0.448429      pass

BARINEL SCORES

         cx 5      cx 3      cx 4       h 0      cx 2       h 1
sum  0.498881  0.498874  0.497915  0.497914  0.497829  0.496691

TARANTULA SCORES

         cx 5      cx 3      cx 4       h 0      cx 2       h 1
sum  0.498881  0.498874  0.497915  0.497914  0.497829  0.496691

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_h_inGap_8_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.26it/s]
100%|██████████| 10/10 [00:00<00:00, 11.33it/s]

         h 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.143478  1.092391  1.033475  0.682765  0.496519  0.466450      fail
1   0.180000  1.065937  1.014727  0.636538  0.454450  0.426151      fail
2   0.150000  1.024062  1.009746  0.663291  0.474885  0.445310      fail
3   0.142857  1.103274  1.022656  0.676905  0.479291  0.450611      fail
4   0.157143  1.037798  1.009468  0.670979  0.478310  0.444363      fail
5   0.163636  1.041193  1.085724  0.714908  0.533090  0.499474      fail
6   0.165000  1.052500  1.045684  0.702771  0.513515  0.484362      fail
7   0.142857  1.144345  1.115513  0.740708  0.528984  0.497235      fail
8   0.163636  1.094034  1.045916  0.665423  0.459211  0.428572      fail
9   0.142857  1.070833  1.017187  0.665698  0.469137  0.443174      fail
10  0.133333  1.008681  0.951997  0.667196  0.472952  0.445322      pass
11  0.180000  1.090000  1.113887  0.715542  0.512155  0.477329      pass
12  0.173684  1.052961  1.050966  0.661471  0.484795  0.462374      pass
13  0.166667  1.108681  1.060872  0.674797  0.493797  0.462712      pass
14  0.120000  1.093437  0.988359  0.657876  0.471248  0.448366      pass
15  0.150000  1.087187  1.044434  0.704893  0.490969  0.455873      pass
16  0.169565  1.052989  1.068988  0.690454  0.495837  0.461282      pass
17  0.105882  1.059926  1.029642  0.741525  0.526371  0.497891      pass
18  0.142857  1.020238  0.970964  0.638438  0.461523  0.444180      pass
19  0.142105  1.044737  1.011040  0.683896  0.495327  0.468975      pass

BARINEL SCORES

          h 5      cx 3      cx 4     cx 2      cx 1       h 0
sum  0.511097  0.502633  0.502519  0.49941  0.499102  0.497904

TARANTULA SCORES

          h 5      cx 3      cx 4     cx 2      cx 1       h 0
sum  0.511097  0.502633  0.502519  0.49941  0.499102  0.497904

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rx_inGap_4_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.54it/s]
100%|██████████| 10/10 [00:00<00:00, 10.32it/s]

        cx 5      cx 4      cx 3      cx 2       h 1      rx 0 pass/fail
0   0.174342  0.853475  0.639264  0.474488  0.456669  0.583446      fail
1   0.149063  0.839492  0.637631  0.457062  0.430254  0.554351      fail
2   0.189286  0.898307  0.657743  0.477261  0.451475  0.597702      fail
3   0.180682  0.858825  0.621751  0.462967  0.438471  0.563863      fail
4   0.174342  0.900308  0.666413  0.486909  0.452745  0.609646      fail
5   0.165625  0.878196  0.630639  0.469927  0.441576  0.587487      fail
6   0.187228  0.890710  0.634256  0.448534  0.419327  0.549060      fail
7   0.205060  0.930339  0.696903  0.490143  0.460953  0.620591      fail
8   0.182188  0.885859  0.651583  0.459895  0.432189  0.583087      fail
9   0.189286  0.913876  0.665588  0.491312  0.465940  0.628094      fail
10  0.182188  0.874063  0.620286  0.460362  0.433231  0.548149      pass
11  0.198750  0.886797  0.661859  0.491247  0.460739  0.612675      pass
12  0.115938  0.782676  0.573894  0.425919  0.400351  0.508876      pass
13  0.156908  0.824280  0.613818  0.444955  0.418186  0.537239      pass
14  0.147222  0.811393  0.567478  0.399162  0.376445  0.476411      pass
15  0.158424  0.821960  0.622158  0.449764  0.421447  0.533945      pass
16  0.220833  0.878906  0.623539  0.455673  0.425228  0.536962      pass
17  0.182188  0.874063  0.612533  0.438641  0.414753  0.533609      pass
18  0.174342  0.825267  0.637807  0.482493  0.455713  0.587410      pass
19  0.139474  0.753043  0.550122  0.401903  0.380530  0.440339      pass

BARINEL SCORES

         rx 0      cx 5      cx 3       h 1      cx 4      cx 2
sum  0.525092  0.517394  0.516618  0.515225  0.515043  0.514636

TARANTULA SCORES

         rx 0      cx 5      cx 3       h 1      cx 4      cx 2
sum  0.525092  0.517394  0.516618  0.515225  0.515043  0.514636

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_y_inGap_8_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.39it/s]
100%|██████████| 10/10 [00:00<00:00, 13.53it/s]

         y 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.272727  1.160795  0.864187  0.608725  0.438541  0.415296      fail
1   0.375000  1.163438  0.841367  0.606718  0.437315  0.411233      fail
2   0.300000  1.134375  0.856777  0.632266  0.445356  0.421923      fail
3   0.291667  1.134375  0.858968  0.637547  0.481247  0.459532      fail
4   0.285714  1.092857  0.795312  0.597013  0.446639  0.423257      fail
5   0.291667  1.110156  0.853271  0.617918  0.446787  0.425329      fail
6   0.250000  1.107955  0.836896  0.611889  0.460200  0.432989      fail
7   0.295455  1.187216  0.889400  0.650101  0.477763  0.444771      fail
8   0.309524  1.092857  0.880060  0.644694  0.471456  0.446703      fail
9   0.315789  1.119079  0.852488  0.665647  0.475397  0.450665      fail
10  0.210526  1.119079  0.858697  0.655187  0.481086  0.451172      pass
11  0.263158  1.119079  0.841488  0.619818  0.434419  0.402559      pass
12  0.260870  1.096467  0.840489  0.607011  0.429944  0.402353      pass
13  0.261905  1.065179  0.826842  0.609880  0.443656  0.419140      pass
14  0.166667  1.166667  0.923958  0.661616  0.481725  0.452624      pass
15  0.305556  1.134375  0.794271  0.595081  0.412275  0.390689      pass
16  0.250000  1.134375  0.776107  0.602652  0.431188  0.405739      pass
17  0.289474  1.119079  0.818072  0.606050  0.445011  0.415751      pass
18  0.263158  1.210855  0.838240  0.606557  0.427452  0.402444      pass
19  0.266667  1.076250  0.789062  0.605679  0.418178  0.383384      pass

BARINEL SCORES

          y 5       h 0     cx 1      cx 3      cx 2      cx 4
sum  0.540681  0.512169  0.50978  0.506578  0.504139  0.501368

TARANTULA SCORES

          y 5       h 0     cx 1      cx 3      cx 2      cx 4
sum  0.540681  0.512169  0.50978  0.506578  0.504139  0.501368

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rxx_inGap_3_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.29it/s]
100%|██████████| 10/10 [00:00<00:00, 11.01it/s]

        cx 5      cx 4      cx 3     rxx 2      cx 1       h 0 pass/fail
0   0.205060  0.887965  0.659399  0.814080  0.476473  0.451962      fail
1   0.158424  0.855520  0.656046  0.791194  0.474507  0.446336      fail
2   0.156908  0.818072  0.650932  0.781804  0.480048  0.458072      fail
3   0.191776  0.884087  0.666995  0.776434  0.479595  0.448033      fail
4   0.195739  0.894762  0.679227  0.829723  0.492541  0.463257      fail
5   0.180682  0.858825  0.604696  0.722000  0.446897  0.424711      fail
6   0.165625  0.817525  0.611379  0.756249  0.444651  0.422727      fail
7   0.195739  0.824592  0.609012  0.733441  0.433728  0.407149      fail
8   0.182188  0.841367  0.630964  0.776368  0.439741  0.416406      fail
9   0.135511  0.821183  0.609115  0.739120  0.433285  0.409581      fail
10  0.158424  0.821960  0.633653  0.761254  0.459751  0.430079      pass
11  0.149063  0.823145  0.602175  0.680837  0.455318  0.431959      pass
12  0.165625  0.834531  0.620649  0.760688  0.449551  0.419818      pass
13  0.191776  0.901295  0.664057  0.771107  0.504975  0.475635      pass
14  0.191776  0.907504  0.641635  0.758109  0.479763  0.448948      pass
15  0.165625  0.771753  0.578494  0.658076  0.441996  0.420020      pass
16  0.191776  0.877878  0.646442  0.760815  0.489647  0.467991      pass
17  0.157738  0.817392  0.633240  0.738482  0.454934  0.432780      pass
18  0.195739  0.889400  0.665470  0.793360  0.482099  0.456602      pass
19  0.110417  0.741202  0.552061  0.650624  0.403950  0.386862      pass

BARINEL SCORES

         cx 5     rxx 2      cx 3      cx 4      cx 1       h 0
sum  0.513015  0.512856  0.505544  0.503488  0.498888  0.498712

TARANTULA SCORES

         cx 5     rxx 2      cx 3      cx 4      cx 1       h 0
sum  0.513015  0.512856  0.505544  0.503488  0.498888  0.498712

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_h_inGap_5_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.87it/s]
100%|██████████| 10/10 [00:01<00:00,  9.88it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       h 0 pass/fail
0   0.198750  0.858652  0.623745  0.447976  0.422517  0.359860      fail
1   0.194853  0.833410  0.601155  0.438308  0.414372  0.362021      fail
2   0.209211  0.885074  0.655348  0.487383  0.466740  0.390570      fail
3   0.191776  0.866879  0.619196  0.439376  0.415699  0.352168      fail
4   0.173512  0.876228  0.632690  0.451425  0.424651  0.364088      fail
5   0.205060  0.899200  0.669274  0.492977  0.466293  0.391955      fail
6   0.157738  0.875335  0.631662  0.455250  0.435005  0.378308      fail
7   0.172826  0.836990  0.614608  0.447900  0.426629  0.372390      fail
8   0.215312  0.881836  0.684978  0.490089  0.463144  0.385266      fail
9   0.165625  0.817525  0.614395  0.452711  0.429927  0.373495      fail
10  0.191776  0.837253  0.632119  0.454891  0.428218  0.362876      pass
11  0.156908  0.811863  0.624625  0.432075  0.408671  0.365511      pass
12  0.182188  0.879961  0.618839  0.450525  0.422563  0.361187      pass
13  0.165625  0.846328  0.629554  0.457348  0.431496  0.370383      pass
14  0.165625  0.856777  0.639238  0.467116  0.438653  0.374306      pass
15  0.182188  0.847266  0.667806  0.491015  0.462304  0.393318      pass
16  0.173512  0.876228  0.619750  0.459461  0.434939  0.370895      pass
17  0.195739  0.929847  0.688581  0.491858  0.461961  0.390586      pass
18  0.180682  0.893910  0.649154  0.485399  0.463149  0.398165      pass
19  0.173512  0.897414  0.656714  0.472263  0.448142  0.386023      pass

BARINEL SCORES

         cx 5      cx 4       h 1       h 0      cx 3     cx 2
sum  0.516004  0.498679  0.497997  0.497126  0.496895  0.49684

TARANTULA SCORES

         cx 5      cx 4       h 1       h 0      cx 3     cx 2
sum  0.516004  0.498679  0.497997  0.497126  0.496895  0.49684

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_y_inGap_3_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.85it/s]
100%|██████████| 10/10 [00:00<00:00, 10.08it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       y 0 pass/fail
0   0.191776  0.860670  0.645066  0.451601  0.423027  0.582678      fail
1   0.126190  0.763281  0.580945  0.414630  0.395659  0.533186      fail
2   0.150568  0.836896  0.648027  0.477135  0.450841  0.619887      fail
3   0.165625  0.848473  0.633337  0.456370  0.428352  0.586062      fail
4   0.182188  0.857715  0.656150  0.493316  0.472084  0.652244      fail
5   0.158424  0.879993  0.648256  0.466310  0.440163  0.598208      fail
6   0.156908  0.841488  0.624053  0.448362  0.427881  0.575577      fail
7   0.139474  0.817085  0.635492  0.478403  0.455696  0.631762      fail
8   0.184028  0.905794  0.691669  0.496035  0.470799  0.654105      fail
9   0.180682  0.873686  0.671056  0.485253  0.460507  0.640328      fail
10  0.165625  0.886589  0.602025  0.436080  0.402319  0.500099      pass
11  0.198750  0.842305  0.632045  0.458470  0.424208  0.580599      pass
12  0.191776  0.884087  0.640651  0.483816  0.463944  0.614734      pass
13  0.182188  0.847266  0.630635  0.469360  0.443913  0.607637      pass
14  0.165625  0.834531  0.613677  0.448472  0.422260  0.580201      pass
15  0.165625  0.802663  0.594822  0.434784  0.410971  0.544805      pass
16  0.139474  0.799877  0.561382  0.414945  0.391813  0.506225      pass
17  0.195739  0.874538  0.645964  0.473083  0.446122  0.592624      pass
18  0.157738  0.786254  0.611561  0.445984  0.420242  0.584833      pass
19  0.165625  0.835514  0.614343  0.451959  0.424499  0.570331      pass

BARINEL SCORES

         y 0      cx 3      h 1      cx 2      cx 4      cx 5
sum  0.51667  0.511404  0.51007  0.508191  0.502709  0.486281

TARANTULA SCORES

         y 0      cx 3      h 1      cx 2      cx 4      cx 5
sum  0.51667  0.511404  0.51007  0.508191  0.502709  0.486281

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_x_inGap_10_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.60it/s]
100%|██████████| 10/10 [00:00<00:00, 13.15it/s]

         x 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.272727  1.160795  0.823739  0.645480  0.485427  0.458613      fail
1   0.261905  1.092857  0.806548  0.615254  0.439627  0.414184      fail
2   0.260870  1.147011  0.836990  0.623556  0.458988  0.433206      fail
3   0.250000  1.158594  0.873372  0.647164  0.481740  0.458003      fail
4   0.315789  1.180263  0.884087  0.676286  0.487096  0.453837      fail
5   0.275000  1.076250  0.816309  0.584150  0.405854  0.379604      fail
6   0.315789  1.149671  0.870683  0.627035  0.454263  0.422054      fail
7   0.250000  1.107955  0.807173  0.616292  0.459637  0.438883      fail
8   0.326087  1.121739  0.855520  0.633670  0.445556  0.415232      fail
9   0.239130  1.172283  0.890710  0.633936  0.470915  0.448384      fail
10  0.277778  1.102083  0.885547  0.660501  0.451791  0.418614      pass
11  0.315789  1.119079  0.858697  0.637780  0.481580  0.448771      pass
12  0.157895  1.180263  0.884087  0.666995  0.470799  0.446284      pass
13  0.214286  1.120536  0.854148  0.633931  0.458269  0.434737      pass
14  0.285714  1.148214  0.860658  0.638508  0.463333  0.436978      pass
15  0.111111  1.102083  0.860829  0.600195  0.447067  0.433564      pass
16  0.323529  1.219853  0.939200  0.677744  0.483332  0.451684      pass
17  0.250000  1.166667  0.881076  0.669798  0.477934  0.453492      pass
18  0.236842  1.210855  0.902282  0.652411  0.485988  0.462626      pass
19  0.263158  1.210855  0.966324  0.710305  0.524027  0.494015      pass

BARINEL SCORES

          x 5      cx 4      cx 1       h 0      cx 2     cx 3
sum  0.531825  0.495358  0.491696  0.490982  0.490454  0.48768

TARANTULA SCORES

          x 5      cx 4      cx 1       h 0      cx 2     cx 3
sum  0.531825  0.495358  0.491696  0.490982  0.490454  0.48768

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rxx_inGap_7_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.85it/s]
100%|██████████| 10/10 [00:01<00:00,  9.47it/s]

       rxx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.057143  1.119048  1.124554  0.824175  0.572083  0.535291      fail
1   0.052174  1.142120  1.104806  0.795997  0.573354  0.533123      fail
2   0.052381  1.159226  1.115011  0.737922  0.532259  0.503012      fail
3   0.052381  1.135417  1.073493  0.758489  0.549506  0.519057      fail
4   0.061905  1.146429  1.128497  0.746021  0.536008  0.497542      fail
5   0.055000  1.120937  1.060254  0.702040  0.495190  0.462492      fail
6   0.047619  1.127976  1.099368  0.745030  0.526728  0.495256      fail
7   0.061905  1.150298  1.149721  0.839671  0.590609  0.546071      fail
8   0.050000  1.152273  1.110281  0.818477  0.593475  0.559594      fail
9   0.055000  1.095938  1.087500  0.793206  0.567755  0.532002      fail
10  0.061111  1.054861  1.096984  0.711952  0.507602  0.468494      pass
11  0.041176  1.206250  1.067808  0.795209  0.539864  0.511707      pass
12  0.052381  1.163095  1.117188  0.782732  0.564148  0.520589      pass
13  0.060000  1.132812  1.128457  0.849896  0.610275  0.573385      pass
14  0.045000  1.084375  0.999746  0.730328  0.510046  0.481001      pass
15  0.054545  1.151989  1.120241  0.784165  0.574144  0.537203      pass
16  0.050000  1.162153  1.100000  0.704222  0.524999  0.494022      pass
17  0.057895  1.161842  1.157545  0.779708  0.556512  0.514871      pass
18  0.055556  1.082986  1.091927  0.778943  0.576515  0.535263      pass
19  0.055000  1.175000  1.141133  0.753136  0.524601  0.485476      pass

BARINEL SCORES

        rxx 5      h 0     cx 2      cx 1      cx 3      cx 4
sum  0.505956  0.50298  0.50294  0.502189  0.500735  0.499434

TARANTULA SCORES

        rxx 5      h 0     cx 2      cx 1      cx 3      cx 4
sum  0.505956  0.50298  0.50294  0.502189  0.500735  0.499434

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rx_inGap_5_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.56it/s]
100%|██████████| 10/10 [00:00<00:00, 10.47it/s]

        cx 5      cx 4      cx 3      cx 2       h 1      rx 0 pass/fail
0   0.202431  0.888672  0.651017  0.452454  0.421495  0.520127      fail
1   0.189286  0.898307  0.650008  0.466686  0.437586  0.541792      fail
2   0.157738  0.823010  0.617528  0.444042  0.418525  0.493248      fail
3   0.187228  0.876495  0.644038  0.454584  0.425733  0.520092      fail
4   0.157738  0.854148  0.627290  0.465731  0.443919  0.522006      fail
5   0.150568  0.822035  0.575328  0.408066  0.388244  0.455156      fail
6   0.180682  0.823739  0.616390  0.437515  0.406789  0.492230      fail
7   0.209211  0.844449  0.623617  0.458859  0.437377  0.540026      fail
8   0.149063  0.839492  0.628435  0.453671  0.430987  0.513403      fail
9   0.210795  0.945561  0.709778  0.519332  0.490335  0.607918      fail
10  0.165625  0.828249  0.628830  0.444890  0.416903  0.506395      pass
11  0.174342  0.842475  0.611663  0.456470  0.427744  0.517966      pass
12  0.147222  0.829557  0.605269  0.413919  0.387290  0.448859      pass
13  0.151823  0.858187  0.637542  0.453904  0.426139  0.511122      pass
14  0.173512  0.881845  0.639719  0.474900  0.443622  0.540343      pass
15  0.141964  0.822117  0.576915  0.418604  0.396305  0.457015      pass
16  0.186328  0.834229  0.594238  0.418362  0.389440  0.461080      pass
17  0.174342  0.801850  0.581064  0.435108  0.413722  0.495588      pass
18  0.122039  0.769264  0.572003  0.438439  0.416517  0.479427      pass
19  0.191776  0.907504  0.671826  0.480349  0.452668  0.560015      pass

BARINEL SCORES

         cx 5      rx 0      cx 3       h 1      cx 4      cx 2
sum  0.524208  0.511203  0.509001  0.507711  0.507081  0.507003

TARANTULA SCORES

         cx 5      rx 0      cx 3       h 1      cx 4      cx 2
sum  0.524208  0.511203  0.509001  0.507711  0.507081  0.507003

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_y_inGap_6_.qasm

100%|██████████| 10/10 [00:00<00:00, 12.20it/s]
100%|██████████| 10/10 [00:00<00:00, 12.97it/s]

         y 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.309524  1.203571  0.914769  0.662785  0.470259  0.439050      fail
1   0.275000  1.163438  0.835469  0.601875  0.439203  0.414669      fail
2   0.300000  1.192500  0.935840  0.710177  0.505972  0.473914      fail
3   0.250000  1.134375  0.850879  0.647689  0.461233  0.438277      fail
4   0.333333  1.231250  0.907878  0.658550  0.452012  0.419584      fail
5   0.315789  1.210855  0.919490  0.692094  0.486336  0.457395      fail
6   0.300000  1.192500  0.858652  0.645085  0.464287  0.438199      fail
7   0.295455  1.187216  0.885263  0.647672  0.459788  0.432197      fail
8   0.236842  1.119079  0.818072  0.606050  0.444817  0.420372      fail
9   0.289474  1.180263  0.837253  0.646033  0.461267  0.436301      fail
10  0.225000  1.105313  0.861738  0.645538  0.471514  0.441007      pass
11  0.200000  1.076250  0.799961  0.592039  0.445680  0.427430      pass
12  0.264706  1.151471  0.786903  0.603330  0.442762  0.420259      pass
13  0.264706  1.151471  0.884651  0.665233  0.477223  0.443832      pass
14  0.250000  1.134375  0.794271  0.599961  0.443231  0.417692      pass
15  0.250000  1.134375  0.846328  0.613018  0.457108  0.432152      pass
16  0.326087  1.222826  0.863910  0.638103  0.464688  0.437577      pass
17  0.272727  1.160795  0.829102  0.634140  0.450053  0.427374      pass
18  0.210526  1.088487  0.793668  0.571021  0.414425  0.393234      pass
19  0.272727  1.160795  0.833239  0.624552  0.445075  0.417680      pass

BARINEL SCORES

          y 5      cx 3      cx 2      cx 4      cx 1       h 0
sum  0.533898  0.513771  0.513029  0.509243  0.507285  0.506474

TARANTULA SCORES

          y 5      cx 3      cx 2      cx 4      cx 1       h 0
sum  0.533898  0.513771  0.513029  0.509243  0.507285  0.506474

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_ry_inGap_6_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.60it/s]
100%|██████████| 10/10 [00:00<00:00, 11.97it/s]

        ry 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.236842  1.119079  0.888322  0.641522  0.452868  0.432475      fail
1   0.250000  1.134375  0.850879  0.609443  0.437820  0.410308      fail
2   0.320000  1.215750  0.890547  0.666315  0.476596  0.447469      fail
3   0.261905  1.148214  0.876228  0.644608  0.460875  0.434233      fail
4   0.300000  1.192500  0.919492  0.696062  0.493278  0.462262      fail
5   0.261905  1.148214  0.823903  0.567406  0.433306  0.411334      fail
6   0.261905  1.148214  0.891797  0.659837  0.488308  0.466942      fail
7   0.275000  1.163438  0.879961  0.678057  0.494695  0.466154      fail
8   0.261905  1.148214  0.855041  0.619913  0.457145  0.434982      fail
9   0.300000  1.192500  0.842305  0.632045  0.472693  0.453779      fail
10  0.250000  1.134375  0.843111  0.626628  0.458418  0.429422      pass
11  0.289474  1.180263  0.877878  0.676633  0.518785  0.495051      pass
12  0.289474  1.180263  0.877878  0.659614  0.509008  0.485677      pass
13  0.282609  1.172283  0.842935  0.646906  0.470581  0.444856      pass
14  0.214286  1.092857  0.795313  0.564772  0.397690  0.370720      pass
15  0.309524  1.203571  0.878013  0.668735  0.475137  0.445980      pass
16  0.210526  1.088487  0.840502  0.631465  0.459922  0.429501      pass
17  0.200000  1.076250  0.805859  0.587686  0.427728  0.406960      pass
18  0.250000  1.134375  0.840430  0.659151  0.499547  0.477272      pass
19  0.263158  1.149671  0.865892  0.621551  0.445636  0.424721      pass

BARINEL SCORES

         ry 5      cx 3      cx 4      cx 2       h 0      cx 1
sum  0.516111  0.507293  0.504302  0.502824  0.500554  0.500275

TARANTULA SCORES

         ry 5      cx 3      cx 4      cx 2       h 0      cx 1
sum  0.516111  0.507293  0.504302  0.502824  0.500554  0.500275

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rxx_inGap_8_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.55it/s]
100%|██████████| 10/10 [00:00<00:00, 12.56it/s]

       rxx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.289474  1.180263  0.860670  0.597079  0.436766  0.417705      fail
1   0.238095  1.175893  0.892690  0.666814  0.495242  0.465829      fail
2   0.269231  1.134375  0.825586  0.615214  0.449214  0.424899      fail
3   0.250000  1.134375  0.824082  0.604698  0.463083  0.439552      fail
4   0.261905  1.120536  0.823010  0.628352  0.456298  0.428013      fail
5   0.291667  1.182813  0.841992  0.626604  0.439845  0.414944      fail
6   0.272727  1.134375  0.837749  0.622935  0.437643  0.412675      fail
7   0.238095  1.148214  0.876228  0.649183  0.483123  0.460329      fail
8   0.289474  1.149671  0.865892  0.628891  0.447234  0.423915      fail
9   0.295455  1.081534  0.876491  0.636699  0.465545  0.438467      fail
10  0.275000  1.134375  0.856777  0.642556  0.483020  0.462525      pass
11  0.277778  1.102083  0.799783  0.574273  0.425689  0.401259      pass
12  0.236842  1.180263  0.890296  0.684055  0.486751  0.457000      pass
13  0.214286  1.148214  0.876228  0.640776  0.473435  0.445631      pass
14  0.294118  1.083088  0.791636  0.610785  0.420145  0.393626      pass
15  0.194444  1.231250  0.907878  0.694889  0.495558  0.462148      pass
16  0.204545  1.160795  0.873686  0.640280  0.479455  0.449812      pass
17  0.227273  1.160795  0.858825  0.617384  0.463887  0.442488      pass
18  0.272727  1.134375  0.808026  0.602576  0.437913  0.411953      pass
19  0.275000  1.163438  0.857715  0.627100  0.461357  0.440850      pass

BARINEL SCORES

        rxx 5      cx 3      cx 4      cx 2       h 0      cx 1
sum  0.521682  0.500104  0.498766  0.497692  0.497644  0.497108

TARANTULA SCORES

        rxx 5      cx 3      cx 4      cx 2       h 0      cx 1
sum  0.521682  0.500104  0.498766  0.497692  0.497644  0.497108

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rx_inGap_6_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.58it/s]
100%|██████████| 10/10 [00:00<00:00, 12.29it/s]

        rx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.275000  1.163438  0.835469  0.639415  0.454029  0.430249      fail
1   0.342105  1.241447  0.909478  0.674489  0.474801  0.444682      fail
2   0.300000  1.192500  0.858652  0.625599  0.437153  0.409853      fail
3   0.285714  1.175893  0.892690  0.669974  0.475962  0.451602      fail
4   0.325000  1.221563  0.942676  0.686638  0.490317  0.463488      fail
5   0.318182  1.213636  0.930700  0.669828  0.483665  0.454491      fail
6   0.275000  1.163438  0.863613  0.669408  0.493537  0.466034      fail
7   0.250000  1.134375  0.818184  0.600267  0.449465  0.430527      fail
8   0.280000  1.169250  0.858172  0.630166  0.450588  0.421932      fail
9   0.333333  1.231250  0.907878  0.671178  0.479466  0.451097      fail
10  0.225000  1.105313  0.855840  0.641107  0.473017  0.440856      pass
11  0.289474  1.180263  0.860670  0.635819  0.483591  0.457771      pass
12  0.300000  1.192500  0.858652  0.658304  0.487708  0.461965      pass
13  0.181818  1.055114  0.765021  0.597929  0.425644  0.395195      pass
14  0.236842  1.119079  0.835280  0.606993  0.451581  0.424782      pass
15  0.217391  1.096467  0.801800  0.613344  0.453546  0.430540      pass
16  0.342105  1.241447  0.886061  0.646806  0.473882  0.448937      pass
17  0.280000  1.169250  0.875969  0.636492  0.464179  0.435150      pass
18  0.263158  1.149671  0.836266  0.648001  0.459876  0.431411      pass
19  0.263158  1.149671  0.900308  0.648617  0.476789  0.449337      pass

BARINEL SCORES

         rx 5      cx 3      cx 4      cx 2       h 0      cx 1
sum  0.534513  0.509878  0.509587  0.507908  0.502728  0.502097

TARANTULA SCORES

         rx 5      cx 3      cx 4      cx 2       h 0      cx 1
sum  0.534513  0.509878  0.509587  0.507908  0.502728  0.502097

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_h_inGap_4_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.62it/s]
100%|██████████| 10/10 [00:00<00:00, 10.54it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       h 0 pass/fail
0   0.149063  0.827695  0.595652  0.430564  0.406027  0.371896      fail
1   0.179427  0.891911  0.643326  0.451081  0.423616  0.403362      fail
2   0.165625  0.895371  0.677504  0.476441  0.451787  0.422228      fail
3   0.158424  0.855520  0.641666  0.469640  0.445859  0.418562      fail
4   0.187228  0.876495  0.661303  0.481990  0.458606  0.437092      fail
5   0.104605  0.797903  0.588523  0.451070  0.429101  0.401504      fail
6   0.122039  0.862932  0.635159  0.463198  0.442456  0.410775      fail
7   0.173512  0.881845  0.651286  0.465636  0.436722  0.415123      fail
8   0.189286  0.898307  0.654934  0.489111  0.459028  0.438400      fail
9   0.182188  0.879961  0.656716  0.465432  0.439279  0.414778      fail
10  0.154583  0.841771  0.625754  0.439896  0.411014  0.382086      pass
11  0.150568  0.822035  0.601738  0.429080  0.402747  0.381068      pass
12  0.174342  0.859683  0.638917  0.462146  0.435887  0.413535      pass
13  0.174342  0.842475  0.608171  0.432859  0.407099  0.392200      pass
14  0.141964  0.758557  0.578456  0.400550  0.374691  0.348512      pass
15  0.215312  0.904082  0.681152  0.510045  0.487886  0.470757      pass
16  0.215312  0.898184  0.656824  0.458486  0.428470  0.409422      pass
17  0.136397  0.784697  0.562708  0.437718  0.420909  0.389701      pass
18  0.165625  0.840430  0.617371  0.440689  0.419165  0.399887      pass
19  0.173512  0.860658  0.626590  0.482619  0.456267  0.433334      pass

BARINEL SCORES

          h 1      cx 3      cx 2      cx 4       h 0      cx 5
sum  0.508588  0.508267  0.508211  0.507475  0.506942  0.486334

TARANTULA SCORES

          h 1      cx 3      cx 2      cx 4       h 0      cx 5
sum  0.508588  0.508267  0.508211  0.507475  0.506942  0.486334

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_x_inGap_8_.qasm

100%|██████████| 10/10 [00:00<00:00, 12.04it/s]
100%|██████████| 10/10 [00:00<00:00, 12.85it/s]

         x 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.275000  1.163438  0.874062  0.637191  0.460605  0.436080      fail
1   0.300000  1.163438  0.841367  0.601914  0.436668  0.411124      fail
2   0.261905  1.175893  0.892690  0.658057  0.480446  0.460445      fail
3   0.289474  1.210855  0.902282  0.655515  0.480564  0.452460      fail
4   0.282609  1.147011  0.836990  0.592232  0.433622  0.411771      fail
5   0.264706  1.083088  0.817808  0.594548  0.432347  0.407385      fail
6   0.325000  1.163438  0.819121  0.584811  0.435884  0.415511      fail
7   0.315789  1.210855  0.925699  0.670026  0.498154  0.467475      fail
8   0.261905  1.231250  0.884524  0.642134  0.464345  0.435849      fail
9   0.272727  1.160795  0.858825  0.624767  0.445568  0.421287      fail
10  0.222222  1.134375  0.837153  0.639201  0.464263  0.440505      pass
11  0.166667  1.148214  0.855041  0.651411  0.466025  0.439840      pass
12  0.210526  1.180263  0.877878  0.623978  0.466815  0.445994      pass
13  0.210526  1.180263  0.884087  0.631359  0.468655  0.442447      pass
14  0.200000  1.163438  0.902207  0.664624  0.470398  0.442985      pass
15  0.166667  1.198958  0.895226  0.659218  0.490559  0.459368      pass
16  0.261905  1.148214  0.860658  0.619599  0.454486  0.431179      pass
17  0.225000  1.134375  0.818184  0.607609  0.414461  0.387033      pass
18  0.214286  1.120536  0.823010  0.637109  0.439475  0.409524      pass
19  0.200000  1.192500  0.864551  0.674175  0.481907  0.456041      pass

BARINEL SCORES

          x 5      cx 4      cx 3       h 0      cx 1      cx 2
sum  0.578276  0.502336  0.501024  0.497952  0.497341  0.494195

TARANTULA SCORES

          x 5      cx 4      cx 3       h 0      cx 1      cx 2
sum  0.578276  0.502336  0.501024  0.497952  0.497341  0.494195

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rxx_inGap_9_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.97it/s]
100%|██████████| 10/10 [00:00<00:00, 10.50it/s]

       rxx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.313043  0.977446  0.706216  0.653762  0.618861  0.644514      fail
1   0.286957  1.037772  0.724524  0.635767  0.590723  0.624763      fail
2   0.300000  1.020000  0.738594  0.670621  0.634958  0.696224      fail
3   0.285714  1.011607  0.761514  0.665210  0.631074  0.662449      fail
4   0.285714  0.929464  0.693601  0.611248  0.575519  0.591418      fail
5   0.330000  1.047813  0.745352  0.688770  0.647422  0.658784      fail
6   0.371429  0.951786  0.703739  0.647747  0.648829  0.697215      fail
7   0.275000  1.005469  0.741699  0.655317  0.612337  0.641272      fail
8   0.347368  0.966776  0.681600  0.643375  0.629887  0.650101      fail
9   0.330000  0.950625  0.729063  0.688265  0.675938  0.726934      fail
10  0.360000  0.872188  0.640488  0.587374  0.605147  0.674028      pass
11  0.314286  1.010417  0.766034  0.687839  0.674308  0.734370      pass
12  0.315789  1.039803  0.796032  0.701371  0.655727  0.691780      pass
13  0.272727  1.056818  0.758452  0.653544  0.610172  0.658545      pass
14  0.333333  0.975000  0.707183  0.677703  0.682755  0.756462      pass
15  0.330000  0.960625  0.670977  0.598337  0.571022  0.632702      pass
16  0.333333  0.996181  0.751910  0.676119  0.672355  0.762665      pass
17  0.300000  0.977431  0.751780  0.693711  0.653924  0.730749      pass
18  0.314286  1.000893  0.709784  0.650761  0.624792  0.670535      pass
19  0.378947  0.954934  0.715563  0.651997  0.654413  0.730328      pass

BARINEL SCORES

         cx 4      cx 2      cx 3      cx 1     rxx 5       h 0
sum  0.501379  0.499289  0.498541  0.494512  0.490006  0.483555

TARANTULA SCORES

         cx 4      cx 2      cx 3      cx 1     rxx 5       h 0
sum  0.501379  0.499289  0.498541  0.494512  0.490006  0.483555

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_cx_inGap_2_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.86it/s]
100%|██████████| 10/10 [00:01<00:00,  9.66it/s]

        cx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.172826  0.861464  0.634644  0.463928  0.457614  0.412154      fail
1   0.157738  0.801823  0.607880  0.450746  0.455639  0.402894      fail
2   0.201630  0.872181  0.653580  0.483171  0.490348  0.437624      fail
3   0.215312  0.926328  0.642693  0.464848  0.457154  0.411678      fail
4   0.198750  0.858922  0.637198  0.462589  0.456900  0.406896      fail
5   0.165625  0.862676  0.633400  0.473401  0.486907  0.443220      fail
6   0.165625  0.840430  0.616296  0.454794  0.457211  0.415170      fail
7   0.157738  0.786254  0.572327  0.418749  0.413090  0.374467      fail
8   0.157738  0.896522  0.662326  0.486455  0.489148  0.443211      fail
9   0.182188  0.819121  0.604666  0.438158  0.429324  0.392176      fail
10  0.175368  0.820014  0.616979  0.450925  0.452476  0.414253      pass
11  0.189286  0.877121  0.655437  0.467048  0.451534  0.398888      pass
12  0.180682  0.853462  0.637084  0.449778  0.429721  0.376636      pass
13  0.191776  0.901295  0.641594  0.470188  0.471778  0.419661      pass
14  0.156908  0.818072  0.623457  0.450709  0.440113  0.412507      pass
15  0.180682  0.873686  0.655313  0.481563  0.486455  0.434626      pass
16  0.182188  0.896309  0.625244  0.456833  0.455250  0.415872      pass
17  0.173512  0.860658  0.616439  0.461810  0.475412  0.426952      pass
18  0.189286  0.855934  0.629348  0.462310  0.462187  0.424661      pass
19  0.174342  0.825267  0.620788  0.451990  0.446284  0.395842      pass

BARINEL SCORES

         cx 1       h 0      cx 2     cx 4      cx 3      cx 5
sum  0.501207  0.501186  0.499657  0.49836  0.497749  0.497358

TARANTULA SCORES

         cx 1       h 0      cx 2     cx 4      cx 3      cx 5
sum  0.501207  0.501186  0.499657  0.49836  0.497749  0.497358

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_sx_inGap_7_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.44it/s]
100%|██████████| 10/10 [00:00<00:00, 10.88it/s]

      sxdg 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.463158  1.179605  0.848643  0.610530  0.441231  0.411266      fail
1   0.545455  1.174432  0.853675  0.627768  0.448426  0.415076      fail
2   0.419048  1.175298  0.868824  0.630315  0.465024  0.434476      fail
3   0.444444  1.145486  0.855642  0.611160  0.427755  0.401116      fail
4   0.400000  1.160227  0.868235  0.650175  0.456467  0.424022      fail
5   0.342857  1.195536  0.886868  0.651960  0.475779  0.448323      fail
6   0.440000  1.162813  0.849004  0.610201  0.432999  0.403375      fail
7   0.463158  1.149013  0.867229  0.635596  0.453862  0.428132      fail
8   0.417391  1.137228  0.842884  0.621371  0.432750  0.403554      fail
9   0.436364  1.229830  0.967436  0.692180  0.476400  0.441455      fail
10  0.400000  1.202500  0.936133  0.658300  0.460080  0.426203      pass
11  0.378947  1.201974  0.908717  0.655375  0.483722  0.452841      pass
12  0.378947  1.201974  0.928783  0.655704  0.462215  0.425953      pass
13  0.444444  1.210069  0.901128  0.659029  0.478092  0.447618      pass
14  0.436364  1.203409  0.896839  0.652862  0.455163  0.420086      pass
15  0.360000  1.242188  0.966074  0.676584  0.474257  0.442483      pass
16  0.421053  1.190789  0.918812  0.643325  0.476933  0.443610      pass
17  0.421053  1.190789  0.898746  0.668131  0.481038  0.446086      pass
18  0.480000  1.181250  0.879063  0.599445  0.415378  0.380409      pass
19  0.440000  1.191875  0.869473  0.647740  0.456425  0.415503      pass

BARINEL SCORES

       sxdg 5       h 0      cx 4      cx 2      cx 1      cx 3
sum  0.512368  0.494713  0.493523  0.493186  0.492757  0.488903

TARANTULA SCORES

       sxdg 5       h 0      cx 4      cx 2      cx 1      cx 3
sum  0.512368  0.494713  0.493523  0.493186  0.492757  0.488903

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_ry_inGap_7_.qasm

100%|██████████| 10/10 [00:00<00:00, 12.19it/s]
100%|██████████| 10/10 [00:00<00:00, 11.98it/s]

        ry 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.457143  1.308036  0.842615  0.616343  0.439273  0.404516      fail
1   0.436364  1.286932  0.825888  0.600463  0.440348  0.409840      fail
2   0.472727  1.352841  0.887784  0.646817  0.464782  0.430938      fail
3   0.463158  1.315461  0.872841  0.628268  0.462059  0.434699      fail
4   0.486957  1.299728  0.827123  0.626222  0.436020  0.400944      fail
5   0.517647  1.366176  0.895611  0.670264  0.482260  0.448779      fail
6   0.457143  1.359524  0.898419  0.680301  0.474977  0.439941      fail
7   0.440000  1.341875  0.891055  0.664838  0.465581  0.438102      fail
8   0.400000  1.296181  0.851128  0.625707  0.433749  0.396455      fail
9   0.440000  1.391875  0.929180  0.679404  0.466662  0.426821      fail
10  0.440000  1.341875  0.891055  0.645015  0.450817  0.425828      pass
11  0.378947  1.333553  0.914535  0.659903  0.461549  0.430990      pass
12  0.463158  1.337500  0.871361  0.633551  0.443721  0.410859      pass
13  0.472727  1.273580  0.779972  0.561919  0.406900  0.380085      pass
14  0.417391  1.368750  0.948115  0.669883  0.477964  0.447291      pass
15  0.488889  1.332639  0.849479  0.582284  0.425491  0.395145      pass
16  0.436364  1.362500  0.915092  0.661518  0.471444  0.437900      pass
17  0.400000  1.345739  0.906463  0.646147  0.440737  0.407141      pass
18  0.311111  1.292014  0.896701  0.672088  0.474749  0.438212      pass
19  0.378947  1.302961  0.872924  0.627516  0.466459  0.439609      pass

BARINEL SCORES

         ry 5      cx 2      cx 1       h 0      cx 4      cx 3
sum  0.521898  0.503079  0.502525  0.501064  0.500517  0.496469

TARANTULA SCORES

         ry 5      cx 2      cx 1       h 0      cx 4      cx 3
sum  0.521898  0.503079  0.502525  0.501064  0.500517  0.496469

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rx_inGap_8_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.75it/s]
100%|██████████| 10/10 [00:00<00:00, 11.16it/s]

        rx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.177273  1.062500  0.969922  0.713345  0.524603  0.496177      fail
1   0.185714  1.077679  0.929371  0.651184  0.470966  0.441256      fail
2   0.156522  1.083152  0.968614  0.742473  0.536609  0.507231      fail
3   0.177273  1.062500  0.955060  0.693130  0.497952  0.465996      fail
4   0.142857  1.043155  0.901711  0.659153  0.489186  0.459666      fail
5   0.177273  1.040625  0.942933  0.723075  0.495999  0.460153      fail
6   0.165000  1.047500  0.939336  0.702682  0.516850  0.484925      fail
7   0.137500  1.077865  0.957926  0.724008  0.514466  0.483272      fail
8   0.185714  1.017560  0.902641  0.663665  0.467284  0.432949      fail
9   0.171429  1.055357  0.955357  0.732095  0.508621  0.472748      fail
10  0.173684  1.027632  0.922183  0.701879  0.504115  0.470512      pass
11  0.130435  1.092935  0.950577  0.713068  0.519744  0.486106      pass
12  0.133333  1.062153  0.916862  0.702808  0.511686  0.476623      pass
13  0.157895  1.145395  1.016365  0.752646  0.536363  0.497872      pass
14  0.156522  1.036957  0.894209  0.656892  0.464310  0.428947      pass
15  0.157895  1.069408  0.928824  0.696005  0.494021  0.461463      pass
16  0.157143  1.065476  0.896912  0.660561  0.481413  0.451464      pass
17  0.185714  1.045238  0.977046  0.734173  0.514489  0.480241      pass
18  0.128571  1.071875  0.890485  0.669287  0.476320  0.442332      pass
19  0.150000  0.975937  0.830059  0.620295  0.450474  0.419545      pass

BARINEL SCORES

         rx 5      cx 3       h 0      cx 2      cx 1      cx 4
sum  0.522658  0.505346  0.504789  0.503493  0.503489  0.499407

TARANTULA SCORES

         rx 5      cx 3       h 0      cx 2      cx 1      cx 4
sum  0.522658  0.505346  0.504789  0.503493  0.503489  0.499407

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_ccx_inGap_7_.qasm

100%|██████████| 10/10 [00:02<00:00,  3.84it/s]
100%|██████████| 10/10 [00:02<00:00,  3.80it/s]

       ccx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.179836  0.872425  0.650324  0.539931  0.394445  0.370717      fail
1   0.180682  0.875173  0.674084  0.557206  0.407238  0.385723      fail
2   0.175822  0.868559  0.677857  0.545804  0.387628  0.362797      fail
3   0.173766  0.783429  0.608426  0.499149  0.365121  0.345322      fail
4   0.177878  0.889406  0.711446  0.589161  0.430234  0.407469      fail
5   0.172396  0.852180  0.632118  0.514676  0.370051  0.348131      fail
6   0.177131  0.891857  0.714722  0.569827  0.412110  0.387835      fail
7   0.175355  0.890118  0.684887  0.562874  0.411397  0.390160      fail
8   0.178906  0.873434  0.644249  0.524653  0.392478  0.371222      fail
9   0.177976  0.901724  0.688258  0.563098  0.415245  0.392532      fail
10  0.178906  0.896420  0.676858  0.556222  0.402422  0.376779      pass
11  0.177757  0.848097  0.610280  0.497925  0.361020  0.347429      pass
12  0.181076  0.942666  0.714833  0.567536  0.418799  0.396873      pass
13  0.176953  0.864382  0.665838  0.541406  0.385621  0.359853      pass
14  0.180055  0.922192  0.688950  0.573498  0.415595  0.388978      pass
15  0.179934  0.921304  0.705362  0.580106  0.418721  0.393538      pass
16  0.180682  0.898159  0.706693  0.570542  0.410587  0.384005      pass
17  0.178906  0.902079  0.696837  0.569052  0.412906  0.389587      pass
18  0.179934  0.830407  0.631761  0.507763  0.364527  0.343176      pass
19  0.178906  0.869402  0.624188  0.500612  0.370394  0.348504      pass

BARINEL SCORES

          h 0      cx 1      cx 2      cx 3     ccx 5      cx 4
sum  0.502215  0.501595  0.500079  0.498686  0.496721  0.494407

TARANTULA SCORES

          h 0      cx 1      cx 2      cx 3     ccx 5      cx 4
sum  0.502215  0.501595  0.500079  0.498686  0.496721  0.494407

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_sx_inGap_10_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.93it/s]
100%|██████████| 10/10 [00:00<00:00, 11.36it/s]

      sxdg 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.400000  1.111250  0.850938  0.612395  0.529623  0.628161      fail
1   0.400000  1.055398  0.824201  0.569911  0.482197  0.558540      fail
2   0.509091  1.004545  0.713281  0.532617  0.480591  0.592965      fail
3   0.382609  1.046196  0.792103  0.575173  0.494426  0.580135      fail
4   0.463158  1.022368  0.740975  0.530861  0.475793  0.581587      fail
5   0.547368  1.066447  0.806353  0.535033  0.484695  0.607536      fail
6   0.448000  1.035750  0.786953  0.590982  0.509069  0.614299      fail
7   0.380952  1.116667  0.823865  0.588437  0.490156  0.572970      fail
8   0.382609  1.067120  0.774932  0.590865  0.499084  0.572951      fail
9   0.366667  1.057813  0.746224  0.546230  0.466328  0.532181      fail
10  0.417391  1.066576  0.760683  0.558113  0.488124  0.583615      pass
11  0.363636  1.065057  0.786790  0.563613  0.477780  0.555587      pass
12  0.444444  1.103125  0.863520  0.609880  0.506647  0.613651      pass
13  0.400000  1.088194  0.800716  0.556627  0.467948  0.547225      pass
14  0.378947  1.070066  0.788302  0.604511  0.504450  0.587432      pass
15  0.400000  1.093750  0.799718  0.570683  0.472846  0.546222      pass
16  0.360000  1.140938  0.847617  0.638817  0.551597  0.654109      pass
17  0.363636  1.065057  0.789347  0.563544  0.471662  0.543917      pass
18  0.304762  1.132143  0.819978  0.612880  0.493554  0.580770      pass
19  0.472727  1.093466  0.790146  0.573496  0.506910  0.614595      pass

BARINEL SCORES

       sxdg 5       h 0    cx 1      cx 3      cx 4      cx 2
sum  0.522899  0.500609  0.4985  0.494122  0.492214  0.492205

TARANTULA SCORES

       sxdg 5       h 0    cx 1      cx 3      cx 4      cx 2
sum  0.522899  0.500609  0.4985  0.494122  0.492214  0.492205

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_cx_inGap_6_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.39it/s]
100%|██████████| 10/10 [00:00<00:00, 12.04it/s]

        cx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.182188  1.149434  0.855385  0.631555  0.452244  0.428809      fail
1   0.209211  1.249527  0.905502  0.671541  0.491370  0.465224      fail
2   0.182188  1.149434  0.836993  0.634833  0.464885  0.439166      fail
3   0.225852  1.311168  0.965777  0.737674  0.546658  0.518538      fail
4   0.184028  1.156250  0.830607  0.638719  0.446000  0.420727      fail
5   0.198750  1.210781  0.899744  0.665724  0.504551  0.479844      fail
6   0.165625  1.088086  0.849471  0.638677  0.472440  0.447160      fail
7   0.172826  1.114759  0.847959  0.608482  0.441047  0.415368      fail
8   0.182188  1.149434  0.810825  0.597246  0.460788  0.441440      fail
9   0.220833  1.292578  0.980378  0.726094  0.539307  0.515287      fail
10  0.128819  0.951758  0.708667  0.496584  0.348596  0.332420      pass
11  0.126190  0.942020  0.706680  0.517550  0.371627  0.349144      pass
12  0.202431  1.224414  0.929405  0.683896  0.508473  0.481430      pass
13  0.184028  1.156250  0.917834  0.657392  0.491388  0.465050      pass
14  0.198750  1.210781  0.942885  0.709189  0.524268  0.497785      pass
15  0.189286  1.175725  0.887127  0.666909  0.468447  0.443285      pass
16  0.191776  1.184951  0.941445  0.703602  0.504009  0.473947      pass
17  0.198750  1.210781  0.855184  0.644879  0.485226  0.465932      pass
18  0.205060  1.234152  0.870772  0.629219  0.470855  0.448254      pass
19  0.165625  1.088086  0.810395  0.618191  0.441934  0.415715      pass

BARINEL SCORES

       cx 5       h 0      cx 1      cx 4      cx 2      cx 3
sum  0.5179  0.511102  0.510837  0.510592  0.508663  0.506116

TARANTULA SCORES

       cx 5       h 0      cx 1      cx 4      cx 2      cx 3
sum  0.5179  0.511102  0.510837  0.510592  0.508663  0.506116

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_h_inGap_7_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.73it/s]
100%|██████████| 10/10 [00:00<00:00, 13.29it/s]

         h 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.176471  1.339706  0.860363  0.628152  0.469896  0.435459      fail
1   0.177273  1.307386  0.853125  0.637676  0.465452  0.439365      fail
2   0.177273  1.330114  0.870455  0.631758  0.461217  0.424022      fail
3   0.157895  1.322368  0.882915  0.645314  0.452074  0.422198      fail
4   0.165000  1.370937  0.930586  0.695605  0.472113  0.435809      fail
5   0.150000  1.300284  0.871804  0.619872  0.433527  0.402013      fail
6   0.165000  1.345937  0.911523  0.648796  0.458189  0.424534      fail
7   0.142857  1.308333  0.901172  0.631570  0.458376  0.432583      fail
8   0.205263  1.402632  0.911410  0.642389  0.458967  0.424936      fail
9   0.165000  1.370937  0.930586  0.641768  0.463021  0.425021      fail
10  0.120000  1.312917  0.888464  0.629214  0.470938  0.444478      pass
11  0.157895  1.348684  0.902981  0.640413  0.443936  0.411481      pass
12  0.088235  1.220956  0.878424  0.640688  0.475942  0.449483      pass
13  0.150000  1.296181  0.851128  0.612853  0.454595  0.430955      pass
14  0.133333  1.307986  0.884505  0.661541  0.482046  0.447350      pass
15  0.177273  1.326420  0.851847  0.614173  0.432884  0.406778      pass
16  0.128571  1.239286  0.836328  0.601181  0.434817  0.407691      pass
17  0.150000  1.323437  0.881562  0.647473  0.463050  0.431971      pass
18  0.141176  1.276471  0.863764  0.604349  0.461170  0.441401      pass
19  0.163636  1.336080  0.879155  0.639806  0.458314  0.424566      pass

BARINEL SCORES

          h 5      cx 4      cx 3     cx 2      cx 1       h 0
sum  0.543968  0.507773  0.505832  0.50516  0.500826  0.498236

TARANTULA SCORES

          h 5      cx 4      cx 3     cx 2      cx 1       h 0
sum  0.543968  0.507773  0.505832  0.50516  0.500826  0.498236

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_sx_inGap_9_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.19it/s]
100%|██████████| 10/10 [00:00<00:00, 11.05it/s]

      sxdg 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.495238  1.050000  0.773903  0.684608  0.490916  0.463299      fail
1   0.480000  1.065937  0.739902  0.660522  0.488654  0.464627      fail
2   0.421053  1.094737  0.796402  0.689458  0.490634  0.461776      fail
3   0.440000  1.071563  0.803906  0.690203  0.482489  0.451218      fail
4   0.480000  1.031875  0.755000  0.676460  0.507956  0.485898      fail
5   0.417391  1.087500  0.822877  0.723072  0.535470  0.507234      fail
6   0.577778  1.052083  0.772721  0.699673  0.494916  0.467817      fail
7   0.400000  1.050347  0.815712  0.694614  0.526630  0.498797      fail
8   0.360000  1.063750  0.780430  0.640676  0.462583  0.436453      fail
9   0.463158  0.966447  0.720847  0.629357  0.453405  0.422427      fail
10  0.400000  1.173958  0.915126  0.763935  0.530431  0.495537      pass
11  0.440000  1.042500  0.780723  0.676042  0.495953  0.464672      pass
12  0.480000  1.060938  0.792793  0.668986  0.465690  0.432220      pass
13  0.421053  1.058882  0.782956  0.690877  0.524192  0.497034      pass
14  0.378947  1.050000  0.765687  0.659650  0.506550  0.478654      pass
15  0.400000  1.053125  0.773477  0.680433  0.494587  0.464119      pass
16  0.400000  1.125313  0.842227  0.734805  0.537260  0.502095      pass
17  0.480000  1.046500  0.770734  0.681252  0.496021  0.469154      pass
18  0.436364  0.997443  0.733487  0.635471  0.468807  0.442989      pass
19  0.463158  1.032895  0.723150  0.654920  0.489610  0.467931      pass

BARINEL SCORES

       sxdg 5      cx 2      cx 4       h 0     cx 3      cx 1
sum  0.513306  0.497883  0.497466  0.497074  0.49685  0.496206

TARANTULA SCORES

       sxdg 5      cx 2      cx 4       h 0     cx 3      cx 1
sum  0.513306  0.497883  0.497466  0.497074  0.49685  0.496206

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_sx_inGap_5_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.10it/s]
100%|██████████| 10/10 [00:00<00:00, 10.31it/s]

        cx 5      cx 4      cx 3      cx 2       h 1    sxdg 0 pass/fail
0   0.215312  0.859590  0.659048  0.482365  0.456880  0.567107      fail
1   0.172826  0.870550  0.657444  0.465205  0.434734  0.529691      fail
2   0.172826  0.875679  0.657799  0.467337  0.441317  0.536298      fail
3   0.173512  0.845089  0.637655  0.478008  0.454299  0.549084      fail
4   0.149063  0.823145  0.627539  0.455210  0.437485  0.526756      fail
5   0.189286  0.892690  0.640541  0.482765  0.460884  0.566115      fail
6   0.165625  0.835514  0.592900  0.430289  0.407273  0.485397      fail
7   0.189286  0.882738  0.655475  0.467465  0.440845  0.543591      fail
8   0.179427  0.905534  0.669519  0.483566  0.455764  0.552083      fail
9   0.205060  0.872396  0.646980  0.468360  0.443978  0.548956      fail
10  0.189286  0.861551  0.624459  0.438722  0.412258  0.502422      pass
11  0.132500  0.899395  0.641160  0.463007  0.434103  0.507847      pass
12  0.144022  0.854704  0.644226  0.462626  0.433276  0.516428      pass
13  0.156908  0.818072  0.616117  0.455579  0.426660  0.504613      pass
14  0.202431  0.882118  0.647697  0.459741  0.426280  0.524148      pass
15  0.179427  0.873372  0.632426  0.449771  0.424450  0.519075      pass
16  0.175368  0.813074  0.564169  0.420355  0.399232  0.470593      pass
17  0.198750  0.858652  0.616404  0.453205  0.433808  0.527370      pass
18  0.174342  0.859683  0.621510  0.455965  0.429925  0.521782      pass
19  0.104605  0.774486  0.608826  0.435444  0.404842  0.467673      pass

BARINEL SCORES

         cx 5    sxdg 0       h 1      cx 2   cx 3     cx 4
sum  0.522275  0.516391  0.512048  0.510145  0.509  0.50489

TARANTULA SCORES

         cx 5    sxdg 0       h 1      cx 2   cx 3     cx 4
sum  0.522275  0.516391  0.512048  0.510145  0.509  0.50489

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_cswap_inGap_5_.qasm

100%|██████████| 10/10 [00:02<00:00,  3.81it/s]
100%|██████████| 10/10 [00:02<00:00,  3.56it/s]

        cx 5   cswap 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.182188  0.946113  0.720467  0.510084  0.377039  0.352369      fail
1   0.165625  0.919279  0.698267  0.499995  0.369659  0.352762      fail
2   0.132500  0.889409  0.685199  0.495683  0.353248  0.336848      fail
3   0.157738  0.904454  0.682869  0.480673  0.349822  0.327811      fail
4   0.141964  0.882886  0.665653  0.489370  0.355217  0.335519      fail
5   0.135511  0.855462  0.643240  0.462842  0.330595  0.309877      fail
6   0.189286  0.959239  0.741227  0.539909  0.389114  0.362494      fail
7   0.165625  0.899004  0.678418  0.491018  0.355796  0.335207      fail
8   0.110417  0.833993  0.650854  0.472004  0.342230  0.323464      fail
9   0.173512  0.953519  0.718822  0.518166  0.373498  0.352760      fail
10  0.165625  0.952235  0.738131  0.525660  0.377218  0.351929      pass
11  0.189286  0.963438  0.739222  0.531362  0.377834  0.356842      pass
12  0.191776  0.984787  0.775778  0.541669  0.380271  0.357122      pass
13  0.226645  1.015996  0.780244  0.561275  0.397760  0.370965      pass
14  0.195739  0.990308  0.760425  0.543974  0.393646  0.366039      pass
15  0.157738  0.935202  0.703059  0.503320  0.365492  0.345846      pass
16  0.156908  0.924235  0.720298  0.518379  0.372588  0.350877      pass
17  0.165625  0.906826  0.701463  0.496555  0.352132  0.332912      pass
18  0.165625  0.932869  0.693700  0.487962  0.339803  0.320369      pass
19  0.157738  0.911904  0.705547  0.502410  0.360101  0.333958      pass

BARINEL SCORES

          h 0      cx 1      cx 2   cswap 4      cx 3      cx 5
sum  0.492892  0.491753  0.487573  0.487219  0.484762  0.467188

TARANTULA SCORES

          h 0      cx 1      cx 2   cswap 4      cx 3      cx 5
sum  0.492892  0.491753  0.487573  0.487219  0.484762  0.467188

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_ry_inGap_8_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.58it/s]
100%|██████████| 10/10 [00:00<00:00, 12.73it/s]

        ry 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.457143  1.027679  1.031603  0.660243  0.476565  0.438785      fail
1   0.440000  1.018438  1.040078  0.686365  0.494950  0.455862      fail
2   0.400000  1.103693  1.037571  0.685418  0.487884  0.460149      fail
3   0.421053  1.002961  0.982648  0.654411  0.476116  0.441333      fail
4   0.400000  1.055398  0.959339  0.619935  0.458785  0.434897      fail
5   0.347826  1.092935  1.033458  0.687497  0.511846  0.477603      fail
6   0.400000  1.072727  1.066442  0.700715  0.520293  0.488850      fail
7   0.452174  1.078261  1.042323  0.662066  0.491621  0.465811      fail
8   0.436364  1.001989  1.015128  0.687813  0.498241  0.473811      fail
9   0.360000  1.010625  0.921348  0.609202  0.446588  0.418178      fail
10  0.419048  1.065476  1.039323  0.691831  0.523625  0.497267      pass
11  0.355556  1.067708  0.978689  0.670169  0.462427  0.425969      pass
12  0.400000  1.081818  0.988938  0.642964  0.472448  0.445729      pass
13  0.400000  1.050347  1.057682  0.701394  0.537302  0.519038      pass
14  0.423529  1.125000  1.069187  0.688208  0.504070  0.476903      pass
15  0.320000  1.069375  1.013379  0.698130  0.534473  0.500346      pass
16  0.380952  1.121429  1.090216  0.727491  0.513027  0.479194      pass
17  0.329412  1.053309  0.968865  0.666212  0.510316  0.477877      pass
18  0.280000  1.050938  0.988105  0.697576  0.512072  0.477352      pass
19  0.421053  1.008224  0.980345  0.646969  0.501334  0.475771      pass

BARINEL SCORES

         ry 5      cx 3     cx 4      cx 2      cx 1       h 0
sum  0.524541  0.498897  0.49459  0.493427  0.489521  0.488202

TARANTULA SCORES

         ry 5      cx 3     cx 4      cx 2      cx 1       h 0
sum  0.524541  0.498897  0.49459  0.493427  0.489521  0.488202

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_cx_inGap_4_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.46it/s]
100%|██████████| 10/10 [00:00<00:00, 10.81it/s]

        cx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.209211  0.861657  0.794222  0.592330  0.415655  0.394389      fail
1   0.187228  0.890710  0.889340  0.629315  0.467888  0.445154      fail
2   0.157738  0.896522  0.945662  0.691930  0.516554  0.492299      fail
3   0.151823  0.858187  0.871272  0.651081  0.482265  0.461146      fail
4   0.172250  0.870500  0.867156  0.638396  0.476058  0.451912      fail
5   0.174342  0.859683  0.840480  0.597323  0.435784  0.410047      fail
6   0.173512  0.860658  0.844835  0.649261  0.487991  0.459151      fail
7   0.189286  0.855934  0.809737  0.608644  0.455544  0.436231      fail
8   0.157738  0.890904  0.931491  0.689023  0.522532  0.494828      fail
9   0.150568  0.831534  0.811488  0.575688  0.419477  0.397480      fail
10  0.156908  0.858697  0.863609  0.619455  0.458039  0.437971      pass
11  0.198750  0.880898  0.851755  0.620198  0.438173  0.415278      pass
12  0.141964  0.837686  0.839651  0.620853  0.459101  0.435184      pass
13  0.165625  0.840430  0.811804  0.600866  0.435254  0.414255      pass
14  0.144022  0.859834  0.886646  0.637730  0.467540  0.441739      pass
15  0.205060  0.930339  0.948613  0.687922  0.485572  0.457448      pass
16  0.157738  0.838579  0.818724  0.591736  0.432846  0.409846      pass
17  0.189286  0.861551  0.823908  0.578587  0.429346  0.407597      pass
18  0.191776  0.866879  0.833014  0.574993  0.411067  0.383953      pass
19  0.149063  0.817246  0.784388  0.590335  0.454877  0.436652      pass

BARINEL SCORES

          h 0     cx 1      cx 2      cx 3      cx 5      cx 4
sum  0.511674  0.51136  0.508048  0.504206  0.503432  0.502437

TARANTULA SCORES

          h 0     cx 1      cx 2      cx 3      cx 5      cx 4
sum  0.511674  0.51136  0.508048  0.504206  0.503432  0.502437

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_x_inGap_3_.qasm

100%|██████████| 10/10 [00:01<00:00, 10.00it/s]
100%|██████████| 10/10 [00:01<00:00,  9.71it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       x 0 pass/fail
0   0.141964  0.837686  0.625408  0.469851  0.447576  0.605409      fail
1   0.180682  0.853462  0.617348  0.462377  0.442768  0.589253      fail
2   0.165625  0.856777  0.642925  0.451627  0.426546  0.587736      fail
3   0.165625  0.840430  0.646052  0.462300  0.436432  0.606472      fail
4   0.182188  0.879961  0.669567  0.497259  0.472690  0.653923      fail
5   0.182188  0.863613  0.643676  0.498631  0.481188  0.654962      fail
6   0.184028  0.862912  0.686393  0.504876  0.481097  0.685555      fail
7   0.189286  0.877121  0.655788  0.476148  0.449570  0.619352      fail
8   0.198750  0.864551  0.649148  0.452925  0.426362  0.583665      fail
9   0.165625  0.856777  0.673461  0.503226  0.477484  0.671973      fail
10  0.182188  0.841367  0.634282  0.462684  0.438390  0.596571      pass
11  0.209211  0.919490  0.640182  0.472219  0.446971  0.588547      pass
12  0.156908  0.893113  0.657119  0.486376  0.456754  0.616028      pass
13  0.132500  0.822207  0.584189  0.435911  0.414002  0.540575      pass
14  0.122039  0.792681  0.610907  0.427368  0.401907  0.556669      pass
15  0.220833  0.915662  0.661005  0.482645  0.458521  0.606180      pass
16  0.202431  0.870508  0.626310  0.460921  0.436597  0.578001      pass
17  0.182188  0.847266  0.638345  0.453401  0.425798  0.589079      pass
18  0.226645  0.967311  0.712219  0.522360  0.491733  0.665676      pass
19  0.165625  0.821891  0.624024  0.455157  0.432089  0.596790      pass

BARINEL SCORES

          x 0       h 1      cx 2      cx 3      cx 4      cx 5
sum  0.513294  0.507767  0.506367  0.504698  0.497159  0.493729

TARANTULA SCORES

          x 0       h 1      cx 2      cx 3      cx 4      cx 5
sum  0.513294  0.507767  0.506367  0.504698  0.497159  0.493729

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_rxx_inGap_6_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.33it/s]
100%|██████████| 10/10 [00:00<00:00, 12.61it/s]

       rxx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.260870  1.172283  0.871365  0.641760  0.470280  0.443645      fail
1   0.238095  1.175893  0.855934  0.636691  0.456197  0.432902      fail
2   0.272727  1.213636  0.910476  0.632198  0.442782  0.416708      fail
3   0.275000  1.221563  0.914531  0.669496  0.480739  0.453432      fail
4   0.300000  1.163438  0.896309  0.654294  0.472142  0.446540      fail
5   0.227273  1.160795  0.838601  0.616869  0.444467  0.424696      fail
6   0.214286  1.120536  0.801823  0.593154  0.440597  0.419041      fail
7   0.260870  1.096467  0.821145  0.610017  0.422846  0.393448      fail
8   0.227273  1.081534  0.786097  0.588386  0.410385  0.382125      fail
9   0.272727  1.187216  0.894762  0.650136  0.477994  0.447840      fail
10  0.239130  1.172283  0.857150  0.624988  0.457012  0.427684      pass
11  0.210526  1.149671  0.812850  0.617601  0.453953  0.422671      pass
12  0.315789  1.149671  0.906517  0.652894  0.466847  0.441100      pass
13  0.238095  1.148214  0.839472  0.615899  0.450127  0.424533      pass
14  0.250000  1.105313  0.817246  0.611332  0.450558  0.427193      pass
15  0.214286  1.175893  0.840365  0.635166  0.472918  0.447492      pass
16  0.235294  1.117279  0.818911  0.591086  0.436544  0.413775      pass
17  0.236842  1.088487  0.799877  0.604357  0.440577  0.410639      pass
18  0.184211  1.272039  0.893257  0.654559  0.460646  0.431161      pass
19  0.275000  1.134375  0.850879  0.619008  0.432924  0.406501      pass

BARINEL SCORES

        rxx 5      cx 3     cx 2      cx 4       h 0      cx 1
sum  0.515151  0.504537  0.50264  0.501734  0.500448  0.499797

TARANTULA SCORES

        rxx 5      cx 3     cx 2      cx 4       h 0      cx 1
sum  0.515151  0.504537  0.50264  0.501734  0.500448  0.499797

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rxx_inGap_5_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.97it/s]
100%|██████████| 10/10 [00:00<00:00, 11.82it/s]

        cx 5     rxx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.195739  1.447159  0.884038  0.638383  0.473091  0.448580      fail
1   0.144022  1.336957  0.796671  0.603428  0.438943  0.414789      fail
2   0.182188  1.397813  0.835469  0.597852  0.442190  0.418923      fail
3   0.151823  1.309375  0.821110  0.615461  0.449943  0.426320      fail
4   0.165625  1.334659  0.787802  0.606054  0.451476  0.430948      fail
5   0.165625  1.368750  0.782440  0.587968  0.439213  0.413843      fail
6   0.187228  1.388315  0.871365  0.644645  0.477808  0.455607      fail
7   0.165625  1.338920  0.837749  0.626928  0.453820  0.429896      fail
8   0.189286  1.412500  0.871503  0.654357  0.478992  0.453125      fail
9   0.149063  1.320938  0.833594  0.612639  0.452377  0.429370      fail
10  0.220833  1.392708  0.914431  0.638943  0.494951  0.464246      pass
11  0.180682  1.344034  0.893910  0.629419  0.453003  0.424934      pass
12  0.184028  1.359375  0.862912  0.658995  0.458747  0.427803      pass
13  0.149063  1.353750  0.772754  0.578199  0.420716  0.398526      pass
14  0.198750  1.389375  0.880898  0.642334  0.463996  0.430649      pass
15  0.120455  1.242614  0.800107  0.611276  0.438221  0.415578      pass
16  0.156908  1.301645  0.800863  0.583031  0.424891  0.404494      pass
17  0.165625  1.270739  0.848473  0.633337  0.464409  0.438890      pass
18  0.141964  1.271429  0.785361  0.570947  0.394731  0.367138      pass
19  0.172826  1.363043  0.836990  0.591912  0.444921  0.423084      pass

BARINEL SCORES

          h 0     rxx 4      cx 1      cx 2      cx 5      cx 3
sum  0.507401  0.506804  0.505505  0.502001  0.500751  0.497758

TARANTULA SCORES

          h 0     rxx 4      cx 1      cx 2      cx 5      cx 3
sum  0.507401  0.506804  0.505505  0.502001  0.500751  0.497758

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_ccx_inGap_6_.qasm

100%|██████████| 10/10 [00:02<00:00,  4.73it/s]
100%|██████████| 10/10 [00:02<00:00,  4.56it/s]

       ccx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.175355  0.851592  0.708560  0.524200  0.380479  0.358299      fail
1   0.176953  0.841664  0.667138  0.502621  0.363391  0.343879      fail
2   0.179755  0.824253  0.669336  0.498406  0.363133  0.341238      fail
3   0.178906  0.829529  0.662198  0.496089  0.356381  0.335376      fail
4   0.176116  0.846865  0.694640  0.516927  0.378981  0.356291      fail
5   0.176116  0.846865  0.700544  0.514512  0.380074  0.359054      fail
6   0.177878  0.835916  0.677705  0.507163  0.369687  0.351341      fail
7   0.174566  0.856495  0.704704  0.510576  0.367695  0.349879      fail
8   0.179836  0.823750  0.667917  0.495803  0.358699  0.341128      fail
9   0.173580  0.862624  0.714802  0.534828  0.388408  0.368497      fail
10  0.174660  0.855909  0.703422  0.514163  0.374311  0.355130      pass
11  0.178906  0.829529  0.668086  0.491323  0.352648  0.333077      pass
12  0.176116  0.846865  0.680996  0.499837  0.359444  0.338556      pass
13  0.180859  0.817394  0.688258  0.497077  0.361632  0.343034      pass
14  0.178906  0.829529  0.662450  0.490056  0.352509  0.332592      pass
15  0.177131  0.840561  0.687352  0.514835  0.373219  0.348820      pass
16  0.178906  0.829529  0.678661  0.500830  0.361660  0.337299      pass
17  0.178906  0.829529  0.666639  0.497895  0.361650  0.342558      pass
18  0.178057  0.834805  0.702079  0.526622  0.384937  0.363015      pass
19  0.173047  0.865934  0.707597  0.510569  0.372027  0.351814      pass

BARINEL SCORES

         h 0      cx 1      cx 2     cx 4      cx 3     ccx 5
sum  0.50425  0.503593  0.502855  0.50119  0.500802  0.499093

TARANTULA SCORES

         h 0      cx 1      cx 2     cx 4      cx 3     ccx 5
sum  0.50425  0.503593  0.502855  0.50119  0.500802  0.499093

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rx_inGap_3_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.36it/s]
100%|██████████| 10/10 [00:01<00:00,  9.59it/s]

        cx 5      cx 4      cx 3      cx 2       h 1      rx 0 pass/fail
0   0.156908  0.852488  0.655967  0.476984  0.444937  0.417513      fail
1   0.150568  0.877344  0.641674  0.478328  0.451288  0.435666      fail
2   0.149063  0.833594  0.658932  0.485028  0.464278  0.431508      fail
3   0.149063  0.823145  0.615763  0.437120  0.413122  0.395884      fail
4   0.189286  0.892690  0.694481  0.498367  0.472163  0.447646      fail
5   0.198750  0.880898  0.668066  0.491544  0.465393  0.435792      fail
6   0.182188  0.863613  0.652871  0.480508  0.450613  0.423439      fail
7   0.187228  0.890710  0.652813  0.475583  0.450548  0.427524      fail
8   0.158424  0.836175  0.630613  0.466628  0.439585  0.418028      fail
9   0.182188  0.863613  0.656189  0.457786  0.430190  0.404769      fail
10  0.174342  0.883100  0.665470  0.485590  0.458505  0.432374      pass
11  0.173512  0.845089  0.598070  0.440546  0.417696  0.389793      pass
12  0.179427  0.841211  0.597185  0.425250  0.399762  0.379123      pass
13  0.173512  0.855041  0.637077  0.457755  0.428032  0.401784      pass
14  0.173512  0.870610  0.644571  0.467401  0.438165  0.413553      pass
15  0.189286  0.877121  0.669121  0.492636  0.463535  0.433629      pass
16  0.209211  0.891283  0.659624  0.472897  0.451467  0.428939      pass
17  0.165625  0.913281  0.685802  0.509088  0.478504  0.455258      pass
18  0.172826  0.836990  0.598295  0.432631  0.405594  0.382070      pass
19  0.182188  0.863613  0.660212  0.477291  0.452286  0.428009      pass

BARINEL SCORES

         rx 0      h 1      cx 2      cx 3      cx 4      cx 5
sum  0.505561  0.50499  0.504612  0.504324  0.498176  0.487164

TARANTULA SCORES

         rx 0      h 1      cx 2      cx 3      cx 4      cx 5
sum  0.505561  0.50499  0.504612  0.504324  0.498176  0.487164

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_y_inGap_2_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.18it/s]
100%|██████████| 10/10 [00:00<00:00, 10.32it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       y 0 pass/fail
0   0.149063  0.811348  0.591807  0.437530  0.411860  0.553083      fail
1   0.172826  0.803431  0.601163  0.437228  0.413114  0.548520      fail
2   0.189286  0.840365  0.596604  0.443877  0.420369  0.566836      fail
3   0.150568  0.801811  0.598207  0.435154  0.409323  0.545866      fail
4   0.165625  0.840430  0.622174  0.471441  0.450571  0.628006      fail
5   0.150568  0.857120  0.621758  0.455769  0.428623  0.579759      fail
6   0.195739  0.839453  0.625569  0.460803  0.436015  0.593234      fail
7   0.165625  0.901270  0.665029  0.504539  0.482138  0.670526      fail
8   0.205060  0.914769  0.674351  0.512266  0.490370  0.681998      fail
9   0.182188  0.851816  0.636625  0.487327  0.464475  0.651138      fail
10  0.184028  0.874523  0.604824  0.428168  0.404961  0.525264      pass
11  0.215312  0.926328  0.689060  0.489086  0.458132  0.612591      pass
12  0.149063  0.817246  0.611332  0.432276  0.405088  0.521467      pass
13  0.220833  0.914431  0.679835  0.510217  0.480031  0.670149      pass
14  0.174342  0.876891  0.635625  0.480336  0.446371  0.615901      pass
15  0.173512  0.891797  0.665434  0.483692  0.456505  0.610581      pass
16  0.175368  0.853125  0.643232  0.458096  0.425786  0.563069      pass
17  0.165625  0.855317  0.639377  0.488193  0.466143  0.644264      pass
18  0.150568  0.842259  0.613293  0.436321  0.408308  0.535160      pass
19  0.173512  0.839472  0.595575  0.434615  0.410991  0.545150      pass

BARINEL SCORES

          y 0      h 1      cx 2      cx 3      cx 4      cx 5
sum  0.507392  0.50254  0.500266  0.494279  0.493308  0.492075

TARANTULA SCORES

          y 0      h 1      cx 2      cx 3      cx 4      cx 5
sum  0.507392  0.50254  0.500266  0.494279  0.493308  0.492075

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_sx_inGap_4_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.44it/s]
100%|██████████| 10/10 [00:00<00:00, 10.38it/s]

        cx 5      cx 4      cx 3      cx 2       h 1    sxdg 0 pass/fail
0   0.129620  0.825459  0.608791  0.459656  0.433734  0.570524      fail
1   0.195739  0.874538  0.652638  0.472340  0.444042  0.572415      fail
2   0.173512  0.891797  0.632521  0.448073  0.419407  0.554241      fail
3   0.157738  0.896522  0.655334  0.467618  0.443912  0.588932      fail
4   0.182188  0.819121  0.588129  0.438169  0.415938  0.513655      fail
5   0.209211  0.936698  0.658965  0.486366  0.455675  0.598656      fail
6   0.144022  0.821145  0.620898  0.447348  0.426129  0.547251      fail
7   0.205060  0.935956  0.696238  0.509424  0.478059  0.643775      fail
8   0.156908  0.882113  0.611290  0.444915  0.419312  0.548124      fail
9   0.189286  0.898307  0.660903  0.486268  0.457954  0.601574      fail
10  0.174342  0.848684  0.655811  0.469271  0.435088  0.577891      pass
11  0.182188  0.874062  0.629481  0.460658  0.433624  0.548542      pass
12  0.180682  0.864187  0.646510  0.466473  0.440609  0.581828      pass
13  0.156908  0.841488  0.672861  0.464423  0.433935  0.563144      pass
14  0.198750  0.864551  0.635929  0.475694  0.450305  0.582047      pass
15  0.157738  0.832961  0.606076  0.430865  0.398637  0.509247      pass
16  0.147222  0.829557  0.623644  0.470259  0.442628  0.559551      pass
17  0.141964  0.816499  0.613302  0.454131  0.433628  0.545527      pass
18  0.182188  0.802773  0.587601  0.444393  0.420963  0.515432      pass
19  0.128819  0.767470  0.564653  0.409958  0.387476  0.471818      pass

BARINEL SCORES

         cx 5      cx 4    sxdg 0       h 1      cx 2      cx 3
sum  0.513624  0.512831  0.512691  0.506762  0.506194  0.505936

TARANTULA SCORES

         cx 5      cx 4    sxdg 0       h 1      cx 2      cx 3
sum  0.513624  0.512831  0.512691  0.506762  0.506194  0.505936

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_swap_inGap_4_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.78it/s]
100%|██████████| 10/10 [00:01<00:00,  9.83it/s]

        cx 5      cx 4    swap 3      cx 2      cx 1       h 0 pass/fail
0   0.182188  0.879961  0.809863  0.660863  0.483560  0.461210      fail
1   0.157738  0.880952  0.751410  0.619825  0.469494  0.444696      fail
2   0.156908  0.824280  0.746353  0.591053  0.449929  0.428682      fail
3   0.165625  0.801836  0.695300  0.532205  0.380709  0.360231      fail
4   0.180682  0.843963  0.693580  0.540271  0.394654  0.372757      fail
5   0.165625  0.818184  0.717130  0.557803  0.413895  0.395100      fail
6   0.182188  0.863613  0.789286  0.625743  0.453586  0.427211      fail
7   0.191776  0.907504  0.801245  0.663339  0.500514  0.477975      fail
8   0.165625  0.873125  0.776006  0.634624  0.482109  0.459636      fail
9   0.149063  0.817246  0.716759  0.564930  0.383346  0.359660      fail
10  0.182188  0.851816  0.685333  0.527484  0.387917  0.363853      pass
11  0.198750  0.880898  0.751425  0.588472  0.428541  0.406394      pass
12  0.198750  0.897246  0.727123  0.577041  0.433880  0.412616      pass
13  0.233824  0.933364  0.828089  0.663244  0.482839  0.452082      pass
14  0.191776  0.901295  0.804310  0.651450  0.464927  0.439397      pass
15  0.128819  0.835069  0.701653  0.579102  0.434901  0.414559      pass
16  0.184028  0.826584  0.771762  0.609294  0.450109  0.427511      pass
17  0.182188  0.857715  0.710063  0.560043  0.423110  0.406393      pass
18  0.165625  0.855317  0.642480  0.509054  0.363209  0.343559      pass
19  0.187228  0.857150  0.707731  0.554340  0.424626  0.401975      pass

BARINEL SCORES

         cx 2       h 0      cx 1   swap 3      cx 4      cx 5
sum  0.507245  0.507196  0.506762  0.50563  0.494601  0.478066

TARANTULA SCORES

         cx 2       h 0      cx 1   swap 3      cx 4      cx 5
sum  0.507245  0.507196  0.506762  0.50563  0.494601  0.478066

ERROR GATE LOCATION:
3
Now evolving the following mutant:  AddGate_rxx_inGap_2_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.96it/s]
100%|██████████| 10/10 [00:01<00:00,  9.82it/s]

        cx 5      cx 4      cx 3      cx 2     rxx 1       h 0 pass/fail
0   0.157738  0.796205  0.593116  0.446686  0.537864  0.480388      fail
1   0.149063  0.833594  0.592373  0.429137  0.500309  0.449792      fail
2   0.174342  0.883100  0.632174  0.461851  0.529128  0.478064      fail
3   0.182188  0.857715  0.677859  0.505684  0.602706  0.538194      fail
4   0.191776  0.820045  0.626119  0.463430  0.561803  0.495547      fail
5   0.191776  0.837253  0.604211  0.458979  0.541738  0.480058      fail
6   0.165625  0.862676  0.630082  0.481296  0.549150  0.490533      fail
7   0.180682  0.853462  0.627748  0.462143  0.521182  0.476388      fail
8   0.172826  0.880808  0.657512  0.479398  0.558820  0.505815      fail
9   0.182188  0.879961  0.641254  0.476388  0.558525  0.499299      fail
10  0.172826  0.856335  0.629160  0.458714  0.503292  0.469028      pass
11  0.195739  0.809730  0.608533  0.433299  0.499143  0.456544      pass
12  0.156908  0.818072  0.623845  0.449646  0.535877  0.485527      pass
13  0.165625  0.855317  0.639377  0.477475  0.550087  0.497699      pass
14  0.189286  0.855934  0.612184  0.470409  0.550339  0.487290      pass
15  0.174342  0.859683  0.638917  0.465527  0.550852  0.498411      pass
16  0.135511  0.800959  0.589200  0.427186  0.492178  0.444431      pass
17  0.128819  0.841623  0.629868  0.458240  0.509581  0.476017      pass
18  0.172826  0.827904  0.612251  0.446503  0.535180  0.475479      pass
19  0.189286  0.935063  0.686451  0.492536  0.566202  0.519041      pass

BARINEL SCORES

         cx 5     rxx 1      cx 2      h 0      cx 4      cx 3
sum  0.509774  0.507834  0.504622  0.50436  0.501303  0.500504

TARANTULA SCORES

         cx 5     rxx 1      cx 2      h 0      cx 4      cx 3
sum  0.509774  0.507834  0.504622  0.50436  0.501303  0.500504

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_rx_inGap_10_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.37it/s]
100%|██████████| 10/10 [00:00<00:00, 12.14it/s]

        rx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.382609  1.088043  0.824304  0.592719  0.500051  0.588233      fail
1   0.419048  1.083631  0.821112  0.601297  0.518923  0.619552      fail
2   0.440000  1.071563  0.820254  0.621248  0.534689  0.636166      fail
3   0.457143  1.050595  0.786068  0.581634  0.521838  0.632104      fail
4   0.486957  1.022826  0.711294  0.525524  0.455093  0.554171      fail
5   0.400000  1.103693  0.807955  0.593665  0.496086  0.595528      fail
6   0.360000  1.063750  0.768105  0.533907  0.449584  0.519443      fail
7   0.556522  1.033967  0.798047  0.579812  0.510688  0.638560      fail
8   0.457143  1.050595  0.776618  0.559247  0.482355  0.570622      fail
9   0.400000  1.072727  0.736648  0.515710  0.447422  0.521288      fail
10  0.463158  1.052961  0.741961  0.549405  0.479647  0.589308      pass
11  0.440000  0.994375  0.708574  0.511650  0.417722  0.488406      pass
12  0.376471  1.040809  0.828355  0.594146  0.483973  0.581045      pass
13  0.505263  1.016447  0.775308  0.576401  0.497017  0.621443      pass
14  0.294737  1.087171  0.803187  0.608424  0.498272  0.577760      pass
15  0.457143  1.105952  0.840179  0.610689  0.527239  0.641966      pass
16  0.495238  1.068155  0.769736  0.558300  0.485788  0.608273      pass
17  0.419048  1.037798  0.790309  0.581341  0.474596  0.562815      pass
18  0.380952  1.088988  0.814676  0.580396  0.511801  0.621493      pass
19  0.450000  1.016016  0.755103  0.556282  0.474531  0.566696      pass

BARINEL SCORES

         rx 5      cx 1      cx 4      cx 3       h 0      cx 2
sum  0.504479  0.503386  0.503138  0.500734  0.500701  0.499026

TARANTULA SCORES

         rx 5      cx 1      cx 4      cx 3       h 0      cx 2
sum  0.504479  0.503386  0.503138  0.500734  0.500701  0.499026

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_ry_inGap_4_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.23it/s]
100%|██████████| 10/10 [00:01<00:00,  9.96it/s]

        cx 5      cx 4      cx 3      cx 2       h 1      ry 0 pass/fail
0   0.194853  0.885754  0.651782  0.474684  0.449173  0.599100      fail
1   0.195739  0.879901  0.664691  0.479468  0.455743  0.616868      fail
2   0.158424  0.836175  0.580411  0.440847  0.419328  0.554758      fail
3   0.150568  0.836896  0.613258  0.459046  0.435444  0.580752      fail
4   0.193229  0.901400  0.656913  0.489813  0.462286  0.633031      fail
5   0.165625  0.895371  0.649896  0.476801  0.452936  0.630021      fail
6   0.132500  0.832656  0.622924  0.480402  0.453704  0.624277      fail
7   0.187228  0.876495  0.636976  0.459302  0.434201  0.586811      fail
8   0.189286  0.887072  0.642270  0.460036  0.431851  0.574692      fail
9   0.195739  0.879901  0.640962  0.474108  0.450009  0.603327      fail
10  0.173512  0.897414  0.675272  0.492230  0.466502  0.646393      pass
11  0.165625  0.837749  0.640985  0.464786  0.434908  0.584955      pass
12  0.180682  0.823739  0.604372  0.431167  0.404582  0.520406      pass
13  0.136397  0.784697  0.605522  0.454526  0.433776  0.578477      pass
14  0.209211  0.902282  0.660959  0.457632  0.425833  0.563978      pass
15  0.128819  0.731141  0.507491  0.363294  0.337668  0.413256      pass
16  0.189286  0.855934  0.597106  0.455623  0.435476  0.571929      pass
17  0.180682  0.843963  0.616569  0.469925  0.447188  0.592439      pass
18  0.157738  0.823010  0.557620  0.411870  0.388738  0.516372      pass
19  0.195739  0.869176  0.626528  0.461422  0.439225  0.577965      pass

BARINEL SCORES

         ry 0       h 1     cx 2      cx 3      cx 4      cx 5
sum  0.518906  0.513327  0.51267  0.510747  0.510026  0.506536

TARANTULA SCORES

         ry 0       h 1     cx 2      cx 3      cx 4      cx 5
sum  0.518906  0.513327  0.51267  0.510747  0.510026  0.506536

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_rx_inGap_2_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.71it/s]
100%|██████████| 10/10 [00:00<00:00, 10.65it/s]

        cx 5      cx 4      cx 3      cx 2       h 1      rx 0 pass/fail
0   0.180682  0.879048  0.628940  0.463054  0.435570  0.592554      fail
1   0.182188  0.902207  0.657283  0.493168  0.468282  0.648992      fail
2   0.165625  0.878196  0.642991  0.469433  0.446707  0.600713      fail
3   0.150568  0.857120  0.617766  0.456088  0.436836  0.593383      fail
4   0.157738  0.838579  0.597004  0.436412  0.410911  0.548157      fail
5   0.165625  0.828249  0.632822  0.469669  0.440457  0.603430      fail
6   0.210795  0.925337  0.674829  0.495107  0.470906  0.639627      fail
7   0.174342  0.876891  0.617397  0.460344  0.439490  0.602243      fail
8   0.165625  0.824082  0.603624  0.444087  0.425391  0.568819      fail
9   0.174342  0.825267  0.628128  0.482108  0.457387  0.636686      fail
10  0.149063  0.817246  0.599187  0.459269  0.434734  0.601599      pass
11  0.165625  0.857972  0.649859  0.470851  0.441731  0.585938      pass
12  0.173512  0.855041  0.659818  0.492623  0.469828  0.644416      pass
13  0.198750  0.836406  0.599301  0.446998  0.429299  0.582409      pass
14  0.136397  0.817808  0.624822  0.440834  0.416585  0.555020      pass
15  0.173512  0.802716  0.613443  0.439049  0.413830  0.550657      pass
16  0.141964  0.843304  0.641169  0.483058  0.453794  0.634698      pass
17  0.209211  0.885074  0.660404  0.451813  0.421826  0.543449      pass
18  0.165625  0.843707  0.619184  0.449797  0.418065  0.567609      pass
19  0.191776  0.837253  0.609655  0.443456  0.425729  0.563094      pass

BARINEL SCORES

        rx 0   cx 4       h 1      cx 2      cx 5      cx 3
sum  0.50867  0.507  0.506081  0.504959  0.503218  0.500952

TARANTULA SCORES

        rx 0   cx 4       h 1      cx 2      cx 5      cx 3
sum  0.50867  0.507  0.506081  0.504959  0.503218  0.500952

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_cswap_inGap_4_.qasm

100%|██████████| 10/10 [00:02<00:00,  4.01it/s]
100%|██████████| 10/10 [00:02<00:00,  4.07it/s]

        cx 5      cx 4   cswap 3      cx 2      cx 1       h 0 pass/fail
0   0.191776  0.860670  0.765821  0.580633  0.411690  0.386890      fail
1   0.172826  0.842120  0.756825  0.579977  0.414996  0.391595      fail
2   0.149063  0.855840  0.740141  0.569850  0.409547  0.383544      fail
3   0.173512  0.855041  0.731610  0.555787  0.400894  0.376829      fail
4   0.195739  0.889400  0.785311  0.596343  0.415557  0.389912      fail
5   0.198750  0.909043  0.814705  0.626018  0.440532  0.415357      fail
6   0.205060  0.893583  0.780897  0.601114  0.423297  0.396624      fail
7   0.173512  0.860658  0.758454  0.584231  0.419953  0.398416      fail
8   0.191776  0.901295  0.812559  0.619761  0.442781  0.416799      fail
9   0.165625  0.837749  0.756195  0.579554  0.417608  0.395809      fail
10  0.195739  0.894762  0.800519  0.611333  0.441723  0.417405      pass
11  0.132500  0.816309  0.710492  0.542102  0.378202  0.356336      pass
12  0.132500  0.799961  0.686650  0.519097  0.370654  0.345412      pass
13  0.149063  0.883984  0.790728  0.600832  0.427006  0.401612      pass
14  0.209211  0.861657  0.776248  0.574040  0.412501  0.392708      pass
15  0.179427  0.873372  0.767011  0.590261  0.410823  0.384815      pass
16  0.174342  0.883100  0.792278  0.600933  0.432925  0.405583      pass
17  0.174342  0.876891  0.774968  0.597661  0.428514  0.406666      pass
18  0.157738  0.823010  0.723664  0.549045  0.398740  0.378396      pass
19  0.165625  0.857972  0.753472  0.568497  0.412862  0.387716      pass

BARINEL SCORES

         cx 5      cx 2      cx 1       h 0   cswap 3      cx 4
sum  0.521093  0.505987  0.504988  0.504798  0.504139  0.503889

TARANTULA SCORES

         cx 5      cx 2      cx 1       h 0   cswap 3      cx 4
sum  0.521093  0.505987  0.504988  0.504798  0.504139  0.503889

ERROR GATE LOCATION:
3
Now evolving the following mutant:  AddGate_ry_inGap_2_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.87it/s]
100%|██████████| 10/10 [00:00<00:00, 10.54it/s]

        cx 5      cx 4      cx 3      cx 2       h 1      ry 0 pass/fail
0   0.139474  0.817085  0.591740  0.446227  0.430647  0.594041      fail
1   0.191776  0.866879  0.660607  0.484784  0.457075  0.621534      fail
2   0.189286  0.861551  0.633568  0.458196  0.437209  0.587271      fail
3   0.150568  0.857120  0.641159  0.466922  0.439541  0.598441      fail
4   0.215312  0.881836  0.621000  0.472533  0.442667  0.610102      fail
5   0.189286  0.877121  0.645637  0.476972  0.445879  0.608207      fail
6   0.172826  0.861464  0.613202  0.453583  0.430032  0.582136      fail
7   0.156908  0.835280  0.581858  0.446767  0.428382  0.584185      fail
8   0.205060  0.856827  0.621970  0.471998  0.447714  0.623333      fail
9   0.184028  0.905794  0.677391  0.499099  0.464904  0.643659      fail
10  0.165625  0.822887  0.626448  0.476897  0.454138  0.634461      pass
11  0.195739  0.879901  0.629922  0.461628  0.437443  0.596484      pass
12  0.220833  0.921280  0.676440  0.493779  0.465915  0.634611      pass
13  0.118304  0.731696  0.517266  0.379764  0.363909  0.477072      pass
14  0.209211  0.908491  0.663284  0.456574  0.428271  0.556673      pass
15  0.189286  0.840365  0.620088  0.463058  0.442564  0.607263      pass
16  0.182188  0.902207  0.649161  0.460758  0.432163  0.573186      pass
17  0.165625  0.818184  0.588123  0.444228  0.420453  0.574699      pass
18  0.139474  0.817085  0.635492  0.447053  0.423599  0.554678      pass
19  0.176667  0.835156  0.639403  0.420722  0.394786  0.478148      pass

BARINEL SCORES

         ry 0    cx 2       h 1      cx 5      cx 4      cx 3
sum  0.515572  0.5094  0.509255  0.504438  0.504202  0.501696

TARANTULA SCORES

         ry 0    cx 2       h 1      cx 5      cx 4      cx 3
sum  0.515572  0.5094  0.509255  0.504438  0.504202  0.501696

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_rxx_inGap_10_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.60it/s]
100%|██████████| 10/10 [00:00<00:00, 11.03it/s]

       rxx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.052381  1.010417  0.731566  0.675224  0.628740  0.624625      fail
1   0.075000  0.837500  0.610664  0.633118  0.668074  0.734919      fail
2   0.052381  1.000893  0.702902  0.663081  0.633830  0.660654      fail
3   0.052941  0.995956  0.696140  0.631432  0.614907  0.640504      fail
4   0.068421  0.901974  0.658183  0.649611  0.682990  0.771033      fail
5   0.052381  0.973214  0.738765  0.674661  0.639545  0.666346      fail
6   0.057143  0.898512  0.652362  0.600716  0.563914  0.607534      fail
7   0.050000  0.958239  0.680629  0.639013  0.608518  0.655172      fail
8   0.066667  0.913393  0.642448  0.631203  0.638515  0.695796      fail
9   0.055556  1.018403  0.758051  0.711985  0.654596  0.661442      fail
10  0.047619  1.030655  0.757068  0.650567  0.610815  0.665749      pass
11  0.057895  0.945724  0.700329  0.665462  0.668604  0.715844      pass
12  0.052632  0.927961  0.673109  0.609227  0.583536  0.631958      pass
13  0.047368  0.990461  0.766016  0.674481  0.650395  0.713358      pass
14  0.045000  0.993125  0.706230  0.584727  0.540242  0.581717      pass
15  0.046667  1.047500  0.718411  0.583569  0.538753  0.616941      pass
16  0.042857  1.004167  0.748084  0.652309  0.582081  0.587865      pass
17  0.045455  0.986648  0.734286  0.650890  0.593728  0.620206      pass
18  0.035294  1.002574  0.693222  0.582013  0.491400  0.523069      pass
19  0.045455  0.995739  0.730469  0.641041  0.601089  0.639239      pass

BARINEL SCORES

        rxx 5      cx 1       h 0      cx 2      cx 4      cx 3
sum  0.555585  0.519394  0.516216  0.508425  0.489295  0.487392

TARANTULA SCORES

        rxx 5      cx 1       h 0      cx 2      cx 4      cx 3
sum  0.555585  0.519394  0.516216  0.508425  0.489295  0.487392

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rxx_inGap_1_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.43it/s]
100%|██████████| 10/10 [00:00<00:00, 10.58it/s]

        cx 5      cx 4      cx 3      cx 2       h 1     rxx 0 pass/fail
0   0.172826  0.856335  0.650922  0.475107  0.448137  0.453066      fail
1   0.141964  0.779743  0.575836  0.405637  0.386286  0.379728      fail
2   0.182188  0.863613  0.619017  0.447072  0.418674  0.413038      fail
3   0.180682  0.873686  0.628904  0.464498  0.440017  0.434963      fail
4   0.182188  0.819121  0.588497  0.441050  0.419704  0.418567      fail
5   0.173512  0.876228  0.638659  0.479297  0.450476  0.443696      fail
6   0.157738  0.844196  0.613142  0.446182  0.419317  0.408955      fail
7   0.173512  0.891797  0.683993  0.502829  0.474603  0.471034      fail
8   0.189286  0.861551  0.643369  0.481533  0.452452  0.453212      fail
9   0.150568  0.801811  0.616592  0.455712  0.428305  0.434103      fail
10  0.182188  0.857715  0.639613  0.441779  0.416186  0.417175      pass
11  0.157738  0.844196  0.637649  0.453841  0.424705  0.428092      pass
12  0.157738  0.823010  0.593693  0.399622  0.373349  0.369758      pass
13  0.174342  0.883100  0.623237  0.437236  0.405851  0.396877      pass
14  0.157738  0.859766  0.645535  0.465739  0.440083  0.449337      pass
15  0.154583  0.833906  0.570775  0.407979  0.374121  0.375224      pass
16  0.191776  0.873088  0.657544  0.487560  0.456353  0.464851      pass
17  0.122039  0.798890  0.580369  0.410424  0.387173  0.384047      pass
18  0.172826  0.836990  0.610111  0.447093  0.420019  0.421068      pass
19  0.156908  0.800863  0.610118  0.427574  0.404534  0.415953      pass

BARINEL SCORES

          h 1      cx 2      cx 5     rxx 0      cx 3      cx 4
sum  0.513957  0.512256  0.511491  0.511146  0.503633  0.501675

TARANTULA SCORES

          h 1      cx 2      cx 5     rxx 0      cx 3      cx 4
sum  0.513957  0.512256  0.511491  0.511146  0.503633  0.501675

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_swap_inGap_3_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.74it/s]
100%|██████████| 10/10 [00:01<00:00,  9.55it/s]

        cx 5      cx 4      cx 3    swap 2      cx 1       h 0 pass/fail
0   0.157738  0.823010  0.601428  0.522489  0.406576  0.387069      fail
1   0.150568  0.836896  0.621953  0.521354  0.415242  0.395157      fail
2   0.182188  0.835469  0.623584  0.585622  0.462831  0.442409      fail
3   0.173512  0.876228  0.612366  0.534926  0.410834  0.388296      fail
4   0.195739  0.894762  0.687587  0.608917  0.489033  0.464888      fail
5   0.173512  0.891797  0.657028  0.579835  0.454065  0.434362      fail
6   0.179427  0.854834  0.636264  0.543845  0.433669  0.412086      fail
7   0.165625  0.880035  0.658790  0.612420  0.491801  0.473273      fail
8   0.187228  0.823590  0.609978  0.536658  0.424989  0.405916      fail
9   0.180682  0.888548  0.629719  0.561444  0.433884  0.413972      fail
10  0.176667  0.872682  0.649507  0.551075  0.435474  0.409312      pass
11  0.189286  0.877121  0.633047  0.563325  0.438934  0.416120      pass
12  0.139474  0.817085  0.625812  0.563563  0.459652  0.442937      pass
13  0.186328  0.848975  0.654085  0.526723  0.420533  0.401039      pass
14  0.189286  0.898307  0.676652  0.576863  0.463165  0.444734      pass
15  0.165625  0.834531  0.617332  0.519758  0.409303  0.387097      pass
16  0.172826  0.880808  0.638635  0.576331  0.450726  0.429817      pass
17  0.198750  0.897246  0.667888  0.510189  0.402176  0.385052      pass
18  0.165625  0.852610  0.612709  0.496502  0.377604  0.357257      pass
19  0.172250  0.852703  0.629271  0.578862  0.457478  0.436484      pass

BARINEL SCORES

       swap 2       h 0      cx 1     cx 4      cx 5      cx 3
sum  0.506518  0.506459  0.506173  0.49922  0.498587  0.497401

TARANTULA SCORES

       swap 2       h 0      cx 1     cx 4      cx 5      cx 3
sum  0.506518  0.506459  0.506173  0.49922  0.498587  0.497401

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_cswap_inGap_3_.qasm

100%|██████████| 10/10 [00:02<00:00,  4.22it/s]
100%|██████████| 10/10 [00:02<00:00,  4.50it/s]

        cx 5      cx 4      cx 3   cswap 2      cx 1       h 0 pass/fail
0   0.189286  0.892690  0.660865  0.580558  0.438571  0.422287      fail
1   0.201630  0.910870  0.668625  0.587069  0.439325  0.425454      fail
2   0.180682  0.858825  0.639465  0.566261  0.424458  0.408771      fail
3   0.189286  0.855934  0.609024  0.536998  0.403874  0.391073      fail
4   0.139474  0.793668  0.581853  0.499126  0.376263  0.369628      fail
5   0.189286  0.861551  0.615702  0.532209  0.397769  0.385127      fail
6   0.220833  0.926042  0.662823  0.578166  0.436284  0.419644      fail
7   0.179427  0.854834  0.650045  0.584960  0.442783  0.431087      fail
8   0.150568  0.862482  0.632835  0.566679  0.423960  0.407896      fail
9   0.184028  0.849805  0.608666  0.534937  0.399697  0.385390      fail
10  0.147222  0.799783  0.593057  0.525815  0.395732  0.381572      pass
11  0.198750  0.909043  0.674939  0.603345  0.456065  0.441290      pass
12  0.165625  0.837749  0.623270  0.558317  0.425584  0.415038      pass
13  0.174342  0.836266  0.577551  0.508065  0.378416  0.368125      pass
14  0.149063  0.845391  0.644642  0.584217  0.443887  0.432996      pass
15  0.189286  0.824795  0.575427  0.510379  0.382461  0.371061      pass
16  0.144922  0.791016  0.619606  0.565026  0.425690  0.410167      pass
17  0.165625  0.840430  0.610716  0.543390  0.413422  0.399677      pass
18  0.158424  0.836175  0.601853  0.537862  0.405341  0.392486      pass
19  0.233824  0.875666  0.648099  0.572495  0.423323  0.411084      pass

BARINEL SCORES

         cx 5      cx 4     cx 3   cswap 2      cx 1       h 0
sum  0.513715  0.507923  0.50643  0.502621  0.501984  0.501416

TARANTULA SCORES

         cx 5      cx 4     cx 3   cswap 2      cx 1       h 0
sum  0.513715  0.507923  0.50643  0.502621  0.501984  0.501416

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_sx_inGap_3_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.12it/s]
100%|██████████| 10/10 [00:00<00:00, 10.48it/s]

        cx 5      cx 4      cx 3      cx 2       h 1    sxdg 0 pass/fail
0   0.174342  0.883100  0.670093  0.469140  0.434381  0.588565      fail
1   0.220833  0.925614  0.709812  0.506299  0.476932  0.645013      fail
2   0.173512  0.839472  0.646726  0.465321  0.436462  0.586586      fail
3   0.139474  0.759252  0.580354  0.433427  0.415627  0.533897      fail
4   0.172826  0.842120  0.634151  0.459664  0.434695  0.564338      fail
5   0.165625  0.893058  0.673911  0.474187  0.446281  0.596198      fail
6   0.147222  0.799783  0.587767  0.439273  0.416216  0.537847      fail
7   0.149063  0.922578  0.690248  0.491577  0.463395  0.622934      fail
8   0.157738  0.817392  0.621323  0.434429  0.410790  0.534344      fail
9   0.182188  0.835469  0.634243  0.473282  0.451261  0.592577      fail
10  0.205060  0.893583  0.663268  0.477832  0.451307  0.593916      pass
11  0.149063  0.811348  0.591807  0.427766  0.404629  0.511740      pass
12  0.202431  0.870508  0.626310  0.460691  0.430042  0.547132      pass
13  0.174342  0.859683  0.608726  0.438110  0.417227  0.517679      pass
14  0.209211  0.931908  0.696411  0.499286  0.470006  0.621646      pass
15  0.165625  0.830599  0.634277  0.461855  0.442194  0.575436      pass
16  0.136397  0.817808  0.605367  0.438863  0.417905  0.534061      pass
17  0.173512  0.866276  0.625925  0.445507  0.416782  0.520284      pass
18  0.139474  0.817085  0.599468  0.402772  0.377210  0.489506      pass
19  0.191776  0.890296  0.627520  0.444797  0.419474  0.526544      pass

BARINEL SCORES

       sxdg 0      cx 2       h 1      cx 3      cx 4     cx 5
sum  0.516208  0.508154  0.508066  0.506661  0.497917  0.49066

TARANTULA SCORES

       sxdg 0      cx 2       h 1      cx 3      cx 4     cx 5
sum  0.516208  0.508154  0.508066  0.506661  0.497917  0.49066

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_rx_inGap_9_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.25it/s]
100%|██████████| 10/10 [00:00<00:00, 11.41it/s]

        rx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.173684  1.052961  0.769182  0.673831  0.492497  0.464475      fail
1   0.171429  1.027679  0.725223  0.652050  0.488431  0.459095      fail
2   0.171429  1.055357  0.749981  0.663074  0.493975  0.469883      fail
3   0.141176  1.103309  0.804021  0.663304  0.476243  0.455640      fail
4   0.177273  1.009659  0.724077  0.647863  0.487582  0.462349      fail
5   0.142857  1.093750  0.827102  0.717603  0.526217  0.499504      fail
6   0.165000  0.989375  0.765625  0.687765  0.519071  0.496684      fail
7   0.142105  1.080592  0.769634  0.644152  0.473999  0.450902      fail
8   0.173684  1.058224  0.809581  0.723272  0.517711  0.485591      fail
9   0.142857  1.047917  0.758389  0.637778  0.464538  0.444924      fail
10  0.150000  1.053125  0.782188  0.664301  0.483268  0.457433      pass
11  0.136364  1.060511  0.746058  0.637231  0.461476  0.430739      pass
12  0.166667  1.135417  0.814974  0.699718  0.494515  0.465012      pass
13  0.150000  1.028977  0.747692  0.647927  0.459412  0.430956      pass
14  0.166667  1.065278  0.775022  0.679818  0.492309  0.468591      pass
15  0.135000  1.082813  0.813047  0.697291  0.498762  0.466877      pass
16  0.110526  1.087171  0.807422  0.681277  0.482763  0.448302      pass
17  0.142857  1.098512  0.818973  0.685410  0.492429  0.457404      pass
18  0.150000  1.058125  0.769629  0.637191  0.485077  0.460424      pass
19  0.180000  1.065938  0.783184  0.690054  0.500427  0.469671      pass

BARINEL SCORES

         rx 5       h 0      cx 1      cx 2      cx 3      cx 4
sum  0.518354  0.507228  0.504587  0.499645  0.495008  0.494894

TARANTULA SCORES

         rx 5       h 0      cx 1      cx 2      cx 3      cx 4
sum  0.518354  0.507228  0.504587  0.499645  0.495008  0.494894

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rx_inGap_7_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.34it/s]
100%|██████████| 10/10 [00:00<00:00, 10.90it/s]

        rx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.327273  1.179545  0.850799  0.633786  0.457483  0.430022      fail
1   0.533333  1.227976  0.918397  0.676449  0.468932  0.434531      fail
2   0.457143  1.192857  0.897452  0.615116  0.447092  0.413971      fail
3   0.363636  1.169886  0.876847  0.634748  0.434751  0.402073      fail
4   0.400000  1.144375  0.818945  0.588169  0.440853  0.414239      fail
5   0.400000  1.173438  0.877539  0.664180  0.484552  0.450702      fail
6   0.355556  1.201389  0.899436  0.647559  0.472513  0.453814      fail
7   0.472727  1.140909  0.833683  0.609726  0.431926  0.399475      fail
8   0.400000  1.115313  0.798477  0.609072  0.432390  0.402659      fail
9   0.509091  1.184091  0.879616  0.627790  0.436093  0.404813      fail
10  0.355556  1.201389  0.941797  0.653079  0.477778  0.445377      pass
11  0.421053  1.160197  0.897266  0.660756  0.480101  0.444546      pass
12  0.336842  1.213158  0.938754  0.680000  0.492592  0.460718      pass
13  0.400000  1.189583  0.931272  0.642866  0.449746  0.410066      pass
14  0.382609  1.171739  0.868920  0.606968  0.423275  0.389660      pass
15  0.363636  1.169886  0.842188  0.615066  0.436552  0.403212      pass
16  0.480000  1.181250  0.879063  0.601299  0.446031  0.417950      pass
17  0.355556  1.201389  0.984158  0.701378  0.486028  0.448375      pass
18  0.347826  1.206250  0.928108  0.666303  0.488626  0.460883      pass
19  0.336842  1.182566  0.897142  0.662372  0.476973  0.439240      pass

BARINEL SCORES

         rx 5      cx 4       h 0     cx 2      cx 1     cx 3
sum  0.527432  0.496873  0.493331  0.49283  0.491755  0.48712

TARANTULA SCORES

         rx 5      cx 4       h 0     cx 2      cx 1     cx 3
sum  0.527432  0.496873  0.493331  0.49283  0.491755  0.48712

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_cx_inGap_7_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.26it/s]
100%|██████████| 10/10 [00:00<00:00, 10.27it/s]

        cx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.173512  0.837742  0.690004  0.487870  0.370240  0.349834      fail
1   0.173512  0.877958  0.702309  0.527776  0.389940  0.370280      fail
2   0.165625  0.830898  0.708201  0.524386  0.389950  0.366815      fail
3   0.205060  0.900930  0.716811  0.518821  0.362557  0.340252      fail
4   0.191776  0.875966  0.734534  0.519089  0.377520  0.360570      fail
5   0.189286  0.877121  0.713996  0.528642  0.372160  0.351083      fail
6   0.165625  0.821236  0.670775  0.519933  0.385134  0.363200      fail
7   0.179427  0.818132  0.694638  0.511353  0.372887  0.349124      fail
8   0.195739  0.911275  0.736793  0.535170  0.394964  0.372960      fail
9   0.215312  0.870488  0.757936  0.547458  0.399228  0.378555      fail
10  0.165625  0.836097  0.690990  0.509137  0.373727  0.352287      pass
11  0.132500  0.783613  0.616948  0.461293  0.347534  0.333327      pass
12  0.191776  0.875966  0.734534  0.508181  0.371510  0.355222      pass
13  0.198750  0.897246  0.736348  0.571342  0.403372  0.377671      pass
14  0.150568  0.813370  0.688303  0.517874  0.378621  0.356999      pass
15  0.165625  0.835135  0.694177  0.492328  0.370753  0.354220      pass
16  0.165625  0.873125  0.721121  0.544370  0.393025  0.368972      pass
17  0.165625  0.856777  0.698884  0.504810  0.374464  0.352410      pass
18  0.165625  0.835135  0.694177  0.496896  0.361230  0.340578      pass
19  0.141964  0.830339  0.696680  0.508392  0.376549  0.356769      pass

BARINEL SCORES

         cx 5      cx 3      cx 4      cx 2      cx 1       h 0
sum  0.530182  0.505456  0.505421  0.505122  0.504216  0.503791

TARANTULA SCORES

         cx 5      cx 3      cx 4      cx 2      cx 1       h 0
sum  0.530182  0.505456  0.505421  0.505122  0.504216  0.503791

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_x_inGap_2_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.35it/s]
100%|██████████| 10/10 [00:00<00:00, 10.68it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       x 0 pass/fail
0   0.172826  0.842120  0.623590  0.467298  0.438924  0.599368      fail
1   0.156908  0.852488  0.647807  0.474701  0.447476  0.612679      fail
2   0.165625  0.843111  0.641661  0.481592  0.452838  0.623505      fail
3   0.165625  0.857972  0.653517  0.472106  0.442108  0.596486      fail
4   0.173512  0.833854  0.630940  0.465399  0.441956  0.594902      fail
5   0.165625  0.824082  0.587793  0.430612  0.406943  0.550760      fail
6   0.195739  0.894762  0.642112  0.489937  0.467637  0.653509      fail
7   0.179427  0.868457  0.623230  0.462458  0.435688  0.586728      fail
8   0.184028  0.862912  0.653248  0.486033  0.456379  0.628627      fail
9   0.151823  0.834733  0.599662  0.443578  0.418839  0.569366      fail
10  0.175368  0.846186  0.648353  0.450838  0.416921  0.548642      pass
11  0.165625  0.824082  0.592185  0.430329  0.403507  0.541682      pass
12  0.194853  0.885754  0.694596  0.510048  0.481283  0.660505      pass
13  0.198750  0.903145  0.653560  0.461455  0.431077  0.569362      pass
14  0.156908  0.818072  0.602945  0.447735  0.418715  0.578450      pass
15  0.175368  0.877711  0.632274  0.433305  0.400182  0.509221      pass
16  0.182188  0.819121  0.604666  0.438158  0.411246  0.547910      pass
17  0.202431  0.925000  0.671021  0.495915  0.467260  0.637893      pass
18  0.202431  0.906836  0.672038  0.467587  0.442961  0.573518      pass
19  0.138021  0.783252  0.583291  0.439810  0.418633  0.571619      pass

BARINEL SCORES

          x 0       h 1      cx 2      cx 3      cx 4      cx 5
sum  0.511788  0.506724  0.505327  0.497971  0.497817  0.488467

TARANTULA SCORES

          x 0       h 1      cx 2      cx 3      cx 4      cx 5
sum  0.511788  0.506724  0.505327  0.497971  0.497817  0.488467

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_sx_inGap_8_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.22it/s]
100%|██████████| 10/10 [00:00<00:00, 11.87it/s]

      sxdg 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.472727  1.067045  0.943786  0.713016  0.503149  0.474943      fail
1   0.417391  1.104076  0.994429  0.739382  0.522912  0.488108      fail
2   0.400000  1.050347  0.881120  0.623319  0.457910  0.430859      fail
3   0.380952  1.093750  0.952065  0.727550  0.536859  0.505782      fail
4   0.440000  1.042500  0.935391  0.715758  0.528318  0.492732      fail
5   0.400000  1.033073  0.884928  0.668355  0.478258  0.447586      fail
6   0.457143  1.083036  0.956250  0.684113  0.485495  0.449998      fail
7   0.452174  1.052989  0.929042  0.684044  0.468875  0.437223      fail
8   0.421053  1.089474  0.960711  0.695861  0.489719  0.458666      fail
9   0.380952  1.025000  0.867243  0.662817  0.461173  0.434076      fail
10  0.421053  1.094737  0.936657  0.672763  0.475613  0.440176      pass
11  0.466667  1.035417  0.947624  0.710728  0.504422  0.470728      pass
12  0.400000  1.089453  0.959082  0.711450  0.506472  0.471741      pass
13  0.419048  1.042560  0.905394  0.702767  0.513192  0.476796      pass
14  0.463158  1.078289  0.990892  0.765736  0.551408  0.520274      pass
15  0.355556  1.003125  0.864670  0.670516  0.478068  0.450321      pass
16  0.426667  1.099167  1.007917  0.788166  0.545998  0.504652      pass
17  0.440000  1.066563  0.975527  0.745299  0.529796  0.500248      pass
18  0.426667  1.028333  0.915625  0.700887  0.501565  0.477013      pass
19  0.480000  1.014167  0.916328  0.674329  0.482716  0.449803      pass

BARINEL SCORES

         cx 4      cx 3    sxdg 5       h 0      cx 1      cx 2
sum  0.502111  0.496936  0.495516  0.492444  0.492188  0.491875

TARANTULA SCORES

         cx 4      cx 3    sxdg 5       h 0      cx 1      cx 2
sum  0.502111  0.496936  0.495516  0.492444  0.492188  0.491875

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_y_inGap_7_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.85it/s]
100%|██████████| 10/10 [00:00<00:00, 12.84it/s]

         y 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.272727  1.160795  0.838601  0.634919  0.454926  0.429633      fail
1   0.275000  1.221563  0.898184  0.681482  0.497991  0.469822      fail
2   0.289474  1.088487  0.793668  0.574125  0.407254  0.386869      fail
3   0.304348  1.172283  0.885581  0.653100  0.461309  0.432970      fail
4   0.225000  1.134375  0.901270  0.681566  0.483870  0.455219      fail
5   0.200000  1.134375  0.884922  0.650134  0.461296  0.436782      fail
6   0.309524  1.120536  0.832961  0.626751  0.456291  0.428309      fail
7   0.315789  1.119079  0.811863  0.588601  0.418588  0.391341      fail
8   0.272727  1.187216  0.909624  0.639575  0.472216  0.442451      fail
9   0.289474  1.088487  0.793668  0.601212  0.428892  0.403370      fail
10  0.285714  1.120536  0.854148  0.618182  0.443377  0.422198      pass
11  0.261905  1.175893  0.877121  0.645637  0.459075  0.430434      pass
12  0.194444  1.134375  0.868424  0.666452  0.488671  0.465495      pass
13  0.236842  1.088487  0.840502  0.578422  0.425736  0.399461      pass
14  0.295455  1.107955  0.816673  0.575628  0.426868  0.409163      pass
15  0.261905  1.148214  0.876228  0.647417  0.475295  0.448905      pass
16  0.166667  1.166667  0.894184  0.687066  0.483698  0.452131      pass
17  0.289474  1.149671  0.876891  0.617009  0.441097  0.413464      pass
18  0.225000  1.163438  0.863613  0.602480  0.424420  0.396796      pass
19  0.294118  1.117279  0.811972  0.617844  0.435037  0.411263      pass

BARINEL SCORES

          y 5      cx 2      cx 1      h 0      cx 4      cx 3
sum  0.523031  0.502992  0.502176  0.50161  0.501199  0.499141

TARANTULA SCORES

          y 5      cx 2      cx 1      h 0      cx 4      cx 3
sum  0.523031  0.502992  0.502176  0.50161  0.501199  0.499141

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_cx_inGap_9_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.13it/s]
100%|██████████| 10/10 [00:01<00:00,  9.83it/s]

        cx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.172826  0.870550  0.636681  0.457617  0.366833  0.344593      fail
1   0.157738  0.823010  0.637170  0.466569  0.378423  0.359059      fail
2   0.202431  0.937609  0.699874  0.512087  0.433283  0.409946      fail
3   0.210795  0.925337  0.683696  0.501130  0.399798  0.374271      fail
4   0.165625  0.866309  0.642365  0.487610  0.390160  0.372063      fail
5   0.173512  0.862388  0.644693  0.458621  0.393364  0.366165      fail
6   0.149063  0.824961  0.623226  0.444096  0.358286  0.330176      fail
7   0.191776  0.930448  0.728991  0.545881  0.428329  0.404558      fail
8   0.139474  0.844326  0.615311  0.448459  0.358990  0.340489      fail
9   0.165625  0.866309  0.635929  0.470471  0.363163  0.344520      fail
10  0.156908  0.897882  0.676534  0.501365  0.400097  0.376408      pass
11  0.191776  0.885999  0.669595  0.470143  0.410148  0.384357      pass
12  0.182188  0.855898  0.624998  0.449917  0.336225  0.319573      pass
13  0.150568  0.845561  0.627945  0.448831  0.356553  0.337409      pass
14  0.157738  0.813932  0.568626  0.436271  0.342855  0.320322      pass
15  0.139474  0.789844  0.568923  0.421338  0.316718  0.304868      pass
16  0.157738  0.854148  0.604318  0.458137  0.361213  0.342674      pass
17  0.155882  0.838143  0.633232  0.484725  0.348428  0.334555      pass
18  0.149063  0.799082  0.614064  0.429002  0.370827  0.346508      pass
19  0.173512  0.813095  0.619215  0.460481  0.365620  0.343950      pass

BARINEL SCORES

         cx 1     cx 5       h 0      cx 3      cx 2      cx 4
sum  0.517511  0.51705  0.516667  0.513347  0.512421  0.510431

TARANTULA SCORES

         cx 1     cx 5       h 0      cx 3      cx 2      cx 4
sum  0.517511  0.51705  0.516667  0.513347  0.512421  0.510431

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_ry_inGap_9_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.64it/s]
100%|██████████| 10/10 [00:00<00:00, 12.06it/s]

        ry 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.171429  1.004762  0.768155  0.752706  0.467994  0.435515      fail
1   0.171429  1.032440  0.784617  0.815387  0.516344  0.487709      fail
2   0.163636  1.050284  0.752610  0.710327  0.455824  0.425246      fail
3   0.214286  1.006845  0.732868  0.825771  0.524731  0.497569      fail
4   0.180000  1.036875  0.744863  0.752570  0.464001  0.430742      fail
5   0.200000  0.967014  0.694683  0.730789  0.446154  0.417196      fail
6   0.163636  1.050284  0.778196  0.719933  0.452048  0.421076      fail
7   0.156522  1.062228  0.792578  0.755820  0.482476  0.452736      fail
8   0.157143  1.055952  0.777846  0.778992  0.485279  0.449980      fail
9   0.130435  1.072011  0.776053  0.751870  0.487050  0.453599      fail
10  0.142105  1.105921  0.798787  0.769401  0.493750  0.459028      pass
11  0.142105  1.070066  0.742599  0.707495  0.454193  0.423442      pass
12  0.128571  1.053274  0.756808  0.690208  0.458697  0.432121      pass
13  0.171429  1.060119  0.801079  0.780828  0.494974  0.460556      pass
14  0.157895  1.008224  0.701933  0.661295  0.426134  0.402131      pass
15  0.157895  1.013487  0.757134  0.712073  0.454760  0.427440      pass
16  0.177273  1.062500  0.773171  0.803365  0.504596  0.471774      pass
17  0.136364  1.113352  0.817933  0.740404  0.484087  0.458060      pass
18  0.157895  1.013487  0.733717  0.730899  0.482274  0.454464      pass
19  0.142105  1.100658  0.806497  0.796650  0.520875  0.496409      pass

BARINEL SCORES

        ry 5      cx 2      cx 1       h 0      cx 3      cx 4
sum  0.53024  0.506724  0.500396  0.499215  0.497149  0.493735

TARANTULA SCORES

        ry 5      cx 2      cx 1       h 0      cx 3      cx 4
sum  0.53024  0.506724  0.500396  0.499215  0.497149  0.493735

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_cx_inGap_8_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.62it/s]
100%|██████████| 10/10 [00:01<00:00,  9.99it/s]

        cx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.172250  0.892656  0.657122  0.523921  0.385099  0.362734      fail
1   0.239236  0.953819  0.708407  0.596100  0.424918  0.397083      fail
2   0.141964  0.839416  0.620889  0.506892  0.363640  0.345792      fail
3   0.191776  0.858758  0.650060  0.519793  0.381464  0.358030      fail
4   0.180682  0.835298  0.643172  0.499463  0.370908  0.351106      fail
5   0.191776  0.848725  0.633442  0.503530  0.369885  0.351902      fail
6   0.182188  0.872246  0.647234  0.543343  0.393087  0.368265      fail
7   0.180682  0.820437  0.613114  0.505470  0.371025  0.348696      fail
8   0.195739  0.902610  0.679129  0.516480  0.362232  0.342059      fail
9   0.173512  0.813095  0.616055  0.493701  0.358376  0.339296      fail
10  0.172826  0.856335  0.653184  0.489087  0.368229  0.347066      pass
11  0.149063  0.780020  0.562371  0.452432  0.315836  0.292890      pass
12  0.179427  0.874886  0.663004  0.533804  0.392267  0.369568      pass
13  0.136397  0.819945  0.619092  0.490878  0.349849  0.331409      pass
14  0.202431  0.901280  0.667430  0.569954  0.407923  0.383736      pass
15  0.149063  0.831777  0.600562  0.486542  0.364297  0.344296      pass
16  0.179427  0.888509  0.629561  0.512040  0.361936  0.340266      pass
17  0.149063  0.867188  0.612640  0.528054  0.373084  0.352358      pass
18  0.180682  0.897212  0.652277  0.552669  0.400984  0.376143      pass
19  0.202431  0.880100  0.619017  0.546577  0.393923  0.374151      pass

BARINEL SCORES

         cx 5      cx 3      h 0      cx 1      cx 2      cx 4
sum  0.520982  0.507432  0.50375  0.503483  0.502249  0.501155

TARANTULA SCORES

         cx 5      cx 3      h 0      cx 1      cx 2      cx 4
sum  0.520982  0.507432  0.50375  0.503483  0.502249  0.501155

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_h_inGap_9_.qasm

100%|██████████| 10/10 [00:00<00:00, 12.00it/s]
100%|██████████| 10/10 [00:00<00:00, 12.77it/s]

         h 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.157895  1.058882  0.804400  0.795934  0.494520  0.457704      fail
1   0.137500  1.082031  0.849528  0.830087  0.541674  0.507489      fail
2   0.210000  1.025625  0.728613  0.731633  0.430344  0.401996      fail
3   0.157143  1.037798  0.769122  0.733432  0.474271  0.444549      fail
4   0.183333  1.043403  0.764800  0.798294  0.516621  0.491983      fail
5   0.141176  1.103309  0.840602  0.780676  0.492382  0.458844      fail
6   0.157143  1.055952  0.804650  0.817227  0.519766  0.488943      fail
7   0.173684  1.052961  0.779626  0.812763  0.516023  0.489762      fail
8   0.171429  1.050595  0.748158  0.714714  0.432793  0.403838      fail
9   0.165000  1.071562  0.768125  0.752521  0.485276  0.453958      fail
10  0.150000  1.083203  0.824951  0.818898  0.541066  0.512361      pass
11  0.126316  1.162500  0.856332  0.797167  0.517947  0.481139      pass
12  0.126316  1.086513  0.771690  0.722041  0.490325  0.462236      pass
13  0.114286  1.063393  0.804148  0.722449  0.471408  0.442799      pass
14  0.128571  1.007440  0.771187  0.718459  0.480458  0.459366      pass
15  0.173684  0.997039  0.707586  0.723434  0.463958  0.436440      pass
16  0.135000  1.087812  0.820859  0.756621  0.496128  0.467520      pass
17  0.120000  1.016250  0.710469  0.650442  0.437036  0.409584      pass
18  0.133333  1.083333  0.798329  0.746288  0.478886  0.447532      pass
19  0.171429  1.055357  0.801935  0.802645  0.505019  0.476428      pass

BARINEL SCORES

          h 5      cx 2      cx 1       h 0      cx 3     cx 4
sum  0.545392  0.510142  0.501095  0.500199  0.499686  0.49857

TARANTULA SCORES

          h 5      cx 2      cx 1       h 0      cx 3     cx 4
sum  0.545392  0.510142  0.501095  0.500199  0.499686  0.49857

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_h_inGap_6_.qasm

100%|██████████| 10/10 [00:00<00:00, 16.71it/s]
100%|██████████| 10/10 [00:00<00:00, 17.78it/s]

         h 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.189474  0.772697  0.543257  0.417677  0.320473  0.304688      fail
1   0.180000  0.776250  0.569707  0.452175  0.338079  0.318668      fail
2   0.163636  0.782386  0.603089  0.420786  0.304050  0.287703      fail
3   0.177273  0.777273  0.582795  0.412227  0.288084  0.272502      fail
4   0.163636  0.782386  0.605646  0.409500  0.305760  0.288597      fail
5   0.180000  0.776250  0.586055  0.428357  0.319477  0.302355      fail
6   0.165000  0.781875  0.602754  0.405385  0.296149  0.280405      fail
7   0.195000  0.770625  0.577266  0.446353  0.314347  0.294623      fail
8   0.180000  0.776250  0.602402  0.463107  0.335373  0.313524      fail
9   0.163636  0.782386  0.573366  0.411947  0.313101  0.293255      fail
10  0.142105  0.790461  0.647615  0.481456  0.355893  0.337368      pass
11  0.163636  0.782386  0.603089  0.438125  0.328690  0.312446      pass
12  0.171429  0.779464  0.590960  0.413588  0.304286  0.283139      pass
13  0.142105  0.790461  0.584704  0.453261  0.319816  0.296173      pass
14  0.133333  0.793750  0.597461  0.475916  0.339348  0.319992      pass
15  0.173684  0.778618  0.578043  0.419759  0.319141  0.302902      pass
16  0.150000  0.787500  0.612109  0.436914  0.326463  0.309114      pass
17  0.142857  0.790179  0.586775  0.433677  0.311107  0.293814      pass
18  0.173684  0.778618  0.563795  0.404470  0.289441  0.272300      pass
19  0.094737  0.808224  0.600617  0.452105  0.339071  0.323447      pass

BARINEL SCORES

          h 5      cx 4     cx 3      cx 1       h 0      cx 2
sum  0.541613  0.496766  0.49497  0.492277  0.492145  0.491831

TARANTULA SCORES

          h 5      cx 4     cx 3      cx 1       h 0      cx 2
sum  0.541613  0.496766  0.49497  0.492277  0.492145  0.491831

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_x_inGap_7_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.69it/s]
100%|██████████| 10/10 [00:00<00:00, 12.59it/s]

         x 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.285714  1.148214  0.855041  0.651060  0.465783  0.436296      fail
1   0.275000  1.163438  0.857715  0.620127  0.475890  0.452251      fail
2   0.342105  1.210855  0.953906  0.685864  0.495086  0.464222      fail
3   0.295455  1.134375  0.852610  0.612373  0.437908  0.410772      fail
4   0.300000  1.163438  0.874062  0.608510  0.423021  0.396282      fail
5   0.250000  1.198958  0.863954  0.631604  0.448787  0.426832      fail
6   0.325000  1.134375  0.812285  0.588083  0.430425  0.410417      fail
7   0.272727  1.187216  0.874538  0.641597  0.457782  0.433415      fail
8   0.250000  1.134375  0.822887  0.637489  0.464214  0.440670      fail
9   0.282609  1.121739  0.836175  0.605352  0.441171  0.419997      fail
10  0.225000  1.163438  0.863613  0.646993  0.474991  0.444346      pass
11  0.275000  1.105313  0.855840  0.619767  0.456637  0.435299      pass
12  0.261905  1.203571  0.914769  0.647707  0.470244  0.438945      pass
13  0.210526  1.149671  0.865892  0.656366  0.500746  0.472094      pass
14  0.147059  1.185662  0.945037  0.691637  0.483343  0.453154      pass
15  0.263158  1.180263  0.860670  0.658238  0.478033  0.447485      pass
16  0.289474  1.241447  0.920477  0.711026  0.520882  0.489985      pass
17  0.200000  1.134375  0.846328  0.646091  0.471604  0.441694      pass
18  0.285714  1.120536  0.817392  0.605222  0.432065  0.407942      pass
19  0.250000  1.231250  0.907878  0.686732  0.493951  0.462661      pass

BARINEL SCORES

          x 5      cx 4      cx 3      cx 2       h 0      cx 1
sum  0.544527  0.497458  0.494405  0.488806  0.488477  0.486998

TARANTULA SCORES

          x 5      cx 4      cx 3      cx 2       h 0      cx 1
sum  0.544527  0.497458  0.494405  0.488806  0.488477  0.486998

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_ry_inGap_10_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.53it/s]
100%|██████████| 10/10 [00:00<00:00, 12.65it/s]

        ry 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.272727  1.134375  0.857972  0.603714  0.458475  0.436132      fail
1   0.285714  1.148214  0.845089  0.634144  0.479725  0.454479      fail
2   0.238095  1.065179  0.815606  0.594407  0.452196  0.432597      fail
3   0.261905  1.175893  0.882738  0.648483  0.482884  0.459844      fail
4   0.275000  1.221563  0.881836  0.672465  0.494253  0.465211      fail
5   0.285714  1.175893  0.840365  0.611330  0.447759  0.420112      fail
6   0.261905  1.175893  0.840365  0.592772  0.453072  0.430723      fail
7   0.260870  1.121739  0.816831  0.609357  0.454596  0.430908      fail
8   0.295455  1.160795  0.908771  0.675708  0.481526  0.450612      fail
9   0.275000  1.279688  0.938652  0.689128  0.494808  0.462856      fail
10  0.238095  1.148214  0.855041  0.655986  0.468295  0.443554      pass
11  0.294118  1.083088  0.772403  0.573807  0.408961  0.387856      pass
12  0.214286  1.120536  0.854148  0.606615  0.429728  0.410594      pass
13  0.294118  1.117279  0.909720  0.668928  0.493185  0.459302      pass
14  0.200000  1.192500  0.880898  0.671384  0.493410  0.468742      pass
15  0.263158  1.180263  0.843462  0.625585  0.445679  0.418005      pass
16  0.285714  1.175893  0.877121  0.648797  0.467518  0.436030      pass
17  0.236842  1.088487  0.840502  0.605897  0.455228  0.434238      pass
18  0.194444  1.231250  0.932595  0.699205  0.501541  0.473196      pass
19  0.194444  1.166667  0.874523  0.641573  0.474797  0.452328      pass

BARINEL SCORES

         ry 5       h 0      cx 4      cx 1      cx 3      cx 2
sum  0.528977  0.503378  0.503347  0.503264  0.499647  0.497397

TARANTULA SCORES

         ry 5       h 0      cx 4      cx 1      cx 3      cx 2
sum  0.528977  0.503378  0.503347  0.503264  0.499647  0.497397

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_ccx_inGap_10_.qasm

100%|██████████| 10/10 [00:02<00:00,  3.87it/s]
100%|██████████| 10/10 [00:02<00:00,  3.65it/s]

       ccx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.232812  0.772363  0.627018  0.519851  0.426406  0.404480      fail
1   0.229416  0.790890  0.665137  0.545521  0.450458  0.428259      fail
2   0.234062  0.794918  0.674287  0.550944  0.456036  0.432567      fail
3   0.229539  0.810570  0.672307  0.544233  0.454277  0.431848      fail
4   0.228125  0.804814  0.642156  0.540858  0.456163  0.436137      fail
5   0.233364  0.724428  0.590631  0.494255  0.402421  0.381694      fail
6   0.232366  0.770408  0.622954  0.500698  0.431309  0.412296      fail
7   0.238021  0.722863  0.599889  0.496561  0.399882  0.376000      fail
8   0.232366  0.776608  0.632025  0.511183  0.420393  0.398837      fail
9   0.235193  0.742646  0.568987  0.470952  0.389481  0.368635      fail
10  0.228125  0.812778  0.663320  0.536129  0.445982  0.424383      pass
11  0.222187  0.831469  0.645700  0.534984  0.460107  0.441839      pass
12  0.223884  0.827975  0.628823  0.501612  0.421180  0.402019      pass
13  0.226562  0.816093  0.671230  0.551646  0.462701  0.440040      pass
14  0.219219  0.843861  0.663330  0.552881  0.462410  0.442958      pass
15  0.231424  0.773155  0.622892  0.513735  0.431176  0.409941      pass
16  0.231094  0.800801  0.631823  0.523243  0.437862  0.416875      pass
17  0.223884  0.842155  0.687678  0.545708  0.461699  0.441247      pass
18  0.226711  0.765653  0.613293  0.495613  0.426266  0.407761      pass
19  0.232366  0.740268  0.572184  0.476085  0.386116  0.365188      pass

BARINEL SCORES

        ccx 5      cx 2      cx 3      cx 1       h 0      cx 4
sum  0.506514  0.497282  0.495869  0.493742  0.492648  0.489099

TARANTULA SCORES

        ccx 5      cx 2      cx 3      cx 1       h 0      cx 4
sum  0.506514  0.497282  0.495869  0.493742  0.492648  0.489099

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_ccx_inGap_4_.qasm

100%|██████████| 10/10 [00:02<00:00,  4.77it/s]
100%|██████████| 10/10 [00:01<00:00,  5.34it/s]

        cx 5      cx 4     ccx 3      cx 2      cx 1       h 0 pass/fail
0   0.182188  0.918555  0.706358  0.539814  0.390616  0.363421      fail
1   0.180682  0.879048  0.692031  0.519593  0.379331  0.360328      fail
2   0.191776  0.884087  0.700640  0.513605  0.375228  0.355490      fail
3   0.165625  0.886589  0.685220  0.515573  0.368199  0.346811      fail
4   0.165625  0.856777  0.676918  0.493064  0.358986  0.340197      fail
5   0.179427  0.868457  0.689510  0.523293  0.386704  0.364016      fail
6   0.195739  0.909624  0.712265  0.540179  0.394565  0.371019      fail
7   0.165625  0.893058  0.688043  0.518628  0.371155  0.348143      fail
8   0.205060  0.914769  0.719304  0.538103  0.395495  0.375596      fail
9   0.165625  0.917617  0.696015  0.520857  0.374541  0.354033      fail
10  0.174342  0.819058  0.669651  0.498394  0.365102  0.342270      pass
11  0.156908  0.800863  0.652492  0.480190  0.352851  0.336072      pass
12  0.155882  0.876608  0.678714  0.506972  0.374485  0.353141      pass
13  0.156908  0.800863  0.652492  0.482596  0.352258  0.331880      pass
14  0.198750  0.875000  0.703563  0.530758  0.385576  0.362686      pass
15  0.149063  0.839492  0.660617  0.494329  0.365708  0.344717      pass
16  0.173512  0.833854  0.675158  0.501202  0.367865  0.351095      pass
17  0.191776  0.907504  0.707556  0.539553  0.386663  0.365075      pass
18  0.147222  0.860829  0.666427  0.497756  0.348378  0.328866      pass
19  0.132500  0.761367  0.625220  0.467756  0.343404  0.322909      pass

BARINEL SCORES

         cx 5      cx 4      cx 2      cx 1     ccx 3       h 0
sum  0.523369  0.515983  0.510918  0.510255  0.510046  0.509999

TARANTULA SCORES

         cx 5      cx 4      cx 2      cx 1     ccx 3       h 0
sum  0.523369  0.515983  0.510918  0.510255  0.510046  0.509999

ERROR GATE LOCATION:
3

,Program,path_to_mutant,exam_score
0,AddGate_ccx_inGap_4_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.714286
1,AddGate_ccx_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.142857
2,AddGate_ry_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.142857
3,AddGate_x_inGap_7_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.142857
4,AddGate_h_inGap_6_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.142857
...,...,...,...
84,AddGate_x_inGap_9_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.142857
85,AddGate_cx_inGap_3_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.857143
86,AddGate_x_inGap_4_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.142857
87,AddGate_y_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.142857
88,AddGate_y_inGap_9_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.142857

,Program,path_to_mutant,exam_score
0,AddGate_ccx_inGap_4_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.714286
1,AddGate_ccx_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.142857
2,AddGate_ry_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.142857
3,AddGate_x_inGap_7_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.142857
4,AddGate_h_inGap_6_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.142857
...,...,...,...
84,AddGate_x_inGap_9_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.142857
85,AddGate_cx_inGap_3_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.857143
86,AddGate_x_inGap_4_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.142857
87,AddGate_y_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.142857
88,AddGate_y_inGap_9_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.142857