<h1 style="text-align: center;">HEISENBERG-BASED FAULT LOCALIZATION (HBFL)</h1>

<h2 style="text-align: center;">Download Initial Dependencies</h2>

In [6]:
import numpy as np
import pandas as pd
import json
import math
from tqdm import tqdm
from qiskit.quantum_info import SparsePauliOp, Operator, Pauli, Clifford
import qiskit.qasm2 as q2
from qiskit import QuantumCircuit
from IPython.display import display

from heisenbergUtilities import *

In [7]:
# from qiskit_aer import AerSimulator
# simulator = AerSimulator()

# print(simulator.available_devices())

<h3>Download MQT Benchmark circuits.</h3>

We'll run this experiment on 11 different quantum circuits, including DJ, GHZ, GraphState, Grover No-Ancilla, QAOA, QFT, QGAN, QPE Exact, QPE Inexact, RealAmpRandom, and VQE.

<h3>Generate mutants.</h3>

We'll start with mutants that add an unnecessary gate, then add mutants that replace a certain gate later. Missing code in SBFL is still a more recent topic even in classical programs.

The mutants were downloaded from QMutBench, choosing specifically mutants that added a gate at any location with 0-10% survival scores

<h2 style="text-align: center;">CONTROL PANEL</h2>

In [8]:
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
#-------------------------------------------------------------------------GENERAL PARAMETERS---------------------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
ALG_NAME = "qpeinexact"
ORIGINAL_QASM = f"{ALG_NAME}_5_qubits.qasm"                                                 #| The original algorithm QASM circuit file name.                           
ORIGINAL_QASM_FOLDER = "SBFL_circuits/MQTBench/"                                            #| The folder containing the original QASM circuit file.                    
QASM_MUTANT_FOLDER = f"SBFL_circuits/QMutBenchMutants/Mutants_{ALG_NAME}_5_qubits/"         #| The folder containing all mutants related to the original QASM circuit.  
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
#-------------------------------------------------------------------------SB-QOPS PARAMETERS---------------------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
RUNS = 10                                                                                   #| Number of times SB-QOPS will run to find a failing or passing test case.            
SHOTS = 20000                                                                               #| Number of shots for SB-QOPS to use to create the compact program specification.     
EPOCH = 80                                                                                  #| Number of epochs SB-QOPS will run to navigate the search space of test cases.       
SBQOPS_TOL = 0.1                                                                            #| Tolerance value SB-QOPS uses to determine if a test case is failing or passing.     
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
#---------------------------------------------------------------------HEISENBERG SBFL PARAMETERS-----------------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
LAMBDA_WEIGHT = 1                                                                           #| The amount to adjust the "weight difference" in the heuristic           #
LAMBDA_COMP = 1                                                                             #| The amount to weigh the "composition difference" in the heuristic       #
LAMBDA_SUPPORT = 1                                                                          #| The amount to weigh the "support overlap" in the heuristic              #
LAMBDA_DIAMETER = 1                                                                         #| The amount to weigh the "diameter difference" in the heuristic          #
LAMBDA_PHASE = 1                                                                            #| The amount to weigh the "phase" in the heuristic                        #
CUSTOM_WEIGHT = 0.25                                                                        #| The amount of weight the "dstar boost" has in the custom heuristic (WIP)#
ATOL = 1e-4                                                                                 #| The tolerance value used to prune negligible magnitudes during Pauli propagation.   
MAX_TERMS = 100                                                                             #| The maximum number of terms to keep during Pauli propagation. If None, use all.     
SEARCH_STEP = 3                                                                             #| The search step size used during Pauli propagation. If None, pauli-prop uses 4.     
VERBOSE = 1                                                                                 #| A boolean value to determine if the program should print out detailed information.  
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#

Generate the linked list of all gates found in a given circuit

In [9]:
"""
LinkedListNode: A class that holds information related to a gate in a quantum circuit. 

PROPERTIES:
    - value (String): The name of the quantum gate
    - depth (int): The depth of the gate in the circuit
    - count (Int): The probability that the gate will meaningfully change the Pauli string.
    - next (LinkedListNode): The next gate in the circuit

"""

class LinkedListNode:
    def __init__(self, name="Initial", depth=0, count=0,  next=None):
        self.value = name
        self.depth = depth
        self.next = next
        self.count = count

class LinkedList:
    def __init__(self):
        self.head = None

    def append(self, name, depth):
        new_node = LinkedListNode(name, depth)
        if not self.head:
            self.head = new_node
            return
        last_node = self.head
        while last_node.next:
            last_node = last_node.next
        last_node.next = new_node

    def mark(self, depth):
        current_node = self.head
        while current_node:
            if current_node.depth == depth:
                current_node.count += 1
                return
            current_node = current_node.next

    def reset(self):
        current_node = self.head
        while current_node:
            current_node.count = 0
            current_node = current_node.next

<h3>Load correct circuit</h3>
Here we want to load the correct version of the circuit from MQT. We use this both to generate a PS_compact from/for SB-QOPS and to check results from SBFL.

In [10]:
correct_circuit = load_program(ORIGINAL_QASM, ORIGINAL_QASM_FOLDER).copy()
correct_list = LinkedList()
correct_list = construct_list(correct_list, correct_circuit, inverse=False)

<h2 style="text-align: center;"> SB-QOPS </h2>

This is where we will use SB-QOPS on a provided circuit and its mutants

For a single mutant, it took about 2 minutes to generate a 20 test suite (10 fail, 10 pass) on an RTX 4090 SUPER. It can only be run on a Linux environment since the AER Simulator does not support Windows

Expect this cell to take up to a few hours, BUT this cell should only need to be run once per algorithm with mutants under test. After it saves to the csv file at the end, this cell can be commented out as to not accidentally run it again. 

In the future if we want to test this methodology on higher qubit circuits or other algorithms, we'll likely either want to reduce the number of tests in the suite or the number of mutants we're analyzing

In [11]:
# import QOPS as qops
# from QOPS_test import get_compact_program_specification_Z
# from pathlib import Path

# ga_result = pd.DataFrame(columns=['Program',"path_to_mutant",'catch_avg','avg_fitness','failing_testcases', 'passing_testcases'])
# program_history = {}

# #program_specification = The compact program specification. SB-QOPS needs this to generate failing test cases.
# # In a public-use environment, this would be provided by the user.
# program_specification = get_compact_program_specification_Z(correct_circuit, shots=SHOTS)

# #mutants = A python list of qiskit QuantumCircuit variables with a mutation in them
# mutants = []
# mutants_names = []
# root = Path(QASM_MUTANT_FOLDER)
# for qasm_mutant in root.rglob("*.qasm"):
#     mutants.append(load_program(qasm_mutant.name, QASM_MUTANT_FOLDER))
#     mutants_names.append(qasm_mutant.name)

# for mutant_index,mutant in enumerate(mutants):
#     tester = qops.Circuit_Tester(CUT=mutant)
#     tester.set_applicable_families_Z(program_specification)
#     mutants_per_run = []
#     fitness_per_run = []
#     failing_testcases_per_run = []
#     history_per_run = []

#     print("NOW RUNNING TO FIND FAILING TESTS")
#     #For a predefined number of attempts, try to find a set of failing test cases (output is above predefined tolerance)
#     for runs in range(RUNS):
#         killed = 0
#         pauli = {}
#         fitness = 0
#         for i in range(len(tester.applicable_families)):
#             best_function,testcase, history = tester.run_mealoneplusone(i, EPOCH)
#             if best_function > SBQOPS_TOL:
#                 killed = 1
#                 pauli = testcase
#                 fitness = best_function
#                 break
#         mutants_per_run.append(killed)
#         failing_testcases_per_run.append(pauli)
#         fitness_per_run.append(fitness)
#         history_per_run.append(history)

#     avg_score = np.mean(mutants_per_run)
#     avg_fitness = np.mean(fitness_per_run)

#     #Here is our new, modified algorithm from the SB-QOPS method that attempts to find passing test cases as well. We'll need them for SBFL
#     passing_testcases_per_run = []

#     print("NOW RUNNING TO FIND PASSING TESTS")
#     for runs in range(RUNS):
#         pauli = {}
#         fitness = 0
#         for i in range(len(tester.applicable_families)):
#             best_function, testcase, history = tester.run_reverse_mealoneplusone(i,EPOCH)
#             if best_function < SBQOPS_TOL:
#                 pauli = testcase
#                 break
#         passing_testcases_per_run.append(pauli)

#     #Replace static program file with "program_name" when ready to test fully
#     """
#     ga_result: A pandas dataframe with the following columns
#         Program: Name of the mutant quantum circuit file
#         Path_To_Mutant: Path to the mutant file
#         Catch_Avg: The average number of times the mutant was identified by SB-QOPS
#         Avg_Fitness: The average fitness of the search algorithm used. Higher usually indicates higher Catch_Avg
#         Failing_Testcases: A list of dicts indicating the set of Pauli strings and the weights that should be applied to generate a failing test case
#         Passing_Testcases: A list of dicts indicating the set of Pauli strings and the weights that should be applied to generate a passing test case
#     """
#     ga_result = pd.concat([pd.DataFrame([[mutants_names[mutant_index],QASM_MUTANT_FOLDER,avg_score,avg_fitness,json.dumps(failing_testcases_per_run), json.dumps(passing_testcases_per_run)]],columns=ga_result.columns),ga_result],ignore_index=True)
#     ga_result.to_csv(f'realamprandom_ga_result', index=False)

ga_result is a slightly altered pandas Dataframe with similar structure found in SB-QOPS. The differences are changing the column "Program" to be the name of the mutant file instead of the original quantum circuit, changing "Mutant" to be the path to the mutant file instead of being an arbitrary index value, and adding a passing_testcases column that returns Pauli strings and coefficients that generate passing tests.

Now we want to run SBFL using Heisenberg evolution trees on each circuit placed in ga_result

Evolution analysis can vary widely in runtime. Some of the simplest circuits take seconds to analyze and only took upwards of 3-4 minutes to get results on the whole dataset (GHZ was the fastest taking 3 minutes to run). Other, more complex algorithms can take upwards of 6-10 minutes PER MUTANT (RealAmpRandom took longest so far with 14 hours).

The runtime of this code segment is directly tied to the depth of the circuit being analyzed and the number of 2-branching gates such as rotation or phase gates that exist in the circuit.

This is something to note in the final paper. Regardless of accuracy this methodology takes a long time to run. If results are promising, then we'll want to look into the tradeoffs between EXAM and hyperparameters to speed this up. Primarily the atol, max_terms, and search_step parameters in the evolve_pauli_exact method in HeisenbergUtilities.py

<h2 style="text-align: center;">HEISENBERG EVOLUTIONS (PAULI PROPAGATION)</h2>

In [12]:
from heisenbergTree import *

LAMBDAS = [LAMBDA_WEIGHT, LAMBDA_COMP, LAMBDA_SUPPORT, LAMBDA_DIAMETER, LAMBDA_PHASE]
ga_result = pd.read_csv(f'{ALG_NAME}_ga_result.csv')
custom_sbfl_result = pd.DataFrame(columns=['Program','path_to_mutant','best_exam_score', 'worst_exam_score', 'avg_exam_score'])
barinel_sbfl_result = pd.DataFrame(columns=['Program','path_to_mutant','best_exam_score', 'worst_exam_score', 'avg_exam_score'])
dstar_sbfl_result = pd.DataFrame(columns=['Program','path_to_mutant','best_exam_score', 'worst_exam_score', 'avg_exam_score'])
mutant_num = 0

#For each mutant of a circuit, run the SBFL implementation
for mutant, path in zip(ga_result.loc[:,"Program"], ga_result.loc[:,"path_to_mutant"]):
    print("Now evolving the following mutant: ", mutant)

    #Extract the raw test cases found for each mutant
    raw_failing_testcases = format_test_case(ga_result, mutant, mutant_num, "failing_testcases")
    raw_passing_testcases = format_test_case(ga_result, mutant, mutant_num, "passing_testcases")

    circuit_inverse = load_program(mutant,path).copy().inverse()  # Invert to track backward evolution of the operator
    forward_mutant = load_program(mutant, path).copy()

    #Create the linked list of operations in the inverse circuit
    operation_list = LinkedList()
    operation_list = construct_list(operation_list, circuit_inverse, True)

    forward_list = LinkedList()
    forward_list = construct_list(forward_list, forward_mutant, False)

    #Create list of nodes in linked list. Somewhere down the road remove the linked list implementation. It's unnecessary and giving me a headache
    node_list = []
    node = operation_list.head
    while node:
        node_list.append(node)
        node = node.next

    #Perform Pauli propagation (Heisenberg evolution) for all test cases. Returns a dataframe with all counts for all operations
    global_frame_fail = heisenberg_evolve(circuit_inverse, 
                                          operation_list, 
                                          raw_failing_testcases, 
                                          "fail", 
                                          LAMBDAS,
                                          atol = ATOL, 
                                          max_terms = MAX_TERMS, 
                                          search_step = SEARCH_STEP)
    
    global_frame_pass = heisenberg_evolve(circuit_inverse, 
                                          operation_list, 
                                          raw_passing_testcases, 
                                          "pass", 
                                          LAMBDAS,
                                          atol = ATOL, 
                                          max_terms = MAX_TERMS, 
                                          search_step = SEARCH_STEP)

    global_frame = pd.concat([global_frame_fail, global_frame_pass], ignore_index=True)

    global_frame = global_frame.drop(["Initial"],axis=1)
    if VERBOSE:
        display(global_frame)

    custom_scores = custom_sbfl(global_frame, CUSTOM_WEIGHT)
    barinel_scores = barinel(global_frame)
    dstar_scores = dstar(global_frame)

    if VERBOSE:
        print("BARINEL SCORES")
        display(barinel_scores)
        print("custom SCORES")
        display(custom_scores)
        print("DSTAR SCORES")
        display(dstar_scores)
    
    # Here is where analysis of the methodology begins. 
    # We first extract the position of the erroneous gate by comparing it to the original MQT gate
    # NOTE: This method is intended for single-added gates for now. Other types of mutants will require other methods later
    error_gate_location = find_erroneous_gate(forward_mutant, correct_circuit)

    if VERBOSE:
        print("ERROR GATE LOCATION:")
        print(error_gate_location)

    #Calculate best, worst, and average EXAM for Barinel, custom, and DStar
    barinel_best_exam, barinel_worst_exam, barinel_average_exam = calc_exams(barinel_scores, error_gate_location, circuit_inverse)
    custom_best_exam, custom_worst_exam, custom_average_exam = calc_exams(custom_scores, error_gate_location, circuit_inverse)
    dstar_best_exam, dstar_worst_exam, dstar_average_exam = calc_exams(dstar_scores, error_gate_location, circuit_inverse)

    # Here we store the results from the HBFL analysis for both barinel and custom into a csv file for later analysis.
    barinel_sbfl_result = pd.concat([pd.DataFrame([[mutant,QASM_MUTANT_FOLDER,barinel_best_exam, barinel_worst_exam, barinel_average_exam]],columns=barinel_sbfl_result.columns),barinel_sbfl_result],ignore_index=True)
    barinel_sbfl_result.to_csv(f'{ALG_NAME}_barinel_sbfl_result.csv', index=False)

    custom_sbfl_result = pd.concat([pd.DataFrame([[mutant,QASM_MUTANT_FOLDER,custom_best_exam, custom_worst_exam, custom_average_exam]],columns=custom_sbfl_result.columns),custom_sbfl_result],ignore_index=True)
    custom_sbfl_result.to_csv(f'{ALG_NAME}_custom_sbfl_result.csv', index=False)

    dstar_sbfl_result = pd.concat([pd.DataFrame([[mutant,QASM_MUTANT_FOLDER,dstar_best_exam, dstar_worst_exam, dstar_average_exam]],columns=dstar_sbfl_result.columns),dstar_sbfl_result],ignore_index=True)
    dstar_sbfl_result.to_csv(f'{ALG_NAME}_dstar_sbfl_result.csv', index=False)

    mutant_num += 1

if VERBOSE:
    display(barinel_sbfl_result)
    display(custom_sbfl_result)

Now evolving the following mutant:  AddGate_ry_inGap_15_.qasm

100%|██████████| 10/10 [00:18<00:00,  1.89s/it]
100%|██████████| 10/10 [00:21<00:00,  2.15s/it]

,ry 21,h 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.541267,0.0,0.0,9.421020e-19,4.643985e-19,0.030795,0.103681,0.054003,0.045138,0.134841,...,0.120233,0.053619,0.012236,0.000189,0.121638,0.093051,0.091353,0.071782,0.067526,fail
1,0.700709,0.0,0.0,1.197371e-18,5.902306e-19,0.057530,0.183176,0.097800,0.072932,0.197564,...,0.173235,0.075493,0.021161,0.000276,0.187421,0.144844,0.133950,0.128439,0.090195,fail
2,0.568103,0.0,0.0,9.058335e-19,4.465203e-19,0.031047,0.103441,0.052640,0.053865,0.168088,...,0.162683,0.064967,0.010864,0.000188,0.152789,0.098585,0.113130,0.070132,0.070007,fail
3,0.618091,0.0,0.0,1.034266e-18,5.098297e-19,0.054182,0.179991,0.093401,0.065327,0.185360,...,0.159527,0.069989,0.019425,0.000240,0.162191,0.125566,0.124244,0.118851,0.085190,fail
4,0.528925,0.0,0.0,1.063958e-18,5.244661e-19,0.051063,0.171875,0.088320,0.068829,0.197762,...,0.170769,0.071493,0.017915,0.000245,0.162550,0.120767,0.125548,0.108999,0.072091,fail
5,0.567266,0.0,0.0,1.170214e-18,5.768436e-19,0.045040,0.154115,0.080101,0.065825,0.201150,...,0.182747,0.073189,0.016244,0.000246,0.161938,0.123282,0.124022,0.094663,0.064904,fail
6,0.369596,0.0,0.0,9.910915e-19,4.885473e-19,0.046026,0.157980,0.081079,0.060389,0.180477,...,0.174351,0.064816,0.015838,0.000224,0.140268,0.107214,0.107434,0.090960,0.037264,fail
7,0.603069,0.0,0.0,1.135911e-18,5.599343e-19,0.061702,0.208518,0.108751,0.078742,0.220927,...,0.169834,0.078391,0.020948,0.000248,0.187869,0.134235,0.138608,0.129648,0.084329,fail
8,0.397809,0.0,0.0,9.881090e-19,4.870771e-19,0.063272,0.209460,0.109054,0.067782,0.188121,...,0.170474,0.068372,0.021935,0.000243,0.151590,0.120017,0.114311,0.129724,0.049790,fail
9,0.395537,0.0,0.0,8.522161e-19,4.200902e-19,0.038363,0.138310,0.070337,0.051422,0.163157,...,0.138833,0.056809,0.013180,0.000152,0.132287,0.081499,0.096381,0.076770,0.048004,fail
10,0.304619,0.0,0.0,7.295588e-19,3.596277e-19,0.038261,0.127696,0.067692,0.050936,0.150914,...,0.142366,0.055365,0.012761,0.000194,0.121806,0.098797,0.093861,0.077644,0.040676,pass
11,0.352879,0.0,0.0,8.750044e-19,4.313235e-19,0.045972,0.147245,0.080079,0.056620,0.153499,...,0.121703,0.054885,0.015188,0.000202,0.150998,0.109417,0.098370,0.095797,0.052016,pass
12,0.303052,0.0,0.0,6.593551e-19,3.250216e-19,0.040029,0.135147,0.069599,0.041573,0.119386,...,0.105104,0.043574,0.014658,0.000163,0.093757,0.080049,0.074111,0.084195,0.042783,pass
13,0.432475,0.0,0.0,1.008404e-18,4.970814e-19,0.056655,0.185507,0.096058,0.070921,0.182096,...,0.137615,0.066237,0.019590,0.000247,0.163288,0.128029,0.118362,0.117457,0.063185,pass
14,0.392136,0.0,0.0,1.139923e-18,5.619121e-19,0.034021,0.105763,0.057473,0.071471,0.204686,...,0.192854,0.076574,0.011468,0.000280,0.163087,0.138789,0.129817,0.071290,0.047871,pass
15,0.349388,0.0,0.0,8.583224e-19,4.231003e-19,0.059971,0.194184,0.101870,0.069037,0.168306,...,0.122848,0.061399,0.021229,0.000234,0.134839,0.117391,0.107549,0.129556,0.062258,pass
16,0.635559,0.0,0.0,1.075171e-18,5.299935e-19,0.067752,0.217148,0.115285,0.083664,0.215071,...,0.169848,0.081839,0.025608,0.000285,0.170724,0.147669,0.143329,0.153124,0.097448,pass
17,0.509763,0.0,0.0,1.026577e-18,5.060395e-19,0.054181,0.169643,0.091286,0.072595,0.187288,...,0.150411,0.067416,0.018785,0.000234,0.168333,0.126609,0.123220,0.117835,0.068997,pass
18,0.506494,0.0,0.0,9.902314e-19,4.881233e-19,0.043325,0.137901,0.073068,0.064996,0.183111,...,0.169358,0.069620,0.015318,0.000246,0.163564,0.126446,0.124309,0.094221,0.066437,pass
19,0.310606,0.0,0.0,9.119189e-19,4.495200e-19,0.048491,0.150566,0.081159,0.066593,0.174608,...,0.167585,0.064910,0.017288,0.000263,0.141468,0.130052,0.115007,0.104783,0.050007,pass

[[1.32449911        nan        nan 1.1646367  1.1646367  1.32085555
  1.30055123 1.30527453 1.24937355 1.20236017 1.31600669 1.14119339
  1.24630704 1.12620186 1.15767737 1.29220254 1.22488457 1.20387325
  1.26054156 1.18571944 1.27184501 1.34760962]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,ry 21,swap 10,h 0,cp 17,cp 18,swap 8,x 4,cp 12,cp 7,h 2,...,cp 6,h 16,h 1,h 13,cp 5,h 3,cp 9,h 11,h 20,cp 19
sum,0.563564,0.546318,0.530779,0.525737,0.525737,0.523046,0.514621,0.513768,0.513389,0.508935,...,0.496858,0.495021,0.493724,0.492901,0.4894,0.488482,0.487035,0.474975,0.0,0.0

custom SCORES

,ry 21,h 0,swap 10,cp 17,cp 18,cp 15,swap 8,x 4,cp 12,cp 14,...,h 16,cp 6,h 1,h 13,h 3,cp 5,cp 9,h 11,h 20,cp 19
sum,0.750174,0.709599,0.702182,0.67881,0.67881,0.670847,0.67031,0.669506,0.668202,0.663921,...,0.658484,0.657369,0.650709,0.646855,0.64242,0.639264,0.638784,0.631242,0.0,0.0

DSTAR SCORES

,ry 21,swap 10,cp 9,cp 12,swap 8,cp 15,x 4,h 2,h 3,h 1,...,cp 7,h 0,h 13,h 16,cp 6,cp 5,cp 18,cp 17,h 20,cp 19
sum,1.985394,0.37901,0.320679,0.287607,0.229371,0.224173,0.212283,0.122801,0.117853,0.094183,...,0.043086,0.042294,0.037303,0.021877,0.002833,5.062700e-07,1.057005e-35,2.568399e-36,0.0,0.0

ERROR GATE LOCATION:
21
Now evolving the following mutant:  AddGate_y_inGap_9_.qasm

100%|██████████| 10/10 [00:51<00:00,  5.15s/it]
100%|██████████| 10/10 [00:41<00:00,  4.17s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,y 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.079919,0.253880,0.130511,0.037828,0.094438,0.249904,0.126739,0.113056,0.302554,0.265750,...,0.210115,0.092086,0.025179,0.006643,0.191537,0.155702,0.152787,0.146191,0.150578,fail
1,0.087165,0.272304,0.137299,0.040402,0.095869,0.221481,0.118323,0.131132,0.341249,0.296559,...,0.217656,0.103086,0.023765,0.007535,0.186460,0.152258,0.173737,0.139870,0.169515,fail
2,0.087087,0.267724,0.132838,0.040220,0.106120,0.260239,0.131793,0.125281,0.339477,0.285845,...,0.205518,0.097212,0.026178,0.007086,0.223425,0.171025,0.169579,0.158721,0.164774,fail
3,0.073282,0.231612,0.117195,0.035539,0.085503,0.215276,0.112356,0.100360,0.262229,0.237358,...,0.150707,0.074840,0.020298,0.005810,0.172321,0.132198,0.131808,0.124882,0.137012,fail
4,0.104175,0.327970,0.160387,0.049020,0.113906,0.276789,0.147527,0.141108,0.380730,0.340044,...,0.232917,0.110584,0.027471,0.008588,0.246757,0.166190,0.192214,0.165669,0.198312,fail
5,0.070039,0.222761,0.113312,0.032456,0.096470,0.254516,0.134818,0.129223,0.359821,0.310156,...,0.250872,0.107071,0.027266,0.006404,0.190443,0.157557,0.176661,0.154865,0.137219,fail
6,0.058670,0.175527,0.091437,0.026071,0.078176,0.198638,0.099744,0.095406,0.258920,0.214160,...,0.175609,0.075555,0.020309,0.004859,0.160811,0.130009,0.128896,0.122007,0.113904,fail
7,0.073080,0.222577,0.109871,0.032175,0.081435,0.202279,0.106765,0.112221,0.305626,0.263491,...,0.194657,0.090332,0.020850,0.006003,0.182522,0.138819,0.151977,0.124029,0.140631,fail
8,0.085762,0.268998,0.137068,0.040233,0.106872,0.263726,0.139446,0.132641,0.338756,0.300256,...,0.196272,0.096451,0.026420,0.007083,0.214345,0.153539,0.170316,0.159696,0.164109,fail
9,0.069834,0.219824,0.110850,0.032674,0.096318,0.249622,0.128161,0.110470,0.287241,0.250524,...,0.173498,0.083524,0.025299,0.006037,0.174233,0.140399,0.143196,0.147731,0.134216,fail
10,0.062595,0.199055,0.100226,0.029308,0.075475,0.189261,0.101451,0.092582,0.228595,0.208641,...,0.134502,0.068574,0.019425,0.005523,0.135602,0.099925,0.116648,0.113450,0.121806,pass
11,0.078772,0.251194,0.120963,0.036388,0.072072,0.184830,0.094671,0.090691,0.258644,0.224359,...,0.175552,0.077736,0.018516,0.006166,0.176737,0.129617,0.130979,0.111599,0.142610,pass
12,0.039418,0.115028,0.062604,0.018034,0.054007,0.129623,0.065318,0.071099,0.190184,0.158622,...,0.111731,0.052946,0.012395,0.003113,0.117587,0.088503,0.094258,0.077547,0.076746,pass
13,0.079331,0.236066,0.119632,0.035728,0.091017,0.203901,0.109342,0.111231,0.269438,0.233255,...,0.146907,0.077059,0.021673,0.006167,0.182454,0.149319,0.140651,0.136648,0.152722,pass
14,0.048127,0.148590,0.078926,0.022513,0.059104,0.147046,0.078950,0.084817,0.234810,0.198980,...,0.151898,0.066017,0.014812,0.003885,0.160456,0.104612,0.116313,0.092499,0.092561,pass
15,0.079650,0.239321,0.118094,0.035346,0.090571,0.222759,0.113966,0.108804,0.280610,0.240770,...,0.162788,0.081774,0.022508,0.006445,0.166969,0.145752,0.142431,0.133095,0.152708,pass
16,0.086062,0.263016,0.132867,0.039762,0.111223,0.266272,0.136987,0.122711,0.319190,0.274219,...,0.197375,0.089086,0.026570,0.006774,0.202406,0.159482,0.159193,0.162977,0.160330,pass
17,0.077344,0.253107,0.123760,0.037378,0.072108,0.188188,0.100145,0.090072,0.222875,0.210967,...,0.126348,0.066673,0.018125,0.006295,0.155889,0.103373,0.117077,0.109890,0.145836,pass
18,0.042813,0.139235,0.071292,0.021066,0.061488,0.167062,0.083718,0.064991,0.186382,0.168401,...,0.132251,0.056111,0.016028,0.003738,0.101903,0.084229,0.089984,0.089064,0.077247,pass
19,0.070746,0.224828,0.116120,0.033878,0.090402,0.230434,0.115181,0.104912,0.275322,0.240165,...,0.186021,0.083523,0.023652,0.006081,0.146481,0.138840,0.137356,0.136097,0.133205,pass

[[1.32031842 1.33149126 1.29264332 1.33709966 1.19259913 1.15691659
  1.18431653 1.18488646 1.19854536 1.23019798 1.15130646 1.17030659
  1.13386924 1.24947488 1.18812869 1.13032343 1.30031659 1.27007229
  1.1419222  1.20800318 1.14755953 1.31308828]]
BARINEL SCORES

,swap 8,cp 7,y 13,cp 12,h 2,h 14,swap 10,x 4,cp 6,cp 15,...,h 1,cp 16,h 17,cp 5,h 11,h 0,cp 20,cp 19,h 21,cp 18
sum,0.568274,0.564004,0.562963,0.56153,0.56105,0.558371,0.557476,0.556797,0.556477,0.554766,...,0.553863,0.553576,0.551265,0.549323,0.546816,0.546004,0.543434,0.542945,0.542699,0.54232

custom SCORES

,swap 8,cp 12,x 4,y 13,cp 7,h 2,cp 5,h 0,cp 20,h 14,...,swap 10,cp 15,cp 19,h 17,cp 6,cp 16,h 1,h 3,cp 9,h 11
sum,0.745784,0.734228,0.733591,0.731647,0.731531,0.730487,0.727896,0.725242,0.724328,0.723773,...,0.72058,0.71902,0.718404,0.715624,0.713727,0.713687,0.712761,0.712703,0.711078,0.704204

DSTAR SCORES

,y 13,cp 9,cp 12,swap 10,cp 20,cp 16,swap 8,x 4,h 2,h 0,...,h 11,cp 15,cp 19,h 14,h 17,cp 7,h 21,cp 18,cp 6,cp 5
sum,0.809464,0.631709,0.628413,0.623805,0.502695,0.479817,0.34978,0.326912,0.225154,0.202644,...,0.164078,0.141067,0.139391,0.129615,0.084642,0.080814,0.058373,0.013037,0.005794,0.000434

ERROR GATE LOCATION:
13
Now evolving the following mutant:  AddGate_y_inGap_10_.qasm

100%|██████████| 10/10 [00:50<00:00,  5.04s/it]
100%|██████████| 10/10 [00:48<00:00,  4.82s/it]

,h 21,cp 20,cp 19,cp 18,h 17,y 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.108056,0.339913,0.168324,0.050168,0.113011,0.384985,0.282347,0.149888,0.139196,0.306877,...,0.157663,0.096456,0.026915,0.008845,0.241793,0.153196,0.175135,0.166660,0.210330,fail
1,0.063768,0.195008,0.091971,0.028213,0.083352,0.320555,0.224270,0.116297,0.095001,0.221756,...,0.156333,0.073741,0.021595,0.004973,0.178607,0.130438,0.130367,0.130316,0.120582,fail
2,0.090906,0.271202,0.142855,0.041938,0.117104,0.368320,0.268066,0.134690,0.130258,0.290699,...,0.207974,0.097202,0.025900,0.007436,0.214484,0.161913,0.169816,0.159232,0.174011,fail
3,0.080191,0.247907,0.124873,0.036570,0.105004,0.361589,0.255118,0.135956,0.139686,0.317905,...,0.214525,0.106770,0.025886,0.007062,0.206275,0.160797,0.183793,0.155669,0.160115,fail
4,0.072122,0.220081,0.113447,0.033157,0.100657,0.364234,0.259417,0.131826,0.115772,0.275683,...,0.203001,0.089641,0.024644,0.005678,0.222120,0.151369,0.159362,0.150105,0.132934,fail
5,0.078623,0.251829,0.132579,0.037898,0.100926,0.368430,0.281548,0.141147,0.112537,0.275774,...,0.182905,0.086392,0.025534,0.006270,0.189873,0.135219,0.148624,0.149535,0.141263,fail
6,0.083674,0.268010,0.133310,0.038951,0.109041,0.403287,0.296935,0.151541,0.130401,0.318685,...,0.230801,0.106986,0.028843,0.007059,0.202859,0.171001,0.177337,0.166474,0.155439,fail
7,0.091844,0.284037,0.143652,0.042832,0.111569,0.388827,0.282311,0.145280,0.131215,0.296625,...,0.192091,0.097849,0.027643,0.007437,0.207999,0.157358,0.170854,0.165151,0.173514,fail
8,0.060446,0.182474,0.095263,0.028249,0.107432,0.388108,0.271141,0.145426,0.121753,0.277519,...,0.183675,0.087251,0.027025,0.005411,0.192584,0.151275,0.154978,0.160663,0.121857,fail
9,0.068835,0.215331,0.111692,0.033334,0.094891,0.344024,0.258185,0.130937,0.100787,0.242075,...,0.148565,0.074136,0.023310,0.005574,0.167925,0.125884,0.129523,0.137562,0.128559,fail
10,0.064467,0.204247,0.101944,0.030382,0.077160,0.274311,0.205712,0.104254,0.085060,0.205610,...,0.151054,0.068795,0.019502,0.005163,0.145172,0.120718,0.116268,0.115330,0.119717,pass
11,0.062555,0.188765,0.095304,0.028537,0.071529,0.247644,0.176000,0.091459,0.096494,0.239238,...,0.189881,0.081846,0.017732,0.005249,0.166022,0.124296,0.137324,0.105272,0.117891,pass
12,0.110350,0.339026,0.169475,0.050189,0.117213,0.382834,0.269128,0.139466,0.137869,0.294343,...,0.207244,0.102584,0.029086,0.009215,0.218290,0.170451,0.177472,0.172649,0.211498,pass
13,0.042643,0.128481,0.064051,0.019505,0.045709,0.152119,0.109174,0.056902,0.054258,0.121084,...,0.084544,0.041996,0.010855,0.003366,0.098671,0.077053,0.072056,0.065629,0.080518,pass
14,0.095976,0.301254,0.151094,0.045194,0.108112,0.368347,0.266992,0.135227,0.115434,0.254513,...,0.164393,0.086009,0.026897,0.007396,0.202450,0.169135,0.150000,0.162355,0.174991,pass
15,0.090447,0.278515,0.137186,0.042208,0.101121,0.343585,0.242372,0.127244,0.112238,0.246430,...,0.158337,0.079415,0.023714,0.006852,0.193000,0.147686,0.144050,0.147862,0.166386,pass
16,0.058425,0.172355,0.088726,0.026259,0.089918,0.318952,0.214669,0.114615,0.115405,0.244696,...,0.167217,0.082144,0.021907,0.004979,0.182172,0.143380,0.147617,0.136360,0.118465,pass
17,0.080360,0.243051,0.124525,0.035384,0.106489,0.371332,0.269477,0.140007,0.122465,0.266308,...,0.144540,0.083897,0.025433,0.006810,0.187450,0.133568,0.150853,0.153695,0.159488,pass
18,0.075643,0.234764,0.114948,0.035216,0.092406,0.332430,0.227832,0.123758,0.110890,0.247266,...,0.156774,0.080192,0.023154,0.006016,0.198014,0.145277,0.144136,0.144236,0.143802,pass
19,0.035754,0.115051,0.057534,0.017411,0.050028,0.185525,0.133599,0.071425,0.070339,0.177159,...,0.141991,0.061143,0.014061,0.003201,0.116345,0.099061,0.100761,0.080248,0.070584,pass

[[1.35329862 1.37294763 1.33806411 1.35111254 1.12277407 1.09222092
  1.1082393  1.09575266 1.14816347 1.12864739 1.12778572 1.23735449
  1.26037481 1.22927922 1.16742677 1.1210068  1.34531138 1.19432232
  1.14118531 1.14885681 1.08124713 1.38502176]]
BARINEL SCORES

,cp 15,cp 14,y 16,cp 12,h 17,cp 6,h 1,swap 8,h 2,cp 7,...,cp 19,cp 5,h 3,cp 18,cp 20,h 21,h 0,swap 10,h 11,cp 9
sum,0.55886,0.55601,0.553624,0.551458,0.54817,0.547861,0.545616,0.545238,0.544086,0.544052,...,0.532415,0.530233,0.529661,0.529237,0.528869,0.52701,0.526937,0.525721,0.524372,0.521796

custom SCORES

,cp 15,swap 8,cp 19,cp 20,h 0,cp 5,cp 14,cp 18,cp 12,h 21,...,cp 7,h 17,cp 6,h 2,h 13,h 1,swap 10,cp 9,h 3,h 11
sum,0.713698,0.712801,0.710517,0.710396,0.709392,0.708566,0.708323,0.708002,0.707058,0.705311,...,0.702837,0.702037,0.7014,0.700355,0.699946,0.693103,0.688347,0.686211,0.680771,0.672217

DSTAR SCORES

,y 16,cp 12,cp 15,cp 9,swap 10,cp 20,x 4,swap 8,h 2,h 1,...,cp 14,h 11,cp 19,h 13,h 17,cp 7,h 21,cp 18,cp 6,cp 5
sum,1.050584,0.648365,0.592562,0.586853,0.547695,0.502195,0.350087,0.304785,0.22568,0.210554,...,0.172244,0.168706,0.142504,0.134308,0.100171,0.077993,0.059491,0.013346,0.006482,0.00043

ERROR GATE LOCATION:
16
Now evolving the following mutant:  AddGate_rzz_inGap_9_.qasm

100%|██████████| 10/10 [00:52<00:00,  5.25s/it]
100%|██████████| 10/10 [00:51<00:00,  5.12s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,rzz 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.074217,0.218988,0.109955,0.033085,0.105329,0.249280,0.135420,0.134942,0.306899,0.279729,...,0.019365,0.096202,0.025981,0.006367,0.199719,0.164820,0.231225,0.218769,0.157503,fail
1,0.079314,0.240539,0.119648,0.034584,0.087191,0.205574,0.105528,0.109106,0.266320,0.230528,...,0.015727,0.077122,0.020567,0.006184,0.171823,0.132222,0.186141,0.177677,0.157777,fail
2,0.097913,0.306827,0.152344,0.045033,0.110047,0.272183,0.139192,0.129666,0.362097,0.305672,...,0.019892,0.096195,0.026595,0.007492,0.222644,0.165577,0.231301,0.222469,0.187958,fail
3,0.085276,0.269064,0.137473,0.040477,0.098591,0.253182,0.129226,0.114969,0.326969,0.274782,...,0.017366,0.085676,0.023065,0.006472,0.199207,0.144452,0.205004,0.195028,0.162418,fail
4,0.088238,0.267776,0.134851,0.040598,0.108818,0.263682,0.139544,0.132900,0.328161,0.291394,...,0.019032,0.091640,0.025363,0.006968,0.210230,0.158911,0.225015,0.219634,0.180051,fail
5,0.077379,0.245488,0.127696,0.036240,0.097406,0.256746,0.131709,0.119268,0.320656,0.293586,...,0.017631,0.087712,0.023938,0.006275,0.181348,0.134775,0.203165,0.193845,0.151908,fail
6,0.057272,0.183717,0.090961,0.028214,0.078645,0.209646,0.107410,0.088436,0.291983,0.232789,...,0.014548,0.073318,0.018423,0.004456,0.152504,0.117722,0.165513,0.151510,0.105254,fail
7,0.099699,0.314521,0.159646,0.046777,0.124403,0.325552,0.169030,0.136791,0.372155,0.306853,...,0.019868,0.096274,0.030019,0.007891,0.225396,0.156110,0.232836,0.236529,0.193563,fail
8,0.078513,0.241773,0.124888,0.036706,0.096304,0.239467,0.124359,0.123282,0.297378,0.272417,...,0.017734,0.088584,0.023501,0.006504,0.195028,0.137572,0.209265,0.200415,0.161935,fail
9,0.081207,0.254572,0.126054,0.037813,0.092450,0.231422,0.121696,0.120214,0.345352,0.290877,...,0.018591,0.094548,0.022113,0.006567,0.177861,0.149836,0.212744,0.191969,0.158719,fail
10,0.080791,0.247252,0.126224,0.038373,0.092868,0.218071,0.112596,0.114696,0.319672,0.253921,...,0.017615,0.087800,0.020708,0.006319,0.185143,0.154637,0.206939,0.189843,0.160451,pass
11,0.067272,0.205179,0.106450,0.031062,0.095385,0.239982,0.122810,0.104309,0.304158,0.251738,...,0.016551,0.075806,0.022910,0.005015,0.188652,0.150963,0.191760,0.187435,0.128090,pass
12,0.064941,0.199177,0.100411,0.030604,0.090336,0.225916,0.116570,0.094669,0.277075,0.216971,...,0.015307,0.070039,0.022159,0.004808,0.171237,0.141717,0.174864,0.175240,0.121675,pass
13,0.078742,0.253392,0.124914,0.037619,0.080533,0.193800,0.103016,0.093047,0.261848,0.211738,...,0.014458,0.070356,0.019818,0.006211,0.157564,0.118055,0.167403,0.163053,0.149379,pass
14,0.069946,0.217125,0.106767,0.031829,0.090139,0.231654,0.120348,0.110664,0.311855,0.240208,...,0.017384,0.081816,0.021362,0.005460,0.208767,0.147726,0.200031,0.193000,0.141889,pass
15,0.080389,0.242805,0.118979,0.036349,0.088394,0.208986,0.108957,0.111492,0.281734,0.217916,...,0.016554,0.080032,0.021091,0.006032,0.189754,0.152979,0.199145,0.189159,0.160723,pass
16,0.084149,0.265446,0.132746,0.039462,0.087226,0.220843,0.111950,0.106591,0.307215,0.244460,...,0.016901,0.081725,0.021607,0.006279,0.189767,0.139594,0.195956,0.181758,0.156758,pass
17,0.066469,0.213945,0.106360,0.031132,0.075504,0.201857,0.104860,0.097132,0.288313,0.237263,...,0.015616,0.078227,0.018882,0.005182,0.165055,0.119575,0.177271,0.162381,0.125397,pass
18,0.107337,0.343983,0.171731,0.051255,0.114907,0.294297,0.148633,0.122995,0.375070,0.284609,...,0.018863,0.093003,0.027343,0.008117,0.208729,0.162788,0.219836,0.214244,0.196054,pass
19,0.075532,0.236670,0.120333,0.035058,0.094063,0.246528,0.125385,0.105266,0.283465,0.244221,...,0.016101,0.071780,0.022565,0.005357,0.199333,0.137993,0.185749,0.184812,0.140615,pass

[[1.21728594 1.23668008 1.24381898 1.2325109  1.24504318 1.29870997
  1.2971257  1.13090567 1.15648925 1.10433295 1.13486942 1.2681846
  1.14106265 1.10661275 1.08505264 1.25306943 1.21073954 1.16438075
  1.13254171 1.10757634 1.17802376 1.19698671]]
BARINEL SCORES

,cp 12,h 14,cp 7,cp 15,cp 5,h 17,cp 16,cp 6,h 2,h 0,...,rzz 13,cp 19,h 21,cp 20,cp 18,cp 9,x 4,h 3,swap 10,h 11
sum,0.536241,0.53275,0.528813,0.525822,0.525802,0.523533,0.523472,0.523059,0.522786,0.521958,...,0.516663,0.513729,0.513628,0.511905,0.511306,0.509949,0.509443,0.506227,0.505819,0.505643

custom SCORES

,cp 15,cp 16,cp 6,h 17,cp 5,cp 12,h 14,h 0,h 1,cp 19,...,h 21,cp 18,h 2,swap 10,rzz 13,swap 8,x 4,cp 9,h 3,h 11
sum,0.696336,0.693432,0.686917,0.686488,0.684955,0.684289,0.683372,0.678152,0.675324,0.673475,...,0.669936,0.668853,0.667543,0.666187,0.666041,0.664971,0.657739,0.655421,0.649558,0.649102

DSTAR SCORES

,rzz 13,cp 12,cp 9,cp 20,cp 16,swap 10,h 2,h 1,x 4,h 0,...,cp 19,h 11,h 14,h 17,cp 7,h 21,cp 18,cp 6,swap 8,cp 5
sum,0.795927,0.62249,0.5898,0.520581,0.511623,0.461727,0.370778,0.340467,0.315844,0.227764,...,0.146895,0.13994,0.132274,0.091515,0.072957,0.062253,0.0139,0.005617,0.003179,0.000422

ERROR GATE LOCATION:
13
Now evolving the following mutant:  AddGate_h_inGap_11_.qasm

100%|██████████| 10/10 [00:19<00:00,  1.92s/it]
100%|██████████| 10/10 [00:19<00:00,  1.91s/it]

,h 21,h 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.063742,0.0,0.0,9.982979e-19,4.920996e-19,0.052277,0.182236,0.093584,0.070221,0.205695,...,0.176867,0.072379,0.018127,0.000223,0.161061,0.113986,0.122444,0.104326,0.048360,fail
1,0.094407,0.0,0.0,1.095275e-18,5.399034e-19,0.060522,0.203046,0.101332,0.067601,0.174965,...,0.144003,0.064540,0.021955,0.000233,0.152986,0.117566,0.114050,0.127277,0.069137,fail
2,0.099463,0.0,0.0,1.138423e-18,5.611725e-19,0.057708,0.187491,0.098379,0.082637,0.225967,...,0.184500,0.082987,0.020953,0.000270,0.183065,0.136073,0.144220,0.126787,0.078055,fail
3,0.088274,0.0,0.0,1.058296e-18,5.216748e-19,0.043872,0.140925,0.071773,0.052755,0.135522,...,0.119170,0.050007,0.015140,0.000226,0.160452,0.117556,0.093452,0.095094,0.060732,fail
4,0.079542,0.0,0.0,1.100599e-18,5.425278e-19,0.050539,0.170031,0.090483,0.068326,0.202987,...,0.190762,0.075164,0.018625,0.000257,0.155856,0.127002,0.125314,0.108176,0.062598,fail
5,0.076905,0.0,0.0,1.241464e-18,6.119655e-19,0.060723,0.208815,0.109057,0.081683,0.236995,...,0.194983,0.082952,0.021452,0.000289,0.164701,0.136053,0.141055,0.124467,0.064377,fail
6,0.098927,0.0,0.0,1.134179e-18,5.590808e-19,0.061128,0.203002,0.105718,0.079010,0.225291,...,0.188237,0.080670,0.021757,0.000252,0.186169,0.132077,0.141777,0.131957,0.079640,fail
7,0.077687,0.0,0.0,1.034128e-18,5.097618e-19,0.044964,0.142833,0.076413,0.060701,0.167619,...,0.159185,0.062049,0.016272,0.000232,0.150311,0.114013,0.105449,0.098594,0.050080,fail
8,0.066189,0.0,0.0,1.056940e-18,5.210065e-19,0.056027,0.192843,0.096836,0.060560,0.180024,...,0.157493,0.060498,0.018895,0.000223,0.158020,0.111403,0.105370,0.110860,0.046359,fail
9,0.088949,0.0,0.0,1.006616e-18,4.961998e-19,0.050058,0.168460,0.086544,0.065041,0.190831,...,0.171459,0.071453,0.017252,0.000237,0.163991,0.124041,0.125504,0.105105,0.073138,fail
10,0.058431,0.0,0.0,9.833074e-19,4.847102e-19,0.058542,0.192896,0.096927,0.059692,0.163477,...,0.156444,0.058400,0.020381,0.000236,0.161510,0.119736,0.102157,0.123939,0.052834,pass
11,0.062397,0.0,0.0,7.326345e-19,3.611438e-19,0.037214,0.127047,0.065283,0.050662,0.149510,...,0.127305,0.054289,0.013391,0.000172,0.115795,0.088673,0.093436,0.079932,0.053771,pass
12,0.065500,0.0,0.0,8.999587e-19,4.436244e-19,0.050875,0.170561,0.087533,0.063745,0.182419,...,0.140280,0.064259,0.016551,0.000222,0.147592,0.113598,0.113325,0.103475,0.061255,pass
13,0.060392,0.0,0.0,1.093996e-18,5.392731e-19,0.056394,0.183901,0.098758,0.071538,0.205596,...,0.187663,0.071773,0.018857,0.000269,0.170948,0.135149,0.122894,0.115821,0.047488,pass
14,0.033559,0.0,0.0,6.877778e-19,3.390323e-19,0.038069,0.123351,0.064665,0.041817,0.114311,...,0.106115,0.041914,0.012712,0.000175,0.103211,0.087260,0.072253,0.079249,0.035287,pass
15,0.084590,0.0,0.0,1.023481e-18,5.045132e-19,0.060544,0.198980,0.106848,0.066931,0.184914,...,0.154843,0.062869,0.022022,0.000239,0.180074,0.130359,0.113049,0.131993,0.068378,pass
16,0.064863,0.0,0.0,9.794585e-19,4.828129e-19,0.037272,0.123405,0.064209,0.049478,0.150167,...,0.143780,0.053934,0.012148,0.000200,0.154490,0.105166,0.093933,0.076156,0.043826,pass
17,0.061979,0.0,0.0,1.061701e-18,5.233536e-19,0.055439,0.179430,0.093556,0.084708,0.229684,...,0.204507,0.084649,0.018943,0.000303,0.179723,0.148349,0.149246,0.116803,0.063691,pass
18,0.093609,0.0,0.0,1.032171e-18,5.087968e-19,0.063287,0.201180,0.107715,0.071760,0.184473,...,0.146860,0.064820,0.021529,0.000245,0.167699,0.128117,0.116901,0.134333,0.066465,pass
19,0.054914,0.0,0.0,9.563831e-19,4.714382e-19,0.050016,0.162734,0.086605,0.063190,0.164457,...,0.135404,0.059752,0.017293,0.000226,0.145410,0.115888,0.105966,0.103552,0.048428,pass

[[1.19248148        nan        nan 1.14270893 1.14270893 1.13659053
  1.16028719 1.17250477 1.2001837  1.21792093 1.12523104 1.09679247
  1.23860276 1.15602817 1.18097498 1.15295839 1.18542134 1.13752675
  1.10649538 1.18345332 1.16503521 1.25918189]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 21,swap 10,h 0,cp 18,cp 17,cp 7,cp 12,h 2,swap 8,h 13,...,cp 9,x 4,cp 5,cp 14,h 1,h 16,h 3,h 11,h 20,cp 19
sum,0.565742,0.559741,0.538782,0.534786,0.534786,0.532608,0.529509,0.529428,0.528756,0.524775,...,0.518995,0.517413,0.516304,0.516097,0.51533,0.514427,0.511964,0.506157,0.0,0.0

custom SCORES

,h 21,swap 10,h 0,cp 12,cp 7,cp 18,cp 17,h 2,h 13,swap 8,...,cp 15,cp 5,cp 14,h 1,x 4,h 16,h 3,h 11,h 20,cp 19
sum,0.734402,0.713221,0.708388,0.690735,0.689857,0.687562,0.687562,0.686066,0.682231,0.681571,...,0.670403,0.669314,0.667378,0.665424,0.664556,0.660601,0.653585,0.648543,0.0,0.0

DSTAR SCORES

,swap 10,cp 9,cp 12,cp 15,swap 8,x 4,h 3,h 2,h 1,cp 14,...,cp 7,h 13,h 0,h 16,cp 6,cp 5,cp 18,cp 17,h 20,cp 19
sum,0.427018,0.384201,0.322833,0.277692,0.247307,0.232378,0.135365,0.133993,0.115937,0.079573,...,0.046511,0.044625,0.037948,0.027527,0.003564,5.961558e-07,1.180312e-35,2.868023e-36,0.0,0.0

ERROR GATE LOCATION:
21
Now evolving the following mutant:  AddGate_rz_inGap_11_.qasm

100%|██████████| 10/10 [00:47<00:00,  4.71s/it]
100%|██████████| 10/10 [00:45<00:00,  4.58s/it]

,h 21,rz 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.086508,0.086508,0.281653,0.143563,0.041891,0.097513,0.255285,0.128048,0.104823,0.248175,...,0.174680,0.081482,0.024995,0.007021,0.185471,0.133122,0.138074,0.145731,0.166075,fail
1,0.073290,0.073290,0.240057,0.121545,0.035634,0.096381,0.268927,0.140539,0.110824,0.273994,...,0.190026,0.088146,0.026093,0.006249,0.188114,0.138972,0.148848,0.151845,0.147496,fail
2,0.060954,0.060954,0.198510,0.103428,0.029792,0.081898,0.225659,0.115358,0.106318,0.269778,...,0.198527,0.089494,0.021477,0.005535,0.181572,0.130718,0.148408,0.123856,0.126208,fail
3,0.081946,0.081946,0.250627,0.133667,0.037826,0.104366,0.261976,0.134575,0.122664,0.265375,...,0.170896,0.087375,0.026889,0.006854,0.210411,0.158809,0.155537,0.161374,0.167947,fail
4,0.074183,0.074183,0.239134,0.117462,0.034894,0.094836,0.252418,0.132221,0.112099,0.273479,...,0.218348,0.091746,0.025389,0.006007,0.203745,0.145855,0.156678,0.150783,0.145846,fail
5,0.076905,0.076905,0.243907,0.124664,0.035627,0.089409,0.233014,0.116242,0.103406,0.224979,...,0.153109,0.075717,0.023419,0.006536,0.173885,0.131293,0.132895,0.138833,0.156228,fail
6,0.093870,0.093870,0.296036,0.151093,0.044515,0.113463,0.279768,0.143208,0.116280,0.249623,...,0.174579,0.085712,0.029703,0.007724,0.184796,0.163071,0.147199,0.173751,0.183900,fail
7,0.080657,0.080657,0.263823,0.135359,0.040181,0.105601,0.272745,0.142217,0.116692,0.284233,...,0.211018,0.093295,0.027282,0.006916,0.183848,0.146915,0.155673,0.159315,0.159481,fail
8,0.096264,0.096264,0.314969,0.156429,0.045867,0.098462,0.254494,0.131941,0.113775,0.264796,...,0.159822,0.085055,0.024850,0.007955,0.182195,0.131467,0.146432,0.146391,0.189915,fail
9,0.081736,0.081736,0.260357,0.135092,0.039373,0.098086,0.236522,0.126038,0.112022,0.249782,...,0.166528,0.082563,0.025365,0.007042,0.196271,0.141788,0.144158,0.149365,0.166954,fail
10,0.055398,0.055398,0.166878,0.088706,0.026530,0.092214,0.243131,0.127282,0.115521,0.276618,...,0.171946,0.086413,0.022644,0.004800,0.202176,0.149798,0.153913,0.138491,0.120874,pass
11,0.045086,0.045086,0.137665,0.075263,0.021462,0.081050,0.209962,0.110991,0.093578,0.213819,...,0.151425,0.069980,0.021638,0.004210,0.130030,0.115115,0.118924,0.124377,0.096676,pass
12,0.070234,0.070234,0.225590,0.115847,0.033267,0.087915,0.243724,0.122517,0.111403,0.259684,...,0.167998,0.087325,0.023085,0.005790,0.199747,0.147164,0.151662,0.137569,0.141048,pass
13,0.075340,0.075340,0.242171,0.117535,0.035353,0.087228,0.227352,0.118909,0.110903,0.262888,...,0.192144,0.090209,0.022981,0.006055,0.192406,0.151767,0.154096,0.137861,0.147093,pass
14,0.062791,0.062791,0.192726,0.099974,0.029193,0.085889,0.220875,0.114794,0.101904,0.236329,...,0.174310,0.079389,0.022336,0.005253,0.164935,0.132240,0.135950,0.132530,0.127577,pass
15,0.120478,0.120478,0.368762,0.182042,0.054298,0.127512,0.305379,0.162050,0.155554,0.334499,...,0.209209,0.114975,0.031933,0.010005,0.254995,0.185269,0.202473,0.193555,0.254024,pass
16,0.045343,0.045343,0.151958,0.072827,0.022074,0.060672,0.172178,0.087353,0.062561,0.157027,...,0.113430,0.050730,0.016781,0.003481,0.121200,0.091465,0.086937,0.098557,0.084240,pass
17,0.050058,0.050058,0.148786,0.074901,0.021579,0.063706,0.149519,0.077593,0.083050,0.172348,...,0.112751,0.059505,0.015710,0.004551,0.134702,0.100765,0.107280,0.096287,0.112893,pass
18,0.048960,0.048960,0.148262,0.071887,0.021429,0.063729,0.158985,0.084420,0.087895,0.200934,...,0.137261,0.069271,0.015671,0.004329,0.143597,0.107740,0.121117,0.097052,0.107255,pass
19,0.085270,0.085270,0.272439,0.135608,0.039737,0.097111,0.261003,0.134235,0.118346,0.280156,...,0.188939,0.092078,0.025231,0.006840,0.208624,0.155890,0.159937,0.152254,0.169600,pass

[[1.19387895 1.19387895 1.21653245 1.18300655 1.18948529 1.15776674
  1.10109667 1.09287026 1.09628759 1.09143465 1.23948188 1.07334424
  1.17449424 1.20134066 1.08408536 1.16271758 1.17262522 1.1131022
  1.14676158 1.06301449 1.15738236 1.17956139]]
BARINEL SCORES

,swap 10,cp 18,cp 17,cp 19,cp 5,rz 20,h 21,h 0,cp 6,cp 15,...,h 1,swap 8,cp 9,cp 12,x 4,cp 7,h 13,h 3,h 2,h 11
sum,0.565494,0.561036,0.558418,0.557472,0.550847,0.550282,0.550282,0.541862,0.53955,0.536838,...,0.534293,0.528822,0.523452,0.520998,0.518928,0.518281,0.518102,0.515366,0.514237,0.512324

custom SCORES

,cp 19,cp 18,cp 17,swap 10,h 21,rz 20,cp 5,h 0,cp 6,h 16,...,cp 15,cp 14,cp 9,h 11,x 4,cp 12,h 3,h 13,cp 7,h 2
sum,0.727018,0.726964,0.724476,0.717236,0.714524,0.714524,0.712332,0.701652,0.696386,0.69165,...,0.684615,0.680835,0.67715,0.671078,0.663332,0.663156,0.663117,0.6601,0.658746,0.650897

DSTAR SCORES

,swap 10,cp 9,cp 19,cp 12,cp 15,x 4,swap 8,h 0,h 1,h 2,...,cp 14,h 11,h 13,h 16,cp 7,rz 20,h 21,cp 17,cp 6,cp 5
sum,0.754711,0.592184,0.556048,0.547182,0.529499,0.304045,0.284302,0.228167,0.199295,0.190689,...,0.154138,0.141532,0.113393,0.088543,0.068575,0.060995,0.060995,0.014429,0.006387,0.000458

ERROR GATE LOCATION:
20
Now evolving the following mutant:  AddGate_cswap_inGap_9_.qasm

100%|██████████| 10/10 [01:51<00:00, 11.10s/it]
100%|██████████| 10/10 [01:45<00:00, 10.53s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cswap 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.087759,0.286359,0.136049,0.041803,0.104738,0.279862,0.149484,0.124982,0.405766,0.260666,...,0.109070,0.081082,0.020175,0.005325,0.176520,0.125852,0.163537,0.140789,0.156990,fail
1,0.063145,0.202845,0.099740,0.029393,0.085160,0.231957,0.120264,0.111851,0.355106,0.200281,...,0.091347,0.065541,0.016866,0.004203,0.140363,0.106469,0.133910,0.120345,0.122698,fail
2,0.088556,0.277889,0.138395,0.041926,0.104835,0.277347,0.141744,0.106721,0.375598,0.226021,...,0.088766,0.071324,0.019092,0.004282,0.156956,0.120331,0.146676,0.135253,0.131271,fail
3,0.084040,0.248094,0.121761,0.036861,0.105138,0.249278,0.134377,0.126171,0.338491,0.215008,...,0.095396,0.075720,0.019329,0.004972,0.172860,0.130719,0.159908,0.138522,0.154157,fail
4,0.081317,0.254450,0.129847,0.038725,0.106724,0.265560,0.142169,0.126303,0.382297,0.234976,...,0.102280,0.074847,0.019665,0.004879,0.179258,0.117763,0.154256,0.137847,0.143766,fail
5,0.080412,0.239489,0.121264,0.036174,0.102478,0.249269,0.129837,0.118793,0.350442,0.215444,...,0.084277,0.070189,0.017628,0.004598,0.170134,0.113311,0.148123,0.128239,0.141484,fail
6,0.080682,0.251862,0.129451,0.038432,0.108436,0.270364,0.140007,0.119249,0.381722,0.222858,...,0.097631,0.073025,0.019553,0.004592,0.169934,0.124789,0.153517,0.141110,0.140206,fail
7,0.080904,0.254887,0.130551,0.039232,0.102738,0.256291,0.134829,0.122996,0.384372,0.224285,...,0.104891,0.073576,0.018920,0.004813,0.161398,0.122577,0.150284,0.134814,0.138385,fail
8,0.078213,0.238701,0.115457,0.034787,0.098270,0.240893,0.126098,0.120592,0.343761,0.208158,...,0.097684,0.072106,0.018089,0.004625,0.155636,0.119527,0.148090,0.130220,0.139217,fail
9,0.076106,0.226619,0.113523,0.032917,0.098379,0.229218,0.120173,0.131497,0.308625,0.195817,...,0.090749,0.068865,0.017249,0.004589,0.155737,0.115801,0.146018,0.127999,0.137297,fail
10,0.071910,0.218666,0.111420,0.033883,0.097419,0.223766,0.121611,0.111056,0.301032,0.190436,...,0.083373,0.065351,0.017022,0.004351,0.132090,0.108812,0.133578,0.120076,0.128351,pass
11,0.060513,0.181396,0.091225,0.026165,0.086559,0.216632,0.113532,0.111326,0.298782,0.183060,...,0.081596,0.061343,0.016153,0.004121,0.133689,0.096654,0.128222,0.112713,0.123436,pass
12,0.055616,0.179008,0.087769,0.026672,0.072939,0.195095,0.106311,0.087535,0.296468,0.181021,...,0.080921,0.055249,0.014151,0.003623,0.123721,0.087091,0.113565,0.099065,0.108425,pass
13,0.088012,0.273335,0.139635,0.041149,0.109599,0.271275,0.141810,0.128156,0.385128,0.233898,...,0.102646,0.077223,0.019852,0.005176,0.162213,0.122447,0.156270,0.137761,0.146898,pass
14,0.084364,0.271577,0.133269,0.039682,0.076467,0.205039,0.100921,0.088871,0.300621,0.187815,...,0.075713,0.061717,0.013643,0.003867,0.137489,0.101883,0.124720,0.102323,0.113297,pass
15,0.071222,0.208835,0.105813,0.032039,0.096564,0.228436,0.123313,0.122475,0.316172,0.202380,...,0.088212,0.068170,0.017341,0.004556,0.156665,0.114349,0.144598,0.124182,0.140829,pass
16,0.069684,0.211696,0.105917,0.031475,0.089942,0.219781,0.120338,0.125522,0.262811,0.198211,...,0.093820,0.069239,0.017122,0.004582,0.132374,0.107862,0.140717,0.119351,0.136756,pass
17,0.079780,0.243254,0.123767,0.036906,0.096124,0.236185,0.117592,0.108115,0.315144,0.192217,...,0.089559,0.064159,0.016552,0.004077,0.144349,0.107748,0.133262,0.121626,0.120575,pass
18,0.080071,0.256910,0.124845,0.036940,0.082303,0.234758,0.121742,0.103653,0.407489,0.222484,...,0.103656,0.069338,0.016239,0.004490,0.162263,0.105567,0.138220,0.117671,0.125055,pass
19,0.072981,0.235691,0.117114,0.034390,0.075691,0.197702,0.097592,0.089511,0.352694,0.179732,...,0.088607,0.058776,0.013826,0.003603,0.154044,0.104565,0.120489,0.105926,0.105436,pass

[[1.10537984 1.15411805 1.11967027 1.13237599 1.0663384  1.09748014
  1.11640088 1.08751327 1.11898947 1.18295776 1.11555134 1.19790965
  1.06656457 1.1336729  1.11640149 1.0813894  1.13589127 1.09384072
  1.09192694 1.08711892 1.05689506 1.11699278]]
BARINEL SCORES

,cp 6,h 17,h 1,cp 15,cp 16,x 4,h 11,h 3,cp 9,h 2,...,cswap 13,cp 12,cp 7,cp 5,swap 10,h 21,cp 18,cp 20,cp 19,swap 8
sum,0.53539,0.535067,0.534947,0.534792,0.533625,0.532475,0.532017,0.53109,0.530435,0.53007,...,0.528404,0.527817,0.527494,0.524808,0.523212,0.521813,0.521808,0.521088,0.52004,0.519995

custom SCORES

,cp 15,cp 12,h 11,cp 6,cp 16,swap 10,x 4,h 17,h 0,h 1,...,cp 7,h 2,cp 5,h 14,cp 9,cp 20,cp 18,swap 8,h 21,cp 19
sum,0.684053,0.683914,0.68039,0.680132,0.680036,0.679902,0.678086,0.677707,0.677313,0.676293,...,0.674718,0.674133,0.673839,0.672931,0.67187,0.671438,0.669529,0.667371,0.666014,0.665608

DSTAR SCORES

,cswap 13,cp 16,cp 20,cp 12,cp 9,swap 10,x 4,h 2,h 0,cp 15,...,h 14,h 3,h 17,swap 8,h 11,h 21,cp 7,cp 18,cp 6,cp 5
sum,0.993416,0.531758,0.501315,0.405595,0.373125,0.285893,0.234782,0.199669,0.175601,0.160583,...,0.132,0.129614,0.095013,0.085012,0.084274,0.059792,0.049526,0.013259,0.003425,0.000219

ERROR GATE LOCATION:
13
Now evolving the following mutant:  AddGate_rzz_inGap_11_.qasm

100%|██████████| 10/10 [00:49<00:00,  4.98s/it]
100%|██████████| 10/10 [00:47<00:00,  4.72s/it]

,h 21,rzz 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.079305,0.333578,0.269590,0.144245,0.042577,0.102617,0.285532,0.147230,0.117456,0.298369,...,0.190212,0.083269,0.024369,0.006411,0.195049,0.131809,0.149832,0.149427,0.163756,fail
1,0.091497,0.387651,0.364153,0.161553,0.047941,0.104410,0.271739,0.137570,0.120250,0.308792,...,0.224936,0.091188,0.023767,0.007144,0.209804,0.154129,0.163929,0.147596,0.184413,fail
2,0.084030,0.358835,0.306303,0.153040,0.043438,0.092271,0.259445,0.125349,0.107287,0.271798,...,0.205896,0.082870,0.022084,0.006527,0.196165,0.128292,0.147020,0.135915,0.168493,fail
3,0.067181,0.285349,0.278319,0.129142,0.035118,0.096175,0.272747,0.133610,0.116516,0.294135,...,0.220112,0.088895,0.023766,0.005464,0.178435,0.141570,0.154857,0.141800,0.136861,fail
4,0.076177,0.320358,0.294905,0.142517,0.040345,0.086440,0.239149,0.114102,0.095906,0.246590,...,0.190920,0.073368,0.020205,0.005747,0.159418,0.118429,0.128524,0.122733,0.145933,fail
5,0.095824,0.395091,0.325737,0.160813,0.044605,0.098811,0.251968,0.119840,0.127012,0.288741,...,0.199444,0.090493,0.022240,0.007679,0.203058,0.156369,0.167109,0.142105,0.201620,fail
6,0.091110,0.385386,0.347265,0.171674,0.052021,0.109477,0.295762,0.151184,0.110760,0.275168,...,0.156067,0.071941,0.024041,0.006793,0.176802,0.127142,0.133776,0.151418,0.177425,fail
7,0.098788,0.424573,0.393017,0.182830,0.051077,0.110483,0.297168,0.142369,0.126510,0.302606,...,0.215668,0.089383,0.025010,0.007693,0.212661,0.157387,0.164834,0.158042,0.203119,fail
8,0.082556,0.342641,0.300181,0.146864,0.045291,0.101419,0.276824,0.139427,0.099809,0.262569,...,0.173479,0.075671,0.022790,0.006152,0.176330,0.136750,0.133731,0.140152,0.158401,fail
9,0.089822,0.370320,0.293963,0.155743,0.045955,0.112822,0.293530,0.149535,0.133200,0.309986,...,0.204957,0.089838,0.026641,0.007263,0.199581,0.153741,0.166281,0.166307,0.189224,fail
10,0.056309,0.224417,0.226516,0.108993,0.027579,0.096936,0.245965,0.116241,0.104612,0.215164,...,0.143042,0.066054,0.021311,0.004748,0.131151,0.122748,0.120312,0.131667,0.117211,pass
11,0.071618,0.288355,0.264413,0.129648,0.038720,0.099530,0.247126,0.125387,0.111379,0.256146,...,0.172659,0.075780,0.021747,0.005717,0.161072,0.137953,0.137165,0.135028,0.147646,pass
12,0.061584,0.251506,0.201109,0.101705,0.031233,0.071939,0.176357,0.092362,0.092382,0.230880,...,0.182714,0.073063,0.017216,0.004780,0.159981,0.131294,0.129569,0.107546,0.123431,pass
13,0.049362,0.207852,0.189710,0.084061,0.026558,0.065926,0.174795,0.093288,0.081244,0.198917,...,0.139176,0.060144,0.016214,0.004018,0.134588,0.106543,0.108195,0.100526,0.105217,pass
14,0.063977,0.257964,0.240760,0.107340,0.030392,0.095341,0.221240,0.112067,0.115397,0.244249,...,0.187853,0.079648,0.022445,0.005498,0.165023,0.156686,0.146794,0.140507,0.142057,pass
15,0.068687,0.286203,0.212073,0.110744,0.035604,0.086392,0.213726,0.119089,0.108504,0.267303,...,0.188286,0.078062,0.020991,0.005647,0.194048,0.142628,0.144907,0.134340,0.148850,pass
16,0.074691,0.303249,0.241125,0.124990,0.038285,0.092497,0.226823,0.113800,0.113177,0.245940,...,0.177728,0.076624,0.020954,0.006091,0.171940,0.147289,0.143296,0.135064,0.164637,pass
17,0.051843,0.213133,0.165596,0.083495,0.024053,0.078274,0.214286,0.104598,0.085974,0.209658,...,0.173612,0.069690,0.019976,0.003770,0.161170,0.146861,0.122522,0.123497,0.101221,pass
18,0.061997,0.260369,0.189283,0.098658,0.029767,0.064449,0.171954,0.090522,0.098054,0.260989,...,0.206997,0.081358,0.016030,0.004847,0.187583,0.135863,0.144900,0.103194,0.130157,pass
19,0.054862,0.236309,0.188783,0.087606,0.028181,0.070658,0.190192,0.100045,0.094341,0.240458,...,0.173334,0.074866,0.017725,0.004607,0.175429,0.127642,0.133404,0.111115,0.121932,pass

[[1.15367127 1.17813254 1.23845986 1.18075039 1.16024017 1.11163017
  1.08302745 1.11147026 1.15353943 1.08433893 1.12968721 1.16177353
  1.0999675  1.13506967 1.08956815 1.13406187 1.15046039 1.11498372
  1.11969872 1.10676053 1.14261719 1.17461086]]
BARINEL SCORES

,cp 19,cp 18,cp 17,rzz 20,h 21,swap 10,cp 5,h 0,cp 15,cp 14,...,cp 12,h 1,x 4,h 13,cp 7,swap 8,h 2,cp 9,h 3,h 11
sum,0.599575,0.598849,0.590937,0.587592,0.582027,0.579708,0.573536,0.570406,0.56852,0.56031,...,0.546768,0.543505,0.537376,0.534643,0.532319,0.531699,0.531473,0.516677,0.509074,0.505268

custom SCORES

,cp 19,cp 18,cp 17,rzz 20,h 21,swap 10,cp 5,h 0,cp 15,cp 14,...,h 1,cp 12,h 13,x 4,swap 8,h 2,cp 7,cp 9,h 3,h 11
sum,0.785213,0.775622,0.762345,0.760657,0.749895,0.74808,0.738494,0.737907,0.722451,0.716002,...,0.698759,0.694988,0.688826,0.687168,0.682578,0.678526,0.677319,0.658759,0.651577,0.647966

DSTAR SCORES

,rzz 20,swap 10,cp 19,cp 12,cp 15,cp 9,swap 8,x 4,h 0,cp 18,...,h 3,cp 14,h 11,h 13,h 16,h 21,cp 7,cp 17,cp 6,cp 5
sum,1.036546,1.011521,0.830957,0.660684,0.623118,0.47838,0.334352,0.312473,0.264572,0.217229,...,0.173991,0.167175,0.145767,0.121158,0.095184,0.069076,0.065245,0.019498,0.005413,0.000445

ERROR GATE LOCATION:
20
Now evolving the following mutant:  AddGate_h_inGap_2_.qasm

100%|██████████| 10/10 [00:53<00:00,  5.34s/it]
100%|██████████| 10/10 [00:50<00:00,  5.06s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,cp 8,cp 7,cp 6,x 5,h 4,h 3,h 2,h 1,h 0,pass/fail
0,0.084528,0.259541,0.131253,0.038649,0.100041,0.257792,0.134960,0.128230,0.295823,0.148600,...,0.099292,0.026027,0.006795,0.225912,0.162533,0.172260,0.157014,0.175078,0.166153,fail
1,0.080260,0.260293,0.130941,0.039303,0.107189,0.285632,0.148878,0.119305,0.288749,0.132959,...,0.092678,0.027225,0.006482,0.216530,0.149732,0.158587,0.162202,0.180847,0.151181,fail
2,0.069000,0.214023,0.107406,0.032003,0.096846,0.257492,0.132918,0.102818,0.228190,0.130855,...,0.073455,0.024994,0.005539,0.168113,0.137067,0.128708,0.147614,0.164425,0.132613,fail
3,0.079160,0.241844,0.123727,0.036193,0.102194,0.259622,0.132373,0.120892,0.274045,0.138745,...,0.089588,0.024676,0.006223,0.221098,0.152175,0.160003,0.153085,0.170784,0.154284,fail
4,0.101425,0.317877,0.160390,0.048343,0.130070,0.339051,0.177595,0.147418,0.337319,0.172210,...,0.107927,0.032514,0.008585,0.211522,0.176102,0.185358,0.191063,0.211998,0.199204,fail
5,0.058490,0.188621,0.099967,0.027865,0.090662,0.261464,0.130916,0.102037,0.237518,0.110130,...,0.075974,0.023841,0.005025,0.170610,0.123065,0.130858,0.139494,0.154218,0.116171,fail
6,0.079994,0.257592,0.130473,0.038624,0.094519,0.243686,0.126749,0.111471,0.271358,0.117387,...,0.087303,0.023926,0.006662,0.206561,0.133661,0.151201,0.139803,0.155793,0.155105,fail
7,0.055914,0.184919,0.091995,0.027610,0.083177,0.252190,0.125626,0.078094,0.215104,0.094740,...,0.061557,0.021143,0.003916,0.181413,0.114873,0.109271,0.126890,0.140810,0.095114,fail
8,0.075726,0.235642,0.114167,0.035033,0.095627,0.248664,0.129176,0.111556,0.269705,0.136849,...,0.086265,0.023253,0.005677,0.200682,0.148153,0.152831,0.143502,0.159873,0.142029,fail
9,0.100082,0.319574,0.161598,0.049102,0.116993,0.290489,0.154731,0.129566,0.305049,0.141344,...,0.093792,0.027565,0.008220,0.211371,0.143721,0.164693,0.165150,0.183750,0.192615,fail
10,0.083097,0.264850,0.132817,0.039459,0.100644,0.266785,0.138420,0.117275,0.269924,0.129096,...,0.086495,0.025962,0.006932,0.198674,0.138701,0.151275,0.152937,0.169711,0.162069,pass
11,0.058689,0.187455,0.095966,0.027709,0.067296,0.174302,0.086793,0.077755,0.175998,0.089216,...,0.059914,0.017427,0.005053,0.121100,0.096273,0.099925,0.099728,0.110483,0.113027,pass
12,0.057219,0.171060,0.085539,0.026072,0.072237,0.165263,0.084805,0.078089,0.166169,0.107969,...,0.059056,0.017263,0.004603,0.132977,0.112968,0.103443,0.105564,0.118188,0.112897,pass
13,0.059704,0.180780,0.089352,0.027573,0.073589,0.179650,0.093597,0.084649,0.193104,0.107473,...,0.065783,0.018329,0.004896,0.126084,0.111925,0.111418,0.108103,0.120512,0.117213,pass
14,0.078814,0.242071,0.125425,0.036738,0.102810,0.266528,0.140724,0.132147,0.297757,0.141987,...,0.097801,0.026143,0.006696,0.219672,0.155457,0.169945,0.156193,0.173947,0.162012,pass
15,0.064267,0.196668,0.099391,0.029201,0.094722,0.246720,0.124936,0.101159,0.218404,0.134661,...,0.070569,0.024081,0.004736,0.183070,0.142814,0.128735,0.148634,0.165742,0.118984,pass
16,0.080437,0.249860,0.123860,0.037397,0.094082,0.236112,0.122098,0.095667,0.220706,0.130671,...,0.071370,0.023469,0.006153,0.159347,0.134519,0.123357,0.138926,0.154030,0.148763,pass
17,0.040485,0.137809,0.068970,0.020195,0.054517,0.156553,0.078107,0.060593,0.159753,0.080357,...,0.049352,0.014569,0.003029,0.131016,0.095889,0.085381,0.088201,0.098182,0.071154,pass
18,0.088144,0.273386,0.135281,0.040983,0.106754,0.251013,0.133416,0.130626,0.304341,0.156402,...,0.103272,0.026433,0.007594,0.198985,0.169412,0.175005,0.157148,0.174852,0.175733,pass
19,0.080287,0.246635,0.124705,0.036388,0.100947,0.261927,0.135283,0.121116,0.272712,0.139341,...,0.090742,0.025669,0.007021,0.168159,0.146268,0.154601,0.151228,0.167317,0.163138,pass

[[1.29273628 1.28864445 1.2908051  1.31738744 1.27855402 1.25756923
  1.27406311 1.28035095 1.23883948 1.30085584 1.17995816 1.27062784
  1.15890344 1.24364097 1.27422859 1.36005422 1.12181201 1.22201181
  1.22447842 1.2521986  1.24882594 1.32407909]]
BARINEL SCORES

,x 5,cp 15,cp 16,cp 13,h 17,h 1,h 2,cp 7,h 3,cp 18,...,h 14,cp 8,swap 11,h 21,swap 9,h 0,cp 6,h 4,h 12,cp 10
sum,0.551292,0.5505,0.550116,0.544384,0.539715,0.538821,0.538687,0.537743,0.537397,0.536727,...,0.535413,0.534976,0.534343,0.531657,0.530994,0.527984,0.526757,0.524926,0.520985,0.515794

custom SCORES

,cp 15,cp 16,cp 18,cp 13,h 17,cp 19,cp 7,cp 20,h 2,h 1,...,cp 6,h 21,h 0,h 3,cp 8,swap 11,h 12,h 4,swap 9,cp 10
sum,0.725843,0.723068,0.713496,0.712985,0.712228,0.70971,0.709045,0.708101,0.707322,0.707044,...,0.705861,0.703481,0.702757,0.701905,0.701306,0.691969,0.690417,0.685292,0.684837,0.679639

DSTAR SCORES

,cp 13,cp 16,swap 11,cp 10,cp 20,x 5,swap 9,h 1,h 2,h 3,...,cp 15,h 12,cp 19,h 14,h 17,cp 8,h 21,cp 18,cp 7,cp 6
sum,0.603799,0.595571,0.571843,0.552947,0.506151,0.348433,0.261599,0.251617,0.205907,0.202733,...,0.174447,0.156233,0.141436,0.120528,0.095231,0.07003,0.057577,0.013459,0.006371,0.000396

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_y_inGap_1_.qasm

100%|██████████| 10/10 [00:55<00:00,  5.51s/it]
100%|██████████| 10/10 [00:51<00:00,  5.11s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,cp 8,cp 7,cp 6,x 5,h 4,h 3,h 2,h 1,y 0,pass/fail
0,0.087411,0.276135,0.139548,0.040779,0.108560,0.284485,0.148985,0.134047,0.302717,0.149753,...,0.100301,0.028622,0.007371,0.221417,0.164378,0.173635,0.171107,0.168754,0.131154,fail
1,0.073167,0.226532,0.117095,0.033805,0.096330,0.242633,0.130218,0.129263,0.304802,0.127741,...,0.099282,0.024034,0.006321,0.217064,0.148124,0.172649,0.145314,0.145668,0.116972,fail
2,0.096958,0.306352,0.158914,0.046199,0.108339,0.270738,0.139616,0.126425,0.289602,0.144418,...,0.095974,0.026680,0.007947,0.210105,0.153290,0.164215,0.159146,0.181652,0.139789,fail
3,0.064899,0.214711,0.111246,0.032471,0.091314,0.261430,0.132542,0.103508,0.267341,0.103718,...,0.088798,0.025341,0.005626,0.162119,0.127745,0.143225,0.140769,0.117340,0.098522,fail
4,0.113387,0.348476,0.174068,0.051906,0.132248,0.311842,0.168769,0.171216,0.376803,0.175178,...,0.125409,0.032289,0.010025,0.245546,0.182973,0.217044,0.190246,0.228438,0.176085,fail
5,0.091731,0.298892,0.149651,0.044025,0.098531,0.251062,0.128449,0.106733,0.249101,0.128938,...,0.078730,0.024174,0.007183,0.183280,0.132943,0.136234,0.142289,0.165485,0.127667,fail
6,0.081372,0.267656,0.133999,0.039480,0.088656,0.233734,0.118220,0.096756,0.247217,0.123363,...,0.084053,0.023529,0.006386,0.171261,0.141180,0.137026,0.135211,0.140316,0.112459,fail
7,0.099831,0.311109,0.154268,0.046696,0.111021,0.261349,0.137979,0.129003,0.289288,0.160656,...,0.098374,0.027183,0.008226,0.214402,0.168971,0.169022,0.161432,0.187756,0.144642,fail
8,0.075784,0.246336,0.122802,0.036668,0.078226,0.206461,0.108240,0.099790,0.253007,0.102835,...,0.085315,0.020428,0.006344,0.159581,0.118434,0.138936,0.115736,0.139078,0.111548,fail
9,0.079549,0.255505,0.126193,0.037747,0.090805,0.220120,0.118746,0.116034,0.271349,0.138838,...,0.092774,0.023952,0.006819,0.194183,0.154108,0.156153,0.140274,0.152246,0.117846,fail
10,0.066197,0.202584,0.100592,0.029669,0.088408,0.226717,0.115725,0.108150,0.240449,0.140923,...,0.083980,0.023594,0.005454,0.160049,0.154925,0.143291,0.141246,0.125451,0.097517,pass
11,0.067076,0.209694,0.104730,0.030192,0.083518,0.220866,0.110750,0.089875,0.194831,0.111457,...,0.066891,0.022611,0.005399,0.159426,0.120763,0.116256,0.133231,0.123776,0.094662,pass
12,0.059454,0.193786,0.094981,0.028531,0.075455,0.215736,0.110735,0.083398,0.221109,0.097094,...,0.069108,0.020021,0.004733,0.157870,0.112919,0.115869,0.115736,0.106008,0.084766,pass
13,0.046667,0.143707,0.071983,0.021860,0.064985,0.159779,0.084299,0.067493,0.146443,0.092555,...,0.046985,0.015982,0.003668,0.117641,0.094318,0.084933,0.098620,0.086985,0.065225,pass
14,0.059086,0.184582,0.093735,0.027830,0.074732,0.194210,0.102536,0.097729,0.238238,0.096590,...,0.078469,0.018863,0.005254,0.152659,0.110617,0.132323,0.110786,0.118203,0.092766,pass
15,0.068185,0.214606,0.104033,0.031034,0.081639,0.207236,0.107794,0.111699,0.260979,0.124385,...,0.090671,0.020899,0.006009,0.169757,0.139771,0.153830,0.124491,0.136320,0.105400,pass
16,0.078680,0.237379,0.120344,0.036382,0.101634,0.250807,0.133048,0.124063,0.280352,0.140093,...,0.092747,0.024683,0.006644,0.200055,0.148624,0.162884,0.149093,0.156046,0.119595,pass
17,0.061952,0.196009,0.094242,0.029201,0.082905,0.212004,0.113555,0.105471,0.254949,0.116304,...,0.084445,0.020993,0.005324,0.176955,0.131111,0.143066,0.125288,0.120083,0.094489,pass
18,0.076590,0.230963,0.109344,0.034767,0.090810,0.214312,0.116977,0.111072,0.240110,0.146130,...,0.083275,0.023626,0.006344,0.188015,0.155064,0.145835,0.142884,0.149629,0.116017,pass
19,0.043049,0.130403,0.062067,0.019431,0.071859,0.188409,0.103279,0.098544,0.223360,0.126820,...,0.079430,0.020681,0.003947,0.176159,0.148427,0.136617,0.124538,0.090223,0.072170,pass

[[1.3122111  1.26640185 1.25428754 1.26668461 1.31717328 1.22586236
  1.26725845 1.41177036 1.32154817 1.29240666 1.09659968 1.16897168
  1.15827509 1.32147368 1.26016606 1.38756029 1.24078288 1.22624006
  1.34965882 1.26701752 1.40427832 1.3792397 ]]
BARINEL SCORES

,cp 19,cp 18,cp 20,h 21,cp 6,swap 11,y 0,h 1,cp 13,h 17,...,h 14,swap 9,cp 15,cp 7,h 3,x 5,h 2,cp 10,h 12,h 4
sum,0.5921,0.586506,0.58604,0.579526,0.577868,0.57643,0.575267,0.572903,0.553416,0.551672,...,0.5487,0.548578,0.547947,0.547287,0.546421,0.544037,0.542568,0.537251,0.532006,0.531261

custom SCORES

,cp 6,cp 19,h 1,y 0,cp 18,cp 20,h 21,h 14,cp 13,swap 11,...,h 3,cp 15,cp 7,cp 16,h 2,x 5,swap 9,h 12,cp 10,h 4
sum,0.778324,0.777766,0.774032,0.773624,0.772236,0.771581,0.769641,0.74236,0.736258,0.734459,...,0.730791,0.721545,0.719706,0.717201,0.714429,0.712795,0.707429,0.703898,0.694259,0.694125

DSTAR SCORES

,swap 11,cp 13,cp 10,cp 20,cp 16,swap 9,x 5,h 1,h 3,h 2,...,h 12,cp 15,y 0,h 14,h 17,cp 8,h 21,cp 18,cp 7,cp 6
sum,0.75423,0.66089,0.638318,0.633963,0.535248,0.345284,0.335913,0.236005,0.228155,0.200123,...,0.164149,0.159802,0.148952,0.133742,0.093203,0.083577,0.07026,0.01632,0.006429,0.000519

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_rx_inGap_12_.qasm

100%|██████████| 10/10 [01:08<00:00,  6.86s/it]
100%|██████████| 10/10 [01:07<00:00,  6.70s/it]

,h 21,cp 20,cp 19,rx 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.078908,0.249190,0.123884,0.120431,0.040646,0.140104,0.317959,0.167621,0.169585,0.463912,...,0.189156,0.105626,0.031592,0.007165,0.242632,0.227426,0.228146,0.208283,0.173657,fail
1,0.070828,0.217763,0.111582,0.115051,0.039538,0.121933,0.268146,0.151924,0.141858,0.426408,...,0.191979,0.090207,0.026296,0.006446,0.204649,0.197465,0.195404,0.174374,0.157293,fail
2,0.084095,0.253397,0.120995,0.167120,0.037284,0.138426,0.260956,0.153270,0.183105,0.467462,...,0.176494,0.102326,0.027179,0.007978,0.257892,0.256413,0.240566,0.196635,0.200183,fail
3,0.073053,0.232394,0.112561,0.105965,0.036908,0.119845,0.269379,0.138362,0.156472,0.440016,...,0.204831,0.106679,0.027761,0.006602,0.253920,0.215042,0.221999,0.184051,0.162228,fail
4,0.065779,0.204031,0.098937,0.160696,0.039897,0.124173,0.252852,0.151602,0.175200,0.502236,...,0.242004,0.114681,0.027409,0.006454,0.238894,0.260770,0.248732,0.187294,0.160941,fail
5,0.078102,0.235524,0.119979,0.127696,0.042945,0.129110,0.268664,0.151639,0.154249,0.479632,...,0.214533,0.101689,0.028091,0.007270,0.239978,0.219714,0.222935,0.189075,0.176706,fail
6,0.083299,0.256002,0.126092,0.142658,0.039560,0.145599,0.306505,0.162589,0.171405,0.479946,...,0.158364,0.096483,0.030524,0.007601,0.250816,0.239226,0.227644,0.211250,0.190409,fail
7,0.064193,0.186685,0.094408,0.141698,0.036951,0.144625,0.298811,0.160197,0.173104,0.477106,...,0.194322,0.106697,0.031218,0.006228,0.247513,0.245523,0.239778,0.212646,0.158263,fail
8,0.069683,0.210128,0.102497,0.124594,0.039787,0.117159,0.244557,0.153454,0.155998,0.441445,...,0.214972,0.096588,0.024095,0.006322,0.272841,0.217847,0.216971,0.171974,0.161519,fail
9,0.080956,0.254429,0.129099,0.099919,0.041949,0.133778,0.297318,0.160380,0.168638,0.433092,...,0.193337,0.106642,0.030437,0.007591,0.248016,0.210021,0.222511,0.196318,0.178498,fail
10,0.067623,0.221826,0.111446,0.084015,0.036314,0.111428,0.269183,0.141947,0.127088,0.360659,...,0.148090,0.082867,0.026028,0.005853,0.183623,0.168377,0.173264,0.166506,0.138941,pass
11,0.087467,0.264940,0.134278,0.093224,0.042061,0.139966,0.324857,0.174003,0.167740,0.459588,...,0.193444,0.108975,0.032912,0.008150,0.226004,0.203399,0.222377,0.207076,0.189958,pass
12,0.069856,0.221432,0.110342,0.071954,0.036468,0.085190,0.210292,0.135729,0.107571,0.323982,...,0.156786,0.069997,0.018406,0.005808,0.192303,0.137091,0.147594,0.124122,0.142020,pass
13,0.066778,0.192869,0.100945,0.103595,0.031013,0.120258,0.258440,0.139761,0.151508,0.399240,...,0.168617,0.091682,0.026031,0.006285,0.228462,0.193584,0.201509,0.174460,0.156340,pass
14,0.091372,0.288504,0.139599,0.136953,0.038500,0.114011,0.243850,0.144769,0.144456,0.442450,...,0.166633,0.087191,0.023499,0.008271,0.221133,0.207001,0.198751,0.163233,0.201277,pass
15,0.061356,0.186078,0.096672,0.074993,0.034558,0.106244,0.230618,0.125741,0.136235,0.357596,...,0.178266,0.089449,0.024793,0.005854,0.210098,0.167601,0.183618,0.159644,0.137115,pass
16,0.053335,0.167149,0.082757,0.056496,0.026499,0.070043,0.155527,0.096322,0.089644,0.243759,...,0.113025,0.054623,0.014854,0.004828,0.145202,0.110158,0.116014,0.099240,0.114556,pass
17,0.080144,0.250025,0.129077,0.106377,0.036715,0.119402,0.257098,0.131610,0.136864,0.370796,...,0.125114,0.078419,0.025220,0.007078,0.215021,0.181021,0.180761,0.170033,0.176174,pass
18,0.077587,0.231797,0.119587,0.110342,0.038694,0.125096,0.244273,0.131806,0.156265,0.431872,...,0.200455,0.100178,0.026511,0.007409,0.201508,0.203437,0.211136,0.174216,0.174990,pass
19,0.064462,0.202810,0.103230,0.089674,0.035053,0.110328,0.242018,0.130615,0.123204,0.360179,...,0.158049,0.081685,0.024246,0.005882,0.182853,0.166349,0.171719,0.157007,0.138526,pass

[[1.12292603 1.11327193 1.13241149 1.27979927 1.08593121 1.10742698
  1.14162443 1.08070325 1.10999053 1.08915216 1.1696034  1.09317988
  1.15032501 1.22224622 1.11598892 1.11004542 1.14525305 1.11039705
  1.13901006 1.09830781 1.10070709 1.16406133]]
BARINEL SCORES

,rx 18,h 11,h 3,h 2,cp 9,swap 8,h 13,cp 12,x 4,cp 7,...,cp 6,swap 10,cp 14,cp 15,cp 17,h 0,cp 5,h 21,cp 20,cp 19
sum,0.584668,0.573989,0.568458,0.556238,0.553382,0.551765,0.551675,0.551495,0.550516,0.548741,...,0.539936,0.536631,0.534225,0.53342,0.526346,0.522769,0.515697,0.509842,0.507965,0.502668

custom SCORES

,rx 18,h 11,h 3,swap 8,cp 9,h 2,h 13,x 4,cp 7,cp 12,...,cp 6,cp 15,swap 10,cp 14,h 0,cp 17,cp 5,h 21,cp 20,cp 19
sum,0.771733,0.741824,0.730328,0.720363,0.712525,0.708969,0.704764,0.703339,0.701838,0.70166,...,0.689774,0.685661,0.683289,0.67856,0.674903,0.66924,0.663348,0.652971,0.649341,0.644975

DSTAR SCORES

,cp 12,h 11,cp 9,swap 10,cp 15,x 4,h 3,h 2,cp 20,swap 8,...,h 13,cp 14,rx 18,h 16,cp 19,cp 7,h 21,cp 17,cp 6,cp 5
sum,1.546435,0.856247,0.685931,0.65524,0.623749,0.502873,0.446546,0.434397,0.432462,0.337716,...,0.239955,0.211915,0.156043,0.1557,0.116794,0.097371,0.052318,0.015102,0.007908,0.000482

ERROR GATE LOCATION:
18
Now evolving the following mutant:  AddGate_rxx_inGap_4_.qasm

100%|██████████| 10/10 [00:53<00:00,  5.30s/it]
100%|██████████| 10/10 [00:50<00:00,  5.01s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,cp 8,cp 7,cp 6,x 5,h 4,rxx 3,h 2,h 1,h 0,pass/fail
0,0.063611,0.206762,0.107116,0.030489,0.089680,0.238826,0.125024,0.109637,0.264276,0.114205,...,0.087594,0.024699,0.005383,0.190906,0.138140,0.339008,0.156785,0.151488,0.126470,fail
1,0.076810,0.251072,0.125830,0.037178,0.092978,0.257737,0.129941,0.090911,0.226154,0.109615,...,0.071665,0.024166,0.006084,0.176751,0.123005,0.307499,0.129394,0.148659,0.144959,fail
2,0.100004,0.305574,0.147552,0.045112,0.096440,0.229128,0.118974,0.116499,0.243529,0.156078,...,0.081111,0.022659,0.007635,0.188279,0.149209,0.300879,0.154637,0.149028,0.195811,fail
3,0.066255,0.209943,0.105650,0.031225,0.073013,0.194701,0.095747,0.084415,0.218497,0.102471,...,0.070307,0.017406,0.004704,0.180680,0.120039,0.311839,0.130016,0.115980,0.122240,fail
4,0.075906,0.252768,0.126085,0.037288,0.093269,0.253768,0.130360,0.100114,0.253692,0.121426,...,0.081003,0.025395,0.005713,0.194200,0.141247,0.342030,0.147075,0.157448,0.136786,fail
5,0.103871,0.319050,0.161055,0.048655,0.122063,0.295057,0.153977,0.133343,0.285865,0.168560,...,0.087724,0.027526,0.007987,0.247646,0.166493,0.393017,0.176842,0.186959,0.209320,fail
6,0.069546,0.209809,0.104875,0.031396,0.074452,0.176369,0.089909,0.084933,0.186938,0.118080,...,0.059570,0.016304,0.005299,0.160576,0.118334,0.264974,0.117421,0.110515,0.139270,fail
7,0.044848,0.140312,0.070253,0.020452,0.075725,0.222245,0.109265,0.077942,0.202350,0.101336,...,0.064453,0.019697,0.003328,0.150660,0.120763,0.271926,0.114696,0.123600,0.081902,fail
8,0.086423,0.257944,0.124307,0.038500,0.096146,0.214608,0.117783,0.115219,0.245854,0.155116,...,0.082064,0.023228,0.006964,0.198023,0.156704,0.328052,0.156844,0.150932,0.176071,fail
9,0.097632,0.288427,0.144074,0.043465,0.114794,0.257734,0.137649,0.142572,0.299151,0.156670,...,0.100770,0.027082,0.008431,0.224540,0.161447,0.366648,0.190423,0.173133,0.209766,fail
10,0.070270,0.220619,0.110981,0.032712,0.078550,0.191767,0.101617,0.100961,0.234834,0.112543,...,0.077714,0.019769,0.005864,0.169785,0.123602,0.292011,0.139972,0.123520,0.141930,pass
11,0.073656,0.234656,0.117465,0.034462,0.088703,0.229066,0.116793,0.095937,0.224264,0.120353,...,0.075653,0.022296,0.006134,0.154217,0.127535,0.275538,0.133356,0.133827,0.142266,pass
12,0.064768,0.211832,0.104193,0.031522,0.071477,0.186132,0.098515,0.076969,0.186360,0.089582,...,0.062167,0.019406,0.005466,0.111407,0.095851,0.209210,0.104967,0.110723,0.122180,pass
13,0.050806,0.153596,0.076058,0.022971,0.075458,0.190471,0.100096,0.090015,0.206533,0.100156,...,0.065907,0.018649,0.004163,0.154124,0.112091,0.262368,0.123657,0.120308,0.103426,pass
14,0.029912,0.087581,0.045151,0.013739,0.068220,0.199712,0.102505,0.075530,0.192819,0.096601,...,0.060950,0.018656,0.002372,0.145456,0.117284,0.262389,0.111664,0.115299,0.058057,pass
15,0.080821,0.242431,0.120721,0.035866,0.101258,0.242585,0.129061,0.123277,0.273916,0.130132,...,0.087240,0.023652,0.006940,0.190254,0.136346,0.315886,0.165276,0.151855,0.173226,pass
16,0.075651,0.218022,0.111397,0.034115,0.096293,0.214397,0.114921,0.120234,0.252942,0.163169,...,0.090020,0.023187,0.006449,0.184891,0.168134,0.325293,0.163134,0.148277,0.159412,pass
17,0.088612,0.279789,0.141429,0.041393,0.096855,0.228548,0.120064,0.116632,0.259743,0.116283,...,0.088859,0.024035,0.007624,0.179461,0.128102,0.311405,0.157885,0.146138,0.176130,pass
18,0.089164,0.273991,0.140177,0.040725,0.108043,0.263504,0.134806,0.137526,0.304708,0.161470,...,0.105129,0.026805,0.007672,0.204996,0.170419,0.347886,0.190243,0.165536,0.182317,pass
19,0.071091,0.223004,0.115027,0.034361,0.084540,0.220698,0.109401,0.085027,0.205235,0.105230,...,0.065187,0.020487,0.005563,0.140970,0.109803,0.240802,0.117572,0.122576,0.131646,pass

[[1.32335366 1.30669064 1.32360006 1.33755606 1.31453377 1.26083411
  1.27398038 1.35064351 1.23294857 1.29307471 1.16945498 1.15535653
  1.29703466 1.28163615 1.20642578 1.37020157 1.29504552 1.19317102
  1.21832632 1.29176297 1.27378741 1.35982411]]
BARINEL SCORES

,x 5,cp 20,rxx 3,cp 18,h 21,cp 19,h 0,h 1,swap 11,h 12,...,cp 15,h 17,cp 6,cp 7,cp 10,h 2,cp 13,h 14,cp 8,swap 9
sum,0.538996,0.532279,0.531562,0.530552,0.530464,0.529181,0.525911,0.52311,0.523044,0.521616,...,0.517302,0.516453,0.513697,0.512606,0.511563,0.511522,0.508909,0.508056,0.502374,0.501818

custom SCORES

,x 5,cp 18,cp 20,h 21,h 0,cp 19,rxx 3,h 12,h 1,cp 6,...,cp 15,h 14,h 2,swap 11,h 4,cp 7,cp 13,swap 9,cp 8,cp 10
sum,0.713502,0.707963,0.70616,0.705962,0.704698,0.704287,0.693467,0.690238,0.689693,0.689664,...,0.682061,0.679606,0.676713,0.675963,0.67483,0.667211,0.665774,0.664537,0.66334,0.659323

DSTAR SCORES

,rxx 3,swap 11,cp 10,cp 20,cp 13,cp 16,x 5,swap 9,h 0,h 2,...,h 12,cp 19,cp 15,h 14,h 17,h 21,cp 8,cp 18,cp 7,cp 6
sum,0.81028,0.529014,0.524911,0.490857,0.477011,0.450108,0.314273,0.227856,0.208909,0.190491,...,0.151781,0.133596,0.131274,0.101093,0.079326,0.057605,0.057354,0.01282,0.005095,0.000376

ERROR GATE LOCATION:
3
Now evolving the following mutant:  AddGate_swap_inGap_6_.qasm

100%|██████████| 10/10 [00:48<00:00,  4.89s/it]
100%|██████████| 10/10 [00:49<00:00,  4.98s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.079545,0.245270,0.125950,0.037155,0.113329,0.276089,0.143942,0.134326,0.295495,0.154579,...,0.179310,0.093395,0.026086,0.005734,0.216188,0.179993,0.163491,0.158612,0.058535,fail
1,0.081409,0.264766,0.128032,0.038464,0.100829,0.278509,0.145146,0.107870,0.271591,0.119634,...,0.151895,0.076985,0.023771,0.004644,0.174876,0.161166,0.135294,0.142635,0.049781,fail
2,0.077861,0.248979,0.131021,0.037884,0.098513,0.255220,0.126979,0.104006,0.234362,0.116369,...,0.141766,0.072414,0.023259,0.004566,0.172410,0.163933,0.127450,0.140363,0.046668,fail
3,0.075605,0.243833,0.119224,0.035282,0.093873,0.247638,0.131034,0.119587,0.296914,0.131526,...,0.197729,0.094977,0.024390,0.005565,0.193317,0.161635,0.158475,0.143742,0.053804,fail
4,0.090340,0.294356,0.145355,0.043384,0.089961,0.228786,0.119389,0.111252,0.272677,0.137580,...,0.175201,0.086945,0.022485,0.005300,0.214171,0.180668,0.149165,0.135597,0.055118,fail
5,0.055820,0.173441,0.088268,0.026529,0.086250,0.211006,0.112364,0.101458,0.242024,0.116321,...,0.148440,0.073570,0.020820,0.004674,0.168094,0.120929,0.126674,0.124732,0.043752,fail
6,0.061309,0.191923,0.089638,0.027063,0.085468,0.239341,0.125496,0.109160,0.272003,0.132937,...,0.177735,0.085371,0.022468,0.005549,0.183645,0.134232,0.144736,0.134661,0.049443,fail
7,0.058679,0.185199,0.094221,0.026723,0.082820,0.236567,0.120251,0.109682,0.271525,0.118072,...,0.174239,0.086119,0.020841,0.005135,0.174623,0.132385,0.143563,0.124151,0.045968,fail
8,0.089322,0.286667,0.142188,0.041399,0.097407,0.264976,0.136956,0.124231,0.296547,0.139646,...,0.176415,0.094306,0.023671,0.005359,0.191683,0.187590,0.162315,0.144204,0.057672,fail
9,0.058589,0.186866,0.095819,0.028305,0.081471,0.212361,0.111407,0.097661,0.241769,0.108351,...,0.155321,0.073646,0.019009,0.004643,0.150546,0.131077,0.125301,0.118049,0.041906,fail
10,0.073119,0.229882,0.110489,0.033031,0.090680,0.245649,0.129499,0.113504,0.255154,0.125993,...,0.134682,0.079660,0.021827,0.004597,0.172586,0.159544,0.138793,0.130916,0.051824,pass
11,0.050925,0.162759,0.079831,0.024113,0.059572,0.149277,0.077555,0.067323,0.160430,0.088118,...,0.111268,0.052911,0.014930,0.003461,0.115028,0.104970,0.088672,0.088533,0.034295,pass
12,0.074913,0.234097,0.114681,0.034247,0.091836,0.238541,0.124732,0.117564,0.282868,0.121586,...,0.175097,0.086344,0.021506,0.004734,0.197309,0.161220,0.151168,0.132734,0.050177,pass
13,0.071785,0.226666,0.110823,0.033486,0.089842,0.229190,0.122416,0.112653,0.261590,0.137452,...,0.156234,0.081123,0.021233,0.005054,0.178088,0.151703,0.141260,0.132049,0.051921,pass
14,0.051691,0.153285,0.077182,0.023298,0.064771,0.157350,0.082704,0.083468,0.194179,0.102391,...,0.123007,0.061794,0.014654,0.003733,0.116442,0.111587,0.105181,0.089446,0.038457,pass
15,0.083953,0.274393,0.134648,0.040280,0.085996,0.242373,0.121845,0.089511,0.224620,0.127509,...,0.138277,0.067684,0.021742,0.004494,0.180378,0.156529,0.120640,0.132073,0.052040,pass
16,0.051418,0.170900,0.086674,0.025451,0.060714,0.178291,0.088282,0.060420,0.150768,0.073222,...,0.079490,0.043434,0.014270,0.002712,0.103181,0.097721,0.075366,0.084796,0.029826,pass
17,0.087608,0.279099,0.145863,0.041804,0.100436,0.251092,0.130027,0.126533,0.292942,0.129855,...,0.180512,0.092388,0.024285,0.005050,0.203464,0.189457,0.159315,0.147182,0.056250,pass
18,0.064153,0.189896,0.093078,0.028842,0.082155,0.185062,0.101387,0.114085,0.242784,0.143137,...,0.145309,0.081008,0.019548,0.004974,0.172113,0.146619,0.141300,0.118461,0.052329,pass
19,0.061692,0.193820,0.097924,0.028944,0.079221,0.200143,0.104308,0.104828,0.243418,0.131169,...,0.150505,0.078675,0.019709,0.005022,0.185421,0.134010,0.135458,0.118974,0.048607,pass

[[1.24011996 1.26806597 1.25336862 1.26784988 1.21869666 1.13654075
  1.14022142 1.20016463 1.10175846 1.21237078 1.11690863 1.11316684
  1.2135002  1.17832324 1.13374547 1.15018678 1.12068593 1.1752171
  1.20744735 1.13814684 1.16050798 1.16453991]]
BARINEL SCORES

,swap 11,swap 8,cp 16,cp 15,cp 6,cp 5,cp 13,h 1,swap 10,cp 7,...,x 4,h 14,cp 19,h 3,cp 20,cp 18,h 21,h 12,h 0,cp 9
sum,0.566854,0.546163,0.541251,0.540371,0.539352,0.538631,0.538587,0.537685,0.537385,0.53606,...,0.531116,0.530663,0.524543,0.523635,0.523276,0.52188,0.52044,0.51926,0.519063,0.519041

custom SCORES

,swap 11,swap 8,h 17,cp 16,cp 6,cp 15,h 1,h 14,cp 5,cp 20,...,cp 18,x 4,cp 13,swap 10,h 2,h 21,h 3,h 12,cp 9,h 0
sum,0.725135,0.707053,0.699218,0.69504,0.694441,0.694407,0.693682,0.689884,0.68954,0.689163,...,0.687297,0.68716,0.686935,0.686935,0.685023,0.681792,0.681701,0.676644,0.676505,0.67018

DSTAR SCORES

,cp 9,swap 11,cp 13,cp 16,cp 20,x 4,swap 8,h 3,swap 10,h 2,...,h 12,cp 19,h 14,h 17,cp 7,h 21,h 0,cp 18,cp 6,cp 5
sum,0.678698,0.671341,0.590029,0.49722,0.444782,0.291118,0.247126,0.21148,0.196841,0.183299,...,0.145402,0.121701,0.113985,0.080031,0.065435,0.04973,0.024141,0.011353,0.005046,0.000261

ERROR GATE LOCATION:
11
Now evolving the following mutant:  AddGate_rz_inGap_6_.qasm

100%|██████████| 10/10 [00:49<00:00,  4.91s/it]
100%|██████████| 10/10 [00:45<00:00,  4.58s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.071684,0.218365,0.113316,0.032897,0.090874,0.229014,0.118340,0.119470,0.276309,0.136847,...,0.205348,0.092494,0.022758,0.006450,0.202308,0.136930,0.160311,0.135017,0.147055,fail
1,0.077317,0.231945,0.117435,0.034613,0.104040,0.258101,0.131621,0.118036,0.265186,0.144970,...,0.178658,0.086528,0.025557,0.006274,0.216278,0.141117,0.154204,0.154860,0.147493,fail
2,0.077353,0.230648,0.116147,0.034707,0.082416,0.188088,0.098013,0.107444,0.220800,0.136753,...,0.133151,0.074256,0.018815,0.006177,0.162447,0.119643,0.134482,0.118986,0.152020,fail
3,0.098192,0.294815,0.147245,0.044065,0.113422,0.279318,0.142102,0.134561,0.289805,0.177348,...,0.180736,0.095809,0.026241,0.007544,0.232087,0.160019,0.172709,0.164902,0.185708,fail
4,0.073619,0.231196,0.111127,0.034683,0.079133,0.188430,0.103896,0.106405,0.254054,0.132329,...,0.194867,0.086587,0.019802,0.006040,0.201650,0.131540,0.148897,0.122274,0.141172,fail
5,0.073980,0.228325,0.120514,0.034222,0.091434,0.234701,0.120508,0.113228,0.269219,0.131577,...,0.207964,0.088930,0.022987,0.005805,0.210525,0.133703,0.153423,0.139425,0.137645,fail
6,0.061101,0.190274,0.091414,0.028267,0.089766,0.235986,0.126981,0.102048,0.223220,0.139175,...,0.151749,0.075394,0.024777,0.005399,0.155150,0.130504,0.129195,0.144074,0.121523,fail
7,0.062683,0.190008,0.096271,0.028905,0.085782,0.211013,0.107228,0.084768,0.181955,0.129278,...,0.129235,0.061871,0.021319,0.004645,0.151227,0.118118,0.108336,0.128401,0.109723,fail
8,0.064702,0.199414,0.101976,0.030852,0.111786,0.288798,0.151572,0.131329,0.302621,0.160849,...,0.227069,0.102825,0.029433,0.005911,0.183739,0.156695,0.171876,0.169354,0.128785,fail
9,0.087209,0.270192,0.131119,0.040209,0.103442,0.251140,0.133679,0.118787,0.249847,0.154563,...,0.140309,0.082282,0.025562,0.007034,0.176658,0.136157,0.145455,0.153246,0.164642,fail
10,0.069569,0.213754,0.113246,0.031805,0.077407,0.193442,0.097386,0.106424,0.236009,0.118885,...,0.156486,0.080283,0.018756,0.005682,0.180456,0.114713,0.138750,0.115146,0.135310,pass
11,0.075424,0.229659,0.116221,0.034582,0.094694,0.237401,0.123556,0.112142,0.252174,0.133646,...,0.155628,0.079870,0.022578,0.005926,0.215776,0.129020,0.146736,0.141908,0.144142,pass
12,0.064558,0.205833,0.099873,0.030130,0.067245,0.168267,0.090584,0.090717,0.211096,0.101592,...,0.145051,0.070485,0.017211,0.005388,0.150775,0.097791,0.121109,0.102713,0.126595,pass
13,0.033664,0.100894,0.051170,0.014934,0.037094,0.089235,0.045734,0.048646,0.106274,0.060838,...,0.074056,0.036015,0.009183,0.002600,0.083245,0.057636,0.064001,0.056824,0.063801,pass
14,0.035127,0.119466,0.059367,0.017234,0.049488,0.142326,0.070878,0.056923,0.151880,0.075377,...,0.127906,0.049666,0.013692,0.002474,0.132685,0.082230,0.083686,0.081201,0.057952,pass
15,0.061481,0.197451,0.100014,0.029295,0.068786,0.182352,0.092497,0.082682,0.195009,0.101514,...,0.139799,0.066199,0.017562,0.004951,0.148597,0.096923,0.111212,0.102576,0.116502,pass
16,0.049370,0.155720,0.080357,0.022777,0.057930,0.156658,0.079918,0.081677,0.219172,0.084195,...,0.182037,0.072578,0.014132,0.004025,0.143892,0.091138,0.118736,0.084683,0.092084,pass
17,0.069282,0.212101,0.109554,0.032603,0.096573,0.235526,0.122591,0.114266,0.265166,0.140855,...,0.197374,0.085438,0.022844,0.005589,0.213693,0.137853,0.152771,0.142220,0.135678,pass
18,0.073818,0.216795,0.110814,0.033495,0.088081,0.204953,0.106855,0.108843,0.233400,0.138857,...,0.144995,0.079726,0.021187,0.006058,0.164902,0.125498,0.137203,0.127409,0.142305,pass
19,0.045381,0.135666,0.068128,0.020926,0.087577,0.229081,0.123245,0.102679,0.246524,0.126955,...,0.188649,0.081346,0.022554,0.003935,0.187733,0.129652,0.139877,0.134836,0.090398,pass

[[1.31300795 1.29011581 1.28423033 1.28312174 1.19128389 1.22134324
  1.22835942 1.18443613 1.1947046  1.22843833 1.21399993 1.19221743
  1.17492288 1.29821643 1.2140241  1.24059087 1.23107023 1.22663129
  1.17279381 1.16783328 1.18384993 1.29344461]]
BARINEL SCORES

,cp 9,h 12,rz 10,cp 6,cp 5,h 17,h 1,h 0,h 21,cp 15,...,cp 18,cp 20,cp 19,swap 11,h 14,h 2,cp 7,cp 13,x 4,swap 8
sum,0.572544,0.571441,0.569267,0.569016,0.56789,0.567747,0.567661,0.565144,0.564189,0.564168,...,0.561878,0.561122,0.557856,0.557835,0.556606,0.549166,0.546936,0.544767,0.538465,0.536354

custom SCORES

,h 21,h 0,h 12,cp 6,cp 5,cp 18,cp 20,cp 9,rz 10,cp 15,...,h 1,cp 16,swap 11,h 3,h 14,cp 7,swap 8,h 2,cp 13,x 4
sum,0.749385,0.747889,0.746936,0.745495,0.742668,0.742118,0.7421,0.740718,0.738939,0.737419,...,0.735668,0.734231,0.727138,0.727054,0.721422,0.712934,0.71043,0.7095,0.707476,0.703589

DSTAR SCORES

,rz 10,cp 9,swap 11,cp 13,cp 16,cp 20,x 4,swap 8,h 2,h 12,...,h 3,cp 15,cp 19,h 14,h 17,cp 7,h 21,cp 18,cp 6,cp 5
sum,1.22266,0.704108,0.585094,0.529531,0.472267,0.443023,0.308037,0.26575,0.195032,0.188062,...,0.168287,0.13901,0.12051,0.118356,0.084522,0.067034,0.052872,0.011486,0.005529,0.000374

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_h_inGap_10_.qasm

100%|██████████| 10/10 [00:37<00:00,  3.79s/it]
100%|██████████| 10/10 [00:34<00:00,  3.41s/it]

,h 21,cp 20,cp 19,cp 18,h 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.067789,0.207909,0.102797,0.030798,0.090346,0.032541,0.0,8.361847e-19,0.072784,0.195885,...,0.117028,0.073687,0.001134,0.004486,0.161272,0.104359,0.130772,0.070182,0.114743,fail
1,0.074630,0.233716,0.116799,0.035822,0.106406,0.037889,0.0,9.301957e-19,0.083163,0.224909,...,0.159044,0.083828,0.001273,0.004981,0.164666,0.132204,0.149643,0.083357,0.125652,fail
2,0.065068,0.205258,0.102009,0.030134,0.077157,0.029835,0.0,8.516085e-19,0.069052,0.190758,...,0.137983,0.069798,0.001054,0.004277,0.148655,0.101765,0.123482,0.059727,0.107849,fail
3,0.084124,0.272213,0.135357,0.039688,0.101625,0.039130,0.0,9.703894e-19,0.067703,0.179198,...,0.157814,0.066148,0.000982,0.005247,0.149608,0.110482,0.116569,0.067640,0.130322,fail
4,0.075055,0.238174,0.120900,0.035243,0.094796,0.035999,0.0,8.514370e-19,0.065285,0.183839,...,0.137275,0.066436,0.000997,0.004799,0.131744,0.097681,0.113558,0.064316,0.115560,fail
5,0.084622,0.254726,0.130946,0.038175,0.117697,0.041260,0.0,1.039860e-18,0.095608,0.249853,...,0.198012,0.091931,0.001400,0.005686,0.197413,0.145814,0.162152,0.088599,0.149241,fail
6,0.087453,0.265041,0.135644,0.039764,0.116742,0.044345,0.0,1.027591e-18,0.090638,0.231682,...,0.170287,0.082574,0.001265,0.005949,0.179747,0.130677,0.148223,0.085777,0.152872,fail
7,0.083134,0.248020,0.121509,0.036744,0.110539,0.039743,0.0,9.976954e-19,0.087739,0.228044,...,0.179256,0.085135,0.001301,0.005766,0.181700,0.139643,0.151667,0.085579,0.147099,fail
8,0.078481,0.243348,0.119815,0.035982,0.097354,0.035612,0.0,9.061332e-19,0.080500,0.213535,...,0.162545,0.078068,0.001191,0.005425,0.142742,0.118276,0.137718,0.069394,0.134486,fail
9,0.089526,0.276392,0.143493,0.041259,0.123291,0.042307,0.0,1.115025e-18,0.092045,0.253604,...,0.177185,0.090008,0.001383,0.005928,0.201097,0.145217,0.162414,0.091827,0.146013,fail
10,0.081706,0.255073,0.128149,0.038199,0.090622,0.040032,0.0,8.508386e-19,0.055361,0.147533,...,0.123941,0.053795,0.000796,0.004658,0.125433,0.090967,0.095482,0.056972,0.120086,pass
11,0.092015,0.286435,0.140772,0.042931,0.096847,0.042489,0.0,1.028940e-18,0.077087,0.203188,...,0.187473,0.077775,0.001164,0.005852,0.176224,0.135482,0.135485,0.069563,0.148970,pass
12,0.049411,0.162767,0.082530,0.023584,0.062553,0.023699,0.0,6.606426e-19,0.052125,0.150397,...,0.139270,0.054933,0.000825,0.003326,0.123818,0.081414,0.093122,0.045037,0.078779,pass
13,0.046800,0.152220,0.077364,0.022249,0.060545,0.021458,0.0,7.176545e-19,0.048089,0.130921,...,0.151570,0.050496,0.000754,0.002951,0.124977,0.085546,0.087516,0.043642,0.073859,pass
14,0.050931,0.157574,0.081986,0.024172,0.088574,0.026584,0.0,7.535237e-19,0.057881,0.158284,...,0.143772,0.058940,0.000898,0.003564,0.130489,0.105775,0.103205,0.065593,0.085573,pass
15,0.070532,0.219210,0.107747,0.032483,0.072667,0.034556,0.0,7.541327e-19,0.062724,0.165133,...,0.133315,0.062790,0.000944,0.004815,0.116433,0.090130,0.106607,0.051363,0.116857,pass
16,0.078042,0.243811,0.123747,0.035703,0.099433,0.037981,0.0,1.030863e-18,0.083129,0.227260,...,0.194538,0.086624,0.001310,0.005166,0.177592,0.131854,0.147880,0.074606,0.126961,pass
17,0.070631,0.221973,0.110833,0.033496,0.081888,0.033998,0.0,7.207715e-19,0.056836,0.150994,...,0.122581,0.057124,0.000854,0.004744,0.097272,0.090826,0.097744,0.057641,0.111924,pass
18,0.034062,0.102402,0.052310,0.015174,0.052964,0.017330,0.0,5.629433e-19,0.037903,0.089275,...,0.094802,0.032235,0.000495,0.002462,0.098536,0.070122,0.060403,0.038583,0.063671,pass
19,0.076179,0.226297,0.113980,0.033939,0.098216,0.038532,0.0,9.192012e-19,0.073264,0.194006,...,0.153544,0.071014,0.001085,0.004440,0.165295,0.129635,0.129953,0.073415,0.122647,pass

[[1.13340652 1.13053129 1.16730453 1.13471771 1.19012173 1.17109475
         nan 1.17049257 1.18838821 1.17883758 1.17997896 1.19197953
  1.15939607 1.24034329 1.16721169 1.16890721 1.13216105 1.21241807
  1.18923439 1.16326067 1.1981612  1.15476411]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 13,cp 12,h 1,h 2,cp 6,cp 7,h 17,h 0,cp 5,x 4,...,cp 19,cp 20,h 11,cp 18,h 16,cp 14,cp 9,swap 8,swap 10,cp 15
sum,0.571019,0.570896,0.57074,0.569042,0.567632,0.56527,0.562938,0.557836,0.55589,0.553857,...,0.546661,0.546621,0.546607,0.546337,0.544583,0.543554,0.534302,0.524928,0.523468,0.0

custom SCORES

,h 1,h 13,cp 12,h 2,cp 6,h 17,cp 7,x 4,h 0,cp 5,...,cp 19,h 16,h 21,cp 14,cp 18,cp 20,cp 9,swap 8,swap 10,cp 15
sum,0.7417,0.740667,0.739145,0.734528,0.73351,0.730429,0.730217,0.721734,0.718878,0.713229,...,0.706191,0.704022,0.703862,0.70261,0.701322,0.701115,0.689169,0.687701,0.679459,0.0

DSTAR SCORES

,cp 20,cp 12,swap 10,cp 9,x 4,swap 8,h 2,h 0,cp 19,h 3,...,h 13,h 21,cp 7,h 1,h 16,cp 18,cp 5,cp 6,cp 14,cp 15
sum,0.496937,0.398392,0.372963,0.360207,0.242685,0.222685,0.176295,0.158611,0.137131,0.136524,...,0.061036,0.058582,0.05849,0.055535,0.013898,0.012834,0.000275,0.000014,9.074697e-36,0.0

ERROR GATE LOCATION:
17
Now evolving the following mutant:  AddGate_cz_inGap_8_.qasm

100%|██████████| 10/10 [01:02<00:00,  6.30s/it]
100%|██████████| 10/10 [01:02<00:00,  6.21s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,cz 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.080047,0.256567,0.127877,0.037404,0.087420,0.221770,0.116725,0.115133,0.263304,0.128662,...,0.368619,0.092043,0.024197,0.006779,0.177829,0.141978,0.207411,0.194607,0.161849,fail
1,0.076239,0.245682,0.120439,0.036596,0.089964,0.246126,0.127749,0.108102,0.256654,0.141001,...,0.360383,0.085340,0.024295,0.005913,0.200412,0.151534,0.202540,0.196671,0.147203,fail
2,0.103957,0.315611,0.160457,0.047895,0.113554,0.263171,0.140337,0.158974,0.349396,0.168516,...,0.463192,0.120267,0.027967,0.008830,0.238195,0.179799,0.275064,0.251876,0.224632,fail
3,0.097722,0.307678,0.157679,0.045812,0.103602,0.264642,0.134167,0.124224,0.289473,0.147679,...,0.379778,0.095458,0.026026,0.007678,0.198247,0.151308,0.223390,0.210542,0.191416,fail
4,0.067890,0.213152,0.111685,0.030961,0.094790,0.256564,0.130993,0.108038,0.243302,0.126323,...,0.349258,0.082225,0.026802,0.005471,0.187647,0.143952,0.200808,0.200353,0.134596,fail
5,0.074117,0.231198,0.116985,0.034533,0.096836,0.241762,0.124633,0.112486,0.254308,0.126172,...,0.337112,0.081412,0.023607,0.005868,0.210089,0.140049,0.205794,0.199043,0.152760,fail
6,0.086715,0.277227,0.139525,0.041661,0.107008,0.275596,0.141720,0.128034,0.304383,0.155604,...,0.433106,0.104766,0.028464,0.007133,0.210066,0.173063,0.240742,0.226248,0.169528,fail
7,0.087247,0.270415,0.131705,0.039180,0.121885,0.317092,0.167641,0.150688,0.351685,0.166722,...,0.469368,0.118381,0.032338,0.007326,0.244061,0.189100,0.275545,0.262134,0.181122,fail
8,0.097995,0.293999,0.148936,0.044182,0.103077,0.233779,0.128409,0.149142,0.311088,0.155625,...,0.378768,0.103300,0.024892,0.008334,0.222390,0.157490,0.246236,0.229820,0.216723,fail
9,0.088729,0.276901,0.142542,0.042193,0.112948,0.282845,0.149443,0.128616,0.284854,0.141260,...,0.362037,0.093169,0.028418,0.007215,0.207919,0.146426,0.224146,0.221409,0.177443,fail
10,0.057313,0.178491,0.086685,0.026180,0.072106,0.181305,0.095806,0.084823,0.190515,0.101007,...,0.256598,0.066063,0.019364,0.004785,0.138789,0.108382,0.155484,0.150897,0.116808,pass
11,0.056792,0.188175,0.094660,0.028078,0.078246,0.225854,0.113910,0.081903,0.209477,0.108631,...,0.308616,0.068245,0.021455,0.004062,0.184276,0.127265,0.168089,0.162809,0.099908,pass
12,0.054550,0.162991,0.082446,0.024057,0.076627,0.180459,0.098151,0.101949,0.224356,0.114728,...,0.309992,0.076385,0.019960,0.004715,0.180621,0.131439,0.185096,0.172680,0.119311,pass
13,0.035491,0.104227,0.055322,0.016214,0.058949,0.150954,0.076671,0.069833,0.159201,0.077032,...,0.205649,0.054089,0.015008,0.002971,0.106754,0.085898,0.125372,0.117416,0.072739,pass
14,0.088353,0.290231,0.143014,0.042280,0.093795,0.255629,0.130807,0.103903,0.267613,0.116515,...,0.378369,0.088894,0.024850,0.006954,0.184158,0.131209,0.198706,0.190286,0.164346,pass
15,0.076205,0.225525,0.115298,0.034429,0.094109,0.220564,0.115794,0.118901,0.267110,0.129224,...,0.354676,0.091905,0.022911,0.006660,0.175036,0.138444,0.209855,0.194265,0.165835,pass
16,0.087076,0.278685,0.135904,0.040730,0.106709,0.277813,0.147063,0.127356,0.297368,0.148901,...,0.424125,0.103793,0.029276,0.007107,0.206054,0.165315,0.236893,0.229351,0.171380,pass
17,0.077956,0.253812,0.131755,0.038195,0.087804,0.227819,0.112160,0.094667,0.234681,0.116924,...,0.334990,0.078341,0.021466,0.006041,0.178826,0.127245,0.181759,0.172409,0.145829,pass
18,0.062777,0.188835,0.101141,0.028682,0.090804,0.216389,0.112093,0.115198,0.264560,0.136976,...,0.388673,0.094320,0.023499,0.005096,0.204032,0.160199,0.220063,0.199733,0.127820,pass
19,0.071701,0.220126,0.111424,0.033408,0.094919,0.223089,0.118628,0.110642,0.239049,0.130120,...,0.328282,0.081879,0.023184,0.005768,0.181973,0.138099,0.199588,0.192122,0.147612,pass

[[1.20787921 1.17396135 1.18171666 1.19613931 1.18210361 1.21801747
  1.23100865 1.23865566 1.20918567 1.1561461  1.08751865 1.14823011
  1.24971955 1.20300819 1.23178727 1.21112387 1.2516692  1.1639408
  1.20086459 1.19714744 1.1954821  1.27830002]]
BARINEL SCORES

,h 0,cp 5,h 21,cp 20,cp 19,cp 18,h 14,cp 13,h 12,h 1,...,cp 7,cp 6,h 17,cp 16,x 4,h 3,swap 11,cp 10,cz 8,swap 9
sum,0.568906,0.565709,0.562937,0.562489,0.562137,0.561855,0.559815,0.552687,0.552606,0.551669,...,0.548432,0.547166,0.546951,0.546552,0.54643,0.54522,0.543203,0.542544,0.542525,0.530992

custom SCORES

,h 0,cp 5,h 14,h 21,cp 18,cp 19,cp 20,cp 13,cp 7,cp 15,...,cp 16,cp 6,h 12,h 3,h 17,cz 8,x 4,cp 10,swap 9,swap 11
sum,0.750715,0.74273,0.733169,0.732927,0.729869,0.728209,0.727574,0.719762,0.71732,0.717274,...,0.712979,0.712837,0.712329,0.708903,0.708589,0.705691,0.705433,0.698285,0.69689,0.690889

DSTAR SCORES

,cz 8,cp 13,cp 10,swap 11,cp 20,cp 16,h 2,h 1,x 4,swap 9,...,h 12,cp 15,cp 19,h 14,h 17,cp 7,h 21,cp 18,cp 6,cp 5
sum,1.145424,0.684727,0.663625,0.663542,0.597767,0.557359,0.445901,0.408077,0.374498,0.315902,...,0.190025,0.16676,0.166735,0.149622,0.097948,0.088235,0.069434,0.015548,0.006975,0.000495

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_rxx_inGap_14_.qasm

100%|██████████| 10/10 [01:06<00:00,  6.64s/it]
100%|██████████| 10/10 [00:57<00:00,  5.72s/it]

,rxx 21,h 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.392233,0.358258,0.377728,0.169296,0.048624,0.273329,0.239604,0.121337,0.105585,0.280409,...,0.191840,0.090578,0.023015,0.007822,0.237506,0.150807,0.160477,0.186835,0.209096,fail
1,0.390213,0.312047,0.335966,0.139635,0.044702,0.249932,0.212880,0.114699,0.101908,0.253219,...,0.143425,0.081965,0.021427,0.007386,0.196417,0.138665,0.146725,0.173565,0.197321,fail
2,0.392974,0.305511,0.341494,0.140029,0.041266,0.257108,0.220983,0.114042,0.110331,0.257942,...,0.188017,0.087989,0.022129,0.007340,0.213368,0.153909,0.156530,0.177895,0.198487,fail
3,0.452524,0.373447,0.396575,0.161986,0.047061,0.301723,0.247334,0.128082,0.125491,0.309323,...,0.179175,0.101264,0.024724,0.008290,0.237708,0.168370,0.182552,0.203213,0.228953,fail
4,0.343655,0.301048,0.360979,0.156760,0.048226,0.249530,0.235338,0.123565,0.116613,0.277520,...,0.196282,0.092666,0.024003,0.008389,0.222146,0.159743,0.162930,0.183702,0.212782,fail
5,0.394639,0.286679,0.330174,0.141211,0.043391,0.240531,0.213865,0.116240,0.109937,0.288554,...,0.162371,0.092457,0.021856,0.007182,0.200333,0.139783,0.162075,0.169880,0.190047,fail
6,0.409103,0.306604,0.330056,0.128120,0.037676,0.259929,0.205234,0.105122,0.096050,0.241842,...,0.161909,0.081742,0.020673,0.006379,0.206387,0.143848,0.145179,0.174160,0.180139,fail
7,0.335265,0.214673,0.279098,0.101925,0.028470,0.211626,0.181583,0.093225,0.095573,0.242265,...,0.181252,0.082044,0.017939,0.004995,0.184599,0.144727,0.143516,0.143892,0.146467,fail
8,0.312209,0.271628,0.346944,0.148614,0.045264,0.228893,0.223972,0.118492,0.108463,0.274993,...,0.158957,0.088011,0.022945,0.007707,0.185321,0.135469,0.155249,0.172147,0.197063,fail
9,0.360863,0.373114,0.369134,0.172748,0.049697,0.265709,0.232299,0.117511,0.120934,0.312176,...,0.236262,0.108360,0.023549,0.008540,0.237110,0.170705,0.185493,0.187098,0.219671,fail
10,0.363641,0.226332,0.300253,0.110007,0.032585,0.221846,0.189403,0.102445,0.107361,0.283499,...,0.164194,0.095170,0.019784,0.006098,0.209197,0.139913,0.166950,0.157068,0.161095,pass
11,0.176659,0.232375,0.311616,0.143006,0.040422,0.185704,0.196841,0.100043,0.099560,0.220020,...,0.128441,0.076292,0.020253,0.007096,0.179250,0.152153,0.137266,0.151694,0.185483,pass
12,0.294496,0.229353,0.253739,0.093215,0.027454,0.198169,0.147804,0.079903,0.088006,0.209162,...,0.093330,0.072493,0.015915,0.005016,0.168639,0.133756,0.133486,0.140898,0.149318,pass
13,0.280408,0.173696,0.250134,0.086950,0.023692,0.186109,0.151644,0.079807,0.092040,0.214440,...,0.140047,0.081421,0.017163,0.004618,0.177017,0.141836,0.142216,0.140539,0.135177,pass
14,0.185051,0.208945,0.267621,0.119423,0.034926,0.170208,0.167866,0.087311,0.095771,0.222865,...,0.129129,0.078691,0.017603,0.006286,0.185257,0.132381,0.139623,0.136584,0.164007,pass
15,0.226130,0.106169,0.198668,0.060060,0.017297,0.139744,0.131697,0.067587,0.067085,0.160850,...,0.135046,0.056035,0.013298,0.003382,0.148426,0.097551,0.099899,0.102176,0.096116,pass
16,0.350539,0.304833,0.361942,0.153673,0.046326,0.255083,0.233178,0.120339,0.125882,0.291978,...,0.190596,0.097809,0.023515,0.008091,0.246108,0.177641,0.178100,0.187445,0.218118,pass
17,0.288776,0.206232,0.245293,0.097145,0.026041,0.187127,0.157045,0.075065,0.085404,0.206537,...,0.180844,0.074889,0.016197,0.004948,0.165567,0.140671,0.131116,0.129860,0.134784,pass
18,0.378678,0.334692,0.379179,0.163186,0.047799,0.268145,0.236092,0.122432,0.112988,0.268794,...,0.162686,0.089467,0.023674,0.007911,0.239015,0.158574,0.164018,0.194301,0.216666,pass
19,0.214357,0.205166,0.210320,0.087983,0.027709,0.154534,0.127235,0.071338,0.078586,0.183444,...,0.083321,0.060751,0.013313,0.005107,0.133570,0.095079,0.109521,0.111139,0.136882,pass

[[1.19599073 1.20350038 1.14347737 1.18294145 1.14409887 1.18867517
  1.11759668 1.11151791 1.15036148 1.14006093 1.11504405 1.1439156
  1.14121651 1.31293923 1.19460515 1.11240344 1.15360526 1.12079234
  1.13347968 1.15880595 1.14655011 1.15631275]]
BARINEL SCORES

,h 20,rxx 21,cp 17,cp 18,h 16,swap 8,cp 15,cp 14,cp 5,cp 19,...,swap 10,h 1,cp 12,cp 7,x 4,h 13,h 2,h 11,h 3,cp 9
sum,0.58209,0.578331,0.572581,0.567122,0.563445,0.561091,0.560007,0.559761,0.558375,0.555178,...,0.550366,0.549732,0.547667,0.536701,0.533835,0.533814,0.533056,0.525643,0.523729,0.519118

custom SCORES

,h 20,rxx 21,swap 8,cp 17,cp 18,h 16,cp 5,cp 15,cp 14,cp 19,...,h 1,cp 6,cp 12,cp 7,h 2,h 13,x 4,h 11,h 3,cp 9
sum,0.757227,0.75125,0.745261,0.736353,0.73484,0.730884,0.719411,0.716473,0.715307,0.713886,...,0.707306,0.704933,0.70376,0.696988,0.687484,0.687334,0.683415,0.672172,0.672138,0.667225

DSTAR SCORES

,rxx 21,cp 19,h 20,swap 10,cp 12,cp 9,h 16,cp 15,x 4,h 0,...,h 2,h 3,cp 18,h 11,cp 14,h 13,cp 7,cp 17,cp 6,cp 5
sum,1.122071,0.941253,0.78744,0.647874,0.611501,0.560347,0.538413,0.417229,0.379529,0.338043,...,0.224722,0.199491,0.191868,0.142894,0.121749,0.108652,0.076304,0.018276,0.004852,0.000545

ERROR GATE LOCATION:
21
Now evolving the following mutant:  AddGate_rz_inGap_10_.qasm

100%|██████████| 10/10 [00:47<00:00,  4.76s/it]
100%|██████████| 10/10 [00:45<00:00,  4.54s/it]

,h 21,cp 20,cp 19,cp 18,h 17,rz 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.065405,0.205571,0.102120,0.030329,0.087003,0.392108,0.218320,0.116247,0.108806,0.252152,...,0.171347,0.082135,0.021783,0.005689,0.174832,0.127689,0.141502,0.137952,0.131398,fail
1,0.094837,0.291455,0.145917,0.044395,0.107373,0.459658,0.264202,0.136743,0.130507,0.306910,...,0.209462,0.103535,0.025346,0.007925,0.192161,0.161548,0.174555,0.157538,0.182840,fail
2,0.079584,0.245145,0.123254,0.035254,0.098805,0.464721,0.269119,0.135249,0.123885,0.287108,...,0.189311,0.096054,0.025250,0.006565,0.193704,0.158822,0.164833,0.159146,0.154072,fail
3,0.069402,0.223333,0.110273,0.034101,0.093627,0.437006,0.258478,0.133554,0.099388,0.243772,...,0.145687,0.076666,0.023526,0.005615,0.164289,0.129655,0.131077,0.146330,0.129879,fail
4,0.087525,0.282942,0.136643,0.040856,0.097792,0.462366,0.267271,0.136183,0.117856,0.289594,...,0.217871,0.099256,0.026384,0.006830,0.210520,0.163740,0.166057,0.163864,0.158752,fail
5,0.064757,0.213155,0.107416,0.031413,0.103357,0.504463,0.297284,0.153406,0.099550,0.247992,...,0.146995,0.074262,0.027153,0.005448,0.162693,0.118949,0.126246,0.167276,0.116849,fail
6,0.073587,0.240092,0.121150,0.035695,0.098113,0.458939,0.276309,0.137929,0.106784,0.284753,...,0.217032,0.092347,0.024974,0.005932,0.183230,0.140579,0.150690,0.152784,0.129808,fail
7,0.068003,0.202636,0.102018,0.030533,0.111935,0.527528,0.290634,0.154338,0.131041,0.296003,...,0.183768,0.094872,0.028787,0.006018,0.205293,0.160126,0.168701,0.182093,0.143285,fail
8,0.061165,0.194039,0.101230,0.028921,0.095224,0.437351,0.252833,0.130368,0.108984,0.263773,...,0.177554,0.082273,0.023898,0.005255,0.176541,0.128208,0.141322,0.148339,0.118333,fail
9,0.066484,0.210793,0.101697,0.030677,0.097533,0.474937,0.260165,0.138320,0.118992,0.277006,...,0.198889,0.091791,0.026895,0.005805,0.197568,0.156647,0.159194,0.168250,0.130573,fail
10,0.082497,0.262059,0.129383,0.038534,0.080417,0.353127,0.205241,0.102983,0.101148,0.230983,...,0.157175,0.082289,0.020263,0.006680,0.143266,0.126213,0.135722,0.125307,0.153988,pass
11,0.097704,0.300644,0.149186,0.045018,0.104349,0.441436,0.240259,0.127869,0.134105,0.289234,...,0.181624,0.098702,0.024473,0.007953,0.211050,0.164781,0.173486,0.160716,0.191419,pass
12,0.049593,0.149212,0.078963,0.023000,0.080331,0.379844,0.199844,0.106401,0.092418,0.202695,...,0.159714,0.070720,0.021996,0.004330,0.165048,0.132021,0.120453,0.135850,0.094086,pass
13,0.068756,0.200249,0.099704,0.030134,0.088960,0.411413,0.218628,0.115687,0.110727,0.242172,...,0.168653,0.081171,0.022782,0.005508,0.190969,0.148261,0.146457,0.147767,0.135752,pass
14,0.029403,0.094280,0.045871,0.013759,0.037810,0.176589,0.105303,0.053459,0.045372,0.116053,...,0.085916,0.038383,0.009519,0.002403,0.081512,0.062427,0.064522,0.058997,0.055055,pass
15,0.055236,0.167120,0.083475,0.025566,0.083061,0.391052,0.215212,0.112114,0.092586,0.219494,...,0.164488,0.072260,0.021478,0.004602,0.162233,0.136908,0.125345,0.136186,0.107953,pass
16,0.073843,0.229853,0.114327,0.033639,0.090651,0.417805,0.229865,0.122015,0.120526,0.272421,...,0.196776,0.092264,0.023251,0.006119,0.194240,0.144067,0.160207,0.149826,0.145765,pass
17,0.090298,0.279948,0.136744,0.040679,0.097992,0.441268,0.249011,0.130679,0.125927,0.287904,...,0.162136,0.092268,0.023879,0.007403,0.214086,0.143042,0.163196,0.154353,0.177159,pass
18,0.058692,0.175671,0.086146,0.025842,0.069753,0.307567,0.157999,0.087428,0.102493,0.222445,...,0.159366,0.078833,0.017877,0.005371,0.147818,0.121699,0.135337,0.113396,0.124073,pass
19,0.073146,0.231725,0.116382,0.033819,0.083422,0.395518,0.232642,0.119527,0.110579,0.272809,...,0.200315,0.093310,0.022810,0.006223,0.183140,0.145555,0.154095,0.138934,0.140335,pass

[[1.29780596 1.26216944 1.26694649 1.29744378 1.12978917 1.1420639
  1.1198752  1.12463531 1.14367105 1.11641843 1.1964033  1.13074447
  1.11424848 1.1726645  1.15915904 1.13336303 1.29745615 1.13131965
  1.13239092 1.14524215 1.14988699 1.30994162]]
BARINEL SCORES

,cp 15,cp 14,rz 16,cp 6,h 17,h 1,cp 12,swap 10,swap 8,cp 7,...,h 13,h 2,cp 20,cp 18,x 4,h 3,cp 5,h 21,h 11,h 0
sum,0.563778,0.560023,0.554199,0.54939,0.548137,0.545138,0.538475,0.537227,0.531733,0.527457,...,0.52519,0.525036,0.524819,0.524675,0.523559,0.521832,0.519084,0.518292,0.51622,0.512899

custom SCORES

,cp 15,cp 14,rz 16,cp 6,h 17,h 1,cp 18,cp 19,cp 20,swap 10,...,cp 5,h 21,h 0,cp 7,h 2,h 13,cp 9,x 4,h 11,h 3
sum,0.721618,0.717479,0.712431,0.705054,0.702956,0.701849,0.69486,0.69187,0.690421,0.689094,...,0.687456,0.686452,0.680865,0.680308,0.675359,0.675351,0.672575,0.671638,0.670622,0.669561

DSTAR SCORES

,rz 16,cp 12,cp 9,cp 15,swap 10,cp 20,swap 8,x 4,h 1,h 2,...,cp 14,h 11,cp 19,h 13,h 17,cp 7,h 21,cp 18,cp 6,cp 5
sum,1.55559,0.611623,0.593556,0.584617,0.568374,0.441017,0.296649,0.296125,0.221503,0.204161,...,0.170002,0.150222,0.120148,0.118961,0.090749,0.073868,0.050003,0.011356,0.00632,0.000371

ERROR GATE LOCATION:
16
Now evolving the following mutant:  AddGate_rzz_inGap_6_.qasm

100%|██████████| 10/10 [00:53<00:00,  5.31s/it]
100%|██████████| 10/10 [00:46<00:00,  4.70s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.077120,0.249904,0.124639,0.038008,0.091341,0.238047,0.124176,0.105253,0.258616,0.125402,...,0.183037,0.083348,0.023269,0.006058,0.200190,0.140469,0.143899,0.139500,0.138904,fail
1,0.092012,0.300126,0.149550,0.044594,0.094176,0.246826,0.127715,0.109162,0.271944,0.116887,...,0.177800,0.086451,0.022694,0.007331,0.186954,0.127675,0.146439,0.134480,0.165924,fail
2,0.082783,0.266599,0.133274,0.040164,0.097792,0.254370,0.135018,0.118293,0.283012,0.128690,...,0.201862,0.094394,0.025597,0.007065,0.188108,0.142738,0.158340,0.147060,0.156991,fail
3,0.088361,0.285811,0.142529,0.043265,0.106073,0.282172,0.149033,0.107768,0.264697,0.137913,...,0.176813,0.083250,0.027756,0.006843,0.198040,0.148984,0.142418,0.163110,0.156444,fail
4,0.080602,0.260549,0.132331,0.038790,0.097067,0.254951,0.127853,0.100150,0.241806,0.126912,...,0.184338,0.079817,0.024810,0.006254,0.202039,0.144489,0.136941,0.146428,0.142511,fail
5,0.106211,0.322394,0.162760,0.047650,0.124404,0.303524,0.159704,0.156820,0.338256,0.178362,...,0.218593,0.113607,0.031707,0.009031,0.236725,0.187758,0.199844,0.190391,0.213011,fail
6,0.099102,0.306245,0.154292,0.046668,0.108191,0.249986,0.129619,0.122647,0.272388,0.153688,...,0.183034,0.091982,0.025552,0.008105,0.199297,0.158407,0.160681,0.151943,0.186435,fail
7,0.089302,0.285239,0.149777,0.043545,0.114945,0.290115,0.150438,0.129903,0.300469,0.136870,...,0.193322,0.095290,0.028241,0.007542,0.218599,0.151214,0.164989,0.164692,0.169103,fail
8,0.074125,0.239268,0.121966,0.035543,0.090602,0.242085,0.125128,0.110661,0.273410,0.118611,...,0.207202,0.091640,0.024483,0.006432,0.169648,0.139331,0.150842,0.139528,0.136499,fail
9,0.107051,0.343460,0.171361,0.049942,0.117750,0.314683,0.162301,0.135872,0.317463,0.142680,...,0.181081,0.098526,0.029142,0.008614,0.215407,0.148432,0.172818,0.174280,0.200128,fail
10,0.067702,0.194344,0.097700,0.029496,0.104742,0.264907,0.140692,0.124288,0.268911,0.161572,...,0.181944,0.087876,0.026955,0.005634,0.221313,0.174372,0.161884,0.166865,0.138870,pass
11,0.060328,0.192078,0.093127,0.028466,0.083524,0.227318,0.116565,0.097780,0.225610,0.126042,...,0.145228,0.075160,0.022066,0.005110,0.146620,0.132463,0.127431,0.129092,0.115667,pass
12,0.064326,0.190189,0.096987,0.029467,0.079622,0.189851,0.096698,0.089369,0.201497,0.117680,...,0.148486,0.068654,0.017987,0.005082,0.156164,0.124040,0.120290,0.111028,0.120486,pass
13,0.046633,0.150694,0.076816,0.022422,0.082100,0.224709,0.118908,0.093814,0.225424,0.096828,...,0.170273,0.072898,0.022678,0.004180,0.155479,0.117877,0.123300,0.133256,0.088504,pass
14,0.069530,0.212423,0.110829,0.032432,0.092124,0.232533,0.117522,0.102857,0.233984,0.134039,...,0.163597,0.078190,0.023189,0.005659,0.148642,0.138658,0.133699,0.134353,0.129465,pass
15,0.082427,0.251397,0.120141,0.037011,0.097760,0.236595,0.123334,0.107605,0.230800,0.160057,...,0.163525,0.080165,0.025059,0.006694,0.169985,0.164051,0.139804,0.150934,0.156351,pass
16,0.083472,0.250312,0.129703,0.038173,0.098937,0.230218,0.115950,0.119001,0.270496,0.145130,...,0.209555,0.093147,0.023437,0.006551,0.211701,0.157223,0.162182,0.143566,0.155268,pass
17,0.077112,0.243578,0.123424,0.036287,0.090004,0.235478,0.118265,0.103332,0.245573,0.124837,...,0.188427,0.081838,0.023011,0.006321,0.183161,0.139724,0.140603,0.135433,0.142963,pass
18,0.072985,0.226184,0.112362,0.033755,0.101577,0.252932,0.132657,0.102719,0.224864,0.134647,...,0.141795,0.071608,0.025174,0.005765,0.169303,0.138250,0.128047,0.150691,0.134196,pass
19,0.079986,0.239419,0.112267,0.035764,0.100346,0.231423,0.128907,0.124717,0.261217,0.155566,...,0.146886,0.086559,0.024214,0.006906,0.198575,0.157445,0.156249,0.150463,0.165402,pass

[[1.19388059 1.20107954 1.18795856 1.16641535 1.19350142 1.1756112
  1.16680946 1.3106206  1.19861393 1.30571107 1.12926713 1.12490911
  1.2210943  1.14621576 1.23714168 1.2044424  1.23248588 1.17480871
  1.26054476 1.26707443 1.22721019 1.27861519]]
BARINEL SCORES

,cp 19,cp 20,cp 18,swap 11,h 21,cp 5,h 0,rzz 10,cp 13,cp 7,...,swap 8,x 4,h 2,cp 6,h 14,h 17,h 1,cp 9,h 3,h 12
sum,0.57336,0.570753,0.569797,0.569311,0.560008,0.558584,0.552898,0.549051,0.541617,0.535643,...,0.534676,0.533642,0.530922,0.529657,0.528967,0.528282,0.524641,0.508376,0.507737,0.501766

custom SCORES

,cp 19,cp 20,cp 18,cp 5,swap 11,h 0,h 21,cp 13,rzz 10,h 14,...,cp 16,cp 15,x 4,cp 6,swap 8,h 17,h 1,h 3,h 12,cp 9
sum,0.743642,0.742133,0.735952,0.730695,0.730037,0.729634,0.727154,0.703914,0.70346,0.702286,...,0.692316,0.690925,0.690374,0.689143,0.68789,0.685908,0.685602,0.667743,0.665557,0.66357

DSTAR SCORES

,rzz 10,swap 11,cp 20,cp 13,cp 9,cp 16,x 4,swap 8,h 0,h 2,...,cp 19,cp 15,h 12,h 14,h 17,cp 7,h 21,cp 18,cp 6,cp 5
sum,0.916786,0.768008,0.672993,0.642863,0.612188,0.581297,0.345232,0.311925,0.244589,0.218335,...,0.187906,0.172607,0.164313,0.129383,0.099396,0.07811,0.07511,0.017759,0.006772,0.000534

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_ccx_inGap_8_.qasm

100%|██████████| 10/10 [01:20<00:00,  8.09s/it]
100%|██████████| 10/10 [01:10<00:00,  7.01s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,swap 12,...,cp 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.078211,0.229173,0.113827,0.034510,0.105319,0.247687,0.131923,0.138550,0.303338,0.249372,...,0.207569,0.068532,0.019866,0.004526,0.170060,0.137336,0.126740,0.127290,0.128905,fail
1,0.084942,0.270962,0.135409,0.040086,0.100899,0.265772,0.136971,0.121449,0.276276,0.195208,...,0.168553,0.059861,0.019291,0.004687,0.154799,0.106679,0.106031,0.119832,0.125688,fail
2,0.059960,0.184308,0.093169,0.028184,0.071245,0.178825,0.092023,0.090610,0.223505,0.206872,...,0.157603,0.053374,0.013656,0.003250,0.129576,0.099146,0.092291,0.084964,0.091849,fail
3,0.076606,0.236999,0.118758,0.035212,0.089984,0.222935,0.117667,0.115647,0.269708,0.215234,...,0.167950,0.060556,0.017061,0.004268,0.142802,0.107642,0.109494,0.107203,0.116691,fail
4,0.085253,0.273123,0.136736,0.040896,0.108286,0.273639,0.142709,0.121166,0.279167,0.211723,...,0.196500,0.062901,0.021155,0.004605,0.164188,0.127122,0.112224,0.131738,0.125802,fail
5,0.070938,0.227499,0.113340,0.034219,0.095787,0.254597,0.136611,0.115589,0.277511,0.222714,...,0.194489,0.063626,0.019789,0.003968,0.163099,0.121929,0.109803,0.122409,0.111974,fail
6,0.083961,0.274354,0.134878,0.041334,0.100435,0.252065,0.133750,0.116916,0.279575,0.208974,...,0.182290,0.062962,0.019159,0.004614,0.157129,0.117035,0.112043,0.119165,0.123892,fail
7,0.073261,0.240064,0.117726,0.035556,0.089145,0.235447,0.125452,0.107129,0.260418,0.187159,...,0.166297,0.059244,0.017933,0.003963,0.144000,0.107410,0.104667,0.111989,0.109503,fail
8,0.081224,0.250438,0.126322,0.037776,0.090515,0.215405,0.113007,0.109262,0.242270,0.170053,...,0.151142,0.052103,0.015598,0.004337,0.132234,0.098980,0.093811,0.098283,0.115398,fail
9,0.086670,0.260743,0.130392,0.038859,0.105995,0.265702,0.135981,0.128308,0.271725,0.188667,...,0.197639,0.061557,0.020419,0.004760,0.156311,0.130728,0.113565,0.129480,0.133121,fail
10,0.074707,0.232299,0.114522,0.034543,0.096951,0.251434,0.133779,0.123940,0.292034,0.239686,...,0.211610,0.068381,0.020915,0.004136,0.170416,0.138242,0.123738,0.132636,0.119931,pass
11,0.077564,0.242295,0.122797,0.036686,0.107465,0.288778,0.147751,0.113431,0.272586,0.218855,...,0.200425,0.065911,0.022728,0.004051,0.165390,0.129202,0.115548,0.141447,0.116609,pass
12,0.081291,0.254854,0.129709,0.038523,0.086923,0.208501,0.107391,0.105599,0.252146,0.216366,...,0.156566,0.056558,0.014932,0.004438,0.142672,0.096832,0.098076,0.091647,0.117225,pass
13,0.065709,0.204343,0.103110,0.030538,0.097046,0.257641,0.137121,0.113807,0.263348,0.185572,...,0.174491,0.060384,0.020522,0.003754,0.149194,0.115274,0.109194,0.128676,0.108948,pass
14,0.090154,0.275432,0.139771,0.040796,0.095589,0.223940,0.118974,0.126411,0.281325,0.201274,...,0.162543,0.058149,0.016492,0.005018,0.139693,0.108770,0.109288,0.105660,0.132949,pass
15,0.071986,0.215326,0.107320,0.032859,0.085160,0.197633,0.103384,0.098036,0.209370,0.161128,...,0.160347,0.047924,0.015261,0.003838,0.130719,0.103605,0.087052,0.097619,0.105234,pass
16,0.095529,0.287481,0.144975,0.043069,0.107901,0.238645,0.125075,0.130048,0.281677,0.219209,...,0.165371,0.059608,0.017608,0.005270,0.152286,0.110731,0.110706,0.111875,0.139227,pass
17,0.068340,0.208137,0.101697,0.029474,0.072655,0.187918,0.098736,0.105472,0.243496,0.190467,...,0.155659,0.054374,0.014602,0.003673,0.135635,0.102316,0.098101,0.093745,0.104545,pass
18,0.093661,0.295664,0.145333,0.043141,0.093450,0.241671,0.127344,0.118190,0.276255,0.205721,...,0.156339,0.057388,0.017737,0.005031,0.143250,0.101921,0.104372,0.110121,0.132129,pass
19,0.058960,0.184891,0.086700,0.026249,0.067687,0.174289,0.092610,0.091403,0.207951,0.167512,...,0.164636,0.050026,0.014211,0.003150,0.126299,0.108492,0.089145,0.090180,0.091221,pass

[[1.10968709 1.12088267 1.12027704 1.1274018  1.13079421 1.1344532
  1.12715972 1.18965081 1.13038582 1.2129131  1.10039048 1.20242493
  1.12643345 1.1595821  1.1332946  1.15016865 1.10765329 1.12309934
  1.19007991 1.17279577 1.14320683 1.12544818]]
BARINEL SCORES

,cp 16,cp 15,swap 9,h 17,cp 6,cp 8,cp 7,h 1,ccx 11,x 4,...,h 14,h 2,cp 18,h 10,swap 12,cp 19,cp 20,cp 5,h 0,h 21
sum,0.515123,0.515037,0.513358,0.512519,0.512423,0.511727,0.510991,0.510804,0.510471,0.509874,...,0.508357,0.508338,0.507443,0.5074,0.506178,0.505094,0.504841,0.503632,0.503149,0.501003

custom SCORES

,cp 16,cp 15,cp 8,h 10,h 3,cp 6,swap 12,h 14,swap 9,h 17,...,cp 7,cp 13,x 4,ccx 11,cp 18,cp 19,cp 20,h 0,cp 5,h 21
sum,0.661218,0.660169,0.660075,0.659927,0.659801,0.659766,0.659665,0.659549,0.657923,0.657407,...,0.655767,0.653884,0.653033,0.650901,0.650466,0.646556,0.646308,0.644716,0.643095,0.639992

DSTAR SCORES

,ccx 11,cp 13,cp 20,cp 16,swap 9,swap 12,cp 8,x 4,cp 15,cp 19,...,h 3,h 1,h 2,h 17,h 10,h 21,cp 7,cp 18,cp 6,cp 5
sum,1.285921,0.572419,0.483122,0.474155,0.419437,0.352083,0.273678,0.200147,0.143225,0.133062,...,0.11981,0.119594,0.105733,0.084046,0.078782,0.056598,0.034568,0.01298,0.003325,0.000184

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_p_inGap_9_.qasm

100%|██████████| 10/10 [00:45<00:00,  4.59s/it]
100%|██████████| 10/10 [00:47<00:00,  4.73s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,p 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.080512,0.258295,0.127794,0.039143,0.089228,0.225988,0.119584,0.101078,0.369536,0.236979,...,0.179497,0.080323,0.023343,0.006356,0.183337,0.149442,0.148320,0.137682,0.146425,fail
1,0.049178,0.151464,0.075563,0.023036,0.076123,0.214531,0.105943,0.082833,0.349500,0.218245,...,0.185617,0.073940,0.020077,0.003508,0.159622,0.141030,0.134177,0.118828,0.082749,fail
2,0.064054,0.206625,0.104640,0.030733,0.084363,0.228777,0.118875,0.108816,0.404705,0.265550,...,0.184662,0.085461,0.021911,0.005533,0.171477,0.134507,0.157430,0.128273,0.125273,fail
3,0.081693,0.248838,0.128308,0.038348,0.101194,0.238223,0.123066,0.122870,0.447718,0.280835,...,0.206897,0.096068,0.024465,0.006865,0.196772,0.161710,0.176926,0.144249,0.157388,fail
4,0.049811,0.151370,0.079557,0.023029,0.074068,0.192565,0.098346,0.101951,0.392159,0.241988,...,0.188467,0.082028,0.018796,0.004163,0.185221,0.144788,0.153316,0.115677,0.099971,fail
5,0.059580,0.179634,0.090586,0.026314,0.070502,0.173805,0.091492,0.096984,0.355289,0.223745,...,0.159929,0.075148,0.018181,0.004939,0.149509,0.127791,0.139677,0.108647,0.118183,fail
6,0.081951,0.245541,0.128264,0.037735,0.095792,0.220237,0.110772,0.122833,0.443931,0.271707,...,0.201678,0.095849,0.022645,0.006927,0.193399,0.160948,0.175534,0.135326,0.161130,fail
7,0.093126,0.284153,0.145796,0.042245,0.098068,0.243909,0.121272,0.127299,0.461695,0.293149,...,0.196099,0.095887,0.022834,0.007500,0.199727,0.152047,0.181194,0.138034,0.179098,fail
8,0.088455,0.275330,0.141612,0.041471,0.103328,0.261412,0.133254,0.112806,0.382056,0.250290,...,0.142431,0.080704,0.024709,0.007072,0.183038,0.138073,0.150095,0.147541,0.166478,fail
9,0.066453,0.206582,0.107788,0.030520,0.089786,0.228541,0.119408,0.127508,0.480086,0.301000,...,0.245511,0.103297,0.023625,0.006138,0.209575,0.162621,0.190464,0.140081,0.137652,fail
10,0.076349,0.244454,0.124168,0.036060,0.095626,0.256877,0.129757,0.107761,0.390932,0.262094,...,0.164003,0.081672,0.022916,0.006042,0.197224,0.133274,0.152659,0.136297,0.142578,pass
11,0.060388,0.194336,0.096504,0.028384,0.070169,0.194257,0.095203,0.079157,0.305191,0.190901,...,0.142798,0.066066,0.018450,0.004567,0.152577,0.122492,0.120748,0.108286,0.105930,pass
12,0.071300,0.235116,0.114985,0.033684,0.082032,0.226627,0.116493,0.099328,0.379583,0.249538,...,0.188892,0.083522,0.022207,0.005916,0.164009,0.129162,0.147912,0.127255,0.129253,pass
13,0.055387,0.177887,0.091070,0.026335,0.065094,0.174967,0.087568,0.067168,0.237683,0.155091,...,0.102484,0.049528,0.016694,0.004370,0.122013,0.084152,0.093198,0.097279,0.100263,pass
14,0.066252,0.193101,0.097743,0.030052,0.095082,0.223500,0.116252,0.106618,0.365726,0.224003,...,0.134973,0.073954,0.022544,0.005582,0.163888,0.136910,0.141288,0.134607,0.133531,pass
15,0.050270,0.162200,0.084219,0.023953,0.055232,0.147865,0.074807,0.066646,0.250510,0.165420,...,0.128220,0.053459,0.013933,0.003982,0.130526,0.081180,0.100404,0.082898,0.092707,pass
16,0.079825,0.248071,0.124979,0.037661,0.094583,0.217801,0.115695,0.110308,0.381027,0.243313,...,0.153883,0.078865,0.021729,0.006605,0.190018,0.136821,0.151811,0.133604,0.155355,pass
17,0.091844,0.284621,0.143282,0.042997,0.085052,0.196360,0.102067,0.104467,0.341633,0.217865,...,0.118144,0.071932,0.019688,0.007368,0.176384,0.122693,0.140167,0.121157,0.179653,pass
18,0.075872,0.248872,0.128101,0.037273,0.079781,0.205949,0.099547,0.078621,0.289244,0.188199,...,0.149010,0.062957,0.019570,0.005658,0.156252,0.115299,0.115834,0.115319,0.131011,pass
19,0.078755,0.240759,0.121042,0.036708,0.090152,0.212743,0.110792,0.109030,0.383594,0.239496,...,0.173744,0.085209,0.022421,0.006605,0.158254,0.149135,0.154680,0.129852,0.154075,pass

[[1.3027983  1.28702341 1.29033372 1.27024354 1.17091936 1.17330957
  1.16683219 1.15394032 1.17475928 1.16508931 1.12697156 1.22520348
  1.12783619 1.29845897 1.1890863  1.1201576  1.27114866 1.14416933
  1.10404462 1.18511673 1.12255071 1.30314898]]
BARINEL SCORES

,swap 8,p 13,cp 7,h 2,h 3,cp 9,cp 12,h 14,h 11,x 4,...,cp 15,h 17,cp 16,swap 10,cp 5,h 0,h 21,cp 19,cp 18,cp 20
sum,0.564931,0.551374,0.551255,0.54929,0.548777,0.548078,0.547418,0.543232,0.541447,0.532028,...,0.52142,0.520542,0.519959,0.51912,0.50996,0.509262,0.503016,0.500846,0.499599,0.497568

custom SCORES

,swap 8,cp 7,p 13,h 2,cp 12,cp 9,h 3,h 14,h 11,x 4,...,cp 15,h 1,h 17,cp 16,cp 5,cp 6,h 21,cp 19,cp 18,cp 20
sum,0.748315,0.715127,0.713307,0.712034,0.706866,0.702613,0.700245,0.699946,0.693996,0.684211,...,0.673523,0.673036,0.67292,0.672477,0.672019,0.671105,0.666848,0.66241,0.658252,0.657663

DSTAR SCORES

,p 13,cp 9,cp 12,swap 10,cp 16,cp 20,swap 8,x 4,h 2,h 3,...,h 1,cp 15,cp 19,h 14,h 17,cp 7,h 21,cp 18,cp 6,cp 5
sum,1.25334,0.610418,0.549972,0.497418,0.411707,0.39859,0.312066,0.28895,0.228195,0.193523,...,0.154425,0.118046,0.114748,0.111718,0.072018,0.070481,0.047725,0.010704,0.00477,0.000346

ERROR GATE LOCATION:
13
Now evolving the following mutant:  AddGate_swap_inGap_8_.qasm

100%|██████████| 10/10 [00:50<00:00,  5.08s/it]
100%|██████████| 10/10 [00:49<00:00,  4.96s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.103467,0.321501,0.158848,0.048456,0.109076,0.257174,0.135219,0.143541,0.333756,0.178169,...,0.209654,0.093148,0.029545,0.007917,0.227463,0.180952,0.169148,0.174918,0.190252,fail
1,0.058419,0.179041,0.095077,0.026994,0.083128,0.221240,0.109538,0.103018,0.241149,0.124672,...,0.162033,0.076534,0.021779,0.004581,0.166090,0.136011,0.134235,0.125212,0.106211,fail
2,0.074943,0.219240,0.114409,0.033193,0.088665,0.197534,0.101964,0.116561,0.247682,0.132783,...,0.165520,0.074944,0.022877,0.006089,0.180791,0.138557,0.135861,0.136233,0.143857,fail
3,0.072101,0.211466,0.108935,0.032006,0.089261,0.206061,0.105318,0.106354,0.222140,0.138544,...,0.143654,0.077920,0.020757,0.005535,0.173193,0.139674,0.141331,0.123396,0.132549,fail
4,0.078090,0.226268,0.113920,0.034509,0.095002,0.206907,0.113008,0.133899,0.274676,0.163944,...,0.169686,0.079652,0.025191,0.006436,0.195942,0.160442,0.149706,0.153200,0.156990,fail
5,0.102065,0.315795,0.158045,0.046693,0.103184,0.241366,0.125831,0.135673,0.292930,0.152659,...,0.190693,0.091147,0.027004,0.008306,0.197492,0.153010,0.159404,0.157696,0.191968,fail
6,0.061693,0.186209,0.093867,0.028502,0.078141,0.191521,0.097424,0.100071,0.224775,0.133608,...,0.133320,0.065222,0.019926,0.004781,0.166144,0.134472,0.120672,0.119596,0.117486,fail
7,0.077046,0.235770,0.118091,0.034764,0.097013,0.248210,0.123350,0.106931,0.235386,0.138978,...,0.129043,0.080648,0.020899,0.005908,0.166793,0.135877,0.146112,0.123126,0.139874,fail
8,0.088778,0.281376,0.143042,0.041625,0.097006,0.249692,0.124743,0.110482,0.260576,0.136775,...,0.160528,0.082446,0.022748,0.006662,0.189053,0.139061,0.147511,0.131992,0.157304,fail
9,0.061735,0.180535,0.089272,0.027376,0.072536,0.161838,0.086981,0.102187,0.219293,0.114988,...,0.134267,0.061396,0.020293,0.005295,0.140829,0.117344,0.111356,0.120287,0.124216,fail
10,0.056421,0.180798,0.089179,0.026720,0.064541,0.178484,0.089656,0.062623,0.159155,0.090915,...,0.092811,0.055339,0.013468,0.003830,0.123391,0.092457,0.100364,0.078548,0.091114,pass
11,0.067195,0.207332,0.105798,0.030847,0.084650,0.214185,0.110114,0.090483,0.205164,0.104730,...,0.124070,0.073201,0.017996,0.005072,0.159149,0.110724,0.131596,0.105082,0.117991,pass
12,0.054056,0.163775,0.079168,0.024450,0.068890,0.168677,0.090670,0.084477,0.198617,0.103340,...,0.108777,0.057505,0.016833,0.004278,0.134952,0.105666,0.106136,0.100669,0.101926,pass
13,0.095843,0.290675,0.146022,0.045031,0.122339,0.295535,0.153512,0.127964,0.270180,0.176845,...,0.151232,0.100889,0.023475,0.007158,0.197225,0.167687,0.185642,0.141594,0.173647,pass
14,0.086142,0.277995,0.141830,0.042378,0.103224,0.268264,0.138348,0.094782,0.238398,0.098424,...,0.118397,0.082172,0.019025,0.006419,0.162659,0.098043,0.144256,0.108148,0.144738,pass
15,0.082938,0.253622,0.123599,0.036921,0.095926,0.253417,0.127759,0.114383,0.251801,0.142115,...,0.150727,0.086793,0.022754,0.006436,0.184677,0.145453,0.155243,0.134729,0.153647,pass
16,0.096990,0.302176,0.146072,0.044421,0.101919,0.246939,0.131512,0.125416,0.260486,0.173675,...,0.157973,0.093493,0.023807,0.007561,0.185547,0.164945,0.166960,0.141889,0.180539,pass
17,0.044474,0.134281,0.071035,0.020864,0.071741,0.184552,0.094557,0.079681,0.177812,0.094266,...,0.102696,0.059513,0.015210,0.003693,0.130098,0.098396,0.108940,0.090495,0.086449,pass
18,0.066050,0.221011,0.109964,0.032129,0.081356,0.223709,0.113012,0.085219,0.224653,0.115093,...,0.152189,0.076000,0.019241,0.004864,0.158938,0.127278,0.131652,0.108387,0.107845,pass
19,0.052340,0.159931,0.076346,0.023652,0.073090,0.176330,0.095808,0.092953,0.212035,0.116869,...,0.144305,0.066715,0.018997,0.004069,0.146136,0.124816,0.121248,0.111324,0.095189,pass

[[1.32933227 1.36390918 1.3309362  1.36836015 1.1946811  1.17886343
  1.2036822  1.23878933 1.30763351 1.25903891 1.29560319 1.19930064
  1.36346636 1.3116481  1.18953625 1.27889144 1.35042032 1.26102619
  1.2606397  1.19510691 1.28083327 1.31421282]]
BARINEL SCORES

,swap 8,h 1,swap 9,cp 6,h 14,h 0,h 12,h 3,cp 13,cp 5,...,h 21,cp 19,cp 18,cp 20,h 17,h 2,cp 7,cp 16,cp 15,swap 11
sum,0.550873,0.549223,0.548595,0.547664,0.547417,0.538253,0.537784,0.537429,0.537265,0.535385,...,0.525624,0.52289,0.519593,0.518203,0.512729,0.511436,0.510243,0.49675,0.495245,0.49443

custom SCORES

,swap 9,swap 8,h 1,cp 6,h 14,cp 5,h 0,cp 13,h 12,h 3,...,cp 18,cp 19,cp 20,cp 10,h 17,h 2,cp 7,swap 11,cp 15,cp 16
sum,0.735592,0.73151,0.725089,0.722764,0.716951,0.716133,0.715098,0.712901,0.707056,0.706805,...,0.697341,0.696873,0.694899,0.683753,0.665867,0.664242,0.661981,0.654576,0.644274,0.64315

DSTAR SCORES

,cp 10,cp 13,cp 20,swap 11,cp 16,swap 9,x 4,swap 8,h 0,h 3,...,h 1,cp 19,h 14,cp 15,h 17,cp 7,h 21,cp 18,cp 6,cp 5
sum,0.589049,0.534055,0.455756,0.425873,0.38977,0.281409,0.280905,0.226032,0.189607,0.183381,...,0.167704,0.128457,0.122525,0.113233,0.076704,0.057031,0.056605,0.012143,0.005237,0.000376

ERROR GATE LOCATION:
9
Now evolving the following mutant:  AddGate_h_inGap_1_.qasm

100%|██████████| 10/10 [00:52<00:00,  5.27s/it]
100%|██████████| 10/10 [00:47<00:00,  4.72s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,cp 8,cp 7,cp 6,x 5,h 4,h 3,h 2,h 1,h 0,pass/fail
0,0.080375,0.260943,0.132388,0.038957,0.091146,0.230488,0.121447,0.116556,0.283049,0.127445,...,0.092406,0.022755,0.006829,0.208696,0.144970,0.158839,0.134234,0.155373,0.170762,fail
1,0.091658,0.293930,0.143457,0.043327,0.098031,0.254118,0.134937,0.122333,0.295328,0.139832,...,0.098406,0.025786,0.007675,0.212807,0.155713,0.167458,0.152073,0.173400,0.189721,fail
2,0.078443,0.253469,0.128546,0.037640,0.091936,0.249140,0.128725,0.111535,0.282977,0.132070,...,0.093895,0.024547,0.006370,0.217315,0.159142,0.157744,0.146074,0.142826,0.156316,fail
3,0.097732,0.307660,0.154106,0.045869,0.116167,0.299679,0.157816,0.142096,0.326865,0.158713,...,0.108933,0.029863,0.008338,0.216449,0.169781,0.185265,0.174218,0.189869,0.207411,fail
4,0.053824,0.178041,0.091403,0.026325,0.076310,0.198907,0.103816,0.082018,0.189873,0.101376,...,0.065451,0.021695,0.004760,0.128654,0.116333,0.107567,0.122256,0.098087,0.107257,fail
5,0.095183,0.296588,0.147245,0.043993,0.116314,0.297187,0.153541,0.133060,0.318876,0.166595,...,0.105582,0.029661,0.007267,0.255813,0.187676,0.184571,0.180994,0.171362,0.187923,fail
6,0.089108,0.283723,0.146782,0.042759,0.117315,0.311861,0.160152,0.126575,0.285505,0.141936,...,0.089430,0.029637,0.007221,0.225482,0.154651,0.158529,0.178003,0.166378,0.182343,fail
7,0.102888,0.317673,0.163183,0.047781,0.116810,0.277122,0.144588,0.133964,0.291032,0.140986,...,0.093446,0.026742,0.008473,0.221523,0.145060,0.166670,0.163316,0.197784,0.217453,fail
8,0.083708,0.267471,0.134298,0.039515,0.087111,0.228405,0.116647,0.108497,0.255024,0.123920,...,0.085336,0.022450,0.006651,0.203235,0.138471,0.147104,0.134934,0.154791,0.169271,fail
9,0.103230,0.315235,0.162340,0.047878,0.115639,0.275654,0.141435,0.130965,0.288667,0.153499,...,0.092468,0.025994,0.008117,0.219034,0.157559,0.166176,0.160639,0.194899,0.213895,fail
10,0.086858,0.263883,0.126587,0.038809,0.102236,0.248778,0.134775,0.131846,0.297509,0.149882,...,0.099946,0.025565,0.007133,0.214064,0.159304,0.174421,0.155521,0.168816,0.185771,pass
11,0.051971,0.164293,0.082028,0.024456,0.070925,0.193426,0.098462,0.091573,0.235297,0.111565,...,0.077452,0.017825,0.004317,0.156441,0.129196,0.130384,0.105985,0.100647,0.109843,pass
12,0.056082,0.174987,0.088941,0.026303,0.080351,0.214930,0.110593,0.097063,0.229826,0.116819,...,0.075775,0.020876,0.004852,0.154929,0.130167,0.129831,0.121637,0.109408,0.119945,pass
13,0.061608,0.197753,0.097696,0.029211,0.069880,0.179947,0.091225,0.081544,0.192010,0.103830,...,0.062441,0.016697,0.004972,0.145435,0.111408,0.109659,0.101531,0.115641,0.126449,pass
14,0.066275,0.204111,0.102488,0.030036,0.084994,0.219210,0.115849,0.107998,0.233545,0.128781,...,0.079425,0.023081,0.005439,0.194444,0.144664,0.141922,0.140944,0.128364,0.141221,pass
15,0.043750,0.130989,0.064503,0.018884,0.075127,0.205933,0.106910,0.095615,0.225122,0.110274,...,0.075090,0.020488,0.003831,0.144384,0.126691,0.127675,0.121318,0.089351,0.097870,pass
16,0.055118,0.164661,0.077663,0.023969,0.073142,0.191356,0.103913,0.105494,0.248019,0.120814,...,0.080375,0.018875,0.004767,0.178352,0.136118,0.141459,0.117539,0.112646,0.123657,pass
17,0.053628,0.168716,0.081242,0.025196,0.082401,0.210855,0.109359,0.085735,0.202825,0.108321,...,0.065443,0.020551,0.004456,0.140783,0.119265,0.114274,0.121475,0.100750,0.110917,pass
18,0.080482,0.243530,0.124298,0.036782,0.098618,0.227089,0.119800,0.123118,0.261410,0.140260,...,0.089575,0.023594,0.006827,0.192337,0.147201,0.157213,0.143082,0.158472,0.174612,pass
19,0.076678,0.243779,0.122203,0.037456,0.104085,0.262877,0.141871,0.111996,0.263758,0.126561,...,0.080715,0.025005,0.006313,0.181700,0.130738,0.140775,0.149923,0.144905,0.158619,pass

[[1.17822419 1.14487912 1.16247918 1.15634872 1.14255807 1.18914698
  1.17491039 1.17667883 1.16025076 1.20166143 1.14061318 1.17479647
  1.24311606 1.17719975 1.15241    1.18165808 1.21295326 1.22715535
  1.15796041 1.17016229 1.2025044  1.20649548]]
BARINEL SCORES

,cp 19,cp 18,cp 20,h 21,cp 6,swap 11,h 1,h 0,x 5,swap 9,...,cp 16,h 2,cp 15,cp 13,cp 8,h 14,h 3,h 4,h 12,cp 10
sum,0.59195,0.587174,0.586446,0.58077,0.575411,0.573333,0.572339,0.571947,0.553273,0.550089,...,0.549002,0.547384,0.546146,0.54109,0.540639,0.539207,0.539142,0.533973,0.532508,0.529115

custom SCORES

,cp 19,cp 18,cp 20,h 21,cp 6,h 0,h 1,swap 11,x 5,swap 9,...,h 2,cp 15,h 17,cp 8,cp 13,h 14,h 4,h 3,h 12,cp 10
sum,0.763982,0.756919,0.754299,0.751839,0.745396,0.74446,0.744399,0.736821,0.721046,0.721045,...,0.707516,0.706564,0.706471,0.699749,0.69804,0.697826,0.69779,0.695218,0.692481,0.684516

DSTAR SCORES

,swap 11,cp 10,cp 20,cp 13,cp 16,x 5,swap 9,h 0,h 1,h 3,...,cp 19,h 12,cp 15,h 14,h 17,cp 8,h 21,cp 18,cp 7,cp 6
sum,0.814269,0.644203,0.643919,0.640599,0.565871,0.38007,0.336773,0.286237,0.240918,0.22518,...,0.179666,0.171348,0.1669,0.132188,0.097242,0.079386,0.072198,0.016658,0.006575,0.000511

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_cswap_inGap_6_.qasm

100%|██████████| 10/10 [01:00<00:00,  6.09s/it]
100%|██████████| 10/10 [00:57<00:00,  5.76s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,swap 12,...,cp 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.105034,0.330482,0.169153,0.049628,0.118075,0.281709,0.145868,0.136081,0.293625,0.190808,...,0.208614,0.073203,0.022618,0.007000,0.171269,0.139269,0.144624,0.140632,0.166396,fail
1,0.070490,0.217194,0.106734,0.033495,0.095946,0.240992,0.125510,0.106641,0.239297,0.185467,...,0.183805,0.061525,0.018567,0.004580,0.140359,0.119787,0.117832,0.114705,0.109894,fail
2,0.102886,0.313405,0.154228,0.047677,0.104351,0.235194,0.123713,0.120930,0.262542,0.182553,...,0.181591,0.063972,0.018351,0.006421,0.144631,0.123265,0.125659,0.115551,0.157682,fail
3,0.081740,0.246447,0.119724,0.036501,0.097978,0.237433,0.123077,0.116198,0.262635,0.215049,...,0.183523,0.062887,0.018216,0.004863,0.149493,0.124272,0.123806,0.115833,0.123558,fail
4,0.057359,0.173997,0.089700,0.026454,0.089059,0.233390,0.123247,0.116436,0.278967,0.237798,...,0.199929,0.067727,0.018448,0.003787,0.152881,0.129413,0.129367,0.114923,0.090967,fail
5,0.074521,0.223625,0.108782,0.033773,0.106402,0.259548,0.136525,0.114351,0.245211,0.173978,...,0.189735,0.063029,0.020678,0.004594,0.155392,0.129810,0.125879,0.131923,0.113943,fail
6,0.087571,0.264648,0.134577,0.040058,0.114280,0.267674,0.140799,0.130094,0.286478,0.218102,...,0.202762,0.069138,0.021228,0.005592,0.167605,0.136643,0.137021,0.134706,0.135300,fail
7,0.093578,0.296661,0.148865,0.043691,0.106015,0.265855,0.141334,0.135780,0.305828,0.227228,...,0.217371,0.075510,0.021945,0.006300,0.172725,0.141674,0.146488,0.135130,0.150072,fail
8,0.088214,0.273820,0.134522,0.040835,0.101984,0.239135,0.129570,0.129710,0.291751,0.212043,...,0.194665,0.069150,0.019352,0.005951,0.158609,0.131017,0.137754,0.121407,0.143054,fail
9,0.056842,0.170636,0.080671,0.025237,0.062137,0.150788,0.080861,0.095949,0.229364,0.207659,...,0.158771,0.055582,0.011896,0.003552,0.127149,0.105941,0.106940,0.077574,0.089513,fail
10,0.037788,0.114523,0.057751,0.016709,0.058989,0.154754,0.077598,0.069444,0.158328,0.125379,...,0.120523,0.040197,0.011361,0.002366,0.097079,0.080147,0.079730,0.073263,0.058494,pass
11,0.064313,0.203662,0.099386,0.030126,0.079808,0.200687,0.109349,0.101339,0.241529,0.195070,...,0.175132,0.060899,0.017121,0.004449,0.135124,0.111986,0.115894,0.104145,0.104475,pass
12,0.076130,0.234362,0.114959,0.035294,0.097102,0.243051,0.129707,0.112826,0.252806,0.188607,...,0.183686,0.062017,0.019454,0.004827,0.143068,0.119360,0.119859,0.120128,0.117099,pass
13,0.056563,0.170302,0.085551,0.024267,0.092058,0.242673,0.128186,0.122150,0.284564,0.223985,...,0.182169,0.065062,0.018622,0.003828,0.149965,0.121632,0.128215,0.118431,0.093077,pass
14,0.067949,0.208162,0.101127,0.030219,0.070694,0.170362,0.087630,0.088240,0.205222,0.168799,...,0.141280,0.050327,0.013113,0.004204,0.116485,0.093554,0.097381,0.083579,0.103879,pass
15,0.082877,0.251631,0.124121,0.037612,0.106170,0.260254,0.135566,0.123103,0.259899,0.172047,...,0.182246,0.063867,0.020056,0.005348,0.146564,0.125563,0.127430,0.126442,0.130726,pass
16,0.060685,0.181595,0.090779,0.027508,0.084207,0.203884,0.109096,0.097509,0.221867,0.170382,...,0.150262,0.052026,0.015842,0.003802,0.123723,0.102125,0.103445,0.100181,0.093284,pass
17,0.084371,0.280708,0.134465,0.040191,0.081316,0.219313,0.115606,0.100850,0.245921,0.183724,...,0.180588,0.061390,0.017422,0.005473,0.151836,0.114769,0.116564,0.106219,0.129169,pass
18,0.098692,0.299913,0.158215,0.046587,0.130881,0.322499,0.165756,0.147121,0.318360,0.210488,...,0.220161,0.077285,0.024346,0.006427,0.180470,0.149860,0.153804,0.154161,0.154684,pass
19,0.095981,0.289813,0.146390,0.043386,0.113937,0.268906,0.138944,0.146453,0.306954,0.221210,...,0.213125,0.075210,0.020690,0.006203,0.172034,0.145884,0.147809,0.133047,0.153603,pass

[[1.28366702 1.31618289 1.35652912 1.31517732 1.18521975 1.16808272
  1.14811154 1.13195998 1.13450532 1.15960272 1.05799468 1.25154337
  1.15328272 1.13168952 1.14111253 1.18233916 1.32976061 1.12150962
  1.10588931 1.1308572  1.1696118  1.29958094]]
BARINEL SCORES

,cp 18,h 11,h 21,h 0,cp 20,cp 5,cp 19,swap 12,cswap 9,h 3,...,h 17,h 2,cp 7,x 4,h 14,cp 13,cp 6,h 1,cp 15,cp 16
sum,0.53204,0.531573,0.530088,0.52933,0.529105,0.528694,0.528438,0.524422,0.52407,0.523755,...,0.521206,0.52117,0.521041,0.520931,0.520149,0.519288,0.517968,0.517827,0.514803,0.513339

custom SCORES

,cp 19,cp 18,cp 5,cp 20,h 0,h 21,swap 10,swap 12,h 17,cswap 9,...,cp 6,cp 7,h 1,h 3,h 2,h 14,x 4,cp 13,cp 16,cp 15
sum,0.707649,0.706972,0.704453,0.703205,0.701307,0.700202,0.68556,0.676452,0.675642,0.67517,...,0.671071,0.669683,0.669241,0.668559,0.668513,0.667346,0.666989,0.666571,0.663245,0.662566

DSTAR SCORES

,cswap 9,cp 13,cp 20,swap 10,cp 16,swap 12,cp 8,x 4,h 11,h 2,...,cp 15,cp 19,h 14,h 1,h 17,h 21,cp 7,cp 18,cp 6,cp 5
sum,1.238431,0.581555,0.515314,0.479435,0.473401,0.354589,0.314009,0.207768,0.162446,0.149952,...,0.144156,0.139921,0.130094,0.130016,0.090926,0.062423,0.041277,0.013782,0.003596,0.000276

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_cz_inGap_7_.qasm

100%|██████████| 10/10 [00:56<00:00,  5.67s/it]
100%|██████████| 10/10 [00:58<00:00,  5.81s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,swap 12,...,cp 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.065625,0.199392,0.105059,0.029137,0.084439,0.218092,0.111708,0.108972,0.265721,0.227368,...,0.237893,0.084984,0.023976,0.004773,0.197510,0.192057,0.154837,0.183339,0.118957,fail
1,0.073102,0.227866,0.112437,0.033206,0.094781,0.242292,0.129715,0.121768,0.270438,0.184003,...,0.250635,0.087320,0.027491,0.005864,0.201555,0.206678,0.163033,0.206702,0.139685,fail
2,0.093918,0.293337,0.141430,0.043546,0.114562,0.294122,0.151724,0.127026,0.293391,0.218188,...,0.279770,0.091529,0.031150,0.007058,0.223210,0.227199,0.171662,0.232612,0.171129,fail
3,0.065640,0.199788,0.101229,0.030685,0.100874,0.258780,0.133293,0.109581,0.258634,0.210185,...,0.246687,0.083978,0.028435,0.005101,0.197472,0.200993,0.154621,0.206891,0.121462,fail
4,0.077855,0.251932,0.122215,0.036928,0.100675,0.265293,0.137806,0.109804,0.260770,0.202129,...,0.248875,0.086281,0.029416,0.006157,0.191461,0.195683,0.153025,0.206746,0.138326,fail
5,0.077017,0.246536,0.117698,0.036025,0.111460,0.303017,0.161939,0.135568,0.320720,0.240139,...,0.285010,0.103822,0.033983,0.006208,0.226923,0.231207,0.188303,0.244210,0.148125,fail
6,0.073132,0.231854,0.112297,0.034137,0.092645,0.240015,0.123621,0.107575,0.260128,0.218977,...,0.263378,0.083923,0.026591,0.005726,0.189840,0.200414,0.151751,0.196976,0.133878,fail
7,0.078079,0.240188,0.119116,0.035626,0.101712,0.256719,0.136101,0.118002,0.277480,0.208878,...,0.270527,0.089213,0.028641,0.006156,0.206961,0.212310,0.160906,0.209327,0.142233,fail
8,0.065347,0.204501,0.098373,0.030485,0.091460,0.242756,0.126305,0.110096,0.275127,0.244505,...,0.256524,0.088840,0.026500,0.004973,0.194544,0.199278,0.159941,0.198220,0.119556,fail
9,0.058948,0.182638,0.094450,0.026736,0.093015,0.245893,0.128893,0.112604,0.259137,0.193130,...,0.241029,0.083171,0.027688,0.004779,0.195361,0.195167,0.153901,0.200143,0.113692,fail
10,0.076725,0.237368,0.119550,0.035556,0.100078,0.265873,0.135105,0.112842,0.267421,0.212294,...,0.261153,0.085248,0.028872,0.005878,0.213124,0.212364,0.158485,0.214908,0.143608,pass
11,0.076624,0.235584,0.121730,0.035216,0.105096,0.277002,0.138568,0.118078,0.272176,0.197113,...,0.233741,0.084761,0.028570,0.005680,0.217448,0.209366,0.161020,0.215182,0.141775,pass
12,0.073654,0.216673,0.109335,0.033395,0.075097,0.160173,0.087259,0.108483,0.239550,0.195356,...,0.226127,0.076629,0.018404,0.005472,0.189906,0.188279,0.145399,0.163780,0.137375,pass
13,0.078418,0.247850,0.120699,0.035868,0.092293,0.240626,0.122813,0.106627,0.235332,0.162942,...,0.255604,0.078368,0.026915,0.005998,0.182816,0.195142,0.143085,0.194904,0.143258,pass
14,0.045386,0.137937,0.067744,0.020308,0.066237,0.164099,0.086624,0.086363,0.192307,0.163794,...,0.215010,0.067760,0.020135,0.003852,0.142243,0.155516,0.120786,0.150938,0.088377,pass
15,0.112158,0.351666,0.181184,0.052366,0.140474,0.370722,0.191232,0.163538,0.372457,0.263043,...,0.351233,0.119436,0.040666,0.008588,0.259738,0.280782,0.217716,0.290053,0.206540,pass
16,0.083842,0.247119,0.126686,0.038042,0.105208,0.235097,0.127392,0.122187,0.246278,0.150814,...,0.245081,0.076820,0.026495,0.006605,0.210723,0.211664,0.151335,0.207205,0.162733,pass
17,0.075582,0.237090,0.122045,0.036284,0.094993,0.245806,0.124642,0.106162,0.239985,0.175196,...,0.255205,0.078472,0.027047,0.005717,0.189611,0.195957,0.143878,0.198291,0.136783,pass
18,0.070185,0.213248,0.110465,0.031872,0.094551,0.241081,0.122362,0.111345,0.236093,0.161606,...,0.246378,0.078724,0.027441,0.005395,0.181124,0.196784,0.146583,0.199341,0.134887,pass
19,0.060623,0.195593,0.104675,0.029450,0.087990,0.242186,0.126487,0.111275,0.269732,0.211342,...,0.266431,0.087428,0.027257,0.005029,0.195344,0.200777,0.155186,0.196686,0.116829,pass

[[1.28890371 1.28767703 1.257935   1.29403747 1.16233281 1.18044377
  1.20750844 1.16769114 1.16985127 1.13855581 1.1932073  1.13547345
  1.22636581 1.10454864 1.17570568 1.19713463 1.24268675 1.12069832
  1.12182957 1.16814599 1.17117879 1.27040577]]
BARINEL SCORES

,swap 12,cz 10,swap 9,cp 13,cp 15,cp 7,cp 16,cp 6,h 2,h 1,...,h 14,cp 8,h 3,cp 20,cp 5,h 11,h 21,cp 18,h 0,cp 19
sum,0.531428,0.51903,0.51705,0.516019,0.515098,0.514392,0.512407,0.51086,0.510855,0.506545,...,0.503054,0.502372,0.501747,0.495422,0.493836,0.492284,0.491722,0.491351,0.488199,0.487046

custom SCORES

,swap 12,swap 9,cp 15,cp 13,cz 10,cp 7,cp 6,cp 16,h 2,cp 20,...,cp 18,h 21,h 14,cp 5,x 4,h 0,h 3,cp 8,cp 19,h 11
sum,0.682693,0.675574,0.670594,0.666936,0.666366,0.665586,0.663752,0.663625,0.660044,0.654908,...,0.650308,0.650167,0.649906,0.647257,0.646918,0.643252,0.642466,0.641096,0.640214,0.639133

DSTAR SCORES

,cz 10,cp 13,cp 8,cp 16,cp 20,swap 12,swap 9,h 1,h 3,x 4,...,h 0,h 11,h 14,cp 19,h 17,cp 7,h 21,cp 18,cp 6,cp 5
sum,1.406344,0.597874,0.530274,0.52958,0.421216,0.387755,0.366231,0.361385,0.352601,0.342175,...,0.158999,0.124586,0.120923,0.113023,0.08862,0.071979,0.049376,0.010943,0.007845,0.000321

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_rxx_inGap_3_.qasm

100%|██████████| 10/10 [00:50<00:00,  5.06s/it]
100%|██████████| 10/10 [00:47<00:00,  4.80s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,cp 8,cp 7,cp 6,x 5,h 4,h 3,rxx 2,h 1,h 0,pass/fail
0,0.119136,0.372003,0.189042,0.056087,0.119123,0.279547,0.145008,0.148339,0.323854,0.170647,...,0.107371,0.028160,0.009859,0.221580,0.169273,0.187541,0.223083,0.169409,0.228932,fail
1,0.072889,0.227090,0.110971,0.033277,0.088757,0.224802,0.120742,0.115979,0.267426,0.141151,...,0.092974,0.024355,0.006357,0.170443,0.156132,0.155005,0.192733,0.140194,0.141721,fail
2,0.071234,0.213223,0.108689,0.031001,0.100028,0.258406,0.132197,0.129473,0.293161,0.145075,...,0.097760,0.025713,0.006062,0.185264,0.158868,0.169266,0.194383,0.152819,0.140562,fail
3,0.090157,0.287214,0.145741,0.042529,0.108117,0.286528,0.148540,0.132668,0.311468,0.157182,...,0.101847,0.028873,0.007442,0.217876,0.171506,0.174802,0.213014,0.168688,0.171054,fail
4,0.088361,0.273214,0.139073,0.040850,0.091672,0.208692,0.109045,0.123831,0.278631,0.140400,...,0.097747,0.022948,0.007769,0.177066,0.150992,0.164207,0.197189,0.133426,0.172887,fail
5,0.046855,0.135481,0.071613,0.021648,0.081393,0.210568,0.109193,0.103296,0.254996,0.114509,...,0.083495,0.019569,0.004145,0.168238,0.130831,0.143159,0.151521,0.118076,0.097552,fail
6,0.075340,0.239229,0.119789,0.035848,0.090771,0.233070,0.124487,0.114147,0.266066,0.125026,...,0.086487,0.023354,0.006253,0.190916,0.137722,0.149266,0.176532,0.140467,0.143379,fail
7,0.072563,0.221972,0.111333,0.033775,0.097411,0.245371,0.127903,0.112079,0.254504,0.134753,...,0.080825,0.023208,0.005810,0.190173,0.144116,0.144205,0.182781,0.145314,0.138529,fail
8,0.083314,0.273244,0.140139,0.040735,0.104017,0.284248,0.140344,0.109323,0.279212,0.136655,...,0.089386,0.026594,0.006371,0.193565,0.154878,0.150640,0.194065,0.155446,0.143720,fail
9,0.100081,0.298603,0.152378,0.045712,0.107199,0.232198,0.120844,0.129459,0.287368,0.151713,...,0.097459,0.023239,0.008245,0.206963,0.153168,0.169076,0.196269,0.143000,0.193862,fail
10,0.072499,0.223876,0.111225,0.033380,0.080123,0.203448,0.109728,0.109357,0.256993,0.119937,...,0.086070,0.020846,0.006117,0.181265,0.132249,0.147718,0.165550,0.123616,0.143150,pass
11,0.066233,0.199431,0.102532,0.029891,0.079495,0.184461,0.096005,0.109776,0.242822,0.125527,...,0.087250,0.020190,0.005667,0.177553,0.140553,0.150207,0.167729,0.121651,0.131895,pass
12,0.085381,0.264846,0.133487,0.039524,0.097855,0.237728,0.126598,0.114740,0.257933,0.123688,...,0.079738,0.022843,0.006840,0.199914,0.128995,0.144905,0.170643,0.141649,0.161974,pass
13,0.038731,0.120461,0.065347,0.017867,0.072977,0.200721,0.103415,0.081881,0.184231,0.087621,...,0.059068,0.019631,0.003662,0.136031,0.103969,0.103116,0.131857,0.114359,0.077884,pass
14,0.061369,0.192529,0.105457,0.029457,0.098441,0.270809,0.136732,0.097022,0.225354,0.103046,...,0.071051,0.025690,0.005092,0.158559,0.117604,0.120905,0.154767,0.147437,0.113145,pass
15,0.055949,0.169672,0.087055,0.025786,0.079082,0.195891,0.102974,0.095937,0.206078,0.114352,...,0.067966,0.019900,0.004607,0.156260,0.123629,0.121337,0.154033,0.122135,0.110586,pass
16,0.064567,0.205652,0.101346,0.030823,0.082451,0.204585,0.106687,0.099493,0.232378,0.136116,...,0.077862,0.021306,0.005373,0.171747,0.148256,0.133902,0.180551,0.127514,0.124101,pass
17,0.063879,0.194170,0.099957,0.028906,0.076693,0.192489,0.097117,0.081524,0.182173,0.096376,...,0.057697,0.018575,0.004866,0.148707,0.101140,0.103926,0.134217,0.111452,0.116658,pass
18,0.087966,0.279003,0.138913,0.041530,0.101092,0.259121,0.135497,0.122367,0.285971,0.146525,...,0.094564,0.025155,0.007228,0.202726,0.155155,0.164134,0.188706,0.148921,0.167116,pass
19,0.088072,0.288988,0.144597,0.042787,0.091094,0.224677,0.118546,0.106625,0.244229,0.107272,...,0.079582,0.022124,0.007481,0.157872,0.111630,0.133791,0.151949,0.128626,0.165779,pass

[[1.45299682 1.46384679 1.466841   1.47030702 1.2051029  1.16312572
  1.16201274 1.21729651 1.14977066 1.20419032 1.22362785 1.12339512
  1.08448415 1.14792158 1.17365233 1.4432503  1.15281036 1.12280236
  1.16690624 1.16094409 1.15492856 1.45613037]]
BARINEL SCORES

,swap 9,cp 8,h 12,cp 13,h 3,h 4,rxx 2,cp 6,cp 10,h 0,...,cp 18,cp 20,cp 19,h 17,h 1,cp 7,x 5,cp 16,cp 15,swap 11
sum,0.556855,0.55144,0.549785,0.548543,0.548314,0.547355,0.545657,0.545433,0.545123,0.545053,...,0.543847,0.543019,0.541799,0.534957,0.532583,0.53218,0.532033,0.531214,0.530064,0.518184

custom SCORES

,cp 18,h 0,h 21,cp 6,cp 20,cp 19,h 12,h 14,cp 8,h 3,...,rxx 2,h 4,cp 10,h 17,cp 7,h 1,cp 16,x 5,cp 15,swap 11
sum,0.743752,0.74347,0.742913,0.742233,0.741743,0.740482,0.715297,0.710424,0.709692,0.708271,...,0.704026,0.700998,0.69822,0.696126,0.688329,0.686357,0.685681,0.685366,0.684049,0.6767

DSTAR SCORES

,cp 10,cp 13,swap 11,cp 20,cp 16,swap 9,rxx 2,x 5,h 3,h 0,...,h 12,cp 19,cp 15,h 14,h 17,cp 8,h 21,cp 18,cp 7,cp 6
sum,0.652706,0.644068,0.565371,0.532026,0.498482,0.325894,0.318312,0.316014,0.228099,0.218506,...,0.179939,0.149769,0.146772,0.134768,0.089979,0.081302,0.062921,0.0141,0.005924,0.000464

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_rxx_inGap_7_.qasm

100%|██████████| 10/10 [00:45<00:00,  4.53s/it]
100%|██████████| 10/10 [00:44<00:00,  4.42s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,swap 12,...,cp 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.069722,0.220718,0.110473,0.032494,0.090070,0.241225,0.122593,0.103379,0.237009,0.175220,...,0.213703,0.076282,0.023338,0.005705,0.167950,0.128483,0.134005,0.139011,0.132708,fail
1,0.085300,0.272725,0.137033,0.040606,0.101388,0.257041,0.136287,0.124904,0.283253,0.197231,...,0.252148,0.094521,0.026098,0.007420,0.188319,0.147127,0.160304,0.152915,0.166362,fail
2,0.099669,0.302359,0.153463,0.045575,0.110631,0.259519,0.135502,0.139806,0.307101,0.233354,...,0.278779,0.103215,0.026377,0.008509,0.219319,0.166517,0.181489,0.160429,0.199122,fail
3,0.084118,0.262789,0.129206,0.038601,0.104319,0.270190,0.141365,0.126740,0.294453,0.212741,...,0.255395,0.091819,0.025387,0.006694,0.236123,0.160353,0.166361,0.157765,0.161902,fail
4,0.070639,0.219822,0.111960,0.032852,0.096168,0.240939,0.127216,0.116225,0.267545,0.214531,...,0.268535,0.090193,0.025097,0.005876,0.199417,0.155575,0.155595,0.150148,0.135358,fail
5,0.069869,0.215836,0.103113,0.032335,0.096381,0.251819,0.135786,0.108395,0.253178,0.187400,...,0.244171,0.081485,0.025568,0.005441,0.204041,0.148851,0.144134,0.154995,0.129775,fail
6,0.058507,0.191253,0.099774,0.028741,0.094295,0.270860,0.139472,0.106028,0.258460,0.186651,...,0.248019,0.083334,0.025761,0.004923,0.176679,0.144582,0.140129,0.149174,0.109494,fail
7,0.066608,0.213458,0.111381,0.032144,0.094920,0.243594,0.126810,0.109873,0.255205,0.188249,...,0.239185,0.083097,0.023957,0.005654,0.185327,0.142269,0.143760,0.142840,0.126242,fail
8,0.083077,0.265296,0.134938,0.039005,0.096015,0.253900,0.131709,0.124566,0.312338,0.265807,...,0.259528,0.103909,0.024733,0.006972,0.212495,0.152804,0.174377,0.145774,0.157992,fail
9,0.065764,0.202139,0.103107,0.030078,0.090277,0.249250,0.126074,0.101973,0.242645,0.179583,...,0.199005,0.077171,0.023351,0.005386,0.183267,0.127809,0.135872,0.136927,0.124299,fail
10,0.048826,0.161857,0.081019,0.023819,0.060917,0.160786,0.088365,0.086857,0.205652,0.154657,...,0.197788,0.071130,0.017026,0.004479,0.131944,0.108504,0.117105,0.098319,0.095731,pass
11,0.089479,0.285370,0.140323,0.042249,0.108349,0.278130,0.144712,0.117896,0.271056,0.202472,...,0.291205,0.091866,0.028273,0.007100,0.197439,0.167389,0.156242,0.166996,0.164332,pass
12,0.087486,0.276813,0.142370,0.042103,0.080681,0.199234,0.099184,0.095015,0.221248,0.172244,...,0.216271,0.075497,0.018957,0.006717,0.186937,0.127684,0.130776,0.115331,0.159275,pass
13,0.080178,0.247622,0.126443,0.037116,0.092487,0.218033,0.114840,0.119503,0.262315,0.197221,...,0.254464,0.090649,0.023614,0.006856,0.187388,0.153302,0.156920,0.140291,0.156025,pass
14,0.073851,0.227561,0.111184,0.034273,0.087636,0.216690,0.113081,0.101558,0.235408,0.186077,...,0.235434,0.076496,0.020860,0.005706,0.181555,0.140338,0.134956,0.130722,0.138985,pass
15,0.074936,0.229696,0.120939,0.035455,0.083489,0.201140,0.104136,0.096589,0.220300,0.152118,...,0.192430,0.069009,0.019006,0.005920,0.173162,0.116720,0.123232,0.116125,0.141023,pass
16,0.072180,0.228551,0.115170,0.034329,0.089774,0.232537,0.123095,0.112451,0.275901,0.230174,...,0.255923,0.093158,0.024092,0.005951,0.186544,0.153715,0.156822,0.141139,0.132832,pass
17,0.083679,0.263961,0.131209,0.038944,0.105855,0.274140,0.144907,0.126438,0.286506,0.209503,...,0.290425,0.095696,0.028366,0.007131,0.186350,0.166532,0.163968,0.165997,0.158670,pass
18,0.037456,0.119749,0.062926,0.017914,0.063853,0.183753,0.093418,0.074742,0.192784,0.175492,...,0.199632,0.063186,0.016916,0.003120,0.147391,0.112248,0.105881,0.102131,0.071864,pass
19,0.063754,0.189547,0.092698,0.028552,0.072609,0.173326,0.089514,0.088491,0.193172,0.151122,...,0.197211,0.064722,0.017030,0.005029,0.151559,0.120950,0.117991,0.106506,0.123627,pass

[[1.32314714 1.2777214  1.28479935 1.29317222 1.13529797 1.06707613
  1.06867108 1.20326605 1.15203327 1.30248689 1.19786129 1.06815259
  1.15664807 1.13395445 1.17408188 1.05647395 1.35965032 1.19680725
  1.12941139 1.18155135 1.07672173 1.37967617]]
BARINEL SCORES

,cp 16,cp 15,rxx 10,cp 6,h 1,h 17,cp 13,x 4,h 14,h 2,...,swap 9,cp 5,h 3,h 0,h 11,cp 19,cp 20,h 21,cp 8,cp 18
sum,0.542831,0.542567,0.542078,0.538298,0.537213,0.535386,0.534168,0.532765,0.532628,0.529679,...,0.521965,0.518954,0.518824,0.518109,0.515646,0.515131,0.514756,0.514146,0.51333,0.512862

custom SCORES

,swap 12,h 0,cp 5,h 14,x 4,cp 13,cp 16,cp 15,h 17,rxx 10,...,cp 7,h 1,cp 19,cp 6,cp 20,cp 18,swap 9,h 11,h 3,cp 8
sum,0.698707,0.696815,0.695353,0.692851,0.692169,0.688013,0.687642,0.687524,0.687342,0.686834,...,0.682878,0.68182,0.680591,0.680473,0.679184,0.678667,0.672897,0.670065,0.665316,0.658854

DSTAR SCORES

,cp 13,swap 9,cp 16,cp 8,cp 20,swap 12,x 4,rxx 10,h 2,h 1,...,cp 15,h 11,cp 19,h 14,h 17,cp 7,h 21,cp 18,cp 6,cp 5
sum,0.594494,0.535524,0.530836,0.49016,0.457849,0.352016,0.331832,0.216863,0.207621,0.19675,...,0.157427,0.129243,0.128251,0.122509,0.087554,0.072583,0.052972,0.012018,0.006103,0.000389

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_cz_inGap_10_.qasm

100%|██████████| 10/10 [01:04<00:00,  6.49s/it]
100%|██████████| 10/10 [01:02<00:00,  6.22s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cz 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.073458,0.239588,0.123470,0.036380,0.106954,0.443183,0.298257,0.163693,0.113110,0.303674,...,0.196054,0.101222,0.033155,0.006698,0.235301,0.161390,0.175929,0.239129,0.216048,fail
1,0.068566,0.223698,0.115378,0.034427,0.106080,0.434464,0.307853,0.156206,0.098572,0.254935,...,0.186651,0.090249,0.033991,0.006423,0.184296,0.162279,0.152784,0.232504,0.204360,fail
2,0.079503,0.252882,0.126262,0.037587,0.105213,0.430977,0.288605,0.161984,0.117087,0.313661,...,0.181976,0.104365,0.032014,0.007706,0.219069,0.148036,0.180035,0.237606,0.220613,fail
3,0.077909,0.255181,0.128564,0.038400,0.095771,0.422982,0.289399,0.144770,0.097413,0.266461,...,0.177412,0.087361,0.029065,0.006985,0.199516,0.146439,0.149519,0.214890,0.204073,fail
4,0.083966,0.268241,0.131102,0.039596,0.093054,0.422181,0.268756,0.146904,0.105219,0.295193,...,0.175931,0.093032,0.027159,0.007295,0.229145,0.143285,0.164143,0.214704,0.211668,fail
5,0.076460,0.250097,0.127637,0.036879,0.107575,0.486022,0.327298,0.175644,0.113709,0.319434,...,0.183973,0.104054,0.034829,0.007062,0.245198,0.161047,0.181013,0.253129,0.224400,fail
6,0.043844,0.128940,0.070056,0.019962,0.086447,0.336710,0.254070,0.132567,0.096902,0.257106,...,0.149587,0.087264,0.028043,0.004286,0.199435,0.137221,0.154653,0.200180,0.157619,fail
7,0.087735,0.262026,0.134110,0.039884,0.119426,0.428604,0.299572,0.165186,0.137594,0.330368,...,0.182084,0.113651,0.033735,0.008093,0.260381,0.184628,0.205281,0.264536,0.252642,fail
8,0.064434,0.200708,0.106545,0.030569,0.082306,0.340529,0.245085,0.129255,0.091004,0.258274,...,0.152549,0.081517,0.024719,0.005979,0.180762,0.111585,0.139078,0.182286,0.171054,fail
9,0.098425,0.312118,0.157171,0.047106,0.108804,0.464210,0.284314,0.151148,0.126997,0.312594,...,0.171154,0.104584,0.030578,0.009022,0.234106,0.161132,0.186196,0.246249,0.252379,fail
10,0.063770,0.196536,0.095707,0.029617,0.081239,0.359874,0.250230,0.126769,0.090552,0.248945,...,0.152100,0.081675,0.024653,0.005615,0.197576,0.136808,0.145547,0.190744,0.174685,pass
11,0.101397,0.314548,0.154712,0.046389,0.104623,0.430322,0.257789,0.135753,0.112192,0.260189,...,0.141748,0.090639,0.028136,0.008878,0.223678,0.165213,0.163327,0.234812,0.250080,pass
12,0.040676,0.122396,0.057637,0.017727,0.072988,0.306548,0.210963,0.109853,0.085688,0.223515,...,0.139890,0.078735,0.024365,0.003639,0.186598,0.140644,0.142156,0.176650,0.143364,pass
13,0.061706,0.190993,0.093908,0.029383,0.088087,0.370720,0.257965,0.134758,0.093045,0.251159,...,0.153774,0.085166,0.027726,0.005843,0.185955,0.144399,0.148542,0.202738,0.180179,pass
14,0.063858,0.202072,0.099374,0.029691,0.080484,0.342225,0.228232,0.117127,0.077551,0.197767,...,0.138118,0.069550,0.024572,0.005304,0.174259,0.134886,0.122995,0.183488,0.173525,pass
15,0.050811,0.155533,0.084084,0.023676,0.082218,0.316465,0.239458,0.120409,0.090237,0.219126,...,0.119824,0.074270,0.025097,0.004948,0.170636,0.116004,0.134165,0.185287,0.160484,pass
16,0.083224,0.250083,0.129012,0.038153,0.106637,0.368080,0.292333,0.137446,0.109801,0.261333,...,0.171836,0.086939,0.027963,0.007478,0.231378,0.162696,0.161828,0.226978,0.221051,pass
17,0.077041,0.237163,0.124142,0.035989,0.089685,0.347735,0.251010,0.121623,0.099989,0.254076,...,0.154946,0.081698,0.024113,0.006950,0.218590,0.126053,0.149520,0.199442,0.197036,pass
18,0.048778,0.167446,0.083371,0.024281,0.085809,0.357407,0.251614,0.133801,0.084937,0.246335,...,0.178656,0.085042,0.029474,0.005005,0.176023,0.128664,0.140841,0.194966,0.158705,pass
19,0.067786,0.199014,0.105446,0.030426,0.082055,0.299041,0.187503,0.102393,0.097642,0.225110,...,0.124278,0.079933,0.022291,0.006381,0.169956,0.131455,0.141543,0.178605,0.181432,pass

[[1.30485399 1.3040325  1.28797485 1.30564862 1.18052971 1.15448356
  1.14311692 1.14998741 1.25358031 1.13462129 1.26943565 1.11683955
  1.13663136 1.11561086 1.17492892 1.13343253 1.2971825  1.19047326
  1.21702567 1.21566488 1.15760014 1.19460759]]
BARINEL SCORES

,swap 10,cp 14,cp 12,cz 16,swap 8,cp 6,cp 7,cp 19,cp 18,cp 15,...,h 2,cp 5,h 1,h 17,h 0,h 21,x 4,cp 9,h 11,h 3
sum,0.567204,0.551932,0.549455,0.546148,0.54365,0.543219,0.543138,0.542911,0.541627,0.541218,...,0.537935,0.536681,0.536571,0.536545,0.534676,0.533697,0.530636,0.530572,0.522968,0.522422

custom SCORES

,swap 10,cp 18,cp 19,cp 20,cp 5,cp 14,h 21,h 13,cp 12,cz 16,...,cp 6,cp 15,swap 8,h 17,h 0,h 1,h 11,x 4,h 3,cp 9
sum,0.725573,0.718421,0.717725,0.716547,0.710725,0.710611,0.707796,0.706925,0.70531,0.703778,...,0.697144,0.695887,0.695275,0.694896,0.694358,0.691854,0.688937,0.688564,0.681372,0.681338

DSTAR SCORES

,cz 16,cp 12,cp 15,swap 10,cp 9,cp 20,h 1,x 4,h 0,swap 8,...,h 3,cp 19,h 11,h 13,h 17,cp 7,h 21,cp 18,cp 6,cp 5
sum,1.312964,0.684396,0.659685,0.64437,0.59032,0.475976,0.436139,0.400839,0.377738,0.269133,...,0.202112,0.135038,0.13348,0.110106,0.094115,0.086526,0.053379,0.012631,0.009205,0.000481

ERROR GATE LOCATION:
16
Now evolving the following mutant:  AddGate_swap_inGap_7_.qasm

100%|██████████| 10/10 [00:42<00:00,  4.29s/it]
100%|██████████| 10/10 [00:43<00:00,  4.39s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,swap 12,...,cp 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.047599,0.148486,0.070307,0.021066,0.064813,0.165607,0.086260,0.081004,0.186609,0.151804,...,0.206171,0.056948,0.014188,0.003535,0.133264,0.111225,0.098260,0.042020,0.075650,fail
1,0.083995,0.267263,0.133571,0.039789,0.116351,0.308160,0.162119,0.129471,0.303122,0.214036,...,0.367337,0.090794,0.020794,0.006182,0.192614,0.189805,0.151905,0.063127,0.129748,fail
2,0.061320,0.179669,0.088181,0.027052,0.083563,0.212136,0.115391,0.107808,0.243122,0.181421,...,0.256880,0.072947,0.017212,0.004712,0.166923,0.142527,0.128930,0.055370,0.103101,fail
3,0.068149,0.202889,0.105941,0.030658,0.096519,0.247539,0.125374,0.109312,0.247575,0.198469,...,0.283666,0.072581,0.018310,0.004896,0.168828,0.154588,0.127558,0.056520,0.107938,fail
4,0.073654,0.222776,0.115349,0.033675,0.102257,0.263764,0.134819,0.122103,0.280830,0.217017,...,0.306325,0.082386,0.019410,0.005537,0.193130,0.166261,0.143092,0.061738,0.119731,fail
5,0.081274,0.265969,0.132055,0.039139,0.099658,0.274628,0.141171,0.103658,0.241008,0.154482,...,0.320013,0.074891,0.018468,0.005701,0.171484,0.162569,0.124720,0.056083,0.120692,fail
6,0.098565,0.295990,0.145530,0.043812,0.109550,0.255899,0.138330,0.139891,0.298743,0.213678,...,0.307273,0.091438,0.021978,0.007340,0.195999,0.166953,0.160362,0.069155,0.159782,fail
7,0.054454,0.164712,0.077734,0.023649,0.068897,0.182757,0.096817,0.100976,0.239165,0.193640,...,0.220302,0.069540,0.015733,0.004220,0.148975,0.123654,0.121015,0.047335,0.091988,fail
8,0.077650,0.254568,0.126398,0.037747,0.076145,0.200970,0.104385,0.092338,0.235431,0.191184,...,0.217530,0.064832,0.015409,0.005430,0.146419,0.115346,0.107854,0.046665,0.116597,fail
9,0.090235,0.290972,0.140641,0.042189,0.092813,0.237944,0.122755,0.110678,0.260264,0.187897,...,0.269128,0.075770,0.017767,0.006270,0.163196,0.142559,0.128779,0.052574,0.134277,fail
10,0.073217,0.218859,0.112222,0.032939,0.094138,0.235311,0.121569,0.120934,0.269002,0.209076,...,0.296800,0.082826,0.019702,0.005365,0.173910,0.155269,0.139798,0.059105,0.115939,pass
11,0.088128,0.270173,0.140611,0.040132,0.089902,0.223293,0.111684,0.121060,0.267432,0.192703,...,0.239861,0.076162,0.017144,0.006240,0.174655,0.136385,0.134631,0.054369,0.137305,pass
12,0.051775,0.165051,0.085156,0.024888,0.077641,0.202585,0.104503,0.080558,0.184182,0.139692,...,0.240973,0.056615,0.014622,0.003803,0.136677,0.125116,0.096193,0.044018,0.080734,pass
13,0.074748,0.232693,0.116597,0.034539,0.086857,0.216386,0.113786,0.112641,0.258425,0.211231,...,0.261883,0.075571,0.018248,0.005330,0.160493,0.138094,0.130277,0.056171,0.114932,pass
14,0.103235,0.321017,0.163612,0.048241,0.112401,0.271496,0.138352,0.123398,0.261930,0.164334,...,0.289133,0.079213,0.020013,0.007257,0.179214,0.162747,0.138534,0.068505,0.157940,pass
15,0.079507,0.242947,0.123118,0.037584,0.098523,0.238346,0.128516,0.125540,0.278070,0.197585,...,0.271796,0.080383,0.019113,0.005769,0.180597,0.157353,0.143501,0.063601,0.127230,pass
16,0.065009,0.200198,0.105580,0.030970,0.071666,0.168561,0.086287,0.080475,0.190012,0.151189,...,0.171864,0.050635,0.011418,0.004455,0.120229,0.096542,0.088111,0.035264,0.097445,pass
17,0.061243,0.195150,0.098725,0.028252,0.090982,0.249332,0.127266,0.103111,0.231173,0.166225,...,0.301166,0.073040,0.017314,0.004457,0.165707,0.158245,0.125358,0.052304,0.095871,pass
18,0.043790,0.138582,0.065827,0.020244,0.049011,0.128030,0.068850,0.070884,0.172852,0.158674,...,0.157942,0.051833,0.011844,0.003152,0.107415,0.085960,0.086614,0.035303,0.068545,pass
19,0.076870,0.246239,0.119473,0.036348,0.097346,0.239717,0.124545,0.112171,0.251587,0.203458,...,0.287123,0.076841,0.019514,0.005605,0.158192,0.150684,0.131632,0.061990,0.119853,pass

[[1.33756743 1.29067592 1.28140313 1.2932561  1.27778958 1.31165124
  1.32080912 1.27493375 1.19533885 1.14001681 1.28679813 1.30740566
  1.24143248 1.33352818 1.21572351 1.22599166 1.36372015 1.16608037
  1.28639191 1.2407375  1.25603082 1.3780185 ]]
BARINEL SCORES

,swap 10,swap 9,cp 8,cp 15,cp 16,h 3,x 4,cp 13,cp 7,h 2,...,h 17,cp 5,h 14,h 0,h 1,cp 20,h 21,h 11,cp 18,cp 19
sum,0.550131,0.527426,0.522386,0.52169,0.519497,0.519193,0.519108,0.517468,0.516839,0.515521,...,0.511832,0.511351,0.510816,0.509606,0.509229,0.506895,0.506661,0.505014,0.503447,0.501056

custom SCORES

,swap 10,cp 8,cp 15,swap 9,cp 16,h 3,cp 5,h 0,h 21,h 2,...,h 14,cp 6,cp 13,cp 20,x 4,h 1,h 11,cp 18,cp 19,swap 12
sum,0.729943,0.69654,0.693953,0.691117,0.689846,0.686165,0.685686,0.685167,0.676084,0.675427,...,0.673631,0.672641,0.672105,0.670454,0.670439,0.669131,0.667477,0.666218,0.661569,0.661521

DSTAR SCORES

,cp 8,cp 13,cp 16,cp 20,swap 10,swap 9,swap 12,x 4,h 3,h 2,...,h 0,cp 19,h 14,h 17,cp 7,h 21,h 1,cp 18,cp 6,cp 5
sum,0.606138,0.520081,0.453436,0.429992,0.355746,0.314033,0.307254,0.244456,0.191535,0.148956,...,0.12095,0.115878,0.108946,0.076288,0.052853,0.050666,0.028787,0.011106,0.00316,0.000288

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_swap_inGap_9_.qasm

100%|██████████| 10/10 [00:44<00:00,  4.44s/it]
100%|██████████| 10/10 [00:42<00:00,  4.25s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,swap 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.105161,0.333472,0.168972,0.049004,0.109221,0.270635,0.138171,0.140859,0.216544,0.326539,...,0.201645,0.111224,0.022305,0.008547,0.217999,0.157147,0.199231,0.078967,0.194586,fail
1,0.114268,0.352890,0.177507,0.052626,0.144170,0.361825,0.185610,0.159634,0.248568,0.437063,...,0.235028,0.139803,0.025299,0.008860,0.265385,0.211090,0.263705,0.093313,0.209906,fail
2,0.083805,0.263330,0.133494,0.039151,0.111107,0.286616,0.147044,0.119236,0.210039,0.348902,...,0.184505,0.115024,0.019821,0.006917,0.192003,0.151159,0.205374,0.069862,0.154196,fail
3,0.070171,0.215782,0.100451,0.032156,0.090301,0.233854,0.127401,0.124602,0.246484,0.298458,...,0.190416,0.097426,0.021288,0.005337,0.200214,0.167817,0.180967,0.069924,0.127029,fail
4,0.077755,0.250162,0.128592,0.037992,0.122427,0.334158,0.172267,0.118815,0.209980,0.409342,...,0.181810,0.125262,0.019659,0.006333,0.203010,0.160067,0.226869,0.070302,0.140770,fail
5,0.071090,0.212211,0.110132,0.032204,0.099949,0.245693,0.128986,0.115322,0.165965,0.300916,...,0.149342,0.097220,0.017573,0.005753,0.183259,0.136758,0.182463,0.065716,0.135097,fail
6,0.050263,0.157698,0.075893,0.023438,0.077740,0.206474,0.109296,0.087738,0.140251,0.256483,...,0.131775,0.082912,0.014396,0.004298,0.154344,0.122983,0.150331,0.052438,0.095232,fail
7,0.100911,0.327734,0.160014,0.047199,0.097304,0.254841,0.133367,0.135581,0.274352,0.321960,...,0.212536,0.100802,0.023230,0.007729,0.215987,0.157475,0.184373,0.075004,0.178391,fail
8,0.070944,0.223631,0.113503,0.033059,0.091862,0.253175,0.126953,0.100416,0.187070,0.299465,...,0.154469,0.096590,0.016768,0.005572,0.171596,0.136986,0.175400,0.059272,0.128683,fail
9,0.083795,0.248594,0.127065,0.037180,0.117393,0.294924,0.155461,0.145372,0.241218,0.365513,...,0.194030,0.120218,0.022775,0.007135,0.214333,0.168048,0.220064,0.081596,0.161549,fail
10,0.042920,0.133412,0.071749,0.020063,0.055711,0.147742,0.074140,0.069538,0.133520,0.175722,...,0.105355,0.058319,0.011524,0.003712,0.111209,0.077238,0.103325,0.038857,0.081320,pass
11,0.052920,0.162217,0.081317,0.024097,0.069769,0.169177,0.088935,0.090881,0.166139,0.215976,...,0.118411,0.067494,0.014241,0.004351,0.136399,0.113166,0.126698,0.050710,0.103316,pass
12,0.064091,0.194797,0.092655,0.028248,0.071312,0.176823,0.090462,0.083301,0.135819,0.215136,...,0.116830,0.068955,0.013609,0.004796,0.156855,0.117578,0.133057,0.050264,0.116164,pass
13,0.052196,0.157848,0.080151,0.024402,0.076921,0.208084,0.108386,0.088492,0.156707,0.251550,...,0.115558,0.077458,0.013704,0.003931,0.144889,0.112403,0.146428,0.048451,0.095263,pass
14,0.059457,0.177449,0.087982,0.027540,0.080772,0.189175,0.100239,0.096865,0.175669,0.235162,...,0.122743,0.077635,0.015153,0.004681,0.171299,0.120257,0.149623,0.053107,0.111104,pass
15,0.064813,0.205800,0.103408,0.030369,0.077242,0.198166,0.101503,0.094807,0.151766,0.237706,...,0.147185,0.081584,0.015600,0.005170,0.168050,0.126625,0.146993,0.056365,0.120176,pass
16,0.052922,0.172559,0.083875,0.024618,0.065081,0.184148,0.093282,0.075930,0.152037,0.223438,...,0.122525,0.067324,0.012854,0.003976,0.139924,0.105728,0.124653,0.044607,0.095043,pass
17,0.086408,0.254730,0.131777,0.038738,0.103328,0.232725,0.122189,0.127280,0.174113,0.287204,...,0.166120,0.097812,0.019521,0.007108,0.185849,0.149145,0.180582,0.072348,0.166042,pass
18,0.081923,0.268946,0.130327,0.039324,0.082195,0.224117,0.114027,0.084453,0.157990,0.270300,...,0.153362,0.087055,0.015623,0.005975,0.168804,0.129149,0.157980,0.054989,0.140276,pass
19,0.093608,0.295925,0.149701,0.044020,0.097076,0.235239,0.123601,0.126053,0.223268,0.296533,...,0.185088,0.095576,0.021089,0.007583,0.189252,0.144328,0.172574,0.071561,0.172622,pass

[[1.37977269 1.36487771 1.37005004 1.37043628 1.35820177 1.31947245
  1.3029354  1.27955298 1.28173692 1.29898905 1.38458431 1.31203451
  1.33221197 1.28041569 1.28675068 1.24553818 1.33265707 1.31500599
  1.3449266  1.32596511 1.30253423 1.37603388]]
BARINEL SCORES

,cp 15,cp 12,cp 16,cp 7,h 2,h 17,swap 8,h 14,cp 6,h 1,...,h 3,swap 10,cp 5,h 11,x 4,cp 19,cp 20,cp 18,h 21,h 0
sum,0.583519,0.582786,0.582505,0.582348,0.579702,0.576612,0.575638,0.570927,0.570493,0.569628,...,0.567612,0.565233,0.564531,0.564365,0.56205,0.561225,0.560946,0.560247,0.559789,0.559432

custom SCORES

,cp 16,cp 15,h 17,cp 12,h 2,cp 7,swap 8,h 11,h 3,cp 9,...,cp 19,h 21,cp 5,cp 20,cp 18,h 0,swap 10,swap 13,cp 6,x 4
sum,0.774655,0.77359,0.7724,0.772045,0.771868,0.769682,0.759902,0.759717,0.758461,0.757662,...,0.753451,0.752885,0.752612,0.752351,0.752192,0.751882,0.750635,0.750193,0.748136,0.746825

DSTAR SCORES

,cp 12,cp 9,cp 16,swap 10,cp 20,swap 13,x 4,h 2,swap 8,h 3,...,h 11,cp 19,h 14,cp 7,h 17,h 21,h 1,cp 18,cp 6,cp 5
sum,0.912325,0.636607,0.628448,0.61645,0.555972,0.394049,0.351941,0.345679,0.296769,0.220035,...,0.175841,0.152424,0.142302,0.109511,0.104526,0.064392,0.048687,0.014315,0.004063,0.00044

ERROR GATE LOCATION:
13
Now evolving the following mutant:  AddGate_ry_inGap_13_.qasm

100%|██████████| 10/10 [01:03<00:00,  6.32s/it]
100%|██████████| 10/10 [01:01<00:00,  6.16s/it]

,h 21,cp 20,ry 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.072840,0.220853,0.592246,0.183022,0.037454,0.157203,0.477277,0.156174,0.308915,0.264965,...,0.115526,0.088393,0.027904,0.006223,0.201447,0.166786,0.212249,0.198590,0.161298,fail
1,0.064143,0.201469,0.449512,0.158754,0.033513,0.127376,0.382371,0.129308,0.239520,0.218772,...,0.100421,0.072971,0.023323,0.005495,0.159877,0.133235,0.166572,0.160971,0.133776,fail
2,0.077220,0.239334,0.554000,0.169976,0.041057,0.131505,0.402896,0.126044,0.276825,0.234729,...,0.094036,0.075172,0.021336,0.006546,0.204458,0.139789,0.189783,0.164897,0.170084,fail
3,0.105882,0.338221,0.671905,0.226317,0.056372,0.171208,0.521651,0.167888,0.342866,0.306522,...,0.128445,0.096575,0.028418,0.008839,0.264516,0.171490,0.242332,0.216031,0.226274,fail
4,0.073086,0.238314,0.479950,0.178571,0.038620,0.132555,0.407795,0.134856,0.254696,0.243414,...,0.113394,0.078907,0.024611,0.006384,0.177746,0.134128,0.176568,0.167094,0.150364,fail
5,0.072920,0.227354,0.565180,0.164188,0.038962,0.139219,0.450913,0.143682,0.286928,0.252285,...,0.119637,0.084859,0.025987,0.006553,0.186661,0.159858,0.203224,0.185682,0.162439,fail
6,0.092902,0.285092,0.533416,0.197528,0.047873,0.151374,0.457898,0.146765,0.284196,0.261109,...,0.117517,0.086338,0.026016,0.007712,0.214277,0.169223,0.205761,0.192453,0.195362,fail
7,0.068440,0.217332,0.491684,0.163789,0.037188,0.116812,0.392220,0.116708,0.249267,0.227281,...,0.115565,0.075275,0.020902,0.006080,0.160469,0.122704,0.170096,0.149908,0.146056,fail
8,0.081655,0.246610,0.690074,0.195596,0.043473,0.160787,0.510115,0.153068,0.341943,0.288635,...,0.113202,0.092670,0.026074,0.007101,0.219664,0.160582,0.233075,0.200837,0.189341,fail
9,0.073939,0.228972,0.561453,0.168891,0.037810,0.127322,0.416644,0.121017,0.277950,0.227303,...,0.109275,0.079860,0.022094,0.006575,0.178145,0.141744,0.186149,0.163225,0.161974,fail
10,0.054135,0.174286,0.296600,0.120965,0.028900,0.124735,0.336120,0.142876,0.181385,0.202304,...,0.088723,0.060915,0.024261,0.004321,0.180702,0.131531,0.145622,0.162800,0.111471,pass
11,0.072950,0.240925,0.335871,0.157810,0.038771,0.108999,0.344966,0.119573,0.189148,0.211488,...,0.093211,0.062202,0.019712,0.005750,0.189067,0.115879,0.146226,0.143217,0.144155,pass
12,0.087091,0.263909,0.440002,0.163189,0.044199,0.123261,0.405981,0.127926,0.236521,0.226014,...,0.115476,0.076746,0.023074,0.006945,0.199220,0.156505,0.179247,0.169990,0.181403,pass
13,0.063971,0.196222,0.402215,0.138546,0.032410,0.096078,0.328787,0.096247,0.204264,0.189530,...,0.079023,0.059878,0.016325,0.005109,0.152316,0.109057,0.141398,0.124850,0.134274,pass
14,0.065703,0.201561,0.297088,0.120923,0.031810,0.093828,0.323134,0.105747,0.169579,0.186037,...,0.102583,0.059442,0.018795,0.005100,0.169206,0.127762,0.133257,0.133965,0.131495,pass
15,0.074875,0.224515,0.393184,0.145967,0.036979,0.123088,0.354029,0.121704,0.216517,0.202021,...,0.091555,0.068779,0.022164,0.006030,0.180708,0.146121,0.167261,0.161085,0.156361,pass
16,0.074163,0.236136,0.361218,0.152665,0.038282,0.120585,0.353899,0.124295,0.205103,0.208946,...,0.113072,0.070574,0.023642,0.006225,0.166578,0.133318,0.158135,0.160696,0.149171,pass
17,0.062233,0.197477,0.441220,0.160848,0.031245,0.107296,0.382067,0.110119,0.230643,0.212935,...,0.106925,0.070218,0.019550,0.004956,0.181626,0.142468,0.163590,0.145992,0.131132,pass
18,0.086703,0.258486,0.534577,0.181215,0.043608,0.152633,0.437443,0.145396,0.283530,0.243810,...,0.106378,0.082198,0.026572,0.007173,0.214736,0.158459,0.203081,0.192015,0.184396,pass
19,0.092565,0.287540,0.472546,0.199112,0.046381,0.152494,0.487059,0.163733,0.269093,0.277141,...,0.139511,0.089514,0.028429,0.007097,0.246082,0.172205,0.204646,0.204319,0.183945,pass

[[1.35221292 1.38413606 1.23460773 1.25270217 1.36718265 1.20963999
  1.18026538 1.20305958 1.19753329 1.2139419  1.19531165 1.2227055
  1.13180836 1.1396891  1.16212746 1.1520984  1.30934207 1.34459114
  1.14361847 1.22032019 1.20038062 1.33340276]]
BARINEL SCORES

,ry 19,h 13,h 2,cp 7,cp 15,h 16,cp 18,cp 12,cp 5,h 1,...,cp 6,cp 17,swap 10,swap 8,h 3,cp 9,cp 20,h 21,h 11,x 4
sum,0.584426,0.567076,0.547316,0.542623,0.54076,0.540553,0.539636,0.538929,0.534867,0.529536,...,0.525729,0.525313,0.524748,0.520929,0.518361,0.517577,0.517197,0.516026,0.513444,0.511308

custom SCORES

,ry 19,h 13,h 2,cp 5,cp 18,h 0,cp 17,h 16,cp 12,cp 15,...,h 21,h 1,swap 10,cp 14,x 4,cp 6,swap 8,h 11,h 3,cp 9
sum,0.764811,0.73685,0.714291,0.709948,0.708637,0.706026,0.704862,0.704022,0.702487,0.700321,...,0.69047,0.688447,0.685152,0.684186,0.683184,0.677151,0.669354,0.666875,0.666563,0.664026

DSTAR SCORES

,ry 19,cp 15,h 13,cp 9,swap 10,cp 12,cp 20,h 2,x 4,cp 18,...,h 3,h 16,cp 14,h 11,swap 8,cp 7,h 21,cp 17,cp 6,cp 5
sum,2.235613,1.420327,0.6727,0.619186,0.54959,0.524308,0.486191,0.338712,0.325761,0.282805,...,0.197363,0.178814,0.17299,0.152314,0.115088,0.064539,0.057118,0.01639,0.005952,0.000453

ERROR GATE LOCATION:
19
Now evolving the following mutant:  AddGate_rxx_inGap_8_.qasm

100%|██████████| 10/10 [00:49<00:00,  4.96s/it]
100%|██████████| 10/10 [00:49<00:00,  4.91s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,rxx 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.086920,0.273633,0.135999,0.040632,0.095365,0.238693,0.120837,0.117074,0.281227,0.136955,...,0.180594,0.092766,0.022769,0.006921,0.195701,0.147999,0.159322,0.136588,0.162522,fail
1,0.067276,0.203395,0.102789,0.030301,0.089072,0.213991,0.114319,0.123978,0.282482,0.149345,...,0.186007,0.095410,0.021937,0.005729,0.217879,0.166798,0.168890,0.138293,0.138347,fail
2,0.050825,0.154086,0.076566,0.022942,0.083554,0.221030,0.115302,0.104832,0.247487,0.142206,...,0.170134,0.084926,0.022125,0.004272,0.157638,0.158133,0.143863,0.132424,0.098879,fail
3,0.068185,0.211389,0.102275,0.031330,0.081798,0.203965,0.105934,0.101599,0.244065,0.128742,...,0.159252,0.082889,0.020062,0.005437,0.179040,0.138965,0.141417,0.121897,0.128231,fail
4,0.084651,0.265055,0.127906,0.039510,0.089090,0.219674,0.117817,0.110818,0.267520,0.139213,...,0.174235,0.089634,0.023193,0.007042,0.192198,0.150916,0.153486,0.136261,0.160448,fail
5,0.080839,0.255278,0.129211,0.038506,0.109087,0.284194,0.146348,0.126097,0.294206,0.156933,...,0.197972,0.095014,0.026786,0.006456,0.235891,0.170491,0.169075,0.164608,0.154093,fail
6,0.088249,0.280762,0.141948,0.042562,0.099218,0.244813,0.126840,0.112145,0.270394,0.139652,...,0.178613,0.088675,0.023674,0.006981,0.191780,0.148522,0.152382,0.141580,0.159247,fail
7,0.068995,0.214793,0.103520,0.031489,0.085580,0.222836,0.117956,0.105627,0.238166,0.139474,...,0.162240,0.080449,0.023031,0.005779,0.167292,0.148787,0.138007,0.136763,0.137659,fail
8,0.082833,0.255637,0.131175,0.039470,0.094219,0.233526,0.120963,0.112579,0.267222,0.133152,...,0.171818,0.087937,0.022337,0.006809,0.183533,0.141626,0.150784,0.134261,0.157791,fail
9,0.079674,0.244432,0.128687,0.037152,0.086103,0.213102,0.108383,0.102808,0.236379,0.108189,...,0.150201,0.075050,0.019827,0.006452,0.162703,0.113319,0.130748,0.119269,0.150823,fail
10,0.022096,0.062409,0.035113,0.009671,0.051434,0.134160,0.070034,0.074050,0.173372,0.078081,...,0.115718,0.059404,0.013835,0.002174,0.130308,0.097702,0.102458,0.084724,0.049872,pass
11,0.084845,0.262355,0.131505,0.039698,0.098573,0.238298,0.122718,0.109249,0.247877,0.136898,...,0.170832,0.082549,0.023189,0.006695,0.186310,0.142975,0.143070,0.140994,0.157490,pass
12,0.069723,0.218249,0.109157,0.033166,0.079154,0.191827,0.101489,0.092763,0.212275,0.123388,...,0.146689,0.071384,0.020436,0.005743,0.140731,0.128448,0.122275,0.120947,0.130043,pass
13,0.080956,0.245597,0.123889,0.036738,0.097521,0.243259,0.125378,0.116930,0.260236,0.145014,...,0.179567,0.090103,0.024589,0.006733,0.179596,0.152914,0.154937,0.145499,0.155443,pass
14,0.062817,0.190410,0.088778,0.027390,0.080537,0.211095,0.112928,0.102480,0.249359,0.124500,...,0.165758,0.084249,0.021326,0.005258,0.175075,0.139657,0.143936,0.126800,0.122900,pass
15,0.078152,0.249262,0.120362,0.037583,0.087390,0.213267,0.116124,0.098461,0.224868,0.131111,...,0.153078,0.073916,0.022209,0.006311,0.155514,0.130803,0.128008,0.131852,0.144544,pass
16,0.088661,0.289347,0.143604,0.042317,0.091471,0.230849,0.118660,0.102802,0.242136,0.130296,...,0.163581,0.078622,0.023196,0.006979,0.194255,0.140492,0.136871,0.137431,0.161149,pass
17,0.077590,0.249353,0.123216,0.035832,0.088944,0.236615,0.119360,0.109333,0.257305,0.128287,...,0.173334,0.086161,0.022781,0.006265,0.199021,0.143572,0.150278,0.136005,0.147679,pass
18,0.073313,0.231902,0.114469,0.034772,0.081593,0.196376,0.105076,0.105950,0.245032,0.121455,...,0.155862,0.081863,0.020457,0.006365,0.155784,0.128166,0.138860,0.120376,0.142011,pass
19,0.072965,0.234749,0.116137,0.034178,0.086862,0.231444,0.120631,0.114425,0.278647,0.116468,...,0.173524,0.090549,0.021791,0.006237,0.204959,0.135052,0.156081,0.130862,0.144148,pass

[[1.16354309 1.1904461  1.20286931 1.20268103 1.19470452 1.23787164
  1.22497987 1.12832618 1.11901749 1.14228027 1.13219661 1.1581744
  1.13676977 1.14364219 1.09320703 1.18657093 1.13797712 1.25230699
  1.14766069 1.1212093  1.2086246  1.12235761]]
BARINEL SCORES

,cp 10,h 12,h 3,swap 9,cp 13,h 2,x 4,cp 7,h 14,rxx 8,...,cp 15,h 0,cp 18,h 1,cp 19,h 21,swap 11,cp 20,cp 6,cp 5
sum,0.526669,0.526513,0.525798,0.524122,0.523708,0.52274,0.522482,0.522121,0.521249,0.519994,...,0.517837,0.516545,0.516453,0.51639,0.51615,0.516104,0.514993,0.513592,0.513572,0.512924

custom SCORES

,x 4,cp 16,cp 10,h 12,h 3,cp 15,h 17,swap 9,h 1,cp 18,...,h 2,rxx 8,h 14,cp 20,h 21,cp 6,cp 7,h 0,swap 11,cp 5
sum,0.686058,0.679696,0.679162,0.676869,0.676657,0.676422,0.675069,0.673073,0.67242,0.671735,...,0.669266,0.668666,0.668283,0.666442,0.666231,0.66592,0.664817,0.661482,0.660762,0.658848

DSTAR SCORES

,cp 10,cp 13,swap 11,cp 20,cp 16,x 4,swap 9,rxx 8,h 2,h 3,...,h 1,cp 15,cp 19,h 14,h 17,cp 7,h 21,cp 18,cp 6,cp 5
sum,0.611291,0.557853,0.526154,0.454676,0.434627,0.302704,0.300329,0.258372,0.199879,0.194614,...,0.164507,0.128443,0.125387,0.113267,0.076887,0.070535,0.053705,0.012122,0.004989,0.000381

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_rxx_inGap_12_.qasm

100%|██████████| 10/10 [01:16<00:00,  7.62s/it]
100%|██████████| 10/10 [01:14<00:00,  7.46s/it]

,h 21,cp 20,rxx 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.075133,0.225549,1.029594,0.168991,0.051971,0.182299,0.522015,0.195092,0.425655,0.424763,...,0.178351,0.117985,0.033874,0.008531,0.260131,0.279185,0.263052,0.249624,0.211391,fail
1,0.089782,0.278170,0.769591,0.186469,0.059029,0.159988,0.517930,0.207178,0.362983,0.422163,...,0.223078,0.123815,0.032709,0.008974,0.291207,0.262901,0.260384,0.236984,0.220559,fail
2,0.080153,0.237962,0.837578,0.164160,0.050672,0.160342,0.482813,0.186483,0.369026,0.382724,...,0.166456,0.103860,0.029766,0.008134,0.280803,0.253537,0.240209,0.229731,0.209540,fail
3,0.111926,0.356228,0.849476,0.219592,0.073513,0.186125,0.579264,0.241209,0.389277,0.470769,...,0.226129,0.132781,0.038390,0.010709,0.310157,0.274662,0.275252,0.267981,0.258259,fail
4,0.074415,0.239194,0.861127,0.178806,0.053840,0.141357,0.512840,0.194897,0.355563,0.385344,...,0.194050,0.109852,0.028412,0.007531,0.277857,0.241351,0.234585,0.214230,0.189524,fail
5,0.085284,0.268497,0.877265,0.199401,0.058930,0.178364,0.533745,0.205284,0.390988,0.420187,...,0.197453,0.118193,0.033704,0.008710,0.284492,0.262257,0.255484,0.246219,0.215278,fail
6,0.089202,0.282893,0.988370,0.187289,0.060538,0.166852,0.607538,0.237074,0.401038,0.437756,...,0.201476,0.119547,0.033695,0.009160,0.301319,0.272585,0.259912,0.254099,0.222339,fail
7,0.062519,0.191928,0.891933,0.164715,0.050258,0.146448,0.516338,0.190771,0.366591,0.377762,...,0.187020,0.101296,0.026807,0.006400,0.277524,0.240459,0.231765,0.215077,0.170082,fail
8,0.091948,0.281175,1.023408,0.191896,0.058906,0.181705,0.591628,0.219673,0.422849,0.453100,...,0.204753,0.121572,0.032552,0.009572,0.300862,0.279093,0.269513,0.250751,0.239154,fail
9,0.055721,0.176279,0.751925,0.139792,0.042636,0.125375,0.437099,0.169053,0.305308,0.329123,...,0.145721,0.089703,0.025191,0.006130,0.211468,0.200774,0.194161,0.185067,0.148684,fail
10,0.036812,0.108954,0.505463,0.097146,0.025253,0.091654,0.293357,0.103757,0.225098,0.226927,...,0.120667,0.065921,0.017256,0.004047,0.169478,0.154997,0.148933,0.132857,0.104498,pass
11,0.047445,0.145760,0.609513,0.142111,0.040774,0.135897,0.410225,0.160987,0.285042,0.309137,...,0.153000,0.091048,0.028372,0.005040,0.219076,0.197486,0.192195,0.195613,0.128984,pass
12,0.054673,0.176679,0.499144,0.138648,0.036081,0.104711,0.369071,0.141420,0.236843,0.278062,...,0.154036,0.082065,0.021714,0.005487,0.199804,0.171523,0.171123,0.156858,0.132444,pass
13,0.068686,0.220075,0.523436,0.157905,0.044728,0.132467,0.401003,0.158480,0.270430,0.322203,...,0.170799,0.094769,0.028213,0.006376,0.245538,0.205372,0.200567,0.197371,0.162778,pass
14,0.037790,0.113775,0.309892,0.074280,0.020191,0.068826,0.223028,0.090254,0.161208,0.189012,...,0.108809,0.060069,0.015223,0.003866,0.134231,0.128617,0.123114,0.109423,0.096145,pass
15,0.055196,0.175474,0.655435,0.147841,0.041632,0.142656,0.428882,0.163290,0.305329,0.328222,...,0.179222,0.096945,0.029620,0.005830,0.225702,0.212818,0.204938,0.203947,0.143507,pass
16,0.102925,0.320453,0.926569,0.215325,0.062751,0.192159,0.532528,0.204906,0.417269,0.441942,...,0.180055,0.120470,0.034798,0.010424,0.305459,0.277845,0.270793,0.257636,0.257026,pass
17,0.082179,0.248925,0.659951,0.164918,0.049948,0.138335,0.417651,0.164475,0.320282,0.361376,...,0.195259,0.113566,0.028206,0.008179,0.256792,0.233127,0.232654,0.201970,0.202234,pass
18,0.082727,0.273841,0.351173,0.173301,0.050908,0.130750,0.402536,0.175706,0.222723,0.337995,...,0.196217,0.104994,0.029955,0.007566,0.199286,0.184034,0.193894,0.189329,0.173675,pass
19,0.092391,0.283135,0.773110,0.168689,0.049475,0.138829,0.474151,0.176610,0.340249,0.377228,...,0.172263,0.109201,0.025919,0.009809,0.235335,0.241381,0.232679,0.201285,0.234104,pass

[[1.37149865 1.40364525 1.1594177  1.21920418 1.31204425 1.1426712
  1.14603593 1.17851823 1.12331368 1.14718466 1.11185589 1.37814148
  1.14288161 1.17500827 1.16617442 1.21834526 1.27714515 1.1093599
  1.08767417 1.10796002 1.14045894 1.23876282]]
BARINEL SCORES

,rxx 19,h 13,cp 15,h 11,cp 14,cp 17,cp 12,h 3,h 16,x 4,...,h 2,cp 5,h 21,cp 20,cp 18,cp 6,cp 7,cp 9,swap 8,swap 10
sum,0.604348,0.576426,0.572878,0.572291,0.570656,0.570544,0.56402,0.561172,0.560681,0.560675,...,0.557621,0.557241,0.552563,0.551119,0.548906,0.548595,0.548024,0.54508,0.541375,0.530162

custom SCORES

,rxx 19,cp 17,cp 20,h 21,cp 14,h 13,cp 15,cp 5,h 0,h 11,...,h 1,cp 18,x 4,cp 6,h 3,swap 10,h 2,cp 7,cp 9,swap 8
sum,0.779521,0.757688,0.744513,0.742022,0.738788,0.738302,0.737013,0.73516,0.733953,0.731367,...,0.719656,0.716213,0.716173,0.715689,0.713765,0.712822,0.712076,0.707797,0.700821,0.700405

DSTAR SCORES

,rxx 19,cp 15,cp 12,h 11,h 13,cp 9,x 4,h 3,swap 10,cp 20,...,h 0,cp 14,swap 8,cp 18,h 16,cp 7,h 21,cp 17,cp 6,cp 5
sum,4.986763,2.014188,1.27848,1.133753,1.12313,0.937852,0.641194,0.548711,0.547244,0.533751,...,0.373553,0.363006,0.318447,0.282574,0.235287,0.118513,0.062471,0.030122,0.009678,0.000698

ERROR GATE LOCATION:
19
Now evolving the following mutant:  AddGate_cswap_inGap_11_.qasm

100%|██████████| 10/10 [01:44<00:00, 10.44s/it]
100%|██████████| 10/10 [01:41<00:00, 10.11s/it]

,h 21,cswap 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.081149,0.510662,0.202125,0.081456,0.022857,0.109610,0.192436,0.091266,0.068851,0.176318,...,0.114793,0.053153,0.016467,0.003769,0.131088,0.099580,0.094118,0.106099,0.103021,fail
1,0.092054,0.585521,0.249858,0.101909,0.028675,0.136669,0.213748,0.103558,0.089269,0.220383,...,0.148348,0.068555,0.019112,0.004791,0.156877,0.119631,0.121943,0.127209,0.131679,fail
2,0.086996,0.531687,0.234639,0.088092,0.024149,0.116635,0.214484,0.100996,0.078099,0.205398,...,0.136531,0.060106,0.017711,0.003781,0.139693,0.099986,0.106792,0.114517,0.108247,fail
3,0.072032,0.630119,0.195994,0.076113,0.022927,0.122366,0.174201,0.089294,0.074278,0.217229,...,0.136281,0.065252,0.015844,0.003851,0.143544,0.106900,0.113822,0.108040,0.109393,fail
4,0.085367,0.522230,0.216347,0.085382,0.024773,0.118767,0.192555,0.095758,0.081266,0.215883,...,0.142295,0.065921,0.017136,0.004059,0.151457,0.105321,0.117435,0.113638,0.114795,fail
5,0.054922,0.460651,0.151192,0.057289,0.017246,0.095151,0.159609,0.080961,0.065778,0.176086,...,0.123999,0.054233,0.014743,0.002812,0.125413,0.096837,0.096652,0.097023,0.084244,fail
6,0.098750,0.676886,0.249881,0.094858,0.027023,0.139468,0.234691,0.109782,0.082049,0.216174,...,0.145964,0.066537,0.020047,0.004425,0.166675,0.128972,0.118960,0.132186,0.125691,fail
7,0.098650,0.715599,0.281560,0.110157,0.032301,0.157149,0.232613,0.116771,0.097571,0.261602,...,0.164680,0.078200,0.020455,0.005194,0.174730,0.130490,0.138176,0.138937,0.146593,fail
8,0.088689,0.594021,0.224680,0.088314,0.026297,0.122949,0.198781,0.100634,0.076108,0.219524,...,0.127593,0.061938,0.017068,0.004189,0.142783,0.100774,0.108823,0.111986,0.116768,fail
9,0.075269,0.508990,0.203775,0.077456,0.021769,0.107311,0.190127,0.090351,0.067101,0.172802,...,0.115224,0.052182,0.015959,0.003448,0.123096,0.094494,0.092089,0.103060,0.098906,fail
10,0.080409,0.596330,0.212138,0.089843,0.024891,0.123772,0.195153,0.088103,0.062951,0.166673,...,0.121039,0.052009,0.016364,0.003916,0.133125,0.108116,0.090699,0.109311,0.110763,pass
11,0.065059,0.505586,0.164813,0.072914,0.021118,0.103532,0.184254,0.091989,0.067434,0.182648,...,0.125717,0.056137,0.016258,0.003312,0.133643,0.101670,0.098465,0.105218,0.096883,pass
12,0.070418,0.516052,0.174511,0.066365,0.020371,0.103801,0.156412,0.080669,0.065580,0.181010,...,0.115351,0.055909,0.014661,0.003452,0.128399,0.094765,0.099192,0.097958,0.097001,pass
13,0.082377,0.497469,0.203811,0.075235,0.022736,0.110198,0.170572,0.086076,0.070239,0.189717,...,0.124012,0.057411,0.015175,0.003596,0.130445,0.098766,0.102827,0.103294,0.105400,pass
14,0.058041,0.570528,0.154528,0.069391,0.019615,0.109157,0.171612,0.081989,0.064216,0.174036,...,0.118867,0.053489,0.015468,0.003269,0.128946,0.104521,0.093572,0.101585,0.093636,pass
15,0.098994,0.640001,0.257215,0.106616,0.031245,0.145965,0.221580,0.107351,0.087285,0.224549,...,0.144422,0.067989,0.019406,0.004985,0.156980,0.125875,0.120718,0.131094,0.139231,pass
16,0.063846,0.394913,0.157019,0.064625,0.018260,0.088837,0.136093,0.065835,0.056956,0.145635,...,0.099499,0.044957,0.012128,0.002970,0.102402,0.077522,0.080397,0.081847,0.085803,pass
17,0.063942,0.696582,0.174691,0.087238,0.024726,0.136772,0.215930,0.104834,0.087827,0.244738,...,0.157570,0.075161,0.019436,0.004310,0.165051,0.128393,0.130584,0.128701,0.122235,pass
18,0.075144,0.669422,0.216881,0.089276,0.028309,0.138688,0.200839,0.107487,0.084440,0.247052,...,0.147976,0.070363,0.018080,0.004580,0.156812,0.114854,0.122199,0.122832,0.126006,pass
19,0.048396,0.557327,0.151386,0.062432,0.017503,0.101047,0.163402,0.075512,0.056702,0.166664,...,0.122017,0.051481,0.013629,0.002778,0.121235,0.092496,0.088316,0.091079,0.081235,pass

[[1.18422342 1.24747752 1.27399913 1.27937318 1.30236224 1.2817225
  1.17155345 1.19230156 1.25031272 1.25685726 1.23865498 1.19943059
  1.19265874 1.21471635 1.24904276 1.17191874 1.28821352 1.20059671
  1.20491155 1.24616538 1.2053243  1.286653  ]]
BARINEL SCORES

,cp 19,h 21,h 13,swap 10,cp 15,cp 14,cp 18,cp 6,cp 5,cp 17,...,h 0,h 1,x 4,cp 7,swap 8,h 16,h 11,h 3,cp 9,cswap 20
sum,0.542072,0.541302,0.525856,0.524945,0.524534,0.523947,0.523432,0.520794,0.520338,0.520178,...,0.518463,0.517923,0.517479,0.516999,0.515052,0.513466,0.510815,0.508453,0.505468,0.504049

custom SCORES

,cp 19,h 21,cp 18,h 13,cp 17,cp 5,h 0,cp 12,swap 10,h 2,...,cp 15,h 16,h 1,cp 6,x 4,swap 8,h 11,h 3,cswap 20,cp 9
sum,0.714722,0.701557,0.690849,0.690227,0.689543,0.687915,0.685233,0.683147,0.682353,0.680899,...,0.678164,0.677996,0.673989,0.673376,0.6728,0.671462,0.668996,0.661613,0.661246,0.656181

DSTAR SCORES

,cswap 20,swap 10,cp 19,cp 12,cp 15,cp 9,x 4,swap 8,h 16,h 1,...,h 3,cp 14,h 11,cp 18,h 21,h 13,cp 7,cp 17,cp 6,cp 5
sum,2.103392,0.454388,0.411589,0.363359,0.339628,0.295668,0.186498,0.162989,0.13468,0.119997,...,0.10617,0.088079,0.076774,0.068747,0.064946,0.056894,0.037031,0.006014,0.002998,0.000162

ERROR GATE LOCATION:
20
Now evolving the following mutant:  AddGate_rxx_inGap_9_.qasm

100%|██████████| 10/10 [01:01<00:00,  6.13s/it]
100%|██████████| 10/10 [00:59<00:00,  5.95s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,rxx 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.067054,0.209485,0.102735,0.030191,0.088222,0.234047,0.123829,0.116699,0.265419,0.258494,...,0.194281,0.091334,0.013240,0.005943,0.184478,0.148952,0.159024,0.085222,0.136623,fail
1,0.070838,0.223846,0.114147,0.034273,0.095457,0.251854,0.126779,0.092995,0.276556,0.218159,...,0.163070,0.073347,0.012912,0.005341,0.177754,0.136958,0.127723,0.082002,0.127400,fail
2,0.084453,0.270638,0.136381,0.040223,0.095615,0.262381,0.131479,0.116286,0.284968,0.285204,...,0.218386,0.098087,0.013428,0.006713,0.196456,0.152651,0.166416,0.082963,0.157450,fail
3,0.083429,0.271443,0.132911,0.040282,0.097912,0.262943,0.137068,0.100485,0.291728,0.244541,...,0.176938,0.081571,0.013494,0.006587,0.185845,0.139429,0.141675,0.084847,0.153055,fail
4,0.064083,0.191083,0.091064,0.029169,0.088708,0.222511,0.119594,0.117550,0.254216,0.264414,...,0.198520,0.093326,0.012062,0.005576,0.194235,0.158735,0.164221,0.082569,0.135750,fail
5,0.073385,0.231733,0.116069,0.033970,0.104351,0.284719,0.148813,0.118245,0.316206,0.274065,...,0.203908,0.091001,0.014850,0.005803,0.225294,0.151770,0.161562,0.093830,0.138310,fail
6,0.081025,0.255149,0.127692,0.039034,0.104089,0.279654,0.143920,0.118771,0.310480,0.269452,...,0.179567,0.089915,0.014258,0.006291,0.205572,0.163802,0.161790,0.095699,0.155416,fail
7,0.056038,0.172055,0.084466,0.025852,0.075555,0.198353,0.102233,0.084495,0.224084,0.184702,...,0.135784,0.065519,0.010557,0.004499,0.136050,0.116414,0.114878,0.067757,0.108164,fail
8,0.080103,0.249024,0.118865,0.036322,0.097586,0.252048,0.131637,0.123044,0.290163,0.285704,...,0.231434,0.104992,0.014514,0.006865,0.207781,0.177035,0.177330,0.095313,0.160368,fail
9,0.059527,0.188085,0.097590,0.029267,0.095904,0.258025,0.132635,0.103831,0.280780,0.250226,...,0.196834,0.083883,0.013050,0.004732,0.189606,0.149467,0.146767,0.085480,0.113962,fail
10,0.078516,0.248102,0.123089,0.036538,0.092149,0.229101,0.123880,0.129200,0.260123,0.296841,...,0.226272,0.102412,0.012824,0.006495,0.201115,0.159549,0.176990,0.088870,0.157894,pass
11,0.048260,0.149766,0.074913,0.022390,0.058354,0.153648,0.078790,0.067067,0.169972,0.144712,...,0.095682,0.051169,0.008198,0.003936,0.089335,0.081375,0.087459,0.052432,0.092377,pass
12,0.077820,0.247717,0.124293,0.037639,0.088224,0.223786,0.114017,0.099268,0.245826,0.232244,...,0.160772,0.077120,0.011196,0.006073,0.210859,0.137996,0.140302,0.078404,0.148342,pass
13,0.065029,0.215866,0.106262,0.031594,0.079762,0.233670,0.121019,0.090035,0.257839,0.234278,...,0.178300,0.079513,0.012353,0.005338,0.170814,0.131288,0.133090,0.073965,0.118763,pass
14,0.072763,0.217092,0.108735,0.032350,0.095922,0.240020,0.124092,0.109949,0.267950,0.233628,...,0.151249,0.078681,0.012571,0.005976,0.194888,0.136051,0.144741,0.086363,0.147897,pass
15,0.070672,0.221960,0.110973,0.033249,0.095955,0.254003,0.137213,0.120246,0.288024,0.269952,...,0.195520,0.090471,0.013752,0.006041,0.198960,0.149968,0.160222,0.089335,0.142642,pass
16,0.073375,0.228950,0.118245,0.035338,0.105606,0.282042,0.146594,0.124650,0.314193,0.274828,...,0.202696,0.095551,0.014970,0.005979,0.195467,0.169734,0.164726,0.097735,0.141943,pass
17,0.047281,0.147892,0.073952,0.021906,0.066544,0.178413,0.093703,0.079024,0.200073,0.186169,...,0.142907,0.063438,0.009591,0.003952,0.142079,0.108004,0.110567,0.061571,0.093035,pass
18,0.127652,0.386453,0.198197,0.059001,0.131684,0.294791,0.152037,0.152766,0.328652,0.296226,...,0.170503,0.103211,0.015938,0.010360,0.216547,0.164214,0.185964,0.114214,0.253000,pass
19,0.083640,0.255400,0.126403,0.038845,0.096350,0.221657,0.115596,0.122540,0.253294,0.259555,...,0.200278,0.094289,0.012519,0.007002,0.196544,0.163360,0.165818,0.088512,0.169657,pass

[[1.17305983 1.19972739 1.2156017  1.18970798 1.10612071 1.13590623
  1.1464914  1.12636871 1.13148879 1.12705682 1.18382308 1.18434742
  1.16169621 1.21889509 1.20269315 1.12193564 1.17655293 1.18384465
  1.18401259 1.16558441 1.11839052 1.15663934]]
BARINEL SCORES

,swap 8,cp 16,rxx 13,cp 15,cp 9,cp 6,h 3,x 4,cp 7,cp 12,...,h 2,h 1,h 11,h 14,cp 20,cp 18,h 21,cp 19,cp 5,h 0
sum,0.524089,0.52028,0.51939,0.518174,0.51701,0.51649,0.516169,0.511622,0.510862,0.510731,...,0.508609,0.507196,0.506986,0.499464,0.493817,0.492532,0.491443,0.490568,0.48827,0.486141

custom SCORES

,swap 8,h 3,cp 16,cp 9,cp 15,rxx 13,cp 7,x 4,cp 6,swap 10,...,cp 12,h 17,h 1,cp 20,h 14,cp 19,cp 18,h 21,cp 5,h 0
sum,0.683791,0.668957,0.668027,0.667163,0.666694,0.666311,0.664464,0.663043,0.661358,0.66083,...,0.654637,0.649574,0.649007,0.641929,0.640109,0.639652,0.639024,0.635567,0.631888,0.626713

DSTAR SCORES

,rxx 13,cp 9,swap 10,cp 12,cp 16,cp 20,swap 8,x 4,h 2,h 3,...,h 11,cp 19,h 14,h 17,cp 7,h 1,h 21,cp 18,cp 6,cp 5
sum,0.620516,0.595049,0.559178,0.517042,0.510328,0.415538,0.307497,0.30649,0.2018,0.196084,...,0.135666,0.112736,0.107559,0.081573,0.07033,0.067599,0.048237,0.011077,0.001731,0.000338

ERROR GATE LOCATION:
13
Now evolving the following mutant:  AddGate_rx_inGap_13_.qasm

100%|██████████| 10/10 [01:03<00:00,  6.32s/it]
100%|██████████| 10/10 [01:00<00:00,  6.06s/it]

,h 21,cp 20,rx 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.087028,0.259803,0.765572,0.166213,0.045986,0.156143,0.485260,0.141578,0.372246,0.291508,...,0.107047,0.094140,0.025717,0.007670,0.241491,0.171687,0.244080,0.203640,0.202065,fail
1,0.074764,0.224827,0.507538,0.136700,0.038148,0.125883,0.421857,0.135332,0.265560,0.250599,...,0.117216,0.079244,0.024215,0.005938,0.220464,0.160222,0.191353,0.178779,0.158442,fail
2,0.098589,0.304029,0.585727,0.178266,0.051531,0.147233,0.466143,0.149277,0.306090,0.277667,...,0.130311,0.091442,0.026771,0.008101,0.216950,0.156918,0.212107,0.195873,0.203785,fail
3,0.065837,0.194725,0.578740,0.132887,0.034689,0.131767,0.427353,0.136286,0.294167,0.246744,...,0.110316,0.081260,0.024138,0.005703,0.196469,0.157544,0.197700,0.179140,0.149300,fail
4,0.086387,0.279252,0.577276,0.171770,0.046934,0.138547,0.443571,0.145599,0.296482,0.266740,...,0.130696,0.088234,0.025904,0.007404,0.204657,0.148428,0.202500,0.184335,0.179904,fail
5,0.064848,0.205950,0.459353,0.141168,0.034996,0.141664,0.428695,0.161265,0.259136,0.270240,...,0.119757,0.082686,0.028346,0.005710,0.188662,0.141807,0.183208,0.186979,0.136568,fail
6,0.073816,0.231536,0.536957,0.149408,0.038404,0.130564,0.434329,0.139523,0.278979,0.261819,...,0.123969,0.083756,0.025366,0.006361,0.198062,0.145704,0.194094,0.180773,0.158337,fail
7,0.081870,0.253448,0.530466,0.153695,0.042634,0.144861,0.447077,0.155960,0.284810,0.277458,...,0.113778,0.086387,0.027492,0.007059,0.192654,0.143440,0.196887,0.188977,0.171635,fail
8,0.064552,0.187295,0.586605,0.129931,0.034066,0.144129,0.423603,0.145053,0.305348,0.251881,...,0.101873,0.082953,0.026226,0.005600,0.222565,0.169502,0.207427,0.192696,0.149897,fail
9,0.076891,0.233069,0.450049,0.140387,0.039153,0.141019,0.383827,0.142988,0.254086,0.237462,...,0.101095,0.076636,0.026576,0.006239,0.190205,0.138335,0.180835,0.182968,0.159066,fail
10,0.058607,0.180165,0.349767,0.119087,0.029076,0.109470,0.321616,0.115992,0.199403,0.195916,...,0.091310,0.060948,0.020340,0.004425,0.188260,0.139483,0.148669,0.149335,0.120839,pass
11,0.093559,0.281952,0.606459,0.155120,0.048310,0.166521,0.470645,0.166640,0.323636,0.292456,...,0.115226,0.088284,0.028788,0.007697,0.263624,0.168046,0.227703,0.218337,0.203551,pass
12,0.079410,0.251833,0.415602,0.137410,0.040934,0.109440,0.369979,0.118075,0.222412,0.210910,...,0.130102,0.075605,0.023975,0.006687,0.176995,0.148230,0.169373,0.164242,0.159959,pass
13,0.072273,0.229912,0.506154,0.126130,0.038465,0.132331,0.412107,0.145679,0.267284,0.250372,...,0.114417,0.078419,0.025298,0.006293,0.208416,0.139184,0.186304,0.179946,0.156698,pass
14,0.090251,0.268550,0.606150,0.131128,0.046585,0.144589,0.433240,0.140643,0.306576,0.252871,...,0.103012,0.085464,0.025852,0.007804,0.202821,0.156278,0.212217,0.192129,0.201020,pass
15,0.071370,0.233443,0.410596,0.125490,0.038547,0.110420,0.357707,0.125088,0.220532,0.216512,...,0.100964,0.069591,0.022407,0.006161,0.180551,0.119581,0.160752,0.154492,0.146413,pass
16,0.049421,0.153077,0.296312,0.091749,0.025260,0.079160,0.247810,0.080635,0.159679,0.145679,...,0.072362,0.049318,0.015438,0.003977,0.132562,0.102816,0.116975,0.112094,0.103411,pass
17,0.079966,0.237049,0.489363,0.119885,0.040890,0.126690,0.358706,0.120653,0.257529,0.211566,...,0.089547,0.074903,0.023660,0.006883,0.171223,0.149074,0.183852,0.172370,0.173673,pass
18,0.064738,0.215785,0.456726,0.140786,0.035337,0.123417,0.388559,0.136735,0.246524,0.229865,...,0.127451,0.077930,0.025434,0.005721,0.192663,0.149390,0.178850,0.175331,0.136467,pass
19,0.098851,0.311450,0.563174,0.150024,0.054080,0.148466,0.425824,0.152448,0.295247,0.271212,...,0.094684,0.085483,0.026477,0.008542,0.190161,0.145803,0.205301,0.190926,0.211415,pass

[[1.27280719 1.28069832 1.37241494 1.18810126 1.26755182 1.11386884
  1.11254511 1.10998525 1.27616973 1.10750215 1.12050354 1.24481783
  1.09013685 1.13053167 1.1117997  1.08710631 1.23149617 1.16539897
  1.11951211 1.21421404 1.08656697 1.22100168]]
BARINEL SCORES

,rx 19,h 13,cp 18,cp 12,cp 15,cp 7,h 2,h 16,cp 14,swap 8,...,h 1,x 4,h 3,swap 10,h 11,h 0,cp 5,cp 17,h 21,cp 20
sum,0.542709,0.538599,0.536396,0.53613,0.535317,0.531642,0.528972,0.528524,0.527269,0.526646,...,0.523017,0.520719,0.519601,0.519015,0.516196,0.508462,0.506143,0.505632,0.505263,0.501131

custom SCORES

,rx 19,h 13,cp 18,h 2,cp 12,cp 15,swap 10,cp 7,h 16,swap 8,...,cp 9,h 21,cp 17,cp 6,h 1,h 3,h 0,cp 5,cp 20,h 11
sum,0.728915,0.710435,0.695719,0.689543,0.684571,0.684208,0.680535,0.679412,0.6757,0.675494,...,0.667197,0.666039,0.665861,0.665335,0.665091,0.665026,0.66367,0.661972,0.661581,0.660796

DSTAR SCORES

,rx 19,cp 15,h 13,cp 9,swap 10,cp 12,cp 20,x 4,h 2,h 1,...,cp 18,cp 14,h 16,h 11,swap 8,cp 7,h 21,cp 17,cp 6,cp 5
sum,2.116776,1.379971,0.68073,0.652982,0.565578,0.564295,0.455833,0.360613,0.342737,0.299976,...,0.199284,0.186754,0.174665,0.162061,0.121067,0.066719,0.055768,0.015896,0.006641,0.00043

ERROR GATE LOCATION:
19
Now evolving the following mutant:  AddGate_z_inGap_10_.qasm

100%|██████████| 10/10 [00:46<00:00,  4.64s/it]
100%|██████████| 10/10 [00:45<00:00,  4.56s/it]

,h 21,cp 20,cp 19,cp 18,h 17,z 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.068032,0.222666,0.110162,0.032773,0.101665,0.389894,0.285768,0.148996,0.105675,0.257463,...,0.162829,0.078283,0.026534,0.005508,0.182360,0.127169,0.136610,0.156444,0.125187,fail
1,0.074755,0.243331,0.124638,0.036526,0.104250,0.390900,0.288389,0.148251,0.111920,0.256923,...,0.151906,0.082602,0.027969,0.006157,0.177217,0.141334,0.140919,0.161724,0.138545,fail
2,0.080266,0.252065,0.125831,0.037799,0.101993,0.360011,0.266822,0.138050,0.113381,0.267793,...,0.184731,0.087064,0.024982,0.006708,0.172527,0.131769,0.148055,0.146770,0.152337,fail
3,0.077670,0.238408,0.121876,0.034901,0.096221,0.346607,0.250862,0.126326,0.118381,0.267026,...,0.190290,0.091960,0.025150,0.006391,0.208095,0.159717,0.159151,0.149341,0.150191,fail
4,0.088948,0.284104,0.138792,0.040499,0.103667,0.390910,0.287680,0.146815,0.121368,0.289329,...,0.178096,0.091189,0.026825,0.006905,0.225653,0.148322,0.161066,0.161027,0.163863,fail
5,0.083258,0.268733,0.136191,0.039576,0.097181,0.346208,0.258430,0.133917,0.116173,0.274693,...,0.186349,0.090229,0.025865,0.007004,0.189325,0.138432,0.152388,0.149003,0.157070,fail
6,0.059800,0.197250,0.098291,0.028452,0.076474,0.282378,0.214466,0.107285,0.086293,0.211880,...,0.155407,0.070359,0.020038,0.004654,0.163272,0.120343,0.119400,0.116968,0.106877,fail
7,0.093734,0.305822,0.150261,0.044970,0.092033,0.344704,0.262037,0.133954,0.105559,0.265817,...,0.163619,0.082551,0.023596,0.007020,0.204043,0.147276,0.142437,0.142516,0.164658,fail
8,0.076986,0.230736,0.117579,0.034052,0.105520,0.384115,0.267853,0.142638,0.128475,0.287566,...,0.181027,0.092673,0.026792,0.006669,0.217354,0.151108,0.164158,0.161124,0.154327,fail
9,0.080271,0.258081,0.128025,0.037893,0.090750,0.321619,0.245212,0.126934,0.117363,0.293644,...,0.203936,0.098033,0.023630,0.006791,0.183182,0.148867,0.162422,0.136347,0.153417,fail
10,0.074054,0.222531,0.111610,0.033744,0.087394,0.287511,0.203991,0.107003,0.111650,0.254876,...,0.193339,0.088614,0.020778,0.006356,0.176553,0.148920,0.151491,0.126284,0.146947,pass
11,0.071795,0.224997,0.114332,0.033571,0.085540,0.309460,0.223531,0.114753,0.102314,0.238064,...,0.173694,0.079071,0.021764,0.005903,0.179495,0.129007,0.136271,0.130630,0.136131,pass
12,0.084651,0.251748,0.130085,0.039101,0.108058,0.348626,0.248627,0.127790,0.111505,0.230192,...,0.136204,0.076370,0.024793,0.006920,0.166429,0.143640,0.136172,0.149838,0.163596,pass
13,0.090120,0.273169,0.134344,0.040659,0.105304,0.351389,0.246184,0.129653,0.124603,0.266147,...,0.162832,0.087978,0.025452,0.007488,0.208173,0.154777,0.159108,0.154156,0.177994,pass
14,0.067961,0.222087,0.110986,0.033038,0.088970,0.315646,0.235694,0.122653,0.102030,0.253420,...,0.161183,0.078273,0.022156,0.005524,0.178049,0.130933,0.134988,0.132915,0.126753,pass
15,0.073394,0.240241,0.116399,0.034635,0.072951,0.253732,0.197174,0.103232,0.097304,0.260484,...,0.187299,0.082494,0.018659,0.006073,0.178860,0.115346,0.140256,0.107845,0.136812,pass
16,0.080306,0.249804,0.124169,0.037655,0.096696,0.329952,0.233117,0.126493,0.113443,0.254361,...,0.159561,0.080606,0.023185,0.006600,0.201019,0.142721,0.146980,0.144195,0.156072,pass
17,0.071999,0.233350,0.116841,0.034543,0.088493,0.309110,0.233409,0.118715,0.098235,0.242705,...,0.174887,0.079219,0.022288,0.005694,0.181430,0.132515,0.134336,0.130889,0.131575,pass
18,0.046344,0.153306,0.078018,0.022791,0.071779,0.281444,0.205838,0.105208,0.081367,0.204652,...,0.158240,0.068068,0.019672,0.004013,0.141519,0.112417,0.110611,0.112840,0.083043,pass
19,0.068870,0.209177,0.107942,0.031097,0.086183,0.293211,0.205927,0.105974,0.109078,0.244562,...,0.190294,0.085358,0.022014,0.005943,0.174645,0.137396,0.145821,0.130383,0.135613,pass

[[1.19601397 1.22270226 1.20050695 1.22386077 1.08811061 1.09888161
  1.09757046 1.10109289 1.14242135 1.09891232 1.11587815 1.12526067
  1.1318355  1.1599192  1.13340831 1.11262463 1.10021468 1.17342571
  1.12927126 1.10424787 1.0917986  1.12281496]]
BARINEL SCORES

,cp 15,cp 14,z 16,cp 6,h 1,swap 10,cp 20,cp 19,cp 12,h 17,...,h 21,cp 7,cp 9,h 13,h 2,cp 5,h 0,h 3,swap 8,h 11
sum,0.540529,0.538115,0.535953,0.532426,0.528788,0.525056,0.523087,0.522309,0.521738,0.521059,...,0.517917,0.517622,0.517472,0.516787,0.51571,0.513238,0.512572,0.512068,0.508776,0.508435

custom SCORES

,cp 15,cp 14,z 16,cp 20,cp 6,cp 19,cp 18,h 1,h 21,swap 10,...,h 13,cp 7,cp 9,h 17,h 2,h 3,h 0,swap 8,cp 5,h 11
sum,0.688846,0.686244,0.68319,0.682982,0.680523,0.679068,0.677512,0.673121,0.672777,0.672763,...,0.664384,0.664291,0.663895,0.662802,0.658078,0.656634,0.656453,0.656311,0.654407,0.650273

DSTAR SCORES

,z 16,swap 10,cp 12,cp 9,cp 15,cp 20,x 4,swap 8,h 2,h 1,...,cp 14,h 11,cp 19,h 13,h 17,cp 7,h 21,cp 18,cp 6,cp 5
sum,0.96748,0.607447,0.573543,0.568506,0.56434,0.509428,0.313761,0.264263,0.193927,0.193829,...,0.164052,0.145996,0.14057,0.114437,0.086346,0.069232,0.057246,0.013056,0.006183,0.000405

ERROR GATE LOCATION:
16
Now evolving the following mutant:  AddGate_rzz_inGap_7_.qasm

100%|██████████| 10/10 [00:46<00:00,  4.67s/it]
100%|██████████| 10/10 [00:43<00:00,  4.39s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,swap 12,...,cp 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.057214,0.169620,0.084317,0.025586,0.091082,0.241907,0.129587,0.115779,0.273715,0.216479,...,0.242605,0.096070,0.026965,0.004795,0.212128,0.205330,0.174077,0.203079,0.114906,fail
1,0.077240,0.254138,0.126800,0.037697,0.112132,0.315743,0.163078,0.117363,0.292667,0.223566,...,0.245116,0.097148,0.032420,0.006221,0.225198,0.215235,0.173540,0.227258,0.143738,fail
2,0.092561,0.287274,0.149056,0.043889,0.122427,0.326166,0.166439,0.140742,0.322196,0.225823,...,0.252622,0.106162,0.032263,0.007267,0.253757,0.237225,0.197002,0.242488,0.178928,fail
3,0.061237,0.186210,0.097523,0.028857,0.090637,0.239312,0.125931,0.111108,0.263365,0.202783,...,0.212350,0.085673,0.024179,0.005062,0.209156,0.186944,0.158598,0.188194,0.125438,fail
4,0.098115,0.303297,0.157673,0.046175,0.118512,0.293800,0.152628,0.134767,0.304626,0.201069,...,0.242233,0.098487,0.029586,0.007618,0.223326,0.219420,0.180369,0.219880,0.185399,fail
5,0.064354,0.209284,0.101778,0.030906,0.085588,0.239976,0.130383,0.104867,0.264866,0.195170,...,0.216243,0.085724,0.025300,0.005363,0.193490,0.180171,0.152982,0.184832,0.125930,fail
6,0.065578,0.211152,0.108025,0.031657,0.092304,0.264648,0.133153,0.095240,0.235167,0.175439,...,0.212663,0.080115,0.027086,0.005144,0.184394,0.184448,0.142049,0.191407,0.118586,fail
7,0.089251,0.291248,0.146790,0.044195,0.111397,0.290387,0.155160,0.127191,0.307740,0.216043,...,0.241434,0.099119,0.029527,0.007334,0.210880,0.207557,0.176878,0.212863,0.170328,fail
8,0.104447,0.326293,0.161021,0.048659,0.123043,0.315781,0.163202,0.136272,0.305045,0.201658,...,0.279519,0.100962,0.032149,0.008178,0.238365,0.241370,0.186371,0.240284,0.197726,fail
9,0.092835,0.284751,0.144048,0.041666,0.124807,0.326248,0.166739,0.143993,0.315862,0.213498,...,0.284211,0.106126,0.033341,0.007314,0.249675,0.248465,0.197589,0.250319,0.181513,fail
10,0.054841,0.166320,0.090463,0.024924,0.085109,0.218146,0.109477,0.101286,0.216045,0.156420,...,0.218043,0.076550,0.023481,0.004625,0.158600,0.176100,0.137928,0.171074,0.113392,pass
11,0.051042,0.157320,0.075125,0.023594,0.091138,0.236777,0.123754,0.091046,0.208478,0.173999,...,0.232356,0.073373,0.026088,0.004083,0.159393,0.178992,0.133673,0.180422,0.096827,pass
12,0.078827,0.249636,0.124282,0.036489,0.082704,0.203378,0.102228,0.100683,0.229908,0.189277,...,0.240543,0.080632,0.021375,0.006456,0.152046,0.175229,0.140819,0.161080,0.150398,pass
13,0.069545,0.223820,0.112216,0.033322,0.078530,0.194363,0.103969,0.081033,0.184654,0.110670,...,0.184022,0.059941,0.020546,0.005410,0.142908,0.150940,0.107644,0.147267,0.126923,pass
14,0.079613,0.246836,0.125451,0.036321,0.095110,0.247559,0.128152,0.124768,0.293439,0.226083,...,0.251902,0.100123,0.026015,0.006255,0.216643,0.208393,0.180594,0.200106,0.152577,pass
15,0.078140,0.246308,0.123538,0.037068,0.086198,0.207561,0.108908,0.103698,0.236698,0.179675,...,0.231899,0.079852,0.021155,0.006179,0.172428,0.175867,0.143484,0.164597,0.146474,pass
16,0.069047,0.208047,0.104249,0.030892,0.082227,0.205964,0.104490,0.101704,0.227175,0.176881,...,0.221666,0.081378,0.021690,0.005485,0.174705,0.176623,0.145150,0.168372,0.135459,pass
17,0.063699,0.202192,0.100937,0.030871,0.082378,0.213259,0.114153,0.096420,0.222916,0.149496,...,0.184674,0.074781,0.022839,0.005354,0.142001,0.158940,0.131986,0.162139,0.122734,pass
18,0.068421,0.212852,0.102803,0.031114,0.079630,0.211419,0.109818,0.097464,0.244881,0.213431,...,0.223300,0.081538,0.021045,0.005069,0.211448,0.179945,0.149092,0.171277,0.129395,pass
19,0.045966,0.132366,0.065774,0.020356,0.052277,0.108954,0.058543,0.068321,0.140629,0.111351,...,0.145166,0.047973,0.011707,0.003564,0.110780,0.113654,0.091646,0.100167,0.092668,pass

[[1.3009805  1.29313701 1.26089899 1.28289618 1.16432349 1.14313865
  1.12183985 1.17322972 1.11670159 1.0901272  1.23871599 1.10480786
  1.12459342 1.17007792 1.11096149 1.13863606 1.27189642 1.15324758
  1.16860542 1.13592261 1.15856236 1.28185867]]
BARINEL SCORES

,rzz 10,cp 15,cp 16,cp 6,swap 9,x 4,h 1,h 17,cp 13,h 2,...,h 3,cp 19,cp 18,cp 20,swap 12,cp 5,h 21,h 0,h 11,cp 8
sum,0.585761,0.582911,0.582282,0.575552,0.57538,0.572816,0.570516,0.567991,0.566839,0.560848,...,0.556464,0.55478,0.55432,0.552262,0.551113,0.550591,0.549143,0.549059,0.536985,0.532375

custom SCORES

,cp 16,rzz 10,cp 15,cp 6,x 4,swap 9,h 1,h 17,cp 18,cp 20,...,cp 5,cp 13,h 0,h 14,h 2,h 3,cp 7,h 11,swap 12,cp 8
sum,0.74869,0.747549,0.746394,0.739388,0.737965,0.737147,0.735761,0.733323,0.732104,0.7308,...,0.725665,0.725086,0.725013,0.723559,0.720118,0.719036,0.713309,0.703278,0.701309,0.688105

DSTAR SCORES

,rzz 10,cp 13,cp 16,cp 20,cp 8,swap 9,x 4,h 1,h 3,swap 12,...,cp 15,cp 19,h 14,h 11,h 17,cp 7,h 21,cp 18,cp 6,cp 5
sum,1.352547,0.68208,0.676092,0.52856,0.486256,0.478794,0.415913,0.401515,0.38655,0.367171,...,0.199674,0.147921,0.137357,0.134693,0.106242,0.084895,0.060468,0.01396,0.008393,0.000411

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_s_inGap_11_.qasm

100%|██████████| 10/10 [00:46<00:00,  4.61s/it]
100%|██████████| 10/10 [00:45<00:00,  4.52s/it]

,h 21,sdg 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.072931,0.072931,0.240759,0.120895,0.035384,0.082575,0.229758,0.118360,0.098552,0.244455,...,0.162106,0.079251,0.021919,0.006252,0.178765,0.114781,0.134879,0.126062,0.145866,fail
1,0.098487,0.098487,0.321938,0.155962,0.047052,0.087893,0.232636,0.119165,0.106611,0.283633,...,0.219916,0.094839,0.022567,0.007745,0.208007,0.145061,0.157941,0.133747,0.186661,fail
2,0.105577,0.105577,0.335297,0.168512,0.050340,0.117390,0.291045,0.155580,0.139302,0.330324,...,0.228159,0.108366,0.030351,0.008795,0.223860,0.174029,0.184614,0.178356,0.212544,fail
3,0.080453,0.080453,0.255072,0.127244,0.036915,0.082813,0.222768,0.112792,0.109498,0.280692,...,0.208039,0.093104,0.020756,0.006413,0.193969,0.132300,0.157195,0.124710,0.156450,fail
4,0.104622,0.104622,0.329361,0.165690,0.048615,0.092076,0.216731,0.112407,0.124595,0.289667,...,0.202901,0.099627,0.022752,0.008921,0.193911,0.142365,0.170233,0.132209,0.214642,fail
5,0.090507,0.090507,0.289051,0.148875,0.043555,0.104540,0.270871,0.136478,0.115762,0.273750,...,0.175310,0.087232,0.025695,0.007346,0.198800,0.145852,0.152021,0.150923,0.177866,fail
6,0.085196,0.085196,0.271913,0.138159,0.040580,0.114582,0.306085,0.159977,0.129950,0.303559,...,0.201779,0.098299,0.029926,0.007197,0.213423,0.165867,0.170498,0.177683,0.173615,fail
7,0.074889,0.074889,0.247722,0.127813,0.037249,0.095474,0.253198,0.131532,0.110697,0.270443,...,0.186360,0.087565,0.024203,0.006434,0.197245,0.135387,0.147372,0.143933,0.148873,fail
8,0.083471,0.083471,0.271152,0.136860,0.041018,0.092853,0.246264,0.129599,0.113328,0.288933,...,0.216875,0.095070,0.023662,0.006759,0.193611,0.142400,0.158682,0.139317,0.162030,fail
9,0.111814,0.111814,0.355882,0.179364,0.052748,0.121868,0.310129,0.162139,0.144248,0.337588,...,0.219388,0.109185,0.031024,0.008992,0.226684,0.176324,0.190383,0.183907,0.220689,fail
10,0.045065,0.045065,0.136835,0.068184,0.020549,0.070476,0.183081,0.094169,0.079645,0.178307,...,0.124315,0.060300,0.018124,0.003973,0.118581,0.100435,0.104052,0.106523,0.097710,pass
11,0.071009,0.071009,0.212770,0.103773,0.032792,0.085276,0.194256,0.107258,0.108311,0.238788,...,0.160567,0.081194,0.021001,0.006176,0.170697,0.148760,0.144604,0.129161,0.154445,pass
12,0.085609,0.085609,0.268066,0.133046,0.039567,0.097177,0.240412,0.128141,0.123975,0.286457,...,0.201407,0.096357,0.025114,0.007380,0.201795,0.154216,0.166489,0.149225,0.179753,pass
13,0.054219,0.054219,0.166963,0.079823,0.025439,0.085293,0.224256,0.118378,0.090521,0.214697,...,0.153029,0.071858,0.022072,0.004416,0.163092,0.133123,0.124592,0.132558,0.108923,pass
14,0.077368,0.077368,0.244716,0.119514,0.036249,0.092237,0.234425,0.123003,0.118569,0.277214,...,0.199890,0.093255,0.024084,0.006416,0.208283,0.163173,0.162954,0.146311,0.158733,pass
15,0.047586,0.047586,0.150693,0.081190,0.022970,0.086398,0.236198,0.123846,0.103237,0.258381,...,0.202435,0.083170,0.023010,0.004152,0.180914,0.140585,0.141180,0.135514,0.097457,pass
16,0.093472,0.093472,0.296791,0.145651,0.044207,0.093924,0.227686,0.119916,0.108554,0.238322,...,0.143967,0.080145,0.024066,0.007497,0.176307,0.151093,0.141077,0.144035,0.186662,pass
17,0.092254,0.092254,0.292773,0.147494,0.044342,0.105222,0.264767,0.141235,0.133521,0.323244,...,0.228920,0.109618,0.026816,0.008302,0.187457,0.160307,0.180660,0.152810,0.193666,pass
18,0.082356,0.082356,0.256881,0.126862,0.038601,0.095802,0.256137,0.131009,0.105953,0.248858,...,0.167407,0.081627,0.024497,0.006500,0.168974,0.149114,0.141200,0.147224,0.161674,pass
19,0.082480,0.082480,0.243246,0.122956,0.036721,0.103364,0.230634,0.122887,0.123322,0.251654,...,0.156877,0.086047,0.024363,0.007286,0.196184,0.153738,0.155950,0.151105,0.181436,pass

[[1.23150183 1.23150183 1.21954834 1.22068204 1.21691985 1.22842713
  1.20228906 1.21177411 1.20958587 1.16287496 1.26456196 1.1402353
  1.19380832 1.12903744 1.14625076 1.2269517  1.20128168 1.1176214
  1.19593334 1.17244236 1.23357594 1.22656882]]
BARINEL SCORES

,cp 18,cp 19,cp 17,swap 10,sdg 20,h 21,cp 5,h 0,swap 8,cp 12,...,cp 15,h 2,cp 14,h 13,cp 6,h 16,h 1,h 3,cp 9,h 11
sum,0.565608,0.562493,0.559375,0.556861,0.553841,0.553841,0.546572,0.541988,0.537506,0.535719,...,0.529523,0.526091,0.525156,0.521182,0.520275,0.520159,0.516702,0.503384,0.502469,0.493894

custom SCORES

,cp 18,cp 19,cp 17,h 21,sdg 20,swap 10,cp 5,h 0,cp 12,swap 8,...,x 4,cp 7,h 2,h 16,cp 6,h 13,h 1,h 3,cp 9,h 11
sum,0.738215,0.73399,0.729553,0.724355,0.724355,0.715599,0.710719,0.708185,0.691463,0.689222,...,0.682791,0.682308,0.680294,0.679903,0.679863,0.678785,0.67605,0.653887,0.652431,0.650034

DSTAR SCORES

,swap 10,cp 19,cp 12,cp 9,cp 15,x 4,swap 8,h 0,h 2,h 1,...,cp 14,h 11,h 13,h 16,cp 7,sdg 20,h 21,cp 17,cp 6,cp 5
sum,0.807593,0.694031,0.673355,0.603391,0.541313,0.349456,0.347885,0.281,0.230031,0.195062,...,0.15971,0.149775,0.128173,0.090167,0.083674,0.076818,0.076818,0.018168,0.006248,0.000557

ERROR GATE LOCATION:
20
Now evolving the following mutant:  AddGate_cz_inGap_6_.qasm

100%|██████████| 10/10 [01:03<00:00,  6.31s/it]
100%|██████████| 10/10 [00:56<00:00,  5.65s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.093897,0.288994,0.144468,0.043022,0.101089,0.236924,0.122603,0.117926,0.254030,0.150870,...,0.130149,0.083312,0.023754,0.007395,0.216255,0.231064,0.160256,0.156059,0.199102,fail
1,0.105467,0.343154,0.169883,0.050424,0.110935,0.285489,0.146745,0.118523,0.281077,0.139796,...,0.141804,0.094492,0.028150,0.008790,0.188400,0.226292,0.163225,0.168612,0.210595,fail
2,0.088982,0.277249,0.138164,0.041394,0.103812,0.247723,0.134904,0.130598,0.308456,0.146155,...,0.166322,0.096852,0.024602,0.007350,0.246703,0.248391,0.182096,0.161855,0.207765,fail
3,0.074349,0.233566,0.118025,0.034394,0.096410,0.244327,0.130596,0.125923,0.297300,0.133049,...,0.162199,0.096197,0.024055,0.006372,0.205261,0.221991,0.173112,0.152403,0.181543,fail
4,0.087701,0.285071,0.140034,0.042177,0.106877,0.282622,0.148003,0.119158,0.283899,0.139185,...,0.138964,0.088609,0.026505,0.007079,0.209118,0.222130,0.161974,0.166384,0.190717,fail
5,0.082912,0.267178,0.135220,0.040376,0.096334,0.257331,0.129903,0.094522,0.227106,0.114285,...,0.108271,0.070416,0.023722,0.006435,0.172924,0.185018,0.127043,0.144927,0.164511,fail
6,0.083923,0.268785,0.134924,0.039964,0.096423,0.247387,0.127847,0.108369,0.244121,0.121070,...,0.117911,0.075577,0.023680,0.006651,0.193886,0.197953,0.144582,0.150846,0.177518,fail
7,0.076157,0.248327,0.124597,0.037118,0.102159,0.270511,0.142589,0.113829,0.275219,0.131971,...,0.135221,0.085308,0.025769,0.006389,0.177205,0.207851,0.150481,0.155191,0.171720,fail
8,0.106072,0.336686,0.171439,0.050321,0.119430,0.297842,0.154116,0.135887,0.313780,0.142689,...,0.143837,0.100916,0.028235,0.009028,0.204354,0.238609,0.179931,0.173396,0.219171,fail
9,0.103519,0.323984,0.164762,0.048349,0.117395,0.272948,0.144971,0.139282,0.302665,0.165955,...,0.160894,0.102582,0.029011,0.008856,0.231631,0.268320,0.187486,0.183806,0.230989,fail
10,0.076957,0.245183,0.125737,0.037067,0.104214,0.272052,0.139326,0.110190,0.263021,0.127510,...,0.138075,0.081898,0.025539,0.006197,0.207828,0.213195,0.150424,0.160667,0.175080,pass
11,0.049790,0.150197,0.075700,0.022890,0.068524,0.159494,0.089155,0.084272,0.183908,0.101573,...,0.095019,0.057733,0.016225,0.004116,0.140561,0.154538,0.110547,0.106604,0.123470,pass
12,0.071378,0.224073,0.112343,0.032535,0.088029,0.229184,0.122325,0.125091,0.293492,0.140419,...,0.150046,0.091030,0.021709,0.005953,0.206692,0.222886,0.169515,0.140804,0.177008,pass
13,0.087878,0.266776,0.134096,0.040886,0.108176,0.256490,0.132965,0.134947,0.303862,0.158272,...,0.159930,0.099494,0.025008,0.007257,0.220064,0.243499,0.183275,0.162291,0.199700,pass
14,0.075842,0.233358,0.116490,0.034261,0.086237,0.217685,0.112809,0.114005,0.261301,0.124818,...,0.135187,0.087210,0.021595,0.006619,0.179801,0.206134,0.158813,0.133615,0.173622,pass
15,0.052546,0.166452,0.080661,0.023563,0.067413,0.191269,0.096910,0.085728,0.210061,0.108972,...,0.118462,0.068114,0.017782,0.004154,0.153221,0.165951,0.122629,0.111236,0.125155,pass
16,0.055619,0.186106,0.093731,0.027054,0.062326,0.180092,0.094012,0.085260,0.219396,0.078480,...,0.113772,0.068958,0.016509,0.004795,0.137538,0.147017,0.120058,0.098616,0.126264,pass
17,0.057908,0.187274,0.096201,0.027435,0.081927,0.240350,0.120458,0.099808,0.241730,0.118390,...,0.121193,0.077843,0.021559,0.004851,0.167310,0.187955,0.136015,0.129764,0.141414,pass
18,0.068668,0.207031,0.104912,0.031319,0.076120,0.171805,0.090629,0.095344,0.203409,0.122850,...,0.098905,0.068000,0.018210,0.005786,0.147568,0.180821,0.126854,0.116014,0.151271,pass
19,0.055105,0.169349,0.088984,0.026623,0.068303,0.167675,0.084045,0.067269,0.159648,0.092477,...,0.088112,0.049465,0.015158,0.004177,0.133105,0.140702,0.091769,0.098052,0.114373,pass

[[1.17469435 1.19441132 1.18929631 1.17940552 1.13648903 1.12686302
  1.11494536 1.15681275 1.12560709 1.19820748 1.16484334 1.15089428
  1.17816102 1.18330516 1.14711379 1.12670862 1.21429215 1.2059366
  1.19379809 1.15008884 1.13919061 1.18235626]]
BARINEL SCORES

,cp 20,cp 18,cp 19,h 21,cp 5,h 0,h 17,cp 6,h 1,cp 15,...,cz 10,x 4,h 3,h 14,cp 7,cp 13,h 2,h 12,swap 8,cp 9
sum,0.585275,0.584731,0.583522,0.580817,0.579688,0.564472,0.564333,0.563695,0.561964,0.560782,...,0.552814,0.547073,0.546824,0.545809,0.543953,0.543669,0.54338,0.541282,0.535604,0.533838

custom SCORES

,cp 20,cp 18,cp 19,cp 5,h 21,h 0,h 17,cp 6,h 1,swap 11,...,x 4,cz 10,h 3,h 14,h 12,cp 7,h 2,cp 13,swap 8,cp 9
sum,0.76004,0.757139,0.757017,0.755665,0.751387,0.731324,0.724673,0.722474,0.72201,0.72052,...,0.712006,0.711872,0.710023,0.703659,0.703424,0.699946,0.699613,0.696659,0.69405,0.691074

DSTAR SCORES

,cz 10,swap 11,cp 9,cp 20,cp 13,cp 16,h 3,x 4,h 0,h 2,...,swap 8,cp 15,h 12,h 14,h 17,h 21,cp 7,cp 18,cp 6,cp 5
sum,2.078184,0.745243,0.689187,0.685796,0.62975,0.578019,0.425856,0.357889,0.331673,0.233731,...,0.176102,0.172404,0.171678,0.131764,0.102145,0.076548,0.074393,0.01774,0.0065,0.00055

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_ccx_inGap_7_.qasm

100%|██████████| 10/10 [01:08<00:00,  6.88s/it]
100%|██████████| 10/10 [01:08<00:00,  6.87s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,swap 12,...,cp 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.056841,0.187216,0.095458,0.028282,0.071896,0.189716,0.100400,0.088700,0.207436,0.146501,...,0.138400,0.048002,0.013891,0.003560,0.108502,0.081022,0.104778,0.102404,0.082581,fail
1,0.048103,0.161105,0.079564,0.023570,0.065218,0.195074,0.099509,0.083989,0.227269,0.207127,...,0.158247,0.052933,0.013731,0.002896,0.113131,0.089299,0.109177,0.100560,0.065712,fail
2,0.069566,0.212235,0.113751,0.031736,0.084691,0.205688,0.104697,0.107588,0.233736,0.172817,...,0.155244,0.055439,0.015267,0.004174,0.131733,0.096352,0.124251,0.118689,0.102910,fail
3,0.081925,0.252422,0.129751,0.037548,0.095583,0.232256,0.121096,0.127299,0.292966,0.241435,...,0.183391,0.070411,0.017567,0.004991,0.146014,0.109924,0.149176,0.136532,0.120754,fail
4,0.071741,0.219163,0.106950,0.032769,0.092159,0.226876,0.121440,0.117396,0.255153,0.194296,...,0.189759,0.061020,0.017346,0.004107,0.148814,0.117258,0.140703,0.136682,0.105633,fail
5,0.045780,0.145454,0.070109,0.021213,0.068884,0.192612,0.101172,0.087632,0.220317,0.195708,...,0.168107,0.051768,0.014155,0.002707,0.118549,0.095281,0.111772,0.106180,0.065059,fail
6,0.102846,0.308434,0.152396,0.046170,0.116688,0.280529,0.146258,0.144890,0.302217,0.210344,...,0.208863,0.071835,0.020504,0.005885,0.175267,0.131224,0.167840,0.164339,0.151586,fail
7,0.093369,0.297470,0.150583,0.043637,0.106704,0.270417,0.137073,0.125022,0.284354,0.223138,...,0.191990,0.066669,0.019293,0.005604,0.139163,0.111623,0.147750,0.144605,0.134295,fail
8,0.077053,0.238182,0.118777,0.035483,0.100676,0.253749,0.130573,0.117161,0.265978,0.213719,...,0.192520,0.063344,0.018466,0.004462,0.143408,0.114580,0.142877,0.139675,0.109966,fail
9,0.070061,0.208943,0.097541,0.030117,0.079594,0.196260,0.104947,0.113040,0.257344,0.216213,...,0.181454,0.061827,0.014756,0.004142,0.123672,0.107278,0.134010,0.121250,0.102934,fail
10,0.039412,0.121920,0.061912,0.017994,0.056061,0.136819,0.072353,0.069676,0.155475,0.124329,...,0.107747,0.036862,0.010320,0.002400,0.076239,0.062002,0.080826,0.077483,0.057532,pass
11,0.079704,0.260402,0.129620,0.037962,0.087140,0.234413,0.122550,0.113083,0.283439,0.227562,...,0.182640,0.067264,0.017105,0.004682,0.143709,0.103113,0.138033,0.128058,0.111372,pass
12,0.053141,0.168354,0.083554,0.024775,0.076018,0.203043,0.107024,0.093672,0.226403,0.177939,...,0.145424,0.050902,0.014414,0.003078,0.128195,0.090283,0.113468,0.109881,0.077451,pass
13,0.080435,0.248367,0.124002,0.037245,0.092956,0.233294,0.121093,0.104595,0.240463,0.185721,...,0.166365,0.057298,0.017226,0.004650,0.130333,0.098099,0.127636,0.126433,0.113786,pass
14,0.061085,0.188537,0.094415,0.027772,0.061421,0.163641,0.081642,0.077029,0.188707,0.157858,...,0.118576,0.042676,0.011005,0.003319,0.107201,0.074531,0.095671,0.088904,0.085926,pass
15,0.076996,0.236707,0.117342,0.034788,0.087827,0.227081,0.117260,0.106512,0.243527,0.167755,...,0.142680,0.055846,0.015815,0.004448,0.130918,0.089816,0.123766,0.121140,0.110992,pass
16,0.078799,0.248489,0.126029,0.036633,0.100811,0.275775,0.140316,0.112005,0.259935,0.175252,...,0.177605,0.059570,0.019248,0.004684,0.123122,0.102139,0.132060,0.135737,0.111594,pass
17,0.087899,0.266650,0.134487,0.040370,0.097772,0.223120,0.120520,0.124899,0.266203,0.186766,...,0.168328,0.060638,0.016440,0.005153,0.141624,0.104696,0.140311,0.134064,0.131632,pass
18,0.087775,0.270001,0.130343,0.040388,0.098825,0.240939,0.127498,0.118267,0.264895,0.196941,...,0.190635,0.063915,0.018217,0.005281,0.123266,0.105873,0.139369,0.135815,0.127608,pass
19,0.076601,0.241522,0.122558,0.036245,0.075879,0.187234,0.096164,0.096765,0.221229,0.169314,...,0.158013,0.053237,0.013889,0.004543,0.124092,0.092745,0.116157,0.109369,0.109292,pass

[[1.43382851 1.38272235 1.36692555 1.39687579 1.32285725 1.25058614
  1.25310134 1.30212748 1.18666927 1.19445473 1.35819497 1.16113618
  1.15602185 1.18136913 1.19079843 1.24282699 1.38388734 1.29995506
  1.24519715 1.25974145 1.29307825 1.45555664]]
BARINEL SCORES

,h 11,swap 12,h 3,cp 8,h 2,cp 7,x 4,swap 9,ccx 10,h 14,...,cp 6,h 17,cp 16,cp 15,cp 5,h 0,h 21,cp 19,cp 20,cp 18
sum,0.540572,0.53322,0.533014,0.531564,0.524617,0.5239,0.523197,0.523059,0.522697,0.522594,...,0.517727,0.513799,0.513485,0.513359,0.501707,0.501021,0.498415,0.497905,0.497732,0.497257

custom SCORES

,h 11,h 3,x 4,h 14,swap 12,h 1,h 2,cp 8,h 17,h 0,...,h 21,cp 5,ccx 10,cp 13,swap 9,cp 15,cp 16,cp 18,cp 20,cp 19
sum,0.724123,0.698941,0.69323,0.692715,0.692447,0.689869,0.689838,0.688557,0.68372,0.683337,...,0.677075,0.675284,0.674428,0.674348,0.674226,0.674182,0.674024,0.670908,0.669789,0.668055

DSTAR SCORES

,ccx 10,cp 13,cp 16,cp 20,swap 12,cp 8,swap 9,x 4,h 2,h 1,...,h 14,cp 19,h 3,h 0,h 17,h 21,cp 7,cp 18,cp 6,cp 5
sum,0.833304,0.525174,0.414985,0.406147,0.34714,0.270439,0.198622,0.161887,0.158389,0.144644,...,0.11239,0.111734,0.101671,0.098265,0.071814,0.047986,0.034499,0.010571,0.002681,0.00018

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_ry_inGap_1_.qasm

100%|██████████| 10/10 [00:51<00:00,  5.11s/it]
100%|██████████| 10/10 [00:45<00:00,  4.52s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,cp 8,cp 7,cp 6,x 5,h 4,h 3,h 2,h 1,ry 0,pass/fail
0,0.102976,0.329600,0.168541,0.049757,0.111863,0.264990,0.141993,0.131423,0.289467,0.142173,...,0.094337,0.027591,0.008834,0.203748,0.147879,0.163114,0.162691,0.198772,0.206387,fail
1,0.086757,0.278994,0.138647,0.041542,0.102304,0.267581,0.138742,0.117311,0.282719,0.140987,...,0.089404,0.025336,0.006831,0.198002,0.151486,0.155196,0.153767,0.159344,0.162201,fail
2,0.059263,0.196572,0.103152,0.029299,0.089299,0.246605,0.126260,0.098953,0.248755,0.099233,...,0.079297,0.023204,0.005136,0.167659,0.118555,0.132255,0.134414,0.110506,0.119147,fail
3,0.083212,0.263896,0.135885,0.039192,0.094820,0.240392,0.121946,0.097531,0.231199,0.116338,...,0.074838,0.023577,0.006254,0.179265,0.126408,0.128515,0.141044,0.145626,0.149471,fail
4,0.095810,0.302384,0.157048,0.045616,0.111375,0.274435,0.140138,0.129298,0.280611,0.146067,...,0.090588,0.026915,0.007754,0.219846,0.151499,0.162801,0.163971,0.182491,0.186741,fail
5,0.064098,0.197627,0.102575,0.029673,0.081443,0.203402,0.106926,0.102106,0.241132,0.107800,...,0.079650,0.020543,0.005313,0.189353,0.126103,0.138385,0.124364,0.123786,0.133288,fail
6,0.071416,0.219411,0.115339,0.032965,0.096508,0.229154,0.119069,0.115007,0.247137,0.104686,...,0.081620,0.023156,0.006539,0.174729,0.117000,0.140656,0.136718,0.142567,0.154220,fail
7,0.106398,0.333942,0.164819,0.049626,0.114058,0.260454,0.141603,0.136734,0.292942,0.158629,...,0.097868,0.028424,0.008917,0.210996,0.159432,0.172340,0.168808,0.205396,0.210383,fail
8,0.082922,0.266849,0.138891,0.040067,0.105523,0.270467,0.138265,0.119269,0.286688,0.131138,...,0.093863,0.026006,0.006896,0.208301,0.147396,0.160450,0.153196,0.153889,0.161675,fail
9,0.102237,0.334583,0.172199,0.050338,0.095987,0.227380,0.115053,0.115177,0.281856,0.132785,...,0.093216,0.022065,0.008272,0.182094,0.139240,0.154877,0.128354,0.186377,0.188667,fail
10,0.082477,0.257786,0.133556,0.038157,0.114218,0.302232,0.154974,0.141406,0.339319,0.149463,...,0.112923,0.029719,0.007311,0.215697,0.170857,0.189868,0.171836,0.161691,0.168790,pass
11,0.087578,0.280730,0.141007,0.041590,0.106070,0.272703,0.141935,0.122134,0.278613,0.137664,...,0.087548,0.026256,0.007216,0.202913,0.145757,0.154536,0.157629,0.166503,0.170942,pass
12,0.052163,0.162803,0.081648,0.024669,0.075189,0.198935,0.109542,0.091005,0.231342,0.104420,...,0.074676,0.019747,0.004262,0.171670,0.124472,0.125443,0.118170,0.096728,0.106719,pass
13,0.080676,0.241336,0.119604,0.036360,0.096298,0.233838,0.121225,0.119212,0.261094,0.159690,...,0.089766,0.024097,0.006188,0.193489,0.167372,0.158927,0.149833,0.152142,0.154024,pass
14,0.080051,0.252521,0.118278,0.036609,0.084211,0.205840,0.110843,0.103647,0.236508,0.120563,...,0.078161,0.021402,0.006468,0.180257,0.128974,0.137397,0.129700,0.149193,0.154082,pass
15,0.063507,0.207898,0.101732,0.030280,0.062380,0.166879,0.082036,0.071856,0.172554,0.108424,...,0.061630,0.016566,0.004941,0.147675,0.118863,0.103604,0.097757,0.115170,0.114065,pass
16,0.046545,0.144916,0.072565,0.021721,0.059319,0.138220,0.075222,0.077630,0.176203,0.091753,...,0.064461,0.015692,0.004291,0.120056,0.103652,0.106200,0.091602,0.092566,0.099035,pass
17,0.032274,0.105564,0.049915,0.014702,0.042966,0.120183,0.064174,0.054121,0.126744,0.077096,...,0.043776,0.012821,0.002714,0.089029,0.086569,0.073411,0.074087,0.058703,0.060669,pass
18,0.049175,0.148478,0.066631,0.020651,0.063956,0.173511,0.093001,0.091285,0.218034,0.114787,...,0.075953,0.017927,0.004154,0.167721,0.136055,0.130214,0.109842,0.097857,0.103211,pass
19,0.056985,0.178352,0.090725,0.026415,0.080217,0.202333,0.107908,0.097543,0.212604,0.115599,...,0.072900,0.021116,0.005171,0.153083,0.125429,0.125413,0.125490,0.115119,0.120975,pass

[[1.24428961 1.22834318 1.23254721 1.23356066 1.13696919 1.1044295
  1.10072387 1.17588855 1.09204709 1.23945066 1.22188213 1.11234441
  1.15221183 1.11890202 1.1516382  1.26043836 1.13674761 1.15113512
  1.1423944  1.15044802 1.27674132 1.25813746]]
BARINEL SCORES

,cp 19,cp 18,cp 20,h 21,cp 6,ry 0,h 1,h 17,cp 16,swap 11,...,h 14,h 2,cp 13,x 5,h 3,cp 8,swap 9,h 12,h 4,cp 10
sum,0.588806,0.583608,0.579021,0.575228,0.573024,0.571746,0.57161,0.561062,0.552248,0.551304,...,0.545242,0.544812,0.54351,0.540889,0.536177,0.534491,0.527149,0.520408,0.514295,0.50786

custom SCORES

,cp 19,cp 18,cp 20,h 21,h 1,cp 6,ry 0,h 17,swap 11,h 14,...,h 2,cp 15,x 5,cp 13,h 3,cp 8,h 12,swap 9,h 4,cp 10
sum,0.770239,0.763587,0.756831,0.754166,0.754059,0.75359,0.751579,0.720539,0.719711,0.705528,...,0.701507,0.699735,0.694602,0.691895,0.689309,0.684002,0.681663,0.678996,0.662301,0.649089

DSTAR SCORES

,swap 11,cp 20,cp 13,cp 10,cp 16,x 5,swap 9,ry 0,h 1,h 3,...,h 4,cp 15,h 12,h 14,h 17,cp 8,h 21,cp 18,cp 7,cp 6
sum,0.692947,0.619296,0.587271,0.521588,0.513915,0.32129,0.285984,0.248495,0.230962,0.201313,...,0.169634,0.150449,0.146517,0.123259,0.093314,0.071091,0.068775,0.016181,0.005969,0.000498

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_cx_inGap_6_.qasm

100%|██████████| 10/10 [01:01<00:00,  6.13s/it]
100%|██████████| 10/10 [00:55<00:00,  5.59s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.097665,0.302520,0.146694,0.044960,0.113858,0.291437,0.154082,0.129822,0.284673,0.165501,...,0.141298,0.085847,0.025844,0.008451,0.205652,0.164706,0.156612,0.156736,0.204757,fail
1,0.087259,0.267271,0.133218,0.040503,0.106658,0.254304,0.133279,0.128675,0.278489,0.164864,...,0.170118,0.088716,0.024479,0.007988,0.176429,0.161765,0.154237,0.145492,0.188142,fail
2,0.094551,0.285730,0.143663,0.043173,0.109812,0.250578,0.135576,0.136015,0.295795,0.153320,...,0.172508,0.094359,0.024989,0.008861,0.200125,0.179602,0.167724,0.152031,0.210614,fail
3,0.097414,0.308229,0.159063,0.045597,0.108612,0.280607,0.140675,0.127093,0.286453,0.146802,...,0.165404,0.088395,0.025675,0.008510,0.209408,0.180895,0.154364,0.153479,0.200953,fail
4,0.079816,0.247341,0.123620,0.037291,0.093745,0.225186,0.120249,0.113443,0.251976,0.130396,...,0.134277,0.077676,0.021326,0.007487,0.177956,0.148609,0.139454,0.129057,0.177467,fail
5,0.099410,0.324966,0.166616,0.049110,0.109254,0.286147,0.140650,0.101230,0.245610,0.119576,...,0.129080,0.072043,0.025443,0.008344,0.175090,0.151729,0.124993,0.147449,0.194485,fail
6,0.091479,0.271951,0.139339,0.041849,0.122643,0.298552,0.154556,0.142476,0.311413,0.178135,...,0.173924,0.096354,0.026721,0.008593,0.208883,0.177521,0.169047,0.159758,0.201187,fail
7,0.138918,0.422120,0.210946,0.063425,0.143765,0.320870,0.171706,0.175877,0.358327,0.203018,...,0.194416,0.121994,0.033491,0.012665,0.261017,0.224318,0.219028,0.202709,0.303746,fail
8,0.090031,0.285880,0.142248,0.042529,0.097778,0.251321,0.131085,0.116335,0.267426,0.134797,...,0.151633,0.082620,0.023340,0.008085,0.176767,0.158345,0.143479,0.137422,0.189351,fail
9,0.089969,0.281170,0.141046,0.041316,0.096491,0.245187,0.124429,0.119144,0.267170,0.143812,...,0.157730,0.085476,0.023106,0.007919,0.184783,0.157453,0.147222,0.136838,0.187458,fail
10,0.067587,0.211282,0.103147,0.031288,0.076655,0.192679,0.103711,0.101782,0.240628,0.112557,...,0.129172,0.070712,0.017690,0.006242,0.136668,0.126059,0.123727,0.105518,0.147732,pass
11,0.063113,0.204917,0.101218,0.030841,0.075800,0.191251,0.104186,0.096228,0.240919,0.113593,...,0.136991,0.067633,0.018191,0.005773,0.164366,0.134940,0.117688,0.108051,0.134091,pass
12,0.097779,0.292099,0.150290,0.044845,0.106146,0.240926,0.123748,0.124286,0.248498,0.158708,...,0.144802,0.084128,0.023717,0.008696,0.183038,0.162744,0.151770,0.146399,0.209875,pass
13,0.034481,0.108224,0.055320,0.016278,0.053302,0.138124,0.071012,0.070721,0.162419,0.092437,...,0.103511,0.048104,0.012184,0.003415,0.098583,0.093120,0.081806,0.071995,0.078147,pass
14,0.081446,0.254279,0.126977,0.037472,0.095202,0.249339,0.128482,0.115845,0.272153,0.131437,...,0.140955,0.078691,0.021608,0.007129,0.187014,0.149940,0.140236,0.130942,0.170684,pass
15,0.060348,0.203698,0.104426,0.030108,0.077356,0.221944,0.110567,0.093864,0.253930,0.107351,...,0.154104,0.070343,0.018842,0.005644,0.148348,0.137235,0.113848,0.106108,0.124752,pass
16,0.040359,0.127437,0.062113,0.018597,0.045951,0.128427,0.065804,0.063088,0.166149,0.077183,...,0.094281,0.044748,0.010606,0.003418,0.115195,0.082775,0.078699,0.064657,0.081247,pass
17,0.063315,0.201501,0.102300,0.030540,0.069668,0.172260,0.088280,0.079816,0.190786,0.095644,...,0.109183,0.056708,0.016108,0.005588,0.134839,0.117238,0.099121,0.095636,0.131130,pass
18,0.080418,0.246628,0.126252,0.037096,0.092404,0.230847,0.119725,0.106655,0.249850,0.112115,...,0.133925,0.072159,0.020230,0.007063,0.159978,0.141840,0.131301,0.124207,0.172011,pass
19,0.053868,0.180021,0.086734,0.026026,0.072907,0.214425,0.113062,0.089290,0.234660,0.095365,...,0.138000,0.064588,0.017562,0.005133,0.133788,0.130088,0.107573,0.100870,0.115586,pass

[[1.43731485 1.40839194 1.40028456 1.41022218 1.30385819 1.18656659
  1.22098673 1.36327485 1.25846498 1.31811007 1.16928255 1.41483337
  1.28844369 1.22244486 1.36537971 1.31640032 1.45742649 1.32086147
  1.31569178 1.38962853 1.33276301 1.4758152 ]]
BARINEL SCORES

,h 0,h 21,cp 5,cp 18,cx 10,cp 19,cp 20,h 1,h 17,cp 6,...,h 14,cp 15,cp 16,cp 7,x 4,h 3,cp 9,cp 13,swap 8,swap 11
sum,0.601201,0.600606,0.59932,0.597405,0.597286,0.59656,0.596185,0.590587,0.590263,0.590082,...,0.578088,0.577563,0.577274,0.575958,0.574797,0.571952,0.57152,0.5575,0.553119,0.546248

custom SCORES

,h 0,cp 5,h 21,cx 10,cp 18,cp 20,cp 19,h 1,cp 6,h 17,...,h 14,cp 7,x 4,h 3,cp 9,cp 15,cp 16,cp 13,swap 8,swap 11
sum,0.823016,0.817687,0.816421,0.808551,0.808024,0.8061,0.805399,0.787365,0.784278,0.782668,...,0.775111,0.772559,0.764604,0.76008,0.755613,0.753862,0.748518,0.732898,0.722158,0.705928

DSTAR SCORES

,cx 10,cp 9,cp 20,cp 13,swap 11,cp 16,h 0,x 4,h 3,swap 8,...,h 1,cp 19,cp 15,h 14,h 17,h 21,cp 7,cp 18,cp 6,cp 5
sum,1.51391,0.808071,0.746718,0.661281,0.645333,0.610393,0.372717,0.340698,0.25779,0.224134,...,0.20927,0.205958,0.17932,0.152115,0.112932,0.087773,0.074904,0.019633,0.00636,0.000751

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_cz_inGap_11_.qasm

100%|██████████| 10/10 [00:52<00:00,  5.26s/it]
100%|██████████| 10/10 [00:53<00:00,  5.32s/it]

,h 21,cz 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.083922,0.370195,0.295686,0.161942,0.045947,0.109557,0.272593,0.136238,0.118870,0.278061,...,0.204364,0.083861,0.023878,0.007043,0.179729,0.129509,0.149988,0.147003,0.168433,fail
1,0.100973,0.462638,0.377402,0.194324,0.053029,0.109785,0.287956,0.136653,0.129682,0.295567,...,0.195928,0.087369,0.024224,0.008206,0.199950,0.141488,0.162355,0.154463,0.205454,fail
2,0.085678,0.387413,0.317935,0.153569,0.051595,0.101912,0.258525,0.142538,0.109152,0.286657,...,0.180645,0.077883,0.023168,0.006723,0.196350,0.133172,0.142736,0.145246,0.167100,fail
3,0.105125,0.483282,0.410137,0.196882,0.056244,0.113568,0.297304,0.143561,0.124647,0.295312,...,0.177076,0.084654,0.024760,0.008340,0.203985,0.145879,0.158048,0.156000,0.210747,fail
4,0.085860,0.376388,0.362684,0.166984,0.047103,0.110828,0.281155,0.136191,0.118881,0.263414,...,0.186421,0.080555,0.023824,0.007133,0.161829,0.134044,0.144408,0.145856,0.173016,fail
5,0.098411,0.434514,0.366128,0.185390,0.052687,0.112343,0.284864,0.138388,0.129001,0.304803,...,0.195008,0.086530,0.023672,0.008083,0.178786,0.142555,0.158182,0.148516,0.198689,fail
6,0.083073,0.382053,0.294628,0.161882,0.044516,0.088826,0.253649,0.122106,0.089633,0.229340,...,0.150756,0.066674,0.021418,0.006478,0.166366,0.106387,0.117434,0.128726,0.156173,fail
7,0.073413,0.334417,0.262719,0.149085,0.040408,0.086040,0.230108,0.110252,0.096702,0.230928,...,0.151212,0.064086,0.018428,0.006089,0.147840,0.096023,0.116826,0.115317,0.148636,fail
8,0.104844,0.478680,0.396427,0.204428,0.058589,0.109695,0.301947,0.147579,0.126328,0.309390,...,0.202509,0.086303,0.025291,0.008330,0.204931,0.135820,0.157813,0.157998,0.205827,fail
9,0.087251,0.401294,0.341174,0.164654,0.050134,0.095854,0.267720,0.135456,0.102661,0.279056,...,0.174646,0.075089,0.022484,0.006724,0.188597,0.121022,0.135126,0.138718,0.165692,fail
10,0.055870,0.249248,0.200428,0.102707,0.029530,0.066318,0.158732,0.078389,0.076639,0.167326,...,0.101401,0.049002,0.013981,0.004705,0.107774,0.080798,0.091873,0.088684,0.117627,pass
11,0.064711,0.293843,0.216051,0.118387,0.031442,0.083988,0.228083,0.107563,0.087456,0.199269,...,0.139229,0.062039,0.019782,0.004966,0.157630,0.123730,0.115310,0.124927,0.126173,pass
12,0.049187,0.217352,0.185061,0.090601,0.027627,0.068478,0.172322,0.091497,0.076128,0.187027,...,0.121579,0.053318,0.015681,0.004002,0.120870,0.097693,0.096948,0.097126,0.097556,pass
13,0.074432,0.341123,0.330533,0.142098,0.041340,0.091565,0.228133,0.115604,0.108005,0.255819,...,0.175235,0.075784,0.019898,0.006111,0.166781,0.128953,0.138036,0.125822,0.152544,pass
14,0.080593,0.364334,0.309877,0.141682,0.041384,0.081264,0.218718,0.107163,0.100157,0.237258,...,0.152871,0.072219,0.019642,0.006499,0.168203,0.128833,0.132399,0.121502,0.163955,pass
15,0.075571,0.339172,0.273525,0.136521,0.039064,0.089051,0.219714,0.111653,0.108367,0.241941,...,0.144641,0.071268,0.019731,0.006394,0.162465,0.122708,0.133689,0.124905,0.159698,pass
16,0.081475,0.371331,0.301839,0.149520,0.046240,0.092596,0.237503,0.124479,0.094690,0.242933,...,0.156238,0.068578,0.021411,0.006551,0.171355,0.118029,0.123397,0.131111,0.159802,pass
17,0.082772,0.362535,0.285153,0.149319,0.041698,0.100214,0.244438,0.120256,0.118766,0.249976,...,0.164269,0.076622,0.021660,0.006815,0.169918,0.137116,0.144834,0.139119,0.172093,pass
18,0.056590,0.240064,0.195410,0.103508,0.028338,0.081316,0.205336,0.103864,0.104530,0.224002,...,0.137104,0.068169,0.018635,0.005037,0.134306,0.118403,0.125604,0.115980,0.121222,pass
19,0.074217,0.318205,0.260932,0.121508,0.040384,0.095755,0.198686,0.113118,0.126757,0.280396,...,0.188081,0.084220,0.020259,0.006535,0.171017,0.144529,0.157098,0.130501,0.164267,pass

[[1.15706116 1.17561753 1.19750782 1.1754571  1.17118423 1.09367424
  1.10368054 1.09401947 1.13204586 1.11591245 1.1867919  1.1998598
  1.1444552  1.12376452 1.10174415 1.09415835 1.14015838 1.12084584
  1.1344554  1.1251843  1.0988565  1.1709696 ]]
BARINEL SCORES

,swap 10,cp 18,cp 17,cp 19,cz 20,h 21,cp 15,cp 5,cp 14,h 0,...,cp 12,cp 6,h 1,x 4,cp 7,h 2,h 13,cp 9,h 3,h 11
sum,0.583079,0.580683,0.576793,0.572372,0.570315,0.566439,0.56438,0.559395,0.556836,0.556392,...,0.548096,0.547967,0.54515,0.544369,0.537913,0.533997,0.533549,0.521496,0.517113,0.510775

custom SCORES

,swap 10,cp 18,cp 17,cp 19,cz 20,h 21,cp 15,h 0,cp 5,cp 14,...,h 16,cp 6,x 4,h 1,cp 7,h 13,h 2,cp 9,h 3,h 11
sum,0.757983,0.751325,0.745676,0.743727,0.737933,0.73029,0.720103,0.719272,0.718845,0.709134,...,0.700033,0.697858,0.696908,0.69491,0.686074,0.684549,0.684209,0.670703,0.663773,0.662321

DSTAR SCORES

,cz 20,swap 10,cp 19,cp 12,cp 15,cp 9,x 4,swap 8,h 0,cp 18,...,cp 14,h 3,h 11,h 13,h 16,h 21,cp 7,cp 17,cp 6,cp 5
sum,1.290297,1.004311,0.934011,0.625667,0.617976,0.385016,0.289924,0.288066,0.283268,0.268714,...,0.164328,0.147627,0.139626,0.119284,0.099377,0.077179,0.058875,0.024139,0.005243,0.000532

ERROR GATE LOCATION:
20
Now evolving the following mutant:  AddGate_p_inGap_10_.qasm

100%|██████████| 10/10 [00:45<00:00,  4.60s/it]
100%|██████████| 10/10 [00:44<00:00,  4.45s/it]

,h 21,cp 20,cp 19,cp 18,h 17,p 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.086330,0.264041,0.135685,0.039862,0.109422,0.500114,0.283725,0.145638,0.130484,0.306138,...,0.214172,0.101955,0.027563,0.007126,0.215859,0.153713,0.173759,0.171999,0.163994,fail
1,0.094463,0.307218,0.157176,0.044487,0.117825,0.558367,0.334586,0.169548,0.133159,0.322166,...,0.194917,0.102365,0.031470,0.007747,0.201246,0.155648,0.171517,0.191775,0.173518,fail
2,0.083071,0.259660,0.130199,0.039057,0.101080,0.445576,0.258123,0.135655,0.123204,0.291914,...,0.186248,0.092885,0.024202,0.006953,0.184444,0.146691,0.161912,0.152794,0.162233,fail
3,0.067783,0.211196,0.101691,0.031127,0.094731,0.446129,0.243787,0.129927,0.119489,0.274132,...,0.185859,0.093960,0.024833,0.005927,0.175275,0.156092,0.160240,0.156221,0.134379,fail
4,0.076981,0.247439,0.123000,0.036642,0.110799,0.521545,0.298643,0.155439,0.127572,0.312207,...,0.211828,0.098826,0.029250,0.006672,0.209362,0.164070,0.170630,0.181501,0.149583,fail
5,0.080122,0.252281,0.129973,0.037013,0.095941,0.427117,0.247319,0.124873,0.110065,0.247792,...,0.156384,0.080944,0.024200,0.006907,0.188568,0.129549,0.141562,0.150894,0.157179,fail
6,0.070931,0.222644,0.114461,0.033203,0.093483,0.417884,0.246714,0.123975,0.098752,0.231275,...,0.142971,0.074518,0.022468,0.005836,0.169835,0.115697,0.128230,0.139573,0.133996,fail
7,0.071699,0.221836,0.110102,0.032675,0.090388,0.426505,0.243828,0.124309,0.104272,0.246811,...,0.178208,0.084135,0.023247,0.005740,0.182193,0.141704,0.143797,0.146620,0.135347,fail
8,0.085224,0.277030,0.141063,0.041671,0.112874,0.522127,0.301483,0.154147,0.121599,0.293318,...,0.203211,0.092827,0.028543,0.006873,0.232509,0.163999,0.162516,0.182692,0.156256,fail
9,0.054542,0.188783,0.094860,0.027265,0.089714,0.455721,0.274770,0.138996,0.095049,0.259684,...,0.208382,0.081828,0.024828,0.004386,0.180424,0.131445,0.135172,0.154663,0.095915,fail
10,0.049917,0.161185,0.082987,0.024146,0.066430,0.310566,0.177765,0.089779,0.079037,0.198849,...,0.167032,0.068006,0.017588,0.004121,0.144615,0.102539,0.111690,0.109698,0.091628,pass
11,0.072681,0.235322,0.114428,0.034115,0.086517,0.409430,0.243020,0.124980,0.101744,0.253738,...,0.167113,0.081506,0.022361,0.005900,0.175451,0.127106,0.138233,0.140331,0.137828,pass
12,0.064280,0.204678,0.103192,0.030051,0.067311,0.290855,0.167031,0.085013,0.080234,0.182226,...,0.117483,0.060900,0.016832,0.005268,0.130240,0.098960,0.104169,0.104093,0.120498,pass
13,0.048722,0.146925,0.067907,0.021467,0.064853,0.302802,0.165277,0.088979,0.084681,0.206131,...,0.155677,0.069535,0.016304,0.004106,0.162923,0.123801,0.121314,0.105295,0.100125,pass
14,0.072292,0.234797,0.110520,0.033606,0.069539,0.310715,0.181763,0.095664,0.103443,0.267546,...,0.204903,0.091245,0.017797,0.005998,0.169343,0.138709,0.150477,0.110679,0.137384,pass
15,0.070702,0.219101,0.108021,0.031469,0.082588,0.389286,0.219167,0.109707,0.097259,0.214747,...,0.139440,0.069726,0.020484,0.005516,0.186782,0.133021,0.127581,0.136547,0.136287,pass
16,0.065950,0.191544,0.100051,0.030159,0.096364,0.430122,0.236268,0.119959,0.114070,0.256193,...,0.184822,0.087368,0.023762,0.005340,0.170782,0.160789,0.151764,0.151634,0.130255,pass
17,0.050548,0.161448,0.080607,0.024656,0.069197,0.322304,0.187605,0.097457,0.070384,0.171130,...,0.117285,0.054460,0.017954,0.004146,0.127283,0.099602,0.094651,0.110841,0.095060,pass
18,0.055566,0.175025,0.083731,0.025184,0.059790,0.272618,0.155727,0.079955,0.074056,0.180183,...,0.124907,0.059522,0.015150,0.004373,0.123592,0.099107,0.103394,0.096345,0.103906,pass
19,0.070031,0.227449,0.111007,0.033740,0.103572,0.493282,0.280141,0.149728,0.117406,0.278016,...,0.174133,0.086030,0.027043,0.005860,0.204949,0.157012,0.152884,0.172386,0.137359,pass

[[1.22496701 1.25286349 1.26938048 1.22553097 1.15940323 1.18270955
  1.22425444 1.2088958  1.14432517 1.15660985 1.11141764 1.28971785
  1.14789405 1.13789251 1.13205282 1.20757648 1.20731549 1.19867847
  1.12483678 1.12150728 1.17744842 1.18653148]]
BARINEL SCORES

,cp 15,cp 14,p 16,cp 6,h 17,h 1,cp 19,cp 5,h 13,cp 12,...,h 21,cp 7,h 2,h 0,x 4,swap 8,swap 10,h 11,h 3,cp 9
sum,0.575759,0.573921,0.57204,0.571653,0.570156,0.568179,0.562654,0.558968,0.557847,0.557735,...,0.554051,0.553887,0.552251,0.551281,0.548612,0.547946,0.541649,0.540578,0.540374,0.535253

custom SCORES

,cp 15,cp 14,cp 6,cp 19,p 16,h 1,h 17,cp 20,cp 18,cp 5,...,h 13,swap 10,h 0,x 4,cp 7,h 2,swap 8,h 3,h 11,cp 9
sum,0.751978,0.747374,0.744231,0.74121,0.74118,0.73543,0.735416,0.730264,0.727785,0.727681,...,0.717436,0.716292,0.714809,0.713015,0.710645,0.707089,0.703822,0.692333,0.690781,0.688857

DSTAR SCORES

,p 16,cp 12,cp 15,cp 9,swap 10,cp 20,x 4,swap 8,h 1,h 2,...,cp 14,h 11,cp 19,h 13,h 17,cp 7,h 21,cp 18,cp 6,cp 5
sum,1.647108,0.6355,0.621718,0.579157,0.569897,0.502861,0.324465,0.306645,0.236057,0.213256,...,0.178153,0.155721,0.139856,0.123973,0.095928,0.076215,0.055992,0.012808,0.006661,0.00041

ERROR GATE LOCATION:
16
Now evolving the following mutant:  AddGate_rxx_inGap_6_.qasm

100%|██████████| 10/10 [00:52<00:00,  5.24s/it]
100%|██████████| 10/10 [00:50<00:00,  5.01s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.077748,0.249514,0.123986,0.037196,0.089162,0.217324,0.115566,0.105934,0.245606,0.116549,...,0.175359,0.081588,0.022278,0.003277,0.186097,0.135075,0.135306,0.127809,0.063760,fail
1,0.065517,0.214286,0.105605,0.032069,0.083028,0.222902,0.118510,0.104965,0.256810,0.118706,...,0.171352,0.079164,0.020427,0.002704,0.174023,0.129894,0.135450,0.121159,0.059048,fail
2,0.086128,0.268557,0.137392,0.040294,0.092031,0.231045,0.116407,0.100999,0.231187,0.121010,...,0.139893,0.070065,0.020335,0.003099,0.172992,0.117485,0.123363,0.122879,0.068442,fail
3,0.066339,0.221098,0.107688,0.031500,0.066252,0.188034,0.094809,0.086149,0.223920,0.100246,...,0.168642,0.071120,0.016799,0.002407,0.161463,0.115345,0.119766,0.099129,0.049085,fail
4,0.082777,0.262381,0.127309,0.038661,0.102601,0.263560,0.140894,0.124423,0.285794,0.140955,...,0.202739,0.093403,0.026348,0.003428,0.204094,0.153484,0.157997,0.154198,0.074089,fail
5,0.078820,0.255492,0.121773,0.037337,0.083940,0.216473,0.113177,0.097145,0.230599,0.136802,...,0.155551,0.073561,0.020568,0.002858,0.175449,0.130003,0.126143,0.121867,0.066793,fail
6,0.112189,0.357033,0.173489,0.052456,0.107331,0.267759,0.138956,0.128739,0.311865,0.160585,...,0.202889,0.095436,0.024736,0.004073,0.210264,0.149554,0.164593,0.145755,0.093173,fail
7,0.048964,0.169217,0.086121,0.025296,0.054194,0.154867,0.077558,0.069842,0.193604,0.072999,...,0.138278,0.058885,0.013709,0.001933,0.114193,0.089351,0.096549,0.077309,0.037201,fail
8,0.072782,0.235465,0.125520,0.035133,0.099028,0.271139,0.138068,0.108138,0.247311,0.116112,...,0.155495,0.076789,0.026198,0.003010,0.181211,0.137140,0.130211,0.149129,0.060977,fail
9,0.073266,0.224558,0.111432,0.034357,0.088607,0.210430,0.109243,0.107185,0.234747,0.154795,...,0.176575,0.080277,0.021770,0.002823,0.170251,0.138057,0.136895,0.127947,0.068477,fail
10,0.043977,0.129311,0.061074,0.019196,0.066772,0.177164,0.096193,0.095103,0.227585,0.106104,...,0.144935,0.072112,0.016668,0.001945,0.135913,0.105260,0.122449,0.098119,0.047279,pass
11,0.070714,0.207298,0.105179,0.031978,0.080680,0.192755,0.098919,0.103999,0.242432,0.135978,...,0.176175,0.079046,0.017182,0.002661,0.175628,0.122680,0.136016,0.103835,0.067353,pass
12,0.064952,0.205014,0.103429,0.030928,0.078392,0.192352,0.102114,0.098980,0.227803,0.114338,...,0.171408,0.075520,0.018911,0.002579,0.166756,0.131336,0.127169,0.113407,0.052530,pass
13,0.066013,0.202607,0.102165,0.030584,0.091989,0.231073,0.118049,0.109070,0.245160,0.126606,...,0.181734,0.080095,0.022404,0.002684,0.193064,0.138430,0.138789,0.133227,0.061285,pass
14,0.081232,0.247334,0.127977,0.036294,0.107202,0.262298,0.135476,0.137563,0.302505,0.149136,...,0.224696,0.097176,0.026493,0.003437,0.193907,0.162788,0.168193,0.157712,0.073686,pass
15,0.080786,0.248819,0.123212,0.037077,0.096080,0.238020,0.128765,0.131024,0.293944,0.145311,...,0.193918,0.096765,0.023234,0.003439,0.205022,0.147956,0.164626,0.138178,0.078362,pass
16,0.078073,0.252668,0.125722,0.036735,0.099441,0.272059,0.138118,0.119611,0.288655,0.137265,...,0.208845,0.093489,0.025856,0.003027,0.188649,0.148878,0.156632,0.148432,0.065336,pass
17,0.074881,0.234016,0.118491,0.033818,0.072990,0.177282,0.089118,0.103263,0.235959,0.124979,...,0.170056,0.077795,0.017171,0.002829,0.160834,0.119062,0.132335,0.102940,0.067866,pass
18,0.070141,0.209933,0.109455,0.031819,0.101229,0.249427,0.126780,0.107553,0.244674,0.136914,...,0.178529,0.078132,0.024005,0.002788,0.189658,0.143930,0.135324,0.141226,0.063110,pass
19,0.083831,0.261600,0.134311,0.038818,0.085700,0.206774,0.104402,0.108317,0.244359,0.125998,...,0.171292,0.080324,0.019398,0.003279,0.162806,0.120027,0.135431,0.114202,0.074733,pass

[[1.46742123 1.45276977 1.42167298 1.43991822 1.23913883 1.20853598
  1.21127935 1.24563668 1.26699966 1.29633539 1.15414192 1.44015958
  1.13780142 1.20282308 1.22308838 1.23602536 1.37548627 1.20148214
  1.18485187 1.24101975 1.23637529 1.45344902]]
BARINEL SCORES

,cp 20,cp 18,cp 19,swap 11,rxx 10,h 21,cp 5,cp 15,cp 16,cp 6,...,x 4,h 0,h 17,h 3,cp 13,h 12,cp 7,h 2,h 14,swap 8
sum,0.527813,0.526789,0.523441,0.520088,0.519786,0.516878,0.508111,0.505487,0.504989,0.502175,...,0.496849,0.495941,0.495906,0.491472,0.490863,0.487434,0.484427,0.48347,0.481154,0.480787

custom SCORES

,cp 20,cp 18,cp 19,rxx 10,h 21,cp 5,h 0,swap 11,cp 15,cp 16,...,h 17,cp 13,x 4,h 12,cp 9,h 3,h 2,cp 7,h 14,swap 8
sum,0.71951,0.716422,0.709482,0.706929,0.706497,0.682836,0.676147,0.670152,0.658559,0.657563,...,0.649531,0.646344,0.646087,0.645404,0.640695,0.637052,0.633469,0.632552,0.63099,0.625362

DSTAR SCORES

,rxx 10,swap 11,cp 20,cp 13,cp 9,cp 16,x 4,swap 8,h 2,h 3,...,cp 19,cp 15,h 14,h 17,cp 7,h 21,h 0,cp 18,cp 6,cp 5
sum,0.829166,0.538326,0.495122,0.482647,0.478458,0.412604,0.260157,0.240679,0.154069,0.14797,...,0.134026,0.121477,0.096106,0.068955,0.056217,0.054552,0.03858,0.012851,0.00445,0.000087

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_ry_inGap_11_.qasm

100%|██████████| 10/10 [00:18<00:00,  1.87s/it]
100%|██████████| 10/10 [00:19<00:00,  1.97s/it]

,h 21,ry 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.090062,0.450310,0.0,1.125955e-18,5.550265e-19,0.054825,0.180543,0.094309,0.068513,0.185067,...,0.152185,0.067804,0.019627,0.000249,0.157697,0.125393,0.118963,0.114937,0.065530,fail
1,0.099252,0.496259,0.0,1.096849e-18,5.406791e-19,0.054997,0.179734,0.093785,0.072395,0.194384,...,0.157414,0.070937,0.020169,0.000246,0.178949,0.127911,0.127639,0.121375,0.079538,fail
2,0.077058,0.385288,0.0,1.198157e-18,5.906179e-19,0.052033,0.172550,0.088840,0.070089,0.215925,...,0.220706,0.078067,0.018369,0.000280,0.189813,0.137165,0.134115,0.110952,0.058499,fail
3,0.113279,0.566395,0.0,1.196697e-18,5.898980e-19,0.051921,0.171250,0.088180,0.068844,0.203013,...,0.201364,0.076636,0.018642,0.000248,0.187724,0.133634,0.132225,0.114627,0.079462,fail
4,0.073610,0.368048,0.0,1.207975e-18,5.954575e-19,0.046977,0.162378,0.082870,0.057804,0.173383,...,0.172155,0.061707,0.016191,0.000246,0.154545,0.117317,0.101440,0.093841,0.036215,fail
5,0.090029,0.450146,0.0,1.022964e-18,5.042583e-19,0.046740,0.154793,0.078911,0.063565,0.185077,...,0.186469,0.070005,0.017868,0.000227,0.163455,0.113430,0.121179,0.106130,0.069444,fail
6,0.099028,0.495141,0.0,1.111819e-18,5.480587e-19,0.050267,0.169565,0.084450,0.064662,0.191695,...,0.176856,0.071104,0.018133,0.000225,0.164548,0.112298,0.121888,0.107142,0.069821,fail
7,0.088595,0.442974,0.0,1.021072e-18,5.033257e-19,0.059470,0.200030,0.104223,0.059872,0.165789,...,0.120679,0.056271,0.020795,0.000206,0.155860,0.111186,0.101920,0.125674,0.070938,fail
8,0.079994,0.399970,0.0,8.771511e-19,4.323816e-19,0.050897,0.170310,0.087756,0.065597,0.182779,...,0.160124,0.068567,0.018306,0.000205,0.156360,0.108948,0.118573,0.108935,0.065665,fail
9,0.095893,0.479467,0.0,1.257779e-18,6.200076e-19,0.054888,0.187284,0.098379,0.069895,0.202189,...,0.162035,0.072443,0.019628,0.000252,0.167507,0.128760,0.124526,0.114051,0.072046,fail
10,0.056466,0.282331,0.0,8.597616e-19,4.238097e-19,0.058131,0.190909,0.099952,0.067333,0.167413,...,0.123930,0.058368,0.020180,0.000204,0.146491,0.107499,0.104699,0.122108,0.055047,pass
11,0.061804,0.309019,0.0,8.366239e-19,4.124042e-19,0.050039,0.166709,0.087118,0.055225,0.146232,...,0.125696,0.053225,0.018073,0.000201,0.130473,0.100927,0.090734,0.106880,0.047900,pass
12,0.100694,0.503468,0.0,1.061317e-18,5.231641e-19,0.045269,0.146322,0.078854,0.065388,0.187627,...,0.169916,0.070269,0.016874,0.000238,0.162329,0.126473,0.123745,0.102972,0.079407,pass
13,0.062498,0.312491,0.0,8.978572e-19,4.425885e-19,0.051980,0.176486,0.093271,0.065952,0.196627,...,0.180550,0.072088,0.018963,0.000237,0.131992,0.115629,0.118897,0.109921,0.055890,pass
14,0.061801,0.309006,0.0,9.054936e-19,4.463528e-19,0.045408,0.149366,0.079230,0.059796,0.167443,...,0.154106,0.060909,0.015486,0.000237,0.134388,0.115202,0.104597,0.095369,0.048533,pass
15,0.043868,0.219338,0.0,8.363373e-19,4.122630e-19,0.042560,0.143339,0.072425,0.045622,0.127962,...,0.113475,0.043846,0.013973,0.000201,0.111089,0.096106,0.077026,0.083153,0.032801,pass
16,0.066928,0.334639,0.0,9.018815e-19,4.445722e-19,0.054058,0.178133,0.094138,0.061365,0.163678,...,0.127655,0.058456,0.018818,0.000210,0.147954,0.111039,0.105674,0.114262,0.062817,pass
17,0.089000,0.445002,0.0,1.169675e-18,5.765778e-19,0.053921,0.176680,0.089485,0.073127,0.204021,...,0.175139,0.073942,0.019062,0.000263,0.187543,0.138758,0.133490,0.117820,0.080388,pass
18,0.069894,0.349468,0.0,1.076296e-18,5.305481e-19,0.052545,0.179354,0.093713,0.065885,0.189101,...,0.148643,0.065762,0.017891,0.000239,0.142384,0.120408,0.115111,0.104336,0.055634,pass
19,0.061414,0.307072,0.0,1.090952e-18,5.377723e-19,0.061095,0.199078,0.103368,0.073026,0.200648,...,0.179833,0.073944,0.021676,0.000273,0.167231,0.138954,0.124857,0.127754,0.059122,pass

[[1.24921714 1.24921714        nan 1.13146046 1.13146046 1.13706116
  1.14404812 1.15584938 1.09483837 1.136864   1.09446559 1.22109267
  1.14905962 1.29068782 1.12563247 1.10772724 1.17514657 1.13222477
  1.12796361 1.11533265 1.12443179 1.19219088]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,swap 10,ry 20,h 21,h 0,cp 17,cp 18,x 4,swap 8,cp 7,h 2,...,h 3,cp 6,cp 5,h 1,cp 9,cp 15,h 16,cp 14,h 11,cp 19
sum,0.576229,0.5735,0.5735,0.536,0.535664,0.535664,0.534188,0.532884,0.523685,0.522518,...,0.509436,0.509129,0.508678,0.507512,0.507426,0.506087,0.503857,0.502829,0.499885,0.0

custom SCORES

,h 21,ry 20,swap 10,swap 8,h 0,cp 18,cp 17,x 4,cp 7,cp 12,...,cp 9,h 3,h 13,cp 15,h 1,cp 6,cp 14,h 16,h 11,cp 19
sum,0.752607,0.752607,0.752136,0.704831,0.695753,0.687184,0.687184,0.685393,0.671054,0.66824,...,0.653192,0.653092,0.65089,0.650834,0.650178,0.650122,0.648128,0.647086,0.636661,0.0

DSTAR SCORES

,ry 20,swap 10,cp 9,cp 12,cp 15,swap 8,x 4,h 3,h 2,h 1,...,h 11,cp 7,h 0,h 13,h 16,cp 6,cp 5,cp 18,cp 17,cp 19
sum,1.537345,0.458668,0.361491,0.306988,0.261142,0.254289,0.245206,0.132375,0.130278,0.112694,...,0.058773,0.045246,0.04208,0.041122,0.026015,0.003462,5.683681e-07,1.235747e-35,3.002723e-36,0.0

ERROR GATE LOCATION:
20
Now evolving the following mutant:  AddGate_rxx_inGap_5_.qasm

100%|██████████| 10/10 [00:53<00:00,  5.39s/it]
100%|██████████| 10/10 [00:49<00:00,  4.97s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,cp 8,cp 7,cp 6,x 5,rxx 4,h 3,h 2,h 1,h 0,pass/fail
0,0.094737,0.291565,0.145865,0.043541,0.113476,0.284286,0.148210,0.132727,0.298397,0.166072,...,0.099895,0.028068,0.007674,0.215525,0.403519,0.175089,0.181823,0.175538,0.187352,fail
1,0.049246,0.143225,0.077346,0.022092,0.084783,0.210540,0.110754,0.110113,0.241377,0.139191,...,0.081930,0.021460,0.004438,0.191379,0.348789,0.159168,0.152693,0.138952,0.108732,fail
2,0.088640,0.277574,0.139181,0.041397,0.101830,0.262118,0.133054,0.113967,0.281509,0.126671,...,0.087659,0.023636,0.006932,0.191898,0.370007,0.141026,0.157878,0.148219,0.169200,fail
3,0.082540,0.258411,0.133165,0.038461,0.098529,0.249011,0.130984,0.121156,0.284192,0.124268,...,0.090729,0.024368,0.006576,0.212183,0.413816,0.152222,0.166924,0.155540,0.159024,fail
4,0.068029,0.220196,0.109784,0.032219,0.093121,0.258174,0.132112,0.104030,0.251843,0.114160,...,0.078947,0.023887,0.005392,0.190010,0.368153,0.140594,0.143972,0.150198,0.129429,fail
5,0.104894,0.327021,0.164463,0.048615,0.109158,0.266871,0.139375,0.131560,0.308727,0.149435,...,0.100779,0.025842,0.008158,0.242648,0.471874,0.182406,0.185861,0.166631,0.202489,fail
6,0.070102,0.219483,0.109879,0.033511,0.104170,0.277133,0.146414,0.120555,0.284032,0.139781,...,0.090237,0.026372,0.005878,0.196339,0.369855,0.152359,0.164406,0.164875,0.140360,fail
7,0.087461,0.279760,0.142833,0.041883,0.104423,0.279726,0.138978,0.115899,0.279335,0.138127,...,0.089976,0.025434,0.006818,0.208078,0.399704,0.159763,0.163732,0.160265,0.167321,fail
8,0.069271,0.207594,0.104783,0.030843,0.096072,0.236376,0.121842,0.107067,0.224851,0.140349,...,0.074534,0.023776,0.005527,0.187968,0.344008,0.152486,0.142803,0.154266,0.139012,fail
9,0.088628,0.282059,0.141736,0.041806,0.097078,0.243180,0.127177,0.120483,0.289907,0.132201,...,0.095249,0.023441,0.007293,0.214287,0.411489,0.163562,0.170986,0.148508,0.172403,fail
10,0.087181,0.264273,0.139650,0.040899,0.103312,0.239833,0.124372,0.125964,0.274398,0.144078,...,0.091176,0.024480,0.007284,0.192214,0.358844,0.155050,0.167865,0.154259,0.176910,pass
11,0.073993,0.216892,0.111842,0.031822,0.110050,0.279944,0.145536,0.145514,0.317424,0.158425,...,0.103934,0.027364,0.006487,0.244235,0.452768,0.193509,0.198068,0.178758,0.161726,pass
12,0.086116,0.270037,0.131414,0.039492,0.101274,0.270545,0.139224,0.123463,0.287125,0.153527,...,0.099872,0.026734,0.007151,0.176386,0.322359,0.147957,0.172174,0.162621,0.168772,pass
13,0.083420,0.248434,0.118259,0.036883,0.100519,0.240394,0.125948,0.118468,0.260370,0.164362,...,0.088581,0.024370,0.006457,0.194126,0.349142,0.159770,0.165092,0.157846,0.164478,pass
14,0.073722,0.233397,0.121129,0.035705,0.107429,0.290759,0.147043,0.111141,0.255995,0.143896,...,0.083397,0.026996,0.006066,0.170199,0.317541,0.139938,0.147646,0.164629,0.144443,pass
15,0.074551,0.235637,0.114191,0.034342,0.085679,0.233780,0.119991,0.106092,0.259795,0.123661,...,0.081707,0.020849,0.005763,0.191594,0.366565,0.144984,0.151030,0.133688,0.147183,pass
16,0.057205,0.181819,0.095600,0.026846,0.086262,0.239123,0.120427,0.096758,0.221679,0.102982,...,0.071672,0.023028,0.004903,0.154535,0.289697,0.122449,0.129733,0.137940,0.112104,pass
17,0.043141,0.134923,0.066644,0.019559,0.049813,0.126587,0.065575,0.061446,0.142434,0.067449,...,0.048646,0.012813,0.003838,0.089790,0.166513,0.072841,0.085680,0.075828,0.087422,pass
18,0.053072,0.161024,0.081732,0.024619,0.088710,0.231215,0.116268,0.088508,0.209993,0.122783,...,0.069156,0.022008,0.003881,0.183568,0.343432,0.144780,0.127992,0.140282,0.096610,pass
19,0.069105,0.203290,0.103651,0.030424,0.088501,0.213615,0.113308,0.117134,0.254674,0.129527,...,0.088948,0.022138,0.005967,0.192446,0.362855,0.151918,0.162697,0.141122,0.145709,pass

[[1.30538406 1.30448868 1.29596621 1.29859345 1.13177048 1.10728437
  1.11528143 1.12713981 1.12502989 1.21197764 1.16686001 1.22468946
  1.12979969 1.13242947 1.13967812 1.26125839 1.18346624 1.20955813
  1.15543783 1.1394986  1.12309089 1.28538126]]
BARINEL SCORES

,swap 11,rxx 4,cp 19,cp 18,cp 20,x 5,h 21,h 0,cp 6,cp 13,...,cp 15,h 17,cp 16,h 2,h 1,cp 8,h 14,cp 7,h 12,cp 10
sum,0.544947,0.539518,0.539292,0.538692,0.53835,0.534019,0.533899,0.528511,0.528125,0.524893,...,0.521835,0.521071,0.520435,0.519608,0.519273,0.518302,0.51828,0.516247,0.511109,0.507057

custom SCORES

,cp 19,cp 20,cp 18,h 21,swap 11,rxx 4,h 0,cp 6,x 5,h 3,...,h 17,h 2,cp 15,h 12,h 1,cp 8,cp 16,h 14,cp 7,cp 10
sum,0.714019,0.713918,0.713577,0.708135,0.703916,0.702662,0.698346,0.694651,0.692017,0.675557,...,0.668504,0.667631,0.667333,0.665972,0.66507,0.665037,0.664502,0.664324,0.663336,0.662303

DSTAR SCORES

,rxx 4,swap 11,cp 13,cp 10,cp 16,cp 20,x 5,swap 9,h 2,h 3,...,h 12,cp 15,cp 19,h 14,h 17,cp 8,h 21,cp 18,cp 7,cp 6
sum,1.14177,0.607225,0.603216,0.576869,0.533053,0.517254,0.356584,0.29343,0.23118,0.217981,...,0.166002,0.157428,0.145293,0.124984,0.092046,0.073149,0.060336,0.01358,0.005929,0.000416

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_ccx_inGap_6_.qasm

100%|██████████| 10/10 [01:04<00:00,  6.47s/it]
100%|██████████| 10/10 [01:08<00:00,  6.87s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,swap 12,...,cp 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.090424,0.283197,0.143537,0.041578,0.089327,0.218256,0.112128,0.110852,0.267294,0.207508,...,0.168077,0.059011,0.017000,0.005770,0.147257,0.107093,0.118063,0.104985,0.137986,fail
1,0.089725,0.282134,0.140375,0.042278,0.095545,0.238557,0.122582,0.117526,0.276271,0.215003,...,0.187796,0.061714,0.018097,0.005671,0.152000,0.118854,0.124700,0.113146,0.136967,fail
2,0.078156,0.244581,0.124255,0.036720,0.098750,0.245592,0.127857,0.112857,0.260302,0.192993,...,0.180300,0.057175,0.019518,0.005066,0.151413,0.114380,0.118518,0.122111,0.121453,fail
3,0.071895,0.210103,0.106374,0.031959,0.085043,0.189889,0.102089,0.114969,0.255900,0.213447,...,0.169489,0.059062,0.015691,0.004840,0.146777,0.110441,0.120767,0.100717,0.118577,fail
4,0.065769,0.201858,0.102410,0.030833,0.102146,0.269021,0.138759,0.112861,0.254556,0.189378,...,0.184203,0.055442,0.020287,0.004288,0.146550,0.117090,0.115460,0.125745,0.103118,fail
5,0.078385,0.248381,0.124162,0.036899,0.091402,0.240202,0.124725,0.113734,0.261456,0.190892,...,0.173255,0.058970,0.018665,0.005144,0.142161,0.108319,0.116970,0.114808,0.122436,fail
6,0.069547,0.213376,0.106932,0.031682,0.091799,0.240528,0.126362,0.119561,0.276570,0.210155,...,0.181654,0.062629,0.018757,0.004407,0.156254,0.117268,0.125564,0.118573,0.107741,fail
7,0.083263,0.264706,0.129694,0.039438,0.106646,0.267497,0.141362,0.124671,0.285531,0.203166,...,0.193015,0.062138,0.020528,0.005261,0.160510,0.123707,0.128314,0.129044,0.127219,fail
8,0.081186,0.252247,0.129072,0.037418,0.082089,0.199772,0.103506,0.112690,0.264695,0.223977,...,0.177666,0.061059,0.016389,0.005172,0.148632,0.111278,0.119722,0.101846,0.124311,fail
9,0.082652,0.244663,0.125919,0.037170,0.099476,0.227967,0.118921,0.124805,0.264879,0.201319,...,0.182315,0.062508,0.018450,0.005371,0.152453,0.119036,0.126862,0.116246,0.132759,fail
10,0.071816,0.231356,0.114616,0.033235,0.073873,0.194477,0.100810,0.097101,0.230725,0.162306,...,0.155494,0.052862,0.015276,0.004513,0.131010,0.096255,0.104291,0.094706,0.108021,pass
11,0.068050,0.210144,0.099865,0.031137,0.074066,0.171281,0.092844,0.096893,0.213084,0.171914,...,0.154339,0.049049,0.014580,0.004487,0.125693,0.097667,0.100405,0.092031,0.108507,pass
12,0.068986,0.216424,0.109002,0.032101,0.093232,0.247795,0.129530,0.106898,0.243945,0.181110,...,0.185947,0.056112,0.020085,0.004542,0.145513,0.112126,0.110830,0.120468,0.105457,pass
13,0.072809,0.221443,0.111178,0.032618,0.092995,0.242936,0.123486,0.109821,0.246538,0.181638,...,0.162862,0.053681,0.017846,0.004573,0.140561,0.105079,0.111304,0.113330,0.113188,pass
14,0.052260,0.157668,0.080117,0.023926,0.073656,0.177937,0.094162,0.081995,0.187619,0.144905,...,0.127019,0.040377,0.013766,0.003445,0.106340,0.081481,0.084514,0.086110,0.083101,pass
15,0.064317,0.205512,0.107477,0.030611,0.062796,0.156546,0.081629,0.088620,0.204089,0.142247,...,0.130482,0.045968,0.012408,0.004365,0.109076,0.080213,0.091251,0.076383,0.102514,pass
16,0.082719,0.265457,0.131717,0.039450,0.094668,0.256096,0.130680,0.119175,0.306302,0.277150,...,0.206857,0.069462,0.019543,0.005212,0.170637,0.127955,0.135751,0.120945,0.124285,pass
17,0.059901,0.197727,0.098890,0.029795,0.069864,0.190862,0.096889,0.074177,0.191916,0.160208,...,0.139519,0.041410,0.014637,0.003738,0.108481,0.082810,0.081764,0.086780,0.086898,pass
18,0.084654,0.267123,0.129289,0.039192,0.104281,0.274384,0.143746,0.112954,0.259763,0.172963,...,0.175701,0.054916,0.020313,0.005383,0.149269,0.111661,0.114640,0.126711,0.130663,pass
19,0.062570,0.188106,0.092073,0.027992,0.089524,0.239033,0.119902,0.099227,0.221464,0.171021,...,0.171552,0.051087,0.017789,0.003748,0.132924,0.108902,0.105309,0.112423,0.095132,pass

[[1.14315702 1.15815238 1.16438131 1.15522606 1.13185454 1.15099818
  1.16032626 1.07172214 1.07042605 1.09372337 1.12978912 1.11165906
  1.05384153 1.07363612 1.04433529 1.11939062 1.13164048 1.06721501
  1.07808667 1.05613633 1.12484496 1.11950089]]
BARINEL SCORES

,h 14,h 11,h 2,h 0,cp 7,swap 12,cp 5,cp 13,h 21,cp 19,...,x 4,h 17,cp 20,cp 8,h 1,ccx 9,cp 6,swap 10,cp 15,cp 16
sum,0.541291,0.539658,0.538777,0.53816,0.538031,0.537025,0.536762,0.536398,0.534791,0.534354,...,0.532673,0.531976,0.530859,0.527586,0.526947,0.526383,0.524512,0.523719,0.52243,0.520712

custom SCORES

,h 11,cp 19,h 0,cp 5,h 21,cp 18,h 14,cp 20,swap 12,h 17,...,cp 7,h 3,h 1,x 4,cp 15,cp 6,cp 16,swap 10,cp 8,ccx 9
sum,0.692082,0.689902,0.688778,0.688617,0.687629,0.687534,0.686319,0.684563,0.683864,0.682506,...,0.678503,0.677042,0.67513,0.674792,0.673978,0.671296,0.670546,0.669268,0.669194,0.665064

DSTAR SCORES

,ccx 9,cp 13,cp 20,swap 10,cp 16,swap 12,cp 8,x 4,h 11,h 0,...,cp 15,h 14,h 3,h 1,h 17,h 21,cp 7,cp 18,cp 6,cp 5
sum,1.05215,0.578225,0.491674,0.478884,0.44957,0.356437,0.278384,0.199836,0.138898,0.137389,...,0.13355,0.123431,0.119653,0.119323,0.081983,0.05854,0.034204,0.012978,0.003308,0.000259

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_y_inGap_2_.qasm

100%|██████████| 10/10 [00:49<00:00,  4.92s/it]
100%|██████████| 10/10 [00:48<00:00,  4.81s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,cp 8,cp 7,cp 6,x 5,h 4,h 3,h 2,y 1,h 0,pass/fail
0,0.085135,0.250830,0.125120,0.037667,0.109993,0.264018,0.137640,0.127002,0.271948,0.155666,...,0.090295,0.026011,0.007040,0.199588,0.160425,0.162165,0.160597,0.135591,0.167872,fail
1,0.075638,0.231030,0.109646,0.033743,0.094871,0.249529,0.132119,0.119222,0.276789,0.143356,...,0.095332,0.025389,0.006193,0.193577,0.159408,0.163161,0.149753,0.129424,0.143241,fail
2,0.082075,0.261366,0.134340,0.038607,0.111682,0.296027,0.149229,0.123242,0.295697,0.137049,...,0.096520,0.028125,0.006785,0.204424,0.153461,0.164356,0.164907,0.140518,0.154294,fail
3,0.059072,0.177791,0.090782,0.027613,0.093006,0.242437,0.127982,0.119991,0.285350,0.142244,...,0.096475,0.023850,0.005256,0.193471,0.161957,0.163549,0.143043,0.121635,0.121697,fail
4,0.048394,0.147876,0.070457,0.021909,0.085227,0.233007,0.122399,0.095720,0.218106,0.112217,...,0.069260,0.022422,0.004201,0.171120,0.126803,0.124815,0.134789,0.116098,0.098466,fail
5,0.080992,0.256027,0.128920,0.038450,0.104183,0.273437,0.140035,0.115046,0.267988,0.139024,...,0.090117,0.027071,0.006964,0.163252,0.148708,0.150242,0.155411,0.132518,0.153651,fail
6,0.072858,0.228088,0.116975,0.034664,0.091537,0.240780,0.124336,0.114334,0.274973,0.129604,...,0.090156,0.022818,0.005755,0.203134,0.145298,0.155271,0.137077,0.115151,0.136033,fail
7,0.083675,0.273820,0.136271,0.040205,0.107089,0.291525,0.155626,0.126406,0.303609,0.130934,...,0.099907,0.029038,0.007375,0.208257,0.148227,0.167561,0.166782,0.140917,0.162307,fail
8,0.078611,0.247791,0.127354,0.037530,0.097719,0.248168,0.127864,0.105387,0.242224,0.116844,...,0.073015,0.022651,0.005993,0.198515,0.123192,0.134039,0.141035,0.119972,0.142941,fail
9,0.075533,0.240598,0.122015,0.036415,0.101737,0.250532,0.130615,0.124897,0.302410,0.135833,...,0.101293,0.025158,0.006768,0.207575,0.156855,0.171147,0.148478,0.125818,0.147832,fail
10,0.078857,0.255028,0.122734,0.037733,0.096319,0.261926,0.136545,0.109913,0.272214,0.126424,...,0.084092,0.023885,0.006258,0.209869,0.140378,0.149077,0.144553,0.123424,0.148295,pass
11,0.067546,0.205530,0.103274,0.031045,0.070112,0.171172,0.089019,0.084944,0.189990,0.114260,...,0.065375,0.017189,0.005049,0.161474,0.118604,0.116300,0.106847,0.088282,0.124918,pass
12,0.073209,0.229345,0.110930,0.033869,0.088651,0.224687,0.119835,0.110491,0.259765,0.137479,...,0.087192,0.022738,0.006219,0.174170,0.145834,0.149448,0.134693,0.112975,0.142527,pass
13,0.055562,0.184808,0.086099,0.026264,0.062547,0.164758,0.085693,0.081644,0.199474,0.088714,...,0.067053,0.016512,0.004749,0.138156,0.101843,0.114058,0.097647,0.083637,0.106093,pass
14,0.074962,0.238207,0.120988,0.035370,0.072540,0.179713,0.092282,0.090612,0.217913,0.111099,...,0.074635,0.018815,0.005967,0.152987,0.119999,0.122737,0.109772,0.090769,0.136941,pass
15,0.062015,0.178019,0.093981,0.027520,0.084141,0.210815,0.103967,0.091235,0.199795,0.120846,...,0.070176,0.020550,0.004898,0.165162,0.131698,0.122990,0.124378,0.105869,0.118769,pass
16,0.056130,0.171509,0.084424,0.025403,0.065962,0.152504,0.080941,0.093160,0.217204,0.109788,...,0.078091,0.017029,0.004855,0.166308,0.129135,0.132153,0.103282,0.087491,0.112185,pass
17,0.062972,0.202599,0.101232,0.029741,0.099165,0.262390,0.138204,0.113705,0.258375,0.129925,...,0.084735,0.026877,0.005758,0.206298,0.150531,0.148588,0.158943,0.135041,0.125338,pass
18,0.070308,0.210740,0.107441,0.032170,0.092617,0.218154,0.117892,0.109976,0.232295,0.128235,...,0.074771,0.022068,0.005905,0.160692,0.126326,0.134477,0.134774,0.111492,0.141545,pass
19,0.043274,0.139786,0.068320,0.020603,0.050425,0.149069,0.077501,0.062698,0.171292,0.070923,...,0.055511,0.013364,0.003452,0.110189,0.084337,0.090638,0.078315,0.068201,0.078463,pass

[[1.14740295 1.18269993 1.17284885 1.15931552 1.12013547 1.14319858
  1.1546272  1.08433402 1.10842837 1.1592909  1.16380231 1.12360428
  1.23338919 1.12252093 1.14988165 1.18323084 1.07187937 1.09111084
  1.09970248 1.11049312 1.10294884 1.17529765]]
BARINEL SCORES

,cp 16,cp 15,h 17,cp 7,y 1,h 2,h 14,cp 13,cp 8,h 3,...,cp 10,h 4,x 5,h 12,cp 6,cp 19,cp 18,h 0,h 21,cp 20
sum,0.564811,0.564017,0.560287,0.559248,0.559187,0.557265,0.552573,0.552525,0.548887,0.548618,...,0.545085,0.543111,0.54147,0.541339,0.539924,0.537583,0.536415,0.536281,0.535026,0.534595

custom SCORES

,cp 15,cp 16,cp 7,h 17,swap 9,y 1,h 2,cp 13,swap 11,cp 8,...,h 3,h 12,cp 10,cp 19,h 0,cp 20,cp 18,h 4,h 21,x 5
sum,0.726824,0.726234,0.720015,0.717186,0.71386,0.713375,0.711975,0.705634,0.705552,0.702921,...,0.699447,0.698231,0.6982,0.695209,0.693853,0.692661,0.691883,0.69126,0.688499,0.686568

DSTAR SCORES

,cp 13,cp 10,swap 11,cp 16,cp 20,x 5,swap 9,h 3,h 2,h 4,...,h 12,y 1,h 14,cp 19,h 17,cp 8,h 21,cp 18,cp 7,cp 6
sum,0.614049,0.603314,0.57439,0.558999,0.446106,0.324158,0.314443,0.214715,0.201517,0.195867,...,0.161886,0.148301,0.125299,0.12273,0.092195,0.075805,0.051719,0.011677,0.006253,0.000386

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_rx_inGap_16_.qasm

100%|██████████| 10/10 [00:46<00:00,  4.61s/it]
100%|██████████| 10/10 [00:47<00:00,  4.78s/it]

,rx 21,h 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.371674,0.060879,0.191347,0.094927,0.027728,0.087963,0.241373,0.126531,0.109810,0.260605,...,0.178559,0.084189,0.023553,0.005142,0.181832,0.142261,0.145700,0.139650,0.119194,fail
1,0.375921,0.081235,0.277495,0.136639,0.040243,0.098744,0.280689,0.143631,0.102350,0.264980,...,0.178432,0.081034,0.026005,0.006400,0.186994,0.131809,0.136857,0.152528,0.140566,fail
2,0.444077,0.102774,0.325714,0.161661,0.048630,0.117378,0.298544,0.157088,0.140341,0.335054,...,0.222753,0.110099,0.029132,0.008504,0.217264,0.166475,0.185862,0.171615,0.195040,fail
3,0.578947,0.080833,0.244666,0.130713,0.038354,0.113189,0.290057,0.149778,0.131063,0.298059,...,0.208066,0.096386,0.027825,0.006511,0.229308,0.160548,0.170329,0.168102,0.155706,fail
4,0.433148,0.058744,0.182576,0.093376,0.027193,0.084057,0.238175,0.119215,0.098730,0.242659,...,0.179869,0.078732,0.022245,0.004818,0.186122,0.131542,0.135165,0.132169,0.109253,fail
5,0.550526,0.096541,0.296500,0.147053,0.043574,0.107986,0.265992,0.138086,0.126835,0.287438,...,0.195759,0.095302,0.026454,0.007487,0.237432,0.164971,0.169800,0.162383,0.182077,fail
6,0.486173,0.082090,0.260347,0.127560,0.037860,0.107340,0.276816,0.147424,0.133261,0.316487,...,0.203270,0.099678,0.027516,0.007140,0.224687,0.154630,0.175191,0.161805,0.161815,fail
7,0.457363,0.104018,0.340044,0.172112,0.051644,0.105992,0.255341,0.134711,0.117358,0.284762,...,0.191154,0.090630,0.025529,0.008564,0.210655,0.135981,0.153920,0.149043,0.191466,fail
8,0.494574,0.100644,0.308385,0.154943,0.047455,0.139872,0.344806,0.180865,0.151307,0.330792,...,0.214956,0.111007,0.034599,0.008365,0.235988,0.188079,0.191816,0.206005,0.194333,fail
9,0.421100,0.078843,0.254842,0.126744,0.038253,0.100226,0.257881,0.136037,0.110616,0.263347,...,0.176613,0.084465,0.025634,0.006340,0.195616,0.143860,0.145746,0.150289,0.142684,fail
10,0.311099,0.051767,0.154161,0.076679,0.023508,0.062724,0.146536,0.075158,0.074717,0.168831,...,0.122118,0.057235,0.014137,0.004010,0.145056,0.104555,0.102704,0.089754,0.097333,pass
11,0.372054,0.089175,0.279926,0.138714,0.042283,0.089524,0.214907,0.111371,0.101250,0.234053,...,0.155134,0.076342,0.021242,0.006893,0.175449,0.134861,0.133567,0.129207,0.162654,pass
12,0.314008,0.043123,0.134340,0.065557,0.019736,0.075228,0.203564,0.110769,0.088968,0.210845,...,0.149296,0.067503,0.020539,0.003682,0.154425,0.118842,0.117928,0.123094,0.082427,pass
13,0.413198,0.081768,0.264302,0.135869,0.040297,0.098793,0.254177,0.131405,0.105972,0.244452,...,0.138652,0.074049,0.023206,0.006620,0.181272,0.116601,0.132114,0.139994,0.152280,pass
14,0.281193,0.064635,0.199559,0.099196,0.029978,0.086507,0.217717,0.111945,0.107998,0.243997,...,0.181218,0.084151,0.021670,0.005467,0.172034,0.144244,0.146482,0.130892,0.127256,pass
15,0.248213,0.070128,0.210618,0.106723,0.032205,0.088419,0.209922,0.111062,0.115545,0.262200,...,0.201202,0.090521,0.022010,0.006126,0.167701,0.145335,0.154544,0.131144,0.142885,pass
16,0.417087,0.098895,0.294528,0.145804,0.044133,0.111705,0.260200,0.133118,0.133677,0.295391,...,0.195563,0.098334,0.025152,0.007827,0.220618,0.172527,0.175118,0.158799,0.191181,pass
17,0.329038,0.083951,0.256357,0.126805,0.038728,0.110194,0.274162,0.142932,0.127917,0.293417,...,0.218195,0.099986,0.028276,0.006932,0.201143,0.176140,0.170807,0.167612,0.159927,pass
18,0.246403,0.059543,0.180336,0.089776,0.026373,0.076413,0.183813,0.099490,0.098692,0.212423,...,0.155769,0.074174,0.020694,0.005204,0.155522,0.127128,0.129230,0.123497,0.118807,pass
19,0.344376,0.083057,0.274518,0.138338,0.040045,0.081087,0.218701,0.109732,0.097666,0.250111,...,0.189801,0.083075,0.021035,0.006547,0.181677,0.124757,0.137290,0.122422,0.146982,pass

[[1.25489612 1.22865269 1.26791495 1.2789519  1.28809558 1.31613449
  1.25398898 1.26182213 1.23852505 1.16169316 1.30747779 1.16430288
  1.24576681 1.14265768 1.19167759 1.28863619 1.23632684 1.12746179
  1.23723334 1.19111894 1.29270969 1.22502496]]
BARINEL SCORES

,rx 21,cp 14,cp 15,swap 10,cp 6,h 1,h 16,x 4,cp 18,cp 12,...,cp 5,h 20,h 13,cp 7,h 0,h 2,swap 8,h 3,cp 9,h 11
sum,0.584715,0.557655,0.557362,0.554124,0.551938,0.547624,0.546866,0.545457,0.545008,0.544195,...,0.538746,0.538331,0.537217,0.536315,0.535375,0.534981,0.533159,0.52689,0.523855,0.52252

custom SCORES

,rx 21,cp 14,cp 15,cp 6,h 16,h 1,cp 18,cp 17,cp 19,swap 10,...,h 13,cp 12,h 0,x 4,cp 7,h 2,h 11,h 3,cp 9,swap 8
sum,0.768154,0.73357,0.732093,0.729749,0.726803,0.724604,0.719268,0.718006,0.716354,0.715415,...,0.703556,0.702242,0.699337,0.699203,0.696094,0.694288,0.693315,0.689862,0.687005,0.685463

DSTAR SCORES

,rx 21,cp 12,swap 10,cp 15,cp 9,cp 19,x 4,swap 8,h 2,h 1,...,cp 14,h 11,cp 18,h 13,h 16,cp 7,h 20,cp 17,cp 6,cp 5
sum,1.603143,0.669998,0.669401,0.620559,0.602183,0.587222,0.377273,0.324617,0.22749,0.224411,...,0.184479,0.171596,0.162808,0.135037,0.103803,0.080306,0.066822,0.01555,0.007055,0.000477

ERROR GATE LOCATION:
21
Now evolving the following mutant:  AddGate_cz_inGap_9_.qasm

100%|██████████| 10/10 [00:58<00:00,  5.82s/it]
100%|██████████| 10/10 [00:57<00:00,  5.76s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cz 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.064375,0.197767,0.099314,0.028999,0.094230,0.257011,0.133265,0.123313,0.405035,0.307985,...,0.031336,0.096891,0.025973,0.005175,0.225122,0.172640,0.230115,0.217755,0.132798,fail
1,0.095364,0.300802,0.151107,0.044665,0.100662,0.253693,0.132147,0.133201,0.430897,0.323157,...,0.032190,0.105759,0.025967,0.007959,0.221667,0.153158,0.239638,0.220536,0.196917,fail
2,0.069949,0.209658,0.107898,0.031472,0.087964,0.210792,0.110522,0.124229,0.350785,0.281466,...,0.030117,0.096270,0.022645,0.006108,0.188209,0.148231,0.217242,0.198112,0.151335,fail
3,0.089852,0.295331,0.149253,0.044062,0.110864,0.298566,0.154718,0.135239,0.514003,0.370122,...,0.040888,0.119162,0.031229,0.006971,0.260136,0.191031,0.271114,0.248386,0.164549,fail
4,0.060612,0.190221,0.095365,0.028449,0.085857,0.234969,0.121963,0.096189,0.352886,0.250174,...,0.024326,0.076385,0.022239,0.004594,0.170568,0.125165,0.179814,0.173100,0.114019,fail
5,0.103288,0.324634,0.162051,0.048278,0.111699,0.303638,0.153561,0.134352,0.490980,0.361550,...,0.032548,0.106480,0.028157,0.007917,0.209786,0.161345,0.244260,0.227794,0.200173,fail
6,0.080194,0.241388,0.120934,0.036784,0.105987,0.269917,0.142633,0.128769,0.418031,0.311244,...,0.030172,0.096858,0.026215,0.006370,0.228674,0.161154,0.232080,0.222868,0.166907,fail
7,0.068805,0.205253,0.106739,0.030584,0.097339,0.252281,0.130912,0.114863,0.391363,0.293808,...,0.028458,0.089152,0.025517,0.005549,0.189893,0.149252,0.210030,0.200268,0.137627,fail
8,0.080000,0.249311,0.123355,0.036711,0.109484,0.296193,0.151022,0.130701,0.460090,0.326016,...,0.033825,0.108847,0.030442,0.006691,0.209226,0.182541,0.246202,0.235750,0.159607,fail
9,0.115285,0.370165,0.188777,0.054229,0.104728,0.267146,0.133028,0.126626,0.434098,0.307042,...,0.030859,0.100701,0.026292,0.008787,0.214473,0.140970,0.228927,0.214455,0.216982,fail
10,0.070132,0.215333,0.106968,0.032365,0.081657,0.191013,0.103604,0.101185,0.294725,0.220732,...,0.022069,0.072838,0.019118,0.005682,0.162748,0.121249,0.174410,0.168318,0.147326,pass
11,0.082120,0.249918,0.124788,0.037993,0.104329,0.251731,0.133565,0.122897,0.385552,0.287261,...,0.028909,0.092567,0.025866,0.006751,0.193875,0.148274,0.219895,0.211145,0.169460,pass
12,0.061236,0.186962,0.096619,0.027707,0.071566,0.170401,0.089257,0.093667,0.287274,0.229835,...,0.023412,0.072498,0.018138,0.004850,0.170395,0.121757,0.170956,0.157583,0.122941,pass
13,0.079920,0.246869,0.127605,0.037459,0.107042,0.252951,0.133845,0.130522,0.411681,0.316980,...,0.032591,0.102554,0.026595,0.006874,0.200283,0.155650,0.235452,0.217411,0.164345,pass
14,0.087203,0.255661,0.126903,0.038846,0.113151,0.275195,0.143659,0.140280,0.460768,0.327785,...,0.036071,0.112963,0.029619,0.007150,0.205373,0.186592,0.256417,0.241038,0.181365,pass
15,0.043204,0.132155,0.064139,0.019630,0.077257,0.213668,0.111739,0.086149,0.291161,0.205616,...,0.020249,0.065516,0.021546,0.003485,0.130601,0.118939,0.156436,0.159067,0.086664,pass
16,0.073903,0.232313,0.115103,0.034353,0.085841,0.218782,0.111355,0.095405,0.353253,0.237635,...,0.024596,0.075543,0.021334,0.005867,0.163541,0.122375,0.178061,0.169961,0.144805,pass
17,0.080719,0.258542,0.122826,0.036679,0.088347,0.229987,0.121852,0.120639,0.392603,0.279549,...,0.030493,0.098800,0.024361,0.006688,0.195510,0.151873,0.219652,0.204958,0.161521,pass
18,0.045731,0.138523,0.065612,0.020311,0.063524,0.165661,0.085135,0.080318,0.259018,0.192462,...,0.019696,0.060032,0.015347,0.003424,0.139929,0.106326,0.145129,0.135748,0.092011,pass
19,0.039057,0.120101,0.059902,0.017838,0.066747,0.175642,0.094011,0.075277,0.244586,0.180405,...,0.017716,0.056631,0.018261,0.003353,0.125298,0.099729,0.137403,0.136963,0.078134,pass

[[1.39279706 1.43223335 1.44679897 1.41135097 1.10722777 1.14831394
  1.1344843  1.08409638 1.20994058 1.18153036 1.14914734 1.42779701
  1.18694653 1.2991825  1.19579513 1.17989228 1.328972   1.22835687
  1.20487474 1.17905268 1.15045573 1.32232372]]
BARINEL SCORES

,cp 19,swap 10,cp 20,cp 18,cp 12,cz 13,x 4,h 21,cp 16,cp 7,...,h 0,h 2,cp 15,cp 6,h 1,h 14,h 3,cp 9,h 17,h 11
sum,0.563563,0.559643,0.559312,0.558955,0.558307,0.55686,0.556526,0.555166,0.552114,0.551638,...,0.548895,0.548365,0.547305,0.545877,0.545041,0.543845,0.543301,0.540812,0.539971,0.535748

custom SCORES

,cp 19,cp 20,swap 10,cp 18,h 21,cp 5,swap 8,h 0,x 4,cz 13,...,cp 16,h 2,h 3,cp 6,cp 15,h 1,cp 9,h 14,h 11,h 17
sum,0.767403,0.759579,0.759407,0.756176,0.748475,0.732581,0.730802,0.730349,0.72743,0.725302,...,0.710614,0.710003,0.706953,0.706896,0.702532,0.701802,0.701291,0.69124,0.689661,0.689438

DSTAR SCORES

,cz 13,cp 12,cp 9,cp 16,cp 20,swap 10,h 2,h 1,x 4,h 0,...,cp 19,h 11,h 14,h 17,cp 7,h 21,cp 18,swap 8,cp 6,cp 5
sum,1.348736,0.786405,0.650351,0.575694,0.554967,0.505071,0.444546,0.394959,0.383731,0.237263,...,0.154624,0.1523,0.140881,0.093716,0.091862,0.064251,0.014329,0.009658,0.006854,0.000435

ERROR GATE LOCATION:
13
Now evolving the following mutant:  AddGate_rx_inGap_14_.qasm

100%|██████████| 10/10 [00:59<00:00,  5.90s/it]
100%|██████████| 10/10 [01:01<00:00,  6.12s/it]

,h 21,rx 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.087223,0.651344,0.437924,0.141190,0.041721,0.303166,0.225551,0.115298,0.104689,0.251298,...,0.184773,0.088956,0.023400,0.007052,0.199712,0.161923,0.155451,0.191676,0.194326,fail
1,0.077808,0.486705,0.404722,0.130842,0.038778,0.229340,0.211383,0.110264,0.086244,0.238500,...,0.204758,0.078561,0.021315,0.006556,0.178276,0.121922,0.128936,0.150005,0.163602,fail
2,0.097769,0.685955,0.480591,0.158102,0.047074,0.325321,0.253156,0.131596,0.117464,0.274586,...,0.201477,0.093875,0.025757,0.008190,0.220737,0.164246,0.166513,0.205666,0.217220,fail
3,0.071347,0.501879,0.385445,0.115846,0.034449,0.230053,0.191667,0.101861,0.106647,0.281409,...,0.229172,0.096444,0.020682,0.006372,0.220142,0.146679,0.166642,0.160412,0.167197,fail
4,0.085183,0.549534,0.442283,0.138561,0.041055,0.259719,0.220029,0.120240,0.114346,0.286269,...,0.160334,0.094056,0.023123,0.007288,0.212563,0.132479,0.168867,0.181003,0.195649,fail
5,0.083975,0.512266,0.410043,0.134914,0.039378,0.246246,0.216259,0.107280,0.103348,0.243880,...,0.191126,0.084208,0.021766,0.006918,0.219540,0.153412,0.149544,0.171871,0.185815,fail
6,0.078457,0.487113,0.410233,0.126664,0.036624,0.228996,0.210590,0.106208,0.104907,0.260049,...,0.187449,0.087082,0.021403,0.006549,0.205419,0.139911,0.156125,0.163396,0.177279,fail
7,0.096948,0.571815,0.464294,0.155523,0.045858,0.277012,0.237667,0.120743,0.114615,0.277793,...,0.193909,0.097074,0.025132,0.008032,0.234420,0.174379,0.171646,0.196778,0.212907,fail
8,0.064838,0.540044,0.416968,0.109198,0.031588,0.235039,0.198658,0.103946,0.100050,0.269535,...,0.182011,0.091578,0.021173,0.005506,0.208267,0.145630,0.161106,0.167595,0.159551,fail
9,0.068998,0.454033,0.367637,0.111135,0.032782,0.210794,0.183785,0.095658,0.091203,0.239993,...,0.163909,0.080624,0.018674,0.005583,0.199631,0.132518,0.142682,0.149095,0.155794,fail
10,0.051864,0.421166,0.272565,0.083374,0.024740,0.192487,0.131030,0.072295,0.073833,0.170998,...,0.098828,0.059068,0.014713,0.004538,0.143211,0.102440,0.108502,0.125507,0.126392,pass
11,0.044906,0.242047,0.214161,0.070430,0.021078,0.118798,0.111594,0.057085,0.052456,0.130175,...,0.093891,0.044323,0.010964,0.003484,0.113229,0.081911,0.078554,0.085358,0.096361,pass
12,0.064248,0.510592,0.379168,0.103307,0.030462,0.227517,0.185662,0.094929,0.092861,0.240918,...,0.188594,0.085855,0.018869,0.004979,0.194708,0.148802,0.149600,0.155279,0.151020,pass
13,0.044792,0.388419,0.298050,0.063375,0.019638,0.165388,0.131791,0.072321,0.093364,0.235451,...,0.199848,0.085743,0.014808,0.003895,0.187027,0.142467,0.152744,0.123889,0.123718,pass
14,0.062602,0.329147,0.268702,0.097107,0.029068,0.167420,0.136822,0.070490,0.074661,0.169302,...,0.117161,0.061307,0.014462,0.004924,0.132378,0.119337,0.109182,0.117475,0.133395,pass
15,0.040753,0.404885,0.259971,0.065380,0.019926,0.173655,0.121898,0.066996,0.061778,0.158530,...,0.129966,0.057852,0.013547,0.003624,0.123335,0.093338,0.098396,0.110047,0.104066,pass
16,0.096006,0.480040,0.422968,0.160629,0.047357,0.244558,0.223829,0.116826,0.111565,0.285196,...,0.196503,0.097178,0.023329,0.007848,0.214944,0.152166,0.169716,0.177641,0.201913,pass
17,0.045243,0.254614,0.227312,0.064430,0.020075,0.122925,0.100429,0.056670,0.073681,0.168628,...,0.108399,0.062641,0.012126,0.004042,0.117434,0.108461,0.110310,0.098174,0.111858,pass
18,0.057917,0.304271,0.259763,0.094441,0.027725,0.154088,0.144212,0.072481,0.073104,0.186782,...,0.158898,0.063090,0.013471,0.004530,0.151776,0.098855,0.108576,0.104131,0.119839,pass
19,0.076424,0.507223,0.419098,0.125353,0.037603,0.235329,0.209999,0.108092,0.097888,0.251399,...,0.201685,0.087870,0.021449,0.006355,0.201383,0.152536,0.153240,0.163069,0.170761,pass

[[1.20324321 1.26078791 1.13880269 1.19595166 1.2091634  1.27792989
  1.17815651 1.18225481 1.12566241 1.09124931 1.21344138 1.09520624
  1.16357329 1.20685648 1.0877135  1.15799135 1.2036271  1.11697111
  1.18375457 1.0950208  1.18368889 1.18742095]]
BARINEL SCORES

,cp 15,cp 18,rx 20,h 16,cp 14,cp 5,cp 6,swap 10,cp 17,cp 19,...,h 0,x 4,cp 12,h 13,swap 8,cp 7,h 2,cp 9,h 3,h 11
sum,0.589341,0.587596,0.586086,0.585504,0.585444,0.58527,0.585077,0.584221,0.583687,0.582739,...,0.577322,0.57059,0.567732,0.564457,0.559709,0.5587,0.558563,0.552136,0.551018,0.547603

custom SCORES

,h 16,rx 20,cp 18,cp 15,cp 5,cp 17,cp 14,h 21,cp 6,h 1,...,swap 10,x 4,swap 8,h 13,cp 12,h 3,h 11,cp 9,h 2,cp 7
sum,0.772562,0.770818,0.763281,0.762926,0.761382,0.76013,0.75848,0.756435,0.754455,0.751037,...,0.744182,0.729924,0.728581,0.723304,0.722616,0.714086,0.713724,0.712749,0.711472,0.710626

DSTAR SCORES

,rx 20,cp 19,cp 12,swap 10,cp 9,h 16,cp 15,x 4,swap 8,h 0,...,h 3,cp 18,h 11,cp 14,h 13,cp 7,h 21,cp 17,cp 6,cp 5
sum,2.138436,1.367678,0.573605,0.554829,0.553502,0.549095,0.401583,0.380379,0.313726,0.295123,...,0.193746,0.159924,0.132825,0.114845,0.100778,0.074404,0.062376,0.014747,0.00487,0.000461

ERROR GATE LOCATION:
20
Now evolving the following mutant:  AddGate_rxx_inGap_2_.qasm

100%|██████████| 10/10 [00:50<00:00,  5.04s/it]
100%|██████████| 10/10 [00:51<00:00,  5.18s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,cp 8,cp 7,cp 6,x 5,h 4,h 3,h 2,rxx 1,h 0,pass/fail
0,0.070332,0.213032,0.108379,0.032072,0.087432,0.214271,0.114651,0.118107,0.268519,0.126975,...,0.087711,0.021228,0.005848,0.198946,0.138854,0.155498,0.131376,0.213376,0.140782,fail
1,0.070112,0.205750,0.104182,0.030880,0.091016,0.214272,0.112141,0.127904,0.273770,0.146069,...,0.097165,0.022675,0.006148,0.185260,0.156691,0.167538,0.137505,0.231203,0.145168,fail
2,0.068166,0.203518,0.104663,0.030517,0.101609,0.260299,0.135631,0.120323,0.277288,0.126717,...,0.093355,0.026109,0.006022,0.173989,0.141904,0.157951,0.152259,0.222321,0.134701,fail
3,0.080177,0.240221,0.119931,0.035817,0.098559,0.252868,0.132220,0.130187,0.311364,0.132529,...,0.102353,0.024373,0.007003,0.195738,0.148003,0.175156,0.143905,0.243757,0.159463,fail
4,0.068954,0.210878,0.109413,0.031771,0.096352,0.248905,0.127507,0.120544,0.284581,0.127011,...,0.093810,0.024035,0.005943,0.209536,0.148465,0.162287,0.144653,0.234748,0.137435,fail
5,0.068662,0.221193,0.115365,0.033729,0.095487,0.261646,0.135960,0.115383,0.279675,0.130441,...,0.088091,0.025391,0.005596,0.196260,0.147211,0.153242,0.150790,0.216602,0.129263,fail
6,0.089175,0.277172,0.137377,0.041085,0.096246,0.241684,0.126001,0.117446,0.284016,0.134768,...,0.091134,0.023024,0.007095,0.200616,0.146290,0.158100,0.139598,0.226963,0.166312,fail
7,0.080461,0.242660,0.121957,0.035916,0.104724,0.261912,0.136421,0.134240,0.297552,0.153314,...,0.101088,0.026469,0.007278,0.193875,0.165474,0.174506,0.156405,0.244790,0.166643,fail
8,0.071607,0.218760,0.109416,0.031957,0.098030,0.246526,0.126145,0.114060,0.264672,0.127231,...,0.089308,0.024480,0.006094,0.196240,0.143437,0.153373,0.145989,0.221283,0.140206,fail
9,0.078195,0.247601,0.124956,0.036094,0.094234,0.254314,0.127999,0.110184,0.278209,0.119265,...,0.089226,0.023867,0.006101,0.209430,0.139430,0.154308,0.141313,0.228569,0.141993,fail
10,0.082717,0.256803,0.129656,0.038422,0.096518,0.242191,0.122502,0.107220,0.241882,0.129977,...,0.078717,0.022881,0.006620,0.171751,0.133834,0.138496,0.137063,0.190176,0.153936,pass
11,0.078689,0.242610,0.121211,0.036048,0.089962,0.205522,0.112320,0.121710,0.264783,0.140380,...,0.092045,0.022410,0.006770,0.199036,0.153783,0.159843,0.137035,0.226683,0.157942,pass
12,0.038743,0.122720,0.061048,0.017994,0.057183,0.165622,0.085756,0.076748,0.199630,0.085655,...,0.063874,0.015035,0.003208,0.142174,0.106445,0.109683,0.090828,0.166700,0.075238,pass
13,0.077686,0.249324,0.122540,0.035873,0.088290,0.238013,0.121483,0.113307,0.267786,0.131203,...,0.089459,0.023217,0.006280,0.206616,0.148084,0.153958,0.138957,0.215243,0.147322,pass
14,0.063291,0.196607,0.096369,0.029289,0.070013,0.157276,0.085245,0.088754,0.199547,0.095117,...,0.066353,0.016591,0.005421,0.142722,0.101402,0.116008,0.099844,0.163673,0.123010,pass
15,0.087313,0.272080,0.131971,0.040470,0.103492,0.249961,0.135024,0.132463,0.313655,0.149259,...,0.102980,0.024883,0.007296,0.231247,0.166185,0.178665,0.152919,0.253060,0.168914,pass
16,0.081804,0.270121,0.134099,0.039658,0.081197,0.210612,0.110780,0.091751,0.224106,0.105242,...,0.073150,0.021288,0.006581,0.167294,0.115285,0.122810,0.123603,0.176236,0.147301,pass
17,0.077609,0.237379,0.116429,0.034312,0.093020,0.222032,0.117182,0.118534,0.254006,0.135913,...,0.084929,0.023374,0.006422,0.207972,0.146096,0.153075,0.142904,0.205962,0.154101,pass
18,0.051529,0.161991,0.083166,0.024732,0.079732,0.215446,0.109172,0.085635,0.207152,0.100945,...,0.065214,0.019941,0.004307,0.146010,0.113346,0.114284,0.117895,0.160672,0.097576,pass
19,0.095573,0.291174,0.144408,0.042900,0.110622,0.278705,0.144476,0.137311,0.303259,0.147735,...,0.100597,0.026621,0.007954,0.229655,0.157986,0.177750,0.163025,0.238605,0.188872,pass

[[1.19562641 1.21524774 1.18875214 1.20896257 1.08670033 1.066114
  1.07023887 1.11090725 1.10426697 1.15768358 1.10966877 1.17890773
  1.06674765 1.0967481  1.09535917 1.15293869 1.06912112 1.12128249
  1.08660356 1.08329086 1.07194155 1.13985616]]
BARINEL SCORES

,swap 9,rxx 1,cp 8,cp 13,h 3,h 14,cp 16,cp 7,cp 15,h 17,...,h 12,cp 10,x 5,cp 6,h 0,h 21,cp 19,cp 18,cp 20,swap 11
sum,0.541675,0.533476,0.53311,0.532466,0.530856,0.52957,0.529224,0.527746,0.527027,0.525538,...,0.52021,0.5193,0.515168,0.509155,0.508302,0.503676,0.50321,0.500103,0.497815,0.49454

custom SCORES

,swap 9,cp 13,cp 8,h 14,rxx 1,h 3,cp 10,cp 7,h 12,h 4,...,cp 15,h 2,cp 6,h 21,h 0,x 5,cp 19,cp 18,cp 20,swap 11
sum,0.686132,0.679462,0.679282,0.676646,0.67644,0.675063,0.672351,0.672264,0.670769,0.670443,...,0.668038,0.667721,0.655911,0.654229,0.653149,0.652863,0.652758,0.651254,0.649057,0.631735

DSTAR SCORES

,cp 13,cp 10,swap 11,cp 16,rxx 1,cp 20,swap 9,x 5,h 3,h 4,...,h 12,cp 15,h 14,cp 19,h 17,cp 8,h 21,cp 18,cp 7,cp 6
sum,0.637265,0.578126,0.513646,0.495295,0.434682,0.422897,0.332098,0.3243,0.227441,0.192011,...,0.156293,0.145801,0.131863,0.119874,0.085436,0.080513,0.051819,0.01117,0.005716,0.000396

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_z_inGap_11_.qasm

100%|██████████| 10/10 [00:46<00:00,  4.61s/it]
100%|██████████| 10/10 [00:44<00:00,  4.47s/it]

,h 21,z 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.078883,0.394417,0.261387,0.128769,0.038052,0.090445,0.256920,0.130692,0.097182,0.243272,...,0.173954,0.078507,0.024435,0.006213,0.179012,0.133568,0.131310,0.142045,0.140618,fail
1,0.091989,0.459946,0.301066,0.150239,0.045386,0.104777,0.277114,0.146965,0.112023,0.276342,...,0.175902,0.087948,0.026939,0.007361,0.197031,0.136181,0.148354,0.156475,0.165031,fail
2,0.093590,0.467952,0.299818,0.154733,0.044336,0.092117,0.230727,0.115604,0.111564,0.264133,...,0.188286,0.087789,0.022572,0.007603,0.191164,0.129315,0.149634,0.133720,0.172738,fail
3,0.098499,0.492493,0.321907,0.159693,0.046924,0.098552,0.257468,0.133759,0.122748,0.293990,...,0.212894,0.097567,0.024834,0.007748,0.217383,0.153964,0.166701,0.148814,0.178402,fail
4,0.085462,0.427309,0.275832,0.138108,0.040923,0.084794,0.199334,0.107829,0.117764,0.278503,...,0.198508,0.091918,0.020196,0.007254,0.185598,0.133078,0.158118,0.121028,0.165134,fail
5,0.055947,0.279735,0.186911,0.095390,0.027732,0.081703,0.234366,0.122403,0.100767,0.265939,...,0.206852,0.086000,0.022052,0.004743,0.175896,0.128527,0.141688,0.128053,0.101913,fail
6,0.084685,0.423426,0.275554,0.138314,0.040274,0.087341,0.227525,0.118397,0.112188,0.269741,...,0.190885,0.090056,0.022648,0.006998,0.200892,0.135275,0.152597,0.134738,0.160927,fail
7,0.084182,0.420909,0.258974,0.136087,0.039751,0.099443,0.235748,0.124447,0.115045,0.256029,...,0.164753,0.080267,0.022688,0.006847,0.188038,0.120390,0.143605,0.140481,0.161850,fail
8,0.095610,0.478052,0.289741,0.150962,0.044417,0.112438,0.269934,0.142731,0.133510,0.292723,...,0.182880,0.095501,0.026941,0.007700,0.228274,0.158070,0.170001,0.164452,0.182983,fail
9,0.091932,0.459659,0.295543,0.150849,0.044036,0.093884,0.241696,0.123857,0.112988,0.268086,...,0.191470,0.087281,0.023791,0.007466,0.185726,0.136879,0.148501,0.141109,0.171124,fail
10,0.063234,0.316170,0.180041,0.094089,0.027568,0.086446,0.194659,0.101171,0.118805,0.250156,...,0.187568,0.089706,0.020980,0.005570,0.190800,0.160628,0.157471,0.129252,0.132828,pass
11,0.065720,0.328601,0.199832,0.096553,0.029175,0.077223,0.200667,0.100529,0.094834,0.206887,...,0.135724,0.070460,0.019340,0.005094,0.160807,0.136080,0.125404,0.120110,0.126263,pass
12,0.048593,0.242963,0.143941,0.073117,0.021998,0.060788,0.138057,0.073322,0.084568,0.185438,...,0.141751,0.064647,0.014301,0.004133,0.139189,0.111358,0.113698,0.089655,0.099587,pass
13,0.071794,0.358972,0.206017,0.098676,0.031681,0.096372,0.219049,0.116568,0.118450,0.236987,...,0.143548,0.081490,0.023000,0.006016,0.182090,0.163606,0.149083,0.144221,0.147905,pass
14,0.086429,0.432143,0.274303,0.139646,0.041170,0.097744,0.258784,0.130921,0.103403,0.242033,...,0.150005,0.080324,0.024584,0.007022,0.147983,0.134833,0.131432,0.139410,0.157450,pass
15,0.080193,0.400966,0.248079,0.122347,0.036851,0.087520,0.207617,0.110589,0.115225,0.256554,...,0.181322,0.089073,0.021811,0.006566,0.183702,0.153008,0.153826,0.132321,0.156299,pass
16,0.072271,0.361357,0.209515,0.102471,0.031000,0.097229,0.235993,0.127582,0.142622,0.310844,...,0.202302,0.106140,0.023963,0.006481,0.206984,0.169310,0.187352,0.147515,0.155658,pass
17,0.060292,0.301460,0.190276,0.097711,0.028636,0.085515,0.222587,0.117148,0.103620,0.243611,...,0.178449,0.079304,0.022059,0.004992,0.203167,0.140521,0.140503,0.133314,0.114043,pass
18,0.048615,0.243077,0.151359,0.079341,0.022846,0.085511,0.240279,0.123654,0.097661,0.235396,...,0.154138,0.073480,0.022852,0.004152,0.174740,0.130281,0.129098,0.136021,0.094869,pass
19,0.049264,0.246321,0.152473,0.075519,0.022205,0.061542,0.163641,0.085766,0.071331,0.176589,...,0.115789,0.054796,0.015236,0.003953,0.134967,0.086582,0.096758,0.092082,0.090701,pass

[[1.1442947  1.1442947  1.16349093 1.13810547 1.13940206 1.1891959
  1.13999808 1.16023598 1.17549621 1.08533188 1.22574876 1.21368897
  1.19149794 1.12858054 1.10515645 1.13629027 1.10790031 1.1712264
  1.15781135 1.12545515 1.16556785 1.1431278 ]]
BARINEL SCORES

,cp 18,swap 10,cp 19,cp 17,z 20,h 21,cp 5,h 0,swap 8,cp 15,...,cp 6,h 16,x 4,cp 7,h 1,h 2,h 13,cp 9,h 3,h 11
sum,0.58891,0.58759,0.585853,0.584191,0.571117,0.571117,0.564373,0.556516,0.542535,0.538729,...,0.532537,0.530764,0.530568,0.527931,0.527481,0.52174,0.519499,0.500252,0.496191,0.488022

custom SCORES

,swap 10,cp 18,cp 19,cp 17,z 20,h 21,cp 5,h 0,swap 8,cp 14,...,x 4,cp 6,cp 12,h 1,cp 7,h 13,h 2,cp 9,h 3,h 11
sum,0.765878,0.75647,0.756262,0.750598,0.734499,0.734499,0.72069,0.715558,0.695609,0.694198,...,0.685922,0.683816,0.681489,0.681185,0.673792,0.672166,0.668539,0.649264,0.639815,0.63757

DSTAR SCORES

,z 20,swap 10,cp 19,cp 12,cp 9,cp 15,x 4,swap 8,h 0,h 2,...,h 3,cp 14,h 11,h 13,h 16,cp 7,h 21,cp 17,cp 6,cp 5
sum,1.399902,0.772263,0.640257,0.594384,0.519539,0.489097,0.323994,0.307011,0.227243,0.200413,...,0.163698,0.144715,0.135,0.116736,0.0825,0.072237,0.069595,0.016478,0.005507,0.000486

ERROR GATE LOCATION:
20
Now evolving the following mutant:  AddGate_rxx_inGap_11_.qasm

100%|██████████| 10/10 [01:02<00:00,  6.28s/it]
100%|██████████| 10/10 [01:01<00:00,  6.11s/it]

,h 21,rxx 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.075651,0.687349,0.247424,0.120505,0.035032,0.106503,0.254261,0.128116,0.135434,0.303622,...,0.208202,0.124510,0.034164,0.008743,0.199962,0.182522,0.196805,0.167250,0.164623,fail
1,0.105597,0.995897,0.242105,0.112310,0.035202,0.124428,0.257808,0.129601,0.162868,0.339006,...,0.240142,0.151803,0.041000,0.011278,0.261241,0.244314,0.249127,0.191054,0.193519,fail
2,0.069373,0.706728,0.333517,0.157123,0.047291,0.119388,0.278745,0.144226,0.148334,0.313185,...,0.179838,0.134989,0.038641,0.010078,0.217687,0.197264,0.214301,0.192485,0.232244,fail
3,0.074395,0.768610,0.309006,0.157598,0.046353,0.127831,0.314373,0.152977,0.135962,0.300273,...,0.199760,0.128958,0.041076,0.009974,0.229828,0.211433,0.203549,0.201338,0.201355,fail
4,0.096629,0.835687,0.298917,0.140789,0.041547,0.125679,0.304244,0.148747,0.143681,0.313330,...,0.220082,0.141004,0.040356,0.010351,0.232520,0.219320,0.214264,0.197351,0.192110,fail
5,0.062232,0.622818,0.342662,0.154961,0.045219,0.106917,0.261298,0.131199,0.144392,0.333333,...,0.224172,0.135780,0.034779,0.009761,0.216089,0.193098,0.216562,0.166700,0.221807,fail
6,0.065204,0.726704,0.277779,0.139435,0.039959,0.102857,0.270478,0.130819,0.109937,0.268762,...,0.169107,0.122701,0.030367,0.007725,0.194857,0.172068,0.168970,0.161023,0.175646,fail
7,0.072243,0.776877,0.220521,0.120073,0.035474,0.105885,0.247839,0.125695,0.118587,0.259574,...,0.156315,0.118093,0.033652,0.008531,0.192614,0.175930,0.172736,0.165018,0.166276,fail
8,0.071004,0.831436,0.271568,0.150596,0.043528,0.156298,0.365184,0.183537,0.159514,0.338411,...,0.193346,0.149732,0.041692,0.010319,0.236565,0.217250,0.225935,0.236085,0.213929,fail
9,0.070044,0.690087,0.227273,0.119489,0.035241,0.124300,0.306819,0.149748,0.116027,0.261420,...,0.158376,0.110949,0.033477,0.008506,0.194315,0.174133,0.166898,0.186197,0.141016,fail
10,0.035705,0.351378,0.099586,0.045498,0.013936,0.065994,0.147064,0.074331,0.075971,0.163494,...,0.116505,0.067602,0.019198,0.004553,0.122537,0.117110,0.112604,0.103666,0.075736,pass
11,0.039459,0.266796,0.181231,0.088737,0.026681,0.074672,0.181012,0.094572,0.085829,0.197808,...,0.128828,0.080860,0.021426,0.005790,0.120033,0.115259,0.125921,0.116212,0.125679,pass
12,0.045987,0.382849,0.179415,0.090031,0.026785,0.082605,0.198928,0.099775,0.085644,0.199957,...,0.130836,0.086263,0.024313,0.005685,0.137723,0.134157,0.127629,0.127164,0.127383,pass
13,0.073406,0.784774,0.324976,0.143055,0.042903,0.125296,0.304713,0.154243,0.134826,0.298817,...,0.196089,0.133063,0.042279,0.010063,0.227172,0.215946,0.205046,0.202516,0.197047,pass
14,0.071179,0.728701,0.271638,0.129889,0.040791,0.123297,0.266248,0.140033,0.151580,0.319929,...,0.219421,0.143113,0.040253,0.010172,0.238089,0.226183,0.229639,0.195215,0.211258,pass
15,0.043450,0.500220,0.127644,0.066737,0.018551,0.072793,0.156859,0.077509,0.070377,0.153050,...,0.108807,0.076766,0.020174,0.005141,0.129649,0.124840,0.109325,0.113117,0.091601,pass
16,0.063922,0.602067,0.136585,0.072583,0.022227,0.081567,0.183174,0.095289,0.109008,0.246673,...,0.195079,0.109332,0.028554,0.007009,0.174767,0.171833,0.168097,0.130333,0.111778,pass
17,0.098812,0.640440,0.282817,0.138550,0.040256,0.134671,0.308752,0.153878,0.152407,0.319402,...,0.216690,0.136139,0.037627,0.010322,0.218692,0.220526,0.212333,0.198237,0.184100,pass
18,0.065168,0.253264,0.291885,0.145193,0.042997,0.105727,0.253876,0.126209,0.128141,0.283916,...,0.187878,0.112278,0.029609,0.008188,0.173236,0.177446,0.183852,0.158159,0.204218,pass
19,0.051491,0.683409,0.270878,0.136062,0.041904,0.113733,0.262311,0.137974,0.139090,0.325509,...,0.248090,0.145254,0.038600,0.009072,0.233605,0.214252,0.221322,0.190926,0.205074,pass

[[1.38511477 1.30315586 1.23670218 1.1479393  1.16811565 1.30238545
  1.27639815 1.28828464 1.1847219  1.11849202 1.20138714 1.14080258
  1.10575625 1.23191195 1.1513136  1.12924582 1.183825   1.20073477
  1.22935691 1.22774091 1.26620791 1.22071576]]
BARINEL SCORES

,rxx 20,cp 18,h 21,cp 19,cp 17,cp 15,cp 5,h 0,cp 14,x 4,...,h 1,h 13,cp 7,cp 12,cp 9,h 2,swap 10,h 3,swap 8,h 11
sum,0.595368,0.565153,0.564322,0.561177,0.560823,0.558364,0.556257,0.553639,0.552522,0.55064,...,0.548375,0.548226,0.547288,0.547149,0.544937,0.54475,0.538649,0.536409,0.527196,0.525969

custom SCORES

,rxx 20,h 21,cp 15,cp 19,cp 14,h 16,cp 18,cp 17,h 0,h 1,...,h 2,h 13,cp 6,cp 7,h 3,cp 12,cp 9,swap 10,swap 8,h 11
sum,0.789332,0.759735,0.736538,0.73468,0.730473,0.729591,0.727344,0.7246,0.722598,0.721964,...,0.711952,0.7106,0.705314,0.704812,0.701268,0.700145,0.695579,0.692272,0.689561,0.683943

DSTAR SCORES

,rxx 20,cp 9,cp 12,cp 15,cp 19,swap 10,x 4,h 2,h 3,swap 8,...,h 11,cp 14,cp 18,h 13,cp 7,h 16,h 21,cp 17,cp 6,cp 5
sum,3.843853,1.158364,0.734414,0.667508,0.631002,0.498507,0.401985,0.352045,0.337058,0.323447,...,0.188718,0.181971,0.170472,0.169759,0.156753,0.131162,0.05489,0.015886,0.013231,0.000901

ERROR GATE LOCATION:
20
Now evolving the following mutant:  AddGate_ry_inGap_2_.qasm

100%|██████████| 10/10 [00:47<00:00,  4.75s/it]
100%|██████████| 10/10 [00:51<00:00,  5.13s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,cp 8,cp 7,cp 6,x 5,h 4,h 3,h 2,ry 1,h 0,pass/fail
0,0.084349,0.254890,0.128379,0.037776,0.113396,0.284406,0.148098,0.137362,0.312918,0.148305,...,0.103519,0.028663,0.007076,0.223978,0.168505,0.181004,0.172541,0.147833,0.161654,fail
1,0.081225,0.261225,0.129298,0.038274,0.086895,0.244518,0.127938,0.112198,0.283083,0.120787,...,0.091695,0.022860,0.006532,0.202305,0.137533,0.156676,0.136018,0.116154,0.150721,fail
2,0.087655,0.287442,0.144397,0.042272,0.114789,0.311518,0.162867,0.131135,0.320650,0.151554,...,0.102818,0.029894,0.007340,0.219411,0.168581,0.173325,0.174443,0.147128,0.163820,fail
3,0.062492,0.201872,0.105417,0.030455,0.093269,0.271288,0.136596,0.106725,0.272222,0.119721,...,0.085404,0.025000,0.005008,0.194444,0.144452,0.147004,0.147670,0.128288,0.112470,fail
4,0.063331,0.191962,0.098674,0.028612,0.096995,0.256266,0.133366,0.121602,0.286328,0.130900,...,0.090675,0.024751,0.005205,0.221351,0.152698,0.162813,0.150492,0.127372,0.125466,fail
5,0.067803,0.212413,0.098447,0.030872,0.083213,0.216338,0.117416,0.111497,0.278589,0.123939,...,0.094002,0.021534,0.005761,0.181598,0.142289,0.157955,0.127146,0.108822,0.129944,fail
6,0.078171,0.235163,0.117793,0.034928,0.112253,0.285993,0.152566,0.140161,0.316482,0.147423,...,0.102015,0.028329,0.006948,0.216368,0.160221,0.180255,0.169724,0.143802,0.160258,fail
7,0.050127,0.149989,0.075342,0.022775,0.095165,0.260203,0.135390,0.098209,0.222884,0.114488,...,0.070519,0.025178,0.004385,0.173560,0.131176,0.126054,0.149024,0.129488,0.097698,fail
8,0.110139,0.354424,0.177701,0.052141,0.124401,0.331390,0.167359,0.154321,0.370010,0.169650,...,0.120840,0.031249,0.009221,0.219391,0.181911,0.203339,0.183825,0.156431,0.208532,fail
9,0.085493,0.258592,0.128541,0.037727,0.119234,0.306582,0.158843,0.133217,0.291869,0.150197,...,0.095552,0.030241,0.007150,0.219436,0.163987,0.169196,0.180172,0.153541,0.165859,fail
10,0.067081,0.213848,0.106408,0.031445,0.085951,0.231602,0.123515,0.104747,0.253388,0.116722,...,0.083424,0.023566,0.005872,0.166878,0.133116,0.140617,0.135425,0.115345,0.129916,pass
11,0.049168,0.156273,0.078636,0.023640,0.066301,0.177810,0.088463,0.072432,0.178604,0.095228,...,0.058916,0.016808,0.004039,0.117476,0.103718,0.098708,0.097165,0.082480,0.090766,pass
12,0.079154,0.236584,0.120106,0.036507,0.099704,0.237710,0.128039,0.110484,0.239080,0.134427,...,0.078174,0.024440,0.006503,0.161455,0.132569,0.137530,0.144874,0.120831,0.151323,pass
13,0.081060,0.234059,0.118353,0.035724,0.104687,0.226561,0.123586,0.140795,0.281356,0.167708,...,0.099821,0.025564,0.007366,0.190781,0.170831,0.176854,0.156367,0.129267,0.172841,pass
14,0.085939,0.278928,0.137609,0.040827,0.082176,0.211566,0.107546,0.098575,0.238527,0.106537,...,0.077085,0.019751,0.006762,0.177937,0.112989,0.132645,0.118373,0.099225,0.157847,pass
15,0.089718,0.277736,0.141571,0.041353,0.094553,0.238371,0.121923,0.113644,0.270332,0.132338,...,0.087749,0.022460,0.007279,0.189595,0.140293,0.151465,0.134586,0.111555,0.170898,pass
16,0.087397,0.271131,0.136474,0.041508,0.097246,0.224594,0.121525,0.128815,0.300815,0.143204,...,0.104108,0.024126,0.007664,0.185530,0.152296,0.173715,0.139600,0.115566,0.170127,pass
17,0.068239,0.216673,0.107262,0.031611,0.071164,0.187224,0.095591,0.088139,0.203359,0.100110,...,0.064970,0.017806,0.005329,0.141265,0.105118,0.114979,0.108249,0.092507,0.126923,pass
18,0.090637,0.266179,0.132672,0.039526,0.093380,0.203117,0.111090,0.127939,0.261823,0.143233,...,0.089380,0.021896,0.007707,0.197458,0.142344,0.161315,0.137339,0.113200,0.184663,pass
19,0.070832,0.210364,0.102218,0.031941,0.082668,0.202013,0.107474,0.106136,0.240518,0.134968,...,0.082568,0.021034,0.005618,0.172440,0.144079,0.144938,0.130204,0.110652,0.135417,pass

[[1.42892419 1.47187605 1.47593826 1.46533048 1.19661012 1.19700264
  1.16185935 1.23810636 1.25213547 1.23205731 1.25516031 1.20137693
  1.21175495 1.2626486  1.16730848 1.42685223 1.08105531 1.17259435
  1.22669409 1.15536612 1.15119059 1.41241381]]
BARINEL SCORES

,cp 16,cp 15,swap 11,ry 1,cp 7,h 2,x 5,swap 9,cp 13,h 17,...,cp 8,h 3,h 14,h 12,cp 20,cp 19,cp 6,cp 18,h 21,h 0
sum,0.563956,0.560658,0.555627,0.554752,0.551787,0.549922,0.549173,0.5458,0.544924,0.542187,...,0.536687,0.53638,0.533087,0.519327,0.504843,0.504754,0.501891,0.501231,0.500507,0.49759

custom SCORES

,cp 16,swap 11,cp 15,cp 13,ry 1,cp 7,swap 9,h 2,cp 8,h 17,...,h 14,x 5,h 4,cp 19,cp 20,cp 18,cp 6,h 21,h 12,h 0
sum,0.732721,0.729977,0.72351,0.715504,0.714408,0.712813,0.711144,0.708763,0.706099,0.704383,...,0.698091,0.697595,0.694474,0.691001,0.690609,0.684849,0.680922,0.679304,0.679287,0.673291

DSTAR SCORES

,cp 13,cp 10,swap 11,cp 16,cp 20,x 5,swap 9,h 3,h 2,h 4,...,h 12,ry 1,h 14,cp 19,h 17,cp 8,h 21,cp 18,cp 7,cp 6
sum,0.700382,0.660856,0.653209,0.631321,0.469053,0.366857,0.338872,0.240336,0.22398,0.21228,...,0.16817,0.166492,0.140067,0.129644,0.099357,0.084603,0.055167,0.012229,0.007014,0.000415

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_rxx_inGap_10_.qasm

100%|██████████| 10/10 [00:50<00:00,  5.06s/it]
100%|██████████| 10/10 [00:50<00:00,  5.08s/it]

,h 21,cp 20,cp 19,cp 18,h 17,rxx 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.085218,0.250236,0.121765,0.037737,0.091946,0.293830,0.189628,0.102960,0.104330,0.236483,...,0.159247,0.082197,0.020074,0.003183,0.195890,0.150154,0.146269,0.124749,0.080874,fail
1,0.083985,0.268652,0.134015,0.038925,0.096322,0.302909,0.243093,0.124718,0.103671,0.258551,...,0.188157,0.085153,0.023930,0.003183,0.190785,0.142589,0.146999,0.142899,0.070189,fail
2,0.084433,0.274796,0.132495,0.040072,0.090212,0.303565,0.237313,0.124855,0.099925,0.266868,...,0.196308,0.085935,0.022821,0.003178,0.204545,0.153037,0.149036,0.136643,0.067724,fail
3,0.103036,0.325419,0.169432,0.048936,0.112982,0.369009,0.281449,0.139708,0.107501,0.263968,...,0.163270,0.084184,0.025709,0.003806,0.198986,0.135249,0.147186,0.153386,0.082265,fail
4,0.090976,0.289211,0.142754,0.042754,0.087306,0.324867,0.200594,0.106089,0.094989,0.245744,...,0.175370,0.085559,0.020498,0.003658,0.145034,0.121184,0.137791,0.117287,0.077066,fail
5,0.073468,0.230557,0.118840,0.035201,0.089773,0.261884,0.231369,0.113515,0.086666,0.217918,...,0.144754,0.069953,0.021018,0.002575,0.174938,0.128677,0.121480,0.127047,0.059525,fail
6,0.105005,0.334919,0.170459,0.049669,0.110544,0.378068,0.269421,0.141272,0.122561,0.301878,...,0.205422,0.100528,0.027573,0.004181,0.227317,0.160348,0.172534,0.161969,0.088663,fail
7,0.095226,0.311510,0.154130,0.045494,0.105087,0.342536,0.263325,0.137844,0.109467,0.274898,...,0.173249,0.089221,0.025795,0.003749,0.191375,0.142458,0.150280,0.151437,0.075190,fail
8,0.073372,0.240944,0.121050,0.034907,0.087117,0.270687,0.247919,0.131029,0.100024,0.261606,...,0.215768,0.089448,0.025513,0.002923,0.184743,0.147420,0.147337,0.147073,0.054916,fail
9,0.089678,0.273845,0.134269,0.040213,0.098643,0.314134,0.242434,0.123692,0.096407,0.229261,...,0.117275,0.072227,0.021501,0.003210,0.187900,0.131727,0.130415,0.134472,0.080550,fail
10,0.086513,0.281020,0.136742,0.041487,0.091762,0.311258,0.236416,0.124059,0.097428,0.258775,...,0.192147,0.086142,0.023226,0.003299,0.209187,0.141295,0.145208,0.138570,0.071544,pass
11,0.054670,0.166253,0.086090,0.024276,0.067687,0.191877,0.146761,0.080264,0.076232,0.176639,...,0.134200,0.058341,0.015951,0.002312,0.150546,0.096312,0.104985,0.096473,0.047968,pass
12,0.045878,0.145105,0.074071,0.021810,0.052649,0.165439,0.139079,0.071496,0.049922,0.121991,...,0.079627,0.038734,0.013242,0.001672,0.098768,0.073712,0.068038,0.079945,0.034980,pass
13,0.085704,0.255685,0.128436,0.038715,0.105214,0.299272,0.226994,0.124637,0.117840,0.265638,...,0.175487,0.091100,0.024743,0.003604,0.181066,0.149042,0.157911,0.145995,0.082981,pass
14,0.068723,0.213757,0.113799,0.031861,0.075639,0.244576,0.160507,0.080900,0.083651,0.202650,...,0.162543,0.070676,0.016367,0.002730,0.157065,0.104327,0.118667,0.097885,0.061371,pass
15,0.063786,0.192380,0.093017,0.028657,0.079782,0.221830,0.180242,0.099336,0.088437,0.210378,...,0.134982,0.071045,0.018527,0.002685,0.140638,0.109337,0.122262,0.109652,0.061104,pass
16,0.033440,0.106475,0.049864,0.015266,0.038128,0.119870,0.096304,0.050645,0.049243,0.122151,...,0.099487,0.044603,0.010188,0.001398,0.090190,0.075579,0.074051,0.060199,0.032312,pass
17,0.067464,0.210336,0.109661,0.032278,0.080130,0.237889,0.179354,0.092710,0.083582,0.206428,...,0.157145,0.069326,0.017859,0.002512,0.144207,0.114773,0.116649,0.106508,0.054529,pass
18,0.053027,0.159596,0.083181,0.024170,0.067558,0.186191,0.150300,0.078667,0.074643,0.166258,...,0.114572,0.058070,0.015628,0.002128,0.113359,0.096268,0.100209,0.093110,0.048233,pass
19,0.103184,0.305095,0.149590,0.045384,0.114957,0.358366,0.242149,0.130257,0.128335,0.287767,...,0.193135,0.097931,0.025616,0.004048,0.229408,0.165969,0.175425,0.158947,0.098098,pass

[[1.18730167 1.19610196 1.21825227 1.19999357 1.16484323 1.19585363
  1.16951552 1.13409122 1.19508543 1.18051276 1.13154011 1.21955462
  1.10062389 1.24088655 1.19052142 1.17616755 1.24264241 1.19545467
  1.13492933 1.19044036 1.1594371  1.2030896 ]]
BARINEL SCORES

,cp 20,cp 15,cp 19,cp 18,rxx 16,swap 10,cp 14,h 21,cp 6,cp 9,...,cp 12,x 4,h 3,h 17,h 11,h 0,cp 7,h 2,h 13,swap 8
sum,0.579034,0.57785,0.577312,0.576625,0.575019,0.571969,0.571767,0.571764,0.563836,0.563569,...,0.558841,0.556658,0.556356,0.556333,0.554912,0.554072,0.551764,0.550503,0.546998,0.54643

custom SCORES

,cp 19,cp 20,cp 18,rxx 16,cp 15,swap 10,h 21,cp 5,cp 14,cp 6,...,x 4,h 0,cp 9,h 17,cp 7,swap 8,h 2,h 3,h 11,h 13
sum,0.75314,0.75218,0.749611,0.746929,0.746801,0.746356,0.741479,0.734545,0.733876,0.729627,...,0.723022,0.720722,0.718638,0.718344,0.715986,0.715944,0.714338,0.714212,0.711888,0.710425

DSTAR SCORES

,rxx 16,cp 20,swap 10,cp 9,cp 12,cp 15,x 4,swap 8,h 2,h 3,...,h 11,cp 14,h 13,h 17,h 21,cp 7,h 0,cp 18,cp 6,cp 5
sum,0.810195,0.651436,0.633499,0.552193,0.544082,0.49255,0.314019,0.264214,0.187827,0.179401,...,0.145586,0.14193,0.09694,0.087323,0.073357,0.066725,0.05127,0.016627,0.005398,0.000113

ERROR GATE LOCATION:
16
Now evolving the following mutant:  AddGate_rx_inGap_15_.qasm

100%|██████████| 10/10 [00:46<00:00,  4.69s/it]
100%|██████████| 10/10 [00:44<00:00,  4.43s/it]

,rx 21,h 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.073129,0.365644,0.232379,0.121504,0.034792,0.077368,0.193313,0.098378,0.102125,0.227735,...,0.154474,0.077757,0.019462,0.006423,0.157887,0.121904,0.132716,0.115502,0.153699,fail
1,0.124226,0.621129,0.385147,0.191304,0.057335,0.113263,0.253583,0.131773,0.143323,0.317109,...,0.214451,0.110685,0.026214,0.010082,0.219791,0.176126,0.189923,0.161050,0.252251,fail
2,0.091572,0.457859,0.298242,0.151672,0.044434,0.106934,0.276126,0.143823,0.116782,0.270555,...,0.178161,0.088177,0.028308,0.007566,0.193348,0.139017,0.149693,0.163397,0.177259,fail
3,0.090008,0.450039,0.289052,0.150185,0.043784,0.115970,0.297530,0.154892,0.132418,0.304701,...,0.207206,0.099934,0.029342,0.007736,0.232078,0.156740,0.173603,0.174838,0.182882,fail
4,0.115750,0.578750,0.359162,0.175622,0.053358,0.108796,0.248404,0.130362,0.130156,0.285097,...,0.191026,0.100022,0.026172,0.009586,0.217331,0.167379,0.173609,0.157008,0.235730,fail
5,0.114407,0.572037,0.361284,0.182049,0.053448,0.124821,0.315015,0.164267,0.153883,0.360906,...,0.246373,0.119828,0.030686,0.009844,0.242496,0.175411,0.206255,0.182347,0.238118,fail
6,0.079299,0.396495,0.257523,0.131245,0.037904,0.090241,0.234161,0.121118,0.107644,0.257378,...,0.166431,0.083565,0.022569,0.006994,0.173207,0.116068,0.142404,0.131203,0.162750,fail
7,0.087903,0.439517,0.280257,0.147138,0.042904,0.100421,0.250640,0.127732,0.111169,0.249797,...,0.177940,0.085140,0.025384,0.007387,0.187020,0.138375,0.144593,0.147503,0.175252,fail
8,0.083825,0.419123,0.273255,0.133440,0.039598,0.100458,0.270004,0.140860,0.115049,0.274665,...,0.182970,0.090223,0.026841,0.006966,0.187391,0.152987,0.153573,0.156453,0.164981,fail
9,0.071291,0.356454,0.239285,0.121299,0.035841,0.089360,0.248756,0.131715,0.105353,0.281646,...,0.183724,0.084651,0.022676,0.006032,0.174031,0.115867,0.143471,0.131726,0.140566,fail
10,0.091574,0.457869,0.281162,0.136768,0.041264,0.102458,0.264026,0.135213,0.127237,0.294193,...,0.213048,0.101578,0.026050,0.007249,0.199343,0.173474,0.175544,0.157799,0.183755,pass
11,0.055894,0.279471,0.171728,0.084939,0.026487,0.084595,0.215870,0.117958,0.102842,0.240263,...,0.171424,0.078967,0.022508,0.004893,0.183707,0.143768,0.139555,0.136478,0.119260,pass
12,0.070484,0.352422,0.215511,0.101470,0.031080,0.080444,0.198152,0.102199,0.092022,0.204035,...,0.129613,0.069239,0.020153,0.005600,0.161654,0.137258,0.124000,0.125285,0.142646,pass
13,0.058786,0.293932,0.192038,0.098477,0.028727,0.081463,0.228066,0.115421,0.087861,0.216769,...,0.152779,0.070288,0.022136,0.004854,0.149398,0.119859,0.118459,0.127268,0.111832,pass
14,0.105474,0.527369,0.330275,0.167863,0.049665,0.123262,0.297965,0.156747,0.155480,0.337295,...,0.200547,0.111568,0.030212,0.008910,0.245124,0.184789,0.199148,0.184624,0.220227,pass
15,0.088688,0.443442,0.283922,0.139087,0.042048,0.094327,0.246298,0.128315,0.116215,0.271992,...,0.175377,0.089585,0.024457,0.006901,0.197533,0.171538,0.158041,0.150027,0.173296,pass
16,0.042752,0.213760,0.135811,0.067952,0.020020,0.063804,0.175266,0.089071,0.063403,0.149835,...,0.091232,0.045317,0.016059,0.003244,0.105095,0.087356,0.081098,0.097616,0.082052,pass
17,0.072517,0.362586,0.227626,0.116317,0.034050,0.100255,0.268548,0.135080,0.115948,0.268150,...,0.202720,0.092938,0.026495,0.006201,0.191531,0.159415,0.155905,0.156370,0.146991,pass
18,0.074432,0.372162,0.219941,0.116438,0.034015,0.094410,0.212633,0.111173,0.121273,0.257046,...,0.188612,0.091136,0.023003,0.006869,0.179070,0.143352,0.156328,0.136884,0.165113,pass
19,0.067147,0.335737,0.217646,0.110507,0.031437,0.075656,0.218449,0.108967,0.096680,0.238903,...,0.174532,0.078914,0.020455,0.005256,0.178864,0.123351,0.134517,0.123376,0.128424,pass

[[1.33373951 1.33373951 1.29435672 1.27073693 1.29307155 1.21464617
  1.2174347  1.22138553 1.26351131 1.27547302 1.30479916 1.13912478
  1.15506837 1.29482307 1.27479555 1.19096493 1.2824773  1.22190089
  1.20644681 1.28121274 1.19884196 1.33927636]]
BARINEL SCORES

,cp 18,cp 5,cp 17,cp 19,rx 21,h 20,h 0,swap 10,cp 12,h 16,...,cp 14,swap 8,h 2,cp 6,cp 15,x 4,h 1,h 3,cp 9,h 11
sum,0.569111,0.567236,0.566868,0.566644,0.561374,0.561374,0.561049,0.557079,0.533073,0.53292,...,0.528443,0.528156,0.527395,0.526706,0.526692,0.525591,0.52148,0.502705,0.502578,0.501682

custom SCORES

,cp 17,cp 19,cp 18,cp 5,h 0,rx 21,h 20,swap 10,cp 12,cp 7,...,h 2,h 16,cp 14,cp 15,x 4,cp 6,h 1,h 11,h 3,cp 9
sum,0.750118,0.750004,0.749909,0.749103,0.748898,0.748556,0.748556,0.715724,0.703053,0.700505,...,0.696321,0.694747,0.689801,0.686995,0.686147,0.683528,0.677772,0.665331,0.654327,0.647705

DSTAR SCORES

,h 20,swap 10,cp 19,cp 12,cp 9,cp 15,x 4,swap 8,h 0,h 2,...,h 3,cp 14,h 11,h 13,h 16,cp 7,rx 21,cp 17,cp 6,cp 5
sum,1.590181,0.753932,0.721274,0.641631,0.583148,0.543219,0.334022,0.309446,0.30919,0.226486,...,0.186228,0.161499,0.15653,0.133883,0.096877,0.081588,0.080867,0.019016,0.006488,0.000614

ERROR GATE LOCATION:
21
Now evolving the following mutant:  AddGate_rxx_inGap_1_.qasm

100%|██████████| 10/10 [00:52<00:00,  5.28s/it]
100%|██████████| 10/10 [00:48<00:00,  4.84s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,cp 8,cp 7,cp 6,x 5,h 4,h 3,h 2,h 1,rxx 0,pass/fail
0,0.066403,0.206255,0.107628,0.031801,0.106185,0.285114,0.146492,0.116653,0.278291,0.138432,...,0.092887,0.027654,0.005638,0.205758,0.159210,0.157052,0.162067,0.126395,0.210130,fail
1,0.103252,0.313744,0.156616,0.047033,0.122209,0.299880,0.155992,0.138063,0.310588,0.160252,...,0.099428,0.028880,0.008473,0.240358,0.167312,0.177771,0.175960,0.200729,0.211193,fail
2,0.072776,0.228714,0.115326,0.033355,0.101248,0.262642,0.138020,0.121550,0.271587,0.128890,...,0.085616,0.025673,0.006139,0.215454,0.146004,0.154911,0.157434,0.143111,0.215383,fail
3,0.078720,0.251272,0.124361,0.036510,0.090044,0.247600,0.125412,0.105797,0.260460,0.120102,...,0.082696,0.022770,0.006330,0.177337,0.133055,0.142230,0.134360,0.145874,0.174894,fail
4,0.081949,0.251863,0.125866,0.037621,0.103547,0.260501,0.136066,0.129118,0.298311,0.146811,...,0.099462,0.026286,0.006956,0.211513,0.160733,0.171951,0.156013,0.157724,0.199625,fail
5,0.116118,0.365383,0.183843,0.054332,0.135851,0.336495,0.176958,0.156202,0.337024,0.181078,...,0.111548,0.034515,0.009738,0.238080,0.185147,0.194128,0.203300,0.222980,0.245461,fail
6,0.101983,0.316911,0.157745,0.046963,0.121369,0.303788,0.159122,0.142490,0.317415,0.165095,...,0.102387,0.029433,0.008470,0.234583,0.171802,0.182414,0.178766,0.198536,0.224631,fail
7,0.067140,0.196071,0.098402,0.030106,0.108342,0.273515,0.142231,0.116979,0.252373,0.154957,...,0.080711,0.026559,0.005384,0.197473,0.162331,0.147003,0.162236,0.131587,0.204496,fail
8,0.080243,0.256566,0.130307,0.038515,0.107705,0.294689,0.148632,0.116368,0.280642,0.145849,...,0.090367,0.027877,0.006273,0.216202,0.162215,0.156349,0.166828,0.145620,0.208613,fail
9,0.072385,0.226053,0.108252,0.033482,0.103954,0.271585,0.141418,0.114192,0.274149,0.145402,...,0.090878,0.026486,0.005887,0.182330,0.158835,0.152993,0.156209,0.134161,0.198797,fail
10,0.093358,0.294993,0.151553,0.043946,0.111579,0.286595,0.144937,0.130032,0.294285,0.154417,...,0.095015,0.026980,0.007464,0.204643,0.161120,0.167288,0.163189,0.176355,0.193183,pass
11,0.035181,0.110826,0.054378,0.016222,0.040963,0.107879,0.058220,0.061548,0.158263,0.071189,...,0.054390,0.011375,0.002963,0.106820,0.086144,0.090670,0.066303,0.066096,0.090959,pass
12,0.054144,0.159727,0.080047,0.023883,0.070491,0.165872,0.091303,0.098366,0.208092,0.111217,...,0.070630,0.017983,0.004793,0.154855,0.119924,0.126011,0.110928,0.113918,0.152086,pass
13,0.054624,0.158291,0.079808,0.023591,0.067985,0.154891,0.082261,0.097735,0.203595,0.111397,...,0.069292,0.016376,0.004706,0.149487,0.117183,0.127256,0.103233,0.115681,0.136842,pass
14,0.090691,0.290166,0.142555,0.043187,0.108696,0.271284,0.144654,0.125931,0.295500,0.141556,...,0.094755,0.026805,0.007525,0.186731,0.148757,0.162382,0.156781,0.169272,0.186012,pass
15,0.065020,0.207232,0.103306,0.030561,0.073573,0.196651,0.099599,0.088671,0.218590,0.102031,...,0.073164,0.019250,0.005207,0.162414,0.120152,0.123513,0.112737,0.117969,0.146753,pass
16,0.099142,0.301820,0.150321,0.044081,0.106253,0.255070,0.129501,0.129802,0.280460,0.147550,...,0.096148,0.024769,0.008253,0.205245,0.150958,0.167351,0.149624,0.194292,0.173377,pass
17,0.050801,0.160154,0.077215,0.023612,0.086941,0.232130,0.124582,0.107747,0.262166,0.119457,...,0.086526,0.023407,0.004507,0.165569,0.139278,0.145087,0.136348,0.097977,0.187512,pass
18,0.058581,0.182085,0.088168,0.026942,0.059105,0.135729,0.071448,0.075187,0.172325,0.098431,...,0.056913,0.013682,0.004767,0.129065,0.101853,0.101225,0.084116,0.113699,0.090542,pass
19,0.079027,0.250876,0.120836,0.036154,0.100275,0.262141,0.140284,0.112569,0.261602,0.138556,...,0.084818,0.026468,0.006603,0.184037,0.149735,0.145475,0.155238,0.150920,0.202440,pass

[[1.38076734 1.39841819 1.4051538  1.39412876 1.23449718 1.1865928
  1.20351723 1.2422499  1.16988088 1.21784997 1.24622741 1.15047404
  1.10239578 1.19177538 1.249957   1.40542153 1.13425117 1.15238561
  1.18601958 1.22975639 1.38779556 1.17264547]]
BARINEL SCORES

,cp 16,cp 15,rxx 0,h 2,cp 7,h 17,x 5,cp 18,cp 19,h 12,...,cp 20,swap 11,cp 10,h 14,cp 13,h 1,cp 6,h 3,cp 8,swap 9
sum,0.578259,0.574997,0.573026,0.571702,0.571434,0.571274,0.562398,0.555235,0.555199,0.554249,...,0.552512,0.552403,0.551712,0.550289,0.550228,0.5497,0.549567,0.546866,0.544925,0.541749

custom SCORES

,cp 19,cp 7,cp 16,cp 18,cp 15,h 17,h 2,cp 20,h 21,cp 6,...,swap 11,h 12,x 5,h 14,h 4,cp 13,cp 10,h 3,cp 8,swap 9
sum,0.750235,0.75,0.749798,0.748752,0.748002,0.747583,0.747465,0.745673,0.7435,0.742661,...,0.724508,0.722998,0.721873,0.721189,0.713195,0.711154,0.710395,0.709014,0.707282,0.691055

DSTAR SCORES

,cp 10,swap 11,cp 13,cp 16,cp 20,x 5,rxx 0,swap 9,h 2,h 3,...,h 12,cp 15,cp 19,h 14,h 17,cp 8,h 21,cp 18,cp 7,cp 6
sum,0.721219,0.674859,0.671737,0.666362,0.563453,0.385491,0.379039,0.307235,0.24318,0.235916,...,0.197465,0.194999,0.154937,0.143375,0.111862,0.081254,0.066216,0.014728,0.00747,0.000477

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_rxx_inGap_15_.qasm

100%|██████████| 10/10 [01:07<00:00,  6.76s/it]
100%|██████████| 10/10 [01:06<00:00,  6.65s/it]

,rxx 21,h 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.440530,0.303335,0.229238,0.115650,0.033632,0.109562,0.258345,0.129346,0.134583,0.302582,...,0.229387,0.150305,0.040979,0.010807,0.273455,0.233818,0.244919,0.206854,0.277299,fail
1,0.503099,0.415515,0.370564,0.184211,0.053586,0.151970,0.346854,0.175028,0.171276,0.359804,...,0.243908,0.172399,0.049782,0.012464,0.319919,0.271304,0.273922,0.263631,0.342427,fail
2,0.436629,0.311246,0.300151,0.142690,0.042951,0.112391,0.312075,0.147844,0.111315,0.278101,...,0.201563,0.134558,0.039569,0.009384,0.246814,0.198470,0.200319,0.201086,0.253651,fail
3,0.442990,0.282455,0.252454,0.109447,0.034445,0.113346,0.260053,0.139887,0.146678,0.316464,...,0.212405,0.149119,0.043328,0.011466,0.288132,0.227980,0.253919,0.222093,0.291282,fail
4,0.334099,0.298088,0.378585,0.186909,0.056159,0.125788,0.333081,0.167133,0.138418,0.361168,...,0.247056,0.142658,0.038986,0.010659,0.298093,0.195667,0.226494,0.211867,0.281079,fail
5,0.440073,0.331329,0.298829,0.139159,0.043373,0.125789,0.303589,0.153562,0.136020,0.296885,...,0.200087,0.144628,0.042039,0.010833,0.277683,0.234789,0.229366,0.236046,0.294765,fail
6,0.403986,0.260917,0.250524,0.116588,0.035123,0.090629,0.234666,0.123382,0.116041,0.292269,...,0.205968,0.132030,0.036584,0.009163,0.251601,0.190312,0.209598,0.175229,0.237984,fail
7,0.477713,0.326778,0.272073,0.134488,0.041138,0.126075,0.302186,0.156586,0.151236,0.358790,...,0.257828,0.164945,0.046371,0.011067,0.295615,0.244602,0.265189,0.229962,0.292115,fail
8,0.392757,0.302467,0.280376,0.152364,0.042289,0.114125,0.269640,0.134146,0.140144,0.324996,...,0.235563,0.143833,0.039994,0.009788,0.274322,0.219881,0.235303,0.191718,0.263391,fail
9,0.528034,0.377980,0.297317,0.167528,0.047452,0.148722,0.334665,0.165296,0.167140,0.362565,...,0.256102,0.176329,0.048506,0.012817,0.330820,0.263154,0.282310,0.254793,0.335159,fail
10,0.238529,0.205756,0.257382,0.121028,0.034301,0.099218,0.247442,0.116985,0.104377,0.226079,...,0.164738,0.108034,0.030595,0.008048,0.223926,0.190957,0.172116,0.170001,0.208389,pass
11,0.319512,0.237263,0.236877,0.109319,0.032170,0.080942,0.200747,0.098911,0.111664,0.259216,...,0.202740,0.120338,0.031359,0.007662,0.214641,0.179602,0.190824,0.144354,0.203859,pass
12,0.174270,0.154179,0.157875,0.069225,0.021890,0.058802,0.145463,0.075751,0.073555,0.173339,...,0.126634,0.071028,0.021979,0.004744,0.134227,0.112640,0.122432,0.100668,0.131626,pass
13,0.384856,0.270542,0.249796,0.115722,0.035741,0.099921,0.241913,0.125722,0.119963,0.270741,...,0.186152,0.123614,0.036317,0.008552,0.227869,0.180015,0.197623,0.167349,0.228907,pass
14,0.347662,0.301484,0.295357,0.153221,0.045406,0.128170,0.302663,0.152253,0.138689,0.296785,...,0.182137,0.137077,0.038494,0.010766,0.272420,0.213552,0.222378,0.226567,0.286534,pass
15,0.250310,0.113859,0.160944,0.080603,0.023564,0.088399,0.250103,0.126026,0.095696,0.240536,...,0.166573,0.106203,0.027983,0.007201,0.221625,0.157202,0.158761,0.166673,0.161222,pass
16,0.232377,0.198685,0.249727,0.124871,0.037353,0.085704,0.208915,0.109886,0.099226,0.241583,...,0.161908,0.099762,0.027433,0.007339,0.210831,0.157862,0.160661,0.152723,0.193741,pass
17,0.339373,0.291364,0.316140,0.162613,0.045450,0.117448,0.287814,0.139878,0.131985,0.300714,...,0.205075,0.133596,0.037574,0.009704,0.264012,0.204583,0.213273,0.195217,0.261354,pass
18,0.264979,0.192876,0.159607,0.085763,0.025603,0.087981,0.193247,0.100499,0.096280,0.208610,...,0.147026,0.099064,0.028651,0.006952,0.184603,0.168060,0.159535,0.161764,0.181505,pass
19,0.254811,0.242602,0.272590,0.126064,0.037186,0.085830,0.216198,0.109187,0.102180,0.242060,...,0.178813,0.100169,0.029980,0.006654,0.204165,0.155876,0.168105,0.142032,0.188517,pass

[[1.20010112 1.29439563 1.29205095 1.28989031 1.30557929 1.24729429
  1.17372468 1.17294124 1.21227464 1.11434141 1.28993762 1.25634384
  1.14688296 1.12595242 1.16711921 1.16820776 1.18184277 1.15815031
  1.18994319 1.16592481 1.20199377 1.19347809]]
BARINEL SCORES

,rxx 21,h 20,h 0,cp 5,cp 7,cp 6,h 2,cp 9,h 1,swap 8,...,cp 12,h 13,h 16,swap 10,cp 14,cp 15,cp 17,cp 18,h 11,cp 19
sum,0.61054,0.592411,0.583777,0.582833,0.578921,0.578597,0.578293,0.574188,0.574063,0.570802,...,0.569484,0.568217,0.566482,0.564824,0.563671,0.562923,0.559498,0.557865,0.556488,0.554273

custom SCORES

,rxx 21,h 20,h 0,cp 5,cp 7,cp 6,h 2,h 1,h 16,swap 10,...,h 3,cp 9,cp 18,h 11,x 4,cp 19,swap 8,cp 14,cp 12,cp 15
sum,0.793717,0.784115,0.757959,0.755037,0.747838,0.747577,0.746855,0.746568,0.743124,0.742228,...,0.739499,0.738819,0.737761,0.735947,0.734531,0.73331,0.731476,0.728959,0.728134,0.728102

DSTAR SCORES

,rxx 21,cp 9,swap 10,cp 12,h 20,cp 15,cp 19,h 0,x 4,h 2,...,h 1,h 11,cp 7,cp 14,cp 18,h 13,h 16,cp 17,cp 6,cp 5
sum,1.511649,1.276843,0.876671,0.849627,0.84406,0.710311,0.694832,0.683404,0.671091,0.498303,...,0.413721,0.224352,0.205653,0.199612,0.18834,0.180262,0.135788,0.017897,0.017613,0.001167

ERROR GATE LOCATION:
21
Now evolving the following mutant:  AddGate_swap_inGap_11_.qasm

100%|██████████| 10/10 [00:57<00:00,  5.79s/it]
100%|██████████| 10/10 [00:57<00:00,  5.75s/it]

,h 21,swap 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.082660,0.401269,0.015616,0.007814,0.002302,0.083653,0.204758,0.100010,0.107238,0.254483,...,0.237604,0.105228,0.029585,0.007238,0.174750,0.166897,0.183566,0.149474,0.109777,fail
1,0.086003,0.359605,0.017894,0.008880,0.002669,0.083432,0.223475,0.111011,0.089066,0.226457,...,0.191848,0.097645,0.029181,0.006183,0.165713,0.151083,0.153999,0.149773,0.118758,fail
2,0.082959,0.359784,0.016060,0.007763,0.002369,0.066243,0.152318,0.082574,0.104838,0.252527,...,0.227839,0.103319,0.028983,0.007358,0.177201,0.168972,0.188296,0.121862,0.125045,fail
3,0.085788,0.505796,0.017308,0.008896,0.002619,0.073963,0.194426,0.092848,0.088490,0.230110,...,0.208715,0.095477,0.024892,0.006205,0.155071,0.148301,0.149461,0.119344,0.074064,fail
4,0.087645,0.453945,0.017780,0.008662,0.002611,0.069873,0.196113,0.097154,0.080202,0.194634,...,0.162558,0.087159,0.028876,0.006146,0.149212,0.147351,0.135480,0.130536,0.103828,fail
5,0.092379,0.410156,0.018851,0.009516,0.002825,0.087536,0.224514,0.103899,0.083271,0.210187,...,0.190940,0.100170,0.027787,0.006786,0.164448,0.150621,0.149549,0.152478,0.114482,fail
6,0.067152,0.387271,0.013520,0.006597,0.001994,0.063154,0.151683,0.074725,0.071131,0.165523,...,0.143235,0.074062,0.020191,0.005517,0.117605,0.118628,0.116761,0.108995,0.066250,fail
7,0.082777,0.445241,0.016356,0.008578,0.002514,0.095266,0.228314,0.111705,0.091026,0.199743,...,0.161246,0.095404,0.026253,0.006590,0.161117,0.160618,0.149998,0.162573,0.106356,fail
8,0.077644,0.501368,0.015547,0.007663,0.002304,0.060659,0.155309,0.080700,0.083379,0.198117,...,0.174528,0.082923,0.026664,0.006004,0.149475,0.148710,0.142609,0.111526,0.088461,fail
9,0.067167,0.358676,0.013730,0.006870,0.001999,0.071065,0.185182,0.094112,0.083487,0.204688,...,0.178850,0.080847,0.024394,0.005491,0.143891,0.132827,0.140360,0.126827,0.086426,fail
10,0.051728,0.288259,0.009932,0.004980,0.001572,0.095190,0.237150,0.117765,0.077054,0.179818,...,0.145773,0.081510,0.023074,0.005151,0.143777,0.151681,0.130148,0.166984,0.099240,pass
11,0.076715,0.350828,0.015864,0.007824,0.002279,0.055921,0.148773,0.077671,0.071256,0.173194,...,0.161285,0.083785,0.024104,0.004652,0.142138,0.130929,0.126482,0.106322,0.094355,pass
12,0.038392,0.284760,0.007378,0.003698,0.001090,0.051619,0.137563,0.069177,0.048230,0.116044,...,0.089632,0.050689,0.014315,0.003002,0.081223,0.085231,0.076119,0.087982,0.043476,pass
13,0.069848,0.380500,0.013663,0.006523,0.002003,0.077726,0.210755,0.104828,0.103947,0.256775,...,0.229763,0.097250,0.029103,0.006699,0.163264,0.154961,0.176987,0.139212,0.103374,pass
14,0.071663,0.463801,0.014016,0.007200,0.002090,0.089424,0.239095,0.113150,0.088929,0.188955,...,0.157453,0.079997,0.026654,0.006111,0.148692,0.146268,0.137201,0.149940,0.078350,pass
15,0.078286,0.398944,0.014927,0.007210,0.002216,0.067172,0.173024,0.085178,0.086708,0.203005,...,0.202850,0.097154,0.026705,0.005993,0.162926,0.165796,0.157110,0.122198,0.106225,pass
16,0.091474,0.334755,0.018211,0.009130,0.002722,0.098514,0.225147,0.118046,0.092180,0.184500,...,0.143983,0.095432,0.029375,0.006696,0.166695,0.169981,0.143930,0.177024,0.107285,pass
17,0.046041,0.179289,0.008720,0.004250,0.001293,0.043671,0.095394,0.049943,0.043965,0.088964,...,0.077466,0.046637,0.014014,0.003538,0.079017,0.085448,0.069474,0.074309,0.038920,pass
18,0.059508,0.267931,0.011817,0.006077,0.001804,0.063638,0.152898,0.074166,0.065594,0.141137,...,0.113408,0.068886,0.020596,0.004619,0.122669,0.121826,0.110469,0.119339,0.093718,pass
19,0.067345,0.323743,0.013291,0.006828,0.002008,0.081472,0.185566,0.098273,0.071669,0.164273,...,0.118886,0.075855,0.019561,0.005278,0.123083,0.128868,0.114056,0.134890,0.074328,pass

[[1.13742522 1.20913848 1.15887574 1.17131446 1.167015   1.26206742
  1.19156129 1.17740734 1.2156768  1.19113993 1.12514799 1.14149677
  1.104636   1.26562401 1.1410116  1.1088649  1.15835021 1.13700955
  1.13099825 1.24692716 1.21924322 1.25869569]]
BARINEL SCORES

,swap 8,swap 20,cp 18,cp 19,cp 17,cp 12,swap 10,h 21,cp 5,h 2,...,h 13,cp 6,x 4,cp 9,h 3,cp 15,cp 14,h 11,h 1,h 16
sum,0.565835,0.561045,0.560427,0.559972,0.559264,0.557369,0.557267,0.555076,0.551095,0.548709,...,0.540633,0.539758,0.538901,0.529449,0.526987,0.514877,0.510916,0.510736,0.510566,0.510309

custom SCORES

,swap 8,swap 20,cp 18,cp 12,cp 17,cp 19,h 2,swap 10,h 21,h 0,...,cp 7,x 4,cp 6,h 3,cp 9,h 16,cp 15,h 1,cp 14,h 11
sum,0.744869,0.730641,0.724535,0.723345,0.722431,0.722206,0.71976,0.716297,0.712915,0.712634,...,0.697472,0.692085,0.689388,0.675993,0.675661,0.67132,0.668254,0.666192,0.661305,0.654399

DSTAR SCORES

,swap 20,cp 9,cp 12,swap 10,cp 15,swap 8,x 4,h 2,h 3,h 1,...,cp 14,cp 7,h 13,h 21,h 16,cp 6,cp 19,cp 18,cp 5,cp 17
sum,1.318365,0.395061,0.390239,0.358849,0.310996,0.308072,0.214309,0.202841,0.196814,0.157643,...,0.082516,0.078918,0.072389,0.061931,0.053131,0.00696,0.002613,0.000656,0.000401,0.000058

ERROR GATE LOCATION:
20
Now evolving the following mutant:  AddGate_ry_inGap_12_.qasm

100%|██████████| 10/10 [01:09<00:00,  6.98s/it]
100%|██████████| 10/10 [01:03<00:00,  6.31s/it]

,h 21,cp 20,cp 19,ry 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.087580,0.267618,0.138978,0.123976,0.050691,0.153907,0.299877,0.178785,0.181188,0.471642,...,0.167875,0.106210,0.031810,0.008156,0.245169,0.226951,0.234765,0.211232,0.198562,fail
1,0.062063,0.186720,0.092436,0.133826,0.040955,0.121140,0.227650,0.153634,0.140942,0.433795,...,0.181774,0.088800,0.023660,0.005624,0.223427,0.208957,0.201294,0.164377,0.144486,fail
2,0.070546,0.218112,0.108181,0.092979,0.042015,0.128104,0.262767,0.157157,0.153581,0.402994,...,0.164295,0.094934,0.027080,0.006291,0.224970,0.192034,0.202122,0.178901,0.155401,fail
3,0.079051,0.235261,0.121650,0.119705,0.048388,0.137071,0.257752,0.166893,0.176027,0.447496,...,0.179014,0.101317,0.026803,0.007339,0.236958,0.216462,0.223813,0.185591,0.185264,fail
4,0.083858,0.258568,0.126996,0.125749,0.050656,0.139161,0.273073,0.177838,0.157391,0.461933,...,0.172806,0.097186,0.029241,0.007558,0.228031,0.214022,0.214985,0.192708,0.182774,fail
5,0.079267,0.244278,0.128272,0.116328,0.051020,0.136696,0.268230,0.174348,0.158283,0.457462,...,0.204004,0.100206,0.027545,0.007284,0.234787,0.209652,0.216891,0.184083,0.175183,fail
6,0.070912,0.221099,0.105746,0.117423,0.048501,0.126148,0.242400,0.168750,0.168663,0.443736,...,0.193902,0.100273,0.025718,0.006582,0.249593,0.217034,0.219119,0.178154,0.165143,fail
7,0.068849,0.198110,0.100490,0.144305,0.045907,0.140129,0.250786,0.173076,0.169085,0.454406,...,0.174876,0.098171,0.027221,0.006739,0.198535,0.225474,0.220116,0.184880,0.167660,fail
8,0.070279,0.211331,0.110821,0.109490,0.047543,0.139941,0.273149,0.171026,0.172195,0.455313,...,0.198963,0.102600,0.028807,0.006317,0.264200,0.220060,0.227062,0.196109,0.162791,fail
9,0.079766,0.251979,0.121004,0.109588,0.045321,0.131698,0.282519,0.175018,0.158064,0.420077,...,0.155724,0.092875,0.027268,0.006803,0.239661,0.201218,0.205152,0.184461,0.171068,fail
10,0.055727,0.181799,0.094792,0.059133,0.034245,0.100062,0.227758,0.126550,0.110220,0.301674,...,0.146754,0.075082,0.022356,0.004909,0.167411,0.136293,0.148145,0.137703,0.113253,pass
11,0.068638,0.221078,0.107742,0.067968,0.043981,0.098258,0.213811,0.141751,0.130375,0.376839,...,0.236803,0.099172,0.021821,0.005785,0.225325,0.165877,0.188968,0.141079,0.135822,pass
12,0.086940,0.265489,0.138726,0.122409,0.050514,0.152952,0.310392,0.184835,0.170248,0.503282,...,0.220572,0.109133,0.030507,0.007898,0.267591,0.228647,0.234808,0.203621,0.193535,pass
13,0.063432,0.200071,0.099996,0.064628,0.037663,0.103947,0.221456,0.133513,0.137489,0.328524,...,0.161418,0.088231,0.022920,0.005794,0.206318,0.159202,0.176897,0.149416,0.138133,pass
14,0.074691,0.229757,0.113194,0.097306,0.043590,0.118259,0.233173,0.152419,0.138053,0.416356,...,0.176379,0.086206,0.024336,0.006762,0.211568,0.181829,0.187505,0.161751,0.161359,pass
15,0.087201,0.262043,0.129328,0.135254,0.047014,0.119666,0.219489,0.153588,0.150693,0.427384,...,0.140541,0.084247,0.022217,0.007834,0.213165,0.201117,0.197927,0.159176,0.197261,pass
16,0.090179,0.291820,0.143058,0.108001,0.053283,0.144119,0.274599,0.164252,0.161566,0.432268,...,0.173019,0.098446,0.029708,0.007790,0.238079,0.209207,0.215023,0.195839,0.186690,pass
17,0.071508,0.223345,0.108609,0.115762,0.040671,0.118707,0.259744,0.168227,0.147083,0.427296,...,0.175672,0.089681,0.023976,0.006378,0.246527,0.200011,0.199030,0.166851,0.160603,pass
18,0.065687,0.204627,0.106078,0.099982,0.046708,0.132538,0.273760,0.172454,0.158247,0.426721,...,0.201215,0.101323,0.028664,0.006431,0.201020,0.197379,0.208250,0.183771,0.148200,pass
19,0.061213,0.194027,0.100341,0.121711,0.048445,0.133894,0.277488,0.181236,0.154298,0.472076,...,0.228608,0.101102,0.028917,0.005843,0.224849,0.216893,0.215306,0.186419,0.139221,pass

[[1.16436664 1.16707205 1.20371348 1.20922382 1.08324003 1.13668629
  1.13667178 1.0538324  1.10790145 1.06014312 1.10462554 1.18503654
  1.07169851 1.13763114 1.08094046 1.15607867 1.18727615 1.12649475
  1.06456744 1.08420716 1.13535331 1.1623163 ]]
BARINEL SCORES

,ry 18,h 11,h 3,h 13,h 16,h 1,h 2,cp 9,h 0,cp 12,...,x 4,cp 17,cp 7,cp 15,cp 5,h 21,cp 19,cp 20,swap 10,swap 8
sum,0.546033,0.538731,0.52922,0.52863,0.525538,0.524657,0.523381,0.520681,0.520451,0.519649,...,0.515777,0.513566,0.513041,0.512285,0.51219,0.509123,0.502767,0.502082,0.497915,0.49073

custom SCORES

,ry 18,h 11,h 13,h 16,h 1,h 0,h 3,cp 6,h 2,cp 5,...,cp 15,cp 12,h 21,cp 14,cp 19,cp 17,cp 7,cp 20,swap 10,swap 8
sum,0.711103,0.687505,0.675048,0.674881,0.673574,0.671683,0.670067,0.668478,0.665244,0.664218,...,0.65786,0.657374,0.657324,0.65443,0.654064,0.652645,0.651683,0.648574,0.645427,0.630298

DSTAR SCORES

,cp 12,h 11,swap 10,cp 9,cp 15,x 4,cp 20,h 2,h 3,h 1,...,cp 14,h 13,h 16,ry 18,cp 19,cp 7,h 21,cp 17,cp 6,cp 5
sum,1.402475,0.727666,0.590845,0.577328,0.55629,0.450798,0.428399,0.391636,0.382034,0.296214,...,0.248574,0.23342,0.163361,0.129559,0.119643,0.088309,0.052751,0.021236,0.007382,0.000469

ERROR GATE LOCATION:
18
Now evolving the following mutant:  AddGate_rzz_inGap_8_.qasm

100%|██████████| 10/10 [00:49<00:00,  4.97s/it]
100%|██████████| 10/10 [00:47<00:00,  4.71s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,rzz 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.105383,0.325083,0.161579,0.048004,0.097100,0.227712,0.115832,0.131511,0.299482,0.150039,...,0.257101,0.105058,0.023654,0.008650,0.196015,0.156516,0.177888,0.140107,0.200090,fail
1,0.082720,0.255022,0.129323,0.037564,0.095124,0.242838,0.123098,0.122243,0.277022,0.135466,...,0.232553,0.092519,0.023873,0.006978,0.195851,0.147392,0.162374,0.141762,0.161443,fail
2,0.066077,0.200372,0.107769,0.031034,0.078321,0.185781,0.098212,0.110448,0.246414,0.110184,...,0.199181,0.079891,0.018592,0.005541,0.177346,0.120614,0.142407,0.114984,0.131044,fail
3,0.085100,0.266879,0.137236,0.040059,0.096566,0.245310,0.127148,0.128189,0.318567,0.128331,...,0.259081,0.103524,0.022801,0.007187,0.226932,0.147838,0.177688,0.136589,0.165537,fail
4,0.068773,0.216184,0.112722,0.031569,0.076038,0.201024,0.099433,0.101659,0.235613,0.101900,...,0.194347,0.079797,0.020144,0.005826,0.161281,0.117208,0.134965,0.117535,0.131272,fail
5,0.096810,0.302724,0.153110,0.044942,0.102686,0.264612,0.133895,0.133836,0.310546,0.150313,...,0.252818,0.102894,0.025591,0.007870,0.219804,0.162892,0.178617,0.153502,0.185119,fail
6,0.075372,0.238498,0.118076,0.034883,0.096996,0.256617,0.130732,0.107672,0.258562,0.125426,...,0.198791,0.081200,0.023764,0.005777,0.194378,0.138104,0.143922,0.143688,0.136657,fail
7,0.078506,0.241621,0.122670,0.036046,0.093777,0.236407,0.123174,0.126752,0.289385,0.131375,...,0.234209,0.095147,0.022913,0.007009,0.194078,0.143961,0.166332,0.137971,0.160600,fail
8,0.101607,0.324684,0.166092,0.048043,0.105975,0.270719,0.134901,0.129465,0.302244,0.137123,...,0.234257,0.098883,0.026143,0.008175,0.202486,0.146542,0.168583,0.152861,0.186331,fail
9,0.079401,0.251968,0.125315,0.037466,0.099010,0.251168,0.130649,0.126736,0.296179,0.134393,...,0.228059,0.093631,0.023520,0.006731,0.210829,0.145025,0.166803,0.144244,0.158279,fail
10,0.097497,0.301554,0.152863,0.045337,0.116612,0.283770,0.145556,0.132612,0.276209,0.167631,...,0.217563,0.092804,0.028720,0.007917,0.202938,0.166866,0.164706,0.172463,0.186049,pass
11,0.068764,0.222165,0.112092,0.032608,0.075142,0.210996,0.110502,0.095560,0.226237,0.104998,...,0.174681,0.074144,0.020517,0.005623,0.162395,0.118157,0.126552,0.120661,0.128675,pass
12,0.067872,0.208556,0.102278,0.030766,0.077158,0.191062,0.094341,0.087610,0.201098,0.125777,...,0.180013,0.069932,0.018758,0.005157,0.172529,0.137138,0.121401,0.115141,0.123655,pass
13,0.066348,0.216098,0.108476,0.032581,0.091488,0.246291,0.128673,0.107206,0.263625,0.128523,...,0.209081,0.085022,0.023996,0.005295,0.191607,0.145092,0.146637,0.142410,0.120757,pass
14,0.069046,0.222283,0.112468,0.033595,0.091465,0.256588,0.130082,0.097360,0.249280,0.121690,...,0.187595,0.077336,0.023212,0.005424,0.183526,0.136291,0.133586,0.135745,0.124343,pass
15,0.038064,0.112861,0.056260,0.016847,0.050087,0.123393,0.065121,0.064615,0.135995,0.086856,...,0.113800,0.046841,0.012759,0.003063,0.121907,0.093096,0.085052,0.080298,0.075637,pass
16,0.037524,0.121351,0.060221,0.017483,0.038108,0.105114,0.052173,0.042290,0.102930,0.064738,...,0.086645,0.035549,0.010519,0.002686,0.081514,0.069748,0.059867,0.061785,0.064222,pass
17,0.087589,0.267338,0.137570,0.040272,0.099291,0.241156,0.126485,0.123745,0.266638,0.143974,...,0.209635,0.088027,0.024561,0.007398,0.191024,0.145918,0.155838,0.146909,0.173457,pass
18,0.064726,0.185500,0.096905,0.029072,0.093717,0.232629,0.122915,0.117720,0.265942,0.140165,...,0.208023,0.085923,0.021971,0.005369,0.199010,0.148144,0.153907,0.136890,0.131651,pass
19,0.075091,0.233432,0.120224,0.035447,0.086133,0.206092,0.102585,0.090329,0.198363,0.121476,...,0.155341,0.065271,0.018969,0.005888,0.168202,0.122326,0.116037,0.116383,0.139274,pass

[[1.25493795 1.23933904 1.24516859 1.23310634 1.12548483 1.13642866
  1.10840383 1.09835539 1.12408451 1.15222357 1.13156397 1.148253
  1.19851372 1.13116364 1.12657258 1.13176824 1.24026574 1.14670051
  1.14222418 1.10286002 1.10972233 1.23789692]]
BARINEL SCORES

,swap 9,rzz 8,cp 13,cp 5,cp 7,h 2,h 0,h 14,cp 19,cp 20,...,swap 11,x 4,h 17,cp 16,cp 6,cp 15,h 1,h 3,cp 10,h 12
sum,0.571157,0.567946,0.564508,0.564433,0.564019,0.561737,0.560444,0.559577,0.557356,0.556415,...,0.547405,0.54165,0.534755,0.531824,0.531053,0.530198,0.529587,0.526453,0.519859,0.519663

custom SCORES

,swap 9,cp 5,h 0,cp 19,h 21,cp 20,rzz 8,cp 18,cp 13,cp 7,...,swap 11,x 4,h 17,cp 16,cp 6,cp 15,h 3,h 1,h 12,cp 10
sum,0.742292,0.739444,0.733887,0.730857,0.729504,0.728811,0.728556,0.724422,0.723146,0.722871,...,0.70226,0.696927,0.68522,0.682919,0.681311,0.677117,0.676785,0.67651,0.669355,0.669091

DSTAR SCORES

,cp 13,cp 20,swap 11,cp 10,cp 16,rzz 8,x 4,swap 9,h 2,h 0,...,cp 19,h 12,h 14,cp 15,h 17,cp 7,h 21,cp 18,cp 6,cp 5
sum,0.65907,0.569038,0.562606,0.537881,0.469106,0.446751,0.335465,0.31722,0.232878,0.231871,...,0.160884,0.151872,0.135484,0.133707,0.081947,0.081117,0.066074,0.014717,0.005229,0.000484

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_p_inGap_11_.qasm

100%|██████████| 10/10 [00:51<00:00,  5.16s/it]
100%|██████████| 10/10 [00:46<00:00,  4.66s/it]

,h 21,p 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.089401,0.447005,0.282881,0.145346,0.042309,0.114568,0.296236,0.154881,0.139230,0.317638,...,0.197836,0.101851,0.029137,0.007557,0.219352,0.163024,0.178186,0.173509,0.171480,fail
1,0.073398,0.366989,0.232519,0.117174,0.035335,0.078325,0.189220,0.096579,0.081203,0.188609,...,0.138629,0.063760,0.018731,0.005826,0.141754,0.107769,0.107289,0.109868,0.132184,fail
2,0.095174,0.475872,0.308417,0.152453,0.045963,0.111779,0.293493,0.152505,0.128968,0.312432,...,0.211540,0.101393,0.028200,0.007799,0.205598,0.154450,0.170251,0.164749,0.175767,fail
3,0.101280,0.506398,0.319256,0.157876,0.048206,0.111923,0.280632,0.149618,0.139519,0.328857,...,0.219657,0.107979,0.027657,0.008492,0.211983,0.170787,0.184555,0.162878,0.192580,fail
4,0.071375,0.356877,0.232462,0.119148,0.034631,0.096686,0.256171,0.129178,0.101724,0.239766,...,0.171203,0.077922,0.024220,0.005867,0.179224,0.128765,0.133382,0.142752,0.130225,fail
5,0.085260,0.426302,0.272818,0.140258,0.041269,0.092509,0.231105,0.116622,0.098819,0.235117,...,0.166907,0.076592,0.022228,0.006639,0.169818,0.130925,0.131209,0.132296,0.153430,fail
6,0.099561,0.497803,0.317099,0.157891,0.047440,0.113908,0.283615,0.149706,0.137929,0.324454,...,0.218888,0.105725,0.027520,0.008415,0.234351,0.161426,0.182725,0.163622,0.192279,fail
7,0.088055,0.440276,0.284009,0.141907,0.041954,0.094912,0.257515,0.131609,0.111596,0.287234,...,0.199172,0.090985,0.023253,0.006881,0.211357,0.133108,0.155162,0.138458,0.158504,fail
8,0.092365,0.461826,0.293310,0.147231,0.044598,0.099682,0.251482,0.133124,0.108930,0.265481,...,0.161083,0.081921,0.023870,0.007272,0.190988,0.134788,0.142136,0.142651,0.169025,fail
9,0.088536,0.442679,0.281183,0.144724,0.042047,0.102946,0.265331,0.136964,0.117319,0.277661,...,0.194049,0.089482,0.025460,0.007161,0.197332,0.147861,0.153658,0.150238,0.164394,fail
10,0.064661,0.323304,0.191980,0.094617,0.028757,0.087718,0.210366,0.110829,0.115313,0.241428,...,0.172429,0.086121,0.022472,0.005615,0.174775,0.154464,0.151176,0.136916,0.133635,pass
11,0.025242,0.126208,0.076070,0.037428,0.011829,0.055954,0.158202,0.082352,0.067786,0.166235,...,0.133015,0.055967,0.015979,0.002224,0.118552,0.098911,0.095316,0.093590,0.050162,pass
12,0.066053,0.330267,0.206759,0.100693,0.030191,0.069697,0.177917,0.092021,0.094583,0.228189,...,0.192782,0.079255,0.018535,0.004979,0.172910,0.141936,0.136129,0.113414,0.121393,pass
13,0.058132,0.290658,0.184002,0.092600,0.027443,0.062730,0.170974,0.087313,0.088418,0.229821,...,0.183633,0.078243,0.016158,0.004847,0.144112,0.113767,0.127907,0.094097,0.107238,pass
14,0.086406,0.432031,0.275790,0.135539,0.040978,0.106233,0.283476,0.144994,0.108340,0.252938,...,0.143997,0.076252,0.025728,0.006531,0.193621,0.140064,0.138119,0.156999,0.157276,pass
15,0.054809,0.274044,0.163668,0.078938,0.024612,0.089921,0.239666,0.124262,0.103505,0.249105,...,0.201313,0.084092,0.023733,0.004242,0.206679,0.154404,0.147832,0.143710,0.102904,pass
16,0.091289,0.456443,0.290658,0.143615,0.044466,0.098600,0.232695,0.125203,0.122030,0.279022,...,0.189621,0.094345,0.023917,0.007655,0.187577,0.152206,0.160077,0.142098,0.173559,pass
17,0.062481,0.312403,0.203617,0.101330,0.030231,0.087409,0.239806,0.123283,0.094503,0.241398,...,0.182723,0.077007,0.022312,0.004895,0.182774,0.133962,0.129761,0.133765,0.111246,pass
18,0.052697,0.263484,0.163029,0.084846,0.024820,0.079477,0.209469,0.106982,0.087440,0.217250,...,0.150474,0.067518,0.019131,0.004305,0.171934,0.114947,0.119589,0.115838,0.100612,pass
19,0.085846,0.429232,0.262774,0.130385,0.039164,0.115076,0.295723,0.153581,0.130845,0.293147,...,0.172328,0.093395,0.027680,0.007009,0.198993,0.157398,0.165691,0.169664,0.167748,pass

[[1.14517072 1.14517072 1.13052804 1.10878173 1.1375939  1.12626898
  1.13727139 1.14659726 1.19734158 1.18411162 1.21627905 1.10744416
  1.21414201 1.16903535 1.20295941 1.16420307 1.18089445 1.19459944
  1.19189316 1.19953634 1.17155091 1.17436288]]
BARINEL SCORES

,cp 18,cp 17,cp 19,cp 5,h 21,p 20,h 0,swap 10,h 16,cp 15,...,cp 12,h 13,h 1,cp 7,h 2,x 4,swap 8,cp 9,h 11,h 3
sum,0.587462,0.583484,0.583184,0.578924,0.57728,0.57728,0.572252,0.565498,0.543962,0.540068,...,0.536586,0.535003,0.532528,0.531191,0.528684,0.528251,0.521749,0.520153,0.518534,0.512673

custom SCORES

,cp 18,cp 5,cp 17,cp 19,h 21,p 20,h 0,swap 10,h 16,cp 12,...,cp 15,cp 6,cp 7,h 1,h 2,x 4,cp 9,h 11,swap 8,h 3
sum,0.750304,0.749836,0.749426,0.748011,0.742552,0.742552,0.740259,0.722062,0.697124,0.69543,...,0.693619,0.693508,0.690942,0.688499,0.687228,0.686013,0.678038,0.676204,0.674235,0.665437

DSTAR SCORES

,p 20,swap 10,cp 19,cp 12,cp 9,cp 15,x 4,swap 8,h 0,h 2,...,h 3,cp 14,h 11,h 13,h 16,cp 7,h 21,cp 17,cp 6,cp 5
sum,1.477127,0.73966,0.663545,0.622099,0.585431,0.555313,0.327478,0.301178,0.239553,0.208162,...,0.180707,0.163631,0.156613,0.123291,0.095346,0.074656,0.07346,0.017429,0.006132,0.000514

ERROR GATE LOCATION:
20
Now evolving the following mutant:  AddGate_cx_inGap_7_.qasm

100%|██████████| 10/10 [00:45<00:00,  4.60s/it]
100%|██████████| 10/10 [00:45<00:00,  4.52s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,swap 12,...,cp 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.089338,0.284744,0.143160,0.042171,0.101619,0.269672,0.138600,0.125579,0.288999,0.222365,...,0.248001,0.082537,0.028771,0.006346,0.165653,0.134911,0.141411,0.167990,0.143806,fail
1,0.060851,0.181601,0.089077,0.027108,0.086431,0.206912,0.111791,0.107107,0.234419,0.182575,...,0.196208,0.066597,0.023094,0.004720,0.128834,0.112918,0.116465,0.137845,0.106500,fail
2,0.096157,0.295521,0.148708,0.043926,0.102963,0.250924,0.129733,0.131366,0.296943,0.229382,...,0.255829,0.083477,0.027791,0.007026,0.169266,0.139801,0.143398,0.163020,0.160328,fail
3,0.055965,0.176581,0.084120,0.025166,0.085887,0.241401,0.124146,0.100033,0.240615,0.193299,...,0.197021,0.067201,0.024774,0.003740,0.152504,0.124043,0.119325,0.150505,0.087856,fail
4,0.074879,0.227698,0.109972,0.034194,0.099685,0.247501,0.129914,0.111801,0.246244,0.182969,...,0.212175,0.072015,0.027318,0.005579,0.164210,0.128440,0.126616,0.161609,0.125829,fail
5,0.051805,0.158870,0.074901,0.022491,0.075656,0.207831,0.111464,0.108408,0.254642,0.209611,...,0.220040,0.071283,0.023340,0.003911,0.153338,0.124099,0.123384,0.137835,0.089197,fail
6,0.060267,0.190260,0.089997,0.026769,0.086368,0.238218,0.124509,0.099896,0.241327,0.179991,...,0.217134,0.066470,0.025354,0.004335,0.168296,0.131603,0.117182,0.149692,0.099238,fail
7,0.056336,0.176644,0.088540,0.026582,0.084738,0.237308,0.121740,0.089678,0.215082,0.164909,...,0.192491,0.061221,0.024197,0.003964,0.138804,0.112440,0.106856,0.143370,0.091155,fail
8,0.071195,0.218498,0.105876,0.031900,0.102636,0.258739,0.135172,0.122946,0.268101,0.196018,...,0.217837,0.077588,0.028194,0.005249,0.177291,0.136683,0.139477,0.170525,0.120631,fail
9,0.101219,0.307393,0.149711,0.044504,0.131976,0.338124,0.177405,0.147467,0.325147,0.220917,...,0.277746,0.091987,0.036233,0.007157,0.213810,0.170868,0.166102,0.216803,0.167507,fail
10,0.056001,0.174897,0.083622,0.025678,0.076600,0.201715,0.107707,0.095699,0.228327,0.181911,...,0.182890,0.063739,0.022509,0.004216,0.153791,0.111026,0.111147,0.131750,0.093272,pass
11,0.059916,0.192500,0.091420,0.027678,0.060720,0.157293,0.084378,0.080788,0.181433,0.116663,...,0.137410,0.050819,0.017763,0.004363,0.126334,0.086065,0.090433,0.104432,0.099272,pass
12,0.085568,0.270948,0.137545,0.040299,0.090211,0.225202,0.112648,0.099518,0.217623,0.134327,...,0.188265,0.061254,0.023401,0.006135,0.155517,0.113349,0.108837,0.140165,0.141022,pass
13,0.075993,0.240276,0.120367,0.035623,0.091706,0.237881,0.124024,0.114689,0.250095,0.159435,...,0.196646,0.070683,0.025587,0.005660,0.167334,0.120467,0.125702,0.151874,0.130239,pass
14,0.073768,0.227275,0.121247,0.034770,0.097920,0.242745,0.125644,0.114552,0.254933,0.188119,...,0.220304,0.070171,0.025510,0.005557,0.145278,0.122394,0.123119,0.150611,0.128028,pass
15,0.087799,0.268501,0.132083,0.039206,0.106880,0.270511,0.141197,0.134922,0.304415,0.248029,...,0.256002,0.087588,0.029714,0.006313,0.174213,0.141623,0.150743,0.173362,0.145933,pass
16,0.058216,0.197820,0.099137,0.028804,0.072761,0.220765,0.110670,0.085150,0.228732,0.201069,...,0.192415,0.063414,0.021976,0.004107,0.139389,0.109332,0.103829,0.124957,0.090935,pass
17,0.065290,0.205811,0.104736,0.031248,0.069122,0.169947,0.088808,0.085887,0.200581,0.153302,...,0.151611,0.054662,0.018520,0.004896,0.125813,0.090666,0.093964,0.108365,0.110645,pass
18,0.096039,0.289321,0.147281,0.044358,0.112358,0.260841,0.136691,0.137775,0.299399,0.220254,...,0.224466,0.082660,0.028731,0.007048,0.186178,0.139292,0.148278,0.173521,0.164253,pass
19,0.100632,0.311821,0.154263,0.046280,0.101931,0.244286,0.125907,0.120542,0.279724,0.217188,...,0.220558,0.076937,0.026246,0.006981,0.176765,0.134531,0.134630,0.157996,0.161654,pass

[[1.40971844 1.3860183  1.3810163  1.37014193 1.37768033 1.35432223
  1.35997107 1.28873263 1.24505001 1.157304   1.29056705 1.3714981
  1.30055737 1.24299956 1.2424291  1.34662078 1.37557005 1.31010547
  1.29858017 1.27749689 1.35570125 1.40520537]]
BARINEL SCORES

,cp 8,h 1,swap 9,cp 15,h 3,cx 10,cp 6,cp 16,h 2,h 11,...,cp 7,h 14,cp 13,x 4,h 21,h 0,cp 5,cp 20,cp 18,cp 19
sum,0.531381,0.530197,0.529955,0.529811,0.529595,0.52864,0.528594,0.528073,0.521987,0.521919,...,0.520548,0.516885,0.516439,0.512787,0.486051,0.485104,0.484843,0.482449,0.478539,0.476351

custom SCORES

,cp 15,cx 10,h 1,cp 16,cp 6,swap 9,h 3,h 17,cp 8,h 11,...,cp 7,x 4,cp 13,swap 12,h 21,h 0,cp 5,cp 20,cp 18,cp 19
sum,0.709943,0.709898,0.709894,0.706868,0.706548,0.702265,0.701525,0.700643,0.696507,0.690311,...,0.682234,0.680739,0.677187,0.672085,0.65735,0.655522,0.651577,0.64962,0.642455,0.640813

DSTAR SCORES

,cx 10,cp 13,cp 16,cp 8,cp 20,swap 9,swap 12,x 4,h 1,h 3,...,h 11,h 0,h 14,cp 19,h 17,cp 7,h 21,cp 18,cp 6,cp 5
sum,1.047355,0.548003,0.509613,0.417099,0.397336,0.333771,0.33235,0.230589,0.224001,0.155017,...,0.14055,0.126138,0.118287,0.105006,0.084344,0.051316,0.047916,0.01019,0.00707,0.000269

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_x_inGap_2_.qasm

100%|██████████| 10/10 [00:52<00:00,  5.28s/it]
100%|██████████| 10/10 [00:49<00:00,  4.92s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,cp 8,cp 7,cp 6,x 5,h 4,h 3,h 2,x 1,h 0,pass/fail
0,0.083573,0.255692,0.130102,0.038318,0.103954,0.254491,0.137328,0.143284,0.325639,0.141475,...,0.103369,0.024555,0.007215,0.232627,0.155927,0.185434,0.154056,0.250804,0.170219,fail
1,0.111457,0.338131,0.166900,0.051157,0.124053,0.296018,0.156507,0.147919,0.336387,0.176061,...,0.111507,0.029804,0.009212,0.225593,0.180128,0.193850,0.179456,0.289659,0.217090,fail
2,0.066814,0.214452,0.110392,0.032399,0.105485,0.284900,0.147920,0.116525,0.276056,0.140807,...,0.095343,0.029625,0.005789,0.178354,0.162787,0.155129,0.168805,0.282250,0.120458,fail
3,0.085386,0.267085,0.139065,0.040371,0.103866,0.266281,0.139140,0.126887,0.299673,0.126551,...,0.098571,0.025947,0.007500,0.186915,0.138866,0.164562,0.148630,0.242825,0.164890,fail
4,0.099375,0.318351,0.159790,0.047251,0.119098,0.314609,0.158130,0.126009,0.292302,0.152834,...,0.093628,0.029299,0.007946,0.206274,0.159773,0.163176,0.174300,0.285490,0.183014,fail
5,0.081555,0.259800,0.129368,0.038597,0.099426,0.261781,0.131801,0.101384,0.247416,0.125155,...,0.079127,0.024347,0.006341,0.168580,0.132376,0.135107,0.143684,0.237501,0.145498,fail
6,0.108719,0.343720,0.171689,0.051099,0.117220,0.292627,0.152713,0.143538,0.333518,0.153224,...,0.107375,0.028169,0.009145,0.233937,0.163046,0.187475,0.168760,0.274564,0.209663,fail
7,0.056058,0.168307,0.084680,0.025449,0.095941,0.265878,0.138337,0.117878,0.293291,0.129998,...,0.092017,0.024803,0.004690,0.216932,0.156511,0.163405,0.150904,0.252680,0.109084,fail
8,0.091931,0.282908,0.139626,0.041387,0.104420,0.263242,0.136074,0.130697,0.299912,0.154534,...,0.098536,0.025569,0.007344,0.235770,0.165768,0.175280,0.156947,0.254149,0.178329,fail
9,0.062538,0.187650,0.096760,0.028774,0.098633,0.256939,0.133539,0.114741,0.265552,0.123382,...,0.085881,0.025025,0.005730,0.172335,0.138248,0.147259,0.146576,0.242365,0.127835,fail
10,0.052081,0.163234,0.081954,0.024035,0.057287,0.142698,0.074415,0.071968,0.165657,0.083947,...,0.054168,0.014091,0.004200,0.119618,0.088546,0.095053,0.086069,0.139230,0.099191,pass
11,0.081080,0.260064,0.129099,0.038451,0.101249,0.275013,0.142414,0.115924,0.277986,0.137028,...,0.087581,0.025878,0.006646,0.194904,0.148426,0.152711,0.153956,0.254980,0.152462,pass
12,0.065199,0.200118,0.101220,0.030651,0.068617,0.152364,0.081517,0.084006,0.189408,0.099024,...,0.060343,0.015271,0.005061,0.167606,0.105162,0.111334,0.097779,0.156399,0.124385,pass
13,0.055785,0.166476,0.086490,0.025546,0.075905,0.195058,0.099570,0.080860,0.172914,0.100924,...,0.056205,0.019006,0.004446,0.127187,0.104079,0.100071,0.113246,0.184730,0.106691,pass
14,0.047164,0.143900,0.069545,0.020522,0.066892,0.184429,0.097386,0.089496,0.216153,0.105807,...,0.072001,0.018252,0.004064,0.166023,0.125621,0.125184,0.110178,0.184019,0.094050,pass
15,0.057677,0.167734,0.084123,0.025835,0.084753,0.211949,0.111351,0.102266,0.245113,0.123997,...,0.081009,0.020476,0.004699,0.185923,0.138144,0.142300,0.126464,0.207279,0.114464,pass
16,0.076969,0.243085,0.124451,0.036767,0.101071,0.256743,0.135143,0.113707,0.264268,0.140133,...,0.087485,0.026775,0.006531,0.186412,0.156974,0.150088,0.156663,0.258357,0.143047,pass
17,0.059281,0.185723,0.091752,0.026970,0.081384,0.230849,0.121838,0.116028,0.287546,0.120812,...,0.095972,0.022013,0.005362,0.182658,0.143077,0.160910,0.128933,0.214384,0.118769,pass
18,0.062988,0.205661,0.103235,0.030026,0.088924,0.245005,0.129589,0.103488,0.243571,0.105568,...,0.078513,0.024998,0.005436,0.161975,0.121444,0.133000,0.142801,0.237501,0.116927,pass
19,0.055550,0.185441,0.095228,0.027024,0.060554,0.172175,0.087576,0.070905,0.177261,0.084170,...,0.059857,0.017095,0.004424,0.127019,0.098079,0.098033,0.097094,0.161878,0.096577,pass

[[1.31527215 1.30389733 1.29247436 1.29576776 1.15710764 1.14122379
  1.10465197 1.16576255 1.13271311 1.23636399 1.1826142  1.12560824
  1.11979034 1.15509338 1.11565497 1.29907171 1.14600611 1.15955026
  1.16030698 1.12715533 1.10883123 1.33505393]]
BARINEL SCORES

,cp 6,h 0,cp 18,h 21,cp 19,cp 20,h 17,h 14,cp 16,cp 13,...,cp 8,h 2,cp 7,x 1,h 12,x 5,h 4,swap 9,cp 10,swap 11
sum,0.582286,0.582273,0.580055,0.579946,0.578693,0.578404,0.576789,0.572201,0.571582,0.57005,...,0.568361,0.567539,0.567185,0.566528,0.563873,0.559564,0.558189,0.556741,0.552202,0.546128

custom SCORES

,h 0,cp 6,h 21,cp 18,cp 20,cp 19,h 17,h 14,h 12,cp 16,...,cp 13,h 2,cp 15,cp 7,x 1,h 4,x 5,swap 9,swap 11,cp 10
sum,0.776614,0.771394,0.770642,0.767959,0.766949,0.76568,0.743641,0.738964,0.738161,0.734657,...,0.731476,0.727466,0.727151,0.725381,0.723575,0.720001,0.71988,0.712599,0.707593,0.707593

DSTAR SCORES

,cp 13,cp 10,cp 16,swap 11,cp 20,x 1,x 5,swap 9,h 3,h 0,...,cp 15,h 12,cp 19,h 14,h 17,cp 8,h 21,cp 18,cp 7,cp 6
sum,0.720546,0.649805,0.629835,0.614035,0.5829,0.568729,0.364269,0.340696,0.247692,0.23679,...,0.184929,0.182665,0.160897,0.147051,0.106557,0.086825,0.067657,0.015154,0.006994,0.0005

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_y_inGap_11_.qasm

100%|██████████| 10/10 [00:52<00:00,  5.30s/it]
100%|██████████| 10/10 [00:47<00:00,  4.75s/it]

,h 21,y 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.088045,0.440227,0.286003,0.148469,0.042701,0.097226,0.253994,0.126976,0.108422,0.261509,...,0.186670,0.085661,0.024065,0.007134,0.185189,0.130749,0.142953,0.140174,0.160809,fail
1,0.081393,0.406964,0.256549,0.130784,0.038028,0.096836,0.250071,0.128561,0.115485,0.274306,...,0.182643,0.088872,0.023973,0.006935,0.168514,0.127794,0.150754,0.138721,0.154946,fail
2,0.086455,0.432277,0.271984,0.137704,0.040326,0.091572,0.225677,0.119357,0.122461,0.282265,...,0.192090,0.094100,0.023284,0.007389,0.197446,0.149257,0.163173,0.137835,0.169569,fail
3,0.089370,0.446849,0.282027,0.142462,0.042650,0.100900,0.236171,0.122720,0.104808,0.226452,...,0.150091,0.075481,0.024566,0.007182,0.159565,0.135801,0.131344,0.144920,0.163920,fail
4,0.098536,0.492681,0.304239,0.152657,0.045089,0.111229,0.276092,0.141201,0.119150,0.270582,...,0.176369,0.087450,0.026701,0.007769,0.209645,0.141772,0.154280,0.160274,0.183699,fail
5,0.063313,0.316565,0.204320,0.104142,0.030286,0.077066,0.197333,0.102974,0.096230,0.231396,...,0.174371,0.076361,0.019518,0.005256,0.163061,0.119856,0.130585,0.116429,0.118573,fail
6,0.104380,0.521899,0.323456,0.164840,0.048672,0.107452,0.258436,0.134826,0.129115,0.281500,...,0.150617,0.090261,0.024739,0.008702,0.203763,0.138358,0.160743,0.150296,0.202871,fail
7,0.094121,0.470604,0.289270,0.146557,0.043864,0.106877,0.250545,0.131410,0.127533,0.282369,...,0.184721,0.092797,0.025132,0.007615,0.225869,0.160713,0.166138,0.154718,0.180231,fail
8,0.077597,0.387987,0.248786,0.126149,0.036818,0.088538,0.228496,0.116690,0.102558,0.242048,...,0.162825,0.078184,0.021904,0.006298,0.183686,0.124628,0.135332,0.130281,0.142511,fail
9,0.080954,0.404769,0.255691,0.129334,0.037751,0.100560,0.271032,0.141993,0.124098,0.302697,...,0.209907,0.098098,0.025906,0.006758,0.191932,0.145139,0.164455,0.151342,0.153974,fail
10,0.101202,0.506010,0.312360,0.153559,0.045099,0.095125,0.223434,0.117435,0.134462,0.301449,...,0.218022,0.105143,0.023499,0.008019,0.237254,0.173065,0.184500,0.146145,0.195548,pass
11,0.084325,0.421625,0.271930,0.135530,0.040855,0.107724,0.292512,0.151787,0.120204,0.292377,...,0.208715,0.096065,0.028820,0.007118,0.182679,0.149330,0.159958,0.163924,0.155372,pass
12,0.094409,0.472047,0.296248,0.151162,0.044640,0.115304,0.281806,0.146685,0.144824,0.340648,...,0.242308,0.114083,0.028367,0.008331,0.226029,0.160423,0.191690,0.165577,0.183278,pass
13,0.066935,0.334673,0.198833,0.099624,0.029709,0.099778,0.241474,0.132556,0.134745,0.292594,...,0.204125,0.098533,0.025581,0.006088,0.216972,0.158498,0.174429,0.156977,0.141593,pass
14,0.071338,0.356692,0.218294,0.108028,0.033254,0.090093,0.215383,0.115749,0.104963,0.226924,...,0.152771,0.077493,0.023048,0.006085,0.162919,0.131581,0.134308,0.138035,0.138111,pass
15,0.078777,0.393883,0.240218,0.121436,0.036162,0.098655,0.237641,0.124726,0.115843,0.252581,...,0.146170,0.080288,0.022993,0.006434,0.191088,0.143901,0.146541,0.143575,0.154820,pass
16,0.078717,0.393584,0.259712,0.123530,0.037352,0.069026,0.192446,0.099671,0.104939,0.269733,...,0.202527,0.091800,0.018512,0.006272,0.175990,0.127865,0.152434,0.109222,0.144292,pass
17,0.051310,0.256551,0.164635,0.079097,0.023555,0.059143,0.154235,0.081397,0.076442,0.188640,...,0.137244,0.062571,0.015252,0.004377,0.138235,0.096981,0.107169,0.089776,0.096490,pass
18,0.047912,0.239559,0.140847,0.071974,0.022176,0.072897,0.166970,0.092713,0.089491,0.197397,...,0.147068,0.067462,0.018349,0.004096,0.152940,0.122613,0.118318,0.110979,0.096589,pass
19,0.089438,0.447189,0.278725,0.136965,0.042149,0.097549,0.245553,0.131815,0.117428,0.271976,...,0.172038,0.089024,0.023753,0.007237,0.184381,0.149463,0.154018,0.143104,0.170856,pass

[[1.20787014 1.20787014 1.18816052 1.19181773 1.19826981 1.13701559
  1.12789681 1.12096134 1.12287805 1.14004667 1.19201355 1.09222864
  1.12202378 1.18571152 1.13111715 1.11353821 1.22496383 1.19591567
  1.16961343 1.10776989 1.12473464 1.243767  ]]
BARINEL SCORES

,cp 18,cp 17,cp 19,swap 10,y 20,h 21,cp 5,h 0,cp 15,h 16,...,h 1,x 4,cp 9,cp 12,h 13,h 11,h 2,cp 7,h 3,swap 8
sum,0.539429,0.533655,0.533358,0.530738,0.530642,0.530642,0.525835,0.524799,0.520896,0.519369,...,0.510327,0.502686,0.502135,0.501967,0.501421,0.496464,0.496095,0.495657,0.492888,0.491575

custom SCORES

,cp 18,cp 17,cp 19,y 20,h 21,h 0,cp 5,swap 10,cp 15,h 16,...,h 1,x 4,cp 12,h 11,cp 9,h 13,swap 8,h 3,cp 7,h 2
sum,0.700154,0.693521,0.691786,0.690878,0.690878,0.687981,0.686867,0.675659,0.667775,0.667001,...,0.653823,0.652979,0.645033,0.644412,0.642987,0.64218,0.637292,0.63701,0.635819,0.633485

DSTAR SCORES

,y 20,swap 10,cp 19,cp 12,cp 9,cp 15,x 4,swap 8,h 0,h 2,...,h 3,h 11,cp 14,h 13,h 16,h 21,cp 7,cp 17,cp 6,cp 5
sum,1.350728,0.654738,0.598544,0.557979,0.533481,0.489081,0.30055,0.264896,0.231812,0.195192,...,0.16542,0.144764,0.143333,0.118652,0.087754,0.069375,0.069116,0.015933,0.005622,0.000501

ERROR GATE LOCATION:
20
Now evolving the following mutant:  AddGate_x_inGap_1_.qasm

100%|██████████| 10/10 [00:55<00:00,  5.55s/it]
100%|██████████| 10/10 [00:55<00:00,  5.55s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,cp 8,cp 7,cp 6,x 5,h 4,h 3,h 2,h 1,x 0,pass/fail
0,0.072688,0.233545,0.121699,0.034820,0.095823,0.256028,0.129468,0.098453,0.233463,0.104397,...,0.073996,0.024066,0.006030,0.153349,0.112698,0.124660,0.137847,0.132456,0.215729,fail
1,0.102639,0.321506,0.162852,0.047035,0.105289,0.256440,0.128612,0.119991,0.265098,0.139626,...,0.089096,0.025297,0.008194,0.200104,0.146171,0.154658,0.150532,0.191522,0.307557,fail
2,0.081487,0.255220,0.127719,0.038246,0.098361,0.241541,0.126396,0.123168,0.293772,0.138467,...,0.096964,0.023397,0.007027,0.200489,0.151468,0.165898,0.138719,0.159043,0.255618,fail
3,0.091338,0.287930,0.137991,0.043046,0.098296,0.233938,0.125036,0.113261,0.266553,0.139860,...,0.087867,0.023814,0.007614,0.191547,0.147549,0.152345,0.141832,0.172432,0.279583,fail
4,0.090172,0.286145,0.140952,0.041447,0.098599,0.250791,0.131155,0.121463,0.286586,0.138044,...,0.094229,0.025271,0.007484,0.197267,0.150909,0.162635,0.148335,0.170117,0.275927,fail
5,0.064258,0.209016,0.109235,0.030775,0.085769,0.235091,0.123848,0.113711,0.293614,0.105292,...,0.095772,0.022819,0.005726,0.203603,0.136325,0.159430,0.132210,0.123107,0.208622,fail
6,0.092001,0.291233,0.141993,0.043060,0.101803,0.244874,0.130046,0.121145,0.268175,0.141609,...,0.090833,0.025590,0.007654,0.195498,0.148237,0.157269,0.152543,0.175028,0.282656,fail
7,0.079447,0.263261,0.133232,0.038999,0.094790,0.255254,0.132019,0.102568,0.252599,0.125407,...,0.082906,0.025050,0.006225,0.180172,0.141190,0.138334,0.144527,0.137778,0.229116,fail
8,0.097696,0.312985,0.161119,0.046049,0.101640,0.265269,0.129391,0.115026,0.267968,0.130791,...,0.088236,0.024916,0.007392,0.212598,0.143529,0.153182,0.149608,0.174434,0.284476,fail
9,0.098082,0.310439,0.158245,0.046237,0.113943,0.287973,0.151307,0.135463,0.305737,0.146024,...,0.100780,0.028936,0.008217,0.220811,0.159291,0.172981,0.169601,0.187243,0.304257,fail
10,0.059728,0.189963,0.097207,0.029322,0.092955,0.255459,0.131267,0.101737,0.243450,0.132760,...,0.078442,0.024532,0.004722,0.178123,0.147449,0.135293,0.147044,0.108628,0.175909,pass
11,0.054055,0.168361,0.084147,0.024743,0.059745,0.149878,0.077256,0.074233,0.172498,0.077512,...,0.056277,0.014723,0.004396,0.126833,0.087122,0.097170,0.088196,0.100830,0.166019,pass
12,0.080638,0.267849,0.131053,0.039439,0.104408,0.285325,0.146374,0.113074,0.282246,0.147952,...,0.091832,0.027485,0.006236,0.194704,0.162299,0.154789,0.160095,0.141566,0.231642,pass
13,0.078182,0.246650,0.131077,0.037704,0.102185,0.267800,0.139004,0.121290,0.279331,0.124924,...,0.086316,0.024575,0.006783,0.170465,0.128330,0.150426,0.146246,0.155870,0.244637,pass
14,0.071528,0.227022,0.110763,0.034117,0.089705,0.228977,0.121856,0.115414,0.278131,0.128349,...,0.092369,0.023289,0.006359,0.166038,0.139592,0.154915,0.135421,0.140887,0.225121,pass
15,0.075279,0.236275,0.117213,0.035205,0.080475,0.202722,0.105622,0.091414,0.210291,0.112963,...,0.070095,0.020393,0.006007,0.155134,0.119486,0.122127,0.120559,0.139018,0.225113,pass
16,0.076937,0.238656,0.118725,0.036213,0.078676,0.184418,0.096203,0.091975,0.201021,0.129226,...,0.068444,0.018864,0.006005,0.141739,0.127054,0.119570,0.115563,0.143154,0.226462,pass
17,0.064052,0.209722,0.107953,0.031715,0.070627,0.179217,0.091795,0.078911,0.185626,0.087732,...,0.057805,0.016743,0.005118,0.133679,0.092024,0.100786,0.099724,0.118050,0.189141,pass
18,0.045376,0.142272,0.069095,0.021028,0.062501,0.159336,0.086142,0.078992,0.182608,0.087629,...,0.059418,0.016013,0.003950,0.132094,0.095861,0.105233,0.095281,0.091981,0.146130,pass
19,0.051881,0.158645,0.078629,0.023359,0.073941,0.188757,0.096355,0.084721,0.193586,0.106357,...,0.064297,0.018598,0.004201,0.138236,0.115327,0.112394,0.112034,0.098211,0.158156,pass

[[1.18002115 1.16013443 1.16736303 1.14800043 1.14594412 1.1394951
  1.1574203  1.16352594 1.11845672 1.11510065 1.16954901 1.10209357
  1.25497096 1.11893408 1.1613485  1.14824053 1.1292142  1.10821117
  1.12223814 1.15709163 1.17993186 1.16342796]]
BARINEL SCORES

,swap 11,cp 19,cp 6,x 0,cp 20,h 21,h 1,cp 18,swap 9,x 5,...,cp 13,h 14,h 17,cp 7,cp 16,h 2,cp 15,cp 10,h 4,h 12
sum,0.57638,0.571526,0.570961,0.570729,0.57061,0.569447,0.56727,0.567031,0.560066,0.559899,...,0.550861,0.550209,0.549486,0.548354,0.545939,0.545718,0.544892,0.544639,0.542012,0.535607

custom SCORES

,swap 11,cp 19,h 21,x 0,cp 20,swap 9,cp 6,h 1,cp 18,x 5,...,cp 7,h 17,h 3,cp 13,h 2,cp 15,cp 16,cp 10,h 4,h 12
sum,0.744906,0.73832,0.737436,0.736729,0.736106,0.735783,0.734861,0.734605,0.729769,0.717961,...,0.707562,0.706906,0.706434,0.704889,0.70358,0.702559,0.701462,0.694699,0.692178,0.684921

DSTAR SCORES

,swap 11,cp 20,cp 13,cp 10,x 0,cp 16,x 5,swap 9,h 1,h 3,...,cp 19,cp 15,h 12,h 14,h 17,cp 8,h 21,cp 18,cp 7,cp 6
sum,0.753742,0.635476,0.611048,0.607379,0.582926,0.527747,0.331431,0.315117,0.234437,0.211139,...,0.176186,0.154075,0.153999,0.123768,0.091413,0.075636,0.070988,0.016277,0.006083,0.000509

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_swap_inGap_10_.qasm

100%|██████████| 10/10 [00:55<00:00,  5.56s/it]
100%|██████████| 10/10 [00:48<00:00,  4.83s/it]

,h 21,cp 20,cp 19,cp 18,h 17,swap 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.082460,0.262980,0.131560,0.039585,0.099205,0.238199,0.308571,0.157820,0.111131,0.258611,...,0.140134,0.071881,0.026086,0.004505,0.165102,0.123797,0.125308,0.156653,0.042508,fail
1,0.068274,0.220092,0.110564,0.032442,0.090600,0.258396,0.264056,0.130209,0.108980,0.264907,...,0.156691,0.075960,0.021553,0.004518,0.156246,0.114455,0.128567,0.129593,0.038829,fail
2,0.105533,0.339937,0.174907,0.050438,0.110355,0.294702,0.408569,0.198024,0.117090,0.291602,...,0.169427,0.077420,0.031469,0.004611,0.204424,0.135093,0.135591,0.192222,0.042624,fail
3,0.075279,0.232160,0.116403,0.034260,0.100858,0.275019,0.270751,0.137226,0.105858,0.245576,...,0.133798,0.069746,0.022967,0.004540,0.156725,0.112320,0.120151,0.141395,0.038051,fail
4,0.082862,0.266088,0.131135,0.039184,0.088181,0.224388,0.309588,0.162467,0.098203,0.232785,...,0.113486,0.060991,0.025492,0.003644,0.150320,0.110558,0.108309,0.156045,0.036196,fail
5,0.083543,0.268112,0.137540,0.040831,0.104694,0.257083,0.322410,0.164013,0.129068,0.316277,...,0.183994,0.087982,0.026346,0.005075,0.188060,0.130633,0.150151,0.158621,0.045600,fail
6,0.086302,0.271530,0.132560,0.039460,0.103177,0.282916,0.315939,0.158149,0.111741,0.261271,...,0.160432,0.077377,0.027357,0.004413,0.196398,0.150889,0.133348,0.167400,0.042756,fail
7,0.064900,0.216577,0.107564,0.031826,0.090063,0.232274,0.254866,0.131850,0.100008,0.244217,...,0.127803,0.067111,0.021092,0.004211,0.158390,0.106574,0.115930,0.125262,0.039480,fail
8,0.080922,0.251014,0.124322,0.037083,0.091070,0.233235,0.294134,0.148234,0.106479,0.247209,...,0.138014,0.070432,0.025027,0.004036,0.176237,0.124448,0.123777,0.154343,0.039211,fail
9,0.086862,0.273226,0.132220,0.039829,0.091089,0.271625,0.310532,0.159667,0.110586,0.267539,...,0.163523,0.078432,0.027582,0.004228,0.172971,0.137710,0.132982,0.164363,0.036800,fail
10,0.107524,0.338364,0.173548,0.051741,0.118040,0.278721,0.408828,0.203992,0.145312,0.349014,...,0.213406,0.099415,0.033833,0.005474,0.214043,0.170068,0.171253,0.203713,0.052946,pass
11,0.078875,0.255712,0.129342,0.038618,0.077507,0.194533,0.301460,0.149450,0.086688,0.225525,...,0.133279,0.059900,0.024115,0.003452,0.153982,0.113292,0.103300,0.144159,0.032636,pass
12,0.069696,0.215691,0.108624,0.032121,0.093807,0.228687,0.256446,0.134798,0.119123,0.267249,...,0.140947,0.076542,0.022708,0.004309,0.175409,0.124148,0.136084,0.138449,0.042368,pass
13,0.071796,0.231322,0.112080,0.033952,0.080676,0.248407,0.274808,0.138428,0.107104,0.259028,...,0.158613,0.075641,0.022909,0.004059,0.168448,0.137946,0.131097,0.140059,0.039280,pass
14,0.084757,0.251743,0.120910,0.038084,0.094292,0.181697,0.278750,0.150643,0.120323,0.250716,...,0.140915,0.075630,0.026501,0.004258,0.181467,0.145044,0.137099,0.165678,0.044913,pass
15,0.050200,0.145352,0.071471,0.020938,0.072881,0.203876,0.171634,0.088403,0.093235,0.215535,...,0.133418,0.065044,0.016700,0.003321,0.151957,0.113590,0.112612,0.104350,0.030151,pass
16,0.087932,0.272852,0.141482,0.041425,0.102505,0.256766,0.330530,0.168242,0.132233,0.305388,...,0.159466,0.087238,0.028153,0.004921,0.179785,0.131378,0.148410,0.168743,0.047539,pass
17,0.059472,0.181805,0.091968,0.027610,0.088876,0.276007,0.227896,0.112745,0.104525,0.247334,...,0.144994,0.070070,0.018462,0.004341,0.154880,0.117501,0.122488,0.117772,0.037604,pass
18,0.055623,0.165681,0.085317,0.025700,0.089054,0.237604,0.205011,0.104524,0.100830,0.226885,...,0.136773,0.067700,0.017961,0.004076,0.162425,0.113342,0.118298,0.112539,0.037006,pass
19,0.071612,0.219227,0.110281,0.031627,0.084399,0.220366,0.258559,0.126348,0.102986,0.235608,...,0.128876,0.067744,0.022142,0.004103,0.147969,0.104445,0.116491,0.136363,0.035375,pass

[[1.29181057 1.30658674 1.34670732 1.31029352 1.13850838 1.14766467
  1.33544677 1.279509   1.17426019 1.20257809 1.22022438 1.15648689
  1.24157775 1.23710193 1.19324953 1.23422744 1.15913204 1.18515226
  1.21052043 1.17847603 1.24343483 1.13418435]]
BARINEL SCORES

,cp 20,cp 19,cp 15,cp 18,cp 14,h 21,swap 10,swap 16,cp 6,h 1,...,x 4,cp 12,cp 9,h 0,swap 8,cp 7,h 13,h 2,h 3,h 11
sum,0.533197,0.531457,0.529922,0.529668,0.529072,0.525556,0.525037,0.524637,0.521994,0.519155,...,0.505052,0.504577,0.501988,0.501395,0.499431,0.497439,0.497012,0.495524,0.495178,0.49388

custom SCORES

,cp 19,cp 20,cp 15,cp 18,cp 14,h 21,cp 6,h 1,swap 10,swap 16,...,cp 12,cp 5,x 4,swap 8,cp 7,h 3,h 11,h 0,h 13,h 2
sum,0.710386,0.707364,0.706842,0.703173,0.698311,0.695286,0.683059,0.680538,0.676837,0.675164,...,0.656275,0.655866,0.654693,0.653893,0.645831,0.645034,0.644541,0.643563,0.642917,0.641515

DSTAR SCORES

,cp 15,cp 20,cp 12,swap 16,swap 10,cp 9,x 4,cp 14,h 1,swap 8,...,h 2,h 3,h 13,h 17,h 21,cp 7,h 0,cp 18,cp 6,cp 5
sum,0.736203,0.551316,0.549731,0.534921,0.447279,0.434928,0.254499,0.210524,0.209048,0.192509,...,0.143697,0.137853,0.108718,0.086179,0.062155,0.050597,0.015543,0.014328,0.006353,0.000191

ERROR GATE LOCATION:
16
Now evolving the following mutant:  AddGate_rxx_inGap_13_.qasm

100%|██████████| 10/10 [01:19<00:00,  7.99s/it]
100%|██████████| 10/10 [01:10<00:00,  7.05s/it]

,h 21,rxx 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.081599,0.935037,0.511978,0.180133,0.046933,0.353895,0.345776,0.163349,0.340322,0.340793,...,0.128041,0.104378,0.028528,0.007672,0.242881,0.160552,0.237794,0.202606,0.207698,fail
1,0.069420,0.861432,0.448362,0.159469,0.038378,0.327683,0.331049,0.141552,0.305035,0.275769,...,0.096020,0.085814,0.024644,0.005884,0.232774,0.154901,0.210159,0.185092,0.175719,fail
2,0.067074,0.873251,0.482261,0.164913,0.040776,0.316228,0.301517,0.137912,0.299523,0.280424,...,0.110414,0.090003,0.024711,0.006134,0.222601,0.155333,0.207053,0.177944,0.175125,fail
3,0.064872,0.790476,0.439008,0.153405,0.038482,0.304287,0.320364,0.155167,0.296947,0.316782,...,0.113867,0.096090,0.026721,0.006331,0.216214,0.145358,0.211857,0.184972,0.171262,fail
4,0.076670,0.852487,0.477942,0.175086,0.041825,0.334238,0.330055,0.156994,0.326200,0.331576,...,0.122695,0.105386,0.028356,0.007529,0.231255,0.168531,0.233165,0.198739,0.201778,fail
5,0.091662,0.740788,0.474210,0.195341,0.049706,0.318616,0.367438,0.164729,0.304762,0.322230,...,0.130691,0.105554,0.030818,0.008304,0.238928,0.174538,0.229950,0.210304,0.214483,fail
6,0.081107,1.030409,0.526606,0.177439,0.046058,0.390182,0.368549,0.165381,0.369286,0.334445,...,0.126807,0.108872,0.030146,0.007537,0.255255,0.179960,0.254301,0.217288,0.212138,fail
7,0.081749,0.972143,0.545870,0.186019,0.045873,0.366059,0.383926,0.178104,0.353764,0.359939,...,0.136202,0.114726,0.032067,0.007630,0.242772,0.184412,0.252379,0.222000,0.209418,fail
8,0.072372,0.828645,0.489581,0.176831,0.041853,0.312652,0.345181,0.153697,0.304455,0.314514,...,0.122832,0.095215,0.026488,0.006559,0.253334,0.150663,0.217677,0.189697,0.182081,fail
9,0.099025,0.887524,0.578262,0.213695,0.052277,0.349862,0.361762,0.170394,0.347734,0.372185,...,0.142370,0.118637,0.031046,0.008961,0.260715,0.181944,0.256852,0.215828,0.244448,fail
10,0.080000,0.903264,0.522134,0.177283,0.043635,0.340730,0.346703,0.147529,0.325493,0.298588,...,0.113797,0.101633,0.028043,0.007297,0.224925,0.179798,0.227575,0.197268,0.200344,pass
11,0.053354,0.804754,0.431554,0.142535,0.029818,0.286145,0.272495,0.122695,0.271282,0.252612,...,0.091745,0.075677,0.020829,0.004466,0.219756,0.131377,0.183368,0.157625,0.143875,pass
12,0.057946,0.947619,0.534307,0.170371,0.030043,0.325262,0.312924,0.133924,0.306332,0.273873,...,0.090997,0.086134,0.023651,0.004633,0.226738,0.162295,0.205574,0.177332,0.158710,pass
13,0.084441,0.933761,0.611682,0.219720,0.043563,0.344829,0.354844,0.143846,0.330720,0.303950,...,0.119512,0.102103,0.027157,0.007342,0.256496,0.184922,0.233680,0.196224,0.213780,pass
14,0.042227,0.386831,0.270953,0.102760,0.023156,0.164119,0.186557,0.083688,0.156642,0.162041,...,0.070572,0.051634,0.015347,0.003604,0.142846,0.092098,0.117534,0.107292,0.101726,pass
15,0.051747,0.420701,0.231747,0.083502,0.029971,0.178349,0.208667,0.091209,0.170639,0.172836,...,0.067822,0.057121,0.016845,0.004823,0.116337,0.099880,0.124904,0.114206,0.115757,pass
16,0.055858,0.526899,0.333246,0.119436,0.029372,0.214034,0.227233,0.106848,0.212426,0.223258,...,0.099208,0.070435,0.019652,0.004991,0.179135,0.105923,0.154906,0.137155,0.135444,pass
17,0.075484,0.604073,0.366652,0.155982,0.042371,0.269961,0.318088,0.143843,0.249382,0.264940,...,0.101431,0.081852,0.024999,0.006570,0.204290,0.137618,0.185760,0.175341,0.170379,pass
18,0.052602,0.799233,0.405281,0.132529,0.030513,0.288017,0.269909,0.127869,0.267983,0.246248,...,0.096588,0.076293,0.022776,0.004592,0.200738,0.138957,0.178701,0.163463,0.137377,pass
19,0.069276,0.691461,0.426027,0.163490,0.036593,0.282932,0.299936,0.136126,0.273826,0.276316,...,0.099228,0.087337,0.024196,0.006260,0.220175,0.161121,0.201028,0.174916,0.178272,pass

[[1.26058315 1.17463181 1.16255131 1.19896632 1.1823028  1.15653966
  1.11101925 1.1220713  1.13695481 1.14565721 1.1747125  1.12182289
  1.13120625 1.15753512 1.1578033  1.13100299 1.23536347 1.08779384
  1.11346818 1.11134075 1.10752557 1.22582573]]
BARINEL SCORES

,cp 5,cp 12,cp 17,cp 7,swap 8,cp 14,h 0,swap 10,h 2,cp 6,...,h 1,h 16,rxx 20,cp 15,cp 18,h 11,x 4,cp 19,h 3,cp 9
sum,0.570658,0.567618,0.566005,0.564592,0.563975,0.561897,0.561762,0.560512,0.560394,0.559198,...,0.55598,0.555975,0.555526,0.552636,0.54842,0.546395,0.54618,0.546142,0.542981,0.538754

custom SCORES

,cp 5,h 0,h 21,cp 17,cp 12,cp 7,swap 8,cp 14,rxx 20,swap 10,...,h 16,h 2,cp 18,h 1,h 11,cp 15,cp 19,x 4,h 3,cp 9
sum,0.746901,0.733918,0.733492,0.733303,0.730192,0.728014,0.72718,0.719519,0.71866,0.717711,...,0.716727,0.716091,0.712804,0.70992,0.70686,0.706133,0.704872,0.694713,0.69413,0.691114

DSTAR SCORES

,rxx 20,cp 19,cp 15,h 16,cp 12,h 13,swap 10,cp 9,x 4,h 2,...,cp 18,h 3,cp 14,h 11,swap 8,cp 7,h 21,cp 17,cp 6,cp 5
sum,4.521603,1.750545,0.933105,0.896607,0.846017,0.839627,0.794166,0.721674,0.479034,0.452177,...,0.277015,0.240739,0.224199,0.167844,0.138139,0.097307,0.05809,0.01891,0.007863,0.000523

ERROR GATE LOCATION:
20
Now evolving the following mutant:  AddGate_ry_inGap_14_.qasm

100%|██████████| 10/10 [00:48<00:00,  4.86s/it]
100%|██████████| 10/10 [00:45<00:00,  4.55s/it]

,h 21,ry 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.075493,0.519506,0.234077,0.116561,0.035177,0.108503,0.275131,0.142335,0.118567,0.277961,...,0.172552,0.086444,0.025667,0.006476,0.193193,0.144875,0.151680,0.153342,0.147104,fail
1,0.067232,0.397158,0.208240,0.108526,0.031080,0.091088,0.230125,0.119995,0.110553,0.248973,...,0.168984,0.079987,0.022725,0.005685,0.171699,0.132841,0.140212,0.137378,0.131877,fail
2,0.078760,0.431616,0.237994,0.118613,0.036096,0.099827,0.241243,0.127004,0.117800,0.273110,...,0.186431,0.091318,0.023832,0.006686,0.179604,0.147411,0.156291,0.142126,0.154483,fail
3,0.086746,0.488704,0.270336,0.137750,0.040267,0.113998,0.298283,0.151217,0.129722,0.294789,...,0.188306,0.094980,0.027437,0.007199,0.213348,0.154113,0.166942,0.165215,0.168372,fail
4,0.090268,0.490144,0.268636,0.134126,0.039735,0.116727,0.284159,0.148763,0.141752,0.304199,...,0.205600,0.105637,0.029380,0.007857,0.211573,0.175289,0.181565,0.173262,0.181402,fail
5,0.068077,0.590813,0.202903,0.106031,0.031856,0.112717,0.282622,0.146789,0.117193,0.265997,...,0.182930,0.086526,0.028189,0.005897,0.197224,0.151885,0.149827,0.166003,0.132279,fail
6,0.072057,0.525874,0.225222,0.117348,0.033585,0.111384,0.296502,0.155042,0.140052,0.325132,...,0.214509,0.105325,0.029891,0.006362,0.217892,0.170684,0.183509,0.174290,0.142281,fail
7,0.083596,0.551631,0.264859,0.136582,0.039874,0.119650,0.314359,0.162616,0.129992,0.297462,...,0.198573,0.097697,0.031494,0.007282,0.208528,0.154611,0.165599,0.180853,0.159193,fail
8,0.077117,0.428423,0.243112,0.121969,0.036080,0.101861,0.276106,0.140803,0.107909,0.248016,...,0.150562,0.078030,0.025672,0.006142,0.198216,0.133846,0.139641,0.155292,0.143959,fail
9,0.088579,0.443252,0.275341,0.137017,0.040537,0.108863,0.281567,0.143638,0.117954,0.276734,...,0.184882,0.088568,0.027056,0.007115,0.224633,0.148184,0.156253,0.161546,0.165477,fail
10,0.060738,0.335935,0.191205,0.095341,0.028646,0.081413,0.216097,0.113202,0.102868,0.242548,...,0.184102,0.081669,0.021971,0.005113,0.187388,0.142077,0.142219,0.130628,0.120027,pass
11,0.062179,0.390846,0.186562,0.095817,0.028205,0.086154,0.224100,0.113296,0.093046,0.209676,...,0.133431,0.068912,0.021248,0.005053,0.142200,0.121569,0.119602,0.124897,0.116403,pass
12,0.076179,0.347621,0.237845,0.118186,0.035438,0.090013,0.219650,0.117135,0.112786,0.254542,...,0.186426,0.088226,0.023698,0.006564,0.183944,0.144048,0.149910,0.138176,0.146912,pass
13,0.040261,0.200814,0.131174,0.062016,0.018810,0.051817,0.149090,0.076374,0.056938,0.141033,...,0.095415,0.046300,0.013662,0.003323,0.096744,0.080373,0.076894,0.079825,0.074356,pass
14,0.046385,0.310331,0.136831,0.069765,0.020894,0.068802,0.189562,0.098393,0.086172,0.218072,...,0.165008,0.070788,0.017115,0.003618,0.155295,0.118618,0.121298,0.104649,0.085905,pass
15,0.087970,0.364634,0.273332,0.137638,0.041180,0.098094,0.253570,0.127344,0.107617,0.257790,...,0.175786,0.084174,0.024090,0.006925,0.173076,0.142575,0.144798,0.141457,0.161641,pass
16,0.084986,0.356515,0.269308,0.132134,0.040617,0.095591,0.235345,0.127736,0.112312,0.253934,...,0.143836,0.080465,0.023561,0.006785,0.199423,0.151004,0.144993,0.144148,0.163381,pass
17,0.090787,0.293807,0.278461,0.135854,0.041681,0.092650,0.207896,0.115582,0.129190,0.277516,...,0.182114,0.095988,0.023421,0.007878,0.186316,0.162797,0.167697,0.140715,0.181931,pass
18,0.069787,0.422048,0.204542,0.103337,0.030296,0.095236,0.236363,0.118661,0.109175,0.228466,...,0.141393,0.076666,0.023375,0.005705,0.171055,0.136710,0.137226,0.140725,0.135801,pass
19,0.059496,0.321858,0.182441,0.090100,0.025923,0.079414,0.213845,0.111490,0.102166,0.241533,...,0.180014,0.083050,0.021346,0.005205,0.164320,0.127313,0.138473,0.124318,0.118000,pass

[[1.1456428  1.21388657 1.13275481 1.1158183  1.11276491 1.10315204
  1.13074731 1.13069007 1.15105543 1.15607771 1.19647478 1.1510986
  1.16380638 1.15742353 1.15511999 1.16068419 1.17787148 1.11429904
  1.15798314 1.15304338 1.12379244 1.18840601]]
BARINEL SCORES

,ry 20,cp 15,h 16,cp 14,cp 6,h 1,swap 10,h 13,x 4,cp 12,...,h 2,cp 7,h 0,cp 17,swap 8,cp 19,h 21,h 3,cp 9,h 11
sum,0.592718,0.564416,0.563789,0.562366,0.559666,0.559012,0.548915,0.548852,0.548447,0.547422,...,0.542324,0.540892,0.539224,0.538904,0.538625,0.537482,0.537212,0.532852,0.530775,0.530217

custom SCORES

,ry 20,cp 15,cp 6,cp 14,h 16,h 1,swap 10,h 13,cp 12,cp 5,...,h 2,cp 7,swap 8,cp 18,h 21,cp 19,cp 17,h 11,h 3,cp 9
sum,0.772591,0.723969,0.722064,0.721331,0.719275,0.716065,0.706879,0.706792,0.705638,0.702712,...,0.698655,0.69709,0.694479,0.69411,0.691075,0.689691,0.688823,0.688815,0.687111,0.685205

DSTAR SCORES

,ry 20,cp 12,cp 15,cp 9,swap 10,cp 19,x 4,swap 8,h 1,h 2,...,cp 14,h 11,cp 18,h 13,h 16,cp 7,h 21,cp 17,cp 6,cp 5
sum,1.775189,0.641735,0.636362,0.634152,0.600446,0.488632,0.34854,0.296425,0.229812,0.223302,...,0.186023,0.172035,0.138046,0.137717,0.108532,0.077609,0.058137,0.012869,0.007209,0.000442

ERROR GATE LOCATION:
20
Now evolving the following mutant:  AddGate_ry_inGap_9_.qasm

100%|██████████| 10/10 [00:44<00:00,  4.48s/it]
100%|██████████| 10/10 [00:43<00:00,  4.35s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,ry 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.083450,0.252373,0.118098,0.036368,0.079460,0.196478,0.102228,0.114274,0.333365,0.279682,...,0.212943,0.096965,0.019537,0.006471,0.193019,0.149999,0.165048,0.119512,0.157932,fail
1,0.065574,0.205658,0.102773,0.030267,0.072109,0.179461,0.095225,0.106625,0.300695,0.258866,...,0.191036,0.084909,0.017699,0.005322,0.198640,0.123481,0.148480,0.110120,0.126407,fail
2,0.084592,0.267774,0.130617,0.038985,0.084466,0.194485,0.107612,0.120918,0.314283,0.282560,...,0.203124,0.097477,0.021727,0.007499,0.195193,0.144561,0.163516,0.126117,0.167506,fail
3,0.064914,0.194644,0.106102,0.030182,0.088719,0.224426,0.113666,0.110039,0.300672,0.257191,...,0.201458,0.086414,0.021752,0.005198,0.197579,0.151700,0.149343,0.134869,0.124766,fail
4,0.074022,0.233671,0.113098,0.034388,0.090103,0.240825,0.124124,0.110759,0.311497,0.267864,...,0.201551,0.089612,0.023936,0.006131,0.194654,0.153872,0.153503,0.143079,0.140088,fail
5,0.082519,0.261170,0.132098,0.038915,0.107997,0.298663,0.149898,0.121135,0.316721,0.284006,...,0.179371,0.090950,0.026955,0.006516,0.205303,0.162847,0.159082,0.163741,0.155309,fail
6,0.080057,0.259518,0.131433,0.037784,0.122978,0.344776,0.176173,0.132476,0.359979,0.319097,...,0.225911,0.104714,0.033551,0.006730,0.231624,0.175333,0.176389,0.194402,0.147355,fail
7,0.090635,0.279181,0.142016,0.041613,0.106877,0.268100,0.139479,0.132265,0.346298,0.302688,...,0.224406,0.103208,0.028117,0.007736,0.219067,0.172279,0.177184,0.164999,0.176040,fail
8,0.072721,0.242520,0.126821,0.035637,0.090524,0.253380,0.132252,0.105787,0.273583,0.262577,...,0.165734,0.080288,0.023507,0.006193,0.177309,0.112464,0.135987,0.136928,0.135241,fail
9,0.091533,0.278075,0.144608,0.042417,0.114531,0.286953,0.145629,0.125058,0.316561,0.282032,...,0.169002,0.087222,0.025924,0.006916,0.215791,0.155466,0.158316,0.162113,0.168282,fail
10,0.065452,0.201030,0.100305,0.029732,0.079085,0.209301,0.108775,0.098199,0.270031,0.228836,...,0.165818,0.076131,0.019955,0.004983,0.187315,0.140210,0.134935,0.123181,0.122374,pass
11,0.087828,0.268591,0.130298,0.039897,0.108832,0.273255,0.138709,0.112641,0.294093,0.251970,...,0.167617,0.084414,0.027404,0.006695,0.203598,0.167777,0.148769,0.163989,0.160954,pass
12,0.062902,0.201963,0.101443,0.030255,0.079015,0.203105,0.108439,0.099674,0.264691,0.237469,...,0.168743,0.079440,0.021927,0.005572,0.148617,0.128631,0.132010,0.124659,0.120563,pass
13,0.066891,0.212816,0.103929,0.030919,0.085711,0.221752,0.119665,0.116495,0.327769,0.283099,...,0.224057,0.096027,0.022765,0.005593,0.202926,0.159601,0.162144,0.139308,0.130013,pass
14,0.045610,0.148038,0.077818,0.022054,0.052331,0.127791,0.064943,0.055894,0.132879,0.124490,...,0.080225,0.039959,0.012742,0.003764,0.100350,0.069002,0.069448,0.075088,0.083664,pass
15,0.065291,0.198294,0.095638,0.028812,0.086922,0.220109,0.115544,0.104379,0.266543,0.228505,...,0.147978,0.076221,0.021994,0.005459,0.162130,0.132379,0.135071,0.133430,0.128952,pass
16,0.075704,0.231661,0.117041,0.034913,0.083548,0.201566,0.098167,0.093242,0.256480,0.214156,...,0.164458,0.075129,0.019614,0.005785,0.184754,0.140151,0.129557,0.119877,0.136991,pass
17,0.059259,0.178971,0.094574,0.027607,0.080019,0.194131,0.098388,0.097259,0.259412,0.219970,...,0.165713,0.075081,0.019458,0.004987,0.159173,0.128952,0.129840,0.117428,0.115042,pass
18,0.076468,0.248532,0.122176,0.036958,0.094432,0.249947,0.132343,0.101937,0.272180,0.246586,...,0.168321,0.080439,0.024724,0.005983,0.195634,0.147449,0.137958,0.145625,0.137272,pass
19,0.033267,0.100932,0.049591,0.015199,0.046804,0.127719,0.065470,0.054123,0.154954,0.132472,...,0.110834,0.045776,0.012112,0.002707,0.104632,0.082653,0.077810,0.073068,0.064838,pass

[[1.15862255 1.12819137 1.15902764 1.1571725  1.28401044 1.38600777
  1.3696225  1.12331233 1.13427215 1.14103386 1.14618458 1.22069232
  1.18833602 1.14412102 1.13602352 1.38236012 1.19545961 1.1420285
  1.16732828 1.11657694 1.33529032 1.17444054]]
BARINEL SCORES

,cp 12,ry 13,cp 7,h 14,swap 8,h 2,cp 19,cp 5,h 0,cp 20,...,x 4,cp 16,cp 15,h 17,h 1,cp 6,swap 10,h 3,h 11,cp 9
sum,0.563356,0.559462,0.558514,0.558086,0.558046,0.557887,0.556874,0.556709,0.555242,0.554167,...,0.551539,0.550803,0.550464,0.545902,0.544961,0.544916,0.53994,0.536658,0.531911,0.526759

custom SCORES

,cp 16,cp 15,cp 6,h 1,cp 12,cp 5,h 17,h 0,cp 19,ry 13,...,h 14,h 2,h 21,cp 18,cp 20,x 4,swap 10,h 3,h 11,cp 9
sum,0.741657,0.738946,0.733234,0.726881,0.724058,0.72309,0.721138,0.718267,0.718232,0.718108,...,0.714812,0.713618,0.713136,0.712924,0.710469,0.709007,0.704715,0.693272,0.684328,0.68325

DSTAR SCORES

,ry 13,cp 12,swap 10,cp 9,cp 16,cp 20,x 4,swap 8,h 2,h 0,...,h 11,cp 15,cp 19,h 14,h 17,cp 7,h 21,cp 18,cp 6,cp 5
sum,0.805829,0.642756,0.609283,0.608138,0.514428,0.510688,0.353117,0.337155,0.22368,0.200593,...,0.162206,0.149725,0.141608,0.127205,0.084962,0.079194,0.058666,0.01305,0.005774,0.000417

ERROR GATE LOCATION:
13
Now evolving the following mutant:  AddGate_cx_inGap_8_.qasm

100%|██████████| 10/10 [01:04<00:00,  6.44s/it]
100%|██████████| 10/10 [00:58<00:00,  5.86s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,cp 13,h 12,...,cx 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.089041,0.280923,0.140056,0.042687,0.112316,0.286334,0.150573,0.130445,0.299513,0.167718,...,0.337674,0.083644,0.029900,0.006603,0.201450,0.164834,0.160176,0.214791,0.158565,fail
1,0.088160,0.282402,0.143649,0.041592,0.102005,0.271420,0.140696,0.130049,0.305606,0.133450,...,0.314235,0.082551,0.026984,0.006752,0.187357,0.135022,0.153966,0.197871,0.157352,fail
2,0.070685,0.214343,0.110728,0.032099,0.092679,0.232440,0.121734,0.114067,0.249494,0.139411,...,0.266217,0.067508,0.023983,0.005430,0.174019,0.136033,0.135743,0.178169,0.135775,fail
3,0.081044,0.259161,0.129737,0.038617,0.094925,0.255141,0.128967,0.106100,0.261270,0.139784,...,0.308997,0.076692,0.025619,0.005640,0.190436,0.145631,0.142454,0.185361,0.136534,fail
4,0.073580,0.235858,0.114428,0.033882,0.088667,0.233653,0.120190,0.108533,0.254155,0.134447,...,0.286781,0.071094,0.024457,0.005396,0.173883,0.138509,0.136377,0.178826,0.129214,fail
5,0.075103,0.241612,0.125305,0.037273,0.098064,0.256752,0.132140,0.110136,0.278271,0.121997,...,0.290873,0.075065,0.024434,0.005741,0.167567,0.124363,0.137954,0.176346,0.133015,fail
6,0.072344,0.227039,0.114318,0.034646,0.091534,0.247094,0.126923,0.102208,0.247190,0.133742,...,0.273675,0.068103,0.024059,0.005195,0.179491,0.133484,0.129374,0.174147,0.126955,fail
7,0.057458,0.169564,0.088086,0.025667,0.093034,0.245545,0.128250,0.120228,0.278185,0.137652,...,0.290210,0.076018,0.024672,0.004779,0.165888,0.141332,0.143247,0.183183,0.114025,fail
8,0.095334,0.302542,0.153300,0.045158,0.108990,0.268340,0.140302,0.136032,0.318296,0.148534,...,0.349814,0.092467,0.028895,0.007316,0.218923,0.156115,0.173400,0.212698,0.169750,fail
9,0.082171,0.260204,0.131102,0.038912,0.105829,0.275715,0.144765,0.126449,0.292982,0.145741,...,0.324335,0.085389,0.029787,0.006647,0.178322,0.149934,0.154072,0.205602,0.148710,fail
10,0.050615,0.164794,0.078357,0.023511,0.059243,0.171591,0.085379,0.062358,0.159075,0.095990,...,0.203186,0.047580,0.016903,0.003539,0.109474,0.098223,0.084374,0.118749,0.083480,pass
11,0.054571,0.167118,0.081400,0.024011,0.064983,0.155781,0.082197,0.078426,0.168329,0.097190,...,0.192941,0.046305,0.016128,0.003893,0.138277,0.096397,0.096381,0.127126,0.099728,pass
12,0.046044,0.139225,0.071229,0.020963,0.065164,0.176392,0.090576,0.076272,0.187658,0.084018,...,0.195375,0.051163,0.016785,0.003411,0.120456,0.088447,0.094498,0.123819,0.081183,pass
13,0.061278,0.202172,0.100582,0.029811,0.073776,0.201784,0.105216,0.077423,0.182339,0.095916,...,0.214122,0.049594,0.020476,0.004481,0.125811,0.095604,0.091170,0.138709,0.103410,pass
14,0.087694,0.266659,0.135348,0.040053,0.087126,0.200159,0.101326,0.110716,0.245661,0.138735,...,0.265349,0.072223,0.021341,0.006453,0.180752,0.132627,0.141197,0.164271,0.159295,pass
15,0.065717,0.198264,0.099112,0.030035,0.077790,0.171568,0.089874,0.094302,0.205327,0.109606,...,0.217512,0.056669,0.018107,0.004987,0.129668,0.102765,0.112750,0.138270,0.122742,pass
16,0.058712,0.169962,0.083394,0.025310,0.080311,0.195896,0.102683,0.105983,0.230438,0.138556,...,0.249451,0.067208,0.021029,0.004520,0.149435,0.137077,0.130347,0.161646,0.110693,pass
17,0.063937,0.191734,0.095905,0.028980,0.090636,0.220994,0.117487,0.108095,0.229339,0.130203,...,0.262705,0.064089,0.023534,0.004812,0.163873,0.130721,0.128098,0.175178,0.121586,pass
18,0.073067,0.233586,0.116633,0.034184,0.095408,0.246691,0.129187,0.113365,0.270177,0.136055,...,0.312886,0.079373,0.026676,0.005403,0.200174,0.148763,0.148919,0.192452,0.126125,pass
19,0.050916,0.163076,0.080643,0.023597,0.079676,0.221066,0.114300,0.094587,0.212043,0.110089,...,0.249121,0.061783,0.023232,0.004228,0.122528,0.117344,0.111061,0.160586,0.096138,pass

[[1.2145712  1.22306026 1.22570078 1.21872771 1.1367545  1.11308654
  1.12827685 1.14868179 1.14290805 1.19586745 1.20808822 1.1531554
  1.22582732 1.14964066 1.18771237 1.13780486 1.22956261 1.19152262
  1.156524   1.18219254 1.12633357 1.20399303]]
BARINEL SCORES

,cp 13,cp 19,cp 18,swap 9,cp 16,cp 15,cp 7,cp 20,cp 5,h 2,...,h 14,h 21,swap 11,h 0,h 17,x 4,h 1,cp 10,h 3,h 12
sum,0.571234,0.570237,0.569185,0.567477,0.567321,0.567222,0.566402,0.566021,0.565444,0.562936,...,0.562381,0.561671,0.560776,0.560756,0.560702,0.560542,0.559597,0.55409,0.55388,0.55241

custom SCORES

,cp 19,cp 18,swap 9,cp 5,cp 20,cp 7,cp 13,h 21,swap 11,h 0,...,cp 15,cp 16,cx 8,h 14,cp 6,h 17,h 12,h 1,h 3,cp 10
sum,0.744972,0.742606,0.741385,0.739256,0.739091,0.734583,0.73445,0.732219,0.730143,0.729543,...,0.727217,0.72519,0.724702,0.723881,0.722786,0.720046,0.717562,0.71717,0.714024,0.713829

DSTAR SCORES

,cx 8,cp 10,cp 13,swap 11,cp 16,cp 20,swap 9,h 1,x 4,h 2,...,h 12,cp 15,cp 19,h 14,h 17,h 21,cp 7,cp 18,cp 6,cp 5
sum,0.748926,0.670186,0.641503,0.614641,0.553207,0.514344,0.323003,0.316206,0.295076,0.193144,...,0.176623,0.161641,0.142953,0.128411,0.090609,0.058054,0.057202,0.013355,0.006768,0.000352

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_z_inGap_9_.qasm

100%|██████████| 10/10 [00:47<00:00,  4.75s/it]
100%|██████████| 10/10 [00:41<00:00,  4.15s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,z 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.082348,0.257864,0.133392,0.039130,0.094805,0.246730,0.127162,0.119269,0.318427,0.283676,...,0.198518,0.095412,0.023625,0.006896,0.198453,0.153862,0.161283,0.140146,0.157648,fail
1,0.065037,0.199416,0.098162,0.029078,0.090515,0.236165,0.123836,0.125244,0.336958,0.285543,...,0.199491,0.096376,0.023888,0.005787,0.212249,0.164081,0.168811,0.144848,0.134630,fail
2,0.063870,0.213613,0.103199,0.031180,0.074273,0.210007,0.110883,0.102250,0.305723,0.269323,...,0.206908,0.088376,0.020268,0.005377,0.178175,0.130605,0.147104,0.119450,0.118081,fail
3,0.083996,0.257565,0.130565,0.039247,0.093543,0.227434,0.119699,0.115008,0.296420,0.263033,...,0.182174,0.089141,0.023687,0.007005,0.176475,0.150842,0.151475,0.140179,0.161189,fail
4,0.095979,0.302313,0.151089,0.045150,0.111290,0.279968,0.142270,0.133639,0.361456,0.310045,...,0.229893,0.104464,0.027484,0.007528,0.221265,0.176220,0.180559,0.167138,0.177611,fail
5,0.072763,0.227880,0.114752,0.034183,0.088822,0.207699,0.112241,0.122261,0.317722,0.276859,...,0.214639,0.098192,0.023932,0.006850,0.195669,0.162321,0.164253,0.138467,0.149945,fail
6,0.107011,0.327578,0.168212,0.048941,0.115123,0.283077,0.144327,0.133866,0.340229,0.311225,...,0.194941,0.100190,0.026860,0.008628,0.227488,0.148840,0.174716,0.161498,0.202645,fail
7,0.082966,0.249071,0.123954,0.037974,0.094323,0.225765,0.122978,0.122011,0.313164,0.275724,...,0.180504,0.089917,0.022953,0.006686,0.199018,0.158195,0.159220,0.142812,0.162038,fail
8,0.096791,0.307206,0.151656,0.044935,0.113600,0.285921,0.150097,0.138552,0.362488,0.319281,...,0.223869,0.107057,0.029055,0.008169,0.247549,0.172877,0.184691,0.172819,0.185464,fail
9,0.087877,0.290561,0.148484,0.042649,0.107121,0.297784,0.149086,0.115704,0.299726,0.282270,...,0.172719,0.088506,0.027221,0.007123,0.196852,0.140178,0.149614,0.160512,0.159094,fail
10,0.039316,0.123558,0.062598,0.018907,0.065585,0.181918,0.094535,0.073743,0.208320,0.188564,...,0.133520,0.059897,0.016821,0.003436,0.123143,0.090339,0.100343,0.098240,0.075881,pass
11,0.064762,0.199070,0.098736,0.029279,0.087847,0.220700,0.112669,0.094985,0.245996,0.208739,...,0.143186,0.070098,0.021857,0.005129,0.157383,0.133174,0.123548,0.132118,0.120366,pass
12,0.059806,0.184795,0.091459,0.027933,0.079027,0.201142,0.102296,0.075259,0.209166,0.178116,...,0.131306,0.058288,0.019939,0.004327,0.154462,0.116977,0.102337,0.118102,0.102125,pass
13,0.044512,0.130784,0.069291,0.019967,0.064592,0.148727,0.081172,0.097276,0.248554,0.207349,...,0.155824,0.073620,0.016603,0.004310,0.140262,0.120200,0.127413,0.100129,0.097927,pass
14,0.071308,0.225756,0.108432,0.032654,0.067908,0.173110,0.088564,0.083357,0.222710,0.193154,...,0.130186,0.066863,0.017580,0.005566,0.136042,0.113467,0.114011,0.105016,0.130460,pass
15,0.068960,0.213397,0.101281,0.030781,0.089654,0.238428,0.129202,0.113879,0.288316,0.253484,...,0.157593,0.083662,0.024674,0.006070,0.193717,0.149945,0.149940,0.148576,0.141999,pass
16,0.079280,0.255820,0.132925,0.037376,0.085312,0.212885,0.107001,0.106247,0.264574,0.240388,...,0.163233,0.081868,0.021872,0.007122,0.139314,0.110203,0.133680,0.121304,0.150808,pass
17,0.055363,0.168681,0.081485,0.025268,0.072753,0.176546,0.096066,0.089045,0.235808,0.204545,...,0.147314,0.069861,0.018607,0.004941,0.143921,0.113671,0.119151,0.110270,0.110734,pass
18,0.095317,0.287724,0.138924,0.042571,0.116105,0.298769,0.148585,0.128455,0.335187,0.277328,...,0.181392,0.095536,0.029090,0.007470,0.222569,0.184562,0.171594,0.176867,0.181814,pass
19,0.085951,0.260686,0.123886,0.037808,0.091432,0.220190,0.119916,0.119896,0.309754,0.268323,...,0.178099,0.091581,0.022859,0.007005,0.196440,0.150519,0.160900,0.139906,0.168567,pass

[[1.27601171 1.24409361 1.27099557 1.24700415 1.17064285 1.19087315
  1.15230617 1.12845521 1.11455517 1.10977832 1.15737442 1.1689299
  1.10557484 1.14736673 1.1179389  1.16698816 1.23178775 1.20567874
  1.13105128 1.12497957 1.16152057 1.25996014]]
BARINEL SCORES

,swap 10,swap 8,cp 19,cp 18,cp 12,cp 20,x 4,cp 7,z 13,cp 5,...,h 0,h 14,h 3,cp 9,cp 16,cp 15,h 17,h 1,cp 6,h 11
sum,0.577118,0.568363,0.567406,0.564692,0.564449,0.56222,0.560913,0.560377,0.55875,0.558487,...,0.556709,0.555581,0.548391,0.54776,0.546812,0.546708,0.545242,0.543336,0.542573,0.542474

custom SCORES

,cp 19,swap 10,cp 18,cp 20,h 21,h 0,swap 8,cp 5,x 4,cp 12,...,h 2,h 14,cp 16,h 17,cp 15,h 3,h 1,cp 6,h 11,cp 9
sum,0.747698,0.74577,0.740735,0.737084,0.735868,0.732066,0.731394,0.730472,0.729984,0.721053,...,0.714332,0.712319,0.709607,0.704813,0.704202,0.703455,0.70111,0.700868,0.699435,0.699157

DSTAR SCORES

,z 13,cp 12,cp 9,swap 10,cp 20,cp 16,x 4,swap 8,h 2,h 0,...,h 11,cp 19,cp 15,h 14,h 17,cp 7,h 21,cp 18,cp 6,cp 5
sum,0.841599,0.677334,0.665033,0.65529,0.575343,0.517937,0.363187,0.348443,0.238457,0.22931,...,0.179978,0.159102,0.153133,0.137269,0.089379,0.085298,0.065948,0.014951,0.006071,0.000488

ERROR GATE LOCATION:
13
Now evolving the following mutant:  AddGate_h_inGap_9_.qasm

100%|██████████| 10/10 [00:38<00:00,  3.84s/it]
100%|██████████| 10/10 [00:37<00:00,  3.72s/it]

,h 21,cp 20,cp 19,cp 18,h 17,cp 16,cp 15,h 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.095093,0.299051,0.149362,0.043901,0.101660,0.246776,0.133923,0.139226,0.078331,0.0,...,0.171617,0.004738,0.020418,0.006054,0.171747,0.123048,0.091656,0.133584,0.147196,fail
1,0.070935,0.227057,0.115542,0.034108,0.099670,0.256119,0.134642,0.125390,0.065050,0.0,...,0.182871,0.004502,0.019409,0.004620,0.165282,0.110720,0.080688,0.127171,0.109491,fail
2,0.081609,0.254399,0.130049,0.037059,0.110582,0.308014,0.155865,0.128370,0.073481,0.0,...,0.160632,0.005357,0.022999,0.004704,0.183559,0.124691,0.084194,0.151801,0.122868,fail
3,0.072890,0.240426,0.124214,0.035070,0.076959,0.209468,0.105981,0.099304,0.051724,0.0,...,0.178865,0.003567,0.015852,0.004500,0.148493,0.080806,0.067130,0.101494,0.106145,fail
4,0.085284,0.259341,0.130257,0.039910,0.104417,0.249286,0.132991,0.133594,0.074672,0.0,...,0.159673,0.004466,0.019591,0.005353,0.156276,0.118097,0.083820,0.129807,0.136324,fail
5,0.073196,0.231238,0.116163,0.033365,0.101205,0.283580,0.142429,0.119532,0.062965,0.0,...,0.171083,0.005016,0.021442,0.004551,0.139733,0.109038,0.076032,0.137764,0.108571,fail
6,0.076641,0.248144,0.128022,0.036685,0.109191,0.285867,0.150141,0.132230,0.073707,0.0,...,0.184611,0.005066,0.022024,0.004959,0.158736,0.106464,0.086205,0.142290,0.117615,fail
7,0.067095,0.203190,0.103322,0.029498,0.085599,0.220753,0.113331,0.105526,0.058009,0.0,...,0.126741,0.003786,0.016478,0.004123,0.124794,0.077451,0.066526,0.108142,0.103601,fail
8,0.076422,0.235370,0.115625,0.033595,0.094376,0.243461,0.128387,0.127115,0.067363,0.0,...,0.153680,0.004039,0.017619,0.004655,0.151208,0.080681,0.076033,0.117781,0.116300,fail
9,0.106520,0.328331,0.168854,0.049803,0.129686,0.313812,0.161757,0.150264,0.087323,0.0,...,0.196070,0.005406,0.023668,0.006832,0.183538,0.120241,0.098333,0.154668,0.166349,fail
10,0.068614,0.219325,0.108576,0.032136,0.079812,0.197758,0.107826,0.109830,0.063487,0.0,...,0.131415,0.003740,0.016074,0.004481,0.116018,0.098114,0.072428,0.106575,0.108321,pass
11,0.100805,0.307709,0.155939,0.045776,0.106204,0.262885,0.133762,0.120278,0.071612,0.0,...,0.145824,0.004545,0.019987,0.005899,0.173865,0.105269,0.079459,0.131243,0.153407,pass
12,0.067711,0.197431,0.096707,0.030347,0.091075,0.214787,0.113128,0.102747,0.060785,0.0,...,0.101445,0.003879,0.016451,0.003868,0.138610,0.119799,0.068470,0.115083,0.108721,pass
13,0.068835,0.217179,0.109905,0.032166,0.084894,0.213439,0.112899,0.101324,0.058758,0.0,...,0.128636,0.004342,0.018496,0.004570,0.119974,0.107917,0.069837,0.118101,0.106294,pass
14,0.054002,0.164129,0.084648,0.024331,0.082102,0.205885,0.107260,0.100156,0.055637,0.0,...,0.126053,0.003842,0.016450,0.003292,0.136646,0.109973,0.069916,0.113630,0.086944,pass
15,0.087271,0.282739,0.141927,0.042466,0.108655,0.289063,0.150254,0.110939,0.068239,0.0,...,0.130716,0.004703,0.020548,0.005376,0.147672,0.111228,0.070832,0.131912,0.130642,pass
16,0.062149,0.185459,0.098189,0.027755,0.075126,0.176223,0.088343,0.097485,0.054202,0.0,...,0.120793,0.002970,0.013075,0.003814,0.138165,0.074795,0.061784,0.090794,0.098016,pass
17,0.090301,0.289268,0.148019,0.044618,0.097947,0.241843,0.125489,0.106232,0.060885,0.0,...,0.144946,0.004302,0.018844,0.005462,0.153100,0.112883,0.071258,0.122249,0.133287,pass
18,0.037926,0.124986,0.063703,0.018753,0.044483,0.129737,0.067559,0.056107,0.027742,0.0,...,0.107455,0.001964,0.008727,0.002332,0.073007,0.045717,0.037285,0.055175,0.054881,pass
19,0.067132,0.224827,0.116884,0.033096,0.075051,0.206117,0.103811,0.088269,0.044597,0.0,...,0.153167,0.003226,0.014265,0.004085,0.146143,0.085395,0.060304,0.094023,0.096239,pass

[[1.3221034  1.29952509 1.31771916 1.33522399 1.27977779 1.19906748
  1.18987599 1.19205054 1.26075229        nan 1.29183143 1.27370712
  1.20875176 1.16303798 1.1767221  1.18639199 1.35680711 1.15929661
  1.18613719 1.2130694  1.18564436 1.34754353]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,swap 8,h 14,h 2,cp 7,cp 6,cp 15,cp 16,h 13,h 1,h 17,...,h 0,h 21,cp 20,cp 19,cp 18,swap 10,h 3,h 11,cp 9,cp 12
sum,0.566424,0.559271,0.55062,0.550515,0.55047,0.550433,0.550411,0.550328,0.547355,0.545192,...,0.534118,0.533414,0.533072,0.53261,0.529491,0.522878,0.519816,0.51191,0.508282,0.0

custom SCORES

,swap 8,h 14,h 13,cp 5,h 17,h 2,cp 16,cp 15,h 0,cp 6,...,h 1,cp 19,cp 20,cp 18,x 4,swap 10,h 11,h 3,cp 9,cp 12
sum,0.731117,0.725941,0.723784,0.720958,0.719623,0.717605,0.715406,0.714169,0.714055,0.713738,...,0.709597,0.708068,0.706257,0.706238,0.697836,0.689376,0.677235,0.673959,0.661879,0.0

DSTAR SCORES

,cp 16,cp 20,swap 10,cp 9,swap 8,x 4,cp 15,h 1,cp 19,h 14,...,h 17,h 11,h 2,h 21,h 13,cp 18,cp 6,cp 5,cp 7,cp 12
sum,0.564306,0.522673,0.492109,0.299505,0.251723,0.221018,0.166341,0.153603,0.147603,0.14454,...,0.094683,0.063389,0.061633,0.060639,0.045403,0.013466,0.003916,0.000252,0.00021,0.0

ERROR GATE LOCATION:
14
Now evolving the following mutant:  AddGate_rzz_inGap_10_.qasm

100%|██████████| 10/10 [00:44<00:00,  4.47s/it]
100%|██████████| 10/10 [00:44<00:00,  4.50s/it]

,h 21,cp 20,cp 19,cp 18,h 17,rzz 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.080236,0.257356,0.133682,0.038467,0.104620,0.380730,0.284499,0.142885,0.117633,0.279534,...,0.203697,0.093548,0.027787,0.006720,0.202016,0.150676,0.157033,0.159801,0.149691,fail
1,0.055660,0.182359,0.088835,0.027481,0.084019,0.320156,0.235572,0.123490,0.096700,0.252815,...,0.194744,0.082870,0.022538,0.004696,0.168743,0.140536,0.137326,0.129865,0.103229,fail
2,0.090878,0.293569,0.148880,0.043068,0.105709,0.380202,0.281285,0.145026,0.120840,0.288642,...,0.196405,0.093249,0.027230,0.007785,0.206251,0.141663,0.159508,0.158235,0.172723,fail
3,0.075883,0.234544,0.117971,0.034826,0.104105,0.382382,0.275278,0.143734,0.125106,0.291618,...,0.189225,0.095677,0.026707,0.006612,0.188027,0.155228,0.163740,0.157179,0.149348,fail
4,0.082901,0.258801,0.129490,0.038952,0.107798,0.366904,0.270187,0.143832,0.129966,0.306314,...,0.189369,0.093823,0.025544,0.006607,0.227801,0.150392,0.168598,0.157272,0.157125,fail
5,0.095421,0.298497,0.153555,0.045408,0.113206,0.399118,0.301294,0.152916,0.132206,0.314336,...,0.190189,0.097784,0.027112,0.007428,0.233074,0.171961,0.175078,0.165988,0.178941,fail
6,0.064345,0.203963,0.102136,0.029693,0.093455,0.338980,0.256590,0.128780,0.114105,0.277250,...,0.202781,0.091765,0.023608,0.005550,0.172639,0.145995,0.154290,0.137662,0.124594,fail
7,0.083724,0.256335,0.133861,0.038916,0.104543,0.342812,0.267021,0.134583,0.118162,0.271828,...,0.174129,0.087000,0.024398,0.006583,0.195229,0.138030,0.153321,0.147604,0.157179,fail
8,0.069013,0.209056,0.107083,0.032338,0.104990,0.356335,0.269295,0.138906,0.124166,0.280077,...,0.176951,0.091253,0.025968,0.006116,0.180610,0.154121,0.158006,0.153835,0.140029,fail
9,0.048108,0.149653,0.073008,0.022122,0.078122,0.299682,0.213439,0.110594,0.090983,0.222658,...,0.158607,0.072359,0.020091,0.003936,0.166284,0.122437,0.125811,0.121385,0.091372,fail
10,0.078131,0.230065,0.118760,0.034629,0.105135,0.363801,0.254328,0.131995,0.133920,0.279752,...,0.183519,0.094726,0.025614,0.006742,0.188555,0.152313,0.166938,0.156780,0.157869,pass
11,0.066298,0.209358,0.108189,0.031753,0.090075,0.334663,0.240615,0.123020,0.090786,0.211139,...,0.148040,0.068455,0.023115,0.005199,0.170873,0.129993,0.117451,0.138081,0.117804,pass
12,0.060484,0.183710,0.095085,0.027984,0.076667,0.244661,0.181247,0.093674,0.088005,0.189158,...,0.132629,0.064426,0.018621,0.005108,0.146510,0.106212,0.112622,0.111575,0.117900,pass
13,0.058837,0.183061,0.088291,0.027252,0.083621,0.311715,0.220781,0.116343,0.088688,0.210162,...,0.140725,0.068146,0.021661,0.004831,0.151171,0.122507,0.116193,0.127571,0.109601,pass
14,0.044238,0.144323,0.070980,0.020797,0.054599,0.217972,0.149599,0.076714,0.074342,0.181316,...,0.148367,0.063473,0.014707,0.003925,0.134534,0.093167,0.106465,0.086654,0.085917,pass
15,0.042866,0.134583,0.066819,0.020280,0.060110,0.240059,0.167671,0.084548,0.059849,0.142003,...,0.101306,0.046051,0.015890,0.003121,0.116369,0.092435,0.080537,0.094773,0.075983,pass
16,0.060290,0.188578,0.094002,0.027997,0.060970,0.232684,0.160694,0.078559,0.061513,0.141964,...,0.104664,0.049392,0.015871,0.004510,0.107836,0.091474,0.082869,0.093081,0.106281,pass
17,0.068660,0.220721,0.111737,0.032712,0.094616,0.342797,0.250427,0.131154,0.109593,0.249893,...,0.154571,0.079779,0.024756,0.005785,0.181087,0.139202,0.139465,0.146845,0.132705,pass
18,0.092416,0.296705,0.150086,0.044135,0.101054,0.356195,0.268965,0.135554,0.107146,0.251419,...,0.147315,0.078338,0.024303,0.007128,0.192839,0.135999,0.138300,0.146660,0.168136,pass
19,0.055026,0.169404,0.085861,0.024662,0.071159,0.266892,0.181693,0.092158,0.088903,0.191443,...,0.149751,0.068956,0.018994,0.004746,0.133468,0.121152,0.116670,0.112837,0.109265,pass

[[1.27881386 1.2733805  1.29200797 1.29267818 1.13141704 1.11882376
  1.13504791 1.12047102 1.1300944  1.12864648 1.23550947 1.31076497
  1.15358786 1.08575013 1.08730092 1.1071385  1.25497157 1.20099696
  1.16897686 1.12756248 1.11488993 1.2564065 ]]
BARINEL SCORES

,cp 12,swap 8,cp 7,h 2,h 13,cp 14,cp 15,x 4,h 17,h 3,...,rzz 16,h 11,cp 5,cp 9,h 0,cp 18,cp 19,cp 20,h 21,swap 10
sum,0.576223,0.570765,0.56881,0.568713,0.564441,0.561979,0.56114,0.560254,0.556312,0.553961,...,0.550617,0.549866,0.548341,0.547798,0.546584,0.545899,0.545607,0.54456,0.543295,0.542094

custom SCORES

,cp 12,h 2,x 4,swap 8,h 13,cp 7,cp 18,cp 19,cp 5,cp 15,...,cp 14,h 0,cp 20,h 21,h 3,h 17,cp 9,cp 6,rzz 16,h 1
sum,0.738811,0.729027,0.72847,0.725692,0.723909,0.723427,0.722317,0.721839,0.720379,0.72037,...,0.719399,0.718267,0.717917,0.716988,0.715853,0.713667,0.705781,0.705042,0.704627,0.704149

DSTAR SCORES

,rzz 16,cp 12,cp 9,cp 15,swap 10,cp 20,x 4,swap 8,h 2,h 1,...,cp 14,h 11,cp 19,h 13,h 17,cp 7,h 21,cp 18,cp 6,cp 5
sum,0.985611,0.643796,0.609903,0.583483,0.564398,0.459425,0.326836,0.308455,0.215693,0.197649,...,0.168346,0.160396,0.128532,0.125527,0.092715,0.075717,0.052391,0.011989,0.006174,0.000383

ERROR GATE LOCATION:
16
Now evolving the following mutant:  AddGate_rxx_inGap_16_.qasm

100%|██████████| 10/10 [00:42<00:00,  4.23s/it]
100%|██████████| 10/10 [00:42<00:00,  4.27s/it]

,rxx 21,h 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.448846,0.080104,0.239815,0.126653,0.036419,0.112743,0.281253,0.150335,0.150208,0.319829,...,0.192524,0.106496,0.027762,0.007139,0.230950,0.170212,0.187934,0.171375,0.167056,fail
1,0.512069,0.069006,0.215830,0.108182,0.032916,0.098049,0.244800,0.131042,0.122017,0.278541,...,0.182980,0.092097,0.024951,0.006349,0.182363,0.157649,0.158669,0.147211,0.138536,fail
2,0.343494,0.070107,0.217297,0.111107,0.032683,0.095326,0.249432,0.129697,0.107197,0.248990,...,0.158218,0.077972,0.023267,0.005684,0.178284,0.128743,0.138819,0.140209,0.133095,fail
3,0.335996,0.076069,0.254048,0.126186,0.037503,0.098541,0.272122,0.139322,0.099841,0.249340,...,0.154493,0.075235,0.024842,0.005955,0.192380,0.125334,0.131883,0.148247,0.132860,fail
4,0.391688,0.076213,0.247749,0.127816,0.037103,0.099218,0.276540,0.137768,0.101532,0.243155,...,0.142742,0.075526,0.025440,0.005967,0.190053,0.130895,0.131840,0.149585,0.136336,fail
5,0.622975,0.118540,0.374273,0.188669,0.056409,0.134595,0.341963,0.179049,0.157747,0.360550,...,0.220146,0.115823,0.033566,0.009865,0.241929,0.186814,0.200692,0.197636,0.226261,fail
6,0.465081,0.062703,0.202588,0.107554,0.030477,0.088660,0.234857,0.122027,0.107083,0.267119,...,0.198559,0.085480,0.022362,0.005504,0.187493,0.123673,0.145382,0.129576,0.116791,fail
7,0.511325,0.101252,0.308737,0.151534,0.045524,0.113243,0.272350,0.139305,0.137754,0.301342,...,0.197942,0.103121,0.027426,0.008259,0.210822,0.174443,0.179547,0.165395,0.194517,fail
8,0.412563,0.077661,0.252308,0.132174,0.037757,0.114663,0.308621,0.159704,0.126605,0.284076,...,0.173946,0.090535,0.029857,0.006993,0.196491,0.143378,0.155821,0.175268,0.151213,fail
9,0.549002,0.098036,0.312313,0.151929,0.045068,0.106932,0.260154,0.137636,0.140321,0.317520,...,0.213650,0.107152,0.027747,0.008430,0.232440,0.171602,0.186642,0.163349,0.190012,fail
10,0.375535,0.064378,0.195285,0.096667,0.028798,0.070598,0.172008,0.092539,0.099498,0.235603,...,0.185799,0.081642,0.018345,0.005195,0.162598,0.135674,0.139185,0.111080,0.121953,pass
11,0.258214,0.070979,0.225159,0.109478,0.033521,0.082279,0.211894,0.113331,0.104046,0.238934,...,0.141869,0.079216,0.021319,0.006098,0.139455,0.128649,0.133567,0.124740,0.139616,pass
12,0.374608,0.088092,0.280294,0.141503,0.041721,0.091677,0.223589,0.113432,0.106903,0.266788,...,0.187300,0.088014,0.021985,0.007293,0.161706,0.131312,0.145553,0.124645,0.162587,pass
13,0.250071,0.068789,0.215770,0.105406,0.030882,0.082981,0.210419,0.112871,0.106742,0.237822,...,0.162877,0.077916,0.021923,0.005470,0.187868,0.131162,0.139682,0.135443,0.132327,pass
14,0.312874,0.071119,0.218729,0.107043,0.031539,0.088739,0.230285,0.116833,0.107742,0.251535,...,0.189952,0.084221,0.022299,0.005609,0.202018,0.136582,0.147672,0.137049,0.134371,pass
15,0.365278,0.049487,0.148014,0.075866,0.022614,0.091049,0.235441,0.122029,0.099270,0.215042,...,0.134900,0.068623,0.022429,0.004420,0.150928,0.126989,0.122056,0.134814,0.102990,pass
16,0.242093,0.040596,0.125676,0.059812,0.018750,0.049959,0.115546,0.062874,0.070546,0.161991,...,0.116232,0.054008,0.011703,0.003286,0.120846,0.091157,0.096227,0.074582,0.081183,pass
17,0.292476,0.062917,0.193033,0.092198,0.028529,0.069392,0.175904,0.094124,0.091450,0.211293,...,0.142149,0.071750,0.017089,0.005152,0.152650,0.120915,0.124042,0.105798,0.123116,pass
18,0.206300,0.045517,0.151298,0.074033,0.022282,0.062206,0.173253,0.093369,0.080831,0.200793,...,0.148626,0.064111,0.017822,0.003756,0.142217,0.110664,0.110365,0.105919,0.084648,pass
19,0.413721,0.060691,0.186453,0.091924,0.027843,0.085682,0.222851,0.116835,0.105808,0.232766,...,0.148348,0.078679,0.022724,0.005196,0.165988,0.146979,0.137396,0.134296,0.121512,pass

[[1.35634651 1.4287208  1.42582598 1.4166439  1.43952425 1.26740981
  1.24708797 1.25570571 1.26166874 1.25607035 1.29544373 1.22828133
  1.2314165  1.19957623 1.24616031 1.2561155  1.40643561 1.18406944
  1.23493617 1.24096049 1.24467399 1.42600698]]
BARINEL SCORES

,rxx 21,cp 18,cp 15,cp 14,h 16,cp 17,cp 5,cp 19,cp 6,h 1,...,swap 10,x 4,h 13,cp 12,h 2,cp 7,h 11,h 3,swap 8,cp 9
sum,0.597725,0.58266,0.58178,0.578658,0.578248,0.577676,0.576751,0.57506,0.574839,0.571947,...,0.563916,0.562947,0.562405,0.560306,0.555181,0.554022,0.546537,0.54556,0.540838,0.540056

custom SCORES

,rxx 21,cp 18,cp 17,cp 19,cp 5,h 20,h 0,cp 15,h 16,cp 14,...,h 13,swap 10,cp 12,x 4,h 2,cp 7,h 11,h 3,cp 9,swap 8
sum,0.800405,0.789015,0.785571,0.780043,0.779542,0.775373,0.771174,0.763162,0.761467,0.760315,...,0.739797,0.737078,0.736252,0.729589,0.727421,0.726622,0.723539,0.713993,0.706314,0.703033

DSTAR SCORES

,rxx 21,cp 12,swap 10,cp 15,cp 9,cp 19,x 4,swap 8,h 2,h 1,...,cp 14,h 11,cp 18,h 13,h 16,cp 7,h 20,cp 17,cp 6,cp 5
sum,1.61147,0.672477,0.6606,0.628097,0.621971,0.577099,0.360313,0.291396,0.231541,0.225347,...,0.184192,0.174289,0.161924,0.142467,0.10467,0.080372,0.064804,0.014928,0.007002,0.00049

ERROR GATE LOCATION:
21
Now evolving the following mutant:  AddGate_ry_inGap_16_.qasm

100%|██████████| 10/10 [01:02<00:00,  6.26s/it]
100%|██████████| 10/10 [01:01<00:00,  6.15s/it]

,ry 21,h 20,cp 19,cp 18,cp 17,h 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.094190,0.130543,0.283213,0.142189,0.041596,0.150565,0.310630,0.156725,0.149466,0.286257,...,0.181354,0.129436,0.040900,0.010234,0.206034,0.218548,0.208732,0.213993,0.206684,fail
1,0.096143,0.100126,0.204213,0.100569,0.029084,0.115786,0.231483,0.117226,0.125304,0.236124,...,0.181923,0.117383,0.034827,0.008714,0.185213,0.186336,0.180910,0.169525,0.160077,fail
2,0.081961,0.107601,0.241621,0.120729,0.035284,0.137877,0.281791,0.144765,0.150612,0.304468,...,0.197718,0.126690,0.036123,0.009681,0.198806,0.197638,0.205339,0.190495,0.179488,fail
3,0.073730,0.122678,0.287757,0.146384,0.042059,0.134524,0.266235,0.135525,0.146081,0.300263,...,0.212722,0.125864,0.034715,0.010569,0.178363,0.175048,0.201696,0.183305,0.198853,fail
4,0.089534,0.118336,0.281198,0.135003,0.040903,0.141843,0.290628,0.144099,0.131149,0.259929,...,0.172984,0.119131,0.034379,0.010238,0.188457,0.193018,0.180333,0.193491,0.178153,fail
5,0.084720,0.131551,0.307541,0.150299,0.044843,0.149576,0.297164,0.151173,0.152985,0.288709,...,0.196523,0.129901,0.039090,0.011284,0.207423,0.221269,0.210369,0.212036,0.215355,fail
6,0.088932,0.124032,0.295596,0.140884,0.041200,0.130332,0.257061,0.131140,0.147835,0.293608,...,0.212105,0.135421,0.035545,0.010878,0.203183,0.205077,0.210236,0.189049,0.199015,fail
7,0.097568,0.137451,0.296584,0.144575,0.042380,0.129147,0.263947,0.131337,0.147967,0.291593,...,0.223191,0.137774,0.039368,0.010265,0.211052,0.217106,0.214716,0.189031,0.203460,fail
8,0.088646,0.133964,0.306714,0.151463,0.044217,0.154537,0.314934,0.162041,0.168445,0.346563,...,0.247446,0.147739,0.041210,0.011170,0.223775,0.226898,0.239542,0.220813,0.212427,fail
9,0.080643,0.130043,0.274611,0.139484,0.040937,0.141647,0.279339,0.141476,0.163411,0.305845,...,0.204328,0.135327,0.039397,0.010249,0.204839,0.221975,0.223824,0.201759,0.217400,fail
10,0.055753,0.102451,0.241130,0.121383,0.036257,0.108251,0.207750,0.108790,0.118218,0.229956,...,0.149681,0.100464,0.026936,0.008330,0.148206,0.162315,0.161128,0.147688,0.169039,pass
11,0.051596,0.080177,0.219185,0.111757,0.032803,0.106462,0.250018,0.124617,0.103880,0.217377,...,0.157641,0.091042,0.029394,0.007575,0.143406,0.149229,0.137795,0.152731,0.128240,pass
12,0.076920,0.086836,0.176166,0.089511,0.026643,0.114599,0.222448,0.113961,0.121328,0.225135,...,0.153417,0.107224,0.029883,0.008113,0.160682,0.180999,0.165164,0.162949,0.136396,pass
13,0.046761,0.086655,0.187235,0.090444,0.026856,0.080403,0.160964,0.082080,0.079863,0.160558,...,0.102459,0.077846,0.020842,0.005518,0.112586,0.116152,0.113483,0.113197,0.132430,pass
14,0.089172,0.163822,0.353469,0.168476,0.050273,0.158548,0.333921,0.171023,0.168069,0.348760,...,0.225507,0.155851,0.042222,0.010553,0.237057,0.255423,0.245249,0.231464,0.245175,pass
15,0.092132,0.135232,0.289027,0.144772,0.041859,0.152890,0.310644,0.152965,0.153718,0.298308,...,0.198136,0.141775,0.038085,0.010274,0.215280,0.229772,0.217453,0.217899,0.207359,pass
16,0.046714,0.070749,0.170550,0.084378,0.024821,0.062831,0.137153,0.070944,0.085850,0.189747,...,0.139900,0.077973,0.020677,0.006073,0.110013,0.110084,0.123432,0.090211,0.117200,pass
17,0.063935,0.083662,0.181636,0.090402,0.027564,0.113880,0.231602,0.121954,0.126800,0.251140,...,0.201899,0.114031,0.033536,0.007771,0.170335,0.195856,0.178803,0.167207,0.139717,pass
18,0.082552,0.082536,0.163694,0.081591,0.023524,0.091519,0.187141,0.097315,0.129823,0.245193,...,0.183511,0.108031,0.034069,0.007549,0.166665,0.181737,0.185661,0.139626,0.137597,pass
19,0.099455,0.108942,0.240004,0.116565,0.034446,0.136625,0.283838,0.145779,0.151365,0.298809,...,0.200950,0.138476,0.038176,0.010416,0.199505,0.216427,0.212651,0.195215,0.176923,pass

[[1.11370631 1.1117727  1.10664192 1.10429962 1.11411464 1.11512241
  1.12749618 1.14475361 1.13564151 1.18956487 1.15359738 1.1697577
  1.0963959  1.21876675 1.13238723 1.09732078 1.09252708 1.1148907
  1.09989122 1.15403239 1.1245906  1.10304278]]
BARINEL SCORES

,cp 5,cp 19,cp 18,ry 21,h 0,cp 17,h 20,h 16,cp 9,h 1,...,h 13,cp 6,h 2,cp 14,swap 8,cp 12,cp 7,swap 10,h 3,h 11
sum,0.556916,0.555682,0.555103,0.554102,0.553474,0.553232,0.552576,0.55172,0.548224,0.548205,...,0.54488,0.544777,0.543872,0.543394,0.542367,0.541683,0.539703,0.5384,0.534308,0.516863

custom SCORES

,cp 19,cp 5,ry 21,cp 18,swap 8,cp 17,h 20,h 0,h 16,cp 12,...,h 13,cp 15,x 4,cp 14,cp 9,swap 10,cp 6,cp 7,h 3,h 11
sum,0.709418,0.709028,0.708379,0.708352,0.707622,0.707323,0.706161,0.7061,0.705529,0.702775,...,0.699577,0.699504,0.699173,0.698907,0.698492,0.695849,0.694225,0.692491,0.681228,0.665926

DSTAR SCORES

,cp 9,cp 12,cp 15,cp 19,swap 10,h 2,h 3,swap 8,x 4,h 0,...,h 13,cp 14,h 16,cp 18,cp 7,h 20,ry 21,cp 17,cp 6,cp 5
sum,0.921479,0.68092,0.633,0.631897,0.614967,0.366969,0.360706,0.351922,0.345398,0.335157,...,0.195752,0.179067,0.172617,0.169491,0.153172,0.138942,0.071695,0.015691,0.013675,0.001058

ERROR GATE LOCATION:
21
Now evolving the following mutant:  AddGate_ry_inGap_10_.qasm

100%|██████████| 10/10 [00:44<00:00,  4.42s/it]
100%|██████████| 10/10 [00:44<00:00,  4.50s/it]

,h 21,cp 20,cp 19,cp 18,h 17,ry 16,cp 15,cp 14,h 13,cp 12,...,swap 8,cp 7,cp 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.057219,0.186922,0.094349,0.027515,0.078250,0.300722,0.222015,0.113274,0.094550,0.247313,...,0.190871,0.079925,0.020771,0.004745,0.165733,0.124419,0.132986,0.121049,0.102886,fail
1,0.067944,0.211824,0.106726,0.031833,0.082404,0.293595,0.216044,0.113531,0.102532,0.257097,...,0.193755,0.085400,0.020915,0.005522,0.175086,0.126774,0.142946,0.122293,0.125454,fail
2,0.077733,0.239757,0.123554,0.036286,0.102724,0.346574,0.253626,0.131593,0.126480,0.275323,...,0.165619,0.089450,0.024336,0.006900,0.178855,0.140327,0.157617,0.146623,0.158439,fail
3,0.077941,0.253096,0.125470,0.037845,0.103274,0.386243,0.284633,0.148403,0.116953,0.287018,...,0.193399,0.091743,0.026906,0.006308,0.218382,0.157071,0.156872,0.159176,0.145146,fail
4,0.062368,0.215051,0.106704,0.031312,0.080268,0.305499,0.236033,0.119095,0.084068,0.241693,...,0.206521,0.078939,0.022533,0.004979,0.172717,0.128811,0.125208,0.126763,0.105905,fail
5,0.047656,0.150375,0.076647,0.022981,0.085044,0.314274,0.230416,0.116372,0.084570,0.213056,...,0.156151,0.067233,0.021269,0.004010,0.163976,0.119551,0.116327,0.124756,0.088167,fail
6,0.092619,0.290463,0.145833,0.042570,0.114120,0.407329,0.297083,0.152557,0.136962,0.318467,...,0.228634,0.110166,0.029896,0.008082,0.193580,0.164106,0.181515,0.171809,0.177854,fail
7,0.083032,0.266068,0.132354,0.039092,0.101308,0.358602,0.261715,0.138506,0.117408,0.266044,...,0.165681,0.088555,0.026850,0.007179,0.166360,0.136925,0.147938,0.152806,0.158440,fail
8,0.088151,0.273307,0.134001,0.040376,0.117048,0.421801,0.297348,0.159873,0.142262,0.322752,...,0.198289,0.102669,0.029232,0.007712,0.220860,0.161685,0.181029,0.176055,0.177023,fail
9,0.070076,0.203739,0.096187,0.030424,0.110397,0.423751,0.286310,0.154461,0.137328,0.304811,...,0.190402,0.101587,0.028364,0.006089,0.220688,0.169912,0.180595,0.171174,0.146590,fail
10,0.048116,0.144611,0.073711,0.021760,0.063000,0.212137,0.145444,0.079421,0.103126,0.237831,...,0.186921,0.082423,0.015409,0.004406,0.148542,0.131305,0.140464,0.094901,0.102020,pass
11,0.084888,0.265649,0.137178,0.040330,0.089317,0.288047,0.218437,0.109060,0.113005,0.259179,...,0.170599,0.086022,0.021112,0.006876,0.192853,0.142997,0.150816,0.128778,0.161441,pass
12,0.100711,0.328431,0.161884,0.046972,0.097913,0.348896,0.259096,0.132212,0.124875,0.294509,...,0.214037,0.102633,0.027018,0.008286,0.183307,0.155286,0.169226,0.155017,0.184956,pass
13,0.099248,0.307312,0.151213,0.045004,0.092869,0.297338,0.220969,0.113363,0.117711,0.270486,...,0.183311,0.090180,0.020601,0.007616,0.217234,0.144870,0.158653,0.131014,0.186846,pass
14,0.050180,0.155974,0.077624,0.023983,0.070590,0.265091,0.181078,0.097656,0.092443,0.218787,...,0.165151,0.074002,0.018608,0.004118,0.172758,0.133123,0.128344,0.113553,0.096894,pass
15,0.100424,0.311113,0.155196,0.045866,0.097662,0.324620,0.241285,0.123140,0.121371,0.282910,...,0.202963,0.094900,0.023453,0.007764,0.215687,0.156244,0.165807,0.143136,0.188327,pass
16,0.082026,0.266500,0.130061,0.039029,0.105331,0.394589,0.290386,0.147159,0.111210,0.270651,...,0.185967,0.087747,0.027500,0.006219,0.201889,0.160011,0.150487,0.161898,0.144804,pass
17,0.073476,0.219265,0.109511,0.033221,0.102370,0.368831,0.256896,0.138766,0.122980,0.276955,...,0.183011,0.091138,0.025318,0.006455,0.190926,0.150234,0.158471,0.151632,0.147464,pass
18,0.071229,0.206953,0.104074,0.031284,0.092376,0.321360,0.222267,0.113142,0.114138,0.242972,...,0.166747,0.084275,0.021958,0.005930,0.186970,0.156567,0.150017,0.137526,0.145181,pass
19,0.077229,0.233797,0.117120,0.034983,0.095871,0.337213,0.232626,0.120103,0.116793,0.263328,...,0.201283,0.090311,0.023559,0.006121,0.207571,0.159401,0.158440,0.146028,0.145316,pass

[[1.27796153 1.26806393 1.27719474 1.25121668 1.20069763 1.19085046
  1.1501842  1.18629684 1.24451301 1.18069426 1.24829359 1.17909042
  1.17929906 1.21013647 1.22998639 1.19074016 1.31359571 1.1771456
  1.18854205 1.19180154 1.19561333 1.28330658]]
BARINEL SCORES

,cp 14,cp 15,ry 16,cp 6,h 1,h 17,cp 12,swap 8,cp 7,swap 10,...,x 4,cp 9,cp 5,h 3,cp 20,cp 18,cp 19,h 11,h 0,h 21
sum,0.53443,0.532629,0.529797,0.527898,0.519221,0.517942,0.510835,0.503912,0.503382,0.501333,...,0.494531,0.492605,0.490948,0.489646,0.48425,0.484202,0.483948,0.480827,0.479692,0.47924

custom SCORES

,cp 14,ry 16,cp 15,cp 6,h 1,h 17,cp 12,cp 7,h 13,swap 8,...,h 2,x 4,cp 19,cp 9,cp 20,cp 18,h 3,h 0,h 21,h 11
sum,0.692928,0.687524,0.685784,0.685045,0.674417,0.673415,0.661621,0.658171,0.657134,0.656362,...,0.64734,0.640065,0.638472,0.637838,0.637765,0.635663,0.635138,0.63359,0.632353,0.630881

DSTAR SCORES

,ry 16,cp 12,cp 9,swap 10,cp 15,cp 20,swap 8,x 4,h 2,h 1,...,cp 14,h 11,h 13,cp 19,h 17,cp 7,h 21,cp 18,cp 6,cp 5
sum,0.962305,0.592222,0.560746,0.554737,0.54476,0.421787,0.300973,0.29538,0.201169,0.19081,...,0.162538,0.142824,0.117324,0.116225,0.087126,0.073709,0.04869,0.011171,0.006165,0.000376

ERROR GATE LOCATION:
16

,Program,path_to_mutant,best_exam_score,worst_exam_score,avg_exam_score
0,AddGate_ry_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeinex...,0.136364,0.136364,0.136364
1,AddGate_ry_inGap_16_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeinex...,0.181818,0.181818,0.181818
2,AddGate_rxx_inGap_16_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeinex...,0.045455,0.045455,0.045455
3,AddGate_rzz_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeinex...,0.590909,0.590909,0.590909
4,AddGate_h_inGap_9_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeinex...,0.090909,0.090909,0.090909
...,...,...,...,...,...
75,AddGate_h_inGap_11_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeinex...,0.045455,0.045455,0.045455
76,AddGate_rzz_inGap_9_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeinex...,0.590909,0.590909,0.590909
77,AddGate_y_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeinex...,0.136364,0.136364,0.136364
78,AddGate_y_inGap_9_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeinex...,0.136364,0.136364,0.136364
79,AddGate_ry_inGap_15_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeinex...,0.045455,0.045455,0.045455

,Program,path_to_mutant,best_exam_score,worst_exam_score,avg_exam_score
0,AddGate_ry_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeinex...,0.090909,0.090909,0.090909
1,AddGate_ry_inGap_16_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeinex...,0.136364,0.136364,0.136364
2,AddGate_rxx_inGap_16_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeinex...,0.045455,0.045455,0.045455
3,AddGate_rzz_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeinex...,0.954545,0.954545,0.954545
4,AddGate_h_inGap_9_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeinex...,0.090909,0.090909,0.090909
...,...,...,...,...,...
75,AddGate_h_inGap_11_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeinex...,0.045455,0.045455,0.045455
76,AddGate_rzz_inGap_9_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeinex...,0.772727,0.772727,0.772727
77,AddGate_y_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeinex...,0.5,0.5,0.5
78,AddGate_y_inGap_9_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeinex...,0.181818,0.181818,0.181818
79,AddGate_ry_inGap_15_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qpeinex...,0.045455,0.045455,0.045455