<h1 style="text-align: center;">HEISENBERG-BASED FAULT LOCALIZATION (HBFL)</h1>

<h2 style="text-align: center;">Download Initial Dependencies</h2>

In [1]:
import numpy as np
import pandas as pd
import json
import math
from tqdm import tqdm
from qiskit.quantum_info import SparsePauliOp, Operator, Pauli, Clifford
import qiskit.qasm2 as q2
from qiskit import QuantumCircuit
from IPython.display import display

from heisenbergUtilities import *

In [2]:
# from qiskit_aer import AerSimulator
# simulator = AerSimulator()

# print(simulator.available_devices())

<h2 style="text-align: center;">CONTROL PANEL</h2>

In [ ]:
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
#-------------------------------------------------------------------------GENERAL PARAMETERS---------------------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
ALG_NAME = "qaoa"
ORIGINAL_QASM = f"{ALG_NAME}_5_qubits.qasm"                                                 #| The original algorithm QASM circuit file name.                           
ORIGINAL_QASM_FOLDER = "SBFL_circuits/MQTBench/"                                            #| The folder containing the original QASM circuit file.                    
QASM_MUTANT_FOLDER = f"SBFL_circuits/QMutBenchMutants/Mutants_{ALG_NAME}_5_qubits/"         #| The folder containing all mutants related to the original QASM circuit.  
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
#-------------------------------------------------------------------------SB-QOPS PARAMETERS---------------------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
RUNS = 10                                                                                   #| Number of times SB-QOPS will run to find a failing or passing test case.            
SHOTS = 20000                                                                               #| Number of shots for SB-QOPS to use to create the compact program specification.     
EPOCH = 80                                                                                  #| Number of epochs SB-QOPS will run to navigate the search space of test cases.       
SBQOPS_TOL = 0.1                                                                            #| Tolerance value SB-QOPS uses to determine if a test case is failing or passing.     
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
#---------------------------------------------------------------------HEISENBERG SBFL PARAMETERS-----------------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
LAMBDA_PHASE = 2                                                                        #| The hyperparameter used to weight the phase change of the Pauli propagation
LAMBDA_CHANGE = 1                                                                         #| The hyperparameter used to weight the change of string of the Pauli propagation
LAMBDA_SIMILARITY = 1                                                                       #| The hyperparameter used to weight the similarity difference between current and target Pauli
ATOL = 1e-4                                                                                 #| The tolerance value used to prune negligible magnitudes during Pauli propagation.   
MAX_TERMS = 100                                                                             #| The maximum number of terms to keep during Pauli propagation. If None, use all.     
SEARCH_STEP = 3                                                                             #| The search step size used during Pauli propagation. If None, pauli-prop uses 4.     
VERBOSE = 1                                                                                 #| A boolean value to determine if the program should print out detailed information.  
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#

Generate the linked list of all operations that take place in the inverse circuit

In [4]:
"""
LinkedListNode: A class that holds information related to a gate in a quantum circuit. 

PROPERTIES:
    - value (String): The name of the quantum gate
    - depth (int): The depth of the gate in the circuit
    - count (Int): The probability that the gate will meaningfully change the Pauli string.
    - next (LinkedListNode): The next gate in the circuit

"""

class LinkedListNode:
    def __init__(self, name="Initial", depth=0, count=0,  next=None):
        self.value = name
        self.depth = depth
        self.next = next
        self.count = count

class LinkedList:
    def __init__(self):
        self.head = None

    def append(self, name, depth):
        new_node = LinkedListNode(name, depth)
        if not self.head:
            self.head = new_node
            return
        last_node = self.head
        while last_node.next:
            last_node = last_node.next
        last_node.next = new_node

    def mark(self, depth):
        current_node = self.head
        while current_node:
            if current_node.depth == depth:
                current_node.count += 1
                return
            current_node = current_node.next

    def reset(self):
        current_node = self.head
        while current_node:
            current_node.count = 0
            current_node = current_node.next

<h3>Download MQT Benchmark circuits.</h3>

We'll start with DJ, RealAmpRandom, and GHZ since SB-QOPS caught those mutants 100% of the time for 5 qubit circuits

<h3>Generate mutants.</h3>

We'll start with mutants that add an unnecessary gate, then add mutants that replace a certain gate later.

The mutants were downloaded from QMutBench, choosing specifically mutants that added a gate anywhere with 0-10% survival scores

In [5]:
correct_circuit = load_program(ORIGINAL_QASM, ORIGINAL_QASM_FOLDER).copy()
correct_list = LinkedList()
correct_list = construct_list(correct_list, correct_circuit, inverse=False)

<h2 style="text-align: center;"> SB-QOPS </h2>

This is where we will use SB-QOPS on a provided circuit and its mutants

For a single mutant, it took about 2 minutes to generate a 20 test suite (10 fail, 10 pass) on an RTX 4090 SUPER. It can only be run on a Linux environment since the AER Simulator does not support Windows

There are 113 mutants for the DJ algorithm in use: 226 minutes or 3 3/4 hours

There are 89 mutants for the GHZ algorithm in use: 178 minutes or about 3 hours

There are 125 mutants for the RealAmpRandom algorithm in use: 250 minutes or just over 4 hours

BUT this cell should only need to be run once per algorithm with mutants under test. After it saves to the csv file at the end, this cell can be commented out as to not accidentally run it again. 

In the future if we want to test this methodology on higher qubit circuits or other algorithms, we'll likely either want to reduce the number of tests in the suite or the number of mutants we're analyzing

In [6]:
# import QOPS as qops
# from QOPS_test import get_compact_program_specification_Z
# from pathlib import Path

# ga_result = pd.DataFrame(columns=['Program',"path_to_mutant",'catch_avg','avg_fitness','failing_testcases', 'passing_testcases'])
# program_history = {}

# #program_specification = The compact program specification. SB-QOPS needs this to generate failing test cases.
# # In a public-use environment, this would be provided by the user.
# program_specification = get_compact_program_specification_Z(correct_circuit, shots=SHOTS)

# #mutants = A python list of qiskit QuantumCircuit variables with a mutation in them
# mutants = []
# mutants_names = []
# root = Path(QASM_MUTANT_FOLDER)
# for qasm_mutant in root.rglob("*.qasm"):
#     mutants.append(load_program(qasm_mutant.name, QASM_MUTANT_FOLDER))
#     mutants_names.append(qasm_mutant.name)

# for mutant_index,mutant in enumerate(mutants):
#     tester = qops.Circuit_Tester(CUT=mutant)
#     tester.set_applicable_families_Z(program_specification)
#     mutants_per_run = []
#     fitness_per_run = []
#     failing_testcases_per_run = []
#     history_per_run = []

#     print("NOW RUNNING TO FIND FAILING TESTS")
#     #For a predefined number of attempts, try to find a set of failing test cases (output is above predefined tolerance)
#     for runs in range(RUNS):
#         killed = 0
#         pauli = {}
#         fitness = 0
#         for i in range(len(tester.applicable_families)):
#             best_function,testcase, history = tester.run_mealoneplusone(i, EPOCH)
#             if best_function > SBQOPS_TOL:
#                 killed = 1
#                 pauli = testcase
#                 fitness = best_function
#                 break
#         mutants_per_run.append(killed)
#         failing_testcases_per_run.append(pauli)
#         fitness_per_run.append(fitness)
#         history_per_run.append(history)

#     avg_score = np.mean(mutants_per_run)
#     avg_fitness = np.mean(fitness_per_run)

#     #Here is our new, modified algorithm from the SB-QOPS method that attempts to find passing test cases as well. We'll need them for SBFL
#     passing_testcases_per_run = []

#     print("NOW RUNNING TO FIND PASSING TESTS")
#     for runs in range(RUNS):
#         pauli = {}
#         fitness = 0
#         for i in range(len(tester.applicable_families)):
#             best_function, testcase, history = tester.run_reverse_mealoneplusone(i,EPOCH)
#             if best_function < SBQOPS_TOL:
#                 pauli = testcase
#                 break
#         passing_testcases_per_run.append(pauli)

#     #Replace static program file with "program_name" when ready to test fully
#     """
#     ga_result: A pandas dataframe with the following columns
#         Program: Name of the mutant quantum circuit file
#         Path_To_Mutant: Path to the mutant file
#         Catch_Avg: The average number of times the mutant was identified by SB-QOPS
#         Avg_Fitness: The average fitness of the search algorithm used. Higher usually indicates higher Catch_Avg
#         Failing_Testcases: A list of dicts indicating the set of Pauli strings and the weights that should be applied to generate a failing test case
#         Passing_Testcases: A list of dicts indicating the set of Pauli strings and the weights that should be applied to generate a passing test case
#     """
#     ga_result = pd.concat([pd.DataFrame([[mutants_names[mutant_index],QASM_MUTANT_FOLDER,avg_score,avg_fitness,json.dumps(failing_testcases_per_run), json.dumps(passing_testcases_per_run)]],columns=ga_result.columns),ga_result],ignore_index=True)
#     ga_result.to_csv(f'realamprandom_ga_result', index=False)

ga_result is a slightly altered pandas Dataframe with similar structure found in SB-QOPS's results folder. The differences are changing the column "Program" to be the name of the mutant file instead of the original quantum circuit, changing "Mutant" to be the path to the mutant file instead of being an arbitrary index value, and adding a passing_testcases column that returns Pauli strings and coefficients that generate passing tests.

Now we want to run SBFL using Heisenberg evolution trees on each circuit placed in ga_result

Evolution analysis tends to take about 5 minutes for 10 failing tests on a very complex algorithm such as QNN, so about 10 minutes for 20 total tests

DJ was a relatively small algorithm with few to no branching gates, so it only ended up taking about 5-6 minutes to evolve and analyze all 113 DJ mutants

About 890 minutes for GHZ, or 14.8 hours to evolve and analyze all 89 GHZ mutants

About 1250 minutes for RealAmpRandom, or 20.8 hours to evolve and analyze all 125 RealAmpRandom mutants

The runtime of this code segment is directly tied to the depth of the circuit being analyzed and the number of 2-branching gates such as rotation or phase gates that exist in the circuit.

This is something to note in the final paper. Regardless of accuracy this methodology takes a long time to run. If results are promising, then we'll want to look into the tradeoffs between EXAM and hyperparameters to speed this up. Primarily the atol, max_terms, and search_step parameters in the evolve_pauli_exact method in HeisenbergUtilities.py

<h2 style="text-align: center;">HEISENBERG EVOLUTIONS (PAULI PROPAGATION)</h2>

In [7]:
from heisenbergTree import *

ga_result = pd.read_csv(f'{ALG_NAME}_ga_result.csv')
tarantula_sbfl_result = pd.DataFrame(columns=['Program','path_to_mutant','exam_score'])
barinel_sbfl_result = pd.DataFrame(columns=['Program','path_to_mutant','exam_score'])
dstar_sbfl_result = pd.DataFrame(columns=['Program','path_to_mutant','exam_score'])
mutant_num = 0

#For each mutant of a circuit, run the SBFL implementation
for mutant, path in zip(ga_result.loc[:,"Program"], ga_result.loc[:,"path_to_mutant"]):
    print("Now evolving the following mutant: ", mutant)

    #Extract the raw test cases found for each mutant
    desired_failing_testcases = ga_result.loc[(ga_result["Program"] == mutant), ["failing_testcases"]]
    desired_passing_testcases = ga_result.loc[(ga_result["Program"] == mutant), ["passing_testcases"]]

    dict_failing_testcases = desired_failing_testcases.to_dict()
    dict_passing_testcases = desired_passing_testcases.to_dict()

    string_failing_testcases = dict_failing_testcases['failing_testcases'][mutant_num]
    string_passing_testcases = dict_passing_testcases['passing_testcases'][mutant_num]

    list_failing_testcases = json.loads(string_failing_testcases)
    list_passing_testcases = json.loads(string_passing_testcases)

    #Remove empty tests
    raw_failing_testcases = remove_null_tests(list_failing_testcases)
    raw_passing_testcases = remove_null_tests(list_passing_testcases)

    circuit_inverse = load_program(mutant,path).copy().inverse()  # Invert to track backward evolution of the operator
    forward_mutant = load_program(mutant, path).copy()

    #Create the linked list of operations in the inverse circuit
    operation_list = LinkedList()
    operation_list = construct_list(operation_list, circuit_inverse, True)

    forward_list = LinkedList()
    forward_list = construct_list(forward_list, forward_mutant, False)

    #Create list of nodes in linked list. Somewhere down the road remove the linked list implementation. It's unnecessary and giving me a headache
    node_list = []
    node = operation_list.head
    while node:
        node_list.append(node)
        node = node.next

    #Perform Pauli propagation (Heisenberg evolution) for all test cases. Returns a dataframe with all counts for all operations
    global_frame_fail = heisenberg_evolve(circuit_inverse, 
                                          operation_list, 
                                          raw_failing_testcases, 
                                          "fail", 
                                          LAMBDA_PHASE, 
                                          LAMBDA_CHANGE, 
                                          LAMBDA_SIMILARITY, 
                                          atol = ATOL, 
                                          max_terms = MAX_TERMS, 
                                          search_step = SEARCH_STEP)
    
    global_frame_pass = heisenberg_evolve(circuit_inverse, 
                                          operation_list, 
                                          raw_passing_testcases, 
                                          "pass", 
                                          LAMBDA_PHASE, 
                                          LAMBDA_CHANGE, 
                                          LAMBDA_SIMILARITY, 
                                          atol = ATOL, 
                                          max_terms = MAX_TERMS, 
                                          search_step = SEARCH_STEP)

    global_frame = pd.concat([global_frame_fail, global_frame_pass], ignore_index=True)

    global_frame = global_frame.drop(["Initial"],axis=1)
    if VERBOSE:
        display(global_frame)

    tarantula_scores = tarantula(global_frame)
    barinel_scores = barinel(global_frame)
    dstar_scores = dstar(global_frame)

    if VERBOSE:
        print("BARINEL SCORES")
        display(barinel_scores)
        print("TARANTULA SCORES")
        display(tarantula_scores)
        print("DSTAR SCORES")
        display(dstar_scores)
    
    # Here is where analysis of the methodology begins. 
    # We first extract the position of the erroneous gate by comparing it to the original MQT gate
    # NOTE: This method is intended for single-added gates for now. Other types of mutants will require other methods later
    error_gate_location = find_erroneous_gate(forward_mutant, correct_circuit)

    if VERBOSE:
        print("ERROR GATE LOCATION:")
        print(error_gate_location)

    # Calculate the EXAM score for Barinel by counting the number of gates we would have to observe before we reach the erroneous gate.
    gates_observed = 0
    barinel_exam_score = 0
    for col_name, col_date in barinel_scores.items():
        gates_observed += 1

        #Extract depth from column name
        gate_depth = int(col_name.split()[1])

        if gate_depth == error_gate_location:
            barinel_exam_score = gates_observed/(circuit_inverse.size())
            break

    # Calculate the EXAM score for Tarantula by counting the number of gates we would have to observe before we reach the erroneous gate.
    gates_observed = 0
    tarantula_exam_score = 0
    for col_name, col_date in tarantula_scores.items():
        gates_observed += 1

        #Extract depth from column name
        gate_depth = int(col_name.split()[1])

        if gate_depth == error_gate_location:
            tarantula_exam_score = gates_observed/(circuit_inverse.size())
            break

    # Calculate the EXAM score for DStar by counting the number of gates we would have to observe before we reach the erroneous gate.
    gates_observed = 0
    dstar_exam_score = 0
    for col_name, col_date in dstar_scores.items():
        gates_observed += 1

        #Extract depth from column name
        gate_depth = int(col_name.split()[1])

        if gate_depth == error_gate_location:
            dstar_exam_score = gates_observed/(circuit_inverse.size())
            break

    # Here we store the results from the HBFL analysis for both barinel and tarantula into a csv file for later analysis.
    barinel_sbfl_result = pd.concat([pd.DataFrame([[mutant,QASM_MUTANT_FOLDER,barinel_exam_score]],columns=barinel_sbfl_result.columns),barinel_sbfl_result],ignore_index=True)
    barinel_sbfl_result.sort_values(by=['exam_score'], ascending=False)
    barinel_sbfl_result.to_csv(f'{ALG_NAME}_barinel_sbfl_result.csv', index=False)

    tarantula_sbfl_result = pd.concat([pd.DataFrame([[mutant,QASM_MUTANT_FOLDER,tarantula_exam_score]],columns=tarantula_sbfl_result.columns),tarantula_sbfl_result],ignore_index=True)
    tarantula_sbfl_result.sort_values(by=['exam_score'], ascending=False)
    tarantula_sbfl_result.to_csv(f'{ALG_NAME}_tarantula_sbfl_result.csv', index=False)

    dstar_sbfl_result = pd.concat([pd.DataFrame([[mutant,QASM_MUTANT_FOLDER,dstar_exam_score]],columns=dstar_sbfl_result.columns),dstar_sbfl_result],ignore_index=True)
    dstar_sbfl_result.sort_values(by=['exam_score'], ascending=False)
    dstar_sbfl_result.to_csv(f'{ALG_NAME}_dstar_sbfl_result.csv', index=False)

    mutant_num += 1

if VERBOSE:
    display(barinel_sbfl_result)
    display(tarantula_sbfl_result)

Now evolving the following mutant:  AddGate_y_inGap_23_.qasm

100%|██████████| 10/10 [00:18<00:00,  1.86s/it]
100%|██████████| 10/10 [00:18<00:00,  1.86s/it]

,ry 23,y 22,ry 21,ry 20,ry 19,ry 18,cx 17,cx 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.672966,0.476569,1.179591,0.893927,2.291129,1.885169,2.027543,1.976690,1.961802,1.999661,...,0.288643,0.674824,0.769131,0.546005,0.240277,0.019246,0.023823,0.261490,0.000007,fail
1,0.633580,0.448677,1.235501,0.712118,1.792391,1.955925,2.091412,1.716144,1.657443,1.686632,...,0.224182,0.550116,0.591625,0.433785,0.216714,0.015403,0.019184,0.194335,0.000006,fail
2,0.622212,0.440627,1.279954,0.549914,1.315406,2.109780,2.340276,2.100459,1.955884,1.683323,...,0.205982,0.600449,0.603157,0.402844,0.180223,0.018436,0.019717,0.208038,0.000006,fail
3,0.690226,0.488792,1.385134,0.851970,2.061784,2.436842,2.618374,2.211791,2.355052,2.312164,...,0.271375,0.746097,0.799958,0.617708,0.307666,0.019078,0.025675,0.262429,0.000008,fail
4,0.372694,0.263928,0.861154,0.618990,1.514276,1.839159,2.081991,2.048568,2.218300,2.278984,...,0.306430,0.693569,0.786102,0.573294,0.260896,0.018363,0.025805,0.256333,0.000007,fail
5,0.617312,0.437157,1.232941,0.754792,1.514766,2.450855,2.769213,2.450721,2.373098,2.123554,...,0.291539,0.707415,0.740858,0.575458,0.268978,0.019398,0.024589,0.257404,0.000009,fail
6,0.557218,0.394601,1.366182,0.612053,1.871638,2.580139,2.707979,2.187734,1.924200,1.750619,...,0.235623,0.560886,0.561892,0.495808,0.252912,0.018570,0.019006,0.202907,0.000007,fail
7,0.669824,0.474344,1.318906,0.773198,2.045405,1.609124,1.708871,1.883707,1.583354,1.693860,...,0.284974,0.611845,0.640270,0.485129,0.246327,0.017508,0.020069,0.232883,0.000005,fail
8,0.543127,0.384622,1.083937,0.743447,1.920294,1.754790,1.836425,1.776362,1.727586,1.543027,...,0.273029,0.517793,0.589350,0.429254,0.198672,0.017457,0.019417,0.187018,0.000005,fail
9,0.634500,0.449329,1.300844,0.565605,1.522333,1.832290,1.951940,1.818234,1.813629,1.386257,...,0.149756,0.428768,0.445146,0.360081,0.189604,0.014627,0.015628,0.138636,0.000005,fail
10,0.590492,0.418165,1.118784,0.945593,1.765755,2.574005,2.803527,2.069614,1.732308,1.953190,...,0.375174,0.666213,0.734621,0.600997,0.300654,0.018343,0.023442,0.263883,0.000008,pass
11,0.493738,0.349647,1.397281,0.750722,2.146087,2.466337,2.503202,1.747947,1.556487,1.444048,...,0.178396,0.493778,0.449441,0.422503,0.238966,0.014888,0.014383,0.164536,0.000006,pass
12,0.612954,0.434071,1.341787,1.069475,1.860387,1.887622,2.065419,2.036741,1.811229,1.642826,...,0.277393,0.650579,0.632411,0.531108,0.273726,0.015769,0.018444,0.226295,0.000007,pass
13,0.412516,0.292128,1.264864,0.753129,1.929287,2.086954,2.106454,1.457304,1.799932,1.967555,...,0.217828,0.567641,0.645461,0.481831,0.232609,0.014073,0.021362,0.189723,0.000007,pass
14,0.481753,0.341159,0.750990,0.417130,1.452664,1.766103,2.029259,2.415800,2.437407,2.188107,...,0.197951,0.649367,0.665250,0.531880,0.284843,0.016835,0.023524,0.249266,0.000007,pass
15,0.667145,0.472447,1.438805,0.880469,2.127783,1.908231,2.083740,2.100091,2.027450,2.006910,...,0.252710,0.654125,0.699659,0.554395,0.305781,0.017322,0.024213,0.248083,0.000007,pass
16,0.615112,0.435599,1.191735,1.102359,1.605528,1.900732,2.039786,1.795412,1.538825,1.371015,...,0.282183,0.552128,0.588443,0.459708,0.220975,0.014264,0.019146,0.194855,0.000006,pass
17,0.659575,0.467086,0.934803,0.822063,2.207093,2.107900,2.270549,2.056019,2.141045,2.328470,...,0.284264,0.704157,0.775694,0.640532,0.320432,0.019813,0.025424,0.279035,0.000007,pass
18,0.340451,0.241095,1.283428,0.878909,2.039790,1.561093,1.540293,1.364622,1.324710,1.321787,...,0.280349,0.531687,0.526869,0.450678,0.203245,0.013805,0.016768,0.165368,0.000005,pass
19,0.505608,0.358052,1.084916,0.652826,1.530505,1.775136,1.992499,1.842584,2.044568,1.994641,...,0.251952,0.656825,0.682419,0.523258,0.250437,0.015025,0.022708,0.211455,0.000006,pass

BARINEL SCORES

,ry 23,y 22,ry 3,ry 12,ry 10,ry 9,cx 16,cx 15,ry 21,cx 17,...,cx 14,ry 0,ry 1,cx 7,cx 8,ry 19,cx 5,ry 4,ry 13,ry 20
sum,0.527838,0.527838,0.526534,0.521743,0.52039,0.519451,0.516441,0.515222,0.50908,0.508025,...,0.503265,0.502202,0.501021,0.498578,0.493502,0.488834,0.486283,0.473027,0.468913,0.461018

TARANTULA SCORES

,ry 23,y 22,ry 3,ry 12,ry 10,ry 9,cx 16,cx 15,ry 21,cx 17,...,cx 14,ry 0,ry 1,cx 7,cx 8,ry 19,cx 5,ry 4,ry 13,ry 20
sum,0.527838,0.527838,0.526534,0.521743,0.52039,0.519451,0.516441,0.515222,0.50908,0.508025,...,0.503265,0.502202,0.501021,0.498578,0.493502,0.488834,0.486283,0.473027,0.468913,0.461018

DSTAR SCORES

,cx 17,cx 16,ry 18,cx 15,cx 14,ry 19,ry 21,ry 12,ry 20,cx 6,...,y 22,ry 13,cx 8,ry 4,ry 1,ry 2,ry 3,ry 0,ry 10,ry 11
sum,15.585155,14.084455,13.929798,13.479236,12.073644,11.114712,6.874691,2.802472,2.740156,2.598012,...,1.313309,1.304766,0.508696,0.441772,0.397497,0.00444,0.003121,4.555514e-10,1.112000e-10,2.486037e-11

ERROR GATE LOCATION:
22
Now evolving the following mutant:  AddGate_ry_inGap_15_.qasm

100%|██████████| 10/10 [00:18<00:00,  1.85s/it]
100%|██████████| 10/10 [00:18<00:00,  1.83s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.573263,1.177970,0.829864,1.706371,2.117417,2.288321,2.195317,2.188994,1.838157,0.934988,...,0.271430,0.716533,0.688611,0.388645,0.164155,0.016579,0.016951,0.192233,0.000006,fail
1,0.678046,1.201107,0.751329,1.684392,1.557148,1.774241,2.205993,2.402339,2.033503,0.738891,...,0.216014,0.706916,0.703782,0.414284,0.189088,0.017949,0.018388,0.212257,0.000006,fail
2,0.439883,0.954118,0.849863,1.426851,1.222914,1.432433,1.840511,1.562079,1.677168,0.809513,...,0.297384,0.638870,0.581589,0.373125,0.152660,0.012437,0.013956,0.194704,0.000005,fail
3,0.641195,0.964315,0.774199,1.755224,2.348311,2.617909,2.496592,2.608109,2.128275,0.902128,...,0.261580,0.777158,0.817903,0.456356,0.181595,0.020766,0.020322,0.222527,0.000007,fail
4,0.536019,1.213944,0.545827,1.613153,1.384464,1.650903,2.369844,2.041481,1.615304,0.669580,...,0.192858,0.665527,0.595445,0.336982,0.150269,0.015373,0.015661,0.213199,0.000005,fail
5,0.446700,1.315594,0.650704,0.982459,1.679139,1.898092,2.086274,1.939785,1.676060,0.691005,...,0.212998,0.628288,0.568201,0.342687,0.157876,0.012564,0.014061,0.175450,0.000006,fail
6,0.649393,1.762412,0.778983,1.809093,2.762684,3.040922,2.739794,2.427765,2.079862,1.082483,...,0.254336,0.904369,0.763070,0.418062,0.178497,0.017639,0.018589,0.235030,0.000008,fail
7,0.338011,1.020590,0.374882,1.278973,1.701531,1.930316,1.899144,1.964937,1.588775,0.766372,...,0.136627,0.589628,0.542382,0.306713,0.160695,0.013159,0.013792,0.159810,0.000005,fail
8,0.529357,1.286488,0.806518,1.921729,2.493197,2.720345,2.413340,2.457205,2.236409,0.931914,...,0.259182,0.786677,0.810154,0.447835,0.196182,0.019225,0.020189,0.234748,0.000007,fail
9,0.456394,1.046702,0.415051,1.440967,1.604291,1.681585,1.689673,1.513650,1.303079,0.547640,...,0.108298,0.442241,0.402618,0.218805,0.090863,0.010615,0.011094,0.130485,0.000004,fail
10,0.441913,1.487327,0.867237,1.976426,1.663870,1.945398,2.720937,2.576802,2.590895,0.941828,...,0.333860,0.940623,0.879651,0.535799,0.245573,0.019295,0.021778,0.291277,0.000007,pass
11,0.473691,0.906182,0.620488,1.212882,1.296528,1.309070,1.109131,0.977131,0.842493,0.428321,...,0.161781,0.355629,0.331462,0.238225,0.104188,0.007481,0.008084,0.092882,0.000004,pass
12,0.509291,1.197367,0.830687,1.731807,1.885437,2.060715,1.880119,1.717851,1.686379,0.735004,...,0.235586,0.683615,0.665957,0.375790,0.153291,0.014827,0.016118,0.193934,0.000006,pass
13,0.395244,1.393403,0.927318,1.897363,2.320408,2.485731,2.043133,1.763902,1.655481,0.627856,...,0.313545,0.723194,0.720612,0.427778,0.180754,0.015342,0.016429,0.216873,0.000007,pass
14,0.441245,1.269867,0.722507,1.779586,1.880517,2.054571,2.169574,2.234287,2.139119,0.890903,...,0.240055,0.752441,0.741438,0.406733,0.169216,0.016916,0.018147,0.211720,0.000006,pass
15,0.563473,1.007250,0.599828,1.520472,1.935617,2.112542,1.952080,1.940097,2.089530,0.783362,...,0.262369,0.649344,0.722653,0.380506,0.147792,0.018607,0.018786,0.211692,0.000006,pass
16,0.455889,1.566807,0.926318,1.545788,1.899523,2.015871,1.791504,1.526302,1.168068,0.593473,...,0.294111,0.580740,0.545100,0.384316,0.169884,0.012878,0.012994,0.148540,0.000005,pass
17,0.303224,0.994396,0.444479,1.669854,2.020967,2.176737,1.820045,1.900200,2.005828,0.945486,...,0.147754,0.632502,0.587519,0.304191,0.127596,0.013278,0.014561,0.180083,0.000005,pass
18,0.584991,1.342425,1.051770,2.173917,2.085576,2.233279,2.297588,1.889558,1.716393,0.796857,...,0.367047,0.809806,0.721476,0.471311,0.195844,0.016367,0.017579,0.220703,0.000007,pass
19,0.624454,1.308623,0.766007,1.818722,1.687783,1.703583,1.426102,1.414801,1.061154,0.518186,...,0.183919,0.462726,0.432577,0.272858,0.100077,0.011434,0.011061,0.103835,0.000004,pass

BARINEL SCORES

,ry 10,cx 16,ry 11,cx 17,ry 9,ry 13,ry 14,ry 23,cx 15,ry 3,...,cx 7,ry 0,cx 6,ry 4,ry 19,cx 5,ry 22,ry 20,ry 21,cx 8
sum,0.540787,0.540533,0.537806,0.533129,0.529361,0.527092,0.526514,0.524542,0.517381,0.51632,...,0.509875,0.508639,0.504886,0.504301,0.502595,0.493733,0.489139,0.474085,0.466306,0.46534

TARANTULA SCORES

,ry 10,cx 16,ry 11,cx 17,ry 9,ry 13,ry 14,ry 23,cx 15,ry 3,...,cx 7,ry 0,cx 6,ry 4,ry 19,cx 5,ry 22,ry 20,ry 21,cx 8
sum,0.540787,0.540533,0.537806,0.533129,0.529361,0.527092,0.526514,0.524542,0.517381,0.51632,...,0.509875,0.508639,0.504886,0.504301,0.502595,0.493733,0.489139,0.474085,0.466306,0.46534

DSTAR SCORES

,cx 17,cx 16,cx 18,ry 19,cx 15,ry 20,ry 22,ry 13,ry 14,cx 7,...,ry 23,cx 5,cx 8,ry 1,ry 4,ry 2,ry 3,ry 0,ry 10,ry 11
sum,16.474006,15.943553,14.701358,12.418586,12.256884,8.927488,6.347033,4.275464,3.777112,2.833383,...,1.890416,0.994083,0.38973,0.327055,0.22688,0.002616,0.002408,3.489904e-10,1.606309e-10,3.726556e-11

ERROR GATE LOCATION:
14
Now evolving the following mutant:  AddGate_y_inGap_9_.qasm

100%|██████████| 10/10 [00:18<00:00,  1.87s/it]
100%|██████████| 10/10 [00:18<00:00,  1.85s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,y 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.529735,0.914180,0.513435,1.494468,1.438671,1.508945,1.412379,1.452486,1.360565,0.270369,...,0.101360,0.389154,0.388837,0.271244,0.130476,0.011241,0.013182,0.131471,0.000004,fail
1,0.480131,1.002727,0.733386,1.684496,1.879233,1.941929,1.700966,1.861687,1.902704,0.375263,...,0.138693,0.527480,0.514806,0.373365,0.190123,0.014001,0.017631,0.168537,0.000006,fail
2,0.489514,1.431856,0.906062,1.354664,2.228022,2.536692,2.344045,2.337492,1.979021,0.535119,...,0.159289,0.728148,0.776857,0.605220,0.282848,0.018904,0.023341,0.254838,0.000008,fail
3,0.655668,1.480974,0.720083,1.817005,1.756822,1.778960,1.633210,1.725980,1.310026,0.254484,...,0.117273,0.431364,0.432941,0.350940,0.183989,0.012602,0.013041,0.123092,0.000005,fail
4,0.544034,1.443689,0.893491,1.481816,2.081146,2.342332,2.330323,2.071759,1.920135,0.496687,...,0.162502,0.755513,0.737855,0.533507,0.251015,0.019075,0.023673,0.258639,0.000008,fail
5,0.629258,1.319064,0.726644,1.483117,1.512066,1.718434,2.112307,2.142254,1.714904,0.428414,...,0.149015,0.594561,0.587388,0.418571,0.193225,0.016023,0.018908,0.198972,0.000006,fail
6,0.487815,1.260776,0.824270,1.925939,1.792853,1.924631,2.062234,2.060881,1.929447,0.415501,...,0.149702,0.645892,0.588608,0.513778,0.248987,0.017402,0.018544,0.211249,0.000007,fail
7,0.686203,1.528040,0.873699,2.128043,2.512915,2.748012,2.538736,2.356065,2.233009,0.531121,...,0.177576,0.823312,0.798150,0.637398,0.307171,0.020638,0.025491,0.285882,0.000009,fail
8,0.591995,1.090084,0.770191,1.830080,2.093653,2.169641,1.744550,1.821072,1.845351,0.439689,...,0.132649,0.575843,0.586952,0.445845,0.203747,0.017596,0.019727,0.194691,0.000007,fail
9,0.670854,1.282987,0.825865,1.554128,1.788419,2.018699,2.327117,2.396926,2.231062,0.522497,...,0.159265,0.638085,0.665956,0.509087,0.260488,0.017952,0.021245,0.230645,0.000008,fail
10,0.427804,1.069742,0.865980,1.799595,2.006697,2.098651,1.587799,1.374540,1.541112,0.445660,...,0.103721,0.581914,0.607758,0.554009,0.286443,0.015253,0.019714,0.209617,0.000007,pass
11,0.419843,1.060914,0.810104,1.020201,1.379271,1.639618,1.773206,1.469471,1.587374,0.409441,...,0.113845,0.510783,0.544463,0.478722,0.225962,0.015416,0.017786,0.221782,0.000006,pass
12,0.464322,0.601569,0.457613,1.233252,1.380661,1.371931,1.001753,1.008542,1.076594,0.307141,...,0.064908,0.317662,0.341355,0.289414,0.151305,0.009705,0.012305,0.100812,0.000004,pass
13,0.589791,1.145746,0.897207,0.834595,1.698640,1.955890,1.621698,1.652594,1.745822,0.430761,...,0.117737,0.602984,0.687948,0.549872,0.249622,0.015300,0.022157,0.219147,0.000007,pass
14,0.471611,0.912068,0.943049,1.567366,1.314568,1.331585,1.358618,1.506552,1.289742,0.250180,...,0.105603,0.428769,0.448875,0.370087,0.168715,0.012533,0.013728,0.131379,0.000005,pass
15,0.490513,0.995185,1.062409,1.400413,1.460017,1.733445,1.858116,1.604212,1.720479,0.428540,...,0.110586,0.594550,0.637486,0.539503,0.253765,0.013732,0.021216,0.232394,0.000007,pass
16,0.513059,1.384317,0.796223,2.528370,1.947374,1.910629,1.752708,1.824309,1.690485,0.394457,...,0.133533,0.579312,0.587113,0.479457,0.244473,0.015871,0.019490,0.182268,0.000006,pass
17,0.560760,0.892460,0.597703,1.461848,1.881767,2.064604,1.940963,1.991680,2.065873,0.530498,...,0.134158,0.552638,0.609944,0.446692,0.225088,0.016484,0.020861,0.225303,0.000007,pass
18,0.467270,1.097686,0.604194,1.290061,1.279628,1.447176,1.523161,1.084767,0.997929,0.351661,...,0.085103,0.411490,0.403715,0.356513,0.196589,0.012207,0.013045,0.171549,0.000004,pass
19,0.352557,0.904789,0.589082,0.710966,1.214098,1.413281,1.538083,1.385103,1.376144,0.356531,...,0.101507,0.443258,0.463079,0.385486,0.195610,0.011485,0.014673,0.172490,0.000005,pass

BARINEL SCORES

,ry 12,ry 11,cx 16,y 8,ry 10,ry 22,cx 17,ry 13,ry 19,cx 15,...,ry 20,ry 3,cx 6,ry 2,ry 1,ry 14,cx 5,ry 4,ry 21,cx 9
sum,0.58159,0.579532,0.575791,0.574786,0.570201,0.55894,0.55876,0.558561,0.550814,0.549745,...,0.547501,0.54523,0.532717,0.526785,0.524368,0.522282,0.511484,0.506124,0.505307,0.486651

TARANTULA SCORES

,ry 12,ry 11,cx 16,y 8,ry 10,ry 22,cx 17,ry 13,ry 19,cx 15,...,ry 20,ry 3,cx 6,ry 2,ry 1,ry 14,cx 5,ry 4,ry 21,cx 9
sum,0.58159,0.579532,0.575791,0.574786,0.570201,0.55894,0.55876,0.558561,0.550814,0.549745,...,0.547501,0.54523,0.532717,0.526785,0.524368,0.522282,0.511484,0.506124,0.505307,0.486651

DSTAR SCORES

,cx 16,cx 18,cx 17,ry 19,cx 15,ry 20,ry 22,ry 21,ry 13,cx 7,...,ry 14,cx 9,ry 4,ry 1,y 8,ry 2,ry 3,ry 0,ry 11,ry 12
sum,16.429171,15.871536,15.729518,14.246974,13.531474,11.770549,8.107569,3.440812,2.967134,2.484411,...,1.310734,0.422368,0.415805,0.356916,0.189216,0.003729,0.0027,4.895455e-10,1.131442e-10,2.810863e-11

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_y_inGap_10_.qasm

100%|██████████| 10/10 [00:22<00:00,  2.26s/it]
100%|██████████| 10/10 [00:24<00:00,  2.40s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.559974,1.032841,0.607026,1.088324,2.519844,2.781010,2.057607,1.502444,1.317641,0.364042,...,0.257884,0.503605,0.491828,0.411845,0.208024,0.015908,0.015713,0.187406,0.000007,fail
1,0.584172,1.209094,0.811543,2.447674,2.487872,2.634281,2.294720,2.050693,1.798144,0.470716,...,0.322341,0.728163,0.727665,0.563669,0.269667,0.018742,0.023848,0.249453,0.000007,fail
2,0.441429,1.081774,0.765836,1.447242,2.342362,2.469293,1.738727,1.485075,1.483196,0.359195,...,0.246598,0.512778,0.514367,0.453994,0.212809,0.015391,0.016156,0.179492,0.000007,fail
3,0.651319,1.354253,0.968270,1.825291,2.861016,3.100220,2.522385,2.223285,1.855498,0.508931,...,0.357225,0.711611,0.719128,0.625770,0.312310,0.021098,0.021290,0.238538,0.000009,fail
4,0.432277,1.288709,0.724419,1.508989,2.689240,2.806872,1.660568,1.893581,1.740589,0.470613,...,0.221107,0.569107,0.640310,0.504198,0.246198,0.014329,0.020289,0.177094,0.000007,fail
5,0.567784,1.459207,1.029981,1.496151,2.343747,2.562205,1.889176,1.653553,1.929151,0.547626,...,0.311547,0.647313,0.662952,0.516089,0.217589,0.016311,0.021467,0.220220,0.000008,fail
6,0.560849,1.302630,0.635497,1.555134,1.980001,2.140066,1.849091,1.809048,1.600015,0.420092,...,0.143841,0.487700,0.519924,0.404658,0.193418,0.014682,0.017175,0.178712,0.000006,fail
7,0.670405,1.451277,0.643996,2.021488,2.221735,2.419833,2.296086,1.865026,1.446993,0.421700,...,0.302814,0.596181,0.595618,0.463695,0.224972,0.019809,0.019438,0.211595,0.000007,fail
8,0.360437,0.998700,0.664972,1.667916,2.298905,2.366075,1.570633,1.536803,1.445780,0.455631,...,0.294044,0.499161,0.487197,0.436213,0.230471,0.013733,0.015458,0.148072,0.000006,fail
9,0.605240,1.444693,1.007117,1.790224,2.819822,3.088734,2.445881,2.187830,1.963163,0.547615,...,0.307205,0.739891,0.751505,0.586064,0.275444,0.019590,0.023770,0.252040,0.000009,fail
10,0.396003,0.917196,0.617442,1.228374,1.751009,1.862128,1.334805,1.350068,1.038364,0.258336,...,0.261360,0.444002,0.411247,0.407294,0.187032,0.011404,0.013143,0.117221,0.000005,pass
11,0.411011,0.711523,0.508071,1.444276,1.160153,1.119160,0.841394,0.825222,1.009734,0.210817,...,0.138292,0.283493,0.313916,0.257894,0.120897,0.009555,0.010595,0.105216,0.000004,pass
12,0.506929,1.143210,0.835219,1.935591,2.132258,2.267358,1.809433,1.861828,1.936344,0.490248,...,0.220238,0.645667,0.652855,0.493858,0.223782,0.016377,0.019526,0.218316,0.000008,pass
13,0.482983,1.045773,0.968846,1.648421,1.676900,1.916832,2.252601,2.313337,1.955588,0.619346,...,0.333227,0.754228,0.794588,0.676765,0.324329,0.018838,0.025159,0.265271,0.000007,pass
14,0.557595,1.335742,0.917120,1.579405,2.389152,2.582594,2.108742,1.910962,1.829981,0.435807,...,0.288029,0.625329,0.628553,0.494907,0.242832,0.018417,0.020650,0.218541,0.000008,pass
15,0.605356,1.382312,0.925236,1.963806,1.804414,1.890919,1.808252,1.551397,1.637850,0.442713,...,0.314414,0.565594,0.611138,0.554017,0.305431,0.016095,0.020078,0.212319,0.000007,pass
16,0.527166,1.317338,1.000445,1.750151,2.162725,2.291045,1.982848,1.653290,1.550090,0.432545,...,0.283708,0.591889,0.581812,0.521179,0.247826,0.017101,0.017614,0.205610,0.000007,pass
17,0.606535,1.201060,0.782026,1.480132,2.470573,2.537495,1.717405,1.588262,1.499872,0.369817,...,0.254716,0.477549,0.524457,0.375407,0.180704,0.016575,0.016215,0.159931,0.000007,pass
18,0.630396,0.915508,0.823678,1.699630,2.440452,2.698062,2.185392,2.038312,2.146208,0.640461,...,0.323217,0.720092,0.801982,0.632175,0.307021,0.019123,0.026230,0.278629,0.000008,pass
19,0.390335,1.075589,0.714024,1.229056,2.173867,2.413074,1.759282,1.760547,2.004272,0.490780,...,0.256982,0.584215,0.624764,0.508741,0.235680,0.014939,0.020725,0.216418,0.000008,pass

BARINEL SCORES

,cx 18,ry 19,y 9,ry 10,ry 22,cx 17,ry 11,ry 0,cx 16,ry 3,...,ry 14,cx 8,cx 6,ry 13,ry 2,ry 1,cx 5,ry 4,cx 15,ry 21
sum,0.54995,0.549222,0.540721,0.537981,0.533334,0.533111,0.527763,0.521426,0.519311,0.517023,...,0.509785,0.508313,0.506851,0.506845,0.506071,0.505588,0.502223,0.501612,0.499576,0.492682

TARANTULA SCORES

,cx 18,ry 19,y 9,ry 10,ry 22,cx 17,ry 11,ry 0,cx 16,ry 3,...,ry 14,cx 8,cx 6,ry 13,ry 2,ry 1,cx 5,ry 4,cx 15,ry 21
sum,0.54995,0.549222,0.540721,0.537981,0.533334,0.533111,0.527763,0.521426,0.519311,0.517023,...,0.509785,0.508313,0.506851,0.506845,0.506071,0.505588,0.502223,0.501612,0.499576,0.492682

DSTAR SCORES

,cx 18,ry 19,cx 17,cx 16,ry 20,cx 15,ry 22,ry 21,ry 13,cx 6,...,ry 14,y 9,cx 8,ry 4,ry 1,ry 2,ry 3,ry 0,ry 11,ry 12
sum,22.018107,20.006192,14.859648,12.345151,10.935375,10.331439,7.571524,3.413561,2.347235,2.341636,...,1.448823,0.612287,0.60304,0.461912,0.347766,0.003716,0.002831,5.481907e-10,9.407265e-11,2.230999e-11

ERROR GATE LOCATION:
9
Now evolving the following mutant:  AddGate_x_inGap_4_.qasm

100%|██████████| 10/10 [00:24<00:00,  2.41s/it]
100%|██████████| 10/10 [00:25<00:00,  2.50s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,ry 5,ry 4,x 3,ry 2,ry 1,ry 0,pass/fail
0,0.586916,1.454547,0.719196,1.983913,2.108895,2.142709,1.743875,1.718678,1.380358,0.341791,...,0.506202,0.549913,0.402729,0.214142,0.015847,0.075568,0.016514,0.168626,0.000006,fail
1,0.578357,0.911494,0.579743,1.657608,1.837613,1.939727,1.433200,1.592002,1.633313,0.364231,...,0.433172,0.521815,0.430507,0.213695,0.014364,0.063633,0.017944,0.175259,0.000005,fail
2,0.558648,0.968914,0.976153,1.961910,1.782422,1.854070,1.510410,1.692824,1.745264,0.415273,...,0.587008,0.697010,0.578752,0.264790,0.015471,0.072555,0.022723,0.198042,0.000006,fail
3,0.584221,1.332797,0.909627,1.755572,1.812497,2.065239,2.051609,1.672918,1.734906,0.425355,...,0.665470,0.678620,0.547754,0.260128,0.015723,0.076330,0.022596,0.250123,0.000007,fail
4,0.521775,1.325064,0.903331,1.391121,1.962176,2.093385,1.824640,2.002925,1.691994,0.332061,...,0.604413,0.613878,0.462918,0.214808,0.015597,0.075341,0.019479,0.184114,0.000006,fail
5,0.646742,1.371825,0.849653,1.628287,1.902072,2.120106,2.199906,2.047400,2.239892,0.496445,...,0.666361,0.711190,0.563447,0.278832,0.017058,0.083832,0.024411,0.269737,0.000007,fail
6,0.492071,1.105977,0.657351,1.593150,2.388100,2.623514,2.286796,2.207181,2.172148,0.552149,...,0.713156,0.744498,0.636240,0.340625,0.018808,0.083541,0.023947,0.274363,0.000009,fail
7,0.618902,1.304339,0.691134,1.812580,2.084728,2.237761,2.112738,2.326632,2.126612,0.543091,...,0.658399,0.667298,0.494101,0.257068,0.015746,0.076658,0.021928,0.213908,0.000007,fail
8,0.722059,1.650666,0.951538,1.838519,1.705824,1.753693,1.597788,1.402751,1.096155,0.378047,...,0.455770,0.438179,0.392341,0.196505,0.015585,0.072510,0.014455,0.143652,0.000005,fail
9,0.553290,1.143124,0.739819,1.434737,1.879759,2.104882,2.180664,2.084919,1.768273,0.436092,...,0.641427,0.637322,0.488803,0.237347,0.016684,0.080108,0.020280,0.217766,0.000007,fail
10,0.420946,0.815013,0.609705,1.241472,1.431002,1.513372,1.094493,1.238381,1.173044,0.300330,...,0.397427,0.424313,0.308707,0.142840,0.007969,0.043255,0.013683,0.118473,0.000004,pass
11,0.381992,1.386358,0.803483,1.486139,2.127150,2.445481,2.617956,2.561462,1.890371,0.590586,...,0.813840,0.779119,0.679165,0.341791,0.018798,0.073695,0.022527,0.255777,0.000009,pass
12,0.426278,0.890264,0.920994,1.771797,1.511186,1.566454,1.483829,1.552899,1.501929,0.373063,...,0.546910,0.557623,0.435901,0.194716,0.014783,0.066764,0.017259,0.175076,0.000006,pass
13,0.311589,1.048453,0.796826,2.138736,2.425530,2.542487,1.846913,1.780108,2.021420,0.528162,...,0.646903,0.596033,0.515740,0.264612,0.012660,0.061177,0.019115,0.215210,0.000008,pass
14,0.371842,1.106383,0.632146,0.922408,1.622418,1.898125,1.874617,1.586845,1.565124,0.488315,...,0.522023,0.486470,0.431410,0.233348,0.012665,0.059824,0.015908,0.194546,0.000007,pass
15,0.455637,1.023517,0.758869,1.561237,1.355871,1.530697,1.817452,1.783641,1.892294,0.487763,...,0.581250,0.549144,0.428597,0.200761,0.015317,0.069385,0.018517,0.223635,0.000007,pass
16,0.562280,1.134736,1.110639,1.282431,1.912159,2.140048,1.804178,1.604972,1.627555,0.488746,...,0.603920,0.602359,0.489424,0.223664,0.014717,0.074601,0.018662,0.213518,0.000008,pass
17,0.409535,0.846825,0.731090,1.007838,1.781769,2.057822,1.803076,1.673249,1.754933,0.487264,...,0.573684,0.575963,0.517965,0.241725,0.013968,0.061190,0.019253,0.208272,0.000008,pass
18,0.493552,0.833572,0.833758,1.466978,1.501634,1.565935,1.339337,1.012882,0.945973,0.250522,...,0.440273,0.455948,0.372328,0.182152,0.012462,0.064130,0.013933,0.153457,0.000004,pass
19,0.401969,1.254973,0.759886,1.021653,1.330853,1.404527,1.132703,0.863876,0.911774,0.306940,...,0.371055,0.369641,0.327789,0.172459,0.010480,0.052212,0.011673,0.134480,0.000004,pass

BARINEL SCORES

,ry 23,ry 20,ry 22,x 3,ry 13,ry 11,ry 4,ry 2,cx 16,ry 12,...,cx 17,cx 18,cx 6,ry 1,ry 10,cx 8,ry 0,ry 21,ry 14,cx 9
sum,0.580573,0.550984,0.548642,0.548273,0.548179,0.54719,0.545917,0.545019,0.544903,0.539549,...,0.529744,0.528663,0.525807,0.525469,0.524921,0.518991,0.505417,0.500632,0.499001,0.494977

TARANTULA SCORES

,ry 23,ry 20,ry 22,x 3,ry 13,ry 11,ry 4,ry 2,cx 16,ry 12,...,cx 17,cx 18,cx 6,ry 1,ry 10,cx 8,ry 0,ry 21,ry 14,cx 9
sum,0.580573,0.550984,0.548642,0.548273,0.548179,0.54719,0.545917,0.545019,0.544903,0.539549,...,0.529744,0.528663,0.525807,0.525469,0.524921,0.518991,0.505417,0.500632,0.499001,0.494977

DSTAR SCORES

,cx 18,ry 19,cx 16,cx 17,cx 15,ry 20,ry 22,ry 21,ry 13,cx 7,...,ry 14,ry 5,cx 9,ry 1,x 3,ry 2,ry 4,ry 0,ry 11,ry 12
sum,15.289677,14.031731,13.699112,13.380242,12.235596,12.173491,7.7666,3.544011,2.605006,2.544983,...,1.283571,0.503374,0.475546,0.369268,0.054367,0.004103,0.002554,4.344953e-10,1.009929e-10,2.391364e-11

ERROR GATE LOCATION:
3
Now evolving the following mutant:  AddGate_x_inGap_9_.qasm

100%|██████████| 10/10 [00:22<00:00,  2.21s/it]
100%|██████████| 10/10 [00:20<00:00,  2.06s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,x 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.686710,1.470096,1.187025,1.904359,2.382435,2.467844,1.857218,1.748631,1.580909,0.452088,...,0.081439,0.615839,0.639825,0.551968,0.242985,0.020675,0.018951,0.198628,0.000008,fail
1,0.470857,0.923200,1.031104,1.957417,2.123712,2.274894,1.915997,1.982295,2.114442,0.607794,...,0.068711,0.696601,0.772349,0.647139,0.312939,0.017010,0.025212,0.258041,0.000008,fail
2,0.520704,1.098860,1.237115,1.455006,2.355007,2.679810,2.565340,2.383398,2.691288,0.680839,...,0.084957,0.892574,0.960554,0.755971,0.367356,0.022259,0.029402,0.341522,0.000010,fail
3,0.573367,1.615114,0.992660,2.104713,2.062165,2.242248,2.312322,2.224440,2.215484,0.599926,...,0.055794,0.730145,0.750663,0.591712,0.297905,0.019756,0.024379,0.267820,0.000008,fail
4,0.496162,1.265810,0.884918,1.935110,1.935046,1.945341,1.589993,1.410661,1.150677,0.425231,...,0.058781,0.492342,0.456214,0.407171,0.173235,0.016342,0.014287,0.141908,0.000006,fail
5,0.493690,1.113766,0.978310,1.975787,1.907878,1.955928,1.746167,1.297347,1.154936,0.380214,...,0.065307,0.569212,0.526627,0.430323,0.195933,0.014159,0.016345,0.174807,0.000006,fail
6,0.754535,1.608785,1.103499,1.771108,2.022003,2.291771,2.489937,2.118154,1.863676,0.595555,...,0.067237,0.748185,0.716347,0.613343,0.288498,0.021035,0.023264,0.271561,0.000008,fail
7,0.484154,0.854860,0.953602,1.260628,1.985275,2.343382,2.601805,2.367160,2.330340,0.558159,...,0.075288,0.861374,0.846499,0.659172,0.286287,0.020861,0.027024,0.309012,0.000009,fail
8,0.512818,1.241626,0.885927,1.773807,1.504965,1.684232,2.135525,1.650074,1.522384,0.488062,...,0.070957,0.668446,0.624416,0.526354,0.242793,0.019082,0.020420,0.237293,0.000006,fail
9,0.689909,1.318234,0.859313,2.691382,2.431953,2.387597,1.594236,1.668959,1.734400,0.429571,...,0.052425,0.537766,0.570430,0.411699,0.189361,0.019113,0.018416,0.175900,0.000007,fail
10,0.414718,0.879563,0.582298,1.568346,1.724331,1.968875,2.079747,1.733909,1.935718,0.436180,...,0.046988,0.608967,0.634869,0.481190,0.247552,0.016431,0.021755,0.258793,0.000007,pass
11,0.626797,1.352872,1.190783,2.057577,2.386647,2.597710,2.292715,2.240872,2.336825,0.554647,...,0.084877,0.793773,0.876590,0.693193,0.311768,0.022071,0.028518,0.291474,0.000010,pass
12,0.238796,0.630873,0.404465,0.888344,0.771365,0.966515,1.488412,1.632625,1.644772,0.371713,...,0.023301,0.477950,0.485175,0.363874,0.183111,0.010997,0.015625,0.185168,0.000005,pass
13,0.369373,1.398996,0.743019,1.702816,2.273589,2.460733,1.806114,1.788868,1.754259,0.482568,...,0.053911,0.654337,0.627601,0.526099,0.247482,0.014807,0.020017,0.209053,0.000007,pass
14,0.401818,1.345313,0.707739,1.669361,2.016534,2.235614,2.332509,2.299169,1.966580,0.617037,...,0.038625,0.677129,0.624129,0.557041,0.314595,0.014484,0.020193,0.228610,0.000007,pass
15,0.197211,0.634494,0.449781,0.654703,0.515967,0.608534,0.866945,0.687198,0.746184,0.162817,...,0.030594,0.291486,0.276551,0.239810,0.118841,0.007455,0.008634,0.110051,0.000003,pass
16,0.391656,1.451769,0.843703,1.262653,2.112520,2.331908,2.003500,2.156390,2.039113,0.478773,...,0.047376,0.665284,0.667452,0.516270,0.238324,0.014975,0.021212,0.218949,0.000008,pass
17,0.224534,0.913655,0.617806,0.934515,1.860781,2.090872,1.564801,1.521143,1.608476,0.443661,...,0.048169,0.574018,0.552601,0.454976,0.213977,0.011294,0.017346,0.182294,0.000007,pass
18,0.441255,1.156137,0.798594,1.504985,2.100265,2.198942,1.657854,1.910294,1.607918,0.529478,...,0.052788,0.538975,0.583702,0.508618,0.256332,0.013770,0.017988,0.162107,0.000007,pass
19,0.348398,1.082638,0.444030,1.146726,2.086346,2.188317,1.349147,1.045741,0.915845,0.387664,...,0.045784,0.366850,0.351861,0.348775,0.172563,0.012648,0.011441,0.127700,0.000005,pass

BARINEL SCORES

,ry 23,ry 21,x 8,cx 9,ry 20,ry 3,cx 6,cx 7,ry 1,cx 17,...,ry 19,ry 22,ry 0,cx 18,ry 4,ry 11,cx 15,cx 16,ry 12,ry 10
sum,0.608613,0.598583,0.590384,0.590153,0.58441,0.578001,0.547168,0.546693,0.546233,0.54401,...,0.537113,0.535622,0.53159,0.531309,0.529861,0.525987,0.525818,0.525579,0.523973,0.513864

TARANTULA SCORES

,ry 23,ry 21,x 8,cx 9,ry 20,ry 3,cx 6,cx 7,ry 1,cx 17,...,ry 19,ry 22,ry 0,cx 18,ry 4,ry 11,cx 15,cx 16,ry 12,ry 10
sum,0.608613,0.598583,0.590384,0.590153,0.58441,0.578001,0.547168,0.546693,0.546233,0.54401,...,0.537113,0.535622,0.53159,0.531309,0.529861,0.525987,0.525818,0.525579,0.523973,0.513864

DSTAR SCORES

,cx 18,cx 17,ry 19,ry 20,cx 16,cx 15,ry 22,ry 21,cx 6,cx 7,...,ry 10,cx 9,ry 4,ry 1,x 8,ry 2,ry 3,ry 0,ry 11,ry 12
sum,16.732604,15.778712,15.402075,15.157879,13.153759,12.691661,7.507751,6.094685,3.004582,2.965724,...,1.837916,0.902628,0.548246,0.471657,0.04427,0.004654,0.003571,5.701551e-10,9.948600e-11,2.418168e-11

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_x_inGap_5_.qasm

100%|██████████| 10/10 [00:23<00:00,  2.33s/it]
100%|██████████| 10/10 [00:20<00:00,  2.05s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,ry 5,x 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.529839,1.313929,1.137595,2.091407,1.835927,1.920644,1.733685,1.689298,1.704065,0.500861,...,0.593412,0.651886,0.569557,0.276701,0.078247,0.017661,0.020432,0.209293,0.000007,fail
1,0.598278,1.601987,0.848330,1.323908,2.825899,3.164796,2.625691,2.535909,2.393882,0.620079,...,0.769049,0.782450,0.599323,0.294347,0.080285,0.020652,0.025361,0.271717,0.000010,fail
2,0.631808,1.341440,0.915192,2.036771,1.872730,2.008428,1.978942,1.812068,2.065971,0.513865,...,0.692453,0.708385,0.625258,0.318748,0.080808,0.017431,0.024215,0.264714,0.000007,fail
3,0.557532,1.306141,0.891301,1.895812,2.115122,2.248969,2.072971,2.156285,2.032106,0.427336,...,0.697957,0.700437,0.517169,0.240912,0.068942,0.017080,0.021698,0.222118,0.000007,fail
4,0.523476,0.966522,0.802199,1.947026,2.243897,2.268834,1.589055,1.572392,1.718476,0.425099,...,0.550556,0.589824,0.478909,0.222886,0.068519,0.015414,0.019249,0.177118,0.000006,fail
5,0.675000,1.375955,0.974143,2.365205,2.369673,2.408800,1.922587,1.815552,1.577714,0.422861,...,0.588731,0.630214,0.498172,0.220971,0.070178,0.019559,0.019806,0.196411,0.000007,fail
6,0.589064,1.398499,0.538250,1.689364,1.810944,1.855027,1.534726,1.368072,1.217750,0.349623,...,0.416421,0.411456,0.298726,0.143086,0.046157,0.016061,0.013340,0.149463,0.000005,fail
7,0.649040,1.232591,0.843915,1.561560,2.410455,2.633810,2.120389,2.088864,2.335104,0.554666,...,0.693685,0.772843,0.560897,0.278536,0.076757,0.018657,0.025773,0.261349,0.000009,fail
8,0.527608,1.109940,1.021354,1.722985,2.250597,2.462854,2.105175,1.979340,2.183713,0.627003,...,0.707412,0.744262,0.624786,0.294790,0.084143,0.017874,0.025375,0.258668,0.000008,fail
9,0.309224,0.863386,0.734806,1.357208,1.280586,1.400150,1.533878,1.785707,1.751762,0.390564,...,0.528669,0.592216,0.457608,0.214552,0.057587,0.013522,0.018563,0.193777,0.000006,fail
10,0.477897,0.780196,0.532628,1.546789,1.324282,1.597185,2.228288,2.206767,2.081619,0.514764,...,0.666769,0.682179,0.559379,0.270485,0.071344,0.017978,0.023485,0.262759,0.000006,pass
11,0.495867,0.938456,0.995720,1.526744,1.789122,2.004376,2.016554,1.809663,1.906890,0.542474,...,0.706844,0.714327,0.573508,0.262926,0.079474,0.017778,0.023207,0.257509,0.000007,pass
12,0.650242,1.149803,0.993488,1.540232,2.427234,2.771795,2.828771,2.482420,2.180166,0.638438,...,0.871636,0.858966,0.710096,0.354867,0.090839,0.019794,0.026576,0.303216,0.000009,pass
13,0.422048,1.130643,0.612748,1.147470,1.758638,1.825771,1.371547,1.266480,0.949107,0.366161,...,0.340494,0.337481,0.328870,0.165119,0.046260,0.011192,0.010878,0.100057,0.000005,pass
14,0.369262,0.914158,0.604397,1.603453,2.029342,2.011781,1.108997,1.760770,2.130738,0.506165,...,0.442888,0.577942,0.457127,0.234154,0.055850,0.010362,0.020206,0.153612,0.000006,pass
15,0.539834,1.596671,1.143690,2.210307,2.267148,2.374420,2.026252,1.739641,1.558173,0.372183,...,0.626138,0.684149,0.566906,0.280392,0.075988,0.017983,0.020475,0.214136,0.000007,pass
16,0.387510,1.173798,0.734029,1.863008,2.239559,2.329670,1.841994,1.463275,1.538354,0.485441,...,0.574094,0.533942,0.521504,0.266747,0.072962,0.015565,0.018472,0.200780,0.000006,pass
17,0.582775,1.078410,0.519579,1.370504,1.690911,1.702999,1.180094,1.136741,0.978504,0.280804,...,0.297787,0.325623,0.272270,0.156811,0.038836,0.011394,0.010395,0.094749,0.000004,pass
18,0.529213,0.850493,1.093132,1.528397,1.896601,2.178440,2.039265,1.898321,2.071882,0.513789,...,0.681866,0.766499,0.646696,0.298228,0.083090,0.017916,0.024650,0.285707,0.000008,pass
19,0.367580,0.892135,0.956808,1.305823,1.919501,2.142897,2.016981,2.210167,2.116514,0.650769,...,0.701537,0.797467,0.682665,0.326042,0.085310,0.018472,0.024675,0.254319,0.000008,pass

BARINEL SCORES

,ry 22,ry 23,ry 20,ry 13,ry 3,ry 19,ry 0,cx 15,ry 11,cx 18,...,ry 2,cx 7,cx 9,cx 16,ry 1,cx 17,x 4,ry 14,cx 6,ry 5
sum,0.543572,0.536908,0.534913,0.532801,0.523282,0.520733,0.520157,0.520122,0.518697,0.516543,...,0.512944,0.511872,0.511406,0.511274,0.508979,0.507371,0.504134,0.497989,0.4958,0.489237

TARANTULA SCORES

,ry 22,ry 23,ry 20,ry 13,ry 3,ry 19,ry 0,cx 15,ry 11,cx 18,...,ry 2,cx 7,cx 9,cx 16,ry 1,cx 17,x 4,ry 14,cx 6,ry 5
sum,0.543572,0.536908,0.534913,0.532801,0.523282,0.520733,0.520157,0.520122,0.518697,0.516543,...,0.512944,0.511872,0.511406,0.511274,0.508979,0.507371,0.504134,0.497989,0.4958,0.489237

DSTAR SCORES

,cx 18,ry 19,cx 15,cx 17,cx 16,ry 20,ry 22,ry 21,ry 13,cx 7,...,ry 14,cx 9,ry 5,ry 1,x 4,ry 2,ry 3,ry 0,ry 11,ry 12
sum,16.177478,15.052142,13.094711,12.886012,12.639167,12.622876,7.632856,4.168724,2.86446,2.662928,...,1.570023,0.642015,0.497605,0.400796,0.047328,0.004481,0.002977,5.358687e-10,9.812089e-11,2.449576e-11

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_x_inGap_27_.qasm

100%|██████████| 10/10 [00:20<00:00,  2.05s/it]
100%|██████████| 10/10 [00:21<00:00,  2.10s/it]

,ry 23,x 22,ry 21,ry 20,ry 19,ry 18,cx 17,cx 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.545400,0.343396,1.028049,0.853362,1.224880,1.380316,1.626675,2.062110,1.947375,1.831096,...,0.221414,0.622360,0.623326,0.461573,0.218027,0.014447,0.020669,0.231159,0.000007,fail
1,0.592467,0.413863,1.376471,0.767474,1.434270,2.024220,2.169989,1.692665,1.403778,1.325241,...,0.276340,0.570552,0.525279,0.421158,0.202203,0.014737,0.017159,0.175038,0.000006,fail
2,0.524099,0.390112,1.142665,0.763529,1.636920,1.400367,1.537708,1.809870,1.712790,1.595870,...,0.248879,0.640647,0.596105,0.465408,0.222003,0.013649,0.018830,0.197796,0.000006,fail
3,0.590349,0.404871,1.220868,0.667701,1.692997,1.968288,2.090824,1.780539,1.670533,1.457931,...,0.258173,0.581730,0.522354,0.391482,0.177414,0.014492,0.016533,0.174427,0.000007,fail
4,0.484172,0.415266,1.195525,0.915824,1.586429,2.081359,2.158896,1.489580,1.195333,1.299941,...,0.359997,0.521030,0.502310,0.498266,0.239277,0.013457,0.016296,0.163064,0.000007,fail
5,0.443425,0.504140,1.502799,0.597259,1.481852,2.470252,2.727712,2.406498,2.183593,2.097306,...,0.246376,0.686798,0.663541,0.572665,0.300008,0.017577,0.022537,0.251576,0.000008,fail
6,0.498913,0.360513,1.101731,0.821550,1.926670,2.172996,2.247275,1.448396,1.314628,1.378856,...,0.279937,0.535407,0.577793,0.452146,0.198064,0.015015,0.018280,0.183075,0.000006,fail
7,0.554580,0.493118,1.603209,0.917518,1.607261,1.797964,2.075395,2.323577,1.790619,1.716585,...,0.224879,0.648992,0.549498,0.478695,0.243080,0.014936,0.018186,0.237359,0.000007,fail
8,0.646563,0.562833,1.711826,1.077380,2.214868,2.063813,2.048187,1.608187,1.625496,1.259987,...,0.263042,0.537540,0.488056,0.414715,0.185713,0.015483,0.015654,0.127303,0.000006,fail
9,0.688294,0.456113,1.591290,0.933498,1.999160,2.157077,2.241332,1.768259,1.661933,1.632757,...,0.221975,0.579707,0.542921,0.393707,0.191174,0.016765,0.016351,0.176625,0.000007,fail
10,0.719874,0.371947,1.191927,0.955503,2.145188,1.886052,1.895716,1.642588,1.535407,1.663454,...,0.303760,0.508897,0.585387,0.420808,0.190539,0.017721,0.018644,0.177147,0.000006,pass
11,0.511972,0.387784,1.156546,0.792950,1.955485,2.031112,2.088985,1.599442,1.443148,1.265590,...,0.285992,0.519622,0.525633,0.463300,0.215934,0.015657,0.017015,0.162857,0.000005,pass
12,0.303483,0.146307,0.434958,0.411893,0.879957,1.217646,1.422339,1.297219,1.399082,1.592372,...,0.242673,0.477087,0.560079,0.428580,0.209131,0.010767,0.018881,0.191594,0.000005,pass
13,0.555819,0.259674,0.922342,0.834033,1.599263,2.104316,2.160251,1.423308,1.492845,1.513724,...,0.272117,0.468655,0.535586,0.438324,0.223947,0.013672,0.015870,0.154296,0.000007,pass
14,0.356357,0.304406,0.804160,0.852358,1.330398,2.152092,2.397545,2.044076,1.574804,1.640353,...,0.359255,0.634035,0.596303,0.511972,0.239671,0.016755,0.019977,0.233732,0.000008,pass
15,0.587960,0.302182,0.990714,0.990638,1.734709,2.245653,2.435178,2.122851,2.269262,2.164315,...,0.275346,0.721989,0.764145,0.516958,0.222907,0.018266,0.024502,0.239217,0.000008,pass
16,0.457244,0.281246,0.955987,0.671209,1.109025,2.036617,2.225206,1.528901,1.719289,2.043231,...,0.231113,0.553923,0.648420,0.479172,0.227380,0.014179,0.020855,0.210479,0.000007,pass
17,0.381361,0.322435,1.014323,0.597386,1.172129,0.649344,0.714663,1.037332,0.639722,0.721216,...,0.160742,0.324446,0.268949,0.256046,0.127439,0.008787,0.009213,0.119123,0.000003,pass
18,0.426035,0.389635,1.196254,0.672530,1.335508,2.051948,2.236062,1.908943,1.506799,1.335975,...,0.281122,0.513673,0.518232,0.476049,0.256659,0.015576,0.017016,0.194104,0.000006,pass
19,0.343732,0.246184,0.716763,0.626634,1.377822,0.908788,1.008569,1.289359,1.287478,1.213406,...,0.170984,0.384273,0.442435,0.357767,0.178001,0.010986,0.014264,0.149065,0.000004,pass

BARINEL SCORES

,x 22,ry 21,ry 23,cx 7,cx 16,ry 19,ry 10,ry 11,ry 9,ry 18,...,ry 3,ry 12,ry 1,cx 5,ry 4,ry 13,cx 14,cx 6,ry 2,cx 8
sum,0.590567,0.589474,0.545261,0.537084,0.536397,0.534438,0.532575,0.532362,0.532111,0.530341,...,0.513983,0.51319,0.511444,0.511285,0.509998,0.509707,0.507186,0.506615,0.50597,0.501727

TARANTULA SCORES

,x 22,ry 21,ry 23,cx 7,cx 16,ry 19,ry 10,ry 11,ry 9,ry 18,...,ry 3,ry 12,ry 1,cx 5,ry 4,ry 13,cx 14,cx 6,ry 2,cx 8
sum,0.590567,0.589474,0.545261,0.537084,0.536397,0.534438,0.532575,0.532362,0.532111,0.530341,...,0.513983,0.51319,0.511444,0.511285,0.509998,0.509707,0.507186,0.506615,0.50597,0.501727

DSTAR SCORES

,cx 17,ry 18,cx 16,ry 19,cx 15,cx 14,ry 21,ry 20,cx 7,ry 12,...,cx 5,ry 13,cx 8,ry 4,ry 1,ry 2,ry 3,ry 0,ry 10,ry 11
sum,15.316458,13.960774,13.060172,11.462023,10.955944,9.669451,9.366516,3.972438,2.323675,2.165209,...,1.442669,1.101448,0.537646,0.391938,0.310736,0.003201,0.002235,4.345080e-10,7.948496e-11,1.887917e-11

ERROR GATE LOCATION:
22
Now evolving the following mutant:  AddGate_h_inGap_11_.qasm

100%|██████████| 10/10 [00:23<00:00,  2.33s/it]
100%|██████████| 10/10 [00:22<00:00,  2.26s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.476735,1.400299,0.973081,1.888026,2.120763,2.205776,1.888112,1.728669,1.481306,0.398488,...,0.809404,0.164300,0.579250,0.634502,0.236228,0.013371,0.017708,0.407989,0.000007,fail
1,0.478652,1.067734,0.642911,1.609451,1.429548,1.688910,2.221057,1.903436,1.880359,0.491901,...,1.436081,0.122481,0.610448,0.703716,0.249680,0.015392,0.017726,0.590992,0.000007,fail
2,0.737492,1.192728,0.717728,1.733299,2.033999,2.306952,2.307225,2.156468,2.297592,0.472511,...,1.377916,0.109780,0.650261,0.728226,0.243069,0.016168,0.016645,0.602746,0.000006,fail
3,0.546275,1.044720,0.671965,1.767855,1.634873,1.762252,1.867408,1.632513,1.662620,0.413138,...,1.198045,0.137526,0.582084,0.625903,0.229268,0.013600,0.015048,0.486735,0.000008,fail
4,0.407260,1.128775,0.728883,1.369760,2.439116,2.803034,2.796867,2.468799,2.320844,0.670308,...,1.853426,0.177377,0.774238,0.820177,0.283607,0.020255,0.022885,0.722184,0.000007,fail
5,0.507361,1.430387,0.956344,1.978786,1.940210,2.001900,1.612868,1.482241,1.450318,0.438678,...,0.777670,0.128243,0.482412,0.525897,0.195707,0.013956,0.017834,0.357976,0.000006,fail
6,0.411498,1.300950,0.853762,1.419428,1.788621,1.979900,1.824649,1.516022,1.230691,0.408638,...,0.858587,0.158261,0.513503,0.528870,0.211523,0.010808,0.017302,0.409428,0.000005,fail
7,0.434372,1.045629,0.689345,1.196453,1.618667,1.777586,1.777761,1.732927,1.675423,0.353006,...,1.224860,0.116872,0.562194,0.683348,0.231364,0.014512,0.014708,0.466112,0.000006,fail
8,0.633753,1.008794,0.664885,1.784787,1.535172,1.726793,2.168519,1.821936,1.298243,0.311957,...,1.071344,0.143498,0.584803,0.669845,0.225456,0.013481,0.014665,0.516586,0.000007,fail
9,0.528168,1.087498,0.990254,2.022147,2.100471,2.215090,1.849336,1.959210,1.781704,0.545529,...,1.062357,0.160812,0.604254,0.646823,0.222524,0.016768,0.015391,0.421450,0.000008,fail
10,0.423657,1.347379,0.571508,1.594647,2.138953,2.370823,1.981240,1.705195,1.397496,0.464325,...,1.018161,0.143397,0.558658,0.587086,0.206238,0.014568,0.018369,0.488533,0.000006,pass
11,0.598358,1.450612,0.737553,1.852853,2.304108,2.484066,2.375225,1.706883,1.404066,0.508503,...,1.345484,0.178271,0.604231,0.620191,0.231853,0.015369,0.022985,0.561790,0.000008,pass
12,0.441072,0.711898,0.640650,1.270868,1.592142,1.748546,1.575921,1.493683,1.492423,0.328175,...,0.822745,0.092482,0.468848,0.502092,0.179333,0.008938,0.011859,0.397603,0.000004,pass
13,0.659782,1.082189,0.884383,2.002882,2.382749,2.491870,2.007550,1.700206,1.590854,0.449769,...,1.253163,0.208114,0.602427,0.641409,0.248880,0.015283,0.018322,0.475857,0.000009,pass
14,0.290773,1.143139,0.706604,1.302226,1.316495,1.472936,1.500191,1.455473,1.559013,0.419012,...,1.017868,0.096972,0.442597,0.500151,0.167713,0.014102,0.014528,0.377732,0.000005,pass
15,0.484659,1.255642,0.786126,1.552242,1.683542,1.877342,1.848924,1.638404,1.476533,0.446951,...,1.126713,0.138051,0.472038,0.526906,0.179258,0.013728,0.016259,0.432394,0.000006,pass
16,0.611731,1.501299,1.075969,1.430340,2.136037,2.382745,2.193370,1.836058,1.625973,0.403910,...,1.338163,0.205025,0.595627,0.633813,0.246459,0.017443,0.019514,0.490623,0.000006,pass
17,0.548885,1.389074,0.619324,2.040748,1.961088,2.117014,2.263722,1.977519,1.633352,0.425089,...,1.312459,0.120444,0.656316,0.738500,0.247782,0.014036,0.018411,0.594984,0.000008,pass
18,0.404944,0.902217,0.480494,1.002820,1.233431,1.369654,1.391018,1.134089,1.031115,0.289638,...,0.709549,0.086985,0.358004,0.382470,0.128517,0.011063,0.010874,0.312501,0.000003,pass
19,0.470442,1.062375,0.741633,1.237021,1.116210,1.232314,1.293302,1.039144,1.257520,0.213730,...,0.701987,0.134710,0.336837,0.377651,0.160107,0.008400,0.009282,0.258888,0.000003,pass

BARINEL SCORES

,cx 5,cx 15,ry 12,cx 16,ry 13,ry 4,cx 6,ry 0,ry 14,ry 1,...,cx 17,ry 20,cx 8,ry 21,ry 2,cx 18,ry 23,ry 19,cx 7,ry 22
sum,0.54376,0.541378,0.541245,0.539831,0.538677,0.538418,0.538403,0.535495,0.532831,0.531542,...,0.524305,0.523136,0.52293,0.521308,0.514392,0.511507,0.511255,0.510638,0.502603,0.497064

TARANTULA SCORES

,cx 5,cx 15,ry 12,cx 16,ry 13,ry 4,cx 6,ry 0,ry 14,ry 1,...,cx 17,ry 20,cx 8,ry 21,ry 2,cx 18,ry 23,ry 19,cx 7,ry 22
sum,0.54376,0.541378,0.541245,0.539831,0.538677,0.538418,0.538403,0.535495,0.532831,0.531542,...,0.524305,0.523136,0.52293,0.521308,0.514392,0.511507,0.511255,0.510638,0.502603,0.497064

DSTAR SCORES

,cx 17,cx 18,cx 16,ry 19,cx 15,ry 20,cx 8,ry 22,ry 21,cx 5,...,ry 1,ry 14,ry 9,ry 4,cx 7,ry 2,ry 3,ry 0,ry 11,ry 12
sum,14.514381,14.178853,13.183568,12.47107,11.921348,11.121784,6.595936,6.274237,3.609252,2.780709,...,1.72486,1.454387,1.146357,0.451943,0.176597,0.002841,0.002171,4.370816e-10,1.009381e-10,2.110470e-11

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_ry_inGap_5_.qasm

100%|██████████| 10/10 [00:22<00:00,  2.27s/it]
100%|██████████| 10/10 [00:20<00:00,  2.07s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,ry 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.644987,1.467914,0.777291,1.481353,2.122407,2.331712,2.128171,1.873192,1.357695,0.342753,...,0.541625,0.516653,0.453815,0.245810,0.091206,0.015770,0.015896,0.180019,0.000007,fail
1,0.337237,1.227031,0.978966,1.091225,1.392432,1.656568,1.991297,2.023633,1.942018,0.520264,...,0.726579,0.724202,0.640235,0.297578,0.109383,0.014082,0.023483,0.243446,0.000007,fail
2,0.715735,1.352878,0.958661,2.180838,1.971528,1.932540,1.355445,1.428392,1.348447,0.256466,...,0.472043,0.551413,0.408687,0.197655,0.072435,0.014892,0.016605,0.158897,0.000005,fail
3,0.506512,1.005261,0.701225,1.895480,1.718043,1.827834,1.856688,1.618001,1.463424,0.368011,...,0.546819,0.551964,0.501656,0.243076,0.087943,0.019047,0.017524,0.211990,0.000006,fail
4,0.589619,1.270237,0.921060,1.814014,2.370889,2.547660,2.144866,2.218509,2.261128,0.561621,...,0.755047,0.779166,0.641501,0.306167,0.113234,0.017727,0.025450,0.253982,0.000008,fail
5,0.597512,1.227212,0.771400,1.443819,2.413887,2.646625,2.253366,1.850510,1.866563,0.476998,...,0.641019,0.668893,0.500548,0.238585,0.090514,0.020702,0.021208,0.254635,0.000008,fail
6,0.707953,1.624640,0.987067,2.292472,1.844153,1.972404,2.073242,2.055499,1.993711,0.546217,...,0.717073,0.774664,0.626326,0.316223,0.115958,0.018066,0.026161,0.255124,0.000007,fail
7,0.466076,1.156576,0.667960,0.997292,1.973409,2.285611,2.080929,1.761123,2.018135,0.454946,...,0.640789,0.644211,0.523301,0.248302,0.092788,0.015210,0.021916,0.254028,0.000009,fail
8,0.514385,1.065033,0.774673,1.506663,1.693468,1.980737,2.221127,2.275213,2.192394,0.440814,...,0.734347,0.801101,0.608119,0.295601,0.112101,0.017178,0.025944,0.275631,0.000008,fail
9,0.677176,1.717349,0.911784,2.645318,1.983795,1.907924,1.512952,1.319783,1.193203,0.392180,...,0.439482,0.431616,0.350325,0.179061,0.069073,0.014928,0.014675,0.134454,0.000005,fail
10,0.549796,1.578137,0.836489,1.639504,2.200649,2.444492,2.309612,1.788375,1.673745,0.504926,...,0.749841,0.660425,0.494167,0.243769,0.088725,0.016239,0.020726,0.246370,0.000007,pass
11,0.373790,0.649128,0.602368,1.299721,1.753835,2.022207,2.024371,1.817629,1.891572,0.451669,...,0.658862,0.628263,0.524253,0.254797,0.094834,0.014767,0.020778,0.250780,0.000007,pass
12,0.364408,0.656699,0.577851,1.284691,1.649849,1.740919,1.438241,1.552788,1.704480,0.379423,...,0.456828,0.479411,0.366775,0.166122,0.065077,0.013372,0.017511,0.158794,0.000006,pass
13,0.500845,1.060353,0.597481,1.155006,1.569371,1.681358,1.575733,1.500480,1.173264,0.263904,...,0.465641,0.442857,0.304727,0.149646,0.058328,0.012214,0.013597,0.134760,0.000005,pass
14,0.584665,1.216028,0.924888,1.637456,1.242327,1.417930,1.618711,1.457727,1.558944,0.408337,...,0.545687,0.597091,0.543639,0.281819,0.103188,0.013933,0.019627,0.221497,0.000006,pass
15,0.466038,0.897979,0.629954,1.256815,1.837466,2.052503,1.908916,2.018857,1.804391,0.430122,...,0.572838,0.587206,0.430292,0.203739,0.079232,0.013519,0.019087,0.186250,0.000007,pass
16,0.420897,0.689888,0.600617,1.176060,1.603471,1.700670,1.395430,1.272987,1.321154,0.277687,...,0.449515,0.475013,0.346391,0.163863,0.061638,0.012948,0.016087,0.164706,0.000005,pass
17,0.337980,1.049858,0.666123,1.348653,1.438930,1.538755,1.304415,1.222264,1.326249,0.314367,...,0.436540,0.453955,0.372736,0.198510,0.070950,0.010258,0.014331,0.165501,0.000005,pass
18,0.327218,0.597071,0.458121,1.292291,1.638297,1.709947,1.198090,1.333198,0.899876,0.228390,...,0.343137,0.345548,0.330361,0.176308,0.064291,0.009553,0.010632,0.093579,0.000004,pass
19,0.464065,1.432568,0.803181,1.807763,2.064322,2.115550,1.451648,1.145630,1.053267,0.428869,...,0.442692,0.400184,0.324545,0.179298,0.065891,0.013742,0.011599,0.137580,0.000005,pass

BARINEL SCORES

,cx 9,ry 22,ry 23,cx 6,ry 3,ry 2,ry 5,cx 7,ry 4,ry 1,...,ry 13,cx 8,cx 17,ry 0,ry 11,ry 10,ry 12,ry 14,ry 19,cx 18
sum,0.574435,0.571625,0.567384,0.565464,0.562146,0.560198,0.559987,0.559664,0.559316,0.558059,...,0.549215,0.548218,0.54733,0.546623,0.545103,0.544049,0.543429,0.541786,0.534064,0.533726

TARANTULA SCORES

,cx 9,ry 22,ry 23,cx 6,ry 3,ry 2,ry 5,cx 7,ry 4,ry 1,...,ry 13,cx 8,cx 17,ry 0,ry 11,ry 10,ry 12,ry 14,ry 19,cx 18
sum,0.574435,0.571625,0.567384,0.565464,0.562146,0.560198,0.559987,0.559664,0.559316,0.558059,...,0.549215,0.548218,0.54733,0.546623,0.545103,0.544049,0.543429,0.541786,0.534064,0.533726

DSTAR SCORES

,cx 18,cx 17,ry 19,cx 16,cx 15,ry 20,ry 22,ry 21,cx 7,ry 13,...,ry 14,cx 9,ry 5,ry 1,ry 4,ry 2,ry 3,ry 0,ry 11,ry 12
sum,15.647577,14.675569,14.06102,13.51809,12.744479,12.593944,8.67374,4.276434,2.755391,2.623228,...,1.388981,0.672526,0.54876,0.419921,0.084758,0.004292,0.002773,4.800430e-10,9.824277e-11,2.189049e-11

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_x_inGap_26_.qasm

100%|██████████| 10/10 [00:21<00:00,  2.16s/it]
100%|██████████| 10/10 [00:20<00:00,  2.08s/it]

,ry 23,ry 22,x 21,ry 20,ry 19,ry 18,cx 17,cx 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.412096,1.041749,0.356859,0.729056,1.669160,1.629435,1.731364,1.888449,1.760117,1.353193,...,0.231264,0.530366,0.497065,0.404445,0.186288,0.015776,0.016449,0.167932,0.000006,fail
1,0.669507,1.186449,0.481352,0.967616,1.664588,2.189604,2.350434,2.084107,2.130417,2.060448,...,0.342497,0.685780,0.717208,0.540216,0.227583,0.019801,0.023758,0.218634,0.000007,fail
2,0.447141,1.122100,0.407656,0.836584,1.321749,1.802172,1.873724,1.416349,1.141250,1.230441,...,0.293868,0.447356,0.446682,0.408920,0.202652,0.012197,0.014903,0.149511,0.000006,fail
3,0.705181,1.325377,0.449066,1.012810,1.724188,2.659221,2.817550,2.191893,2.002908,2.002633,...,0.267370,0.666179,0.683448,0.567584,0.257828,0.018861,0.022670,0.240935,0.000009,fail
4,0.584117,1.271744,0.318478,0.710912,1.694914,1.812998,1.963434,1.928676,1.914194,1.579718,...,0.191000,0.567576,0.555007,0.409972,0.189305,0.014818,0.018690,0.177891,0.000006,fail
5,0.564199,1.093668,0.365757,0.757492,1.820350,2.156607,2.351603,2.356348,2.061993,1.578057,...,0.273059,0.665989,0.610619,0.453362,0.208686,0.019852,0.019399,0.218523,0.000007,fail
6,0.567615,1.337644,0.505437,1.155498,1.802141,2.006681,2.064398,1.565429,1.325030,1.454718,...,0.352361,0.587867,0.616976,0.527049,0.239418,0.017461,0.019416,0.205154,0.000006,fail
7,0.619339,1.236942,0.365119,0.842035,2.201416,2.002024,2.163418,2.304459,2.311517,2.307876,...,0.206860,0.738571,0.735030,0.528871,0.251878,0.017983,0.025087,0.266508,0.000008,fail
8,0.424593,0.842796,0.347184,0.681300,1.442666,1.767585,1.931522,1.596048,1.397549,1.348241,...,0.236520,0.495300,0.471880,0.394831,0.164606,0.013192,0.015829,0.171684,0.000006,fail
9,0.459547,0.990378,0.402019,0.832983,1.525185,1.503131,1.626872,1.390417,1.357528,1.503123,...,0.241740,0.489921,0.551906,0.484239,0.225389,0.012827,0.018613,0.190253,0.000006,fail
10,0.340929,0.767940,0.289589,0.533137,1.262975,1.180802,1.294359,1.385775,1.147861,0.885035,...,0.199276,0.361000,0.353847,0.337076,0.174460,0.010601,0.011316,0.128189,0.000004,pass
11,0.382569,1.270256,0.361816,0.837749,1.288408,1.660602,1.756435,1.548170,1.297426,1.266840,...,0.240082,0.476517,0.452213,0.388926,0.211890,0.011079,0.015321,0.153259,0.000005,pass
12,0.441565,0.681312,0.254771,0.562097,1.381866,1.735220,1.997297,2.153713,2.241485,2.390371,...,0.180460,0.674173,0.739602,0.538797,0.294289,0.015258,0.025239,0.273108,0.000007,pass
13,0.394775,0.794465,0.225443,0.465021,1.337691,1.497498,1.604595,1.476338,1.621125,1.361630,...,0.178800,0.467977,0.505324,0.369216,0.178204,0.012536,0.015446,0.152450,0.000005,pass
14,0.394696,0.673640,0.259764,0.480816,1.320089,1.387524,1.482517,1.434689,1.468541,1.002760,...,0.178498,0.389869,0.417988,0.322058,0.145147,0.014020,0.012464,0.129971,0.000004,pass
15,0.491802,1.442073,0.424086,0.907547,1.386827,1.965286,2.203863,2.195554,1.756429,1.792052,...,0.298792,0.662432,0.653640,0.588400,0.307502,0.018323,0.020747,0.258977,0.000007,pass
16,0.664790,1.528811,0.276189,0.655402,1.329835,2.445781,2.820340,2.765699,2.393921,2.045615,...,0.234795,0.779216,0.687211,0.515768,0.255450,0.019609,0.021629,0.270010,0.000009,pass
17,0.431498,0.795119,0.266197,0.601685,0.885574,0.430307,0.487835,0.922962,0.823741,0.769428,...,0.161606,0.283286,0.282160,0.234051,0.106064,0.008268,0.010289,0.097756,0.000002,pass
18,0.488008,1.507713,0.241402,0.625676,2.434872,1.640279,1.757611,1.995351,1.944689,1.898725,...,0.105187,0.624117,0.574527,0.446481,0.245362,0.013014,0.021225,0.224349,0.000005,pass
19,0.383272,1.178634,0.321281,0.592487,1.547134,1.782201,1.929898,1.599378,1.439136,1.746840,...,0.251560,0.564612,0.533494,0.483471,0.245925,0.013567,0.017794,0.208517,0.000007,pass

BARINEL SCORES

,x 21,ry 20,cx 8,ry 18,ry 23,cx 17,ry 3,ry 19,ry 0,ry 13,...,cx 5,cx 7,ry 12,cx 14,cx 15,ry 22,cx 16,ry 1,ry 10,ry 4
sum,0.577924,0.576572,0.565103,0.553949,0.552671,0.546318,0.544297,0.543346,0.536785,0.532281,...,0.527687,0.526515,0.526287,0.519937,0.518907,0.51831,0.51719,0.514146,0.504006,0.498765

TARANTULA SCORES

,x 21,ry 20,cx 8,ry 18,ry 23,cx 17,ry 3,ry 19,ry 0,ry 13,...,cx 5,cx 7,ry 12,cx 14,cx 15,ry 22,cx 16,ry 1,ry 10,ry 4
sum,0.577924,0.576572,0.565103,0.553949,0.552671,0.546318,0.544297,0.543346,0.536785,0.532281,...,0.527687,0.526515,0.526287,0.519937,0.518907,0.51831,0.51719,0.514146,0.504006,0.498765

DSTAR SCORES

,cx 17,ry 18,cx 16,ry 19,cx 15,cx 14,ry 22,ry 20,ry 12,cx 6,...,ry 13,x 21,cx 8,ry 4,ry 1,ry 2,ry 3,ry 0,ry 10,ry 11
sum,15.94078,14.825748,12.756552,11.76715,11.588087,10.714346,6.350599,4.470499,2.294234,2.279136,...,1.414796,1.237674,0.577879,0.381291,0.338597,0.003731,0.002614,4.318484e-10,8.138204e-11,2.074671e-11

ERROR GATE LOCATION:
21
Now evolving the following mutant:  AddGate_ry_inGap_21_.qasm

100%|██████████| 10/10 [00:24<00:00,  2.41s/it]
100%|██████████| 10/10 [00:22<00:00,  2.24s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,ry 18,cx 17,cx 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.504151,1.468817,0.977924,0.951824,1.279234,2.268592,2.623168,3.208072,2.871072,2.315881,...,0.864113,1.152139,0.883872,0.572140,0.330242,0.027937,0.034854,0.289568,0.000009,fail
1,0.532862,1.288858,1.030724,0.965031,1.554334,2.182255,2.275115,2.012821,1.493824,1.332895,...,1.090927,0.961512,0.623904,0.411458,0.259687,0.023773,0.025091,0.168741,0.000007,fail
2,0.743480,1.605221,1.167586,1.117516,1.696835,2.963621,3.178162,2.857294,2.151460,1.614326,...,1.191111,1.166892,0.786703,0.662074,0.420285,0.032714,0.031528,0.233144,0.000007,fail
3,0.504267,1.160659,1.048827,0.947045,1.929399,1.934892,2.092914,2.405166,2.025965,1.738377,...,1.279376,1.113116,0.627979,0.557044,0.393790,0.024715,0.032428,0.250768,0.000007,fail
4,0.645827,1.414003,0.881837,0.859841,1.923982,2.039552,2.037445,1.663814,1.379277,1.325675,...,0.736493,0.833360,0.659129,0.331300,0.151951,0.024110,0.020994,0.137814,0.000005,fail
5,0.678326,1.211085,0.940769,0.884602,1.982436,1.641997,1.660018,2.060912,1.662786,1.464140,...,0.912063,0.861572,0.625762,0.424548,0.258627,0.024019,0.023511,0.180716,0.000006,fail
6,0.506704,1.389155,1.092159,1.014490,1.828160,2.147693,2.241390,2.144686,1.607879,1.569863,...,1.070136,1.066046,0.732604,0.597468,0.366061,0.023596,0.028427,0.201080,0.000006,fail
7,0.599323,1.429864,1.144223,1.127723,1.590398,1.942420,2.079051,2.201165,1.686484,1.603963,...,0.836514,0.914492,0.764371,0.578814,0.343839,0.023750,0.027404,0.194798,0.000008,fail
8,0.589674,1.376982,1.088524,1.008177,1.860153,2.102445,2.269566,2.589146,1.986918,1.504136,...,1.194482,1.160026,0.765532,0.638786,0.412091,0.029477,0.030013,0.234063,0.000006,fail
9,0.579537,1.194877,0.961720,0.911702,1.848058,1.877665,1.985830,2.043386,1.763093,1.646462,...,1.046179,0.960429,0.722373,0.515407,0.325997,0.026663,0.025708,0.209372,0.000006,fail
10,0.555551,0.802414,0.703281,0.685047,1.112328,1.495762,1.548163,1.537095,1.134911,0.866716,...,0.619386,0.702717,0.518548,0.412783,0.226642,0.020645,0.019491,0.119058,0.000003,pass
11,0.460819,0.817797,0.660868,0.591621,1.017323,1.817470,1.866446,1.386399,1.167043,1.310972,...,0.655281,0.609289,0.430782,0.303306,0.234206,0.015333,0.019230,0.137483,0.000005,pass
12,0.447707,0.941854,0.687540,0.622905,0.805623,1.204394,1.497263,2.286311,2.165308,1.988291,...,0.734573,0.854487,0.645039,0.486254,0.273715,0.020862,0.027372,0.233657,0.000007,pass
13,0.490054,1.215996,0.558318,0.525940,1.540178,1.901982,2.004863,1.788535,1.633844,1.816230,...,0.640779,0.817943,0.746282,0.532422,0.337986,0.019665,0.020992,0.190643,0.000006,pass
14,0.415295,1.061708,0.662864,0.598273,1.042090,1.768191,1.990816,2.244761,1.845279,1.286303,...,0.822290,0.826182,0.488820,0.413219,0.282879,0.020150,0.022791,0.189088,0.000004,pass
15,0.579023,1.211275,0.836222,0.800161,1.059514,1.834712,2.227582,2.815476,2.653466,2.278206,...,0.804200,0.978373,0.791703,0.656662,0.394012,0.026938,0.031461,0.288380,0.000008,pass
16,0.474024,0.789364,0.553411,0.511008,1.209756,1.642469,1.782995,1.996435,1.789932,1.580605,...,0.657879,0.867917,0.697259,0.416360,0.238771,0.022481,0.021797,0.189912,0.000006,pass
17,0.469044,1.043909,0.640896,0.626381,0.949383,1.444925,1.678332,2.081920,1.889603,1.639427,...,0.450447,0.782013,0.670016,0.452480,0.248450,0.018144,0.021245,0.187050,0.000006,pass
18,0.386178,0.934893,0.681427,0.651421,1.173938,1.242614,1.320866,1.597556,1.363364,1.372937,...,0.582346,0.656598,0.487242,0.469292,0.337502,0.015736,0.022049,0.163127,0.000004,pass
19,0.503002,0.974157,0.886322,0.849928,1.405990,1.390896,1.525414,1.669051,1.415682,1.380607,...,0.775678,0.793671,0.560305,0.476814,0.293626,0.018489,0.023138,0.181235,0.000005,pass

BARINEL SCORES

,ry 19,cx 8,ry 20,ry 21,ry 22,ry 18,ry 3,cx 7,cx 17,ry 0,...,cx 5,ry 13,ry 4,ry 1,ry 12,cx 15,ry 9,ry 11,cx 14,ry 10
sum,0.607203,0.602525,0.602312,0.600641,0.580276,0.572707,0.567846,0.563621,0.562679,0.558592,...,0.533781,0.533639,0.532199,0.527694,0.525011,0.522001,0.521642,0.514544,0.509411,0.500959

TARANTULA SCORES

,ry 19,cx 8,ry 20,ry 21,ry 22,ry 18,ry 3,cx 7,cx 17,ry 0,...,cx 5,ry 13,ry 4,ry 1,ry 12,cx 15,ry 9,ry 11,cx 14,ry 10
sum,0.607203,0.602525,0.602312,0.600641,0.580276,0.572707,0.567846,0.563621,0.562679,0.558592,...,0.533781,0.533639,0.532199,0.527694,0.525011,0.522001,0.521642,0.514544,0.509411,0.500959

DSTAR SCORES

,cx 17,cx 16,ry 18,ry 19,cx 15,cx 14,ry 22,ry 21,cx 8,ry 20,...,ry 9,cx 5,ry 13,ry 4,ry 1,ry 2,ry 3,ry 0,ry 10,ry 11
sum,18.353596,18.283923,17.295983,14.35555,12.82523,10.176857,9.261622,6.330191,6.240087,5.819463,...,1.920373,1.913455,1.455341,0.827211,0.371246,0.007662,0.006667,4.643514e-10,7.172688e-11,2.578530e-11

ERROR GATE LOCATION:
21
Now evolving the following mutant:  AddGate_z_inGap_23_.qasm

100%|██████████| 10/10 [00:21<00:00,  2.10s/it]
100%|██████████| 10/10 [00:20<00:00,  2.03s/it]

,ry 23,z 22,ry 21,ry 20,ry 19,ry 18,cx 17,cx 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.583037,0.412269,1.167388,0.673120,1.407450,2.090984,2.358115,2.299461,1.947463,2.184803,...,0.220129,0.640212,0.659423,0.500627,0.248446,0.018972,0.022203,0.273217,0.000008,fail
1,0.531082,0.375532,1.193561,0.766178,2.026889,1.920330,2.015446,1.801900,1.969031,2.049794,...,0.262270,0.640455,0.674790,0.507947,0.242116,0.018881,0.021682,0.221143,0.000007,fail
2,0.494482,0.349651,0.977730,0.427187,1.366466,1.509205,1.660878,1.593884,1.868652,2.101667,...,0.201131,0.502344,0.605215,0.442184,0.234668,0.014667,0.020616,0.199297,0.000006,fail
3,0.487424,0.344661,1.003541,0.570737,1.717174,1.502102,1.604224,1.592519,1.491266,1.475160,...,0.289197,0.555198,0.572981,0.460644,0.217745,0.015412,0.019165,0.189215,0.000005,fail
4,0.774741,0.547825,1.478368,0.804700,2.008089,2.511511,2.703521,2.406822,2.058682,1.559603,...,0.234352,0.641158,0.582899,0.418624,0.201818,0.020771,0.018061,0.213562,0.000007,fail
5,0.510391,0.360901,0.905347,0.738769,1.599036,1.894041,2.065846,1.740828,1.847681,2.033324,...,0.241775,0.568958,0.616169,0.496507,0.226010,0.015158,0.022197,0.204102,0.000006,fail
6,0.493764,0.349144,1.187125,0.799356,1.678791,1.838424,2.189462,2.524470,2.059757,2.458805,...,0.364184,0.809939,0.818833,0.655379,0.294644,0.020774,0.027079,0.337824,0.000009,fail
7,0.583586,0.412657,1.203726,0.886078,1.661680,1.895507,1.997169,1.703822,1.515813,1.779733,...,0.289479,0.541158,0.627310,0.532267,0.256299,0.017262,0.021508,0.227658,0.000006,fail
8,0.605116,0.427882,1.179113,0.940173,1.904598,2.284688,2.438219,2.131382,1.837575,1.534033,...,0.382720,0.635320,0.698979,0.556123,0.260065,0.021145,0.021386,0.235449,0.000008,fail
9,0.508943,0.359877,1.197773,0.718475,1.815905,2.173444,2.295746,1.684751,1.665470,1.427976,...,0.263786,0.553139,0.581010,0.451682,0.202086,0.016969,0.018054,0.179870,0.000006,fail
10,0.532616,0.376617,0.722732,0.730609,1.401789,1.517812,1.740893,1.905157,1.980656,2.195758,...,0.306622,0.639617,0.779288,0.603846,0.287443,0.016851,0.025793,0.267536,0.000007,pass
11,0.594455,0.420343,1.467094,0.833427,1.676239,2.215811,2.299090,1.468618,1.228332,1.181774,...,0.267726,0.463877,0.455725,0.393695,0.214191,0.013923,0.013269,0.142829,0.000006,pass
12,0.578652,0.409169,1.228805,1.004826,1.532364,1.671186,1.755307,1.675663,1.716722,1.346107,...,0.302783,0.548980,0.594632,0.458723,0.209262,0.015690,0.016589,0.162016,0.000006,pass
13,0.462689,0.327171,1.310020,0.490583,1.298183,2.000138,2.175391,2.127771,2.110506,1.520466,...,0.180720,0.556389,0.518676,0.450978,0.256932,0.014813,0.017563,0.177221,0.000006,pass
14,0.376894,0.266504,0.927894,0.679506,1.405530,1.195916,1.269884,1.282457,1.050274,0.930481,...,0.234450,0.459553,0.449959,0.393798,0.199987,0.011185,0.013316,0.158036,0.000004,pass
15,0.596060,0.421478,1.534525,1.187957,1.766926,1.888016,2.123007,2.076568,1.728027,1.727332,...,0.365669,0.712383,0.736948,0.614311,0.288115,0.018238,0.023023,0.260669,0.000008,pass
16,0.661940,0.468062,1.214930,1.136988,1.519824,1.784764,1.900736,1.670729,1.432076,1.374592,...,0.361673,0.561166,0.604695,0.479947,0.210369,0.017004,0.018048,0.194670,0.000006,pass
17,0.556936,0.393813,1.155017,0.721851,1.842849,2.389222,2.524159,1.952268,2.113217,2.178673,...,0.212517,0.661434,0.721256,0.533269,0.259488,0.018195,0.022228,0.233003,0.000008,pass
18,0.377285,0.266781,0.811069,0.574039,0.992428,1.549335,1.747332,1.535796,1.328242,1.387087,...,0.204027,0.465007,0.470936,0.425811,0.215946,0.011348,0.015283,0.181139,0.000006,pass
19,0.486242,0.343825,0.927507,0.591115,0.580188,1.726167,2.093951,2.325772,2.276618,2.411134,...,0.234075,0.691083,0.714302,0.584966,0.305703,0.017906,0.023747,0.284332,0.000009,pass

BARINEL SCORES

,ry 19,ry 12,ry 3,cx 14,ry 2,ry 1,ry 10,ry 18,cx 17,cx 16,...,ry 9,ry 0,cx 7,cx 8,ry 11,ry 13,ry 21,cx 5,ry 4,ry 20
sum,0.550793,0.543264,0.537082,0.533729,0.528808,0.525316,0.52272,0.52239,0.520739,0.519454,...,0.515215,0.5139,0.513859,0.507267,0.50618,0.504571,0.504257,0.504148,0.493424,0.479506

TARANTULA SCORES

,ry 19,ry 12,ry 3,cx 14,ry 2,ry 1,ry 10,ry 18,cx 17,cx 16,...,ry 9,ry 0,cx 7,cx 8,ry 11,ry 13,ry 21,cx 5,ry 4,ry 20
sum,0.550793,0.543264,0.537082,0.533729,0.528808,0.525316,0.52272,0.52239,0.520739,0.519454,...,0.515215,0.5139,0.513859,0.507267,0.50618,0.504571,0.504257,0.504148,0.493424,0.479506

DSTAR SCORES

,cx 17,ry 18,cx 16,cx 14,cx 15,ry 19,ry 21,ry 20,ry 12,cx 6,...,ry 13,z 22,cx 8,ry 4,ry 1,ry 2,ry 3,ry 0,ry 10,ry 11
sum,15.35316,13.778673,13.54223,13.184662,12.367233,12.298356,6.202208,2.988835,2.962771,2.582682,...,1.324086,1.133855,0.596446,0.456557,0.431499,0.004409,0.003191,4.766556e-10,9.783129e-11,2.076286e-11

ERROR GATE LOCATION:
22
Now evolving the following mutant:  AddGate_y_inGap_4_.qasm

100%|██████████| 10/10 [00:21<00:00,  2.15s/it]
100%|██████████| 10/10 [00:21<00:00,  2.14s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,ry 5,ry 4,y 3,ry 2,ry 1,ry 0,pass/fail
0,0.629761,1.283232,0.691829,2.091094,2.475993,2.715608,2.549396,2.661089,2.343726,0.588612,...,0.751848,0.799671,0.610289,0.319220,0.020039,0.096679,0.025890,0.274660,0.000008,fail
1,0.486865,0.892573,0.400765,1.552340,1.595127,1.717769,1.746564,1.744918,1.633760,0.428442,...,0.468686,0.492330,0.368379,0.196605,0.013234,0.063695,0.016542,0.175630,0.000006,fail
2,0.762227,1.140712,0.988477,1.812320,2.024481,2.293778,2.374515,1.911557,1.911718,0.545312,...,0.789722,0.788837,0.651375,0.309915,0.020936,0.095947,0.025080,0.296490,0.000008,fail
3,0.531701,0.786665,0.815192,1.957897,1.876390,2.091172,2.192400,2.244053,2.262961,0.467479,...,0.696980,0.765253,0.627579,0.301878,0.017935,0.093086,0.024875,0.271135,0.000008,fail
4,0.625270,1.093683,0.666404,2.184824,1.985753,2.081056,1.993642,2.152022,2.099167,0.439251,...,0.629884,0.690580,0.543564,0.286211,0.016367,0.084469,0.023453,0.227199,0.000007,fail
5,0.641883,1.013843,0.577739,1.743472,1.817650,1.914316,1.708434,1.411270,1.187449,0.302482,...,0.401727,0.379693,0.317736,0.173201,0.014468,0.069929,0.012442,0.148218,0.000005,fail
6,0.752594,1.802178,0.950412,1.778371,2.123267,2.367947,2.492167,2.389129,2.121597,0.589793,...,0.730310,0.743539,0.524651,0.261512,0.021215,0.099105,0.023642,0.255805,0.000008,fail
7,0.552705,1.194171,0.609848,2.061536,1.983289,2.122019,2.135335,2.189974,2.217487,0.488338,...,0.673903,0.705751,0.546613,0.268105,0.017282,0.086811,0.023960,0.246300,0.000007,fail
8,0.607933,1.413609,0.896855,1.933774,1.437030,1.609972,2.123687,1.898895,1.653397,0.497850,...,0.645563,0.671730,0.586749,0.315258,0.017023,0.080522,0.021189,0.243664,0.000006,fail
9,0.553517,1.038306,0.740066,2.103015,2.016876,2.016435,1.468662,1.638559,1.413931,0.288798,...,0.420344,0.457012,0.353992,0.166162,0.014513,0.074530,0.014226,0.135353,0.000005,fail
10,0.577934,1.450929,0.803257,1.827334,1.834258,2.059929,2.383589,2.416233,2.115347,0.580988,...,0.714555,0.748012,0.625462,0.320041,0.018571,0.089512,0.024643,0.252142,0.000007,pass
11,0.547010,0.786400,0.756770,0.936010,1.132818,1.355944,1.853384,1.978400,1.848394,0.517108,...,0.541160,0.640048,0.515112,0.241626,0.015301,0.076037,0.021522,0.216601,0.000006,pass
12,0.611659,1.165222,0.516318,1.668285,1.842683,1.914827,1.769384,1.701351,1.318880,0.379051,...,0.427644,0.408598,0.297914,0.166180,0.013861,0.065687,0.013631,0.133028,0.000005,pass
13,0.481636,1.421334,0.651569,1.524002,2.272400,2.662404,2.842859,2.744263,2.511037,0.684884,...,0.905506,0.854032,0.606540,0.288267,0.020174,0.095449,0.027147,0.310917,0.000009,pass
14,0.401489,0.951702,0.533824,1.232673,1.636640,1.672697,1.179220,0.969218,0.946344,0.326914,...,0.340936,0.325901,0.289213,0.153620,0.010112,0.048019,0.010597,0.113132,0.000004,pass
15,0.348035,1.139011,0.759802,1.090927,1.619566,1.808682,1.751257,1.530011,1.355668,0.397766,...,0.506103,0.495438,0.451853,0.232595,0.013836,0.068634,0.016439,0.184770,0.000005,pass
16,0.497382,0.663403,0.912356,1.510157,1.865862,1.959666,1.466282,1.344820,1.054370,0.281506,...,0.476412,0.487263,0.430615,0.186103,0.012943,0.062833,0.014862,0.135998,0.000006,pass
17,0.526771,1.219694,0.983020,1.280492,2.240152,2.486148,2.050479,1.935588,1.885175,0.491434,...,0.702895,0.770474,0.586087,0.270366,0.017961,0.083493,0.023148,0.252484,0.000009,pass
18,0.592256,1.218525,0.848975,1.669248,2.092729,2.279536,1.886840,1.752158,1.743676,0.596386,...,0.626172,0.629680,0.505012,0.256323,0.016475,0.075331,0.019475,0.217190,0.000008,pass
19,0.554604,1.372433,0.862203,1.598287,1.606991,1.747837,1.663394,1.448499,1.223970,0.276979,...,0.481515,0.443937,0.405858,0.211027,0.013841,0.072078,0.014493,0.161056,0.000005,pass

BARINEL SCORES

,ry 20,ry 13,ry 23,cx 15,ry 1,y 3,ry 11,ry 2,cx 16,ry 4,...,ry 10,cx 6,cx 8,ry 19,cx 18,ry 0,ry 22,ry 14,cx 9,ry 21
sum,0.572732,0.546214,0.544565,0.540782,0.534943,0.534043,0.532877,0.531897,0.531802,0.530569,...,0.522508,0.521192,0.520369,0.515899,0.512016,0.511366,0.505864,0.505635,0.495287,0.490294

TARANTULA SCORES

,ry 20,ry 13,ry 23,cx 15,ry 1,y 3,ry 11,ry 2,cx 16,ry 4,...,ry 10,cx 6,cx 8,ry 19,cx 18,ry 0,ry 22,ry 14,cx 9,ry 21
sum,0.572732,0.546214,0.544565,0.540782,0.534943,0.534043,0.532877,0.531897,0.531802,0.530569,...,0.522508,0.521192,0.520369,0.515899,0.512016,0.511366,0.505864,0.505635,0.495287,0.490294

DSTAR SCORES

,ry 20,cx 17,cx 16,cx 18,cx 15,ry 19,ry 22,ry 21,ry 13,cx 7,...,ry 14,ry 5,cx 9,ry 1,y 3,ry 2,ry 4,ry 0,ry 11,ry 12
sum,15.176474,14.976,14.727139,14.627778,13.657779,13.284325,6.355315,3.054226,2.897728,2.66887,...,1.479102,0.547613,0.467451,0.431911,0.066465,0.004383,0.002948,4.656697e-10,1.157226e-10,2.737020e-11

ERROR GATE LOCATION:
3
Now evolving the following mutant:  AddGate_y_inGap_1_.qasm

100%|██████████| 10/10 [00:22<00:00,  2.22s/it]
100%|██████████| 10/10 [00:21<00:00,  2.18s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,ry 5,ry 4,ry 3,ry 2,ry 1,y 0,pass/fail
0,0.559950,1.257309,0.739293,1.397243,1.767978,2.001136,1.846972,1.847307,1.882777,0.517058,...,0.622776,0.591799,0.456509,0.203196,0.015431,0.020078,0.206783,0.000007,0.091721,fail
1,0.676890,1.426358,0.812921,2.244496,2.255985,2.406603,2.351843,2.322375,1.941104,0.487255,...,0.670068,0.677229,0.530931,0.272326,0.018555,0.021467,0.228446,0.000007,0.105203,fail
2,0.691386,1.144973,0.917898,2.011329,2.689416,2.867464,2.248559,2.129865,2.086512,0.500895,...,0.689468,0.746012,0.546482,0.254370,0.020131,0.025272,0.246437,0.000008,0.106866,fail
3,0.728744,1.437227,0.805313,1.243304,2.582609,2.868724,2.296928,1.858183,1.470743,0.393894,...,0.623872,0.603448,0.473256,0.226627,0.019504,0.018776,0.211600,0.000008,0.106422,fail
4,0.469961,1.063546,0.808722,1.769134,3.063795,3.255963,2.308101,2.016800,1.883736,0.508984,...,0.653587,0.619187,0.576308,0.288388,0.018168,0.018955,0.224601,0.000010,0.131444,fail
5,0.519691,1.123301,0.682773,1.071850,2.163654,2.434950,2.173465,2.430823,2.177209,0.567693,...,0.626715,0.711838,0.576746,0.276792,0.017661,0.023226,0.229023,0.000008,0.112053,fail
6,0.541295,1.346298,0.908379,1.529599,2.975957,3.129812,1.991977,1.908032,1.664930,0.464671,...,0.570025,0.616389,0.507148,0.247308,0.017730,0.018778,0.183643,0.000008,0.110167,fail
7,0.599899,0.583455,0.588762,1.585931,1.970464,2.148097,1.876414,1.638526,1.386495,0.284637,...,0.511142,0.499083,0.414321,0.187446,0.015887,0.017321,0.179493,0.000006,0.083500,fail
8,0.481533,1.359382,0.730589,1.642351,1.942040,2.112188,1.875798,1.975987,1.702432,0.364151,...,0.609219,0.640652,0.504042,0.240225,0.015705,0.019701,0.197292,0.000007,0.091891,fail
9,0.506746,1.374361,0.719945,1.844458,1.164713,1.182703,1.296382,0.947153,0.867950,0.260726,...,0.341635,0.312126,0.275608,0.140760,0.009543,0.011498,0.116073,0.000003,0.047114,fail
10,0.397561,1.291265,0.909439,1.845086,1.815445,1.989688,2.080989,1.729399,1.571294,0.516991,...,0.676694,0.654001,0.544491,0.258836,0.018137,0.020143,0.238794,0.000007,0.092128,pass
11,0.641374,1.212732,0.774841,1.673354,1.843675,2.006703,1.810745,1.820987,2.073410,0.491385,...,0.634261,0.683201,0.491604,0.234597,0.016608,0.022417,0.247509,0.000007,0.096660,pass
12,0.438129,0.931507,0.743507,1.669355,1.644554,1.778106,1.612135,1.784705,1.727252,0.490104,...,0.590080,0.607858,0.481401,0.224212,0.014504,0.019142,0.192976,0.000007,0.090255,pass
13,0.540763,1.305536,1.153813,1.336613,1.402533,1.564865,1.605516,1.497163,1.568140,0.439885,...,0.606596,0.619047,0.515990,0.225917,0.014228,0.019037,0.199634,0.000007,0.095659,pass
14,0.543395,1.318080,0.836980,1.598644,2.488642,2.700622,2.383699,1.992656,1.854422,0.502278,...,0.706279,0.663660,0.496335,0.237676,0.018966,0.021198,0.241350,0.000008,0.107164,pass
15,0.565962,1.044331,0.695750,1.556824,2.389366,2.595775,2.232242,2.017377,1.738788,0.401582,...,0.572677,0.622858,0.499545,0.249188,0.018663,0.020837,0.222805,0.000007,0.093957,pass
16,0.521436,0.793738,0.968324,1.565808,1.792871,2.007736,2.058270,1.990518,2.109077,0.474156,...,0.733461,0.794997,0.603577,0.273053,0.019095,0.025453,0.271131,0.000008,0.108058,pass
17,0.474018,1.524289,0.853186,2.115048,1.436739,1.614274,2.282454,2.136324,1.766425,0.564141,...,0.727024,0.704340,0.571194,0.296310,0.016704,0.021934,0.260145,0.000006,0.091731,pass
18,0.472438,0.986134,0.575907,1.473028,1.339982,1.451260,1.277227,1.583241,1.459213,0.424111,...,0.450222,0.479880,0.338155,0.170435,0.010950,0.016536,0.141838,0.000005,0.068147,pass
19,0.460580,0.597653,0.425055,0.942273,1.190158,1.309839,1.351359,1.174265,0.989987,0.197572,...,0.362267,0.343675,0.269715,0.145657,0.010080,0.010623,0.129694,0.000004,0.063979,pass

BARINEL SCORES

,ry 19,cx 18,ry 10,ry 23,ry 22,y 0,cx 17,ry 1,cx 16,ry 12,...,cx 15,cx 6,cx 9,ry 5,ry 3,cx 8,cx 7,ry 21,ry 14,ry 2
sum,0.565538,0.562045,0.539994,0.533256,0.524024,0.520759,0.520171,0.519203,0.51832,0.516129,...,0.503035,0.502551,0.502364,0.502316,0.497138,0.494112,0.493612,0.492901,0.491401,0.485311

TARANTULA SCORES

,ry 19,cx 18,ry 10,ry 23,ry 22,y 0,cx 17,ry 1,cx 16,ry 12,...,cx 15,cx 6,cx 9,ry 5,ry 3,cx 8,cx 7,ry 21,ry 14,ry 2
sum,0.565538,0.562045,0.539994,0.533256,0.524024,0.520759,0.520171,0.519203,0.51832,0.516129,...,0.503035,0.502551,0.502364,0.502316,0.497138,0.494112,0.493612,0.492901,0.491401,0.485311

DSTAR SCORES

,cx 18,ry 19,cx 17,cx 16,cx 15,ry 20,ry 22,ry 21,ry 13,cx 7,...,ry 14,cx 9,ry 5,ry 2,y 0,ry 3,ry 4,ry 1,ry 11,ry 12
sum,20.529158,18.640432,14.313776,13.123035,10.841321,10.3579,6.988846,3.318037,2.463729,2.239059,...,1.30478,0.546307,0.443623,0.337078,0.089198,0.003732,0.002789,5.016472e-10,1.002233e-10,2.454439e-11

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_x_inGap_13_.qasm

100%|██████████| 10/10 [00:21<00:00,  2.12s/it]
100%|██████████| 10/10 [00:19<00:00,  2.00s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.631248,1.417194,0.792708,1.668746,2.267524,2.542027,2.546174,2.383994,2.106770,0.542342,...,0.253050,0.714452,0.704632,0.558478,0.274777,0.019186,0.023908,0.255501,0.000008,fail
1,0.570307,1.183719,0.630274,1.566998,2.317013,2.581523,2.144903,2.143481,2.170564,0.469958,...,0.221997,0.662986,0.709859,0.551200,0.263599,0.018073,0.023976,0.248704,0.000008,fail
2,0.580571,1.144339,0.965602,1.688035,2.252066,2.415657,2.159950,2.032588,1.925158,0.463470,...,0.400944,0.735510,0.760826,0.620038,0.288510,0.020067,0.024452,0.247792,0.000008,fail
3,0.644052,1.153164,0.786444,1.294296,1.947418,2.210183,2.367854,1.826799,1.627194,0.421267,...,0.339589,0.610224,0.598890,0.525599,0.251806,0.019133,0.021001,0.238552,0.000007,fail
4,0.645020,0.836204,0.750970,1.614925,2.247800,2.451366,2.078066,2.116706,2.089539,0.531291,...,0.298054,0.584705,0.662973,0.497907,0.220408,0.019763,0.022169,0.223107,0.000008,fail
5,0.472035,1.108407,0.783246,2.182227,2.289778,2.204744,1.160262,1.136014,1.478448,0.401476,...,0.334773,0.439073,0.472497,0.455717,0.207983,0.015464,0.016369,0.143925,0.000006,fail
6,0.696367,1.435746,0.697088,1.470065,1.404417,1.557690,2.025936,1.651744,1.244811,0.341191,...,0.223038,0.464205,0.406372,0.353068,0.174372,0.016829,0.014079,0.169237,0.000005,fail
7,0.706598,1.551625,0.774664,2.540224,2.426846,2.541602,2.146766,2.315241,2.060951,0.528945,...,0.226969,0.679226,0.709275,0.545509,0.272539,0.020366,0.022196,0.236172,0.000007,fail
8,0.608070,0.758586,0.826335,1.587171,1.998001,2.134917,1.671858,1.510389,1.631566,0.371901,...,0.334790,0.576875,0.643996,0.475615,0.206984,0.017956,0.020465,0.209537,0.000007,fail
9,0.460809,1.403450,0.825906,1.642246,1.695524,1.845355,1.738740,1.423002,1.183138,0.354775,...,0.260177,0.516060,0.505361,0.445164,0.213982,0.015119,0.016385,0.176119,0.000005,fail
10,0.653084,1.008954,0.760118,1.946209,1.997881,2.139811,2.209824,1.861333,1.594176,0.455382,...,0.272666,0.569178,0.566833,0.485408,0.252772,0.020299,0.018528,0.215172,0.000007,pass
11,0.534820,1.031498,0.844734,1.656205,2.127137,2.335506,2.180057,2.297014,2.106821,0.566625,...,0.281011,0.710606,0.733974,0.542208,0.268426,0.017493,0.024006,0.250977,0.000008,pass
12,0.545953,0.954172,0.754595,1.818299,1.588383,1.635740,1.383700,1.570956,1.495765,0.409066,...,0.161506,0.488029,0.540917,0.389963,0.172252,0.013061,0.017522,0.164796,0.000005,pass
13,0.494076,1.404441,0.838707,2.027370,2.195495,2.246567,1.909995,1.623263,1.327317,0.528571,...,0.290095,0.607460,0.582025,0.495235,0.256723,0.016893,0.017918,0.192341,0.000006,pass
14,0.590183,0.989968,0.897066,1.203688,1.439465,1.729308,2.011517,1.966949,1.768147,0.411632,...,0.252064,0.632073,0.633384,0.457640,0.203328,0.014886,0.019872,0.224278,0.000007,pass
15,0.443630,0.801629,0.449561,0.690684,1.494455,1.758110,1.673264,1.824809,1.610718,0.350905,...,0.153154,0.508411,0.566125,0.361026,0.156843,0.012614,0.017742,0.174123,0.000006,pass
16,0.555388,1.532699,0.691222,1.460860,1.888359,2.103052,2.029688,1.301817,1.029536,0.380932,...,0.236158,0.484235,0.409071,0.386306,0.206443,0.014560,0.014767,0.176164,0.000005,pass
17,0.471416,1.047313,0.843499,2.011380,1.047615,1.047991,1.236696,1.041475,1.025325,0.321779,...,0.201300,0.417799,0.422792,0.401300,0.212198,0.011761,0.013790,0.166030,0.000003,pass
18,0.392958,1.121523,0.902285,1.660443,2.104961,2.329714,2.288532,2.024865,2.120104,0.610923,...,0.321467,0.742187,0.724269,0.627729,0.343020,0.015829,0.023527,0.270691,0.000009,pass
19,0.528776,1.179402,0.798855,1.575707,2.694462,2.864014,1.910699,1.454288,1.248293,0.438560,...,0.358788,0.578153,0.550913,0.474852,0.231745,0.016615,0.017052,0.179326,0.000008,pass

BARINEL SCORES

,x 12,ry 13,ry 3,ry 23,cx 8,cx 15,ry 19,cx 18,ry 2,ry 0,...,cx 6,ry 20,ry 10,ry 1,cx 17,ry 11,cx 7,ry 4,ry 21,ry 14
sum,0.550173,0.543838,0.541591,0.535847,0.533678,0.533369,0.528766,0.526892,0.526011,0.5256,...,0.518664,0.518076,0.517048,0.516186,0.515518,0.513555,0.510459,0.50761,0.501684,0.497317

TARANTULA SCORES

,x 12,ry 13,ry 3,ry 23,cx 8,cx 15,ry 19,cx 18,ry 2,ry 0,...,cx 6,ry 20,ry 10,ry 1,cx 17,ry 11,cx 7,ry 4,ry 21,ry 14
sum,0.550173,0.543838,0.541591,0.535847,0.533678,0.533369,0.528766,0.526892,0.526011,0.5256,...,0.518664,0.518076,0.517048,0.516186,0.515518,0.513555,0.510459,0.50761,0.501684,0.497317

DSTAR SCORES

,cx 18,ry 19,cx 17,cx 16,cx 15,ry 20,ry 22,ry 21,ry 13,cx 6,...,ry 14,cx 8,ry 4,ry 1,x 12,ry 2,ry 3,ry 0,ry 10,ry 11
sum,16.746647,15.206405,13.928777,12.74643,12.1173,11.428907,6.825227,3.450921,2.74623,2.423773,...,1.353766,0.668224,0.458432,0.384278,0.292241,0.004126,0.003261,5.008091e-10,9.662315e-11,2.121972e-11

ERROR GATE LOCATION:
12
Now evolving the following mutant:  AddGate_rxx_inGap_4_.qasm

100%|██████████| 10/10 [00:20<00:00,  2.09s/it]
100%|██████████| 10/10 [00:20<00:00,  2.06s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,ry 5,ry 4,rxx 3,ry 2,ry 1,ry 0,pass/fail
0,0.652006,1.035335,0.581031,2.004636,1.900914,1.964547,1.633463,1.724250,1.548491,0.383762,...,0.543524,0.548290,0.413934,0.213288,0.015435,0.402478,0.020079,0.183485,0.000006,fail
1,0.492677,1.175322,0.878438,1.496866,1.602148,1.794963,1.851308,1.737053,1.897369,0.545389,...,0.627057,0.664031,0.528165,0.257916,0.015752,0.401717,0.024022,0.235877,0.000007,fail
2,0.718836,1.790801,0.814886,1.900953,1.818885,2.015984,2.342129,1.958322,1.663697,0.457137,...,0.668979,0.655507,0.486341,0.239270,0.021532,0.508307,0.023755,0.248907,0.000006,fail
3,0.528077,1.285860,0.577656,1.928672,1.757015,1.859211,1.994321,2.248394,1.966760,0.565989,...,0.592966,0.598821,0.479044,0.243106,0.014754,0.382162,0.023316,0.198924,0.000006,fail
4,0.566588,1.347969,0.712398,1.526920,1.514679,1.559984,1.439451,1.138490,1.086972,0.339529,...,0.409882,0.397448,0.318276,0.162535,0.012503,0.277686,0.015384,0.145779,0.000004,fail
5,0.585686,0.895797,0.638106,1.588675,1.887923,2.160385,2.208989,2.239764,2.330663,0.506514,...,0.734940,0.837610,0.572912,0.259748,0.019264,0.518540,0.030605,0.295670,0.000008,fail
6,0.531381,1.357543,0.848783,1.986661,2.271727,2.392517,1.952513,2.155350,1.888768,0.560730,...,0.603971,0.649304,0.555506,0.293600,0.015990,0.411102,0.022335,0.191943,0.000007,fail
7,0.597161,1.376064,0.809959,1.299237,1.711145,1.985101,2.168374,2.002547,2.170378,0.497260,...,0.720799,0.743131,0.560700,0.278158,0.017673,0.475391,0.025882,0.262466,0.000007,fail
8,0.687625,0.934118,0.862614,1.722945,1.332192,1.454420,1.740208,1.421047,1.510751,0.253865,...,0.489143,0.543121,0.441165,0.237785,0.015970,0.409327,0.020232,0.214931,0.000006,fail
9,0.624583,1.492976,0.871733,2.087903,2.647883,2.726289,1.843437,1.832649,1.544642,0.414107,...,0.598258,0.607985,0.466640,0.229318,0.016168,0.405584,0.020969,0.178493,0.000007,fail
10,0.538178,0.958364,0.668344,1.573897,2.349402,2.662606,2.302546,2.216376,1.881712,0.624536,...,0.687255,0.774898,0.666727,0.341857,0.018843,0.482409,0.025298,0.277088,0.000009,pass
11,0.330036,1.007187,0.599765,1.296160,1.590325,1.704458,1.497228,1.691731,1.671016,0.375824,...,0.478680,0.521239,0.429471,0.224898,0.012283,0.337498,0.018155,0.158809,0.000006,pass
12,0.512194,0.939699,0.809852,1.704054,1.576993,1.573295,1.102238,1.161552,1.074425,0.319964,...,0.386142,0.353231,0.287822,0.128420,0.012045,0.282430,0.012870,0.101984,0.000005,pass
13,0.487022,1.029400,0.775611,1.773613,2.059399,2.119720,1.496563,1.618040,1.434421,0.452101,...,0.516598,0.576590,0.478020,0.242628,0.012471,0.329779,0.020150,0.177464,0.000006,pass
14,0.443470,1.168203,0.588112,1.916862,1.952148,1.957066,1.570741,1.429197,1.182182,0.365997,...,0.474857,0.413841,0.330386,0.167801,0.013493,0.319562,0.014191,0.129954,0.000005,pass
15,0.716964,1.177001,0.624522,1.545571,1.851657,2.070949,2.310551,2.145360,1.993470,0.465434,...,0.607501,0.607414,0.440120,0.229551,0.016043,0.416141,0.022983,0.233097,0.000007,pass
16,0.473596,1.159989,0.744211,1.421747,2.064688,2.267803,2.020569,1.649693,1.641066,0.425026,...,0.541901,0.608222,0.490696,0.254480,0.016820,0.408058,0.021579,0.228127,0.000006,pass
17,0.322347,0.948109,0.638959,1.586943,1.106820,1.150781,1.303299,1.288301,1.064578,0.294513,...,0.469730,0.481262,0.357841,0.167166,0.010661,0.283221,0.015802,0.146556,0.000004,pass
18,0.608099,0.989488,0.838516,1.390132,1.591157,1.772691,1.768922,1.733894,1.710954,0.491945,...,0.603480,0.640315,0.532025,0.261259,0.016090,0.420337,0.021783,0.216871,0.000007,pass
19,0.356916,0.752629,0.520220,1.599297,1.909944,2.067016,1.701633,1.916513,1.868487,0.465133,...,0.576915,0.626505,0.433618,0.197995,0.014958,0.398391,0.021159,0.194537,0.000007,pass

BARINEL SCORES

,ry 22,ry 23,ry 2,ry 1,ry 4,ry 13,ry 11,rxx 3,cx 15,cx 17,...,cx 16,ry 5,cx 6,cx 9,ry 12,ry 14,ry 10,cx 18,ry 19,ry 0
sum,0.556124,0.555497,0.53877,0.536308,0.53455,0.53415,0.533362,0.532685,0.531484,0.528965,...,0.52276,0.521451,0.520279,0.519513,0.514438,0.513845,0.509346,0.507221,0.50537,0.504506

TARANTULA SCORES

,ry 22,ry 23,ry 2,ry 1,ry 4,ry 13,ry 11,rxx 3,cx 15,cx 17,...,cx 16,ry 5,cx 6,cx 9,ry 12,ry 14,ry 10,cx 18,ry 19,ry 0
sum,0.556124,0.555497,0.53877,0.536308,0.53455,0.53415,0.533362,0.532685,0.531484,0.528965,...,0.52276,0.521451,0.520279,0.519513,0.514438,0.513845,0.509346,0.507221,0.50537,0.504506

DSTAR SCORES

,cx 17,cx 18,cx 16,cx 15,ry 19,ry 20,ry 22,ry 21,ry 13,cx 7,...,ry 14,rxx 3,cx 9,ry 5,ry 1,ry 2,ry 4,ry 0,ry 11,ry 12
sum,13.579292,13.512518,12.688435,12.148542,12.127247,11.92537,8.002029,3.432461,2.526152,2.499637,...,1.433365,1.284949,0.477883,0.477313,0.391958,0.005036,0.002685,4.079692e-10,1.008796e-10,2.249530e-11

ERROR GATE LOCATION:
3
Now evolving the following mutant:  AddGate_y_inGap_24_.qasm

100%|██████████| 10/10 [00:19<00:00,  2.00s/it]
100%|██████████| 10/10 [00:19<00:00,  1.97s/it]

,ry 23,ry 22,ry 21,ry 20,y 19,ry 18,cx 17,cx 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.624811,1.361673,0.792813,1.810556,0.501873,2.759420,2.855401,1.744040,1.475576,1.436192,...,0.287831,0.529458,0.581634,0.442544,0.200742,0.018047,0.017808,0.182300,0.000007,fail
1,0.708756,1.533378,0.795888,1.805383,0.452361,2.196560,2.405243,2.242027,2.052906,2.034717,...,0.220973,0.618052,0.624882,0.480053,0.247649,0.017886,0.021351,0.237021,0.000008,fail
2,0.751008,1.243306,0.612795,1.798629,0.482529,2.440584,2.690639,2.346355,2.392376,2.334477,...,0.205249,0.747047,0.765001,0.514613,0.257530,0.018479,0.025639,0.264324,0.000008,fail
3,0.517337,1.215246,0.835915,1.561802,0.363278,1.931907,2.043836,1.589471,1.563840,1.430735,...,0.263769,0.497821,0.559941,0.436077,0.201811,0.014328,0.017334,0.164538,0.000006,fail
4,0.645635,1.318525,0.874563,1.944565,0.469641,2.391280,2.568345,2.215834,1.882943,1.487425,...,0.270056,0.585254,0.549591,0.520513,0.256918,0.018547,0.018457,0.196957,0.000007,fail
5,0.601124,1.707689,0.921593,1.468012,0.545135,2.697696,3.009458,2.543196,2.237050,2.048719,...,0.288439,0.719323,0.684762,0.559387,0.273466,0.020885,0.020966,0.253761,0.000009,fail
6,0.524055,1.497825,0.956544,1.893521,0.545824,2.799672,3.010707,2.062405,1.941557,2.122453,...,0.333779,0.735213,0.783614,0.630005,0.297782,0.020374,0.024795,0.263373,0.000009,fail
7,0.573945,1.303277,0.519096,1.508456,0.437505,2.068456,2.347934,2.359753,2.363443,2.122137,...,0.191423,0.675240,0.622432,0.478295,0.240238,0.018279,0.020884,0.231139,0.000008,fail
8,0.357944,1.099098,0.513872,1.419012,0.335586,1.646303,1.791488,1.735010,1.483950,1.070913,...,0.201379,0.455135,0.367124,0.345066,0.175662,0.012264,0.011610,0.140714,0.000005,fail
9,0.466498,1.114265,0.953859,1.817854,0.494418,2.535810,2.690709,1.840490,2.189248,2.240053,...,0.282523,0.690092,0.750746,0.576700,0.256503,0.017135,0.021890,0.220802,0.000009,fail
10,0.325420,0.829867,0.325486,1.158984,0.110281,0.604140,0.617777,0.837472,0.704617,0.636668,...,0.090340,0.275174,0.249561,0.232915,0.117325,0.007479,0.009029,0.093003,0.000002,pass
11,0.540006,1.215871,0.815188,1.922324,0.356155,1.792291,1.917687,1.737478,1.813414,2.057306,...,0.305428,0.657127,0.673680,0.552146,0.277387,0.015751,0.022902,0.225109,0.000007,pass
12,0.232023,0.783928,0.533780,0.971186,0.225001,1.202564,1.292468,1.137938,1.044775,1.002236,...,0.153481,0.366560,0.381682,0.331100,0.176378,0.008446,0.011660,0.132487,0.000005,pass
13,0.467165,1.047322,0.884633,1.968402,0.317985,1.678433,1.703041,1.568411,1.455909,1.630910,...,0.262524,0.530943,0.494899,0.395223,0.180905,0.014779,0.016334,0.180395,0.000006,pass
14,0.379425,0.877131,0.574709,1.628388,0.285307,1.277974,1.438530,1.798008,1.633392,1.844227,...,0.234567,0.580582,0.583059,0.511151,0.268707,0.014361,0.020189,0.239703,0.000006,pass
15,0.435888,1.076144,0.774173,1.909669,0.544928,2.682731,2.903556,2.520181,2.497035,2.411985,...,0.283597,0.790797,0.785249,0.648162,0.332012,0.018706,0.024664,0.277280,0.000010,pass
16,0.556514,1.301794,0.769749,1.721178,0.534105,2.714838,2.878206,2.035954,2.098202,1.672671,...,0.233466,0.645290,0.639600,0.517662,0.244938,0.016580,0.020211,0.201107,0.000007,pass
17,0.408325,1.137368,0.825141,1.221091,0.295749,1.525832,1.659816,1.561567,1.529647,1.542132,...,0.221003,0.472424,0.523985,0.465098,0.234081,0.011854,0.016595,0.177464,0.000006,pass
18,0.661673,0.906591,0.720079,1.228913,0.389397,1.789168,2.151440,2.459179,2.408060,2.216391,...,0.288806,0.713493,0.788941,0.596887,0.299028,0.020461,0.027088,0.292775,0.000008,pass
19,0.517435,1.295274,0.497811,1.330647,0.416921,2.045015,2.287966,2.177161,2.036164,1.710555,...,0.259237,0.578842,0.579063,0.442124,0.222239,0.017713,0.019243,0.201397,0.000007,pass

BARINEL SCORES

,ry 18,cx 17,y 19,ry 9,ry 22,ry 23,ry 0,ry 3,ry 12,ry 11,...,ry 10,cx 7,ry 13,cx 6,cx 14,cx 8,ry 2,ry 1,cx 5,ry 4
sum,0.575461,0.574137,0.571096,0.5656,0.561239,0.560575,0.549499,0.546681,0.537316,0.537108,...,0.53017,0.527032,0.525442,0.524605,0.522862,0.52183,0.516489,0.51607,0.515027,0.505807

TARANTULA SCORES

,ry 18,cx 17,y 19,ry 9,ry 22,ry 23,ry 0,ry 3,ry 12,ry 11,...,ry 10,cx 7,ry 13,cx 6,cx 14,cx 8,ry 2,ry 1,cx 5,ry 4
sum,0.575461,0.574137,0.571096,0.5656,0.561239,0.560575,0.549499,0.546681,0.537316,0.537108,...,0.53017,0.527032,0.525442,0.524605,0.522862,0.52183,0.516489,0.51607,0.515027,0.505807

DSTAR SCORES

,cx 17,ry 18,cx 16,cx 15,cx 14,ry 20,ry 22,ry 21,ry 12,ry 9,...,ry 13,y 19,cx 8,ry 4,ry 1,ry 2,ry 3,ry 0,ry 10,ry 11
sum,22.386421,20.163756,15.362999,14.087891,12.569055,11.569696,8.763823,3.617109,2.829515,2.535057,...,1.598605,1.589496,0.525375,0.469515,0.386309,0.003955,0.003061,5.959125e-10,1.104121e-10,2.663852e-11

ERROR GATE LOCATION:
19
Now evolving the following mutant:  AddGate_y_inGap_5_.qasm

100%|██████████| 10/10 [00:22<00:00,  2.22s/it]
100%|██████████| 10/10 [00:21<00:00,  2.19s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,ry 5,y 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.584511,1.602412,0.762222,1.611409,2.334639,2.616052,2.528873,2.538678,2.179056,0.551394,...,0.734760,0.738563,0.527168,0.291131,0.110091,0.017208,0.023721,0.249243,0.000008,fail
1,0.589687,1.492987,0.770766,1.821695,2.264909,2.440293,2.109616,2.147857,2.061503,0.488824,...,0.589854,0.625317,0.501640,0.258961,0.096216,0.016299,0.021242,0.219383,0.000008,fail
2,0.715662,1.462772,0.894771,2.277307,2.504535,2.514522,1.772998,1.864965,1.642102,0.434642,...,0.597669,0.633238,0.474971,0.201062,0.074943,0.020240,0.020421,0.180967,0.000007,fail
3,0.542682,1.176065,0.681696,1.561148,1.796730,1.899613,1.679298,1.594777,1.396837,0.375729,...,0.569258,0.570835,0.460350,0.231702,0.083846,0.016270,0.018048,0.192952,0.000006,fail
4,0.514439,0.810264,0.666783,1.687427,2.476716,2.702363,2.330388,2.514339,2.186378,0.500040,...,0.650966,0.715737,0.601912,0.289239,0.108933,0.019655,0.022770,0.229662,0.000008,fail
5,0.580635,0.992858,0.841298,1.474257,1.891349,2.009275,1.779978,1.561645,1.609230,0.320575,...,0.489198,0.608347,0.530570,0.278097,0.104979,0.016263,0.019383,0.200228,0.000007,fail
6,0.572341,1.026779,0.819900,1.695456,1.919955,2.072651,2.004185,2.239628,2.073939,0.482014,...,0.657592,0.740763,0.557158,0.269898,0.101145,0.017714,0.022860,0.231383,0.000008,fail
7,0.465898,1.392532,0.728436,2.153693,2.122260,2.223244,2.053533,2.185296,2.480159,0.528927,...,0.695267,0.761313,0.625144,0.336668,0.125816,0.018555,0.025670,0.263031,0.000008,fail
8,0.665235,1.016220,0.835606,1.892245,1.758834,1.872257,1.801593,1.759675,1.975374,0.504716,...,0.567915,0.651377,0.549683,0.282562,0.106669,0.015889,0.023153,0.229427,0.000006,fail
9,0.598871,1.101915,0.825915,1.461652,1.725452,1.862422,1.643660,1.570449,1.378916,0.327540,...,0.503148,0.535838,0.395891,0.178766,0.068138,0.017264,0.016308,0.170452,0.000006,fail
10,0.456195,1.396068,0.821528,1.455292,1.743709,2.030622,2.455645,2.110557,1.798153,0.506965,...,0.697685,0.617438,0.521571,0.295232,0.108125,0.015122,0.019382,0.239106,0.000007,pass
11,0.652335,1.503216,0.797424,1.803386,1.962244,2.125079,2.080885,1.866466,1.884839,0.584484,...,0.641928,0.664038,0.565686,0.311756,0.118023,0.016007,0.023068,0.241341,0.000007,pass
12,0.648789,1.315915,0.829218,1.922842,2.177957,2.234046,1.789346,1.306541,1.166972,0.347593,...,0.486888,0.420845,0.368088,0.188057,0.068234,0.014645,0.013083,0.153165,0.000006,pass
13,0.569774,1.023928,0.599003,1.121871,1.338760,1.483596,1.577672,1.109097,0.780727,0.284987,...,0.378041,0.339698,0.318960,0.171869,0.066610,0.012914,0.011496,0.130264,0.000005,pass
14,0.686958,1.227436,0.960765,1.439985,1.920601,2.150499,2.222385,1.878623,1.659688,0.435241,...,0.622102,0.711172,0.505510,0.236915,0.091145,0.019829,0.022575,0.241032,0.000007,pass
15,0.483535,1.299207,0.842959,1.000251,1.689065,1.880943,1.780600,1.512029,1.296278,0.333795,...,0.540260,0.532920,0.455325,0.221240,0.081643,0.014986,0.016725,0.183783,0.000006,pass
16,0.713536,1.355271,0.908846,2.186048,2.515841,2.660758,2.385294,2.297205,2.013014,0.587758,...,0.691875,0.701629,0.535360,0.284590,0.104743,0.019023,0.022456,0.238054,0.000009,pass
17,0.387495,0.911079,0.567430,1.146654,1.665613,1.748565,1.140632,1.128972,1.158750,0.383456,...,0.378605,0.384169,0.294890,0.127061,0.047891,0.010799,0.012847,0.118584,0.000005,pass
18,0.472424,0.774488,0.686668,1.595841,2.229411,2.381907,1.702797,1.797298,1.863417,0.423906,...,0.571912,0.639191,0.482214,0.227846,0.084392,0.015115,0.020072,0.209772,0.000008,pass
19,0.529463,1.561309,0.936070,1.879212,1.833736,1.834366,1.407138,1.470685,1.237480,0.435334,...,0.438902,0.478070,0.417454,0.217720,0.080528,0.013891,0.014658,0.137852,0.000005,pass

BARINEL SCORES

,ry 13,cx 15,ry 12,cx 16,ry 2,cx 7,cx 6,ry 11,y 4,ry 3,...,ry 0,cx 8,ry 19,cx 18,cx 17,ry 14,ry 23,cx 9,ry 21,ry 22
sum,0.561273,0.560931,0.555336,0.548002,0.547717,0.545241,0.539188,0.53833,0.535326,0.535134,...,0.528062,0.526401,0.521549,0.519679,0.515187,0.510799,0.510037,0.505429,0.496117,0.494004

TARANTULA SCORES

,ry 13,cx 15,ry 12,cx 16,ry 2,cx 7,cx 6,ry 11,y 4,ry 3,...,ry 0,cx 8,ry 19,cx 18,cx 17,ry 14,ry 23,cx 9,ry 21,ry 22
sum,0.561273,0.560931,0.555336,0.548002,0.547717,0.545241,0.539188,0.53833,0.535326,0.535134,...,0.528062,0.526401,0.521549,0.519679,0.515187,0.510799,0.510037,0.505429,0.496117,0.494004

DSTAR SCORES

,cx 18,cx 16,ry 19,cx 15,cx 17,ry 20,ry 22,ry 21,ry 13,cx 7,...,ry 14,ry 5,cx 9,ry 1,y 4,ry 2,ry 3,ry 0,ry 11,ry 12
sum,16.161071,15.072921,14.872535,14.496499,13.602658,12.173067,6.518304,3.41328,3.146455,2.796396,...,1.422822,0.55807,0.51161,0.394747,0.088646,0.004482,0.003029,5.215885e-10,1.082647e-10,2.867747e-11

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_z_inGap_19_.qasm

100%|██████████| 10/10 [00:19<00:00,  1.97s/it]
100%|██████████| 10/10 [00:19<00:00,  1.96s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,z 18,cx 17,cx 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.390790,1.146667,0.469649,1.715797,2.334633,0.484484,2.455453,1.634069,1.874391,1.984018,...,0.100326,0.524739,0.540167,0.430145,0.208724,0.013055,0.018287,0.180873,0.000007,fail
1,0.695933,1.342175,0.794755,1.859526,2.278472,0.436377,2.381589,1.867645,1.870996,1.828953,...,0.195701,0.555224,0.576656,0.410777,0.218489,0.014223,0.018408,0.179133,0.000007,fail
2,0.552263,1.137266,0.817214,1.372608,2.531199,0.523249,2.895227,2.644224,2.376226,2.149761,...,0.338587,0.767325,0.814636,0.609386,0.309491,0.018839,0.025052,0.277739,0.000009,fail
3,0.483430,1.340741,0.692543,1.407880,1.644488,0.351840,1.898561,1.980708,1.596180,1.473950,...,0.299506,0.599878,0.569256,0.446704,0.210639,0.016102,0.018365,0.217340,0.000006,fail
4,0.708530,1.534642,0.724633,1.401956,3.114361,0.603408,3.470871,2.835090,2.585646,2.373013,...,0.254475,0.793547,0.818599,0.576642,0.285326,0.020849,0.025769,0.285843,0.000011,fail
5,0.401129,0.993070,0.478260,1.685631,1.977340,0.401271,2.085961,1.592091,1.776797,1.762836,...,0.121939,0.533699,0.494627,0.402011,0.189674,0.013026,0.016702,0.171026,0.000006,fail
6,0.464071,1.131148,0.631781,1.497158,2.161388,0.423516,2.318577,1.819874,1.859325,1.608285,...,0.207663,0.538487,0.562241,0.417157,0.189225,0.015765,0.017231,0.178617,0.000007,fail
7,0.589239,1.234102,0.930447,1.186279,1.679144,0.351993,1.984421,2.251518,1.725597,1.380509,...,0.322702,0.613113,0.578422,0.461503,0.208406,0.019090,0.018687,0.226099,0.000006,fail
8,0.582300,1.488294,0.788353,1.827236,2.178285,0.415037,2.343527,2.104138,2.277332,2.058308,...,0.172540,0.692846,0.681530,0.515177,0.257474,0.016122,0.021682,0.220225,0.000008,fail
9,0.593637,1.166602,0.646296,1.840236,2.136732,0.432597,2.337797,2.056989,1.690155,1.408475,...,0.312094,0.635673,0.576079,0.454162,0.207751,0.018159,0.018241,0.207842,0.000006,fail
10,0.507709,1.482864,1.053311,1.789738,2.413722,0.467304,2.602447,1.921047,1.398039,1.455805,...,0.346371,0.651919,0.626490,0.500057,0.238136,0.016536,0.019051,0.212255,0.000007,pass
11,0.550746,1.279390,0.904263,1.733279,1.387764,0.258616,1.419429,1.477194,1.371455,1.474042,...,0.266602,0.503725,0.532163,0.468434,0.223444,0.013985,0.017814,0.179731,0.000004,pass
12,0.339196,0.765955,0.529777,0.867110,0.963772,0.193721,1.061404,1.087153,0.854035,0.709125,...,0.186684,0.315997,0.309280,0.293000,0.138334,0.010210,0.009995,0.115279,0.000003,pass
13,0.521558,0.997479,0.885636,1.056378,1.463782,0.266216,1.589451,1.344831,1.030571,0.977920,...,0.261413,0.444611,0.421818,0.368375,0.166584,0.012894,0.012869,0.148376,0.000005,pass
14,0.374367,0.620045,0.821939,1.848797,1.652326,0.292759,1.579350,0.928943,0.950491,0.982744,...,0.304226,0.382179,0.455695,0.418294,0.189860,0.012231,0.013147,0.116170,0.000005,pass
15,0.454133,0.799001,0.768636,1.382163,1.452602,0.304286,1.600166,1.543689,1.259862,1.076189,...,0.262077,0.442533,0.430850,0.378907,0.192462,0.013204,0.015025,0.158048,0.000005,pass
16,0.493482,1.157285,0.628389,2.035664,1.516623,0.276200,1.546301,1.742092,1.614580,1.567012,...,0.169519,0.553364,0.515176,0.376578,0.192295,0.015258,0.017912,0.187176,0.000005,pass
17,0.531850,1.625795,0.690316,2.225448,1.457293,0.260762,1.493076,1.694997,1.287001,1.431597,...,0.168849,0.557426,0.510145,0.446646,0.258999,0.014113,0.017713,0.210110,0.000004,pass
18,0.414781,1.290120,0.584948,1.725238,2.274425,0.459583,2.506816,2.106029,2.043017,2.063651,...,0.216934,0.693833,0.663097,0.547077,0.288188,0.016623,0.021562,0.241582,0.000008,pass
19,0.488463,0.830315,0.567217,1.191599,1.575337,0.335218,1.706403,1.589430,1.513859,1.332481,...,0.161743,0.427549,0.397129,0.296624,0.135205,0.012850,0.014494,0.150659,0.000006,pass

BARINEL SCORES

,ry 9,ry 11,ry 10,cx 15,z 18,ry 0,cx 17,cx 14,ry 12,ry 19,...,ry 2,ry 13,ry 3,ry 23,cx 5,ry 22,ry 4,ry 20,cx 8,ry 21
sum,0.626282,0.601287,0.597167,0.595731,0.586829,0.586782,0.585607,0.579707,0.578671,0.576955,...,0.554246,0.545905,0.545076,0.538719,0.535705,0.535665,0.530368,0.499035,0.497978,0.48402

TARANTULA SCORES

,ry 9,ry 11,ry 10,cx 15,z 18,ry 0,cx 17,cx 14,ry 12,ry 19,...,ry 2,ry 13,ry 3,ry 23,cx 5,ry 22,ry 4,ry 20,cx 8,ry 21
sum,0.626282,0.601287,0.597167,0.595731,0.586829,0.586782,0.585607,0.579707,0.578671,0.576955,...,0.554246,0.545905,0.545076,0.538719,0.535705,0.535665,0.530368,0.499035,0.497978,0.48402

DSTAR SCORES

,cx 17,ry 19,cx 16,cx 15,cx 14,ry 20,ry 22,ry 12,ry 21,ry 9,...,z 18,ry 13,cx 8,ry 4,ry 1,ry 2,ry 3,ry 0,ry 10,ry 11
sum,21.55647,18.563869,16.987039,16.526272,14.087765,9.648274,7.512282,2.973737,2.789636,2.636084,...,1.492203,1.344235,0.438101,0.434327,0.392504,0.003875,0.002693,5.364348e-10,1.166384e-10,2.540300e-11

ERROR GATE LOCATION:
18
Now evolving the following mutant:  AddGate_h_inGap_10_.qasm

100%|██████████| 10/10 [00:24<00:00,  2.42s/it]
100%|██████████| 10/10 [00:21<00:00,  2.17s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.495857,1.150488,0.939017,1.400930,2.376971,2.661814,2.286240,1.603485,1.592799,0.396368,...,1.233510,0.668704,1.078705,1.180254,0.442513,0.025848,0.032341,0.286899,0.000008,fail
1,0.546534,1.273795,0.600195,1.608433,2.047154,2.263305,2.090944,2.092545,1.892898,0.491200,...,1.307995,0.669829,1.050600,1.094687,0.438105,0.026643,0.031479,0.308227,0.000008,fail
2,0.496038,0.573084,0.658301,1.542808,2.168115,2.390476,1.992224,2.121316,2.056690,0.471804,...,1.285238,0.743077,1.060414,1.122764,0.417037,0.026566,0.032596,0.315491,0.000007,fail
3,0.573342,1.104112,0.845235,1.729123,2.459188,2.698611,2.265473,2.448085,2.342513,0.512879,...,1.457812,0.877395,1.157789,1.211163,0.510116,0.030295,0.035689,0.356812,0.000008,fail
4,0.262188,1.304030,0.631380,1.185332,2.320383,2.576000,1.829454,1.660744,1.661906,0.441252,...,1.173522,0.741281,0.906919,1.036200,0.428137,0.027660,0.026550,0.286702,0.000007,fail
5,0.548247,1.093116,0.949419,1.540708,2.477885,2.598608,1.775898,1.800782,1.458826,0.340933,...,1.153764,0.762113,0.950032,0.988798,0.427273,0.024841,0.028576,0.317474,0.000006,fail
6,0.456090,1.345687,0.800000,1.358355,1.966615,2.138043,1.842061,1.646480,1.480126,0.345272,...,1.042123,0.698488,0.825540,0.884765,0.405543,0.021975,0.027199,0.257573,0.000005,fail
7,0.456249,1.239263,0.743037,1.784895,1.801349,1.987926,2.253224,1.992118,1.600727,0.431588,...,1.052245,0.713282,0.956961,1.013468,0.429725,0.021807,0.031444,0.292280,0.000007,fail
8,0.526429,1.236315,0.632571,1.813156,1.875540,1.871882,1.397994,1.487837,1.252683,0.319369,...,1.002818,0.704086,0.803995,0.854676,0.391822,0.022286,0.024427,0.330007,0.000006,fail
9,0.747095,1.935661,0.955642,1.528612,2.026246,2.241532,2.242751,1.572568,1.246421,0.440893,...,0.957205,0.617585,0.822525,0.861211,0.382414,0.022579,0.026023,0.237836,0.000006,fail
10,0.313220,1.005904,0.511645,1.639609,1.352235,1.461959,1.656441,1.427695,0.927314,0.336816,...,0.644655,0.613131,0.643244,0.732809,0.304813,0.018751,0.023067,0.237504,0.000004,pass
11,0.559153,1.257623,0.790014,1.258797,1.481626,1.563570,1.416334,1.414688,1.717358,0.443655,...,0.851753,0.661375,0.763211,0.737901,0.343954,0.023149,0.027433,0.275899,0.000004,pass
12,0.194736,0.662782,0.369028,0.540746,0.897251,1.003778,0.898339,0.708999,0.679392,0.223893,...,0.460783,0.283440,0.426456,0.521028,0.209850,0.014051,0.014101,0.128192,0.000004,pass
13,0.575270,1.141326,0.989237,2.137989,2.072546,2.082492,1.650479,1.937706,1.763851,0.535613,...,1.166233,0.854974,0.902161,0.896747,0.371893,0.029342,0.033405,0.385241,0.000007,pass
14,0.505652,1.247995,0.686250,1.787600,1.761793,1.869181,1.754216,1.760416,1.704847,0.427237,...,0.989000,0.699315,0.854841,0.815154,0.308762,0.021234,0.027468,0.297172,0.000006,pass
15,0.500665,1.188923,0.880060,0.867217,1.732568,2.075678,2.406692,2.194775,2.287825,0.600881,...,1.183674,0.532082,0.946956,0.970580,0.363306,0.022103,0.030833,0.190203,0.000007,pass
16,0.272158,0.630492,0.377965,0.943084,1.270224,1.384753,1.079251,1.504484,1.613009,0.340797,...,0.831156,0.439166,0.575374,0.588429,0.225380,0.017696,0.016955,0.180882,0.000004,pass
17,0.574725,1.341585,0.823184,1.807920,2.471609,2.580449,1.885666,1.969901,1.822886,0.449802,...,1.190576,0.890040,1.083658,1.077395,0.485317,0.029314,0.035855,0.372942,0.000007,pass
18,0.539480,1.126135,0.698062,1.666673,1.519989,1.567722,1.638550,1.640028,1.505744,0.394859,...,0.758655,0.607109,0.722200,0.694153,0.272076,0.020930,0.022323,0.263609,0.000005,pass
19,0.404102,0.890610,0.648041,1.160967,1.813124,2.045824,1.839258,1.648753,1.888423,0.557498,...,1.067198,0.569645,0.902489,0.940100,0.357919,0.022453,0.031499,0.255854,0.000006,pass

BARINEL SCORES

,h 9,ry 10,cx 18,ry 4,ry 19,cx 5,cx 8,ry 0,cx 17,cx 6,...,ry 21,ry 3,ry 11,cx 16,ry 2,ry 20,ry 13,ry 12,cx 15,ry 14
sum,0.572936,0.571794,0.570534,0.568482,0.567909,0.562388,0.560609,0.559426,0.551808,0.551419,...,0.533772,0.533521,0.53351,0.532029,0.529848,0.528696,0.525288,0.521739,0.510385,0.492973

TARANTULA SCORES

,h 9,ry 10,cx 18,ry 4,ry 19,cx 5,cx 8,ry 0,cx 17,cx 6,...,ry 21,ry 3,ry 11,cx 16,ry 2,ry 20,ry 13,ry 12,cx 15,ry 14
sum,0.572936,0.571794,0.570534,0.568482,0.567909,0.562388,0.560609,0.559426,0.551808,0.551419,...,0.533772,0.533521,0.53351,0.532029,0.529848,0.528696,0.525288,0.521739,0.510385,0.492973

DSTAR SCORES

,cx 18,ry 19,cx 17,cx 16,cx 15,ry 20,ry 22,cx 8,cx 5,cx 6,...,ry 10,ry 23,ry 4,ry 14,ry 1,ry 2,ry 3,ry 0,ry 11,ry 12
sum,19.861493,17.559139,15.216307,12.954944,10.616551,10.080089,7.329126,7.109445,5.842856,5.186079,...,2.251492,1.807056,1.3785,1.227664,0.709904,0.008556,0.006141,4.538419e-10,9.680474e-11,2.222986e-11

ERROR GATE LOCATION:
9
Now evolving the following mutant:  AddGate_ry_inGap_26_.qasm

100%|██████████| 10/10 [00:23<00:00,  2.31s/it]
100%|██████████| 10/10 [00:19<00:00,  1.95s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,ry 18,cx 17,cx 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.542383,1.335695,1.493874,0.950681,1.695178,1.484759,1.650136,2.354091,2.029161,1.941201,...,1.103323,0.997040,0.717989,0.653523,0.425535,0.025271,0.030862,0.248420,0.000008,fail
1,0.455308,1.535930,1.467546,0.947804,1.665075,2.676282,2.960696,2.811095,2.484549,2.538800,...,1.085774,1.300615,1.034837,0.781348,0.458083,0.027461,0.038303,0.300711,0.000007,fail
2,0.489871,1.415861,1.082269,0.695746,1.667238,1.932304,1.994051,1.950969,1.456528,1.213115,...,0.727762,0.802425,0.441979,0.340127,0.234061,0.018643,0.023575,0.142152,0.000005,fail
3,0.650683,0.863809,1.330649,0.857454,1.475280,2.005973,2.207549,2.498644,2.317225,2.182746,...,0.985455,1.116400,0.927389,0.579089,0.307301,0.030418,0.031323,0.265212,0.000009,fail
4,0.354711,1.094887,1.034513,0.651717,1.652983,1.936494,2.059273,2.129391,1.958737,2.084759,...,0.815709,0.985078,0.828759,0.590109,0.346269,0.019889,0.026671,0.218859,0.000008,fail
5,0.495982,1.355747,1.387034,0.889190,1.712885,1.484590,1.611952,2.079914,1.648893,1.342935,...,0.980451,0.851161,0.522491,0.463126,0.312246,0.022773,0.023386,0.181440,0.000006,fail
6,0.465096,1.443725,1.627632,1.040195,1.712326,2.357111,2.622857,3.051119,2.528914,2.299720,...,1.255599,1.346480,0.966743,0.782895,0.516237,0.028568,0.037910,0.305542,0.000009,fail
7,0.546995,1.264802,1.293423,0.818293,1.969003,2.050866,2.251092,2.757938,2.414186,2.247949,...,1.152640,1.249942,0.913084,0.697473,0.439092,0.029159,0.032491,0.283559,0.000008,fail
8,0.585795,1.700486,1.576876,1.027457,2.042405,2.240257,2.402334,2.634027,2.132820,1.935791,...,0.883421,1.190728,0.922939,0.666146,0.345504,0.027664,0.031836,0.231186,0.000007,fail
9,0.524974,1.355317,1.077704,0.701198,1.548181,1.704456,1.792623,1.915698,1.500558,1.212417,...,0.752912,0.787136,0.570589,0.367969,0.197595,0.022485,0.020176,0.148570,0.000005,fail
10,0.435473,1.144018,0.947987,0.598919,1.120064,1.938997,2.267952,2.616712,2.421259,2.231208,...,0.977470,0.951989,0.684897,0.549032,0.386657,0.021719,0.029536,0.287182,0.000009,pass
11,0.527566,1.232372,0.923120,0.600219,1.263847,2.336726,2.648715,2.395659,2.280532,1.959496,...,0.873136,0.868595,0.660812,0.529292,0.346742,0.025680,0.030460,0.250274,0.000006,pass
12,0.472390,1.081439,0.865492,0.551296,1.939850,1.547802,1.819030,2.780167,2.758166,2.281270,...,0.585624,1.003692,0.817052,0.672080,0.381688,0.020917,0.030420,0.290523,0.000008,pass
13,0.642762,1.164847,0.951488,0.619636,1.060691,1.784904,1.835272,1.580212,1.125977,0.981635,...,0.529804,0.525285,0.374154,0.266044,0.202364,0.017830,0.018930,0.104994,0.000004,pass
14,0.406864,0.808396,1.183906,0.763253,1.015570,1.249739,1.282238,1.354402,1.023172,1.227424,...,0.830731,0.638838,0.484547,0.447321,0.304193,0.018791,0.022690,0.149752,0.000005,pass
15,0.642065,1.164311,1.401195,0.909739,1.182034,1.969482,2.224886,2.296671,2.099125,2.276317,...,1.161697,1.085902,0.985582,0.631870,0.401656,0.031340,0.033333,0.287912,0.000008,pass
16,0.220406,0.475965,0.519545,0.321992,0.902877,1.468009,1.681307,1.636694,1.675027,1.612363,...,0.508744,0.670733,0.529511,0.419688,0.250116,0.013509,0.020527,0.192245,0.000005,pass
17,0.538352,1.429715,1.004909,0.643601,1.635731,1.751023,1.973382,2.589174,2.495938,2.710828,...,0.878770,1.106279,0.963867,0.621926,0.419797,0.024522,0.034340,0.299265,0.000008,pass
18,0.514864,1.119843,1.162764,0.736685,1.797915,1.634262,1.716467,2.131450,1.757021,1.412779,...,0.871640,0.859720,0.563567,0.542402,0.364705,0.023749,0.023591,0.187378,0.000005,pass
19,0.437803,0.869894,1.006368,0.627730,1.197186,1.759670,1.852014,1.905747,1.534782,1.415322,...,0.790644,0.806164,0.469658,0.456849,0.342485,0.017150,0.023874,0.167661,0.000005,pass

BARINEL SCORES

,ry 20,ry 21,ry 19,ry 22,cx 7,cx 8,cx 6,ry 11,ry 3,cx 5,...,ry 13,ry 2,ry 10,cx 15,ry 23,ry 9,ry 4,cx 14,ry 1,ry 12
sum,0.573788,0.572943,0.566512,0.560264,0.555103,0.548864,0.545658,0.545367,0.539702,0.535507,...,0.525941,0.525549,0.520164,0.516404,0.513731,0.513492,0.512999,0.512003,0.511938,0.510051

TARANTULA SCORES

,ry 20,ry 21,ry 19,ry 22,cx 7,cx 8,cx 6,ry 11,ry 3,cx 5,...,ry 13,ry 2,ry 10,cx 15,ry 23,ry 9,ry 4,cx 14,ry 1,ry 12
sum,0.573788,0.572943,0.566512,0.560264,0.555103,0.548864,0.545658,0.545367,0.539702,0.535507,...,0.525941,0.525549,0.520164,0.516404,0.513731,0.513492,0.512999,0.512003,0.511938,0.510051

DSTAR SCORES

,cx 16,cx 17,ry 18,cx 15,cx 14,ry 19,ry 21,ry 22,cx 7,cx 8,...,ry 9,ry 23,ry 13,ry 4,ry 1,ry 2,ry 3,ry 0,ry 10,ry 11
sum,18.691917,15.853003,14.392528,14.366502,12.842258,12.709881,8.954753,8.718881,6.098832,5.271299,...,2.13874,1.760987,1.722005,0.957447,0.442709,0.008564,0.006233,5.233863e-10,9.263691e-11,3.283542e-11

ERROR GATE LOCATION:
21
Now evolving the following mutant:  AddGate_rxx_inGap_14_.qasm

100%|██████████| 10/10 [00:20<00:00,  2.08s/it]
100%|██████████| 10/10 [00:21<00:00,  2.14s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.585444,1.095796,0.961531,1.285599,1.869216,2.122602,1.888291,1.507294,1.837269,0.503248,...,0.385117,0.645404,0.673651,0.607551,0.296807,0.016640,0.022830,0.264268,0.000008,fail
1,0.745014,1.443786,0.843476,1.288913,1.699909,2.042804,2.590431,2.388903,1.940539,0.460658,...,0.220234,0.684180,0.668001,0.494834,0.262973,0.017978,0.021864,0.250134,0.000008,fail
2,0.273848,0.741844,0.500569,1.569824,1.690297,1.771322,1.294955,1.214260,1.471093,0.419448,...,0.226660,0.450594,0.474703,0.439064,0.232015,0.011757,0.015505,0.171301,0.000006,fail
3,0.580350,1.489942,0.903604,1.596071,2.070793,2.302537,2.373596,2.112649,2.251231,0.610282,...,0.243715,0.679245,0.678500,0.539367,0.293433,0.019203,0.021197,0.271311,0.000009,fail
4,0.488990,0.925780,0.405635,1.328360,1.129059,1.331695,1.928750,2.097412,1.970640,0.456756,...,0.127049,0.587738,0.614719,0.436861,0.218957,0.014412,0.021421,0.227993,0.000006,fail
5,0.438306,1.026112,0.736636,2.055861,1.662214,1.711722,1.788570,1.776588,1.561789,0.392401,...,0.202180,0.504233,0.527771,0.439135,0.234270,0.014425,0.017647,0.182157,0.000005,fail
6,0.595712,0.894672,0.683994,1.446603,1.756182,1.899214,1.859336,1.848610,1.786343,0.476551,...,0.204756,0.553426,0.576049,0.446147,0.208602,0.016109,0.019805,0.210226,0.000006,fail
7,0.512794,1.370715,0.864211,1.275477,1.871991,2.150671,2.428768,2.177877,1.869634,0.569750,...,0.324958,0.680822,0.681477,0.637514,0.331705,0.017499,0.023044,0.253302,0.000008,fail
8,0.687395,1.708560,0.940671,1.684072,1.983977,2.154780,2.176480,1.606790,1.151099,0.360513,...,0.262567,0.524975,0.507611,0.471835,0.254717,0.017218,0.016019,0.198138,0.000006,fail
9,0.479287,1.122966,0.467995,1.784610,1.851841,2.092509,2.116103,1.911012,2.289186,0.590045,...,0.216089,0.721722,0.685274,0.556609,0.297229,0.016571,0.025395,0.283438,0.000007,fail
10,0.329961,0.390378,0.293698,1.005399,0.705772,0.724262,0.683080,0.721146,0.721431,0.163114,...,0.112746,0.229932,0.246845,0.201183,0.103401,0.006420,0.008799,0.084264,0.000002,pass
11,0.439662,1.068673,0.541594,1.368773,1.581716,1.594566,0.878290,0.725339,0.815308,0.243719,...,0.167778,0.320894,0.326767,0.241825,0.119263,0.009085,0.009866,0.095766,0.000004,pass
12,0.599715,0.916165,0.588032,1.830563,1.746884,2.031667,2.476636,2.645308,2.415032,0.515996,...,0.125275,0.711467,0.721564,0.526528,0.274741,0.016869,0.024942,0.269577,0.000007,pass
13,0.683002,1.592213,0.996237,1.803951,2.163083,2.334947,2.150706,1.984089,2.118229,0.488324,...,0.301200,0.668988,0.719178,0.523318,0.259451,0.017762,0.023663,0.241975,0.000008,pass
14,0.529588,0.854266,0.664380,1.573605,1.516069,1.611265,1.539526,1.572826,1.449931,0.387782,...,0.182742,0.478839,0.496188,0.438161,0.218094,0.012385,0.016520,0.172499,0.000006,pass
15,0.516260,1.083654,0.775161,1.864128,2.526364,2.574015,1.470447,1.328384,1.315979,0.360098,...,0.278395,0.510613,0.497477,0.393913,0.178940,0.014569,0.016167,0.148558,0.000006,pass
16,0.562081,1.353058,0.729703,2.208188,2.272449,2.424557,2.014768,1.860593,1.974375,0.503177,...,0.201723,0.587809,0.622337,0.529002,0.276569,0.017912,0.020327,0.239281,0.000007,pass
17,0.505941,1.084961,0.815715,1.565482,1.598252,1.723005,1.915342,1.629691,1.236737,0.399543,...,0.252259,0.519341,0.482786,0.374483,0.165538,0.016231,0.015122,0.171741,0.000006,pass
18,0.306633,0.834181,0.620975,1.209378,1.349168,1.556130,1.757881,1.712425,1.611842,0.454522,...,0.167629,0.535226,0.504113,0.425577,0.211094,0.012521,0.017040,0.193719,0.000006,pass
19,0.394670,0.847645,0.700994,1.314201,1.144282,1.183278,1.103085,0.961050,0.644720,0.207563,...,0.203060,0.357275,0.332130,0.253629,0.125578,0.009601,0.009386,0.098770,0.000004,pass

BARINEL SCORES

,ry 4,ry 1,rxx 13,ry 14,cx 5,ry 10,cx 17,cx 15,ry 2,ry 0,...,ry 3,ry 12,cx 8,ry 22,ry 11,ry 23,cx 18,ry 21,ry 19,ry 20
sum,0.576483,0.573989,0.568175,0.565149,0.564685,0.563258,0.561143,0.558972,0.55851,0.553116,...,0.548206,0.547983,0.54772,0.541084,0.537735,0.525336,0.524401,0.520728,0.514353,0.493105

TARANTULA SCORES

,ry 4,ry 1,rxx 13,ry 14,cx 5,ry 10,cx 17,cx 15,ry 2,ry 0,...,ry 3,ry 12,cx 8,ry 22,ry 11,ry 23,cx 18,ry 21,ry 19,ry 20
sum,0.576483,0.573989,0.568175,0.565149,0.564685,0.563258,0.561143,0.558972,0.55851,0.553116,...,0.548206,0.547983,0.54772,0.541084,0.537735,0.525336,0.524401,0.520728,0.514353,0.493105

DSTAR SCORES

,cx 17,cx 16,cx 18,cx 15,ry 19,ry 20,ry 22,ry 21,ry 12,cx 6,...,ry 14,ry 4,cx 8,ry 1,rxx 13,ry 2,ry 3,ry 0,ry 10,ry 11
sum,16.083618,13.822189,13.811335,13.522872,11.624142,9.111411,6.977035,3.193233,2.58714,2.479084,...,1.706682,0.579973,0.485636,0.456343,0.215457,0.004125,0.002584,4.730817e-10,1.091064e-10,2.171741e-11

ERROR GATE LOCATION:
13
Now evolving the following mutant:  AddGate_x_inGap_6_.qasm

100%|██████████| 10/10 [00:20<00:00,  2.05s/it]
100%|██████████| 10/10 [00:20<00:00,  2.03s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,x 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.680005,1.304328,0.774187,2.395695,1.930617,2.025810,2.215007,2.394856,2.241849,0.587484,...,0.666833,0.739060,0.528910,0.091913,0.274617,0.019893,0.023556,0.250172,0.000007,fail
1,0.673379,1.480755,0.840793,2.030167,2.415578,2.587387,2.302841,1.984877,1.534614,0.488744,...,0.676207,0.627434,0.490413,0.085086,0.269368,0.018375,0.020770,0.214836,0.000007,fail
2,0.434694,0.918735,0.636442,1.882015,1.864363,2.046663,2.140966,2.341041,2.323363,0.575095,...,0.716102,0.813718,0.636270,0.105302,0.309960,0.019310,0.027668,0.271691,0.000008,fail
3,0.386844,1.036063,0.667159,1.520368,1.747612,2.001712,2.279447,2.502090,2.197902,0.581321,...,0.679949,0.655654,0.543200,0.099780,0.290730,0.014183,0.021601,0.232132,0.000007,fail
4,0.636264,1.288986,0.744329,1.556449,2.101935,2.352489,2.419864,2.382368,2.268638,0.610775,...,0.738764,0.794053,0.554992,0.094805,0.299861,0.018929,0.024543,0.275650,0.000008,fail
5,0.612263,1.128402,0.864348,1.516656,2.125156,2.356172,2.211046,1.853857,1.616087,0.473017,...,0.667999,0.657748,0.579544,0.087611,0.293191,0.018840,0.019500,0.238011,0.000008,fail
6,0.522210,0.773536,0.648867,1.080905,2.007062,2.127482,1.499998,1.316195,1.277580,0.373139,...,0.362501,0.413345,0.383688,0.062160,0.217380,0.013350,0.013388,0.142318,0.000006,fail
7,0.639720,1.127754,0.873357,1.549683,1.913229,2.058183,1.833099,1.510592,1.334668,0.409456,...,0.516325,0.518831,0.421948,0.069329,0.216285,0.013976,0.017182,0.176661,0.000005,fail
8,0.683377,1.437526,1.018336,1.962664,1.551002,1.706785,2.249567,2.130266,1.981119,0.648520,...,0.697517,0.673007,0.536330,0.098080,0.285860,0.016856,0.021257,0.250828,0.000006,fail
9,0.573538,1.198219,0.732867,1.626545,1.606298,1.746470,1.943289,1.877492,1.701477,0.412504,...,0.548856,0.575518,0.518595,0.086235,0.258063,0.016540,0.020487,0.198785,0.000005,fail
10,0.608802,1.044411,0.779025,1.757968,2.255770,2.400853,2.057080,2.134449,1.635794,0.516823,...,0.607843,0.660362,0.549060,0.086398,0.272623,0.018141,0.020648,0.201136,0.000007,pass
11,0.371785,0.948423,0.619523,1.211028,1.723453,1.827118,1.297806,1.225442,1.037393,0.316076,...,0.387344,0.413895,0.283749,0.048954,0.131564,0.012433,0.012682,0.121398,0.000005,pass
12,0.597073,1.313909,0.752090,1.672549,2.035197,2.180652,2.057009,1.629171,1.332206,0.340093,...,0.525848,0.542126,0.429568,0.057565,0.223546,0.016516,0.016127,0.196161,0.000006,pass
13,0.475508,0.890997,0.646589,1.470138,1.643308,1.820960,1.996032,1.984202,1.979219,0.498162,...,0.612243,0.651204,0.481306,0.084716,0.253860,0.014984,0.021353,0.236172,0.000007,pass
14,0.319529,0.989530,0.601511,1.358616,1.214721,1.277110,1.225941,1.100368,0.983190,0.263663,...,0.400191,0.364878,0.321642,0.049508,0.147632,0.010414,0.010657,0.116148,0.000004,pass
15,0.254016,0.987304,0.551483,1.643996,2.306217,2.435558,1.488591,1.567033,1.657142,0.485094,...,0.568813,0.591298,0.512199,0.085578,0.245028,0.012191,0.018277,0.182257,0.000007,pass
16,0.461403,0.981129,0.749196,1.214698,1.668610,1.800642,1.353253,1.236686,1.176194,0.310783,...,0.456156,0.526468,0.432450,0.065043,0.184397,0.013040,0.017871,0.157944,0.000005,pass
17,0.662983,1.362874,0.888436,2.265848,1.813249,1.864703,1.603633,1.085338,1.161645,0.307481,...,0.490494,0.463773,0.411961,0.059478,0.197665,0.015840,0.014996,0.183534,0.000005,pass
18,0.533230,1.439350,0.738194,1.939674,2.263699,2.371995,1.877878,1.926645,1.750330,0.439734,...,0.603441,0.650477,0.496275,0.072944,0.256379,0.015723,0.019788,0.206785,0.000007,pass
19,0.408036,0.922360,0.772425,1.357251,1.791931,2.023808,1.789155,1.575510,1.858310,0.550598,...,0.613297,0.669105,0.538339,0.093429,0.273471,0.014604,0.021867,0.249384,0.000007,pass

BARINEL SCORES

,ry 11,ry 12,cx 16,ry 14,cx 15,cx 17,x 5,ry 23,ry 13,ry 4,...,cx 7,cx 6,ry 10,ry 0,ry 21,ry 20,ry 22,cx 18,ry 19,cx 9
sum,0.569711,0.568044,0.56752,0.561574,0.559093,0.55746,0.555776,0.554578,0.554389,0.553978,...,0.538943,0.538202,0.534424,0.53104,0.523566,0.51862,0.51803,0.512262,0.507197,0.49682

TARANTULA SCORES

,ry 11,ry 12,cx 16,ry 14,cx 15,cx 17,x 5,ry 23,ry 13,ry 4,...,cx 7,cx 6,ry 10,ry 0,ry 21,ry 20,ry 22,cx 18,ry 19,cx 9
sum,0.569711,0.568044,0.56752,0.561574,0.559093,0.55746,0.555776,0.554578,0.554389,0.553978,...,0.538943,0.538202,0.534424,0.53104,0.523566,0.51862,0.51803,0.512262,0.507197,0.49682

DSTAR SCORES

,cx 17,cx 16,cx 18,cx 15,ry 19,ry 20,ry 22,ry 21,ry 13,cx 7,...,cx 6,ry 4,cx 9,ry 1,x 5,ry 2,ry 3,ry 0,ry 11,ry 12
sum,16.637926,16.172555,14.711149,13.894617,12.921557,11.321503,6.549563,3.558837,2.713385,2.693505,...,1.866039,0.605025,0.476983,0.427594,0.072399,0.004332,0.002857,4.618854e-10,1.176368e-10,2.799537e-11

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_swap_inGap_14_.qasm

100%|██████████| 10/10 [00:19<00:00,  1.90s/it]
100%|██████████| 10/10 [00:17<00:00,  1.78s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.527633,1.118354,0.822416,1.790368,1.578710,1.781799,2.070610,2.056263,2.089040,0.405169,...,0.279955,0.735601,0.420490,0.420582,0.115747,0.011808,0.015581,0.168111,0.000005,fail
1,0.554615,1.241910,0.965995,1.985257,2.296663,2.480597,2.009801,2.043826,2.224177,0.460004,...,0.364745,0.844915,0.492717,0.414581,0.133653,0.011977,0.017750,0.177869,0.000006,fail
2,0.608120,1.132688,0.751704,1.641293,1.262854,1.399493,1.722944,1.546642,1.257863,0.261992,...,0.278179,0.615564,0.310784,0.286781,0.102860,0.008448,0.012796,0.118957,0.000003,fail
3,0.723121,1.237561,0.557551,1.337975,1.809868,2.120637,2.427308,2.423073,1.787756,0.479154,...,0.158545,0.757829,0.347058,0.287677,0.112917,0.008431,0.010801,0.140171,0.000005,fail
4,0.627766,1.267778,0.775954,1.985766,1.847988,1.868426,1.438075,1.614565,1.480996,0.332404,...,0.215893,0.571234,0.333930,0.305354,0.092286,0.008776,0.012796,0.103817,0.000004,fail
5,0.587211,1.163913,0.700096,1.572874,1.770465,2.052805,2.246792,2.218788,1.984650,0.507446,...,0.251020,0.771043,0.409108,0.378312,0.121172,0.011344,0.014849,0.170865,0.000005,fail
6,0.668441,1.388565,0.700760,1.681497,1.913060,2.089307,1.830183,1.949268,2.153629,0.425751,...,0.174807,0.748784,0.418689,0.365096,0.105500,0.011590,0.014555,0.176395,0.000005,fail
7,0.602985,0.944675,1.005729,1.609055,2.399256,2.664962,2.194293,2.227812,2.535077,0.556698,...,0.335300,0.893820,0.539287,0.481977,0.139893,0.014014,0.019371,0.206470,0.000007,fail
8,0.818947,1.534462,1.114358,1.641008,2.288730,2.390737,1.902737,1.871350,1.291663,0.420841,...,0.305140,0.647718,0.418035,0.347778,0.118238,0.011132,0.015916,0.133662,0.000006,fail
9,0.623308,1.335344,0.796535,1.794114,2.510005,2.575191,1.733297,1.593743,1.518407,0.484143,...,0.240172,0.636312,0.387718,0.288234,0.113081,0.008347,0.013163,0.120848,0.000005,fail
10,0.284709,1.080828,0.475369,1.122725,1.471674,1.606911,1.643617,1.409930,1.236934,0.453577,...,0.181768,0.549298,0.354868,0.345522,0.097666,0.011462,0.013135,0.147809,0.000005,pass
11,0.563030,1.037926,0.873968,1.831187,1.899103,2.013198,1.881075,1.767871,1.379511,0.369455,...,0.266272,0.618697,0.365888,0.302206,0.100357,0.008368,0.013099,0.118013,0.000004,pass
12,0.385290,1.021693,0.666658,1.005788,1.679881,1.973498,2.473998,1.958067,1.493413,0.412018,...,0.233795,0.685420,0.396554,0.307848,0.105405,0.009505,0.012992,0.158104,0.000006,pass
13,0.548087,1.443482,0.846934,2.243208,2.223246,2.226368,1.748115,1.462077,1.011078,0.397939,...,0.261255,0.589705,0.381757,0.363527,0.108611,0.011140,0.015166,0.120489,0.000005,pass
14,0.684332,1.685261,0.954916,2.260231,2.272999,2.368003,2.192293,2.114506,1.687948,0.451229,...,0.346366,0.769937,0.413767,0.364716,0.140772,0.010527,0.015481,0.137788,0.000005,pass
15,0.233331,0.648200,0.333684,0.940418,0.910413,0.983645,0.878823,0.660310,0.965950,0.282207,...,0.171932,0.330055,0.213746,0.193483,0.063082,0.005368,0.007467,0.082611,0.000002,pass
16,0.529045,1.114653,0.836010,1.202974,1.641210,1.789116,1.759235,1.477914,1.265520,0.291481,...,0.320625,0.571788,0.377787,0.343819,0.096442,0.010549,0.015208,0.139576,0.000005,pass
17,0.399740,0.765037,0.458379,1.680352,1.500955,1.482133,1.159378,1.220757,1.468717,0.300140,...,0.148075,0.475026,0.280996,0.215171,0.072932,0.005928,0.008707,0.079429,0.000003,pass
18,0.536428,1.390620,0.880930,1.956541,1.574740,1.694594,1.815542,1.924277,1.693621,0.516452,...,0.153644,0.605575,0.375933,0.373342,0.110920,0.011579,0.013121,0.143500,0.000004,pass
19,0.486312,1.505023,0.809385,1.622294,2.481519,2.621048,2.018313,1.533639,1.452639,0.499707,...,0.302612,0.657133,0.425908,0.365429,0.122305,0.011289,0.015799,0.149240,0.000006,pass

BARINEL SCORES

,ry 23,cx 15,ry 11,ry 10,ry 9,cx 16,swap 13,cx 7,ry 1,ry 0,...,ry 2,cx 5,ry 19,cx 17,ry 3,cx 8,ry 14,ry 12,ry 20,ry 22
sum,0.576955,0.572985,0.56643,0.562004,0.559207,0.557249,0.553698,0.552395,0.543062,0.535605,...,0.531331,0.52972,0.527078,0.526997,0.525182,0.521784,0.52163,0.521235,0.517832,0.513977

TARANTULA SCORES

,ry 23,cx 15,ry 11,ry 10,ry 9,cx 16,swap 13,cx 7,ry 1,ry 0,...,ry 2,cx 5,ry 19,cx 17,ry 3,cx 8,ry 14,ry 12,ry 20,ry 22
sum,0.576955,0.572985,0.56643,0.562004,0.559207,0.557249,0.553698,0.552395,0.543062,0.535605,...,0.531331,0.52972,0.527078,0.526997,0.525182,0.521784,0.52163,0.521235,0.517832,0.513977

DSTAR SCORES

,cx 18,cx 16,cx 15,ry 19,cx 17,ry 20,ry 22,ry 21,cx 7,ry 9,...,cx 5,cx 8,swap 13,ry 1,ry 4,ry 2,ry 3,ry 0,ry 10,ry 11
sum,15.959998,14.963952,14.19307,14.000996,13.899744,11.224686,7.04842,3.915335,3.290881,3.226926,...,0.970807,0.54734,0.311473,0.204122,0.121144,0.00215,0.00111,2.683610e-10,1.694168e-10,4.187617e-11

ERROR GATE LOCATION:
13
Now evolving the following mutant:  AddGate_rz_inGap_21_.qasm

100%|██████████| 10/10 [00:19<00:00,  2.00s/it]
100%|██████████| 10/10 [00:19<00:00,  1.95s/it]

,ry 23,ry 22,ry 21,rz 20,ry 19,ry 18,cx 17,cx 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.493786,0.999828,0.851908,0.310412,1.737807,1.688328,1.850063,1.719717,1.668982,2.031028,...,0.248980,0.625798,0.637200,0.518102,0.256010,0.014813,0.020854,0.231487,0.000007,fail
1,0.668462,1.690963,0.932024,0.290023,1.647317,2.388445,2.614076,2.443004,1.875520,1.581412,...,0.243483,0.664946,0.572002,0.511176,0.264548,0.016295,0.018550,0.231096,0.000008,fail
2,0.659745,1.173010,1.004101,0.358299,1.585914,2.358585,2.464545,1.626495,1.726345,1.506244,...,0.265635,0.464569,0.544920,0.465298,0.236161,0.013902,0.017022,0.153810,0.000007,fail
3,0.746599,1.727749,1.262777,0.398624,2.311028,2.166481,2.241919,2.036193,1.542809,1.608178,...,0.405759,0.638142,0.709420,0.501309,0.248644,0.019976,0.021091,0.233253,0.000007,fail
4,0.641335,1.311874,1.073185,0.350419,1.881511,2.113627,2.329165,2.376577,1.904606,1.848541,...,0.331816,0.669235,0.702347,0.571488,0.292291,0.018632,0.022586,0.269950,0.000008,fail
5,0.461100,1.292514,0.921349,0.311047,1.769314,2.354435,2.392265,1.567626,1.467216,1.427661,...,0.272406,0.519975,0.586838,0.485675,0.259548,0.014739,0.017290,0.160202,0.000007,fail
6,0.779719,1.428377,0.956002,0.319618,2.069625,2.414380,2.538571,2.072060,2.054223,1.993248,...,0.251238,0.648937,0.695571,0.593355,0.318304,0.017873,0.021521,0.227914,0.000008,fail
7,0.631141,1.212229,0.757663,0.286196,1.242444,2.771015,3.077874,2.565334,2.428978,2.114179,...,0.247360,0.677116,0.728018,0.603584,0.306599,0.018883,0.022566,0.249332,0.000009,fail
8,0.668037,1.354613,0.987231,0.343081,2.113651,2.684539,2.824842,2.208087,1.875856,1.541371,...,0.312814,0.618133,0.605593,0.534017,0.290884,0.017196,0.018678,0.202621,0.000008,fail
9,0.554351,1.335762,0.865874,0.270223,1.687052,2.120725,2.330729,2.188432,2.134286,1.949484,...,0.213811,0.669969,0.685283,0.553132,0.292500,0.015544,0.021729,0.244097,0.000007,fail
10,0.545992,1.118569,0.674237,0.226315,1.701785,1.638315,1.660668,1.333000,1.319171,1.431049,...,0.156638,0.388088,0.442895,0.294854,0.150667,0.013119,0.014916,0.142588,0.000004,pass
11,0.463550,0.825261,0.899366,0.306535,1.397992,1.417398,1.432447,0.952873,0.792544,0.881702,...,0.256213,0.369995,0.417470,0.359428,0.155359,0.011176,0.012301,0.121542,0.000004,pass
12,0.465793,0.898646,0.365163,0.142291,1.503073,1.312310,1.481933,1.744109,1.913435,2.000150,...,0.114766,0.516785,0.549533,0.383544,0.216961,0.012192,0.019501,0.205525,0.000005,pass
13,0.281478,0.616872,0.438612,0.157627,0.769416,1.043191,1.142962,1.217857,1.053636,0.870113,...,0.158555,0.338112,0.310568,0.278067,0.136672,0.009970,0.011422,0.120614,0.000004,pass
14,0.356373,1.017633,0.505389,0.177714,0.910082,1.747329,1.921904,1.487535,1.770871,1.911790,...,0.144301,0.523577,0.580504,0.451516,0.228455,0.012204,0.018746,0.191890,0.000007,pass
15,0.607038,1.072192,0.770381,0.275601,1.313793,1.756412,1.993791,2.173860,2.040387,1.963668,...,0.253803,0.629397,0.663631,0.503284,0.257478,0.017756,0.021334,0.240418,0.000007,pass
16,0.548953,1.367138,1.109402,0.386860,2.550653,2.562896,2.644512,1.780214,1.932734,2.071050,...,0.354912,0.682223,0.780797,0.636448,0.309468,0.018660,0.024685,0.237673,0.000008,pass
17,0.345513,1.544427,1.047205,0.372266,2.598221,1.988220,2.102966,1.962783,1.601602,1.856146,...,0.355715,0.737197,0.664134,0.529631,0.246236,0.015457,0.021512,0.243717,0.000007,pass
18,0.523929,1.175273,1.206036,0.422453,1.675373,1.966614,2.187014,1.966660,1.597698,1.761143,...,0.402115,0.687159,0.689672,0.595922,0.286570,0.017365,0.021035,0.253288,0.000008,pass
19,0.520094,1.166463,0.774903,0.278821,1.512117,1.745180,1.847522,1.828288,1.713611,1.444829,...,0.222017,0.491005,0.502759,0.437882,0.234800,0.015720,0.016837,0.174542,0.000006,pass

BARINEL SCORES

,ry 23,ry 18,cx 17,ry 9,cx 16,ry 22,ry 4,ry 21,ry 0,ry 10,...,ry 3,ry 12,cx 7,cx 8,cx 6,ry 1,ry 19,ry 2,cx 14,ry 13
sum,0.575051,0.573098,0.57252,0.57212,0.558473,0.555991,0.554411,0.552331,0.551454,0.546555,...,0.538902,0.538296,0.53604,0.535902,0.535845,0.532881,0.531096,0.525507,0.520858,0.511711

TARANTULA SCORES

,ry 23,ry 18,cx 17,ry 9,cx 16,ry 22,ry 4,ry 21,ry 0,ry 10,...,ry 3,ry 12,cx 7,cx 8,cx 6,ry 1,ry 19,ry 2,cx 14,ry 13
sum,0.575051,0.573098,0.57252,0.57212,0.558473,0.555991,0.554411,0.552331,0.551454,0.546555,...,0.538902,0.538296,0.53604,0.535902,0.535845,0.532881,0.531096,0.525507,0.520858,0.511711

DSTAR SCORES

,cx 17,ry 18,cx 16,cx 15,ry 19,cx 14,ry 22,ry 21,ry 12,ry 23,...,ry 13,rz 20,cx 8,ry 4,ry 1,ry 2,ry 3,ry 0,ry 10,ry 11
sum,21.407704,19.567004,16.36419,13.556985,12.557442,11.828485,8.795951,5.193318,2.788356,2.71128,...,1.396255,0.822522,0.628273,0.625716,0.407027,0.004003,0.002778,5.804922e-10,1.013636e-10,2.421766e-11

ERROR GATE LOCATION:
20
Now evolving the following mutant:  AddGate_swap_inGap_13_.qasm

100%|██████████| 10/10 [00:21<00:00,  2.11s/it]
100%|██████████| 10/10 [00:20<00:00,  2.10s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.602694,1.187105,0.613954,1.584897,1.483620,1.541069,1.426364,1.259214,1.036150,0.323569,...,0.169024,0.310997,0.241106,0.243608,0.139616,0.012302,0.009506,0.101832,0.000004,fail
1,0.779008,1.092448,1.026564,1.702599,2.100409,2.208087,1.749728,1.869097,1.662049,0.389021,...,0.270132,0.549992,0.471926,0.495493,0.236851,0.018883,0.018182,0.175160,0.000006,fail
2,0.754846,1.178056,0.701721,1.746397,1.885681,2.142649,2.336632,2.386898,2.429339,0.566741,...,0.244856,0.608570,0.519844,0.498353,0.282044,0.020876,0.019088,0.221701,0.000007,fail
3,0.723807,1.718425,0.855060,2.506577,1.988657,2.056151,2.018973,1.916394,1.690216,0.493620,...,0.182643,0.564129,0.532542,0.435743,0.207768,0.017421,0.020500,0.192646,0.000006,fail
4,0.510155,1.022317,0.612358,1.111398,1.712352,1.856019,1.471847,1.401820,1.549067,0.352278,...,0.190920,0.413640,0.353479,0.349983,0.169308,0.014785,0.012776,0.153061,0.000005,fail
5,0.633864,1.274696,0.698260,1.736219,2.082200,2.168296,1.924376,1.848976,1.482042,0.459752,...,0.176952,0.437161,0.374681,0.356238,0.193272,0.015425,0.014908,0.137831,0.000005,fail
6,0.714777,1.465361,0.906475,1.685689,1.931086,2.055217,1.987258,1.427317,1.440536,0.426084,...,0.289394,0.488729,0.434739,0.397064,0.176056,0.014841,0.017593,0.173647,0.000006,fail
7,0.513078,1.534532,1.007598,1.895408,1.773750,1.887692,1.893247,2.003763,2.034797,0.491362,...,0.224691,0.574515,0.570725,0.469296,0.223580,0.015055,0.021221,0.210213,0.000006,fail
8,0.745891,1.603665,1.011188,1.460762,2.581381,2.857312,2.441121,2.439448,2.141390,0.555062,...,0.229295,0.627930,0.597513,0.524102,0.242238,0.018944,0.023198,0.233605,0.000007,fail
9,0.670920,1.333323,0.952515,1.966230,2.823976,2.960406,2.102604,2.147468,2.125657,0.494560,...,0.276668,0.598413,0.584217,0.547235,0.262056,0.020838,0.022436,0.216002,0.000007,fail
10,0.482457,1.268079,0.882113,2.505862,1.780153,1.853601,1.933455,1.906340,1.994772,0.468635,...,0.211483,0.557821,0.499466,0.422014,0.205192,0.014047,0.018673,0.186852,0.000005,pass
11,0.524679,1.376770,0.709935,1.839077,2.138527,2.303454,2.063595,1.493347,1.316153,0.390127,...,0.234919,0.480609,0.463550,0.395560,0.177231,0.014516,0.017866,0.187645,0.000005,pass
12,0.637313,1.555687,0.805875,1.476691,2.040984,2.258782,2.030030,1.464123,1.536079,0.438307,...,0.230988,0.471151,0.435747,0.402555,0.181523,0.017037,0.017204,0.204602,0.000006,pass
13,0.313968,0.780629,0.471520,1.307424,1.157842,1.268853,1.295443,1.357488,1.618130,0.414478,...,0.089384,0.350332,0.348698,0.267779,0.130123,0.009290,0.011974,0.146715,0.000004,pass
14,0.459532,0.758494,1.042795,1.597245,1.359023,1.496427,1.682115,1.627017,1.761573,0.406448,...,0.311051,0.505432,0.438848,0.477097,0.235560,0.015529,0.017051,0.190982,0.000005,pass
15,0.464317,0.812789,0.667306,1.410589,1.795396,1.865054,1.439315,1.701553,1.551105,0.320888,...,0.184774,0.422784,0.373577,0.366124,0.188916,0.014232,0.012673,0.128549,0.000005,pass
16,0.501082,1.249299,0.810777,1.707829,1.849490,1.990485,1.837395,1.408074,1.121806,0.459044,...,0.229746,0.443130,0.380823,0.360217,0.188140,0.014059,0.015383,0.150600,0.000004,pass
17,0.350999,1.456544,1.177362,1.665726,1.983913,2.228357,1.995811,1.713534,1.900230,0.549598,...,0.318310,0.597590,0.594128,0.509988,0.214975,0.014613,0.020229,0.233003,0.000007,pass
18,0.491270,1.338937,0.564052,1.547784,1.565011,1.665656,1.849430,1.305975,0.913821,0.327303,...,0.171766,0.360124,0.306924,0.276420,0.109173,0.011557,0.012933,0.131335,0.000004,pass
19,0.686733,1.492174,0.922664,2.040918,2.353582,2.343474,1.547540,1.348863,1.223656,0.429708,...,0.211928,0.429679,0.369475,0.344355,0.148481,0.015307,0.015907,0.125057,0.000005,pass

BARINEL SCORES

,ry 23,ry 11,swap 12,ry 10,ry 9,cx 16,ry 3,ry 13,ry 4,cx 15,...,ry 2,cx 7,cx 6,ry 22,cx 17,ry 14,ry 1,ry 21,cx 8,ry 20
sum,0.575107,0.564101,0.561824,0.551542,0.549897,0.54958,0.547135,0.54704,0.545177,0.540794,...,0.528758,0.528359,0.526402,0.525893,0.52266,0.519843,0.518617,0.510076,0.506769,0.504305

TARANTULA SCORES

,ry 23,ry 11,swap 12,ry 10,ry 9,cx 16,ry 3,ry 13,ry 4,cx 15,...,ry 2,cx 7,cx 6,ry 22,cx 17,ry 14,ry 1,ry 21,cx 8,ry 20
sum,0.575107,0.564101,0.561824,0.551542,0.549897,0.54958,0.547135,0.54704,0.545177,0.540794,...,0.528758,0.528359,0.526402,0.525893,0.52266,0.519843,0.518617,0.510076,0.506769,0.504305

DSTAR SCORES

,cx 18,ry 19,cx 16,cx 17,cx 15,ry 20,ry 22,ry 21,ry 23,ry 13,...,cx 5,cx 8,ry 4,swap 12,ry 1,ry 2,ry 3,ry 0,ry 10,ry 11
sum,16.134338,14.796514,13.80796,13.532701,12.409181,11.167397,8.140833,3.894886,2.964639,2.70137,...,1.348382,0.416842,0.386168,0.314608,0.282128,0.003168,0.002829,3.546271e-10,7.964155e-11,1.879822e-11

ERROR GATE LOCATION:
12
Now evolving the following mutant:  AddGate_y_inGap_8_.qasm

100%|██████████| 10/10 [00:22<00:00,  2.21s/it]
100%|██████████| 10/10 [00:18<00:00,  1.87s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,y 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.549365,1.054789,0.995050,1.220618,2.165016,2.320062,1.546891,1.407352,1.531028,0.381722,...,0.484643,0.139136,0.562196,0.492080,0.219251,0.016658,0.018357,0.187063,0.000007,fail
1,0.640190,1.652845,1.053033,1.865987,1.955685,2.141051,2.211322,1.898611,1.666118,0.508647,...,0.649842,0.120488,0.613138,0.500599,0.254700,0.017117,0.018901,0.212610,0.000007,fail
2,0.429974,0.941891,0.877547,1.265182,2.317459,2.620783,2.097861,1.969667,2.025042,0.506294,...,0.727760,0.138939,0.726004,0.570927,0.255545,0.016743,0.022104,0.246655,0.000009,fail
3,0.715093,1.796172,1.280917,2.443461,2.847583,3.026382,2.537969,2.032204,1.811021,0.480017,...,0.755791,0.159471,0.761109,0.583451,0.259716,0.023773,0.023639,0.270521,0.000009,fail
4,0.525772,1.146383,1.203503,1.943375,2.176238,2.480312,2.522745,2.266639,2.203029,0.569433,...,0.824374,0.170442,0.808699,0.710866,0.334682,0.020362,0.025282,0.302646,0.000010,fail
5,0.440829,1.042247,0.665868,1.541454,2.353800,2.597457,2.314773,2.478675,2.318859,0.579360,...,0.751778,0.116375,0.780680,0.594324,0.263476,0.020125,0.024737,0.261176,0.000008,fail
6,0.380352,1.597196,0.832018,1.118995,1.953786,2.208000,2.300007,1.597251,1.093007,0.428797,...,0.606986,0.127073,0.469299,0.465515,0.234795,0.016583,0.014513,0.194785,0.000007,fail
7,0.616011,1.509529,0.879664,1.710348,1.900079,2.093377,2.165539,1.883202,1.410694,0.457788,...,0.579871,0.111436,0.516437,0.433651,0.218542,0.018526,0.016329,0.195802,0.000006,fail
8,0.502400,1.366344,0.899274,1.940324,2.335149,2.428421,1.873645,1.654081,1.244520,0.419079,...,0.529327,0.118629,0.527258,0.451122,0.199159,0.016469,0.016478,0.162260,0.000007,fail
9,0.603811,1.111650,0.761907,1.329607,1.605770,1.707437,1.279573,1.183588,1.385002,0.363168,...,0.437150,0.101768,0.471057,0.392308,0.187253,0.014430,0.017320,0.158459,0.000005,fail
10,0.408190,0.866334,0.494710,1.032449,1.300710,1.479139,1.544866,1.747898,1.385985,0.352127,...,0.490922,0.049997,0.490694,0.335370,0.151250,0.010532,0.014664,0.156391,0.000005,pass
11,0.447604,0.676606,0.752114,1.598196,2.100397,2.330705,1.842247,1.708469,1.886250,0.482987,...,0.667580,0.124622,0.669236,0.567658,0.250998,0.015791,0.022143,0.247876,0.000008,pass
12,0.516261,1.287575,0.810506,2.119591,2.147260,2.115634,1.396424,1.491828,1.386913,0.365339,...,0.498435,0.105274,0.531815,0.427219,0.202071,0.012960,0.015874,0.136259,0.000006,pass
13,0.449422,0.728824,0.385557,1.028092,1.390367,1.513167,1.298304,1.235257,1.234201,0.284014,...,0.359079,0.065354,0.378573,0.309168,0.166929,0.011905,0.012111,0.141763,0.000005,pass
14,0.522090,0.731744,0.691088,1.314175,1.563164,1.775028,1.932229,1.889961,1.700227,0.339008,...,0.549611,0.090692,0.578364,0.397879,0.168136,0.015563,0.019851,0.203750,0.000006,pass
15,0.493791,0.653404,0.839127,1.463480,1.426282,1.516598,1.533052,1.712009,1.897548,0.364258,...,0.539606,0.112728,0.641103,0.481824,0.237876,0.015122,0.020345,0.203421,0.000006,pass
16,0.555616,1.331634,0.536420,2.656110,1.856921,1.982454,2.246920,2.183068,2.454684,0.663787,...,0.672292,0.079155,0.665567,0.530306,0.287666,0.016393,0.025118,0.268048,0.000007,pass
17,0.748232,1.193093,0.962075,1.548348,1.350275,1.560968,1.938862,1.564163,1.787775,0.448839,...,0.617565,0.123397,0.640662,0.515787,0.256031,0.017413,0.021411,0.254388,0.000006,pass
18,0.514089,1.067256,0.771418,1.388316,1.894237,2.161533,2.439617,2.180664,1.979958,0.540869,...,0.661256,0.105959,0.664893,0.514895,0.247291,0.017459,0.020763,0.252517,0.000008,pass
19,0.623198,1.126944,0.898376,2.213494,2.158773,2.252375,1.808265,2.151413,1.988814,0.496401,...,0.600130,0.098765,0.673815,0.504169,0.244408,0.015681,0.020890,0.204125,0.000008,pass

BARINEL SCORES

,cx 9,ry 22,y 7,ry 21,cx 18,ry 19,ry 3,cx 17,cx 5,ry 0,...,ry 1,cx 6,ry 11,cx 16,ry 23,ry 2,ry 20,ry 12,ry 13,cx 15
sum,0.592905,0.577693,0.576961,0.569541,0.558326,0.556988,0.548491,0.536949,0.531218,0.530573,...,0.514487,0.512372,0.507374,0.506989,0.505865,0.505744,0.500261,0.500091,0.495932,0.485257

TARANTULA SCORES

,cx 9,ry 22,y 7,ry 21,cx 18,ry 19,ry 3,cx 17,cx 5,ry 0,...,ry 1,cx 6,ry 11,cx 16,ry 23,ry 2,ry 20,ry 12,ry 13,cx 15
sum,0.592905,0.577693,0.576961,0.569541,0.558326,0.556988,0.548491,0.536949,0.531218,0.530573,...,0.514487,0.512372,0.507374,0.506989,0.505865,0.505744,0.500261,0.500091,0.495932,0.485257

DSTAR SCORES

,cx 18,ry 19,cx 17,cx 16,ry 20,cx 15,ry 22,ry 21,cx 8,cx 6,...,ry 14,cx 9,ry 4,ry 1,y 7,ry 2,ry 3,ry 0,ry 11,ry 12
sum,19.452985,17.177058,15.53695,12.112215,10.176793,10.0533,8.886718,5.208412,2.573441,2.440341,...,1.53697,0.764361,0.482361,0.398123,0.155148,0.003833,0.00322,5.454810e-10,9.541431e-11,2.179475e-11

ERROR GATE LOCATION:
7
Now evolving the following mutant:  AddGate_h_inGap_5_.qasm

100%|██████████| 10/10 [00:22<00:00,  2.23s/it]
100%|██████████| 10/10 [00:22<00:00,  2.21s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,ry 5,h 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.482364,1.136370,0.419241,1.908341,2.171869,2.260252,1.658906,1.797755,1.881281,0.573497,...,0.511132,0.508917,0.437209,0.246642,0.221101,0.012418,0.017369,0.191045,0.000006,fail
1,0.587886,1.014087,1.108177,2.291520,2.356062,2.532121,2.358813,2.211679,2.301176,0.616060,...,0.820103,0.883259,0.728601,0.352598,0.364840,0.019536,0.027465,0.312772,0.000008,fail
2,0.471246,1.346086,0.827702,2.427241,2.550639,2.646647,2.047375,1.873633,1.816669,0.555335,...,0.682601,0.718513,0.591270,0.308027,0.299522,0.020038,0.021174,0.250305,0.000007,fail
3,0.692547,0.991411,0.907433,1.974860,2.270981,2.530448,2.402593,2.159106,1.762789,0.538490,...,0.698880,0.722062,0.607258,0.303503,0.306153,0.018118,0.021687,0.253425,0.000008,fail
4,0.346015,1.054864,0.757557,1.290513,1.475253,1.814763,2.386274,2.210535,2.108855,0.532249,...,0.764858,0.696472,0.605172,0.319570,0.316112,0.015142,0.022006,0.288541,0.000007,fail
5,0.536294,1.190806,0.943990,1.890062,2.099161,2.279788,1.993681,1.795977,1.648850,0.480829,...,0.664254,0.685951,0.575483,0.269120,0.280135,0.018820,0.021616,0.231726,0.000007,fail
6,0.687054,1.391053,0.842952,2.137643,2.617540,2.698345,1.935087,1.665390,1.283145,0.406528,...,0.536251,0.583216,0.452562,0.230285,0.233963,0.018292,0.017457,0.187601,0.000007,fail
7,0.637744,1.087271,0.778827,1.863907,2.221374,2.466994,2.493314,2.342346,2.033247,0.470196,...,0.695702,0.709038,0.563044,0.276758,0.289786,0.018852,0.021977,0.261813,0.000008,fail
8,0.540692,1.067095,0.815791,2.363884,2.151190,2.289045,2.177669,2.144955,2.011483,0.514820,...,0.756268,0.741573,0.612606,0.303437,0.308342,0.017409,0.022762,0.258444,0.000008,fail
9,0.538801,0.979174,0.804259,1.466506,2.247316,2.542010,2.450202,2.437519,2.463937,0.614352,...,0.795320,0.836899,0.629441,0.308699,0.311283,0.020318,0.026369,0.301534,0.000009,fail
10,0.351999,0.676889,0.931051,1.088155,1.187339,1.513366,2.143752,2.163507,2.561134,0.539321,...,0.750168,0.878538,0.674382,0.324353,0.328480,0.018380,0.027049,0.334787,0.000008,pass
11,0.457600,1.006507,0.748133,1.826801,1.669179,1.795497,1.673166,1.709005,1.426031,0.431792,...,0.561550,0.545348,0.443346,0.204279,0.206312,0.013451,0.017272,0.181267,0.000005,pass
12,0.584617,0.948848,0.755896,1.936813,2.074024,2.186848,1.751116,1.514976,1.468016,0.306454,...,0.568698,0.580690,0.420287,0.191808,0.213042,0.017122,0.017219,0.209419,0.000006,pass
13,0.550474,1.178410,1.072847,1.265392,2.145621,2.303901,1.586689,1.159720,1.062928,0.321174,...,0.499373,0.527050,0.453210,0.216093,0.236134,0.013641,0.016165,0.169349,0.000006,pass
14,0.476570,0.991665,0.615431,1.690112,2.258697,2.356506,1.627436,1.535799,1.160555,0.417428,...,0.467870,0.452949,0.385221,0.176303,0.175837,0.013107,0.013960,0.143614,0.000006,pass
15,0.452478,0.997847,0.841893,1.447334,1.812368,1.886529,1.504878,1.477786,1.392359,0.374656,...,0.477604,0.483925,0.404423,0.193586,0.205234,0.013468,0.015069,0.147413,0.000006,pass
16,0.366851,0.624570,0.521204,1.102588,0.678257,0.672070,0.755559,0.772120,0.717590,0.144859,...,0.217530,0.249001,0.218828,0.112311,0.121597,0.007954,0.007587,0.078115,0.000002,pass
17,0.550675,1.644343,1.169244,2.144333,1.923800,1.994895,1.866529,1.625140,1.352472,0.418814,...,0.647789,0.610223,0.571985,0.255469,0.268660,0.017191,0.018715,0.190125,0.000006,pass
18,0.440018,0.771220,0.903485,1.249910,1.713175,1.893508,1.833720,1.762072,1.754782,0.422422,...,0.573568,0.660707,0.558075,0.265730,0.271447,0.016213,0.021669,0.235068,0.000007,pass
19,0.485464,1.026779,0.507959,1.175224,1.936227,2.175884,2.093695,2.145598,1.944782,0.472950,...,0.578253,0.586922,0.420557,0.204190,0.203003,0.015309,0.018546,0.213784,0.000007,pass

BARINEL SCORES

,ry 14,ry 5,ry 11,ry 1,h 4,ry 20,ry 12,ry 10,cx 15,cx 17,...,cx 6,ry 19,cx 7,ry 2,ry 13,ry 3,ry 23,ry 22,cx 9,ry 21
sum,0.579352,0.576492,0.574543,0.571424,0.567961,0.567858,0.567257,0.566815,0.565454,0.565402,...,0.560482,0.560196,0.559652,0.559307,0.556881,0.550968,0.539263,0.532926,0.527142,0.504264

TARANTULA SCORES

,ry 14,ry 5,ry 11,ry 1,h 4,ry 20,ry 12,ry 10,cx 15,cx 17,...,cx 6,ry 19,cx 7,ry 2,ry 13,ry 3,ry 23,ry 22,cx 9,ry 21
sum,0.579352,0.576492,0.574543,0.571424,0.567961,0.567858,0.567257,0.566815,0.565454,0.565402,...,0.560482,0.560196,0.559652,0.559307,0.556881,0.550968,0.539263,0.532926,0.527142,0.504264

DSTAR SCORES

,cx 18,ry 19,cx 17,cx 16,ry 20,cx 15,ry 22,ry 21,cx 7,cx 8,...,ry 14,h 4,ry 5,cx 9,ry 1,ry 2,ry 3,ry 0,ry 11,ry 12
sum,20.115478,17.925201,17.877917,16.468279,15.434387,15.01295,6.379774,3.727057,3.223682,3.126025,...,2.029982,0.702562,0.701446,0.660627,0.540826,0.004752,0.003156,5.819680e-10,1.234963e-10,2.882601e-11

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_y_inGap_27_.qasm

100%|██████████| 10/10 [00:18<00:00,  1.85s/it]
100%|██████████| 10/10 [00:19<00:00,  1.91s/it]

,ry 23,y 22,ry 21,ry 20,ry 19,ry 18,cx 17,cx 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.584182,0.455360,1.339663,0.668607,1.648986,1.997445,2.206896,2.105621,1.631796,1.573501,...,0.340762,0.633506,0.558052,0.507125,0.257834,0.017349,0.018916,0.225236,0.000007,fail
1,0.652475,0.326251,1.058880,0.715711,1.564659,1.959657,2.068798,1.520469,1.690827,1.668980,...,0.256085,0.565309,0.646799,0.484448,0.205049,0.015698,0.020026,0.181899,0.000006,fail
2,0.578437,0.381089,1.252092,0.665226,1.330692,1.634508,1.765411,1.714841,1.717060,1.549178,...,0.180372,0.464665,0.449346,0.363705,0.183677,0.013714,0.014805,0.145709,0.000005,fail
3,0.652558,0.440905,1.402037,0.592727,1.940175,1.834369,1.953617,2.022303,1.671928,1.478524,...,0.271796,0.613328,0.591378,0.416192,0.203083,0.016225,0.020538,0.197380,0.000005,fail
4,0.472155,0.521484,1.567954,0.877488,1.916344,1.725148,1.846134,1.919671,1.260956,1.373387,...,0.330341,0.602491,0.499995,0.480061,0.244463,0.015363,0.017208,0.211108,0.000006,fail
5,0.399875,0.382267,1.238110,0.571464,1.393416,1.886498,2.010912,1.516688,1.357505,1.142534,...,0.231772,0.465560,0.420995,0.359803,0.167587,0.013475,0.012800,0.136272,0.000006,fail
6,0.618402,0.436090,1.469792,0.583867,1.597177,1.855220,2.124793,2.534578,2.199543,1.869019,...,0.159784,0.732310,0.643242,0.501919,0.292710,0.015215,0.020820,0.256938,0.000007,fail
7,0.441346,0.385355,1.145946,0.350581,1.638858,1.504871,1.557079,1.356013,1.213294,1.108923,...,0.120685,0.386137,0.343503,0.266587,0.159948,0.009329,0.013187,0.122212,0.000003,fail
8,0.490671,0.446137,1.236362,0.665225,2.101022,1.728720,1.756320,1.774844,1.601950,1.501916,...,0.182585,0.548777,0.463815,0.372997,0.209979,0.012218,0.018058,0.172567,0.000004,fail
9,0.609282,0.410988,1.314843,0.874251,2.476094,1.776700,1.834550,1.851741,1.958357,1.819568,...,0.223722,0.634745,0.614561,0.521430,0.255323,0.014320,0.018795,0.190975,0.000006,fail
10,0.469470,0.223244,0.616001,0.482660,1.212533,1.598530,1.800925,1.844125,1.579472,1.532150,...,0.216228,0.498991,0.492764,0.396843,0.180574,0.016268,0.017565,0.204947,0.000006,pass
11,0.457967,0.282334,0.902966,0.575613,1.578664,0.871651,0.988404,1.458654,1.352722,1.508782,...,0.176183,0.484203,0.456616,0.382602,0.207215,0.009625,0.015325,0.174762,0.000005,pass
12,0.427105,0.194762,0.627087,0.365458,1.207880,1.527567,1.548754,1.191301,1.443350,1.130858,...,0.072896,0.304520,0.349905,0.268966,0.145541,0.010792,0.012361,0.103953,0.000004,pass
13,0.476560,0.436498,1.373067,0.762137,1.618633,2.238709,2.405460,2.007338,1.754206,1.770910,...,0.307867,0.637067,0.631419,0.498524,0.245782,0.016370,0.019926,0.218658,0.000008,pass
14,0.639366,0.376135,1.225858,0.618649,2.018286,2.115670,2.182337,1.694973,1.355001,1.108753,...,0.227011,0.434504,0.434714,0.423650,0.233183,0.016088,0.014535,0.159989,0.000006,pass
15,0.319330,0.234547,0.718681,0.769165,1.157737,1.347142,1.481330,1.327601,1.152385,1.097820,...,0.326192,0.478012,0.481208,0.420926,0.181137,0.012402,0.015113,0.158938,0.000005,pass
16,0.590167,0.473196,1.510592,0.871521,1.684501,2.359413,2.344536,1.353411,1.368758,1.363973,...,0.242734,0.465947,0.508896,0.395683,0.197172,0.015018,0.015036,0.144242,0.000007,pass
17,0.398626,0.260292,0.799454,0.795351,0.908382,1.164860,1.269572,1.336903,1.116785,0.861957,...,0.233295,0.351931,0.337708,0.288399,0.128217,0.011097,0.010409,0.108995,0.000004,pass
18,0.442644,0.235473,0.680667,0.763563,1.002085,1.867965,2.104274,1.982283,1.934825,2.025859,...,0.333876,0.613513,0.726152,0.621512,0.322613,0.016698,0.023807,0.256536,0.000007,pass
19,0.562881,0.333100,1.018619,0.702351,1.624090,1.842552,1.921726,1.904857,1.775098,1.323968,...,0.173318,0.517864,0.433551,0.398778,0.226342,0.012728,0.014701,0.152763,0.000006,pass

BARINEL SCORES

,ry 21,y 22,ry 19,cx 7,ry 23,cx 16,ry 10,ry 2,ry 12,cx 15,...,ry 11,ry 18,ry 4,cx 5,ry 9,ry 3,cx 8,ry 13,ry 0,ry 20
sum,0.578953,0.578526,0.556841,0.541227,0.534777,0.532182,0.531655,0.52452,0.524036,0.523616,...,0.514486,0.513909,0.51317,0.510656,0.510487,0.510397,0.498731,0.497494,0.49485,0.494676

TARANTULA SCORES

,ry 21,y 22,ry 19,cx 7,ry 23,cx 16,ry 10,ry 2,ry 12,cx 15,...,ry 11,ry 18,ry 4,cx 5,ry 9,ry 3,cx 8,ry 13,ry 0,ry 20
sum,0.578953,0.578526,0.556841,0.541227,0.534777,0.532182,0.531655,0.52452,0.524036,0.523616,...,0.514486,0.513909,0.51317,0.510656,0.510487,0.510397,0.498731,0.497494,0.49485,0.494676

DSTAR SCORES

,cx 17,ry 19,cx 16,ry 18,cx 15,cx 14,ry 21,ry 20,cx 7,ry 23,...,cx 5,ry 13,cx 8,ry 4,ry 1,ry 2,ry 3,ry 0,ry 10,ry 11
sum,13.040351,12.910674,12.853848,11.900259,10.703466,9.592114,8.713004,2.579909,2.156464,2.045654,...,1.296079,1.052961,0.428963,0.393684,0.289862,0.00302,0.002015,3.171204e-10,7.908865e-11,1.668278e-11

ERROR GATE LOCATION:
22
Now evolving the following mutant:  AddGate_y_inGap_3_.qasm

100%|██████████| 10/10 [00:23<00:00,  2.38s/it]
100%|██████████| 10/10 [00:22<00:00,  2.23s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,ry 5,ry 4,ry 3,y 2,ry 1,ry 0,pass/fail
0,0.625061,1.051149,0.851987,1.242750,2.247026,2.523010,2.333319,1.786449,1.613463,0.417823,...,0.611737,0.587637,0.486977,0.223637,0.019723,0.018977,0.081632,0.228151,0.000008,fail
1,0.561948,1.476310,0.766030,1.697567,2.200923,2.407656,2.223059,2.208262,2.000064,0.496472,...,0.675506,0.732335,0.585038,0.302422,0.018275,0.022966,0.094395,0.247406,0.000008,fail
2,0.618215,1.493275,1.115617,2.055224,2.037875,2.172707,2.205998,2.114719,2.190482,0.558032,...,0.789255,0.776170,0.626967,0.311889,0.021305,0.024727,0.103224,0.272213,0.000008,fail
3,0.633243,1.193023,0.688327,1.851554,1.786811,1.959145,2.082207,2.009458,1.928592,0.520957,...,0.643456,0.671209,0.528632,0.260486,0.016965,0.023056,0.093717,0.230355,0.000006,fail
4,0.568326,1.288812,0.660944,1.528281,1.893992,2.085255,2.030912,1.978852,1.565875,0.418855,...,0.511358,0.529380,0.454130,0.230339,0.016059,0.016445,0.072080,0.182342,0.000006,fail
5,0.580600,1.341753,0.887950,1.728668,2.543764,2.757166,2.333236,2.495753,2.171851,0.591713,...,0.690702,0.763125,0.587649,0.294045,0.019406,0.024006,0.098410,0.241074,0.000009,fail
6,0.618310,1.349824,0.777258,1.870015,1.966816,2.106620,2.085856,1.926343,1.673141,0.436497,...,0.591097,0.623186,0.495023,0.255344,0.018283,0.019706,0.083360,0.208640,0.000007,fail
7,0.527388,1.245870,0.609854,1.325220,1.746493,1.989587,1.990944,1.877717,1.990318,0.438615,...,0.595967,0.583372,0.439995,0.226031,0.014317,0.018425,0.075258,0.218839,0.000007,fail
8,0.564395,1.255175,0.874121,1.726517,2.310598,2.623900,2.535115,2.032321,2.018975,0.554054,...,0.743756,0.668350,0.609789,0.301417,0.018396,0.022278,0.091924,0.276531,0.000009,fail
9,0.739268,1.074712,0.891704,1.753239,2.233842,2.439294,2.222190,2.370269,2.348072,0.539469,...,0.729945,0.804325,0.595192,0.265865,0.021050,0.025625,0.107887,0.253654,0.000009,fail
10,0.439425,1.187653,0.878366,1.235743,1.497737,1.640400,1.428078,1.389213,1.607367,0.457938,...,0.550493,0.553446,0.436171,0.206888,0.011852,0.018807,0.074757,0.185652,0.000006,pass
11,0.458264,0.562106,0.853596,1.066849,2.116170,2.475841,2.235504,2.008057,2.356618,0.556398,...,0.736536,0.793341,0.629821,0.301053,0.018536,0.025987,0.104883,0.312831,0.000009,pass
12,0.441216,1.043447,1.053116,1.576116,2.002700,2.014396,1.208958,1.252303,1.195918,0.357772,...,0.479950,0.494273,0.421173,0.165286,0.013688,0.015246,0.067556,0.130823,0.000006,pass
13,0.500194,1.373691,0.928526,1.458109,1.849350,1.885612,1.259559,1.151428,1.160243,0.294893,...,0.431673,0.495095,0.409099,0.186459,0.012723,0.014666,0.066029,0.132238,0.000006,pass
14,0.451511,0.974486,0.630810,1.005796,1.406264,1.657220,1.950262,1.591015,1.373414,0.398683,...,0.536279,0.465186,0.425790,0.218994,0.013421,0.015507,0.064861,0.195111,0.000006,pass
15,0.465044,0.760079,0.629083,1.416783,1.942952,2.045366,1.651003,1.525702,1.374805,0.425601,...,0.480834,0.477991,0.453453,0.216534,0.015863,0.016954,0.074255,0.173547,0.000006,pass
16,0.491679,0.955249,0.660957,1.879217,2.009126,2.039491,1.444424,1.324804,1.276814,0.417252,...,0.435331,0.472006,0.364186,0.182011,0.014106,0.014444,0.060436,0.152259,0.000005,pass
17,0.632892,1.082239,0.657762,1.372697,2.502397,2.698057,2.129955,2.153702,2.406771,0.570070,...,0.609832,0.646137,0.488077,0.255408,0.017523,0.021297,0.086886,0.234412,0.000009,pass
18,0.551389,0.945807,0.902049,2.111753,2.046908,2.037302,1.696733,1.791342,1.531416,0.514374,...,0.531143,0.576281,0.519080,0.257795,0.017069,0.018762,0.079947,0.168807,0.000006,pass
19,0.607186,1.139350,1.017096,2.018476,1.623329,1.669873,1.667029,1.444891,1.335047,0.295261,...,0.550117,0.575822,0.433671,0.198160,0.016506,0.018759,0.080883,0.187760,0.000006,pass

BARINEL SCORES

,ry 11,cx 16,cx 17,ry 10,ry 12,ry 22,ry 1,cx 15,ry 13,cx 8,...,ry 3,ry 23,y 2,cx 6,ry 14,cx 18,ry 20,ry 19,cx 9,ry 21
sum,0.578959,0.570921,0.569371,0.568099,0.562822,0.560231,0.557383,0.555275,0.554499,0.552017,...,0.545105,0.545052,0.542527,0.541485,0.536943,0.533552,0.52565,0.524662,0.51829,0.49732

TARANTULA SCORES

,ry 11,cx 16,cx 17,ry 10,ry 12,ry 22,ry 1,cx 15,ry 13,cx 8,...,ry 3,ry 23,y 2,cx 6,ry 14,cx 18,ry 20,ry 19,cx 9,ry 21
sum,0.578959,0.570921,0.569371,0.568099,0.562822,0.560231,0.557383,0.555275,0.554499,0.552017,...,0.545105,0.545052,0.542527,0.541485,0.536943,0.533552,0.52565,0.524662,0.51829,0.49732

DSTAR SCORES

,cx 17,cx 18,cx 16,ry 19,cx 15,ry 20,ry 22,ry 21,ry 13,cx 7,...,ry 14,cx 9,ry 5,ry 1,y 2,ry 3,ry 4,ry 0,ry 11,ry 12
sum,18.217444,17.635975,16.87883,15.162391,14.844107,11.198042,8.143706,3.623891,3.13891,2.920678,...,1.730487,0.651382,0.585529,0.468765,0.075591,0.004592,0.003327,6.061327e-10,1.250249e-10,2.782386e-11

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_x_inGap_11_.qasm

100%|██████████| 10/10 [00:23<00:00,  2.30s/it]
100%|██████████| 10/10 [00:20<00:00,  2.04s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.586860,1.052266,0.853651,1.911097,1.729119,1.849045,1.866658,1.672098,1.556229,0.500002,...,0.307747,0.613388,0.608085,0.489480,0.221145,0.018430,0.019734,0.214717,0.000007,fail
1,0.593832,1.249700,0.955494,1.776246,1.678368,1.851108,1.839194,1.948793,2.135761,0.458363,...,0.304338,0.648705,0.753314,0.519072,0.228473,0.018035,0.023702,0.249454,0.000007,fail
2,0.549992,0.992813,0.952431,1.638266,2.235456,2.555934,2.571498,2.266836,2.235977,0.586033,...,0.330478,0.775815,0.796835,0.669504,0.318053,0.021452,0.025545,0.306208,0.000009,fail
3,0.395402,1.342172,0.821715,1.600745,1.822489,1.993263,1.968470,1.550740,1.365733,0.478540,...,0.289578,0.588238,0.547368,0.453663,0.215127,0.015069,0.017617,0.194726,0.000006,fail
4,0.485287,1.012258,0.819941,1.639627,1.807398,2.003047,1.973502,1.652463,1.511326,0.391934,...,0.329813,0.637474,0.645722,0.500894,0.229632,0.015709,0.021749,0.224826,0.000006,fail
5,0.459489,1.139133,1.091315,1.706764,1.578633,1.680032,1.724003,1.459274,1.689691,0.418774,...,0.377410,0.602423,0.642032,0.584048,0.277076,0.016924,0.021046,0.230823,0.000006,fail
6,0.498546,0.988231,0.982486,1.457849,2.033553,2.271295,2.041423,1.789772,2.213161,0.543717,...,0.402512,0.696609,0.746062,0.629295,0.301772,0.019047,0.024837,0.281559,0.000009,fail
7,0.567531,1.519609,1.287843,2.334134,2.699730,2.863356,2.316774,2.008834,2.113184,0.613735,...,0.425044,0.845806,0.836747,0.702238,0.330182,0.020475,0.024647,0.288230,0.000010,fail
8,0.535541,1.203018,0.938169,1.883400,2.276213,2.361489,1.760828,1.619949,1.084213,0.366667,...,0.282489,0.543748,0.487093,0.410552,0.172104,0.016051,0.015052,0.143354,0.000006,fail
9,0.443278,1.210227,0.959818,1.768967,2.269340,2.398156,1.885730,1.432545,1.428176,0.442408,...,0.397668,0.622308,0.600183,0.521363,0.239912,0.018384,0.018689,0.209024,0.000007,fail
10,0.432757,1.356902,0.944024,2.315211,2.269048,2.235780,1.517243,1.739854,1.821937,0.388639,...,0.257600,0.577676,0.701882,0.525175,0.277556,0.015723,0.021525,0.199576,0.000006,pass
11,0.419881,0.833061,0.675504,1.188683,1.554026,1.621289,1.215140,1.233228,1.279662,0.220549,...,0.201298,0.379751,0.452821,0.351678,0.180152,0.011287,0.014358,0.140635,0.000005,pass
12,0.391200,1.080451,0.668856,1.721535,1.592701,1.600502,1.066783,1.013337,1.039285,0.335963,...,0.256111,0.385045,0.446469,0.373609,0.186781,0.011472,0.013726,0.126773,0.000004,pass
13,0.567011,1.114213,0.862672,1.400682,1.641136,1.813032,1.849012,1.494152,1.554875,0.351999,...,0.256044,0.533863,0.555117,0.441059,0.217482,0.016360,0.018192,0.213774,0.000006,pass
14,0.445332,1.045351,0.795835,1.491403,2.111491,2.243852,1.719140,1.632576,1.361095,0.342293,...,0.196100,0.507573,0.503097,0.422910,0.206199,0.014120,0.014775,0.167434,0.000007,pass
15,0.488812,1.465014,0.742183,1.516113,1.578003,1.629979,1.414348,1.279841,1.234631,0.414707,...,0.142611,0.406233,0.428460,0.356885,0.197652,0.012572,0.014675,0.149369,0.000004,pass
16,0.339832,0.761717,0.409538,1.363798,1.129045,1.164956,1.172806,1.064786,0.821047,0.291150,...,0.106205,0.309647,0.273253,0.259374,0.139285,0.009672,0.010006,0.102365,0.000003,pass
17,0.326401,0.867470,0.404009,0.819931,0.996626,1.148959,1.377472,0.944897,0.858281,0.229219,...,0.157899,0.394024,0.309453,0.276436,0.141874,0.009417,0.010827,0.141113,0.000003,pass
18,0.554751,1.273596,0.871663,1.698889,2.198574,2.387526,2.454967,2.141115,1.690201,0.510965,...,0.212631,0.677772,0.621996,0.527808,0.263926,0.017893,0.020408,0.237789,0.000007,pass
19,0.538952,0.922083,0.929752,2.002446,1.687830,1.688573,1.466935,1.506704,1.398998,0.423827,...,0.310791,0.516340,0.593576,0.503627,0.225623,0.015775,0.019779,0.173628,0.000005,pass

BARINEL SCORES

,cx 8,x 10,ry 0,ry 1,cx 7,ry 14,ry 9,cx 6,cx 5,ry 2,...,ry 13,ry 11,cx 18,ry 4,cx 16,ry 12,ry 19,ry 20,ry 23,ry 22
sum,0.621726,0.598808,0.58862,0.586408,0.583756,0.577674,0.577562,0.576943,0.575722,0.573266,...,0.560588,0.555482,0.554524,0.55437,0.553269,0.550447,0.545703,0.533073,0.531746,0.52206

TARANTULA SCORES

,cx 8,x 10,ry 0,ry 1,cx 7,ry 14,ry 9,cx 6,cx 5,ry 2,...,ry 13,ry 11,cx 18,ry 4,cx 16,ry 12,ry 19,ry 20,ry 23,ry 22
sum,0.621726,0.598808,0.58862,0.586408,0.583756,0.577674,0.577562,0.576943,0.575722,0.573266,...,0.560588,0.555482,0.554524,0.55437,0.553269,0.550447,0.545703,0.533073,0.531746,0.52206

DSTAR SCORES

,cx 18,cx 17,ry 19,cx 15,cx 16,ry 20,ry 22,ry 21,cx 6,cx 7,...,ry 14,cx 8,ry 4,ry 1,x 10,ry 2,ry 3,ry 0,ry 11,ry 12
sum,17.302181,15.757043,15.143945,13.028986,12.590402,12.30061,6.617358,5.395905,2.98274,2.942842,...,1.705614,0.982233,0.533252,0.471083,0.040924,0.00445,0.003182,5.460458e-10,8.773956e-11,1.955246e-11

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_x_inGap_10_.qasm

100%|██████████| 10/10 [00:20<00:00,  2.08s/it]
100%|██████████| 10/10 [00:19<00:00,  2.00s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.534396,1.367172,0.888255,1.822883,2.381779,2.539404,1.967695,1.632520,1.563671,0.425891,...,0.322085,0.614300,0.604018,0.462636,0.223488,0.018123,0.017981,0.211132,0.000008,fail
1,0.466153,1.367380,0.759365,1.700283,2.676126,2.809195,1.890726,1.671134,1.594366,0.422706,...,0.222120,0.568511,0.539987,0.398725,0.195523,0.016583,0.016428,0.177834,0.000008,fail
2,0.614580,1.202912,0.711348,1.292222,2.067436,2.354084,1.987869,1.822285,1.842389,0.462233,...,0.205695,0.618008,0.607690,0.435908,0.192456,0.015272,0.019379,0.226277,0.000007,fail
3,0.402109,1.378205,0.871940,1.651829,1.978264,2.256936,2.337294,2.337956,2.239672,0.521735,...,0.215944,0.786729,0.803359,0.603136,0.294586,0.016753,0.024594,0.277516,0.000008,fail
4,0.500171,1.276941,0.581974,1.388390,2.045002,2.345273,2.412692,2.514865,2.262509,0.540543,...,0.134867,0.652015,0.611768,0.460111,0.211947,0.017632,0.020583,0.229297,0.000008,fail
5,0.632987,1.259566,0.831234,1.336523,1.915280,2.199060,2.297427,1.902350,2.066443,0.442101,...,0.285658,0.690057,0.682029,0.532379,0.252891,0.018996,0.023077,0.275308,0.000007,fail
6,0.723481,1.466681,0.784440,2.063351,2.416979,2.572584,2.137953,1.922186,1.582563,0.390747,...,0.266297,0.656817,0.669868,0.510401,0.247711,0.017982,0.022054,0.218767,0.000006,fail
7,0.488114,1.278264,0.762046,1.591873,2.181997,2.465145,2.358644,1.833835,1.754795,0.426785,...,0.341836,0.697950,0.616962,0.520652,0.255552,0.018845,0.020654,0.257844,0.000008,fail
8,0.582260,1.285024,0.688703,1.415061,1.808123,1.982964,1.920178,1.463065,1.296765,0.294317,...,0.200262,0.488693,0.428992,0.340330,0.170862,0.013682,0.013618,0.170405,0.000006,fail
9,0.413460,1.223769,0.873748,2.337393,2.573518,2.648493,1.807507,1.619452,1.709995,0.416066,...,0.278815,0.592818,0.577613,0.481816,0.233530,0.014900,0.018643,0.202303,0.000008,fail
10,0.341772,0.886721,0.445480,1.112399,1.792967,1.957804,1.586254,1.387092,1.193675,0.372738,...,0.166862,0.472175,0.422065,0.325139,0.153930,0.010978,0.013447,0.149177,0.000006,pass
11,0.576575,1.107916,0.707453,1.868801,1.600576,1.754518,1.934038,2.212606,2.383336,0.505539,...,0.195554,0.707297,0.761111,0.506939,0.232660,0.016696,0.025982,0.257797,0.000007,pass
12,0.380641,0.820035,0.712029,1.035344,1.100659,1.248413,1.321687,1.381700,1.324939,0.312210,...,0.214516,0.422176,0.478630,0.405219,0.181721,0.013157,0.015494,0.162274,0.000005,pass
13,0.334482,0.698123,0.573601,0.882681,1.201951,1.298002,1.163082,1.199389,1.333793,0.354071,...,0.162031,0.377669,0.380071,0.308695,0.144535,0.009801,0.013575,0.133324,0.000005,pass
14,0.439551,1.394839,0.827554,1.616666,1.431751,1.507520,1.446157,1.343854,1.357594,0.378220,...,0.249298,0.518498,0.570591,0.470091,0.250971,0.012927,0.017353,0.180392,0.000005,pass
15,0.417153,1.053567,0.722056,1.821737,2.154715,2.237405,1.574634,1.846487,2.086816,0.602866,...,0.261497,0.660506,0.671190,0.535708,0.286770,0.013902,0.021868,0.207711,0.000007,pass
16,0.595273,1.685666,0.921697,2.394942,1.829744,1.901281,2.002822,1.970747,2.126316,0.554148,...,0.226912,0.669798,0.723067,0.577793,0.309988,0.016148,0.024128,0.253430,0.000006,pass
17,0.258034,1.031270,0.802743,1.472512,1.405104,1.524989,1.480260,1.244947,0.944462,0.314367,...,0.309526,0.486108,0.433860,0.444575,0.210812,0.012090,0.013330,0.141659,0.000005,pass
18,0.695597,1.507064,0.835655,1.855296,1.730628,1.911353,2.158546,1.735643,1.394840,0.385838,...,0.200443,0.555483,0.456963,0.391124,0.193802,0.016126,0.014969,0.191378,0.000006,pass
19,0.567577,1.225773,0.928441,1.550291,2.196958,2.420823,2.073211,1.755342,2.025888,0.544343,...,0.348730,0.683123,0.710536,0.629586,0.326618,0.016476,0.022460,0.254618,0.000009,pass

BARINEL SCORES

,cx 18,x 9,ry 19,ry 10,cx 17,ry 11,ry 3,ry 13,ry 0,cx 16,...,ry 12,cx 15,cx 6,ry 2,ry 20,cx 8,ry 21,cx 5,ry 14,ry 4
sum,0.57644,0.574605,0.57274,0.572471,0.557811,0.555078,0.549603,0.546174,0.544315,0.53796,...,0.526933,0.525547,0.522731,0.518972,0.515354,0.51437,0.509072,0.508095,0.501084,0.498549

TARANTULA SCORES

,cx 18,x 9,ry 19,ry 10,cx 17,ry 11,ry 3,ry 13,ry 0,cx 16,...,ry 12,cx 15,cx 6,ry 2,ry 20,cx 8,ry 21,cx 5,ry 14,ry 4
sum,0.57644,0.574605,0.57274,0.572471,0.557811,0.555078,0.549603,0.546174,0.544315,0.53796,...,0.526933,0.525547,0.522731,0.518972,0.515354,0.51437,0.509072,0.508095,0.501084,0.498549

DSTAR SCORES

,cx 18,ry 19,cx 17,cx 16,cx 15,ry 20,ry 22,ry 21,ry 13,cx 7,...,ry 14,x 9,cx 8,ry 1,ry 4,ry 2,ry 3,ry 0,ry 11,ry 12
sum,21.048136,18.376222,16.677555,13.437681,12.260651,10.759332,8.022289,3.439424,2.830251,2.605612,...,1.316832,0.594228,0.49602,0.423038,0.422377,0.003812,0.002809,5.360620e-10,1.143804e-10,2.223513e-11

ERROR GATE LOCATION:
9
Now evolving the following mutant:  AddGate_z_inGap_18_.qasm

100%|██████████| 10/10 [00:21<00:00,  2.11s/it]
100%|██████████| 10/10 [00:19<00:00,  1.96s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,z 17,cx 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.457686,1.242853,0.682048,1.569244,1.459866,1.617436,0.304444,1.802956,1.461937,1.365650,...,0.219927,0.554805,0.499040,0.395766,0.196904,0.014426,0.016592,0.188126,0.000005,fail
1,0.491803,0.839303,0.500782,0.968309,1.921824,2.253771,0.384317,2.387457,2.200901,1.996853,...,0.244320,0.654055,0.622255,0.505193,0.233407,0.017999,0.021025,0.251941,0.000008,fail
2,0.660696,1.333330,0.848691,1.968613,1.618881,1.800744,0.350492,2.130614,2.074820,2.077802,...,0.253835,0.669468,0.710273,0.539176,0.248789,0.017920,0.023415,0.251339,0.000007,fail
3,0.520584,1.308166,1.055962,1.748514,1.782771,1.990784,0.335522,2.187926,2.393866,2.218449,...,0.315771,0.754754,0.823068,0.616714,0.277376,0.016948,0.025706,0.250830,0.000008,fail
4,0.684622,1.050161,1.003956,1.755612,2.220635,2.409005,0.340454,2.041356,2.006829,2.228554,...,0.337009,0.710565,0.777136,0.589814,0.267914,0.019325,0.024597,0.260717,0.000009,fail
5,0.622806,1.085874,0.763428,1.648057,1.617957,1.690748,0.291565,1.713031,1.518142,1.294900,...,0.217726,0.519181,0.471763,0.361604,0.174334,0.013926,0.016864,0.156485,0.000005,fail
6,0.571619,1.134818,0.771786,1.468737,1.875067,2.204937,0.388103,2.484039,2.431380,1.926525,...,0.286239,0.730869,0.707176,0.556260,0.254996,0.019335,0.022288,0.247647,0.000008,fail
7,0.438729,1.211480,0.689860,1.294787,1.746302,1.991421,0.356892,2.113684,1.917186,1.746753,...,0.230645,0.658839,0.641340,0.506703,0.249111,0.016045,0.021473,0.235697,0.000006,fail
8,0.639709,1.444533,0.882220,1.862927,1.705921,1.911566,0.408655,2.346675,1.683549,1.326523,...,0.355847,0.700138,0.572252,0.480233,0.229066,0.018302,0.019027,0.230286,0.000007,fail
9,0.576564,1.201135,0.671071,1.612653,1.963774,2.137009,0.361410,2.138899,1.969919,1.618956,...,0.311867,0.646100,0.649098,0.474990,0.247565,0.018013,0.020952,0.215033,0.000006,fail
10,0.592114,1.466811,1.132273,1.863387,2.103264,2.110142,0.240225,1.493529,1.206116,1.068379,...,0.335511,0.524837,0.506851,0.457173,0.223486,0.014653,0.014540,0.153208,0.000007,pass
11,0.577210,1.181003,0.826289,1.601179,2.270291,2.364908,0.244095,1.517735,1.549008,1.320756,...,0.256829,0.485838,0.535561,0.420235,0.165467,0.015437,0.016582,0.148261,0.000006,pass
12,0.547916,1.154898,0.790449,2.078339,2.111260,2.329175,0.378202,2.253088,2.207353,2.338213,...,0.309847,0.734339,0.841682,0.652359,0.337466,0.019186,0.028008,0.293865,0.000008,pass
13,0.388842,1.070051,0.598562,1.203134,1.875270,2.145626,0.291827,1.862507,1.893286,1.912441,...,0.190895,0.596054,0.633504,0.509793,0.251599,0.015015,0.019545,0.229053,0.000007,pass
14,0.440278,1.294087,0.788680,1.473456,1.705465,1.997016,0.347252,2.139142,1.704532,1.709776,...,0.203532,0.674888,0.648582,0.540062,0.275167,0.014792,0.020441,0.265749,0.000007,pass
15,0.508993,1.015722,0.825802,1.534125,1.762401,1.829855,0.212690,1.436371,1.462856,1.157488,...,0.291473,0.411336,0.451578,0.402455,0.207068,0.014985,0.013059,0.127132,0.000006,pass
16,0.506379,1.287058,1.069780,1.655224,1.602497,1.691301,0.244584,1.471954,1.198434,1.494335,...,0.279760,0.530875,0.529899,0.479221,0.246024,0.012416,0.016165,0.194801,0.000006,pass
17,0.498142,1.008623,0.608218,1.393364,1.670401,1.826536,0.298896,1.993410,1.893888,1.529214,...,0.167356,0.523999,0.536413,0.396010,0.212033,0.015208,0.017572,0.185924,0.000006,pass
18,0.392902,0.679801,0.738234,1.304471,1.092314,1.298475,0.313197,1.777853,1.675422,1.835265,...,0.300976,0.596674,0.615449,0.503527,0.236611,0.015671,0.020049,0.234685,0.000007,pass
19,0.514660,0.846875,0.739221,1.545489,2.094177,2.326179,0.348610,2.110821,2.221723,1.950914,...,0.272744,0.666324,0.695688,0.603788,0.293528,0.015850,0.024392,0.232621,0.000007,pass

BARINEL SCORES

,z 17,ry 10,cx 16,cx 15,cx 7,ry 23,ry 3,ry 2,ry 11,ry 1,...,ry 13,ry 9,cx 8,ry 0,ry 20,cx 5,cx 18,ry 19,ry 4,ry 21
sum,0.54675,0.542606,0.541751,0.536076,0.534576,0.532796,0.529229,0.526829,0.526175,0.52559,...,0.515929,0.515434,0.51526,0.510251,0.503887,0.503094,0.501105,0.49483,0.492855,0.492253

TARANTULA SCORES

,z 17,ry 10,cx 16,cx 15,cx 7,ry 23,ry 3,ry 2,ry 11,ry 1,...,ry 13,ry 9,cx 8,ry 0,ry 20,cx 5,cx 18,ry 19,ry 4,ry 21
sum,0.54675,0.542606,0.541751,0.536076,0.534576,0.532796,0.529229,0.526829,0.526175,0.52559,...,0.515929,0.515434,0.51526,0.510251,0.503887,0.503094,0.501105,0.49483,0.492855,0.492253

DSTAR SCORES

,cx 16,cx 15,cx 18,cx 14,ry 19,ry 20,ry 22,ry 21,cx 7,cx 6,...,ry 13,z 17,cx 8,ry 4,ry 1,ry 2,ry 3,ry 0,ry 10,ry 11
sum,16.241524,14.306566,13.379259,12.04077,11.34343,9.852149,6.687085,3.41845,2.765537,2.619843,...,1.429647,0.960051,0.60993,0.454823,0.433923,0.004408,0.002922,4.738672e-10,1.156259e-10,2.421496e-11

ERROR GATE LOCATION:
17
Now evolving the following mutant:  AddGate_rx_inGap_11_.qasm

100%|██████████| 10/10 [00:22<00:00,  2.23s/it]
100%|██████████| 10/10 [00:19<00:00,  1.97s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.482563,1.183170,1.106256,1.554852,1.431975,1.539008,1.448582,1.015206,0.984307,0.318533,...,0.347295,0.472301,0.462472,0.415432,0.175675,0.013813,0.013979,0.163338,0.000005,fail
1,0.508488,1.132212,0.776081,1.322815,1.968206,2.162768,1.865337,1.618165,1.513085,0.510287,...,0.290340,0.582803,0.619050,0.497217,0.231598,0.016512,0.019252,0.214197,0.000007,fail
2,0.445771,0.832388,0.799900,1.963068,1.922280,1.922657,1.162115,0.947528,1.137844,0.330987,...,0.315109,0.424234,0.460553,0.376942,0.166488,0.013554,0.014623,0.140548,0.000005,fail
3,0.629764,1.411999,1.132565,1.552487,2.837233,3.078702,2.601293,2.481923,2.149207,0.614630,...,0.360162,0.764088,0.801130,0.619304,0.299084,0.021970,0.025110,0.253553,0.000009,fail
4,0.492159,1.379531,0.985919,1.518445,1.656602,1.819122,1.949471,1.799677,1.412567,0.336508,...,0.257437,0.628169,0.637493,0.457747,0.196957,0.017590,0.019018,0.207817,0.000006,fail
5,0.584778,1.283912,1.093355,1.833864,2.608610,2.722734,1.817529,1.387502,1.542130,0.490508,...,0.359947,0.540569,0.567174,0.565117,0.279517,0.018079,0.018639,0.202218,0.000008,fail
6,0.526829,1.125430,0.867481,1.676593,2.335690,2.560037,2.289727,2.156566,2.125715,0.569563,...,0.320005,0.697060,0.764886,0.600131,0.283551,0.019292,0.024937,0.263303,0.000008,fail
7,0.453526,0.694514,0.696623,1.432676,1.715844,1.832535,1.480617,1.714913,1.973562,0.457730,...,0.227616,0.574199,0.641492,0.473481,0.215765,0.013541,0.020582,0.204814,0.000007,fail
8,0.484039,1.024897,0.684442,1.678566,1.985342,2.300062,2.719809,2.574358,2.297480,0.641625,...,0.289702,0.846748,0.800748,0.600935,0.269269,0.021257,0.026183,0.301761,0.000008,fail
9,0.397630,1.029515,0.724669,0.975633,1.629479,1.856423,1.927310,1.687827,1.327348,0.430508,...,0.258793,0.563678,0.510682,0.407778,0.169290,0.015613,0.015301,0.177351,0.000006,fail
10,0.538886,1.318343,0.693874,0.987011,1.670581,1.965841,1.976163,1.790771,1.792299,0.480810,...,0.253852,0.611985,0.657326,0.508216,0.269725,0.015736,0.020335,0.234995,0.000007,pass
11,0.712134,1.334772,1.000774,1.831565,1.949537,2.051814,2.048758,1.603340,1.287477,0.457919,...,0.295810,0.579881,0.552332,0.508767,0.264571,0.016754,0.017350,0.200780,0.000006,pass
12,0.239916,0.992123,0.491006,1.222411,1.464037,1.657478,1.879399,1.503755,1.164247,0.410975,...,0.224254,0.540707,0.423141,0.387575,0.185053,0.014174,0.013294,0.175924,0.000006,pass
13,0.524835,1.449132,0.983137,1.751117,2.367719,2.507183,1.991848,1.600140,1.569985,0.516427,...,0.297873,0.600533,0.580792,0.501943,0.250099,0.017238,0.019111,0.204514,0.000007,pass
14,0.541500,1.261201,0.528772,1.546783,2.181561,2.449297,2.151153,2.062593,1.891940,0.502784,...,0.160193,0.652794,0.599112,0.454582,0.238895,0.015383,0.019401,0.216346,0.000008,pass
15,0.528931,1.022631,0.794365,1.717104,1.466535,1.518875,1.532326,1.382044,1.373970,0.385185,...,0.240356,0.493005,0.444800,0.412375,0.227205,0.011890,0.015853,0.159582,0.000005,pass
16,0.550823,1.212519,0.726676,0.952039,1.542669,1.883947,2.417246,2.266588,2.004820,0.553644,...,0.290853,0.659486,0.675343,0.564657,0.286557,0.017954,0.022361,0.257509,0.000008,pass
17,0.441271,0.747343,0.832604,1.296600,2.042932,2.313109,2.056334,2.019947,1.884860,0.491750,...,0.377100,0.740581,0.719599,0.577619,0.260953,0.016874,0.022561,0.239469,0.000008,pass
18,0.449228,1.169310,0.656352,1.717424,1.950199,2.191883,2.443420,2.234326,2.014662,0.593591,...,0.255595,0.757337,0.730775,0.593411,0.319106,0.016835,0.023406,0.267234,0.000008,pass
19,0.450444,0.878366,0.741009,1.838332,1.873919,1.975972,1.493451,1.719925,1.843558,0.537849,...,0.241475,0.578248,0.665845,0.523474,0.238367,0.014835,0.021243,0.200296,0.000006,pass

BARINEL SCORES

,ry 21,rx 10,cx 8,ry 3,ry 19,cx 18,ry 20,cx 6,ry 13,ry 0,...,ry 1,cx 7,cx 15,ry 22,ry 12,cx 17,cx 16,ry 14,ry 11,ry 4
sum,0.543477,0.539104,0.534345,0.520597,0.520486,0.515111,0.510679,0.508795,0.508718,0.507087,...,0.496763,0.495097,0.494524,0.493591,0.491496,0.490723,0.488757,0.488057,0.482465,0.473762

TARANTULA SCORES

,ry 21,rx 10,cx 8,ry 3,ry 19,cx 18,ry 20,cx 6,ry 13,ry 0,...,ry 1,cx 7,cx 15,ry 22,ry 12,cx 17,cx 16,ry 14,ry 11,ry 4
sum,0.543477,0.539104,0.534345,0.520597,0.520486,0.515111,0.510679,0.508795,0.508718,0.507087,...,0.496763,0.495097,0.494524,0.493591,0.491496,0.490723,0.488757,0.488057,0.482465,0.473762

DSTAR SCORES

,cx 18,ry 19,cx 17,cx 16,cx 15,ry 20,ry 22,ry 21,cx 6,cx 7,...,ry 14,cx 8,ry 4,ry 1,rx 10,ry 2,ry 3,ry 0,ry 11,ry 12
sum,15.565272,14.158652,12.371301,10.722323,10.102888,9.675196,5.758794,4.50632,2.44617,2.290226,...,1.480032,0.724767,0.417148,0.372819,0.032309,0.003831,0.002886,4.952407e-10,8.410235e-11,2.039689e-11

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_rz_inGap_23_.qasm

100%|██████████| 10/10 [00:20<00:00,  2.06s/it]
100%|██████████| 10/10 [00:19<00:00,  1.91s/it]

,ry 23,rz 22,ry 21,ry 20,ry 19,ry 18,cx 17,cx 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.588907,0.588907,1.070620,0.610714,1.231844,1.422591,1.632978,1.843631,1.587340,1.789328,...,0.284046,0.813980,0.747637,0.708578,0.249912,0.014092,0.031465,0.312537,0.000008,fail
1,0.630009,0.630009,1.028614,0.778890,1.385238,1.763712,1.961119,1.994380,1.915084,2.001129,...,0.365110,0.891159,0.867079,0.815833,0.260745,0.018048,0.035003,0.324851,0.000010,fail
2,0.892394,0.892394,0.873752,0.667997,1.690350,1.471816,1.600089,1.715695,1.666552,1.718690,...,0.297402,0.841281,0.829707,0.770315,0.218711,0.015362,0.036334,0.329082,0.000009,fail
3,0.563064,0.563064,0.896918,0.931026,1.952209,2.140242,2.249342,1.654265,1.769937,1.832178,...,0.362362,0.829734,0.883601,0.857371,0.251000,0.018245,0.031403,0.297923,0.000010,fail
4,0.584295,0.584295,1.330972,0.730665,1.824810,2.179104,2.287726,1.768437,1.427557,1.499882,...,0.368586,0.794120,0.656524,0.684674,0.233409,0.016699,0.025647,0.256250,0.000008,fail
5,0.702872,0.702872,1.260645,0.976648,1.666111,1.866164,1.971630,1.877601,1.705791,1.722243,...,0.417578,0.865365,0.827246,0.799190,0.266320,0.017945,0.031669,0.277768,0.000010,fail
6,0.638970,0.638970,1.219848,0.727195,1.637532,2.318659,2.445980,1.802734,1.999105,2.012956,...,0.330361,0.829177,0.886027,0.801232,0.267515,0.015095,0.035207,0.263304,0.000010,fail
7,0.639753,0.639753,1.148645,0.636333,1.627062,1.954774,2.155891,2.165113,2.116446,2.166681,...,0.298704,0.972139,0.915706,0.836691,0.288261,0.016726,0.037819,0.363611,0.000009,fail
8,0.673373,0.673373,0.939555,0.823509,1.644574,2.028371,2.097246,1.675618,1.625402,1.705451,...,0.375196,0.806545,0.817356,0.801108,0.266558,0.017138,0.032689,0.287673,0.000009,fail
9,0.608034,0.608034,1.213830,0.903837,1.558021,2.049870,2.163158,1.931967,1.792957,1.937908,...,0.400619,0.900351,0.889597,0.826578,0.279053,0.017432,0.035738,0.306281,0.000010,fail
10,0.480210,0.480210,0.839047,0.677115,1.055560,1.374816,1.495756,1.403614,1.179486,1.352790,...,0.354154,0.692283,0.588666,0.610049,0.237051,0.014484,0.022184,0.242643,0.000007,pass
11,0.478884,0.478884,0.875869,0.528520,0.979137,1.237394,1.587373,2.471905,2.338734,2.223068,...,0.284015,1.057200,0.906521,0.803397,0.280100,0.015564,0.038091,0.390293,0.000008,pass
12,0.456804,0.456804,0.790781,0.587176,1.562071,1.793915,1.852407,1.379386,1.535050,1.484550,...,0.221260,0.677909,0.762818,0.727420,0.208333,0.014336,0.025991,0.239946,0.000007,pass
13,0.478931,0.478931,1.121901,0.862302,1.198501,1.307183,1.618949,2.077476,1.553095,2.010114,...,0.482505,0.946318,0.816288,0.818516,0.329165,0.020160,0.027775,0.368345,0.000008,pass
14,0.525298,0.525298,1.756443,0.924370,2.063860,1.875136,2.070689,2.342820,2.087321,2.139080,...,0.363322,0.946575,0.840433,0.804506,0.375813,0.016821,0.032969,0.322711,0.000008,pass
15,0.348194,0.348194,1.066472,0.784354,1.193771,2.180766,2.257768,1.206018,1.123071,1.231578,...,0.342392,0.594629,0.564365,0.600079,0.201889,0.014739,0.015899,0.179709,0.000007,pass
16,0.431924,0.431924,0.954784,0.508987,1.283377,1.272507,1.367025,1.347646,0.982737,1.156324,...,0.275625,0.579776,0.440050,0.456952,0.202650,0.010344,0.018885,0.190725,0.000005,pass
17,0.795034,0.795034,1.346331,0.966899,2.020093,1.573464,1.588012,1.606772,1.440092,1.458614,...,0.383663,0.785756,0.791645,0.753756,0.237255,0.016398,0.032737,0.270959,0.000008,pass
18,0.389920,0.389920,0.645981,0.510832,0.552530,1.534747,1.700766,1.304365,0.894423,1.099132,...,0.259921,0.582132,0.367524,0.421927,0.176515,0.011725,0.014330,0.189722,0.000006,pass
19,0.628006,0.628006,0.836755,0.408532,1.386006,1.520517,1.679512,1.843232,1.880050,1.841932,...,0.230566,0.826040,0.785194,0.747367,0.241556,0.012695,0.031661,0.276659,0.000009,pass

BARINEL SCORES

,ry 13,ry 23,rz 22,ry 2,ry 0,ry 18,ry 19,cx 6,cx 17,cx 15,...,ry 11,ry 3,ry 1,ry 10,cx 7,cx 8,cx 16,ry 21,ry 12,ry 4
sum,0.573362,0.565387,0.565387,0.561039,0.551827,0.550549,0.549519,0.547977,0.544291,0.539732,...,0.534311,0.531072,0.530537,0.527868,0.526343,0.522587,0.520419,0.517651,0.513486,0.508987

TARANTULA SCORES

,ry 13,rz 22,ry 23,ry 2,ry 0,ry 18,ry 19,cx 6,cx 17,cx 15,...,ry 11,ry 3,ry 1,ry 10,cx 7,cx 8,cx 16,ry 21,ry 12,ry 4
sum,0.573362,0.565387,0.565387,0.561039,0.551827,0.550549,0.549519,0.547977,0.544291,0.539732,...,0.534311,0.531072,0.530537,0.527868,0.526343,0.522587,0.520419,0.517651,0.513486,0.508987

DSTAR SCORES

,cx 17,ry 18,cx 14,cx 16,cx 15,ry 19,ry 21,ry 13,cx 7,cx 6,...,ry 23,ry 12,cx 8,ry 1,ry 4,ry 2,ry 3,ry 0,ry 10,ry 11
sum,15.538314,14.35346,13.003771,12.587234,12.392122,11.290685,5.96189,4.980608,4.126799,4.105338,...,2.832985,2.446089,0.928193,0.719402,0.533537,0.010806,0.002741,8.582962e-10,1.829927e-10,4.507014e-11

ERROR GATE LOCATION:
22
Now evolving the following mutant:  AddGate_ry_inGap_13_.qasm

100%|██████████| 10/10 [00:21<00:00,  2.13s/it]
100%|██████████| 10/10 [00:19<00:00,  1.99s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.626834,1.225233,0.787787,1.686429,1.186188,1.254765,1.567095,1.680399,1.417810,0.276807,...,0.226515,0.495349,0.525336,0.378987,0.187115,0.014003,0.016912,0.154997,0.000004,fail
1,0.476951,0.839328,0.543354,0.977168,1.989414,2.325510,2.117713,2.027091,1.919543,0.423929,...,0.331298,0.700296,0.724976,0.537488,0.231531,0.017771,0.022608,0.247002,0.000008,fail
2,0.548305,1.418070,0.908552,1.544260,2.186999,2.448611,2.501705,1.940262,1.637270,0.406838,...,0.346559,0.675249,0.649481,0.569777,0.280745,0.020612,0.020073,0.254807,0.000008,fail
3,0.569348,1.234424,0.905650,2.100794,2.127143,2.176611,1.718157,1.571062,1.659898,0.477595,...,0.286040,0.592923,0.577022,0.460299,0.213602,0.016053,0.019171,0.184044,0.000006,fail
4,0.710392,0.977643,0.807508,1.773072,2.172415,2.445246,2.157632,2.204557,2.305930,0.439152,...,0.353345,0.699945,0.778605,0.600131,0.277298,0.018618,0.026922,0.275895,0.000009,fail
5,0.702506,1.258478,0.789603,1.735145,2.220006,2.215382,1.256908,1.416855,1.302722,0.339011,...,0.190259,0.391717,0.499088,0.363326,0.169346,0.014487,0.015570,0.122560,0.000005,fail
6,0.622888,1.404406,1.040525,1.535265,2.264545,2.499489,2.188043,1.928916,1.934630,0.571975,...,0.352745,0.675268,0.702769,0.584224,0.265647,0.020123,0.021823,0.253092,0.000009,fail
7,0.572431,1.092485,0.686533,1.351334,2.231712,2.489030,2.057559,2.140449,2.206726,0.587266,...,0.279436,0.674090,0.718162,0.554449,0.257579,0.019008,0.023599,0.241169,0.000008,fail
8,0.438573,1.201869,0.765061,1.682463,2.045017,2.185996,1.618675,1.654448,1.827132,0.472973,...,0.268452,0.601235,0.648175,0.522364,0.248051,0.015375,0.020753,0.214650,0.000007,fail
9,0.584845,1.417585,0.897003,1.634114,2.001200,2.185762,1.955643,1.854930,1.573959,0.449801,...,0.284138,0.613099,0.597471,0.496561,0.244398,0.016314,0.019298,0.193461,0.000006,fail
10,0.574698,1.081789,0.926850,1.621408,1.057981,1.273950,2.056236,1.964849,1.681443,0.468999,...,0.270303,0.609826,0.623395,0.489708,0.232498,0.016130,0.020226,0.228673,0.000006,pass
11,0.777647,1.596715,0.984175,2.383530,1.664392,1.529900,1.086932,1.220346,1.098216,0.261532,...,0.201039,0.392847,0.443488,0.359021,0.182071,0.013243,0.012762,0.102609,0.000004,pass
12,0.603757,1.051312,0.607581,1.868663,2.184334,2.435130,2.404401,2.263085,2.383428,0.545266,...,0.213644,0.763151,0.724366,0.561867,0.297864,0.016914,0.024963,0.286316,0.000008,pass
13,0.516260,0.820649,0.777292,1.014363,1.732972,2.043364,2.216039,2.235166,2.064712,0.500084,...,0.335759,0.704141,0.733894,0.558592,0.231894,0.018910,0.023077,0.245798,0.000008,pass
14,0.456121,1.042593,0.361896,1.364434,1.693072,1.792871,1.684212,1.576317,1.059311,0.317316,...,0.180083,0.429202,0.408044,0.294387,0.155679,0.013303,0.012085,0.124457,0.000005,pass
15,0.380423,0.908483,0.422043,1.316781,1.453069,1.593140,1.733345,1.250483,1.048126,0.364473,...,0.206948,0.449746,0.392893,0.363906,0.217094,0.011347,0.013989,0.163423,0.000004,pass
16,0.598432,1.174563,0.934666,1.200987,1.584507,1.856498,2.268168,1.823193,1.513646,0.369150,...,0.322011,0.577804,0.573856,0.481837,0.222099,0.018193,0.018384,0.219644,0.000007,pass
17,0.590219,1.174258,0.760885,1.288345,2.115786,2.451594,2.538403,2.340893,2.231568,0.548434,...,0.276892,0.757197,0.768296,0.577089,0.276495,0.019601,0.024735,0.281255,0.000008,pass
18,0.180125,0.419897,0.538241,0.544375,1.048267,1.263259,1.139279,0.947726,1.225228,0.310235,...,0.226985,0.409247,0.431685,0.394996,0.203482,0.008385,0.013585,0.172948,0.000005,pass
19,0.253105,0.759148,0.724569,0.981389,1.182730,1.318202,1.341372,1.037904,1.334061,0.331149,...,0.323388,0.454902,0.492757,0.466435,0.235006,0.012237,0.016129,0.183890,0.000006,pass

BARINEL SCORES

,ry 19,cx 18,ry 22,ry 23,ry 20,ry 9,ry 3,ry 12,ry 21,ry 11,...,cx 15,ry 0,cx 5,ry 14,cx 16,cx 7,ry 1,ry 4,ry 10,cx 17
sum,0.565126,0.558673,0.546159,0.542762,0.541139,0.539316,0.53758,0.536668,0.536038,0.535118,...,0.5321,0.531891,0.527028,0.525332,0.525072,0.524475,0.515981,0.513083,0.513068,0.508918

TARANTULA SCORES

,ry 19,cx 18,ry 22,ry 23,ry 20,ry 9,ry 3,ry 12,ry 21,ry 11,...,cx 15,ry 0,cx 5,ry 14,cx 16,cx 7,ry 1,ry 4,ry 10,cx 17
sum,0.565126,0.558673,0.546159,0.542762,0.541139,0.539316,0.53758,0.536668,0.536038,0.535118,...,0.5321,0.531891,0.527028,0.525332,0.525072,0.524475,0.515981,0.513083,0.513068,0.508918

DSTAR SCORES

,cx 18,ry 19,cx 17,cx 16,cx 15,ry 20,ry 22,ry 21,cx 6,ry 13,...,ry 14,cx 8,ry 12,ry 4,ry 1,ry 2,ry 3,ry 0,ry 10,ry 11
sum,17.92636,16.221336,12.867123,12.72539,12.337424,10.881906,7.272972,3.88084,2.644211,2.625367,...,1.409833,0.678449,0.475339,0.460423,0.381945,0.004198,0.002927,4.874791e-10,9.140979e-11,2.258347e-11

ERROR GATE LOCATION:
13
Now evolving the following mutant:  AddGate_y_inGap_6_.qasm

100%|██████████| 10/10 [00:22<00:00,  2.24s/it]
100%|██████████| 10/10 [00:21<00:00,  2.13s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,y 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.426255,1.043328,0.761318,1.569876,1.797867,1.947500,1.974488,1.695812,1.628714,0.359992,...,0.604218,0.590505,0.506181,0.097353,0.258178,0.016095,0.019545,0.218603,0.000006,fail
1,0.490407,1.295012,0.870219,1.580963,2.384714,2.389580,1.370947,1.350584,1.268248,0.329437,...,0.476102,0.502294,0.425024,0.077967,0.209398,0.012982,0.014381,0.121991,0.000007,fail
2,0.494406,1.330242,0.683520,1.528689,2.330703,2.551203,1.911882,1.631728,1.835032,0.516761,...,0.561666,0.630800,0.588389,0.115792,0.319738,0.014766,0.020618,0.236971,0.000008,fail
3,0.499014,0.963137,0.693043,1.205661,2.159641,2.350576,1.822734,1.773094,1.716333,0.377000,...,0.560339,0.646179,0.533872,0.099583,0.262426,0.017558,0.020822,0.213307,0.000008,fail
4,0.606240,1.142036,1.021545,1.990805,2.505510,2.596319,1.937675,1.659177,1.558847,0.389058,...,0.612145,0.670373,0.546267,0.094774,0.258133,0.017845,0.020020,0.205905,0.000008,fail
5,0.604880,1.081489,0.878345,1.760938,1.593915,1.817092,2.158917,2.003843,2.196068,0.508801,...,0.705623,0.741029,0.565410,0.106603,0.281867,0.018870,0.025157,0.276894,0.000007,fail
6,0.578166,1.174633,0.707251,1.381064,1.558307,1.813892,2.043795,2.229508,2.212460,0.534105,...,0.675317,0.766644,0.560724,0.103638,0.274057,0.018179,0.025502,0.258744,0.000007,fail
7,0.601098,1.274307,0.809378,2.413662,2.459416,2.577089,2.088057,1.971088,1.600230,0.528288,...,0.631068,0.653167,0.557560,0.101233,0.278706,0.019100,0.021451,0.216847,0.000007,fail
8,0.556398,1.163894,0.973971,1.765643,2.458772,2.609592,2.124566,1.895744,1.669750,0.480264,...,0.663194,0.682196,0.569725,0.100861,0.278460,0.019611,0.020423,0.221386,0.000008,fail
9,0.411263,1.184967,0.589249,1.635875,1.844610,1.890578,1.492747,1.402520,1.246067,0.332060,...,0.425242,0.438563,0.367573,0.076654,0.203693,0.011864,0.014387,0.133079,0.000005,fail
10,0.289033,0.669758,0.509710,0.911460,1.095666,1.264038,1.338346,1.512239,1.560459,0.363066,...,0.469257,0.494900,0.410847,0.067881,0.185408,0.011821,0.016629,0.173087,0.000006,pass
11,0.523302,0.901923,0.735073,1.476268,2.040305,2.168571,1.565276,1.313489,1.103872,0.345235,...,0.502987,0.471793,0.377079,0.060857,0.164973,0.013829,0.014919,0.150462,0.000006,pass
12,0.373026,0.686574,0.571493,1.036197,0.937633,1.113246,1.322208,1.088818,1.271265,0.314469,...,0.436354,0.418470,0.352094,0.063723,0.174058,0.010430,0.013919,0.174914,0.000005,pass
13,0.567516,1.286808,0.647615,1.616907,1.312707,1.405470,1.693780,1.721786,1.214097,0.323243,...,0.434950,0.446101,0.360471,0.075928,0.196809,0.013462,0.014369,0.149272,0.000004,pass
14,0.590722,0.866974,0.868835,1.647564,1.522275,1.712341,1.986491,1.951028,1.782838,0.415409,...,0.574274,0.623169,0.499219,0.091227,0.244711,0.016422,0.019530,0.222794,0.000007,pass
15,0.599359,1.172985,1.063478,1.385657,2.203490,2.398805,1.957742,1.580230,1.290817,0.411408,...,0.598725,0.597072,0.523674,0.085499,0.240423,0.016395,0.017638,0.195834,0.000007,pass
16,0.479492,0.850200,0.676745,0.871999,2.218122,2.519124,2.123638,1.915758,1.882053,0.580540,...,0.578654,0.579343,0.474634,0.092036,0.240118,0.014988,0.019045,0.221109,0.000008,pass
17,0.469658,1.581298,0.853411,1.768613,2.666891,2.808099,2.201245,2.311178,2.051715,0.590814,...,0.672212,0.678410,0.547533,0.103891,0.278057,0.016355,0.020966,0.209251,0.000008,pass
18,0.435814,1.425249,0.954766,1.394840,2.311168,2.448974,1.678085,1.707780,1.680824,0.430488,...,0.612706,0.622824,0.513636,0.096522,0.257501,0.012459,0.019438,0.177304,0.000008,pass
19,0.515005,1.272402,0.761960,1.385401,1.010546,1.185293,1.700698,1.404771,1.235567,0.371076,...,0.533045,0.461075,0.370559,0.066714,0.182771,0.011654,0.015017,0.186294,0.000005,pass

BARINEL SCORES

,cx 9,ry 20,ry 19,ry 4,y 5,ry 3,cx 18,ry 2,cx 6,cx 7,...,ry 10,cx 8,ry 23,ry 22,cx 17,ry 12,cx 16,ry 11,ry 14,ry 21
sum,0.57283,0.555036,0.549133,0.548004,0.547837,0.547683,0.542334,0.541252,0.540981,0.539633,...,0.524058,0.522146,0.521027,0.520988,0.51861,0.516981,0.516208,0.51473,0.512352,0.511028

TARANTULA SCORES

,cx 9,ry 20,ry 19,ry 4,y 5,ry 3,cx 18,ry 2,cx 6,cx 7,...,ry 10,cx 8,ry 23,ry 22,cx 17,ry 12,cx 16,ry 11,ry 14,ry 21
sum,0.57283,0.555036,0.549133,0.548004,0.547837,0.547683,0.542334,0.541252,0.540981,0.539633,...,0.524058,0.522146,0.521027,0.520988,0.51861,0.516981,0.516208,0.51473,0.512352,0.511028

DSTAR SCORES

,cx 18,ry 19,cx 17,ry 20,cx 16,cx 15,ry 22,ry 21,cx 7,ry 13,...,ry 14,cx 9,ry 4,ry 1,y 5,ry 2,ry 3,ry 0,ry 11,ry 12
sum,17.509871,16.286725,12.993056,12.060311,11.703334,11.433747,6.555582,3.616463,2.596252,2.500313,...,1.34123,0.703893,0.56629,0.373149,0.087888,0.004024,0.002747,4.877785e-10,8.676395e-11,2.120179e-11

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_y_inGap_28_.qasm

100%|██████████| 10/10 [00:20<00:00,  2.01s/it]
100%|██████████| 10/10 [00:19<00:00,  1.92s/it]

,y 23,ry 22,ry 21,ry 20,ry 19,ry 18,cx 17,cx 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.488671,0.690055,1.491728,0.635683,2.252333,2.078101,2.152041,2.200262,2.092852,1.448265,...,0.227611,0.551123,0.506044,0.375270,0.181359,0.019459,0.016329,0.169107,0.000006,fail
1,0.468824,0.662028,1.381064,0.810071,1.647637,2.454116,2.717738,2.221126,2.042260,1.935894,...,0.320661,0.700091,0.728178,0.544229,0.266164,0.019660,0.023115,0.252176,0.000008,fail
2,0.314766,0.444483,1.157594,0.866528,2.144178,2.273747,2.357124,1.854043,1.681163,1.775383,...,0.278324,0.644365,0.658285,0.507112,0.242074,0.017140,0.020228,0.224858,0.000007,fail
3,0.470559,0.664479,1.062412,0.911809,2.172279,1.848119,1.981080,1.814693,1.752969,1.944641,...,0.341201,0.684179,0.695442,0.546926,0.254682,0.016972,0.023074,0.241928,0.000007,fail
4,0.455369,0.643029,0.998947,0.869394,1.793919,2.308023,2.413224,1.879795,1.925750,1.954108,...,0.315960,0.632256,0.697280,0.543856,0.244075,0.020223,0.022217,0.223472,0.000007,fail
5,0.381619,0.538886,1.382732,0.655220,1.329576,2.148740,2.334513,2.069402,1.618230,1.633157,...,0.244758,0.554083,0.534286,0.452908,0.241843,0.015418,0.019113,0.211273,0.000007,fail
6,0.455540,0.643271,1.320421,0.741055,1.546420,1.855165,2.141504,2.424230,2.249149,2.049196,...,0.264450,0.687065,0.693522,0.539355,0.271321,0.017528,0.022302,0.247673,0.000008,fail
7,0.412195,0.582062,1.173873,0.996305,1.540427,2.230191,2.555419,2.695343,2.744460,2.411077,...,0.356472,0.808487,0.879854,0.700935,0.334954,0.021449,0.028292,0.294326,0.000009,fail
8,0.508624,0.718231,1.715590,0.935769,2.413928,2.391527,2.601119,2.718006,2.567850,2.367453,...,0.226989,0.814911,0.829543,0.610725,0.308477,0.021643,0.026094,0.293574,0.000009,fail
9,0.458772,0.647835,1.167088,0.707281,1.683471,1.602582,1.804662,1.865597,1.997199,1.896217,...,0.203424,0.570492,0.612352,0.453482,0.195427,0.016344,0.021110,0.207057,0.000006,fail
10,0.434729,0.613882,1.315720,0.952526,1.626527,2.442912,2.625708,2.150409,1.746497,1.536928,...,0.301519,0.614120,0.622441,0.502172,0.224253,0.020617,0.018587,0.220320,0.000008,pass
11,0.283951,0.400968,0.928416,0.432483,0.747081,1.199728,1.341417,1.010384,1.074383,1.206584,...,0.137656,0.318693,0.340554,0.281018,0.137494,0.008612,0.011722,0.115110,0.000004,pass
12,0.424215,0.599037,1.050289,0.954689,2.180910,2.335653,2.427594,1.966784,1.632860,1.911562,...,0.325950,0.652738,0.713262,0.526538,0.257501,0.018616,0.023656,0.253660,0.000007,pass
13,0.246752,0.348440,1.073141,0.785980,1.552616,1.634361,1.758469,1.811678,1.901713,1.697881,...,0.266072,0.617419,0.612499,0.504796,0.247836,0.013480,0.019817,0.187541,0.000007,pass
14,0.407145,0.574932,0.939048,0.586839,1.488125,1.953133,2.077768,1.774620,1.627210,1.566645,...,0.235567,0.512341,0.526605,0.426611,0.222724,0.015853,0.017731,0.189831,0.000006,pass
15,0.338246,0.477639,0.896473,0.718622,1.648134,1.744241,1.874437,1.727282,1.636615,1.695338,...,0.187486,0.540038,0.485611,0.423141,0.215929,0.013509,0.016760,0.193908,0.000007,pass
16,0.344442,0.486388,1.190088,0.613215,1.750876,1.863862,1.929170,1.302839,1.208155,1.283698,...,0.165036,0.446143,0.444055,0.366069,0.176681,0.011368,0.013869,0.146103,0.000005,pass
17,0.345686,0.488146,0.833581,0.803896,1.405934,1.568673,1.728810,1.680817,1.872662,1.827282,...,0.198151,0.609706,0.685146,0.518238,0.256572,0.014014,0.020657,0.213465,0.000006,pass
18,0.414535,0.585367,0.939000,0.726772,1.316414,1.708943,1.789145,1.381245,1.285496,1.480420,...,0.164076,0.413766,0.435348,0.351736,0.181021,0.013285,0.014829,0.162805,0.000005,pass
19,0.357817,0.505275,0.859160,0.772645,1.491499,1.406272,1.467955,1.415720,1.152936,1.027619,...,0.234870,0.367538,0.381605,0.362708,0.170845,0.014630,0.013124,0.138900,0.000004,pass

BARINEL SCORES

,ry 10,cx 15,cx 16,ry 11,ry 9,ry 12,cx 7,cx 6,ry 2,ry 1,...,ry 0,cx 5,ry 22,y 23,ry 19,ry 4,cx 17,ry 18,ry 13,ry 20
sum,0.579989,0.577259,0.572709,0.570891,0.568038,0.566361,0.56621,0.565704,0.565101,0.564938,...,0.555549,0.55304,0.551009,0.551009,0.549153,0.548531,0.547981,0.542672,0.531072,0.525246

TARANTULA SCORES

,ry 10,cx 15,cx 16,ry 11,ry 9,ry 12,cx 7,cx 6,ry 2,ry 1,...,ry 0,cx 5,ry 22,y 23,ry 19,ry 4,cx 17,ry 18,ry 13,ry 20
sum,0.579989,0.577259,0.572709,0.570891,0.568038,0.566361,0.56621,0.565704,0.565101,0.564938,...,0.555549,0.55304,0.551009,0.551009,0.549153,0.548531,0.547981,0.542672,0.531072,0.525246

DSTAR SCORES

,cx 17,cx 16,cx 15,ry 18,cx 14,ry 19,ry 21,ry 20,ry 12,cx 6,...,ry 13,y 23,cx 8,ry 4,ry 1,ry 2,ry 3,ry 0,ry 10,ry 11
sum,18.321234,18.028381,16.998878,16.118632,14.938498,13.612474,8.247712,3.809302,3.250792,3.06381,...,1.581289,1.433474,0.632558,0.533751,0.473312,0.00484,0.003404,5.402032e-10,1.255269e-10,2.737675e-11

ERROR GATE LOCATION:
23
Now evolving the following mutant:  AddGate_ry_inGap_6_.qasm

100%|██████████| 10/10 [00:20<00:00,  2.07s/it]
100%|██████████| 10/10 [00:20<00:00,  2.07s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,ry 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.651477,1.459062,1.039949,2.013846,2.470615,2.627353,2.135651,2.097336,1.863203,0.559073,...,0.693170,0.688774,0.589226,0.310742,0.260908,0.016808,0.021146,0.227305,0.000009,fail
1,0.690512,1.067299,0.676774,1.759674,1.513161,1.660739,1.957519,2.061729,2.364124,0.464209,...,0.621127,0.684635,0.487815,0.283047,0.249487,0.015908,0.021909,0.257465,0.000007,fail
2,0.446459,1.082843,0.768475,1.386166,1.377433,1.663175,2.046549,1.595286,1.447158,0.404154,...,0.636139,0.595819,0.534687,0.299270,0.255609,0.013536,0.018918,0.244910,0.000006,fail
3,0.520864,1.142238,0.866205,1.779939,1.980319,2.164026,2.106117,1.820674,1.709459,0.562593,...,0.655943,0.644569,0.504557,0.246765,0.203466,0.017650,0.020223,0.242341,0.000007,fail
4,0.631827,0.781932,0.642168,1.447405,2.122508,2.358346,2.317272,2.139130,1.748566,0.406169,...,0.591534,0.641740,0.510424,0.282497,0.242527,0.017752,0.020972,0.239687,0.000007,fail
5,0.717960,1.357431,0.784631,1.734879,2.236234,2.415729,2.299714,2.220971,2.074106,0.500066,...,0.681436,0.767219,0.563362,0.323775,0.280169,0.017959,0.023511,0.272297,0.000008,fail
6,0.607274,1.205306,0.730557,1.814063,1.859672,1.889612,1.208260,1.600249,2.043939,0.452224,...,0.440809,0.592717,0.461889,0.255333,0.217260,0.010424,0.018910,0.193119,0.000005,fail
7,0.446123,1.182414,0.702757,2.055999,2.755240,2.875745,1.905857,2.253415,2.351435,0.546812,...,0.681908,0.735606,0.543590,0.274587,0.227432,0.016288,0.022554,0.235664,0.000008,fail
8,0.409383,1.252362,0.484736,1.667644,2.299450,2.528908,2.155079,1.771968,1.685254,0.526880,...,0.608094,0.515260,0.472327,0.253622,0.202088,0.015449,0.017329,0.221231,0.000007,fail
9,0.416023,1.655746,0.877762,1.848232,2.131428,2.244631,1.818534,1.809179,2.023993,0.555983,...,0.703746,0.719059,0.571315,0.314263,0.260220,0.014997,0.021854,0.245114,0.000008,fail
10,0.636319,1.111070,0.942508,1.713006,2.224941,2.401792,1.837481,1.739555,1.995762,0.549503,...,0.668498,0.759306,0.626818,0.310448,0.259500,0.017771,0.023916,0.258814,0.000008,pass
11,0.706017,1.186580,0.788417,1.339522,1.632588,1.865578,2.144808,1.971602,1.908146,0.454865,...,0.587690,0.602893,0.452422,0.248786,0.220842,0.016062,0.019184,0.246870,0.000007,pass
12,0.347513,1.018434,0.561471,1.161867,1.321277,1.391917,1.064581,0.764217,0.856028,0.303958,...,0.372032,0.366445,0.285520,0.158081,0.127692,0.009411,0.010613,0.135867,0.000004,pass
13,0.260499,0.881161,0.508245,1.468120,1.691804,1.824852,1.428149,1.322873,1.368161,0.389211,...,0.483995,0.461729,0.434004,0.227894,0.179951,0.013346,0.015112,0.169955,0.000005,pass
14,0.498781,1.054895,1.014854,1.272977,1.937042,2.114780,1.685104,1.608501,1.451385,0.401349,...,0.566865,0.580968,0.470273,0.232425,0.197928,0.017663,0.017579,0.176239,0.000007,pass
15,0.268893,0.585866,0.473841,1.007980,1.123570,1.256842,1.246460,1.317739,1.597538,0.337118,...,0.421816,0.472882,0.379225,0.210934,0.181144,0.009792,0.015420,0.178313,0.000005,pass
16,0.438015,1.398665,0.950963,1.793927,1.770968,1.724980,1.212717,1.116735,1.366131,0.373965,...,0.471387,0.484069,0.380253,0.199055,0.166641,0.011951,0.015473,0.141555,0.000005,pass
17,0.585153,1.065972,0.661398,2.201429,2.282386,2.248646,1.626791,1.874648,1.527012,0.407236,...,0.491548,0.522186,0.355138,0.193834,0.163633,0.015962,0.016717,0.140226,0.000006,pass
18,0.394503,1.024348,0.717206,1.222312,1.795146,1.968427,1.774709,1.856236,1.738654,0.509729,...,0.579537,0.599239,0.534955,0.282054,0.228392,0.014168,0.019094,0.211154,0.000007,pass
19,0.499988,1.132452,1.008445,2.371760,2.759830,2.863924,1.904495,2.037708,2.401716,0.626973,...,0.760557,0.870347,0.691501,0.388564,0.329679,0.016462,0.026407,0.285432,0.000009,pass

BARINEL SCORES

,ry 11,cx 17,cx 16,ry 1,ry 10,ry 12,ry 23,cx 15,ry 13,cx 8,...,cx 7,ry 14,ry 0,cx 18,cx 6,ry 20,ry 19,ry 3,ry 21,cx 9
sum,0.56381,0.5561,0.553747,0.550272,0.549917,0.546589,0.544341,0.543645,0.539014,0.538829,...,0.535161,0.533447,0.533055,0.532864,0.531935,0.529566,0.528083,0.523692,0.498246,0.485993

TARANTULA SCORES

,ry 11,cx 17,cx 16,ry 1,ry 10,ry 12,ry 23,cx 15,ry 13,cx 8,...,cx 7,ry 14,ry 0,cx 18,cx 6,ry 20,ry 19,ry 3,ry 21,cx 9
sum,0.56381,0.5561,0.553747,0.550272,0.549917,0.546589,0.544341,0.543645,0.539014,0.538829,...,0.535161,0.533447,0.533055,0.532864,0.531935,0.529566,0.528083,0.523692,0.498246,0.485993

DSTAR SCORES

,cx 18,cx 17,ry 19,cx 16,cx 15,ry 20,ry 22,ry 21,ry 13,cx 7,...,ry 14,ry 5,ry 4,ry 1,cx 9,ry 2,ry 3,ry 0,ry 11,ry 12
sum,16.958785,15.35275,15.080788,14.650416,14.228014,11.995691,7.258948,3.254357,2.786711,2.758734,...,1.726506,0.649511,0.477462,0.473884,0.437238,0.004223,0.002423,5.125977e-10,1.134574e-10,2.576323e-11

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_h_inGap_4_.qasm

100%|██████████| 10/10 [00:22<00:00,  2.24s/it]
100%|██████████| 10/10 [00:22<00:00,  2.24s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,ry 5,ry 4,h 3,ry 2,ry 1,ry 0,pass/fail
0,0.550555,1.316499,0.880888,1.932167,2.130910,2.344150,2.228063,2.197323,2.282393,0.539147,...,0.791254,0.815874,0.611890,0.291177,0.017594,0.264661,0.029215,0.277953,0.000008,fail
1,0.550101,1.259783,0.733812,1.622695,1.392949,1.614363,2.065653,2.077761,2.058509,0.420947,...,0.648922,0.693190,0.519350,0.258928,0.016586,0.237307,0.023895,0.243410,0.000007,fail
2,0.519933,1.356870,0.541449,1.818017,2.535789,2.658833,1.796948,2.283175,2.317256,0.518884,...,0.619757,0.738440,0.496434,0.245233,0.014926,0.208618,0.026489,0.212535,0.000007,fail
3,0.435886,0.896233,0.654773,0.888108,1.523175,1.775574,1.686291,1.814249,1.730679,0.410156,...,0.557664,0.598704,0.460260,0.219767,0.012624,0.187169,0.021207,0.200311,0.000006,fail
4,0.731889,2.057744,1.077371,2.421388,2.982174,3.068769,2.109689,1.720433,1.727737,0.625885,...,0.653016,0.659688,0.573214,0.296415,0.019312,0.286182,0.021199,0.248664,0.000009,fail
5,0.700429,1.137083,0.985431,1.767511,2.430641,2.706310,2.381406,2.173463,2.176306,0.413726,...,0.714643,0.799236,0.636737,0.300840,0.019513,0.287283,0.027453,0.288878,0.000009,fail
6,0.695354,1.517004,0.761822,1.600697,1.973946,2.211581,2.270288,2.171662,1.943804,0.499904,...,0.624740,0.640971,0.477457,0.264585,0.015579,0.226106,0.023394,0.245141,0.000007,fail
7,0.630586,1.160780,0.669065,1.728825,2.403276,2.522720,1.937926,2.076922,1.919394,0.475318,...,0.571300,0.611668,0.424445,0.208207,0.016743,0.236069,0.021848,0.198803,0.000008,fail
8,0.672059,1.638195,0.898776,1.796527,2.484059,2.594346,1.980103,1.962783,1.796941,0.576610,...,0.607414,0.620865,0.525314,0.269882,0.016407,0.243812,0.020130,0.214838,0.000008,fail
9,0.645098,1.179522,0.738318,1.286495,2.173015,2.444644,2.506130,1.976466,1.553263,0.396782,...,0.631362,0.592624,0.477898,0.218284,0.020401,0.288283,0.021695,0.258596,0.000008,fail
10,0.397423,0.600390,0.601205,1.373950,1.432846,1.396797,0.893267,0.938194,1.117671,0.283218,...,0.325188,0.392702,0.295387,0.137722,0.010314,0.153054,0.012905,0.118806,0.000004,pass
11,0.289356,0.955264,0.745673,1.000343,1.796919,1.988428,1.503345,0.988093,1.061761,0.346966,...,0.488068,0.409761,0.388726,0.181452,0.013079,0.202279,0.013477,0.179485,0.000006,pass
12,0.356918,0.838659,0.546500,0.896453,1.125818,1.280002,1.571830,1.208983,0.984917,0.267080,...,0.406372,0.363966,0.333583,0.184149,0.012580,0.181171,0.012825,0.158119,0.000005,pass
13,0.384869,1.120241,0.289257,1.518611,1.495358,1.661211,1.760945,1.970373,2.155699,0.524101,...,0.589263,0.589853,0.457286,0.244274,0.013243,0.184374,0.023548,0.220156,0.000006,pass
14,0.530564,1.179004,0.981765,1.775415,2.020349,2.198939,1.968213,1.645776,1.483815,0.443078,...,0.663550,0.632157,0.535763,0.246758,0.016454,0.249974,0.019563,0.231583,0.000007,pass
15,0.255100,0.912289,0.709125,1.590199,1.932905,2.080841,1.741602,1.914765,1.944897,0.512003,...,0.645435,0.675871,0.553478,0.278622,0.013016,0.203656,0.021453,0.211606,0.000007,pass
16,0.442447,0.861063,0.852684,2.023414,1.424981,1.523288,1.680678,1.491599,1.522629,0.384180,...,0.538869,0.599361,0.521545,0.268340,0.016059,0.235913,0.021167,0.230084,0.000005,pass
17,0.431506,0.819997,0.743111,1.381909,2.232025,2.477764,1.974492,2.015619,1.781000,0.505370,...,0.720291,0.732790,0.618999,0.283181,0.016080,0.243540,0.021580,0.234169,0.000008,pass
18,0.281273,0.868756,0.630521,1.702060,1.925072,2.049814,1.605795,1.394561,1.405159,0.435505,...,0.572120,0.512558,0.484789,0.223729,0.012913,0.194899,0.017092,0.199575,0.000006,pass
19,0.576335,1.036674,0.848760,1.151096,1.588643,1.688228,1.566503,1.237122,1.229988,0.355791,...,0.440163,0.407808,0.381434,0.183970,0.014459,0.217160,0.014724,0.161556,0.000006,pass

BARINEL SCORES

,ry 23,ry 22,ry 12,ry 11,ry 10,cx 16,ry 13,cx 15,ry 2,cx 18,...,ry 1,ry 4,ry 14,h 3,cx 8,ry 20,ry 5,ry 21,cx 6,cx 9
sum,0.608462,0.595266,0.589141,0.588612,0.587856,0.580109,0.578326,0.570462,0.570134,0.566167,...,0.551218,0.551134,0.545892,0.544077,0.543641,0.539151,0.535493,0.533347,0.532331,0.473871

TARANTULA SCORES

,ry 23,ry 22,ry 12,ry 11,ry 10,cx 16,ry 13,cx 15,ry 2,cx 18,...,ry 1,ry 4,ry 14,h 3,cx 8,ry 20,ry 5,ry 21,cx 6,cx 9
sum,0.608462,0.595266,0.589141,0.588612,0.587856,0.580109,0.578326,0.570462,0.570134,0.566167,...,0.551218,0.551134,0.545892,0.544077,0.543641,0.539151,0.535493,0.533347,0.532331,0.473871

DSTAR SCORES

,cx 18,ry 19,cx 16,cx 17,cx 15,ry 20,ry 22,ry 21,ry 13,cx 7,...,ry 14,ry 5,h 3,ry 1,cx 9,ry 2,ry 4,ry 0,ry 11,ry 12
sum,20.221521,17.991451,16.866532,16.729428,15.412435,11.646923,9.52373,3.721291,3.190196,2.993437,...,1.692262,0.541355,0.503782,0.477846,0.429875,0.005496,0.00284,5.781007e-10,1.242988e-10,2.922869e-11

ERROR GATE LOCATION:
3
Now evolving the following mutant:  AddGate_rxx_inGap_12_.qasm

100%|██████████| 10/10 [00:20<00:00,  2.01s/it]
100%|██████████| 10/10 [00:19<00:00,  1.98s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.491479,0.715547,0.831093,1.423767,2.059191,2.276829,1.991201,2.371765,2.371690,0.515499,...,0.247430,0.690895,0.753290,0.580685,0.265452,0.017215,0.024898,0.247928,0.000008,fail
1,0.728300,1.259263,0.893284,1.482555,2.203621,2.359478,2.038109,1.912940,1.462067,0.362605,...,0.324344,0.555640,0.574738,0.437714,0.186306,0.018949,0.018192,0.175206,0.000007,fail
2,0.638173,1.500554,0.797816,2.274141,1.952753,2.016758,1.836795,1.839520,1.795475,0.491142,...,0.193739,0.581414,0.624233,0.465340,0.225828,0.016008,0.020345,0.195622,0.000006,fail
3,0.389711,0.986700,0.533299,0.964046,1.408998,1.688722,1.957925,1.865511,2.039956,0.502153,...,0.211335,0.560166,0.587921,0.471389,0.232698,0.015525,0.019420,0.243280,0.000007,fail
4,0.625105,1.037890,0.996423,2.035410,2.085347,2.203484,1.905899,1.946044,2.263078,0.568412,...,0.334581,0.719889,0.758003,0.572451,0.234011,0.019670,0.025313,0.247839,0.000007,fail
5,0.572883,1.317356,0.847916,1.348954,1.456048,1.587100,1.520044,1.351711,1.560457,0.294936,...,0.176652,0.440891,0.493810,0.371893,0.184476,0.013681,0.016230,0.179810,0.000005,fail
6,0.574997,0.825615,0.614009,1.660378,1.374944,1.454926,1.456340,1.441613,1.657065,0.319221,...,0.216109,0.455111,0.536976,0.405090,0.193351,0.014119,0.018497,0.181021,0.000005,fail
7,0.564988,1.173075,0.990711,1.706468,2.300306,2.508229,2.096322,1.973009,2.353235,0.497633,...,0.280925,0.707446,0.767158,0.639213,0.318195,0.019409,0.023756,0.284958,0.000009,fail
8,0.530343,1.476949,0.807620,1.789669,2.357028,2.515343,1.962087,2.045998,2.285853,0.536622,...,0.195929,0.673600,0.682586,0.492279,0.252844,0.015546,0.022796,0.237464,0.000008,fail
9,0.409001,1.375928,0.987786,1.633668,2.129173,2.407707,2.263805,2.058341,2.018351,0.540074,...,0.397594,0.764809,0.794823,0.691799,0.306041,0.019934,0.025050,0.274176,0.000008,fail
10,0.413192,0.777492,0.607322,1.345601,1.827554,1.924830,1.336223,1.394536,1.293883,0.371503,...,0.202282,0.417482,0.484178,0.356696,0.167403,0.013273,0.015475,0.146406,0.000005,pass
11,0.420432,1.212615,0.741260,1.728992,1.817342,1.988125,2.032471,2.112965,1.976631,0.596986,...,0.250928,0.667267,0.688079,0.581600,0.303367,0.016221,0.022300,0.233772,0.000007,pass
12,0.462924,1.073747,0.705161,1.615149,1.745017,1.821875,1.506170,1.186119,1.004590,0.304125,...,0.256354,0.456438,0.446098,0.406442,0.187811,0.013830,0.013772,0.145960,0.000005,pass
13,0.401693,0.745130,0.509779,1.291205,1.281557,1.526460,1.967286,1.779024,1.530293,0.488962,...,0.253689,0.567822,0.584852,0.507516,0.259369,0.014782,0.019115,0.231231,0.000006,pass
14,0.233338,0.731942,0.490795,0.928828,0.785527,0.904151,1.121630,1.081047,1.218817,0.312457,...,0.171522,0.422498,0.407609,0.327388,0.164346,0.007875,0.013394,0.146848,0.000004,pass
15,0.321412,0.605149,0.507718,0.837771,1.540474,1.670462,1.347093,1.156432,1.108080,0.247199,...,0.169223,0.398615,0.377597,0.317403,0.149487,0.011650,0.011865,0.141215,0.000005,pass
16,0.570871,1.222509,0.704627,1.560679,1.878498,2.060000,1.929359,1.795092,1.561169,0.484661,...,0.192603,0.575387,0.535636,0.410597,0.190235,0.015342,0.018312,0.190865,0.000006,pass
17,0.324756,1.037459,0.511184,1.196717,1.654245,1.826706,1.620640,1.338653,1.281502,0.361055,...,0.197377,0.467081,0.422564,0.390334,0.216595,0.011989,0.014778,0.166417,0.000005,pass
18,0.355135,0.921976,0.696543,1.457268,1.208039,1.261325,1.072828,1.066889,1.273700,0.347847,...,0.219069,0.410042,0.459830,0.351067,0.157618,0.010816,0.014620,0.147743,0.000005,pass
19,0.355706,0.865263,0.691813,1.264600,2.128669,2.434966,2.214365,2.502140,2.302282,0.541464,...,0.237214,0.794007,0.770666,0.523454,0.231427,0.016221,0.024670,0.255349,0.000009,pass

BARINEL SCORES

,rxx 11,ry 23,ry 13,cx 15,ry 21,ry 3,ry 2,cx 6,ry 22,ry 0,...,cx 5,cx 16,ry 19,ry 10,cx 18,cx 8,cx 7,ry 4,cx 17,ry 14
sum,0.596828,0.588738,0.588341,0.576492,0.57375,0.563,0.560339,0.559419,0.559332,0.559294,...,0.551361,0.549585,0.549163,0.548428,0.546825,0.545294,0.542962,0.541965,0.540943,0.532934

TARANTULA SCORES

,rxx 11,ry 23,ry 13,cx 15,ry 21,ry 3,ry 2,cx 6,ry 22,ry 0,...,cx 5,cx 16,ry 19,ry 10,cx 18,cx 8,cx 7,ry 4,cx 17,ry 14
sum,0.596828,0.588738,0.588341,0.576492,0.57375,0.563,0.560339,0.559419,0.559332,0.559294,...,0.551361,0.549585,0.549163,0.548428,0.546825,0.545294,0.542962,0.541965,0.540943,0.532934

DSTAR SCORES

,cx 18,cx 15,ry 19,cx 16,cx 17,ry 20,ry 22,ry 21,ry 13,cx 6,...,ry 14,cx 8,ry 4,ry 1,rxx 11,ry 2,ry 3,ry 0,ry 10,ry 12
sum,16.112264,15.980088,14.441176,13.917449,13.847482,11.465697,7.094289,4.261316,3.300807,2.847144,...,1.523957,0.547262,0.478578,0.435436,0.351731,0.004525,0.002854,5.084416e-10,1.010211e-10,2.410938e-11

ERROR GATE LOCATION:
11
Now evolving the following mutant:  AddGate_x_inGap_8_.qasm

100%|██████████| 10/10 [00:22<00:00,  2.27s/it]
100%|██████████| 10/10 [00:19<00:00,  1.98s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,x 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.507960,1.229490,0.967373,1.370333,1.890738,2.076994,1.958955,1.657756,1.417087,0.418439,...,0.555236,0.063225,0.551894,0.449805,0.229798,0.015088,0.017800,0.191337,0.000006,fail
1,0.688712,1.175727,0.840976,1.658604,1.895045,2.018370,1.822970,1.589305,1.477304,0.373422,...,0.472893,0.053921,0.501695,0.388712,0.196602,0.016780,0.016962,0.182639,0.000006,fail
2,0.552490,1.068668,0.613924,1.188862,2.014398,2.259185,1.925231,1.835197,1.825665,0.518156,...,0.554237,0.049399,0.604958,0.455460,0.209678,0.016742,0.020320,0.221258,0.000007,fail
3,0.485540,1.134936,0.642503,2.035050,2.376801,2.575992,2.417829,2.540665,2.520876,0.648547,...,0.810441,0.058334,0.822821,0.592352,0.271790,0.021003,0.027217,0.279978,0.000009,fail
4,0.516665,1.674476,1.128514,2.052379,1.478739,1.627077,2.211563,1.652783,1.664947,0.506505,...,0.716623,0.063970,0.610057,0.522366,0.267892,0.015587,0.020596,0.249667,0.000006,fail
5,0.480581,1.183084,0.781661,2.207985,1.669258,1.834576,2.225906,1.854947,1.734600,0.503393,...,0.709122,0.063838,0.656384,0.548308,0.270232,0.017999,0.021595,0.253471,0.000006,fail
6,0.569402,1.363989,1.015686,1.943624,1.981462,2.030135,1.514563,1.440107,1.193429,0.348331,...,0.518375,0.064150,0.507811,0.414870,0.178285,0.015322,0.014951,0.147614,0.000005,fail
7,0.541178,1.135632,1.072579,1.495815,2.485643,2.659264,2.059043,2.008558,1.836785,0.437100,...,0.700454,0.086939,0.741686,0.594284,0.266742,0.020615,0.021861,0.222996,0.000008,fail
8,0.498475,1.004843,0.689099,1.852530,2.434042,2.638119,2.326293,2.209672,2.098549,0.604620,...,0.700933,0.066056,0.675783,0.572338,0.289826,0.018501,0.022248,0.243530,0.000009,fail
9,0.413248,1.288045,1.056440,1.844962,2.990198,3.187437,2.181282,1.947247,2.169967,0.638249,...,0.776756,0.091474,0.810273,0.701292,0.332154,0.019931,0.024946,0.275613,0.000010,fail
10,0.387727,0.943610,0.985528,1.828561,2.533052,2.555737,1.347928,1.298699,1.111182,0.384805,...,0.508851,0.072629,0.496523,0.428453,0.181950,0.013751,0.014630,0.133159,0.000007,pass
11,0.528184,1.327260,0.857484,1.545873,1.395979,1.484852,1.546267,1.287982,1.325651,0.402348,...,0.510548,0.052672,0.513152,0.369080,0.170084,0.015335,0.016459,0.185828,0.000005,pass
12,0.419335,0.659066,0.536199,1.385188,1.385451,1.353672,0.915206,1.262522,1.269629,0.340820,...,0.361024,0.027414,0.448400,0.304944,0.157268,0.008915,0.014808,0.117844,0.000004,pass
13,0.301921,0.499341,0.516648,1.314609,1.164380,1.304024,1.204544,1.224194,1.377516,0.365726,...,0.422188,0.049306,0.483341,0.439222,0.219026,0.010462,0.015526,0.169797,0.000005,pass
14,0.504074,0.772641,0.698115,1.373525,1.955005,2.205276,1.999488,2.247253,2.258382,0.515944,...,0.669144,0.055980,0.774047,0.566901,0.280983,0.017827,0.025409,0.257512,0.000008,pass
15,0.625700,1.222273,0.814735,1.528257,1.852265,2.155611,2.396179,2.214204,1.854029,0.428886,...,0.655429,0.064404,0.651043,0.531976,0.265255,0.017423,0.021436,0.232200,0.000008,pass
16,0.554133,1.544067,1.097761,1.477993,1.805258,2.038341,2.340714,2.144684,1.899350,0.422327,...,0.729140,0.066314,0.726734,0.554710,0.269058,0.018978,0.022752,0.250798,0.000007,pass
17,0.759955,1.436436,0.835348,1.357478,1.794134,2.050722,2.266560,1.823278,1.345905,0.386579,...,0.595048,0.057894,0.575073,0.450634,0.218164,0.019315,0.018053,0.211891,0.000007,pass
18,0.494456,1.271804,0.878725,2.060391,1.919873,2.069660,1.923727,2.097260,2.094743,0.546186,...,0.712141,0.051593,0.698352,0.503076,0.242700,0.017280,0.021989,0.235725,0.000008,pass
19,0.537605,1.429844,0.997228,1.899328,1.967723,1.995018,1.397217,1.373266,1.348310,0.400079,...,0.499188,0.069930,0.570939,0.459398,0.192984,0.014201,0.018111,0.159761,0.000006,pass

BARINEL SCORES

,ry 19,cx 18,ry 14,cx 17,ry 10,x 7,cx 9,ry 1,ry 0,ry 3,...,cx 15,ry 13,ry 20,cx 16,ry 22,ry 2,cx 6,ry 12,ry 21,ry 23
sum,0.544156,0.543854,0.54369,0.543519,0.538856,0.537891,0.537637,0.537132,0.536857,0.53637,...,0.530371,0.529306,0.52811,0.524684,0.524664,0.524296,0.521969,0.521696,0.517355,0.506808

TARANTULA SCORES

,ry 19,cx 18,ry 14,cx 17,ry 10,x 7,cx 9,ry 1,ry 0,ry 3,...,cx 15,ry 13,ry 20,cx 16,ry 22,ry 2,cx 6,ry 12,ry 21,ry 23
sum,0.544156,0.543854,0.54369,0.543519,0.538856,0.537891,0.537637,0.537132,0.536857,0.53637,...,0.530371,0.529306,0.52811,0.524684,0.524664,0.524296,0.521969,0.521696,0.517355,0.506808

DSTAR SCORES

,cx 18,ry 19,cx 17,cx 16,cx 15,ry 20,ry 22,ry 21,cx 8,cx 6,...,ry 14,cx 9,ry 4,ry 1,x 7,ry 2,ry 3,ry 0,ry 11,ry 12
sum,17.962517,16.207485,15.588646,13.014576,12.432645,12.088202,7.120153,4.259256,2.710014,2.637409,...,1.759065,0.723622,0.517744,0.430322,0.041382,0.004266,0.003105,5.348984e-10,1.013340e-10,2.375804e-11

ERROR GATE LOCATION:
7
Now evolving the following mutant:  AddGate_x_inGap_28_.qasm

100%|██████████| 10/10 [00:20<00:00,  2.05s/it]
100%|██████████| 10/10 [00:19<00:00,  1.93s/it]

,x 23,ry 22,ry 21,ry 20,ry 19,ry 18,cx 17,cx 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.493272,0.696553,1.221301,1.072573,2.306942,1.748586,1.768922,1.558202,1.354275,1.544514,...,0.318344,0.567317,0.574737,0.456034,0.201228,0.016127,0.019321,0.192830,0.000005,fail
1,0.516547,0.729418,1.388332,0.877513,1.674451,2.335196,2.481120,1.897808,1.595904,1.672507,...,0.328151,0.564276,0.640360,0.503467,0.252338,0.018366,0.021386,0.215021,0.000007,fail
2,0.395923,0.559086,1.106798,0.627049,1.549180,2.348699,2.523538,1.960993,2.302614,2.414436,...,0.158300,0.613779,0.711455,0.534907,0.269891,0.015298,0.023866,0.226890,0.000008,fail
3,0.444701,0.627965,1.243923,0.693611,1.567453,1.920493,2.056462,1.986064,1.837317,1.450948,...,0.277179,0.519127,0.549877,0.473006,0.248682,0.018130,0.017177,0.184639,0.000006,fail
4,0.444350,0.627469,1.366465,0.791129,1.377785,1.950493,2.321786,2.647827,2.381330,2.060226,...,0.332255,0.772231,0.762411,0.588540,0.287103,0.020386,0.024455,0.285348,0.000009,fail
5,0.429097,0.605931,1.401022,0.931536,1.728822,2.188504,2.419546,2.175966,1.904557,1.933675,...,0.275470,0.655462,0.702511,0.557538,0.269545,0.017382,0.023464,0.256547,0.000008,fail
6,0.417149,0.589058,1.194282,0.540721,1.266306,1.583907,1.722261,1.728255,1.700939,1.334097,...,0.142073,0.403738,0.365228,0.284676,0.134072,0.013389,0.013054,0.121228,0.000005,fail
7,0.449970,0.635405,1.284116,0.763728,1.750785,1.928886,1.987412,1.645445,1.775142,1.520314,...,0.196090,0.517532,0.525450,0.394350,0.182121,0.014682,0.016138,0.149636,0.000006,fail
8,0.412514,0.582513,1.022933,0.839658,1.632171,1.788925,2.042505,2.283809,2.422807,2.385381,...,0.294462,0.684710,0.776350,0.578998,0.267584,0.020026,0.026735,0.277145,0.000008,fail
9,0.417574,0.589658,1.283076,0.771353,1.265446,1.753318,1.880803,1.875133,1.729023,1.429496,...,0.245939,0.492199,0.503022,0.435736,0.224474,0.016036,0.016476,0.174671,0.000006,fail
10,0.300223,0.423947,0.872996,0.614710,1.281319,1.111221,1.345827,1.895542,1.818244,1.678012,...,0.205107,0.569567,0.544999,0.430638,0.204264,0.013965,0.018006,0.207748,0.000006,pass
11,0.364304,0.514436,1.029299,0.720080,1.003795,1.703985,1.957411,1.753166,1.924876,1.703794,...,0.222274,0.600611,0.595483,0.437839,0.195823,0.012991,0.018341,0.191690,0.000007,pass
12,0.272918,0.385389,0.846746,0.611926,1.100764,0.936318,0.964362,0.927737,0.959841,1.011428,...,0.184167,0.381182,0.385848,0.286781,0.132446,0.009240,0.012815,0.123483,0.000004,pass
13,0.387034,0.546533,1.200566,0.743590,1.113408,1.970469,2.245596,2.065503,1.935146,1.786538,...,0.287145,0.628128,0.667861,0.535201,0.262081,0.015685,0.020897,0.223741,0.000008,pass
14,0.280616,0.396259,0.719319,0.541002,1.346318,1.225509,1.355048,1.566263,1.709522,1.912930,...,0.129485,0.521865,0.551679,0.394975,0.183459,0.013753,0.019622,0.207600,0.000005,pass
15,0.265988,0.375603,1.153981,0.988870,1.635268,2.407479,2.469670,1.475654,1.335492,1.603093,...,0.301289,0.556592,0.583973,0.536848,0.253287,0.015743,0.018305,0.195868,0.000007,pass
16,0.315547,0.445586,0.912316,0.543128,1.375202,2.044167,2.259338,2.165140,2.280708,2.013995,...,0.219268,0.649232,0.695546,0.475222,0.225664,0.016254,0.023088,0.226416,0.000007,pass
17,0.428912,0.605670,1.184038,0.860100,2.084988,2.200695,2.395850,2.001228,1.744294,1.883195,...,0.339750,0.704832,0.721577,0.574928,0.290280,0.017039,0.022480,0.254529,0.000007,pass
18,0.293246,0.414095,0.868908,0.504570,1.547871,1.093505,1.184515,1.620359,1.450118,1.199445,...,0.219900,0.491598,0.435300,0.360936,0.190572,0.012545,0.015631,0.158359,0.000004,pass
19,0.325517,0.459665,0.893160,0.602498,1.272975,1.451332,1.540299,1.444732,1.340896,1.288776,...,0.188554,0.439351,0.463871,0.339636,0.177654,0.013724,0.014387,0.159506,0.000005,pass

BARINEL SCORES

,x 23,ry 22,ry 21,ry 18,ry 3,cx 17,ry 12,ry 20,ry 19,ry 9,...,ry 10,cx 8,ry 4,cx 14,ry 2,cx 5,cx 6,ry 1,cx 7,ry 13
sum,0.577513,0.577513,0.563778,0.547663,0.54647,0.544787,0.542958,0.540248,0.539447,0.538837,...,0.531968,0.527884,0.524874,0.524602,0.523984,0.523651,0.519786,0.516739,0.510915,0.5073

TARANTULA SCORES

,ry 22,x 23,ry 21,ry 18,ry 3,cx 17,ry 12,ry 20,ry 19,ry 9,...,ry 10,cx 8,ry 4,cx 14,ry 2,cx 5,cx 6,ry 1,cx 7,ry 13
sum,0.577513,0.577513,0.563778,0.547663,0.54647,0.544787,0.542958,0.540248,0.539447,0.538837,...,0.531968,0.527884,0.524874,0.524602,0.523984,0.523651,0.519786,0.516739,0.510915,0.5073

DSTAR SCORES

,cx 17,ry 18,cx 16,cx 15,cx 14,ry 19,ry 21,ry 20,ry 12,ry 22,...,x 23,ry 13,cx 8,ry 4,ry 1,ry 2,ry 3,ry 0,ry 10,ry 11
sum,16.221449,14.614273,14.506156,13.62869,12.074061,10.934859,7.954562,3.738702,2.802024,2.675585,...,1.476927,1.227273,0.536391,0.450805,0.363451,0.00401,0.002844,4.637229e-10,1.027149e-10,2.367247e-11

ERROR GATE LOCATION:
23
Now evolving the following mutant:  AddGate_y_inGap_18_.qasm

100%|██████████| 10/10 [00:19<00:00,  1.99s/it]
100%|██████████| 10/10 [00:20<00:00,  2.02s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,y 17,cx 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.408908,1.168694,0.736315,1.410213,1.438047,1.738463,0.354188,2.163165,2.127691,1.968873,...,0.274399,0.723923,0.676015,0.520910,0.244021,0.016408,0.021338,0.255831,0.000007,fail
1,0.544376,0.827373,0.465766,1.517131,1.563003,1.679961,0.279195,1.743848,1.735450,1.425221,...,0.173484,0.438790,0.427782,0.323999,0.142383,0.013998,0.015281,0.147585,0.000005,fail
2,0.746837,1.137715,0.586891,1.840399,2.222319,2.362544,0.332073,1.986460,1.854070,1.421826,...,0.215190,0.506992,0.483564,0.391482,0.184259,0.017477,0.017370,0.168316,0.000006,fail
3,0.458241,1.192950,0.970967,1.839386,2.638698,2.857999,0.364125,2.298961,2.464825,2.296023,...,0.312214,0.816735,0.821992,0.625916,0.267333,0.019839,0.024890,0.259446,0.000010,fail
4,0.575969,1.053933,0.862720,0.990712,1.906021,2.228932,0.332168,2.189285,2.262005,2.004469,...,0.251073,0.662923,0.672610,0.497274,0.205716,0.018521,0.021121,0.232422,0.000008,fail
5,0.546946,1.391913,0.612033,2.010725,1.968974,2.217988,0.405658,2.447055,2.105575,1.615844,...,0.268389,0.692589,0.616828,0.503943,0.249752,0.018530,0.020811,0.239523,0.000007,fail
6,0.654423,1.123508,0.604510,1.735924,1.955130,2.222892,0.371549,2.356053,2.233101,1.986509,...,0.186515,0.658345,0.649205,0.472689,0.234470,0.016789,0.021526,0.249665,0.000007,fail
7,0.638210,1.186242,0.829598,1.829403,1.352409,1.505374,0.328204,1.933126,1.769555,1.893144,...,0.240722,0.637249,0.686892,0.504968,0.251943,0.016660,0.022314,0.248036,0.000005,fail
8,0.603400,1.274547,0.862341,2.271519,1.658031,1.745570,0.327035,1.983815,1.927087,1.631903,...,0.259123,0.615605,0.576781,0.423881,0.196621,0.017232,0.018872,0.192255,0.000005,fail
9,0.588045,1.279698,0.846627,2.329068,1.656108,1.765352,0.367530,2.201257,1.841241,1.547467,...,0.256510,0.613887,0.492004,0.453902,0.245730,0.016453,0.017218,0.203221,0.000006,fail
10,0.548967,1.345703,0.772748,1.994463,2.698540,2.910365,0.357530,2.326453,2.166372,2.229903,...,0.287092,0.733259,0.769979,0.573297,0.316925,0.017542,0.024183,0.271600,0.000009,pass
11,0.401355,1.074756,0.578695,1.025466,0.898109,1.063976,0.216722,1.488410,1.459496,1.449760,...,0.141348,0.443231,0.438890,0.327442,0.172756,0.010711,0.013956,0.168844,0.000005,pass
12,0.579856,1.140570,0.794773,1.981191,2.128123,2.287249,0.321773,2.058773,1.845917,1.798364,...,0.246997,0.655748,0.672819,0.528553,0.278922,0.016019,0.021188,0.233676,0.000007,pass
13,0.498544,1.829786,0.915377,1.877860,2.052642,2.156262,0.308015,1.953115,1.447403,1.418060,...,0.273573,0.572597,0.518398,0.491272,0.269244,0.015577,0.016187,0.205321,0.000007,pass
14,0.658584,1.559412,0.845210,1.808458,2.467866,2.580206,0.317677,2.033909,1.385183,1.085645,...,0.247110,0.515605,0.486034,0.392656,0.207534,0.015782,0.014428,0.178645,0.000006,pass
15,0.434671,1.004184,0.772179,1.706931,2.038139,2.113683,0.275568,1.662651,1.319926,1.102233,...,0.246942,0.498965,0.482780,0.461847,0.249116,0.014195,0.015011,0.175068,0.000006,pass
16,0.388997,0.967494,0.772076,2.017837,2.242025,2.347880,0.246682,1.582208,1.825354,2.134542,...,0.209767,0.550020,0.679296,0.541112,0.260868,0.015429,0.021933,0.214903,0.000008,pass
17,0.306749,0.815479,0.367820,1.234488,1.298935,1.342459,0.191251,1.211700,1.134787,0.828370,...,0.120749,0.342636,0.318361,0.260403,0.135109,0.010017,0.009584,0.108968,0.000003,pass
18,0.613793,1.038004,1.019746,1.596724,2.004655,2.232458,0.402154,2.228300,1.827111,1.928681,...,0.329357,0.688667,0.673311,0.555806,0.258292,0.019760,0.021860,0.268177,0.000007,pass
19,0.487754,1.087129,0.711954,1.345435,1.261371,1.421705,0.238364,1.488048,1.274711,1.257830,...,0.191195,0.477774,0.481118,0.366605,0.165891,0.013601,0.015257,0.178975,0.000005,pass

BARINEL SCORES

,cx 15,ry 11,ry 10,y 17,cx 16,ry 23,cx 14,cx 7,ry 12,ry 3,...,ry 9,cx 8,cx 5,ry 13,ry 0,cx 18,ry 22,ry 21,ry 19,ry 4
sum,0.564354,0.555017,0.553286,0.546232,0.541557,0.539594,0.538727,0.537505,0.536974,0.536306,...,0.515748,0.515162,0.511932,0.511683,0.51098,0.498392,0.495192,0.494212,0.490231,0.489813

TARANTULA SCORES

,cx 15,ry 11,ry 10,y 17,cx 16,ry 23,cx 14,cx 7,ry 12,ry 3,...,ry 9,cx 8,cx 5,ry 13,ry 0,cx 18,ry 22,ry 21,ry 19,ry 4
sum,0.564354,0.555017,0.553286,0.546232,0.541557,0.539594,0.538727,0.537505,0.536974,0.536306,...,0.515748,0.515162,0.511932,0.511683,0.51098,0.498392,0.495192,0.494212,0.490231,0.489813

DSTAR SCORES

,cx 16,cx 15,cx 18,cx 14,ry 20,ry 19,ry 22,ry 21,ry 12,cx 7,...,ry 13,y 17,cx 8,ry 1,ry 4,ry 2,ry 3,ry 0,ry 10,ry 11
sum,16.188412,16.075783,13.564004,12.54408,11.882127,11.586063,6.193697,3.101406,2.663141,2.619064,...,1.341061,0.930708,0.483319,0.401838,0.401009,0.003961,0.002912,4.413350e-10,1.190900e-10,2.579469e-11

ERROR GATE LOCATION:
17
Now evolving the following mutant:  AddGate_h_inGap_23_.qasm

100%|██████████| 10/10 [00:21<00:00,  2.15s/it]
100%|██████████| 10/10 [00:20<00:00,  2.08s/it]

,ry 23,h 22,ry 21,ry 20,ry 19,ry 18,cx 17,cx 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.541537,0.000809,0.967620,0.406413,1.313194,1.414949,1.607886,1.659494,1.430016,1.851156,...,0.216953,0.755809,0.636330,0.566367,0.293979,0.014837,0.030192,0.310982,0.000010,fail
1,0.637952,0.000952,0.797436,0.603790,1.161297,1.870055,2.024189,1.617601,1.504664,2.116521,...,0.365592,0.904423,0.881854,0.775606,0.447605,0.022573,0.037113,0.369630,0.000011,fail
2,0.557282,0.000832,0.964977,0.697068,1.479541,2.241440,2.564414,2.390825,2.208560,2.745491,...,0.450850,1.160138,1.020549,0.930484,0.530163,0.025794,0.044825,0.466743,0.000012,fail
3,0.459027,0.000685,0.963384,0.610889,1.803851,1.724647,1.771083,1.288096,1.382470,1.769756,...,0.320623,0.666053,0.664199,0.573241,0.367091,0.015495,0.025487,0.238674,0.000007,fail
4,0.545813,0.000815,1.025042,0.613924,1.458402,2.006271,2.167611,1.902393,1.991370,2.348941,...,0.351951,0.925364,0.896501,0.810006,0.435405,0.019552,0.035293,0.324420,0.000011,fail
5,0.699360,0.001044,0.972772,0.610451,1.624350,1.360652,1.498122,1.595168,1.987528,2.292450,...,0.281456,0.912695,0.978422,0.776048,0.493392,0.020747,0.036844,0.354014,0.000008,fail
6,0.644800,0.000963,0.863504,0.461913,1.000341,1.717944,1.848831,1.489025,1.387174,1.770262,...,0.313474,0.818478,0.672536,0.612274,0.359763,0.017987,0.029966,0.294220,0.000010,fail
7,0.510047,0.000762,1.050009,0.638940,1.239864,2.177217,2.306563,1.386789,1.778420,2.045429,...,0.225239,0.667952,0.795350,0.609102,0.386387,0.016501,0.029395,0.234359,0.000011,fail
8,0.540647,0.000807,0.633428,0.398266,1.032210,1.594180,1.807177,1.680072,1.726009,2.141179,...,0.228583,0.841432,0.785662,0.648191,0.385510,0.018506,0.033394,0.319999,0.000011,fail
9,0.812609,0.001213,1.228161,0.615775,1.419412,2.132809,2.399482,2.281703,2.219129,2.813069,...,0.358270,1.173751,1.082767,0.899632,0.525757,0.025787,0.043231,0.452858,0.000013,fail
10,0.717268,0.001071,0.768393,0.665490,1.784950,1.169732,1.350747,1.953462,1.794696,2.497436,...,0.394218,1.014476,0.895357,0.800349,0.396788,0.021170,0.028014,0.376515,0.000010,pass
11,0.513426,0.000767,1.169707,0.503193,0.875668,1.390029,1.655156,1.976037,1.581589,1.655378,...,0.286306,0.847009,0.654186,0.572675,0.357348,0.018840,0.025997,0.300930,0.000010,pass
12,0.468353,0.000699,0.911303,0.731658,0.744302,1.921269,2.173802,1.666868,1.808298,2.393254,...,0.373596,0.914051,0.862560,0.774477,0.410386,0.019769,0.031804,0.343954,0.000012,pass
13,0.450129,0.000672,0.826371,0.415854,0.918029,1.602557,1.870352,1.915250,1.718676,2.066517,...,0.302009,0.874841,0.709102,0.632960,0.349184,0.016423,0.026290,0.312320,0.000009,pass
14,0.610835,0.000912,0.963860,0.574783,1.211669,1.552502,1.705555,1.694901,1.500258,1.735013,...,0.264869,0.835448,0.713636,0.712340,0.392684,0.020415,0.035685,0.338382,0.000009,pass
15,0.587757,0.000878,1.097196,0.760700,1.799196,2.011850,2.142099,1.941488,1.537449,1.746847,...,0.401529,0.947580,0.755785,0.711196,0.357813,0.020414,0.028397,0.327990,0.000010,pass
16,0.375828,0.000561,0.443956,0.325285,1.040244,1.195806,1.261716,1.099533,1.225331,1.401052,...,0.230830,0.596067,0.610928,0.482306,0.320504,0.014036,0.025227,0.232519,0.000006,pass
17,0.451081,0.000673,0.941325,0.685416,1.428975,1.475961,1.565812,1.338824,1.394980,1.726971,...,0.327661,0.735941,0.682123,0.617503,0.320712,0.015868,0.020730,0.247279,0.000007,pass
18,0.461662,0.000689,0.902352,0.457289,0.897928,1.054852,1.199074,1.420284,1.296181,1.463037,...,0.181802,0.620849,0.487978,0.464940,0.244873,0.013175,0.020705,0.211151,0.000006,pass
19,0.365403,0.000546,0.770148,0.597490,1.021612,1.751053,2.038611,1.688477,1.782407,2.581907,...,0.371649,0.865088,0.909965,0.740379,0.428538,0.019467,0.025419,0.321048,0.000009,pass

BARINEL SCORES

,ry 2,ry 18,ry 23,h 22,ry 4,cx 17,ry 0,cx 6,ry 19,ry 9,...,ry 3,ry 11,ry 10,ry 21,cx 7,cx 16,cx 8,ry 20,ry 13,ry 12
sum,0.563085,0.546673,0.543254,0.543254,0.541404,0.541025,0.537622,0.536078,0.535832,0.533346,...,0.524119,0.520724,0.518464,0.518392,0.516828,0.508769,0.498281,0.497374,0.496418,0.49639

TARANTULA SCORES

,ry 2,ry 18,ry 23,h 22,ry 4,cx 17,ry 0,cx 6,ry 19,ry 9,...,ry 3,ry 11,ry 10,ry 21,cx 7,cx 16,cx 8,ry 20,ry 13,ry 12
sum,0.563085,0.546673,0.543254,0.543254,0.541404,0.541025,0.537622,0.536078,0.535832,0.533346,...,0.524119,0.520724,0.518464,0.518392,0.516828,0.508769,0.498281,0.497374,0.496418,0.49639

DSTAR SCORES

,cx 14,cx 17,ry 18,cx 15,cx 16,ry 19,ry 21,ry 9,cx 7,cx 6,...,ry 20,ry 4,ry 1,cx 8,ry 2,ry 3,h 22,ry 0,ry 10,ry 11
sum,16.37857,14.8283,13.241612,12.102256,11.199964,8.430286,4.767934,4.294632,4.268174,4.096737,...,2.036405,1.314625,0.870672,0.737808,0.011641,0.003843,0.000008,1.061660e-09,2.167660e-10,5.695756e-11

ERROR GATE LOCATION:
22
Now evolving the following mutant:  AddGate_x_inGap_12_.qasm

100%|██████████| 10/10 [00:21<00:00,  2.14s/it]
100%|██████████| 10/10 [00:20<00:00,  2.03s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.474626,1.104331,0.862875,1.860784,1.332936,1.417371,1.603301,1.594932,1.643560,0.514923,...,0.285999,0.564442,0.606958,0.518957,0.266094,0.014571,0.019168,0.206023,0.000006,fail
1,0.372583,0.938713,0.736878,1.259676,1.244295,1.412688,1.608465,1.696492,1.787117,0.413873,...,0.220925,0.548263,0.541103,0.469886,0.207128,0.014197,0.018136,0.199929,0.000006,fail
2,0.542771,1.288813,0.980438,1.891906,2.239808,2.391487,2.277960,2.213739,1.801241,0.504773,...,0.272471,0.666902,0.665660,0.534140,0.245766,0.019585,0.019939,0.221121,0.000008,fail
3,0.357993,0.936462,1.044454,1.481423,1.485103,1.711178,1.902466,1.854639,1.945689,0.469827,...,0.343165,0.663081,0.734856,0.587435,0.257167,0.017893,0.023524,0.267181,0.000007,fail
4,0.551139,1.325686,0.900635,1.896829,1.510969,1.703783,2.007107,1.568112,1.650048,0.486010,...,0.229047,0.623910,0.575353,0.468342,0.225413,0.015451,0.019010,0.237241,0.000007,fail
5,0.566408,1.100909,0.877959,1.495509,1.622328,1.725145,1.438309,1.442611,1.327693,0.328681,...,0.263416,0.476984,0.502016,0.349442,0.136403,0.016903,0.015582,0.155871,0.000005,fail
6,0.532466,1.666310,0.987044,2.180040,1.648129,1.703629,1.868655,1.661270,1.446715,0.443687,...,0.239451,0.564687,0.479926,0.460858,0.235722,0.015127,0.016022,0.173872,0.000006,fail
7,0.630594,1.698459,1.029174,1.958929,1.969553,2.214519,2.596094,2.422914,2.144900,0.589834,...,0.276722,0.781641,0.742053,0.545139,0.253703,0.020564,0.023997,0.263859,0.000008,fail
8,0.494732,1.258719,0.678610,1.545468,1.682584,1.861296,1.899537,1.776880,1.716615,0.581765,...,0.205161,0.631076,0.569137,0.454482,0.203166,0.016024,0.018530,0.215807,0.000007,fail
9,0.709478,1.259205,1.007089,1.769345,2.447556,2.722549,2.613966,2.460430,2.413189,0.627855,...,0.362589,0.811455,0.887631,0.724363,0.349094,0.021728,0.028370,0.302552,0.000009,fail
10,0.625752,1.638910,0.852991,2.434840,1.770463,1.891241,2.140570,1.947089,1.629079,0.539186,...,0.278189,0.674058,0.671497,0.584682,0.306606,0.017823,0.021151,0.242215,0.000007,pass
11,0.506437,0.998234,0.707486,1.193312,1.698252,1.922691,1.920191,1.696399,1.945276,0.538420,...,0.283058,0.582382,0.648441,0.553950,0.299603,0.014635,0.021971,0.242221,0.000007,pass
12,0.316392,0.510255,0.530926,0.542943,1.213177,1.393031,1.122279,1.284647,1.466890,0.330142,...,0.152765,0.387205,0.421717,0.323045,0.145804,0.010222,0.013344,0.151345,0.000006,pass
13,0.398132,1.086142,0.799200,1.275001,1.870235,2.056774,1.605192,1.225253,1.184857,0.282598,...,0.254735,0.513524,0.483537,0.394597,0.206483,0.011183,0.014368,0.165048,0.000005,pass
14,0.580499,1.666669,0.833452,1.607870,1.773972,1.872703,1.576675,1.184866,1.147403,0.399859,...,0.247850,0.479949,0.498310,0.406442,0.244923,0.013131,0.016027,0.168366,0.000005,pass
15,0.500215,1.094177,0.897746,1.609186,1.857283,2.001685,1.833682,1.670072,1.394257,0.412453,...,0.282858,0.581511,0.592853,0.484107,0.228338,0.014683,0.018020,0.191066,0.000007,pass
16,0.484946,0.924104,0.804855,1.363312,2.101804,2.269774,1.954584,1.548131,1.267040,0.444726,...,0.319958,0.569514,0.581415,0.501022,0.254181,0.014963,0.018400,0.198722,0.000006,pass
17,0.472431,1.125454,0.680385,1.038388,1.277501,1.386169,1.280364,0.940701,0.947436,0.230936,...,0.158682,0.341193,0.358062,0.276926,0.152664,0.010634,0.011371,0.139770,0.000004,pass
18,0.447899,0.782587,0.948928,1.312282,1.929111,2.224992,2.222341,1.737550,2.013795,0.526196,...,0.358650,0.739512,0.731679,0.620762,0.292397,0.016127,0.024381,0.286185,0.000009,pass
19,0.599167,0.796427,0.582244,1.560695,1.542184,1.541868,1.292799,1.593404,1.540389,0.348346,...,0.150406,0.416568,0.487168,0.321968,0.154599,0.014022,0.016483,0.143899,0.000005,pass

BARINEL SCORES

,ry 12,cx 16,ry 3,ry 20,cx 15,ry 14,ry 13,cx 7,ry 21,ry 10,...,ry 2,cx 6,x 11,cx 5,ry 9,cx 8,ry 23,ry 4,cx 18,ry 19
sum,0.563422,0.557636,0.555934,0.554385,0.551528,0.550386,0.54666,0.545061,0.543807,0.543475,...,0.53542,0.535232,0.534893,0.53369,0.52589,0.52042,0.514802,0.510081,0.504044,0.502181

TARANTULA SCORES

,ry 12,cx 16,ry 3,ry 20,cx 15,ry 14,ry 13,cx 7,ry 21,ry 10,...,ry 2,cx 6,x 11,cx 5,ry 9,cx 8,ry 23,ry 4,cx 18,ry 19
sum,0.563422,0.557636,0.555934,0.554385,0.551528,0.550386,0.54666,0.545061,0.543807,0.543475,...,0.53542,0.535232,0.534893,0.53369,0.52589,0.52042,0.514802,0.510081,0.504044,0.502181

DSTAR SCORES

,cx 17,cx 16,cx 15,ry 20,cx 18,ry 19,ry 22,ry 21,cx 7,cx 6,...,ry 9,cx 8,ry 4,ry 1,x 11,ry 2,ry 3,ry 0,ry 10,ry 12
sum,14.57097,14.072418,13.02467,12.560558,12.458878,10.921973,7.670878,4.700242,2.623404,2.568657,...,1.650091,0.583345,0.460927,0.421927,0.029617,0.004021,0.00292,4.770882e-10,9.759705e-11,2.377592e-11

ERROR GATE LOCATION:
11
Now evolving the following mutant:  AddGate_h_inGap_22_.qasm

100%|██████████| 10/10 [00:20<00:00,  2.09s/it]
100%|██████████| 10/10 [00:20<00:00,  2.04s/it]

,ry 23,ry 22,h 21,ry 20,ry 19,ry 18,cx 17,cx 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.581483,1.299908,0.264682,0.392124,0.998949,1.920202,2.192733,2.056481,2.554496,2.590733,...,0.194419,0.806674,0.888403,0.812786,0.299515,0.020991,0.026808,0.251245,0.000015,fail
1,0.707912,1.397325,0.370826,0.709536,1.647505,1.401537,1.528504,1.747969,2.319941,2.390768,...,0.246349,0.767214,0.826067,0.704546,0.301869,0.020352,0.023767,0.288218,0.000010,fail
2,0.547779,1.415225,0.316686,0.593812,1.877790,1.605965,1.610222,1.473013,1.880391,1.947049,...,0.299681,0.650275,0.748952,0.675462,0.281451,0.019401,0.019331,0.223805,0.000012,fail
3,0.524454,1.120263,0.231682,0.661523,1.232232,1.210020,1.472066,1.808578,1.967702,2.061678,...,0.419311,0.788471,0.907779,0.786115,0.331101,0.021100,0.028914,0.254326,0.000010,fail
4,0.461509,1.141798,0.211742,0.483462,1.745365,1.471277,1.560880,1.637475,2.054947,2.303046,...,0.303640,0.731307,0.850702,0.708056,0.305971,0.021480,0.027442,0.293241,0.000011,fail
5,0.690504,1.453166,0.431472,0.509299,1.507849,2.221239,2.475377,2.407349,3.186082,3.535673,...,0.206385,0.933815,1.123678,0.892781,0.363027,0.023307,0.028160,0.347380,0.000015,fail
6,0.552632,1.570925,0.323105,0.734145,1.628925,2.055051,2.206448,1.860907,2.582323,2.483205,...,0.426191,0.973565,0.968193,0.893072,0.418202,0.021618,0.037745,0.359001,0.000013,fail
7,0.494235,1.498499,0.320933,0.606012,1.661180,1.853782,2.070666,2.084888,2.598075,2.515770,...,0.445194,0.970929,1.045822,0.925899,0.404400,0.023132,0.035571,0.314321,0.000013,fail
8,0.658903,1.184304,0.229880,0.670646,1.611421,1.922269,2.025646,1.522022,1.956940,1.695537,...,0.376910,0.711045,0.746219,0.660406,0.265852,0.020568,0.027555,0.217922,0.000011,fail
9,0.631755,1.348805,0.337761,0.690272,1.456280,1.375339,1.739622,2.357738,2.448539,2.713411,...,0.374794,0.902645,1.057173,0.877140,0.362255,0.024085,0.029875,0.332158,0.000012,fail
10,0.562804,1.255012,0.346445,0.436439,1.777651,1.765488,1.799463,1.325247,1.616228,1.374146,...,0.252487,0.588148,0.580980,0.564834,0.289773,0.015081,0.019944,0.241128,0.000007,pass
11,0.722626,1.132984,0.276698,0.626141,1.504319,1.547359,1.718482,1.927103,2.420769,2.324263,...,0.344209,0.804161,0.886665,0.730523,0.303615,0.024011,0.030478,0.287880,0.000010,pass
12,0.515429,1.107849,0.266572,0.729764,1.496594,2.127559,2.349191,1.814591,2.310700,2.232938,...,0.439662,0.899007,0.929610,0.840630,0.423719,0.020539,0.035599,0.333315,0.000012,pass
13,0.619622,1.271053,0.356690,0.797947,1.676676,1.269500,1.388947,1.630512,2.091513,2.135998,...,0.332789,0.786834,0.801141,0.705484,0.304492,0.016500,0.031798,0.269642,0.000009,pass
14,0.337420,1.195733,0.239409,0.564372,1.451473,1.507992,1.586597,1.412632,1.841781,1.730552,...,0.339400,0.665578,0.663212,0.626210,0.304588,0.016800,0.023120,0.283983,0.000011,pass
15,0.313779,0.445962,0.091766,0.361962,0.641705,0.930410,1.168832,1.386205,1.612778,1.660695,...,0.195394,0.519540,0.588300,0.428418,0.198613,0.012874,0.019046,0.224544,0.000006,pass
16,0.578609,1.533628,0.378414,0.540475,1.353445,1.693908,1.898402,1.902061,2.747877,2.451476,...,0.315114,0.891250,0.870512,0.758871,0.367391,0.019569,0.032092,0.391955,0.000014,pass
17,0.431681,1.202166,0.243850,0.777899,1.478984,1.553856,1.615488,1.370068,1.749366,1.583767,...,0.401421,0.727210,0.729937,0.672948,0.303180,0.017712,0.029290,0.229169,0.000010,pass
18,0.315418,1.324270,0.237565,0.552732,1.478872,1.622087,1.654445,1.167008,1.787348,1.813468,...,0.341356,0.695392,0.711069,0.614644,0.272784,0.015922,0.024352,0.258954,0.000011,pass
19,0.520056,1.151328,0.290676,0.563681,1.284276,1.612681,1.707848,1.533738,2.235634,2.041648,...,0.263420,0.689546,0.674400,0.606193,0.283511,0.019155,0.023911,0.277358,0.000010,pass

BARINEL SCORES

,ry 10,ry 13,cx 14,ry 0,cx 6,cx 16,ry 3,cx 5,ry 9,ry 23,...,h 21,ry 4,ry 18,ry 19,ry 2,ry 12,ry 11,ry 1,cx 8,ry 20
sum,0.567808,0.564266,0.556072,0.552962,0.552027,0.550649,0.548034,0.547895,0.546011,0.543354,...,0.526937,0.52208,0.521517,0.520729,0.514003,0.513709,0.507695,0.507367,0.505187,0.504142

TARANTULA SCORES

,ry 10,ry 13,cx 14,ry 0,cx 6,cx 16,ry 3,cx 5,ry 9,ry 23,...,h 21,ry 4,ry 18,ry 19,ry 2,ry 12,ry 11,ry 1,cx 8,ry 20
sum,0.567808,0.564266,0.556072,0.552962,0.552027,0.550649,0.548034,0.547895,0.546011,0.543354,...,0.526937,0.52208,0.521517,0.520729,0.514003,0.513709,0.507695,0.507367,0.505187,0.504142

DSTAR SCORES

,cx 14,cx 15,cx 16,cx 17,ry 18,ry 19,ry 22,cx 6,cx 7,cx 5,...,ry 23,ry 4,cx 8,h 21,ry 1,ry 2,ry 3,ry 0,ry 10,ry 11
sum,20.015224,18.234236,14.109056,13.260197,11.324192,9.781309,8.342779,4.815393,3.928419,3.805984,...,2.295041,0.851475,0.819873,0.725491,0.648832,0.007919,0.004585,1.509109e-09,2.003786e-10,3.937738e-11

ERROR GATE LOCATION:
21
Now evolving the following mutant:  AddGate_ry_inGap_28_.qasm

100%|██████████| 10/10 [00:21<00:00,  2.17s/it]
100%|██████████| 10/10 [00:20<00:00,  2.00s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,ry 18,cx 17,cx 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.658403,0.464867,0.805277,0.613481,1.793467,1.895237,2.026749,1.728526,1.830101,2.137551,...,0.362053,0.879584,0.886420,0.762676,0.447561,0.020466,0.034419,0.337822,0.000010,fail
1,0.799876,0.564755,0.692744,0.593273,1.431613,1.943807,2.073378,1.520104,1.541256,2.270609,...,0.422231,0.923426,0.919018,0.798710,0.445076,0.021126,0.036471,0.370704,0.000011,fail
2,0.691411,0.488173,0.674416,0.461153,1.469282,1.373595,1.509184,1.576663,1.814116,2.469624,...,0.269818,0.862784,0.936164,0.708972,0.498426,0.020684,0.039905,0.386449,0.000010,fail
3,0.626858,0.442595,0.930717,0.401650,1.215426,1.893096,1.995002,1.495528,1.591463,1.875649,...,0.244268,0.788641,0.782609,0.653103,0.428824,0.020701,0.032181,0.283795,0.000009,fail
4,0.847866,0.598638,1.137483,0.681878,1.392329,1.207918,1.367410,1.764983,1.383386,1.902672,...,0.405955,0.969955,0.817207,0.755434,0.439707,0.022752,0.035684,0.395889,0.000010,fail
5,0.574376,0.405540,0.800103,0.596071,1.496350,1.546253,1.572421,1.109421,1.200515,1.618170,...,0.259264,0.626015,0.594438,0.559948,0.310301,0.015486,0.022761,0.225318,0.000007,fail
6,0.492283,0.347578,0.770661,0.593538,1.657013,1.426397,1.622530,1.751316,1.717413,2.200531,...,0.314270,0.857621,0.903822,0.732963,0.442882,0.021232,0.036212,0.373717,0.000010,fail
7,0.635506,0.448701,1.177340,0.663209,1.844121,1.732888,2.005929,2.470633,2.345121,2.557378,...,0.372451,1.117376,1.065955,0.953987,0.556732,0.023672,0.045952,0.469015,0.000012,fail
8,0.559337,0.394922,0.883627,0.601584,1.232928,2.042381,2.338510,1.987829,1.964227,2.541735,...,0.441190,1.063706,1.084907,0.881973,0.577937,0.024154,0.043414,0.436378,0.000013,fail
9,0.624539,0.440957,0.893584,0.616120,0.601802,1.243176,1.492400,1.661679,1.356222,1.647052,...,0.348770,0.776457,0.670695,0.611058,0.355670,0.018320,0.029348,0.297035,0.000010,fail
10,0.520634,0.367595,1.005882,0.640196,0.824949,1.637093,1.895053,1.812598,1.309355,1.673966,...,0.404293,0.817147,0.645455,0.611808,0.334554,0.016918,0.024618,0.309270,0.000010,pass
11,0.530158,0.374319,1.051937,0.615561,1.694340,1.880914,1.941644,1.510239,1.594111,2.152753,...,0.296307,0.782871,0.745438,0.628773,0.339102,0.016241,0.022225,0.241157,0.000010,pass
12,0.460005,0.324788,0.746339,0.490633,1.081700,0.608801,0.850566,1.536621,1.449678,1.847839,...,0.222903,0.614439,0.570022,0.517075,0.236682,0.011427,0.020960,0.250555,0.000005,pass
13,0.552193,0.389877,0.737166,0.499102,1.483779,1.432785,1.526353,1.296813,1.145180,1.797902,...,0.341953,0.749246,0.661686,0.582858,0.306741,0.015388,0.019464,0.262598,0.000008,pass
14,0.688735,0.486283,0.953887,0.748532,1.168683,1.489092,1.550329,1.334092,1.033636,1.685007,...,0.334783,0.709430,0.594146,0.596035,0.267470,0.017517,0.023593,0.249621,0.000008,pass
15,0.318189,0.224658,0.886349,0.773942,1.354869,1.597058,1.799586,1.821217,1.523307,1.920313,...,0.399837,0.853175,0.766762,0.722933,0.373497,0.019005,0.027234,0.322136,0.000009,pass
16,0.601703,0.424834,0.673439,0.631456,0.978594,1.495418,1.618615,1.314089,1.146571,1.667257,...,0.401379,0.705597,0.643753,0.585987,0.319187,0.016973,0.017149,0.232143,0.000008,pass
17,0.592033,0.418006,1.106158,0.663932,1.797488,1.880408,1.972393,1.694486,1.384364,1.993961,...,0.352148,0.858981,0.750333,0.708157,0.368644,0.018703,0.023870,0.316291,0.000009,pass
18,0.496842,0.350797,0.771777,0.555938,1.202206,1.214322,1.382382,1.619269,1.999997,2.196556,...,0.222782,0.862636,0.908567,0.703233,0.435618,0.018750,0.034841,0.328031,0.000010,pass
19,0.446441,0.315211,0.802701,0.573369,1.415689,1.038412,1.225689,1.721307,1.800099,1.846423,...,0.279510,0.779198,0.792503,0.672795,0.405181,0.017116,0.031222,0.315579,0.000008,pass

BARINEL SCORES

,ry 2,ry 4,ry 1,ry 23,ry 22,ry 3,cx 6,ry 0,ry 10,cx 5,...,cx 17,cx 14,cx 16,ry 11,ry 19,cx 8,ry 13,ry 12,ry 21,ry 20
sum,0.592409,0.570752,0.558463,0.555623,0.555623,0.553841,0.550273,0.546806,0.542161,0.539611,...,0.533183,0.530485,0.52148,0.521004,0.520858,0.513767,0.502011,0.501353,0.500866,0.484573

TARANTULA SCORES

,ry 2,ry 4,ry 1,ry 23,ry 22,ry 3,cx 6,ry 0,ry 10,cx 5,...,cx 17,cx 14,cx 16,ry 11,ry 19,cx 8,ry 13,ry 12,ry 21,ry 20
sum,0.592409,0.570752,0.558463,0.555623,0.555623,0.553841,0.550273,0.546806,0.542161,0.539611,...,0.533183,0.530485,0.52148,0.521004,0.520858,0.513767,0.502011,0.501353,0.500866,0.484573

DSTAR SCORES

,cx 14,cx 17,cx 15,cx 16,ry 18,ry 19,cx 7,cx 6,ry 21,ry 9,...,ry 20,ry 22,ry 4,ry 1,cx 8,ry 2,ry 3,ry 0,ry 10,ry 11
sum,15.646237,12.581274,11.496436,11.350871,10.951697,8.685189,4.432385,4.39244,4.101379,3.733653,...,2.093244,1.544992,1.514795,0.996981,0.892844,0.012394,0.004279,1.031226e-09,2.090041e-10,4.940956e-11

ERROR GATE LOCATION:
23
Now evolving the following mutant:  AddGate_ry_inGap_7_.qasm

100%|██████████| 10/10 [00:20<00:00,  2.06s/it]
100%|██████████| 10/10 [00:20<00:00,  2.01s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,ry 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.526735,1.026946,0.713669,1.288658,1.614486,1.782062,1.781437,1.671495,1.909955,0.361245,...,0.548033,0.623585,0.375404,0.696954,0.245734,0.015758,0.028247,0.275020,0.000007,fail
1,0.694029,1.404672,0.893255,2.111791,2.105148,2.353930,2.386518,2.287831,2.184597,0.534110,...,0.715761,0.706293,0.421848,0.763378,0.300821,0.018585,0.028714,0.308038,0.000009,fail
2,0.805589,1.605400,1.092433,2.062720,2.102871,2.098788,1.555060,1.284034,1.110378,0.328030,...,0.471304,0.491221,0.278765,0.574872,0.274924,0.015368,0.017675,0.177972,0.000006,fail
3,0.530853,1.196272,0.563679,1.423329,1.621791,1.764956,1.741892,1.636565,1.161040,0.365622,...,0.469191,0.465841,0.353679,0.524622,0.201793,0.013662,0.019586,0.195798,0.000004,fail
4,0.706831,1.984370,1.080166,2.073847,2.238747,2.385415,2.345776,2.092759,1.855903,0.469276,...,0.673246,0.693399,0.371441,0.783102,0.320064,0.021069,0.028925,0.294354,0.000008,fail
5,0.517088,1.337657,0.615219,1.845065,1.541773,1.726173,2.093057,2.097329,2.002593,0.470459,...,0.684264,0.666159,0.398016,0.692832,0.257289,0.016188,0.027340,0.279547,0.000007,fail
6,0.650187,0.888295,0.657637,1.445774,1.582452,1.775862,1.780878,1.652460,1.545019,0.287392,...,0.502657,0.526426,0.352463,0.593701,0.230176,0.013211,0.023645,0.234943,0.000007,fail
7,0.641739,1.331651,0.891815,1.220014,2.122357,2.441233,2.423130,2.367496,2.448189,0.636215,...,0.744638,0.792260,0.444986,0.813727,0.287674,0.020053,0.030609,0.334724,0.000010,fail
8,0.613354,1.087977,0.722693,1.751977,2.542975,2.633691,1.748828,1.665675,1.902729,0.395575,...,0.550252,0.610451,0.374431,0.709278,0.281478,0.016409,0.028208,0.247632,0.000008,fail
9,0.635870,1.086793,0.683402,2.040907,2.319403,2.487607,1.905232,1.902948,2.055504,0.517509,...,0.672315,0.698201,0.449853,0.769772,0.270416,0.019541,0.028145,0.293306,0.000010,fail
10,0.626947,1.327173,0.927336,1.658789,1.808525,2.004748,2.017716,1.793481,1.925006,0.471643,...,0.658241,0.666963,0.358103,0.705931,0.280425,0.017317,0.025880,0.292859,0.000008,pass
11,0.576696,1.342836,0.880124,1.595155,1.463123,1.662668,2.070027,1.857390,1.706479,0.498157,...,0.646229,0.607639,0.317310,0.588552,0.241220,0.014820,0.020391,0.238333,0.000007,pass
12,0.599299,1.188097,1.022153,1.676969,1.526472,1.717645,2.260898,1.926471,1.337809,0.356543,...,0.596331,0.623675,0.387272,0.707898,0.292978,0.019018,0.021926,0.251957,0.000007,pass
13,0.670008,1.349192,1.064277,1.876672,2.426346,2.623619,2.543208,2.153458,1.637929,0.428035,...,0.714002,0.680350,0.349287,0.789106,0.347536,0.021753,0.025989,0.291418,0.000009,pass
14,0.325103,0.963498,0.710494,1.412879,1.500722,1.622019,1.574205,1.888481,1.603477,0.471027,...,0.521993,0.514503,0.249929,0.444695,0.152355,0.011030,0.015750,0.165400,0.000006,pass
15,0.236224,0.638655,0.307793,0.758219,0.910911,0.917029,0.651263,0.633955,0.416452,0.174162,...,0.184464,0.166264,0.108381,0.167589,0.062637,0.005022,0.005293,0.052800,0.000002,pass
16,0.761543,1.483589,0.963560,1.688685,2.277336,2.460885,2.214367,1.738055,1.397914,0.406278,...,0.634968,0.592070,0.351646,0.663000,0.316405,0.016413,0.020958,0.228753,0.000008,pass
17,0.366176,0.919410,0.697927,1.840230,1.029639,0.983471,0.861339,0.754379,0.728911,0.204639,...,0.310847,0.335611,0.185406,0.322042,0.123034,0.006802,0.010390,0.105204,0.000003,pass
18,0.346607,0.880599,0.427013,1.418070,0.997604,1.170089,1.712376,1.654419,1.549756,0.391421,...,0.563964,0.554360,0.329782,0.490777,0.161821,0.009987,0.020615,0.226499,0.000005,pass
19,0.450704,1.611048,0.890803,1.682132,2.599370,2.824601,2.434052,2.151959,1.701118,0.602790,...,0.710515,0.626928,0.372064,0.668548,0.256423,0.019815,0.021138,0.250909,0.000009,pass

BARINEL SCORES

,ry 2,ry 13,cx 15,ry 23,ry 6,ry 1,cx 5,ry 0,ry 19,ry 3,...,cx 7,cx 16,ry 12,ry 22,ry 20,ry 14,cx 8,cx 9,cx 17,ry 21
sum,0.580951,0.569547,0.564807,0.560407,0.559422,0.556601,0.555095,0.550682,0.544753,0.544688,...,0.538888,0.529913,0.526866,0.525268,0.525193,0.521549,0.521174,0.519656,0.518665,0.500711

TARANTULA SCORES

,ry 2,ry 13,cx 15,ry 23,ry 6,ry 1,cx 5,ry 0,ry 19,ry 3,...,cx 7,cx 16,ry 12,ry 22,ry 20,ry 14,cx 8,cx 9,cx 17,ry 21
sum,0.580951,0.569547,0.564807,0.560407,0.559422,0.556601,0.555095,0.550682,0.544753,0.544688,...,0.538888,0.529913,0.526866,0.525268,0.525193,0.521549,0.521174,0.519656,0.518665,0.500711

DSTAR SCORES

,cx 18,ry 19,cx 17,cx 15,cx 16,ry 20,ry 22,ry 21,cx 5,ry 13,...,ry 14,ry 6,ry 4,ry 1,cx 9,ry 2,ry 3,ry 0,ry 11,ry 12
sum,16.439566,14.759709,13.780402,13.762366,13.11172,11.638974,7.726806,3.500599,3.081873,2.95283,...,1.360759,1.122221,0.582833,0.576386,0.518262,0.006691,0.002844,5.988079e-10,1.057834e-10,2.248111e-11

ERROR GATE LOCATION:
6
Now evolving the following mutant:  AddGate_y_inGap_19_.qasm

100%|██████████| 10/10 [00:20<00:00,  2.06s/it]
100%|██████████| 10/10 [00:20<00:00,  2.01s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,y 18,cx 17,cx 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.665698,1.534095,0.913104,1.999460,2.614470,0.524432,2.827825,2.214727,2.092084,2.074945,...,0.288631,0.699010,0.730926,0.551243,0.277224,0.017756,0.023765,0.249086,0.000009,fail
1,0.483904,1.168632,0.994447,1.418765,1.969466,0.424155,2.330372,2.566833,2.304455,2.480942,...,0.315861,0.815355,0.865623,0.629513,0.309691,0.018109,0.028390,0.324570,0.000009,fail
2,0.616730,1.627077,0.862912,1.448832,2.409512,0.448045,2.566457,1.950068,1.566136,1.226340,...,0.325379,0.554932,0.501917,0.411234,0.194614,0.015875,0.015827,0.160857,0.000007,fail
3,0.527573,1.402083,0.979206,2.077413,2.251746,0.420480,2.288328,1.716973,1.827551,1.466363,...,0.215372,0.530135,0.526257,0.419206,0.191935,0.014888,0.014746,0.144656,0.000006,fail
4,0.705335,1.378594,0.928223,1.724870,2.505218,0.497645,2.770629,2.266090,2.267390,2.122473,...,0.289821,0.739656,0.780852,0.594994,0.276173,0.019582,0.023928,0.255391,0.000009,fail
5,0.542697,1.352350,0.671978,1.851823,2.502672,0.538765,2.798460,2.504356,2.333364,2.422725,...,0.257991,0.768316,0.738864,0.567666,0.289458,0.018816,0.025150,0.283881,0.000009,fail
6,0.442076,1.095387,0.586193,1.797854,2.263426,0.451199,2.440548,2.008834,1.925992,1.753954,...,0.208384,0.608059,0.623505,0.473846,0.229665,0.014824,0.019752,0.212493,0.000007,fail
7,0.608118,1.030879,0.921522,1.211267,2.074262,0.412128,2.240335,1.729576,1.846884,1.712019,...,0.262833,0.586134,0.614270,0.439288,0.178099,0.016073,0.018388,0.186334,0.000008,fail
8,0.597377,1.329456,0.723646,1.558321,2.414474,0.492181,2.668346,2.263215,2.207916,2.021739,...,0.227589,0.685328,0.687868,0.509516,0.230912,0.017908,0.023221,0.245877,0.000008,fail
9,0.585480,0.863578,1.023655,1.621370,2.141838,0.427112,2.321176,1.818997,1.743689,1.448607,...,0.320800,0.597078,0.680981,0.508699,0.230224,0.016242,0.020119,0.208636,0.000007,fail
10,0.290580,1.070746,0.745530,1.136687,1.898923,0.392622,2.111812,1.813147,1.602246,1.699841,...,0.257147,0.569131,0.581520,0.536057,0.261897,0.013897,0.018456,0.215767,0.000007,pass
11,0.427073,0.923576,0.571307,1.428119,1.460504,0.329627,1.678736,1.804463,1.564814,1.596580,...,0.265254,0.526118,0.537887,0.476156,0.239497,0.014950,0.018531,0.210313,0.000006,pass
12,0.456634,1.530313,0.788162,1.930963,1.644975,0.297609,1.732815,1.761522,1.414853,1.274478,...,0.184842,0.555068,0.487897,0.417446,0.222637,0.015303,0.015247,0.189728,0.000005,pass
13,0.483204,1.485061,0.758703,1.263997,2.288926,0.454740,2.508304,2.293606,2.106076,1.593046,...,0.269681,0.619414,0.605464,0.468107,0.218122,0.018613,0.018761,0.192031,0.000007,pass
14,0.558127,1.245961,1.178564,1.445460,1.804327,0.365545,2.065659,2.237475,1.773249,1.807341,...,0.374242,0.711148,0.731868,0.609124,0.285090,0.019419,0.023862,0.278789,0.000008,pass
15,0.618498,1.059307,0.773189,1.854900,2.354968,0.447717,2.497184,1.929297,1.804930,1.490033,...,0.317724,0.650336,0.612836,0.529272,0.246657,0.017076,0.018979,0.195104,0.000007,pass
16,0.494815,1.458310,0.907270,1.916238,2.072129,0.397371,2.216797,2.126454,1.666185,1.585897,...,0.330969,0.718817,0.636322,0.565122,0.280052,0.017059,0.021927,0.240839,0.000007,pass
17,0.632757,1.341958,0.965804,1.972320,1.708692,0.318928,1.810433,1.654993,1.450058,1.471925,...,0.297969,0.546316,0.584003,0.446445,0.226630,0.016801,0.018943,0.197030,0.000005,pass
18,0.652969,1.568252,0.914359,2.164310,2.019473,0.374207,2.091058,2.246392,2.087445,1.527694,...,0.184151,0.603454,0.579517,0.451375,0.249654,0.016759,0.018764,0.196433,0.000006,pass
19,0.466343,1.312839,0.872607,1.616373,1.685953,0.307396,1.739799,1.462253,1.290955,1.232417,...,0.323891,0.517324,0.544697,0.468708,0.223545,0.014852,0.017154,0.169323,0.000006,pass

BARINEL SCORES

,ry 9,ry 11,y 18,cx 17,ry 0,cx 14,ry 12,ry 19,cx 15,ry 10,...,ry 1,cx 16,ry 13,ry 3,cx 5,ry 21,ry 20,ry 22,ry 4,cx 8
sum,0.575841,0.55958,0.557101,0.552509,0.551834,0.550734,0.550162,0.549995,0.545485,0.543017,...,0.521393,0.52118,0.513674,0.507977,0.50682,0.503788,0.49971,0.495845,0.495291,0.491555

TARANTULA SCORES

,ry 9,ry 11,y 18,cx 17,ry 0,cx 14,ry 12,ry 19,cx 15,ry 10,...,ry 1,cx 16,ry 13,ry 3,cx 5,ry 21,ry 20,ry 22,ry 4,cx 8
sum,0.575841,0.55958,0.557101,0.552509,0.551834,0.550734,0.550162,0.549995,0.545485,0.543017,...,0.521393,0.52118,0.513674,0.507977,0.50682,0.503788,0.49971,0.495845,0.495291,0.491555

DSTAR SCORES

,cx 17,ry 19,cx 15,cx 16,cx 14,ry 20,ry 22,ry 21,ry 12,cx 6,...,y 18,ry 13,cx 8,ry 4,ry 1,ry 2,ry 3,ry 0,ry 10,ry 11
sum,20.940333,18.514459,15.120312,15.092863,13.877661,10.446312,7.104737,4.007692,2.975493,2.866107,...,1.570524,1.456487,0.574622,0.465597,0.427045,0.004464,0.002846,6.140874e-10,1.191623e-10,2.808915e-11

ERROR GATE LOCATION:
18
Now evolving the following mutant:  AddGate_swap_inGap_12_.qasm

100%|██████████| 10/10 [00:25<00:00,  2.54s/it]
100%|██████████| 10/10 [00:24<00:00,  2.49s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.539772,1.442771,0.946604,2.001857,2.647348,2.814436,2.520924,2.409235,1.771593,0.520097,...,0.341488,0.880298,0.809106,0.654423,0.321714,0.023228,0.020619,0.254524,0.000010,fail
1,0.597200,1.070883,0.631359,1.922575,2.668016,2.875847,2.464771,2.181868,1.744488,0.506571,...,0.245746,0.861579,0.764536,0.611361,0.284678,0.023542,0.019425,0.225502,0.000009,fail
2,0.469124,1.140752,0.526773,1.642960,1.597672,1.719957,1.780063,1.521515,1.285724,0.240435,...,0.239128,0.661610,0.611132,0.427621,0.218106,0.012472,0.013952,0.156991,0.000006,fail
3,0.639234,1.507064,0.735080,1.910495,2.422392,2.597126,2.259508,2.330266,2.487513,0.600573,...,0.200851,0.860658,0.800693,0.659582,0.258034,0.020207,0.013017,0.158908,0.000010,fail
4,0.435633,1.230419,0.829433,1.754000,2.058962,2.129962,1.649976,1.501028,1.294144,0.391203,...,0.247062,0.646869,0.562032,0.477757,0.213798,0.015375,0.011981,0.142684,0.000006,fail
5,0.585684,1.591015,0.861424,1.458507,2.453967,2.755719,2.559433,2.012466,1.914423,0.468247,...,0.342350,0.928717,0.866187,0.661143,0.311953,0.022027,0.017689,0.192296,0.000010,fail
6,0.668546,1.408102,0.841725,2.059602,1.997588,2.226741,2.573369,2.437804,1.928211,0.444616,...,0.236998,0.905229,0.830326,0.606769,0.292142,0.020864,0.016564,0.203096,0.000009,fail
7,0.529097,1.391548,1.029136,1.927010,1.744753,1.978614,2.178838,1.539729,1.557566,0.430185,...,0.337362,0.782006,0.694498,0.611610,0.280700,0.020505,0.015668,0.173888,0.000009,fail
8,0.553391,1.329124,0.604442,1.720889,1.227236,1.319390,1.798495,1.706556,1.493084,0.416966,...,0.172826,0.661176,0.565456,0.562575,0.297237,0.019906,0.013407,0.167406,0.000006,fail
9,0.498756,0.826856,0.748282,1.409381,1.963405,2.205455,2.169492,2.212804,2.127359,0.513604,...,0.274841,0.792592,0.758161,0.579700,0.205941,0.017477,0.014536,0.170476,0.000009,fail
10,0.402511,0.971910,0.577598,1.787716,1.939719,2.058030,1.792137,1.955225,1.808259,0.522689,...,0.177747,0.658842,0.585789,0.584838,0.259699,0.018909,0.013034,0.167327,0.000008,pass
11,0.465007,1.046619,0.771781,1.550174,1.433578,1.395991,0.920715,0.925555,0.691595,0.252911,...,0.181609,0.340657,0.289922,0.311461,0.156449,0.011136,0.010166,0.132116,0.000004,pass
12,0.672378,1.349042,0.920220,2.082917,1.924864,2.009818,1.778194,2.013777,1.849196,0.419082,...,0.245783,0.659557,0.647206,0.569371,0.250494,0.015113,0.015139,0.188701,0.000008,pass
13,0.429630,0.903841,0.490690,1.091956,1.278953,1.405185,1.563424,1.355395,1.158237,0.306259,...,0.136400,0.558822,0.497926,0.399409,0.190518,0.015066,0.009700,0.115937,0.000006,pass
14,0.502875,0.998324,0.566331,1.252502,1.403088,1.486883,1.452139,1.276314,1.111789,0.359264,...,0.186310,0.539650,0.446120,0.419321,0.205137,0.016569,0.013118,0.153054,0.000005,pass
15,0.242645,0.713768,0.622112,1.462653,1.812098,1.903940,1.438828,1.487093,1.531198,0.401197,...,0.232593,0.596714,0.527408,0.489625,0.223239,0.013976,0.013108,0.152858,0.000006,pass
16,0.533442,0.737139,0.762981,1.090678,1.416019,1.537243,1.495906,1.414793,1.291821,0.321232,...,0.277441,0.553799,0.534874,0.437282,0.209748,0.014305,0.015983,0.173357,0.000006,pass
17,0.272630,1.293361,0.475500,1.552942,1.851561,1.938627,1.494617,1.566783,1.687072,0.508993,...,0.159384,0.598904,0.488652,0.563057,0.267641,0.018483,0.014874,0.178097,0.000006,pass
18,0.565148,1.446124,0.846800,2.240439,1.379519,1.446924,1.536970,1.675648,1.572498,0.391810,...,0.210364,0.555564,0.569640,0.516053,0.249406,0.016546,0.009864,0.131359,0.000006,pass
19,0.555302,1.544841,1.117732,2.125574,1.917799,1.986807,1.879666,1.761207,1.760477,0.495753,...,0.273286,0.734586,0.626217,0.646738,0.312159,0.020660,0.014377,0.180237,0.000008,pass

BARINEL SCORES

,cx 17,ry 9,ry 10,cx 6,cx 7,ry 0,cx 18,cx 16,ry 13,ry 19,...,ry 3,ry 2,ry 23,cx 5,ry 22,ry 1,ry 4,ry 14,ry 20,ry 21
sum,0.588485,0.587125,0.586587,0.582093,0.579245,0.574357,0.568528,0.562654,0.562076,0.559563,...,0.548884,0.548033,0.543063,0.542419,0.540378,0.539886,0.535918,0.532503,0.523054,0.52021

TARANTULA SCORES

,cx 17,ry 9,ry 10,cx 6,cx 7,ry 0,cx 18,cx 16,ry 13,ry 19,...,ry 3,ry 2,ry 23,cx 5,ry 22,ry 1,ry 4,ry 14,ry 20,ry 21
sum,0.588485,0.587125,0.586587,0.582093,0.579245,0.574357,0.568528,0.562654,0.562076,0.559563,...,0.548884,0.548033,0.543063,0.542419,0.540378,0.539886,0.535918,0.532503,0.523054,0.52021

DSTAR SCORES

,cx 17,cx 18,ry 19,cx 16,cx 15,ry 20,ry 22,cx 7,ry 21,cx 6,...,ry 14,ry 4,cx 8,ry 1,swap 11,ry 3,ry 2,ry 0,ry 10,ry 12
sum,19.012503,18.837752,16.38505,15.498409,12.668741,12.085698,7.969812,4.031886,3.505679,3.4665,...,1.46958,0.584647,0.576321,0.29438,0.252235,0.003766,0.002429,7.326097e-10,1.060120e-10,2.540010e-11

ERROR GATE LOCATION:
11
Now evolving the following mutant:  AddGate_y_inGap_25_.qasm

100%|██████████| 10/10 [00:23<00:00,  2.34s/it]
100%|██████████| 10/10 [00:19<00:00,  1.93s/it]

,ry 23,ry 22,ry 21,y 20,ry 19,ry 18,cx 17,cx 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.834132,1.692232,1.012544,0.649312,3.089830,2.530408,2.395252,1.612401,1.599249,1.152983,...,0.253661,0.518732,0.542718,0.421680,0.202953,0.017476,0.017588,0.134528,0.000006,fail
1,0.630421,1.256664,0.863308,0.552174,2.438101,2.183358,2.218297,1.779820,1.562656,1.231497,...,0.309660,0.547024,0.563031,0.494198,0.244524,0.017591,0.018255,0.177942,0.000006,fail
2,0.696870,1.732026,0.725374,0.451167,2.022794,2.182074,2.351016,2.380579,2.251541,1.737403,...,0.191584,0.643700,0.639040,0.490957,0.268843,0.018262,0.020082,0.209146,0.000006,fail
3,0.513221,1.468997,0.859842,0.542167,2.399133,2.545477,2.504933,1.517659,1.416959,1.214894,...,0.209599,0.505764,0.461840,0.389210,0.190491,0.013208,0.014088,0.125237,0.000006,fail
4,0.470717,1.035242,0.713074,0.486575,2.196986,1.807250,1.842500,1.442661,1.515529,1.548090,...,0.192786,0.534022,0.508633,0.383505,0.200905,0.011680,0.016577,0.162337,0.000006,fail
5,0.570411,1.483255,0.634621,0.388094,1.581334,2.032129,2.250541,2.092138,1.932896,1.683873,...,0.158842,0.600401,0.508821,0.420520,0.206427,0.015197,0.017424,0.197385,0.000007,fail
6,0.493526,1.061105,0.533110,0.522245,2.080694,2.051731,2.256223,2.229024,2.083172,2.244477,...,0.247761,0.688957,0.651239,0.576046,0.320376,0.017632,0.023272,0.267656,0.000007,fail
7,0.444191,1.018779,0.950326,0.450495,1.936422,1.573167,1.694227,1.691454,1.668140,1.956172,...,0.261350,0.634597,0.665980,0.547951,0.276229,0.014261,0.021717,0.236329,0.000006,fail
8,0.604943,1.142016,0.867046,0.503562,2.143873,1.779198,1.918273,2.157124,1.730157,1.396476,...,0.235519,0.595296,0.570238,0.523282,0.294271,0.017437,0.018768,0.230257,0.000005,fail
9,0.490450,1.268108,0.742807,0.491293,2.043289,2.235020,2.393553,2.231283,2.341330,1.957438,...,0.246265,0.620674,0.612204,0.544268,0.281832,0.017847,0.020359,0.208348,0.000008,fail
10,0.598002,1.400064,0.931235,0.347908,1.491624,2.433213,2.892497,3.111847,2.877749,2.336919,...,0.372581,0.912406,0.885585,0.707370,0.326877,0.021828,0.027878,0.321324,0.000011,pass
11,0.244982,0.598526,0.403588,0.212400,0.880109,1.391324,1.591285,1.336575,1.256189,1.407239,...,0.177714,0.422699,0.447232,0.390330,0.194034,0.010762,0.014522,0.169374,0.000005,pass
12,0.549408,1.859794,1.141363,0.202620,0.927126,1.991736,2.286631,2.358885,1.748987,1.351886,...,0.402631,0.701454,0.616252,0.555416,0.275197,0.018060,0.019551,0.225410,0.000008,pass
13,0.487505,1.188032,0.734268,0.452703,1.864487,2.145645,2.247141,1.782965,1.570151,1.590181,...,0.229525,0.524904,0.536384,0.447634,0.214274,0.015914,0.018362,0.200002,0.000006,pass
14,0.558502,1.884225,0.863165,0.394455,1.834665,1.892554,2.180879,2.835054,2.470234,2.086500,...,0.211688,0.749466,0.737505,0.602883,0.326776,0.018743,0.023381,0.288885,0.000009,pass
15,0.413632,1.206062,0.672009,0.456455,1.951780,1.809341,1.945008,1.966270,1.815157,1.523668,...,0.203264,0.614387,0.571463,0.458334,0.234875,0.015844,0.019085,0.211462,0.000005,pass
16,0.263196,1.208849,0.741385,0.453826,2.078526,1.665599,1.742522,1.810068,1.786349,1.430519,...,0.216138,0.655266,0.551520,0.478539,0.216223,0.014059,0.016736,0.183798,0.000006,pass
17,0.643089,1.332762,0.891729,0.465997,2.142523,2.198618,2.230037,1.799466,1.378759,1.343908,...,0.234952,0.524214,0.500852,0.410386,0.221452,0.013833,0.016951,0.172003,0.000006,pass
18,0.460566,1.730813,0.744689,0.370331,1.552403,1.963884,2.092468,1.888362,1.736427,1.618289,...,0.186589,0.553797,0.515833,0.475581,0.254878,0.013976,0.016906,0.192253,0.000007,pass
19,0.336015,0.712031,0.440479,0.248942,1.096727,1.682307,1.843823,1.538633,1.612671,1.726270,...,0.151381,0.473912,0.500500,0.364413,0.172689,0.011303,0.016898,0.171490,0.000006,pass

BARINEL SCORES

,y 20,ry 19,ry 23,ry 18,ry 21,ry 3,cx 17,ry 11,ry 4,ry 12,...,cx 14,cx 5,cx 6,cx 8,cx 7,cx 16,ry 10,ry 1,ry 0,ry 9
sum,0.582812,0.580955,0.557939,0.521769,0.510932,0.509957,0.509009,0.507847,0.505034,0.504073,...,0.495512,0.494874,0.493985,0.491538,0.489879,0.483646,0.481463,0.477132,0.473095,0.471062

TARANTULA SCORES

,y 20,ry 19,ry 23,ry 18,ry 21,ry 3,cx 17,ry 11,ry 4,ry 12,...,cx 14,cx 5,cx 6,cx 8,cx 7,cx 16,ry 10,ry 1,ry 0,ry 9
sum,0.582812,0.580955,0.557939,0.521769,0.510932,0.509957,0.509009,0.507847,0.505034,0.504073,...,0.495512,0.494874,0.493985,0.491538,0.489879,0.483646,0.481463,0.477132,0.473095,0.471062

DSTAR SCORES

,ry 19,cx 17,ry 18,cx 16,cx 15,cx 14,ry 22,ry 21,ry 23,ry 12,...,ry 9,ry 13,ry 4,cx 8,ry 1,ry 2,ry 3,ry 0,ry 10,ry 11
sum,18.630257,15.33937,15.000862,12.032141,11.597804,9.841271,7.488556,3.555156,2.270689,2.15323,...,1.429979,1.418556,0.49725,0.429694,0.313055,0.003473,0.00254,3.830687e-10,8.800039e-11,2.306809e-11

ERROR GATE LOCATION:
20
Now evolving the following mutant:  AddGate_ry_inGap_23_.qasm

100%|██████████| 10/10 [00:19<00:00,  1.98s/it]
100%|██████████| 10/10 [00:19<00:00,  1.98s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,ry 18,cx 17,cx 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.625980,0.443295,0.951280,0.712306,1.571929,1.727533,1.908988,1.797259,1.820387,1.742388,...,0.215135,0.591744,0.632700,0.413852,0.185893,0.014839,0.020226,0.208632,0.000006,fail
1,0.625637,0.443053,1.156781,0.687287,1.704758,2.447006,2.602358,2.101794,1.853531,1.716949,...,0.281100,0.569657,0.547235,0.458722,0.217291,0.018906,0.018914,0.207384,0.000007,fail
2,0.564090,0.399468,1.255392,0.599485,1.703695,1.948938,2.077976,1.855071,1.877860,1.610135,...,0.181350,0.535971,0.506139,0.381820,0.187591,0.016050,0.015495,0.169335,0.000006,fail
3,0.656854,0.465159,0.957231,0.643904,1.563011,2.047527,2.247526,2.216812,2.226354,1.883568,...,0.201684,0.602519,0.585881,0.435906,0.208307,0.017241,0.019516,0.204557,0.000007,fail
4,0.630269,0.446333,1.767384,0.846752,2.393073,2.622741,2.791603,2.501056,2.403976,2.207753,...,0.274148,0.776221,0.779392,0.648263,0.332461,0.021538,0.025284,0.270311,0.000009,fail
5,0.629438,0.445745,0.885525,0.706249,1.574295,1.538533,1.649938,1.758182,1.781757,1.620533,...,0.255491,0.468197,0.501028,0.425739,0.209774,0.016004,0.017317,0.166699,0.000006,fail
6,0.514066,0.364042,1.527649,0.873584,1.384223,2.327600,2.542922,2.293215,1.863724,1.759489,...,0.289057,0.608382,0.620030,0.524655,0.248657,0.018567,0.020777,0.232539,0.000008,fail
7,0.611683,0.433171,1.159958,0.675428,1.703263,1.665520,1.747215,1.631770,1.525772,1.607967,...,0.172847,0.458890,0.460498,0.372595,0.191071,0.014520,0.017047,0.176312,0.000005,fail
8,0.489655,0.346755,1.157584,0.515292,1.402771,2.216288,2.448957,2.043563,2.215785,2.153069,...,0.218874,0.683342,0.744741,0.561669,0.271144,0.016835,0.023989,0.242935,0.000007,fail
9,0.569355,0.403196,1.407237,0.799497,1.788542,2.536202,2.576362,1.512862,1.634179,1.430343,...,0.288846,0.495167,0.563856,0.422604,0.189139,0.015031,0.017645,0.134003,0.000007,fail
10,0.422643,0.299300,0.984221,0.820950,1.536413,1.852139,2.009782,1.774649,1.707255,1.734567,...,0.243580,0.630978,0.618676,0.494237,0.247619,0.013289,0.018365,0.204396,0.000007,pass
11,0.426252,0.301855,1.203443,0.534934,1.297113,1.430905,1.493141,1.417336,1.530096,1.398988,...,0.101181,0.388529,0.414919,0.305693,0.164403,0.012011,0.013086,0.130233,0.000005,pass
12,0.417066,0.295350,1.310203,1.023908,2.109020,1.967508,2.015504,1.695188,1.918728,2.001017,...,0.242299,0.672495,0.684604,0.538024,0.260135,0.015963,0.021042,0.218768,0.000007,pass
13,0.330147,0.233798,0.873170,0.731407,1.290801,1.377048,1.426541,1.339995,1.133430,1.045677,...,0.215301,0.386733,0.364446,0.374094,0.199118,0.011686,0.011827,0.138518,0.000004,pass
14,0.606813,0.429722,1.109558,0.853729,1.156185,2.096162,2.391214,2.246773,1.834945,1.678215,...,0.284865,0.637561,0.618815,0.500503,0.234052,0.017771,0.018836,0.231971,0.000008,pass
15,0.420703,0.297926,0.932740,0.694057,1.672044,1.303031,1.422335,1.673165,1.950873,2.133213,...,0.223949,0.571635,0.704893,0.552974,0.269526,0.015096,0.024164,0.237806,0.000006,pass
16,0.439722,0.311395,1.081140,0.645051,1.123978,1.309268,1.330852,0.938468,0.754234,0.712056,...,0.190810,0.321987,0.325182,0.241396,0.107922,0.010491,0.010146,0.093195,0.000004,pass
17,0.551618,0.390635,1.428633,0.941319,2.371746,2.537283,2.480596,1.373841,1.217927,1.356998,...,0.240446,0.473946,0.499501,0.406923,0.209868,0.014121,0.015953,0.149367,0.000006,pass
18,0.499287,0.353576,1.205859,0.777026,1.682336,1.870695,1.882889,1.422732,1.489418,1.525590,...,0.255603,0.471462,0.526099,0.451846,0.219884,0.013461,0.017448,0.151865,0.000005,pass
19,0.570949,0.404325,1.262302,1.113684,1.697985,1.937059,2.213369,2.327665,2.367161,2.289426,...,0.322486,0.813123,0.829277,0.678191,0.320770,0.020941,0.025531,0.302151,0.000009,pass

BARINEL SCORES

,ry 23,ry 22,ry 10,cx 16,ry 9,cx 17,cx 15,ry 18,ry 12,ry 3,...,ry 1,cx 7,ry 21,cx 6,ry 19,ry 13,cx 8,cx 5,ry 4,ry 20
sum,0.558093,0.558093,0.5524,0.548742,0.548719,0.547596,0.546988,0.543819,0.539302,0.53929,...,0.519948,0.518893,0.517672,0.515401,0.513016,0.506746,0.506173,0.505547,0.500897,0.464586

TARANTULA SCORES

,ry 23,ry 22,ry 10,cx 16,ry 9,cx 17,cx 15,ry 18,ry 12,ry 3,...,ry 1,cx 7,ry 21,cx 6,ry 19,ry 13,cx 8,cx 5,ry 4,ry 20
sum,0.558093,0.558093,0.5524,0.548742,0.548719,0.547596,0.546988,0.543819,0.539302,0.53929,...,0.519948,0.518893,0.517672,0.515401,0.513016,0.506746,0.506173,0.505547,0.500897,0.464586

DSTAR SCORES

,cx 17,ry 18,cx 16,cx 15,cx 14,ry 19,ry 21,ry 12,ry 20,ry 23,...,ry 13,ry 22,cx 8,ry 4,ry 1,ry 2,ry 3,ry 0,ry 10,ry 11
sum,17.807782,16.049848,14.824472,14.235897,12.151563,10.86797,6.987692,2.749418,2.748145,2.384115,...,1.320278,1.318371,0.459186,0.410645,0.341617,0.003783,0.002833,4.665692e-10,1.030583e-10,2.466255e-11

ERROR GATE LOCATION:
23
Now evolving the following mutant:  AddGate_z_inGap_21_.qasm

100%|██████████| 10/10 [00:21<00:00,  2.12s/it]
100%|██████████| 10/10 [00:20<00:00,  2.02s/it]

,ry 23,ry 22,ry 21,z 20,ry 19,ry 18,cx 17,cx 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.603848,1.345236,1.077400,0.409027,1.966571,2.225595,2.312622,1.892733,1.474047,1.508822,...,0.350614,0.562981,0.558643,0.538612,0.275818,0.018691,0.018141,0.204233,0.000007,fail
1,0.401315,1.147145,0.624794,0.251305,1.581437,1.778010,2.037386,2.182257,2.156728,2.243645,...,0.244127,0.692072,0.691449,0.563884,0.288817,0.015435,0.023415,0.258588,0.000008,fail
2,0.555803,1.150029,1.082755,0.353162,1.873495,1.904756,1.942200,1.670965,1.484841,1.375473,...,0.224962,0.508961,0.537366,0.456112,0.239255,0.012615,0.016877,0.165229,0.000006,fail
3,0.622335,1.127927,1.008654,0.363997,1.797449,2.150912,2.336493,2.287487,1.998549,1.780022,...,0.357404,0.656469,0.682309,0.579144,0.289309,0.019361,0.022543,0.244459,0.000008,fail
4,0.688366,1.700101,1.154477,0.373719,2.431611,2.131902,2.174916,1.987350,1.845673,1.631997,...,0.343131,0.667648,0.681725,0.548211,0.274860,0.019725,0.019887,0.219482,0.000007,fail
5,0.562700,0.787246,0.911874,0.336343,1.351301,1.784053,1.934212,1.560224,1.123577,0.951125,...,0.348317,0.453420,0.488596,0.491176,0.248132,0.014285,0.015277,0.172804,0.000006,fail
6,0.527130,0.953398,0.829633,0.290209,1.343170,1.997032,2.233112,2.101263,1.993610,2.240098,...,0.271372,0.674623,0.716370,0.555618,0.284360,0.015596,0.023803,0.255828,0.000008,fail
7,0.577949,1.040898,1.061004,0.386511,2.190553,1.842805,2.022054,2.194505,2.188475,1.969649,...,0.385573,0.756650,0.786564,0.643482,0.322426,0.017490,0.024538,0.248126,0.000008,fail
8,0.434876,0.693569,0.803265,0.273597,1.447742,1.574176,1.737131,1.807215,1.741373,1.754960,...,0.256492,0.603359,0.670320,0.522359,0.250763,0.015313,0.020941,0.232920,0.000006,fail
9,0.530007,1.214126,0.957614,0.318808,2.116672,2.421443,2.555782,1.848759,1.624266,1.901781,...,0.314344,0.672056,0.720666,0.568329,0.260834,0.017632,0.022608,0.252012,0.000008,fail
10,0.607520,1.250364,1.015247,0.345345,1.720961,2.357444,2.642775,2.393207,2.137980,2.078778,...,0.366798,0.760075,0.777853,0.626437,0.306188,0.018796,0.024928,0.283195,0.000008,pass
11,0.393494,1.010566,0.681524,0.271961,1.209263,1.932938,2.273813,2.597681,2.683080,2.254751,...,0.263503,0.781759,0.744324,0.570377,0.257896,0.019768,0.023812,0.260159,0.000009,pass
12,0.326008,1.042462,0.518068,0.203444,1.518336,1.435815,1.432783,1.064990,1.162867,1.349332,...,0.126422,0.390440,0.411354,0.343999,0.165624,0.010457,0.013127,0.135471,0.000004,pass
13,0.485122,1.022683,0.597971,0.225485,1.211662,1.635012,1.731607,1.232730,1.113459,1.086699,...,0.219927,0.377470,0.361980,0.315161,0.159233,0.010087,0.013099,0.119881,0.000004,pass
14,0.450385,1.416786,0.899131,0.294935,1.509149,1.695831,1.648720,0.880034,0.828499,0.948448,...,0.254989,0.329195,0.411397,0.345919,0.175746,0.009662,0.012270,0.096460,0.000005,pass
15,0.572631,1.439109,0.933911,0.313877,1.377395,2.591577,2.775764,1.866854,1.542675,1.422110,...,0.325736,0.593891,0.563093,0.471865,0.219087,0.015687,0.017708,0.174707,0.000007,pass
16,0.246196,0.683415,0.471619,0.184375,0.974810,1.232860,1.396703,1.311487,1.229460,1.448045,...,0.201735,0.462733,0.479814,0.385153,0.194235,0.010919,0.015410,0.178455,0.000006,pass
17,0.402764,0.669898,0.611525,0.254858,1.340313,1.991636,2.175502,1.994880,2.109725,1.602652,...,0.174952,0.520538,0.542112,0.465237,0.234034,0.016189,0.017085,0.181533,0.000006,pass
18,0.567543,0.930193,0.796878,0.281968,1.740243,2.731569,2.917871,1.971136,1.960331,2.326371,...,0.253720,0.643444,0.701660,0.558669,0.268051,0.017292,0.023732,0.253074,0.000010,pass
19,0.428004,1.233765,0.750457,0.273893,1.201989,1.873310,2.007295,1.679910,1.381904,1.076275,...,0.273974,0.450104,0.442787,0.385502,0.168776,0.014568,0.014087,0.142512,0.000006,pass

BARINEL SCORES

,ry 19,ry 21,ry 4,z 20,cx 8,ry 1,ry 23,cx 5,cx 6,ry 2,...,ry 10,cx 14,ry 0,cx 15,ry 11,ry 22,ry 13,ry 9,ry 18,cx 17
sum,0.567325,0.56657,0.559968,0.558811,0.557086,0.552491,0.551315,0.550256,0.545848,0.542752,...,0.529352,0.526769,0.526241,0.521923,0.515871,0.510532,0.50895,0.508904,0.504234,0.503347

TARANTULA SCORES

,ry 19,ry 21,ry 4,z 20,cx 8,ry 1,ry 23,cx 5,cx 6,ry 2,...,ry 10,cx 14,ry 0,cx 15,ry 11,ry 22,ry 13,ry 9,ry 18,cx 17
sum,0.567325,0.56657,0.559968,0.558811,0.557086,0.552491,0.551315,0.550256,0.545848,0.542752,...,0.529352,0.526769,0.526241,0.521923,0.515871,0.510532,0.50895,0.508904,0.504234,0.503347

DSTAR SCORES

,cx 17,cx 16,ry 19,ry 18,cx 15,cx 14,ry 22,ry 21,cx 6,ry 12,...,ry 13,z 20,cx 8,ry 4,ry 1,ry 2,ry 3,ry 0,ry 10,ry 11
sum,14.614468,14.134402,13.762743,13.313769,11.887467,11.771964,6.016566,5.236531,2.765757,2.628221,...,1.305819,0.890685,0.769338,0.615521,0.429504,0.004253,0.002721,5.113939e-10,8.964432e-11,2.073383e-11

ERROR GATE LOCATION:
20
Now evolving the following mutant:  AddGate_ry_inGap_8_.qasm

100%|██████████| 10/10 [00:21<00:00,  2.12s/it]
100%|██████████| 10/10 [00:20<00:00,  2.03s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,ry 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.593696,1.019431,0.740240,1.547426,2.521634,2.708753,2.064101,1.884093,1.935101,0.503223,...,0.631099,0.317330,0.599291,0.497728,0.248880,0.019024,0.021706,0.233465,0.000006,fail
1,0.442466,1.294913,0.888258,1.693708,1.702574,1.961041,2.399888,2.092131,1.705147,0.498932,...,0.682551,0.317941,0.632820,0.568057,0.262358,0.017181,0.020610,0.258514,0.000007,fail
2,0.735279,1.487049,0.720231,1.954791,2.115837,2.239235,2.255156,2.065630,1.518984,0.390714,...,0.565134,0.246104,0.519500,0.397423,0.193553,0.019160,0.018745,0.192980,0.000005,fail
3,0.572408,1.200168,1.043112,1.837007,2.340570,2.618231,2.474422,2.524357,2.391789,0.609151,...,0.848883,0.397673,0.821945,0.710746,0.359375,0.018542,0.026305,0.293192,0.000008,fail
4,0.689694,1.308260,0.789809,2.341568,2.478694,2.521093,2.001495,1.829769,1.432913,0.446068,...,0.570116,0.277772,0.500034,0.442180,0.225510,0.016443,0.018545,0.170944,0.000005,fail
5,0.573991,1.289367,0.842223,1.377460,2.020356,2.198046,1.922219,1.803047,1.496193,0.437183,...,0.532684,0.280061,0.529593,0.424350,0.209237,0.018003,0.017450,0.190800,0.000006,fail
6,0.363348,1.158153,0.704593,1.528056,1.734496,1.826658,1.517396,1.572145,1.228633,0.412775,...,0.471122,0.251244,0.440117,0.392061,0.191604,0.013176,0.013465,0.135848,0.000004,fail
7,0.743213,1.311244,1.017864,1.856225,2.942439,3.253526,2.789483,2.632186,2.656233,0.636466,...,0.853557,0.402231,0.890943,0.731731,0.347940,0.022893,0.030511,0.341668,0.000009,fail
8,0.655432,1.407745,0.944584,1.687761,1.748241,1.910073,1.797553,1.498071,1.508532,0.336794,...,0.556955,0.334595,0.585742,0.498918,0.235833,0.018866,0.019001,0.234585,0.000006,fail
9,0.445289,0.908444,0.923499,1.607650,1.719935,1.766868,1.139961,0.893962,0.981345,0.282670,...,0.407480,0.316759,0.443416,0.426724,0.168377,0.011846,0.013862,0.152940,0.000004,fail
10,0.401991,0.838751,0.495237,0.987841,1.347072,1.429662,1.165920,1.397438,1.450667,0.320345,...,0.397333,0.150179,0.423908,0.313342,0.150788,0.008332,0.014871,0.130043,0.000004,pass
11,0.448225,1.305580,0.704373,1.682725,2.459640,2.631995,2.066763,1.774082,1.711217,0.536882,...,0.568887,0.293977,0.534391,0.515776,0.258469,0.015569,0.019357,0.214931,0.000006,pass
12,0.414297,1.090877,0.779445,0.764199,1.674161,1.934535,1.841722,1.684611,1.531966,0.454652,...,0.566362,0.281486,0.552969,0.481095,0.216061,0.013826,0.017617,0.198584,0.000006,pass
13,0.442482,0.998193,0.515884,1.532844,1.887645,2.045730,1.681485,1.922689,1.546716,0.517770,...,0.543298,0.224479,0.509680,0.438243,0.232214,0.014995,0.016295,0.173491,0.000005,pass
14,0.462437,0.662498,0.696697,1.125648,1.483284,1.714500,1.758286,1.577017,1.515401,0.361032,...,0.529137,0.260916,0.569110,0.454461,0.197813,0.012666,0.017594,0.214084,0.000006,pass
15,0.365744,0.925729,0.531128,0.984213,1.154789,1.335708,1.662092,1.709497,1.538664,0.424216,...,0.481804,0.202277,0.501365,0.437221,0.219085,0.013677,0.016683,0.186564,0.000005,pass
16,0.328129,0.684245,0.383540,1.122393,1.377112,1.352146,0.792150,1.028370,0.881937,0.265167,...,0.238826,0.122733,0.285085,0.234383,0.125385,0.008286,0.009804,0.071807,0.000003,pass
17,0.382907,0.900063,0.642179,1.026378,1.364591,1.474003,1.286614,1.042219,1.416068,0.332118,...,0.434448,0.276731,0.462566,0.433744,0.205179,0.012579,0.016727,0.180216,0.000004,pass
18,0.448146,1.081486,1.061428,2.050904,2.314239,2.333411,1.398697,1.376291,1.533741,0.461228,...,0.569316,0.397364,0.615863,0.606250,0.295833,0.015435,0.019890,0.213933,0.000006,pass
19,0.459104,1.011393,0.716580,1.421646,1.632779,1.771772,1.721474,1.560735,1.205238,0.371875,...,0.521321,0.260491,0.489091,0.426812,0.204107,0.012832,0.015742,0.172455,0.000004,pass

BARINEL SCORES

,ry 23,ry 20,ry 3,cx 17,ry 21,ry 0,ry 11,ry 22,ry 10,ry 19,...,cx 9,ry 1,cx 16,ry 12,ry 2,cx 6,cx 15,cx 5,ry 4,ry 14
sum,0.583332,0.57854,0.577366,0.569766,0.56895,0.567678,0.566191,0.565939,0.560886,0.560882,...,0.556656,0.556655,0.554955,0.550375,0.548823,0.546728,0.540454,0.539687,0.537133,0.529578

TARANTULA SCORES

,ry 23,ry 20,ry 3,cx 17,ry 21,ry 0,ry 11,ry 22,ry 10,ry 19,...,cx 9,ry 1,cx 16,ry 12,ry 2,cx 6,cx 15,cx 5,ry 4,ry 14
sum,0.583332,0.57854,0.577366,0.569766,0.56895,0.567678,0.566191,0.565939,0.560886,0.560882,...,0.556656,0.556655,0.554955,0.550375,0.548823,0.546728,0.540454,0.539687,0.537133,0.529578

DSTAR SCORES

,cx 18,ry 19,cx 17,cx 16,ry 20,cx 15,ry 22,ry 21,ry 13,cx 8,...,ry 14,ry 7,cx 9,ry 4,ry 1,ry 2,ry 3,ry 0,ry 11,ry 12
sum,18.882824,17.034681,16.338698,14.089553,13.386726,11.675619,7.866255,4.490252,2.549965,2.521713,...,1.476559,0.791486,0.62203,0.492908,0.413551,0.003943,0.003028,3.690703e-10,1.029591e-10,2.398077e-11

ERROR GATE LOCATION:
7
Now evolving the following mutant:  AddGate_h_inGap_21_.qasm

100%|██████████| 10/10 [00:20<00:00,  2.07s/it]
100%|██████████| 10/10 [00:20<00:00,  2.04s/it]

,ry 23,ry 22,ry 21,h 20,ry 19,ry 18,cx 17,cx 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.503552,1.167207,0.861290,0.674465,1.549259,2.451930,2.658870,2.653147,2.510255,2.628665,...,0.963592,1.244505,1.036265,0.681585,0.355606,0.027494,0.034652,0.274016,0.000009,fail
1,0.584970,1.216367,0.860471,0.705284,1.667784,2.450768,2.674664,2.579350,2.594231,2.756824,...,0.974400,1.259514,1.010806,0.636333,0.376879,0.028357,0.036383,0.311124,0.000007,fail
2,0.440535,1.048579,0.953438,0.799261,1.307082,2.009265,2.174571,2.112475,1.795052,1.672458,...,1.099640,1.088940,0.737989,0.494262,0.330012,0.027454,0.030984,0.218551,0.000005,fail
3,0.557361,1.192565,0.933350,0.768921,1.262924,1.897715,2.103740,2.257534,1.943875,1.996972,...,1.060483,1.087376,0.896141,0.664660,0.385156,0.028188,0.031235,0.247524,0.000007,fail
4,0.481190,1.052294,0.854432,0.717395,1.293310,1.996565,2.244100,2.290740,2.204222,2.298389,...,0.926243,0.987618,0.904853,0.524764,0.279562,0.024542,0.029102,0.256642,0.000008,fail
5,0.573158,1.341298,1.259595,1.075160,1.905048,1.603639,1.753407,2.534178,2.302120,2.391320,...,1.024327,1.213026,0.987131,0.737663,0.447268,0.027694,0.035951,0.279207,0.000008,fail
6,0.463689,1.176334,0.817314,0.649339,1.315428,1.964056,2.093476,1.997287,1.735234,1.556767,...,0.865157,0.824865,0.498727,0.399463,0.267845,0.021470,0.027841,0.194867,0.000005,fail
7,0.401739,1.009462,0.939703,0.741823,1.178476,2.145483,2.401462,2.183421,1.880804,1.964927,...,1.120622,1.059195,0.804438,0.551448,0.315333,0.024546,0.031638,0.249812,0.000007,fail
8,0.666555,1.218902,0.831677,0.693812,1.828431,2.199812,2.305415,2.089312,1.765978,1.696786,...,0.784952,0.973002,0.808878,0.551713,0.273422,0.026837,0.025919,0.190207,0.000006,fail
9,0.568267,1.234469,1.027248,0.860331,1.519378,1.354112,1.444421,2.109101,1.760611,1.666613,...,0.886507,0.966768,0.777838,0.543457,0.307388,0.024018,0.026597,0.199895,0.000007,fail
10,0.451246,0.857500,0.576785,0.489709,1.095862,1.191413,1.291550,1.329008,1.203779,1.451465,...,0.523452,0.639752,0.608412,0.383513,0.226220,0.016590,0.018918,0.155458,0.000004,pass
11,0.456641,0.843598,0.603575,0.466217,1.427160,2.075781,2.195733,2.118421,2.010359,2.020974,...,0.451116,0.797882,0.652442,0.573417,0.345925,0.017842,0.025352,0.212040,0.000007,pass
12,0.605223,0.612179,0.823226,0.659412,1.381936,1.994127,2.268978,2.416790,2.356593,2.278060,...,0.853797,0.989370,0.781147,0.639911,0.384974,0.027941,0.034491,0.283135,0.000007,pass
13,0.466321,1.626302,0.762006,0.641453,1.777676,2.233330,2.277840,1.983656,1.581319,1.565681,...,0.704521,0.910958,0.660534,0.491751,0.309202,0.017709,0.025059,0.170756,0.000006,pass
14,0.632419,1.505259,0.925175,0.850092,1.722557,1.762086,1.807363,1.671652,1.150222,1.021084,...,0.738650,0.779270,0.529201,0.366826,0.293092,0.021426,0.022021,0.147615,0.000004,pass
15,0.587061,1.452650,0.811105,0.681912,1.763392,2.295483,2.437685,2.720754,2.257345,1.799638,...,0.869406,1.107798,0.833602,0.622639,0.436140,0.026952,0.028245,0.231339,0.000006,pass
16,0.432712,0.655693,0.418800,0.253371,1.106833,1.646946,1.754780,1.671058,1.565691,1.415409,...,0.666393,0.639959,0.419777,0.342922,0.255606,0.016092,0.018468,0.176871,0.000005,pass
17,0.314863,1.043169,0.515338,0.390219,1.704968,1.908211,1.945381,1.672228,1.555902,1.944968,...,0.639643,0.841763,0.800307,0.541537,0.332224,0.014858,0.022402,0.181556,0.000006,pass
18,0.383242,0.820798,0.688199,0.600489,1.097201,0.964007,0.999797,1.311280,1.033942,0.922881,...,0.518752,0.533592,0.391302,0.326119,0.206223,0.016330,0.016741,0.115696,0.000004,pass
19,0.586770,1.376464,0.738960,0.626958,1.980490,1.983121,2.097332,2.193870,1.898576,1.770539,...,0.738853,0.953121,0.711988,0.542160,0.369473,0.021094,0.027146,0.215317,0.000005,pass

BARINEL SCORES

,cx 8,ry 21,h 20,ry 9,ry 12,cx 6,ry 3,cx 7,ry 2,ry 1,...,cx 16,cx 17,ry 11,ry 10,ry 18,ry 22,ry 23,ry 13,ry 4,ry 19
sum,0.591446,0.576392,0.575903,0.570974,0.56985,0.569835,0.569699,0.566444,0.565063,0.561701,...,0.54437,0.533932,0.53302,0.530005,0.526475,0.519239,0.515974,0.51462,0.513805,0.496136

TARANTULA SCORES

,cx 8,ry 21,h 20,ry 9,ry 12,cx 6,ry 3,cx 7,ry 2,ry 1,...,cx 16,cx 17,ry 11,ry 10,ry 18,ry 22,ry 23,ry 13,ry 4,ry 19
sum,0.591446,0.576392,0.575903,0.570974,0.56985,0.569835,0.569699,0.566444,0.565063,0.561701,...,0.54437,0.533932,0.53302,0.530005,0.526475,0.519239,0.515974,0.51462,0.513805,0.496136

DSTAR SCORES

,cx 16,cx 17,cx 14,cx 15,ry 18,ry 19,ry 22,cx 7,cx 8,ry 21,...,cx 5,ry 23,ry 13,ry 4,ry 1,ry 2,ry 3,ry 0,ry 10,ry 11
sum,17.881107,16.425768,16.249486,15.77899,14.362726,8.773358,6.535508,6.298576,5.639468,5.171503,...,2.256807,1.841469,1.518003,0.846972,0.493308,0.009404,0.00666,4.739862e-10,9.668195e-11,3.336315e-11

ERROR GATE LOCATION:
20
Now evolving the following mutant:  AddGate_x_inGap_14_.qasm

100%|██████████| 10/10 [00:19<00:00,  1.97s/it]
100%|██████████| 10/10 [00:19<00:00,  1.94s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.420531,1.204650,0.492344,1.235847,2.086760,2.266699,1.975336,2.047121,1.648773,0.515549,...,0.162472,0.583025,0.525637,0.385840,0.195058,0.014801,0.016587,0.175875,0.000007,fail
1,0.637271,1.315448,1.019106,2.101581,1.322719,1.387484,1.736612,1.545560,1.290332,0.359949,...,0.360780,0.598566,0.638090,0.542565,0.265521,0.016806,0.020217,0.203405,0.000004,fail
2,0.576180,1.189494,0.516802,1.496697,2.055415,2.226154,1.797632,2.060829,2.124203,0.478175,...,0.228011,0.571665,0.653119,0.531630,0.281693,0.015103,0.021272,0.214663,0.000007,fail
3,0.595898,1.010728,0.772143,1.487454,1.806438,1.916399,1.548921,1.154904,1.323221,0.354414,...,0.224325,0.457777,0.470360,0.359210,0.176610,0.012421,0.016941,0.173652,0.000005,fail
4,0.571123,0.773199,0.685696,1.835202,2.255006,2.468966,2.188644,2.313485,2.240510,0.655723,...,0.220946,0.670803,0.723794,0.600664,0.297719,0.019249,0.024883,0.254662,0.000008,fail
5,0.553983,1.243385,0.681645,1.399523,2.055698,2.255780,2.092474,1.709814,1.398298,0.478260,...,0.236956,0.598252,0.506276,0.473654,0.246566,0.016032,0.017046,0.203256,0.000006,fail
6,0.553481,1.400307,0.758140,1.927859,1.505996,1.708029,2.375559,2.043239,2.070574,0.610100,...,0.231112,0.682921,0.664909,0.561989,0.316562,0.017535,0.023200,0.276112,0.000007,fail
7,0.652830,1.387768,0.852054,1.854481,2.240524,2.290125,1.670074,1.601335,0.890011,0.363298,...,0.223042,0.447656,0.427288,0.365773,0.174773,0.014024,0.013393,0.103944,0.000005,fail
8,0.584521,1.447974,0.771132,1.015989,2.182349,2.466576,2.162252,2.034026,1.830557,0.581187,...,0.284270,0.658737,0.698352,0.566143,0.290455,0.016377,0.022609,0.231923,0.000008,fail
9,0.603622,1.270308,0.872357,1.413360,1.692099,1.881381,2.072121,1.740611,1.485889,0.453679,...,0.370288,0.619883,0.635908,0.529987,0.259292,0.017184,0.021830,0.216463,0.000006,fail
10,0.413839,1.024457,0.876829,1.448795,1.965807,2.051920,1.333029,1.136906,1.055249,0.317246,...,0.310032,0.501027,0.504996,0.443482,0.203009,0.013210,0.015352,0.156187,0.000006,pass
11,0.392237,1.260792,0.837185,1.839158,2.217503,2.362469,1.815386,1.414344,1.203765,0.371711,...,0.352026,0.600040,0.538669,0.491152,0.240176,0.015362,0.016324,0.179301,0.000006,pass
12,0.572326,1.147662,0.846672,2.532977,1.916206,1.857967,1.345928,1.585594,1.509577,0.451200,...,0.191867,0.522527,0.553175,0.387584,0.198283,0.015546,0.018628,0.162608,0.000004,pass
13,0.645210,1.397763,0.791193,1.292782,1.467634,1.601319,1.848945,1.570817,1.325162,0.345365,...,0.219861,0.492206,0.497407,0.381671,0.198456,0.015471,0.017281,0.183621,0.000005,pass
14,0.245690,0.515940,0.404669,1.057601,1.282157,1.256351,0.751093,0.875561,1.008538,0.262741,...,0.133209,0.279029,0.300827,0.232125,0.109226,0.008285,0.009825,0.084742,0.000003,pass
15,0.642751,1.315149,0.532135,2.261741,1.701500,1.852536,2.081126,2.358973,2.375970,0.464674,...,0.213286,0.734076,0.789835,0.527221,0.252203,0.018613,0.024830,0.262240,0.000007,pass
16,0.661912,1.569651,1.020507,1.558805,1.389206,1.572287,1.937653,1.238497,1.004626,0.333514,...,0.271553,0.471200,0.417948,0.410152,0.228107,0.013553,0.013821,0.175385,0.000005,pass
17,0.292682,1.192809,0.830100,1.523651,1.230158,1.381713,1.557815,1.502100,1.787589,0.463901,...,0.224637,0.590075,0.601924,0.511302,0.259143,0.011949,0.019862,0.229376,0.000006,pass
18,0.413939,1.069876,0.991284,1.813389,1.663133,1.721104,1.497082,1.520913,1.681924,0.445936,...,0.316001,0.556867,0.556542,0.540078,0.252769,0.014684,0.018801,0.190376,0.000007,pass
19,0.467534,1.260841,0.962811,1.501908,1.508855,1.588990,1.587495,1.431536,1.546953,0.372311,...,0.292905,0.504513,0.546143,0.467383,0.226348,0.015833,0.017742,0.190320,0.000006,pass

BARINEL SCORES

,ry 14,ry 10,cx 16,cx 17,ry 9,x 13,ry 23,cx 18,ry 11,ry 19,...,cx 15,cx 7,cx 6,cx 5,ry 3,ry 12,ry 22,cx 8,ry 20,ry 21
sum,0.558863,0.558796,0.554973,0.554616,0.554021,0.552702,0.547693,0.547501,0.54567,0.540242,...,0.529268,0.528621,0.528276,0.528213,0.528183,0.51501,0.510174,0.50166,0.483699,0.478344

TARANTULA SCORES

,ry 14,ry 10,cx 16,cx 17,ry 9,x 13,ry 23,cx 18,ry 11,ry 19,...,cx 15,cx 7,cx 6,cx 5,ry 3,ry 12,ry 22,cx 8,ry 20,ry 21
sum,0.558863,0.558796,0.554973,0.554616,0.554021,0.552702,0.547693,0.547501,0.54567,0.540242,...,0.529268,0.528621,0.528276,0.528213,0.528183,0.51501,0.510174,0.50166,0.483699,0.478344

DSTAR SCORES

,cx 18,cx 17,ry 19,cx 16,cx 15,ry 20,ry 22,ry 21,cx 6,cx 7,...,cx 5,cx 8,ry 4,ry 1,x 13,ry 2,ry 3,ry 0,ry 10,ry 11
sum,15.982016,14.945502,13.998678,13.521127,10.847928,9.26657,6.890273,3.044068,2.307891,2.274108,...,1.680176,0.515976,0.515401,0.357091,0.219278,0.003853,0.002509,4.106559e-10,9.479805e-11,2.205223e-11

ERROR GATE LOCATION:
13
Now evolving the following mutant:  AddGate_x_inGap_3_.qasm

100%|██████████| 10/10 [00:22<00:00,  2.29s/it]
100%|██████████| 10/10 [00:22<00:00,  2.22s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,ry 5,ry 4,ry 3,x 2,ry 1,ry 0,pass/fail
0,0.529489,1.120887,0.739986,1.519027,1.991733,2.139805,1.713182,1.546525,1.514139,0.366397,...,0.529374,0.524565,0.390158,0.146052,0.016407,0.017532,0.068565,0.182824,0.000007,fail
1,0.551589,1.235367,0.736282,0.995665,2.204434,2.609510,2.659471,2.237726,2.285197,0.541251,...,0.744765,0.747497,0.594926,0.288957,0.020904,0.024352,0.103101,0.305425,0.000009,fail
2,0.614299,1.191040,1.042688,1.920493,2.098397,2.279923,2.219510,2.398097,2.163435,0.575483,...,0.686513,0.775983,0.602629,0.293331,0.019738,0.023795,0.094745,0.257369,0.000008,fail
3,0.629877,1.297346,0.904852,1.891944,2.102538,2.301214,2.094937,1.932604,2.231909,0.541827,...,0.720967,0.774820,0.573496,0.250733,0.020819,0.024476,0.100947,0.275524,0.000008,fail
4,0.579441,1.107691,0.672491,1.508853,2.168517,2.287772,1.975234,2.076532,1.810851,0.452053,...,0.558237,0.639497,0.486525,0.225809,0.018224,0.020356,0.077461,0.189766,0.000007,fail
5,0.683212,1.179724,0.844376,1.690848,1.458245,1.501408,1.535906,1.572768,1.364667,0.313468,...,0.474701,0.509025,0.404148,0.201506,0.015359,0.016410,0.060251,0.152102,0.000005,fail
6,0.678612,1.359203,0.945103,1.877344,2.089508,2.184905,1.816978,1.400196,1.510362,0.426474,...,0.608855,0.641396,0.520493,0.243357,0.018440,0.020438,0.079386,0.220332,0.000006,fail
7,0.727034,1.153683,0.655878,1.593368,1.704990,1.839134,1.733342,1.741061,1.269877,0.244210,...,0.495252,0.493436,0.311498,0.115057,0.015111,0.016391,0.052772,0.141102,0.000005,fail
8,0.473033,1.004262,0.709674,1.277739,1.216238,1.405980,1.740756,1.465293,1.454825,0.360345,...,0.516316,0.488812,0.400928,0.189037,0.013676,0.016552,0.064699,0.184012,0.000005,fail
9,0.543554,1.173490,0.950490,1.665226,1.897606,2.112741,2.195856,2.335700,2.581900,0.565479,...,0.743125,0.775627,0.581341,0.268068,0.017268,0.025593,0.107333,0.269508,0.000009,fail
10,0.417806,1.127384,0.703695,1.463709,2.175213,2.427679,2.260211,2.194837,1.866944,0.565997,...,0.670120,0.667788,0.591075,0.323043,0.014721,0.021375,0.083610,0.234823,0.000008,pass
11,0.346432,0.644272,0.389906,1.000302,1.213751,1.361023,1.325165,1.131544,1.249376,0.303810,...,0.410534,0.426021,0.331584,0.169783,0.010090,0.015005,0.054236,0.166637,0.000004,pass
12,0.524261,1.363408,0.845386,1.737667,1.725999,1.863902,2.003443,1.752161,1.377912,0.422036,...,0.574641,0.569354,0.502216,0.256293,0.017676,0.017518,0.069550,0.193459,0.000006,pass
13,0.396303,0.897996,0.345154,1.160506,1.197007,1.289111,1.320319,1.272564,1.003326,0.286601,...,0.366234,0.331409,0.252947,0.126032,0.010252,0.011046,0.041421,0.112819,0.000003,pass
14,0.497785,1.053166,0.683978,1.654289,1.870855,2.069416,2.188050,2.097052,2.003085,0.508228,...,0.674851,0.677360,0.516522,0.270387,0.016743,0.022642,0.087641,0.244794,0.000007,pass
15,0.595222,1.453684,1.057039,1.744293,2.384462,2.661027,2.451850,2.078239,1.902632,0.644357,...,0.759173,0.699268,0.590258,0.298440,0.018467,0.022041,0.093708,0.265366,0.000009,pass
16,0.516451,1.331480,0.984544,1.264061,2.040615,2.203186,1.490929,1.069594,1.389711,0.363693,...,0.471722,0.456492,0.440902,0.231091,0.013535,0.014879,0.078193,0.172947,0.000006,pass
17,0.691625,1.360711,0.876634,2.545886,2.246367,2.373114,2.138974,2.050135,2.292751,0.574874,...,0.753851,0.753661,0.584894,0.283318,0.020116,0.024649,0.100891,0.274307,0.000008,pass
18,0.398990,0.823446,0.643725,0.972106,1.390433,1.522526,1.465181,1.264975,1.248285,0.333346,...,0.401165,0.410401,0.316179,0.157595,0.011659,0.014020,0.062325,0.155296,0.000005,pass
19,0.355068,0.823718,0.724657,0.571305,1.249038,1.402038,1.312589,1.295315,1.144523,0.294491,...,0.363585,0.370897,0.310936,0.160329,0.008508,0.011638,0.057073,0.118503,0.000005,pass

BARINEL SCORES

,ry 23,ry 4,ry 13,cx 9,cx 7,ry 3,cx 15,cx 16,ry 12,ry 11,...,ry 10,x 2,ry 0,cx 6,cx 17,ry 22,ry 19,cx 18,ry 14,ry 5
sum,0.559078,0.553789,0.54913,0.54879,0.542955,0.540826,0.540228,0.535805,0.533345,0.531818,...,0.526873,0.526209,0.525438,0.523036,0.522959,0.520779,0.519745,0.518694,0.505156,0.493953

TARANTULA SCORES

,ry 23,ry 4,ry 13,cx 9,cx 7,ry 3,cx 15,cx 16,ry 12,ry 11,...,ry 10,x 2,ry 0,cx 6,cx 17,ry 22,ry 19,cx 18,ry 14,ry 5
sum,0.559078,0.553789,0.54913,0.54879,0.542955,0.540826,0.540228,0.535805,0.533345,0.531818,...,0.526873,0.526209,0.525438,0.523036,0.522959,0.520779,0.519745,0.518694,0.505156,0.493953

DSTAR SCORES

,cx 18,cx 17,cx 16,ry 19,cx 15,ry 20,ry 22,ry 21,ry 13,cx 7,...,ry 14,cx 9,ry 5,ry 1,x 2,ry 3,ry 4,ry 0,ry 11,ry 12
sum,14.634562,13.860927,13.352962,13.036727,12.98241,10.537384,6.694491,3.898635,2.844877,2.641814,...,1.346092,0.596822,0.402146,0.397316,0.061042,0.004167,0.003052,4.762328e-10,1.013295e-10,2.296422e-11

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_y_inGap_21_.qasm

100%|██████████| 10/10 [00:20<00:00,  2.09s/it]
100%|██████████| 10/10 [00:20<00:00,  2.04s/it]

,ry 23,ry 22,ry 21,y 20,ry 19,ry 18,cx 17,cx 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.656149,1.775125,1.035835,0.444710,1.985909,2.437155,2.629764,2.450124,2.215151,1.997629,...,0.295766,0.757711,0.730769,0.599052,0.297753,0.019838,0.024354,0.255772,0.000008,fail
1,0.467465,1.109866,0.795078,0.386260,1.450965,1.592568,1.841127,2.112553,1.761335,1.635311,...,0.271920,0.590146,0.553558,0.471426,0.232039,0.015907,0.019028,0.220906,0.000007,fail
2,0.640789,1.434900,1.208821,0.546023,2.085625,1.996291,2.076409,1.843236,1.862627,1.927120,...,0.310012,0.683546,0.663613,0.541135,0.251568,0.018029,0.020692,0.212730,0.000008,fail
3,0.409425,0.702475,0.792057,0.424636,1.436034,1.733628,1.847825,1.509889,1.500641,1.852672,...,0.295344,0.521278,0.565537,0.464023,0.202079,0.015262,0.019786,0.193163,0.000007,fail
4,0.499152,1.330738,0.933718,0.396996,1.708221,2.420176,2.527362,1.809283,1.891925,1.967546,...,0.238188,0.665866,0.688401,0.547459,0.275903,0.015269,0.021646,0.214509,0.000008,fail
5,0.456836,1.216232,0.848302,0.408404,1.788634,2.069428,2.152335,1.598600,1.559914,1.589374,...,0.263301,0.544518,0.568833,0.491379,0.240934,0.015334,0.017529,0.184185,0.000007,fail
6,0.709851,1.321413,1.085642,0.451478,1.544630,2.784656,3.088911,2.304036,2.085181,2.149536,...,0.329203,0.757223,0.804663,0.600659,0.263404,0.019466,0.025021,0.274253,0.000010,fail
7,0.586535,1.370780,0.665582,0.299844,1.501126,1.934905,2.168494,2.120025,1.802504,1.719342,...,0.201004,0.568847,0.570531,0.436835,0.216434,0.016593,0.019512,0.212991,0.000007,fail
8,0.496411,1.049476,0.795880,0.385271,1.318356,1.487967,1.738988,2.261760,2.298071,2.083381,...,0.231685,0.674144,0.692524,0.547702,0.253551,0.017767,0.022540,0.255231,0.000008,fail
9,0.547760,1.452421,1.002454,0.468152,1.529291,1.801760,2.029703,2.092891,1.821145,1.902870,...,0.356667,0.707455,0.716432,0.566517,0.270493,0.017790,0.021661,0.253435,0.000008,fail
10,0.496666,1.220352,0.728356,0.313149,2.071173,2.062230,2.010090,1.325328,1.529232,1.639578,...,0.195536,0.517188,0.529225,0.370877,0.182923,0.014205,0.016929,0.151888,0.000006,pass
11,0.570773,0.851317,0.971339,0.448534,0.981795,1.551783,1.702432,1.334457,0.947237,1.050737,...,0.306496,0.424495,0.444700,0.420841,0.189410,0.013088,0.014085,0.160506,0.000005,pass
12,0.309689,0.795383,0.465818,0.234628,1.114304,1.547317,1.568095,0.910738,0.787206,0.792375,...,0.116795,0.234323,0.215394,0.201188,0.111554,0.008266,0.006737,0.074015,0.000004,pass
13,0.479087,0.894653,0.517098,0.286458,1.331611,2.021720,2.215092,1.901497,1.493141,1.312600,...,0.304913,0.549718,0.523214,0.436667,0.203896,0.016403,0.016977,0.197425,0.000006,pass
14,0.511217,1.345689,0.635281,0.270325,1.743706,1.502578,1.521808,1.450604,1.355501,1.191430,...,0.170726,0.420827,0.432756,0.357504,0.217002,0.011642,0.014333,0.138083,0.000004,pass
15,0.369228,1.011287,0.600918,0.320513,1.362897,1.710416,1.886708,1.680886,1.509877,1.324819,...,0.284234,0.579784,0.516699,0.422488,0.202069,0.013806,0.016508,0.169844,0.000005,pass
16,0.281603,0.725599,0.646732,0.287429,1.182604,1.036306,1.013312,0.890256,0.964219,0.995483,...,0.209385,0.341519,0.399134,0.294972,0.154169,0.008126,0.012614,0.109616,0.000003,pass
17,0.322622,0.935930,0.547642,0.285892,1.006564,1.260154,1.443708,1.694619,1.446281,1.124114,...,0.240768,0.464937,0.449175,0.378117,0.196114,0.013290,0.014338,0.159790,0.000005,pass
18,0.535513,1.153663,0.814077,0.396766,2.056830,2.267842,2.377196,1.980523,1.919629,1.811133,...,0.233804,0.570992,0.617431,0.460471,0.230116,0.016431,0.020000,0.194961,0.000006,pass
19,0.476421,0.962114,0.692394,0.381995,1.226395,2.318011,2.598923,2.286944,2.104030,1.915908,...,0.321963,0.678617,0.684331,0.541893,0.247452,0.019530,0.020717,0.236475,0.000009,pass

BARINEL SCORES

,ry 13,ry 0,cx 14,ry 1,ry 21,ry 2,ry 9,cx 6,ry 11,cx 5,...,y 20,cx 16,ry 4,ry 22,ry 3,ry 23,cx 17,ry 18,cx 8,ry 19
sum,0.610437,0.591183,0.588588,0.588451,0.580584,0.580178,0.577999,0.576661,0.576532,0.575464,...,0.566292,0.565337,0.564144,0.563273,0.559581,0.556884,0.546535,0.539697,0.539445,0.537318

TARANTULA SCORES

,ry 13,ry 0,cx 14,ry 1,ry 21,ry 2,ry 9,cx 6,ry 11,cx 5,...,y 20,cx 16,ry 4,ry 22,ry 3,ry 23,cx 17,ry 18,cx 8,ry 19
sum,0.610437,0.591183,0.588588,0.588451,0.580584,0.580178,0.577999,0.576661,0.576532,0.575464,...,0.566292,0.565337,0.564144,0.563273,0.559581,0.556884,0.546535,0.539697,0.539445,0.537318

DSTAR SCORES

,cx 17,cx 16,cx 14,ry 18,cx 15,ry 19,ry 22,ry 21,cx 6,ry 12,...,cx 5,y 20,cx 8,ry 4,ry 1,ry 2,ry 3,ry 0,ry 10,ry 11
sum,17.236979,15.874792,15.302257,15.045193,14.689814,11.100769,8.187835,5.052289,2.900759,2.848873,...,1.997314,1.341257,0.629923,0.525426,0.447313,0.004417,0.002894,5.967274e-10,1.004629e-10,2.527679e-11

ERROR GATE LOCATION:
20
Now evolving the following mutant:  AddGate_ry_inGap_24_.qasm

100%|██████████| 10/10 [00:18<00:00,  1.80s/it]
100%|██████████| 10/10 [00:16<00:00,  1.62s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,ry 18,cx 17,cx 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.775898,1.503603,1.010714,2.434691,1.672713,1.141472,0.0,1.556679,1.047132,1.102449,...,0.671947,0.424110,0.600123,0.582564,0.229318,0.018390,0.020360,0.152128,0.000004,fail
1,0.481533,1.378235,0.713160,1.470298,2.075930,1.339084,0.0,1.063056,0.957803,0.926854,...,0.810592,0.551270,0.611145,0.616180,0.256906,0.017539,0.020102,0.197541,0.000005,fail
2,0.689335,1.425345,0.843166,2.299451,1.944322,1.247511,0.0,1.551459,1.249181,1.109892,...,0.774349,0.502124,0.699783,0.728255,0.291639,0.020278,0.021278,0.181103,0.000005,fail
3,0.597681,1.190641,0.765474,1.972565,1.984652,1.291505,0.0,1.348631,1.204209,1.274780,...,0.832599,0.490957,0.737297,0.717462,0.293671,0.019533,0.024575,0.193243,0.000005,fail
4,0.519716,1.314669,0.617975,2.475941,1.919660,1.285808,0.0,1.629339,1.136393,1.142616,...,0.829062,0.467108,0.652416,0.661646,0.232347,0.020449,0.021727,0.159757,0.000005,fail
5,0.717443,1.516856,0.887237,1.189625,1.875551,1.244573,0.0,0.930764,0.935777,0.796861,...,0.664750,0.482765,0.555760,0.541281,0.199043,0.015084,0.017788,0.173107,0.000004,fail
6,0.615816,1.166751,0.929438,2.277567,2.216653,1.434279,0.0,1.565148,1.225720,1.068446,...,0.956302,0.572880,0.743892,0.786710,0.308384,0.023626,0.025240,0.217451,0.000005,fail
7,0.621494,1.912133,1.307611,1.808812,2.205706,1.445820,0.0,1.225321,0.895875,1.016641,...,0.838406,0.627126,0.659707,0.652993,0.274756,0.022313,0.019915,0.242773,0.000004,fail
8,0.570824,1.257477,0.602546,1.791369,1.924373,1.230539,0.0,1.250553,0.986735,0.916837,...,0.780383,0.527522,0.611484,0.650234,0.287944,0.019410,0.018173,0.199120,0.000005,fail
9,0.510269,1.323404,1.047659,1.882720,1.858645,1.217853,0.0,1.205598,0.712149,0.755274,...,0.745566,0.526768,0.589287,0.613380,0.246710,0.019145,0.020564,0.189068,0.000004,fail
10,0.574062,1.658172,0.804566,1.616741,1.280499,0.872635,0.0,1.219043,1.080556,0.883074,...,0.547604,0.465220,0.540002,0.541528,0.237525,0.015016,0.018495,0.168682,0.000003,pass
11,0.540166,0.995357,0.735952,1.614914,1.540768,1.009981,0.0,1.141722,1.045122,1.112681,...,0.620158,0.473278,0.648771,0.596353,0.245670,0.015787,0.020398,0.217710,0.000004,pass
12,0.425115,0.512504,0.638499,1.064508,0.749661,0.409855,0.0,0.819879,0.881669,0.916077,...,0.458894,0.327363,0.494635,0.456710,0.179543,0.012354,0.014006,0.136132,0.000003,pass
13,0.515244,0.666993,0.531237,1.361445,1.346102,0.860973,0.0,0.896589,0.696467,0.612392,...,0.473805,0.342804,0.452860,0.437444,0.182440,0.012266,0.013772,0.116734,0.000003,pass
14,0.457677,0.898840,0.863041,1.224276,1.025999,0.704328,0.0,0.841529,0.587466,0.703737,...,0.475297,0.292223,0.421904,0.424153,0.184798,0.010487,0.014086,0.091329,0.000002,pass
15,0.591919,1.134762,1.044668,1.288401,1.432215,0.914373,0.0,0.963369,0.941611,0.823251,...,0.636355,0.427680,0.502960,0.519978,0.208250,0.017880,0.016305,0.171425,0.000004,pass
16,0.311536,0.566537,0.230205,0.735266,0.534274,0.317232,0.0,0.514148,0.425049,0.409293,...,0.234361,0.189317,0.238870,0.253572,0.099044,0.007416,0.007136,0.075623,0.000002,pass
17,0.441871,1.255267,0.528954,1.650080,1.252873,0.807275,0.0,1.164210,0.996164,0.958746,...,0.505421,0.433225,0.523270,0.500671,0.211090,0.016965,0.019872,0.166896,0.000003,pass
18,0.387305,0.850172,0.667429,0.496169,0.923991,0.521301,0.0,0.503081,0.736506,0.638105,...,0.429203,0.319246,0.425237,0.432477,0.181014,0.010471,0.014706,0.125721,0.000003,pass
19,0.477163,1.130264,0.649255,1.095359,1.130882,0.660882,0.0,0.897586,1.044561,1.079806,...,0.645399,0.450160,0.582066,0.582140,0.244235,0.015424,0.015702,0.184644,0.000004,pass

BARINEL SCORES

,ry 18,ry 19,ry 9,ry 20,cx 8,ry 0,cx 16,ry 3,ry 22,ry 13,...,cx 6,ry 4,ry 1,ry 21,ry 23,ry 12,cx 14,cx 15,ry 11,cx 17
sum,0.645301,0.636929,0.635603,0.617415,0.611267,0.598534,0.597933,0.593531,0.591306,0.587393,...,0.572192,0.570425,0.567019,0.565867,0.563664,0.559308,0.554075,0.55099,0.530934,NaN

TARANTULA SCORES

,ry 18,ry 19,ry 9,ry 20,cx 8,ry 0,cx 16,ry 3,ry 22,ry 13,...,cx 6,ry 4,ry 1,ry 21,ry 23,ry 12,cx 14,cx 15,ry 11,cx 17
sum,0.645301,0.636929,0.635603,0.617415,0.611267,0.598534,0.597933,0.593531,0.591306,0.587393,...,0.572192,0.570425,0.567019,0.565867,0.563664,0.559308,0.554075,0.55099,0.530934,NaN

DSTAR SCORES

,ry 19,ry 20,ry 22,ry 18,cx 16,cx 15,cx 14,ry 21,cx 8,ry 9,...,ry 12,ry 13,ry 4,ry 1,ry 2,ry 3,ry 0,ry 10,ry 11,cx 17
sum,18.250786,17.351171,9.949494,9.711102,9.366354,5.811861,5.636231,4.56009,4.157491,3.215029,...,1.003774,0.590774,0.573608,0.316907,0.004331,0.003782,2.042963e-10,3.347759e-11,4.794208e-12,0.0

ERROR GATE LOCATION:
19
Now evolving the following mutant:  AddGate_rxx_inGap_5_.qasm

100%|██████████| 10/10 [00:21<00:00,  2.16s/it]
100%|██████████| 10/10 [00:21<00:00,  2.19s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,ry 5,rxx 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.755577,1.428546,0.721458,2.018880,2.456712,2.597289,2.160939,2.371068,2.155731,0.530195,...,0.647164,0.728116,0.530438,0.283770,0.447987,0.006148,0.026255,0.232915,0.000008,fail
1,0.555771,1.169518,0.855833,1.351390,2.130635,2.434061,2.417034,1.881769,1.521280,0.377398,...,0.670591,0.631704,0.521986,0.242116,0.435486,0.005733,0.022746,0.240585,0.000008,fail
2,0.576542,1.245238,0.897748,1.281512,2.126552,2.379606,2.153612,2.091602,2.039548,0.484371,...,0.710844,0.794467,0.627920,0.312801,0.420905,0.006664,0.027268,0.255914,0.000008,fail
3,0.772290,1.323218,0.925107,2.107915,2.069672,2.105399,1.527022,1.344481,1.414775,0.375556,...,0.496633,0.527814,0.389577,0.171469,0.381203,0.004583,0.018747,0.173454,0.000006,fail
4,0.490935,1.351084,0.875228,1.676783,1.472831,1.700729,1.894516,1.436465,1.979183,0.523386,...,0.642565,0.624864,0.543758,0.278766,0.366090,0.006930,0.021735,0.252259,0.000006,fail
5,0.569617,0.856280,0.650905,1.767050,1.949804,1.975445,1.575542,1.777778,1.802429,0.429491,...,0.531154,0.622859,0.418863,0.189742,0.426765,0.004668,0.023004,0.188456,0.000006,fail
6,0.532651,1.349488,0.897824,2.160450,2.672990,2.908660,2.739191,2.612536,2.292035,0.658180,...,0.842090,0.851345,0.671808,0.315880,0.531299,0.007480,0.028032,0.283606,0.000010,fail
7,0.526834,1.049914,0.557939,1.735151,1.732928,1.882556,2.061626,2.014911,2.005428,0.526001,...,0.599112,0.578434,0.457076,0.245027,0.407746,0.005922,0.021713,0.216363,0.000006,fail
8,0.744153,1.535867,0.965617,2.347202,1.654111,1.646221,1.719608,1.558406,1.102037,0.367064,...,0.509576,0.440756,0.344354,0.159515,0.324960,0.004579,0.014958,0.141200,0.000005,fail
9,0.704430,1.112310,0.899389,1.241018,2.099322,2.322511,1.746029,1.856314,2.116587,0.421823,...,0.603102,0.717909,0.536012,0.258464,0.415899,0.006027,0.024078,0.223797,0.000008,fail
10,0.413276,1.023237,0.776312,1.057246,1.433131,1.637170,1.579783,1.396957,1.722094,0.427884,...,0.563978,0.577267,0.434039,0.204663,0.312509,0.005288,0.020663,0.205586,0.000006,pass
11,0.503444,0.855198,0.761059,1.192468,0.969994,1.108773,1.499266,1.610284,1.691791,0.346165,...,0.466207,0.565464,0.410955,0.198459,0.331861,0.004440,0.021241,0.192148,0.000006,pass
12,0.365897,0.921893,0.577587,1.098751,1.343075,1.481418,1.529279,1.372579,1.345336,0.295487,...,0.454837,0.436428,0.354584,0.177472,0.313893,0.004147,0.015826,0.150596,0.000005,pass
13,0.491342,1.152989,0.524331,1.153472,1.395934,1.533745,1.640946,1.454077,1.121742,0.276828,...,0.435337,0.329027,0.275915,0.129258,0.281918,0.003479,0.012841,0.124759,0.000005,pass
14,0.760373,1.116733,0.832249,1.583469,1.963268,2.152743,2.170462,2.065434,1.953654,0.503925,...,0.622299,0.640226,0.476337,0.224504,0.452259,0.005971,0.023308,0.235117,0.000008,pass
15,0.322361,0.700821,0.572234,1.032663,1.060535,1.212859,1.324474,1.314505,1.355315,0.364525,...,0.435601,0.488953,0.375392,0.194607,0.251349,0.004414,0.016170,0.165278,0.000005,pass
16,0.268274,1.020352,0.602140,1.574105,1.423227,1.590004,1.739918,1.685257,1.554314,0.434766,...,0.591200,0.563137,0.494213,0.249132,0.354194,0.005488,0.019755,0.193529,0.000005,pass
17,0.577133,1.235355,0.866726,1.451512,1.488622,1.700710,1.942249,1.745722,1.608866,0.458093,...,0.580118,0.558484,0.459978,0.234047,0.312878,0.005578,0.019142,0.211947,0.000007,pass
18,0.520773,1.165803,1.088083,1.475236,2.436025,2.654265,2.231139,2.067127,1.601617,0.564425,...,0.718431,0.726649,0.664851,0.322406,0.437367,0.007198,0.022365,0.224552,0.000008,pass
19,0.552275,1.009229,0.806053,1.323572,1.880696,2.091714,2.110683,1.834328,1.634634,0.430984,...,0.568868,0.517087,0.428015,0.227955,0.388320,0.005829,0.018924,0.202116,0.000007,pass

BARINEL SCORES

,ry 20,ry 19,ry 23,cx 18,ry 22,rxx 4,ry 13,cx 7,ry 2,ry 10,...,ry 12,cx 8,cx 16,ry 14,ry 11,ry 5,ry 3,cx 9,cx 17,ry 21
sum,0.577455,0.569506,0.566051,0.561217,0.549062,0.547518,0.546966,0.546789,0.545732,0.543251,...,0.535147,0.534901,0.533798,0.533558,0.532463,0.531931,0.531219,0.530719,0.529485,0.526839

TARANTULA SCORES

,ry 20,ry 19,ry 23,cx 18,ry 22,rxx 4,ry 13,cx 7,ry 2,ry 10,...,ry 12,cx 8,cx 16,ry 14,ry 11,ry 5,ry 3,cx 9,cx 17,ry 21
sum,0.577455,0.569506,0.566051,0.561217,0.549062,0.547518,0.546966,0.546789,0.545732,0.543251,...,0.535147,0.534901,0.533798,0.533558,0.532463,0.531931,0.531219,0.530719,0.529485,0.526839

DSTAR SCORES

,cx 18,ry 19,cx 17,ry 20,cx 16,cx 15,ry 22,ry 21,ry 13,cx 7,...,ry 14,rxx 4,cx 9,ry 5,ry 1,ry 2,ry 3,ry 0,ry 11,ry 12
sum,17.741195,16.332506,14.397939,13.635934,13.520756,13.272285,7.637648,3.907319,2.871676,2.758462,...,1.561972,1.286922,0.594579,0.496571,0.409696,0.005125,0.000343,5.017316e-10,1.041539e-10,2.417655e-11

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_y_inGap_2_.qasm

100%|██████████| 10/10 [00:22<00:00,  2.28s/it]
100%|██████████| 10/10 [00:20<00:00,  2.09s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,ry 5,ry 4,ry 3,ry 2,y 1,ry 0,pass/fail
0,0.547918,1.116044,0.828699,1.911036,2.463200,2.689762,2.398342,2.290250,1.867434,0.607390,...,0.756027,0.660026,0.519066,0.236892,0.019040,0.021238,0.233152,0.129133,0.000009,fail
1,0.398945,1.139081,0.571594,1.666592,1.305446,1.498186,1.937008,1.990363,1.916506,0.395079,...,0.591216,0.610690,0.458019,0.232796,0.013344,0.020821,0.218915,0.116433,0.000006,fail
2,0.515786,1.119015,0.706448,1.474638,1.849568,2.073026,2.061047,1.976270,2.022630,0.453133,...,0.656223,0.633191,0.453316,0.199059,0.015838,0.021400,0.231639,0.123443,0.000008,fail
3,0.452447,1.359590,0.714930,1.971106,2.051137,2.268996,2.269042,1.774695,1.727666,0.541305,...,0.689309,0.590201,0.489439,0.258265,0.014718,0.020103,0.246947,0.131206,0.000007,fail
4,0.685795,1.621202,0.965164,2.012002,2.094435,2.224594,2.289354,2.174776,1.540293,0.408568,...,0.648157,0.607682,0.464637,0.214147,0.018651,0.018574,0.197896,0.112708,0.000007,fail
5,0.535113,1.199574,0.922328,1.773930,2.167102,2.296725,1.941843,1.786608,1.662197,0.312342,...,0.576300,0.565386,0.472944,0.219459,0.016206,0.017962,0.188291,0.108884,0.000007,fail
6,0.458938,0.904400,0.634197,1.694201,2.049939,2.341614,2.505080,2.318862,2.061727,0.586673,...,0.757303,0.729831,0.572465,0.269585,0.019736,0.024643,0.277852,0.159548,0.000008,fail
7,0.515799,1.197721,0.659944,1.637111,2.386691,2.604302,2.462656,2.574909,2.129104,0.585670,...,0.736284,0.696884,0.540212,0.275590,0.018329,0.021692,0.232792,0.127286,0.000009,fail
8,0.570131,1.059950,0.590582,1.567171,1.381525,1.597233,1.890678,1.847208,1.757252,0.370111,...,0.572618,0.598893,0.417593,0.194154,0.014860,0.019820,0.207072,0.114041,0.000006,fail
9,0.555791,0.908214,0.759075,1.367491,1.183908,1.301522,1.644068,1.610867,1.344733,0.227818,...,0.477895,0.502610,0.384586,0.188407,0.012598,0.015489,0.160831,0.093223,0.000005,fail
10,0.494841,1.476145,0.901621,2.175980,1.787444,1.901528,1.927110,1.737707,1.944727,0.491714,...,0.616498,0.606386,0.483461,0.227676,0.014629,0.021858,0.220388,0.120367,0.000006,pass
11,0.499023,1.202337,0.598465,2.020690,2.069500,2.272137,2.142341,1.743187,1.947878,0.530169,...,0.616872,0.584213,0.518961,0.265780,0.017970,0.020817,0.249502,0.141118,0.000008,pass
12,0.497021,1.551107,0.816247,1.941417,2.507654,2.611023,1.782106,1.222350,1.300053,0.496000,...,0.527140,0.488019,0.434731,0.239397,0.016811,0.014542,0.185367,0.101212,0.000006,pass
13,0.333630,0.940822,0.785667,1.422337,1.560052,1.613148,1.182788,1.623082,1.546015,0.348332,...,0.441817,0.572391,0.475153,0.237437,0.013081,0.018890,0.152651,0.089869,0.000004,pass
14,0.288396,0.851920,0.462970,1.131755,1.233064,1.256874,1.053207,0.933577,0.687901,0.232885,...,0.280866,0.256627,0.271247,0.148223,0.008425,0.009140,0.085656,0.056483,0.000003,pass
15,0.411530,0.912423,0.543547,1.374395,1.531128,1.643896,1.589023,1.516403,1.159455,0.317935,...,0.468153,0.444667,0.323989,0.159499,0.012660,0.012904,0.148673,0.084852,0.000005,pass
16,0.561508,1.297229,0.748818,1.536789,2.337639,2.595495,2.188181,2.115934,2.244656,0.577333,...,0.711760,0.744787,0.585410,0.303253,0.019212,0.023592,0.260710,0.139835,0.000009,pass
17,0.564121,1.434699,0.917007,1.277038,2.108478,2.248802,1.783415,1.282790,1.166354,0.394560,...,0.504237,0.490796,0.407805,0.183412,0.016239,0.015243,0.169196,0.097544,0.000007,pass
18,0.487591,1.191644,0.731142,1.362811,1.680841,1.932955,2.054361,1.786836,1.709497,0.471803,...,0.684689,0.618016,0.501047,0.230608,0.015523,0.019892,0.230181,0.123810,0.000007,pass
19,0.505413,1.015378,0.819876,1.775399,1.476886,1.496936,1.324232,1.342503,1.113113,0.321467,...,0.447736,0.480650,0.369396,0.175027,0.011984,0.014811,0.147533,0.077342,0.000004,pass

BARINEL SCORES

,ry 12,ry 11,cx 16,ry 10,cx 17,ry 13,cx 8,cx 15,ry 2,ry 0,...,ry 4,cx 6,ry 14,cx 18,ry 20,ry 5,ry 19,ry 21,ry 22,cx 9
sum,0.573015,0.57232,0.570695,0.559982,0.556893,0.553608,0.549382,0.548858,0.542708,0.542446,...,0.527092,0.521932,0.51764,0.516348,0.515965,0.513237,0.5086,0.50094,0.494704,0.469249

TARANTULA SCORES

,ry 12,ry 11,cx 16,ry 10,cx 17,ry 13,cx 8,cx 15,ry 2,ry 0,...,ry 4,cx 6,ry 14,cx 18,ry 20,ry 5,ry 19,ry 21,ry 22,cx 9
sum,0.573015,0.57232,0.570695,0.559982,0.556893,0.553608,0.549382,0.548858,0.542708,0.542446,...,0.527092,0.521932,0.51764,0.516348,0.515965,0.513237,0.5086,0.50094,0.494704,0.469249

DSTAR SCORES

,cx 17,cx 16,cx 18,cx 15,ry 19,ry 20,ry 22,ry 21,ry 13,cx 8,...,ry 14,ry 5,cx 9,ry 2,y 1,ry 3,ry 4,ry 0,ry 11,ry 12
sum,16.943289,16.357299,14.764958,13.097056,12.669584,11.20602,6.178001,3.120629,2.748678,2.728721,...,1.420298,0.430274,0.409396,0.406732,0.134007,0.004001,0.002629,4.979760e-10,1.240608e-10,2.755133e-11

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_cz_inGap_17_.qasm

100%|██████████| 10/10 [00:26<00:00,  2.67s/it]
100%|██████████| 10/10 [00:26<00:00,  2.63s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cz 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.718888,1.493707,1.139380,2.248043,2.184855,2.260117,2.277734,1.901412,2.093537,1.568880,...,1.465129,0.763708,0.720635,0.733844,0.315715,0.026817,0.029101,0.406053,0.000006,fail
1,0.453489,0.888976,0.730227,1.669455,2.088396,2.290820,1.882938,1.532248,1.791861,1.978414,...,1.361364,0.716440,0.690078,0.656104,0.312620,0.019042,0.021386,0.346554,0.000007,fail
2,0.654486,1.433670,1.057584,1.934943,2.292523,2.608632,2.772195,2.217389,2.402265,2.084494,...,1.653343,0.965686,0.817599,0.844583,0.405398,0.029506,0.034130,0.387993,0.000009,fail
3,0.528922,1.447623,0.819466,2.303942,2.222644,2.396586,2.256303,1.699776,2.293508,2.155192,...,1.792273,0.950634,0.875867,0.770466,0.396653,0.022316,0.028893,0.437705,0.000007,fail
4,0.430454,0.928953,0.414169,1.301740,1.853335,1.971828,1.542713,1.188949,1.389334,1.289960,...,0.897218,0.554961,0.469631,0.465083,0.193119,0.019196,0.018803,0.180175,0.000005,fail
5,0.412548,1.220292,0.970619,1.672565,1.415351,1.509748,1.567027,1.439916,1.204137,1.064203,...,0.724206,0.472015,0.469851,0.511459,0.203938,0.013759,0.017951,0.259532,0.000006,fail
6,0.636353,1.486361,0.917092,2.138346,2.038200,2.198908,2.220712,1.831004,1.792329,1.334249,...,1.145808,0.764835,0.601583,0.617891,0.218458,0.025807,0.027416,0.241011,0.000008,fail
7,0.600436,1.287159,0.797287,1.869120,2.222599,2.429026,2.322978,1.750359,2.165335,1.772431,...,1.482801,0.846566,0.687399,0.693457,0.343246,0.026275,0.029507,0.327363,0.000006,fail
8,0.587377,0.923919,0.646772,1.612467,2.020106,2.313365,2.404909,1.883916,2.137298,1.846192,...,1.379496,0.832973,0.740263,0.731464,0.358709,0.022747,0.026618,0.319657,0.000008,fail
9,0.613440,0.898016,0.702428,1.910163,1.903194,2.085275,1.916360,1.506057,1.914179,1.978191,...,1.475424,0.749222,0.668970,0.674906,0.311994,0.024624,0.024154,0.321398,0.000007,fail
10,0.436908,1.142052,0.767632,1.429783,2.620528,2.801897,1.666302,1.641320,1.595261,1.938407,...,1.094548,0.611432,0.725791,0.679624,0.327435,0.019092,0.020738,0.362447,0.000008,pass
11,0.568438,1.194530,0.946757,2.096856,2.587393,2.620608,1.707285,1.654286,1.683478,1.742592,...,1.137476,0.614151,0.678736,0.661736,0.246986,0.026267,0.022905,0.376985,0.000006,pass
12,0.587662,1.267223,0.937675,2.297762,2.350635,2.467406,2.046534,1.772918,1.827012,1.884863,...,1.264620,0.757889,0.755048,0.731356,0.341339,0.024989,0.025966,0.362305,0.000007,pass
13,0.381218,1.025801,0.745050,1.323550,1.684572,1.888170,1.911530,1.598075,1.863610,1.858810,...,1.553337,0.757154,0.801367,0.776593,0.418378,0.019310,0.024849,0.388173,0.000008,pass
14,0.532061,1.351246,0.924685,2.118594,2.042546,2.301163,2.305325,1.818200,2.041013,2.030418,...,1.425327,0.870302,0.763417,0.753285,0.373937,0.024209,0.028604,0.324445,0.000007,pass
15,0.268043,0.365896,0.466005,0.830187,1.114657,1.234430,1.079370,0.899390,1.100822,1.352486,...,0.874814,0.424445,0.474744,0.465111,0.228350,0.012110,0.012817,0.241703,0.000005,pass
16,0.555704,1.056947,0.828372,1.216440,1.400473,1.583611,1.751080,1.418289,1.540947,1.552483,...,1.206963,0.646225,0.630758,0.628678,0.320472,0.018073,0.021906,0.287003,0.000006,pass
17,0.495955,1.185542,0.700555,1.562818,1.455163,1.558739,1.644245,1.309000,1.531876,1.015926,...,1.122568,0.566589,0.458290,0.500687,0.199435,0.019565,0.021349,0.238284,0.000005,pass
18,0.602579,0.977480,0.866029,1.825973,1.645431,1.671895,1.438327,1.396002,1.276063,1.252772,...,0.874411,0.484289,0.570687,0.610459,0.236725,0.020195,0.018174,0.297043,0.000007,pass
19,0.546116,1.320405,0.991741,1.161910,1.649873,1.839932,1.572144,1.394456,1.452129,1.584862,...,1.048961,0.598564,0.692395,0.678473,0.326517,0.015561,0.020725,0.309601,0.000007,pass

BARINEL SCORES

,cx 17,cx 15,cx 7,ry 2,ry 20,ry 3,cx 8,ry 9,cz 16,ry 23,...,cx 14,cx 5,cx 6,ry 0,ry 13,ry 4,ry 1,ry 21,ry 10,ry 11
sum,0.552783,0.546609,0.5461,0.541939,0.540506,0.535763,0.535509,0.532934,0.532165,0.53118,...,0.512897,0.508087,0.507171,0.504011,0.503491,0.503312,0.503075,0.500627,0.49719,0.493328

TARANTULA SCORES

,cx 17,cx 15,cx 7,ry 2,ry 20,ry 3,cx 8,ry 9,cz 16,ry 23,...,cx 14,cx 5,cx 6,ry 0,ry 13,ry 4,ry 1,ry 21,ry 10,ry 11
sum,0.552783,0.546609,0.5461,0.541939,0.540506,0.535763,0.535509,0.532934,0.532165,0.53118,...,0.512897,0.508087,0.507171,0.504011,0.503491,0.503312,0.503075,0.500627,0.49719,0.493328

DSTAR SCORES

,cx 17,cx 18,ry 19,cx 15,ry 20,cz 16,cx 14,cx 8,ry 22,ry 21,...,ry 23,ry 9,ry 13,ry 1,ry 4,ry 2,ry 3,ry 0,ry 10,ry 11
sum,16.514529,16.245194,14.349843,14.202473,13.463754,11.538752,11.118656,8.283367,6.904173,3.6952,...,2.121511,1.779217,1.096061,0.789838,0.719124,0.006512,0.005191,4.700526e-10,6.239476e-11,2.332780e-11

ERROR GATE LOCATION:
16
Now evolving the following mutant:  AddGate_rx_inGap_10_.qasm

100%|██████████| 10/10 [00:23<00:00,  2.38s/it]
100%|██████████| 10/10 [00:23<00:00,  2.32s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.753101,1.381531,0.665965,1.688092,2.605691,2.897670,2.672231,2.412188,2.151335,0.578849,...,1.167637,0.679941,1.162642,1.202667,0.482355,0.026672,0.035312,0.310232,0.000002,fail
1,0.497115,1.090915,0.890776,1.345274,1.981948,2.156405,1.981417,1.779721,1.517033,0.402439,...,1.060533,0.625449,0.915238,0.963950,0.406614,0.021358,0.029744,0.267238,0.000003,fail
2,0.532777,1.267275,0.975813,1.620836,2.638747,2.765701,1.849296,1.876565,1.858209,0.429653,...,1.252077,0.872430,1.107376,1.141200,0.497708,0.028432,0.032794,0.384458,0.000004,fail
3,0.613695,1.577428,0.986018,1.133710,2.708947,3.128362,2.825938,2.601134,2.665340,0.653161,...,1.491067,0.694001,1.330371,1.427956,0.547353,0.031003,0.033284,0.317135,0.000003,fail
4,0.460091,0.855865,0.584829,1.379432,2.200722,2.493726,2.268232,2.189351,2.245040,0.604015,...,1.203825,0.596155,1.122609,1.210814,0.462941,0.023780,0.033777,0.296640,0.000002,fail
5,0.467956,1.215199,0.895758,1.673333,2.090124,2.142268,1.408205,1.660472,1.762373,0.403133,...,0.861917,0.739336,0.929620,0.930061,0.419037,0.022556,0.026021,0.348680,0.000002,fail
6,0.459712,1.115748,0.747269,1.991157,2.045237,2.159789,1.746850,1.840079,1.813146,0.446883,...,1.042150,0.787174,0.940110,0.979893,0.418140,0.026187,0.026642,0.346265,0.000003,fail
7,0.654354,1.422721,0.790100,2.250823,2.194409,2.240905,1.823547,1.858034,1.561422,0.335390,...,0.903378,0.811657,0.995178,0.987153,0.431474,0.023198,0.028025,0.370675,0.000002,fail
8,0.688588,1.368823,0.970400,1.746532,2.214784,2.423062,2.096109,2.016552,2.007092,0.447999,...,1.276109,0.657098,1.092228,1.148298,0.459743,0.024655,0.028540,0.315256,0.000003,fail
9,0.617608,1.375547,0.815726,1.767051,2.224878,2.338363,1.821008,1.817633,1.230666,0.328207,...,0.998373,0.713713,0.882264,0.941664,0.397068,0.023008,0.025552,0.297225,0.000003,fail
10,0.345971,0.638780,0.684334,1.481390,0.931981,0.915428,0.942477,0.901814,0.778999,0.203472,...,0.448668,0.507471,0.427536,0.408956,0.216877,0.012912,0.017459,0.201538,0.000002,pass
11,0.533421,0.766595,0.686995,1.640366,2.374122,2.449667,1.689552,1.669661,1.389769,0.398224,...,1.019819,0.703811,0.974766,1.010030,0.402800,0.024509,0.030590,0.345514,0.000002,pass
12,0.485451,1.287433,0.815859,1.575921,1.965788,1.937161,1.095098,1.106632,1.120283,0.386497,...,0.732916,0.626921,0.797035,0.801412,0.341635,0.018508,0.026781,0.335165,0.000002,pass
13,0.535752,1.012872,0.905990,1.966815,2.298294,2.422725,1.863126,1.769043,1.862305,0.573363,...,1.139478,0.808448,0.963090,1.024952,0.394267,0.029599,0.033746,0.368557,0.000003,pass
14,0.426421,0.995228,0.425413,1.301495,2.015136,2.096843,1.470018,1.199083,1.121024,0.351001,...,0.706722,0.557784,0.767420,0.789034,0.313092,0.020016,0.023665,0.280885,0.000001,pass
15,0.415102,1.192573,0.856636,1.263062,1.841568,2.166195,2.330795,2.000408,1.667065,0.509274,...,1.084650,0.591838,0.823559,0.965351,0.310378,0.025857,0.027768,0.206781,0.000003,pass
16,0.414160,1.107524,0.799490,1.338221,1.703431,1.903481,1.948221,1.967818,2.058571,0.470086,...,1.040894,0.614059,0.847151,0.862778,0.346429,0.024251,0.024232,0.245733,0.000002,pass
17,0.582306,1.162533,0.799654,1.723419,1.508451,1.658776,1.898456,1.589758,1.555855,0.320394,...,0.831163,0.639649,0.814676,0.822776,0.324955,0.023917,0.022610,0.269156,0.000003,pass
18,0.510146,1.464718,0.905834,1.731162,2.207839,2.404522,2.140543,1.635330,1.268552,0.450358,...,0.954964,0.762063,0.840096,0.944679,0.364169,0.028290,0.029039,0.293612,0.000003,pass
19,0.596332,1.329332,0.896178,1.758156,1.637078,1.822775,2.092523,2.231772,2.182032,0.488376,...,1.058426,0.638541,0.962443,0.963538,0.418430,0.024846,0.024471,0.286935,0.000002,pass

BARINEL SCORES

,ry 4,ry 10,rx 9,cx 6,ry 13,cx 5,ry 11,cx 15,cx 18,cx 8,...,cx 17,ry 22,ry 2,ry 1,ry 0,ry 14,cx 7,ry 3,ry 21,ry 20
sum,0.568469,0.563202,0.560706,0.560439,0.560154,0.55992,0.55769,0.556293,0.555798,0.555225,...,0.539802,0.536258,0.535113,0.53449,0.531578,0.527258,0.526651,0.518763,0.516966,0.512605

TARANTULA SCORES

,ry 4,ry 10,rx 9,cx 6,ry 13,cx 5,ry 11,cx 15,cx 18,cx 8,...,cx 17,ry 22,ry 2,ry 1,ry 0,ry 14,cx 7,ry 3,ry 21,ry 20
sum,0.568469,0.563202,0.560706,0.560439,0.560154,0.55992,0.55769,0.556293,0.555798,0.555225,...,0.539802,0.536258,0.535113,0.53449,0.531578,0.527258,0.526651,0.518763,0.516966,0.512605

DSTAR SCORES

,cx 18,ry 19,cx 16,cx 17,cx 15,ry 20,ry 22,cx 8,cx 5,cx 6,...,ry 10,ry 23,ry 4,ry 14,ry 1,ry 2,ry 3,ry 11,ry 0,ry 12
sum,20.565038,18.41971,15.421999,15.287361,14.152614,10.684062,7.660975,6.663347,6.429387,6.026031,...,2.3786,2.223297,1.522546,1.514687,0.824945,0.008754,0.006149,1.157016e-10,6.749658e-11,2.798674e-11

ERROR GATE LOCATION:
9
Now evolving the following mutant:  AddGate_rz_inGap_22_.qasm

100%|██████████| 10/10 [00:22<00:00,  2.21s/it]
100%|██████████| 10/10 [00:18<00:00,  1.87s/it]

,ry 23,ry 22,rz 21,ry 20,ry 19,ry 18,cx 17,cx 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.436202,1.158012,0.404068,0.634351,1.796729,1.754181,1.905198,1.894814,2.018135,2.231799,...,0.206080,0.644951,0.658130,0.523916,0.255373,0.015758,0.021703,0.241557,0.000007,fail
1,0.565855,1.454964,0.462536,1.021732,1.880764,2.378580,2.615277,2.232598,2.033088,2.215048,...,0.338912,0.776345,0.779166,0.636253,0.313910,0.019036,0.024784,0.276190,0.000008,fail
2,0.642692,1.530965,0.477688,0.996634,1.495787,1.962872,2.161330,2.038998,1.614803,1.555192,...,0.322090,0.630855,0.592598,0.474171,0.225020,0.016665,0.018668,0.216662,0.000007,fail
3,0.594162,1.832063,0.572757,0.951636,2.036819,2.397946,2.597689,2.592751,2.172803,2.010669,...,0.335763,0.760888,0.686526,0.634550,0.347056,0.019470,0.023361,0.266231,0.000008,fail
4,0.557220,0.958593,0.300675,0.856766,1.497308,1.902440,2.133109,2.033226,2.106618,1.941974,...,0.307557,0.680790,0.703443,0.535108,0.245947,0.016084,0.022239,0.221236,0.000007,fail
5,0.656887,1.409716,0.445389,0.912790,1.852050,2.068718,2.311187,2.505744,2.064498,1.669830,...,0.350239,0.757500,0.677261,0.566358,0.283965,0.020437,0.022497,0.251192,0.000007,fail
6,0.542835,1.151213,0.383162,0.878930,1.608989,2.325010,2.450512,1.834984,1.902395,1.416762,...,0.264797,0.525645,0.549229,0.457935,0.205238,0.016383,0.016846,0.151223,0.000007,fail
7,0.467399,1.235524,0.400311,0.644371,1.406402,1.617723,1.643826,1.278993,1.453551,1.119013,...,0.166130,0.400380,0.387338,0.305492,0.144783,0.009665,0.012635,0.092881,0.000005,fail
8,0.584435,1.342494,0.436259,1.003730,2.170997,3.020696,3.198912,2.245942,1.902260,2.070611,...,0.400647,0.789619,0.787958,0.681412,0.317955,0.019801,0.024761,0.272927,0.000010,fail
9,0.616602,1.188559,0.369847,0.940913,1.468199,1.858440,2.116432,2.137698,2.227382,2.059905,...,0.303559,0.663714,0.704179,0.530204,0.242993,0.017500,0.022448,0.228338,0.000008,fail
10,0.471876,0.817299,0.271870,0.615205,0.550369,1.044733,1.279170,1.579369,1.677235,1.520063,...,0.207608,0.457505,0.502533,0.375945,0.183654,0.010783,0.015906,0.162971,0.000006,pass
11,0.450314,0.851930,0.304512,0.679762,1.519921,2.204161,2.347819,1.724827,1.639126,1.694662,...,0.296829,0.541136,0.579056,0.504260,0.235115,0.015817,0.019483,0.193132,0.000007,pass
12,0.462172,1.048474,0.327087,0.695826,1.535220,1.567070,1.836420,2.091089,1.853269,2.068707,...,0.292072,0.660365,0.710861,0.558069,0.308940,0.016142,0.024232,0.279444,0.000007,pass
13,0.284190,0.824244,0.302240,0.515508,1.207066,1.581028,1.784744,1.930805,1.874860,1.570437,...,0.191158,0.559147,0.479188,0.411509,0.212633,0.012983,0.016039,0.187604,0.000006,pass
14,0.555997,1.251876,0.397927,0.781366,1.912383,1.751581,1.849005,1.915014,1.828515,1.669685,...,0.215325,0.586837,0.572067,0.508177,0.255031,0.016827,0.019178,0.206277,0.000006,pass
15,0.375777,0.905129,0.312034,0.550072,1.535032,1.523473,1.555186,1.251709,1.448007,1.277382,...,0.144550,0.428181,0.416970,0.346848,0.162634,0.010650,0.013759,0.119666,0.000005,pass
16,0.574301,1.036729,0.315050,0.683083,1.211714,1.605048,1.901880,2.359418,2.427443,2.315790,...,0.212640,0.657872,0.715009,0.524671,0.276840,0.018569,0.022876,0.265531,0.000008,pass
17,0.475714,1.120842,0.359575,0.702761,1.648171,2.079145,2.460389,2.752712,2.464375,2.281761,...,0.341766,0.836202,0.826524,0.623560,0.302371,0.021140,0.026456,0.311947,0.000009,pass
18,0.472268,0.867554,0.289488,0.713363,1.320379,0.957170,0.988659,1.097393,0.905301,0.892815,...,0.160032,0.309615,0.362945,0.278082,0.131433,0.011427,0.012004,0.124081,0.000003,pass
19,0.330237,0.793007,0.253789,0.431264,0.879546,1.333338,1.487509,1.286612,1.035167,0.733870,...,0.149488,0.327623,0.273134,0.302609,0.170070,0.009456,0.008501,0.108029,0.000004,pass

BARINEL SCORES

,ry 22,ry 20,ry 18,rz 21,cx 8,cx 17,ry 19,ry 23,ry 9,cx 7,...,ry 2,ry 11,ry 12,cx 16,ry 4,ry 13,cx 14,cx 15,ry 1,ry 10
sum,0.582203,0.581316,0.576352,0.575757,0.575309,0.56945,0.563769,0.559871,0.554034,0.55278,...,0.540567,0.538903,0.53806,0.536184,0.535628,0.533286,0.533011,0.531955,0.531092,0.528059

TARANTULA SCORES

,ry 22,ry 20,ry 18,rz 21,cx 8,cx 17,ry 19,ry 23,ry 9,cx 7,...,ry 2,ry 11,ry 12,cx 16,ry 4,ry 13,cx 14,cx 15,ry 1,ry 10
sum,0.582203,0.581316,0.576352,0.575757,0.575309,0.56945,0.563769,0.559871,0.554034,0.55278,...,0.540567,0.538903,0.53806,0.536184,0.535628,0.533286,0.533011,0.531955,0.531092,0.528059

DSTAR SCORES

,cx 17,ry 18,cx 16,cx 15,cx 14,ry 19,ry 22,ry 20,cx 7,cx 6,...,ry 13,rz 21,cx 8,ry 4,ry 1,ry 2,ry 3,ry 0,ry 10,ry 11
sum,19.466801,17.667722,15.451211,13.99741,12.854996,12.70694,9.011764,4.776231,2.861536,2.758496,...,1.600567,1.377035,0.734936,0.544825,0.411538,0.00433,0.002876,5.522519e-10,1.056992e-10,2.562026e-11

ERROR GATE LOCATION:
21
Now evolving the following mutant:  AddGate_ry_inGap_4_.qasm

100%|██████████| 10/10 [00:23<00:00,  2.31s/it]
100%|██████████| 10/10 [00:22<00:00,  2.23s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,ry 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.437548,1.149131,0.667285,1.619085,1.897283,1.978907,1.316398,1.433228,1.437475,0.438465,...,0.494066,0.530617,0.417824,0.175886,0.012777,0.191388,0.016639,0.164782,0.000006,fail
1,0.688674,1.336121,0.968026,1.496185,1.788108,1.948455,1.807742,1.650561,1.656495,0.361059,...,0.574394,0.602617,0.426572,0.161501,0.018816,0.276605,0.021741,0.210930,0.000007,fail
2,0.635821,1.317691,0.751574,1.646177,2.387120,2.487720,1.727115,1.798579,1.515154,0.381146,...,0.522525,0.575800,0.441656,0.216835,0.016909,0.242368,0.019650,0.182449,0.000007,fail
3,0.593080,1.285446,0.857536,1.702513,1.432379,1.567556,1.845421,1.858779,1.555410,0.415000,...,0.571171,0.605794,0.475668,0.231308,0.017208,0.253551,0.020011,0.210456,0.000005,fail
4,0.495295,1.395881,0.496882,1.520582,1.766522,2.069913,2.553480,2.229316,2.055514,0.491737,...,0.670642,0.638412,0.504612,0.274296,0.017233,0.246304,0.023494,0.270535,0.000007,fail
5,0.441377,1.062870,0.746219,1.459395,2.168763,2.331509,1.749573,2.189035,2.151322,0.506558,...,0.610979,0.725662,0.531181,0.261625,0.015939,0.234045,0.024908,0.215123,0.000008,fail
6,0.589920,1.300068,0.832170,1.905107,2.061543,2.318326,2.341625,1.993278,2.002206,0.521316,...,0.697504,0.702839,0.587910,0.288154,0.019894,0.293779,0.025132,0.292746,0.000008,fail
7,0.494354,1.276382,0.815254,1.767593,2.109270,2.336365,2.220909,1.994618,2.297323,0.538535,...,0.763790,0.732800,0.608181,0.297315,0.016962,0.262006,0.026683,0.274474,0.000008,fail
8,0.626590,0.886397,0.730307,1.487825,1.931312,2.078947,1.761316,1.690201,1.561883,0.362097,...,0.501293,0.514867,0.440848,0.214300,0.017289,0.255766,0.018643,0.184846,0.000007,fail
9,0.594279,1.527327,0.826940,1.659941,1.856122,2.037612,2.020785,1.720511,1.506488,0.450566,...,0.585099,0.554964,0.495284,0.249789,0.015207,0.229591,0.019412,0.211730,0.000007,fail
10,0.311990,0.557655,0.533151,1.200619,1.195713,1.260262,1.045784,1.142468,1.218815,0.291332,...,0.357995,0.396805,0.329086,0.152148,0.008891,0.132144,0.012889,0.134476,0.000005,pass
11,0.512888,1.197375,0.864050,1.187816,1.245533,1.343312,1.344773,1.039498,0.815706,0.258800,...,0.367750,0.332616,0.289001,0.137362,0.010942,0.161316,0.011076,0.125434,0.000004,pass
12,0.315662,0.985911,0.590773,1.171350,1.330459,1.372846,1.016456,0.952123,0.865854,0.266424,...,0.347904,0.333973,0.279912,0.145518,0.008901,0.136646,0.010739,0.105321,0.000003,pass
13,0.365675,0.828996,0.489286,1.196561,1.287782,1.459926,1.527809,1.465675,1.355652,0.430459,...,0.513497,0.499386,0.422244,0.217706,0.011994,0.180678,0.015785,0.183174,0.000006,pass
14,0.405781,1.149552,0.795067,1.581137,1.971341,2.232680,2.260362,2.215917,2.075535,0.616483,...,0.716546,0.709700,0.556277,0.260687,0.017024,0.258033,0.024569,0.256852,0.000008,pass
15,0.647075,1.369408,1.053482,1.833833,2.553743,2.638310,1.775566,1.477581,1.695615,0.447074,...,0.611888,0.640568,0.497423,0.245166,0.018419,0.272632,0.020611,0.222390,0.000008,pass
16,0.414895,0.979244,0.484014,0.866000,1.183209,1.375167,1.671278,1.510288,1.288391,0.390386,...,0.432708,0.419514,0.348605,0.194905,0.011945,0.168493,0.014330,0.180997,0.000005,pass
17,0.313356,1.491008,0.805834,1.616632,2.557471,2.674161,1.973480,1.489690,1.361523,0.490051,...,0.544525,0.503786,0.496923,0.251325,0.015902,0.251997,0.015584,0.189289,0.000007,pass
18,0.494368,0.974352,0.915893,1.886307,1.964012,2.087790,1.877764,2.006934,1.836501,0.468558,...,0.630680,0.678508,0.515364,0.246073,0.016161,0.237702,0.021163,0.225797,0.000008,pass
19,0.406430,1.161694,0.530356,1.611733,1.253835,1.428814,2.026067,1.603041,1.425745,0.386696,...,0.508303,0.469031,0.408074,0.224532,0.013445,0.198960,0.017855,0.211026,0.000005,pass

BARINEL SCORES

,ry 23,ry 2,ry 13,cx 15,ry 4,ry 11,cx 16,ry 3,cx 7,ry 1,...,cx 18,ry 19,ry 22,cx 17,ry 0,ry 20,cx 9,ry 5,ry 14,ry 21
sum,0.571988,0.567878,0.565899,0.559976,0.557328,0.555913,0.554614,0.554282,0.553745,0.54729,...,0.542047,0.539722,0.539645,0.539386,0.538927,0.534725,0.534118,0.533239,0.524682,0.52136

TARANTULA SCORES

,ry 23,ry 2,ry 13,cx 15,ry 4,ry 11,cx 16,ry 3,cx 7,ry 1,...,cx 18,ry 19,ry 22,cx 17,ry 0,ry 20,cx 9,ry 5,ry 14,ry 21
sum,0.571988,0.567878,0.565899,0.559976,0.557328,0.555913,0.554614,0.554282,0.553745,0.54729,...,0.542047,0.539722,0.539645,0.539386,0.538927,0.534725,0.534118,0.533239,0.524682,0.52136

DSTAR SCORES

,cx 18,ry 19,cx 17,cx 16,cx 15,ry 20,ry 22,ry 21,ry 13,cx 7,...,ry 14,cx 9,ry 3,ry 5,ry 1,ry 2,ry 4,ry 0,ry 11,ry 12
sum,16.056501,14.176895,14.110623,13.829675,13.144963,10.952757,7.595205,3.46795,2.714925,2.552506,...,1.420267,0.532063,0.514829,0.465547,0.415711,0.004603,0.002793,4.879005e-10,9.996366e-11,2.249590e-11

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_ry_inGap_27_.qasm

100%|██████████| 10/10 [00:20<00:00,  2.04s/it]
100%|██████████| 10/10 [00:21<00:00,  2.12s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,ry 18,cx 17,cx 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.434449,0.379600,1.116802,0.807875,1.165851,1.482971,1.754832,1.910638,1.885538,1.734318,...,0.192035,0.609745,0.606745,0.468552,0.200718,0.013701,0.019173,0.214063,0.000007,fail
1,0.534847,0.482030,1.508343,0.859368,1.960725,2.367047,2.707351,2.957564,2.461684,2.638969,...,0.285131,0.854711,0.820637,0.662039,0.342770,0.020080,0.027734,0.341833,0.000010,fail
2,0.735812,0.322856,1.010414,0.916859,2.045755,2.586568,2.635278,1.813510,1.885360,1.959937,...,0.307677,0.630962,0.717250,0.568026,0.270370,0.018726,0.023454,0.219547,0.000007,fail
3,0.551060,0.346216,1.098496,0.645254,1.721485,1.832003,1.935163,1.552163,1.478229,1.427068,...,0.173673,0.527931,0.488395,0.384185,0.187106,0.011589,0.015166,0.165619,0.000006,fail
4,0.444786,0.321560,0.906707,0.637618,1.264628,1.531838,1.597513,1.205673,1.125660,1.059935,...,0.201956,0.379450,0.340470,0.300168,0.134257,0.010577,0.011977,0.107810,0.000005,fail
5,0.312486,0.344872,1.056675,0.451523,1.618901,2.180995,2.242953,1.314902,1.475764,1.462456,...,0.178872,0.502621,0.478359,0.393366,0.192743,0.010392,0.016033,0.135544,0.000005,fail
6,0.426361,0.359180,1.062233,0.673294,1.252770,1.429259,1.527383,1.209801,1.179393,1.330039,...,0.206318,0.435487,0.433592,0.354886,0.171994,0.011552,0.014992,0.149643,0.000004,fail
7,0.658152,0.439273,1.452393,0.925229,2.277209,2.374703,2.601561,2.361559,2.134816,1.721658,...,0.285607,0.732499,0.679548,0.542698,0.267530,0.017362,0.021903,0.236547,0.000008,fail
8,0.485464,0.570407,1.745241,1.013921,2.197496,2.701430,2.775836,1.820554,1.473344,1.354477,...,0.340191,0.629363,0.567801,0.524593,0.261597,0.015893,0.017230,0.182882,0.000008,fail
9,0.537931,0.355890,1.143250,0.905058,2.083807,2.049981,2.176339,1.820464,1.937887,1.912819,...,0.235534,0.645908,0.636910,0.482132,0.214759,0.014130,0.019819,0.195755,0.000007,fail
10,0.481110,0.215563,0.683607,0.769872,1.311457,1.359399,1.570180,1.792084,1.797019,1.828828,...,0.247306,0.562188,0.631046,0.483974,0.229738,0.015362,0.019962,0.226630,0.000007,pass
11,0.558533,0.239472,0.815426,0.813636,0.969936,1.763032,1.975016,1.560362,1.610276,1.880772,...,0.223370,0.509934,0.586670,0.449088,0.209082,0.014254,0.018992,0.196496,0.000007,pass
12,0.408523,0.334752,0.999359,0.623186,1.429323,2.015062,2.102079,1.384333,1.365510,1.462089,...,0.179168,0.476654,0.500555,0.388493,0.184953,0.012949,0.016118,0.159487,0.000006,pass
13,0.468288,0.298691,0.973118,0.727090,1.186465,1.788174,1.897575,1.427790,1.338764,1.112307,...,0.237603,0.435716,0.468259,0.341525,0.154690,0.012632,0.013445,0.133688,0.000006,pass
14,0.478992,0.319163,0.990166,0.708906,1.301932,1.317969,1.489238,1.755305,1.454174,1.182338,...,0.241915,0.463751,0.484060,0.407110,0.212687,0.015780,0.015258,0.183454,0.000005,pass
15,0.581828,0.416351,1.261206,1.089733,1.407389,1.926978,2.129869,2.162519,1.677903,1.546046,...,0.348736,0.592190,0.554898,0.511023,0.248442,0.018546,0.018854,0.210742,0.000007,pass
16,0.513866,0.439751,1.339551,0.882762,1.955769,1.888424,2.005673,1.733977,1.815380,1.742485,...,0.251369,0.611167,0.664199,0.516431,0.257040,0.013841,0.020827,0.202328,0.000006,pass
17,0.298566,0.299873,0.893610,0.349344,1.196433,1.020788,1.134299,1.374333,1.439791,1.386592,...,0.090726,0.431507,0.375507,0.299166,0.151588,0.009666,0.013350,0.141396,0.000004,pass
18,0.491510,0.221667,0.692335,0.656466,1.602726,2.142198,2.296117,1.617353,1.934579,2.157955,...,0.247404,0.583924,0.721913,0.516510,0.232250,0.016549,0.023851,0.216064,0.000007,pass
19,0.465507,0.354159,1.139861,0.800876,1.251931,1.471988,1.686500,1.828705,1.647138,1.691157,...,0.260941,0.590412,0.562632,0.482641,0.243317,0.013727,0.018901,0.217632,0.000007,pass

BARINEL SCORES

,ry 19,ry 22,ry 21,ry 18,cx 17,cx 7,ry 9,cx 16,ry 23,ry 0,...,ry 4,ry 20,ry 13,ry 2,cx 6,cx 14,cx 8,ry 1,ry 12,ry 3
sum,0.563702,0.555403,0.55282,0.551608,0.545571,0.530842,0.523229,0.519219,0.518982,0.517235,...,0.513744,0.513571,0.512634,0.510792,0.509716,0.509375,0.508284,0.507991,0.506887,0.501214

TARANTULA SCORES

,ry 19,ry 22,ry 21,ry 18,cx 17,cx 7,ry 9,cx 16,ry 23,ry 0,...,ry 4,ry 20,ry 13,ry 2,cx 6,cx 14,cx 8,ry 1,ry 12,ry 3
sum,0.563702,0.555403,0.55282,0.551608,0.545571,0.530842,0.523229,0.519219,0.518982,0.517235,...,0.513744,0.513571,0.512634,0.510792,0.509716,0.509375,0.508284,0.507991,0.506887,0.501214

DSTAR SCORES

,cx 17,ry 18,ry 19,cx 16,cx 15,cx 14,ry 21,ry 20,cx 7,ry 12,...,ry 13,ry 22,cx 8,ry 4,ry 1,ry 2,ry 3,ry 0,ry 10,ry 11
sum,17.039454,15.799794,13.101049,12.118848,11.130232,10.604447,7.399514,3.52447,2.319311,2.201918,...,1.253317,1.17061,0.469936,0.415286,0.319614,0.003453,0.002044,4.415148e-10,8.092433e-11,2.058606e-11

ERROR GATE LOCATION:
22
Now evolving the following mutant:  AddGate_y_inGap_22_.qasm

100%|██████████| 10/10 [00:19<00:00,  1.94s/it]
100%|██████████| 10/10 [00:20<00:00,  2.02s/it]

,ry 23,ry 22,y 21,ry 20,ry 19,ry 18,cx 17,cx 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.578894,1.288552,0.427388,1.005034,1.576206,2.730024,3.056594,2.837658,2.580061,2.427309,...,0.377367,0.841576,0.838356,0.723976,0.350790,0.021353,0.028046,0.314895,0.000011,fail
1,0.690761,1.692100,0.522998,0.797251,1.805715,1.732365,1.815588,1.691427,1.416770,1.183266,...,0.175045,0.498818,0.451059,0.336172,0.161879,0.013002,0.015176,0.146433,0.000005,fail
2,0.621765,1.656669,0.484526,0.982250,2.139229,2.081993,2.218130,2.102211,1.854187,1.742956,...,0.259252,0.673036,0.665175,0.572049,0.298398,0.017351,0.020406,0.236643,0.000008,fail
3,0.488993,1.081341,0.369467,0.599318,2.076778,2.196702,2.216099,1.574430,1.773236,1.437000,...,0.178482,0.512464,0.521430,0.436697,0.219832,0.014412,0.016566,0.147277,0.000005,fail
4,0.525654,1.756065,0.565082,0.821375,1.977101,1.888928,2.044389,2.416251,1.818830,1.604965,...,0.258076,0.635277,0.557320,0.514377,0.294482,0.017067,0.019061,0.227287,0.000006,fail
5,0.559673,1.404525,0.460074,0.855965,1.475907,1.665529,1.823729,1.774927,1.975412,1.756541,...,0.248256,0.614995,0.594484,0.460102,0.221394,0.013203,0.018484,0.169057,0.000007,fail
6,0.523506,1.240711,0.407935,0.742899,2.372305,2.228709,2.411102,2.335097,2.261004,2.240422,...,0.239495,0.751950,0.703339,0.544819,0.266385,0.018821,0.022731,0.258385,0.000008,fail
7,0.394644,1.229459,0.413614,0.872071,1.450054,1.930271,2.186773,2.075965,2.020271,1.920829,...,0.267305,0.716864,0.674020,0.538077,0.254987,0.015902,0.020149,0.238966,0.000008,fail
8,0.598274,1.444002,0.448586,0.743401,2.223028,1.985137,2.122536,1.833312,1.667634,1.507516,...,0.193308,0.595882,0.547750,0.442160,0.235924,0.012774,0.017636,0.189750,0.000006,fail
9,0.555423,1.352161,0.427186,0.672379,1.541361,1.737420,1.803667,1.281156,0.915508,0.939555,...,0.176631,0.385028,0.333318,0.287871,0.143563,0.011338,0.011742,0.126334,0.000004,fail
10,0.677712,1.333394,0.417028,0.861438,1.634020,2.280193,2.568624,2.687379,2.269893,2.026950,...,0.278629,0.707969,0.744982,0.615338,0.301568,0.021310,0.024406,0.281602,0.000008,pass
11,0.370197,0.985247,0.312302,0.367313,1.132858,1.451572,1.677092,1.753097,1.571608,1.222245,...,0.146392,0.434319,0.422628,0.362695,0.200589,0.012593,0.013938,0.158355,0.000005,pass
12,0.467295,1.057512,0.367671,0.996384,1.767995,2.344967,2.457375,1.824713,1.359083,1.426180,...,0.384277,0.574606,0.581371,0.538821,0.265402,0.015670,0.018591,0.200622,0.000007,pass
13,0.504006,0.962912,0.303479,0.453718,1.273577,1.302806,1.489241,2.029328,2.035615,1.431976,...,0.168113,0.504940,0.480352,0.354182,0.189162,0.015037,0.015225,0.170853,0.000005,pass
14,0.531504,1.252514,0.383980,0.844164,1.694727,1.447363,1.803114,2.867254,2.218989,1.946120,...,0.296717,0.761227,0.713950,0.604094,0.325282,0.019344,0.023497,0.314945,0.000007,pass
15,0.486390,0.976504,0.336650,0.656474,1.693153,2.160107,2.274342,1.588731,1.564289,1.221213,...,0.226239,0.521140,0.492090,0.439933,0.224974,0.014346,0.015230,0.150520,0.000006,pass
16,0.327552,0.573370,0.169371,0.544084,0.891505,1.141792,1.309538,1.283075,1.353140,1.620525,...,0.190295,0.489758,0.573783,0.392606,0.171908,0.011193,0.018319,0.187182,0.000005,pass
17,0.676962,1.545582,0.457757,1.165789,1.768181,1.986391,2.139785,2.013355,1.727603,1.724498,...,0.412983,0.688503,0.676247,0.538057,0.251900,0.020679,0.020675,0.229286,0.000007,pass
18,0.505185,0.916967,0.292181,0.868798,1.702765,1.883470,2.054238,1.860313,2.168012,2.089918,...,0.304882,0.671227,0.767920,0.563701,0.271556,0.016443,0.024448,0.232261,0.000007,pass
19,0.579800,1.353663,0.420096,0.811676,1.929042,2.265650,2.518655,2.465270,2.377141,2.160520,...,0.235843,0.731307,0.708089,0.570982,0.278254,0.020234,0.022797,0.265200,0.000008,pass

BARINEL SCORES

,y 21,ry 22,ry 19,ry 18,ry 23,cx 17,ry 20,ry 13,cx 7,ry 11,...,cx 15,ry 10,cx 16,cx 5,ry 12,ry 2,cx 6,ry 1,ry 3,cx 8
sum,0.566752,0.563496,0.546151,0.524879,0.519269,0.516749,0.516668,0.513919,0.505722,0.501383,...,0.495092,0.49478,0.494415,0.493692,0.491698,0.490793,0.48858,0.484008,0.48195,0.47298

TARANTULA SCORES

,y 21,ry 22,ry 19,ry 18,ry 23,cx 17,ry 20,ry 13,cx 7,ry 11,...,cx 15,ry 10,cx 16,cx 5,ry 12,ry 2,cx 6,ry 1,ry 3,cx 8
sum,0.566752,0.563496,0.546151,0.524879,0.519269,0.516749,0.516668,0.513919,0.505722,0.501383,...,0.495092,0.49478,0.494415,0.493692,0.491698,0.490793,0.48858,0.484008,0.48195,0.47298

DSTAR SCORES

,cx 17,ry 18,ry 19,cx 16,cx 15,cx 14,ry 22,ry 20,cx 7,ry 12,...,y 21,ry 13,ry 4,cx 8,ry 1,ry 2,ry 3,ry 0,ry 10,ry 11
sum,15.543029,14.403836,13.628598,13.067848,11.669071,10.454339,9.547703,3.726816,2.409804,2.168056,...,1.522411,1.44573,0.480018,0.445428,0.346419,0.00354,0.00237,4.392441e-10,9.708946e-11,2.228155e-11

ERROR GATE LOCATION:
21
Now evolving the following mutant:  AddGate_ry_inGap_22_.qasm

100%|██████████| 10/10 [00:20<00:00,  2.03s/it]
100%|██████████| 10/10 [00:19<00:00,  1.99s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,ry 18,cx 17,cx 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.640459,1.466489,0.378789,0.622387,1.884170,2.028385,2.088394,1.581161,2.041759,2.099675,...,0.338488,0.732373,0.838769,0.645244,0.268301,0.020077,0.023326,0.282323,0.000011,fail
1,0.438263,1.374751,0.285174,0.375292,1.251845,1.826601,2.148246,2.109901,2.658388,2.756431,...,0.259302,0.880488,0.998138,0.856147,0.315023,0.021898,0.030830,0.262085,0.000015,fail
2,0.500183,1.191027,0.267100,0.645580,1.683789,2.029126,2.160345,1.669959,2.073878,2.055804,...,0.399627,0.770003,0.853812,0.734744,0.323525,0.019197,0.028200,0.301604,0.000012,fail
3,0.718531,1.249615,0.338414,0.574616,0.998106,1.694982,1.812528,1.447571,1.903882,1.768444,...,0.274221,0.626522,0.668655,0.592955,0.235553,0.019827,0.019648,0.213342,0.000011,fail
4,0.549101,1.694012,0.363874,0.638117,1.268547,1.575386,1.736627,1.519264,2.199328,2.033793,...,0.362260,0.861876,0.865264,0.768585,0.300923,0.021365,0.032237,0.277385,0.000013,fail
5,0.598748,1.426643,0.304346,0.621803,1.404780,1.856466,1.950777,1.640247,2.141441,2.033168,...,0.282788,0.715704,0.826029,0.741667,0.304166,0.018843,0.024645,0.165816,0.000013,fail
6,0.666463,1.708837,0.397491,0.571458,1.459949,1.918035,2.143326,1.976536,2.892406,2.779482,...,0.248483,0.892278,0.951040,0.810761,0.329407,0.022878,0.031178,0.334911,0.000015,fail
7,0.638989,1.209643,0.283762,0.648323,1.879467,2.015085,2.133473,1.851593,2.223212,2.266047,...,0.323638,0.724375,0.835752,0.741016,0.319499,0.021565,0.023561,0.264672,0.000014,fail
8,0.701594,1.345729,0.313801,0.722203,1.773391,1.582672,1.718125,1.812212,2.222494,2.391568,...,0.274651,0.746373,0.865660,0.743024,0.288182,0.022155,0.027305,0.242473,0.000011,fail
9,0.540984,1.205750,0.279729,0.623465,1.324649,1.769582,1.920806,1.669282,2.026108,2.066682,...,0.281702,0.658940,0.716325,0.608554,0.219815,0.019577,0.021199,0.266261,0.000012,fail
10,0.603714,1.645646,0.402282,0.710912,1.198080,1.255397,1.419129,1.375105,1.874466,1.696497,...,0.344614,0.763866,0.783981,0.743782,0.326895,0.017868,0.027389,0.191263,0.000009,pass
11,0.512083,1.378792,0.305100,0.504507,1.338413,1.598246,1.712274,1.497032,1.856430,1.922826,...,0.296800,0.688643,0.778723,0.750681,0.338561,0.017447,0.019964,0.168046,0.000013,pass
12,0.515723,1.227503,0.256698,0.560568,1.248275,1.507277,1.620772,1.531943,2.079513,1.860617,...,0.311744,0.739766,0.761715,0.636544,0.305231,0.019058,0.027511,0.273047,0.000010,pass
13,0.534954,1.268550,0.306992,0.700688,1.795516,1.831143,2.000875,1.828778,2.351636,2.322063,...,0.400493,0.837527,0.955777,0.763126,0.354806,0.021206,0.032772,0.332990,0.000011,pass
14,0.591457,0.987180,0.266085,0.457136,1.165225,1.429115,1.605192,1.714256,2.029597,1.754445,...,0.303196,0.671340,0.728498,0.612026,0.286588,0.017172,0.022949,0.213168,0.000009,pass
15,0.550321,0.881785,0.248758,0.419391,1.872039,1.296510,1.292038,1.212737,1.431020,1.194207,...,0.222609,0.497753,0.527858,0.456714,0.220240,0.014436,0.020114,0.175868,0.000006,pass
16,0.536776,1.122518,0.281470,0.402415,1.173672,1.134214,1.361350,1.834238,2.316213,2.425103,...,0.228881,0.753528,0.870788,0.778680,0.350978,0.015443,0.027541,0.266172,0.000009,pass
17,0.595503,1.133853,0.290620,0.436776,1.814515,1.817801,1.949024,1.761757,2.221714,2.315805,...,0.216718,0.696643,0.793919,0.780963,0.375897,0.016599,0.022022,0.236743,0.000012,pass
18,0.364911,0.940986,0.183461,0.472906,1.313447,1.609939,1.786381,1.483919,1.780156,1.825055,...,0.271697,0.683765,0.769991,0.657948,0.259630,0.016754,0.027918,0.195168,0.000010,pass
19,0.534677,0.922086,0.223355,0.503738,1.235709,1.632700,1.816048,1.530257,2.051480,1.995345,...,0.290870,0.740462,0.789102,0.656401,0.293621,0.015621,0.032834,0.259835,0.000009,pass

BARINEL SCORES

,ry 0,ry 9,ry 18,ry 3,ry 22,cx 17,ry 20,ry 21,cx 14,ry 13,...,cx 16,cx 6,cx 7,cx 5,ry 19,cx 8,ry 12,ry 11,ry 2,ry 4
sum,0.566328,0.564819,0.547652,0.547202,0.546562,0.544667,0.538984,0.537447,0.535357,0.53373,...,0.522811,0.520368,0.518241,0.514412,0.513303,0.513277,0.511713,0.510229,0.501067,0.482711

TARANTULA SCORES

,ry 0,ry 9,ry 18,ry 3,ry 22,cx 17,ry 20,ry 21,cx 14,ry 13,...,cx 16,cx 6,cx 7,cx 5,ry 19,cx 8,ry 12,ry 11,ry 2,ry 4
sum,0.566328,0.564819,0.547652,0.547202,0.546562,0.544667,0.538984,0.537447,0.535357,0.53373,...,0.522811,0.520368,0.518241,0.514412,0.513303,0.513277,0.511713,0.510229,0.501067,0.482711

DSTAR SCORES

,cx 14,cx 15,cx 17,ry 18,cx 16,ry 19,ry 22,cx 6,cx 7,ry 9,...,ry 13,ry 21,cx 8,ry 4,ry 1,ry 2,ry 3,ry 0,ry 10,ry 11
sum,16.891094,16.704129,14.777689,13.330311,11.583994,9.226532,8.947282,3.991308,3.391017,3.320847,...,1.776428,0.808474,0.719527,0.64332,0.553646,0.006696,0.004228,1.598803e-09,1.708560e-10,3.928027e-11

ERROR GATE LOCATION:
22
Now evolving the following mutant:  AddGate_ry_inGap_25_.qasm

100%|██████████| 10/10 [00:19<00:00,  1.98s/it]
100%|██████████| 10/10 [00:19<00:00,  1.96s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,ry 18,cx 17,cx 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.553582,1.287400,0.665709,0.377152,1.673445,2.129041,2.245038,1.504657,1.457848,1.209579,...,0.211213,0.519575,0.486499,0.387945,0.171279,0.012520,0.015125,0.147448,0.000006,fail
1,0.537202,1.182930,0.652107,0.501727,2.156909,2.791756,2.933760,2.175006,1.880861,1.468931,...,0.240928,0.604387,0.534895,0.407878,0.173586,0.018497,0.017914,0.185526,0.000007,fail
2,0.708593,1.657198,0.997505,0.478108,2.161397,2.630202,2.664041,1.804191,1.735317,1.393231,...,0.231050,0.527074,0.566697,0.422396,0.213066,0.017226,0.017353,0.165864,0.000007,fail
3,0.622464,1.253161,0.842607,0.467232,1.998046,2.298188,2.320915,1.516092,1.125005,1.195584,...,0.247008,0.416545,0.449829,0.441474,0.233489,0.014207,0.014691,0.162958,0.000006,fail
4,0.487994,1.031697,0.609111,0.425732,1.660389,1.778267,1.909560,1.710648,1.685458,1.637447,...,0.267883,0.514128,0.513038,0.399072,0.176277,0.015259,0.017153,0.173911,0.000005,fail
5,0.625659,1.095947,0.743198,0.422545,1.672736,2.490425,2.803454,2.633107,2.374755,2.258595,...,0.295856,0.753954,0.735898,0.603121,0.297510,0.020221,0.024713,0.288576,0.000009,fail
6,0.492520,1.491747,0.672792,0.379297,1.604632,1.829166,2.038137,2.089570,1.560767,1.161366,...,0.262493,0.535683,0.432164,0.403177,0.218361,0.014986,0.014672,0.183850,0.000006,fail
7,0.630203,1.137201,0.848453,0.440701,1.939796,1.974733,2.152261,2.412378,2.100488,1.796270,...,0.305280,0.706740,0.682599,0.554956,0.272717,0.021814,0.021921,0.260371,0.000007,fail
8,0.695692,1.332055,0.767960,0.469072,1.954351,2.053496,2.170326,2.009943,1.854383,1.505659,...,0.265112,0.589876,0.546811,0.425265,0.194280,0.018311,0.018588,0.183225,0.000006,fail
9,0.654275,1.140008,0.842612,0.458644,1.949433,2.702997,2.860215,2.103612,2.156466,2.199288,...,0.231118,0.611911,0.681511,0.541246,0.262163,0.018840,0.022457,0.231846,0.000009,fail
10,0.646675,1.022900,0.835377,0.364926,1.684737,2.624537,2.655548,1.420853,1.583612,1.486741,...,0.278029,0.494024,0.585710,0.460341,0.205415,0.017006,0.017984,0.152260,0.000007,pass
11,0.415331,0.846902,0.694131,0.390368,1.606799,1.576735,1.822008,2.024127,2.170452,2.051708,...,0.304559,0.736218,0.802694,0.606094,0.294292,0.016411,0.025481,0.268112,0.000007,pass
12,0.464158,1.234742,0.734115,0.452428,1.940757,2.287060,2.483983,2.256738,2.127111,1.709566,...,0.179877,0.675695,0.625207,0.519058,0.261932,0.015705,0.019558,0.220111,0.000007,pass
13,0.513898,1.047207,0.758547,0.380745,1.612746,2.453720,2.609008,1.787151,1.584489,1.553876,...,0.339359,0.548946,0.630582,0.519010,0.251572,0.018382,0.019256,0.204449,0.000007,pass
14,0.286989,0.688664,0.591005,0.182425,0.799782,0.788808,0.952947,1.198884,1.140266,1.040000,...,0.172395,0.376259,0.391311,0.326490,0.155295,0.008800,0.012904,0.135065,0.000004,pass
15,0.402087,1.083306,0.626289,0.324377,1.481451,1.449057,1.600133,1.739692,1.682484,1.383211,...,0.127399,0.524494,0.492439,0.371115,0.198406,0.011107,0.015349,0.170208,0.000005,pass
16,0.300798,0.956898,0.519749,0.204194,0.806243,1.104927,1.233094,1.422445,1.081626,0.791952,...,0.203662,0.327133,0.260630,0.289121,0.141568,0.010111,0.009589,0.106547,0.000004,pass
17,0.698264,1.631136,0.838469,0.541535,2.453867,2.502580,2.718727,2.651917,2.474479,1.921106,...,0.253044,0.761913,0.755171,0.574067,0.279340,0.019565,0.024089,0.262486,0.000008,pass
18,0.301535,0.960982,0.811742,0.273108,1.251118,1.367757,1.486073,1.475786,1.025141,0.919062,...,0.271864,0.485486,0.404434,0.403830,0.191416,0.011817,0.012421,0.158548,0.000005,pass
19,0.596136,1.218378,0.702055,0.480108,2.042732,2.202669,2.419840,2.330891,2.109283,2.259920,...,0.233489,0.715934,0.694381,0.517367,0.264422,0.016481,0.023765,0.261003,0.000008,pass

BARINEL SCORES

,ry 23,ry 18,ry 20,cx 17,ry 19,ry 3,ry 22,ry 12,cx 16,ry 9,...,ry 10,ry 13,cx 14,cx 7,ry 2,ry 1,ry 11,cx 5,cx 6,ry 4
sum,0.564995,0.552642,0.551532,0.546693,0.544859,0.541757,0.541163,0.528512,0.521568,0.520098,...,0.513162,0.512166,0.511453,0.505854,0.505742,0.505709,0.504922,0.500002,0.49944,0.49653

TARANTULA SCORES

,ry 23,ry 18,ry 20,cx 17,ry 19,ry 3,ry 22,ry 12,cx 16,ry 9,...,ry 10,ry 13,cx 14,cx 7,ry 2,ry 1,ry 11,cx 5,cx 6,ry 4
sum,0.564995,0.552642,0.551532,0.546693,0.544859,0.541757,0.541163,0.528512,0.521568,0.520098,...,0.513162,0.512166,0.511453,0.505854,0.505742,0.505709,0.504922,0.500002,0.49944,0.49653

DSTAR SCORES

,cx 17,ry 18,cx 16,ry 19,cx 15,cx 14,ry 22,ry 21,ry 23,ry 12,...,ry 20,ry 13,cx 8,ry 4,ry 1,ry 2,ry 3,ry 0,ry 10,ry 11
sum,19.368683,18.136214,14.072454,13.720883,11.917935,9.971705,7.684244,3.412973,2.468112,2.318059,...,1.437248,1.350481,0.529217,0.399894,0.329562,0.003347,0.002912,4.425626e-10,9.154369e-11,2.007493e-11

ERROR GATE LOCATION:
20
Now evolving the following mutant:  AddGate_cz_inGap_16_.qasm

100%|██████████| 10/10 [00:24<00:00,  2.47s/it]
100%|██████████| 10/10 [00:25<00:00,  2.59s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cz 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.707234,1.539142,1.020769,1.800718,2.062930,2.272607,2.361988,1.847250,1.745002,1.646582,...,0.403613,0.714517,0.754996,0.886483,0.313736,0.018651,0.028781,0.183714,0.000011,fail
1,0.497604,1.098534,0.641954,1.988561,2.340576,2.528714,2.288324,2.437114,1.821682,2.372655,...,0.233631,0.721648,0.821938,0.836825,0.308824,0.018242,0.022663,0.220518,0.000013,fail
2,0.701159,1.234321,0.611752,1.391959,2.247290,2.471903,2.154167,2.159542,1.758340,1.845270,...,0.242203,0.715313,0.706209,0.719408,0.261583,0.016709,0.021376,0.239582,0.000011,fail
3,0.557881,1.223851,0.735249,1.895221,1.852905,1.922334,1.583398,1.847713,1.420894,1.793341,...,0.179477,0.595969,0.608914,0.602297,0.254310,0.013215,0.015854,0.218831,0.000010,fail
4,0.612147,1.769607,0.970717,1.751574,1.924093,2.142403,2.337118,1.999106,1.884150,1.732844,...,0.281008,0.673062,0.684043,0.802082,0.305348,0.015755,0.022772,0.168879,0.000010,fail
5,0.570852,1.205323,0.763596,1.719817,2.178347,2.342060,1.859970,1.852565,1.423619,1.690672,...,0.343957,0.675176,0.716527,0.748354,0.282155,0.013534,0.023277,0.203372,0.000010,fail
6,0.643604,1.115629,0.697414,1.908833,1.663396,1.933886,2.427233,2.209436,1.585676,2.359818,...,0.294469,0.809842,0.902081,0.927355,0.306954,0.018904,0.026812,0.199919,0.000012,fail
7,0.843310,1.740180,0.805483,1.847761,2.540815,2.772426,2.785935,2.253439,2.228661,1.616914,...,0.380409,0.785383,0.774344,0.929801,0.362580,0.013341,0.027969,0.240509,0.000013,fail
8,0.660114,1.040414,0.574056,1.621800,1.757954,1.878482,1.727530,1.697961,1.315899,1.483190,...,0.182237,0.566121,0.582238,0.648708,0.237608,0.011941,0.017046,0.164530,0.000007,fail
9,0.795787,1.344317,0.993767,2.147530,2.125299,2.294471,2.144306,2.116572,1.643980,1.814406,...,0.307756,0.645124,0.725967,0.787429,0.280485,0.016989,0.022830,0.192225,0.000011,fail
10,0.530561,0.948177,0.656373,1.371794,1.361341,1.538769,1.776436,1.786605,1.225010,1.601611,...,0.222210,0.545516,0.604102,0.626985,0.236529,0.011173,0.019353,0.187632,0.000009,pass
11,0.496469,1.092409,0.815246,1.777808,2.053787,2.258680,1.968801,2.112389,1.505759,2.139761,...,0.263484,0.729246,0.757028,0.781701,0.293000,0.018070,0.024131,0.236172,0.000012,pass
12,0.492420,1.158713,0.744693,1.541855,1.602650,1.799906,2.116922,2.025051,1.669278,1.501266,...,0.277910,0.634161,0.630280,0.688782,0.247576,0.016231,0.021120,0.208834,0.000010,pass
13,0.548165,1.016781,0.871888,1.730339,1.766363,1.893445,1.735015,1.220457,1.136428,1.390837,...,0.360278,0.641769,0.625003,0.701280,0.272628,0.014047,0.027605,0.168771,0.000008,pass
14,0.358612,0.952055,0.649117,0.964993,1.349104,1.517582,1.493660,1.535125,1.300648,1.451437,...,0.157961,0.478809,0.490155,0.495768,0.177988,0.014168,0.013105,0.149948,0.000008,pass
15,0.420900,1.030752,0.731042,1.515877,2.213934,2.501867,2.285216,2.258613,1.655730,2.092142,...,0.349609,0.659313,0.805763,0.830368,0.274950,0.017099,0.026586,0.192346,0.000012,pass
16,0.468629,1.104513,0.844626,1.160381,1.481969,1.667999,1.813867,1.354007,1.182255,1.260075,...,0.287324,0.567063,0.568721,0.644163,0.240619,0.010909,0.021119,0.141790,0.000009,pass
17,0.621028,1.193480,0.910224,1.560166,2.275736,2.505537,2.080361,1.835633,1.470569,1.620152,...,0.324709,0.608120,0.693916,0.727574,0.255989,0.016069,0.025698,0.175905,0.000010,pass
18,0.408420,0.870835,0.786777,0.827768,1.746184,1.938586,1.411956,1.569721,1.177579,1.392686,...,0.227969,0.459371,0.518395,0.461360,0.160303,0.013202,0.014316,0.153980,0.000008,pass
19,0.480949,0.909118,0.683323,1.531684,2.015742,2.093136,1.529365,1.541097,1.230465,1.510443,...,0.264627,0.610728,0.607391,0.620157,0.252372,0.011603,0.020831,0.210826,0.000008,pass

BARINEL SCORES

,ry 23,ry 22,ry 20,ry 10,cz 15,ry 11,ry 12,ry 4,cx 5,cx 17,...,cx 14,cx 18,ry 0,ry 9,ry 1,ry 3,ry 2,cx 8,ry 13,ry 21
sum,0.577241,0.564322,0.563811,0.55962,0.553884,0.552441,0.550308,0.547097,0.545297,0.543358,...,0.5349,0.533634,0.529202,0.527719,0.52668,0.524529,0.517502,0.510088,0.506236,0.503916

TARANTULA SCORES

,ry 23,ry 22,ry 20,ry 10,cz 15,ry 11,ry 12,ry 4,cx 5,cx 17,...,cx 14,cx 18,ry 0,ry 9,ry 1,ry 3,ry 2,cx 8,ry 13,ry 21
sum,0.577241,0.564322,0.563811,0.55962,0.553884,0.552441,0.550308,0.547097,0.545297,0.543358,...,0.5349,0.533634,0.529202,0.527719,0.52668,0.524529,0.517502,0.510088,0.506236,0.503916

DSTAR SCORES

,cx 18,cx 17,ry 19,cx 16,ry 20,cx 14,cz 15,ry 22,cx 5,ry 21,...,ry 12,ry 13,ry 4,cx 8,ry 1,ry 2,ry 3,ry 0,ry 10,ry 11
sum,17.126456,16.645196,15.366858,15.309281,13.620727,12.978663,12.022657,8.738605,3.753874,3.451611,...,1.649285,1.028852,0.683935,0.6372,0.349169,0.005151,0.002439,1.141725e-09,1.496611e-10,3.018740e-11

ERROR GATE LOCATION:
15
Now evolving the following mutant:  AddGate_z_inGap_22_.qasm

100%|██████████| 10/10 [00:19<00:00,  1.92s/it]
100%|██████████| 10/10 [00:20<00:00,  2.04s/it]

,ry 23,ry 22,z 21,ry 20,ry 19,ry 18,cx 17,cx 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.500951,1.228129,0.408556,0.397168,1.460120,1.704394,1.901350,1.898198,1.791826,1.584825,...,0.133578,0.515621,0.466569,0.380357,0.217903,0.012366,0.016450,0.180143,0.000005,fail
1,0.654944,1.515481,0.490106,0.653055,1.647441,2.365656,2.442765,1.689028,1.561916,1.096835,...,0.148812,0.371495,0.339080,0.330059,0.160758,0.013648,0.012684,0.109744,0.000006,fail
2,0.504879,1.110157,0.360907,0.648342,1.205884,0.800884,0.927482,1.406517,1.431169,1.287973,...,0.160051,0.406390,0.377297,0.305250,0.138035,0.009840,0.013349,0.133023,0.000004,fail
3,0.550467,1.211084,0.401201,0.742525,1.678443,2.050290,2.340330,2.216385,2.125658,2.089326,...,0.271793,0.762047,0.740737,0.543024,0.255454,0.016043,0.022804,0.259822,0.000008,fail
4,0.652748,1.602091,0.503194,0.846793,2.109496,2.423176,2.556939,2.021754,2.001989,1.893435,...,0.167085,0.636921,0.628505,0.507519,0.260469,0.015852,0.020440,0.218824,0.000007,fail
5,0.492154,1.295149,0.409889,0.742814,1.723738,2.672382,2.877987,2.115599,2.144511,1.955116,...,0.253462,0.704729,0.687751,0.570653,0.277210,0.015593,0.020342,0.218894,0.000009,fail
6,0.598847,1.418640,0.445669,0.854726,1.317830,1.977448,2.228527,2.159383,1.936475,1.787556,...,0.279846,0.644793,0.651315,0.490700,0.220816,0.018129,0.020710,0.235534,0.000008,fail
7,0.530588,1.301610,0.442406,0.778345,1.584493,2.272917,2.532872,2.336463,2.222424,2.033840,...,0.234268,0.697882,0.667413,0.510223,0.240775,0.018129,0.021536,0.239034,0.000008,fail
8,0.569889,1.521912,0.483564,0.945309,2.016285,1.811029,1.950062,2.008390,1.589897,1.576332,...,0.312671,0.643741,0.543078,0.481543,0.238144,0.016275,0.018505,0.215245,0.000007,fail
9,0.383658,1.135162,0.404166,0.763657,2.042453,1.956126,1.992044,1.556220,1.564924,1.373220,...,0.278481,0.553827,0.532762,0.453808,0.217138,0.013894,0.017097,0.158604,0.000005,fail
10,0.557201,1.280407,0.391917,1.097844,1.255539,2.134055,2.299373,1.742857,1.445384,1.273507,...,0.337659,0.545775,0.606962,0.521999,0.248566,0.016680,0.017932,0.191969,0.000007,pass
11,0.455233,1.065000,0.362759,0.775364,1.782514,1.986711,2.007380,1.369998,1.636943,1.560828,...,0.241718,0.499988,0.567086,0.445494,0.210247,0.012581,0.017914,0.148324,0.000007,pass
12,0.436931,1.122399,0.359611,0.733033,1.201054,1.365538,1.547818,1.911256,1.637885,1.194457,...,0.278860,0.520971,0.521106,0.404549,0.202958,0.014290,0.016110,0.177551,0.000006,pass
13,0.583639,1.074799,0.333670,1.058884,2.256062,2.307611,2.310976,1.592522,1.274994,1.425163,...,0.338172,0.552904,0.602451,0.491434,0.228855,0.017069,0.018743,0.194060,0.000007,pass
14,0.514895,1.042614,0.361807,0.887544,1.816733,1.780211,1.788689,1.636963,1.754292,1.722623,...,0.208647,0.527394,0.606991,0.472655,0.226601,0.016189,0.019484,0.179939,0.000006,pass
15,0.488929,0.951921,0.306612,0.714447,1.992246,1.613338,1.734463,1.882802,1.880960,1.963717,...,0.216180,0.603346,0.657268,0.489166,0.259940,0.014527,0.022181,0.227486,0.000006,pass
16,0.432813,1.183416,0.354082,0.697905,1.578195,1.416664,1.550700,1.468289,1.307013,1.468217,...,0.224958,0.520488,0.558168,0.419771,0.205470,0.012343,0.018249,0.192683,0.000005,pass
17,0.563652,1.172813,0.338217,0.741772,1.317982,1.830027,2.009216,2.069291,1.848895,1.531177,...,0.272629,0.602924,0.643387,0.467539,0.237946,0.016735,0.020265,0.219590,0.000006,pass
18,0.541340,0.913898,0.289412,0.791744,2.150994,1.996873,2.135356,1.843895,1.857783,1.954563,...,0.248778,0.656001,0.706926,0.538066,0.259360,0.015902,0.023014,0.233556,0.000007,pass
19,0.493889,1.396628,0.468330,0.888051,1.839409,1.937109,2.134905,2.193764,1.702763,1.275085,...,0.312118,0.669081,0.596562,0.533835,0.257407,0.017887,0.018561,0.220906,0.000006,pass

BARINEL SCORES

,z 21,ry 22,ry 9,ry 10,cx 15,cx 17,ry 11,cx 16,ry 18,cx 14,...,ry 13,ry 1,ry 19,ry 3,cx 5,ry 2,ry 4,cx 6,ry 20,cx 8
sum,0.549472,0.543505,0.537981,0.530525,0.529148,0.527036,0.523317,0.522849,0.521693,0.520425,...,0.498239,0.497826,0.494047,0.492709,0.488706,0.488658,0.487879,0.481524,0.467833,0.455316

TARANTULA SCORES

,z 21,ry 22,ry 9,ry 10,cx 15,cx 17,ry 11,cx 16,ry 18,cx 14,...,ry 13,ry 1,ry 19,ry 3,cx 5,ry 2,ry 4,cx 6,ry 20,cx 8
sum,0.549472,0.543505,0.537981,0.530525,0.529148,0.527036,0.523317,0.522849,0.521693,0.520425,...,0.498239,0.497826,0.494047,0.492709,0.488706,0.488658,0.487879,0.481524,0.467833,0.455316

DSTAR SCORES

,cx 17,ry 18,cx 16,cx 15,cx 14,ry 19,ry 22,ry 20,cx 7,ry 12,...,z 21,ry 13,ry 4,cx 8,ry 1,ry 2,ry 3,ry 0,ry 10,ry 11
sum,16.026289,14.148736,13.592413,12.809315,10.96485,10.362942,8.391855,2.95635,2.245592,2.208164,...,1.394585,1.322289,0.401886,0.395736,0.323412,0.003319,0.002209,4.536768e-10,9.789334e-11,2.294230e-11

ERROR GATE LOCATION:
21
Now evolving the following mutant:  AddGate_ry_inGap_12_.qasm

100%|██████████| 10/10 [00:20<00:00,  2.07s/it]
100%|██████████| 10/10 [00:20<00:00,  2.04s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.482237,1.128402,0.737980,2.018606,2.254514,2.375095,2.102810,2.352164,2.065769,0.448193,...,0.296686,0.688620,0.753815,0.933084,0.313939,0.020838,0.022637,0.249763,0.000010,fail
1,0.492778,1.384236,0.762669,1.858424,1.294555,1.436326,2.127468,1.797179,1.586053,0.381606,...,0.242663,0.662027,0.667056,0.807286,0.275697,0.016244,0.016655,0.216330,0.000010,fail
2,0.673428,1.211412,0.530235,2.324432,2.097863,2.205546,2.341475,2.319709,1.616388,0.432970,...,0.213809,0.631015,0.752158,0.938021,0.272033,0.017656,0.019244,0.163915,0.000010,fail
3,0.475130,0.793660,0.793320,1.557516,1.462284,1.594479,1.649913,1.735924,1.679036,0.384227,...,0.326534,0.613428,0.621658,0.746790,0.279727,0.015265,0.020584,0.238750,0.000007,fail
4,0.590664,1.216401,0.772287,1.237370,1.468073,1.567275,1.662002,1.811667,1.738756,0.368015,...,0.192815,0.603058,0.588604,0.717705,0.239735,0.014683,0.017037,0.231248,0.000009,fail
5,0.436960,1.440237,0.577692,2.010721,2.349367,2.573470,2.525406,2.685945,2.405772,0.632003,...,0.204876,0.746607,0.821433,1.045733,0.332171,0.020445,0.022502,0.194970,0.000014,fail
6,0.481052,0.998609,0.564647,1.248648,1.485994,1.696658,2.063835,1.854254,1.131275,0.332721,...,0.276815,0.555972,0.658334,0.793252,0.241700,0.014806,0.016243,0.167905,0.000009,fail
7,0.729251,1.755861,0.818644,1.651407,1.686403,1.938681,2.555603,2.420488,1.791613,0.474911,...,0.302023,0.699064,0.822085,1.014597,0.339061,0.017184,0.021246,0.199196,0.000012,fail
8,0.624520,1.554126,0.706534,1.504798,2.326015,2.588141,2.562200,2.330278,2.055339,0.538768,...,0.219956,0.754536,0.800906,0.947564,0.299539,0.019781,0.021181,0.234823,0.000013,fail
9,0.560903,1.118287,0.788278,1.222434,1.751171,1.945448,1.838802,2.023859,1.655290,0.397424,...,0.253056,0.573831,0.608185,0.752465,0.232130,0.017278,0.018559,0.195042,0.000010,fail
10,0.437359,1.326677,0.654937,1.296572,1.986853,2.220378,2.025619,1.769013,1.557876,0.443202,...,0.192404,0.590661,0.606082,0.759149,0.246134,0.015412,0.015880,0.193803,0.000011,pass
11,0.507123,1.291605,0.765744,1.563777,1.920304,2.155167,2.430719,1.905488,1.482846,0.473992,...,0.229924,0.717038,0.710323,0.857093,0.277403,0.018074,0.015987,0.215843,0.000010,pass
12,0.502464,0.919284,0.727663,1.363698,2.333044,2.605508,2.271086,2.025849,2.193354,0.597752,...,0.281500,0.708098,0.744641,0.825463,0.294102,0.018868,0.022626,0.272353,0.000013,pass
13,0.349849,1.153500,0.723542,1.872847,1.530240,1.569862,1.571608,1.234431,0.930890,0.292337,...,0.254012,0.517096,0.532627,0.590643,0.205406,0.014530,0.012182,0.202902,0.000006,pass
14,0.483197,1.111798,0.750274,1.127433,1.643036,1.922502,1.967063,1.994826,1.725325,0.469193,...,0.200015,0.525981,0.606090,0.715076,0.172803,0.017404,0.017017,0.177654,0.000011,pass
15,0.506570,0.362812,0.421669,1.198521,1.441567,1.612842,1.674518,1.444494,1.269764,0.306491,...,0.270708,0.503700,0.563471,0.657247,0.209817,0.012684,0.017446,0.141336,0.000008,pass
16,0.673696,1.358858,0.927571,1.462027,1.697157,1.897334,1.916215,1.541536,1.515052,0.338852,...,0.266805,0.549349,0.617355,0.689513,0.232849,0.018214,0.017829,0.220883,0.000009,pass
17,0.571115,1.335248,0.770072,1.866874,1.847348,2.182416,2.613746,2.144556,2.372806,0.556428,...,0.208433,0.783890,0.776075,0.958238,0.293379,0.023053,0.022121,0.185460,0.000012,pass
18,0.537523,0.966632,0.658447,1.568210,1.943348,2.061003,1.734663,1.813144,1.798742,0.523812,...,0.191487,0.557062,0.585682,0.629342,0.192653,0.016257,0.016605,0.236196,0.000009,pass
19,0.251399,0.751731,0.335276,0.808151,0.826394,0.852673,0.749455,0.944329,0.945188,0.224181,...,0.077742,0.293194,0.288905,0.351077,0.115693,0.008574,0.008220,0.119387,0.000004,pass

BARINEL SCORES

,ry 11,ry 12,cx 16,ry 4,cx 5,ry 22,ry 2,ry 20,cx 6,ry 10,...,ry 0,cx 17,cx 15,ry 3,ry 1,ry 19,ry 21,cx 18,ry 14,ry 9
sum,0.566539,0.566539,0.55916,0.557787,0.552884,0.54364,0.541428,0.540735,0.540493,0.538511,...,0.53076,0.530641,0.528843,0.516469,0.515541,0.514244,0.511499,0.510787,0.509551,0.503286

TARANTULA SCORES

,ry 11,ry 12,cx 16,ry 4,cx 5,ry 22,ry 2,ry 20,cx 6,ry 10,...,ry 0,cx 17,cx 15,ry 3,ry 1,ry 19,ry 21,cx 18,ry 14,ry 9
sum,0.566539,0.566539,0.55916,0.557787,0.552884,0.54364,0.541428,0.540735,0.540493,0.538511,...,0.53076,0.530641,0.528843,0.516469,0.515541,0.514244,0.511499,0.510787,0.509551,0.503286

DSTAR SCORES

,cx 16,cx 17,cx 18,cx 15,ry 19,ry 20,ry 22,cx 5,cx 6,ry 21,...,ry 14,ry 9,ry 4,cx 8,ry 1,ry 2,ry 3,ry 0,ry 10,ry 12
sum,16.967601,15.860089,13.647016,12.181601,12.159893,11.468026,7.71649,4.44019,3.139377,2.971865,...,1.355204,1.147447,0.652337,0.525508,0.365727,0.003775,0.002985,1.101885e-09,9.462293e-11,3.006291e-11

ERROR GATE LOCATION:
12
Now evolving the following mutant:  AddGate_rx_inGap_9_.qasm

100%|██████████| 10/10 [00:21<00:00,  2.18s/it]
100%|██████████| 10/10 [00:19<00:00,  1.98s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,rx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.541135,1.187075,0.924737,1.469530,2.221561,2.475444,2.321795,2.274418,2.502104,0.647702,...,0.046482,0.732326,0.780861,0.577468,0.294041,0.018927,0.024209,0.287109,0.000009,fail
1,0.606434,1.342960,1.072894,2.154675,2.675774,2.722965,1.868646,1.677407,1.541742,0.503018,...,0.067471,0.597792,0.593933,0.465154,0.218030,0.020088,0.018004,0.188199,0.000008,fail
2,0.497891,1.642813,1.036211,2.002200,2.199967,2.359702,2.242489,2.043596,2.102111,0.633419,...,0.059143,0.759292,0.727104,0.597911,0.300125,0.017393,0.022941,0.256507,0.000008,fail
3,0.392283,1.225665,0.799249,1.815502,1.987751,2.101090,1.923341,1.950271,1.818137,0.554135,...,0.060053,0.647095,0.631245,0.557178,0.268810,0.017012,0.020942,0.206078,0.000007,fail
4,0.359529,0.908020,0.871466,1.099941,1.262886,1.409767,1.655112,1.448995,1.156141,0.385372,...,0.060651,0.485190,0.453509,0.431760,0.192396,0.015584,0.014389,0.168183,0.000006,fail
5,0.515930,1.357402,0.844497,1.917934,1.901617,1.935143,1.494266,1.246474,1.134819,0.372410,...,0.048411,0.458866,0.424051,0.349549,0.172365,0.015006,0.013074,0.139731,0.000005,fail
6,0.675255,1.109969,1.019486,1.433986,2.193901,2.446979,2.246532,2.300848,2.268677,0.561221,...,0.069307,0.702377,0.813869,0.621953,0.299433,0.019263,0.026482,0.263042,0.000009,fail
7,0.499266,1.336454,0.950339,1.702507,2.068722,2.401978,2.564938,2.144207,1.904880,0.560055,...,0.072154,0.718663,0.753963,0.636208,0.304369,0.018822,0.024183,0.282064,0.000008,fail
8,0.628038,1.253598,0.856762,2.444252,1.915803,2.012626,2.308486,2.272251,1.729668,0.492612,...,0.061871,0.649986,0.675395,0.535349,0.248841,0.021745,0.022261,0.230743,0.000006,fail
9,0.569750,1.523149,1.050021,2.078968,2.157385,2.290984,2.208687,1.501568,1.268533,0.522925,...,0.068623,0.640340,0.561182,0.478480,0.233392,0.018701,0.017213,0.217526,0.000007,fail
10,0.710667,1.212553,1.198411,1.941537,2.098139,2.254968,2.178301,1.775227,1.751288,0.422228,...,0.080936,0.677659,0.715045,0.569860,0.270752,0.020712,0.022239,0.248584,0.000008,pass
11,0.253585,0.661680,0.557524,1.069037,0.918164,1.013259,1.054342,0.712338,0.953179,0.276155,...,0.034025,0.343249,0.312014,0.282056,0.142743,0.008856,0.010066,0.135440,0.000004,pass
12,0.389357,1.229874,0.674573,1.265201,1.889724,2.174968,2.157073,2.061420,2.131065,0.497075,...,0.036743,0.690079,0.650322,0.492487,0.254506,0.014396,0.021481,0.245472,0.000007,pass
13,0.741569,1.295940,0.969520,1.598860,1.987425,2.256874,2.327492,1.725374,1.758462,0.551520,...,0.069597,0.710829,0.640070,0.572112,0.282195,0.019060,0.021372,0.272186,0.000008,pass
14,0.355896,0.827094,0.604467,1.620797,1.383658,1.407839,1.249973,1.727623,1.837947,0.498918,...,0.036377,0.482762,0.598052,0.488910,0.259586,0.011136,0.019658,0.174316,0.000005,pass
15,0.535685,1.262381,0.757931,1.415280,1.232076,1.395063,2.025551,1.611038,1.429591,0.383978,...,0.033465,0.486440,0.461201,0.369165,0.196751,0.013922,0.016829,0.192434,0.000005,pass
16,0.318313,1.014345,0.706779,1.392497,1.799867,1.932516,1.280728,1.348022,1.812325,0.462679,...,0.049596,0.518894,0.593373,0.525847,0.272593,0.011274,0.019784,0.200612,0.000006,pass
17,0.593910,1.298057,0.637715,1.745416,1.809386,1.861429,1.572744,1.628832,1.398152,0.428250,...,0.042536,0.491342,0.494747,0.368389,0.178418,0.015067,0.016032,0.146322,0.000005,pass
18,0.597720,1.008225,0.863674,1.506217,1.968557,2.050775,1.501039,1.676395,1.517383,0.443310,...,0.049609,0.472817,0.563104,0.429534,0.208951,0.014388,0.017489,0.158890,0.000006,pass
19,0.495030,1.401398,0.809691,2.362725,2.112419,2.087442,1.661865,1.704907,1.363724,0.411251,...,0.055207,0.609391,0.540631,0.459709,0.216509,0.016647,0.015472,0.162260,0.000006,pass

BARINEL SCORES

,rx 8,cx 9,ry 3,cx 17,ry 21,cx 18,ry 19,ry 14,ry 10,ry 0,...,ry 1,cx 5,cx 6,ry 22,ry 20,ry 2,ry 13,ry 4,cx 15,ry 23
sum,0.55719,0.556849,0.556532,0.55054,0.547814,0.545841,0.544806,0.544623,0.543489,0.542389,...,0.536241,0.535321,0.535321,0.534765,0.532346,0.530303,0.527692,0.525837,0.522075,0.514293

TARANTULA SCORES

,rx 8,cx 9,ry 3,cx 17,ry 21,cx 18,ry 19,ry 14,ry 10,ry 0,...,ry 1,cx 5,cx 6,ry 22,ry 20,ry 2,ry 13,ry 4,cx 15,ry 23
sum,0.55719,0.556849,0.556532,0.55054,0.547814,0.545841,0.544806,0.544623,0.543489,0.542389,...,0.536241,0.535321,0.535321,0.534765,0.532346,0.530303,0.527692,0.525837,0.522075,0.514293

DSTAR SCORES

,cx 18,cx 17,ry 19,cx 16,ry 20,cx 15,ry 22,ry 21,cx 6,cx 7,...,ry 23,cx 9,ry 4,ry 1,rx 8,ry 2,ry 3,ry 0,ry 11,ry 12
sum,17.2645,16.07116,15.57965,13.695988,12.667706,11.701631,7.82958,4.996719,2.643382,2.638734,...,1.863469,0.74089,0.521861,0.42005,0.035964,0.004076,0.003284,5.357475e-10,9.972096e-11,2.435593e-11

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_x_inGap_25_.qasm

100%|██████████| 10/10 [00:20<00:00,  2.03s/it]
100%|██████████| 10/10 [00:19<00:00,  1.99s/it]

,ry 23,ry 22,ry 21,x 20,ry 19,ry 18,cx 17,cx 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.595609,1.036148,0.685018,0.361193,1.547979,1.920944,2.130319,2.024019,2.268197,2.028719,...,0.198835,0.626527,0.694693,0.465703,0.227120,0.016752,0.023043,0.222657,0.000007,fail
1,0.568504,1.656379,0.916573,0.519702,2.250369,1.964815,2.031346,1.735145,1.484834,1.671284,...,0.220187,0.580700,0.585621,0.472124,0.240255,0.016579,0.020177,0.214071,0.000006,fail
2,0.449439,1.279714,0.663920,0.497759,2.128207,1.819197,1.814070,1.241188,1.062273,1.179727,...,0.255663,0.436950,0.435430,0.363722,0.181624,0.011746,0.014565,0.134825,0.000005,fail
3,0.414199,1.048705,0.727559,0.393818,1.713538,1.853028,1.865371,1.244003,1.418100,1.210175,...,0.203880,0.436353,0.398608,0.293442,0.127414,0.011408,0.012131,0.090638,0.000005,fail
4,0.627474,1.329822,1.000839,0.515277,2.231151,2.995643,3.122168,2.125056,1.846493,2.021759,...,0.375761,0.694590,0.713901,0.559395,0.281795,0.019865,0.022087,0.241104,0.000009,fail
5,0.497769,1.288908,0.817617,0.496857,2.162552,2.264935,2.320783,1.833253,1.688762,1.016771,...,0.236212,0.536326,0.471076,0.419372,0.199164,0.015393,0.014147,0.146922,0.000006,fail
6,0.568420,1.270625,0.861531,0.402367,1.834599,1.764660,1.947923,1.943499,1.716094,1.727019,...,0.243854,0.611289,0.596331,0.503847,0.250807,0.017309,0.019140,0.232008,0.000007,fail
7,0.604173,1.683812,1.136467,0.674921,2.988805,2.611362,2.609312,1.996081,1.761167,1.550703,...,0.349730,0.684834,0.639493,0.526063,0.250272,0.018665,0.020578,0.201628,0.000007,fail
8,0.604733,1.068531,0.783550,0.425574,1.725808,2.205402,2.349610,1.873762,1.753193,1.614141,...,0.325959,0.592918,0.646389,0.486731,0.230274,0.016301,0.022093,0.198646,0.000006,fail
9,0.559436,1.606365,0.857758,0.492178,2.068879,1.766245,2.014432,2.740937,2.321907,1.963026,...,0.241445,0.734634,0.621968,0.507851,0.263222,0.019683,0.021625,0.269664,0.000007,fail
10,0.560992,1.199149,0.701940,0.330908,1.417858,1.638982,1.961261,2.570428,1.993543,1.949959,...,0.266765,0.726998,0.654331,0.587960,0.318136,0.016765,0.022049,0.289145,0.000008,pass
11,0.436360,1.092734,0.469938,0.448742,1.726778,1.499060,1.621260,1.802537,1.566052,1.450125,...,0.204692,0.480453,0.411304,0.361121,0.180877,0.015688,0.015072,0.169494,0.000006,pass
12,0.708565,1.145626,1.174022,0.391656,1.712424,2.548910,2.698904,2.093202,2.162842,2.112748,...,0.396024,0.699257,0.829469,0.690855,0.338753,0.020017,0.025271,0.250944,0.000009,pass
13,0.537826,0.943850,0.965328,0.376495,1.641875,1.924579,2.042748,1.587457,1.527280,1.586375,...,0.353240,0.536571,0.581198,0.531281,0.262506,0.016623,0.017453,0.194346,0.000007,pass
14,0.552507,1.311429,0.841104,0.305290,1.349401,2.728101,2.970064,2.006772,1.683847,1.833919,...,0.273651,0.595729,0.610719,0.521196,0.270156,0.015613,0.019805,0.216344,0.000009,pass
15,0.615521,1.390467,0.757762,0.446402,2.003062,2.250462,2.463989,2.238357,2.142142,1.966410,...,0.252835,0.713385,0.692816,0.488515,0.216067,0.017648,0.023258,0.232750,0.000008,pass
16,0.452159,0.906890,0.734728,0.230879,0.992775,1.405126,1.506842,1.319521,1.188420,1.425865,...,0.202925,0.433604,0.461477,0.360432,0.178188,0.012429,0.014980,0.164732,0.000005,pass
17,0.492949,0.968235,0.939631,0.465994,2.050066,2.505709,2.625783,1.904942,2.214015,2.261041,...,0.377138,0.728724,0.848044,0.665078,0.307722,0.018929,0.026934,0.249542,0.000009,pass
18,0.354684,1.003014,0.832019,0.385564,1.681613,1.738752,1.763715,1.369217,1.358047,1.266066,...,0.281230,0.500294,0.526791,0.412216,0.174584,0.013297,0.016772,0.153902,0.000006,pass
19,0.475450,1.083513,0.678196,0.249789,1.062527,1.600047,1.780641,1.382999,1.236516,1.455452,...,0.251164,0.483597,0.537287,0.425701,0.208324,0.012085,0.016642,0.183623,0.000006,pass

BARINEL SCORES

,ry 19,x 20,ry 22,ry 18,ry 23,ry 21,cx 17,ry 3,cx 16,ry 10,...,ry 2,cx 6,ry 1,cx 8,cx 14,ry 9,ry 4,cx 5,ry 0,ry 13
sum,0.569075,0.568237,0.545737,0.516174,0.514178,0.510763,0.508824,0.507134,0.506501,0.505027,...,0.488847,0.485367,0.481185,0.481117,0.480105,0.478405,0.478399,0.476868,0.467315,0.459734

TARANTULA SCORES

,ry 19,x 20,ry 22,ry 18,ry 23,ry 21,cx 17,ry 3,cx 16,ry 10,...,ry 2,cx 6,ry 1,cx 8,cx 14,ry 9,ry 4,cx 5,ry 0,ry 13
sum,0.569075,0.568237,0.545737,0.516174,0.514178,0.510763,0.508824,0.507134,0.506501,0.505027,...,0.488847,0.485367,0.481185,0.481117,0.480105,0.478405,0.478399,0.476868,0.467315,0.459734

DSTAR SCORES

,ry 19,cx 17,ry 18,cx 16,cx 15,cx 14,ry 22,ry 21,ry 12,cx 7,...,cx 5,ry 13,cx 8,ry 4,ry 1,ry 2,ry 3,ry 0,ry 10,ry 11
sum,16.635237,15.685497,15.013851,12.442707,11.081928,9.355026,8.366234,3.94683,2.283153,2.215643,...,1.405437,1.094715,0.546716,0.407156,0.314828,0.003524,0.002638,4.046277e-10,8.571020e-11,2.045282e-11

ERROR GATE LOCATION:
20
Now evolving the following mutant:  AddGate_x_inGap_2_.qasm

100%|██████████| 10/10 [00:21<00:00,  2.18s/it]
100%|██████████| 10/10 [00:21<00:00,  2.12s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,ry 5,ry 4,ry 3,ry 2,x 1,ry 0,pass/fail
0,0.559694,1.299106,0.687053,2.071114,1.732729,1.697600,1.490725,1.642109,1.276187,0.300311,...,0.458014,0.429944,0.355797,0.162546,0.014070,0.013313,0.118442,0.071910,0.000005,fail
1,0.648151,1.372627,0.887255,2.082951,1.760760,1.945203,2.433087,1.899698,1.482256,0.377532,...,0.636685,0.536740,0.471297,0.247141,0.017807,0.018828,0.223067,0.138776,0.000006,fail
2,0.605701,1.484689,0.933983,1.524523,1.723346,1.964670,2.533312,2.021233,1.655338,0.435874,...,0.670935,0.587394,0.480795,0.249959,0.019218,0.019187,0.241328,0.142918,0.000007,fail
3,0.473392,1.277928,0.731772,1.589164,1.462085,1.653849,2.136518,2.364663,2.342047,0.557959,...,0.656311,0.722050,0.537866,0.267035,0.017715,0.024563,0.254706,0.134923,0.000007,fail
4,0.639868,1.158346,0.637345,1.952139,2.242696,2.274587,1.842456,1.902943,1.359072,0.322921,...,0.449488,0.477087,0.387110,0.191085,0.015298,0.015931,0.134523,0.088998,0.000006,fail
5,0.586538,1.075599,0.904454,1.134434,2.071108,2.306570,1.977266,2.261106,2.211150,0.506659,...,0.668623,0.718797,0.501413,0.210534,0.017641,0.022517,0.218151,0.116383,0.000008,fail
6,0.519994,1.010076,0.661239,2.120434,1.660115,1.823530,2.036869,1.981003,1.702360,0.420569,...,0.629881,0.610842,0.461098,0.222580,0.016051,0.019490,0.215747,0.120633,0.000006,fail
7,0.496123,1.054639,0.615269,1.496501,1.848895,2.078621,2.101368,2.303063,2.023805,0.465003,...,0.634822,0.678066,0.526887,0.264152,0.016774,0.022465,0.222367,0.128907,0.000007,fail
8,0.367807,1.272532,0.597875,1.489517,2.149452,2.323214,1.921309,1.945894,1.691855,0.382115,...,0.582644,0.542621,0.428918,0.211536,0.014853,0.019594,0.188395,0.116658,0.000006,fail
9,0.616542,1.237133,0.978041,1.195065,1.569746,1.955301,2.539379,2.224286,2.002132,0.481953,...,0.770840,0.757586,0.582545,0.268369,0.019681,0.023846,0.293708,0.160687,0.000008,fail
10,0.429915,1.283256,0.846766,1.306153,1.416960,1.600443,2.072386,1.675878,1.451135,0.456066,...,0.513242,0.473747,0.418966,0.226006,0.013801,0.015586,0.181738,0.103207,0.000007,pass
11,0.377830,0.878770,0.509598,1.146563,1.183077,1.328768,1.355491,1.246437,1.066219,0.369570,...,0.376998,0.360930,0.340980,0.173123,0.011074,0.012012,0.140633,0.076277,0.000005,pass
12,0.610601,1.317320,0.958404,2.400107,1.932168,2.155591,2.435723,2.259502,2.146896,0.599652,...,0.803493,0.855781,0.687789,0.337972,0.020179,0.027926,0.302595,0.166820,0.000007,pass
13,0.509835,1.145422,0.777485,1.825692,1.560262,1.712017,1.881028,1.629104,1.729016,0.474167,...,0.607489,0.554576,0.481393,0.229092,0.016518,0.019019,0.221335,0.122626,0.000007,pass
14,0.592563,1.096934,0.863984,1.581695,2.631090,2.925220,2.264101,2.328011,2.260468,0.567522,...,0.734870,0.813012,0.609817,0.288769,0.020239,0.024215,0.266717,0.138785,0.000009,pass
15,0.334041,1.287124,0.921582,1.391887,1.938561,2.129070,1.707643,1.840509,2.087780,0.562717,...,0.655328,0.704506,0.578857,0.250252,0.016537,0.023392,0.238353,0.119541,0.000008,pass
16,0.477997,0.526966,0.602433,1.463138,1.249335,1.374181,1.465537,1.545602,1.627264,0.397183,...,0.485509,0.544670,0.426799,0.210705,0.014002,0.017500,0.185939,0.102418,0.000005,pass
17,0.495899,1.203166,0.749990,1.145556,1.181494,1.228065,1.018428,0.822726,0.754977,0.259223,...,0.341164,0.337487,0.354639,0.177320,0.010486,0.009725,0.110780,0.061126,0.000004,pass
18,0.351581,0.730554,0.613899,1.002749,1.187884,1.310995,1.273376,1.088396,1.379491,0.356559,...,0.418342,0.446005,0.387414,0.207883,0.010807,0.014546,0.168569,0.090179,0.000005,pass
19,0.221532,0.603889,0.503073,0.985599,1.339623,1.374614,0.908350,0.762538,0.755155,0.212353,...,0.261396,0.292625,0.290961,0.157119,0.008286,0.009062,0.096116,0.055143,0.000004,pass

BARINEL SCORES

,ry 11,cx 16,ry 12,cx 17,ry 23,ry 13,ry 22,ry 10,ry 4,cx 8,...,cx 15,ry 3,cx 7,ry 2,ry 0,ry 21,cx 6,ry 5,ry 14,cx 9
sum,0.577331,0.574798,0.57376,0.561911,0.556074,0.55474,0.548603,0.548562,0.543692,0.542286,...,0.537689,0.535884,0.529612,0.524565,0.522007,0.509581,0.508383,0.50403,0.499758,0.48788

TARANTULA SCORES

,ry 11,cx 16,ry 12,cx 17,ry 23,ry 13,ry 22,ry 10,ry 4,cx 8,...,cx 15,ry 3,cx 7,ry 2,ry 0,ry 21,cx 6,ry 5,ry 14,cx 9
sum,0.577331,0.574798,0.57376,0.561911,0.556074,0.55474,0.548603,0.548562,0.543692,0.542286,...,0.537689,0.535884,0.529612,0.524565,0.522007,0.509581,0.508383,0.50403,0.499758,0.48788

DSTAR SCORES

,cx 16,cx 17,cx 18,ry 19,cx 15,ry 20,ry 22,ry 21,ry 13,cx 8,...,ry 14,cx 9,ry 5,ry 2,x 1,ry 3,ry 4,ry 0,ry 11,ry 12
sum,16.752371,16.735474,14.773089,12.958488,12.468233,11.440287,7.466753,3.35975,2.776323,2.495354,...,1.267632,0.435106,0.429649,0.373879,0.135042,0.003922,0.00282,4.332119e-10,1.189880e-10,2.729784e-11

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_y_inGap_11_.qasm

100%|██████████| 10/10 [00:20<00:00,  2.06s/it]
100%|██████████| 10/10 [00:19<00:00,  1.95s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.577443,1.670567,0.837260,1.555263,1.647849,1.750598,1.670750,1.739858,1.427715,0.404587,...,0.204575,0.565167,0.484633,0.365469,0.170443,0.013156,0.014640,0.140970,0.000006,fail
1,0.427257,1.092794,0.836041,1.667986,1.961347,2.213033,2.230805,2.273499,2.286248,0.512709,...,0.235450,0.731106,0.737284,0.603097,0.298813,0.016593,0.024432,0.274885,0.000008,fail
2,0.267991,0.968509,0.462456,1.193231,1.533303,1.749669,1.897832,2.058755,1.830273,0.430690,...,0.166497,0.585581,0.584467,0.477752,0.250083,0.012224,0.019609,0.207002,0.000007,fail
3,0.515667,1.362100,0.672439,1.568992,2.027690,2.238354,2.148937,1.774236,1.222476,0.417722,...,0.251742,0.566722,0.485828,0.445043,0.223485,0.017073,0.015442,0.175749,0.000006,fail
4,0.603635,1.291811,0.775477,1.859418,1.912925,2.079220,1.906913,2.184792,2.069692,0.432777,...,0.204943,0.606779,0.699229,0.490972,0.222034,0.015456,0.022429,0.210800,0.000007,fail
5,0.513535,0.873512,0.804664,1.383340,1.521580,1.796432,2.176769,2.355723,2.136075,0.501685,...,0.196711,0.699616,0.709018,0.504141,0.221596,0.016555,0.023369,0.243598,0.000007,fail
6,0.556247,1.597493,0.952650,2.141579,2.041255,2.258006,2.499031,2.307005,2.025573,0.488859,...,0.304084,0.759843,0.768308,0.608006,0.309171,0.018738,0.024137,0.265257,0.000008,fail
7,0.529218,1.406336,0.952467,1.858734,2.230463,2.367313,2.046268,1.774016,1.359017,0.469145,...,0.303595,0.599686,0.536792,0.480726,0.229067,0.016374,0.017174,0.184024,0.000007,fail
8,0.460257,1.081607,0.568036,1.684373,1.398533,1.554069,1.849249,2.011683,1.633533,0.358339,...,0.165725,0.544285,0.547296,0.427153,0.197477,0.013442,0.018820,0.178365,0.000006,fail
9,0.717122,1.173934,0.934159,1.824191,2.482928,2.644829,2.088644,1.947992,1.821178,0.449251,...,0.356089,0.621020,0.663644,0.525616,0.249381,0.019375,0.021320,0.216795,0.000008,fail
10,0.592168,1.387781,0.754921,1.983700,1.899555,1.876895,1.507231,1.282145,1.316435,0.397455,...,0.216012,0.393797,0.415608,0.367093,0.215592,0.013864,0.014377,0.142933,0.000006,pass
11,0.389164,0.482525,0.331957,1.024532,1.032317,1.034980,0.811728,0.791135,0.647751,0.172519,...,0.090325,0.232688,0.212634,0.163081,0.078410,0.008236,0.006584,0.071758,0.000003,pass
12,0.612903,1.179986,0.737174,1.593257,1.907019,1.961814,1.491124,1.684040,1.629032,0.450443,...,0.186224,0.458186,0.539933,0.414245,0.211225,0.014882,0.017183,0.159299,0.000006,pass
13,0.293599,0.876564,0.458342,0.933782,1.248234,1.319142,0.864575,0.824390,0.991221,0.209254,...,0.178372,0.294399,0.298123,0.254685,0.123742,0.008487,0.010373,0.096841,0.000004,pass
14,0.460206,1.192609,0.728327,1.287480,1.901467,2.057107,1.530812,1.754687,1.705660,0.408332,...,0.259927,0.587401,0.620907,0.507789,0.236313,0.014336,0.018840,0.182709,0.000007,pass
15,0.450390,1.106865,0.719642,1.750559,1.311171,1.475383,1.856350,1.689777,1.537318,0.377985,...,0.250688,0.578632,0.563287,0.445708,0.226607,0.014297,0.018289,0.210708,0.000005,pass
16,0.511276,0.890396,0.629013,1.438653,0.949097,1.074519,1.290611,1.280657,1.373499,0.370368,...,0.180661,0.445896,0.464748,0.371401,0.175439,0.011060,0.015467,0.171818,0.000004,pass
17,0.571420,1.117137,0.842411,1.053893,1.690674,1.938171,2.038370,2.023562,1.946994,0.513780,...,0.210660,0.629144,0.675321,0.483903,0.236271,0.017197,0.020380,0.237116,0.000008,pass
18,0.420496,1.102150,0.747811,2.132514,1.838937,1.837353,1.512953,1.314765,1.276228,0.341914,...,0.183680,0.492762,0.487395,0.396399,0.195772,0.012797,0.016401,0.165056,0.000005,pass
19,0.303054,0.864229,0.459667,0.805211,1.525539,1.770129,1.749987,1.502424,1.480506,0.413784,...,0.216993,0.519741,0.504135,0.435303,0.227922,0.010957,0.017266,0.193447,0.000006,pass

BARINEL SCORES

,cx 16,ry 11,ry 12,y 10,cx 17,ry 9,cx 7,ry 0,cx 6,ry 2,...,cx 18,ry 3,ry 4,ry 22,ry 19,ry 14,ry 21,cx 8,ry 20,ry 23
sum,0.590816,0.588701,0.588065,0.587823,0.583333,0.57773,0.575472,0.567289,0.565209,0.564804,...,0.558194,0.557648,0.551672,0.551024,0.5507,0.549863,0.548799,0.547659,0.544461,0.528839

TARANTULA SCORES

,cx 16,ry 11,ry 12,y 10,cx 17,ry 9,cx 7,ry 0,cx 6,ry 2,...,cx 18,ry 3,ry 4,ry 22,ry 19,ry 14,ry 21,cx 8,ry 20,ry 23
sum,0.590816,0.588701,0.588065,0.587823,0.583333,0.57773,0.575472,0.567289,0.565209,0.564804,...,0.558194,0.557648,0.551672,0.551024,0.5507,0.549863,0.548799,0.547659,0.544461,0.528839

DSTAR SCORES

,cx 16,cx 17,cx 18,ry 19,cx 15,ry 20,ry 22,ry 21,cx 7,cx 6,...,ry 14,y 10,cx 8,ry 4,ry 1,ry 2,ry 3,ry 0,ry 11,ry 12
sum,17.280619,17.07138,16.188175,13.905216,13.271878,11.670373,7.75817,3.703526,2.695067,2.614302,...,1.460405,0.504874,0.476825,0.471545,0.378215,0.003993,0.002496,4.671830e-10,1.158298e-10,2.794453e-11

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_x_inGap_1_.qasm

100%|██████████| 10/10 [00:22<00:00,  2.29s/it]
100%|██████████| 10/10 [00:23<00:00,  2.31s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,ry 5,ry 4,ry 3,ry 2,ry 1,x 0,pass/fail
0,0.508207,1.080933,0.764454,1.798351,2.323889,2.569261,2.197278,2.196939,1.967018,0.411434,...,0.711204,0.737186,0.551793,0.245213,0.017654,0.023036,0.242959,0.000008,0.106321,fail
1,0.477823,1.550301,0.813869,1.588651,2.370147,2.619356,2.265140,1.979537,1.821355,0.596053,...,0.665035,0.584040,0.535007,0.279717,0.015806,0.019439,0.225604,0.000008,0.115525,fail
2,0.603231,1.233131,0.900003,1.754392,2.227342,2.440709,2.343065,2.671333,2.102691,0.490292,...,0.695776,0.749648,0.594911,0.288855,0.018159,0.023119,0.222010,0.000008,0.117425,fail
3,0.396890,1.059222,0.648171,1.782422,1.486514,1.607287,1.656070,1.522029,1.451963,0.395696,...,0.572261,0.525356,0.412645,0.195445,0.011188,0.017563,0.182192,0.000005,0.071212,fail
4,0.555174,1.444005,0.999150,1.853251,1.710074,1.789339,1.584588,1.485535,1.181167,0.382060,...,0.506881,0.548540,0.446603,0.208619,0.013683,0.017869,0.150916,0.000004,0.058276,fail
5,0.608960,1.109914,0.716142,1.794665,1.485961,1.654642,2.032631,1.640111,1.658491,0.375758,...,0.592967,0.597975,0.479197,0.226550,0.017310,0.020147,0.231195,0.000005,0.076503,fail
6,0.534029,1.074528,0.828575,1.788827,2.318645,2.646892,2.605866,2.344931,2.472374,0.580783,...,0.852287,0.839111,0.632301,0.296200,0.020548,0.027235,0.320275,0.000009,0.122454,fail
7,0.554170,1.353989,0.651615,1.788017,2.222020,2.489921,2.516326,2.587378,2.274941,0.566324,...,0.777036,0.774950,0.593123,0.287306,0.018905,0.024690,0.274279,0.000008,0.115709,fail
8,0.422067,0.937576,1.168669,1.383895,2.369291,2.560070,1.726561,1.739990,1.695189,0.461439,...,0.628308,0.693730,0.588144,0.261518,0.016201,0.020893,0.205279,0.000008,0.108508,fail
9,0.485469,1.169419,1.122051,1.849721,2.426159,2.576963,1.829411,1.504971,1.633687,0.445932,...,0.618790,0.647035,0.545470,0.254755,0.015913,0.020679,0.209087,0.000008,0.104847,fail
10,0.303239,0.394280,0.340168,0.705560,1.083332,1.201685,1.027803,1.201758,1.221524,0.301039,...,0.306507,0.368607,0.278853,0.145525,0.008156,0.012342,0.124925,0.000004,0.055991,pass
11,0.261823,0.800950,0.498831,1.058386,1.340095,1.437670,1.209922,1.223100,1.372814,0.381316,...,0.454786,0.457750,0.379338,0.198210,0.010338,0.015046,0.151928,0.000005,0.059367,pass
12,0.525742,0.965378,0.722702,1.316537,1.248398,1.460428,2.043838,1.956033,1.627015,0.390863,...,0.561462,0.549937,0.432155,0.207775,0.014721,0.017483,0.200105,0.000006,0.087322,pass
13,0.543038,1.284724,0.644917,1.986280,2.096693,2.273849,2.317096,2.171534,1.898098,0.546868,...,0.701791,0.676612,0.547582,0.304355,0.016176,0.022411,0.237587,0.000007,0.094234,pass
14,0.465040,1.100494,0.604340,1.643607,1.650674,1.836340,2.129959,2.144138,1.934685,0.523536,...,0.623934,0.644853,0.542770,0.275457,0.018139,0.022132,0.236940,0.000007,0.099073,pass
15,0.434989,1.136420,0.907467,1.787516,1.411994,1.503864,1.520828,1.562653,1.885335,0.476391,...,0.597802,0.685193,0.545713,0.264966,0.014050,0.021610,0.226774,0.000006,0.079924,pass
16,0.471694,1.135567,0.754217,1.436414,1.392048,1.432011,1.347304,1.506031,1.294626,0.299486,...,0.377639,0.483766,0.382099,0.173972,0.014475,0.015125,0.136722,0.000004,0.063921,pass
17,0.590256,1.083437,0.594585,1.317883,1.814111,1.926482,1.593830,1.284473,1.351312,0.317240,...,0.425049,0.446031,0.346389,0.181064,0.015350,0.014008,0.166360,0.000006,0.081246,pass
18,0.618649,1.058569,0.837586,1.423372,1.990552,2.187106,2.004889,2.107726,1.974890,0.443372,...,0.594686,0.710596,0.521370,0.251487,0.017823,0.022284,0.227687,0.000008,0.109732,pass
19,0.822111,1.220163,1.269225,2.135558,2.089203,2.238388,2.013568,1.981637,2.121381,0.502114,...,0.694571,0.783053,0.589446,0.276995,0.018994,0.024251,0.252086,0.000009,0.118686,pass

BARINEL SCORES

,cx 18,ry 19,cx 8,ry 10,cx 9,cx 17,ry 21,ry 22,ry 1,cx 6,...,cx 7,ry 3,cx 16,ry 12,ry 14,ry 5,ry 4,cx 15,ry 13,ry 23
sum,0.567445,0.565074,0.553614,0.54945,0.547822,0.546725,0.545565,0.541298,0.541153,0.540899,...,0.535635,0.534854,0.534414,0.53219,0.529452,0.527402,0.527335,0.52257,0.518442,0.505374

TARANTULA SCORES

,cx 18,ry 19,cx 8,ry 10,cx 9,cx 17,ry 21,ry 22,ry 1,cx 6,...,cx 7,ry 3,cx 16,ry 12,ry 14,ry 5,ry 4,cx 15,ry 13,ry 23
sum,0.567445,0.565074,0.553614,0.54945,0.547822,0.546725,0.545565,0.541298,0.541153,0.540899,...,0.535635,0.534854,0.534414,0.53219,0.529452,0.527402,0.527335,0.52257,0.518442,0.505374

DSTAR SCORES

,cx 18,ry 19,cx 17,cx 16,cx 15,ry 20,ry 22,ry 21,cx 8,cx 7,...,ry 14,cx 9,ry 5,ry 2,x 0,ry 3,ry 4,ry 1,ry 11,ry 12
sum,19.161748,16.789206,15.834825,14.260513,12.49496,12.177633,7.151276,4.319228,2.857672,2.837929,...,1.561411,0.64421,0.527112,0.428453,0.091578,0.004524,0.002695,5.190799e-10,1.092150e-10,2.624843e-11

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_y_inGap_7_.qasm

100%|██████████| 10/10 [00:22<00:00,  2.21s/it]
100%|██████████| 10/10 [00:19<00:00,  1.95s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,y 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.622379,1.244398,0.708138,1.541273,1.628148,1.651328,1.489746,1.617451,1.192535,0.331129,...,0.385730,0.445491,0.100253,0.345469,0.177982,0.015473,0.014315,0.129822,0.000005,fail
1,0.611036,1.309327,0.930828,2.070874,2.507075,2.563348,1.900275,2.052283,1.997876,0.478242,...,0.625084,0.666261,0.139861,0.548267,0.247753,0.019036,0.022230,0.208857,0.000007,fail
2,0.489997,0.847377,0.617112,1.671272,1.731103,1.987446,2.202091,1.954890,2.056157,0.524718,...,0.664277,0.650537,0.128863,0.534291,0.253529,0.017862,0.022996,0.263589,0.000007,fail
3,0.624891,1.214333,0.874567,1.650492,2.010849,2.191106,2.214327,2.147873,1.975325,0.537206,...,0.659761,0.706576,0.132354,0.518157,0.244654,0.019599,0.022214,0.238892,0.000008,fail
4,0.666739,1.277850,1.002600,2.051120,2.161121,2.337402,2.218113,2.191154,2.154674,0.541091,...,0.721491,0.794404,0.159506,0.606490,0.281206,0.021026,0.024973,0.268481,0.000008,fail
5,0.530468,1.394150,0.764590,2.086108,2.654390,2.890408,2.671096,2.594396,2.504486,0.643092,...,0.842465,0.871635,0.150073,0.661077,0.330480,0.021493,0.027297,0.316689,0.000009,fail
6,0.700573,1.259986,0.834670,1.808226,1.751010,1.845459,1.781172,1.778773,1.629282,0.403842,...,0.557043,0.603980,0.141263,0.477277,0.239959,0.017813,0.020649,0.195822,0.000006,fail
7,0.571779,1.185662,0.736885,1.979292,1.884356,2.013821,1.872070,1.857018,2.033584,0.500704,...,0.622895,0.633566,0.134509,0.481489,0.220435,0.017434,0.021827,0.232067,0.000007,fail
8,0.803435,1.107719,0.973775,1.988365,2.047200,1.976790,1.230375,1.210433,1.260138,0.306404,...,0.398680,0.460014,0.072575,0.359518,0.171812,0.014463,0.014010,0.117755,0.000005,fail
9,0.591187,1.644959,0.909769,1.792594,2.454113,2.659545,2.333187,2.318215,2.121209,0.565807,...,0.702248,0.773361,0.150911,0.624012,0.330613,0.018172,0.024931,0.248084,0.000008,fail
10,0.526623,0.979541,0.924005,1.561381,2.036448,2.207857,1.756379,1.628719,1.973885,0.468754,...,0.600654,0.635482,0.121289,0.533106,0.260012,0.016008,0.022040,0.232234,0.000007,pass
11,0.574451,0.963993,0.846187,2.203704,1.863432,1.774943,1.346560,1.446650,1.154893,0.318168,...,0.412053,0.463503,0.095203,0.400782,0.203663,0.013605,0.014766,0.122466,0.000005,pass
12,0.221041,1.166409,0.713453,1.366258,1.277444,1.458341,1.757662,1.479239,1.376034,0.456911,...,0.571278,0.520091,0.078877,0.478033,0.246998,0.013031,0.015431,0.209233,0.000006,pass
13,0.695685,1.142567,0.956735,1.888148,2.154869,2.299882,1.969732,2.157534,2.418971,0.566592,...,0.700744,0.809864,0.140981,0.614240,0.312249,0.018759,0.026305,0.261958,0.000008,pass
14,0.408071,0.806591,0.317913,0.847293,1.206910,1.291750,1.214098,1.110427,0.901942,0.294103,...,0.292175,0.250315,0.052569,0.222973,0.117240,0.008955,0.009456,0.101518,0.000003,pass
15,0.386549,0.851977,0.491812,1.531149,1.704104,1.869791,1.924646,2.075839,2.277913,0.522387,...,0.650634,0.619348,0.111358,0.480096,0.248958,0.014786,0.020741,0.234648,0.000007,pass
16,0.724058,1.565804,0.935148,1.928437,1.992099,2.080834,2.013715,1.778002,1.199681,0.319023,...,0.574958,0.551094,0.112758,0.407106,0.200816,0.016971,0.016903,0.178059,0.000006,pass
17,0.618962,1.330610,0.736001,1.271761,1.839253,1.997451,1.762327,1.604498,1.147487,0.350772,...,0.451931,0.437021,0.080484,0.331163,0.166580,0.014716,0.012667,0.135578,0.000005,pass
18,0.417310,1.004094,0.760049,1.607389,1.492324,1.437837,0.951258,1.049861,0.985937,0.310149,...,0.351519,0.412534,0.075848,0.339886,0.147927,0.012504,0.012111,0.098241,0.000004,pass
19,0.518113,1.604054,0.814094,1.486904,2.298706,2.374392,1.760953,1.457746,1.040021,0.471801,...,0.527140,0.458780,0.058971,0.419752,0.225213,0.015128,0.012953,0.146360,0.000007,pass

BARINEL SCORES

,y 6,ry 2,ry 13,cx 15,ry 1,cx 7,ry 11,ry 3,cx 16,ry 12,...,cx 17,cx 8,cx 9,ry 20,ry 14,cx 18,ry 4,ry 19,ry 21,ry 22
sum,0.585287,0.568724,0.567925,0.56659,0.563416,0.561536,0.558531,0.557995,0.555391,0.550433,...,0.5475,0.546257,0.544391,0.542922,0.542284,0.540621,0.53984,0.538297,0.527054,0.522386

TARANTULA SCORES

,y 6,ry 2,ry 13,cx 15,ry 1,cx 7,ry 11,ry 3,cx 16,ry 12,...,cx 17,cx 8,cx 9,ry 20,ry 14,cx 18,ry 4,ry 19,ry 21,ry 22
sum,0.585287,0.568724,0.567925,0.56659,0.563416,0.561536,0.558531,0.557995,0.555391,0.550433,...,0.5475,0.546257,0.544391,0.542922,0.542284,0.540621,0.53984,0.538297,0.527054,0.522386

DSTAR SCORES

,cx 18,ry 19,cx 16,cx 17,cx 15,ry 20,ry 22,ry 21,ry 13,cx 7,...,ry 14,cx 9,ry 4,ry 1,y 6,ry 2,ry 3,ry 0,ry 11,ry 12
sum,16.988332,15.569828,15.083322,14.986612,14.632888,13.522869,7.279456,3.98799,3.086819,2.878799,...,1.658573,0.58386,0.514617,0.420523,0.157073,0.004567,0.003279,4.984153e-10,1.092525e-10,2.663239e-11

ERROR GATE LOCATION:
6
Now evolving the following mutant:  AddGate_x_inGap_24_.qasm

100%|██████████| 10/10 [00:19<00:00,  1.96s/it]
100%|██████████| 10/10 [00:18<00:00,  1.90s/it]

,ry 23,ry 22,ry 21,ry 20,x 19,ry 18,cx 17,cx 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.658332,1.220613,0.786826,2.045282,0.518540,2.678615,2.782046,1.912901,2.178913,2.043791,...,0.266280,0.599087,0.684880,0.501185,0.234111,0.018021,0.022051,0.200039,0.000008,fail
1,0.397236,0.969301,0.780792,1.613542,0.506893,2.276319,2.584898,2.212336,2.041371,2.266423,...,0.321319,0.747016,0.708319,0.602191,0.282551,0.016838,0.024948,0.269364,0.000009,fail
2,0.579269,1.434583,1.003494,1.864421,0.456052,2.340340,2.559144,2.337232,2.461402,2.681622,...,0.274187,0.802621,0.832178,0.595367,0.271249,0.019896,0.027400,0.278834,0.000009,fail
3,0.546942,0.899688,0.574026,1.093291,0.360451,1.679796,1.823614,1.456386,1.423383,1.377005,...,0.166861,0.428881,0.423117,0.310994,0.133013,0.013227,0.014549,0.149590,0.000006,fail
4,0.353592,1.057404,0.468610,1.304487,0.464080,2.218696,2.493155,2.155749,2.009327,1.910414,...,0.227565,0.649959,0.638901,0.507830,0.229673,0.015403,0.020879,0.232309,0.000008,fail
5,0.660369,1.066731,1.111106,1.901905,0.509387,2.658926,2.798821,1.888945,1.642752,1.500126,...,0.353406,0.600592,0.676663,0.537548,0.232855,0.019308,0.020221,0.215920,0.000008,fail
6,0.583450,1.379013,0.609051,1.537398,0.451307,2.307062,2.547422,2.231180,2.248784,2.051299,...,0.211609,0.676899,0.719424,0.548613,0.286794,0.016655,0.022630,0.238350,0.000008,fail
7,0.477419,0.893424,0.628655,0.993590,0.399455,1.825161,2.122682,2.054539,1.899544,1.793920,...,0.251888,0.572385,0.605480,0.473120,0.241427,0.015386,0.020026,0.219302,0.000007,fail
8,0.753725,1.573914,1.036511,1.884699,0.497773,2.608895,2.898808,2.833626,2.517328,2.105216,...,0.321578,0.831456,0.790042,0.639921,0.307280,0.022479,0.024472,0.284039,0.000009,fail
9,0.571566,1.057209,0.959072,1.453601,0.519354,2.702104,2.845762,1.948107,2.101360,2.023165,...,0.329177,0.668087,0.756350,0.589447,0.285362,0.017412,0.023450,0.216505,0.000008,fail
10,0.643033,0.828076,0.911603,1.434864,0.446742,2.140393,2.486300,2.394413,2.261954,2.289102,...,0.302805,0.777432,0.831651,0.658854,0.309520,0.020523,0.026300,0.308612,0.000009,pass
11,0.452518,1.045118,0.589616,0.945478,0.251809,1.083284,1.320204,1.955974,1.884510,1.363643,...,0.202547,0.524351,0.490616,0.403933,0.193429,0.013088,0.015580,0.179636,0.000005,pass
12,0.394286,0.713870,0.570006,0.506555,0.265938,1.279152,1.496995,1.509717,1.229645,0.950593,...,0.211052,0.369722,0.376940,0.338823,0.176238,0.011582,0.012743,0.144157,0.000005,pass
13,0.467004,1.161118,1.059724,1.612156,0.476256,2.522306,2.686247,1.822388,1.451218,1.329851,...,0.384909,0.616469,0.634109,0.532262,0.248168,0.016582,0.019736,0.195967,0.000008,pass
14,0.545629,1.022560,0.868260,1.587541,0.318764,1.704347,1.760967,1.163554,0.708591,0.949606,...,0.324231,0.372256,0.424437,0.417710,0.208284,0.012022,0.013672,0.153690,0.000005,pass
15,0.364109,0.543447,0.466903,0.980345,0.176591,0.981847,0.990965,0.740408,0.752677,0.757204,...,0.107961,0.249251,0.290423,0.242043,0.121254,0.007509,0.008915,0.087847,0.000003,pass
16,0.666719,1.423513,0.954220,1.752334,0.362906,2.044185,2.139416,1.867568,1.517457,1.254336,...,0.316131,0.555368,0.593309,0.430295,0.200890,0.018240,0.017936,0.195856,0.000007,pass
17,0.534814,1.078952,0.560220,1.179594,0.373550,1.958618,2.106363,1.620995,1.500431,1.600095,...,0.233862,0.548638,0.520974,0.418335,0.215279,0.013376,0.018010,0.184895,0.000006,pass
18,0.317605,0.828617,0.355060,1.236308,0.252707,1.373697,1.354157,0.735345,0.622444,0.649552,...,0.108954,0.216549,0.190745,0.170183,0.088019,0.006997,0.006428,0.061185,0.000003,pass
19,0.606325,1.079025,0.803681,1.768195,0.379191,1.909802,2.048469,1.825128,2.158777,2.247074,...,0.274905,0.660992,0.778262,0.591262,0.283200,0.018101,0.025820,0.247133,0.000007,pass

BARINEL SCORES

,ry 11,ry 9,cx 14,cx 15,ry 10,ry 12,x 19,ry 13,ry 0,cx 17,...,cx 6,ry 1,ry 3,cx 5,ry 4,ry 20,ry 22,ry 23,ry 21,cx 8
sum,0.60056,0.597171,0.595974,0.592981,0.589469,0.587593,0.58631,0.585621,0.585411,0.58058,...,0.571192,0.567099,0.558539,0.557967,0.550569,0.546851,0.542949,0.527892,0.527119,0.524707

TARANTULA SCORES

,ry 11,ry 9,cx 14,cx 15,ry 10,ry 12,x 19,ry 13,ry 0,cx 17,...,cx 6,ry 1,ry 3,cx 5,ry 4,ry 20,ry 22,ry 23,ry 21,cx 8
sum,0.60056,0.597171,0.595974,0.592981,0.589469,0.587593,0.58631,0.585621,0.585411,0.58058,...,0.571192,0.567099,0.558539,0.557967,0.550569,0.546851,0.542949,0.527892,0.527119,0.524707

DSTAR SCORES

,cx 17,ry 18,cx 15,cx 16,cx 14,ry 20,ry 22,ry 21,ry 12,cx 6,...,ry 13,x 19,cx 8,ry 4,ry 1,ry 2,ry 3,ry 0,ry 10,ry 11
sum,22.825781,20.101749,17.487819,17.253541,16.680748,10.704764,6.765563,3.695138,3.402196,3.087743,...,1.675128,1.648562,0.595112,0.520712,0.451534,0.004788,0.003008,6.455576e-10,1.207015e-10,2.845517e-11

ERROR GATE LOCATION:
19
Now evolving the following mutant:  AddGate_rxx_inGap_13_.qasm

100%|██████████| 10/10 [00:18<00:00,  1.89s/it]
100%|██████████| 10/10 [00:20<00:00,  2.07s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.500547,1.446775,0.632735,1.884213,1.643935,1.748372,1.814644,1.696759,1.501863,0.444944,...,0.152843,0.527270,0.485043,0.362166,0.181162,0.013408,0.015563,0.162983,0.000005,fail
1,0.512376,0.985396,0.758689,1.118559,1.354726,1.627660,2.011120,1.866318,1.783117,0.475625,...,0.263701,0.579211,0.573245,0.503440,0.257824,0.015744,0.019593,0.222788,0.000007,fail
2,0.640060,1.186234,0.650627,1.775977,1.544924,1.639515,1.708568,1.778022,1.909630,0.458372,...,0.201310,0.548494,0.595487,0.457847,0.251435,0.013418,0.021042,0.203193,0.000006,fail
3,0.723606,1.223834,0.824102,1.620174,2.225082,2.374117,1.905734,1.813162,1.503267,0.355605,...,0.275985,0.572832,0.577517,0.386516,0.158098,0.017865,0.019047,0.176480,0.000007,fail
4,0.728243,1.042171,0.613321,1.699308,1.563731,1.698788,1.700262,1.965403,2.257621,0.389862,...,0.113092,0.534061,0.630531,0.415511,0.197854,0.014868,0.022630,0.221396,0.000007,fail
5,0.667587,1.096390,0.813533,1.312677,2.095287,2.361630,2.125480,2.133062,2.396507,0.504817,...,0.267139,0.726849,0.762247,0.543297,0.259924,0.017940,0.024889,0.272717,0.000008,fail
6,0.657454,1.327751,0.921523,1.596098,2.356801,2.607365,2.230503,2.193857,2.062123,0.549980,...,0.295441,0.687937,0.777474,0.607135,0.269841,0.021098,0.025054,0.263064,0.000009,fail
7,0.581877,1.374189,1.115807,1.557267,1.879847,2.054456,1.639048,1.567510,1.940704,0.476717,...,0.398868,0.623331,0.720026,0.560503,0.261982,0.016485,0.023049,0.226139,0.000007,fail
8,0.618317,1.315535,0.769485,1.703783,1.892849,2.074152,2.163518,2.076381,2.036474,0.546953,...,0.299334,0.670921,0.711907,0.572962,0.289536,0.018144,0.023942,0.245496,0.000007,fail
9,0.461104,0.983166,0.649193,1.453580,2.207863,2.391897,1.880193,1.967179,1.938126,0.435889,...,0.329381,0.642988,0.693970,0.509452,0.239019,0.018074,0.022591,0.221248,0.000007,fail
10,0.426757,0.839421,0.661494,1.699605,1.937758,2.073360,1.713801,1.941665,2.118423,0.484668,...,0.221210,0.633976,0.723579,0.486483,0.242516,0.013999,0.023353,0.227738,0.000007,pass
11,0.637520,1.610444,1.045577,1.814175,2.214509,2.278170,1.653251,1.516388,1.373371,0.464360,...,0.236048,0.532045,0.564230,0.472433,0.245336,0.014701,0.017908,0.169214,0.000006,pass
12,0.386499,0.864362,0.734412,1.255742,1.383590,1.421619,1.150699,1.325926,1.113410,0.285741,...,0.228538,0.404393,0.437858,0.347062,0.153778,0.012344,0.013237,0.118416,0.000005,pass
13,0.355360,1.115134,0.605767,0.976806,1.123046,1.335427,1.788011,1.881578,1.955681,0.500660,...,0.145461,0.544787,0.568258,0.453184,0.240710,0.012773,0.018699,0.214074,0.000006,pass
14,0.393868,0.771505,0.585369,1.040509,1.937303,2.316578,2.373362,2.076485,1.975486,0.559119,...,0.333204,0.685005,0.657483,0.583237,0.289181,0.017077,0.022086,0.261304,0.000008,pass
15,0.474569,1.192302,0.987560,1.665489,2.215248,2.480097,2.578105,2.473049,2.412583,0.604347,...,0.269571,0.754620,0.804951,0.675384,0.357208,0.018279,0.026199,0.291635,0.000009,pass
16,0.635520,1.285843,0.967739,2.157697,2.182443,2.237670,1.848378,1.625126,1.789533,0.491118,...,0.372469,0.668115,0.638455,0.534144,0.264601,0.018922,0.021558,0.211710,0.000007,pass
17,0.490836,1.068868,0.832665,1.581739,1.634748,1.955360,2.471492,2.029341,2.197898,0.535854,...,0.338356,0.789070,0.748864,0.624928,0.297791,0.018208,0.025038,0.314126,0.000007,pass
18,0.463652,0.861403,0.866952,1.406766,1.661935,1.753665,1.405447,1.181770,1.148188,0.277904,...,0.311258,0.457654,0.452533,0.423915,0.198602,0.012901,0.014613,0.158690,0.000006,pass
19,0.401527,1.015922,0.642448,1.549119,1.269345,1.322321,1.339944,1.175482,1.304557,0.359860,...,0.238093,0.467460,0.463835,0.396036,0.172169,0.014780,0.015801,0.163971,0.000004,pass

BARINEL SCORES

,ry 23,rxx 12,ry 13,ry 22,ry 9,cx 15,ry 10,cx 16,ry 11,ry 2,...,ry 0,cx 17,ry 1,ry 20,cx 7,ry 14,cx 5,ry 21,cx 8,ry 4
sum,0.566237,0.543793,0.532746,0.529996,0.526624,0.526421,0.526087,0.525229,0.5232,0.522731,...,0.514534,0.511421,0.509735,0.509297,0.507334,0.504082,0.496068,0.494229,0.490823,0.49014

TARANTULA SCORES

,ry 23,rxx 12,ry 13,ry 22,ry 9,cx 15,ry 10,cx 16,ry 11,ry 2,...,ry 0,cx 17,ry 1,ry 20,cx 7,ry 14,cx 5,ry 21,cx 8,ry 4
sum,0.566237,0.543793,0.532746,0.529996,0.526624,0.526421,0.526087,0.525229,0.5232,0.522731,...,0.514534,0.511421,0.509735,0.509297,0.507334,0.504082,0.496068,0.494229,0.490823,0.49014

DSTAR SCORES

,cx 18,cx 15,cx 16,cx 17,ry 19,ry 20,ry 22,ry 21,ry 13,cx 6,...,ry 14,cx 8,ry 4,ry 1,rxx 12,ry 2,ry 3,ry 0,ry 10,ry 11
sum,14.514574,13.641432,13.339577,12.987443,12.776775,9.828744,6.96017,3.348984,2.920016,2.653016,...,1.477525,0.531336,0.449461,0.404625,0.31244,0.004634,0.002748,4.814921e-10,1.056512e-10,2.359628e-11

ERROR GATE LOCATION:
12
Now evolving the following mutant:  AddGate_cz_inGap_15_.qasm

100%|██████████| 10/10 [00:21<00:00,  2.19s/it]
100%|██████████| 10/10 [00:20<00:00,  2.08s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,cz 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.666529,1.204598,0.596993,1.572484,2.061546,2.214002,2.002117,2.311598,2.260957,1.635671,...,0.146320,0.733817,0.881327,0.548821,0.388217,0.022109,0.035249,0.306714,0.000009,fail
1,0.551024,1.443676,0.906055,1.602907,1.748277,1.986092,2.214589,2.084469,2.037368,1.499407,...,0.435621,0.801917,0.852084,0.678262,0.430605,0.024384,0.029812,0.344518,0.000010,fail
2,0.526082,0.847553,0.660913,1.774023,1.774709,1.976532,1.967328,2.023234,2.261866,1.618588,...,0.247672,0.801544,0.850011,0.572862,0.367612,0.022913,0.033023,0.348175,0.000009,fail
3,0.584207,1.590046,0.826709,1.633910,2.108150,2.326977,2.155029,1.884393,1.999123,1.268978,...,0.369338,0.764252,0.854449,0.654864,0.421684,0.022889,0.031576,0.342316,0.000008,fail
4,0.647507,1.065720,0.793249,1.871781,2.404743,2.556937,1.788966,1.952241,2.095740,1.662168,...,0.334108,0.781697,0.888526,0.572026,0.391425,0.025019,0.029525,0.305105,0.000010,fail
5,0.509819,0.866342,0.627327,0.993495,1.625638,1.879041,1.783215,1.825309,1.959644,1.404322,...,0.240446,0.668321,0.718107,0.472052,0.322094,0.020513,0.028522,0.290868,0.000009,fail
6,0.486512,1.135600,0.644137,1.920294,2.773261,2.919206,2.134597,2.443640,2.541884,1.856636,...,0.280068,0.845471,0.999916,0.704264,0.451295,0.024287,0.033925,0.352268,0.000011,fail
7,0.580364,1.227731,0.693143,1.644394,1.867846,2.036475,1.898986,1.806989,1.577684,1.440869,...,0.264345,0.678222,0.713455,0.447170,0.305263,0.020331,0.025513,0.257830,0.000008,fail
8,0.669502,1.332761,0.815506,2.127686,2.115648,2.244882,2.236135,1.855326,1.651838,1.670476,...,0.340394,0.777823,0.777224,0.603019,0.368114,0.020307,0.026338,0.331990,0.000007,fail
9,0.594870,1.572614,1.045863,1.773126,2.418801,2.679923,2.372907,2.097190,1.889765,1.465517,...,0.371307,0.856337,0.844155,0.686315,0.395292,0.022687,0.026994,0.346107,0.000010,fail
10,0.568093,1.598563,0.786540,1.680168,1.571565,1.888759,2.453939,2.035880,1.749078,1.304497,...,0.289167,0.747846,0.719582,0.592862,0.366971,0.020914,0.029400,0.336557,0.000008,pass
11,0.393870,1.022556,0.491640,1.457220,1.920922,2.163192,1.895827,1.838464,2.024142,1.411960,...,0.273385,0.731456,0.792926,0.545575,0.351898,0.019674,0.027337,0.318919,0.000009,pass
12,0.366824,0.636677,0.583101,0.961084,1.510291,1.549159,0.926013,0.929673,1.025095,0.840471,...,0.123504,0.340588,0.371874,0.281457,0.148073,0.008406,0.013782,0.137490,0.000005,pass
13,0.369446,0.971184,0.662877,1.535146,1.735153,1.967601,1.942428,1.991991,2.119460,1.260884,...,0.255850,0.724486,0.840426,0.590799,0.392784,0.021387,0.032092,0.329436,0.000008,pass
14,0.401746,0.704129,0.617174,1.009837,1.004293,1.081998,0.990840,0.738705,0.875659,0.702059,...,0.242372,0.361047,0.388973,0.344173,0.183814,0.010468,0.012272,0.161614,0.000004,pass
15,0.321037,0.938153,0.913094,1.663663,1.906892,1.959170,1.377872,1.269841,1.390247,0.946064,...,0.326384,0.584559,0.625927,0.509800,0.303628,0.016643,0.019814,0.229419,0.000006,pass
16,0.638743,1.380795,1.038871,1.463417,2.170748,2.250786,1.390446,1.221276,0.856759,0.927885,...,0.293639,0.516033,0.535190,0.411181,0.230497,0.014645,0.013692,0.160193,0.000006,pass
17,0.472637,1.071523,0.917779,1.621031,2.034130,2.130929,1.691176,1.466319,1.225236,1.210355,...,0.309229,0.622065,0.600696,0.488551,0.250209,0.016159,0.015952,0.214990,0.000007,pass
18,0.439787,0.888662,0.624548,1.131509,1.440338,1.610944,1.587595,1.928333,2.148138,1.306005,...,0.201075,0.681336,0.821664,0.548263,0.371062,0.019429,0.030277,0.300649,0.000009,pass
19,0.509003,1.046241,0.907700,1.775465,2.074592,2.189401,1.740986,1.698489,1.628373,1.443009,...,0.303314,0.665666,0.692274,0.551686,0.310501,0.017192,0.020687,0.250971,0.000008,pass

BARINEL SCORES

,ry 2,ry 13,ry 12,ry 10,cz 14,ry 3,cx 15,cx 16,ry 11,ry 1,...,ry 9,cx 7,cx 17,cx 5,cx 18,ry 19,ry 22,ry 20,cx 8,ry 21
sum,0.582567,0.582373,0.581782,0.579088,0.577569,0.577521,0.574094,0.572951,0.571702,0.569329,...,0.56462,0.563368,0.562334,0.549764,0.548401,0.546119,0.54498,0.541899,0.53645,0.502197

TARANTULA SCORES

,ry 2,ry 13,ry 12,ry 10,cz 14,ry 3,cx 15,cx 16,ry 11,ry 1,...,ry 9,cx 7,cx 17,cx 5,cx 18,ry 19,ry 22,ry 20,cx 8,ry 21
sum,0.582567,0.582373,0.581782,0.579088,0.577569,0.577521,0.574094,0.572951,0.571702,0.569329,...,0.56462,0.563368,0.562334,0.549764,0.548401,0.546119,0.54498,0.541899,0.53645,0.502197

DSTAR SCORES

,cx 18,cx 15,cx 16,cx 17,ry 19,ry 20,cz 14,ry 22,cx 6,ry 13,...,cx 5,ry 23,ry 4,ry 1,cx 8,ry 2,ry 3,ry 0,ry 10,ry 11
sum,18.08685,16.416733,16.380305,16.250319,15.957964,11.773827,11.284126,7.451771,4.283947,3.936653,...,2.373432,2.336182,1.143188,0.836509,0.727425,0.008838,0.005,8.294848e-10,1.574559e-10,3.709879e-11

ERROR GATE LOCATION:
14
Now evolving the following mutant:  AddGate_ry_inGap_14_.qasm

100%|██████████| 10/10 [00:20<00:00,  2.02s/it]
100%|██████████| 10/10 [00:20<00:00,  2.01s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.452406,0.990415,0.760212,1.404927,2.287124,2.587914,2.599281,2.268682,2.224857,0.651034,...,0.383794,0.843698,0.801262,0.508759,0.205361,0.019469,0.020503,0.254694,0.000008,fail
1,0.413235,0.902280,0.782034,1.133814,1.925529,2.218857,2.134943,1.826190,1.985988,0.564238,...,0.288623,0.690062,0.664570,0.422824,0.185998,0.013384,0.016064,0.220033,0.000007,fail
2,0.517026,1.063618,0.549248,1.917980,2.225920,2.300275,1.795155,1.792759,1.508470,0.414673,...,0.208519,0.575886,0.556236,0.334122,0.146588,0.014354,0.014453,0.152284,0.000005,fail
3,0.592218,1.260036,0.900834,1.835181,1.971718,2.013891,1.615695,1.419768,1.140791,0.413732,...,0.313347,0.528204,0.529499,0.345388,0.138930,0.014031,0.013334,0.129775,0.000005,fail
4,0.646936,0.987016,0.808416,1.642102,1.338361,1.500764,2.077195,1.662665,1.362836,0.328999,...,0.269138,0.625605,0.553293,0.346658,0.156675,0.013194,0.014170,0.193488,0.000004,fail
5,0.731833,1.023248,0.817691,2.089023,2.540953,2.625200,2.039691,1.905235,1.676935,0.438249,...,0.388005,0.628582,0.686245,0.447207,0.159999,0.020422,0.018862,0.180433,0.000007,fail
6,0.671546,1.412336,0.728166,1.935253,2.393969,2.550856,2.070538,1.953414,1.894218,0.413601,...,0.243486,0.689506,0.691797,0.394119,0.178111,0.015916,0.017169,0.197918,0.000007,fail
7,0.577097,1.470721,0.621214,1.862052,2.105252,2.240649,2.097424,1.792523,1.631942,0.519236,...,0.214012,0.638724,0.591899,0.376131,0.175092,0.015383,0.015997,0.189067,0.000005,fail
8,0.495274,1.181294,0.790196,1.555348,1.498947,1.827395,2.610777,2.309444,2.184993,0.587729,...,0.319790,0.870005,0.829968,0.480005,0.204085,0.019830,0.020867,0.273999,0.000007,fail
9,0.509326,1.133290,0.557955,1.592779,1.743370,1.722400,1.253139,1.319132,1.349039,0.282012,...,0.123749,0.415559,0.402428,0.235889,0.112232,0.008498,0.010197,0.105989,0.000004,fail
10,0.365688,1.060978,0.632970,1.401714,1.247670,1.287459,1.289564,1.296824,1.155159,0.356919,...,0.163836,0.437121,0.411260,0.236023,0.098729,0.009821,0.010441,0.111697,0.000003,pass
11,0.492434,1.158683,0.958610,2.259675,2.813127,2.948921,2.252641,2.575805,2.438355,0.722400,...,0.276253,0.839556,0.882588,0.481467,0.226820,0.018825,0.020640,0.235186,0.000008,pass
12,0.420528,1.336598,0.850099,1.592147,1.689396,1.796345,1.779582,1.768696,1.374862,0.473589,...,0.223014,0.610432,0.555359,0.339151,0.131919,0.011798,0.011895,0.145885,0.000005,pass
13,0.607679,1.471127,0.739040,1.643921,1.850794,1.993616,1.908519,1.576699,1.598860,0.485707,...,0.275046,0.572172,0.554071,0.361683,0.162003,0.014404,0.014936,0.181642,0.000005,pass
14,0.590947,1.458337,1.055788,1.453113,2.422036,2.628447,2.245124,2.145388,1.844222,0.464335,...,0.365616,0.718502,0.791101,0.474314,0.196654,0.019333,0.019426,0.208640,0.000008,pass
15,0.314996,0.853772,0.516696,1.200279,1.476280,1.691907,1.798589,1.852100,1.756703,0.424498,...,0.193621,0.624821,0.618334,0.355250,0.142036,0.015034,0.015608,0.186881,0.000005,pass
16,0.367690,1.098580,0.859472,1.423162,1.614683,1.660127,1.126073,1.081015,1.050171,0.314377,...,0.333984,0.469282,0.551623,0.350584,0.117546,0.015647,0.014140,0.123007,0.000005,pass
17,0.323636,0.954204,0.713364,1.230139,1.078609,1.207335,1.393115,1.004814,0.720776,0.229865,...,0.298973,0.443342,0.396297,0.320588,0.117904,0.011147,0.010529,0.121323,0.000004,pass
18,0.410983,1.230731,0.648545,1.706300,2.175675,2.309732,1.827352,1.968853,1.794874,0.500255,...,0.252210,0.599867,0.611592,0.379491,0.160439,0.015002,0.015357,0.156041,0.000006,pass
19,0.643340,1.056714,1.076170,1.671408,1.946927,2.192926,2.248099,1.961151,1.992854,0.458851,...,0.344863,0.837917,0.814879,0.458647,0.182296,0.018268,0.019968,0.252231,0.000007,pass

BARINEL SCORES

,ry 23,cx 17,ry 10,ry 1,ry 12,cx 18,ry 19,ry 20,ry 4,cx 15,...,ry 13,ry 14,cx 5,ry 3,ry 0,cx 6,cx 8,ry 11,ry 22,ry 21
sum,0.552686,0.531774,0.526735,0.524191,0.522843,0.522653,0.522374,0.521299,0.519804,0.518864,...,0.513515,0.510101,0.508754,0.508561,0.506292,0.504806,0.502285,0.500362,0.494471,0.476092

TARANTULA SCORES

,ry 23,cx 17,ry 10,ry 1,ry 12,cx 18,ry 19,ry 20,ry 4,cx 15,...,ry 13,ry 14,cx 5,ry 3,ry 0,cx 6,cx 8,ry 11,ry 22,ry 21
sum,0.552686,0.531774,0.526735,0.524191,0.522843,0.522653,0.522374,0.521299,0.519804,0.518864,...,0.513515,0.510101,0.508754,0.508561,0.506292,0.504806,0.502285,0.500362,0.494471,0.476092

DSTAR SCORES

,cx 18,cx 17,ry 19,cx 16,ry 20,cx 15,ry 22,ry 13,ry 21,ry 12,...,ry 14,cx 5,cx 8,ry 1,ry 4,ry 2,ry 3,ry 0,ry 10,ry 11
sum,15.683055,14.777886,14.17072,12.230598,11.255188,11.180695,6.020077,3.474675,2.965159,2.745202,...,1.47493,1.100564,0.595255,0.307203,0.239747,0.002573,0.002351,3.359107e-10,1.228288e-10,2.684644e-11

ERROR GATE LOCATION:
14
Now evolving the following mutant:  AddGate_h_inGap_9_.qasm

100%|██████████| 10/10 [00:20<00:00,  2.01s/it]
100%|██████████| 10/10 [00:19<00:00,  1.96s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,h 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.650519,1.351697,1.013027,1.765788,2.041920,2.357138,2.755185,2.364069,2.311935,0.642922,...,0.365672,0.220957,0.526687,0.550626,0.208974,0.014277,0.017269,0.374334,0.000007,fail
1,0.445448,0.582284,0.575725,1.474131,1.304522,1.456416,1.619779,1.521035,1.402301,0.344849,...,0.202205,0.128567,0.338502,0.358894,0.127358,0.008517,0.007386,0.224024,0.000005,fail
2,0.500779,0.930836,0.822791,1.461698,1.612451,1.796990,1.830559,2.069750,1.980322,0.421718,...,0.278635,0.180510,0.468810,0.558878,0.201624,0.012486,0.011941,0.273998,0.000007,fail
3,0.478861,0.721649,0.711413,1.419151,2.175411,2.394976,2.071291,2.254407,2.052946,0.456594,...,0.299872,0.230198,0.538035,0.597897,0.227887,0.014242,0.013293,0.284211,0.000008,fail
4,0.523453,1.016617,0.716563,1.712787,1.733414,1.847789,1.862305,1.649054,1.677678,0.455020,...,0.224816,0.189975,0.422511,0.449675,0.185978,0.011841,0.011847,0.254192,0.000006,fail
5,0.632148,1.341740,0.893501,2.010414,2.080437,2.212913,2.031634,2.072624,1.649267,0.464422,...,0.266649,0.212277,0.501693,0.557057,0.194704,0.012804,0.014469,0.270630,0.000007,fail
6,0.466659,1.063485,0.961394,1.556933,1.497440,1.679829,1.925373,1.682616,1.521856,0.375897,...,0.247409,0.185005,0.387591,0.458772,0.166971,0.013660,0.012689,0.245632,0.000006,fail
7,0.639824,0.950357,1.072731,1.269235,2.517572,2.943494,2.800064,2.549938,3.158454,0.696824,...,0.401852,0.274105,0.587491,0.613288,0.248642,0.018507,0.016318,0.373563,0.000009,fail
8,0.253289,0.877654,0.778521,1.188326,1.792014,1.993774,1.727355,1.649170,1.612423,0.456297,...,0.221186,0.206140,0.440597,0.496301,0.192784,0.014130,0.012815,0.227284,0.000006,fail
9,0.517516,0.932993,0.549597,1.961425,2.240593,2.367090,1.967498,1.944454,1.707293,0.470830,...,0.257109,0.182426,0.466656,0.516867,0.184691,0.013840,0.012451,0.297412,0.000006,fail
10,0.646395,1.374057,1.170575,2.132735,2.336246,2.527467,2.341835,2.487075,2.181327,0.603925,...,0.344660,0.263521,0.590969,0.658050,0.246953,0.016068,0.017790,0.313502,0.000009,pass
11,0.554837,1.126999,0.700991,1.853065,2.020912,2.170013,1.815006,1.903685,1.774833,0.444549,...,0.264432,0.180451,0.457177,0.480440,0.162717,0.011548,0.012686,0.249856,0.000007,pass
12,0.402624,0.928496,0.632690,1.070682,0.921915,1.084451,1.545911,1.594905,1.518915,0.413293,...,0.232972,0.106011,0.343807,0.396684,0.119480,0.010394,0.010087,0.215053,0.000006,pass
13,0.587324,1.604807,0.888837,1.696051,2.201470,2.324031,1.943253,1.791844,1.657324,0.439641,...,0.239823,0.162068,0.417904,0.490317,0.175515,0.011337,0.015477,0.242308,0.000007,pass
14,0.477515,1.170982,0.539873,1.176729,1.415216,1.433683,1.089204,1.137523,0.940084,0.208724,...,0.142310,0.103136,0.302043,0.346874,0.112423,0.007015,0.009381,0.137236,0.000004,pass
15,0.564362,0.722493,0.615219,1.928368,1.763076,1.759060,1.438164,1.562388,1.498789,0.411244,...,0.204347,0.168208,0.406748,0.447447,0.165939,0.010844,0.009217,0.212067,0.000005,pass
16,0.335299,0.835279,0.594224,1.017440,1.280518,1.539056,1.925675,1.828044,2.094818,0.454212,...,0.275711,0.130193,0.381391,0.430526,0.174139,0.010042,0.010500,0.282707,0.000006,pass
17,0.566281,0.901068,0.948874,1.569517,2.036126,2.144192,1.676993,1.367896,1.243927,0.418008,...,0.183266,0.228023,0.382303,0.409378,0.181569,0.010798,0.012496,0.186919,0.000006,pass
18,0.466129,0.838003,0.657556,1.565323,1.673938,1.834423,1.705445,1.916163,1.752200,0.450325,...,0.262021,0.141031,0.430901,0.483393,0.158746,0.010069,0.010650,0.257060,0.000006,pass
19,0.256036,0.719120,0.741398,1.394736,1.707838,1.829893,1.599553,1.771854,1.553720,0.388091,...,0.227681,0.178271,0.424711,0.500089,0.174255,0.011426,0.012141,0.223075,0.000006,pass

BARINEL SCORES

,cx 9,ry 3,ry 1,cx 7,cx 17,ry 13,cx 15,ry 11,h 8,ry 4,...,cx 18,cx 5,ry 19,ry 2,ry 21,ry 0,ry 12,ry 23,ry 20,ry 22
sum,0.562057,0.550776,0.549124,0.547568,0.546586,0.541186,0.5405,0.538519,0.537742,0.537088,...,0.530281,0.526275,0.522536,0.520031,0.51941,0.519115,0.518921,0.512629,0.506649,0.488695

TARANTULA SCORES

,cx 9,ry 3,ry 1,cx 7,cx 17,ry 13,cx 15,ry 11,h 8,ry 4,...,cx 18,cx 5,ry 19,ry 2,ry 21,ry 0,ry 12,ry 23,ry 20,ry 22
sum,0.562057,0.550776,0.549124,0.547568,0.546586,0.541186,0.5405,0.538519,0.537742,0.537088,...,0.530281,0.526275,0.522536,0.520031,0.51941,0.519115,0.518921,0.512629,0.506649,0.488695

DSTAR SCORES

,cx 17,cx 18,cx 16,cx 15,ry 19,ry 20,ry 22,ry 21,ry 13,ry 10,...,cx 9,ry 1,h 8,cx 7,ry 4,ry 3,ry 2,ry 0,ry 11,ry 12
sum,15.656382,15.468671,14.266228,13.878414,13.189898,9.851303,4.719747,3.746849,2.865094,1.928442,...,0.65024,0.647918,0.617867,0.34652,0.322325,0.001784,0.001682,4.393927e-10,1.099103e-10,2.503249e-11

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_x_inGap_7_.qasm

100%|██████████| 10/10 [00:20<00:00,  2.04s/it]
100%|██████████| 10/10 [00:19<00:00,  1.93s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,cx 15,ry 14,...,cx 8,cx 7,x 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.526864,1.209827,0.548828,1.266427,1.843853,2.098238,2.276967,2.392340,2.021480,0.510222,...,0.631934,0.638222,0.117164,0.535845,0.269242,0.017242,0.021093,0.217134,0.000007,fail
1,0.671988,1.454741,0.958799,1.962166,2.383853,2.445033,1.645571,1.875150,1.867210,0.453942,...,0.574981,0.620566,0.101644,0.477617,0.242693,0.013995,0.019141,0.172833,0.000007,fail
2,0.755174,1.621823,1.020762,2.695359,2.032716,1.979114,1.663771,1.629606,1.468611,0.294795,...,0.535313,0.636195,0.118391,0.452763,0.196929,0.017990,0.019740,0.185214,0.000006,fail
3,0.733015,1.679697,1.021932,1.995064,2.529803,2.715155,2.414504,2.213843,2.038910,0.532220,...,0.713905,0.771993,0.127101,0.588678,0.280172,0.019261,0.023931,0.251301,0.000009,fail
4,0.560891,0.874775,0.507508,1.666529,1.901127,1.978190,1.499729,1.599997,1.441439,0.313392,...,0.459249,0.507572,0.097173,0.357195,0.158459,0.013545,0.016927,0.144734,0.000006,fail
5,0.497865,1.524782,0.732154,1.867349,1.557480,1.536472,1.192737,1.161738,1.057557,0.300248,...,0.421146,0.405083,0.079416,0.323722,0.152024,0.013498,0.012636,0.120317,0.000004,fail
6,0.495356,0.965206,0.632984,1.510475,2.439228,2.653553,1.920560,1.962148,2.138708,0.490334,...,0.614762,0.651903,0.118621,0.527963,0.246155,0.015420,0.020966,0.229134,0.000008,fail
7,0.611839,1.267505,0.890034,2.112459,1.742905,1.829882,1.734108,1.789041,2.017778,0.497994,...,0.634955,0.693985,0.121779,0.545902,0.272894,0.015665,0.023794,0.233118,0.000006,fail
8,0.539076,1.732971,0.777094,1.128031,2.581137,2.815170,2.276330,2.094496,1.912419,0.526652,...,0.636288,0.622891,0.116013,0.489938,0.253517,0.017825,0.020349,0.215583,0.000009,fail
9,0.563318,1.105115,0.678370,1.066330,1.578641,1.704120,1.353834,1.654862,1.395781,0.248115,...,0.392225,0.461591,0.092642,0.358327,0.161982,0.011950,0.015160,0.120511,0.000005,fail
10,0.394156,0.986296,0.844334,1.880425,1.741758,1.721175,1.198121,1.283584,1.101857,0.307062,...,0.407501,0.426104,0.076215,0.378061,0.189799,0.010884,0.013641,0.119626,0.000005,pass
11,0.291800,0.645352,0.535182,1.429357,0.920546,0.892109,0.851041,0.815167,0.661622,0.207940,...,0.290062,0.279162,0.046028,0.276356,0.145707,0.007552,0.008328,0.090627,0.000003,pass
12,0.484628,1.169619,0.906458,1.660822,2.555908,2.758533,1.903952,1.919128,2.243484,0.650357,...,0.753562,0.812665,0.124101,0.623305,0.312002,0.017101,0.025798,0.261819,0.000009,pass
13,0.564080,1.357215,0.750691,2.026179,1.843446,1.946309,1.889868,1.889576,1.603195,0.507955,...,0.597877,0.592130,0.096382,0.482904,0.235993,0.016540,0.018446,0.194746,0.000006,pass
14,0.249923,0.684998,0.430227,1.168203,0.991371,1.081262,1.146460,1.066367,0.979618,0.303751,...,0.422591,0.447081,0.065763,0.353976,0.175908,0.010276,0.013749,0.146295,0.000003,pass
15,0.548652,1.148145,0.942416,1.540879,1.730713,1.941778,1.846960,1.763515,1.904857,0.493161,...,0.644442,0.665788,0.110433,0.571018,0.284218,0.015711,0.021132,0.239635,0.000007,pass
16,0.320964,0.831222,0.655132,1.640508,1.485155,1.697628,2.123294,2.443031,2.550013,0.548106,...,0.743691,0.755321,0.141809,0.572174,0.268870,0.017127,0.024862,0.280830,0.000007,pass
17,0.524951,1.160404,0.843776,1.643555,1.545139,1.753013,2.221587,1.905714,1.979586,0.564750,...,0.685226,0.640963,0.114210,0.518656,0.255595,0.017734,0.021723,0.259820,0.000007,pass
18,0.292212,1.022368,0.764437,1.494144,1.882133,2.021639,1.432801,1.100733,1.293049,0.358949,...,0.531972,0.531169,0.087660,0.474142,0.230706,0.012674,0.016343,0.193210,0.000006,pass
19,0.405119,0.710803,0.663553,1.218323,2.061870,2.193748,1.568463,1.331655,1.062593,0.357352,...,0.408998,0.330461,0.058163,0.337595,0.183155,0.011488,0.009965,0.122976,0.000006,pass

BARINEL SCORES

,ry 23,ry 22,ry 19,ry 10,cx 18,ry 13,ry 12,cx 16,x 6,ry 11,...,cx 17,ry 20,cx 7,cx 9,ry 21,cx 8,cx 5,ry 1,ry 4,ry 14
sum,0.593647,0.580336,0.55131,0.551006,0.547127,0.543147,0.542438,0.542116,0.54207,0.536212,...,0.526281,0.523774,0.523025,0.521392,0.514309,0.505803,0.503773,0.497407,0.494698,0.492237

TARANTULA SCORES

,ry 23,ry 22,ry 19,ry 10,cx 18,ry 13,ry 12,cx 16,x 6,ry 11,...,cx 17,ry 20,cx 7,cx 9,ry 21,cx 8,cx 5,ry 1,ry 4,ry 14
sum,0.593647,0.580336,0.55131,0.551006,0.547127,0.543147,0.542438,0.542116,0.54207,0.536212,...,0.526281,0.523774,0.523025,0.521392,0.514309,0.505803,0.503773,0.497407,0.494698,0.492237

DSTAR SCORES

,cx 18,ry 19,cx 16,cx 17,cx 15,ry 20,ry 22,ry 21,ry 13,ry 23,...,ry 14,cx 9,ry 4,ry 1,x 6,ry 2,ry 3,ry 0,ry 11,ry 12
sum,16.898404,15.844909,13.228664,12.344575,11.87421,11.604346,9.156731,3.481099,2.558657,2.519565,...,1.214844,0.480829,0.406373,0.299896,0.108782,0.003689,0.002413,4.459173e-10,9.010984e-11,2.369267e-11

ERROR GATE LOCATION:
6
Now evolving the following mutant:  AddGate_ry_inGap_16_.qasm

100%|██████████| 10/10 [00:19<00:00,  1.93s/it]
100%|██████████| 10/10 [00:18<00:00,  1.80s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,cx 16,ry 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.562862,1.106737,0.681172,2.087054,2.244810,2.330580,1.971518,2.521153,0.301316,2.595984,...,0.170545,0.679428,0.777884,0.539919,0.261180,0.018358,0.025462,0.235907,0.000008,fail
1,0.633586,0.985972,0.579087,1.842501,2.025569,2.074656,1.796847,2.024045,0.231320,1.663293,...,0.155435,0.491658,0.549566,0.395126,0.200030,0.015787,0.018615,0.151368,0.000005,fail
2,0.722013,0.893730,0.772661,1.360991,2.258759,2.509301,2.290240,2.380636,0.299690,2.407910,...,0.241225,0.631453,0.725938,0.532451,0.263634,0.019285,0.024946,0.247648,0.000008,fail
3,0.604577,1.165182,0.801855,1.165747,2.075664,2.371938,2.264902,2.239057,0.258312,2.139888,...,0.225406,0.695794,0.739195,0.506503,0.237278,0.016023,0.023632,0.244411,0.000008,fail
4,0.646969,1.047136,0.912175,1.329673,1.767768,2.096455,2.525359,2.267538,0.245980,2.027564,...,0.358200,0.718397,0.762286,0.608761,0.293056,0.020232,0.025113,0.288308,0.000008,fail
5,0.744936,1.386339,0.943701,1.847351,2.120666,2.290080,2.089286,1.886279,0.256702,1.959230,...,0.240450,0.636777,0.678558,0.491144,0.250427,0.018297,0.021844,0.240536,0.000007,fail
6,0.659966,1.481684,0.884266,1.743610,2.181902,2.374817,2.186438,2.382619,0.279614,2.307591,...,0.262098,0.759512,0.840371,0.592145,0.283342,0.019564,0.026724,0.264027,0.000008,fail
7,0.615466,0.978426,0.818122,1.340023,1.725572,2.011730,2.452908,2.465609,0.272870,2.289355,...,0.243692,0.699215,0.746160,0.569639,0.275684,0.018903,0.024696,0.264704,0.000008,fail
8,0.539583,1.371479,0.940071,1.791227,2.035330,2.300354,2.535782,2.418976,0.288634,2.306409,...,0.367979,0.807010,0.871796,0.700369,0.318822,0.022772,0.028869,0.309391,0.000009,fail
9,0.608807,1.021543,0.728983,1.458138,1.494194,1.555844,1.323639,1.405132,0.204991,1.506306,...,0.220483,0.436990,0.531180,0.365577,0.182757,0.013358,0.017555,0.163735,0.000005,fail
10,0.550058,1.211137,0.831027,1.946535,1.739977,1.848451,1.889193,1.520307,0.182561,1.385612,...,0.306272,0.542292,0.497938,0.475038,0.266586,0.014431,0.017363,0.188558,0.000006,pass
11,0.509545,1.051834,0.781209,1.502562,1.975920,2.208938,2.006019,1.871685,0.208877,1.843157,...,0.307147,0.637494,0.686025,0.535661,0.270387,0.016437,0.021468,0.239464,0.000008,pass
12,0.538158,1.419454,0.946441,2.400192,2.560754,2.530072,1.372143,1.426305,0.221291,1.683237,...,0.291620,0.561139,0.610375,0.515044,0.255290,0.015010,0.019725,0.179922,0.000006,pass
13,0.650385,1.470009,0.877200,1.425786,2.294381,2.602107,2.428703,2.690670,0.253871,2.040507,...,0.227688,0.752215,0.776342,0.564725,0.252106,0.018593,0.023903,0.230392,0.000009,pass
14,0.437259,0.943579,0.834757,1.469074,1.400665,1.394122,1.097242,1.010735,0.163199,1.213789,...,0.215544,0.342643,0.400879,0.324656,0.167204,0.010522,0.014104,0.129626,0.000004,pass
15,0.419216,0.883508,0.561207,1.275240,0.922750,1.093396,1.644095,1.502674,0.164264,1.525484,...,0.148425,0.486366,0.485291,0.388563,0.200982,0.013158,0.016127,0.202159,0.000004,pass
16,0.334340,0.945468,0.548882,1.104766,1.066171,1.118366,1.064071,0.861461,0.146465,1.167994,...,0.160900,0.357448,0.338352,0.289138,0.152356,0.008294,0.011892,0.132361,0.000004,pass
17,0.629317,0.860855,0.778219,1.214362,0.967314,1.017690,1.107400,1.079639,0.161758,1.119030,...,0.225907,0.364562,0.383707,0.349699,0.186481,0.010425,0.012783,0.124348,0.000003,pass
18,0.517015,0.962034,0.955724,1.836021,1.796264,1.868086,1.569615,1.124061,0.183829,1.350750,...,0.340272,0.568454,0.554435,0.441764,0.192537,0.015918,0.016443,0.204593,0.000006,pass
19,0.638938,1.309681,1.099861,1.962231,1.714664,1.809877,1.732839,1.412438,0.227733,1.586387,...,0.331882,0.540297,0.536767,0.453581,0.211612,0.015430,0.019229,0.193846,0.000006,pass

BARINEL SCORES

,ry 11,ry 10,ry 9,cx 16,ry 12,cx 14,ry 15,ry 2,cx 6,cx 17,...,cx 18,cx 5,ry 23,ry 19,ry 13,ry 4,ry 22,ry 20,ry 21,cx 8
sum,0.608711,0.607818,0.606292,0.602643,0.591903,0.587039,0.579677,0.578465,0.578156,0.573974,...,0.556141,0.54999,0.548194,0.547999,0.546401,0.543487,0.508461,0.497345,0.495317,0.493043

TARANTULA SCORES

,ry 11,ry 10,ry 9,cx 16,ry 12,cx 14,ry 15,ry 2,cx 6,cx 17,...,cx 18,cx 5,ry 23,ry 19,ry 13,ry 4,ry 22,ry 20,ry 21,cx 8
sum,0.608711,0.607818,0.606292,0.602643,0.591903,0.587039,0.579677,0.578465,0.578156,0.573974,...,0.556141,0.54999,0.548194,0.547999,0.546401,0.543487,0.508461,0.497345,0.495317,0.493043

DSTAR SCORES

,cx 16,cx 14,cx 17,cx 18,ry 19,ry 20,ry 22,ry 12,ry 21,cx 6,...,ry 13,ry 15,ry 4,cx 8,ry 1,ry 2,ry 3,ry 0,ry 10,ry 11
sum,19.739041,18.044254,17.735163,17.471115,15.02388,9.753431,6.213116,3.842487,3.568434,3.416528,...,1.627069,0.584747,0.541764,0.492031,0.491174,0.005543,0.003288,5.440017e-10,1.403029e-10,3.342621e-11

ERROR GATE LOCATION:
15
Now evolving the following mutant:  AddGate_y_inGap_20_.qasm

100%|██████████| 10/10 [00:20<00:00,  2.09s/it]
100%|██████████| 10/10 [00:23<00:00,  2.32s/it]

,ry 23,ry 22,ry 21,ry 20,y 19,ry 18,cx 17,cx 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.541872,1.039054,0.650358,1.894436,0.448311,1.699266,1.743382,1.469979,1.454345,1.412360,...,0.196002,0.429109,0.427045,0.359014,0.195401,0.013640,0.014352,0.154571,0.000005,fail
1,0.691159,1.243893,0.623246,2.158032,0.483146,2.112198,2.213910,1.817719,1.983933,1.761029,...,0.238192,0.578298,0.616491,0.470158,0.241896,0.016629,0.019754,0.187703,0.000007,fail
2,0.632375,0.940159,0.733019,1.485982,0.331439,2.319761,2.502051,2.147339,1.908644,1.576429,...,0.242308,0.579011,0.548989,0.428365,0.197047,0.016664,0.017989,0.184312,0.000007,fail
3,0.606143,1.343819,0.853138,1.531072,0.358217,2.226653,2.503150,2.510356,2.102144,1.651957,...,0.317423,0.700295,0.630405,0.485039,0.228841,0.019717,0.019199,0.234919,0.000008,fail
4,0.601357,1.197679,0.747517,1.994917,0.434240,2.291596,2.461979,2.173585,2.038840,1.812061,...,0.220053,0.666473,0.640946,0.473863,0.227448,0.017040,0.020595,0.222873,0.000007,fail
5,0.722239,1.625410,1.109792,2.011835,0.434949,1.975845,2.230074,2.340890,2.066620,2.172153,...,0.321263,0.791857,0.787864,0.568085,0.255856,0.021371,0.025036,0.292141,0.000008,fail
6,0.448096,1.257044,0.745294,1.775563,0.395336,1.855208,2.082730,2.219377,2.248016,1.912993,...,0.246922,0.695615,0.698179,0.519276,0.248014,0.019173,0.021142,0.241468,0.000008,fail
7,0.346921,1.179548,0.876160,1.689121,0.409393,1.738034,1.882807,1.637774,1.875123,2.183228,...,0.242820,0.634272,0.683372,0.592078,0.297133,0.014558,0.023434,0.232779,0.000007,fail
8,0.544538,1.263194,0.890367,2.338866,0.515509,2.271908,2.322010,1.488822,1.748504,1.895583,...,0.250283,0.622859,0.657852,0.494886,0.221897,0.014920,0.020552,0.190997,0.000007,fail
9,0.573196,1.207242,0.477547,1.310577,0.360425,2.139243,2.356884,2.123209,2.040724,1.895011,...,0.182590,0.556589,0.523505,0.406636,0.206880,0.017325,0.019271,0.203369,0.000006,fail
10,0.506706,0.980714,0.857644,1.719620,0.449406,1.653102,1.694540,1.314579,1.260337,1.327483,...,0.294288,0.461480,0.462297,0.422620,0.211345,0.012866,0.016642,0.155427,0.000005,pass
11,0.559824,1.078721,0.604916,1.120883,0.248407,1.567498,1.875001,2.314272,1.969688,1.840338,...,0.193345,0.630198,0.622912,0.474551,0.247746,0.017131,0.020651,0.253487,0.000007,pass
12,0.416735,0.854929,0.562061,1.242030,0.309325,1.517576,1.814088,2.439836,2.195000,1.916974,...,0.244465,0.650143,0.633891,0.551327,0.282653,0.017102,0.022150,0.261537,0.000007,pass
13,0.524089,1.490694,0.890851,1.404785,0.297270,2.284266,2.559739,2.242531,2.037638,2.098908,...,0.341046,0.766096,0.773690,0.602559,0.269033,0.017748,0.023532,0.261435,0.000009,pass
14,0.734697,1.290302,0.701959,1.636587,0.348590,1.964713,2.235378,2.550784,2.525630,1.964966,...,0.201873,0.732960,0.698012,0.487807,0.230004,0.019389,0.021738,0.243970,0.000008,pass
15,0.553875,0.923684,0.819561,1.491521,0.305208,1.665075,1.866604,1.917232,1.305189,1.325149,...,0.319746,0.583294,0.527328,0.455501,0.218959,0.017171,0.017381,0.216515,0.000006,pass
16,0.513458,1.130972,0.771326,1.463217,0.327232,1.870929,2.113058,2.178092,2.167988,1.879267,...,0.220193,0.598190,0.630314,0.539379,0.272048,0.016912,0.020609,0.220413,0.000007,pass
17,0.562498,1.117034,0.827041,1.149653,0.241763,1.621912,1.821548,1.744048,1.390471,1.054899,...,0.279959,0.460505,0.439855,0.404416,0.218312,0.013558,0.014394,0.154857,0.000005,pass
18,0.384219,0.824367,0.525747,1.376980,0.345031,1.484644,1.575857,1.404071,1.122503,0.910365,...,0.165217,0.386731,0.356795,0.336790,0.168372,0.011466,0.012232,0.139081,0.000004,pass
19,0.541082,1.379193,0.622815,1.088300,0.228167,1.850812,2.005131,1.623625,1.741742,1.676497,...,0.191767,0.501828,0.541133,0.368477,0.163949,0.015330,0.017443,0.165116,0.000006,pass

BARINEL SCORES

,y 19,ry 20,ry 18,ry 11,ry 12,cx 14,cx 17,ry 22,cx 15,ry 9,...,ry 2,ry 3,ry 23,ry 13,ry 21,ry 1,cx 5,ry 4,cx 16,cx 8
sum,0.573615,0.570519,0.541317,0.53663,0.534605,0.533238,0.532705,0.526242,0.523542,0.522879,...,0.51875,0.518746,0.51866,0.517628,0.517546,0.50869,0.508155,0.504127,0.502521,0.500607

TARANTULA SCORES

,y 19,ry 20,ry 18,ry 11,ry 12,cx 14,cx 17,ry 22,cx 15,ry 9,...,ry 2,ry 3,ry 23,ry 13,ry 21,ry 1,cx 5,ry 4,cx 16,cx 8
sum,0.573615,0.570519,0.541317,0.53663,0.534605,0.533238,0.532705,0.526242,0.523542,0.522879,...,0.51875,0.518746,0.51866,0.517628,0.517546,0.50869,0.508155,0.504127,0.502521,0.500607

DSTAR SCORES

,cx 17,ry 18,ry 20,cx 15,cx 16,cx 14,ry 22,ry 21,ry 12,cx 7,...,ry 13,y 19,cx 8,ry 4,ry 1,ry 2,ry 3,ry 0,ry 10,ry 11
sum,16.820993,15.486786,13.965418,13.672875,13.359553,12.844675,7.176691,3.456092,2.770657,2.480259,...,1.488082,1.32797,0.485152,0.438376,0.381184,0.003979,0.00288,4.947553e-10,1.077317e-10,2.542829e-11

ERROR GATE LOCATION:
19
Now evolving the following mutant:  AddGate_y_inGap_26_.qasm

100%|██████████| 10/10 [00:21<00:00,  2.12s/it]
100%|██████████| 10/10 [00:20<00:00,  2.08s/it]

,ry 23,ry 22,y 21,ry 20,ry 19,ry 18,cx 17,cx 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.581266,1.216155,0.477801,0.970822,2.079842,2.341803,2.404239,1.770480,1.763500,1.939131,...,0.366006,0.636379,0.680789,0.521206,0.248456,0.018072,0.022167,0.212345,0.000007,fail
1,0.555689,1.166294,0.481211,1.085027,2.060662,2.198287,2.353573,1.955867,2.027307,1.791582,...,0.268918,0.684445,0.675928,0.558559,0.247714,0.018447,0.020755,0.219296,0.000008,fail
2,0.578056,1.587292,0.482057,1.077615,1.822659,3.181526,3.435615,2.581990,2.389052,2.098983,...,0.316441,0.782038,0.778299,0.631232,0.309814,0.020311,0.023414,0.256381,0.000010,fail
3,0.723134,1.581938,0.405456,0.961264,2.161040,1.988531,2.211052,2.495915,2.104889,1.888384,...,0.330666,0.757960,0.742890,0.524816,0.221751,0.022113,0.023957,0.270510,0.000008,fail
4,0.502703,1.236919,0.451956,0.968006,1.801416,1.705608,1.804289,1.676138,1.582796,1.588643,...,0.273089,0.594431,0.615708,0.509197,0.226332,0.015655,0.019236,0.203879,0.000006,fail
5,0.594916,1.621531,0.519544,1.105976,1.803217,2.348285,2.473911,1.981218,2.164837,1.950201,...,0.296790,0.685605,0.698915,0.537664,0.212476,0.019348,0.021179,0.198317,0.000008,fail
6,0.750074,1.494541,0.446379,1.037838,2.107712,1.916750,2.065780,2.298779,2.024480,1.737785,...,0.301277,0.645589,0.680853,0.527356,0.264145,0.021361,0.022266,0.246157,0.000007,fail
7,0.681821,1.244440,0.442450,0.887120,2.036223,2.314892,2.573829,2.406463,2.250611,2.191481,...,0.319921,0.742430,0.750389,0.582911,0.252318,0.023109,0.024274,0.272660,0.000009,fail
8,0.521529,1.070771,0.384147,0.781613,1.424641,1.388860,1.538139,1.839655,1.576933,1.334292,...,0.248256,0.522236,0.455564,0.405272,0.178403,0.014919,0.015742,0.174884,0.000006,fail
9,0.571329,0.994183,0.430143,0.917335,1.759060,1.750399,1.781577,1.569846,1.730372,1.651105,...,0.246328,0.492899,0.557955,0.392058,0.176384,0.014765,0.018776,0.149202,0.000005,fail
10,0.409531,0.913318,0.347100,0.650035,1.481150,1.916364,1.938168,1.243987,1.121506,0.925026,...,0.290038,0.432391,0.390655,0.317460,0.131392,0.010926,0.012222,0.102005,0.000005,pass
11,0.581759,0.911844,0.375097,0.711718,1.450699,1.877336,2.051198,1.846460,1.609737,1.452822,...,0.250891,0.504688,0.482589,0.406860,0.210667,0.015487,0.015917,0.178613,0.000006,pass
12,0.667586,1.431697,0.472706,0.980041,1.639136,2.282782,2.413108,2.055898,1.793144,1.490782,...,0.307336,0.537516,0.563366,0.513130,0.279607,0.016806,0.016861,0.186320,0.000007,pass
13,0.369552,0.634736,0.318855,0.662357,1.038303,0.836807,0.846832,0.779960,0.711361,0.614073,...,0.188063,0.253361,0.258955,0.235322,0.098637,0.007742,0.008312,0.076530,0.000003,pass
14,0.544773,1.338414,0.341601,0.754667,1.348620,2.090679,2.160535,1.427228,1.066245,1.141323,...,0.283517,0.469880,0.436787,0.369264,0.176323,0.014757,0.013697,0.149383,0.000006,pass
15,0.638112,0.992714,0.414830,0.836701,1.876511,1.631911,1.859777,2.110590,2.083118,1.975397,...,0.294664,0.672344,0.709872,0.539049,0.262713,0.017233,0.022450,0.242444,0.000007,pass
16,0.505264,1.186750,0.365040,0.737453,1.289044,2.268014,2.509107,2.061439,1.742872,2.010457,...,0.314557,0.636890,0.648534,0.560066,0.282176,0.018133,0.022740,0.248486,0.000008,pass
17,0.411737,0.820179,0.314082,0.638646,1.444319,1.251673,1.236797,0.940306,1.014880,0.930560,...,0.174742,0.324856,0.334177,0.322681,0.153051,0.009787,0.011508,0.093443,0.000004,pass
18,0.188883,0.678150,0.269202,0.556144,1.266272,1.093404,1.280124,1.529607,1.344123,1.313085,...,0.206479,0.505677,0.518672,0.469833,0.249032,0.009560,0.016909,0.198819,0.000005,pass
19,0.507932,1.472557,0.321773,0.737957,2.065725,2.380305,2.483877,2.059886,2.014327,1.773270,...,0.172532,0.645050,0.626921,0.510821,0.268891,0.015765,0.018738,0.207339,0.000007,pass

BARINEL SCORES

,ry 3,ry 11,cx 15,ry 20,ry 13,ry 12,ry 10,cx 6,cx 14,ry 2,...,y 21,ry 22,ry 23,ry 0,ry 9,cx 5,cx 17,ry 18,cx 8,ry 4
sum,0.580027,0.57626,0.574942,0.574066,0.573818,0.572562,0.571885,0.571795,0.571463,0.570615,...,0.560836,0.56005,0.556744,0.556721,0.553556,0.550122,0.546624,0.545218,0.544479,0.525313

TARANTULA SCORES

,ry 3,ry 11,cx 15,ry 20,ry 13,ry 12,ry 10,cx 6,cx 14,ry 2,...,y 21,ry 22,ry 23,ry 0,ry 9,cx 5,cx 17,ry 18,cx 8,ry 4
sum,0.580027,0.57626,0.574942,0.574066,0.573818,0.572562,0.571885,0.571795,0.571463,0.570615,...,0.560836,0.56005,0.556744,0.556721,0.553556,0.550122,0.546624,0.545218,0.544479,0.525313

DSTAR SCORES

,cx 17,cx 16,ry 18,cx 15,ry 19,cx 14,ry 22,ry 20,ry 12,cx 6,...,ry 13,y 21,cx 8,ry 4,ry 1,ry 2,ry 3,ry 0,ry 10,ry 11
sum,17.813369,16.249485,16.167116,15.702811,14.584431,13.975935,8.567633,5.554086,2.955356,2.942688,...,1.782231,1.509624,0.705545,0.45121,0.415632,0.004414,0.003491,5.373020e-10,1.020772e-10,2.634327e-11

ERROR GATE LOCATION:
21
Now evolving the following mutant:  AddGate_ry_inGap_17_.qasm

100%|██████████| 10/10 [00:21<00:00,  2.14s/it]
100%|██████████| 10/10 [00:21<00:00,  2.13s/it]

,ry 23,ry 22,ry 21,ry 20,ry 19,cx 18,cx 17,ry 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.476071,1.039024,0.633365,1.665090,1.526127,1.714822,2.069474,1.029565,0.377257,1.080065,...,0.306686,0.419764,0.534604,0.604349,0.200631,0.014825,0.012524,0.210240,0.000007,fail
1,0.448267,1.101082,0.681320,1.689585,1.928704,2.056057,1.772393,0.938510,0.394501,1.065742,...,0.292525,0.417151,0.502790,0.515824,0.191141,0.013317,0.014451,0.225493,0.000006,fail
2,0.597385,1.344851,0.852931,2.019370,2.005397,2.079762,1.901185,1.106669,0.495821,1.322574,...,0.408278,0.440493,0.550509,0.559239,0.197538,0.015776,0.016438,0.275583,0.000007,fail
3,0.703485,1.103749,0.876613,1.610958,2.142076,2.260596,2.095357,1.555099,0.571633,1.197690,...,0.483625,0.425087,0.606793,0.606244,0.201986,0.013957,0.016465,0.316666,0.000008,fail
4,0.509639,0.889752,0.596947,1.241832,1.760874,1.898745,1.819431,1.003761,0.371726,1.003876,...,0.347988,0.371980,0.479047,0.512561,0.160502,0.011855,0.011819,0.198218,0.000007,fail
5,0.567932,1.387500,1.069910,1.668581,1.908487,2.004453,1.991635,1.403543,0.559230,1.451888,...,0.509946,0.451503,0.590060,0.632970,0.232125,0.015435,0.017255,0.336919,0.000008,fail
6,0.612605,1.106242,0.623645,1.785269,2.519136,2.748969,2.348213,1.390930,0.409248,1.350334,...,0.354284,0.446167,0.585094,0.665385,0.197312,0.016210,0.015603,0.225449,0.000009,fail
7,0.352740,0.918297,0.442399,1.649428,1.763056,1.931510,1.910110,1.244773,0.325926,1.007537,...,0.342000,0.362061,0.511126,0.557939,0.195588,0.011932,0.012414,0.195218,0.000007,fail
8,0.564088,1.149987,0.670659,1.560893,1.411092,1.630500,1.883193,1.007455,0.304829,0.854027,...,0.218478,0.355880,0.489749,0.485724,0.132701,0.012988,0.012882,0.160888,0.000006,fail
9,0.643435,1.244574,1.012913,1.403640,1.979632,2.264424,2.520776,1.267886,0.501251,1.291019,...,0.403475,0.540777,0.664331,0.710450,0.240470,0.017431,0.016395,0.288092,0.000009,fail
10,0.481614,1.595243,0.974452,1.516584,1.829694,2.025018,2.208198,1.233208,0.475464,1.353009,...,0.353091,0.532659,0.585169,0.642371,0.241425,0.015919,0.016989,0.283755,0.000009,pass
11,0.554674,1.204226,0.595184,1.641363,2.031211,2.146237,1.658514,0.811140,0.319781,0.923369,...,0.261070,0.378758,0.492813,0.482463,0.182950,0.011242,0.013521,0.174276,0.000006,pass
12,0.492151,1.553155,1.037949,2.140948,1.458115,1.443352,1.379380,0.822178,0.530614,1.166194,...,0.428566,0.387048,0.471516,0.465128,0.181295,0.014122,0.014908,0.300213,0.000005,pass
13,0.509765,1.107128,0.794197,1.743174,2.010143,2.125120,1.883846,0.974480,0.478555,1.278532,...,0.340366,0.462529,0.515514,0.551953,0.218187,0.014517,0.015974,0.256029,0.000007,pass
14,0.517521,0.842951,0.714957,1.375193,2.091903,2.213416,1.659626,1.048572,0.447635,1.011702,...,0.384293,0.338997,0.458126,0.479631,0.153164,0.011473,0.012526,0.236810,0.000008,pass
15,0.547424,1.305001,1.015694,1.440295,1.391568,1.530149,1.815492,1.083598,0.483921,1.190023,...,0.439705,0.427951,0.539477,0.572206,0.214847,0.013692,0.014553,0.294680,0.000007,pass
16,0.459708,0.923463,0.757663,1.402805,2.376396,2.636725,2.051664,1.126325,0.524542,1.018380,...,0.396708,0.409246,0.620906,0.623127,0.224613,0.014337,0.015360,0.274505,0.000007,pass
17,0.601587,1.404481,0.747356,1.422835,2.635134,2.794607,2.083306,1.313563,0.504147,1.392175,...,0.383264,0.452210,0.573989,0.596393,0.231926,0.014940,0.016970,0.283924,0.000009,pass
18,0.548728,1.330699,0.747819,1.618717,2.515489,2.631242,1.795852,0.913014,0.437515,1.099459,...,0.375813,0.432059,0.512259,0.500642,0.193713,0.012791,0.013870,0.248556,0.000008,pass
19,0.270874,0.940067,0.689973,0.480079,1.347512,1.668215,1.830992,0.746390,0.371302,0.979416,...,0.275391,0.408835,0.475389,0.521341,0.196022,0.012285,0.012458,0.200111,0.000007,pass

BARINEL SCORES

,ry 11,ry 16,cx 17,ry 20,ry 23,ry 10,cx 5,ry 3,cx 6,ry 13,...,ry 2,ry 12,cx 18,ry 19,ry 9,ry 4,ry 1,cx 15,ry 22,ry 21
sum,0.543369,0.54259,0.525142,0.524337,0.5235,0.522879,0.518405,0.515068,0.512498,0.512474,...,0.498496,0.498035,0.492534,0.490389,0.489337,0.488949,0.487956,0.485253,0.48039,0.480222

TARANTULA SCORES

,ry 11,ry 16,cx 17,ry 20,ry 23,ry 10,cx 5,ry 3,cx 6,ry 13,...,ry 2,ry 12,cx 18,ry 19,ry 9,ry 4,ry 1,cx 15,ry 22,ry 21
sum,0.543369,0.54259,0.525142,0.524337,0.5235,0.522879,0.518405,0.515068,0.512498,0.512474,...,0.498496,0.498035,0.492534,0.490389,0.489337,0.488949,0.487956,0.485253,0.48039,0.480222

DSTAR SCORES

,cx 17,cx 18,ry 19,ry 20,ry 16,cx 14,ry 22,ry 21,cx 5,ry 23,...,cx 8,ry 13,ry 9,ry 1,ry 4,ry 2,ry 3,ry 0,ry 10,ry 11
sum,14.544005,13.581737,12.089303,10.71405,7.112193,6.311099,5.734944,3.079465,2.217683,2.000975,...,0.986121,0.760763,0.75438,0.471474,0.315869,0.002108,0.002038,5.464209e-10,5.543753e-11,2.964029e-11

ERROR GATE LOCATION:
16
Now evolving the following mutant:  AddGate_z_inGap_20_.qasm

100%|██████████| 10/10 [00:20<00:00,  2.00s/it]
100%|██████████| 10/10 [00:20<00:00,  2.00s/it]

,ry 23,ry 22,ry 21,ry 20,z 19,ry 18,cx 17,cx 16,cx 15,cx 14,...,cx 8,cx 7,cx 6,cx 5,ry 4,ry 3,ry 2,ry 1,ry 0,pass/fail
0,0.626838,1.230841,0.929730,2.236950,0.547876,2.252738,2.381007,2.148739,1.996404,1.759328,...,0.327669,0.632726,0.639553,0.602949,0.311311,0.019753,0.021576,0.232031,0.000006,fail
1,0.691331,0.979619,0.764583,1.471769,0.366283,2.133906,2.483610,2.608966,2.438397,2.322474,...,0.313765,0.791535,0.831107,0.631063,0.311591,0.021256,0.027530,0.306652,0.000008,fail
2,0.435493,0.901186,0.586843,2.260513,0.529405,1.211675,1.232050,1.499257,1.453708,1.446522,...,0.155156,0.463895,0.502479,0.384598,0.184374,0.013689,0.016963,0.186459,0.000004,fail
3,0.652334,1.362179,0.627883,1.558593,0.393720,1.938897,2.004328,1.526733,1.357807,1.372302,...,0.174936,0.433813,0.447183,0.367003,0.200028,0.013924,0.015561,0.155314,0.000005,fail
4,0.651294,1.078509,0.698674,2.014375,0.468211,2.306482,2.458143,2.212075,2.436782,2.176217,...,0.241026,0.681806,0.731258,0.538822,0.262533,0.019735,0.024828,0.238554,0.000008,fail
5,0.627145,1.478732,0.645062,1.801971,0.434317,2.826054,2.997529,2.291007,2.196309,1.853103,...,0.222891,0.675226,0.664745,0.491552,0.237914,0.019387,0.021493,0.214192,0.000008,fail
6,0.715176,1.134834,0.917195,2.462679,0.534040,2.172512,2.257172,2.216265,2.119023,1.701578,...,0.327939,0.688021,0.711641,0.567904,0.270596,0.020124,0.021877,0.228516,0.000006,fail
7,0.593467,1.048601,0.706820,1.868469,0.472140,1.784376,2.002124,2.284846,2.132841,1.707042,...,0.339795,0.710561,0.678743,0.520616,0.254203,0.019010,0.022594,0.241726,0.000006,fail
8,0.525376,0.650738,0.601960,1.369829,0.335629,1.322290,1.563831,1.938655,1.951757,1.612849,...,0.176717,0.563081,0.561535,0.417575,0.167457,0.014845,0.018738,0.200055,0.000005,fail
9,0.533695,1.073457,0.536175,1.938960,0.464974,1.828445,1.922370,1.926850,2.052992,2.041874,...,0.163500,0.594285,0.605369,0.502298,0.262648,0.015365,0.020949,0.213119,0.000006,fail
10,0.537537,1.466731,0.904415,1.211288,0.284648,1.661113,1.918657,2.076791,1.674244,1.896381,...,0.305711,0.670482,0.648861,0.544954,0.259998,0.017150,0.022280,0.250734,0.000006,pass
11,0.667456,1.181747,0.676053,1.406692,0.311887,2.265107,2.377836,1.743846,1.451095,1.342028,...,0.291888,0.508856,0.548183,0.408630,0.209804,0.015547,0.016562,0.172950,0.000007,pass
12,0.482991,0.902046,0.619152,1.277239,0.282458,1.518698,1.554862,1.105045,1.080081,1.172466,...,0.247542,0.370203,0.440850,0.348252,0.172714,0.012121,0.014324,0.128980,0.000005,pass
13,0.478361,1.176707,0.686890,1.672664,0.357841,1.850726,2.041378,2.162386,1.958946,1.546705,...,0.223331,0.662229,0.634480,0.498493,0.242203,0.016827,0.020145,0.223632,0.000007,pass
14,0.548040,0.951887,0.732139,2.164098,0.529496,2.528764,2.702512,2.166809,1.561959,1.602562,...,0.343511,0.646890,0.572703,0.501174,0.237542,0.017905,0.020134,0.235052,0.000007,pass
15,0.432432,0.954535,0.884340,1.211322,0.316908,2.464664,2.774307,2.281052,1.944926,1.970377,...,0.371349,0.670211,0.682744,0.603464,0.292625,0.017945,0.022571,0.257663,0.000010,pass
16,0.410044,0.948367,0.920931,1.347679,0.283590,1.110079,1.357059,1.965985,1.756595,1.852661,...,0.283421,0.605561,0.652136,0.551941,0.259825,0.017329,0.021155,0.262085,0.000007,pass
17,0.495981,1.128317,0.942983,1.582043,0.361237,1.545600,1.707821,1.788214,1.306768,1.301669,...,0.281672,0.517680,0.483889,0.452781,0.244019,0.013660,0.015633,0.194962,0.000006,pass
18,0.377840,0.992632,0.678515,1.195649,0.288575,1.265518,1.483950,1.837870,1.904137,1.747863,...,0.224996,0.599877,0.600659,0.548334,0.276868,0.012778,0.020871,0.214919,0.000006,pass
19,0.631745,1.159260,0.949598,2.247982,0.490893,1.954330,1.966376,1.486902,1.309179,1.253482,...,0.275067,0.497419,0.492633,0.461672,0.218649,0.016245,0.016241,0.165203,0.000005,pass

BARINEL SCORES

,z 19,ry 11,cx 15,ry 20,ry 10,ry 23,ry 12,cx 14,ry 3,ry 2,...,ry 9,cx 17,ry 1,ry 13,cx 5,ry 4,ry 22,ry 0,ry 21,cx 8
sum,0.564505,0.561404,0.558033,0.55346,0.553251,0.544524,0.538755,0.534251,0.529262,0.527601,...,0.518542,0.517207,0.512774,0.505427,0.505264,0.504963,0.501754,0.491948,0.467352,0.461725

TARANTULA SCORES

,z 19,ry 11,cx 15,ry 20,ry 10,ry 23,ry 12,cx 14,ry 3,ry 2,...,ry 9,cx 17,ry 1,ry 13,cx 5,ry 4,ry 22,ry 0,ry 21,cx 8
sum,0.564505,0.561404,0.558033,0.55346,0.553251,0.544524,0.538755,0.534251,0.529262,0.527601,...,0.518542,0.517207,0.512774,0.505427,0.505264,0.504963,0.501754,0.491948,0.467352,0.461725

DSTAR SCORES

,cx 15,cx 17,cx 16,ry 20,ry 18,cx 14,ry 22,ry 21,ry 12,cx 6,...,z 19,ry 13,ry 4,cx 8,ry 1,ry 2,ry 3,ry 0,ry 10,ry 11
sum,15.625883,15.184403,14.907013,14.235544,13.887808,12.604379,5.735489,2.734601,2.719971,2.578067,...,1.530372,1.370611,0.488525,0.46466,0.405858,0.004415,0.003087,3.920834e-10,1.160490e-10,2.579398e-11

ERROR GATE LOCATION:
19

,Program,path_to_mutant,exam_score
0,AddGate_z_inGap_20_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_vqe_5_q...,0.041667
1,AddGate_ry_inGap_17_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_vqe_5_q...,0.083333
2,AddGate_y_inGap_26_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_vqe_5_q...,0.625
3,AddGate_y_inGap_20_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_vqe_5_q...,0.041667
4,AddGate_ry_inGap_16_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_vqe_5_q...,0.291667
...,...,...,...
86,AddGate_x_inGap_4_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_vqe_5_q...,0.166667
87,AddGate_y_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_vqe_5_q...,0.125
88,AddGate_y_inGap_9_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_vqe_5_q...,0.166667
89,AddGate_ry_inGap_15_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_vqe_5_q...,0.291667
90,AddGate_y_inGap_23_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_vqe_5_q...,0.083333

,Program,path_to_mutant,exam_score
0,AddGate_z_inGap_20_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_vqe_5_q...,0.041667
1,AddGate_ry_inGap_17_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_vqe_5_q...,0.083333
2,AddGate_y_inGap_26_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_vqe_5_q...,0.625
3,AddGate_y_inGap_20_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_vqe_5_q...,0.041667
4,AddGate_ry_inGap_16_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_vqe_5_q...,0.291667
...,...,...,...
86,AddGate_x_inGap_4_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_vqe_5_q...,0.166667
87,AddGate_y_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_vqe_5_q...,0.125
88,AddGate_y_inGap_9_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_vqe_5_q...,0.166667
89,AddGate_ry_inGap_15_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_vqe_5_q...,0.291667
90,AddGate_y_inGap_23_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_vqe_5_q...,0.083333