<h1 style="text-align: center;">HEISENBERG-BASED FAULT LOCALIZATION (HBFL)</h1>

<h2 style="text-align: center;">Download Initial Dependencies</h2>

In [15]:
import numpy as np
import pandas as pd
import json
import math
from tqdm import tqdm
from qiskit.quantum_info import SparsePauliOp, Operator, Pauli, Clifford
import qiskit.qasm2 as q2
from qiskit import QuantumCircuit
from IPython.display import display

from heisenbergUtilities import *

In [16]:
# from qiskit_aer import AerSimulator
# simulator = AerSimulator()

# print(simulator.available_devices())

<h3>Download MQT Benchmark circuits.</h3>

We'll run this experiment on 11 different quantum circuits, including DJ, GHZ, GraphState, Grover No-Ancilla, QAOA, QFT, QGAN, QPE Exact, QPE Inexact, RealAmpRandom, and VQE.

<h3>Generate mutants.</h3>

We'll start with mutants that add an unnecessary gate, then add mutants that replace a certain gate later. Missing code in SBFL is still a more recent topic even in classical programs.

The mutants were downloaded from QMutBench, choosing specifically mutants that added a gate at any location with 0-10% survival scores

<h2 style="text-align: center;">CONTROL PANEL</h2>

In [17]:
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
#-------------------------------------------------------------------------GENERAL PARAMETERS---------------------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
ALG_NAME = "qaoa"
ORIGINAL_QASM = f"{ALG_NAME}_5_qubits.qasm"                                                 #| The original algorithm QASM circuit file name.                           
ORIGINAL_QASM_FOLDER = "SBFL_circuits/MQTBench/"                                            #| The folder containing the original QASM circuit file.                    
QASM_MUTANT_FOLDER = f"SBFL_circuits/QMutBenchMutants/Mutants_{ALG_NAME}_5_qubits/"         #| The folder containing all mutants related to the original QASM circuit.  
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
#-------------------------------------------------------------------------SB-QOPS PARAMETERS---------------------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
RUNS = 10                                                                                   #| Number of times SB-QOPS will run to find a failing or passing test case.            
SHOTS = 20000                                                                               #| Number of shots for SB-QOPS to use to create the compact program specification.     
EPOCH = 80                                                                                  #| Number of epochs SB-QOPS will run to navigate the search space of test cases.       
SBQOPS_TOL = 0.1                                                                            #| Tolerance value SB-QOPS uses to determine if a test case is failing or passing.     
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
#---------------------------------------------------------------------HEISENBERG SBFL PARAMETERS-----------------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
LAMBDA_WEIGHT = 1                                                                           #| The amount to adjust the "weight difference" in the heuristic           #
LAMBDA_COMP = 1                                                                             #| The amount to weigh the "composition difference" in the heuristic       #
LAMBDA_SUPPORT = 1                                                                          #| The amount to weigh the "support overlap" in the heuristic              #
LAMBDA_DIAMETER = 1                                                                         #| The amount to weigh the "diameter difference" in the heuristic          #
LAMBDA_PHASE = 1                                                                            #| The amount to weigh the "phase" in the heuristic                        #
CUSTOM_WEIGHT = 0.25                                                                        #| The amount of weight the "dstar boost" has in the custom heuristic (WIP)#
ATOL = 1e-4                                                                                 #| The tolerance value used to prune negligible magnitudes during Pauli propagation.   
MAX_TERMS = 100                                                                             #| The maximum number of terms to keep during Pauli propagation. If None, use all.     
SEARCH_STEP = 3                                                                             #| The search step size used during Pauli propagation. If None, pauli-prop uses 4.     
VERBOSE = 1                                                                                 #| A boolean value to determine if the program should print out detailed information.  
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#

Generate the linked list of all gates found in a given circuit

In [18]:
"""
LinkedListNode: A class that holds information related to a gate in a quantum circuit. 

PROPERTIES:
    - value (String): The name of the quantum gate
    - depth (int): The depth of the gate in the circuit
    - count (Int): The probability that the gate will meaningfully change the Pauli string.
    - next (LinkedListNode): The next gate in the circuit

"""

class LinkedListNode:
    def __init__(self, name="Initial", depth=0, count=0,  next=None):
        self.value = name
        self.depth = depth
        self.next = next
        self.count = count

class LinkedList:
    def __init__(self):
        self.head = None

    def append(self, name, depth):
        new_node = LinkedListNode(name, depth)
        if not self.head:
            self.head = new_node
            return
        last_node = self.head
        while last_node.next:
            last_node = last_node.next
        last_node.next = new_node

    def mark(self, depth):
        current_node = self.head
        while current_node:
            if current_node.depth == depth:
                current_node.count += 1
                return
            current_node = current_node.next

    def reset(self):
        current_node = self.head
        while current_node:
            current_node.count = 0
            current_node = current_node.next

<h3>Load correct circuit</h3>
Here we want to load the correct version of the circuit from MQT. We use this both to generate a PS_compact from/for SB-QOPS and to check results from SBFL.

In [19]:
correct_circuit = load_program(ORIGINAL_QASM, ORIGINAL_QASM_FOLDER).copy()
correct_list = LinkedList()
correct_list = construct_list(correct_list, correct_circuit, inverse=False)

<h2 style="text-align: center;"> SB-QOPS </h2>

This is where we will use SB-QOPS on a provided circuit and its mutants

For a single mutant, it took about 2 minutes to generate a 20 test suite (10 fail, 10 pass) on an RTX 4090 SUPER. It can only be run on a Linux environment since the AER Simulator does not support Windows

Expect this cell to take up to a few hours, BUT this cell should only need to be run once per algorithm with mutants under test. After it saves to the csv file at the end, this cell can be commented out as to not accidentally run it again. 

In the future if we want to test this methodology on higher qubit circuits or other algorithms, we'll likely either want to reduce the number of tests in the suite or the number of mutants we're analyzing

In [20]:
# import QOPS as qops
# from QOPS_test import get_compact_program_specification_Z
# from pathlib import Path

# ga_result = pd.DataFrame(columns=['Program',"path_to_mutant",'catch_avg','avg_fitness','failing_testcases', 'passing_testcases'])
# program_history = {}

# #program_specification = The compact program specification. SB-QOPS needs this to generate failing test cases.
# # In a public-use environment, this would be provided by the user.
# program_specification = get_compact_program_specification_Z(correct_circuit, shots=SHOTS)

# #mutants = A python list of qiskit QuantumCircuit variables with a mutation in them
# mutants = []
# mutants_names = []
# root = Path(QASM_MUTANT_FOLDER)
# for qasm_mutant in root.rglob("*.qasm"):
#     mutants.append(load_program(qasm_mutant.name, QASM_MUTANT_FOLDER))
#     mutants_names.append(qasm_mutant.name)

# for mutant_index,mutant in enumerate(mutants):
#     tester = qops.Circuit_Tester(CUT=mutant)
#     tester.set_applicable_families_Z(program_specification)
#     mutants_per_run = []
#     fitness_per_run = []
#     failing_testcases_per_run = []
#     history_per_run = []

#     print("NOW RUNNING TO FIND FAILING TESTS")
#     #For a predefined number of attempts, try to find a set of failing test cases (output is above predefined tolerance)
#     for runs in range(RUNS):
#         killed = 0
#         pauli = {}
#         fitness = 0
#         for i in range(len(tester.applicable_families)):
#             best_function,testcase, history = tester.run_mealoneplusone(i, EPOCH)
#             if best_function > SBQOPS_TOL:
#                 killed = 1
#                 pauli = testcase
#                 fitness = best_function
#                 break
#         mutants_per_run.append(killed)
#         failing_testcases_per_run.append(pauli)
#         fitness_per_run.append(fitness)
#         history_per_run.append(history)

#     avg_score = np.mean(mutants_per_run)
#     avg_fitness = np.mean(fitness_per_run)

#     #Here is our new, modified algorithm from the SB-QOPS method that attempts to find passing test cases as well. We'll need them for SBFL
#     passing_testcases_per_run = []

#     print("NOW RUNNING TO FIND PASSING TESTS")
#     for runs in range(RUNS):
#         pauli = {}
#         fitness = 0
#         for i in range(len(tester.applicable_families)):
#             best_function, testcase, history = tester.run_reverse_mealoneplusone(i,EPOCH)
#             if best_function < SBQOPS_TOL:
#                 pauli = testcase
#                 break
#         passing_testcases_per_run.append(pauli)

#     #Replace static program file with "program_name" when ready to test fully
#     """
#     ga_result: A pandas dataframe with the following columns
#         Program: Name of the mutant quantum circuit file
#         Path_To_Mutant: Path to the mutant file
#         Catch_Avg: The average number of times the mutant was identified by SB-QOPS
#         Avg_Fitness: The average fitness of the search algorithm used. Higher usually indicates higher Catch_Avg
#         Failing_Testcases: A list of dicts indicating the set of Pauli strings and the weights that should be applied to generate a failing test case
#         Passing_Testcases: A list of dicts indicating the set of Pauli strings and the weights that should be applied to generate a passing test case
#     """
#     ga_result = pd.concat([pd.DataFrame([[mutants_names[mutant_index],QASM_MUTANT_FOLDER,avg_score,avg_fitness,json.dumps(failing_testcases_per_run), json.dumps(passing_testcases_per_run)]],columns=ga_result.columns),ga_result],ignore_index=True)
#     ga_result.to_csv(f'realamprandom_ga_result', index=False)

ga_result is a slightly altered pandas Dataframe with similar structure found in SB-QOPS. The differences are changing the column "Program" to be the name of the mutant file instead of the original quantum circuit, changing "Mutant" to be the path to the mutant file instead of being an arbitrary index value, and adding a passing_testcases column that returns Pauli strings and coefficients that generate passing tests.

Now we want to run SBFL using Heisenberg evolution trees on each circuit placed in ga_result

Evolution analysis can vary widely in runtime. Some of the simplest circuits take seconds to analyze and only took upwards of 3-4 minutes to get results on the whole dataset (GHZ was the fastest taking 3 minutes to run). Other, more complex algorithms can take upwards of 6-10 minutes PER MUTANT (RealAmpRandom took longest so far with 14 hours).

The runtime of this code segment is directly tied to the depth of the circuit being analyzed and the number of 2-branching gates such as rotation or phase gates that exist in the circuit.

This is something to note in the final paper. Regardless of accuracy this methodology takes a long time to run. If results are promising, then we'll want to look into the tradeoffs between EXAM and hyperparameters to speed this up. Primarily the atol, max_terms, and search_step parameters in the evolve_pauli_exact method in HeisenbergUtilities.py

<h2 style="text-align: center;">HEISENBERG EVOLUTIONS (PAULI PROPAGATION)</h2>

In [ ]:
from heisenbergTree import *

LAMBDAS = [LAMBDA_WEIGHT, LAMBDA_COMP, LAMBDA_SUPPORT, LAMBDA_DIAMETER, LAMBDA_PHASE]
ga_result = pd.read_csv(f'{ALG_NAME}_ga_result.csv')
custom_sbfl_result = pd.DataFrame(columns=['Program','path_to_mutant','best_exam_score', 'worst_exam_score', 'avg_exam_score'])
barinel_sbfl_result = pd.DataFrame(columns=['Program','path_to_mutant','best_exam_score', 'worst_exam_score', 'avg_exam_score'])
dstar_sbfl_result = pd.DataFrame(columns=['Program','path_to_mutant','best_exam_score', 'worst_exam_score', 'avg_exam_score'])
mutant_num = 0

#For each mutant of a circuit, run the SBFL implementation
for mutant, path in zip(ga_result.loc[:,"Program"], ga_result.loc[:,"path_to_mutant"]):
    print("Now evolving the following mutant: ", mutant)

    #Extract the raw test cases found for each mutant
    raw_failing_testcases = format_test_case(ga_result, mutant, mutant_num, "failing_testcases")
    raw_passing_testcases = format_test_case(ga_result, mutant, mutant_num, "passing_testcases")

    circuit_inverse = load_program(mutant,path).copy().inverse()  # Invert to track backward evolution of the operator
    forward_mutant = load_program(mutant, path).copy()

    #Create the linked list of operations in the inverse circuit
    operation_list = LinkedList()
    operation_list = construct_list(operation_list, circuit_inverse, True)

    forward_list = LinkedList()
    forward_list = construct_list(forward_list, forward_mutant, False)

    #Create list of nodes in linked list. Somewhere down the road remove the linked list implementation. It's unnecessary and giving me a headache
    node_list = []
    node = operation_list.head
    while node:
        node_list.append(node)
        node = node.next

    #Perform Pauli propagation (Heisenberg evolution) for all test cases. Returns a dataframe with all counts for all operations
    global_frame_fail = heisenberg_evolve(circuit_inverse, 
                                          operation_list, 
                                          raw_failing_testcases, 
                                          "fail", 
                                          LAMBDAS,
                                          atol = ATOL, 
                                          max_terms = MAX_TERMS, 
                                          search_step = SEARCH_STEP)
    
    global_frame_pass = heisenberg_evolve(circuit_inverse, 
                                          operation_list, 
                                          raw_passing_testcases, 
                                          "pass", 
                                          LAMBDAS,
                                          atol = ATOL, 
                                          max_terms = MAX_TERMS, 
                                          search_step = SEARCH_STEP)

    global_frame = pd.concat([global_frame_fail, global_frame_pass], ignore_index=True)

    global_frame = global_frame.drop(["Initial"],axis=1)
    if VERBOSE:
        display(global_frame)

    custom_scores = custom_sbfl(global_frame, CUSTOM_WEIGHT)
    barinel_scores = barinel(global_frame)
    dstar_scores = dstar(global_frame)

    if VERBOSE:
        print("BARINEL SCORES")
        display(barinel_scores)
        print("custom SCORES")
        display(custom_scores)
        print("DSTAR SCORES")
        display(dstar_scores)
    
    # Here is where analysis of the methodology begins. 
    # We first extract the position of the erroneous gate by comparing it to the original MQT gate
    # NOTE: This method is intended for single-added gates for now. Other types of mutants will require other methods later
    error_gate_location = find_erroneous_gate(forward_mutant, correct_circuit)

    if VERBOSE:
        print("ERROR GATE LOCATION:")
        print(error_gate_location)

    #Calculate best, worst, and average EXAM for Barinel, custom, and DStar
    barinel_best_exam, barinel_worst_exam, barinel_average_exam = calc_exams(barinel_scores, error_gate_location, circuit_inverse)
    custom_best_exam, custom_worst_exam, custom_average_exam = calc_exams(custom_scores, error_gate_location, circuit_inverse)
    dstar_best_exam, dstar_worst_exam, dstar_average_exam = calc_exams(dstar_scores, error_gate_location, circuit_inverse)

    # Here we store the results from the HBFL analysis for both barinel and custom into a csv file for later analysis.
    barinel_sbfl_result = pd.concat([pd.DataFrame([[mutant,QASM_MUTANT_FOLDER,barinel_best_exam, barinel_worst_exam, barinel_average_exam]],columns=barinel_sbfl_result.columns),barinel_sbfl_result],ignore_index=True)
    barinel_sbfl_result.to_csv(f'{ALG_NAME}_barinel_sbfl_result.csv', index=False)

    custom_sbfl_result = pd.concat([pd.DataFrame([[mutant,QASM_MUTANT_FOLDER,custom_best_exam, custom_worst_exam, custom_average_exam]],columns=custom_sbfl_result.columns),custom_sbfl_result],ignore_index=True)
    custom_sbfl_result.to_csv(f'{ALG_NAME}_custom_sbfl_result.csv', index=False)

    dstar_sbfl_result = pd.concat([pd.DataFrame([[mutant,QASM_MUTANT_FOLDER,dstar_best_exam, dstar_worst_exam, dstar_average_exam]],columns=dstar_sbfl_result.columns),dstar_sbfl_result],ignore_index=True)
    dstar_sbfl_result.to_csv(f'{ALG_NAME}_dstar_sbfl_result.csv', index=False)

    mutant_num += 1

if VERBOSE:
    display(barinel_sbfl_result)
    display(custom_sbfl_result)

Now evolving the following mutant:  AddGate_y_inGap_23_.qasm

100%|██████████| 10/10 [01:25<00:00,  8.56s/it]
100%|██████████| 10/10 [01:31<00:00,  9.13s/it]

,rx 25,rx 24,rzz 23,y 22,rx 21,rzz 20,rx 19,rx 18,rzz 17,rx 16,...,rx 8,rzz 7,h 6,rx 5,rzz 4,h 3,rzz 2,h 1,h 0,pass/fail
0,0.162301,0.141048,0.333299,0.481286,0.126316,0.298656,0.242007,0.154991,0.272344,0.225422,...,0.266005,0.415192,0.320485,0.241923,0.484027,0.324480,0.446339,0.323574,0.298065,fail
1,0.118938,0.130071,0.286048,0.371036,0.103333,0.231480,0.185471,0.112202,0.250599,0.215623,...,0.210734,0.461229,0.294144,0.229162,0.460835,0.272737,0.419235,0.272327,0.277382,fail
2,0.119028,0.114370,0.270618,0.376295,0.107670,0.231075,0.180974,0.138102,0.248496,0.189364,...,0.221812,0.398239,0.271155,0.244059,0.360801,0.266283,0.330075,0.282193,0.280997,fail
3,0.146419,0.091802,0.265414,0.444783,0.145386,0.280500,0.212181,0.182105,0.273976,0.173067,...,0.309935,0.450839,0.271239,0.241440,0.473709,0.335970,0.514476,0.358628,0.305044,fail
4,0.093977,0.107742,0.244141,0.317680,0.112978,0.211038,0.151458,0.135776,0.248083,0.184580,...,0.237334,0.435365,0.265044,0.188834,0.412765,0.261488,0.426487,0.288722,0.240826,fail
5,0.156946,0.105256,0.295248,0.474013,0.137275,0.292275,0.227559,0.082415,0.186196,0.186929,...,0.178809,0.406224,0.264342,0.243051,0.458942,0.316165,0.413458,0.242516,0.288256,fail
6,0.124069,0.104259,0.249785,0.368667,0.141445,0.271815,0.185017,0.127853,0.231323,0.179870,...,0.234861,0.426308,0.263683,0.291020,0.450579,0.329856,0.428611,0.298089,0.337192,fail
7,0.149355,0.121499,0.288099,0.434769,0.097056,0.224136,0.206180,0.136064,0.236196,0.194878,...,0.234544,0.386863,0.278241,0.243936,0.456040,0.271850,0.410373,0.293443,0.290054,fail
8,0.145789,0.116566,0.311276,0.467554,0.109575,0.243394,0.216651,0.128577,0.249048,0.206357,...,0.226074,0.445634,0.294034,0.236335,0.442978,0.288174,0.385788,0.288332,0.284315,fail
9,0.132268,0.124223,0.296318,0.421128,0.088346,0.208637,0.196421,0.135656,0.264388,0.212229,...,0.236940,0.472239,0.300586,0.236068,0.400022,0.246624,0.439646,0.303363,0.281840,fail
10,0.140706,0.132333,0.300250,0.419640,0.116294,0.251328,0.202454,0.119758,0.243585,0.211882,...,0.219366,0.421451,0.294158,0.254728,0.460870,0.294843,0.395139,0.282129,0.298633,pass
11,0.123047,0.102149,0.238407,0.356535,0.092487,0.195267,0.169404,0.089812,0.181253,0.162289,...,0.166907,0.300072,0.224930,0.203261,0.352918,0.225626,0.333558,0.214655,0.237375,pass
12,0.093632,0.119835,0.222725,0.267610,0.113302,0.208922,0.136113,0.144986,0.265431,0.186286,...,0.245803,0.402261,0.258531,0.163448,0.318120,0.248921,0.368552,0.285999,0.211599,pass
13,0.111139,0.105167,0.236882,0.333148,0.114124,0.224059,0.162766,0.105299,0.220079,0.174284,...,0.197245,0.409524,0.246912,0.234310,0.392485,0.262757,0.398968,0.257514,0.275366,pass
14,0.087960,0.097434,0.235002,0.318759,0.121778,0.223381,0.157915,0.163229,0.283141,0.184884,...,0.274868,0.492067,0.275482,0.236433,0.471392,0.299241,0.413463,0.334740,0.292486,pass
15,0.132546,0.115636,0.277416,0.400102,0.143000,0.301717,0.200454,0.119734,0.254828,0.200367,...,0.227751,0.502382,0.284660,0.264185,0.533968,0.339822,0.494026,0.298334,0.321881,pass
16,0.089019,0.124077,0.244932,0.286300,0.062548,0.167859,0.147156,0.093511,0.206832,0.187732,...,0.173855,0.347156,0.251864,0.222075,0.368449,0.201395,0.392421,0.231550,0.256795,pass
17,0.094269,0.121394,0.257783,0.322405,0.083760,0.176917,0.154980,0.099174,0.204268,0.191700,...,0.185493,0.340967,0.261902,0.209058,0.375226,0.226480,0.378589,0.241515,0.250507,pass
18,0.099068,0.099998,0.230201,0.311854,0.080600,0.190234,0.156312,0.118915,0.234619,0.173639,...,0.210133,0.417710,0.247048,0.208110,0.350160,0.221680,0.362562,0.264575,0.245942,pass
19,0.125497,0.125067,0.287610,0.396192,0.123715,0.250770,0.192671,0.169484,0.291278,0.206319,...,0.280700,0.439009,0.297142,0.211265,0.446952,0.298317,0.445616,0.332829,0.269640,pass

[[1.20304264 1.21925658 1.173486   1.15771264 1.24327467 1.19797473
  1.20766789 1.36536605 1.11342878 1.14524936 1.14416992 1.30238104
  1.19166868 1.18415306 1.24325231 1.1821049  1.24817942 1.31492867
  1.09870898 1.13528456 1.21469508 1.09988553 1.15309912 1.22073188
  1.21520041 1.1691944 ]]
BARINEL SCORES

,rx 25,y 22,rx 19,h 10,rzz 20,rzz 23,h 3,rx 21,rx 12,rzz 11,...,rx 8,rzz 13,h 1,rzz 9,h 6,rzz 2,rzz 7,rx 16,rzz 17,rx 24
sum,0.551555,0.549187,0.54393,0.536145,0.5323,0.528767,0.526618,0.526513,0.525804,0.524482,...,0.519269,0.518752,0.518204,0.517938,0.516496,0.514126,0.513471,0.511557,0.507773,0.502988

custom SCORES

,rx 25,rx 19,y 22,rx 18,rx 14,h 10,rzz 20,rx 21,rx 8,rzz 11,...,rzz 13,h 0,rzz 15,rzz 2,h 6,rzz 4,rx 16,rx 24,rzz 7,rzz 17
sum,0.717442,0.708152,0.708137,0.699473,0.694714,0.69459,0.69172,0.690163,0.689969,0.687498,...,0.673297,0.672226,0.672079,0.671029,0.663089,0.662331,0.658022,0.656306,0.65451,0.649115

DSTAR SCORES

,rzz 11,rzz 4,rzz 15,rzz 7,y 22,rzz 2,h 10,h 1,h 3,h 0,...,rx 8,rzz 9,rx 12,rx 19,rx 16,rx 25,rx 18,rx 14,rx 21,rx 24
sum,1.402694,1.376362,1.336662,1.312759,1.288525,1.27026,0.695243,0.683429,0.672729,0.656963,...,0.456052,0.39951,0.379416,0.343802,0.326135,0.164014,0.158489,0.154914,0.123733,0.120099

ERROR GATE LOCATION:
22
Now evolving the following mutant:  AddGate_cswap_inGap_24_.qasm

100%|██████████| 10/10 [03:58<00:00, 23.85s/it]
100%|██████████| 10/10 [03:55<00:00, 23.59s/it]

,rx 25,rx 24,cswap 23,rzz 22,rx 21,rzz 20,rx 19,rx 18,rzz 17,rx 16,...,rx 8,rzz 7,h 6,rx 5,rzz 4,h 3,rzz 2,h 1,h 0,pass/fail
0,0.135052,0.113858,0.509275,0.231756,0.077432,0.241011,0.146773,0.109399,0.247040,0.187728,...,0.186020,0.341410,0.236288,0.196188,0.335212,0.234752,0.354449,0.233687,0.237695,fail
1,0.107840,0.144160,0.503771,0.219661,0.082326,0.232531,0.140091,0.085840,0.253316,0.193617,...,0.171868,0.348986,0.241605,0.166066,0.321562,0.229261,0.373383,0.220929,0.211534,fail
2,0.113097,0.120607,0.579532,0.232008,0.096215,0.270408,0.151333,0.126375,0.299308,0.210634,...,0.224207,0.401691,0.270621,0.206333,0.398049,0.270396,0.449453,0.280191,0.262783,fail
3,0.101445,0.132580,0.480683,0.202602,0.075842,0.208955,0.129666,0.087153,0.240353,0.180099,...,0.178684,0.332132,0.227482,0.199898,0.336969,0.223529,0.377440,0.229391,0.239721,fail
4,0.102173,0.077759,0.503510,0.192441,0.068389,0.203635,0.119383,0.085733,0.207587,0.152261,...,0.150957,0.306509,0.193701,0.171109,0.309315,0.193887,0.321010,0.195307,0.207485,fail
5,0.099997,0.081499,0.535464,0.212852,0.067627,0.228481,0.126712,0.102726,0.243342,0.159816,...,0.177846,0.308919,0.201386,0.182925,0.325083,0.205969,0.371865,0.222984,0.224137,fail
6,0.139141,0.139484,0.491320,0.199612,0.084729,0.207396,0.149441,0.138764,0.264704,0.188252,...,0.221241,0.365771,0.250266,0.202046,0.359628,0.242216,0.356303,0.267838,0.245106,fail
7,0.093113,0.113410,0.495583,0.217281,0.078599,0.237481,0.132840,0.113337,0.257230,0.184126,...,0.185545,0.330828,0.230772,0.170096,0.354438,0.232781,0.339757,0.231981,0.218469,fail
8,0.102411,0.120556,0.550117,0.235584,0.073744,0.245424,0.134929,0.085217,0.249070,0.186359,...,0.173864,0.345678,0.229417,0.228929,0.355047,0.232109,0.398474,0.231359,0.266807,fail
9,0.095615,0.128956,0.443651,0.194404,0.076669,0.216978,0.124501,0.098597,0.250687,0.179761,...,0.184357,0.318755,0.229266,0.197566,0.315805,0.227455,0.336296,0.233021,0.235105,fail
10,0.120144,0.180557,0.505137,0.251386,0.076094,0.241260,0.147265,0.077525,0.270926,0.208201,...,0.157782,0.334189,0.245526,0.204328,0.357160,0.240846,0.333082,0.214061,0.243030,pass
11,0.101219,0.075572,0.455931,0.185528,0.076633,0.207837,0.131211,0.101009,0.214485,0.160051,...,0.175736,0.316500,0.213326,0.192494,0.323912,0.221606,0.349405,0.221343,0.231043,pass
12,0.125688,0.108669,0.413231,0.181694,0.070192,0.192036,0.129602,0.070815,0.216548,0.158202,...,0.146289,0.289634,0.200165,0.155977,0.289073,0.198930,0.302676,0.188285,0.191697,pass
13,0.128841,0.102903,0.450800,0.221865,0.074021,0.226482,0.145688,0.108687,0.253014,0.174807,...,0.176928,0.307512,0.223043,0.193055,0.315586,0.227586,0.293740,0.223326,0.230427,pass
14,0.116423,0.092819,0.464089,0.198986,0.072339,0.215252,0.131614,0.095985,0.228526,0.163202,...,0.159174,0.303564,0.208199,0.172812,0.310024,0.212046,0.273761,0.203510,0.208811,pass
15,0.111961,0.113789,0.397988,0.179603,0.063994,0.185892,0.121452,0.078049,0.201223,0.153396,...,0.135418,0.266426,0.188476,0.130238,0.281283,0.187142,0.244833,0.172608,0.166336,pass
16,0.079222,0.125137,0.538583,0.228837,0.068194,0.232894,0.124217,0.114246,0.274332,0.181042,...,0.194191,0.340682,0.223327,0.183536,0.331585,0.212505,0.376724,0.243467,0.227169,pass
17,0.104026,0.139046,0.575309,0.246134,0.080565,0.259321,0.144688,0.124428,0.296326,0.200767,...,0.202872,0.359480,0.248084,0.202668,0.373801,0.246588,0.368823,0.255818,0.250080,pass
18,0.092331,0.119988,0.457060,0.207996,0.073108,0.229017,0.126508,0.099778,0.252778,0.178561,...,0.170814,0.315562,0.222075,0.175082,0.310023,0.220284,0.300709,0.217232,0.214460,pass
19,0.089512,0.086486,0.392760,0.181493,0.054440,0.194306,0.105467,0.071520,0.194965,0.140026,...,0.120888,0.236192,0.167419,0.127204,0.243184,0.170216,0.224049,0.155528,0.157200,pass

[[1.27666192 1.22912018 1.13791974 1.10178596 1.23103872 1.17963699
  1.11629994 1.3431258  1.19121129 1.15564607 1.16812759 1.35107352
  1.19159309 1.2069907  1.15532099 1.14425313 1.15416979 1.20893346
  1.18120787 1.17111224 1.19162027 1.1669201  1.17955431 1.2218605
  1.19398488 1.13590782]]
BARINEL SCORES

,rzz 2,rzz 9,rx 8,h 1,h 0,rzz 7,rx 5,rx 21,rx 18,cswap 23,...,h 10,rx 16,rzz 20,rzz 11,rzz 13,rzz 17,rx 19,rzz 22,rx 24,rx 25
sum,0.545257,0.537577,0.530689,0.528311,0.525574,0.525573,0.525114,0.52414,0.523061,0.522682,...,0.514863,0.514742,0.512063,0.51176,0.511157,0.511139,0.509003,0.506476,0.50602,0.504751

custom SCORES

,rzz 2,rx 18,rx 14,rzz 9,rx 8,h 1,rx 21,rx 5,rzz 7,h 0,...,rx 25,rx 16,rzz 13,rzz 17,rzz 20,h 10,rx 24,rzz 11,rx 19,rzz 22
sum,0.711814,0.698695,0.696496,0.69269,0.691081,0.68601,0.685449,0.681548,0.680776,0.674825,...,0.66585,0.663457,0.66343,0.663358,0.663076,0.662146,0.661509,0.659571,0.651053,0.645983

DSTAR SCORES

,cswap 23,rzz 2,rzz 4,rzz 7,rzz 15,rzz 11,rzz 13,rzz 17,h 1,h 0,...,rx 12,rx 5,rx 8,rx 16,rx 19,rx 24,rx 14,rx 25,rx 18,rx 21
sum,1.770383,1.035434,0.885809,0.884839,0.850939,0.825447,0.692587,0.509013,0.455301,0.455193,...,0.318188,0.314452,0.295487,0.283495,0.162529,0.12343,0.107794,0.10731,0.097549,0.057038

ERROR GATE LOCATION:
23
Now evolving the following mutant:  AddGate_p_inGap_20_.qasm

100%|██████████| 10/10 [01:34<00:00,  9.42s/it]
100%|██████████| 10/10 [01:33<00:00,  9.38s/it]

,rx 25,rx 24,rzz 23,rx 22,rzz 21,rx 20,p 19,rx 18,rzz 17,rx 16,...,rx 8,rzz 7,h 6,rx 5,rzz 4,h 3,rzz 2,h 1,h 0,pass/fail
0,0.101268,0.076750,0.202253,0.106318,0.215399,0.154595,0.256489,0.108017,0.173309,0.132346,...,0.189666,0.307135,0.200252,0.199143,0.366318,0.252914,0.367039,0.233475,0.239429,fail
1,0.141719,0.126866,0.300527,0.105436,0.229053,0.205886,0.335250,0.142866,0.258564,0.208676,...,0.241864,0.405180,0.296656,0.250812,0.464169,0.279131,0.403055,0.304625,0.299346,fail
2,0.119567,0.116296,0.295197,0.115915,0.239903,0.194103,0.320469,0.122478,0.235451,0.199588,...,0.226866,0.428096,0.285337,0.224385,0.400706,0.278157,0.444649,0.283634,0.274314,fail
3,0.157894,0.141862,0.322073,0.151640,0.302605,0.224040,0.370039,0.140954,0.278680,0.231593,...,0.258866,0.482043,0.322644,0.246776,0.492330,0.341243,0.485618,0.322534,0.305259,fail
4,0.113804,0.081271,0.218362,0.117251,0.232781,0.163836,0.273882,0.080334,0.159647,0.140061,...,0.151771,0.297673,0.198696,0.136527,0.333842,0.246380,0.313968,0.189798,0.179435,fail
5,0.082314,0.121619,0.232781,0.108817,0.209406,0.137644,0.232991,0.110618,0.242175,0.191910,...,0.214169,0.436670,0.265774,0.259859,0.416072,0.263024,0.477721,0.278715,0.303387,fail
6,0.126969,0.100679,0.253614,0.117746,0.229141,0.183923,0.302313,0.151317,0.261290,0.181026,...,0.272682,0.463361,0.269305,0.272713,0.479251,0.293844,0.518143,0.336006,0.328651,fail
7,0.132347,0.132076,0.289580,0.131383,0.268360,0.198513,0.328092,0.136971,0.251994,0.209115,...,0.245513,0.409594,0.292150,0.218147,0.469024,0.311447,0.452595,0.299316,0.274775,fail
8,0.091114,0.094161,0.224942,0.109966,0.225092,0.153868,0.261930,0.110237,0.215791,0.163865,...,0.203322,0.404075,0.235452,0.187118,0.407735,0.261495,0.393374,0.253095,0.235388,fail
9,0.092460,0.127430,0.247843,0.095762,0.198816,0.151114,0.250268,0.166878,0.298805,0.203953,...,0.274989,0.465903,0.288819,0.231441,0.397450,0.254688,0.443617,0.334843,0.281162,fail
10,0.104585,0.103709,0.266033,0.137792,0.245112,0.174667,0.292327,0.140779,0.245696,0.190282,...,0.252746,0.453947,0.282021,0.239454,0.386279,0.302232,0.440782,0.309265,0.288269,pass
11,0.057832,0.061102,0.139434,0.063162,0.112544,0.087585,0.142713,0.039268,0.089682,0.098245,...,0.083607,0.179186,0.134032,0.140819,0.274995,0.150560,0.221316,0.117620,0.165342,pass
12,0.129750,0.135257,0.294968,0.130474,0.242552,0.189840,0.317011,0.131258,0.251466,0.224958,...,0.247199,0.445243,0.315624,0.297246,0.437229,0.320679,0.418104,0.318523,0.341933,pass
13,0.103018,0.115600,0.249054,0.093709,0.183481,0.157638,0.262640,0.141093,0.245321,0.192895,...,0.236411,0.382702,0.274017,0.241549,0.356177,0.245372,0.353442,0.294538,0.279802,pass
14,0.105279,0.136955,0.277761,0.145907,0.251019,0.168495,0.284114,0.140170,0.262095,0.217335,...,0.257066,0.420550,0.303867,0.243143,0.465536,0.325533,0.478663,0.313452,0.300022,pass
15,0.097532,0.131474,0.260199,0.171114,0.279243,0.157973,0.265681,0.134437,0.240878,0.207336,...,0.242541,0.387609,0.291245,0.245327,0.456123,0.346248,0.408013,0.298465,0.300291,pass
16,0.116321,0.116810,0.265868,0.114184,0.249892,0.185842,0.299580,0.114286,0.248248,0.198015,...,0.221133,0.486119,0.277493,0.220544,0.432657,0.277375,0.459971,0.281394,0.270330,pass
17,0.103692,0.144545,0.280553,0.137539,0.279577,0.172662,0.295020,0.155555,0.283275,0.221758,...,0.262555,0.433828,0.310427,0.250210,0.520617,0.341625,0.413065,0.324518,0.306734,pass
18,0.109288,0.086233,0.226820,0.146674,0.269739,0.170087,0.277574,0.078308,0.165337,0.153736,...,0.162649,0.352927,0.219559,0.187820,0.460742,0.307414,0.367465,0.209903,0.237327,pass
19,0.121463,0.094459,0.231340,0.156246,0.271795,0.177118,0.290838,0.180006,0.289963,0.178884,...,0.302915,0.495368,0.274234,0.304434,0.444706,0.344312,0.442650,0.369912,0.357294,pass

[[1.36179073 1.26774803 1.24488432 1.30697434 1.28737595 1.26753929
  1.26218829 1.31330597 1.257754   1.2436992  1.24939522 1.27825419
  1.15661821 1.2606422  1.15819823 1.25936825 1.21673686 1.2062452
  1.17579093 1.21519145 1.22461963 1.16475465 1.22646656 1.20504596
  1.18477029 1.20776768]]
BARINEL SCORES

,rx 25,rx 20,p 19,rzz 2,h 10,rzz 23,rzz 11,rzz 17,rzz 7,rzz 15,...,h 6,rx 16,rzz 21,h 0,h 3,rx 5,rzz 13,rx 14,rx 12,rx 22
sum,0.525065,0.518422,0.518044,0.517843,0.509594,0.509366,0.505854,0.50572,0.503825,0.503606,...,0.49743,0.497155,0.496368,0.488669,0.484415,0.48438,0.480295,0.478209,0.478082,0.472209

custom SCORES

,rx 25,rx 20,p 19,rzz 2,h 10,rx 18,rzz 23,rzz 17,rzz 15,rx 24,...,h 6,h 1,rzz 4,h 0,h 3,rx 5,rx 14,rx 12,rx 22,rzz 13
sum,0.703822,0.682702,0.681511,0.673849,0.670035,0.668242,0.667891,0.664738,0.660906,0.656376,...,0.648548,0.647919,0.644972,0.636218,0.632945,0.632675,0.631027,0.628754,0.6265,0.619174

DSTAR SCORES

,rzz 2,rzz 4,rzz 11,rzz 7,rzz 15,p 19,h 1,h 3,h 0,h 10,...,rx 5,rzz 9,rx 12,rx 16,rx 20,rx 18,rx 14,rx 25,rx 22,rx 24
sum,1.320251,1.255118,1.243922,1.197351,1.160126,0.67531,0.626529,0.597262,0.576355,0.567924,...,0.400885,0.37974,0.344242,0.291796,0.268353,0.143455,0.124739,0.121673,0.119161,0.112544

ERROR GATE LOCATION:
19
Now evolving the following mutant:  AddGate_cx_inGap_16_.qasm

100%|██████████| 10/10 [02:20<00:00, 14.02s/it]
100%|██████████| 10/10 [02:22<00:00, 14.22s/it]

,rx 25,rx 24,rzz 23,rx 22,rzz 21,rx 20,rx 19,rzz 18,rx 17,rzz 16,...,rx 8,rzz 7,h 6,rx 5,rzz 4,h 3,rzz 2,h 1,h 0,pass/fail
0,0.137201,0.126038,0.309459,0.067731,0.186962,0.200497,0.097492,0.216709,0.205960,0.466669,...,0.174620,0.391429,0.293881,0.221647,0.387119,0.218054,0.382266,0.236858,0.255619,fail
1,0.133642,0.112157,0.281873,0.080113,0.216863,0.201297,0.113908,0.209628,0.187542,0.433498,...,0.187594,0.338101,0.268124,0.224378,0.389926,0.228525,0.357037,0.245809,0.260952,fail
2,0.113290,0.094678,0.245259,0.093523,0.212511,0.178116,0.159339,0.258189,0.169300,0.424446,...,0.231264,0.366724,0.265669,0.234146,0.413048,0.243212,0.373399,0.283664,0.276199,fail
3,0.136088,0.082807,0.233480,0.106897,0.239672,0.191548,0.136907,0.246255,0.157562,0.369275,...,0.211380,0.373124,0.232921,0.218053,0.397545,0.244176,0.388956,0.256620,0.261862,fail
4,0.117632,0.142324,0.295615,0.116998,0.229726,0.175041,0.103162,0.231558,0.220417,0.422225,...,0.183358,0.374486,0.298555,0.214976,0.376588,0.246631,0.374298,0.244319,0.252866,fail
5,0.152822,0.132879,0.303686,0.143325,0.264890,0.207446,0.113448,0.229528,0.217399,0.374443,...,0.193628,0.371086,0.278562,0.204921,0.417526,0.295372,0.303807,0.250938,0.247629,fail
6,0.134127,0.118409,0.270360,0.136150,0.280833,0.191384,0.124076,0.240273,0.191564,0.380654,...,0.189872,0.351338,0.258723,0.214199,0.431051,0.277580,0.327885,0.242591,0.257005,fail
7,0.106287,0.107034,0.253038,0.135737,0.232715,0.165912,0.168461,0.299534,0.195355,0.452867,...,0.244526,0.443321,0.300863,0.192922,0.427218,0.273776,0.410696,0.292173,0.245793,fail
8,0.086769,0.107923,0.240365,0.119427,0.209084,0.143118,0.098770,0.202620,0.178023,0.418041,...,0.164833,0.348071,0.277003,0.211709,0.360755,0.242039,0.347662,0.220555,0.245881,fail
9,0.139769,0.106800,0.289157,0.162480,0.303841,0.212853,0.173164,0.282289,0.199967,0.503044,...,0.260565,0.424202,0.317034,0.264767,0.423622,0.321775,0.437914,0.319609,0.314221,fail
10,0.104776,0.128322,0.257167,0.104502,0.218135,0.163631,0.099644,0.220942,0.202112,0.368539,...,0.172588,0.366186,0.265907,0.233525,0.374309,0.246889,0.357602,0.235607,0.268326,pass
11,0.092845,0.078637,0.204670,0.144404,0.252890,0.154330,0.100966,0.181368,0.149322,0.372043,...,0.166304,0.326924,0.230905,0.179304,0.420686,0.274258,0.302359,0.210977,0.223602,pass
12,0.108837,0.147032,0.297237,0.099079,0.192286,0.165426,0.147269,0.288556,0.233443,0.465047,...,0.224914,0.422406,0.327103,0.240911,0.396610,0.247250,0.387268,0.288030,0.279967,pass
13,0.094581,0.085907,0.190061,0.123393,0.229450,0.143366,0.136977,0.222723,0.148089,0.287652,...,0.208183,0.304050,0.204823,0.184176,0.361291,0.241121,0.337195,0.248349,0.228622,pass
14,0.046725,0.064274,0.134064,0.064379,0.120645,0.081854,0.068270,0.138099,0.107429,0.244672,...,0.106669,0.220812,0.160378,0.134681,0.200855,0.140557,0.220491,0.139464,0.155185,pass
15,0.106223,0.079537,0.217117,0.130396,0.217462,0.154380,0.086311,0.175494,0.150198,0.374404,...,0.151896,0.324981,0.238849,0.205012,0.394626,0.251662,0.355270,0.202710,0.243876,pass
16,0.060922,0.081856,0.177087,0.104041,0.168969,0.105000,0.122157,0.217568,0.145536,0.348270,...,0.180815,0.318647,0.233956,0.181583,0.284417,0.203153,0.327770,0.221916,0.214731,pass
17,0.083824,0.112551,0.233443,0.105389,0.215270,0.150307,0.125418,0.233414,0.184013,0.401946,...,0.190473,0.355217,0.260513,0.207516,0.335309,0.236894,0.338675,0.243307,0.244025,pass
18,0.063535,0.073380,0.172162,0.124104,0.201920,0.115961,0.093175,0.180049,0.140174,0.335291,...,0.156254,0.321992,0.214727,0.162970,0.335495,0.239673,0.317302,0.193249,0.201738,pass
19,0.065003,0.090629,0.183929,0.075264,0.142079,0.107120,0.072644,0.156910,0.145323,0.290132,...,0.124037,0.252066,0.200888,0.124453,0.237681,0.162361,0.265404,0.162097,0.152951,pass

[[1.21516124 1.2583378  1.13675821 1.39782246 1.27820075 1.13994834
  1.34368336 1.23949263 1.14616272 1.18498293 1.13233685 1.26893106
  1.15821334 1.25165487 1.14933297 1.16836028 1.31103867 1.27625394
  1.17222248 1.13578027 1.20254713 1.07109343 1.24182729 1.18229926
  1.23251817 1.20022068]]
BARINEL SCORES

,rx 25,rx 20,rzz 23,h 10,rzz 11,cx 15,rx 19,rzz 16,rx 8,rzz 21,...,rx 14,rx 5,h 0,rzz 7,rzz 9,h 3,rzz 2,rzz 13,rx 12,rx 22
sum,0.603208,0.581942,0.56842,0.559543,0.556094,0.55199,0.550372,0.548956,0.548272,0.548198,...,0.543101,0.54285,0.541917,0.540642,0.537258,0.535918,0.535771,0.5347,0.524312,0.519539

custom SCORES

,rx 25,rx 20,rx 19,rzz 23,rzz 21,rx 8,h 10,rx 24,rzz 11,h 1,...,h 0,h 3,rx 17,rx 22,rzz 7,h 6,rzz 2,rzz 4,rzz 13,rx 12
sum,0.786457,0.747788,0.735253,0.729959,0.723375,0.723206,0.72298,0.717189,0.715878,0.71582,...,0.704522,0.702297,0.70114,0.701095,0.699081,0.698704,0.694131,0.692676,0.689524,0.688376

DSTAR SCORES

,cx 15,rzz 16,rzz 11,rzz 4,rzz 7,rzz 2,h 10,h 6,rzz 23,h 0,...,rx 8,rzz 9,rx 17,rx 20,rx 12,rx 19,rx 25,rx 14,rx 22,rx 24
sum,1.473283,1.336107,1.252578,1.21396,1.082444,1.038586,0.734325,0.631506,0.614148,0.561209,...,0.356809,0.336546,0.318662,0.307413,0.288208,0.150262,0.146078,0.136704,0.121999,0.116912

ERROR GATE LOCATION:
15
Now evolving the following mutant:  AddGate_ry_inGap_15_.qasm

100%|██████████| 10/10 [02:02<00:00, 12.24s/it]
100%|██████████| 10/10 [01:52<00:00, 11.24s/it]

,rx 25,rx 24,rzz 23,rx 22,rzz 21,rx 20,rx 19,rzz 18,rx 17,rzz 16,...,rx 8,rzz 7,h 6,rx 5,rzz 4,h 3,rzz 2,h 1,h 0,pass/fail
0,0.066130,0.076296,0.177566,0.111139,0.201168,0.122993,0.129722,0.221749,0.143596,0.368899,...,0.207774,0.443908,0.233634,0.269924,0.404250,0.301337,0.392662,0.270191,0.250413,fail
1,0.156122,0.084681,0.274505,0.110384,0.265325,0.227561,0.135524,0.220634,0.163632,0.439594,...,0.224297,0.399905,0.271483,0.307924,0.455715,0.371913,0.405441,0.291552,0.290159,fail
2,0.119107,0.114521,0.268523,0.152706,0.275797,0.182583,0.164645,0.284925,0.203860,0.443171,...,0.282901,0.429805,0.311157,0.276055,0.474047,0.335474,0.482664,0.348263,0.279936,fail
3,0.127916,0.120586,0.269626,0.111193,0.226509,0.185623,0.113296,0.225123,0.199204,0.386899,...,0.224805,0.457865,0.300153,0.308818,0.410357,0.332206,0.394503,0.299064,0.285013,fail
4,0.076629,0.083741,0.195946,0.087245,0.186678,0.135352,0.093758,0.167596,0.140980,0.349393,...,0.188684,0.332219,0.219478,0.214481,0.331961,0.259951,0.298462,0.238881,0.202956,fail
5,0.106317,0.099843,0.241947,0.074801,0.182667,0.161104,0.102515,0.212587,0.173812,0.382811,...,0.160161,0.328841,0.261193,0.264212,0.298935,0.247136,0.305544,0.221493,0.230353,fail
6,0.099431,0.113809,0.244092,0.129515,0.215258,0.152346,0.140251,0.241617,0.189799,0.378359,...,0.220719,0.371008,0.285983,0.277750,0.367824,0.265518,0.390083,0.281029,0.259097,fail
7,0.133528,0.121454,0.273990,0.164182,0.299055,0.198449,0.136323,0.246749,0.200145,0.404336,...,0.264640,0.488985,0.310765,0.328227,0.515535,0.397171,0.434317,0.336550,0.314607,fail
8,0.103877,0.112540,0.258622,0.103891,0.221678,0.168469,0.113243,0.235947,0.196108,0.439762,...,0.263227,0.526982,0.302183,0.290793,0.401704,0.313165,0.407065,0.337313,0.270553,fail
9,0.108275,0.119767,0.261785,0.104135,0.220486,0.166720,0.100809,0.231622,0.200349,0.406157,...,0.188133,0.448669,0.291065,0.252302,0.432383,0.358754,0.357498,0.257101,0.245319,fail
10,0.084037,0.099931,0.212724,0.095696,0.189332,0.133814,0.082669,0.189582,0.164290,0.340089,...,0.191618,0.376346,0.236728,0.173701,0.304876,0.220174,0.300221,0.238746,0.172980,pass
11,0.108768,0.100639,0.234019,0.103185,0.190015,0.153109,0.096210,0.196761,0.171511,0.340598,...,0.209811,0.361185,0.257405,0.219115,0.352379,0.296278,0.333026,0.264766,0.218115,pass
12,0.106849,0.079545,0.213270,0.096770,0.201997,0.165013,0.117858,0.224603,0.154795,0.370637,...,0.200810,0.392200,0.239190,0.239784,0.326453,0.238885,0.361163,0.260312,0.222920,pass
13,0.103776,0.104951,0.241107,0.090290,0.204101,0.165697,0.152763,0.265622,0.182399,0.406300,...,0.250899,0.456674,0.280625,0.231556,0.385619,0.303773,0.446364,0.310425,0.236958,pass
14,0.113344,0.125888,0.264097,0.090508,0.190074,0.167429,0.130765,0.244413,0.197457,0.366302,...,0.194687,0.337375,0.284251,0.208477,0.331014,0.256016,0.352168,0.240411,0.212143,pass
15,0.101775,0.109018,0.248624,0.122820,0.210955,0.155849,0.115665,0.221458,0.184864,0.394816,...,0.211194,0.384427,0.269946,0.197724,0.366867,0.278140,0.350157,0.262193,0.208235,pass
16,0.083183,0.044331,0.140840,0.061492,0.140605,0.113238,0.067736,0.120266,0.084363,0.201983,...,0.115462,0.232261,0.129152,0.103378,0.191090,0.125741,0.201641,0.146170,0.105572,pass
17,0.125498,0.122115,0.281030,0.144413,0.247617,0.183126,0.129016,0.253318,0.210461,0.440144,...,0.233165,0.471068,0.314400,0.316678,0.395557,0.306929,0.394215,0.309316,0.286966,pass
18,0.080659,0.090636,0.213992,0.080266,0.170125,0.139122,0.082558,0.174840,0.154326,0.382163,...,0.177160,0.389514,0.232250,0.205752,0.318456,0.230560,0.306478,0.235188,0.195301,pass
19,0.060051,0.106788,0.212516,0.111634,0.204679,0.128673,0.120197,0.248301,0.188186,0.426853,...,0.226068,0.432182,0.279182,0.227601,0.403621,0.283719,0.413858,0.288633,0.228960,pass

[[1.42273787 1.15975862 1.11288543 1.42867426 1.30328544 1.33765223
  1.33848573 1.24500269 1.1253765  1.10809846 1.15315169 1.17629475
  1.21841279 1.282282   1.18998607 1.24498769 1.16789205 1.2712681
  1.24635435 1.11641968 1.17623535 1.25964242 1.24793613 1.24776254
  1.20864519 1.19695016]]
BARINEL SCORES

,ry 14,rx 15,rzz 13,rx 5,rzz 9,h 0,rzz 11,h 3,rx 12,rzz 4,...,rx 19,rzz 2,rx 8,h 6,rzz 7,rzz 23,rzz 16,rx 17,rzz 18,rx 24
sum,0.583458,0.581433,0.578171,0.567835,0.564271,0.557272,0.556372,0.556127,0.5543,0.547986,...,0.52895,0.527905,0.525314,0.524854,0.524497,0.521611,0.521482,0.516956,0.51687,0.515607

custom SCORES

,ry 14,rzz 13,rx 15,rx 5,rx 12,h 3,rzz 9,rx 22,h 0,rzz 11,...,rzz 2,rx 8,h 1,rzz 7,rzz 18,h 6,rzz 23,rzz 16,rx 24,rx 17
sum,0.755037,0.754284,0.749052,0.734812,0.731993,0.729629,0.729024,0.726679,0.724029,0.721891,...,0.69258,0.692267,0.690028,0.687924,0.677746,0.671344,0.666734,0.665945,0.665102,0.662399

DSTAR SCORES

,rzz 9,rzz 13,rzz 11,rzz 7,rzz 4,rzz 16,rzz 2,h 3,h 1,rx 5,...,rzz 18,rx 8,rx 17,rx 20,rx 15,rx 19,rx 22,ry 14,rx 25,rx 24
sum,2.303694,1.780223,1.577784,1.292364,1.252269,1.170094,1.111743,0.807729,0.661243,0.642277,...,0.431452,0.412305,0.280645,0.251548,0.192851,0.136372,0.12009,0.119318,0.109787,0.099847

ERROR GATE LOCATION:
14
Now evolving the following mutant:  AddGate_y_inGap_9_.qasm

100%|██████████| 10/10 [01:46<00:00, 10.62s/it]
100%|██████████| 10/10 [01:44<00:00, 10.45s/it]

,rx 25,rx 24,rzz 23,rx 22,rzz 21,rx 20,rx 19,rzz 18,rx 17,rzz 16,...,y 8,rzz 7,h 6,rx 5,rzz 4,h 3,rzz 2,h 1,h 0,pass/fail
0,0.132379,0.120798,0.296084,0.149990,0.276616,0.207612,0.154322,0.295212,0.222127,0.503223,...,0.181760,0.547844,0.320662,0.278288,0.517771,0.346887,0.521054,0.355680,0.339840,fail
1,0.081151,0.097706,0.224795,0.104589,0.192344,0.138658,0.091603,0.208612,0.173155,0.411793,...,0.115698,0.418185,0.242463,0.198074,0.351736,0.233764,0.377574,0.235408,0.238655,fail
2,0.113305,0.126784,0.282744,0.081806,0.188027,0.178268,0.165407,0.281834,0.208427,0.461267,...,0.182179,0.439177,0.299978,0.261894,0.456047,0.251333,0.458238,0.337311,0.311410,fail
3,0.088116,0.146268,0.280844,0.086015,0.183812,0.148161,0.114845,0.265338,0.228415,0.447315,...,0.136375,0.444710,0.307015,0.236315,0.431566,0.242183,0.380636,0.271791,0.277786,fail
4,0.133458,0.088943,0.252988,0.129007,0.247241,0.194564,0.120228,0.225618,0.170027,0.424093,...,0.142994,0.445489,0.251477,0.270400,0.445468,0.296121,0.447101,0.291858,0.317599,fail
5,0.112685,0.128037,0.275862,0.107261,0.221365,0.178105,0.156080,0.277199,0.212126,0.430898,...,0.176175,0.471880,0.304273,0.309020,0.504604,0.301406,0.474620,0.345334,0.357853,fail
6,0.114613,0.108955,0.254418,0.077415,0.187269,0.170093,0.156502,0.253894,0.178474,0.373487,...,0.169662,0.380180,0.260218,0.207962,0.399256,0.234390,0.386106,0.306366,0.255113,fail
7,0.110125,0.140379,0.278261,0.110933,0.214635,0.167180,0.147345,0.288235,0.224120,0.418911,...,0.168616,0.476379,0.311364,0.261223,0.430063,0.279541,0.440520,0.326426,0.307478,fail
8,0.128007,0.064156,0.207846,0.093746,0.197921,0.176183,0.151832,0.236197,0.134561,0.336876,...,0.170295,0.416470,0.216279,0.234542,0.350839,0.240870,0.418710,0.310852,0.277901,fail
9,0.140525,0.117668,0.279962,0.105589,0.246676,0.202133,0.155534,0.273356,0.195616,0.408349,...,0.180328,0.462826,0.286132,0.277623,0.521276,0.302523,0.518744,0.339426,0.334733,fail
10,0.129516,0.112033,0.261768,0.100030,0.225886,0.188233,0.113474,0.212748,0.184061,0.369228,...,0.128642,0.368943,0.259777,0.243339,0.374718,0.260468,0.398097,0.265555,0.282086,pass
11,0.063556,0.103495,0.189534,0.092225,0.168019,0.107516,0.064465,0.153387,0.157695,0.283783,...,0.078271,0.274322,0.208429,0.168872,0.310352,0.209456,0.286148,0.176712,0.201318,pass
12,0.090270,0.064731,0.174433,0.067518,0.149634,0.133215,0.072404,0.128219,0.110290,0.277812,...,0.081765,0.215682,0.160775,0.171825,0.311951,0.184608,0.265405,0.168629,0.201123,pass
13,0.110908,0.092860,0.234187,0.071706,0.186009,0.169682,0.100614,0.194663,0.159643,0.377834,...,0.117982,0.352795,0.227967,0.198004,0.359392,0.208266,0.363558,0.233772,0.235998,pass
14,0.131142,0.153022,0.313670,0.133608,0.248979,0.190228,0.139926,0.289352,0.247034,0.450682,...,0.161115,0.501155,0.339034,0.246902,0.417325,0.304710,0.447692,0.322615,0.297442,pass
15,0.078825,0.079271,0.177158,0.133901,0.218192,0.124954,0.091070,0.173725,0.140476,0.284634,...,0.109102,0.340862,0.201838,0.174625,0.300781,0.259650,0.337083,0.223725,0.216113,pass
16,0.092445,0.095325,0.203405,0.100966,0.195130,0.140031,0.108175,0.196572,0.152634,0.301215,...,0.126537,0.335633,0.217506,0.199986,0.364903,0.240455,0.397948,0.247995,0.244110,pass
17,0.113733,0.103836,0.253512,0.085613,0.219700,0.181691,0.139871,0.237738,0.175015,0.406632,...,0.159516,0.402612,0.259038,0.227995,0.399348,0.252682,0.437064,0.298596,0.274066,pass
18,0.096646,0.097158,0.224021,0.133451,0.239098,0.154240,0.120162,0.228738,0.174003,0.386762,...,0.140679,0.431901,0.249847,0.249703,0.473034,0.298187,0.426556,0.277245,0.300547,pass
19,0.119945,0.093551,0.234124,0.090831,0.207237,0.175051,0.132224,0.222220,0.160252,0.367314,...,0.147656,0.370534,0.238321,0.283885,0.414076,0.262602,0.395857,0.288920,0.322856,pass

[[1.21733906 1.28339698 1.12416856 1.43345663 1.28306172 1.17897482
  1.17002872 1.1330376  1.17313203 1.19354317 1.26910962 1.21542442
  1.33723676 1.19178666 1.18569276 1.13853927 1.13316702 1.12173675
  1.21658241 1.14527707 1.21885185 1.18240076 1.27110646 1.17797544
  1.13983577 1.18558402]]
BARINEL SCORES

,rx 19,y 8,rzz 18,rx 9,rzz 7,h 1,rzz 10,rzz 16,h 6,rzz 4,...,rzz 14,rx 24,h 11,rx 20,rx 25,h 3,rzz 12,rx 13,rzz 21,rx 22
sum,0.566366,0.56483,0.561184,0.556945,0.556109,0.554824,0.546061,0.545992,0.542357,0.541966,...,0.536171,0.533821,0.529924,0.529484,0.529197,0.523794,0.523649,0.518644,0.511631,0.508876

custom SCORES

,rx 19,rzz 7,y 8,rzz 18,rx 9,h 1,rx 15,rzz 16,rx 24,rx 5,...,h 6,rx 13,rx 22,rx 25,h 3,rzz 23,h 11,rx 20,rzz 12,rzz 21
sum,0.732032,0.725248,0.723228,0.720144,0.714723,0.712927,0.711735,0.708909,0.705097,0.703736,...,0.697645,0.692032,0.69124,0.69025,0.690243,0.688628,0.687006,0.685546,0.679669,0.675745

DSTAR SCORES

,rzz 7,rzz 2,rzz 4,rzz 16,rzz 12,h 1,h 0,h 6,h 3,h 11,...,rzz 21,rx 17,rx 13,rx 20,y 8,rx 19,rx 15,rx 25,rx 24,rx 22
sum,1.49166,1.422395,1.416011,1.316199,1.196126,0.778744,0.724458,0.634112,0.596706,0.575699,...,0.385468,0.325098,0.323047,0.268138,0.234431,0.180335,0.175907,0.120845,0.118133,0.099443

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_y_inGap_10_.qasm

100%|██████████| 10/10 [01:44<00:00, 10.40s/it]
100%|██████████| 10/10 [01:40<00:00, 10.01s/it]

,rx 25,rx 24,rzz 23,rx 22,rzz 21,rx 20,rx 19,rzz 18,rx 17,rzz 16,...,rx 8,rzz 7,h 6,rx 5,rzz 4,h 3,rzz 2,h 1,h 0,pass/fail
0,0.087416,0.102319,0.233247,0.115447,0.206546,0.148694,0.115240,0.215233,0.176983,0.422495,...,0.213081,0.402915,0.255492,0.251538,0.420749,0.271346,0.426969,0.275065,0.296353,fail
1,0.078498,0.148550,0.257931,0.138589,0.237833,0.142209,0.171322,0.314193,0.233239,0.410766,...,0.295906,0.485442,0.323906,0.242503,0.506514,0.319454,0.504555,0.359816,0.307509,fail
2,0.125455,0.119456,0.280650,0.130785,0.242799,0.189504,0.151900,0.262036,0.206746,0.444786,...,0.268431,0.455902,0.301247,0.300777,0.472286,0.316910,0.467487,0.337193,0.350025,fail
3,0.106061,0.106621,0.264012,0.146944,0.256790,0.175317,0.130190,0.227158,0.188761,0.474871,...,0.234006,0.399296,0.276829,0.248664,0.451415,0.322106,0.414856,0.292900,0.299574,fail
4,0.110505,0.092013,0.239021,0.090602,0.207473,0.170869,0.111010,0.195326,0.157014,0.379684,...,0.181944,0.331804,0.227610,0.184063,0.376353,0.235805,0.295988,0.231511,0.222456,fail
5,0.082745,0.120366,0.231872,0.119507,0.201046,0.137787,0.151895,0.261400,0.193895,0.383864,...,0.257724,0.405651,0.278151,0.272178,0.418146,0.278681,0.427603,0.320498,0.319147,fail
6,0.135978,0.154770,0.322635,0.141639,0.279347,0.207822,0.148084,0.288405,0.246506,0.482993,...,0.273515,0.483849,0.342880,0.313972,0.532892,0.351350,0.512052,0.348316,0.368643,fail
7,0.086731,0.093949,0.222672,0.144859,0.236696,0.145485,0.148812,0.249687,0.173459,0.423905,...,0.270809,0.452534,0.261001,0.260430,0.506000,0.318012,0.534377,0.333400,0.322250,fail
8,0.096862,0.128609,0.270376,0.134647,0.260544,0.169601,0.166016,0.307018,0.223069,0.494577,...,0.284956,0.540327,0.318531,0.273274,0.520799,0.324964,0.493918,0.358250,0.334276,fail
9,0.124524,0.112058,0.271677,0.099091,0.218710,0.186709,0.146857,0.256616,0.195346,0.411996,...,0.259266,0.464715,0.285274,0.276303,0.454522,0.281697,0.440231,0.327710,0.322493,fail
10,0.130675,0.113966,0.292273,0.122551,0.238051,0.196135,0.146602,0.268448,0.206025,0.484359,...,0.260257,0.476250,0.299737,0.259627,0.445910,0.296832,0.441569,0.327822,0.311270,pass
11,0.093795,0.084183,0.213360,0.092799,0.177188,0.139756,0.089387,0.181418,0.142620,0.368326,...,0.151759,0.321212,0.203237,0.173316,0.358915,0.209323,0.304258,0.199652,0.208769,pass
12,0.113220,0.090308,0.232861,0.142198,0.260763,0.173658,0.113119,0.205644,0.159172,0.391229,...,0.203375,0.382730,0.234382,0.214832,0.458491,0.310675,0.394136,0.254182,0.266914,pass
13,0.094973,0.140516,0.255175,0.151854,0.271365,0.156651,0.125223,0.256211,0.222841,0.365405,...,0.243519,0.467634,0.308009,0.303026,0.454140,0.349716,0.449168,0.314885,0.349353,pass
14,0.140358,0.146997,0.299831,0.129899,0.262922,0.198581,0.130601,0.249438,0.223784,0.379193,...,0.247006,0.414856,0.309090,0.265484,0.440821,0.315833,0.448432,0.307797,0.313130,pass
15,0.115460,0.130305,0.275779,0.108489,0.209484,0.172555,0.157106,0.280575,0.215733,0.409523,...,0.268597,0.440760,0.303160,0.237658,0.461039,0.281014,0.420831,0.326188,0.289693,pass
16,0.078140,0.052896,0.146349,0.096357,0.182073,0.117388,0.081169,0.142544,0.099323,0.258314,...,0.146952,0.285134,0.152166,0.191516,0.336421,0.216921,0.317554,0.191340,0.224671,pass
17,0.070459,0.091303,0.183251,0.120304,0.185831,0.107838,0.076452,0.157759,0.143079,0.277245,...,0.149963,0.266356,0.194917,0.164212,0.335261,0.239770,0.311576,0.187290,0.202077,pass
18,0.109911,0.095348,0.222849,0.106215,0.208736,0.158625,0.096317,0.171408,0.152839,0.305862,...,0.177195,0.298122,0.217430,0.212188,0.347951,0.249919,0.342654,0.225654,0.246556,pass
19,0.124041,0.146249,0.301308,0.144185,0.276407,0.192419,0.131546,0.264622,0.228739,0.454113,...,0.241386,0.441347,0.316920,0.275317,0.507368,0.340526,0.460163,0.308035,0.328486,pass

[[1.31407829 1.31304248 1.24373088 1.16427577 1.18983186 1.24146982
  1.18864388 1.21918559 1.23560935 1.14222553 1.18893567 1.16081451
  1.15776987 1.19101796 1.22829593 1.10537229 1.16509093 1.16515223
  1.2217864  1.19432136 1.19667429 1.14362459 1.16328446 1.18276308
  1.1298423  1.17300602]]
BARINEL SCORES

,rx 19,y 9,rx 8,h 1,rzz 10,rzz 18,rzz 16,rzz 7,rzz 2,rx 15,...,rzz 14,rx 24,h 3,rzz 23,rx 13,h 11,rx 22,rx 20,rzz 21,rx 25
sum,0.556744,0.553252,0.548559,0.546488,0.544866,0.541956,0.539656,0.538216,0.537326,0.534707,...,0.522851,0.519077,0.51799,0.517047,0.513485,0.512778,0.50954,0.509185,0.508112,0.491391

custom SCORES

,rx 19,y 9,rx 8,rzz 18,rzz 7,h 1,rzz 2,rzz 10,rzz 16,rx 15,...,rzz 4,rzz 23,rzz 14,h 11,h 3,rx 20,rx 13,rzz 21,rx 22,rx 25
sum,0.722187,0.714399,0.708348,0.707142,0.702613,0.700849,0.696208,0.695436,0.693759,0.69364,...,0.680435,0.677814,0.674585,0.670239,0.668633,0.667219,0.662109,0.659254,0.657851,0.652823

DSTAR SCORES

,rzz 4,rzz 2,rzz 7,rzz 16,rzz 12,y 9,h 1,h 0,h 3,h 6,...,rzz 10,rzz 21,rx 13,rx 17,rx 20,rx 19,rx 15,rx 22,rx 24,rx 25
sum,1.534857,1.469557,1.417817,1.369136,1.340816,1.110874,0.802198,0.775197,0.712098,0.657322,...,0.487184,0.449129,0.413107,0.337464,0.241292,0.186357,0.186224,0.142037,0.125257,0.096717

ERROR GATE LOCATION:
9
Now evolving the following mutant:  AddGate_ccx_inGap_17_.qasm

100%|██████████| 10/10 [03:54<00:00, 23.46s/it]
100%|██████████| 10/10 [03:50<00:00, 23.07s/it]

,rx 25,rx 24,rzz 23,rx 22,rzz 21,rx 20,rx 19,rzz 18,rx 17,ccx 16,...,rx 8,rzz 7,h 6,rx 5,rzz 4,h 3,rzz 2,h 1,h 0,pass/fail
0,0.143537,0.128911,0.304181,0.148781,0.286482,0.208613,0.100241,0.214790,0.210360,0.544991,...,0.156349,0.372561,0.243889,0.191963,0.370346,0.243657,0.359932,0.204488,0.230673,fail
1,0.113563,0.153742,0.302908,0.114113,0.234110,0.177953,0.088748,0.252685,0.245668,0.536110,...,0.150722,0.387808,0.256867,0.183340,0.354249,0.226370,0.342620,0.204599,0.216297,fail
2,0.083724,0.144965,0.289871,0.150718,0.266345,0.167498,0.183662,0.343392,0.249467,0.679920,...,0.250072,0.435833,0.292638,0.178122,0.426380,0.269566,0.400632,0.302378,0.232689,fail
3,0.135436,0.132484,0.306877,0.097864,0.250705,0.212539,0.133324,0.268718,0.222809,0.555249,...,0.184875,0.380301,0.257435,0.207775,0.367770,0.243105,0.323776,0.237139,0.242653,fail
4,0.119453,0.129258,0.285169,0.136497,0.255387,0.186746,0.091472,0.226193,0.218323,0.588826,...,0.151507,0.389882,0.254357,0.246839,0.399509,0.253669,0.346287,0.214752,0.279653,fail
5,0.121099,0.125579,0.278382,0.144820,0.273174,0.187111,0.154460,0.259429,0.202330,0.548272,...,0.203225,0.350591,0.246916,0.198234,0.372086,0.250887,0.334175,0.250177,0.238922,fail
6,0.134209,0.162081,0.324347,0.125465,0.263111,0.199621,0.148795,0.301605,0.252138,0.551190,...,0.205992,0.385897,0.270618,0.177877,0.358136,0.238304,0.357267,0.256011,0.219756,fail
7,0.119854,0.158419,0.325760,0.106299,0.242732,0.196908,0.123227,0.284306,0.255611,0.551692,...,0.186161,0.399526,0.270688,0.158062,0.353412,0.228302,0.367041,0.233372,0.196858,fail
8,0.122302,0.121855,0.290752,0.138260,0.265616,0.192163,0.127177,0.247307,0.207573,0.476395,...,0.168496,0.339612,0.233463,0.131008,0.309858,0.216665,0.265657,0.204709,0.168125,fail
9,0.125162,0.109784,0.296630,0.103713,0.239287,0.206802,0.129909,0.239249,0.195429,0.620331,...,0.182447,0.388712,0.251682,0.187247,0.376636,0.236520,0.377619,0.228657,0.226347,fail
10,0.112511,0.095956,0.234944,0.096772,0.185665,0.163083,0.085858,0.175640,0.164876,0.423681,...,0.143884,0.268571,0.192486,0.173503,0.280009,0.181462,0.346407,0.182209,0.203843,pass
11,0.086962,0.048439,0.170600,0.111046,0.195805,0.137846,0.115200,0.189129,0.116117,0.485282,...,0.162066,0.302274,0.178288,0.177576,0.283833,0.186760,0.285626,0.210305,0.209270,pass
12,0.114679,0.106677,0.245998,0.136452,0.264430,0.179096,0.146836,0.244086,0.178581,0.547816,...,0.196438,0.335801,0.229329,0.210239,0.375436,0.248096,0.333411,0.244211,0.250259,pass
13,0.089803,0.120509,0.237246,0.125111,0.233650,0.153417,0.134585,0.238025,0.192423,0.487208,...,0.192815,0.322096,0.227446,0.199843,0.324749,0.224534,0.377222,0.239952,0.236344,pass
14,0.082206,0.104307,0.211298,0.080126,0.167156,0.128652,0.100305,0.188447,0.158730,0.411428,...,0.139805,0.254110,0.183288,0.140471,0.266421,0.169938,0.277257,0.173168,0.170955,pass
15,0.134077,0.149844,0.324996,0.101396,0.228714,0.205305,0.198342,0.337213,0.245701,0.590182,...,0.257378,0.380522,0.281568,0.215992,0.388981,0.247345,0.406949,0.304999,0.260981,pass
16,0.115739,0.091360,0.244321,0.086863,0.196873,0.175618,0.126509,0.220646,0.162908,0.473429,...,0.169555,0.303856,0.204356,0.149948,0.279126,0.188894,0.292539,0.207674,0.181733,pass
17,0.091391,0.118076,0.239754,0.106730,0.202172,0.145366,0.118541,0.238638,0.189787,0.483237,...,0.170120,0.318646,0.215244,0.141117,0.296987,0.196153,0.326152,0.211250,0.179356,pass
18,0.108428,0.110575,0.252150,0.088999,0.198288,0.166280,0.106550,0.217650,0.187394,0.450390,...,0.163746,0.308530,0.209461,0.138403,0.298902,0.187286,0.328188,0.200113,0.173081,pass
19,0.105107,0.086282,0.217344,0.129211,0.228766,0.154509,0.146433,0.244705,0.160292,0.526693,...,0.198949,0.335490,0.212528,0.172517,0.321846,0.211777,0.329503,0.244595,0.210895,pass

[[1.17813597 1.18560204 1.08410502 1.19000921 1.11170925 1.09785096
  1.43372524 1.30187298 1.13116865 1.20276567 1.21833452 1.49094854
  1.28815126 1.14313984 1.08374018 1.04849658 1.17020542 1.35919847
  1.13773144 1.13489086 1.32676134 1.15600745 1.11990439 1.15289646
  1.29427192 1.24181301]]
BARINEL SCORES

,rx 24,rx 17,rzz 23,rzz 21,rzz 7,h 6,rzz 15,rx 20,rzz 11,h 10,...,rzz 13,rzz 18,h 0,rx 14,rx 5,h 1,rzz 2,rx 8,rx 19,rzz 9
sum,0.569829,0.562604,0.558161,0.55081,0.550342,0.547168,0.546661,0.546089,0.544499,0.544319,...,0.536144,0.534824,0.520244,0.519868,0.519672,0.512932,0.512669,0.506203,0.500362,0.500199

custom SCORES

,rx 24,rx 17,rx 14,rzz 15,rzz 23,rzz 18,rzz 13,rzz 7,rx 22,rzz 21,...,h 3,rx 5,rzz 11,h 10,h 0,rx 19,h 1,rx 8,rzz 2,rzz 9
sum,0.738727,0.721704,0.713642,0.713165,0.709438,0.708892,0.708802,0.706878,0.705521,0.703896,...,0.692461,0.692043,0.692023,0.686998,0.681755,0.679708,0.678901,0.67821,0.660433,0.646532

DSTAR SCORES

,ccx 16,rzz 7,rzz 4,rzz 11,rzz 2,rzz 15,rzz 23,rzz 18,rzz 21,h 6,...,rx 20,rx 5,rx 8,rzz 9,rx 12,rx 24,rx 19,rx 22,rx 25,rx 14
sum,2.147683,1.117636,1.037197,0.917672,0.907723,0.860237,0.729424,0.565904,0.548746,0.54796,...,0.322841,0.295346,0.286995,0.259401,0.2592,0.169407,0.145489,0.145,0.134441,0.095797

ERROR GATE LOCATION:
16
Now evolving the following mutant:  AddGate_p_inGap_16_.qasm

100%|██████████| 10/10 [01:39<00:00,  9.94s/it]
100%|██████████| 10/10 [01:41<00:00, 10.13s/it]

,rx 25,rx 24,rzz 23,rx 22,rzz 21,rx 20,rx 19,rzz 18,rx 17,rzz 16,...,rx 8,rzz 7,h 6,rx 5,rzz 4,h 3,rzz 2,h 1,h 0,pass/fail
0,0.107913,0.114477,0.266634,0.126086,0.234221,0.170495,0.130630,0.248206,0.200570,0.441101,...,0.233583,0.438026,0.286070,0.228628,0.379916,0.287765,0.426703,0.292830,0.278659,fail
1,0.124032,0.149394,0.313248,0.138711,0.261550,0.193194,0.133357,0.270854,0.239201,0.483409,...,0.229402,0.443857,0.325587,0.249640,0.490592,0.322848,0.421352,0.297793,0.303985,fail
2,0.145683,0.072755,0.249428,0.120306,0.264604,0.213530,0.141338,0.231875,0.153688,0.425796,...,0.237687,0.438740,0.241346,0.249422,0.452966,0.297850,0.431119,0.299084,0.300989,fail
3,0.109839,0.091675,0.235551,0.106484,0.207720,0.167730,0.139412,0.231987,0.164696,0.399268,...,0.244175,0.414241,0.246500,0.231311,0.417087,0.263754,0.492042,0.302417,0.284569,fail
4,0.144790,0.131972,0.306317,0.115971,0.244431,0.208139,0.144096,0.257221,0.215758,0.424889,...,0.247939,0.433687,0.305044,0.266065,0.456802,0.300582,0.442677,0.316038,0.316241,fail
5,0.127717,0.086095,0.253096,0.081523,0.207828,0.194352,0.119046,0.198257,0.154349,0.419502,...,0.196400,0.350829,0.230304,0.183924,0.372825,0.231890,0.360017,0.245913,0.226737,fail
6,0.162414,0.094687,0.285120,0.105156,0.249772,0.229560,0.120689,0.229235,0.177237,0.438603,...,0.213682,0.428433,0.260795,0.234790,0.408538,0.275672,0.406704,0.274632,0.281067,fail
7,0.134655,0.114117,0.290467,0.115127,0.255140,0.206398,0.128044,0.240034,0.194014,0.450361,...,0.226305,0.410539,0.276601,0.192957,0.343263,0.273786,0.414157,0.281395,0.243235,fail
8,0.094435,0.088115,0.232028,0.101426,0.210541,0.163284,0.148955,0.248134,0.161545,0.443418,...,0.244658,0.431209,0.242696,0.198565,0.423048,0.252835,0.442371,0.301546,0.253650,fail
9,0.149878,0.112203,0.292798,0.133984,0.287889,0.221737,0.185734,0.294864,0.196330,0.460177,...,0.300617,0.474853,0.296548,0.279223,0.542904,0.343509,0.514317,0.368602,0.343383,fail
10,0.046895,0.079841,0.149118,0.086253,0.154256,0.088049,0.077237,0.160964,0.132063,0.258672,...,0.136744,0.282678,0.178981,0.143123,0.317685,0.199720,0.229664,0.175371,0.176376,pass
11,0.085531,0.111426,0.219861,0.082364,0.155846,0.125826,0.101491,0.196277,0.172744,0.289115,...,0.172267,0.300875,0.231325,0.153784,0.280050,0.200580,0.267295,0.215154,0.187615,pass
12,0.084847,0.100965,0.212538,0.091246,0.170972,0.125112,0.050025,0.154385,0.161451,0.321609,...,0.113513,0.336055,0.212664,0.210746,0.362486,0.217712,0.314530,0.172159,0.241508,pass
13,0.111607,0.109306,0.262664,0.137275,0.241846,0.175090,0.129955,0.237966,0.191250,0.443820,...,0.231013,0.431266,0.276589,0.254614,0.409270,0.302491,0.441667,0.295345,0.304701,pass
14,0.099444,0.099672,0.244438,0.119406,0.218891,0.162163,0.128128,0.216616,0.175556,0.419516,...,0.222997,0.369282,0.255906,0.223870,0.411300,0.277220,0.399013,0.278372,0.272747,pass
15,0.092986,0.073866,0.194025,0.075056,0.179144,0.141306,0.100954,0.197035,0.138151,0.331066,...,0.172123,0.375429,0.201502,0.188320,0.365109,0.208875,0.299543,0.223914,0.224134,pass
16,0.139612,0.115459,0.281344,0.116926,0.253211,0.205473,0.115263,0.215262,0.192296,0.401384,...,0.205310,0.388447,0.271927,0.239123,0.449236,0.299721,0.360057,0.266405,0.284311,pass
17,0.090886,0.090063,0.222287,0.105948,0.194419,0.143860,0.122272,0.215622,0.158771,0.391054,...,0.209594,0.380674,0.235062,0.226394,0.392236,0.251448,0.412197,0.267202,0.272407,pass
18,0.101208,0.098366,0.215782,0.111126,0.221849,0.153063,0.123797,0.221221,0.161691,0.325392,...,0.209567,0.359435,0.229292,0.181547,0.393633,0.256269,0.402410,0.258604,0.232914,pass
19,0.065418,0.074628,0.154211,0.049074,0.103986,0.091225,0.053004,0.118989,0.115583,0.208317,...,0.098969,0.217247,0.155229,0.140770,0.239373,0.135683,0.217791,0.137035,0.161173,pass

[[1.24803392 1.41540146 1.1496646  1.2116877  1.18780896 1.16621625
  1.33496502 1.20319923 1.2878349  1.10203206 1.15303174 1.19465392
  1.23947726 1.20440855 1.21462228 1.14484207 1.25155893 1.26604893
  1.11352497 1.20076603 1.20639463 1.26611851 1.20508622 1.181942
  1.23681673 1.21228913]]
BARINEL SCORES

,rx 25,rx 20,rx 19,p 15,rx 8,h 10,rzz 11,h 1,rzz 2,rzz 16,...,h 6,h 0,rzz 4,rx 5,rx 12,rx 22,rx 14,rx 17,rzz 13,rx 24
sum,0.586252,0.582444,0.5813,0.579269,0.572633,0.571159,0.566295,0.565533,0.565446,0.564077,...,0.546675,0.545722,0.542206,0.541179,0.541078,0.540129,0.537594,0.537291,0.535736,0.52536

custom SCORES

,rx 19,rx 25,rx 8,rx 20,p 15,h 1,rzz 9,rzz 11,h 10,rzz 2,...,rx 24,h 0,h 6,rx 17,rzz 7,rx 5,rx 12,rx 22,rzz 13,rx 14
sum,0.775304,0.769167,0.753878,0.752258,0.746248,0.740398,0.738728,0.738253,0.734631,0.732527,...,0.711259,0.711115,0.710782,0.710277,0.70746,0.704398,0.703998,0.703745,0.701744,0.698154

DSTAR SCORES

,rzz 16,rzz 2,rzz 7,rzz 4,rzz 11,h 1,h 3,h 0,rzz 23,h 6,...,h 10,rx 12,rx 20,rx 17,p 15,rx 19,rx 25,rx 14,rx 22,rx 24
sum,1.437019,1.418987,1.352927,1.349923,1.301789,0.722718,0.657934,0.649232,0.610707,0.600253,...,0.378375,0.357556,0.339551,0.297415,0.279932,0.17594,0.155107,0.148407,0.119412,0.101707

ERROR GATE LOCATION:
15
Now evolving the following mutant:  AddGate_p_inGap_22_.qasm

100%|██████████| 10/10 [01:41<00:00, 10.18s/it]
100%|██████████| 10/10 [01:39<00:00,  9.96s/it]

,rx 25,rx 24,rzz 23,rx 22,p 21,rzz 20,rx 19,rx 18,rzz 17,rx 16,...,rx 8,rzz 7,h 6,rx 5,rzz 4,h 3,rzz 2,h 1,h 0,pass/fail
0,0.091556,0.082644,0.203196,0.117910,0.096893,0.220641,0.142868,0.101462,0.191325,0.145193,...,0.186025,0.352412,0.211281,0.178989,0.394317,0.264247,0.375659,0.231675,0.225886,fail
1,0.093765,0.107946,0.248487,0.166241,0.134623,0.271798,0.158608,0.100574,0.194500,0.183371,...,0.193098,0.378326,0.261598,0.245300,0.430938,0.334688,0.402099,0.250466,0.293049,fail
2,0.096603,0.099042,0.212892,0.139628,0.112972,0.244853,0.145823,0.139856,0.225129,0.159872,...,0.237102,0.356780,0.234833,0.234192,0.472149,0.303415,0.422139,0.288376,0.288274,fail
3,0.097953,0.092834,0.236680,0.130781,0.106209,0.236252,0.160735,0.119147,0.212298,0.167084,...,0.220689,0.401751,0.245400,0.196402,0.377921,0.279481,0.417119,0.268653,0.245501,fail
4,0.110478,0.104078,0.246438,0.131117,0.106136,0.225620,0.161850,0.129444,0.231188,0.177804,...,0.230649,0.383204,0.253810,0.195302,0.404025,0.283590,0.413523,0.275456,0.248159,fail
5,0.095970,0.119313,0.258898,0.130185,0.105364,0.239736,0.161977,0.132540,0.244029,0.197900,...,0.236560,0.418344,0.282554,0.260036,0.429781,0.296408,0.435859,0.297795,0.307001,fail
6,0.144597,0.150305,0.337280,0.142378,0.115376,0.282001,0.220621,0.140363,0.270893,0.244703,...,0.262789,0.469273,0.341025,0.265299,0.491011,0.340046,0.504247,0.329792,0.323091,fail
7,0.107537,0.112759,0.233943,0.140456,0.111733,0.249909,0.161027,0.115745,0.215939,0.179989,...,0.213068,0.367047,0.253776,0.237276,0.401844,0.298851,0.381827,0.267373,0.283278,fail
8,0.108887,0.118306,0.279485,0.132863,0.108511,0.265588,0.184032,0.080668,0.202800,0.198892,...,0.174248,0.408278,0.273754,0.221670,0.427558,0.300961,0.423214,0.234371,0.269443,fail
9,0.119433,0.123895,0.279744,0.135246,0.108601,0.256390,0.184900,0.099015,0.212221,0.204112,...,0.196304,0.403859,0.281907,0.252569,0.454448,0.307558,0.420859,0.260592,0.300350,fail
10,0.110687,0.125203,0.261442,0.083747,0.068140,0.203565,0.170340,0.140837,0.260427,0.200276,...,0.241108,0.420374,0.280589,0.203685,0.394964,0.240616,0.415866,0.298235,0.250578,pass
11,0.070291,0.127755,0.225750,0.112075,0.089933,0.187515,0.115889,0.112851,0.233544,0.198340,...,0.200857,0.397874,0.270093,0.233489,0.420259,0.263669,0.337671,0.261674,0.273377,pass
12,0.041578,0.071049,0.129455,0.087479,0.070423,0.146492,0.075492,0.065512,0.126994,0.110122,...,0.121888,0.202617,0.150639,0.130885,0.267064,0.182296,0.238950,0.152857,0.162915,pass
13,0.049938,0.042807,0.124951,0.042489,0.034994,0.110137,0.092433,0.086407,0.136530,0.084036,...,0.139315,0.240766,0.131502,0.138924,0.275812,0.134687,0.241985,0.173805,0.166766,pass
14,0.098436,0.094898,0.226985,0.059539,0.047012,0.148865,0.151314,0.109421,0.203432,0.162711,...,0.198428,0.366916,0.233762,0.223849,0.338365,0.189610,0.396204,0.254502,0.258048,pass
15,0.091106,0.095691,0.204435,0.080530,0.064262,0.179618,0.138249,0.081671,0.168655,0.151647,...,0.152454,0.288361,0.207391,0.159173,0.273398,0.200303,0.277232,0.190315,0.190323,pass
16,0.085687,0.084541,0.210174,0.111180,0.090492,0.215949,0.145490,0.088244,0.185032,0.156326,...,0.177576,0.376102,0.222754,0.198380,0.325569,0.253565,0.322269,0.227645,0.236085,pass
17,0.102017,0.103713,0.250053,0.059578,0.047869,0.170008,0.171664,0.113794,0.195016,0.173114,...,0.200173,0.345621,0.249385,0.262626,0.436416,0.226435,0.382674,0.260329,0.297175,pass
18,0.096459,0.101149,0.222498,0.090435,0.072722,0.192940,0.153815,0.134164,0.234656,0.171457,...,0.236371,0.402944,0.249824,0.252003,0.401379,0.250105,0.431142,0.293957,0.294934,pass
19,0.078899,0.128556,0.237789,0.104111,0.082918,0.182416,0.129953,0.124796,0.251075,0.201574,...,0.221553,0.423575,0.278485,0.251472,0.404416,0.255872,0.391653,0.284567,0.291576,pass

[[1.35545148 1.35272955 1.32942178 1.21627223 1.2167499  1.13126626
  1.31131457 1.21126289 1.23115068 1.31637312 1.19747678 1.21396038
  1.11662899 1.15216494 1.17695303 1.27535002 1.15840421 1.22197326
  1.19126669 1.29179349 1.16001248 1.14615373 1.1300066  1.20157645
  1.21939676 1.16051293]]
BARINEL SCORES

,p 21,rx 22,rx 12,rzz 20,h 3,rx 25,rzz 13,h 10,rx 19,rzz 11,...,h 0,rzz 9,rx 24,rx 8,rzz 7,h 1,rx 5,rzz 17,rx 18,rx 14
sum,0.62327,0.621849,0.590985,0.589271,0.577989,0.563873,0.559339,0.559008,0.555797,0.551203,...,0.534793,0.533582,0.532533,0.532276,0.532016,0.530051,0.526782,0.524425,0.52281,0.515652

custom SCORES

,p 21,rx 22,rx 12,rzz 20,rx 25,h 3,rx 19,h 10,rzz 23,rzz 13,...,rzz 4,rx 8,h 1,rzz 7,h 0,rzz 9,rzz 17,rx 18,rx 5,rx 14
sum,0.812861,0.810934,0.761213,0.755926,0.754949,0.741272,0.738004,0.737241,0.729983,0.715482,...,0.704651,0.694883,0.691636,0.690459,0.689952,0.688108,0.685837,0.681125,0.67955,0.672147

DSTAR SCORES

,rzz 4,rzz 11,rzz 2,rzz 15,rzz 7,h 3,h 0,h 1,rzz 13,h 10,...,rx 8,rzz 9,rx 16,rx 19,rx 22,rx 14,rx 18,p 21,rx 24,rx 25
sum,1.355671,1.314326,1.310766,1.262513,1.152448,0.742431,0.623972,0.589987,0.588048,0.569616,...,0.388974,0.37498,0.297649,0.249511,0.17248,0.136371,0.12144,0.114742,0.112488,0.105128

ERROR GATE LOCATION:
21
Now evolving the following mutant:  AddGate_rzz_inGap_16_.qasm

100%|██████████| 10/10 [01:41<00:00, 10.16s/it]
100%|██████████| 10/10 [01:36<00:00,  9.63s/it]

,rx 25,rx 24,rzz 23,rx 22,rzz 21,rx 20,rx 19,rzz 18,rx 17,rzz 16,...,rx 8,rzz 7,h 6,rx 5,rzz 4,h 3,rzz 2,h 1,h 0,pass/fail
0,0.132085,0.133229,0.297307,0.120855,0.238144,0.191759,0.126637,0.241464,0.213758,0.426178,...,0.224768,0.395164,0.271245,0.249987,0.431619,0.289201,0.422006,0.289987,0.299393,fail
1,0.131364,0.149507,0.318241,0.121997,0.246078,0.198431,0.121726,0.250719,0.232311,0.447294,...,0.217419,0.390561,0.282529,0.195401,0.405633,0.281995,0.393865,0.275201,0.246421,fail
2,0.125753,0.128473,0.281009,0.142472,0.266821,0.183224,0.096993,0.227119,0.208264,0.391859,...,0.197271,0.425419,0.261783,0.211209,0.469136,0.310119,0.443834,0.259039,0.265646,fail
3,0.123533,0.165158,0.316306,0.127795,0.248486,0.185009,0.131186,0.284331,0.250995,0.422554,...,0.235968,0.458778,0.300100,0.240906,0.429460,0.296016,0.434776,0.306734,0.292318,fail
4,0.109653,0.108855,0.258984,0.099918,0.215174,0.174751,0.103689,0.198242,0.180889,0.396842,...,0.189357,0.350841,0.230202,0.203331,0.384564,0.255578,0.385928,0.247571,0.249178,fail
5,0.126676,0.131991,0.298653,0.092736,0.212186,0.190957,0.110081,0.249024,0.219494,0.453324,...,0.213591,0.450789,0.267757,0.180711,0.361916,0.236949,0.431868,0.273499,0.230393,fail
6,0.109664,0.120476,0.290098,0.091949,0.208895,0.185649,0.133294,0.263577,0.210416,0.511980,...,0.226320,0.450654,0.261097,0.221804,0.434254,0.258045,0.387778,0.293531,0.273208,fail
7,0.137869,0.130696,0.307305,0.110866,0.216450,0.198683,0.116302,0.231189,0.217423,0.451692,...,0.222166,0.414876,0.274340,0.273291,0.450038,0.280578,0.467697,0.296006,0.323231,fail
8,0.095980,0.074765,0.202822,0.104570,0.209216,0.147385,0.084049,0.176795,0.138466,0.342176,...,0.156025,0.347647,0.180117,0.140889,0.365933,0.227062,0.337932,0.203918,0.187252,fail
9,0.148449,0.128665,0.318705,0.110936,0.273375,0.229671,0.141668,0.262844,0.213669,0.495766,...,0.243337,0.450670,0.280817,0.243133,0.506305,0.309452,0.462570,0.313710,0.302152,fail
10,0.077312,0.090139,0.192474,0.068334,0.130250,0.112750,0.072826,0.166703,0.150572,0.286040,...,0.143942,0.311321,0.180352,0.157358,0.266444,0.165636,0.309029,0.192117,0.189756,pass
11,0.101178,0.141791,0.296400,0.087292,0.210807,0.179011,0.147610,0.284746,0.230887,0.508033,...,0.253023,0.469344,0.280489,0.267732,0.469108,0.263496,0.476528,0.328608,0.320469,pass
12,0.096770,0.089583,0.225778,0.120284,0.225522,0.157429,0.119604,0.209027,0.163143,0.388153,...,0.204917,0.372419,0.217089,0.177520,0.365074,0.264671,0.343555,0.255749,0.225261,pass
13,0.118401,0.112944,0.258968,0.143046,0.254391,0.177869,0.120663,0.222205,0.194381,0.394318,...,0.228562,0.408643,0.256354,0.273659,0.442711,0.323148,0.420337,0.295107,0.323933,pass
14,0.122257,0.171347,0.330961,0.120284,0.239484,0.187914,0.148348,0.319719,0.269833,0.486583,...,0.266556,0.520849,0.320900,0.274971,0.455705,0.301141,0.493083,0.346905,0.330184,pass
15,0.108187,0.110040,0.268551,0.131781,0.249006,0.176596,0.108928,0.208351,0.186124,0.464131,...,0.193188,0.375963,0.238090,0.241058,0.482292,0.305054,0.392684,0.259124,0.291877,pass
16,0.101335,0.101847,0.244961,0.079084,0.203879,0.173212,0.105200,0.201742,0.171087,0.422229,...,0.190742,0.352884,0.220090,0.236339,0.392691,0.234878,0.416954,0.255783,0.280188,pass
17,0.108573,0.130701,0.252433,0.133648,0.251703,0.163295,0.128306,0.249315,0.204186,0.348367,...,0.232433,0.404292,0.261602,0.260059,0.448630,0.313037,0.434936,0.294697,0.312011,pass
18,0.088667,0.131115,0.245790,0.157377,0.255134,0.144357,0.146880,0.275083,0.208063,0.383301,...,0.243655,0.403376,0.255030,0.202610,0.425037,0.314689,0.373634,0.298824,0.259496,pass
19,0.107016,0.122037,0.259742,0.101823,0.230541,0.170613,0.116083,0.254194,0.203635,0.427176,...,0.230693,0.487433,0.257891,0.266480,0.517290,0.284358,0.515687,0.301650,0.320519,pass

[[1.19617716 1.29860389 1.10300097 1.26743675 1.17086022 1.21807862
  1.21537989 1.19201272 1.20341505 1.17976875 1.19908578 1.32616521
  1.14165614 1.17935433 1.28732007 1.13546926 1.14103926 1.14445855
  1.10939252 1.14981552 1.26484882 1.1944372  1.12976211 1.12204515
  1.13696223 1.21096826]]
BARINEL SCORES

,rx 25,rx 20,rzz 23,h 10,rx 24,rzz 16,rx 17,h 6,rzz 15,rzz 21,...,h 3,rx 22,h 1,rx 8,rx 19,rzz 13,h 0,rzz 9,rx 5,rx 14
sum,0.546534,0.534358,0.528668,0.519637,0.514206,0.513692,0.512756,0.511975,0.511052,0.509171,...,0.497723,0.495841,0.493793,0.492873,0.489743,0.483718,0.483297,0.48283,0.478187,0.46871

custom SCORES

,rx 25,rx 20,rx 24,rzz 23,h 10,rx 17,rzz 16,rzz 15,rzz 11,h 6,...,rzz 2,rx 19,h 3,h 1,rx 8,h 0,rx 5,rx 14,rzz 13,rzz 9
sum,0.709971,0.697081,0.681143,0.674449,0.667146,0.667021,0.665201,0.664251,0.663637,0.659145,...,0.639628,0.638549,0.638301,0.634149,0.633891,0.629611,0.629395,0.624107,0.621778,0.620562

DSTAR SCORES

,rzz 15,rzz 16,rzz 4,rzz 2,rzz 7,rzz 11,rzz 23,h 1,h 3,h 0,...,rx 8,rx 17,rzz 9,rx 12,rx 20,rx 24,rx 25,rx 19,rx 14,rx 22
sum,1.763624,1.334862,1.259582,1.225579,1.212314,1.180989,0.663865,0.593454,0.59005,0.554284,...,0.370933,0.363055,0.335832,0.329843,0.305348,0.144401,0.139636,0.121154,0.118689,0.113398

ERROR GATE LOCATION:
16
Now evolving the following mutant:  AddGate_rz_inGap_24_.qasm

100%|██████████| 10/10 [02:02<00:00, 12.26s/it]
100%|██████████| 10/10 [02:04<00:00, 12.40s/it]

,rx 25,rx 24,rz 23,rzz 22,rx 21,rzz 20,rx 19,rx 18,rzz 17,rx 16,...,rx 8,rzz 7,h 6,rx 5,rzz 4,h 3,rzz 2,h 1,h 0,pass/fail
0,0.144006,0.139078,0.025256,0.233848,0.104434,0.233056,0.200145,0.084549,0.248276,0.202464,...,0.180474,0.430200,0.295797,0.261050,0.525459,0.282538,0.418003,0.250844,0.303746,fail
1,0.129486,0.151536,0.027242,0.224784,0.116663,0.239805,0.192748,0.099755,0.251769,0.211405,...,0.198322,0.384407,0.309751,0.267554,0.434797,0.292476,0.403531,0.264693,0.305933,fail
2,0.102543,0.144655,0.025501,0.206542,0.154546,0.296269,0.182720,0.127146,0.306661,0.210455,...,0.240258,0.474206,0.319535,0.228511,0.497133,0.345901,0.468800,0.303327,0.289115,fail
3,0.109030,0.124791,0.021922,0.208492,0.097729,0.226460,0.184099,0.124149,0.284493,0.186514,...,0.218783,0.449951,0.290433,0.247067,0.502679,0.273016,0.425658,0.283057,0.293874,fail
4,0.112855,0.148616,0.026485,0.210298,0.133252,0.270779,0.181059,0.141091,0.299069,0.211464,...,0.250608,0.448896,0.315570,0.248543,0.539207,0.329577,0.462578,0.316534,0.305976,fail
5,0.120161,0.120144,0.021771,0.198979,0.086896,0.203970,0.175722,0.117054,0.251893,0.175801,...,0.208087,0.380172,0.259907,0.202734,0.361124,0.229616,0.376564,0.261796,0.241297,fail
6,0.122411,0.149113,0.026316,0.227576,0.128184,0.260262,0.203554,0.143649,0.316789,0.219779,...,0.260189,0.479686,0.337871,0.270088,0.447814,0.314827,0.482493,0.329959,0.319890,fail
7,0.143328,0.138581,0.025070,0.235471,0.119346,0.250353,0.206167,0.128188,0.266881,0.204959,...,0.224804,0.395821,0.301918,0.212563,0.426752,0.287763,0.364890,0.279372,0.257799,fail
8,0.156606,0.162489,0.029076,0.265282,0.153326,0.295026,0.234232,0.158266,0.351855,0.247570,...,0.289728,0.538355,0.370140,0.238141,0.496587,0.350834,0.475618,0.357967,0.298947,fail
9,0.107592,0.141225,0.025164,0.200333,0.090563,0.199937,0.171967,0.117947,0.278191,0.199588,...,0.219004,0.414598,0.295592,0.263900,0.420605,0.254728,0.438496,0.287349,0.306075,fail
10,0.053267,0.113160,0.019617,0.132156,0.093000,0.159184,0.105436,0.090043,0.222528,0.155845,...,0.167783,0.340527,0.235945,0.167591,0.350680,0.219009,0.319291,0.214757,0.204841,pass
11,0.081232,0.088789,0.015756,0.143138,0.105867,0.187465,0.126863,0.110400,0.211734,0.138351,...,0.192757,0.331677,0.214789,0.159983,0.320781,0.230198,0.324767,0.233212,0.199722,pass
12,0.056660,0.051169,0.009067,0.100057,0.057578,0.135667,0.095293,0.045037,0.103659,0.077927,...,0.084485,0.173840,0.119253,0.081341,0.190416,0.132374,0.183452,0.109376,0.104030,pass
13,0.068973,0.089526,0.015852,0.127666,0.100411,0.172886,0.112477,0.129207,0.227091,0.137425,...,0.210896,0.324597,0.216014,0.189529,0.330233,0.229550,0.305551,0.255711,0.228408,pass
14,0.138566,0.150883,0.027275,0.234620,0.136262,0.284094,0.209067,0.143843,0.310459,0.221004,...,0.253676,0.455490,0.328269,0.243500,0.494598,0.332120,0.412748,0.314704,0.297053,pass
15,0.102216,0.069076,0.012371,0.162088,0.085858,0.181592,0.149841,0.086109,0.166703,0.114908,...,0.143620,0.261818,0.179275,0.125587,0.282362,0.197417,0.208241,0.175829,0.156823,pass
16,0.058255,0.090368,0.016016,0.115142,0.081734,0.147462,0.098572,0.084106,0.190344,0.130603,...,0.148819,0.285388,0.196073,0.172720,0.341146,0.199728,0.249187,0.193683,0.203689,pass
17,0.107305,0.132056,0.023861,0.184613,0.090753,0.193343,0.158513,0.116850,0.270680,0.190111,...,0.222606,0.428653,0.283878,0.246235,0.345330,0.237837,0.430188,0.283177,0.282480,pass
18,0.091868,0.092925,0.016010,0.173945,0.096275,0.205349,0.161764,0.110075,0.234370,0.147210,...,0.194221,0.377550,0.237044,0.201730,0.396266,0.244863,0.381448,0.249306,0.245803,pass
19,0.076062,0.095588,0.017032,0.139309,0.074358,0.163046,0.125807,0.100368,0.201446,0.136827,...,0.176025,0.293873,0.207849,0.151676,0.236194,0.187165,0.321629,0.214599,0.183834,pass

[[1.25483962 1.14410133 1.1456212  1.1994999  1.30425097 1.19660369
  1.21212289 1.27449608 1.2320382  1.19598852 1.14578748 1.15802876
  1.10440813 1.23419191 1.20831306 1.20675081 1.1649817  1.26504511
  1.22456557 1.19534564 1.10685139 1.15904621 1.1847385  1.11775459
  1.21968974 1.09452075]]
BARINEL SCORES

,rx 25,rz 23,rzz 22,rx 24,rx 19,rx 16,h 10,rzz 4,rx 5,rx 14,...,rzz 20,rzz 7,h 3,rzz 17,rx 12,h 1,rzz 9,rx 21,rx 8,rx 18
sum,0.59931,0.594861,0.593825,0.593303,0.589861,0.588033,0.586163,0.585902,0.583762,0.583598,...,0.574992,0.573202,0.572611,0.571759,0.569225,0.566664,0.56622,0.562372,0.560631,0.549994

custom SCORES

,rx 25,rzz 22,rx 19,rz 23,rx 16,rx 24,h 10,h 6,rzz 4,rzz 11,...,rx 5,rx 12,h 3,rzz 13,rzz 2,h 0,h 1,rx 8,rzz 9,rx 18
sum,0.78732,0.771898,0.768608,0.765232,0.763853,0.763002,0.763001,0.756715,0.755674,0.753804,...,0.745296,0.744858,0.742209,0.741023,0.741013,0.740133,0.739453,0.737937,0.73113,0.725235

DSTAR SCORES

,rzz 4,rzz 11,rzz 15,rzz 7,rzz 2,h 6,h 3,h 10,h 0,h 1,...,rx 12,rzz 9,rx 16,rx 19,rx 24,rx 14,rx 25,rx 18,rx 21,rz 23
sum,1.628729,1.591106,1.488363,1.456096,1.418437,0.784751,0.71818,0.717637,0.705552,0.703478,...,0.417569,0.389254,0.37422,0.329191,0.183811,0.158282,0.143759,0.139982,0.128554,0.006332

ERROR GATE LOCATION:
23
Now evolving the following mutant:  AddGate_p_inGap_19_.qasm

100%|██████████| 10/10 [01:50<00:00, 11.05s/it]
100%|██████████| 10/10 [01:51<00:00, 11.18s/it]

,rx 25,rx 24,rzz 23,rx 22,rzz 21,rx 20,rx 19,p 18,rzz 17,rx 16,...,rx 8,rzz 7,h 6,rx 5,rzz 4,h 3,rzz 2,h 1,h 0,pass/fail
0,0.082719,0.090275,0.216062,0.100432,0.217019,0.152642,0.132109,0.027654,0.158971,0.163641,...,0.201103,0.404704,0.241537,0.217464,0.435811,0.259709,0.393684,0.276480,0.267770,fail
1,0.128983,0.119610,0.297623,0.103176,0.224026,0.202138,0.155359,0.037115,0.170299,0.198763,...,0.230778,0.376068,0.290568,0.229218,0.411699,0.269591,0.372639,0.297459,0.274107,fail
2,0.131206,0.107468,0.278953,0.104758,0.228537,0.196954,0.141884,0.031877,0.179836,0.188654,...,0.224582,0.448791,0.274602,0.237872,0.422775,0.267907,0.438753,0.304240,0.286872,fail
3,0.144947,0.134748,0.308053,0.122585,0.255079,0.210584,0.153568,0.035984,0.207603,0.223930,...,0.251805,0.485069,0.317079,0.266507,0.453914,0.306512,0.501293,0.337687,0.320414,fail
4,0.109229,0.075017,0.210627,0.115244,0.237481,0.171295,0.129169,0.027405,0.158394,0.151155,...,0.209335,0.443541,0.228103,0.236451,0.473813,0.284306,0.456126,0.294720,0.291521,fail
5,0.126565,0.102739,0.250425,0.138042,0.263172,0.187932,0.126870,0.029670,0.167676,0.185009,...,0.224665,0.447801,0.268546,0.282930,0.472157,0.321516,0.489470,0.310088,0.334540,fail
6,0.119762,0.098445,0.257663,0.082044,0.204918,0.183614,0.142534,0.032531,0.170589,0.172664,...,0.216946,0.405416,0.253012,0.179159,0.360892,0.227783,0.387307,0.285933,0.226300,fail
7,0.138020,0.130420,0.299750,0.106252,0.245794,0.208158,0.175043,0.041776,0.200004,0.215899,...,0.272500,0.446330,0.312259,0.226635,0.427082,0.292717,0.454432,0.348746,0.282823,fail
8,0.084851,0.123662,0.255146,0.121569,0.233482,0.154293,0.152664,0.034266,0.194563,0.207785,...,0.247807,0.465515,0.296162,0.264283,0.482403,0.303352,0.496104,0.333244,0.321663,fail
9,0.127510,0.142812,0.305296,0.130374,0.247601,0.198341,0.128494,0.030120,0.184146,0.234761,...,0.232026,0.451151,0.326862,0.324306,0.454621,0.320179,0.456678,0.320210,0.368642,fail
10,0.092884,0.125446,0.261107,0.095896,0.196536,0.154628,0.115176,0.024939,0.198365,0.215547,...,0.205990,0.489062,0.296778,0.254218,0.385057,0.254838,0.444134,0.289846,0.296557,pass
11,0.111661,0.126328,0.272222,0.125600,0.241719,0.177802,0.154076,0.035825,0.207859,0.216481,...,0.246374,0.481881,0.306912,0.275259,0.485497,0.309035,0.457217,0.331472,0.328682,pass
12,0.109397,0.108054,0.265490,0.125857,0.259111,0.181563,0.129867,0.029107,0.173876,0.195777,...,0.220863,0.466977,0.282039,0.235832,0.476159,0.308371,0.476997,0.303241,0.293067,pass
13,0.130093,0.123567,0.282464,0.125155,0.257067,0.192835,0.138540,0.033627,0.194431,0.211308,...,0.221589,0.454228,0.296211,0.214012,0.390353,0.291159,0.359250,0.293846,0.259451,pass
14,0.150036,0.120600,0.299750,0.092839,0.248780,0.217852,0.119249,0.027629,0.193550,0.208534,...,0.194570,0.473068,0.287696,0.192221,0.400546,0.258131,0.376163,0.270710,0.238814,pass
15,0.148190,0.086911,0.268725,0.140375,0.280597,0.216852,0.163477,0.039203,0.156698,0.163978,...,0.252675,0.397688,0.257498,0.261450,0.500308,0.330909,0.469115,0.325972,0.319067,pass
16,0.130136,0.129119,0.291034,0.109608,0.228182,0.188745,0.133727,0.032228,0.167643,0.203929,...,0.217835,0.377595,0.289559,0.248295,0.406266,0.281211,0.409129,0.287940,0.291835,pass
17,0.092261,0.087357,0.218044,0.105104,0.226112,0.161952,0.144298,0.033451,0.172350,0.163745,...,0.221651,0.424390,0.241735,0.161610,0.366105,0.257400,0.398215,0.288424,0.216592,pass
18,0.124955,0.121581,0.285912,0.121553,0.244829,0.194088,0.109912,0.026605,0.167193,0.204642,...,0.208644,0.435725,0.288538,0.287464,0.447736,0.298789,0.473574,0.289941,0.333034,pass
19,0.108100,0.109683,0.236951,0.073925,0.168494,0.149984,0.156041,0.036774,0.184943,0.182133,...,0.238469,0.420034,0.261323,0.221336,0.389532,0.218775,0.412435,0.313533,0.265098,pass

[[1.21417302 1.26921342 1.14962577 1.22760938 1.11650125 1.12855816
  1.21752752 1.2721035  1.15844939 1.20869842 1.08163112 1.42309635
  1.20490503 1.14434398 1.07280873 1.12571416 1.10715062 1.17886307
  1.10888399 1.16373543 1.31573731 1.09757573 1.12671254 1.12739114
  1.12180164 1.2392773 ]]
BARINEL SCORES

,rx 19,rx 5,h 0,rx 14,rzz 9,rzz 2,rzz 13,h 1,rx 8,rzz 4,...,rzz 11,rx 22,rzz 21,h 6,rzz 23,rx 25,rzz 7,rx 24,rx 16,rzz 17
sum,0.513085,0.511744,0.511386,0.511232,0.510509,0.509759,0.509756,0.509329,0.509128,0.508539,...,0.502814,0.501911,0.500603,0.500039,0.499804,0.49918,0.49737,0.49703,0.496954,0.49656

custom SCORES

,rx 14,rx 5,h 0,rx 19,p 18,rzz 13,rx 8,rx 22,rx 24,rzz 2,...,rx 20,h 3,h 6,h 10,rzz 15,rzz 23,rzz 17,rzz 21,rzz 11,rzz 7
sum,0.693115,0.680074,0.669823,0.669259,0.668179,0.663308,0.659176,0.655949,0.654739,0.653434,...,0.646204,0.645927,0.645517,0.64449,0.644054,0.643451,0.64037,0.640334,0.63767,0.635251

DSTAR SCORES

,rzz 2,rzz 4,rzz 11,rzz 15,rzz 7,h 1,h 0,h 3,h 6,h 10,...,rx 12,rx 16,rx 20,rzz 17,rx 19,rx 14,rx 25,rx 22,rx 24,p 18
sum,1.384906,1.355846,1.342834,1.335481,1.326934,0.743727,0.689022,0.635734,0.615927,0.610962,...,0.358485,0.315256,0.294161,0.271776,0.181881,0.15883,0.12727,0.113751,0.113665,0.010451

ERROR GATE LOCATION:
18
Now evolving the following mutant:  AddGate_s_inGap_16_.qasm

100%|██████████| 10/10 [01:50<00:00, 11.09s/it]
100%|██████████| 10/10 [01:33<00:00,  9.38s/it]

,rx 25,rx 24,rzz 23,rx 22,rzz 21,rx 20,rx 19,rzz 18,rx 17,rzz 16,...,rx 8,rzz 7,h 6,rx 5,rzz 4,h 3,rzz 2,h 1,h 0,pass/fail
0,0.121965,0.119620,0.285481,0.087546,0.211220,0.192073,0.118448,0.250977,0.207745,0.460444,...,0.215732,0.488844,0.289855,0.242952,0.452385,0.254944,0.423660,0.283466,0.287607,fail
1,0.111460,0.126639,0.275160,0.133133,0.259698,0.182634,0.118985,0.235515,0.209236,0.441686,...,0.222855,0.432160,0.290275,0.254456,0.449388,0.312173,0.435966,0.287934,0.304597,fail
2,0.133641,0.113103,0.291617,0.157325,0.301676,0.211173,0.136401,0.239460,0.198759,0.499418,...,0.238049,0.433514,0.289392,0.225768,0.529988,0.350726,0.441869,0.294753,0.287220,fail
3,0.133574,0.104884,0.278256,0.149728,0.283885,0.208807,0.169789,0.272256,0.194602,0.479321,...,0.282859,0.465759,0.292188,0.282696,0.499296,0.343552,0.468022,0.350126,0.341883,fail
4,0.119046,0.116047,0.260997,0.142657,0.261701,0.180942,0.155635,0.256334,0.194282,0.412078,...,0.264712,0.433552,0.286637,0.325189,0.501314,0.340616,0.480915,0.339690,0.377928,fail
5,0.099648,0.111562,0.233298,0.122538,0.236209,0.158106,0.122188,0.257193,0.189983,0.365018,...,0.220747,0.474265,0.260599,0.190819,0.426466,0.274418,0.411266,0.278378,0.243346,fail
6,0.097118,0.117660,0.249753,0.092862,0.196314,0.154802,0.106576,0.214845,0.189968,0.392810,...,0.192393,0.381045,0.262423,0.228524,0.377794,0.245068,0.383496,0.252199,0.269341,fail
7,0.113014,0.108014,0.255070,0.108656,0.231696,0.175350,0.101361,0.213851,0.185351,0.408130,...,0.197883,0.426490,0.262127,0.277599,0.428214,0.280955,0.427856,0.268733,0.320489,fail
8,0.149710,0.129099,0.324548,0.140030,0.302469,0.235115,0.150472,0.285752,0.224452,0.521812,...,0.273471,0.525484,0.323583,0.258155,0.515656,0.349701,0.534729,0.343528,0.321610,fail
9,0.126919,0.117522,0.276688,0.079202,0.198825,0.190609,0.128279,0.240139,0.193536,0.414867,...,0.218005,0.402704,0.275379,0.253623,0.364101,0.240759,0.407865,0.283361,0.292574,fail
10,0.146618,0.121068,0.306379,0.118422,0.278035,0.219500,0.098628,0.188912,0.192976,0.457906,...,0.190181,0.354807,0.276277,0.291277,0.528774,0.325021,0.472428,0.257459,0.339893,pass
11,0.101723,0.085983,0.209729,0.139392,0.250483,0.160724,0.097171,0.177561,0.151576,0.335596,...,0.189479,0.343120,0.217152,0.209560,0.406688,0.291383,0.421918,0.241123,0.260612,pass
12,0.123773,0.152873,0.295777,0.148122,0.277253,0.186092,0.118362,0.254105,0.230959,0.399086,...,0.229570,0.436815,0.311178,0.275102,0.447940,0.333451,0.478560,0.296862,0.326784,pass
13,0.075457,0.103605,0.215679,0.106276,0.206758,0.139103,0.102590,0.197537,0.169717,0.369557,...,0.183985,0.358075,0.236694,0.210334,0.418641,0.256226,0.372699,0.240845,0.255918,pass
14,0.133937,0.093457,0.256606,0.098309,0.218448,0.188125,0.126061,0.201232,0.158843,0.389550,...,0.195728,0.326378,0.237570,0.254705,0.465848,0.269822,0.347698,0.256367,0.295134,pass
15,0.112265,0.110809,0.255925,0.118809,0.220911,0.173136,0.109918,0.221040,0.192717,0.403956,...,0.213968,0.429901,0.274166,0.287633,0.423312,0.291853,0.468605,0.284623,0.332955,pass
16,0.097944,0.107350,0.235278,0.085931,0.191393,0.157114,0.106213,0.219576,0.183451,0.373818,...,0.204608,0.422001,0.254993,0.229091,0.405899,0.242716,0.415912,0.265491,0.272932,pass
17,0.071228,0.083662,0.176577,0.075290,0.144623,0.112538,0.062273,0.132468,0.131699,0.274123,...,0.134445,0.255005,0.184022,0.222537,0.294052,0.193052,0.350431,0.186101,0.251282,pass
18,0.091973,0.114355,0.250240,0.092657,0.183320,0.151206,0.130831,0.263861,0.199515,0.440202,...,0.226571,0.457292,0.278121,0.215717,0.381690,0.237720,0.416029,0.289583,0.262770,pass
19,0.063482,0.049272,0.134299,0.078065,0.156957,0.101688,0.072835,0.136656,0.094782,0.241630,...,0.138478,0.278498,0.142083,0.149698,0.307212,0.187488,0.303209,0.176771,0.185095,pass

[[1.24128017 1.10895499 1.18844153 1.29626672 1.21782066 1.24425248
  1.29794617 1.15861687 1.12908491 1.1871271  1.23368255 1.34928338
  1.23921424 1.24051463 1.24436426 1.21395675 1.20700144 1.21570551
  1.17720895 1.14241206 1.28038138 1.16619159 1.17185524 1.2109876
  1.17406469 1.24049265]]
BARINEL SCORES

,rx 19,rzz 18,rx 8,rzz 7,h 1,rzz 16,rx 20,rx 25,sdg 15,h 10,...,rx 22,rx 24,h 3,rzz 9,rzz 4,h 0,rzz 13,rzz 2,rx 5,rx 14
sum,0.560705,0.553077,0.549566,0.549345,0.54445,0.54394,0.543173,0.542188,0.541295,0.540206,...,0.533496,0.532405,0.532391,0.529968,0.526931,0.522575,0.522356,0.52175,0.519868,0.51554

custom SCORES

,rx 19,rx 8,rzz 18,rx 20,rzz 7,rx 25,sdg 15,rx 22,rzz 16,h 1,...,rx 17,rzz 9,rx 14,h 3,rx 5,h 0,rzz 13,rzz 4,rx 24,rzz 2
sum,0.742646,0.716593,0.713279,0.712134,0.711018,0.71044,0.708242,0.706385,0.705372,0.704255,...,0.690022,0.689886,0.689443,0.688362,0.686275,0.684637,0.684184,0.680557,0.680009,0.679709

DSTAR SCORES

,rzz 4,rzz 7,rzz 16,rzz 2,rzz 11,sdg 15,h 0,h 1,h 3,h 6,...,rzz 9,rx 12,h 10,rx 17,rx 20,rx 14,rx 19,rx 22,rx 25,rx 24
sum,1.466856,1.458484,1.411807,1.387999,1.360721,0.809606,0.72608,0.711739,0.709297,0.646363,...,0.43019,0.398039,0.358305,0.337581,0.308099,0.183173,0.155214,0.133168,0.132021,0.122953

ERROR GATE LOCATION:
15
Now evolving the following mutant:  AddGate_x_inGap_16_.qasm

100%|██████████| 10/10 [01:37<00:00,  9.77s/it]
100%|██████████| 10/10 [01:34<00:00,  9.47s/it]

,rx 25,rx 24,rzz 23,rx 22,rzz 21,rx 20,rx 19,rzz 18,rx 17,rzz 16,...,rx 8,rzz 7,h 6,rx 5,rzz 4,h 3,rzz 2,h 1,h 0,pass/fail
0,0.103850,0.114347,0.246869,0.142400,0.247953,0.162343,0.157542,0.272844,0.194704,0.416434,...,0.266792,0.456185,0.283915,0.306654,0.525291,0.335000,0.448162,0.334989,0.359312,fail
1,0.124054,0.132751,0.293871,0.133394,0.258652,0.185012,0.087657,0.216331,0.214262,0.436986,...,0.186375,0.423662,0.291191,0.276076,0.495666,0.312486,0.449027,0.258516,0.321910,fail
2,0.155078,0.146500,0.331461,0.131555,0.265301,0.216547,0.082374,0.233153,0.236392,0.465177,...,0.193805,0.484694,0.316997,0.257823,0.501924,0.309790,0.505679,0.267119,0.309552,fail
3,0.119932,0.126399,0.276361,0.171371,0.287207,0.183214,0.130126,0.260260,0.218703,0.456845,...,0.253502,0.505221,0.310570,0.313004,0.522657,0.369366,0.511432,0.328688,0.369769,fail
4,0.145471,0.113691,0.298881,0.097474,0.222570,0.210012,0.152640,0.266650,0.197606,0.473351,...,0.267860,0.459213,0.290848,0.266329,0.441357,0.272546,0.499667,0.329185,0.316211,fail
5,0.090396,0.072126,0.209155,0.094529,0.180734,0.149869,0.081360,0.168414,0.144229,0.406128,...,0.172617,0.381457,0.212679,0.230745,0.356789,0.234491,0.414659,0.229061,0.268985,fail
6,0.154238,0.094424,0.287284,0.152635,0.289051,0.225077,0.141207,0.251378,0.188276,0.481353,...,0.258698,0.488284,0.281348,0.239797,0.502939,0.341641,0.459658,0.315920,0.299385,fail
7,0.165518,0.136773,0.340021,0.155396,0.328121,0.246202,0.141127,0.278987,0.237029,0.517801,...,0.275883,0.551945,0.339632,0.314024,0.607485,0.389275,0.559048,0.352965,0.378127,fail
8,0.095234,0.122503,0.265105,0.127337,0.239217,0.165992,0.145416,0.263929,0.206460,0.453235,...,0.247120,0.436833,0.294682,0.234782,0.425191,0.297256,0.396279,0.308634,0.285517,fail
9,0.125729,0.132765,0.298962,0.107079,0.229160,0.194059,0.121279,0.274472,0.228696,0.473441,...,0.236743,0.507488,0.314265,0.254126,0.449494,0.281180,0.461347,0.306079,0.305068,fail
10,0.097722,0.111554,0.232482,0.136286,0.250963,0.156069,0.102244,0.202249,0.180562,0.362190,...,0.196255,0.371749,0.251616,0.263498,0.463475,0.310170,0.388999,0.256586,0.307944,pass
11,0.062679,0.074557,0.179414,0.092797,0.192531,0.126001,0.114287,0.210343,0.143917,0.361622,...,0.200600,0.402310,0.213513,0.191890,0.350613,0.236493,0.329665,0.250553,0.232531,pass
12,0.095998,0.050663,0.166130,0.053133,0.138764,0.139921,0.096980,0.157431,0.105726,0.292555,...,0.167885,0.308233,0.165617,0.228134,0.368065,0.184905,0.322811,0.217882,0.258564,pass
13,0.069510,0.124059,0.221098,0.102120,0.186552,0.115492,0.095000,0.225769,0.189414,0.335710,...,0.180987,0.389467,0.248549,0.145557,0.401603,0.228609,0.368518,0.228069,0.194126,pass
14,0.149241,0.105376,0.279934,0.113679,0.269905,0.221339,0.163709,0.270817,0.183480,0.433577,...,0.270976,0.444653,0.274613,0.239215,0.446868,0.298720,0.437657,0.329538,0.293823,pass
15,0.111687,0.089549,0.241894,0.074609,0.180857,0.165512,0.072474,0.180556,0.163045,0.385102,...,0.152341,0.384453,0.223231,0.125673,0.360939,0.196513,0.328772,0.193539,0.167371,pass
16,0.080572,0.115156,0.226663,0.119191,0.216507,0.140004,0.104137,0.204436,0.181315,0.371594,...,0.191638,0.341436,0.252904,0.234976,0.344804,0.268840,0.376591,0.245931,0.273087,pass
17,0.121866,0.116167,0.276238,0.115728,0.232600,0.189531,0.114095,0.230549,0.201844,0.434666,...,0.213615,0.450998,0.288274,0.284012,0.463560,0.295613,0.402702,0.285726,0.325488,pass
18,0.072561,0.070740,0.173277,0.082004,0.149516,0.112374,0.061883,0.128255,0.122866,0.275628,...,0.125532,0.261648,0.173654,0.149154,0.276137,0.187549,0.256830,0.164908,0.178074,pass
19,0.106300,0.076940,0.217908,0.090435,0.191397,0.160868,0.113603,0.198678,0.146800,0.378146,...,0.209888,0.385278,0.221033,0.212333,0.363724,0.236105,0.376559,0.261166,0.251699,pass

[[1.29361436 1.22874145 1.19390668 1.30501817 1.28777509 1.27017764
  1.26975529 1.12204519 1.14708832 1.13038568 1.24589929 1.20944362
  1.20211414 1.23282043 1.34046946 1.24668174 1.14508221 1.1692961
  1.17560531 1.15673491 1.16591955 1.25804771 1.23853409 1.18821055
  1.16445738 1.17655863]]
BARINEL SCORES

,rx 22,rx 25,rzz 2,rx 5,h 0,rx 12,rx 14,h 3,rzz 23,h 10,...,rx 20,rzz 21,rzz 16,rzz 4,rzz 7,h 1,rzz 18,rx 8,rx 19,rzz 11
sum,0.572648,0.569265,0.567268,0.564906,0.564173,0.563347,0.562873,0.562607,0.562506,0.560986,...,0.559331,0.559064,0.557843,0.557045,0.556594,0.554643,0.55309,0.552667,0.544384,0.540816

custom SCORES

,rx 22,rx 25,rzz 21,rx 12,rx 20,h 3,h 10,rzz 2,x 15,rx 14,...,rzz 11,rx 17,h 6,rzz 9,rzz 7,rx 19,h 1,rzz 16,rx 8,rzz 18
sum,0.759477,0.753367,0.739051,0.736973,0.736944,0.736809,0.735829,0.735777,0.734589,0.733064,...,0.722052,0.721491,0.721111,0.720381,0.720177,0.717193,0.716108,0.715487,0.714224,0.708238

DSTAR SCORES

,rzz 4,rzz 2,rzz 7,rzz 16,rzz 11,x 15,h 0,h 3,h 1,h 10,...,rx 8,rzz 9,rx 12,rx 17,rx 20,rx 14,rx 22,rx 25,rx 19,rx 24
sum,1.684798,1.628998,1.604258,1.539402,1.41024,1.097684,0.827444,0.793879,0.73894,0.701733,...,0.467412,0.459524,0.454735,0.367488,0.325937,0.195479,0.157051,0.149261,0.139459,0.130001

ERROR GATE LOCATION:
15
Now evolving the following mutant:  AddGate_ccx_inGap_19_.qasm

100%|██████████| 10/10 [04:08<00:00, 24.84s/it]
100%|██████████| 10/10 [03:40<00:00, 22.04s/it]

,rx 25,rx 24,rzz 23,rx 22,rzz 21,rx 20,rx 19,ccx 18,rzz 17,rx 16,...,rx 8,rzz 7,h 6,rx 5,rzz 4,h 3,rzz 2,h 1,h 0,pass/fail
0,0.123391,0.106979,0.274113,0.132636,0.256677,0.194827,0.140987,0.487569,0.217540,0.158500,...,0.225058,0.354974,0.239793,0.168305,0.365447,0.238204,0.363195,0.245692,0.218818,fail
1,0.101621,0.143301,0.277209,0.098268,0.206486,0.162774,0.126910,0.484429,0.205597,0.161853,...,0.211233,0.341124,0.233937,0.220050,0.365174,0.229932,0.376510,0.240015,0.261407,fail
2,0.094657,0.099835,0.230543,0.133332,0.237185,0.150979,0.166933,0.480488,0.216332,0.141854,...,0.221154,0.336527,0.215948,0.166620,0.346419,0.229861,0.311802,0.244505,0.212132,fail
3,0.117018,0.124307,0.264981,0.130812,0.252498,0.182986,0.130702,0.417950,0.195659,0.152146,...,0.212495,0.317159,0.223836,0.182489,0.327862,0.232080,0.347064,0.233307,0.224026,fail
4,0.121700,0.115158,0.266444,0.146056,0.262718,0.184612,0.140810,0.552222,0.225865,0.165149,...,0.225281,0.374655,0.249434,0.212557,0.400585,0.262527,0.364827,0.254809,0.260788,fail
5,0.154789,0.139570,0.324142,0.121788,0.267143,0.221794,0.120237,0.528501,0.221236,0.174875,...,0.218957,0.369917,0.255618,0.189060,0.381594,0.252038,0.367056,0.237568,0.238213,fail
6,0.114018,0.153004,0.302425,0.154320,0.260361,0.177945,0.157415,0.467788,0.221962,0.174203,...,0.234812,0.347841,0.243354,0.193272,0.351456,0.242149,0.373376,0.260467,0.240268,fail
7,0.132592,0.137541,0.305172,0.110216,0.236194,0.198697,0.131196,0.529925,0.213552,0.175567,...,0.226322,0.367933,0.256215,0.188310,0.386681,0.240153,0.376856,0.250483,0.237988,fail
8,0.121187,0.169180,0.326476,0.169732,0.283806,0.185181,0.159836,0.508328,0.239530,0.191939,...,0.251848,0.381118,0.269969,0.222710,0.349271,0.266545,0.373473,0.276767,0.267052,fail
9,0.143746,0.105784,0.276966,0.119736,0.250429,0.200587,0.103189,0.443704,0.182488,0.147367,...,0.183956,0.314406,0.218381,0.177367,0.333859,0.229665,0.299340,0.204361,0.216460,fail
10,0.095250,0.076532,0.191020,0.102592,0.194884,0.136311,0.097859,0.413992,0.157551,0.113374,...,0.158687,0.271538,0.169813,0.150844,0.297443,0.192053,0.286432,0.179986,0.188031,pass
11,0.116628,0.148514,0.288372,0.112512,0.242593,0.179380,0.152875,0.426043,0.211113,0.165170,...,0.231551,0.335085,0.236320,0.169677,0.321488,0.225518,0.346243,0.248402,0.214290,pass
12,0.118989,0.133339,0.282548,0.119476,0.235454,0.179974,0.130757,0.519993,0.214717,0.162394,...,0.209938,0.351836,0.236724,0.201233,0.351779,0.232276,0.336421,0.237910,0.243813,pass
13,0.126058,0.111990,0.259572,0.094743,0.210785,0.180905,0.098935,0.433340,0.177703,0.148365,...,0.180156,0.308052,0.218768,0.166665,0.296340,0.197415,0.268603,0.201299,0.202382,pass
14,0.107837,0.110637,0.249405,0.086032,0.180513,0.156347,0.130445,0.402363,0.176230,0.136680,...,0.183634,0.286818,0.197257,0.151578,0.279597,0.181880,0.273329,0.207568,0.186496,pass
15,0.079649,0.082297,0.168421,0.058843,0.134727,0.107834,0.070250,0.293676,0.116430,0.099981,...,0.125716,0.209072,0.143463,0.121528,0.208436,0.135712,0.218117,0.142918,0.147002,pass
16,0.127220,0.148107,0.291092,0.108960,0.214440,0.173431,0.133510,0.442911,0.198724,0.167945,...,0.220307,0.331252,0.237880,0.205928,0.329016,0.222220,0.350579,0.244065,0.243642,pass
17,0.070815,0.060419,0.149429,0.071146,0.149220,0.110500,0.070327,0.312643,0.118372,0.090758,...,0.120469,0.205096,0.137125,0.119300,0.212521,0.140191,0.209253,0.136934,0.144496,pass
18,0.111776,0.112306,0.264392,0.097263,0.202682,0.172232,0.119417,0.515947,0.206903,0.155769,...,0.212355,0.350242,0.235684,0.187997,0.355057,0.220157,0.379447,0.236387,0.232331,pass
19,0.036859,0.034079,0.081743,0.062262,0.106100,0.061820,0.045881,0.245698,0.086666,0.061771,...,0.089701,0.155366,0.098028,0.104153,0.183795,0.112195,0.176742,0.104713,0.123609,pass

[[1.26387219 1.30675421 1.14614312 1.28887816 1.12912633 1.19219436
  1.21122571 1.12677635 1.11942227 1.16790241 1.06516385 1.29968015
  1.14238442 1.13005799 1.08957925 1.15396417 1.11472808 1.13901037
  1.08715255 1.12184004 1.1595015  1.11016235 1.09999048 1.06052085
  1.13059541 1.1234109 ]]
BARINEL SCORES

,rx 22,rzz 21,rx 12,rx 19,h 3,rzz 13,rzz 17,rzz 23,rx 8,rx 20,...,h 1,h 6,rzz 9,rzz 7,rzz 2,rx 25,h 0,ccx 18,rx 5,rx 14
sum,0.590344,0.573217,0.571165,0.567524,0.565791,0.564017,0.562478,0.561334,0.56068,0.560505,...,0.557859,0.557373,0.555628,0.55557,0.55535,0.552721,0.552409,0.550199,0.548839,0.53872

custom SCORES

,rx 22,rx 24,rx 19,rzz 21,rx 12,rx 20,rx 25,rzz 13,rzz 23,h 3,...,rx 14,h 6,rzz 11,rzz 9,rzz 15,rx 5,h 0,rzz 7,ccx 18,rzz 2
sum,0.780565,0.742629,0.739373,0.735026,0.732527,0.727563,0.727363,0.725098,0.722177,0.721383,...,0.713761,0.713694,0.712154,0.710471,0.708741,0.707934,0.707555,0.706568,0.705187,0.70259

DSTAR SCORES

,ccx 18,rzz 4,rzz 15,rzz 2,rzz 11,rzz 7,rzz 9,rzz 23,rzz 21,h 1,...,rzz 13,rx 5,rx 20,rx 12,rx 16,rx 19,rx 22,rx 24,rx 25,rx 14
sum,1.714823,1.01439,0.993102,0.983044,0.969793,0.959799,0.848549,0.663651,0.532175,0.501883,...,0.383091,0.318618,0.302042,0.282859,0.238974,0.171894,0.158901,0.152125,0.136468,0.103413

ERROR GATE LOCATION:
18
Now evolving the following mutant:  AddGate_ry_inGap_20_.qasm

100%|██████████| 10/10 [01:31<00:00,  9.14s/it]
100%|██████████| 10/10 [01:37<00:00,  9.78s/it]

,rx 25,rx 24,rzz 23,rx 22,rzz 21,rx 20,ry 19,rx 18,rzz 17,rx 16,...,rx 8,rzz 7,h 6,rx 5,rzz 4,h 3,rzz 2,h 1,h 0,pass/fail
0,0.116958,0.093196,0.251480,0.065135,0.182761,0.177423,0.146336,0.080595,0.164354,0.159357,...,0.145265,0.315162,0.223450,0.167805,0.316139,0.195926,0.277742,0.192988,0.199333,fail
1,0.105247,0.137579,0.294226,0.132463,0.232282,0.170522,0.138560,0.124475,0.258425,0.224034,...,0.229841,0.453710,0.308729,0.249277,0.489865,0.305605,0.462679,0.296099,0.302928,fail
2,0.133808,0.141813,0.314555,0.090731,0.238865,0.208610,0.170989,0.146717,0.277616,0.229555,...,0.245876,0.466173,0.322127,0.267231,0.462023,0.280257,0.408140,0.317644,0.313011,fail
3,0.118454,0.106565,0.272811,0.138510,0.268350,0.189486,0.153392,0.106236,0.231160,0.192549,...,0.206543,0.448323,0.272000,0.223442,0.442064,0.305297,0.433604,0.266444,0.276723,fail
4,0.133680,0.121687,0.267029,0.128718,0.258390,0.188044,0.162030,0.133457,0.244554,0.196784,...,0.239812,0.401017,0.277587,0.246527,0.471105,0.310973,0.420835,0.297838,0.297764,fail
5,0.118194,0.122380,0.276810,0.106385,0.212024,0.177126,0.146864,0.094210,0.233165,0.206147,...,0.180446,0.451042,0.280127,0.236864,0.462559,0.262894,0.373648,0.249524,0.278340,fail
6,0.100843,0.129646,0.276653,0.141154,0.250639,0.166114,0.135037,0.107993,0.241199,0.216398,...,0.213430,0.467182,0.298057,0.251873,0.486744,0.320469,0.434456,0.281888,0.302382,fail
7,0.137614,0.119118,0.285027,0.103823,0.222069,0.193792,0.167054,0.118186,0.235075,0.199185,...,0.215145,0.424794,0.280803,0.269489,0.482931,0.277816,0.389934,0.282972,0.311075,fail
8,0.105503,0.119122,0.256756,0.124424,0.241550,0.168172,0.137883,0.133806,0.234687,0.192130,...,0.230996,0.391703,0.273585,0.259758,0.477344,0.301588,0.414056,0.291820,0.307808,fail
9,0.130172,0.115898,0.275318,0.112765,0.242578,0.188510,0.159361,0.109212,0.229332,0.190822,...,0.200569,0.403256,0.263698,0.149792,0.379067,0.255449,0.369638,0.246854,0.199465,fail
10,0.120237,0.112800,0.261119,0.096424,0.228430,0.187553,0.150655,0.123121,0.229737,0.187511,...,0.207757,0.370145,0.262940,0.184217,0.387897,0.251821,0.328115,0.257549,0.229496,pass
11,0.124829,0.119910,0.282693,0.192806,0.307647,0.190124,0.158432,0.159584,0.293503,0.216981,...,0.288582,0.528906,0.314147,0.257255,0.504230,0.386364,0.487599,0.350644,0.322817,pass
12,0.087841,0.112783,0.229808,0.119634,0.224346,0.142985,0.115613,0.090405,0.208213,0.183865,...,0.175812,0.384874,0.248774,0.167740,0.395139,0.266408,0.320479,0.221197,0.211129,pass
13,0.126022,0.124657,0.293478,0.113775,0.240032,0.200073,0.160865,0.116897,0.237428,0.211441,...,0.225530,0.448256,0.297994,0.242765,0.435570,0.288374,0.459435,0.290770,0.292431,pass
14,0.121257,0.112290,0.275147,0.123474,0.242391,0.189747,0.154329,0.143974,0.269768,0.202308,...,0.272950,0.522191,0.295960,0.302785,0.485386,0.311739,0.529832,0.347041,0.354536,pass
15,0.150658,0.122701,0.292373,0.154000,0.278121,0.207697,0.180505,0.110953,0.233112,0.212603,...,0.229809,0.452789,0.295150,0.243451,0.499214,0.338246,0.444515,0.289783,0.297318,pass
16,0.092332,0.063626,0.178299,0.075277,0.181153,0.144850,0.115693,0.113225,0.202400,0.124770,...,0.196018,0.371174,0.188872,0.169094,0.343410,0.204146,0.343362,0.241372,0.209810,pass
17,0.147020,0.166603,0.351506,0.168265,0.311685,0.223211,0.184770,0.122260,0.274465,0.270462,...,0.237094,0.501138,0.366000,0.302713,0.539330,0.376736,0.431467,0.312970,0.353787,pass
18,0.059247,0.119620,0.207135,0.092625,0.159070,0.103105,0.080252,0.070054,0.187024,0.184409,...,0.144383,0.334527,0.238777,0.187010,0.400035,0.216597,0.332932,0.198023,0.226435,pass
19,0.089709,0.085538,0.214205,0.075234,0.167110,0.142776,0.115956,0.067192,0.155826,0.149133,...,0.141696,0.321992,0.208125,0.185575,0.348785,0.202136,0.321321,0.188662,0.217736,pass

[[1.14633443 1.17492019 1.13530583 1.23374949 1.14215407 1.14131982
  1.12677666 1.27040628 1.18156359 1.1437931  1.15209525 1.22085422
  1.1615562  1.16948068 1.18045705 1.11280264 1.1517192  1.16643725
  1.10644714 1.15038509 1.16055869 1.09593353 1.13791998 1.16112881
  1.16606227 1.12237531]]
BARINEL SCORES

,rx 25,rzz 23,rx 14,ry 19,rx 24,rx 20,rzz 15,h 10,rx 5,rx 18,...,rzz 9,rzz 13,h 1,rzz 21,rzz 7,rzz 2,rx 8,h 3,rx 12,rx 22
sum,0.517529,0.51726,0.517121,0.517112,0.514159,0.513438,0.511369,0.510822,0.508703,0.508189,...,0.502862,0.502812,0.502403,0.501015,0.499194,0.499103,0.498615,0.497677,0.490658,0.485692

custom SCORES

,rx 14,rx 18,rx 25,rx 24,rzz 23,ry 19,rx 20,rzz 15,rzz 11,rx 5,...,rzz 13,rzz 9,rzz 4,rzz 21,rx 8,rzz 2,h 3,rzz 7,rx 22,rx 12
sum,0.674953,0.669591,0.665844,0.665183,0.664072,0.66278,0.659938,0.658655,0.657979,0.656298,...,0.648823,0.647651,0.646454,0.644075,0.644016,0.643983,0.639256,0.637277,0.635498,0.634112

DSTAR SCORES

,rzz 4,rzz 15,rzz 11,rzz 7,rzz 2,h 3,h 6,h 0,rzz 23,h 10,...,rx 12,rx 16,rzz 9,rx 20,ry 19,rx 14,rx 24,rx 25,rx 18,rx 22
sum,1.393367,1.291049,1.26838,1.252342,1.134225,0.617587,0.616582,0.611661,0.609942,0.602355,...,0.354125,0.337246,0.326854,0.284761,0.2017,0.144914,0.130771,0.129608,0.119968,0.116753

ERROR GATE LOCATION:
19
Now evolving the following mutant:  AddGate_h_inGap_13_.qasm

100%|██████████| 10/10 [02:12<00:00, 13.30s/it]
100%|██████████| 10/10 [02:05<00:00, 12.57s/it]

,rx 25,rx 24,rzz 23,rx 22,rzz 21,rx 20,rx 19,rzz 18,rx 17,rzz 16,...,rx 8,rzz 7,h 6,rx 5,rzz 4,h 3,rzz 2,h 1,h 0,pass/fail
0,0.147466,0.128439,0.300784,0.149464,0.294428,0.215454,0.160547,0.286886,0.217063,0.439666,...,0.284935,0.481590,0.315422,0.275170,0.522043,0.363466,0.454627,0.341954,0.331027,fail
1,0.126986,0.080053,0.230673,0.128960,0.266643,0.187169,0.100366,0.195723,0.152054,0.369787,...,0.195401,0.401366,0.226740,0.228833,0.448207,0.307529,0.362491,0.242626,0.272228,fail
2,0.127477,0.116035,0.278546,0.121049,0.236050,0.184357,0.128989,0.230022,0.188963,0.420948,...,0.213756,0.371429,0.271324,0.202939,0.418987,0.282538,0.333901,0.259322,0.244565,fail
3,0.098190,0.080282,0.207510,0.124555,0.231197,0.157239,0.098294,0.182637,0.143567,0.373306,...,0.196632,0.372174,0.217160,0.271918,0.484653,0.302668,0.448064,0.251281,0.314517,fail
4,0.115823,0.097061,0.250174,0.123175,0.247700,0.178483,0.119016,0.224942,0.174723,0.429691,...,0.227807,0.426080,0.258153,0.264287,0.486726,0.302459,0.477133,0.284669,0.314470,fail
5,0.115892,0.146058,0.299697,0.149933,0.267938,0.181007,0.123454,0.284206,0.239176,0.480910,...,0.248752,0.540590,0.332302,0.298376,0.515753,0.345588,0.507750,0.318205,0.349734,fail
6,0.122510,0.122520,0.275639,0.136661,0.262630,0.182539,0.105273,0.244767,0.208959,0.427435,...,0.210640,0.486026,0.291125,0.299812,0.550330,0.332922,0.408836,0.279220,0.342907,fail
7,0.088141,0.137645,0.255446,0.163892,0.263926,0.146727,0.107020,0.225120,0.213519,0.392706,...,0.209947,0.378157,0.292957,0.261795,0.444972,0.346409,0.379306,0.261523,0.306557,fail
8,0.097942,0.127420,0.249426,0.097011,0.189391,0.148223,0.150530,0.261844,0.196414,0.376812,...,0.248308,0.380124,0.278022,0.260125,0.493411,0.268135,0.436297,0.305175,0.306719,fail
9,0.126206,0.092671,0.252344,0.118832,0.253081,0.193811,0.150715,0.253178,0.171062,0.431553,...,0.254975,0.459259,0.261634,0.258805,0.556857,0.316901,0.445130,0.312632,0.312376,fail
10,0.121725,0.106672,0.262166,0.100822,0.219150,0.186577,0.127818,0.215316,0.179066,0.401903,...,0.223804,0.339714,0.260548,0.198397,0.369782,0.260801,0.356904,0.260398,0.240101,pass
11,0.107599,0.093214,0.231447,0.120083,0.228732,0.167957,0.104133,0.189953,0.165552,0.383677,...,0.208077,0.376930,0.245337,0.296388,0.505402,0.313392,0.423789,0.265088,0.337269,pass
12,0.132197,0.131776,0.303299,0.096133,0.211983,0.202972,0.184065,0.300086,0.223170,0.471776,...,0.317355,0.482055,0.329266,0.325256,0.503044,0.299839,0.505093,0.382109,0.373173,pass
13,0.095685,0.102622,0.223491,0.079583,0.175523,0.145082,0.107327,0.219556,0.171508,0.354158,...,0.204377,0.413852,0.243641,0.218305,0.421756,0.232970,0.417325,0.255424,0.259446,pass
14,0.062734,0.091228,0.186706,0.072967,0.144327,0.108671,0.090662,0.173594,0.145854,0.303358,...,0.152803,0.272261,0.203522,0.145257,0.337855,0.191335,0.248589,0.188217,0.178457,pass
15,0.110488,0.106081,0.264573,0.115681,0.235415,0.181081,0.143218,0.264602,0.194449,0.469136,...,0.253601,0.480891,0.284413,0.187495,0.453290,0.288262,0.399450,0.298978,0.242870,pass
16,0.084870,0.156601,0.272878,0.120647,0.214016,0.143328,0.140055,0.275720,0.234216,0.394482,...,0.246855,0.413585,0.319532,0.247561,0.464581,0.300851,0.395011,0.303995,0.294979,pass
17,0.102077,0.067556,0.199945,0.130312,0.241359,0.157038,0.111215,0.196624,0.135555,0.365009,...,0.202894,0.369906,0.206906,0.179822,0.428344,0.288863,0.374126,0.241872,0.231924,pass
18,0.183406,0.137466,0.342105,0.120765,0.290467,0.257850,0.177203,0.307596,0.233420,0.472942,...,0.315753,0.518908,0.342151,0.306420,0.500507,0.342096,0.488664,0.375975,0.357239,pass
19,0.119508,0.119401,0.285910,0.118532,0.248910,0.195106,0.165872,0.281717,0.204982,0.493588,...,0.286283,0.464409,0.306459,0.299296,0.466106,0.323831,0.449997,0.344174,0.347241,pass

[[1.26403312 1.29462606 1.15675467 1.24771709 1.17162765 1.21381861
  1.29035576 1.20069981 1.25518759 1.16082907 1.21406114 1.1492199
  1.15800551 1.14493145 1.15719442 1.19383601 1.13747903 1.24363066
  1.25812368 1.21064149 1.14342048 1.13137683 1.14708214 1.19371246
  1.19706461 1.12996165]]
BARINEL SCORES

,rx 22,rzz 14,rzz 21,h 12,rx 13,rx 15,h 3,rzz 4,rx 5,h 0,...,rx 20,rx 24,rzz 23,rx 17,rzz 16,h 6,rzz 18,h 1,rx 8,rx 19
sum,0.549812,0.538657,0.532089,0.531367,0.531149,0.530549,0.527149,0.525141,0.521672,0.519504,...,0.504168,0.503473,0.502679,0.502337,0.501986,0.500279,0.496319,0.494836,0.487173,0.479319

custom SCORES

,rx 22,rzz 14,rx 15,rzz 21,rx 13,h 12,h 3,rzz 4,rx 25,rx 5,...,rx 17,rx 20,h 6,rzz 9,rzz 23,rzz 16,rzz 18,h 1,rx 8,rx 19
sum,0.721314,0.693416,0.691579,0.687941,0.684918,0.683462,0.67832,0.673674,0.671338,0.670795,...,0.659969,0.65716,0.651694,0.650906,0.648048,0.647666,0.645302,0.642924,0.638639,0.633942

DSTAR SCORES

,rzz 4,rzz 11,rzz 7,rzz 2,rzz 16,h 12,h 3,h 0,rzz 14,h 1,...,rx 13,rx 8,rzz 9,rx 17,rx 20,rx 15,rx 22,rx 19,rx 25,rx 24
sum,1.676427,1.459103,1.306381,1.286908,1.216362,0.818223,0.781805,0.744762,0.688976,0.631779,...,0.44007,0.422935,0.409812,0.305434,0.26824,0.183823,0.155782,0.136373,0.122392,0.114536

ERROR GATE LOCATION:
12
Now evolving the following mutant:  AddGate_x_inGap_27_.qasm

100%|██████████| 10/10 [01:37<00:00,  9.75s/it]
100%|██████████| 10/10 [01:35<00:00,  9.51s/it]

,rx 25,rx 24,rzz 23,rx 22,rzz 21,rx 20,x 19,rx 18,rzz 17,rx 16,...,rx 8,rzz 7,h 6,rx 5,rzz 4,h 3,rzz 2,h 1,h 0,pass/fail
0,0.139144,0.119966,0.290138,0.115190,0.241764,0.205921,0.509027,0.168205,0.288614,0.206451,...,0.284224,0.473636,0.301183,0.265293,0.482438,0.299890,0.449739,0.348245,0.318781,fail
1,0.085971,0.121724,0.233114,0.082037,0.178662,0.133105,0.370634,0.120086,0.252491,0.189259,...,0.211092,0.404304,0.258495,0.182839,0.330399,0.209159,0.377063,0.263107,0.224932,fail
2,0.090701,0.159067,0.288248,0.080723,0.176764,0.150389,0.453458,0.144271,0.301388,0.246241,...,0.252517,0.505872,0.334602,0.262289,0.436980,0.243575,0.451201,0.329372,0.306372,fail
3,0.110878,0.126598,0.254613,0.126437,0.236573,0.165875,0.397395,0.131108,0.246296,0.200319,...,0.238505,0.407154,0.281089,0.266832,0.407376,0.293154,0.441989,0.301235,0.313207,fail
4,0.115487,0.117893,0.258206,0.153271,0.268676,0.174099,0.454408,0.148600,0.271531,0.200463,...,0.269069,0.469312,0.290420,0.262016,0.418842,0.328263,0.470019,0.331214,0.315139,fail
5,0.118069,0.113777,0.265951,0.132368,0.246582,0.180834,0.392539,0.129176,0.248471,0.196815,...,0.226417,0.446603,0.278903,0.223867,0.443848,0.296878,0.392003,0.288424,0.274218,fail
6,0.099381,0.104553,0.245118,0.142553,0.239607,0.159271,0.437852,0.142425,0.248401,0.186629,...,0.241692,0.429218,0.272235,0.231589,0.457269,0.306995,0.391828,0.300711,0.283802,fail
7,0.116499,0.118985,0.284306,0.103233,0.208911,0.180849,0.393969,0.129871,0.256618,0.208106,...,0.230835,0.452869,0.292649,0.210888,0.430957,0.265344,0.386102,0.290041,0.258753,fail
8,0.088517,0.100654,0.228199,0.147105,0.266380,0.156922,0.344059,0.111785,0.214844,0.175692,...,0.206064,0.409031,0.252452,0.228521,0.409958,0.312295,0.389708,0.264169,0.275919,fail
9,0.101040,0.123346,0.259351,0.089175,0.215406,0.163947,0.361817,0.118201,0.255164,0.200947,...,0.214097,0.454087,0.275177,0.189145,0.439165,0.248484,0.389276,0.270080,0.235548,fail
10,0.097052,0.052032,0.172189,0.110431,0.205189,0.142423,0.272259,0.090143,0.155835,0.112793,...,0.166840,0.315620,0.173028,0.163593,0.328928,0.236241,0.266433,0.204282,0.201590,pass
11,0.128976,0.134499,0.291624,0.164363,0.310469,0.197348,0.355461,0.116648,0.240249,0.217913,...,0.222668,0.442288,0.303697,0.267157,0.491140,0.359900,0.403606,0.290064,0.317378,pass
12,0.156276,0.097431,0.284745,0.104120,0.260053,0.227198,0.414126,0.138454,0.248394,0.182134,...,0.249356,0.447874,0.268424,0.187067,0.408453,0.281693,0.410442,0.297897,0.239730,pass
13,0.149793,0.098482,0.290216,0.061867,0.215696,0.228209,0.375000,0.126425,0.215529,0.176155,...,0.220314,0.394006,0.261610,0.247429,0.377560,0.236104,0.399995,0.278332,0.283720,pass
14,0.108658,0.108657,0.234004,0.104436,0.206553,0.155012,0.460892,0.152148,0.250892,0.176211,...,0.251492,0.375012,0.255964,0.219500,0.342842,0.254097,0.339504,0.301622,0.261864,pass
15,0.148453,0.152050,0.334483,0.134816,0.268691,0.218886,0.373987,0.127109,0.247062,0.240089,...,0.252977,0.449219,0.334753,0.342913,0.475151,0.336187,0.514089,0.328807,0.387148,pass
16,0.102595,0.116142,0.234357,0.087504,0.205115,0.152776,0.184536,0.061707,0.161541,0.173994,...,0.130760,0.303725,0.229885,0.188639,0.409229,0.238408,0.296725,0.181450,0.222157,pass
17,0.113824,0.134338,0.290708,0.100682,0.223889,0.184183,0.335740,0.109982,0.247383,0.223229,...,0.218839,0.480552,0.308037,0.316194,0.446212,0.282619,0.438533,0.297467,0.354674,pass
18,0.107629,0.096635,0.223864,0.094953,0.190182,0.155083,0.312512,0.105830,0.186573,0.157927,...,0.194241,0.308126,0.224950,0.190524,0.355022,0.237149,0.344978,0.236829,0.230284,pass
19,0.113807,0.067812,0.215632,0.114894,0.220259,0.173678,0.352376,0.112961,0.197017,0.139485,...,0.210577,0.403018,0.215796,0.237211,0.453065,0.269292,0.453368,0.269755,0.287345,pass

[[1.30567229 1.31834364 1.11281552 1.30767369 1.17875105 1.23216689
  1.23695726 1.25178123 1.16644433 1.22451753 1.11754271 1.1792967
  1.12584682 1.19580146 1.13758521 1.17094452 1.17560216 1.19697957
  1.1362575  1.17933545 1.14851541 1.13321944 1.17068027 1.13560496
  1.16602433 1.1357974 ]]
BARINEL SCORES

,rzz 17,x 19,rx 18,rx 24,rzz 7,rx 8,rx 16,h 1,h 6,rx 22,...,h 3,rzz 23,h 0,rzz 11,rzz 21,rx 5,rx 14,h 10,rx 20,rx 25
sum,0.545766,0.544906,0.540706,0.532783,0.531813,0.528541,0.527683,0.526449,0.524113,0.520894,...,0.506534,0.50342,0.501858,0.498222,0.497081,0.496056,0.492609,0.489045,0.476671,0.464808

custom SCORES

,x 19,rx 18,rx 24,rzz 17,rx 22,rx 16,rx 8,rzz 7,h 1,h 6,...,rzz 13,h 0,rzz 21,rzz 23,rzz 11,rx 5,rx 14,h 10,rx 20,rx 25
sum,0.713413,0.709918,0.708381,0.704918,0.691183,0.689222,0.686705,0.682882,0.679912,0.678639,...,0.650516,0.64436,0.643564,0.643473,0.639915,0.638488,0.637842,0.632206,0.623505,0.616529

DSTAR SCORES

,rzz 7,rzz 4,x 19,rzz 2,rzz 15,rzz 11,h 1,h 6,h 3,h 0,...,rzz 21,rzz 9,rx 12,rx 16,rx 20,rx 18,rx 14,rx 24,rx 22,rx 25
sum,1.423985,1.286523,1.260301,1.235299,1.210966,1.200025,0.703091,0.640079,0.617563,0.616102,...,0.422174,0.389659,0.363595,0.342697,0.235995,0.162063,0.142222,0.13165,0.124011,0.101157

ERROR GATE LOCATION:
19
Now evolving the following mutant:  AddGate_sx_inGap_28_.qasm

100%|██████████| 10/10 [01:40<00:00, 10.09s/it]
100%|██████████| 10/10 [01:38<00:00,  9.84s/it]

,rx 25,rx 24,rzz 23,sxdg 22,rx 21,rzz 20,rx 19,rx 18,rzz 17,rx 16,...,rx 8,rzz 7,h 6,rx 5,rzz 4,h 3,rzz 2,h 1,h 0,pass/fail
0,0.126331,0.103352,0.254575,0.475166,0.004428,0.507574,0.173989,0.109456,0.198100,0.176084,...,0.191635,0.337056,0.245602,0.221778,0.380010,0.260512,0.398265,0.248200,0.276736,fail
1,0.109049,0.116950,0.256187,0.548231,0.005663,0.546032,0.166587,0.172733,0.273278,0.206124,...,0.282276,0.434533,0.290225,0.229286,0.384391,0.285114,0.458141,0.342911,0.294797,fail
2,0.113089,0.135380,0.289090,0.604170,0.007348,0.594753,0.187575,0.126573,0.250241,0.234329,...,0.220151,0.419695,0.306396,0.238007,0.423742,0.297815,0.456055,0.286379,0.309037,fail
3,0.100491,0.121597,0.245447,0.419673,0.004849,0.434869,0.154703,0.156525,0.267238,0.200380,...,0.254236,0.403334,0.273007,0.238103,0.420935,0.244919,0.433829,0.316244,0.300219,fail
4,0.088537,0.089685,0.205225,0.345613,0.003045,0.387262,0.144829,0.095524,0.198528,0.160030,...,0.172588,0.368907,0.217732,0.186637,0.327431,0.194141,0.390399,0.227953,0.238109,fail
5,0.085213,0.070292,0.175823,0.554249,0.004350,0.581087,0.150762,0.116785,0.191506,0.142433,...,0.202672,0.353504,0.204832,0.210557,0.376683,0.270553,0.401147,0.253759,0.270428,fail
6,0.104423,0.097922,0.223333,0.589407,0.005880,0.612119,0.174471,0.120467,0.218328,0.180816,...,0.216982,0.406745,0.247946,0.213387,0.410114,0.284314,0.473903,0.272525,0.284318,fail
7,0.150799,0.130078,0.300306,0.553840,0.007623,0.547790,0.195882,0.124734,0.248318,0.224365,...,0.226614,0.432397,0.296973,0.261405,0.435861,0.297323,0.430824,0.296503,0.324415,fail
8,0.117403,0.081056,0.228645,0.493288,0.004833,0.502266,0.167750,0.132321,0.214509,0.165861,...,0.229319,0.405127,0.236914,0.259112,0.430685,0.274164,0.452169,0.293480,0.320712,fail
9,0.167961,0.131886,0.336496,0.636468,0.007818,0.644687,0.231030,0.166834,0.301329,0.249311,...,0.282576,0.535271,0.336988,0.272552,0.493978,0.341440,0.523514,0.357478,0.350327,fail
10,0.072653,0.106528,0.228485,0.429104,0.002969,0.452326,0.140605,0.165520,0.272425,0.195088,...,0.260345,0.420785,0.274694,0.239310,0.396664,0.245933,0.427163,0.323449,0.296367,pass
11,0.116966,0.118470,0.268782,0.565170,0.006472,0.574078,0.183265,0.127334,0.224976,0.212539,...,0.224725,0.397872,0.285028,0.244889,0.419651,0.297581,0.401129,0.290907,0.307214,pass
12,0.134597,0.106746,0.280509,0.562846,0.005404,0.584576,0.199783,0.152011,0.257568,0.212343,...,0.255460,0.480893,0.293362,0.265652,0.462808,0.313313,0.452330,0.325533,0.334687,pass
13,0.107727,0.110463,0.247078,0.459320,0.005320,0.459113,0.153327,0.119292,0.230786,0.198805,...,0.222141,0.412403,0.266235,0.240619,0.430690,0.258720,0.416859,0.289016,0.302241,pass
14,0.113177,0.112804,0.248498,0.428315,0.005795,0.436658,0.161740,0.141083,0.249885,0.192423,...,0.224769,0.381773,0.257905,0.197333,0.340517,0.239947,0.376900,0.278607,0.248123,pass
15,0.076653,0.110742,0.211806,0.290958,0.004344,0.297021,0.126121,0.128753,0.244611,0.187381,...,0.214736,0.378567,0.246075,0.173208,0.322476,0.181925,0.389782,0.265368,0.224665,pass
16,0.102944,0.084224,0.203858,0.426259,0.002768,0.500182,0.168773,0.140556,0.234756,0.155912,...,0.237939,0.398286,0.225040,0.227959,0.402579,0.245425,0.444102,0.292939,0.286394,pass
17,0.051258,0.070069,0.144380,0.259545,0.003574,0.262695,0.095655,0.044215,0.115923,0.125125,...,0.087201,0.221487,0.155386,0.119181,0.208942,0.138928,0.190375,0.122787,0.149547,pass
18,0.053558,0.096602,0.180419,0.318400,0.002848,0.347033,0.110615,0.094298,0.196614,0.162711,...,0.161701,0.339461,0.216513,0.171616,0.294508,0.178999,0.308841,0.214807,0.212996,pass
19,0.132953,0.115699,0.280943,0.593403,0.007652,0.577024,0.186738,0.156090,0.264895,0.211394,...,0.258773,0.433853,0.288670,0.241789,0.440926,0.300535,0.465842,0.324904,0.315156,pass

[[1.44383914 1.25561219 1.33788894 1.21926322 1.40021177 1.20312486
  1.32200174 1.30665157 1.2760745  1.28528361 1.20358045 1.14991224
  1.20019628 1.217011   1.26328644 1.27018784 1.25429675 1.23988717
  1.30663331 1.26848498 1.16933808 1.20959431 1.24146835 1.18489085
  1.23462741 1.17991034]]
BARINEL SCORES

,rx 25,sxdg 22,rzz 20,rx 21,rx 14,rx 12,h 3,rx 19,rzz 2,h 10,...,rzz 23,rzz 15,h 1,rx 8,rzz 7,h 6,rx 16,rx 24,rx 18,rzz 17
sum,0.547232,0.546412,0.544051,0.542201,0.538318,0.536998,0.533872,0.533742,0.53286,0.531544,...,0.522908,0.519442,0.514858,0.514825,0.514518,0.514297,0.511337,0.510862,0.510189,0.507406

custom SCORES

,rx 25,rx 21,sxdg 22,rx 19,rzz 20,rx 12,h 10,h 3,rzz 23,rzz 9,...,h 0,h 6,rx 18,rx 5,rzz 15,rx 16,rx 8,h 1,rx 24,rzz 17
sum,0.744761,0.732,0.712967,0.710144,0.707691,0.700382,0.700334,0.699568,0.697806,0.697564,...,0.680939,0.677392,0.676848,0.676538,0.675739,0.67564,0.674407,0.673772,0.671223,0.669278

DSTAR SCORES

,rzz 20,sxdg 22,rzz 13,rzz 2,rzz 4,rzz 7,rzz 15,rzz 11,h 0,h 1,...,rzz 17,rx 5,rx 8,rx 16,rx 19,rx 14,rx 18,rx 25,rx 24,rx 21
sum,1.981466,1.901128,1.654856,1.407081,1.215595,1.210343,1.158824,1.097093,0.695376,0.658652,...,0.45362,0.448188,0.427573,0.317416,0.264955,0.190785,0.155074,0.123445,0.105373,0.00031

ERROR GATE LOCATION:
22
Now evolving the following mutant:  AddGate_h_inGap_11_.qasm

100%|██████████| 10/10 [01:37<00:00,  9.77s/it]
100%|██████████| 10/10 [01:42<00:00, 10.23s/it]

,rx 25,rx 24,rzz 23,rx 22,rzz 21,rx 20,rx 19,rzz 18,rx 17,rzz 16,...,rx 8,rzz 7,h 6,rx 5,rzz 4,h 3,rzz 2,h 1,h 0,pass/fail
0,0.066529,0.114112,0.229660,0.105435,0.200385,0.131274,0.113169,0.219200,0.181427,0.406317,...,0.196000,0.373849,0.253900,0.251437,0.469236,0.273338,0.402810,0.263683,0.296451,fail
1,0.109080,0.107902,0.238504,0.134969,0.252387,0.166847,0.149242,0.269865,0.186561,0.369973,...,0.254806,0.462637,0.266382,0.195368,0.461136,0.298230,0.424139,0.307830,0.251924,fail
2,0.125447,0.086857,0.246060,0.098133,0.240626,0.194966,0.073150,0.182529,0.160918,0.408788,...,0.160517,0.422877,0.231887,0.232197,0.430753,0.263589,0.427775,0.226545,0.274497,fail
3,0.098358,0.132335,0.271695,0.143820,0.268333,0.170028,0.119946,0.265434,0.221869,0.470030,...,0.229605,0.517125,0.306672,0.275994,0.528665,0.335507,0.510974,0.304619,0.332109,fail
4,0.151791,0.135189,0.324222,0.207116,0.370913,0.238386,0.169299,0.294822,0.240274,0.516268,...,0.304038,0.537628,0.350714,0.319434,0.633307,0.454153,0.554358,0.379554,0.390784,fail
5,0.116387,0.080294,0.228184,0.101462,0.230135,0.184691,0.122560,0.198426,0.142824,0.396234,...,0.209511,0.355430,0.220780,0.230098,0.399822,0.261506,0.418575,0.265087,0.275503,fail
6,0.092140,0.086599,0.203261,0.102045,0.207785,0.144422,0.098600,0.209699,0.153538,0.354232,...,0.189394,0.414613,0.220262,0.215664,0.415344,0.250075,0.419788,0.245954,0.260344,fail
7,0.148792,0.172659,0.365363,0.140569,0.291322,0.228209,0.123262,0.277255,0.270080,0.534198,...,0.232955,0.481991,0.362504,0.274661,0.534840,0.342948,0.480444,0.307886,0.329113,fail
8,0.117487,0.139878,0.296573,0.147234,0.274963,0.191199,0.175014,0.301414,0.227393,0.485531,...,0.292811,0.489550,0.327265,0.293528,0.524938,0.347745,0.499808,0.365376,0.352087,fail
9,0.156371,0.103057,0.291892,0.176550,0.349104,0.240401,0.173607,0.266499,0.188104,0.483247,...,0.297222,0.454590,0.290579,0.250296,0.497300,0.384309,0.506863,0.356925,0.316692,fail
10,0.082233,0.070587,0.167584,0.080979,0.162915,0.123685,0.112093,0.180804,0.122966,0.266732,...,0.195428,0.312679,0.187498,0.228398,0.319269,0.214055,0.353586,0.246110,0.262779,pass
11,0.167918,0.133950,0.335449,0.144363,0.314638,0.248075,0.137127,0.258874,0.223430,0.485139,...,0.247006,0.454435,0.319305,0.288374,0.580941,0.368720,0.465743,0.317242,0.344312,pass
12,0.085937,0.105090,0.222880,0.123981,0.219400,0.144958,0.141568,0.232562,0.176661,0.377413,...,0.234006,0.356418,0.255690,0.226741,0.392236,0.280964,0.374476,0.287808,0.273688,pass
13,0.089454,0.092747,0.200415,0.089995,0.191094,0.135364,0.082029,0.159690,0.146641,0.285009,...,0.152627,0.285142,0.204709,0.209199,0.321186,0.225084,0.297672,0.199484,0.238385,pass
14,0.100735,0.094840,0.226681,0.080272,0.188971,0.164322,0.118860,0.213329,0.168476,0.384753,...,0.219724,0.404794,0.247153,0.261082,0.405936,0.245478,0.428129,0.283516,0.300108,pass
15,0.057092,0.085171,0.167549,0.089021,0.170488,0.103679,0.113649,0.213747,0.145095,0.302837,...,0.199554,0.381883,0.207628,0.174279,0.398244,0.222439,0.393654,0.249356,0.220869,pass
16,0.072589,0.112585,0.228846,0.145774,0.237533,0.132353,0.117325,0.239618,0.193699,0.419046,...,0.221234,0.443071,0.271575,0.276808,0.489999,0.325427,0.450187,0.290316,0.328858,pass
17,0.139040,0.132368,0.289552,0.093560,0.199853,0.184339,0.128043,0.242979,0.206423,0.355552,...,0.230309,0.388429,0.286141,0.250372,0.407519,0.253724,0.418406,0.293160,0.292960,pass
18,0.100317,0.098528,0.231548,0.113347,0.215580,0.161942,0.136226,0.223002,0.169467,0.395363,...,0.241935,0.394618,0.252968,0.292563,0.450179,0.286203,0.480725,0.306908,0.338775,pass
19,0.061339,0.081498,0.157473,0.085310,0.148913,0.093694,0.096656,0.181611,0.129437,0.241199,...,0.156733,0.274438,0.178656,0.117959,0.238188,0.175731,0.237539,0.190646,0.152223,pass

[[1.32250446 1.48987855 1.3554987  1.52590495 1.38093726 1.27168008
  1.32802761 1.21286472 1.36889021 1.20727618 1.23977046 1.34766529
  1.46538748 1.28492716 1.29079614 1.29947861 1.2188205  1.28456297
  1.19200304 1.28050312 1.25827055 1.29369348 1.41419062 1.19331418
  1.25536445 1.26898454]]
BARINEL SCORES

,rzz 21,rx 22,rzz 12,rx 13,rx 20,rzz 16,h 11,h 10,h 3,rx 25,...,rx 17,rzz 18,rx 24,h 1,rx 8,rzz 9,h 0,rx 19,rx 5,rx 15
sum,0.567215,0.56463,0.561445,0.559439,0.558828,0.557432,0.553973,0.553315,0.55281,0.552764,...,0.539764,0.536591,0.534973,0.53155,0.530042,0.528656,0.527994,0.526839,0.521884,0.513955

custom SCORES

,rx 22,rx 13,rzz 21,h 3,rzz 12,rx 20,rx 25,rx 24,h 10,rzz 23,...,h 6,rzz 2,rx 19,rx 8,rzz 18,h 1,h 0,rzz 9,rx 5,rx 15
sum,0.780023,0.764388,0.763037,0.748255,0.741799,0.736491,0.735522,0.734234,0.73307,0.732995,...,0.712898,0.705789,0.701754,0.700261,0.699294,0.698372,0.695498,0.689741,0.686051,0.673251

DSTAR SCORES

,rzz 4,rzz 12,rzz 2,rzz 7,rzz 16,h 3,h 0,h 1,rzz 14,h 11,...,rx 13,rx 8,rzz 9,rx 17,rx 20,rx 15,rx 22,rx 19,rx 25,rx 24
sum,1.711287,1.711058,1.552576,1.485313,1.448896,0.81864,0.743619,0.721803,0.693839,0.673998,...,0.485563,0.463033,0.444492,0.333212,0.310962,0.170963,0.16678,0.155293,0.127596,0.12201

ERROR GATE LOCATION:
11
Now evolving the following mutant:  AddGate_swap_inGap_17_.qasm

100%|██████████| 10/10 [01:59<00:00, 11.91s/it]
100%|██████████| 10/10 [02:03<00:00, 12.38s/it]

,rx 25,rx 24,rzz 23,rx 22,rzz 21,rx 20,rx 19,rzz 18,rx 17,swap 16,...,rx 8,rzz 7,h 6,rx 5,rzz 4,h 3,rzz 2,h 1,h 0,pass/fail
0,0.103783,0.122315,0.266145,0.146828,0.266722,0.174791,0.144703,0.264812,0.205982,0.362478,...,0.233393,0.423297,0.262331,0.232963,0.460698,0.289240,0.456201,0.290651,0.285534,fail
1,0.121889,0.102404,0.267196,0.131863,0.264931,0.194959,0.123010,0.244716,0.185256,0.376809,...,0.193995,0.433000,0.272007,0.201068,0.375949,0.259873,0.376899,0.250430,0.243985,fail
2,0.123418,0.096382,0.240468,0.131243,0.239981,0.171802,0.100363,0.211446,0.170422,0.265769,...,0.170014,0.347872,0.235680,0.160480,0.379176,0.249395,0.330051,0.215189,0.204458,fail
3,0.145557,0.116560,0.304722,0.121197,0.272450,0.224145,0.148274,0.262494,0.202037,0.382394,...,0.229860,0.465346,0.306633,0.209558,0.479228,0.285104,0.415362,0.286873,0.262751,fail
4,0.148556,0.137208,0.324860,0.107745,0.246702,0.221571,0.105073,0.245729,0.228333,0.382031,...,0.199916,0.391551,0.298249,0.212542,0.469972,0.258329,0.446824,0.263378,0.260379,fail
5,0.091371,0.130913,0.266739,0.138594,0.256083,0.162646,0.141859,0.288815,0.220484,0.362001,...,0.216050,0.419242,0.245794,0.193043,0.439268,0.279436,0.391614,0.275576,0.243950,fail
6,0.156381,0.146376,0.338445,0.117592,0.276666,0.236150,0.164078,0.302677,0.243117,0.369938,...,0.264509,0.473489,0.323788,0.216703,0.510677,0.300188,0.488511,0.325056,0.275929,fail
7,0.099797,0.131757,0.264966,0.121867,0.242043,0.164994,0.115011,0.264129,0.215224,0.342850,...,0.190926,0.397253,0.238029,0.211929,0.442175,0.257878,0.393295,0.244961,0.256584,fail
8,0.146174,0.115816,0.289751,0.092386,0.230027,0.209705,0.124746,0.241108,0.193615,0.317304,...,0.199709,0.385815,0.277252,0.188470,0.367044,0.221486,0.342763,0.250087,0.227817,fail
9,0.128225,0.142353,0.307542,0.096395,0.231819,0.197002,0.136625,0.282562,0.232412,0.358345,...,0.220640,0.401168,0.273049,0.192655,0.430256,0.247996,0.396794,0.270966,0.238529,fail
10,0.094584,0.104057,0.236741,0.072757,0.195716,0.164249,0.127274,0.244869,0.177826,0.338426,...,0.202375,0.371470,0.235846,0.197093,0.360386,0.197421,0.402505,0.256881,0.236240,pass
11,0.090256,0.141141,0.253110,0.115809,0.210126,0.144815,0.131155,0.242733,0.210812,0.238973,...,0.197343,0.314952,0.213431,0.182222,0.299195,0.237045,0.317106,0.243712,0.220834,pass
12,0.104699,0.085330,0.222518,0.106097,0.211176,0.159181,0.094523,0.177634,0.152655,0.281543,...,0.153641,0.336569,0.225129,0.188890,0.361628,0.226299,0.284698,0.204487,0.222187,pass
13,0.107617,0.130156,0.271368,0.087461,0.194469,0.166851,0.107757,0.241472,0.209691,0.312314,...,0.185641,0.333692,0.232971,0.176062,0.392805,0.218742,0.364404,0.234227,0.217692,pass
14,0.098617,0.133010,0.264036,0.093854,0.171392,0.143746,0.114795,0.245968,0.208997,0.295612,...,0.184191,0.342360,0.214412,0.177069,0.345456,0.212860,0.357013,0.232135,0.216260,pass
15,0.160672,0.126119,0.315815,0.134872,0.263076,0.223366,0.134391,0.254675,0.214044,0.338163,...,0.229869,0.433091,0.306077,0.239794,0.386904,0.283146,0.459376,0.286218,0.284901,pass
16,0.067036,0.078583,0.169344,0.060239,0.129701,0.108158,0.079945,0.162452,0.133473,0.222314,...,0.124014,0.251031,0.155108,0.151224,0.286888,0.155680,0.241475,0.162974,0.177322,pass
17,0.058677,0.083332,0.165110,0.082042,0.137871,0.092664,0.057633,0.135795,0.130974,0.205669,...,0.102363,0.241081,0.141360,0.150583,0.268589,0.165630,0.240975,0.140273,0.175559,pass
18,0.085645,0.107916,0.239336,0.088875,0.189744,0.147450,0.069190,0.182232,0.175460,0.332499,...,0.120550,0.351090,0.205399,0.141403,0.338616,0.202111,0.281225,0.166511,0.175234,pass
19,0.063968,0.076101,0.159700,0.102595,0.184928,0.107474,0.109418,0.194307,0.133551,0.210418,...,0.170355,0.289501,0.166415,0.188084,0.333441,0.210022,0.311270,0.210695,0.223201,pass

[[1.2360689  1.17847034 1.1789074  1.21777303 1.09465601 1.20622152
  1.25851434 1.16035332 1.15942288 1.08637186 1.07680779 1.19212789
  1.15048435 1.10854223 1.10498086 1.12818827 1.19862137 1.24826681
  1.14423716 1.18481752 1.15362011 1.17277174 1.13324295 1.20969151
  1.21599471 1.14217362]]
BARINEL SCORES

,rx 25,rx 20,rzz 21,h 6,rzz 4,rx 12,rx 22,rzz 11,rx 19,rx 8,...,rzz 23,rzz 2,rzz 13,h 10,rx 17,rzz 9,rx 24,h 0,rx 5,rx 14
sum,0.575874,0.573163,0.572382,0.565921,0.563438,0.561282,0.560714,0.559622,0.559588,0.559201,...,0.555512,0.553318,0.549032,0.54822,0.545443,0.541169,0.538205,0.537692,0.529774,0.514816

custom SCORES

,rx 25,rx 20,rx 19,rx 8,h 6,rx 22,rzz 21,rzz 4,h 1,rzz 2,...,swap 16,rzz 13,rzz 15,rx 17,rzz 9,h 10,rx 24,h 0,rx 5,rx 14
sum,0.75383,0.746004,0.73565,0.73371,0.73355,0.73142,0.729023,0.728633,0.724507,0.720654,...,0.710929,0.706945,0.706638,0.703543,0.703334,0.702844,0.69677,0.691226,0.682563,0.668248

DSTAR SCORES

,rzz 15,rzz 4,rzz 7,rzz 11,rzz 2,swap 16,rzz 23,h 6,h 1,h 3,...,rx 17,rx 5,rx 12,rx 20,rzz 9,rx 19,rx 25,rx 24,rx 22,rx 14
sum,1.629315,1.417774,1.290881,1.265954,1.229858,0.969779,0.670216,0.617408,0.588709,0.579472,...,0.374286,0.345817,0.337455,0.334514,0.328636,0.154157,0.146418,0.139419,0.132827,0.096563

ERROR GATE LOCATION:
16
Now evolving the following mutant:  AddGate_sx_inGap_20_.qasm

100%|██████████| 10/10 [01:31<00:00,  9.19s/it]
100%|██████████| 10/10 [01:30<00:00,  9.08s/it]

,rx 25,rx 24,rzz 23,rx 22,rzz 21,rx 20,sxdg 19,rx 18,rzz 17,rx 16,...,rx 8,rzz 7,h 6,rx 5,rzz 4,h 3,rzz 2,h 1,h 0,pass/fail
0,0.146123,0.144467,0.332219,0.145122,0.295698,0.222279,0.179705,0.122802,0.272348,0.233057,...,0.259278,0.540354,0.334824,0.253708,0.520341,0.334681,0.560588,0.330841,0.319635,fail
1,0.154723,0.145456,0.328859,0.131190,0.289954,0.228875,0.184241,0.128896,0.259017,0.222910,...,0.250866,0.470839,0.322893,0.279167,0.481418,0.324862,0.463607,0.320446,0.331715,fail
2,0.125925,0.121861,0.293553,0.133488,0.268443,0.198470,0.160297,0.101302,0.221201,0.195376,...,0.201122,0.436190,0.281372,0.216194,0.418907,0.293299,0.395544,0.263438,0.265193,fail
3,0.121021,0.112621,0.269477,0.116621,0.255323,0.190431,0.152929,0.102046,0.223383,0.182431,...,0.200688,0.449282,0.264810,0.212683,0.424602,0.277798,0.401221,0.260261,0.261810,fail
4,0.157206,0.126971,0.322794,0.166115,0.321622,0.232755,0.187752,0.124749,0.240134,0.207722,...,0.242268,0.466681,0.307333,0.268307,0.492072,0.368532,0.416807,0.308188,0.322971,fail
5,0.166942,0.105760,0.317209,0.127421,0.300431,0.250553,0.198008,0.089606,0.200738,0.186776,...,0.199546,0.435544,0.270944,0.267466,0.539225,0.324167,0.492769,0.266618,0.323262,fail
6,0.143905,0.103744,0.272548,0.138334,0.282491,0.210362,0.168694,0.154942,0.259758,0.176107,...,0.275431,0.460035,0.274125,0.251440,0.447946,0.325304,0.425511,0.333976,0.306397,fail
7,0.176529,0.182844,0.389570,0.145766,0.303246,0.247776,0.201464,0.154609,0.314555,0.268935,...,0.294506,0.522491,0.382326,0.259490,0.570705,0.350478,0.535260,0.364169,0.328364,fail
8,0.108425,0.133059,0.275381,0.127981,0.238439,0.165449,0.136296,0.137066,0.257593,0.203215,...,0.246939,0.425261,0.292607,0.255198,0.407622,0.289680,0.427689,0.308093,0.304190,fail
9,0.124904,0.121314,0.269742,0.102112,0.229154,0.182690,0.147129,0.082570,0.197591,0.181186,...,0.174129,0.381113,0.256998,0.203640,0.426005,0.258070,0.385414,0.231432,0.249262,fail
10,0.066634,0.117385,0.230334,0.108045,0.168706,0.117573,0.098215,0.134477,0.258409,0.192795,...,0.238862,0.445094,0.275998,0.238740,0.412464,0.247011,0.435902,0.301470,0.287731,pass
11,0.074877,0.127993,0.234971,0.115853,0.201945,0.129640,0.108297,0.131219,0.268213,0.198160,...,0.245175,0.444232,0.282679,0.258283,0.396756,0.268606,0.470213,0.311216,0.308863,pass
12,0.100350,0.150001,0.283323,0.128360,0.234807,0.158942,0.131750,0.080509,0.200950,0.214007,...,0.172555,0.364083,0.292728,0.235536,0.449668,0.289826,0.397975,0.236417,0.282526,pass
13,0.099636,0.123338,0.254403,0.125786,0.221916,0.157425,0.129073,0.110168,0.199941,0.183142,...,0.208912,0.335825,0.264192,0.252674,0.379296,0.282508,0.417110,0.266571,0.296765,pass
14,0.123906,0.153999,0.309203,0.113534,0.241653,0.191899,0.155781,0.129622,0.276500,0.231138,...,0.249031,0.482241,0.328727,0.296144,0.447363,0.295790,0.490482,0.326275,0.345612,pass
15,0.158277,0.126209,0.318833,0.119067,0.263013,0.231148,0.184742,0.148863,0.251618,0.200283,...,0.270337,0.420727,0.302250,0.275124,0.499343,0.309233,0.453404,0.331292,0.329200,pass
16,0.130691,0.117985,0.270447,0.121197,0.241231,0.189540,0.153559,0.134894,0.245521,0.189399,...,0.245904,0.421393,0.277841,0.239412,0.449707,0.287704,0.415556,0.304422,0.293041,pass
17,0.144556,0.116693,0.293290,0.093962,0.215822,0.209734,0.166940,0.129287,0.241890,0.188425,...,0.243965,0.443124,0.283547,0.269839,0.393646,0.247963,0.482969,0.312681,0.313928,pass
18,0.154442,0.136582,0.313712,0.166717,0.319057,0.220218,0.179546,0.160322,0.299123,0.215149,...,0.291682,0.515848,0.322484,0.277387,0.506348,0.367314,0.487127,0.359644,0.341017,pass
19,0.123633,0.152414,0.311955,0.137454,0.268706,0.192187,0.157255,0.123838,0.292836,0.238859,...,0.250707,0.550308,0.335361,0.261344,0.443762,0.315127,0.498980,0.324330,0.315933,pass

[[1.2381862  1.40855322 1.2684004  1.24509612 1.1549189  1.1765015
  1.17367917 1.29270788 1.28582865 1.30696004 1.25172477 1.18212348
  1.14964808 1.19386975 1.15161234 1.18499285 1.15812065 1.25601169
  1.17780953 1.27944011 1.13146976 1.2068598  1.17110481 1.24453153
  1.21899251 1.10102016]]
BARINEL SCORES

,rx 25,rx 20,rzz 21,sxdg 19,h 10,rzz 11,rx 12,rzz 23,rx 22,h 3,...,rzz 2,rx 24,h 1,rx 8,h 0,rzz 17,rx 5,rx 18,rzz 9,rx 14
sum,0.547778,0.542177,0.539517,0.539501,0.531609,0.527732,0.523369,0.521291,0.520314,0.519461,...,0.497498,0.495325,0.492836,0.492403,0.491692,0.491099,0.486475,0.482954,0.482715,0.47883

custom SCORES

,rx 25,rx 20,sxdg 19,rzz 21,h 10,rzz 23,rx 22,rzz 11,rx 12,rzz 4,...,rzz 13,rzz 2,rzz 17,rx 8,h 1,rx 18,h 0,rx 5,rzz 9,rx 14
sum,0.71734,0.701645,0.697801,0.695291,0.689098,0.686592,0.682274,0.679668,0.679578,0.675906,...,0.652336,0.652286,0.648966,0.647018,0.643027,0.639033,0.627032,0.624083,0.622475,0.62034

DSTAR SCORES

,rzz 4,rzz 7,rzz 2,rzz 11,rzz 15,h 3,rzz 23,h 0,h 6,h 1,...,h 10,rzz 9,rx 20,rx 16,sxdg 19,rx 25,rx 22,rx 24,rx 14,rx 18
sum,1.555252,1.459336,1.394509,1.281017,1.135486,0.767,0.735792,0.692126,0.688698,0.682631,...,0.437489,0.394771,0.384409,0.351346,0.256989,0.181858,0.158501,0.148822,0.145807,0.127323

ERROR GATE LOCATION:
19
Now evolving the following mutant:  AddGate_rzz_inGap_20_.qasm

100%|██████████| 10/10 [01:37<00:00,  9.73s/it]
100%|██████████| 10/10 [01:28<00:00,  8.83s/it]

,rx 25,rx 24,rzz 23,rx 22,rzz 21,rx 20,rzz 19,rx 18,rzz 17,rx 16,...,rx 8,rzz 7,h 6,rx 5,rzz 4,h 3,rzz 2,h 1,h 0,pass/fail
0,0.152551,0.153840,0.343970,0.105800,0.238403,0.220869,0.364316,0.146903,0.282720,0.242918,...,0.252580,0.461696,0.335222,0.239786,0.433931,0.275261,0.418501,0.316518,0.286951,fail
1,0.155792,0.139759,0.331823,0.137874,0.287112,0.229686,0.388014,0.127810,0.250506,0.228614,...,0.233986,0.447603,0.322074,0.261515,0.494799,0.337139,0.404653,0.300075,0.310753,fail
2,0.138134,0.123689,0.288154,0.117764,0.265859,0.208518,0.360249,0.145939,0.256087,0.202818,...,0.256033,0.451393,0.294383,0.299525,0.527568,0.325513,0.471367,0.324325,0.348683,fail
3,0.136235,0.174023,0.317024,0.120409,0.249055,0.193444,0.341278,0.172308,0.313531,0.254049,...,0.295611,0.443191,0.347116,0.250763,0.415990,0.297831,0.486218,0.357022,0.304768,fail
4,0.107845,0.142564,0.272958,0.125113,0.236848,0.163565,0.284351,0.148123,0.303656,0.228561,...,0.269300,0.515864,0.314961,0.254450,0.416966,0.293502,0.470327,0.337911,0.307279,fail
5,0.127908,0.121991,0.301867,0.140564,0.282913,0.212878,0.358187,0.151815,0.253841,0.210729,...,0.269868,0.458495,0.312410,0.332776,0.440018,0.351832,0.482301,0.345213,0.379504,fail
6,0.128715,0.117637,0.291527,0.166018,0.292134,0.201585,0.338654,0.141844,0.290279,0.221097,...,0.271923,0.571143,0.318866,0.263884,0.474147,0.359935,0.496297,0.340803,0.322157,fail
7,0.123956,0.145844,0.299518,0.132379,0.256739,0.183783,0.316754,0.107877,0.228507,0.224120,...,0.203651,0.402364,0.302894,0.246508,0.481291,0.312139,0.377567,0.264778,0.292590,fail
8,0.120370,0.155021,0.309965,0.130285,0.248553,0.184739,0.318063,0.117325,0.271571,0.249756,...,0.239770,0.505591,0.335674,0.273614,0.492765,0.317201,0.498349,0.314695,0.328005,fail
9,0.122867,0.086157,0.224389,0.090990,0.216861,0.175474,0.302611,0.091145,0.182697,0.147458,...,0.172965,0.362593,0.214127,0.231131,0.422083,0.249084,0.385668,0.229789,0.269878,fail
10,0.112900,0.132050,0.265160,0.153136,0.275613,0.171874,0.295652,0.151226,0.264370,0.208985,...,0.258783,0.415007,0.296274,0.275967,0.466926,0.337462,0.423374,0.322073,0.327283,pass
11,0.089915,0.084721,0.192862,0.098105,0.198054,0.140467,0.242571,0.139950,0.249086,0.158752,...,0.248533,0.451146,0.236227,0.273268,0.427983,0.261858,0.454230,0.312392,0.321185,pass
12,0.105132,0.108662,0.228906,0.124537,0.219392,0.151299,0.265945,0.133044,0.232380,0.179043,...,0.238546,0.377829,0.257133,0.232816,0.368535,0.282629,0.392427,0.290062,0.278066,pass
13,0.090683,0.089265,0.203750,0.094025,0.180449,0.137035,0.232745,0.099475,0.204280,0.156809,...,0.183284,0.388133,0.223719,0.232671,0.325407,0.227553,0.356851,0.243464,0.266716,pass
14,0.112030,0.081350,0.224497,0.091723,0.185488,0.164267,0.271214,0.095915,0.184317,0.151646,...,0.180958,0.365305,0.220587,0.233357,0.352167,0.231648,0.355541,0.235765,0.266359,pass
15,0.138545,0.126942,0.285607,0.118049,0.268516,0.206597,0.353405,0.101445,0.226266,0.207924,...,0.210647,0.432398,0.285159,0.241293,0.426007,0.298464,0.439042,0.271083,0.287166,pass
16,0.145895,0.127842,0.291256,0.104607,0.248702,0.210422,0.358670,0.145055,0.263673,0.205955,...,0.249864,0.423516,0.291720,0.229265,0.407725,0.278656,0.414706,0.308510,0.277088,pass
17,0.082407,0.075311,0.176674,0.076103,0.153207,0.119725,0.202896,0.092495,0.179945,0.126709,...,0.166266,0.308652,0.180726,0.165183,0.282504,0.184610,0.320221,0.207695,0.200366,pass
18,0.050230,0.071636,0.156962,0.088951,0.150317,0.095952,0.157475,0.132075,0.210680,0.128316,...,0.225107,0.350604,0.195643,0.170065,0.287073,0.202380,0.391467,0.267398,0.213388,pass
19,0.086041,0.125736,0.241974,0.117585,0.199668,0.131855,0.225671,0.089638,0.214763,0.193740,...,0.178516,0.368192,0.256065,0.173946,0.362520,0.250880,0.357313,0.228399,0.218957,pass

[[1.18529537 1.27908801 1.153799   1.31012284 1.13473106 1.16323512
  1.15053041 1.27532815 1.19059563 1.14947962 1.17815905 1.38414756
  1.1256163  1.20111919 1.16670272 1.1280771  1.19623495 1.19889924
  1.23625747 1.12055101 1.25388908 1.1469974  1.15384453 1.10959947
  1.14023397 1.20455863]]
BARINEL SCORES

,rx 24,rzz 23,rx 25,rzz 19,rx 20,rx 16,h 10,h 6,rzz 4,rzz 11,...,rx 5,rzz 7,rx 22,h 0,rzz 17,h 1,rx 8,rzz 2,rx 18,rzz 9
sum,0.570681,0.567972,0.564557,0.56408,0.563505,0.562658,0.560517,0.559058,0.553736,0.553347,...,0.543644,0.543476,0.542925,0.542533,0.541499,0.538182,0.535298,0.5349,0.53373,0.532673

custom SCORES

,rx 24,rx 14,rx 25,rzz 23,rx 20,rzz 19,rx 16,rx 22,h 10,rzz 15,...,rzz 21,h 3,h 0,rx 18,rzz 17,rzz 13,rx 8,rzz 9,h 1,rzz 2
sum,0.753168,0.733373,0.731848,0.731803,0.727377,0.726328,0.724349,0.72075,0.718593,0.716148,...,0.710119,0.70817,0.705912,0.703901,0.702676,0.698409,0.69574,0.691973,0.691596,0.683282

DSTAR SCORES

,rzz 4,rzz 7,rzz 11,rzz 2,rzz 15,rzz 19,h 0,h 3,h 1,h 6,...,rx 8,rzz 9,rx 12,rx 16,rx 20,rx 14,rx 24,rx 18,rx 25,rx 22
sum,1.543458,1.537649,1.516469,1.450633,1.393692,0.902219,0.784263,0.774991,0.772767,0.771174,...,0.50077,0.454461,0.444786,0.416853,0.33816,0.193402,0.167916,0.163273,0.156856,0.145099

ERROR GATE LOCATION:
19
Now evolving the following mutant:  AddGate_rxx_inGap_20_.qasm

100%|██████████| 10/10 [01:38<00:00,  9.88s/it]
100%|██████████| 10/10 [01:31<00:00,  9.19s/it]

,rx 25,rx 24,rzz 23,rx 22,rzz 21,rx 20,rxx 19,rx 18,rzz 17,rx 16,...,rx 8,rzz 7,h 6,rx 5,rzz 4,h 3,rzz 2,h 1,h 0,pass/fail
0,0.136973,0.155235,0.328224,0.157558,0.271868,0.201306,0.475966,0.187135,0.341232,0.255743,...,0.320828,0.539794,0.361089,0.274533,0.510358,0.341621,0.520737,0.389436,0.337900,fail
1,0.119961,0.105656,0.261593,0.094781,0.207974,0.187142,0.414763,0.148268,0.241114,0.181780,...,0.255867,0.398038,0.269714,0.308002,0.475589,0.279934,0.496982,0.324242,0.356381,fail
2,0.122981,0.099648,0.247233,0.124702,0.250086,0.185258,0.362310,0.177619,0.276195,0.175680,...,0.292508,0.441493,0.268094,0.252801,0.496095,0.307853,0.457649,0.350990,0.311288,fail
3,0.097815,0.091287,0.218719,0.110875,0.207553,0.153803,0.349983,0.125402,0.227171,0.165576,...,0.231350,0.411295,0.241510,0.207661,0.381621,0.251635,0.450757,0.280939,0.258008,fail
4,0.112916,0.112927,0.263901,0.134802,0.262807,0.179771,0.395851,0.140896,0.252855,0.194898,...,0.253485,0.453019,0.284139,0.248833,0.486914,0.319537,0.480483,0.314541,0.304600,fail
5,0.089819,0.132185,0.252464,0.157873,0.251698,0.143568,0.373462,0.140889,0.258498,0.205213,...,0.245671,0.411813,0.287489,0.247500,0.463382,0.324534,0.422244,0.305904,0.301873,fail
6,0.134616,0.148003,0.315964,0.127246,0.259939,0.208770,0.426460,0.137953,0.255786,0.231661,...,0.247132,0.397912,0.321180,0.241105,0.493084,0.321044,0.460560,0.307906,0.298621,fail
7,0.101942,0.157281,0.321653,0.153909,0.268700,0.180198,0.546665,0.089169,0.222806,0.246129,...,0.192003,0.410765,0.329240,0.250712,0.484052,0.334671,0.444881,0.259040,0.302238,fail
8,0.101222,0.144078,0.270767,0.104388,0.217966,0.160672,0.350865,0.175208,0.322824,0.224973,...,0.285166,0.491722,0.313612,0.224318,0.463679,0.273916,0.451047,0.346007,0.279510,fail
9,0.107902,0.159342,0.296622,0.115200,0.227575,0.170230,0.389749,0.120785,0.267702,0.243330,...,0.225086,0.434469,0.324735,0.246066,0.411949,0.281469,0.395888,0.288941,0.287941,fail
10,0.118729,0.123485,0.264445,0.144750,0.270389,0.176919,0.316638,0.128703,0.244541,0.199099,...,0.235300,0.413786,0.279863,0.213000,0.454225,0.320865,0.424386,0.286402,0.267334,pass
11,0.138228,0.117455,0.286016,0.153870,0.280859,0.202415,0.370753,0.123009,0.234530,0.204415,...,0.235018,0.433887,0.289755,0.226129,0.462935,0.335133,0.434280,0.290632,0.281459,pass
12,0.079869,0.074966,0.174855,0.108834,0.205172,0.128577,0.278976,0.139268,0.230089,0.134653,...,0.238971,0.387913,0.206507,0.216622,0.454298,0.264217,0.448685,0.289861,0.270717,pass
13,0.109812,0.075847,0.200553,0.087526,0.190801,0.155260,0.236251,0.120947,0.204016,0.138759,...,0.202306,0.353115,0.206013,0.198712,0.328808,0.220455,0.316309,0.247724,0.235495,pass
14,0.123708,0.097029,0.235020,0.124923,0.255422,0.178357,0.277061,0.155972,0.261319,0.169032,...,0.264004,0.447869,0.252714,0.229109,0.400614,0.293043,0.413801,0.318279,0.279009,pass
15,0.113010,0.132863,0.301185,0.102540,0.203269,0.181601,0.499197,0.126069,0.263465,0.228756,...,0.236549,0.507948,0.320047,0.289917,0.474934,0.280286,0.457801,0.310127,0.333358,pass
16,0.108716,0.136466,0.298721,0.149751,0.278859,0.190661,0.515898,0.155276,0.280153,0.232995,...,0.277624,0.496703,0.330271,0.267526,0.520013,0.352840,0.456955,0.343907,0.326191,pass
17,0.143329,0.081816,0.258886,0.094344,0.245521,0.216656,0.390690,0.162797,0.266747,0.162309,...,0.282954,0.485976,0.256245,0.288521,0.461363,0.284750,0.522431,0.347878,0.339748,pass
18,0.133367,0.094498,0.271846,0.131399,0.270242,0.202909,0.421870,0.111746,0.225409,0.177417,...,0.207373,0.445586,0.259578,0.191789,0.420114,0.298057,0.386506,0.260117,0.240634,pass
19,0.076685,0.051482,0.141161,0.036128,0.106698,0.106108,0.165522,0.041551,0.101634,0.090631,...,0.088093,0.219917,0.128125,0.126844,0.180977,0.115576,0.192781,0.123273,0.141467,pass

[[1.21630043 1.22040665 1.1818776  1.23209863 1.12056707 1.1790138
  1.33787315 1.29655456 1.27985227 1.20350461 1.22482852 1.35049499
  1.11222576 1.15135302 1.11872928 1.15317453 1.18065022 1.25859613
  1.22950955 1.20330771 1.23125323 1.09361176 1.12515408 1.13667658
  1.22930155 1.1729377 ]]
BARINEL SCORES

,rx 24,rx 16,h 6,rxx 19,rzz 17,rzz 23,rx 18,rzz 2,rx 22,h 1,...,rx 12,rzz 13,h 3,rx 14,h 10,rzz 11,rzz 21,rzz 7,rx 20,rx 25
sum,0.569765,0.550079,0.542648,0.540563,0.535584,0.533058,0.532855,0.530532,0.530485,0.529213,...,0.526422,0.525061,0.523355,0.521154,0.514566,0.513112,0.512563,0.511512,0.504452,0.495751

custom SCORES

,rx 24,rxx 19,rx 16,rzz 17,h 6,rx 18,rx 14,rx 8,rx 22,h 1,...,rx 12,rzz 4,rzz 13,h 3,rzz 7,h 10,rzz 11,rzz 21,rx 20,rx 25
sum,0.743601,0.721364,0.715585,0.706951,0.705891,0.705574,0.697109,0.695654,0.693888,0.691853,...,0.677946,0.673384,0.671057,0.670569,0.66874,0.662912,0.65662,0.656153,0.653141,0.646496

DSTAR SCORES

,rzz 4,rzz 2,rzz 15,rzz 7,rzz 11,rxx 19,h 1,h 0,h 3,h 6,...,rzz 21,rzz 9,rx 12,rx 16,rx 20,rx 18,rx 14,rx 24,rx 22,rx 25
sum,1.538202,1.493364,1.366588,1.358087,1.339038,1.239233,0.78294,0.726019,0.722164,0.71871,...,0.478278,0.463509,0.428662,0.384693,0.267086,0.18492,0.157584,0.155172,0.147459,0.113787

ERROR GATE LOCATION:
19
Now evolving the following mutant:  AddGate_ry_inGap_5_.qasm

100%|██████████| 10/10 [01:44<00:00, 10.43s/it]
100%|██████████| 10/10 [01:46<00:00, 10.69s/it]

,rx 25,rx 24,rzz 23,rx 22,rzz 21,rx 20,rx 19,rzz 18,rx 17,rzz 16,...,rzz 8,h 7,rx 6,rzz 5,ry 4,h 3,rzz 2,h 1,h 0,pass/fail
0,0.097539,0.114926,0.244225,0.137157,0.244496,0.158941,0.115068,0.212314,0.183406,0.395445,...,0.370734,0.262172,0.282453,0.473600,0.208502,0.309783,0.436744,0.273613,0.327304,fail
1,0.155984,0.145618,0.344601,0.137965,0.276613,0.224749,0.136231,0.285938,0.243474,0.510797,...,0.522948,0.339050,0.283657,0.489751,0.212544,0.317329,0.420146,0.314939,0.330130,fail
2,0.113936,0.087991,0.238961,0.105195,0.223930,0.175344,0.090279,0.184505,0.157745,0.394649,...,0.383265,0.228051,0.208516,0.417735,0.171982,0.250024,0.399703,0.231093,0.252807,fail
3,0.130748,0.116094,0.275013,0.086032,0.206371,0.183131,0.079462,0.186840,0.182978,0.371317,...,0.357536,0.250874,0.214744,0.382850,0.149919,0.226857,0.356078,0.216091,0.248048,fail
4,0.126370,0.118060,0.279983,0.147913,0.271829,0.191408,0.097912,0.182274,0.190830,0.421830,...,0.348114,0.269624,0.263556,0.445357,0.212018,0.315060,0.422916,0.252520,0.308973,fail
5,0.106991,0.093179,0.242374,0.146577,0.258645,0.171083,0.103508,0.198166,0.169917,0.431736,...,0.398609,0.248775,0.289583,0.464507,0.209915,0.311905,0.391932,0.262052,0.333823,fail
6,0.136948,0.138975,0.296210,0.124946,0.250153,0.191251,0.110416,0.222127,0.213490,0.377120,...,0.378795,0.292655,0.264376,0.395715,0.187965,0.286421,0.428672,0.274318,0.305162,fail
7,0.104270,0.097326,0.231746,0.108833,0.215614,0.156771,0.093323,0.197718,0.168797,0.365958,...,0.375032,0.236636,0.215574,0.389838,0.170096,0.250517,0.365164,0.233842,0.256405,fail
8,0.117512,0.140907,0.284450,0.118255,0.239486,0.174673,0.108003,0.237288,0.215478,0.390870,...,0.416709,0.292784,0.247262,0.477354,0.193177,0.283154,0.407597,0.266899,0.292978,fail
9,0.117791,0.096000,0.236098,0.115432,0.247087,0.176038,0.121577,0.208655,0.162493,0.378076,...,0.385508,0.238679,0.266623,0.495377,0.197104,0.287582,0.427946,0.278160,0.313368,fail
10,0.080225,0.109496,0.222608,0.123689,0.228632,0.138983,0.094204,0.207321,0.178992,0.394540,...,0.383150,0.246990,0.255061,0.398991,0.188426,0.274538,0.359423,0.239469,0.294337,pass
11,0.102781,0.097089,0.248291,0.117671,0.239579,0.176889,0.132547,0.239696,0.181235,0.472369,...,0.446677,0.266621,0.269631,0.474470,0.200737,0.293810,0.373543,0.288496,0.313116,pass
12,0.135102,0.169618,0.342184,0.135664,0.257130,0.199197,0.149255,0.302185,0.265189,0.478770,...,0.487892,0.361989,0.260977,0.466936,0.211108,0.313425,0.455081,0.332911,0.314436,pass
13,0.075029,0.119200,0.228452,0.091503,0.160968,0.124022,0.127571,0.253643,0.191849,0.376738,...,0.421945,0.266754,0.241529,0.401899,0.155588,0.226577,0.416935,0.281962,0.281297,pass
14,0.135054,0.103579,0.276067,0.127896,0.271375,0.209245,0.135089,0.238550,0.187708,0.451760,...,0.440698,0.277216,0.251082,0.423774,0.205774,0.305798,0.420673,0.299649,0.299680,pass
15,0.058980,0.078159,0.159437,0.095783,0.172312,0.100746,0.077792,0.153097,0.127482,0.270983,...,0.272542,0.179208,0.157087,0.277958,0.141372,0.205479,0.253455,0.179470,0.189091,pass
16,0.061193,0.108673,0.197544,0.106702,0.182618,0.104334,0.051707,0.166917,0.171146,0.307247,...,0.340863,0.221379,0.167004,0.328574,0.155710,0.223527,0.327972,0.176361,0.205683,pass
17,0.108893,0.129472,0.265382,0.091174,0.217322,0.168465,0.108418,0.258799,0.211899,0.393142,...,0.485769,0.285995,0.194655,0.417845,0.163794,0.236607,0.426474,0.268471,0.242458,pass
18,0.077708,0.126120,0.236926,0.139403,0.236337,0.135143,0.129421,0.257978,0.203145,0.393626,...,0.435960,0.283586,0.256661,0.396169,0.205940,0.298113,0.436639,0.300136,0.306139,pass
19,0.109851,0.117617,0.254904,0.098177,0.205508,0.160540,0.064557,0.175751,0.186664,0.349520,...,0.357236,0.249454,0.206263,0.370713,0.155717,0.232152,0.341911,0.197933,0.240603,pass

[[1.29115939 1.26726391 1.28887264 1.20420256 1.13635091 1.24625825
  1.29033258 1.35142539 1.28917066 1.26503855 1.22147351 1.16007297
  1.13817843 1.11063529 1.2303838  1.1363254  1.20284008 1.32820581
  1.27495862 1.14173413 1.11770667 1.11092373 1.11789343 1.07654721
  1.20966269 1.12436193]]
BARINEL SCORES

,rx 25,rx 20,h 11,rx 15,rzz 14,rx 6,rzz 21,rzz 5,h 0,rzz 23,...,rzz 10,rzz 16,h 1,h 7,rx 9,rx 24,rx 17,rx 19,rzz 8,rzz 18
sum,0.561144,0.543033,0.533347,0.533271,0.532294,0.528813,0.528489,0.528295,0.524944,0.523687,...,0.513602,0.509405,0.503741,0.501898,0.500935,0.497845,0.497799,0.496524,0.491543,0.484197

custom SCORES

,rx 25,rx 20,h 11,rx 15,rzz 23,rzz 14,rx 6,rzz 21,rx 22,rzz 5,...,rzz 10,rzz 12,rx 17,rx 19,h 1,rx 24,rzz 8,rzz 2,rx 9,rzz 18
sum,0.742275,0.712223,0.697403,0.696115,0.692428,0.686669,0.679754,0.678627,0.678315,0.675914,...,0.659507,0.659471,0.658236,0.656694,0.65608,0.655571,0.65476,0.654309,0.651571,0.647786

DSTAR SCORES

,rzz 5,rzz 12,rzz 2,rzz 16,rzz 8,h 0,h 3,rzz 14,h 11,rzz 23,...,rzz 10,rx 9,ry 4,rx 17,rx 20,rx 15,rx 22,rx 25,rx 24,rx 19
sum,1.407386,1.27016,1.191593,1.173891,1.101558,0.69481,0.639002,0.629207,0.602878,0.575014,...,0.358416,0.334978,0.310622,0.299601,0.282369,0.186523,0.135584,0.133349,0.118324,0.100688

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_ccx_inGap_16_.qasm

100%|██████████| 10/10 [03:46<00:00, 22.64s/it]
100%|██████████| 10/10 [03:45<00:00, 22.59s/it]

,rx 25,rx 24,rzz 23,rx 22,rzz 21,rx 20,rx 19,rzz 18,rx 17,rzz 16,...,rx 8,rzz 7,h 6,rx 5,rzz 4,h 3,rzz 2,h 1,h 0,pass/fail
0,0.136572,0.132299,0.307438,0.144770,0.270537,0.203335,0.118708,0.234527,0.219156,0.457594,...,0.166665,0.321220,0.228539,0.200738,0.330762,0.240840,0.323074,0.215963,0.234379,fail
1,0.127943,0.135298,0.293774,0.145624,0.276849,0.194772,0.116596,0.255910,0.223585,0.452436,...,0.167356,0.347903,0.229716,0.181604,0.347538,0.251312,0.336925,0.213940,0.218521,fail
2,0.129055,0.113171,0.275059,0.135957,0.272572,0.198555,0.109178,0.210127,0.188198,0.415934,...,0.159701,0.289736,0.207141,0.192379,0.362892,0.245822,0.374209,0.204586,0.232952,fail
3,0.110186,0.129587,0.294478,0.121947,0.240443,0.181415,0.142910,0.270498,0.220344,0.498586,...,0.194747,0.373889,0.246046,0.239700,0.397231,0.263465,0.364237,0.253355,0.279353,fail
4,0.120991,0.097442,0.261386,0.131383,0.248468,0.187595,0.125946,0.235555,0.181274,0.448335,...,0.174465,0.339693,0.210224,0.175373,0.357604,0.238823,0.348067,0.221130,0.216065,fail
5,0.166958,0.123425,0.325743,0.122907,0.269160,0.235223,0.145422,0.265941,0.215401,0.485270,...,0.192940,0.346910,0.235686,0.201760,0.378468,0.249012,0.361377,0.240795,0.242719,fail
6,0.108680,0.105714,0.261646,0.120602,0.220293,0.168709,0.133365,0.236402,0.186887,0.445095,...,0.172212,0.320738,0.208670,0.163474,0.326151,0.217436,0.277757,0.214625,0.198806,fail
7,0.131621,0.141650,0.306627,0.105150,0.228473,0.190301,0.136108,0.275877,0.223978,0.443710,...,0.182358,0.348424,0.236337,0.190848,0.371312,0.239025,0.357763,0.232979,0.230765,fail
8,0.131237,0.128271,0.309992,0.135902,0.258351,0.205270,0.163485,0.285075,0.220163,0.526756,...,0.222632,0.370080,0.247612,0.207362,0.415870,0.270526,0.465223,0.270980,0.258626,fail
9,0.112974,0.070965,0.212525,0.083995,0.193235,0.165668,0.115995,0.201879,0.137404,0.351331,...,0.146792,0.264764,0.163430,0.148579,0.312756,0.196970,0.256593,0.182752,0.181939,fail
10,0.109728,0.122684,0.247210,0.092368,0.205882,0.159187,0.101554,0.213031,0.185345,0.320466,...,0.139152,0.255443,0.184526,0.147403,0.298003,0.191571,0.261259,0.177353,0.178595,pass
11,0.102491,0.127369,0.276876,0.133531,0.243602,0.168654,0.106931,0.196964,0.200513,0.448662,...,0.154971,0.270365,0.216812,0.202018,0.354290,0.239522,0.343417,0.200920,0.237943,pass
12,0.095356,0.135181,0.266289,0.132149,0.231362,0.154657,0.120290,0.234535,0.210076,0.404712,...,0.169320,0.296744,0.220644,0.201766,0.368949,0.242889,0.337771,0.216654,0.241546,pass
13,0.120939,0.055255,0.211479,0.092964,0.214551,0.184866,0.116716,0.194437,0.123827,0.393828,...,0.161202,0.294971,0.165091,0.161035,0.340518,0.215519,0.351616,0.201263,0.200839,pass
14,0.071002,0.117971,0.205473,0.112534,0.203101,0.118215,0.127301,0.229449,0.178754,0.285831,...,0.167584,0.257347,0.177661,0.125401,0.241402,0.183688,0.264681,0.199267,0.158320,pass
15,0.097231,0.085775,0.209610,0.073613,0.150483,0.140230,0.103710,0.181823,0.142235,0.319612,...,0.136435,0.218554,0.156106,0.112795,0.218458,0.148947,0.253875,0.164685,0.139247,pass
16,0.100512,0.162408,0.299108,0.111703,0.218248,0.162894,0.109863,0.246583,0.244712,0.425045,...,0.165022,0.321007,0.238785,0.200310,0.335711,0.231308,0.345668,0.214918,0.233334,pass
17,0.113924,0.094524,0.245612,0.094928,0.205535,0.177792,0.113840,0.203339,0.165119,0.406122,...,0.149672,0.275590,0.190508,0.182901,0.320987,0.215524,0.275783,0.192569,0.213056,pass
18,0.142310,0.105430,0.282293,0.136863,0.267308,0.210796,0.162990,0.262688,0.190705,0.452824,...,0.205848,0.342481,0.222716,0.211482,0.368252,0.252617,0.357907,0.255336,0.251981,pass
19,0.065306,0.112325,0.210932,0.109308,0.198292,0.119048,0.124039,0.255129,0.185874,0.359617,...,0.170521,0.335162,0.193434,0.117251,0.309524,0.204428,0.290873,0.208237,0.156326,pass

[[1.30822226 1.2026433  1.14349152 1.16663597 1.11705591 1.21824209
  1.2501593  1.15331391 1.11078939 1.16409026 1.14070044 1.37570281
  1.15321001 1.11526348 1.12755676 1.11315512 1.27030138 1.25083545
  1.12503319 1.11869246 1.2603734  1.15500647 1.12101032 1.34254879
  1.20376493 1.21768748]]
BARINEL SCORES

,rx 25,rx 20,rzz 16,h 10,ccx 15,rzz 23,rzz 21,rzz 7,rx 14,rzz 11,...,rx 12,h 6,rzz 2,rzz 18,h 1,rx 17,rx 19,rx 8,rzz 9,rx 24
sum,0.556082,0.547418,0.542457,0.538526,0.537211,0.537125,0.536824,0.536803,0.536772,0.536324,...,0.531243,0.529562,0.529198,0.52706,0.525676,0.524617,0.524145,0.523553,0.522393,0.512822

custom SCORES

,rx 25,rx 14,rx 20,rzz 2,rx 5,rzz 16,h 0,rzz 23,ccx 15,rx 22,...,rx 8,rzz 4,rzz 21,h 1,h 3,rx 12,rzz 18,h 6,rx 17,rx 24
sum,0.737952,0.721382,0.71414,0.706816,0.701723,0.700324,0.695073,0.690674,0.69041,0.689547,...,0.687273,0.686766,0.68674,0.683874,0.68063,0.679363,0.679027,0.677666,0.670301,0.667008

DSTAR SCORES

,ccx 15,rzz 16,rzz 4,rzz 11,rzz 2,rzz 7,rzz 23,rzz 21,rzz 18,h 3,...,rx 20,rx 5,rx 8,rzz 9,rx 12,rx 19,rx 25,rx 22,rx 24,rx 14
sum,1.977004,1.481977,0.985414,0.926955,0.917827,0.858329,0.651545,0.50603,0.500063,0.480264,...,0.321494,0.310135,0.272634,0.266152,0.243342,0.152863,0.147814,0.140496,0.124766,0.10365

ERROR GATE LOCATION:
15
Now evolving the following mutant:  AddGate_sx_inGap_24_.qasm

100%|██████████| 10/10 [01:33<00:00,  9.36s/it]
100%|██████████| 10/10 [01:40<00:00, 10.07s/it]

,rx 25,rx 24,sxdg 23,rzz 22,rx 21,rzz 20,rx 19,rx 18,rzz 17,rx 16,...,rx 8,rzz 7,h 6,rx 5,rzz 4,h 3,rzz 2,h 1,h 0,pass/fail
0,0.114635,0.137738,0.414115,0.578057,0.112560,0.241935,0.184345,0.127550,0.459235,0.288130,...,0.219016,0.417806,0.268877,0.237277,0.469300,0.284043,0.460707,0.297720,0.288534,fail
1,0.058262,0.131310,0.394112,0.514555,0.088913,0.170656,0.123799,0.123841,0.384168,0.260484,...,0.174791,0.324718,0.230305,0.212809,0.433095,0.235960,0.375093,0.245944,0.258178,fail
2,0.134829,0.154502,0.465063,0.621294,0.135580,0.281883,0.199498,0.148566,0.564830,0.322988,...,0.256886,0.484720,0.302300,0.221562,0.458560,0.312392,0.467834,0.345789,0.281195,fail
3,0.147944,0.142600,0.429012,0.612868,0.163419,0.314517,0.222805,0.140406,0.451829,0.299165,...,0.249871,0.453428,0.297240,0.254786,0.531986,0.361151,0.512257,0.329650,0.318613,fail
4,0.121561,0.159282,0.478759,0.657952,0.096189,0.236585,0.197776,0.145264,0.541857,0.329299,...,0.240105,0.461303,0.297455,0.252088,0.478799,0.275013,0.499109,0.331106,0.306196,fail
5,0.132727,0.147193,0.443140,0.590234,0.157895,0.276189,0.187681,0.149537,0.503049,0.303830,...,0.253215,0.438272,0.293066,0.226843,0.398140,0.320496,0.462521,0.329663,0.281106,fail
6,0.137195,0.120930,0.363749,0.537117,0.106846,0.222575,0.199768,0.151033,0.390421,0.255537,...,0.230511,0.396105,0.261330,0.218416,0.393812,0.258044,0.451817,0.298440,0.267288,fail
7,0.132282,0.136934,0.412262,0.553723,0.137932,0.245871,0.177742,0.159436,0.432341,0.283476,...,0.251679,0.432334,0.285745,0.289793,0.466666,0.309158,0.475240,0.329817,0.341290,fail
8,0.125822,0.136790,0.411100,0.591838,0.121211,0.250296,0.202943,0.165556,0.464020,0.289588,...,0.255092,0.460510,0.285918,0.225514,0.466555,0.295008,0.474202,0.329370,0.283690,fail
9,0.122186,0.127220,0.382384,0.554153,0.114734,0.229844,0.189928,0.131373,0.420608,0.272357,...,0.219967,0.404851,0.261534,0.239821,0.492412,0.287506,0.449498,0.298359,0.291835,fail
10,0.129548,0.138153,0.415732,0.564024,0.146705,0.274938,0.193976,0.155577,0.446968,0.289718,...,0.256261,0.434812,0.288686,0.321525,0.553173,0.350859,0.489562,0.342393,0.378816,pass
11,0.157195,0.144297,0.434576,0.601211,0.161956,0.310071,0.218704,0.153185,0.433020,0.300489,...,0.236220,0.412962,0.300442,0.250055,0.549546,0.357154,0.459501,0.310521,0.313242,pass
12,0.114971,0.113221,0.341188,0.449083,0.123801,0.242361,0.151113,0.066693,0.350870,0.225471,...,0.153870,0.305302,0.214122,0.228737,0.390943,0.272611,0.392533,0.223610,0.266056,pass
13,0.088848,0.131197,0.394027,0.548772,0.095056,0.192316,0.153784,0.081194,0.410235,0.270807,...,0.175393,0.360992,0.236856,0.213165,0.338619,0.228672,0.371441,0.252304,0.251239,pass
14,0.069253,0.114416,0.343316,0.477561,0.142974,0.219318,0.137005,0.100525,0.379489,0.243025,...,0.193381,0.360134,0.225796,0.214527,0.388679,0.287749,0.390077,0.262015,0.259213,pass
15,0.122775,0.126740,0.382012,0.488947,0.143430,0.251120,0.163350,0.159910,0.428518,0.263227,...,0.262617,0.436828,0.271137,0.292725,0.459111,0.310992,0.468635,0.340423,0.345705,pass
16,0.107483,0.119913,0.360406,0.511310,0.105976,0.226586,0.173924,0.151767,0.413652,0.254537,...,0.236600,0.406105,0.250118,0.234978,0.472403,0.277896,0.465807,0.309287,0.289248,pass
17,0.123707,0.104555,0.314516,0.471858,0.139004,0.283104,0.196486,0.140780,0.345439,0.229503,...,0.215612,0.373657,0.241722,0.202805,0.490262,0.316345,0.391707,0.275292,0.259038,pass
18,0.090385,0.103047,0.309723,0.439312,0.080629,0.159553,0.135831,0.099597,0.324685,0.216149,...,0.161042,0.307228,0.201524,0.196973,0.354319,0.203129,0.370190,0.221218,0.234799,pass
19,0.105715,0.134042,0.402849,0.556076,0.112882,0.214293,0.178066,0.117965,0.426233,0.276716,...,0.210624,0.400593,0.261588,0.294501,0.450878,0.283064,0.465479,0.298508,0.339747,pass

[[1.20529935 1.14221656 1.14161495 1.13209856 1.3229275  1.27316695
  1.18118507 1.14765273 1.2246005  1.13361683 1.13669953 1.27966137
  1.15281166 1.26133692 1.17442392 1.15161803 1.16045782 1.09260507
  1.1341017  1.08593738 1.21817509 1.15918242 1.22891841 1.10679781
  1.10269143 1.1696335 ]]
BARINEL SCORES

,rx 18,rzz 17,rzz 22,rx 24,sxdg 23,rx 16,rzz 7,rx 8,h 6,rzz 15,...,rzz 11,rzz 20,rzz 4,h 3,rx 12,h 0,rx 21,rzz 13,rx 5,rx 14
sum,0.540335,0.538106,0.532218,0.531424,0.531383,0.530616,0.529447,0.528018,0.527653,0.527513,...,0.519129,0.509981,0.507823,0.504316,0.504094,0.498362,0.496556,0.492783,0.49264,0.480628

custom SCORES

,rzz 17,rx 18,rx 25,rx 24,sxdg 23,rzz 22,rx 16,rx 19,rzz 7,rzz 15,...,h 1,rzz 2,rx 12,rx 21,h 3,rzz 4,h 0,rx 5,rzz 13,rx 14
sum,0.702847,0.695364,0.68339,0.683174,0.683042,0.682849,0.680995,0.680865,0.679559,0.677419,...,0.669911,0.66443,0.663052,0.660783,0.659257,0.654987,0.644088,0.642671,0.634805,0.634388

DSTAR SCORES

,rzz 22,rzz 17,rzz 2,rzz 4,rzz 11,rzz 7,sxdg 23,rzz 15,h 1,rx 16,...,rzz 9,rx 8,rx 5,rx 12,rx 19,rx 18,rx 24,rx 14,rx 25,rx 21
sum,2.235674,1.524012,1.501651,1.457779,1.367303,1.323864,1.283885,1.19724,0.766122,0.671314,...,0.487295,0.456784,0.454556,0.386809,0.304051,0.185353,0.17317,0.138959,0.135611,0.135608

ERROR GATE LOCATION:
23
Now evolving the following mutant:  AddGate_swap_inGap_16_.qasm

100%|██████████| 10/10 [01:58<00:00, 11.81s/it]
100%|██████████| 10/10 [01:54<00:00, 11.40s/it]

,rx 25,rx 24,rzz 23,rx 22,rzz 21,rx 20,rx 19,rzz 18,rx 17,rzz 16,...,rx 8,rzz 7,h 6,rx 5,rzz 4,h 3,rzz 2,h 1,h 0,pass/fail
0,0.106772,0.120156,0.272789,0.144921,0.285271,0.181605,0.098999,0.225625,0.206637,0.438671,...,0.190739,0.386698,0.258363,0.187354,0.381916,0.287256,0.385194,0.243117,0.232654,fail
1,0.137444,0.115877,0.295644,0.125236,0.255794,0.208279,0.113750,0.223760,0.203026,0.475469,...,0.203737,0.417623,0.287975,0.216185,0.439327,0.276348,0.450608,0.259836,0.264118,fail
2,0.099941,0.149547,0.287866,0.120260,0.232467,0.163536,0.145642,0.284993,0.233089,0.439995,...,0.225432,0.379830,0.248481,0.205472,0.405539,0.258698,0.395079,0.280772,0.251526,fail
3,0.102967,0.109030,0.233862,0.121417,0.243298,0.163674,0.126888,0.229901,0.175262,0.360356,...,0.189033,0.359927,0.231633,0.186829,0.388938,0.250388,0.335889,0.237039,0.230176,fail
4,0.085737,0.136035,0.266130,0.109266,0.211561,0.150700,0.183385,0.325452,0.227284,0.447142,...,0.274370,0.410106,0.240675,0.200319,0.439360,0.261764,0.446582,0.328263,0.254920,fail
5,0.083586,0.141562,0.261775,0.125178,0.218488,0.143766,0.143846,0.290741,0.227723,0.428868,...,0.225222,0.371731,0.224849,0.207049,0.385514,0.262241,0.427093,0.277518,0.254331,fail
6,0.114685,0.149317,0.313139,0.148311,0.277239,0.190502,0.129760,0.246670,0.234433,0.489012,...,0.205639,0.453509,0.280578,0.232970,0.456759,0.309664,0.411480,0.270130,0.280437,fail
7,0.152703,0.139173,0.317682,0.142350,0.275627,0.217713,0.140364,0.287169,0.237106,0.452005,...,0.227114,0.397364,0.298975,0.228106,0.421811,0.296682,0.375418,0.286665,0.274156,fail
8,0.102082,0.123830,0.267571,0.126578,0.254062,0.170788,0.098553,0.227710,0.201965,0.442491,...,0.170634,0.390373,0.244260,0.178082,0.338372,0.244323,0.367001,0.223578,0.218071,fail
9,0.163344,0.144992,0.336867,0.118386,0.260113,0.229394,0.136991,0.285555,0.237933,0.473259,...,0.229877,0.435059,0.312706,0.232294,0.418585,0.273326,0.449458,0.288459,0.277864,fail
10,0.069840,0.092932,0.186391,0.112788,0.198061,0.113727,0.121433,0.236442,0.158414,0.328965,...,0.182515,0.311247,0.177823,0.139750,0.363317,0.213519,0.346054,0.215860,0.186740,pass
11,0.100609,0.117886,0.243313,0.160984,0.251945,0.149875,0.100760,0.229606,0.203931,0.382257,...,0.181758,0.344501,0.221079,0.214953,0.453778,0.302639,0.378132,0.232347,0.263427,pass
12,0.101773,0.070879,0.203804,0.132010,0.246726,0.167394,0.131254,0.208795,0.139721,0.384457,...,0.199989,0.368810,0.242285,0.233775,0.408924,0.270268,0.368735,0.252324,0.274428,pass
13,0.091023,0.113254,0.242075,0.132742,0.242819,0.153607,0.108812,0.215407,0.182393,0.417702,...,0.173274,0.389211,0.226473,0.186596,0.414625,0.258777,0.361851,0.219189,0.231897,pass
14,0.101418,0.124436,0.255149,0.086661,0.197906,0.167045,0.140745,0.272604,0.204882,0.406659,...,0.221080,0.360513,0.237015,0.226033,0.361485,0.227236,0.415726,0.276355,0.268079,pass
15,0.118978,0.069188,0.205745,0.158148,0.261675,0.165614,0.082553,0.155620,0.135646,0.327041,...,0.154790,0.329093,0.231507,0.224171,0.329329,0.273749,0.325146,0.204758,0.258137,pass
16,0.064569,0.062619,0.155348,0.076683,0.145721,0.102620,0.066503,0.132059,0.109413,0.265402,...,0.103053,0.268659,0.148506,0.118408,0.256421,0.160696,0.195701,0.137073,0.144224,pass
17,0.117328,0.087892,0.250934,0.142016,0.267620,0.188334,0.143358,0.233136,0.162021,0.464898,...,0.216093,0.451656,0.273456,0.217050,0.395063,0.274680,0.418238,0.268330,0.263960,pass
18,0.109457,0.138444,0.278949,0.121213,0.233734,0.171472,0.172840,0.306149,0.223492,0.442497,...,0.261465,0.404002,0.260936,0.246656,0.416960,0.271487,0.449180,0.318051,0.295915,pass
19,0.103844,0.144825,0.296628,0.102595,0.212660,0.170740,0.104753,0.214757,0.221347,0.444385,...,0.171966,0.393870,0.248241,0.204909,0.407445,0.253501,0.356198,0.229105,0.244269,pass

[[1.42129859 1.12482032 1.1806127  1.1569582  1.13476498 1.26043367
  1.39120026 1.23860126 1.08920797 1.0995782  1.08987853 1.16876958
  1.14581286 1.15350609 1.10009837 1.09373311 1.15442643 1.28102874
  1.13314267 1.1896779  1.12293067 1.12057165 1.13818259 1.1143189
  1.21787461 1.1048448 ]]
BARINEL SCORES

,rx 24,rx 17,rzz 23,h 10,rzz 18,rx 25,rx 20,swap 15,h 6,rzz 11,...,rzz 7,h 3,rx 12,rzz 4,rzz 9,rx 22,h 0,rzz 13,rx 5,rx 14
sum,0.565302,0.556447,0.551723,0.54531,0.543769,0.540041,0.539985,0.537149,0.536886,0.536124,...,0.524965,0.520483,0.518895,0.517047,0.515953,0.511178,0.510784,0.508284,0.507629,0.501976

custom SCORES

,rx 25,rx 24,rzz 23,rx 19,rzz 18,rx 20,rx 17,rx 8,h 6,h 1,...,rzz 7,h 3,rx 12,rzz 9,rzz 4,rx 22,rzz 13,h 0,rx 5,rx 14
sum,0.731931,0.724267,0.714566,0.713169,0.712148,0.710139,0.707969,0.705558,0.696566,0.696414,...,0.67368,0.668584,0.668532,0.66486,0.661894,0.659031,0.653884,0.651868,0.650137,0.648649

DSTAR SCORES

,rzz 16,rzz 11,rzz 4,rzz 2,rzz 7,swap 15,rzz 23,h 3,h 10,h 1,...,rx 8,rx 5,rx 12,rzz 9,rx 20,rx 24,rx 19,rx 22,rx 25,rx 14
sum,1.426559,1.223202,1.203328,1.201055,1.175912,0.692063,0.660923,0.591862,0.59071,0.588102,...,0.386591,0.358317,0.346127,0.345657,0.286764,0.160367,0.155517,0.146383,0.120304,0.108228

ERROR GATE LOCATION:
15
Now evolving the following mutant:  AddGate_rx_inGap_19_.qasm

100%|██████████| 10/10 [01:44<00:00, 10.48s/it]
100%|██████████| 10/10 [01:35<00:00,  9.51s/it]

,rx 25,rx 24,rzz 23,rx 22,rzz 21,rx 20,rx 19,rx 18,rzz 17,rx 16,...,rx 8,rzz 7,h 6,rx 5,rzz 4,h 3,rzz 2,h 1,h 0,pass/fail
0,0.130641,0.106464,0.272116,0.127394,0.246273,0.193704,0.155795,0.471288,0.254852,0.187954,...,0.269112,0.429736,0.278951,0.230328,0.483369,0.307789,0.458798,0.322823,0.288330,fail
1,0.149774,0.142184,0.323454,0.158206,0.292515,0.221038,0.203896,0.612887,0.331572,0.238950,...,0.336120,0.518742,0.349247,0.309446,0.563096,0.378471,0.488691,0.408091,0.371766,fail
2,0.125000,0.109647,0.272421,0.109600,0.247339,0.199956,0.127668,0.388854,0.234198,0.185178,...,0.230134,0.414347,0.269222,0.259005,0.439345,0.288978,0.442512,0.293452,0.305271,fail
3,0.125343,0.128993,0.289050,0.101593,0.225250,0.180822,0.110385,0.335230,0.246736,0.210834,...,0.201862,0.436955,0.286894,0.205873,0.448129,0.259943,0.379597,0.262432,0.252382,fail
4,0.106418,0.109062,0.257292,0.133450,0.232061,0.169662,0.131264,0.399985,0.248441,0.193855,...,0.236446,0.452221,0.279312,0.256411,0.419867,0.296196,0.448495,0.298848,0.305319,fail
5,0.111891,0.109515,0.247609,0.076831,0.200770,0.173154,0.152485,0.468219,0.273959,0.183079,...,0.254325,0.451634,0.265561,0.242625,0.390602,0.234424,0.425148,0.317178,0.285535,fail
6,0.103152,0.124377,0.264535,0.110047,0.200288,0.163897,0.158858,0.481277,0.258088,0.202751,...,0.272971,0.396244,0.292973,0.256712,0.408106,0.277900,0.441482,0.332285,0.305944,fail
7,0.132793,0.126027,0.291604,0.107632,0.214940,0.189989,0.131270,0.392831,0.249994,0.207564,...,0.230590,0.423546,0.291447,0.279325,0.432370,0.275748,0.415448,0.299070,0.321172,fail
8,0.161568,0.185220,0.384518,0.128210,0.263970,0.233699,0.147450,0.439627,0.321020,0.293120,...,0.268199,0.535643,0.397087,0.324282,0.480645,0.333764,0.468778,0.352297,0.370665,fail
9,0.113122,0.080650,0.235233,0.108309,0.216402,0.179484,0.139833,0.421411,0.217674,0.156795,...,0.244003,0.386754,0.240784,0.227754,0.405441,0.273400,0.414566,0.295012,0.277128,fail
10,0.137821,0.104711,0.267710,0.130254,0.265119,0.193038,0.114886,0.348446,0.232809,0.180927,...,0.224018,0.440165,0.259082,0.225440,0.437478,0.295210,0.461728,0.279896,0.276754,pass
11,0.100870,0.125839,0.251084,0.127869,0.239784,0.163327,0.120482,0.359248,0.237894,0.200262,...,0.231306,0.410533,0.278219,0.243714,0.427294,0.294724,0.455194,0.286105,0.293227,pass
12,0.070484,0.082276,0.177289,0.070031,0.151815,0.114400,0.073604,0.226981,0.156599,0.135560,...,0.141671,0.286911,0.187905,0.161435,0.279364,0.183169,0.278808,0.183530,0.192014,pass
13,0.084306,0.094615,0.199110,0.101225,0.202494,0.139467,0.101898,0.303824,0.187289,0.153307,...,0.189740,0.322921,0.218205,0.211659,0.345109,0.245770,0.381956,0.236750,0.252697,pass
14,0.114579,0.128075,0.272050,0.130166,0.241116,0.172681,0.114676,0.342005,0.240085,0.212752,...,0.224887,0.442539,0.291291,0.197215,0.384521,0.290308,0.390058,0.278054,0.245078,pass
15,0.131895,0.151567,0.325479,0.131013,0.250907,0.195428,0.068569,0.201193,0.228786,0.247257,...,0.173396,0.483651,0.325697,0.280894,0.420704,0.302584,0.449239,0.248453,0.318768,pass
16,0.099070,0.086528,0.223780,0.100480,0.208190,0.160828,0.089811,0.271243,0.169919,0.147960,...,0.165146,0.316858,0.215252,0.232966,0.379811,0.251076,0.343998,0.218147,0.268075,pass
17,0.130513,0.107712,0.262653,0.136198,0.266344,0.191739,0.123786,0.374750,0.231738,0.185631,...,0.235184,0.412288,0.265814,0.186332,0.342892,0.290169,0.430816,0.283388,0.238588,pass
18,0.106865,0.128903,0.286662,0.110043,0.207970,0.168915,0.140495,0.426434,0.265702,0.212438,...,0.242904,0.433194,0.298190,0.198709,0.425911,0.264472,0.419659,0.295999,0.251239,pass
19,0.135011,0.116820,0.288347,0.155449,0.280800,0.201512,0.110761,0.331708,0.236949,0.208047,...,0.221104,0.467161,0.292859,0.231998,0.490511,0.339097,0.449269,0.280522,0.287251,pass

[[1.28258904 1.51554031 1.35496982 1.36235496 1.2501683  1.22650477
  1.39760015 1.38925934 1.25760658 1.42285925 1.19815427 1.32024595
  1.29143918 1.33634529 1.17263263 1.24142167 1.21792734 1.32135009
  1.20482298 1.34538265 1.25120406 1.25944926 1.29320499 1.11483759
  1.2827043  1.20565643]]
BARINEL SCORES

,rx 18,rx 19,rx 8,rx 14,h 1,rzz 17,rx 5,rzz 9,h 0,rzz 4,...,rzz 7,rzz 15,rx 16,rx 24,rzz 2,h 3,rzz 11,rx 12,rzz 21,rx 22
sum,0.58067,0.579419,0.55382,0.552869,0.551162,0.546511,0.544245,0.541853,0.540284,0.531969,...,0.525384,0.525244,0.522303,0.52024,0.519113,0.514959,0.514537,0.507365,0.502715,0.493319

custom SCORES

,rx 18,rx 19,rx 8,rx 14,h 1,rzz 17,rx 24,rx 5,rx 16,rzz 9,...,rx 20,h 10,rzz 7,rzz 15,h 3,rx 12,rzz 11,rzz 2,rx 22,rzz 21
sum,0.782346,0.781869,0.736768,0.73535,0.727906,0.718335,0.717351,0.714485,0.708095,0.706838,...,0.690278,0.688836,0.683633,0.682575,0.681446,0.676869,0.665378,0.663795,0.661338,0.659834

DSTAR SCORES

,rx 18,rzz 4,rzz 7,rzz 15,rzz 2,rzz 11,h 1,h 0,h 6,h 3,...,rzz 9,rzz 21,rx 12,rx 16,rx 20,rx 19,rx 14,rx 25,rx 24,rx 22
sum,1.476,1.434632,1.410176,1.39027,1.366587,1.290173,0.803907,0.753191,0.689587,0.671423,...,0.454775,0.444572,0.375502,0.357109,0.31027,0.192459,0.183915,0.142812,0.134234,0.120485

ERROR GATE LOCATION:
19
Now evolving the following mutant:  AddGate_x_inGap_26_.qasm

100%|██████████| 10/10 [01:46<00:00, 10.64s/it]
100%|██████████| 10/10 [01:35<00:00,  9.54s/it]

,rx 25,rx 24,rzz 23,rx 22,rzz 21,rx 20,rx 19,rzz 18,rx 17,rzz 16,...,rx 8,rzz 7,h 6,rx 5,rzz 4,h 3,rzz 2,h 1,h 0,pass/fail
0,0.077246,0.097603,0.196815,0.089956,0.184786,0.126132,0.096593,0.194504,0.157051,0.307908,...,0.182633,0.349537,0.218844,0.202916,0.371227,0.231572,0.393569,0.235063,0.244599,fail
1,0.140726,0.103081,0.280616,0.124497,0.261859,0.208308,0.136192,0.243624,0.186395,0.458468,...,0.240231,0.440471,0.274300,0.246072,0.465447,0.305499,0.406533,0.299784,0.297711,fail
2,0.088437,0.075817,0.192937,0.096237,0.204577,0.146902,0.108289,0.192153,0.137379,0.361813,...,0.199503,0.368563,0.206191,0.248472,0.453315,0.256291,0.430951,0.257519,0.293712,fail
3,0.090343,0.146835,0.268846,0.107444,0.217896,0.152633,0.151017,0.294116,0.227540,0.419239,...,0.264084,0.490260,0.315805,0.284118,0.506155,0.292087,0.494612,0.340344,0.336448,fail
4,0.097320,0.082737,0.207895,0.100232,0.213139,0.154142,0.114057,0.227111,0.159036,0.369835,...,0.216013,0.464165,0.231642,0.231804,0.406606,0.255709,0.413772,0.276282,0.276680,fail
5,0.096925,0.118679,0.250468,0.134620,0.239668,0.158225,0.146255,0.275582,0.203789,0.446328,...,0.268048,0.499823,0.294519,0.308615,0.459828,0.318076,0.499927,0.338918,0.358144,fail
6,0.116415,0.118410,0.254725,0.142056,0.263361,0.171199,0.115816,0.227393,0.192684,0.364842,...,0.209356,0.419456,0.272391,0.290217,0.491575,0.325986,0.384109,0.278830,0.332891,fail
7,0.135300,0.124655,0.292538,0.092337,0.230029,0.204916,0.152804,0.258008,0.203173,0.441215,...,0.264886,0.438681,0.295401,0.304636,0.496542,0.289496,0.474051,0.334219,0.351727,fail
8,0.138058,0.083275,0.248587,0.104648,0.245898,0.204647,0.137264,0.231150,0.158752,0.420157,...,0.239447,0.429063,0.243770,0.281573,0.469446,0.284824,0.459283,0.303513,0.327519,fail
9,0.124076,0.120422,0.272965,0.128066,0.251783,0.184143,0.108649,0.220935,0.196754,0.406846,...,0.203003,0.405949,0.275157,0.272787,0.459847,0.304142,0.398795,0.266917,0.315770,fail
10,0.105931,0.091763,0.212634,0.086788,0.189292,0.150265,0.094292,0.190633,0.154387,0.309861,...,0.173340,0.355771,0.217258,0.210666,0.394789,0.228397,0.336066,0.226762,0.248367,pass
11,0.081873,0.103975,0.225179,0.100112,0.190254,0.135477,0.122952,0.209720,0.169475,0.376456,...,0.211469,0.333154,0.242681,0.208962,0.400931,0.246399,0.348122,0.258397,0.250726,pass
12,0.103208,0.132979,0.256816,0.117448,0.252095,0.169161,0.135818,0.266183,0.211245,0.380288,...,0.243481,0.447060,0.291884,0.244005,0.427450,0.294642,0.421309,0.307047,0.294311,pass
13,0.054211,0.053262,0.119472,0.029086,0.087225,0.077931,0.043400,0.089679,0.079938,0.153642,...,0.078779,0.152687,0.109556,0.083114,0.160849,0.089683,0.163945,0.100803,0.098613,pass
14,0.151782,0.143570,0.330961,0.092865,0.229689,0.221540,0.179369,0.316990,0.235992,0.473961,...,0.303006,0.515184,0.339861,0.279503,0.425831,0.282331,0.474355,0.374553,0.327030,pass
15,0.096292,0.074957,0.204551,0.112331,0.206941,0.150192,0.115218,0.192561,0.143269,0.375331,...,0.207964,0.379667,0.217794,0.257361,0.433748,0.273950,0.388724,0.264179,0.298221,pass
16,0.070225,0.126544,0.242832,0.098895,0.168934,0.121409,0.137458,0.254520,0.199963,0.411022,...,0.244592,0.405591,0.279572,0.190241,0.397457,0.238500,0.453695,0.294381,0.242902,pass
17,0.094564,0.085017,0.227998,0.088417,0.194905,0.158396,0.094384,0.187860,0.159220,0.415297,...,0.182463,0.393777,0.232324,0.228630,0.393903,0.241717,0.369656,0.240188,0.266950,pass
18,0.120290,0.118565,0.261651,0.092993,0.209450,0.173015,0.101518,0.205254,0.186807,0.360815,...,0.187844,0.352328,0.258190,0.230749,0.437200,0.251969,0.384843,0.245340,0.271317,pass
19,0.118121,0.119832,0.283438,0.120591,0.235806,0.189106,0.185418,0.294685,0.207739,0.466808,...,0.306624,0.467943,0.308838,0.262365,0.422857,0.305776,0.432786,0.365829,0.312877,pass

[[1.27371887 1.37034862 1.18609916 1.26825101 1.13861444 1.21728773
  1.2060918  1.24384285 1.24846945 1.14713099 1.16220936 1.17037268
  1.15815185 1.18921742 1.09168142 1.16278078 1.1943335  1.17194756
  1.16076904 1.20168387 1.15533668 1.10514403 1.13834544 1.14777861
  1.16103287 1.14233307]]
BARINEL SCORES

,x 15,rx 14,rzz 13,rx 5,h 0,rx 22,rzz 21,rzz 4,h 3,rx 12,...,h 10,h 1,rzz 16,rzz 18,rx 8,h 6,rx 19,rzz 23,rx 17,rx 24
sum,0.563204,0.559037,0.552533,0.548863,0.545583,0.543835,0.540724,0.540411,0.538585,0.53811,...,0.524593,0.522635,0.517692,0.517111,0.516676,0.512687,0.511529,0.510437,0.510435,0.50496

custom SCORES

,x 15,rx 14,rx 22,rzz 13,rx 5,h 0,rx 12,rzz 21,rzz 9,rx 25,...,rx 24,rzz 18,h 10,h 1,rx 17,rx 8,h 6,rzz 16,rx 19,rzz 23
sum,0.726844,0.722607,0.716265,0.712512,0.707394,0.701393,0.698092,0.694644,0.693325,0.693205,...,0.677953,0.677913,0.677089,0.674334,0.669751,0.668056,0.666708,0.666157,0.665766,0.661794

DSTAR SCORES

,rzz 4,x 15,rzz 2,rzz 11,rzz 7,rzz 16,h 0,h 1,h 3,rzz 13,...,rzz 9,rx 8,rx 12,rx 17,rx 20,rx 14,rx 19,rx 22,rx 25,rx 24
sum,1.509627,1.493909,1.377374,1.369461,1.343269,1.163933,0.779419,0.67782,0.658511,0.645084,...,0.444598,0.43093,0.358625,0.282746,0.253616,0.209153,0.143189,0.114686,0.111007,0.1039

ERROR GATE LOCATION:
15
Now evolving the following mutant:  AddGate_ry_inGap_21_.qasm

100%|██████████| 10/10 [01:55<00:00, 11.59s/it]
100%|██████████| 10/10 [01:38<00:00,  9.87s/it]

,rx 25,rx 24,rzz 23,rx 22,rzz 21,ry 20,rx 19,rx 18,rzz 17,rx 16,...,rx 8,rzz 7,h 6,rx 5,rzz 4,h 3,rzz 2,h 1,h 0,pass/fail
0,0.159849,0.119372,0.297235,0.114904,0.261255,0.147743,0.110834,0.147163,0.249380,0.192968,...,0.242672,0.392795,0.282167,0.261174,0.494524,0.300988,0.455451,0.303198,0.311512,fail
1,0.121290,0.130299,0.291357,0.127366,0.247905,0.126339,0.083403,0.135446,0.273149,0.218611,...,0.229128,0.473918,0.302362,0.225265,0.433796,0.291658,0.410380,0.294995,0.275260,fail
2,0.124441,0.138252,0.301858,0.123731,0.244346,0.129288,0.087933,0.124498,0.261355,0.225907,...,0.217676,0.457761,0.310228,0.243253,0.480774,0.299814,0.433485,0.284516,0.293289,fail
3,0.115600,0.109160,0.258723,0.106895,0.237713,0.118631,0.078101,0.105056,0.221439,0.183719,...,0.189229,0.405928,0.257194,0.211755,0.431402,0.270209,0.380171,0.249106,0.257729,fail
4,0.118378,0.104718,0.263121,0.114129,0.240454,0.121724,0.080953,0.152381,0.275051,0.191784,...,0.245408,0.472141,0.276201,0.195616,0.423867,0.277223,0.375601,0.303018,0.247316,fail
5,0.158913,0.074240,0.265417,0.086457,0.234786,0.139880,0.110219,0.122001,0.209033,0.148494,...,0.202812,0.408581,0.229355,0.197943,0.463525,0.253304,0.388352,0.257165,0.244200,fail
6,0.142074,0.087513,0.258261,0.087292,0.215716,0.128329,0.096485,0.141184,0.221158,0.155763,...,0.221062,0.355198,0.237133,0.207208,0.419826,0.250727,0.365144,0.270544,0.250821,fail
7,0.120974,0.113278,0.254228,0.142617,0.278260,0.125662,0.084160,0.129926,0.228733,0.186615,...,0.227495,0.390139,0.268156,0.273639,0.493633,0.336596,0.444073,0.289776,0.325956,fail
8,0.139559,0.104781,0.264381,0.100118,0.237010,0.132401,0.095287,0.125590,0.233052,0.181203,...,0.227523,0.429478,0.264016,0.287328,0.444720,0.285088,0.483915,0.298633,0.333904,fail
9,0.112607,0.130484,0.288384,0.113748,0.222516,0.120187,0.076382,0.109797,0.234365,0.214160,...,0.197358,0.416914,0.291688,0.228496,0.472866,0.283779,0.395767,0.261967,0.276312,fail
10,0.064925,0.131308,0.237648,0.127896,0.210048,0.088074,0.043896,0.132505,0.269525,0.213036,...,0.227227,0.446319,0.285151,0.192829,0.464694,0.286554,0.369953,0.281365,0.245302,pass
11,0.124473,0.088639,0.243808,0.135316,0.254419,0.124900,0.084775,0.185747,0.295420,0.175378,...,0.301151,0.516499,0.272158,0.283705,0.447419,0.316466,0.507202,0.369507,0.339995,pass
12,0.124078,0.125291,0.275091,0.088678,0.247038,0.126063,0.085833,0.133317,0.263389,0.198283,...,0.236674,0.448513,0.279208,0.219158,0.427942,0.263684,0.516766,0.296228,0.271940,pass
13,0.089575,0.114909,0.222939,0.102211,0.195315,0.096070,0.063649,0.083387,0.191716,0.178206,...,0.168780,0.342882,0.239588,0.234593,0.377582,0.242442,0.407395,0.224810,0.272252,pass
14,0.050789,0.063186,0.135177,0.049869,0.126042,0.057433,0.034934,0.062278,0.132814,0.104004,...,0.111115,0.247609,0.145123,0.130689,0.218496,0.141224,0.209068,0.147134,0.152951,pass
15,0.089625,0.077967,0.204458,0.134831,0.263125,0.102298,0.065652,0.075080,0.162645,0.147376,...,0.158860,0.375671,0.212868,0.230664,0.486359,0.300412,0.405537,0.216512,0.280132,pass
16,0.103650,0.153802,0.287815,0.141571,0.240369,0.116434,0.073655,0.112254,0.234323,0.231257,...,0.198794,0.363195,0.303787,0.219124,0.401687,0.297703,0.372885,0.258118,0.266112,pass
17,0.066632,0.099445,0.204521,0.097603,0.189638,0.083343,0.046687,0.102482,0.226407,0.175308,...,0.189081,0.446234,0.244108,0.223027,0.369028,0.247628,0.390181,0.252263,0.264515,pass
18,0.129440,0.095949,0.257763,0.105742,0.223835,0.123867,0.091351,0.116934,0.216163,0.176367,...,0.201130,0.398844,0.253907,0.225187,0.463200,0.273841,0.390407,0.260219,0.272682,pass
19,0.073622,0.115746,0.233679,0.099052,0.183003,0.089305,0.049963,0.134324,0.254986,0.191162,...,0.222008,0.420159,0.265463,0.191039,0.380674,0.238775,0.391432,0.275934,0.236264,pass

[[1.21679556 1.24316968 1.10048011 1.2764962  1.14985164 1.14513178
  1.2263679  1.17846838 1.14284746 1.18946921 1.12312227 1.31110686
  1.1879095  1.23094932 1.10683912 1.12017227 1.15650315 1.11530734
  1.12760968 1.14117172 1.23227885 1.08473636 1.18129217 1.17104438
  1.07787866 1.18561348]]
BARINEL SCORES

,rx 25,rx 19,ry 20,h 10,rzz 23,rx 18,rzz 21,rzz 4,rzz 15,h 3,...,h 0,rx 14,rzz 17,rx 12,rx 16,rzz 7,rzz 9,rzz 2,rx 24,rx 22
sum,0.588966,0.585278,0.561444,0.552426,0.543606,0.53182,0.531533,0.530354,0.526434,0.522046,...,0.519761,0.51862,0.517117,0.515596,0.51475,0.511995,0.510903,0.510596,0.510525,0.507838

custom SCORES

,rx 25,rx 19,ry 20,h 10,rzz 23,rx 14,rx 18,rzz 21,rx 5,h 3,...,h 6,rx 24,rx 16,rx 8,rzz 11,rzz 17,h 1,rzz 2,rzz 9,rzz 7
sum,0.768129,0.76472,0.722176,0.707129,0.693163,0.688611,0.688504,0.68433,0.680546,0.676218,...,0.66938,0.669193,0.66782,0.667559,0.66551,0.664863,0.661892,0.660079,0.658618,0.656328

DSTAR SCORES

,rzz 4,rzz 11,rzz 7,rzz 2,rzz 15,h 3,h 0,h 1,rzz 23,h 6,...,rzz 9,rx 12,rx 16,rx 25,rx 14,ry 20,rx 18,rx 22,rx 24,rx 19
sum,1.480639,1.305566,1.261179,1.223154,1.155082,0.643919,0.62938,0.628871,0.611551,0.591155,...,0.361872,0.360225,0.305931,0.158084,0.155012,0.151218,0.150109,0.112631,0.11176,0.076762

ERROR GATE LOCATION:
20
Now evolving the following mutant:  AddGate_rzz_inGap_11_.qasm

100%|██████████| 10/10 [01:36<00:00,  9.61s/it]
100%|██████████| 10/10 [01:40<00:00, 10.03s/it]

,rx 25,rx 24,rzz 23,rx 22,rzz 21,rx 20,rx 19,rzz 18,rx 17,rzz 16,...,rx 8,rzz 7,h 6,rx 5,rzz 4,h 3,rzz 2,h 1,h 0,pass/fail
0,0.120112,0.123703,0.285584,0.110507,0.233356,0.187212,0.151188,0.288101,0.215162,0.473242,...,0.264167,0.492443,0.284606,0.247368,0.457369,0.282054,0.504851,0.335689,0.305603,fail
1,0.103324,0.097775,0.246102,0.135035,0.245310,0.163701,0.118650,0.229915,0.178355,0.432622,...,0.206072,0.411411,0.240204,0.155490,0.409668,0.280566,0.393493,0.259723,0.214264,fail
2,0.099668,0.122476,0.251746,0.089398,0.194491,0.154349,0.126915,0.248657,0.197761,0.377306,...,0.213963,0.404560,0.242545,0.208161,0.324134,0.227056,0.375388,0.280066,0.251289,fail
3,0.096412,0.118454,0.242460,0.120195,0.243477,0.160753,0.156483,0.269116,0.193277,0.385471,...,0.256721,0.427971,0.257285,0.257229,0.485305,0.306358,0.426406,0.325862,0.312593,fail
4,0.082284,0.134518,0.251611,0.096549,0.194263,0.141015,0.135107,0.260782,0.207646,0.403131,...,0.228886,0.416584,0.243610,0.238832,0.372231,0.243997,0.421123,0.294677,0.283009,fail
5,0.087714,0.086903,0.205698,0.090425,0.181171,0.138051,0.114969,0.218833,0.154305,0.349446,...,0.196623,0.392324,0.208690,0.203995,0.378379,0.228524,0.371310,0.255693,0.245532,fail
6,0.111917,0.164064,0.318697,0.139811,0.261196,0.182668,0.168958,0.328940,0.259405,0.488244,...,0.283484,0.501444,0.310351,0.234329,0.505583,0.328953,0.501475,0.356821,0.301916,fail
7,0.113671,0.157422,0.299938,0.123769,0.232695,0.167565,0.106418,0.249352,0.237267,0.421800,...,0.196671,0.420438,0.282354,0.285017,0.539628,0.304960,0.432651,0.277337,0.333739,fail
8,0.083480,0.142386,0.255948,0.115457,0.215357,0.138884,0.113365,0.242143,0.212646,0.380766,...,0.200206,0.396022,0.247222,0.234289,0.442020,0.272078,0.436067,0.269624,0.282426,fail
9,0.118606,0.128308,0.287961,0.132586,0.267900,0.183458,0.112209,0.257716,0.216156,0.459665,...,0.212910,0.480436,0.283391,0.215411,0.454448,0.306413,0.455574,0.282501,0.272060,fail
10,0.093535,0.099350,0.228333,0.084328,0.194524,0.153367,0.134107,0.216962,0.158393,0.374396,...,0.207075,0.312204,0.214452,0.196726,0.378917,0.229930,0.375631,0.263491,0.243809,pass
11,0.079686,0.072356,0.179766,0.081586,0.159092,0.123911,0.086454,0.158250,0.129577,0.303755,...,0.155558,0.296065,0.180329,0.184539,0.328773,0.205432,0.290808,0.205779,0.219967,pass
12,0.119827,0.084678,0.227030,0.092545,0.189803,0.169790,0.094706,0.182849,0.152338,0.346971,...,0.169724,0.333603,0.222860,0.206049,0.398019,0.236351,0.345823,0.226904,0.249444,pass
13,0.081469,0.064567,0.166437,0.067061,0.133775,0.117883,0.089526,0.149726,0.110978,0.266332,...,0.147421,0.242229,0.155551,0.164138,0.281132,0.165163,0.288261,0.190518,0.196218,pass
14,0.063086,0.078380,0.156340,0.041274,0.098923,0.090370,0.066065,0.153107,0.123521,0.213579,...,0.115853,0.254669,0.146193,0.106768,0.204803,0.117341,0.207438,0.152305,0.130633,pass
15,0.138923,0.114233,0.272345,0.104895,0.240289,0.203005,0.144666,0.259507,0.191522,0.397835,...,0.248770,0.425413,0.281157,0.273523,0.432422,0.287178,0.465948,0.319909,0.322284,pass
16,0.105683,0.128227,0.278621,0.081246,0.188735,0.172186,0.137976,0.272429,0.216244,0.466914,...,0.255012,0.492216,0.263899,0.281404,0.488255,0.254829,0.550654,0.336778,0.335412,pass
17,0.150772,0.105168,0.283636,0.089695,0.236177,0.218116,0.125095,0.241244,0.186488,0.415529,...,0.229249,0.438814,0.271256,0.224114,0.466404,0.263881,0.482314,0.296550,0.280311,pass
18,0.108324,0.116680,0.248965,0.101229,0.200968,0.159937,0.126436,0.217700,0.180651,0.360156,...,0.205438,0.309199,0.237166,0.190422,0.419311,0.250594,0.365729,0.258821,0.239614,pass
19,0.079597,0.054657,0.156881,0.100795,0.194054,0.127088,0.099755,0.164781,0.106320,0.290221,...,0.166691,0.280900,0.166557,0.164450,0.322995,0.226575,0.304867,0.211845,0.207744,pass

[[1.1808253  1.2857597  1.20456637 1.21181664 1.18058219 1.15730461
  1.29542905 1.26829752 1.25196526 1.17037317 1.30495382 1.272493
  1.21951133 1.14535895 1.15702885 1.13791458 1.16206118 1.25451918
  1.15443393 1.19353759 1.25000917 1.2351961  1.1828747  1.16908641
  1.21450601 1.19089205]]
BARINEL SCORES

,rx 24,rx 22,rx 17,rzz 18,rx 13,rzz 7,h 3,rzz 21,rzz 10,rzz 14,...,rzz 9,rx 19,rzz 2,rzz 4,rx 15,h 0,rx 5,h 11,rx 20,rx 25
sum,0.58151,0.577333,0.571106,0.56258,0.562334,0.561995,0.554171,0.552718,0.551632,0.549743,...,0.542777,0.541402,0.540075,0.540034,0.538832,0.536057,0.533704,0.529659,0.513003,0.499089

custom SCORES

,rx 24,rx 22,rx 17,rzz 18,rx 13,rzz 14,rzz 7,h 3,rx 19,rzz 21,...,rzz 10,rzz 4,rzz 12,rx 5,rzz 9,rzz 2,h 0,h 11,rx 20,rx 25
sum,0.76843,0.752238,0.749857,0.74096,0.733778,0.724629,0.724192,0.71805,0.716739,0.715851,...,0.708559,0.706796,0.706376,0.700488,0.700462,0.697924,0.695653,0.682867,0.661428,0.646423

DSTAR SCORES

,rzz 7,rzz 4,rzz 2,rzz 12,rzz 16,rzz 10,h 1,h 0,h 3,rzz 23,...,rx 8,rzz 9,rx 17,rx 13,rx 20,rx 19,rx 24,rx 15,rx 22,rx 25
sum,1.40954,1.391012,1.363412,1.300325,1.295284,1.17678,0.6926,0.63206,0.631982,0.573845,...,0.429069,0.427614,0.371503,0.368533,0.226846,0.153186,0.149126,0.146837,0.122742,0.093883

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_z_inGap_23_.qasm

100%|██████████| 10/10 [01:37<00:00,  9.73s/it]
100%|██████████| 10/10 [01:33<00:00,  9.39s/it]

,rx 25,rx 24,rzz 23,z 22,rx 21,rzz 20,rx 19,rx 18,rzz 17,rx 16,...,rx 8,rzz 7,h 6,rx 5,rzz 4,h 3,rzz 2,h 1,h 0,pass/fail
0,0.122630,0.083270,0.241482,0.102192,0.091190,0.201720,0.180632,0.131373,0.230567,0.157143,...,0.219268,0.407036,0.234834,0.182476,0.360769,0.230419,0.369451,0.269719,0.226934,fail
1,0.128290,0.153148,0.308904,0.106908,0.150567,0.282045,0.192786,0.140986,0.297030,0.248786,...,0.253272,0.501787,0.339445,0.253157,0.492195,0.339243,0.411957,0.321252,0.308514,fail
2,0.124787,0.107211,0.262499,0.103989,0.095364,0.221151,0.183247,0.108937,0.216888,0.180649,...,0.193086,0.398949,0.255352,0.230672,0.461619,0.261980,0.349525,0.252933,0.269830,fail
3,0.124492,0.079576,0.232182,0.103744,0.075474,0.197099,0.181281,0.109639,0.184480,0.139593,...,0.195001,0.332259,0.208784,0.208204,0.372322,0.219953,0.381081,0.243683,0.248141,fail
4,0.116939,0.074283,0.221619,0.097449,0.091139,0.219098,0.175272,0.093411,0.168677,0.131014,...,0.166981,0.310922,0.193330,0.161639,0.377193,0.233311,0.342750,0.207777,0.204032,fail
5,0.111846,0.094987,0.244687,0.093205,0.051888,0.160781,0.168658,0.078940,0.196271,0.166131,...,0.154742,0.391903,0.229275,0.160088,0.305464,0.166294,0.340680,0.205587,0.192672,fail
6,0.124154,0.112471,0.270869,0.103462,0.099164,0.226447,0.188682,0.134787,0.240766,0.191611,...,0.241968,0.429897,0.275207,0.235138,0.422303,0.268977,0.424555,0.299279,0.281814,fail
7,0.127127,0.136594,0.297537,0.105939,0.105011,0.233871,0.194978,0.143795,0.253285,0.212707,...,0.242336,0.394104,0.301207,0.280141,0.448013,0.290937,0.415133,0.307891,0.323535,fail
8,0.121019,0.134749,0.286312,0.100849,0.108090,0.222554,0.179057,0.128626,0.270867,0.221390,...,0.226051,0.464831,0.303010,0.224359,0.403328,0.263842,0.385606,0.290076,0.269561,fail
9,0.133787,0.123191,0.279210,0.111489,0.141538,0.274175,0.189848,0.095240,0.220696,0.204185,...,0.195197,0.442449,0.280560,0.248618,0.521315,0.328557,0.409110,0.261400,0.299014,fail
10,0.128175,0.118310,0.275058,0.106813,0.166896,0.298826,0.197661,0.175608,0.286141,0.205311,...,0.307706,0.471584,0.303782,0.273795,0.477412,0.361787,0.502070,0.368072,0.336878,pass
11,0.130790,0.112786,0.264827,0.108992,0.129072,0.253369,0.184982,0.085225,0.199645,0.188663,...,0.185355,0.403371,0.258860,0.211748,0.411213,0.288220,0.426322,0.242488,0.259653,pass
12,0.100032,0.136996,0.265653,0.083360,0.128848,0.244160,0.160520,0.163526,0.286631,0.214852,...,0.286397,0.439008,0.303341,0.231483,0.431687,0.299675,0.479987,0.340479,0.288813,pass
13,0.043747,0.046009,0.116003,0.036456,0.040848,0.095314,0.083250,0.054378,0.107804,0.085270,...,0.098753,0.213609,0.124094,0.128793,0.238091,0.128605,0.200596,0.131385,0.150025,pass
14,0.138638,0.124857,0.305764,0.115532,0.134618,0.266569,0.208419,0.125829,0.237858,0.207456,...,0.231431,0.418267,0.295883,0.267028,0.450510,0.316062,0.446639,0.295450,0.315167,pass
15,0.077751,0.056065,0.154206,0.064792,0.076521,0.154663,0.121013,0.078610,0.154924,0.112340,...,0.162188,0.332095,0.167590,0.198181,0.273222,0.190846,0.337300,0.208183,0.228173,pass
16,0.052885,0.100883,0.186706,0.044071,0.082324,0.132980,0.092511,0.078387,0.185415,0.163695,...,0.157697,0.353832,0.221081,0.202683,0.322938,0.192721,0.343407,0.211855,0.233816,pass
17,0.100795,0.077982,0.207382,0.083996,0.079329,0.187766,0.154421,0.118967,0.191985,0.136832,...,0.205922,0.339416,0.205448,0.223827,0.404534,0.227867,0.377416,0.255986,0.262978,pass
18,0.094614,0.125112,0.243799,0.078845,0.091977,0.171417,0.138213,0.098541,0.214997,0.191521,...,0.188303,0.355972,0.258065,0.216846,0.388309,0.232131,0.379333,0.242567,0.254987,pass
19,0.084636,0.079737,0.197869,0.070530,0.091464,0.179343,0.132646,0.109473,0.207545,0.142562,...,0.197832,0.372430,0.206525,0.148786,0.363170,0.212528,0.382978,0.238513,0.195369,pass

[[1.08323383 1.39291097 1.16774563 1.08323383 1.49161028 1.25972322
  1.06287193 1.23351539 1.30303446 1.34246102 1.12305183 1.36248149
  1.30627518 1.37939246 1.154853   1.13112352 1.23020273 1.21304728
  1.23163898 1.29509461 1.28240979 1.25180132 1.30301979 1.10854214
  1.20789798 1.23296265]]
BARINEL SCORES

,rx 25,z 22,rx 19,rzz 23,h 10,rzz 11,rzz 15,rzz 20,rx 16,rx 24,...,h 1,rx 12,rx 14,h 0,rx 5,rzz 13,rx 8,rzz 9,rzz 2,rx 21
sum,0.564699,0.564699,0.554534,0.544013,0.543827,0.534319,0.531227,0.530134,0.52923,0.529049,...,0.511995,0.511039,0.510423,0.509533,0.509483,0.509254,0.508069,0.498366,0.497002,0.496929

custom SCORES

,rx 25,z 22,rx 24,rx 16,rzz 23,rx 19,h 6,h 10,rzz 20,rzz 17,...,rx 21,rzz 15,rx 18,rzz 13,rx 5,h 1,h 0,rx 8,rzz 9,rzz 2
sum,0.717624,0.717624,0.713279,0.706847,0.70283,0.701884,0.69872,0.697611,0.69709,0.694341,...,0.682235,0.680376,0.67659,0.67556,0.672825,0.666604,0.666592,0.662146,0.651639,0.634739

DSTAR SCORES

,rzz 4,rzz 11,rzz 7,rzz 15,rzz 2,h 10,rzz 23,h 1,h 6,h 0,...,rzz 9,rx 12,rx 16,rx 19,rx 25,rx 14,rx 18,rx 24,z 22,rx 21
sum,1.260311,1.238458,1.211613,1.183362,1.057054,0.595209,0.572763,0.564297,0.556487,0.549713,...,0.315324,0.300653,0.294835,0.293296,0.13928,0.127351,0.122553,0.110109,0.098144,0.092446

ERROR GATE LOCATION:
22
Now evolving the following mutant:  AddGate_s_inGap_20_.qasm

100%|██████████| 10/10 [01:39<00:00,  9.99s/it]
100%|██████████| 10/10 [01:34<00:00,  9.46s/it]

,rx 25,rx 24,rzz 23,rx 22,rzz 21,rx 20,sdg 19,rx 18,rzz 17,rx 16,...,rx 8,rzz 7,h 6,rx 5,rzz 4,h 3,rzz 2,h 1,h 0,pass/fail
0,0.144859,0.098341,0.281245,0.122849,0.258363,0.214342,0.379202,0.091063,0.189660,0.176643,...,0.184859,0.398114,0.255589,0.241550,0.483197,0.296524,0.447649,0.247081,0.292146,fail
1,0.126387,0.121687,0.271841,0.111626,0.253052,0.192854,0.345828,0.136195,0.253089,0.192269,...,0.230996,0.415751,0.275411,0.235282,0.413591,0.284911,0.391553,0.291460,0.281263,fail
2,0.101991,0.116632,0.248910,0.089626,0.196436,0.156747,0.284361,0.103614,0.221147,0.182406,...,0.183620,0.376152,0.253480,0.212714,0.370517,0.230172,0.348559,0.244058,0.251395,fail
3,0.152063,0.136353,0.324734,0.126621,0.253999,0.218554,0.390891,0.159801,0.292531,0.224852,...,0.261263,0.467348,0.322348,0.241468,0.401763,0.296414,0.412074,0.328912,0.292226,fail
4,0.133028,0.143101,0.307610,0.111886,0.253849,0.202428,0.365237,0.142734,0.286945,0.228956,...,0.245365,0.493732,0.319705,0.220779,0.442022,0.287877,0.411825,0.309513,0.271911,fail
5,0.143258,0.125542,0.293916,0.148747,0.293162,0.212967,0.386974,0.153135,0.274786,0.208079,...,0.271188,0.476285,0.304382,0.295541,0.520277,0.355252,0.501368,0.345657,0.354916,fail
6,0.113080,0.108662,0.259885,0.117760,0.246386,0.182138,0.336081,0.127746,0.232203,0.184370,...,0.233175,0.417566,0.270623,0.258081,0.431554,0.293845,0.461969,0.296971,0.308436,fail
7,0.135310,0.128496,0.308119,0.133617,0.256540,0.200841,0.370246,0.135783,0.240104,0.211874,...,0.235974,0.412861,0.305288,0.261082,0.464967,0.315855,0.446042,0.300288,0.311783,fail
8,0.153712,0.116551,0.305885,0.113782,0.250938,0.220815,0.390991,0.120849,0.233218,0.197872,...,0.228047,0.453399,0.289265,0.272209,0.505388,0.298728,0.495177,0.295656,0.324131,fail
9,0.172101,0.134775,0.341909,0.153840,0.313420,0.248579,0.442996,0.137494,0.272869,0.234067,...,0.254316,0.503717,0.335487,0.296093,0.533105,0.367181,0.456683,0.327122,0.351694,fail
10,0.092311,0.099491,0.218916,0.106976,0.196002,0.146048,0.265570,0.113970,0.217974,0.167387,...,0.207818,0.388739,0.238855,0.219816,0.425636,0.251682,0.440646,0.264888,0.270109,pass
11,0.111236,0.135441,0.284653,0.158601,0.255202,0.168557,0.318923,0.108218,0.222657,0.216727,...,0.203772,0.401230,0.299150,0.280371,0.434780,0.324542,0.408294,0.272624,0.325160,pass
12,0.128986,0.125517,0.290015,0.123212,0.247219,0.195132,0.352453,0.144681,0.255671,0.204684,...,0.259433,0.419003,0.294603,0.255909,0.449589,0.295055,0.509943,0.322434,0.311365,pass
13,0.123105,0.118544,0.275301,0.108032,0.225587,0.185897,0.337392,0.152795,0.302175,0.213268,...,0.267318,0.553847,0.303320,0.205901,0.389497,0.266893,0.427355,0.330230,0.258050,pass
14,0.083922,0.143482,0.248935,0.097930,0.190374,0.132728,0.256049,0.118252,0.254600,0.213115,...,0.207223,0.425483,0.286160,0.227878,0.419872,0.250057,0.393057,0.272821,0.271660,pass
15,0.109225,0.101198,0.229767,0.112814,0.218327,0.158237,0.287960,0.099557,0.222798,0.174635,...,0.196218,0.441420,0.245981,0.222010,0.383872,0.260212,0.405431,0.257231,0.265328,pass
16,0.116831,0.139647,0.292627,0.150795,0.262604,0.179076,0.334684,0.141265,0.265018,0.224746,...,0.253596,0.457117,0.314984,0.237745,0.495558,0.332124,0.467291,0.316566,0.298208,pass
17,0.120322,0.102139,0.247477,0.112421,0.226049,0.176010,0.321640,0.135014,0.236196,0.171161,...,0.230910,0.385078,0.252125,0.213714,0.435799,0.278037,0.440493,0.285982,0.269548,pass
18,0.105210,0.097318,0.237012,0.103090,0.219367,0.168910,0.310161,0.136016,0.249883,0.171073,...,0.224471,0.434958,0.254752,0.241800,0.391967,0.265505,0.386470,0.287674,0.285170,pass
19,0.134211,0.120221,0.273358,0.103576,0.225694,0.192321,0.345231,0.146965,0.253731,0.193772,...,0.253750,0.401734,0.281109,0.235154,0.397755,0.278157,0.414149,0.312128,0.284367,pass

[[1.25092533 1.16328776 1.16135595 1.25037488 1.21662474 1.21242123
  1.1996195  1.22133248 1.17173982 1.14660704 1.17627231 1.19356511
  1.20344875 1.23480969 1.14936973 1.22016738 1.14665007 1.16449671
  1.14094055 1.14438936 1.16811189 1.16745575 1.21311671 1.14653571
  1.1573146  1.16752466]]
BARINEL SCORES

,rx 25,rx 20,sdg 19,h 10,rzz 11,rzz 21,rzz 23,rx 14,rzz 15,rx 5,...,rx 16,rx 22,rx 24,rzz 9,rzz 7,h 1,rzz 2,rx 8,rx 18,rzz 17
sum,0.550063,0.546274,0.54124,0.536169,0.534194,0.531979,0.531215,0.527381,0.523497,0.519948,...,0.511376,0.510987,0.509768,0.506435,0.506094,0.505427,0.504602,0.502622,0.502242,0.501592

custom SCORES

,rx 25,rx 20,sdg 19,h 10,rzz 21,rzz 11,rzz 23,rx 14,rzz 15,h 3,...,h 6,rx 24,rx 16,rx 18,h 1,rzz 9,rzz 7,rzz 2,rx 8,rzz 17
sum,0.722085,0.711853,0.70356,0.699723,0.693784,0.687691,0.685447,0.684746,0.677441,0.676736,...,0.661152,0.658019,0.657962,0.655593,0.651662,0.65161,0.650449,0.649239,0.648947,0.648526

DSTAR SCORES

,rzz 4,rzz 7,rzz 11,rzz 2,rzz 15,sdg 19,h 0,h 3,h 1,rzz 23,...,rzz 9,h 10,rx 12,rx 20,rx 16,rx 14,rx 25,rx 18,rx 22,rx 24
sum,1.465928,1.362227,1.342031,1.337863,1.197085,1.038596,0.719762,0.715598,0.690302,0.687999,...,0.414826,0.40713,0.398317,0.359191,0.348709,0.18353,0.170133,0.151544,0.135431,0.135316

ERROR GATE LOCATION:
19
Now evolving the following mutant:  AddGate_x_inGap_30_.qasm

100%|██████████| 10/10 [01:36<00:00,  9.63s/it]
100%|██████████| 10/10 [01:32<00:00,  9.27s/it]

,x 25,rx 24,rx 23,rzz 22,rx 21,rzz 20,rx 19,rx 18,rzz 17,rx 16,...,rx 8,rzz 7,h 6,rx 5,rzz 4,h 3,rzz 2,h 1,h 0,pass/fail
0,0.431165,0.129801,0.136987,0.309185,0.140735,0.269430,0.203436,0.168367,0.308910,0.229862,...,0.306030,0.515615,0.330696,0.256020,0.444198,0.325970,0.568373,0.367988,0.318455,fail
1,0.561890,0.169155,0.122970,0.315533,0.122433,0.263444,0.230625,0.137068,0.266638,0.217094,...,0.257393,0.497141,0.311689,0.295531,0.469256,0.313933,0.488160,0.329369,0.342642,fail
2,0.437217,0.131622,0.085803,0.246520,0.135811,0.265490,0.192586,0.123475,0.229179,0.165924,...,0.235467,0.456242,0.246348,0.211181,0.440980,0.307890,0.478387,0.287984,0.268626,fail
3,0.450850,0.135727,0.120817,0.290760,0.123432,0.270175,0.206457,0.091180,0.205134,0.200234,...,0.191962,0.423894,0.280030,0.277603,0.481963,0.313724,0.442913,0.259229,0.320296,fail
4,0.526923,0.158628,0.127387,0.320233,0.088941,0.215035,0.223799,0.155590,0.269746,0.211512,...,0.272501,0.438776,0.306315,0.281631,0.466179,0.267673,0.521133,0.338179,0.331060,fail
5,0.452533,0.136233,0.167548,0.330229,0.155193,0.286433,0.201231,0.144744,0.319057,0.263352,...,0.264557,0.531675,0.355929,0.215185,0.431942,0.327182,0.466750,0.325563,0.273441,fail
6,0.392023,0.118017,0.104448,0.242112,0.106089,0.209706,0.165889,0.101932,0.212505,0.174441,...,0.197192,0.399916,0.244932,0.247627,0.398039,0.259778,0.405537,0.256283,0.287466,fail
7,0.336816,0.101397,0.123469,0.249267,0.143780,0.245687,0.151657,0.107921,0.226891,0.194396,...,0.204674,0.393354,0.267338,0.238268,0.467614,0.302671,0.436037,0.265605,0.289274,fail
8,0.424242,0.127717,0.134191,0.292544,0.096215,0.216537,0.194035,0.128507,0.259033,0.215757,...,0.240207,0.446772,0.300970,0.266068,0.386316,0.257862,0.469893,0.306340,0.308437,fail
9,0.558278,0.168068,0.147783,0.350885,0.146702,0.299437,0.245180,0.113222,0.252692,0.245161,...,0.232448,0.482060,0.335719,0.252746,0.485385,0.347441,0.492120,0.300394,0.310325,fail
10,0.290369,0.087415,0.059225,0.161902,0.052265,0.138763,0.120121,0.044921,0.103188,0.099591,...,0.089383,0.202927,0.138560,0.107647,0.217110,0.140904,0.164776,0.117434,0.127102,pass
11,0.318737,0.095955,0.107241,0.234557,0.113314,0.184080,0.138865,0.095942,0.207233,0.183398,...,0.189104,0.407374,0.255416,0.261058,0.381220,0.252284,0.373307,0.253851,0.294863,pass
12,0.272602,0.082066,0.144812,0.272718,0.126782,0.236392,0.153137,0.144821,0.275702,0.230349,...,0.245159,0.442692,0.317733,0.252927,0.448937,0.307640,0.362639,0.307758,0.298555,pass
13,0.251107,0.075595,0.096518,0.218044,0.122875,0.231441,0.144026,0.143757,0.242919,0.168312,...,0.251435,0.413836,0.249697,0.189587,0.360495,0.271563,0.430373,0.299164,0.241342,pass
14,0.253358,0.076273,0.120807,0.237183,0.084807,0.180701,0.136655,0.105051,0.201272,0.180249,...,0.185927,0.315268,0.248212,0.226929,0.398175,0.235632,0.369765,0.239981,0.265735,pass
15,0.398783,0.120052,0.111038,0.269942,0.129046,0.260524,0.190515,0.083497,0.168979,0.184332,...,0.180457,0.354815,0.262824,0.280155,0.465018,0.321244,0.416877,0.244234,0.320935,pass
16,0.414922,0.124911,0.094050,0.259419,0.099081,0.223355,0.189683,0.130367,0.231128,0.170008,...,0.228280,0.404603,0.249620,0.179212,0.383455,0.249957,0.406767,0.275504,0.228520,pass
17,0.402268,0.121101,0.077741,0.236857,0.048882,0.156287,0.179479,0.149352,0.236735,0.148467,...,0.241396,0.403799,0.231463,0.245461,0.364001,0.196400,0.384505,0.301218,0.281322,pass
18,0.309525,0.093181,0.119769,0.237464,0.093477,0.194364,0.142442,0.086140,0.180574,0.178895,...,0.161771,0.298583,0.240628,0.193723,0.328319,0.227847,0.335235,0.210025,0.228767,pass
19,0.516879,0.155605,0.134649,0.322505,0.154693,0.298834,0.225283,0.123514,0.256738,0.224177,...,0.240228,0.457690,0.311622,0.227475,0.481722,0.338716,0.482584,0.297771,0.286589,pass

[[1.22899795 1.22899795 1.31782281 1.19054328 1.23234246 1.17824966
  1.21683557 1.32363332 1.25130819 1.24355715 1.15079131 1.21764258
  1.10668696 1.17735923 1.14594483 1.19230978 1.21695076 1.27383625
  1.15948351 1.19440584 1.16265603 1.08541868 1.14889932 1.19173166
  1.21170895 1.1234078 ]]
BARINEL SCORES

,x 25,rx 24,rzz 2,rx 19,rzz 7,rx 21,h 10,rzz 17,rzz 20,rzz 9,...,h 3,h 6,h 0,rx 5,rzz 4,rzz 13,rx 14,rx 18,rzz 11,rzz 15
sum,0.571457,0.571457,0.56135,0.554289,0.553328,0.551237,0.550991,0.54784,0.546989,0.546638,...,0.54329,0.54322,0.542347,0.540128,0.538759,0.537918,0.535047,0.534598,0.529622,0.529053

custom SCORES

,x 25,rx 24,rzz 2,rx 23,rx 19,rx 21,rzz 17,rx 8,h 10,rx 16,...,h 6,rx 12,h 3,rx 14,rx 5,h 0,rzz 13,rzz 4,rzz 11,rzz 15
sum,0.747037,0.747037,0.728595,0.723188,0.722909,0.721065,0.719219,0.717349,0.715229,0.714478,...,0.705427,0.70359,0.699337,0.697921,0.697123,0.694666,0.686744,0.684953,0.681352,0.68126

DSTAR SCORES

,rzz 2,x 25,rzz 7,rzz 4,rzz 15,rzz 11,h 0,h 1,h 10,h 3,...,rx 8,rzz 9,rx 12,rx 16,rx 19,rx 24,rx 14,rx 23,rx 18,rx 21
sum,1.657064,1.55658,1.534589,1.446123,1.380057,1.371285,0.739847,0.735077,0.729393,0.729165,...,0.480446,0.458034,0.417665,0.381108,0.349375,0.171715,0.168004,0.146077,0.145669,0.143844

ERROR GATE LOCATION:
25
Now evolving the following mutant:  AddGate_y_inGap_4_.qasm

  0%|          | 0/10 [00:00<?, ?it/s]