<h1 style="text-align: center;">HEISENBERG-BASED FAULT LOCALIZATION (HBFL)</h1>

<h2 style="text-align: center;">Download Initial Dependencies</h2>

In [29]:
import numpy as np
import pandas as pd
import json
import math
from tqdm import tqdm
from qiskit.quantum_info import SparsePauliOp, Operator, Pauli, Clifford
import qiskit.qasm2 as q2
from qiskit import QuantumCircuit
from IPython.display import display

from heisenbergUtilities import *

In [30]:
# from qiskit_aer import AerSimulator
# simulator = AerSimulator()

# print(simulator.available_devices())

<h3>Download MQT Benchmark circuits.</h3>

We'll run this experiment on 11 different quantum circuits, including DJ, GHZ, GraphState, Grover No-Ancilla, QAOA, QFT, QGAN, QPE Exact, QPE Inexact, RealAmpRandom, and VQE.

<h3>Generate mutants.</h3>

We'll start with mutants that add an unnecessary gate, then add mutants that replace a certain gate later. Missing code in SBFL is still a more recent topic even in classical programs.

The mutants were downloaded from QMutBench, choosing specifically mutants that added a gate at any location with 0-10% survival scores

<h2 style="text-align: center;">CONTROL PANEL</h2>

In [31]:
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
#-------------------------------------------------------------------------GENERAL PARAMETERS---------------------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
ALG_NAME = "graphstate"
ORIGINAL_QASM = f"{ALG_NAME}_5_qubits.qasm"                                                 #| The original algorithm QASM circuit file name.                           
ORIGINAL_QASM_FOLDER = "SBFL_circuits/MQTBench/"                                            #| The folder containing the original QASM circuit file.                    
QASM_MUTANT_FOLDER = f"SBFL_circuits/QMutBenchMutants/Mutants_{ALG_NAME}_5_qubits/"         #| The folder containing all mutants related to the original QASM circuit.  
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
#-------------------------------------------------------------------------SB-QOPS PARAMETERS---------------------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
RUNS = 10                                                                                   #| Number of times SB-QOPS will run to find a failing or passing test case.            
SHOTS = 20000                                                                               #| Number of shots for SB-QOPS to use to create the compact program specification.     
EPOCH = 80                                                                                  #| Number of epochs SB-QOPS will run to navigate the search space of test cases.       
SBQOPS_TOL = 0.1                                                                            #| Tolerance value SB-QOPS uses to determine if a test case is failing or passing.     
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
#---------------------------------------------------------------------HEISENBERG SBFL PARAMETERS-----------------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
LAMBDA_WEIGHT = 1                                                                           #| The amount to adjust the "weight difference" in the heuristic           #
LAMBDA_COMP = 1                                                                             #| The amount to weigh the "composition difference" in the heuristic       #
LAMBDA_SUPPORT = 1                                                                          #| The amount to weigh the "support overlap" in the heuristic              #
LAMBDA_DIAMETER = 1                                                                         #| The amount to weigh the "diameter difference" in the heuristic          #
LAMBDA_PHASE = 1                                                                            #| The amount to weigh the "phase" in the heuristic                        #
CUSTOM_WEIGHT = 0.25                                                                        #| The amount of weight the "dstar boost" has in the custom heuristic (WIP)#
ATOL = 1e-4                                                                                 #| The tolerance value used to prune negligible magnitudes during Pauli propagation.   
MAX_TERMS = 100                                                                             #| The maximum number of terms to keep during Pauli propagation. If None, use all.     
SEARCH_STEP = 3                                                                             #| The search step size used during Pauli propagation. If None, pauli-prop uses 4.     
VERBOSE = 1                                                                                 #| A boolean value to determine if the program should print out detailed information.  
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#

Generate the linked list of all gates found in a given circuit

In [32]:
"""
LinkedListNode: A class that holds information related to a gate in a quantum circuit. 

PROPERTIES:
    - value (String): The name of the quantum gate
    - depth (int): The depth of the gate in the circuit
    - count (Int): The probability that the gate will meaningfully change the Pauli string.
    - next (LinkedListNode): The next gate in the circuit

"""

class LinkedListNode:
    def __init__(self, name="Initial", depth=0, count=0,  next=None):
        self.value = name
        self.depth = depth
        self.next = next
        self.count = count

class LinkedList:
    def __init__(self):
        self.head = None

    def append(self, name, depth):
        new_node = LinkedListNode(name, depth)
        if not self.head:
            self.head = new_node
            return
        last_node = self.head
        while last_node.next:
            last_node = last_node.next
        last_node.next = new_node

    def mark(self, depth):
        current_node = self.head
        while current_node:
            if current_node.depth == depth:
                current_node.count += 1
                return
            current_node = current_node.next

    def reset(self):
        current_node = self.head
        while current_node:
            current_node.count = 0
            current_node = current_node.next

<h3>Load correct circuit</h3>
Here we want to load the correct version of the circuit from MQT. We use this both to generate a PS_compact from/for SB-QOPS and to check results from SBFL.

In [33]:
correct_circuit = load_program(ORIGINAL_QASM, ORIGINAL_QASM_FOLDER).copy()
correct_list = LinkedList()
correct_list = construct_list(correct_list, correct_circuit, inverse=False)

<h2 style="text-align: center;"> SB-QOPS </h2>

This is where we will use SB-QOPS on a provided circuit and its mutants

For a single mutant, it took about 2 minutes to generate a 20 test suite (10 fail, 10 pass) on an RTX 4090 SUPER. It can only be run on a Linux environment since the AER Simulator does not support Windows

Expect this cell to take up to a few hours, BUT this cell should only need to be run once per algorithm with mutants under test. After it saves to the csv file at the end, this cell can be commented out as to not accidentally run it again. 

In the future if we want to test this methodology on higher qubit circuits or other algorithms, we'll likely either want to reduce the number of tests in the suite or the number of mutants we're analyzing

In [34]:
# import QOPS as qops
# from QOPS_test import get_compact_program_specification_Z
# from pathlib import Path

# ga_result = pd.DataFrame(columns=['Program',"path_to_mutant",'catch_avg','avg_fitness','failing_testcases', 'passing_testcases'])
# program_history = {}

# #program_specification = The compact program specification. SB-QOPS needs this to generate failing test cases.
# # In a public-use environment, this would be provided by the user.
# program_specification = get_compact_program_specification_Z(correct_circuit, shots=SHOTS)

# #mutants = A python list of qiskit QuantumCircuit variables with a mutation in them
# mutants = []
# mutants_names = []
# root = Path(QASM_MUTANT_FOLDER)
# for qasm_mutant in root.rglob("*.qasm"):
#     mutants.append(load_program(qasm_mutant.name, QASM_MUTANT_FOLDER))
#     mutants_names.append(qasm_mutant.name)

# for mutant_index,mutant in enumerate(mutants):
#     tester = qops.Circuit_Tester(CUT=mutant)
#     tester.set_applicable_families_Z(program_specification)
#     mutants_per_run = []
#     fitness_per_run = []
#     failing_testcases_per_run = []
#     history_per_run = []

#     print("NOW RUNNING TO FIND FAILING TESTS")
#     #For a predefined number of attempts, try to find a set of failing test cases (output is above predefined tolerance)
#     for runs in range(RUNS):
#         killed = 0
#         pauli = {}
#         fitness = 0
#         for i in range(len(tester.applicable_families)):
#             best_function,testcase, history = tester.run_mealoneplusone(i, EPOCH)
#             if best_function > SBQOPS_TOL:
#                 killed = 1
#                 pauli = testcase
#                 fitness = best_function
#                 break
#         mutants_per_run.append(killed)
#         failing_testcases_per_run.append(pauli)
#         fitness_per_run.append(fitness)
#         history_per_run.append(history)

#     avg_score = np.mean(mutants_per_run)
#     avg_fitness = np.mean(fitness_per_run)

#     #Here is our new, modified algorithm from the SB-QOPS method that attempts to find passing test cases as well. We'll need them for SBFL
#     passing_testcases_per_run = []

#     print("NOW RUNNING TO FIND PASSING TESTS")
#     for runs in range(RUNS):
#         pauli = {}
#         fitness = 0
#         for i in range(len(tester.applicable_families)):
#             best_function, testcase, history = tester.run_reverse_mealoneplusone(i,EPOCH)
#             if best_function < SBQOPS_TOL:
#                 pauli = testcase
#                 break
#         passing_testcases_per_run.append(pauli)

#     #Replace static program file with "program_name" when ready to test fully
#     """
#     ga_result: A pandas dataframe with the following columns
#         Program: Name of the mutant quantum circuit file
#         Path_To_Mutant: Path to the mutant file
#         Catch_Avg: The average number of times the mutant was identified by SB-QOPS
#         Avg_Fitness: The average fitness of the search algorithm used. Higher usually indicates higher Catch_Avg
#         Failing_Testcases: A list of dicts indicating the set of Pauli strings and the weights that should be applied to generate a failing test case
#         Passing_Testcases: A list of dicts indicating the set of Pauli strings and the weights that should be applied to generate a passing test case
#     """
#     ga_result = pd.concat([pd.DataFrame([[mutants_names[mutant_index],QASM_MUTANT_FOLDER,avg_score,avg_fitness,json.dumps(failing_testcases_per_run), json.dumps(passing_testcases_per_run)]],columns=ga_result.columns),ga_result],ignore_index=True)
#     ga_result.to_csv(f'realamprandom_ga_result', index=False)

ga_result is a slightly altered pandas Dataframe with similar structure found in SB-QOPS. The differences are changing the column "Program" to be the name of the mutant file instead of the original quantum circuit, changing "Mutant" to be the path to the mutant file instead of being an arbitrary index value, and adding a passing_testcases column that returns Pauli strings and coefficients that generate passing tests.

Now we want to run SBFL using Heisenberg evolution trees on each circuit placed in ga_result

Evolution analysis can vary widely in runtime. Some of the simplest circuits take seconds to analyze and only took upwards of 3-4 minutes to get results on the whole dataset (GHZ was the fastest taking 3 minutes to run). Other, more complex algorithms can take upwards of 6-10 minutes PER MUTANT (RealAmpRandom took longest so far with 14 hours).

The runtime of this code segment is directly tied to the depth of the circuit being analyzed and the number of 2-branching gates such as rotation or phase gates that exist in the circuit.

This is something to note in the final paper. Regardless of accuracy this methodology takes a long time to run. If results are promising, then we'll want to look into the tradeoffs between EXAM and hyperparameters to speed this up. Primarily the atol, max_terms, and search_step parameters in the evolve_pauli_exact method in HeisenbergUtilities.py

<h2 style="text-align: center;">HEISENBERG EVOLUTIONS (PAULI PROPAGATION)</h2>

In [35]:
from heisenbergTree import *

LAMBDAS = [LAMBDA_WEIGHT, LAMBDA_COMP, LAMBDA_SUPPORT, LAMBDA_DIAMETER, LAMBDA_PHASE]
ga_result = pd.read_csv(f'{ALG_NAME}_ga_result.csv')
custom_sbfl_result = pd.DataFrame(columns=['Program','path_to_mutant','best_exam_score', 'worst_exam_score', 'avg_exam_score'])
barinel_sbfl_result = pd.DataFrame(columns=['Program','path_to_mutant','best_exam_score', 'worst_exam_score', 'avg_exam_score'])
dstar_sbfl_result = pd.DataFrame(columns=['Program','path_to_mutant','best_exam_score', 'worst_exam_score', 'avg_exam_score'])
mutant_num = 0

#For each mutant of a circuit, run the SBFL implementation
for mutant, path in zip(ga_result.loc[:,"Program"], ga_result.loc[:,"path_to_mutant"]):
    print("Now evolving the following mutant: ", mutant)

    #Extract the raw test cases found for each mutant
    raw_failing_testcases = format_test_case(ga_result, mutant, mutant_num, "failing_testcases")
    raw_passing_testcases = format_test_case(ga_result, mutant, mutant_num, "passing_testcases")

    circuit_inverse = load_program(mutant,path).copy().inverse()  # Invert to track backward evolution of the operator
    forward_mutant = load_program(mutant, path).copy()

    #Create the linked list of operations in the inverse circuit
    operation_list = LinkedList()
    operation_list = construct_list(operation_list, circuit_inverse, True)

    forward_list = LinkedList()
    forward_list = construct_list(forward_list, forward_mutant, False)

    #Create list of nodes in linked list. Somewhere down the road remove the linked list implementation. It's unnecessary and giving me a headache
    node_list = []
    node = operation_list.head
    while node:
        node_list.append(node)
        node = node.next

    #Perform Pauli propagation (Heisenberg evolution) for all test cases. Returns a dataframe with all counts for all operations
    global_frame_fail = heisenberg_evolve(circuit_inverse, 
                                          operation_list, 
                                          raw_failing_testcases, 
                                          "fail", 
                                          LAMBDAS,
                                          atol = ATOL, 
                                          max_terms = MAX_TERMS, 
                                          search_step = SEARCH_STEP)
    
    global_frame_pass = heisenberg_evolve(circuit_inverse, 
                                          operation_list, 
                                          raw_passing_testcases, 
                                          "pass", 
                                          LAMBDAS,
                                          atol = ATOL, 
                                          max_terms = MAX_TERMS, 
                                          search_step = SEARCH_STEP)

    global_frame = pd.concat([global_frame_fail, global_frame_pass], ignore_index=True)

    global_frame = global_frame.drop(["Initial"],axis=1)
    if VERBOSE:
        display(global_frame)

    custom_scores = custom_sbfl(global_frame, CUSTOM_WEIGHT)
    barinel_scores = barinel(global_frame)
    dstar_scores = dstar(global_frame)

    if VERBOSE:
        print("BARINEL SCORES")
        display(barinel_scores)
        print("custom SCORES")
        display(custom_scores)
        print("DSTAR SCORES")
        display(dstar_scores)
    
    # Here is where analysis of the methodology begins. 
    # We first extract the position of the erroneous gate by comparing it to the original MQT gate
    # NOTE: This method is intended for single-added gates for now. Other types of mutants will require other methods later
    error_gate_location = find_erroneous_gate(forward_mutant, correct_circuit)

    if VERBOSE:
        print("ERROR GATE LOCATION:")
        print(error_gate_location)

    #Calculate best, worst, and average EXAM for Barinel, custom, and DStar
    barinel_best_exam, barinel_worst_exam, barinel_average_exam = calc_exams(barinel_scores, error_gate_location, circuit_inverse)
    custom_best_exam, custom_worst_exam, custom_average_exam = calc_exams(custom_scores, error_gate_location, circuit_inverse)
    dstar_best_exam, dstar_worst_exam, dstar_average_exam = calc_exams(dstar_scores, error_gate_location, circuit_inverse)

    # Here we store the results from the HBFL analysis for both barinel and custom into a csv file for later analysis.
    barinel_sbfl_result = pd.concat([pd.DataFrame([[mutant,QASM_MUTANT_FOLDER,barinel_best_exam, barinel_worst_exam, barinel_average_exam]],columns=barinel_sbfl_result.columns),barinel_sbfl_result],ignore_index=True)
    barinel_sbfl_result.to_csv(f'{ALG_NAME}_barinel_sbfl_result.csv', index=False)

    custom_sbfl_result = pd.concat([pd.DataFrame([[mutant,QASM_MUTANT_FOLDER,custom_best_exam, custom_worst_exam, custom_average_exam]],columns=custom_sbfl_result.columns),custom_sbfl_result],ignore_index=True)
    custom_sbfl_result.to_csv(f'{ALG_NAME}_custom_sbfl_result.csv', index=False)

    dstar_sbfl_result = pd.concat([pd.DataFrame([[mutant,QASM_MUTANT_FOLDER,dstar_best_exam, dstar_worst_exam, dstar_average_exam]],columns=dstar_sbfl_result.columns),dstar_sbfl_result],ignore_index=True)
    dstar_sbfl_result.to_csv(f'{ALG_NAME}_dstar_sbfl_result.csv', index=False)

    mutant_num += 1

if VERBOSE:
    display(barinel_sbfl_result)
    display(custom_sbfl_result)

Now evolving the following mutant:  AddGate_ccx_inGap_11_.qasm

100%|██████████| 3/3 [00:00<00:00,  3.03it/s]
100%|██████████| 10/10 [00:03<00:00,  3.21it/s]

,ccx 10,cz 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.450481,0.0,0.068274,0.023995,0.0,0.0,0.011479,0.012420,0.016393,0.011114,0.014266,fail
1,0.446898,0.0,0.057740,0.024625,0.0,0.0,0.009564,0.011517,0.015297,0.011712,0.013451,fail
2,0.435293,0.0,0.051863,0.027951,0.0,0.0,0.012524,0.013176,0.013969,0.010828,0.015629,fail
3,0.499356,0.0,0.078664,0.025135,0.0,0.0,0.012075,0.014451,0.022811,0.013372,0.014534,pass
4,0.529376,0.0,0.067147,0.027263,0.0,0.0,0.012448,0.014991,0.020321,0.012667,0.015407,pass
5,0.482722,0.0,0.076173,0.030895,0.0,0.0,0.014390,0.014859,0.018578,0.012429,0.016934,pass
6,0.473074,0.0,0.057610,0.023970,0.0,0.0,0.008391,0.012285,0.017400,0.009438,0.011889,pass
7,0.364630,0.0,0.060993,0.018018,0.0,0.0,0.007916,0.009480,0.016152,0.008322,0.009130,pass
8,0.393551,0.0,0.064003,0.020275,0.0,0.0,0.011886,0.010927,0.014914,0.008342,0.010945,pass
9,0.517406,0.0,0.064628,0.034064,0.0,0.0,0.013533,0.015986,0.020841,0.016173,0.017988,pass
10,0.414255,0.0,0.051456,0.022427,0.0,0.0,0.011673,0.013025,0.014829,0.012183,0.015580,pass
11,0.485326,0.0,0.083137,0.022890,0.0,0.0,0.013004,0.012849,0.018334,0.011750,0.014048,pass
12,0.443849,0.0,0.065933,0.025173,0.0,0.0,0.015617,0.013687,0.016408,0.012382,0.015604,pass

[[1.01408549        nan 1.15147692 1.09510398        nan        nan
  1.11934684 1.06508692 1.07709627 1.04403488 1.08172182]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 7,h 0,ccx 10,h 1,h 3,h 4,cz 8,cz 2,cz 9,cz 6,cz 5
sum,0.234388,0.233792,0.224499,0.223297,0.218762,0.21726,0.209855,0.201808,0.0,0.0,0.0

custom SCORES

,h 7,h 0,h 1,ccx 10,h 4,h 3,cz 8,cz 2,cz 9,cz 6,cz 5
sum,0.298558,0.297017,0.281579,0.281414,0.278057,0.277012,0.270265,0.25615,0.0,0.0,0.0

DSTAR SCORES

,ccx 10,cz 8,h 7,cz 2,h 0,h 3,h 1,h 4,cz 9,cz 6,cz 5
sum,0.233577,0.008622,0.001804,0.000655,0.000598,0.00044,0.000363,0.000361,0.0,0.0,0.0

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_p_inGap_7_.qasm

100%|██████████| 3/3 [00:00<00:00, 17.14it/s]
100%|██████████| 10/10 [00:00<00:00, 16.96it/s]

,cz 10,cz 9,h 8,cz 7,p 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.023728,0.0,0.0,0.0,0.009186,0.010986,0.0,0.006207,0.007534,fail
1,0.0,0.0,0.018639,0.0,0.0,0.0,0.010589,0.016729,0.0,0.009014,0.015892,fail
2,0.0,0.0,0.021853,0.0,0.0,0.0,0.010551,0.014083,0.0,0.013585,0.012112,fail
3,0.0,0.0,0.025784,0.0,0.0,0.0,0.012306,0.015259,0.0,0.011897,0.010434,pass
4,0.0,0.0,0.010394,0.0,0.0,0.0,0.003891,0.007660,0.0,0.003797,0.006476,pass
5,0.0,0.0,0.026881,0.0,0.0,0.0,0.008833,0.013811,0.0,0.009694,0.014759,pass
6,0.0,0.0,0.026967,0.0,0.0,0.0,0.013803,0.016843,0.0,0.012407,0.012108,pass
7,0.0,0.0,0.028104,0.0,0.0,0.0,0.008215,0.012621,0.0,0.009602,0.018199,pass
8,0.0,0.0,0.030648,0.0,0.0,0.0,0.012323,0.013532,0.0,0.006400,0.010090,pass
9,0.0,0.0,0.023322,0.0,0.0,0.0,0.014494,0.015035,0.0,0.012161,0.010496,pass
10,0.0,0.0,0.022496,0.0,0.0,0.0,0.011602,0.011795,0.0,0.005721,0.013726,pass
11,0.0,0.0,0.024653,0.0,0.0,0.0,0.007378,0.009740,0.0,0.008643,0.008835,pass
12,0.0,0.0,0.025655,0.0,0.0,0.0,0.008479,0.017661,0.0,0.012231,0.013835,pass

[[       nan        nan 1.10845503        nan        nan        nan
  1.04752862 1.20069875        nan 1.41483172 1.34156199]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 3,h 1,h 4,h 0,h 8,cz 10,cz 9,cz 7,p 6,cz 5,cz 2
sum,0.237823,0.237353,0.230357,0.230021,0.207749,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 1,h 3,h 0,h 4,h 8,cz 10,cz 9,cz 7,p 6,cz 5,cz 2
sum,0.321307,0.309211,0.307168,0.290683,0.265319,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 3,h 0,h 4,h 1,cz 10,cz 9,cz 7,p 6,cz 5,cz 2
sum,0.001271,0.000557,0.000405,0.000297,0.000268,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
6
Now evolving the following mutant:  AddGate_sx_inGap_1_.qasm

100%|██████████| 6/6 [00:00<00:00, 16.20it/s]
100%|██████████| 10/10 [00:00<00:00, 16.85it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,h 2,h 1,sxdg 0,pass/fail
0,0.0,0.0,0.030372,0.0,0.0,0.014697,0.015280,0.0,0.010081,0.017325,0.0,fail
1,0.0,0.0,0.021891,0.0,0.0,0.010048,0.016169,0.0,0.011019,0.014947,0.0,fail
2,0.0,0.0,0.027510,0.0,0.0,0.015176,0.018862,0.0,0.017291,0.015330,0.0,fail
3,0.0,0.0,0.025516,0.0,0.0,0.010037,0.013505,0.0,0.010694,0.012193,0.0,fail
4,0.0,0.0,0.022565,0.0,0.0,0.011130,0.016476,0.0,0.011742,0.015962,0.0,fail
5,0.0,0.0,0.032518,0.0,0.0,0.012903,0.017434,0.0,0.012785,0.015182,0.0,fail
6,0.0,0.0,0.022621,0.0,0.0,0.012776,0.016205,0.0,0.007057,0.018192,0.0,pass
7,0.0,0.0,0.023039,0.0,0.0,0.006629,0.007704,0.0,0.007182,0.007579,0.0,pass
8,0.0,0.0,0.024064,0.0,0.0,0.012022,0.013715,0.0,0.012116,0.011816,0.0,pass
9,0.0,0.0,0.018293,0.0,0.0,0.011955,0.012640,0.0,0.011074,0.011735,0.0,pass
10,0.0,0.0,0.017271,0.0,0.0,0.007266,0.013714,0.0,0.012909,0.013794,0.0,pass
11,0.0,0.0,0.008186,0.0,0.0,0.006844,0.009117,0.0,0.005388,0.008589,0.0,pass
12,0.0,0.0,0.023276,0.0,0.0,0.009042,0.013659,0.0,0.007466,0.011934,0.0,pass
13,0.0,0.0,0.026464,0.0,0.0,0.013980,0.020024,0.0,0.012029,0.015946,0.0,pass
14,0.0,0.0,0.019950,0.0,0.0,0.006308,0.016414,0.0,0.011552,0.006405,0.0,pass
15,0.0,0.0,0.022695,0.0,0.0,0.009730,0.016381,0.0,0.011369,0.012161,0.0,pass

[[       nan        nan 1.2165847         nan        nan 1.23063444
  1.15802646        nan 1.40935342 1.14309568        nan]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 8,h 1,h 5,h 2,h 4,cz 10,cz 9,cz 7,cz 6,cz 3,sxdg 0
sum,0.4379,0.434925,0.43386,0.428584,0.411826,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 2,h 8,h 5,h 1,h 4,cz 10,cz 9,cz 7,cz 6,cz 3,sxdg 0
sum,0.579591,0.571085,0.567341,0.559215,0.531052,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 4,h 1,h 5,h 2,cz 10,cz 9,cz 7,cz 6,cz 3,sxdg 0
sum,0.004144,0.001556,0.001352,0.000898,0.000889,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_ry_inGap_15_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.42it/s]
100%|██████████| 10/10 [00:01<00:00,  8.91it/s]

,ry 10,cz 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.536189,0.340438,0.605067,0.070979,0.0,0.0,0.017954,0.026275,0.0,0.029691,0.022374,fail
1,0.512302,0.274144,0.498429,0.062727,0.0,0.0,0.027512,0.028021,0.0,0.031286,0.024661,fail
2,0.630343,0.400637,0.757250,0.096411,0.0,0.0,0.020472,0.032785,0.0,0.021865,0.028460,fail
3,0.475108,0.295225,0.523490,0.061269,0.0,0.0,0.015022,0.028551,0.0,0.020523,0.019815,fail
4,0.379417,0.219552,0.447287,0.056835,0.0,0.0,0.020086,0.021039,0.0,0.020467,0.022819,fail
5,0.449302,0.253427,0.474822,0.064404,0.0,0.0,0.025609,0.024078,0.0,0.024940,0.021234,fail
6,0.382402,0.251095,0.444486,0.053686,0.0,0.0,0.015319,0.032639,0.0,0.015661,0.015258,fail
7,0.606747,0.333996,0.659574,0.085212,0.0,0.0,0.028851,0.021734,0.0,0.025394,0.029606,fail
8,0.412854,0.269208,0.545608,0.054979,0.0,0.0,0.021234,0.015605,0.0,0.012070,0.025497,fail
9,0.406246,0.236122,0.426927,0.056207,0.0,0.0,0.017288,0.027873,0.0,0.019787,0.017604,fail
10,0.354953,0.213276,0.402367,0.071182,0.0,0.0,0.022622,0.023350,0.0,0.020491,0.018269,pass
11,0.496623,0.327860,0.540106,0.060902,0.0,0.0,0.018855,0.028358,0.0,0.021027,0.027256,pass
12,0.400815,0.229473,0.436117,0.068720,0.0,0.0,0.020219,0.019796,0.0,0.025554,0.021625,pass
13,0.462902,0.293939,0.519686,0.073516,0.0,0.0,0.020940,0.025133,0.0,0.025839,0.026546,pass
14,0.405453,0.244445,0.355531,0.039760,0.0,0.0,0.016640,0.020900,0.0,0.024739,0.015395,pass
15,0.408361,0.278907,0.454623,0.047365,0.0,0.0,0.012917,0.021439,0.0,0.016761,0.020612,pass
16,0.589189,0.380593,0.681070,0.088238,0.0,0.0,0.030335,0.025238,0.0,0.022530,0.024184,pass
17,0.252297,0.147736,0.251125,0.023038,0.0,0.0,0.021064,0.018013,0.0,0.011654,0.011734,pass
18,0.449554,0.264296,0.453595,0.066208,0.0,0.0,0.025433,0.029269,0.0,0.024890,0.020085,pass
19,0.382643,0.259793,0.465289,0.049207,0.0,0.0,0.017706,0.016059,0.0,0.011902,0.020566,pass

[[1.31570542 1.39408173 1.40675904 1.45479742        nan        nan
  1.37812621 1.26778948        nan 1.4112937  1.30235933]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,cz 8,ry 10,h 3,h 7,h 0,cz 9,h 1,h 4,cz 6,cz 5,cz 2
sum,0.54141,0.532696,0.53193,0.529808,0.524277,0.521175,0.519079,0.503145,0.0,0.0,0.0

custom SCORES

,cz 8,h 7,ry 10,cz 9,h 1,h 3,h 0,h 4,cz 6,cz 5,cz 2
sum,0.731818,0.722499,0.707914,0.702815,0.702223,0.700523,0.694977,0.676494,0.0,0.0,0.0

DSTAR SCORES

,cz 8,ry 10,cz 9,h 7,h 3,h 0,h 1,h 4,cz 6,cz 5,cz 2
sum,1.99018,1.616078,0.653384,0.041479,0.006539,0.005063,0.004815,0.004294,0.0,0.0,0.0

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_y_inGap_9_.qasm

100%|██████████| 4/4 [00:00<00:00, 14.98it/s]
100%|██████████| 10/10 [00:00<00:00, 17.54it/s]

,cz 10,cz 9,y 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.104994,0.020999,0.0,0.0,0.014476,0.016279,0.0,0.011413,0.014085,fail
1,0.0,0.0,0.108786,0.021757,0.0,0.0,0.011813,0.015130,0.0,0.011128,0.012879,fail
2,0.0,0.0,0.136324,0.027265,0.0,0.0,0.015119,0.019657,0.0,0.011151,0.010780,fail
3,0.0,0.0,0.123820,0.024764,0.0,0.0,0.011596,0.014420,0.0,0.008628,0.010174,fail
4,0.0,0.0,0.134228,0.026846,0.0,0.0,0.013298,0.013157,0.0,0.009361,0.016034,pass
5,0.0,0.0,0.120741,0.024148,0.0,0.0,0.009936,0.016870,0.0,0.011351,0.014968,pass
6,0.0,0.0,0.093466,0.018693,0.0,0.0,0.012587,0.013403,0.0,0.008460,0.014854,pass
7,0.0,0.0,0.125718,0.025144,0.0,0.0,0.010785,0.018966,0.0,0.009196,0.009811,pass
8,0.0,0.0,0.148911,0.029782,0.0,0.0,0.013269,0.019445,0.0,0.015874,0.013755,pass
9,0.0,0.0,0.116832,0.023366,0.0,0.0,0.012243,0.015334,0.0,0.009844,0.008351,pass
10,0.0,0.0,0.111602,0.022320,0.0,0.0,0.012165,0.016060,0.0,0.017552,0.012697,pass
11,0.0,0.0,0.130530,0.026106,0.0,0.0,0.014944,0.018251,0.0,0.015615,0.017436,pass
12,0.0,0.0,0.062221,0.012444,0.0,0.0,0.006052,0.007188,0.0,0.007219,0.009842,pass
13,0.0,0.0,0.128857,0.025771,0.0,0.0,0.007310,0.011808,0.0,0.010645,0.011698,pass

[[       nan        nan 1.15060204 1.15060204        nan        nan
  1.14094996 1.20064898        nan 1.07872153 1.17576521]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 4,h 3,y 8,h 7,h 0,h 1,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.320087,0.303223,0.287745,0.287745,0.270168,0.268806,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 4,h 3,h 7,y 8,h 0,h 1,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.411388,0.394239,0.370515,0.370515,0.349581,0.341298,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,y 8,h 7,h 3,h 4,h 0,h 1,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.043418,0.002122,0.001033,0.000683,0.000556,0.000435,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_x_inGap_4_.qasm

100%|██████████| 4/4 [00:00<00:00, 16.25it/s]
100%|██████████| 10/10 [00:00<00:00, 17.34it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,x 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.029918,0.0,0.0,0.010860,0.014248,0.0,0.0,0.012724,0.012578,fail
1,0.0,0.0,0.017978,0.0,0.0,0.013062,0.014043,0.0,0.0,0.011579,0.014741,fail
2,0.0,0.0,0.020976,0.0,0.0,0.011275,0.017424,0.0,0.0,0.009467,0.013647,fail
3,0.0,0.0,0.027626,0.0,0.0,0.011443,0.019733,0.0,0.0,0.011213,0.013486,fail
4,0.0,0.0,0.023551,0.0,0.0,0.010919,0.014969,0.0,0.0,0.009168,0.011888,pass
5,0.0,0.0,0.015483,0.0,0.0,0.005496,0.006940,0.0,0.0,0.005466,0.004949,pass
6,0.0,0.0,0.028496,0.0,0.0,0.014067,0.020869,0.0,0.0,0.011181,0.018491,pass
7,0.0,0.0,0.021643,0.0,0.0,0.012143,0.012249,0.0,0.0,0.012807,0.012439,pass
8,0.0,0.0,0.023216,0.0,0.0,0.012293,0.010728,0.0,0.0,0.007459,0.013323,pass
9,0.0,0.0,0.029871,0.0,0.0,0.012103,0.022379,0.0,0.0,0.009189,0.016531,pass
10,0.0,0.0,0.016806,0.0,0.0,0.008473,0.012386,0.0,0.0,0.010536,0.008003,pass
11,0.0,0.0,0.019438,0.0,0.0,0.013730,0.015921,0.0,0.0,0.011531,0.013290,pass
12,0.0,0.0,0.023395,0.0,0.0,0.012755,0.018366,0.0,0.0,0.009128,0.015415,pass
13,0.0,0.0,0.023746,0.0,0.0,0.008165,0.011097,0.0,0.0,0.008143,0.008194,pass

[[       nan        nan 1.24013565        nan        nan 1.12022799
  1.2060568         nan        nan 1.13139965 1.08284613]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,h 4,h 0,h 8,h 5,cz 10,cz 9,cz 7,cz 6,x 3,cz 2
sum,0.32225,0.309662,0.30768,0.29955,0.297476,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 1,h 4,h 8,h 0,h 5,cz 10,cz 9,cz 7,cz 6,x 3,cz 2
sum,0.413399,0.403029,0.39242,0.390972,0.380786,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 4,h 0,h 5,h 1,cz 10,cz 9,cz 7,cz 6,x 3,cz 2
sum,0.002204,0.001033,0.000719,0.000529,0.000494,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
3
Now evolving the following mutant:  AddGate_x_inGap_9_.qasm

100%|██████████| 2/2 [00:00<00:00, 15.47it/s]
100%|██████████| 10/10 [00:00<00:00, 17.19it/s]

,cz 10,cz 9,x 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.104736,0.020947,0.0,0.0,0.011108,0.013658,0.0,0.011345,0.015030,fail
1,0.0,0.0,0.129296,0.025859,0.0,0.0,0.012023,0.017191,0.0,0.016004,0.013684,fail
2,0.0,0.0,0.131393,0.026279,0.0,0.0,0.009637,0.015739,0.0,0.011696,0.012410,pass
3,0.0,0.0,0.138533,0.027707,0.0,0.0,0.013941,0.017042,0.0,0.012390,0.015957,pass
4,0.0,0.0,0.143474,0.028695,0.0,0.0,0.016184,0.016199,0.0,0.014422,0.017824,pass
5,0.0,0.0,0.094752,0.018950,0.0,0.0,0.016627,0.016568,0.0,0.011985,0.017153,pass
6,0.0,0.0,0.122094,0.024419,0.0,0.0,0.011023,0.013529,0.0,0.007963,0.009254,pass
7,0.0,0.0,0.123530,0.024706,0.0,0.0,0.011237,0.012873,0.0,0.013690,0.014830,pass
8,0.0,0.0,0.081048,0.016210,0.0,0.0,0.005719,0.008307,0.0,0.009345,0.007444,pass
9,0.0,0.0,0.111459,0.022292,0.0,0.0,0.010376,0.010736,0.0,0.012273,0.011234,pass
10,0.0,0.0,0.133680,0.026736,0.0,0.0,0.013868,0.021036,0.0,0.010656,0.014518,pass
11,0.0,0.0,0.083399,0.016680,0.0,0.0,0.012479,0.017401,0.0,0.008115,0.013081,pass

[[       nan        nan 1.10494161 1.10494161        nan        nan
  1.0395822  1.11452559        nan 1.17034784 1.04686412]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,h 0,h 3,x 8,h 7,h 4,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.195516,0.176789,0.171115,0.167477,0.167477,0.160385,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 1,h 0,h 3,h 7,x 8,h 4,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.252721,0.223058,0.218793,0.213741,0.213741,0.202068,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,x 8,h 7,h 3,h 0,h 1,h 4,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.017314,0.000981,0.000443,0.000386,0.000354,0.000252,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_x_inGap_5_.qasm

100%|██████████| 5/5 [00:00<00:00, 16.48it/s]
100%|██████████| 10/10 [00:00<00:00, 17.86it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,x 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.032842,0.0,0.0,0.014369,0.0,0.019066,0.0,0.012900,0.016325,fail
1,0.0,0.0,0.023181,0.0,0.0,0.010362,0.0,0.016446,0.0,0.014588,0.017788,fail
2,0.0,0.0,0.028696,0.0,0.0,0.012921,0.0,0.011365,0.0,0.012043,0.010347,fail
3,0.0,0.0,0.028062,0.0,0.0,0.010354,0.0,0.012358,0.0,0.011569,0.015722,fail
4,0.0,0.0,0.022826,0.0,0.0,0.009828,0.0,0.012005,0.0,0.011426,0.012099,fail
5,0.0,0.0,0.025025,0.0,0.0,0.005450,0.0,0.012524,0.0,0.009885,0.009910,pass
6,0.0,0.0,0.017787,0.0,0.0,0.007611,0.0,0.010199,0.0,0.008061,0.012222,pass
7,0.0,0.0,0.011521,0.0,0.0,0.007395,0.0,0.004691,0.0,0.004862,0.008447,pass
8,0.0,0.0,0.030225,0.0,0.0,0.012783,0.0,0.011770,0.0,0.012402,0.013791,pass
9,0.0,0.0,0.027374,0.0,0.0,0.007473,0.0,0.012778,0.0,0.007566,0.013504,pass
10,0.0,0.0,0.030812,0.0,0.0,0.012797,0.0,0.015866,0.0,0.011758,0.017912,pass
11,0.0,0.0,0.029527,0.0,0.0,0.009185,0.0,0.011019,0.0,0.011599,0.012979,pass
12,0.0,0.0,0.014984,0.0,0.0,0.007485,0.0,0.010790,0.0,0.011592,0.009039,pass
13,0.0,0.0,0.025454,0.0,0.0,0.008324,0.0,0.017107,0.0,0.013199,0.011406,pass
14,0.0,0.0,0.028491,0.0,0.0,0.011134,0.0,0.014219,0.0,0.010316,0.017493,pass

[[       nan        nan 1.21092443        nan        nan 1.24221745
         nan 1.33815551        nan 1.16655356 1.23047919]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 5,h 1,h 3,h 0,h 8,cz 10,cz 9,cz 7,cz 6,x 4,cz 2
sum,0.392173,0.381798,0.370652,0.363245,0.359885,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 5,h 3,h 1,h 0,h 8,cz 10,cz 9,cz 7,cz 6,x 4,cz 2
sum,0.513964,0.49465,0.493145,0.474986,0.468833,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 0,h 3,h 1,h 5,cz 10,cz 9,cz 7,cz 6,x 4,cz 2
sum,0.003509,0.001019,0.000991,0.000766,0.000657,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_rzz_inGap_9_.qasm

100%|██████████| 2/2 [00:00<00:00, 15.78it/s]
100%|██████████| 10/10 [00:00<00:00, 16.84it/s]

,cz 10,cz 9,rzz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.0,0.025416,0.0,0.0,0.010749,0.009732,0.0,0.012855,0.011992,fail
1,0.0,0.0,0.0,0.026230,0.0,0.0,0.008642,0.015931,0.0,0.011913,0.017039,fail
2,0.0,0.0,0.0,0.025662,0.0,0.0,0.009819,0.012904,0.0,0.008559,0.011455,pass
3,0.0,0.0,0.0,0.015417,0.0,0.0,0.008677,0.012581,0.0,0.008552,0.008397,pass
4,0.0,0.0,0.0,0.016777,0.0,0.0,0.013515,0.012148,0.0,0.012409,0.014107,pass
5,0.0,0.0,0.0,0.023447,0.0,0.0,0.009672,0.017242,0.0,0.012158,0.012620,pass
6,0.0,0.0,0.0,0.022839,0.0,0.0,0.011158,0.015364,0.0,0.008743,0.008177,pass
7,0.0,0.0,0.0,0.027767,0.0,0.0,0.009004,0.012458,0.0,0.013404,0.013637,pass
8,0.0,0.0,0.0,0.020086,0.0,0.0,0.009333,0.014225,0.0,0.007311,0.015244,pass
9,0.0,0.0,0.0,0.019544,0.0,0.0,0.008626,0.009186,0.0,0.007529,0.008565,pass
10,0.0,0.0,0.0,0.021181,0.0,0.0,0.008582,0.014418,0.0,0.009507,0.009907,pass
11,0.0,0.0,0.0,0.029019,0.0,0.0,0.014826,0.015505,0.0,0.013788,0.012024,pass

[[       nan        nan        nan 1.01574522        nan        nan
  1.1086255  1.24156717        nan 1.038002   1.17382437]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 0,h 1,h 7,h 3,h 4,cz 10,cz 9,rzz 8,cz 6,cz 5,cz 2
sum,0.202781,0.195443,0.188914,0.15871,0.158164,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 0,h 1,h 7,h 3,h 4,cz 10,cz 9,rzz 8,cz 6,cz 5,cz 2
sum,0.262289,0.24616,0.236886,0.207972,0.202,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 7,h 0,h 3,h 1,h 4,cz 10,cz 9,rzz 8,cz 6,cz 5,cz 2
sum,0.001201,0.000399,0.000308,0.000292,0.000179,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_h_inGap_13_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.38it/s]
100%|██████████| 10/10 [00:01<00:00,  9.79it/s]

,h 10,cz 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.086102,0.419506,0.0,0.053570,0.249603,0.0,0.029077,0.036263,0.0,0.022858,0.028299,fail
1,0.065764,0.342486,0.0,0.052688,0.193736,0.0,0.037242,0.027646,0.0,0.020281,0.023898,fail
2,0.093521,0.460081,0.0,0.063148,0.246347,0.0,0.034932,0.038778,0.0,0.022838,0.037168,fail
3,0.072345,0.335285,0.0,0.045465,0.199138,0.0,0.022558,0.030151,0.0,0.026345,0.030059,fail
4,0.080588,0.408785,0.0,0.061156,0.215980,0.0,0.032037,0.032913,0.0,0.014242,0.027153,fail
5,0.098406,0.492525,0.0,0.059759,0.311040,0.0,0.038272,0.042977,0.0,0.020145,0.025306,fail
6,0.087490,0.422646,0.0,0.048482,0.288440,0.0,0.028076,0.039653,0.0,0.020075,0.025128,fail
7,0.091413,0.454620,0.0,0.028221,0.297981,0.0,0.044728,0.037737,0.0,0.025361,0.019677,fail
8,0.104175,0.526605,0.0,0.064447,0.321956,0.0,0.040215,0.046104,0.0,0.027701,0.033947,fail
9,0.072465,0.360022,0.0,0.042488,0.224293,0.0,0.032368,0.030952,0.0,0.017974,0.021241,fail
10,0.044004,0.206800,0.0,0.025055,0.133539,0.0,0.018494,0.018818,0.0,0.017426,0.015282,pass
11,0.082595,0.426215,0.0,0.039251,0.260332,0.0,0.048048,0.034393,0.0,0.019953,0.037569,pass
12,0.045220,0.217490,0.0,0.043771,0.115043,0.0,0.017870,0.018650,0.0,0.010225,0.021599,pass
13,0.069174,0.361466,0.0,0.028569,0.238106,0.0,0.038993,0.029749,0.0,0.017724,0.023049,pass
14,0.070324,0.388125,0.0,0.063404,0.228673,0.0,0.043121,0.030957,0.0,0.024722,0.021680,pass
15,0.105943,0.555171,0.0,0.071818,0.301255,0.0,0.053949,0.043653,0.0,0.030328,0.033334,pass
16,0.073128,0.370939,0.0,0.059483,0.206346,0.0,0.029109,0.030874,0.0,0.020749,0.030490,pass
17,0.065077,0.336253,0.0,0.039508,0.185722,0.0,0.033245,0.026010,0.0,0.018541,0.021833,pass
18,0.037118,0.197492,0.0,0.021476,0.108844,0.0,0.025164,0.014591,0.0,0.010699,0.012612,pass
19,0.065204,0.329554,0.0,0.048991,0.181681,0.0,0.026460,0.027438,0.0,0.018454,0.027822,pass

[[1.22232149 1.24712136        nan 1.24074268 1.26331048        nan
  1.31742736 1.26947996        nan 1.2717219  1.36709368]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 3,cz 6,h 10,cz 9,h 7,h 1,h 0,h 4,cz 8,cz 5,cz 2
sum,0.568965,0.565325,0.564395,0.554719,0.540646,0.53566,0.525726,0.503749,0.0,0.0,0.0

custom SCORES

,h 3,cz 6,h 10,cz 9,h 7,h 1,h 0,h 4,cz 8,cz 5,cz 2
sum,0.749537,0.74387,0.736863,0.72767,0.708346,0.705963,0.705405,0.669662,0.0,0.0,0.0

DSTAR SCORES

,cz 9,cz 6,h 10,h 7,h 3,h 4,h 0,h 1,cz 8,cz 5,cz 2
sum,1.331642,0.543075,0.068153,0.02584,0.012836,0.011153,0.007215,0.004657,0.0,0.0,0.0

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_t_inGap_1_.qasm

100%|██████████| 8/8 [00:00<00:00, 16.01it/s]
100%|██████████| 10/10 [00:00<00:00, 16.53it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,h 2,h 1,tdg 0,pass/fail
0,0.0,0.0,0.021715,0.0,0.0,0.012396,0.014924,0.0,0.010185,0.014960,0.006674,fail
1,0.0,0.0,0.028415,0.0,0.0,0.016379,0.014910,0.0,0.011144,0.017383,0.007756,fail
2,0.0,0.0,0.029172,0.0,0.0,0.013074,0.015125,0.0,0.010673,0.013240,0.005913,fail
3,0.0,0.0,0.023478,0.0,0.0,0.011063,0.013622,0.0,0.009686,0.014788,0.006581,fail
4,0.0,0.0,0.023188,0.0,0.0,0.011605,0.015327,0.0,0.008752,0.012214,0.005411,fail
5,0.0,0.0,0.017317,0.0,0.0,0.009257,0.010465,0.0,0.008436,0.009322,0.004142,fail
6,0.0,0.0,0.026047,0.0,0.0,0.015251,0.015681,0.0,0.013656,0.016192,0.007244,fail
7,0.0,0.0,0.015419,0.0,0.0,0.008879,0.015072,0.0,0.011583,0.013802,0.006189,fail
8,0.0,0.0,0.018929,0.0,0.0,0.010467,0.014173,0.0,0.009373,0.009898,0.004441,pass
9,0.0,0.0,0.024765,0.0,0.0,0.013635,0.014853,0.0,0.013817,0.010256,0.004596,pass
10,0.0,0.0,0.011687,0.0,0.0,0.006317,0.010933,0.0,0.006203,0.010194,0.004533,pass
11,0.0,0.0,0.025700,0.0,0.0,0.009903,0.013934,0.0,0.006961,0.009541,0.004248,pass
12,0.0,0.0,0.018189,0.0,0.0,0.010065,0.012354,0.0,0.009308,0.012562,0.005592,pass
13,0.0,0.0,0.020448,0.0,0.0,0.008321,0.008205,0.0,0.008516,0.012173,0.005424,pass
14,0.0,0.0,0.020996,0.0,0.0,0.011254,0.011621,0.0,0.009211,0.014757,0.006593,pass
15,0.0,0.0,0.024715,0.0,0.0,0.012169,0.016053,0.0,0.006882,0.012767,0.005648,pass
16,0.0,0.0,0.025572,0.0,0.0,0.013990,0.014798,0.0,0.014973,0.012439,0.005594,pass
17,0.0,0.0,0.020994,0.0,0.0,0.011202,0.013287,0.0,0.011634,0.016208,0.007213,pass

[[       nan        nan 1.26321097        nan        nan 1.3383655
  1.08963475        nan 1.29884385 1.24271488 1.24312286]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,tdg 0,h 5,h 4,h 8,h 2,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.480894,0.480873,0.477054,0.469256,0.465666,0.464739,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 5,tdg 0,h 1,h 2,h 8,h 4,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.636672,0.630319,0.630297,0.615645,0.612725,0.597085,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 4,h 1,h 5,h 2,tdg 0,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.004156,0.00163,0.001542,0.001182,0.000874,0.000309,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_cswap_inGap_8_.qasm

100%|██████████| 10/10 [00:01<00:00,  5.47it/s]
100%|██████████| 10/10 [00:01<00:00,  5.17it/s]

,cz 10,cz 9,h 8,cswap 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.023225,0.173023,0.042996,0.0,0.013039,0.016210,0.0,0.007593,0.011188,fail
1,0.0,0.0,0.027382,0.192848,0.051453,0.0,0.013834,0.015184,0.0,0.005686,0.011052,fail
2,0.0,0.0,0.029006,0.165541,0.050019,0.0,0.012264,0.011764,0.0,0.006872,0.008857,fail
3,0.0,0.0,0.028481,0.199534,0.053843,0.0,0.012678,0.014607,0.0,0.006520,0.011899,fail
4,0.0,0.0,0.029120,0.230915,0.059963,0.0,0.013540,0.015669,0.0,0.008938,0.011657,fail
5,0.0,0.0,0.025466,0.174766,0.048043,0.0,0.012075,0.013285,0.0,0.007095,0.005736,fail
6,0.0,0.0,0.033429,0.185281,0.057886,0.0,0.014124,0.012470,0.0,0.007920,0.010296,fail
7,0.0,0.0,0.028532,0.194677,0.057170,0.0,0.013664,0.014258,0.0,0.005958,0.010337,fail
8,0.0,0.0,0.030860,0.222892,0.062472,0.0,0.014351,0.015005,0.0,0.008490,0.008901,fail
9,0.0,0.0,0.025228,0.186405,0.048965,0.0,0.014505,0.017754,0.0,0.009374,0.009836,fail
10,0.0,0.0,0.026171,0.205750,0.059240,0.0,0.013990,0.015184,0.0,0.010211,0.010906,pass
11,0.0,0.0,0.014639,0.095040,0.024352,0.0,0.006252,0.007124,0.0,0.004010,0.006547,pass
12,0.0,0.0,0.019366,0.201369,0.046306,0.0,0.011998,0.016044,0.0,0.009467,0.010358,pass
13,0.0,0.0,0.031519,0.222493,0.062083,0.0,0.014027,0.016811,0.0,0.008151,0.012368,pass
14,0.0,0.0,0.022748,0.192100,0.051192,0.0,0.012384,0.014494,0.0,0.007053,0.009317,pass
15,0.0,0.0,0.022759,0.177730,0.043332,0.0,0.009353,0.011013,0.0,0.009394,0.008136,pass
16,0.0,0.0,0.020724,0.189440,0.049203,0.0,0.011716,0.014264,0.0,0.007202,0.008870,pass
17,0.0,0.0,0.021144,0.145759,0.038661,0.0,0.007481,0.010537,0.0,0.006594,0.004734,pass
18,0.0,0.0,0.027956,0.206589,0.054147,0.0,0.013065,0.015692,0.0,0.009664,0.011983,pass
19,0.0,0.0,0.023096,0.158035,0.046880,0.0,0.011551,0.013617,0.0,0.006144,0.008533,pass

[[       nan        nan 1.19078989 1.19900801 1.17249065        nan
  1.08189378 1.21432122        nan 1.25919251 1.1927835 ]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 8,h 4,cz 6,h 0,h 3,cswap 7,h 1,cz 10,cz 9,cz 5,cz 2
sum,0.549529,0.545253,0.528474,0.520904,0.520335,0.517684,0.488697,0.0,0.0,0.0,0.0

custom SCORES

,h 8,h 4,cz 6,h 3,h 0,cswap 7,h 1,cz 10,cz 9,cz 5,cz 2
sum,0.713122,0.69273,0.683381,0.678298,0.676235,0.672861,0.642538,0.0,0.0,0.0,0.0

DSTAR SCORES

,cswap 7,cz 6,h 8,h 3,h 4,h 0,h 1,cz 10,cz 9,cz 5,cz 2
sum,0.314475,0.0271,0.007703,0.002109,0.001778,0.000986,0.00055,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
7
Now evolving the following mutant:  AddGate_sx_inGap_2_.qasm

100%|██████████| 3/3 [00:00<00:00, 16.67it/s]
100%|██████████| 10/10 [00:00<00:00, 17.75it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,h 2,sxdg 1,h 0,pass/fail
0,0.0,0.0,0.020964,0.0,0.0,0.011479,0.014275,0.0,0.010731,0.0,0.010819,fail
1,0.0,0.0,0.028006,0.0,0.0,0.014927,0.018475,0.0,0.014266,0.0,0.016088,fail
2,0.0,0.0,0.026016,0.0,0.0,0.009885,0.021666,0.0,0.012948,0.0,0.015033,fail
3,0.0,0.0,0.013593,0.0,0.0,0.008184,0.014066,0.0,0.009919,0.0,0.013239,pass
4,0.0,0.0,0.024164,0.0,0.0,0.010231,0.019335,0.0,0.010699,0.0,0.014328,pass
5,0.0,0.0,0.011799,0.0,0.0,0.008686,0.007806,0.0,0.007599,0.0,0.008087,pass
6,0.0,0.0,0.025349,0.0,0.0,0.009395,0.014376,0.0,0.011947,0.0,0.011616,pass
7,0.0,0.0,0.029817,0.0,0.0,0.014718,0.021737,0.0,0.013567,0.0,0.014888,pass
8,0.0,0.0,0.029009,0.0,0.0,0.012260,0.015238,0.0,0.011048,0.0,0.014225,pass
9,0.0,0.0,0.018146,0.0,0.0,0.011184,0.010431,0.0,0.011024,0.0,0.013174,pass
10,0.0,0.0,0.022624,0.0,0.0,0.007078,0.012039,0.0,0.009232,0.0,0.008767,pass
11,0.0,0.0,0.025564,0.0,0.0,0.011866,0.010372,0.0,0.009300,0.0,0.010565,pass
12,0.0,0.0,0.015604,0.0,0.0,0.007115,0.013561,0.0,0.010192,0.0,0.011017,pass

[[       nan        nan 1.12045696        nan        nan 1.23394993
  1.19447636        nan 1.12785853        nan 1.15077984]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 4,h 2,h 5,h 0,h 8,cz 10,cz 9,cz 7,cz 6,cz 3,sxdg 1
sum,0.281401,0.266335,0.264882,0.25914,0.257991,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 4,h 5,h 2,h 0,h 8,cz 10,cz 9,cz 7,cz 6,cz 3,sxdg 1
sum,0.365433,0.346594,0.341432,0.333694,0.330257,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 4,h 0,h 2,h 5,cz 10,cz 9,cz 7,cz 6,cz 3,sxdg 1
sum,0.001749,0.000943,0.000564,0.000464,0.000425,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_rz_inGap_3_.qasm

100%|██████████| 6/6 [00:00<00:00, 16.39it/s]
100%|██████████| 10/10 [00:00<00:00, 17.35it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,rz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.029435,0.0,0.0,0.014851,0.015190,0.0,0.0,0.013312,0.011220,fail
1,0.0,0.0,0.028954,0.0,0.0,0.012236,0.018540,0.0,0.0,0.009925,0.009922,fail
2,0.0,0.0,0.022458,0.0,0.0,0.015511,0.017932,0.0,0.0,0.011191,0.014873,fail
3,0.0,0.0,0.030115,0.0,0.0,0.013571,0.022702,0.0,0.0,0.012674,0.013765,fail
4,0.0,0.0,0.022430,0.0,0.0,0.012078,0.014708,0.0,0.0,0.011218,0.013447,fail
5,0.0,0.0,0.025407,0.0,0.0,0.011353,0.014447,0.0,0.0,0.012113,0.018372,fail
6,0.0,0.0,0.020181,0.0,0.0,0.009483,0.017007,0.0,0.0,0.010331,0.006298,pass
7,0.0,0.0,0.026934,0.0,0.0,0.011697,0.018702,0.0,0.0,0.010796,0.016190,pass
8,0.0,0.0,0.008721,0.0,0.0,0.007357,0.010930,0.0,0.0,0.008455,0.008214,pass
9,0.0,0.0,0.014533,0.0,0.0,0.008531,0.010190,0.0,0.0,0.008348,0.010065,pass
10,0.0,0.0,0.012166,0.0,0.0,0.006727,0.008795,0.0,0.0,0.009495,0.008604,pass
11,0.0,0.0,0.020075,0.0,0.0,0.009386,0.013891,0.0,0.0,0.008586,0.011005,pass
12,0.0,0.0,0.022945,0.0,0.0,0.011781,0.016215,0.0,0.0,0.014915,0.013445,pass
13,0.0,0.0,0.017785,0.0,0.0,0.005193,0.011788,0.0,0.0,0.008689,0.009341,pass
14,0.0,0.0,0.024439,0.0,0.0,0.014835,0.010850,0.0,0.0,0.013819,0.014410,pass
15,0.0,0.0,0.023433,0.0,0.0,0.012756,0.011921,0.0,0.0,0.013218,0.015381,pass

[[       nan        nan 1.13784243        nan        nan 1.16915791
  1.31578259        nan        nan 1.13399878 1.35088935]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 8,h 5,h 4,h 0,h 1,cz 10,cz 9,cz 7,cz 6,cz 3,rz 2
sum,0.453697,0.44884,0.442754,0.419419,0.397738,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 4,h 8,h 5,h 0,h 1,cz 10,cz 9,cz 7,cz 6,cz 3,rz 2
sum,0.588396,0.582756,0.580031,0.561066,0.510496,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 4,h 0,h 5,h 1,cz 10,cz 9,cz 7,cz 6,cz 3,rz 2
sum,0.004073,0.001748,0.001089,0.001039,0.000812,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_h_inGap_11_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.27it/s]
100%|██████████| 10/10 [00:00<00:00, 11.73it/s]

,cz 10,h 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.045112,0.241299,0.047372,0.0,0.0,0.021931,0.029640,0.083817,0.034164,0.034750,fail
1,0.0,0.046108,0.281572,0.050520,0.0,0.0,0.020928,0.023806,0.092948,0.027251,0.032238,fail
2,0.0,0.044802,0.267803,0.054418,0.0,0.0,0.020455,0.030200,0.088032,0.024986,0.032785,fail
3,0.0,0.028016,0.172139,0.044334,0.0,0.0,0.014805,0.028853,0.052023,0.018442,0.018486,fail
4,0.0,0.048041,0.289198,0.052341,0.0,0.0,0.019220,0.034972,0.098370,0.037141,0.034051,fail
5,0.0,0.047162,0.266762,0.036245,0.0,0.0,0.021631,0.024191,0.093337,0.021801,0.032791,fail
6,0.0,0.037794,0.226406,0.046627,0.0,0.0,0.017165,0.023077,0.078296,0.031743,0.026231,fail
7,0.0,0.049160,0.296999,0.067975,0.0,0.0,0.021185,0.031464,0.089278,0.019061,0.034803,fail
8,0.0,0.044132,0.270429,0.048576,0.0,0.0,0.023978,0.013446,0.086388,0.025233,0.027418,fail
9,0.0,0.038777,0.229480,0.050630,0.0,0.0,0.017497,0.037358,0.073016,0.018295,0.029182,fail
10,0.0,0.054373,0.326667,0.058841,0.0,0.0,0.025514,0.035448,0.104465,0.030980,0.038994,pass
11,0.0,0.043947,0.218458,0.050906,0.0,0.0,0.030257,0.040312,0.080461,0.030996,0.037645,pass
12,0.0,0.041829,0.251564,0.055875,0.0,0.0,0.019274,0.020648,0.070638,0.024405,0.028944,pass
13,0.0,0.040978,0.235827,0.052828,0.0,0.0,0.021590,0.021701,0.070526,0.031690,0.029818,pass
14,0.0,0.046023,0.252095,0.067211,0.0,0.0,0.034382,0.031549,0.082655,0.032201,0.036827,pass
15,0.0,0.031459,0.156108,0.032392,0.0,0.0,0.020690,0.029736,0.052089,0.020661,0.026610,pass
16,0.0,0.042620,0.273706,0.057104,0.0,0.0,0.012844,0.027766,0.080453,0.030766,0.028066,pass
17,0.0,0.044067,0.268080,0.058065,0.0,0.0,0.022762,0.017071,0.082955,0.030191,0.029269,pass
18,0.0,0.044626,0.260416,0.055984,0.0,0.0,0.018757,0.035860,0.074895,0.021923,0.034056,pass
19,0.0,0.045337,0.261809,0.047469,0.0,0.0,0.022280,0.035347,0.086590,0.032612,0.033822,pass

[[       nan 1.14564069 1.16832843 1.36212716        nan        nan
  1.20618518 1.34862812 1.17737474 1.43890256 1.14963815]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,cz 2,cz 8,h 9,h 3,h 0,h 7,h 1,h 4,cz 10,cz 6,cz 5
sum,0.515352,0.503701,0.49644,0.483902,0.482995,0.48183,0.474008,0.465403,0.0,0.0,0.0

custom SCORES

,cz 2,cz 8,h 3,h 7,h 1,h 9,h 0,h 4,cz 10,cz 6,cz 5
sum,0.667043,0.650823,0.647053,0.645909,0.644521,0.638626,0.621813,0.605744,0.0,0.0,0.0

DSTAR SCORES

,cz 8,cz 2,h 7,h 9,h 0,h 3,h 1,h 4,cz 10,cz 6,cz 5
sum,0.516781,0.064721,0.023635,0.017645,0.008877,0.007453,0.006477,0.003864,0.0,0.0,0.0

ERROR GATE LOCATION:
9
Now evolving the following mutant:  AddGate_rx_inGap_1_.qasm

100%|██████████| 4/4 [00:00<00:00, 15.71it/s]
100%|██████████| 10/10 [00:00<00:00, 16.68it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,h 2,h 1,rx 0,pass/fail
0,0.0,0.0,0.024502,0.0,0.0,0.012491,0.015532,0.0,0.011928,0.010471,0.0,fail
1,0.0,0.0,0.021662,0.0,0.0,0.010235,0.014117,0.0,0.011214,0.014564,0.0,fail
2,0.0,0.0,0.019748,0.0,0.0,0.011171,0.014751,0.0,0.011019,0.014606,0.0,fail
3,0.0,0.0,0.030087,0.0,0.0,0.014037,0.018799,0.0,0.016380,0.016087,0.0,fail
4,0.0,0.0,0.024114,0.0,0.0,0.011548,0.016023,0.0,0.009005,0.015293,0.0,pass
5,0.0,0.0,0.022246,0.0,0.0,0.010376,0.014444,0.0,0.008002,0.011602,0.0,pass
6,0.0,0.0,0.019647,0.0,0.0,0.010210,0.017988,0.0,0.009428,0.009458,0.0,pass
7,0.0,0.0,0.021153,0.0,0.0,0.014487,0.016816,0.0,0.008652,0.013534,0.0,pass
8,0.0,0.0,0.019096,0.0,0.0,0.009798,0.009254,0.0,0.010367,0.014608,0.0,pass
9,0.0,0.0,0.017154,0.0,0.0,0.011073,0.013520,0.0,0.007440,0.013482,0.0,pass
10,0.0,0.0,0.020913,0.0,0.0,0.011448,0.012254,0.0,0.008457,0.016117,0.0,pass
11,0.0,0.0,0.016646,0.0,0.0,0.006443,0.014319,0.0,0.008083,0.008063,0.0,pass
12,0.0,0.0,0.019772,0.0,0.0,0.011518,0.014335,0.0,0.008552,0.014429,0.0,pass
13,0.0,0.0,0.022044,0.0,0.0,0.009818,0.018751,0.0,0.014783,0.015689,0.0,pass

[[       nan        nan 1.253649          nan        nan 1.17135086
  1.18981961        nan 1.29637527 1.15464477        nan]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 2,h 8,h 5,h 4,h 1,cz 10,cz 9,cz 7,cz 6,cz 3,rx 0
sum,0.352673,0.321302,0.309945,0.299658,0.296423,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 2,h 8,h 5,h 4,h 1,cz 10,cz 9,cz 7,cz 6,cz 3,rx 0
sum,0.466972,0.422002,0.400708,0.388792,0.381989,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 4,h 1,h 2,h 5,cz 10,cz 9,cz 7,cz 6,cz 3,rx 0
sum,0.002193,0.000963,0.000752,0.000624,0.000559,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_cswap_inGap_7_.qasm

100%|██████████| 4/4 [00:00<00:00,  4.62it/s]
100%|██████████| 10/10 [00:01<00:00,  5.26it/s]

,cz 10,cz 9,h 8,cz 7,cswap 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.023058,0.0,0.084030,0.022520,0.019315,0.021899,0.0,0.007109,0.014213,fail
1,0.0,0.0,0.016247,0.0,0.086574,0.022230,0.018426,0.020772,0.0,0.009028,0.010491,fail
2,0.0,0.0,0.020907,0.0,0.075996,0.018925,0.017822,0.019252,0.0,0.006168,0.010397,fail
3,0.0,0.0,0.025326,0.0,0.073914,0.023386,0.021142,0.021930,0.0,0.009859,0.009841,fail
4,0.0,0.0,0.025786,0.0,0.076606,0.018450,0.016638,0.018264,0.0,0.007399,0.007914,pass
5,0.0,0.0,0.019791,0.0,0.075264,0.021817,0.017004,0.018237,0.0,0.006541,0.005313,pass
6,0.0,0.0,0.025254,0.0,0.082341,0.020061,0.018203,0.020069,0.0,0.008749,0.009605,pass
7,0.0,0.0,0.020309,0.0,0.071594,0.018201,0.015690,0.016568,0.0,0.008505,0.008735,pass
8,0.0,0.0,0.020249,0.0,0.072831,0.016369,0.016254,0.016957,0.0,0.007583,0.008443,pass
9,0.0,0.0,0.020049,0.0,0.070642,0.015829,0.015084,0.016739,0.0,0.007094,0.010300,pass
10,0.0,0.0,0.022876,0.0,0.074370,0.018115,0.017279,0.018619,0.0,0.006558,0.008853,pass
11,0.0,0.0,0.016771,0.0,0.056692,0.015749,0.011996,0.013452,0.0,0.005284,0.006665,pass
12,0.0,0.0,0.015123,0.0,0.074024,0.016396,0.015138,0.016053,0.0,0.005791,0.007329,pass
13,0.0,0.0,0.021088,0.0,0.063435,0.012902,0.014185,0.015627,0.0,0.007235,0.009828,pass

[[       nan        nan 1.18431264        nan 1.0804406  1.07446739
  1.10249894 1.04610155        nan 1.22612045 1.26500552]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 0,cz 5,h 3,h 4,h 1,cswap 6,h 8,cz 10,cz 9,cz 7,cz 2
sum,0.351309,0.333629,0.32956,0.327553,0.312566,0.308687,0.292102,0.0,0.0,0.0,0.0

custom SCORES

,h 0,cz 5,h 4,h 3,h 1,cswap 6,h 8,cz 10,cz 9,cz 7,cz 2
sum,0.462411,0.423248,0.417835,0.415748,0.408376,0.392067,0.378587,0.0,0.0,0.0,0.0

DSTAR SCORES

,cswap 6,cz 5,h 8,h 3,h 4,h 0,h 1,cz 10,cz 9,cz 7,cz 2
sum,0.021775,0.001816,0.001739,0.001686,0.001415,0.000495,0.000254,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
6
Now evolving the following mutant:  AddGate_rz_inGap_11_.qasm

100%|██████████| 4/4 [00:00<00:00, 16.77it/s]
100%|██████████| 10/10 [00:00<00:00, 17.91it/s]

,cz 10,rz 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.0,0.022570,0.0,0.0,0.010562,0.017465,0.0,0.007846,0.012527,fail
1,0.0,0.0,0.0,0.023435,0.0,0.0,0.012185,0.022315,0.0,0.011777,0.014798,fail
2,0.0,0.0,0.0,0.028642,0.0,0.0,0.015830,0.014556,0.0,0.011333,0.013217,fail
3,0.0,0.0,0.0,0.023442,0.0,0.0,0.007340,0.015739,0.0,0.007351,0.012878,fail
4,0.0,0.0,0.0,0.016560,0.0,0.0,0.007566,0.013030,0.0,0.013402,0.012803,pass
5,0.0,0.0,0.0,0.020276,0.0,0.0,0.007826,0.013769,0.0,0.008199,0.011480,pass
6,0.0,0.0,0.0,0.019866,0.0,0.0,0.009884,0.009353,0.0,0.009560,0.012060,pass
7,0.0,0.0,0.0,0.022828,0.0,0.0,0.013928,0.017409,0.0,0.013711,0.013843,pass
8,0.0,0.0,0.0,0.017894,0.0,0.0,0.008019,0.016791,0.0,0.006266,0.010926,pass
9,0.0,0.0,0.0,0.019847,0.0,0.0,0.010534,0.007841,0.0,0.009472,0.008385,pass
10,0.0,0.0,0.0,0.013717,0.0,0.0,0.009057,0.009961,0.0,0.007251,0.006492,pass
11,0.0,0.0,0.0,0.022435,0.0,0.0,0.011312,0.015267,0.0,0.009679,0.011576,pass
12,0.0,0.0,0.0,0.018193,0.0,0.0,0.012321,0.012182,0.0,0.012000,0.013180,pass
13,0.0,0.0,0.0,0.024825,0.0,0.0,0.013757,0.020805,0.0,0.016918,0.014002,pass

[[       nan        nan        nan 1.1679766         nan        nan
  1.37903008 1.27377218        nan 1.22977457 1.10805126]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 3,h 7,h 0,h 4,h 1,cz 10,rz 9,cz 8,cz 6,cz 5,cz 2
sum,0.339371,0.333035,0.317666,0.305861,0.264619,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 3,h 7,h 4,h 0,h 1,cz 10,rz 9,cz 8,cz 6,cz 5,cz 2
sum,0.447442,0.430279,0.411308,0.405664,0.345974,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 7,h 3,h 0,h 4,h 1,cz 10,rz 9,cz 8,cz 6,cz 5,cz 2
sum,0.002293,0.001187,0.000694,0.000514,0.000357,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
9
Now evolving the following mutant:  AddGate_ry_inGap_5_.qasm

100%|██████████| 10/10 [00:00<00:00, 16.57it/s]
100%|██████████| 10/10 [00:00<00:00, 17.21it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,ry 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.030858,0.0,0.0,0.013596,0.004973,0.015183,0.0,0.009295,0.010605,fail
1,0.0,0.0,0.022184,0.0,0.0,0.011228,0.003615,0.012300,0.0,0.009774,0.010568,fail
2,0.0,0.0,0.023388,0.0,0.0,0.014078,0.003337,0.012598,0.0,0.009779,0.014023,fail
3,0.0,0.0,0.024151,0.0,0.0,0.011084,0.003893,0.006882,0.0,0.009608,0.005035,fail
4,0.0,0.0,0.031167,0.0,0.0,0.014112,0.005499,0.013547,0.0,0.009276,0.014640,fail
5,0.0,0.0,0.026123,0.0,0.0,0.013449,0.004221,0.016419,0.0,0.008735,0.012581,fail
6,0.0,0.0,0.020370,0.0,0.0,0.012274,0.003539,0.013089,0.0,0.007196,0.013339,fail
7,0.0,0.0,0.025040,0.0,0.0,0.014625,0.004614,0.013722,0.0,0.008930,0.013903,fail
8,0.0,0.0,0.020018,0.0,0.0,0.011936,0.003738,0.012278,0.0,0.005961,0.011752,fail
9,0.0,0.0,0.024559,0.0,0.0,0.014556,0.005493,0.013914,0.0,0.010207,0.011166,fail
10,0.0,0.0,0.021681,0.0,0.0,0.010531,0.003548,0.012484,0.0,0.007351,0.011287,pass
11,0.0,0.0,0.025883,0.0,0.0,0.013675,0.005435,0.008211,0.0,0.008429,0.010321,pass
12,0.0,0.0,0.028989,0.0,0.0,0.014742,0.004745,0.012507,0.0,0.012723,0.013393,pass
13,0.0,0.0,0.019909,0.0,0.0,0.010750,0.003896,0.014106,0.0,0.007626,0.011524,pass
14,0.0,0.0,0.033016,0.0,0.0,0.013832,0.005003,0.016992,0.0,0.010147,0.015160,pass
15,0.0,0.0,0.023119,0.0,0.0,0.013097,0.004393,0.011518,0.0,0.010261,0.011410,pass
16,0.0,0.0,0.020171,0.0,0.0,0.011695,0.004196,0.008254,0.0,0.008290,0.010538,pass
17,0.0,0.0,0.021883,0.0,0.0,0.014188,0.004936,0.010330,0.0,0.007971,0.010263,pass
18,0.0,0.0,0.022272,0.0,0.0,0.008849,0.003329,0.006372,0.0,0.006598,0.008043,pass
19,0.0,0.0,0.023247,0.0,0.0,0.007654,0.002489,0.011997,0.0,0.008569,0.011515,pass

[[       nan        nan 1.25748043        nan        nan 1.11697587
  1.28120175 1.26364215        nan 1.14994093 1.24474305]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 3,h 5,h 0,h 8,ry 4,h 1,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.53535,0.523857,0.508992,0.507877,0.505622,0.502257,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 3,h 5,ry 4,h 8,h 0,h 1,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.704473,0.67014,0.667572,0.667538,0.667383,0.646648,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 5,h 3,h 0,h 1,ry 4,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.005999,0.001694,0.001669,0.001368,0.000781,0.000183,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_ccx_inGap_3_.qasm

100%|██████████| 5/5 [00:00<00:00, 10.81it/s]
100%|██████████| 10/10 [00:00<00:00, 12.09it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,ccx 2,h 1,h 0,pass/fail
0,0.0,0.0,0.031522,0.0,0.0,0.012431,0.016228,0.0,0.027654,0.011793,0.007570,fail
1,0.0,0.0,0.024004,0.0,0.0,0.014798,0.018088,0.0,0.025923,0.016330,0.011720,fail
2,0.0,0.0,0.034819,0.0,0.0,0.013106,0.018121,0.0,0.027083,0.013654,0.010116,fail
3,0.0,0.0,0.023701,0.0,0.0,0.011414,0.012398,0.0,0.029258,0.008903,0.007216,fail
4,0.0,0.0,0.018746,0.0,0.0,0.008151,0.010259,0.0,0.021454,0.007557,0.007804,fail
5,0.0,0.0,0.023239,0.0,0.0,0.008256,0.012830,0.0,0.025434,0.010701,0.009338,pass
6,0.0,0.0,0.015591,0.0,0.0,0.011181,0.007109,0.0,0.021357,0.008940,0.005202,pass
7,0.0,0.0,0.017267,0.0,0.0,0.009713,0.012261,0.0,0.020653,0.010309,0.008364,pass
8,0.0,0.0,0.032337,0.0,0.0,0.013222,0.017914,0.0,0.026807,0.011130,0.006213,pass
9,0.0,0.0,0.025354,0.0,0.0,0.012130,0.016537,0.0,0.027436,0.012200,0.011471,pass
10,0.0,0.0,0.018614,0.0,0.0,0.010132,0.014381,0.0,0.024875,0.009303,0.007428,pass
11,0.0,0.0,0.013690,0.0,0.0,0.007992,0.011574,0.0,0.016582,0.008909,0.005240,pass
12,0.0,0.0,0.026433,0.0,0.0,0.013037,0.016644,0.0,0.022219,0.012748,0.007658,pass
13,0.0,0.0,0.021934,0.0,0.0,0.009014,0.009889,0.0,0.023257,0.009694,0.005157,pass
14,0.0,0.0,0.016079,0.0,0.0,0.007071,0.012098,0.0,0.018207,0.007159,0.005675,pass

[[       nan        nan 1.31102581        nan        nan 1.23520345
  1.20653838        nan 1.11356417 1.40204037 1.31901867]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 8,h 0,h 5,ccx 2,h 1,h 4,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.386776,0.382409,0.370558,0.366759,0.365513,0.363951,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 8,h 0,h 1,h 5,h 4,ccx 2,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.513544,0.50851,0.493629,0.484987,0.473731,0.468861,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,ccx 2,h 4,h 5,h 1,h 0,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.003384,0.003302,0.001099,0.000703,0.000665,0.000389,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_cswap_inGap_9_.qasm

100%|██████████| 5/5 [00:01<00:00,  4.21it/s]
100%|██████████| 10/10 [00:02<00:00,  4.38it/s]

,cz 10,cz 9,cswap 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.178458,0.036119,0.018352,0.0,0.012219,0.020260,0.0,0.011866,0.014323,fail
1,0.0,0.0,0.160381,0.032004,0.016381,0.0,0.010879,0.017859,0.0,0.010964,0.013658,fail
2,0.0,0.0,0.184621,0.037370,0.018425,0.0,0.012827,0.021371,0.0,0.010946,0.016014,fail
3,0.0,0.0,0.166232,0.031911,0.017615,0.0,0.009347,0.017495,0.0,0.009173,0.010802,fail
4,0.0,0.0,0.190323,0.033498,0.018898,0.0,0.011860,0.019030,0.0,0.007291,0.013647,fail
5,0.0,0.0,0.145135,0.026565,0.014346,0.0,0.008508,0.015594,0.0,0.007906,0.013468,pass
6,0.0,0.0,0.151083,0.031495,0.015245,0.0,0.010952,0.019031,0.0,0.008322,0.013034,pass
7,0.0,0.0,0.188756,0.036753,0.022988,0.0,0.012493,0.021647,0.0,0.008526,0.011863,pass
8,0.0,0.0,0.137150,0.030526,0.014720,0.0,0.012390,0.018904,0.0,0.014989,0.011057,pass
9,0.0,0.0,0.143148,0.026322,0.014072,0.0,0.009460,0.015294,0.0,0.009863,0.009512,pass
10,0.0,0.0,0.110997,0.021777,0.009957,0.0,0.008054,0.012953,0.0,0.010643,0.008251,pass
11,0.0,0.0,0.144437,0.026361,0.012804,0.0,0.009724,0.016176,0.0,0.008775,0.006310,pass
12,0.0,0.0,0.169670,0.032877,0.016752,0.0,0.012180,0.019542,0.0,0.008890,0.012937,pass
13,0.0,0.0,0.143792,0.028919,0.010251,0.0,0.011067,0.015756,0.0,0.011031,0.015533,pass
14,0.0,0.0,0.126250,0.022969,0.010826,0.0,0.007267,0.012703,0.0,0.006424,0.011583,pass

[[       nan        nan 1.08135936 1.09331906 1.05376022        nan
  1.12261318 1.11290164        nan 1.18098308 1.16984522]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,cz 6,h 0,cswap 8,h 7,h 3,h 4,h 1,cz 10,cz 9,cz 5,cz 2
sum,0.387131,0.376087,0.376005,0.375225,0.364222,0.358812,0.345034,0.0,0.0,0.0,0.0

custom SCORES

,cz 6,h 0,h 7,cswap 8,h 3,h 4,h 1,cz 10,cz 9,cz 5,cz 2
sum,0.489116,0.486078,0.477785,0.477654,0.465558,0.459514,0.446904,0.0,0.0,0.0,0.0

DSTAR SCORES

,cswap 8,h 7,h 3,cz 6,h 0,h 4,h 1,cz 10,cz 9,cz 5,cz 2
sum,0.119872,0.005527,0.001784,0.001564,0.000916,0.00064,0.000495,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_rzz_inGap_11_.qasm

100%|██████████| 2/2 [00:00<00:00, 14.94it/s]
100%|██████████| 10/10 [00:00<00:00, 15.48it/s]

,cz 10,rzz 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.0,0.020506,0.0,0.0,0.011413,0.017856,0.0,0.007439,0.008817,fail
1,0.0,0.0,0.0,0.020989,0.0,0.0,0.007014,0.013349,0.0,0.008404,0.010885,fail
2,0.0,0.0,0.0,0.021204,0.0,0.0,0.012337,0.017697,0.0,0.011561,0.013044,pass
3,0.0,0.0,0.0,0.019757,0.0,0.0,0.012227,0.013031,0.0,0.007457,0.011451,pass
4,0.0,0.0,0.0,0.024155,0.0,0.0,0.011027,0.016100,0.0,0.012389,0.012272,pass
5,0.0,0.0,0.0,0.017833,0.0,0.0,0.006883,0.012269,0.0,0.005381,0.005193,pass
6,0.0,0.0,0.0,0.028264,0.0,0.0,0.013201,0.019267,0.0,0.011081,0.018201,pass
7,0.0,0.0,0.0,0.026370,0.0,0.0,0.011912,0.012626,0.0,0.012240,0.013699,pass
8,0.0,0.0,0.0,0.020610,0.0,0.0,0.008500,0.012041,0.0,0.009069,0.009963,pass
9,0.0,0.0,0.0,0.023987,0.0,0.0,0.008629,0.015375,0.0,0.008071,0.007636,pass
10,0.0,0.0,0.0,0.024364,0.0,0.0,0.014052,0.013918,0.0,0.009699,0.010073,pass
11,0.0,0.0,0.0,0.020411,0.0,0.0,0.007346,0.010967,0.0,0.006045,0.011206,pass

[[       nan        nan        nan 1.01164199        nan        nan
  1.23871461 1.14442953        nan 1.06092798 1.10499461]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 3,h 7,h 0,h 4,h 1,cz 10,rzz 9,cz 8,cz 6,cz 5,cz 2
sum,0.17883,0.154574,0.148762,0.147966,0.145565,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 3,h 4,h 7,h 0,h 1,cz 10,rzz 9,cz 8,cz 6,cz 5,cz 2
sum,0.229994,0.193788,0.193667,0.189858,0.184173,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 7,h 3,h 0,h 4,h 1,cz 10,rzz 9,cz 8,cz 6,cz 5,cz 2
sum,0.000773,0.000454,0.000184,0.000161,0.00012,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
9
Now evolving the following mutant:  AddGate_rzz_inGap_1_.qasm

100%|██████████| 5/5 [00:00<00:00, 15.15it/s]
100%|██████████| 10/10 [00:00<00:00, 16.85it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,h 2,h 1,rzz 0,pass/fail
0,0.0,0.0,0.020788,0.0,0.0,0.011158,0.012800,0.0,0.012002,0.012270,0.041473,fail
1,0.0,0.0,0.026315,0.0,0.0,0.009311,0.014305,0.0,0.007817,0.010651,0.044738,fail
2,0.0,0.0,0.019245,0.0,0.0,0.010620,0.013373,0.0,0.010696,0.013975,0.042394,fail
3,0.0,0.0,0.019274,0.0,0.0,0.009206,0.015435,0.0,0.011525,0.009955,0.039859,fail
4,0.0,0.0,0.025288,0.0,0.0,0.009791,0.018230,0.0,0.010827,0.011890,0.050209,fail
5,0.0,0.0,0.014067,0.0,0.0,0.007348,0.009786,0.0,0.006054,0.007585,0.042077,pass
6,0.0,0.0,0.011620,0.0,0.0,0.008569,0.010090,0.0,0.009967,0.010349,0.040001,pass
7,0.0,0.0,0.031503,0.0,0.0,0.013879,0.016257,0.0,0.011360,0.010150,0.043007,pass
8,0.0,0.0,0.018760,0.0,0.0,0.011524,0.014845,0.0,0.008658,0.010879,0.052621,pass
9,0.0,0.0,0.020205,0.0,0.0,0.011856,0.016560,0.0,0.010899,0.010187,0.043094,pass
10,0.0,0.0,0.031631,0.0,0.0,0.011964,0.017262,0.0,0.010503,0.014459,0.034807,pass
11,0.0,0.0,0.027826,0.0,0.0,0.011205,0.017937,0.0,0.012294,0.016163,0.045612,pass
12,0.0,0.0,0.023228,0.0,0.0,0.007571,0.010074,0.0,0.009162,0.009704,0.023486,pass
13,0.0,0.0,0.013974,0.0,0.0,0.006885,0.009370,0.0,0.007679,0.008765,0.026400,pass
14,0.0,0.0,0.022039,0.0,0.0,0.012366,0.012255,0.0,0.009437,0.014299,0.032142,pass

[[       nan        nan 1.1863254         nan        nan 1.11381371
  1.22939123        nan 1.13514077 1.18954456 1.14803466]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,rzz 0,h 4,h 2,h 1,h 8,h 5,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.363293,0.355472,0.355102,0.342953,0.340464,0.326823,0.0,0.0,0.0,0.0,0.0

custom SCORES

,rzz 0,h 4,h 2,h 1,h 8,h 5,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.467561,0.464726,0.455875,0.444943,0.441439,0.417828,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,rzz 0,h 8,h 4,h 1,h 2,h 5,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.008883,0.002359,0.001071,0.000675,0.000548,0.000492,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_h_inGap_2_.qasm

100%|██████████| 10/10 [00:00<00:00, 15.47it/s]
100%|██████████| 10/10 [00:00<00:00, 15.56it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,h 2,h 1,h 0,pass/fail
0,0.0,0.0,0.032928,0.0,0.0,0.014084,0.017410,0.0,0.013766,0.008552,0.014691,fail
1,0.0,0.0,0.028538,0.0,0.0,0.012521,0.018853,0.0,0.010968,0.006808,0.011094,fail
2,0.0,0.0,0.029907,0.0,0.0,0.010278,0.014422,0.0,0.009081,0.005116,0.009875,fail
3,0.0,0.0,0.021454,0.0,0.0,0.009419,0.008673,0.0,0.011262,0.006781,0.009437,fail
4,0.0,0.0,0.028868,0.0,0.0,0.013716,0.014131,0.0,0.013291,0.007868,0.008625,fail
5,0.0,0.0,0.026659,0.0,0.0,0.012353,0.018549,0.0,0.010090,0.006503,0.012680,fail
6,0.0,0.0,0.025922,0.0,0.0,0.014112,0.016677,0.0,0.010329,0.006211,0.009643,fail
7,0.0,0.0,0.025953,0.0,0.0,0.013144,0.014469,0.0,0.013096,0.007653,0.005697,fail
8,0.0,0.0,0.017175,0.0,0.0,0.007847,0.009084,0.0,0.009470,0.004817,0.006328,fail
9,0.0,0.0,0.023240,0.0,0.0,0.011444,0.012715,0.0,0.013853,0.008606,0.010355,fail
10,0.0,0.0,0.024567,0.0,0.0,0.008548,0.013810,0.0,0.007344,0.004504,0.011009,pass
11,0.0,0.0,0.021471,0.0,0.0,0.009649,0.016341,0.0,0.012298,0.007527,0.013967,pass
12,0.0,0.0,0.024000,0.0,0.0,0.007731,0.010055,0.0,0.007550,0.004465,0.010658,pass
13,0.0,0.0,0.013762,0.0,0.0,0.006362,0.008633,0.0,0.003440,0.001783,0.006229,pass
14,0.0,0.0,0.020643,0.0,0.0,0.009223,0.011013,0.0,0.010096,0.006471,0.008284,pass
15,0.0,0.0,0.023285,0.0,0.0,0.012804,0.014722,0.0,0.011460,0.007347,0.010934,pass
16,0.0,0.0,0.027649,0.0,0.0,0.012096,0.017030,0.0,0.009230,0.005796,0.010371,pass
17,0.0,0.0,0.033640,0.0,0.0,0.012230,0.020843,0.0,0.010502,0.006623,0.013885,pass
18,0.0,0.0,0.023453,0.0,0.0,0.016478,0.013250,0.0,0.011704,0.007783,0.008223,pass
19,0.0,0.0,0.025902,0.0,0.0,0.011397,0.018002,0.0,0.011422,0.006997,0.011886,pass

[[       nan        nan 1.26333802        nan        nan 1.18667789
  1.30034045        nan 1.20246424 1.24881508 1.49261682]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 2,h 1,h 5,h 8,h 4,h 0,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.547948,0.537512,0.527505,0.522317,0.502224,0.482777,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 2,h 1,h 8,h 5,h 4,h 0,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.71267,0.705326,0.687282,0.684,0.665489,0.662927,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 4,h 5,h 2,h 0,h 1,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.006635,0.002072,0.001399,0.001315,0.000959,0.000472,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_t_inGap_8_.qasm

100%|██████████| 6/6 [00:00<00:00, 12.72it/s]
100%|██████████| 10/10 [00:00<00:00, 13.34it/s]

,cz 10,cz 9,h 8,tdg 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.022723,0.011361,0.0,0.0,0.008925,0.009725,0.0,0.007210,0.012098,fail
1,0.0,0.0,0.025658,0.012829,0.0,0.0,0.010528,0.015034,0.0,0.010877,0.010711,fail
2,0.0,0.0,0.024630,0.012315,0.0,0.0,0.010358,0.016760,0.0,0.011624,0.014226,fail
3,0.0,0.0,0.024640,0.012320,0.0,0.0,0.009634,0.015410,0.0,0.012073,0.010981,fail
4,0.0,0.0,0.019344,0.009672,0.0,0.0,0.012611,0.015983,0.0,0.010842,0.015459,fail
5,0.0,0.0,0.025295,0.012647,0.0,0.0,0.012525,0.013126,0.0,0.008690,0.010226,fail
6,0.0,0.0,0.022103,0.011051,0.0,0.0,0.006879,0.011042,0.0,0.006671,0.007278,pass
7,0.0,0.0,0.028320,0.014160,0.0,0.0,0.014544,0.021664,0.0,0.013572,0.018395,pass
8,0.0,0.0,0.015279,0.007640,0.0,0.0,0.008221,0.007820,0.0,0.005936,0.007114,pass
9,0.0,0.0,0.024341,0.012170,0.0,0.0,0.011304,0.013278,0.0,0.011871,0.014268,pass
10,0.0,0.0,0.041943,0.020972,0.0,0.0,0.015590,0.018771,0.0,0.011756,0.012912,pass
11,0.0,0.0,0.021675,0.010837,0.0,0.0,0.012015,0.013894,0.0,0.007879,0.014679,pass
12,0.0,0.0,0.022460,0.011230,0.0,0.0,0.009444,0.013035,0.0,0.012013,0.014757,pass
13,0.0,0.0,0.031375,0.015687,0.0,0.0,0.012953,0.013885,0.0,0.010010,0.014330,pass
14,0.0,0.0,0.020718,0.010359,0.0,0.0,0.009543,0.016317,0.0,0.011819,0.012077,pass
15,0.0,0.0,0.018086,0.009043,0.0,0.0,0.011902,0.015923,0.0,0.010302,0.013985,pass

[[       nan        nan 1.08194249 1.08194249        nan        nan
  1.17161979 1.16877056        nan 1.18139848 1.25851442]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,h 3,h 8,tdg 7,h 4,h 0,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.375841,0.371385,0.36617,0.36617,0.364914,0.362175,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 1,h 3,h 0,h 4,h 8,tdg 7,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.486845,0.4799,0.476125,0.471799,0.465214,0.465214,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 3,h 0,tdg 7,h 4,h 1,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.003241,0.001205,0.000886,0.000827,0.000682,0.000616,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
7
Now evolving the following mutant:  AddGate_ccx_inGap_5_.qasm

100%|██████████| 8/8 [00:01<00:00,  6.45it/s]
100%|██████████| 10/10 [00:01<00:00,  6.74it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,ccx 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.029508,0.0,0.0,0.007741,0.072250,0.010378,0.0,0.008270,0.011021,fail
1,0.0,0.0,0.025787,0.0,0.0,0.009814,0.070245,0.010013,0.0,0.008438,0.010563,fail
2,0.0,0.0,0.025582,0.0,0.0,0.012564,0.071762,0.010958,0.0,0.009642,0.010352,fail
3,0.0,0.0,0.022706,0.0,0.0,0.011846,0.061025,0.009814,0.0,0.009785,0.007446,fail
4,0.0,0.0,0.020338,0.0,0.0,0.010914,0.065645,0.011362,0.0,0.008737,0.010814,fail
5,0.0,0.0,0.022677,0.0,0.0,0.015752,0.063450,0.011431,0.0,0.010127,0.009464,fail
6,0.0,0.0,0.020920,0.0,0.0,0.013560,0.074396,0.010775,0.0,0.009678,0.013708,fail
7,0.0,0.0,0.024255,0.0,0.0,0.014063,0.065196,0.011290,0.0,0.004810,0.009450,fail
8,0.0,0.0,0.028141,0.0,0.0,0.010307,0.077370,0.011773,0.0,0.008716,0.008945,pass
9,0.0,0.0,0.025643,0.0,0.0,0.011384,0.057746,0.010148,0.0,0.006472,0.008521,pass
10,0.0,0.0,0.019270,0.0,0.0,0.009996,0.046079,0.007528,0.0,0.006478,0.004219,pass
11,0.0,0.0,0.019184,0.0,0.0,0.011544,0.059044,0.010718,0.0,0.008337,0.010476,pass
12,0.0,0.0,0.015882,0.0,0.0,0.010594,0.057261,0.010160,0.0,0.004616,0.009656,pass
13,0.0,0.0,0.021240,0.0,0.0,0.010539,0.059750,0.008840,0.0,0.007995,0.009868,pass
14,0.0,0.0,0.014308,0.0,0.0,0.008587,0.044956,0.007765,0.0,0.004406,0.009880,pass
15,0.0,0.0,0.020688,0.0,0.0,0.012121,0.056835,0.009709,0.0,0.007871,0.009249,pass
16,0.0,0.0,0.014271,0.0,0.0,0.008199,0.058503,0.008412,0.0,0.005683,0.009546,pass
17,0.0,0.0,0.031306,0.0,0.0,0.011739,0.066181,0.011528,0.0,0.008418,0.011475,pass

[[       nan        nan 1.23095726        nan        nan 1.30920223
  1.09412475 1.0630643         nan 1.16592674 1.32410796]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,ccx 4,h 5,h 8,h 0,h 3,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.501777,0.482371,0.478248,0.477398,0.474186,0.471083,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 1,h 5,h 0,h 8,ccx 4,h 3,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.648036,0.634779,0.631155,0.624312,0.614315,0.596281,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,ccx 4,h 8,h 5,h 3,h 0,h 1,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.034472,0.00448,0.001143,0.000914,0.000848,0.000598,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_y_inGap_4_.qasm

100%|██████████| 3/3 [00:00<00:00, 14.54it/s]
100%|██████████| 10/10 [00:00<00:00, 16.09it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,y 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.021151,0.0,0.0,0.008175,0.012758,0.035511,0.0,0.007890,0.010137,fail
1,0.0,0.0,0.025178,0.0,0.0,0.010975,0.014303,0.038261,0.0,0.012819,0.011980,fail
2,0.0,0.0,0.031488,0.0,0.0,0.012482,0.018292,0.042996,0.0,0.008218,0.009332,fail
3,0.0,0.0,0.018023,0.0,0.0,0.012282,0.009170,0.018206,0.0,0.008487,0.010333,pass
4,0.0,0.0,0.026926,0.0,0.0,0.012970,0.014442,0.034587,0.0,0.010007,0.015200,pass
5,0.0,0.0,0.011334,0.0,0.0,0.007218,0.011556,0.030236,0.0,0.007876,0.008314,pass
6,0.0,0.0,0.014875,0.0,0.0,0.008176,0.007288,0.017258,0.0,0.009079,0.008040,pass
7,0.0,0.0,0.030510,0.0,0.0,0.009815,0.021495,0.053741,0.0,0.011018,0.016922,pass
8,0.0,0.0,0.022352,0.0,0.0,0.008988,0.010121,0.026371,0.0,0.009764,0.013477,pass
9,0.0,0.0,0.027371,0.0,0.0,0.015483,0.020433,0.052804,0.0,0.013823,0.012597,pass
10,0.0,0.0,0.017554,0.0,0.0,0.010350,0.013857,0.036192,0.0,0.007768,0.010131,pass
11,0.0,0.0,0.025603,0.0,0.0,0.011049,0.015283,0.036441,0.0,0.011613,0.012111,pass
12,0.0,0.0,0.028410,0.0,0.0,0.010241,0.010270,0.025420,0.0,0.010043,0.014005,pass

[[       nan        nan 1.21393942        nan        nan 1.18378088
  1.20996193 1.10465191        nan 1.32946166 1.14278528]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,y 3,h 8,h 4,h 5,h 1,h 0,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.260628,0.258721,0.252993,0.228879,0.225274,0.206112,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 8,y 3,h 4,h 1,h 5,h 0,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.337238,0.332604,0.329521,0.300147,0.296615,0.264998,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,y 3,h 8,h 4,h 5,h 0,h 1,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.004093,0.001879,0.000656,0.000322,0.000317,0.00027,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
3
Now evolving the following mutant:  AddGate_y_inGap_1_.qasm

100%|██████████| 3/3 [00:00<00:00, 13.12it/s]
100%|██████████| 10/10 [00:00<00:00, 15.45it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,h 2,h 1,y 0,pass/fail
0,0.0,0.0,0.018837,0.0,0.0,0.015429,0.016533,0.0,0.013457,0.018498,0.030757,fail
1,0.0,0.0,0.026509,0.0,0.0,0.018093,0.022392,0.0,0.011607,0.015093,0.023248,fail
2,0.0,0.0,0.028754,0.0,0.0,0.011619,0.015772,0.0,0.012226,0.015092,0.024328,fail
3,0.0,0.0,0.016060,0.0,0.0,0.005743,0.009600,0.0,0.007474,0.005874,0.008885,pass
4,0.0,0.0,0.014969,0.0,0.0,0.008002,0.012282,0.0,0.008182,0.012943,0.023032,pass
5,0.0,0.0,0.023163,0.0,0.0,0.012236,0.019652,0.0,0.013068,0.014152,0.020815,pass
6,0.0,0.0,0.027863,0.0,0.0,0.014153,0.017115,0.0,0.011450,0.010038,0.017552,pass
7,0.0,0.0,0.020365,0.0,0.0,0.008902,0.009702,0.0,0.006603,0.011435,0.020331,pass
8,0.0,0.0,0.025078,0.0,0.0,0.012565,0.015766,0.0,0.011634,0.012862,0.019831,pass
9,0.0,0.0,0.011355,0.0,0.0,0.005146,0.004110,0.0,0.004178,0.007145,0.016167,pass
10,0.0,0.0,0.017121,0.0,0.0,0.011191,0.010665,0.0,0.008821,0.010614,0.016882,pass
11,0.0,0.0,0.027922,0.0,0.0,0.007919,0.012696,0.0,0.007957,0.010234,0.017537,pass
12,0.0,0.0,0.020576,0.0,0.0,0.010945,0.011663,0.0,0.006638,0.006289,0.012496,pass

[[       nan        nan 1.16411938        nan        nan 1.2024441
  1.22814588        nan 1.08262466 1.13987833 1.17794536]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,h 5,y 0,h 4,h 2,h 8,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.323971,0.318027,0.311019,0.307376,0.302441,0.266001,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 1,h 5,y 0,h 4,h 2,h 8,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.416293,0.413629,0.402609,0.401751,0.384299,0.343415,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,y 0,h 8,h 4,h 1,h 5,h 2,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.001934,0.001713,0.000958,0.000764,0.000658,0.000451,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_rx_inGap_12_.qasm

100%|██████████| 6/6 [00:00<00:00, 14.91it/s]
100%|██████████| 10/10 [00:00<00:00, 16.74it/s]

,cz 10,cz 9,h 8,cz 7,rx 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.025040,0.0,0.054200,0.0,0.012726,0.019600,0.0,0.007966,0.014678,fail
1,0.0,0.0,0.022971,0.0,0.087640,0.0,0.009133,0.011482,0.0,0.012746,0.013594,fail
2,0.0,0.0,0.018007,0.0,0.082406,0.0,0.007653,0.007794,0.0,0.011788,0.011155,fail
3,0.0,0.0,0.032470,0.0,0.077945,0.0,0.012471,0.013170,0.0,0.011141,0.015357,fail
4,0.0,0.0,0.021099,0.0,0.068786,0.0,0.012182,0.014585,0.0,0.011848,0.008042,fail
5,0.0,0.0,0.030496,0.0,0.071776,0.0,0.013839,0.018556,0.0,0.011113,0.015035,fail
6,0.0,0.0,0.024309,0.0,0.046021,0.0,0.013777,0.017951,0.0,0.007993,0.012450,pass
7,0.0,0.0,0.015034,0.0,0.033201,0.0,0.004332,0.005238,0.0,0.004608,0.007448,pass
8,0.0,0.0,0.023095,0.0,0.080247,0.0,0.011390,0.014336,0.0,0.013419,0.013757,pass
9,0.0,0.0,0.024886,0.0,0.081744,0.0,0.010120,0.015680,0.0,0.012669,0.011020,pass
10,0.0,0.0,0.023315,0.0,0.079741,0.0,0.012460,0.015163,0.0,0.012513,0.019339,pass
11,0.0,0.0,0.019873,0.0,0.048193,0.0,0.010683,0.015409,0.0,0.007155,0.006970,pass
12,0.0,0.0,0.023447,0.0,0.062042,0.0,0.009845,0.012592,0.0,0.009210,0.009715,pass
13,0.0,0.0,0.022577,0.0,0.089790,0.0,0.010964,0.017314,0.0,0.014197,0.020340,pass
14,0.0,0.0,0.022229,0.0,0.083825,0.0,0.014165,0.014592,0.0,0.014613,0.014644,pass
15,0.0,0.0,0.014294,0.0,0.057843,0.0,0.007077,0.014260,0.0,0.007931,0.010531,pass

[[       nan        nan 1.29807298        nan 1.18765859        nan
  1.2210033  1.38051311        nan 1.14827741 1.18339764]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 8,rx 6,h 4,h 1,h 0,h 3,cz 10,cz 9,cz 7,cz 5,cz 2
sum,0.413291,0.400537,0.393503,0.389689,0.381534,0.374083,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 8,rx 6,h 4,h 3,h 1,h 0,cz 10,cz 9,cz 7,cz 5,cz 2
sum,0.547411,0.519462,0.51362,0.503189,0.501557,0.49441,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,rx 6,h 8,h 3,h 0,h 4,h 1,cz 10,cz 9,cz 7,cz 5,cz 2
sum,0.029422,0.003625,0.001181,0.00099,0.000758,0.000727,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
6
Now evolving the following mutant:  AddGate_h_inGap_3_.qasm

100%|██████████| 10/10 [00:00<00:00, 13.33it/s]
100%|██████████| 10/10 [00:00<00:00, 16.07it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,h 2,h 1,h 0,pass/fail
0,0.0,0.0,0.022462,0.0,0.0,0.011299,0.013115,0.0,0.012798,0.007074,0.008853,fail
1,0.0,0.0,0.023837,0.0,0.0,0.013074,0.021219,0.0,0.014112,0.008508,0.010940,fail
2,0.0,0.0,0.023262,0.0,0.0,0.012130,0.016565,0.0,0.010145,0.006277,0.011719,fail
3,0.0,0.0,0.029335,0.0,0.0,0.014147,0.021317,0.0,0.014121,0.008656,0.013080,fail
4,0.0,0.0,0.027052,0.0,0.0,0.013875,0.016875,0.0,0.009641,0.005144,0.009697,fail
5,0.0,0.0,0.026395,0.0,0.0,0.014308,0.015006,0.0,0.011428,0.006884,0.010659,fail
6,0.0,0.0,0.022275,0.0,0.0,0.007600,0.011972,0.0,0.012867,0.007773,0.007636,fail
7,0.0,0.0,0.019033,0.0,0.0,0.007163,0.011532,0.0,0.006285,0.003435,0.006369,fail
8,0.0,0.0,0.028037,0.0,0.0,0.015579,0.017031,0.0,0.010151,0.005483,0.011436,fail
9,0.0,0.0,0.026038,0.0,0.0,0.013743,0.012673,0.0,0.008923,0.005403,0.009385,fail
10,0.0,0.0,0.025856,0.0,0.0,0.012990,0.017890,0.0,0.010372,0.006575,0.012966,pass
11,0.0,0.0,0.020480,0.0,0.0,0.009129,0.011578,0.0,0.009957,0.005932,0.004617,pass
12,0.0,0.0,0.026227,0.0,0.0,0.009542,0.013133,0.0,0.005973,0.003506,0.011252,pass
13,0.0,0.0,0.017478,0.0,0.0,0.007014,0.011282,0.0,0.007195,0.003904,0.011580,pass
14,0.0,0.0,0.022943,0.0,0.0,0.012810,0.018027,0.0,0.008760,0.005867,0.011430,pass
15,0.0,0.0,0.030388,0.0,0.0,0.009755,0.010664,0.0,0.010493,0.006579,0.007446,pass
16,0.0,0.0,0.029685,0.0,0.0,0.014055,0.014104,0.0,0.010133,0.006507,0.011178,pass
17,0.0,0.0,0.010521,0.0,0.0,0.002626,0.005330,0.0,0.005043,0.002812,0.006912,pass
18,0.0,0.0,0.033103,0.0,0.0,0.016088,0.016752,0.0,0.015443,0.009592,0.014844,pass
19,0.0,0.0,0.027480,0.0,0.0,0.013191,0.011954,0.0,0.010216,0.006226,0.013417,pass

[[       nan        nan 1.18417045        nan        nan 1.26740461
  1.35511563        nan 1.27825438 1.33922914 1.31092802]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 4,h 2,h 5,h 1,h 8,h 0,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.546165,0.541373,0.53415,0.529216,0.503626,0.485716,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 4,h 2,h 1,h 5,h 8,h 0,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.731195,0.714376,0.706401,0.703397,0.65272,0.6449,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 4,h 5,h 2,h 0,h 1,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.005991,0.002443,0.001495,0.001209,0.000985,0.000415,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_s_inGap_9_.qasm

100%|██████████| 7/7 [00:00<00:00, 15.32it/s]
100%|██████████| 10/10 [00:00<00:00, 15.26it/s]

,cz 10,cz 9,sdg 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.0,0.026247,0.0,0.0,0.014109,0.018562,0.0,0.011176,0.016074,fail
1,0.0,0.0,0.0,0.022680,0.0,0.0,0.008615,0.015065,0.0,0.012782,0.012234,fail
2,0.0,0.0,0.0,0.033391,0.0,0.0,0.011526,0.020771,0.0,0.014090,0.015069,fail
3,0.0,0.0,0.0,0.021869,0.0,0.0,0.010291,0.016255,0.0,0.011741,0.012497,fail
4,0.0,0.0,0.0,0.023497,0.0,0.0,0.010023,0.019957,0.0,0.010801,0.013796,fail
5,0.0,0.0,0.0,0.025517,0.0,0.0,0.013604,0.016797,0.0,0.012747,0.010511,fail
6,0.0,0.0,0.0,0.023462,0.0,0.0,0.009798,0.018469,0.0,0.012284,0.011816,fail
7,0.0,0.0,0.0,0.016481,0.0,0.0,0.006432,0.013171,0.0,0.008702,0.004665,pass
8,0.0,0.0,0.0,0.021981,0.0,0.0,0.012130,0.015590,0.0,0.010074,0.011477,pass
9,0.0,0.0,0.0,0.034000,0.0,0.0,0.012765,0.018150,0.0,0.010502,0.014770,pass
10,0.0,0.0,0.0,0.019345,0.0,0.0,0.008607,0.011754,0.0,0.010324,0.012304,pass
11,0.0,0.0,0.0,0.024627,0.0,0.0,0.009792,0.017636,0.0,0.011989,0.012561,pass
12,0.0,0.0,0.0,0.025598,0.0,0.0,0.013105,0.017597,0.0,0.010792,0.008181,pass
13,0.0,0.0,0.0,0.018976,0.0,0.0,0.010875,0.012058,0.0,0.006106,0.012143,pass
14,0.0,0.0,0.0,0.028014,0.0,0.0,0.012009,0.018175,0.0,0.011152,0.015789,pass
15,0.0,0.0,0.0,0.014158,0.0,0.0,0.009633,0.011585,0.0,0.009429,0.011588,pass
16,0.0,0.0,0.0,0.022069,0.0,0.0,0.008799,0.013122,0.0,0.010320,0.009614,pass

[[       nan        nan        nan 1.32305865        nan        nan
  1.26676263 1.15507087        nan 1.15193282 1.22309059]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,h 3,h 0,h 7,h 4,cz 10,cz 9,sdg 8,cz 6,cz 5,cz 2
sum,0.462787,0.458206,0.448568,0.439557,0.428114,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 1,h 3,h 0,h 7,h 4,cz 10,cz 9,sdg 8,cz 6,cz 5,cz 2
sum,0.596062,0.590521,0.585728,0.584946,0.563694,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 7,h 3,h 0,h 1,h 4,cz 10,cz 9,sdg 8,cz 6,cz 5,cz 2
sum,0.00432,0.002216,0.00119,0.001033,0.000856,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_rxx_inGap_4_.qasm

100%|██████████| 4/4 [00:00<00:00, 15.51it/s]
100%|██████████| 10/10 [00:00<00:00, 15.94it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,rxx 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.030778,0.0,0.0,0.014028,0.015140,0.0,0.0,0.007847,0.014205,fail
1,0.0,0.0,0.024300,0.0,0.0,0.014633,0.015417,0.0,0.0,0.012108,0.013729,fail
2,0.0,0.0,0.029885,0.0,0.0,0.014659,0.018561,0.0,0.0,0.012378,0.019644,fail
3,0.0,0.0,0.026574,0.0,0.0,0.014843,0.020039,0.0,0.0,0.014263,0.012535,fail
4,0.0,0.0,0.016138,0.0,0.0,0.009011,0.013701,0.0,0.0,0.009281,0.013279,pass
5,0.0,0.0,0.019809,0.0,0.0,0.010406,0.011674,0.0,0.0,0.011876,0.016443,pass
6,0.0,0.0,0.021495,0.0,0.0,0.010607,0.013759,0.0,0.0,0.010232,0.007080,pass
7,0.0,0.0,0.022481,0.0,0.0,0.012633,0.017691,0.0,0.0,0.010150,0.011988,pass
8,0.0,0.0,0.020399,0.0,0.0,0.010479,0.013823,0.0,0.0,0.009499,0.007248,pass
9,0.0,0.0,0.019807,0.0,0.0,0.008233,0.014273,0.0,0.0,0.012089,0.012477,pass
10,0.0,0.0,0.028242,0.0,0.0,0.012405,0.018501,0.0,0.0,0.012972,0.015552,pass
11,0.0,0.0,0.022853,0.0,0.0,0.007810,0.017258,0.0,0.0,0.008909,0.014348,pass
12,0.0,0.0,0.016935,0.0,0.0,0.004882,0.010336,0.0,0.0,0.006634,0.010539,pass
13,0.0,0.0,0.019534,0.0,0.0,0.010520,0.013401,0.0,0.0,0.008511,0.006078,pass

[[       nan        nan 1.10376674        nan        nan 1.02080564
  1.15904138        nan        nan 1.22437848 1.30714164]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 5,h 8,h 0,h 4,h 1,cz 10,cz 9,cz 7,cz 6,rxx 3,cz 2
sum,0.374889,0.349395,0.34322,0.323812,0.317523,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 5,h 0,h 8,h 4,h 1,cz 10,cz 9,cz 7,cz 6,rxx 3,cz 2
sum,0.470561,0.45538,0.445807,0.41764,0.414715,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 4,h 0,h 5,h 1,cz 10,cz 9,cz 7,cz 6,rxx 3,cz 2
sum,0.002957,0.001154,0.000878,0.000826,0.00053,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
3
Now evolving the following mutant:  AddGate_y_inGap_5_.qasm

100%|██████████| 7/7 [00:00<00:00, 15.42it/s]
100%|██████████| 10/10 [00:00<00:00, 16.70it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,y 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.024891,0.0,0.0,0.007870,0.026879,0.014931,0.0,0.011517,0.015658,fail
1,0.0,0.0,0.022483,0.0,0.0,0.011663,0.038254,0.018967,0.0,0.010961,0.010649,fail
2,0.0,0.0,0.026711,0.0,0.0,0.009991,0.030594,0.019473,0.0,0.008493,0.013135,fail
3,0.0,0.0,0.029394,0.0,0.0,0.011019,0.033680,0.015871,0.0,0.010541,0.011452,fail
4,0.0,0.0,0.014182,0.0,0.0,0.007789,0.030623,0.013774,0.0,0.009145,0.014413,fail
5,0.0,0.0,0.028025,0.0,0.0,0.007652,0.026505,0.016822,0.0,0.012144,0.011243,fail
6,0.0,0.0,0.030407,0.0,0.0,0.012756,0.039138,0.013836,0.0,0.011425,0.018348,fail
7,0.0,0.0,0.026659,0.0,0.0,0.017137,0.055187,0.020063,0.0,0.013226,0.019180,pass
8,0.0,0.0,0.023092,0.0,0.0,0.011637,0.040207,0.012953,0.0,0.010704,0.012003,pass
9,0.0,0.0,0.020767,0.0,0.0,0.010395,0.038501,0.013810,0.0,0.012606,0.015208,pass
10,0.0,0.0,0.018572,0.0,0.0,0.010383,0.033035,0.014289,0.0,0.007224,0.014140,pass
11,0.0,0.0,0.024053,0.0,0.0,0.011297,0.035244,0.009911,0.0,0.010186,0.012335,pass
12,0.0,0.0,0.031970,0.0,0.0,0.011798,0.037776,0.011480,0.0,0.012642,0.013820,pass
13,0.0,0.0,0.019025,0.0,0.0,0.007934,0.025658,0.011773,0.0,0.007653,0.010610,pass
14,0.0,0.0,0.024704,0.0,0.0,0.010722,0.038114,0.016710,0.0,0.011922,0.014165,pass
15,0.0,0.0,0.020228,0.0,0.0,0.007687,0.022326,0.010299,0.0,0.008367,0.009838,pass
16,0.0,0.0,0.026871,0.0,0.0,0.012220,0.041892,0.016403,0.0,0.012326,0.013008,pass

[[       nan        nan 1.20871133        nan        nan 1.29895426
  1.21400734 1.19913608        nan 1.14522953 1.35341823]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 3,h 8,h 0,h 1,h 5,y 4,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.452227,0.427374,0.414025,0.409903,0.382002,0.380167,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 3,h 8,h 0,h 1,h 5,y 4,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.587797,0.556517,0.554113,0.527262,0.506053,0.495549,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,y 4,h 8,h 3,h 0,h 1,h 5,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.006912,0.004285,0.00181,0.001262,0.000775,0.000664,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_rz_inGap_6_.qasm

100%|██████████| 3/3 [00:00<00:00, 14.08it/s]
100%|██████████| 10/10 [00:00<00:00, 16.74it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,rz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.027821,0.0,0.0,0.0,0.013689,0.016118,0.0,0.011307,0.015678,fail
1,0.0,0.0,0.021095,0.0,0.0,0.0,0.009559,0.018323,0.0,0.013515,0.013888,fail
2,0.0,0.0,0.023981,0.0,0.0,0.0,0.009915,0.016882,0.0,0.010468,0.011035,fail
3,0.0,0.0,0.020416,0.0,0.0,0.0,0.008379,0.013609,0.0,0.009753,0.008931,pass
4,0.0,0.0,0.018052,0.0,0.0,0.0,0.008084,0.012662,0.0,0.009143,0.010434,pass
5,0.0,0.0,0.025306,0.0,0.0,0.0,0.010076,0.012415,0.0,0.013671,0.015101,pass
6,0.0,0.0,0.021453,0.0,0.0,0.0,0.010869,0.014534,0.0,0.009076,0.009561,pass
7,0.0,0.0,0.029373,0.0,0.0,0.0,0.010626,0.018954,0.0,0.011667,0.015382,pass
8,0.0,0.0,0.022065,0.0,0.0,0.0,0.009926,0.012170,0.0,0.008958,0.009714,pass
9,0.0,0.0,0.014765,0.0,0.0,0.0,0.008139,0.009833,0.0,0.007555,0.012417,pass
10,0.0,0.0,0.014788,0.0,0.0,0.0,0.005797,0.007780,0.0,0.005935,0.009003,pass
11,0.0,0.0,0.026149,0.0,0.0,0.0,0.007885,0.012961,0.0,0.008514,0.010214,pass
12,0.0,0.0,0.020536,0.0,0.0,0.0,0.009687,0.008920,0.0,0.005570,0.011889,pass

[[       nan        nan 1.14495763        nan        nan        nan
  1.23836949 1.07105061        nan 1.14891926 1.15847781]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 3,h 1,h 4,h 0,h 8,cz 10,cz 9,cz 7,cz 6,rz 5,cz 2
sum,0.293006,0.282025,0.270427,0.264938,0.255062,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 3,h 1,h 4,h 0,h 8,cz 10,cz 9,cz 7,cz 6,rz 5,cz 2
sum,0.371462,0.363031,0.354149,0.341669,0.328071,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 3,h 0,h 1,h 4,cz 10,cz 9,cz 7,cz 6,rz 5,cz 2
sum,0.001654,0.000843,0.00053,0.000403,0.000356,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_p_inGap_2_.qasm

100%|██████████| 3/3 [00:00<00:00, 14.89it/s]
100%|██████████| 10/10 [00:00<00:00, 16.15it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,h 2,p 1,h 0,pass/fail
0,0.0,0.0,0.031750,0.0,0.0,0.011862,0.017133,0.0,0.013130,0.011669,0.009620,fail
1,0.0,0.0,0.029193,0.0,0.0,0.013889,0.015560,0.0,0.012668,0.011273,0.015794,fail
2,0.0,0.0,0.023489,0.0,0.0,0.010070,0.016893,0.0,0.010369,0.009132,0.011568,fail
3,0.0,0.0,0.022250,0.0,0.0,0.009172,0.007031,0.0,0.009299,0.008275,0.010303,pass
4,0.0,0.0,0.021355,0.0,0.0,0.008980,0.016277,0.0,0.010055,0.008995,0.012526,pass
5,0.0,0.0,0.014676,0.0,0.0,0.006652,0.008529,0.0,0.006383,0.005621,0.011444,pass
6,0.0,0.0,0.021114,0.0,0.0,0.006851,0.012332,0.0,0.008944,0.007851,0.009109,pass
7,0.0,0.0,0.020825,0.0,0.0,0.011539,0.013738,0.0,0.010625,0.009475,0.011121,pass
8,0.0,0.0,0.030079,0.0,0.0,0.014796,0.015472,0.0,0.011667,0.010266,0.010519,pass
9,0.0,0.0,0.012976,0.0,0.0,0.005393,0.009594,0.0,0.005164,0.004577,0.009844,pass
10,0.0,0.0,0.025972,0.0,0.0,0.012329,0.013984,0.0,0.013906,0.012397,0.010622,pass
11,0.0,0.0,0.019414,0.0,0.0,0.009944,0.011448,0.0,0.008159,0.007335,0.008888,pass
12,0.0,0.0,0.013015,0.0,0.0,0.008383,0.009652,0.0,0.003857,0.003431,0.008105,pass

[[       nan        nan 1.12812402        nan        nan 1.16321523
  1.03657223        nan 1.08910551 1.09141234 1.28122945]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 4,h 8,h 2,p 1,h 5,h 0,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.295781,0.295103,0.291137,0.290796,0.275846,0.265177,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 8,h 4,h 2,p 1,h 5,h 0,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.378332,0.37243,0.370406,0.370141,0.356062,0.350115,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 4,h 0,h 2,h 5,p 1,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.002227,0.000789,0.000441,0.000424,0.000415,0.000334,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_rzz_inGap_5_.qasm

100%|██████████| 7/7 [00:00<00:00, 15.61it/s]
100%|██████████| 10/10 [00:00<00:00, 16.03it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,rzz 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.020637,0.0,0.0,0.010653,0.077763,0.013121,0.0,0.009239,0.008756,fail
1,0.0,0.0,0.031320,0.0,0.0,0.014661,0.068731,0.016821,0.0,0.012934,0.013836,fail
2,0.0,0.0,0.023368,0.0,0.0,0.010685,0.063720,0.009057,0.0,0.008420,0.008034,fail
3,0.0,0.0,0.027292,0.0,0.0,0.011887,0.071431,0.011967,0.0,0.008354,0.011416,fail
4,0.0,0.0,0.022146,0.0,0.0,0.013143,0.062764,0.015222,0.0,0.009362,0.009285,fail
5,0.0,0.0,0.022866,0.0,0.0,0.011302,0.059934,0.010883,0.0,0.007667,0.012268,fail
6,0.0,0.0,0.022825,0.0,0.0,0.012631,0.073086,0.014577,0.0,0.008003,0.012849,fail
7,0.0,0.0,0.024507,0.0,0.0,0.008556,0.070290,0.013799,0.0,0.009624,0.014014,pass
8,0.0,0.0,0.027545,0.0,0.0,0.009036,0.077280,0.014046,0.0,0.010545,0.009547,pass
9,0.0,0.0,0.028028,0.0,0.0,0.011363,0.085775,0.012437,0.0,0.010654,0.011834,pass
10,0.0,0.0,0.020593,0.0,0.0,0.012999,0.064745,0.010822,0.0,0.008770,0.006759,pass
11,0.0,0.0,0.007388,0.0,0.0,0.009763,0.048064,0.009573,0.0,0.008830,0.009311,pass
12,0.0,0.0,0.016778,0.0,0.0,0.006509,0.063708,0.007991,0.0,0.006575,0.008315,pass
13,0.0,0.0,0.028847,0.0,0.0,0.013610,0.062728,0.015120,0.0,0.008270,0.014486,pass
14,0.0,0.0,0.032131,0.0,0.0,0.014094,0.074957,0.010434,0.0,0.011120,0.011756,pass
15,0.0,0.0,0.019521,0.0,0.0,0.008988,0.074001,0.008049,0.0,0.005920,0.007087,pass
16,0.0,0.0,0.025957,0.0,0.0,0.010132,0.067978,0.013996,0.0,0.009884,0.013783,pass

[[       nan        nan 1.28622457        nan        nan 1.20793396
  1.14014514 1.28478296        nan 1.41508025 1.2669253 ]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 5,h 3,h 8,h 0,h 1,rzz 4,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.447139,0.440797,0.424279,0.416963,0.41498,0.409123,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 3,h 5,h 1,h 8,h 0,rzz 4,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.582379,0.582168,0.561788,0.560709,0.549028,0.525739,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,rzz 4,h 8,h 3,h 5,h 0,h 1,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.029643,0.004018,0.00118,0.001016,0.000822,0.000577,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_h_inGap_10_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.82it/s]
100%|██████████| 10/10 [00:01<00:00,  9.84it/s]

,cz 10,h 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.041607,0.238280,0.029421,0.0,0.0,0.010316,0.015199,0.0,0.012513,0.011939,fail
1,0.0,0.044819,0.268467,0.031692,0.0,0.0,0.008604,0.009450,0.0,0.012309,0.011028,fail
2,0.0,0.036173,0.203716,0.025579,0.0,0.0,0.014459,0.014698,0.0,0.012494,0.013039,fail
3,0.0,0.043801,0.237613,0.030972,0.0,0.0,0.006234,0.009838,0.0,0.012516,0.012201,fail
4,0.0,0.050083,0.281433,0.035414,0.0,0.0,0.008828,0.015766,0.0,0.013301,0.010290,fail
5,0.0,0.043509,0.240820,0.030765,0.0,0.0,0.013818,0.019447,0.0,0.014089,0.014633,fail
6,0.0,0.039658,0.236017,0.028043,0.0,0.0,0.009486,0.011839,0.0,0.011907,0.014175,fail
7,0.0,0.064097,0.388884,0.045323,0.0,0.0,0.016828,0.025821,0.0,0.014438,0.011925,fail
8,0.0,0.044403,0.261118,0.031398,0.0,0.0,0.010870,0.008986,0.0,0.011475,0.015639,fail
9,0.0,0.036053,0.217536,0.025494,0.0,0.0,0.009113,0.018380,0.0,0.010007,0.013219,fail
10,0.0,0.043179,0.220138,0.030532,0.0,0.0,0.014051,0.020827,0.0,0.016479,0.015192,pass
11,0.0,0.050367,0.281047,0.035615,0.0,0.0,0.015047,0.014168,0.0,0.016446,0.018215,pass
12,0.0,0.017528,0.094629,0.012394,0.0,0.0,0.007535,0.009505,0.0,0.005318,0.009251,pass
13,0.0,0.029684,0.159241,0.020990,0.0,0.0,0.005535,0.016876,0.0,0.008556,0.013736,pass
14,0.0,0.039510,0.222251,0.027938,0.0,0.0,0.011457,0.010427,0.0,0.010909,0.010570,pass
15,0.0,0.038732,0.230683,0.027388,0.0,0.0,0.007652,0.015142,0.0,0.010324,0.014223,pass
16,0.0,0.042790,0.209051,0.030257,0.0,0.0,0.011359,0.018867,0.0,0.018240,0.013624,pass
17,0.0,0.024322,0.128569,0.017198,0.0,0.0,0.008242,0.005603,0.0,0.008240,0.010318,pass
18,0.0,0.033569,0.170241,0.023737,0.0,0.0,0.014200,0.020752,0.0,0.012348,0.013476,pass
19,0.0,0.044934,0.232910,0.031773,0.0,0.0,0.013473,0.019005,0.0,0.009909,0.013041,pass

[[       nan 1.44296102 1.51088373 1.44296102        nan        nan
  1.55020771 1.72804326        nan 1.15456732 1.22092097]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,cz 8,h 9,h 7,h 1,h 4,h 3,h 0,cz 10,cz 6,cz 5,cz 2
sum,0.56911,0.549201,0.549201,0.517121,0.500011,0.49709,0.49315,0.0,0.0,0.0,0.0

custom SCORES

,cz 8,h 9,h 7,h 3,h 4,h 1,h 0,cz 10,cz 6,cz 5,cz 2
sum,0.784075,0.74732,0.74732,0.711839,0.693792,0.666383,0.643674,0.0,0.0,0.0,0.0

DSTAR SCORES

,cz 8,h 9,h 7,h 3,h 0,h 1,h 4,cz 10,cz 6,cz 5,cz 2
sum,0.554441,0.019038,0.009618,0.002199,0.001619,0.001546,0.001166,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
9
Now evolving the following mutant:  AddGate_id_inGap_5_.qasm

100%|██████████| 4/4 [00:00<00:00, 13.58it/s]
100%|██████████| 10/10 [00:00<00:00, 13.53it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,id 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.019007,0.0,0.0,0.010281,0.0,0.016204,0.0,0.010704,0.011220,fail
1,0.0,0.0,0.029216,0.0,0.0,0.014500,0.0,0.017985,0.0,0.013488,0.012819,fail
2,0.0,0.0,0.016802,0.0,0.0,0.005244,0.0,0.012527,0.0,0.008458,0.012898,fail
3,0.0,0.0,0.027701,0.0,0.0,0.009954,0.0,0.010722,0.0,0.010557,0.012749,fail
4,0.0,0.0,0.023190,0.0,0.0,0.010287,0.0,0.016542,0.0,0.009163,0.009960,pass
5,0.0,0.0,0.030536,0.0,0.0,0.014676,0.0,0.018086,0.0,0.012244,0.018668,pass
6,0.0,0.0,0.027968,0.0,0.0,0.010856,0.0,0.011591,0.0,0.007646,0.015209,pass
7,0.0,0.0,0.016467,0.0,0.0,0.009823,0.0,0.012410,0.0,0.010228,0.014581,pass
8,0.0,0.0,0.022048,0.0,0.0,0.009283,0.0,0.010449,0.0,0.007959,0.010515,pass
9,0.0,0.0,0.014246,0.0,0.0,0.009960,0.0,0.014736,0.0,0.006821,0.009691,pass
10,0.0,0.0,0.017604,0.0,0.0,0.011491,0.0,0.011448,0.0,0.010387,0.011578,pass
11,0.0,0.0,0.020736,0.0,0.0,0.011680,0.0,0.013011,0.0,0.012935,0.012959,pass
12,0.0,0.0,0.022115,0.0,0.0,0.008321,0.0,0.013883,0.0,0.008924,0.008310,pass
13,0.0,0.0,0.030350,0.0,0.0,0.015574,0.0,0.019047,0.0,0.010505,0.015980,pass

[[       nan        nan 1.26033254        nan        nan 1.45077529
         nan 1.25246515        nan 1.24867516 1.03837825]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,h 8,h 3,h 0,h 5,cz 10,cz 9,cz 7,cz 6,id 4,cz 2
sum,0.308581,0.291603,0.289152,0.280496,0.263141,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 1,h 8,h 3,h 5,h 0,cz 10,cz 9,cz 7,cz 6,id 4,cz 2
sum,0.404911,0.383482,0.37969,0.358581,0.353312,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 3,h 0,h 1,h 5,cz 10,cz 9,cz 7,cz 6,id 4,cz 2
sum,0.002035,0.000797,0.000598,0.000456,0.000389,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_rxx_inGap_14_.qasm

100%|██████████| 7/7 [00:01<00:00,  4.22it/s]
100%|██████████| 10/10 [00:01<00:00,  5.17it/s]

,rxx 10,cz 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.981260,0.476607,0.869995,0.323945,0.521861,0.696976,0.424497,0.082029,0.0,0.074089,0.092601,fail
1,0.982962,0.475857,0.817105,0.402039,0.488601,0.724796,0.388461,0.103144,0.0,0.061903,0.069617,fail
2,0.869771,0.358411,0.637221,0.386868,0.450334,0.620518,0.324688,0.123215,0.0,0.048262,0.063669,fail
3,0.627230,0.283642,0.494503,0.172654,0.326593,0.483226,0.318708,0.062872,0.0,0.048897,0.054939,fail
4,0.918980,0.404171,0.685887,0.363758,0.432533,0.661936,0.376110,0.113140,0.0,0.053579,0.071598,fail
5,0.723378,0.333463,0.575054,0.256344,0.349113,0.496495,0.329606,0.077206,0.0,0.053646,0.046427,fail
6,0.802820,0.365396,0.646757,0.287270,0.415029,0.594232,0.354480,0.083843,0.0,0.054724,0.058696,fail
7,0.763574,0.350473,0.624521,0.214345,0.378898,0.566849,0.378568,0.075008,0.0,0.062123,0.051793,pass
8,0.358408,0.202459,0.377164,0.169112,0.188341,0.330665,0.126457,0.034381,0.0,0.034198,0.040812,pass
9,0.595777,0.301575,0.505943,0.264433,0.308287,0.413689,0.232239,0.064527,0.0,0.037766,0.054778,pass
10,0.487444,0.192924,0.442475,0.189522,0.290101,0.391635,0.198201,0.055336,0.0,0.054186,0.040654,pass
11,0.451346,0.199477,0.368322,0.161186,0.208753,0.286251,0.210815,0.058063,0.0,0.021121,0.038061,pass
12,0.497009,0.270578,0.449438,0.158216,0.225042,0.355390,0.253555,0.047320,0.0,0.035528,0.039827,pass
13,0.622625,0.271899,0.563728,0.187978,0.339916,0.497316,0.305566,0.065402,0.0,0.052849,0.062967,pass
14,0.732203,0.379561,0.593030,0.278770,0.356527,0.470156,0.304539,0.053744,0.0,0.044537,0.051730,pass
15,0.784695,0.338881,0.698952,0.278337,0.416124,0.576958,0.348242,0.085145,0.0,0.051623,0.083086,pass
16,0.692246,0.296189,0.544263,0.259036,0.352914,0.526040,0.305336,0.083681,0.0,0.062236,0.046616,pass

[[1.16496169 1.23677142 1.28846721 1.28336924 1.22417916 1.18591776
  1.18077545 1.33629143        nan 1.31263193 1.41669505]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 3,h 7,rxx 10,cz 6,cz 5,cz 9,h 4,cz 8,h 0,h 1,cz 2
sum,0.509007,0.503668,0.496681,0.493318,0.492133,0.490324,0.485814,0.477699,0.472735,0.464132,0.0

custom SCORES

,h 3,h 7,cz 6,cz 9,rxx 10,h 0,cz 5,cz 8,h 4,h 1,cz 2
sum,0.679052,0.665266,0.644295,0.641928,0.641335,0.640166,0.638041,0.631573,0.629223,0.61644,0.0

DSTAR SCORES

,rxx 10,cz 8,cz 5,cz 6,cz 9,h 4,h 7,h 3,h 0,h 1,cz 2
sum,2.686538,1.835988,1.603408,0.884721,0.742222,0.655354,0.524915,0.054654,0.027875,0.020936,0.0

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_rz_inGap_10_.qasm

100%|██████████| 3/3 [00:00<00:00, 16.66it/s]
100%|██████████| 10/10 [00:00<00:00, 17.04it/s]

,cz 10,rz 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.0,0.026249,0.0,0.0,0.010088,0.018375,0.0,0.009422,0.014478,fail
1,0.0,0.0,0.0,0.025795,0.0,0.0,0.011767,0.020943,0.0,0.009754,0.016642,fail
2,0.0,0.0,0.0,0.019894,0.0,0.0,0.010866,0.014510,0.0,0.009425,0.009401,fail
3,0.0,0.0,0.0,0.020393,0.0,0.0,0.009698,0.009934,0.0,0.010906,0.008764,pass
4,0.0,0.0,0.0,0.027919,0.0,0.0,0.013291,0.018577,0.0,0.010999,0.013884,pass
5,0.0,0.0,0.0,0.014718,0.0,0.0,0.007188,0.005931,0.0,0.006476,0.011410,pass
6,0.0,0.0,0.0,0.025603,0.0,0.0,0.011817,0.019931,0.0,0.012601,0.015050,pass
7,0.0,0.0,0.0,0.022070,0.0,0.0,0.011868,0.021907,0.0,0.008814,0.011990,pass
8,0.0,0.0,0.0,0.026545,0.0,0.0,0.011166,0.015815,0.0,0.010620,0.009368,pass
9,0.0,0.0,0.0,0.019955,0.0,0.0,0.011847,0.017869,0.0,0.012053,0.010116,pass
10,0.0,0.0,0.0,0.016815,0.0,0.0,0.008061,0.012109,0.0,0.006669,0.007186,pass
11,0.0,0.0,0.0,0.026506,0.0,0.0,0.013636,0.016966,0.0,0.009447,0.015953,pass
12,0.0,0.0,0.0,0.022559,0.0,0.0,0.009801,0.013256,0.0,0.009205,0.010439,pass

[[       nan        nan        nan 1.09464702        nan        nan
  1.07884762 1.16720509        nan 1.02311799 1.23210016]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 0,h 3,h 7,h 4,h 1,cz 10,rz 9,cz 8,cz 6,cz 5,cz 2
sum,0.261967,0.261143,0.243841,0.231909,0.226289,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 0,h 3,h 7,h 4,h 1,cz 10,rz 9,cz 8,cz 6,cz 5,cz 2
sum,0.34266,0.337345,0.310571,0.294457,0.284169,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 7,h 3,h 0,h 4,h 1,cz 10,rz 9,cz 8,cz 6,cz 5,cz 2
sum,0.001606,0.000919,0.000527,0.000344,0.000264,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
9
Now evolving the following mutant:  AddGate_sx_inGap_6_.qasm

100%|██████████| 3/3 [00:00<00:00, 13.43it/s]
100%|██████████| 10/10 [00:00<00:00, 17.25it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,sxdg 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.024511,0.0,0.0,0.054390,0.042520,0.014535,0.0,0.010365,0.011853,fail
1,0.0,0.0,0.027150,0.0,0.0,0.060096,0.047197,0.012968,0.0,0.010544,0.011175,fail
2,0.0,0.0,0.017020,0.0,0.0,0.036150,0.028408,0.011640,0.0,0.009062,0.010191,fail
3,0.0,0.0,0.025098,0.0,0.0,0.048795,0.037745,0.008816,0.0,0.007301,0.007739,pass
4,0.0,0.0,0.021754,0.0,0.0,0.071652,0.056673,0.020077,0.0,0.009318,0.015876,pass
5,0.0,0.0,0.023971,0.0,0.0,0.038849,0.030170,0.013343,0.0,0.007638,0.009554,pass
6,0.0,0.0,0.026970,0.0,0.0,0.036563,0.029045,0.012065,0.0,0.008702,0.014908,pass
7,0.0,0.0,0.021339,0.0,0.0,0.042106,0.033232,0.009408,0.0,0.010576,0.013355,pass
8,0.0,0.0,0.023942,0.0,0.0,0.053236,0.040602,0.009461,0.0,0.009361,0.010451,pass
9,0.0,0.0,0.021897,0.0,0.0,0.033650,0.026846,0.008273,0.0,0.008432,0.014990,pass
10,0.0,0.0,0.024430,0.0,0.0,0.062928,0.049264,0.015661,0.0,0.012996,0.016274,pass
11,0.0,0.0,0.029374,0.0,0.0,0.051326,0.040329,0.013623,0.0,0.011442,0.016629,pass
12,0.0,0.0,0.014386,0.0,0.0,0.047836,0.039347,0.012853,0.0,0.011366,0.011237,pass

[[       nan        nan 1.18590844        nan        nan 1.19684178
  1.19866684 1.11398238        nan 1.05541651 1.07040976]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 3,sxdg 5,h 1,h 4,h 8,h 0,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.240551,0.236262,0.235799,0.2356,0.227538,0.202271,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 3,sxdg 5,h 4,h 1,h 8,h 0,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.307544,0.306954,0.306201,0.298016,0.294998,0.256399,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,sxdg 5,h 4,h 8,h 3,h 0,h 1,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.006507,0.004124,0.001459,0.000491,0.000352,0.00029,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rzz_inGap_6_.qasm

100%|██████████| 6/6 [00:00<00:00, 16.46it/s]
100%|██████████| 10/10 [00:00<00:00, 17.24it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,rzz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.024259,0.0,0.0,0.0,0.011460,0.013643,0.0,0.012055,0.014055,fail
1,0.0,0.0,0.029339,0.0,0.0,0.0,0.013645,0.018696,0.0,0.008685,0.013376,fail
2,0.0,0.0,0.027006,0.0,0.0,0.0,0.013492,0.013404,0.0,0.012308,0.014982,fail
3,0.0,0.0,0.025261,0.0,0.0,0.0,0.010035,0.012876,0.0,0.008415,0.013649,fail
4,0.0,0.0,0.021263,0.0,0.0,0.0,0.011443,0.015419,0.0,0.010339,0.016438,fail
5,0.0,0.0,0.022901,0.0,0.0,0.0,0.013790,0.019784,0.0,0.010943,0.013846,fail
6,0.0,0.0,0.020838,0.0,0.0,0.0,0.010392,0.009850,0.0,0.006237,0.011693,pass
7,0.0,0.0,0.026140,0.0,0.0,0.0,0.011104,0.011768,0.0,0.010598,0.006157,pass
8,0.0,0.0,0.017075,0.0,0.0,0.0,0.010067,0.015876,0.0,0.010473,0.011852,pass
9,0.0,0.0,0.028627,0.0,0.0,0.0,0.012554,0.016235,0.0,0.011725,0.014701,pass
10,0.0,0.0,0.020336,0.0,0.0,0.0,0.009594,0.016515,0.0,0.009618,0.010792,pass
11,0.0,0.0,0.012918,0.0,0.0,0.0,0.008812,0.007274,0.0,0.006815,0.006723,pass
12,0.0,0.0,0.021951,0.0,0.0,0.0,0.009687,0.012847,0.0,0.011275,0.013627,pass
13,0.0,0.0,0.019297,0.0,0.0,0.0,0.007206,0.013435,0.0,0.008061,0.007660,pass
14,0.0,0.0,0.011326,0.0,0.0,0.0,0.005951,0.011160,0.0,0.007809,0.009687,pass
15,0.0,0.0,0.022727,0.0,0.0,0.0,0.011214,0.010483,0.0,0.010157,0.013785,pass

[[       nan        nan 1.17334351        nan        nan        nan
  1.12015438 1.2652232         nan 1.17694173 1.14225327]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 0,h 4,h 3,h 8,h 1,cz 10,cz 9,cz 7,cz 6,rzz 5,cz 2
sum,0.447338,0.433363,0.427893,0.427113,0.403475,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 0,h 3,h 4,h 8,h 1,cz 10,cz 9,cz 7,cz 6,rzz 5,cz 2
sum,0.575081,0.563238,0.554721,0.552401,0.522192,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 3,h 0,h 4,h 1,cz 10,cz 9,cz 7,cz 6,rzz 5,cz 2
sum,0.00363,0.001437,0.001221,0.000895,0.000646,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_ccx_inGap_8_.qasm

100%|██████████| 7/7 [00:02<00:00,  3.37it/s]
100%|██████████| 10/10 [00:02<00:00,  3.67it/s]

,cz 10,cz 9,h 8,ccx 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.021786,0.209953,0.0,0.0,0.011107,0.014728,0.0,0.013341,0.017193,fail
1,0.0,0.0,0.025483,0.207286,0.0,0.0,0.010890,0.014068,0.0,0.010006,0.014856,fail
2,0.0,0.0,0.026931,0.207284,0.0,0.0,0.010258,0.014139,0.0,0.012898,0.011607,fail
3,0.0,0.0,0.031930,0.232814,0.0,0.0,0.011596,0.015824,0.0,0.011487,0.009396,fail
4,0.0,0.0,0.024237,0.200243,0.0,0.0,0.010826,0.017847,0.0,0.010884,0.010957,fail
5,0.0,0.0,0.020457,0.212007,0.0,0.0,0.010559,0.013679,0.0,0.010732,0.016480,fail
6,0.0,0.0,0.024160,0.247864,0.0,0.0,0.012523,0.018828,0.0,0.013070,0.015148,fail
7,0.0,0.0,0.020776,0.214953,0.0,0.0,0.012165,0.014659,0.0,0.011660,0.013900,pass
8,0.0,0.0,0.010004,0.158204,0.0,0.0,0.007760,0.010294,0.0,0.006213,0.010280,pass
9,0.0,0.0,0.024948,0.230625,0.0,0.0,0.010676,0.014713,0.0,0.015322,0.012329,pass
10,0.0,0.0,0.023642,0.206183,0.0,0.0,0.009701,0.013337,0.0,0.011590,0.010541,pass
11,0.0,0.0,0.022517,0.193978,0.0,0.0,0.009494,0.011306,0.0,0.007399,0.012090,pass
12,0.0,0.0,0.025953,0.195689,0.0,0.0,0.009929,0.014127,0.0,0.011282,0.010482,pass
13,0.0,0.0,0.026170,0.223963,0.0,0.0,0.009772,0.014690,0.0,0.010907,0.014139,pass
14,0.0,0.0,0.011980,0.161463,0.0,0.0,0.007102,0.009226,0.0,0.004731,0.009617,pass
15,0.0,0.0,0.010492,0.114143,0.0,0.0,0.005921,0.007606,0.0,0.007582,0.007601,pass
16,0.0,0.0,0.021429,0.209445,0.0,0.0,0.010400,0.016358,0.0,0.015759,0.012488,pass

[[       nan        nan 1.27732232 1.14339733        nan        nan
  1.12735175 1.20788275        nan 1.13310998 1.25840641]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 8,h 3,h 0,h 4,h 1,ccx 7,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.469258,0.463462,0.457366,0.455584,0.44583,0.442909,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 8,h 3,h 0,h 4,h 1,ccx 7,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.619107,0.603414,0.601254,0.583985,0.572124,0.569515,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,ccx 7,h 8,h 3,h 0,h 1,h 4,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.258474,0.004254,0.001671,0.001286,0.000956,0.000852,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
7
Now evolving the following mutant:  AddGate_ccx_inGap_9_.qasm

100%|██████████| 4/4 [00:01<00:00,  3.83it/s]
100%|██████████| 10/10 [00:02<00:00,  3.94it/s]

,cz 10,cz 9,ccx 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.218517,0.026822,0.0,0.0,0.007973,0.012669,0.0,0.007736,0.011901,fail
1,0.0,0.0,0.220526,0.024755,0.0,0.0,0.007583,0.010000,0.0,0.009604,0.007555,fail
2,0.0,0.0,0.215825,0.026687,0.0,0.0,0.008010,0.012013,0.0,0.011353,0.009883,fail
3,0.0,0.0,0.199650,0.022925,0.0,0.0,0.007476,0.010183,0.0,0.005242,0.007299,fail
4,0.0,0.0,0.157142,0.023287,0.0,0.0,0.005640,0.008463,0.0,0.006749,0.006426,pass
5,0.0,0.0,0.193230,0.026728,0.0,0.0,0.007924,0.010492,0.0,0.007625,0.007376,pass
6,0.0,0.0,0.167632,0.022507,0.0,0.0,0.006686,0.008104,0.0,0.006112,0.002562,pass
7,0.0,0.0,0.189856,0.027080,0.0,0.0,0.008105,0.011054,0.0,0.009466,0.011146,pass
8,0.0,0.0,0.156800,0.020462,0.0,0.0,0.007342,0.010471,0.0,0.008989,0.012831,pass
9,0.0,0.0,0.215893,0.030366,0.0,0.0,0.007930,0.010487,0.0,0.008977,0.012722,pass
10,0.0,0.0,0.220691,0.025633,0.0,0.0,0.008296,0.011704,0.0,0.007869,0.009730,pass
11,0.0,0.0,0.173964,0.021681,0.0,0.0,0.006915,0.009026,0.0,0.005580,0.009378,pass
12,0.0,0.0,0.175969,0.025466,0.0,0.0,0.006080,0.008495,0.0,0.006360,0.008587,pass
13,0.0,0.0,0.142086,0.021238,0.0,0.0,0.005657,0.007463,0.0,0.004848,0.008463,pass

[[       nan        nan 1.03228079 1.06026814        nan        nan
  1.0321063  1.12954315        nan 1.33816978 1.29935939]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,ccx 8,h 3,h 1,h 4,h 7,h 0,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.32273,0.31904,0.318611,0.305485,0.292764,0.2911,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 1,h 3,ccx 8,h 0,h 4,h 7,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.425201,0.409132,0.406017,0.385661,0.384308,0.370366,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,ccx 8,h 7,h 3,h 0,h 1,h 4,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.126043,0.002412,0.000491,0.000328,0.000283,0.000237,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_z_inGap_5_.qasm

100%|██████████| 5/5 [00:00<00:00, 14.68it/s]
100%|██████████| 10/10 [00:00<00:00, 15.90it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,z 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.025544,0.0,0.0,0.010017,0.031243,0.009514,0.0,0.012371,0.010825,fail
1,0.0,0.0,0.024863,0.0,0.0,0.011139,0.038237,0.014993,0.0,0.011269,0.014018,fail
2,0.0,0.0,0.026334,0.0,0.0,0.014222,0.045986,0.011385,0.0,0.011154,0.013305,fail
3,0.0,0.0,0.019632,0.0,0.0,0.011732,0.039593,0.015460,0.0,0.011640,0.012053,fail
4,0.0,0.0,0.023946,0.0,0.0,0.013383,0.047667,0.015719,0.0,0.014849,0.018045,fail
5,0.0,0.0,0.015785,0.0,0.0,0.007707,0.025270,0.014697,0.0,0.008223,0.008618,pass
6,0.0,0.0,0.033013,0.0,0.0,0.013949,0.041169,0.018455,0.0,0.010171,0.011459,pass
7,0.0,0.0,0.023705,0.0,0.0,0.010459,0.033915,0.017680,0.0,0.009125,0.015041,pass
8,0.0,0.0,0.018211,0.0,0.0,0.011513,0.037815,0.016563,0.0,0.007552,0.014704,pass
9,0.0,0.0,0.025130,0.0,0.0,0.012973,0.042222,0.016736,0.0,0.013581,0.015161,pass
10,0.0,0.0,0.020771,0.0,0.0,0.011108,0.036939,0.016737,0.0,0.011396,0.012786,pass
11,0.0,0.0,0.027721,0.0,0.0,0.007203,0.023130,0.018234,0.0,0.010810,0.017439,pass
12,0.0,0.0,0.021734,0.0,0.0,0.011013,0.037187,0.015758,0.0,0.011172,0.012615,pass
13,0.0,0.0,0.022412,0.0,0.0,0.008822,0.030767,0.017078,0.0,0.010501,0.012847,pass
14,0.0,0.0,0.026738,0.0,0.0,0.012164,0.041162,0.016154,0.0,0.008766,0.017350,pass

[[       nan        nan 1.09433852        nan        nan 1.1754879
  1.17565289 1.1717917         nan 1.21152673 1.32206861]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,z 4,h 5,h 8,h 0,h 3,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.376938,0.367055,0.361362,0.338414,0.33086,0.285207,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 1,z 4,h 5,h 0,h 8,h 3,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.491106,0.474937,0.467556,0.440214,0.430999,0.368758,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,z 4,h 8,h 0,h 3,h 1,h 5,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.007682,0.002765,0.000906,0.00087,0.000736,0.000717,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_s_inGap_5_.qasm

100%|██████████| 6/6 [00:00<00:00, 15.32it/s]
100%|██████████| 10/10 [00:00<00:00, 16.01it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,sdg 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.016766,0.0,0.0,0.008707,0.008345,0.014923,0.0,0.009804,0.008959,fail
1,0.0,0.0,0.024385,0.0,0.0,0.014094,0.013011,0.014772,0.0,0.010268,0.015118,fail
2,0.0,0.0,0.026478,0.0,0.0,0.014143,0.012653,0.014798,0.0,0.009855,0.012118,fail
3,0.0,0.0,0.031529,0.0,0.0,0.011070,0.009995,0.014524,0.0,0.013821,0.015071,fail
4,0.0,0.0,0.024730,0.0,0.0,0.006291,0.005515,0.012662,0.0,0.008102,0.009684,fail
5,0.0,0.0,0.027100,0.0,0.0,0.012185,0.010934,0.015891,0.0,0.013595,0.014851,fail
6,0.0,0.0,0.021541,0.0,0.0,0.009326,0.008549,0.011375,0.0,0.005624,0.010245,pass
7,0.0,0.0,0.018793,0.0,0.0,0.008652,0.008111,0.014616,0.0,0.010410,0.010319,pass
8,0.0,0.0,0.025326,0.0,0.0,0.011471,0.010455,0.017690,0.0,0.007665,0.011536,pass
9,0.0,0.0,0.023273,0.0,0.0,0.012376,0.011381,0.017938,0.0,0.011198,0.013350,pass
10,0.0,0.0,0.018514,0.0,0.0,0.012725,0.011659,0.010284,0.0,0.008334,0.014381,pass
11,0.0,0.0,0.017183,0.0,0.0,0.009780,0.009050,0.013201,0.0,0.009192,0.015413,pass
12,0.0,0.0,0.021243,0.0,0.0,0.015116,0.013942,0.015027,0.0,0.011286,0.016142,pass
13,0.0,0.0,0.021063,0.0,0.0,0.009596,0.008949,0.013404,0.0,0.008196,0.009678,pass
14,0.0,0.0,0.022626,0.0,0.0,0.010052,0.009162,0.016231,0.0,0.008758,0.010717,pass
15,0.0,0.0,0.022449,0.0,0.0,0.011828,0.010838,0.013056,0.0,0.010684,0.006967,pass

[[       nan        nan 1.25291944        nan        nan 1.2762518
  1.29132096 1.08881949        nan 1.26709742 1.19663228]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,h 8,h 0,h 3,h 5,sdg 4,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.417399,0.415947,0.389627,0.380094,0.374783,0.371909,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 1,h 8,h 0,h 5,sdg 4,h 3,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.54962,0.546234,0.506187,0.494362,0.491973,0.483557,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 3,h 0,h 5,h 1,sdg 4,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.00367,0.001248,0.000939,0.000723,0.000703,0.000599,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_p_inGap_9_.qasm

100%|██████████| 7/7 [00:00<00:00, 15.40it/s]
100%|██████████| 10/10 [00:00<00:00, 15.74it/s]

,cz 10,cz 9,p 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.0,0.027381,0.0,0.0,0.012557,0.014899,0.0,0.012412,0.012355,fail
1,0.0,0.0,0.0,0.025109,0.0,0.0,0.010718,0.012778,0.0,0.010792,0.011991,fail
2,0.0,0.0,0.0,0.024045,0.0,0.0,0.009354,0.012997,0.0,0.011057,0.012081,fail
3,0.0,0.0,0.0,0.024932,0.0,0.0,0.013702,0.011870,0.0,0.007210,0.012583,fail
4,0.0,0.0,0.0,0.020248,0.0,0.0,0.010548,0.013218,0.0,0.011433,0.010270,fail
5,0.0,0.0,0.0,0.025167,0.0,0.0,0.010323,0.013993,0.0,0.011751,0.012860,fail
6,0.0,0.0,0.0,0.031273,0.0,0.0,0.013428,0.016858,0.0,0.013350,0.014946,fail
7,0.0,0.0,0.0,0.023769,0.0,0.0,0.008297,0.010464,0.0,0.008176,0.011410,pass
8,0.0,0.0,0.0,0.027532,0.0,0.0,0.008003,0.012232,0.0,0.010710,0.014923,pass
9,0.0,0.0,0.0,0.021720,0.0,0.0,0.009857,0.007329,0.0,0.009203,0.014231,pass
10,0.0,0.0,0.0,0.018423,0.0,0.0,0.009452,0.011451,0.0,0.009357,0.005142,pass
11,0.0,0.0,0.0,0.020517,0.0,0.0,0.009215,0.013433,0.0,0.009487,0.010308,pass
12,0.0,0.0,0.0,0.018066,0.0,0.0,0.012202,0.015839,0.0,0.007975,0.010513,pass
13,0.0,0.0,0.0,0.020311,0.0,0.0,0.007828,0.009362,0.0,0.006796,0.006458,pass
14,0.0,0.0,0.0,0.032673,0.0,0.0,0.016450,0.016597,0.0,0.009143,0.014566,pass
15,0.0,0.0,0.0,0.022796,0.0,0.0,0.007669,0.015146,0.0,0.009778,0.010165,pass
16,0.0,0.0,0.0,0.025715,0.0,0.0,0.011995,0.015141,0.0,0.010509,0.014032,pass

[[       nan        nan        nan 1.22875448        nan        nan
  1.1895472  1.22138645        nan 1.1980263  1.20138596]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,h 4,h 0,h 7,h 3,cz 10,cz 9,p 8,cz 6,cz 5,cz 2
sum,0.461187,0.444004,0.437984,0.434867,0.432067,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 1,h 4,h 0,h 7,h 3,cz 10,cz 9,p 8,cz 6,cz 5,cz 2
sum,0.599316,0.576045,0.569531,0.568453,0.563997,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 7,h 3,h 0,h 4,h 1,cz 10,cz 9,p 8,cz 6,cz 5,cz 2
sum,0.004389,0.00131,0.001066,0.000916,0.000858,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_t_inGap_12_.qasm

100%|██████████| 4/4 [00:00<00:00, 15.19it/s]
100%|██████████| 10/10 [00:00<00:00, 17.23it/s]

,cz 10,cz 9,h 8,cz 7,tdg 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.031672,0.0,1.094899e-18,0.0,0.011214,0.017480,0.0,0.010001,0.014047,fail
1,0.0,0.0,0.030228,0.0,1.066402e-18,0.0,0.010893,0.018300,0.0,0.009870,0.014699,fail
2,0.0,0.0,0.024711,0.0,1.038411e-18,0.0,0.012215,0.018291,0.0,0.009481,0.013927,fail
3,0.0,0.0,0.025609,0.0,8.926850e-19,0.0,0.010011,0.011670,0.0,0.007770,0.011456,fail
4,0.0,0.0,0.019430,0.0,8.775312e-19,0.0,0.014173,0.010574,0.0,0.010291,0.008804,pass
5,0.0,0.0,0.024694,0.0,7.289081e-19,0.0,0.009803,0.013410,0.0,0.006789,0.008679,pass
6,0.0,0.0,0.018983,0.0,7.999226e-19,0.0,0.010863,0.010459,0.0,0.008791,0.011988,pass
7,0.0,0.0,0.018253,0.0,7.001507e-19,0.0,0.006170,0.013076,0.0,0.011258,0.007890,pass
8,0.0,0.0,0.025969,0.0,9.470704e-19,0.0,0.007970,0.013252,0.0,0.010412,0.011772,pass
9,0.0,0.0,0.032146,0.0,9.682049e-19,0.0,0.013335,0.016028,0.0,0.013598,0.015663,pass
10,0.0,0.0,0.016023,0.0,9.121062e-19,0.0,0.013927,0.010220,0.0,0.009593,0.014174,pass
11,0.0,0.0,0.018616,0.0,9.505443e-19,0.0,0.009978,0.010426,0.0,0.009782,0.013343,pass
12,0.0,0.0,0.016159,0.0,8.364424e-19,0.0,0.009343,0.011685,0.0,0.008884,0.009369,pass
13,0.0,0.0,0.014959,0.0,7.256728e-19,0.0,0.006104,0.009548,0.0,0.006147,0.010663,pass

[[       nan        nan 1.12892293        nan 1.07017866        nan
  1.10213903 1.11347709        nan 1.07763751 1.08620641]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 3,h 8,tdg 6,h 0,h 4,h 1,cz 10,cz 9,cz 7,cz 5,cz 2
sum,0.356478,0.353502,0.326375,0.325152,0.303657,0.279807,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 3,h 8,tdg 6,h 0,h 4,h 1,cz 10,cz 9,cz 7,cz 5,cz 2
sum,0.455711,0.453272,0.413695,0.413447,0.387325,0.355189,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 3,h 0,h 4,h 1,tdg 6,cz 10,cz 9,cz 7,cz 5,cz 2
sum,0.002995,0.001049,0.000712,0.000479,0.000336,4.186926e-36,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
6
Now evolving the following mutant:  AddGate_x_inGap_6_.qasm

100%|██████████| 6/6 [00:00<00:00, 16.21it/s]
100%|██████████| 10/10 [00:00<00:00, 17.10it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,x 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.024201,0.0,0.0,0.035983,0.010367,0.014230,0.0,0.008587,0.011463,fail
1,0.0,0.0,0.031427,0.0,0.0,0.026806,0.009944,0.011248,0.0,0.011245,0.015748,fail
2,0.0,0.0,0.031351,0.0,0.0,0.040625,0.013918,0.019229,0.0,0.008451,0.010918,fail
3,0.0,0.0,0.028477,0.0,0.0,0.038369,0.011102,0.013515,0.0,0.012120,0.009383,fail
4,0.0,0.0,0.019303,0.0,0.0,0.039382,0.009771,0.014308,0.0,0.009597,0.008915,fail
5,0.0,0.0,0.021327,0.0,0.0,0.040303,0.011177,0.012056,0.0,0.010118,0.016421,fail
6,0.0,0.0,0.023401,0.0,0.0,0.041568,0.011036,0.021612,0.0,0.011925,0.014194,pass
7,0.0,0.0,0.017624,0.0,0.0,0.023868,0.006963,0.008803,0.0,0.007223,0.004905,pass
8,0.0,0.0,0.017245,0.0,0.0,0.033052,0.009365,0.016492,0.0,0.010602,0.014405,pass
9,0.0,0.0,0.022395,0.0,0.0,0.034966,0.011293,0.020547,0.0,0.010229,0.014499,pass
10,0.0,0.0,0.021062,0.0,0.0,0.039917,0.010877,0.013548,0.0,0.008010,0.013541,pass
11,0.0,0.0,0.031961,0.0,0.0,0.039666,0.013171,0.015699,0.0,0.012555,0.012161,pass
12,0.0,0.0,0.023811,0.0,0.0,0.032309,0.010214,0.011305,0.0,0.006394,0.011082,pass
13,0.0,0.0,0.028468,0.0,0.0,0.049222,0.014294,0.010280,0.0,0.011242,0.014159,pass
14,0.0,0.0,0.019841,0.0,0.0,0.035492,0.011313,0.012350,0.0,0.011675,0.011153,pass
15,0.0,0.0,0.026514,0.0,0.0,0.036566,0.011500,0.016863,0.0,0.015043,0.016963,pass

[[       nan        nan 1.20805368        nan        nan 1.10061946
  1.25994181 1.36399081        nan 1.20959339 1.35246541]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 8,x 5,h 4,h 3,h 0,h 1,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.401861,0.376585,0.375938,0.364464,0.364405,0.364316,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 8,h 4,h 3,h 0,x 5,h 1,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.523228,0.494353,0.488745,0.487616,0.480204,0.474484,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,x 5,h 8,h 3,h 0,h 4,h 1,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.007704,0.003909,0.001164,0.000866,0.000719,0.000592,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rz_inGap_1_.qasm

100%|██████████| 5/5 [00:00<00:00, 15.48it/s]
100%|██████████| 10/10 [00:00<00:00, 16.45it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,h 2,h 1,rz 0,pass/fail
0,0.0,0.0,0.021587,0.0,0.0,0.012055,0.015633,0.0,0.010888,0.009860,0.026266,fail
1,0.0,0.0,0.020970,0.0,0.0,0.010639,0.016510,0.0,0.014093,0.015886,0.039389,fail
2,0.0,0.0,0.023650,0.0,0.0,0.012960,0.014241,0.0,0.012809,0.012408,0.030431,fail
3,0.0,0.0,0.026737,0.0,0.0,0.013553,0.021522,0.0,0.014096,0.014675,0.035108,fail
4,0.0,0.0,0.027201,0.0,0.0,0.014071,0.020155,0.0,0.010529,0.012384,0.033051,fail
5,0.0,0.0,0.024746,0.0,0.0,0.010079,0.012532,0.0,0.012458,0.011045,0.030408,pass
6,0.0,0.0,0.019036,0.0,0.0,0.011649,0.013999,0.0,0.006000,0.011374,0.028489,pass
7,0.0,0.0,0.017586,0.0,0.0,0.011538,0.009504,0.0,0.011041,0.012784,0.033929,pass
8,0.0,0.0,0.018305,0.0,0.0,0.008674,0.015566,0.0,0.011619,0.008340,0.023410,pass
9,0.0,0.0,0.025992,0.0,0.0,0.012826,0.012623,0.0,0.009904,0.018009,0.045095,pass
10,0.0,0.0,0.021714,0.0,0.0,0.011714,0.012102,0.0,0.011277,0.014710,0.038518,pass
11,0.0,0.0,0.022223,0.0,0.0,0.009854,0.018474,0.0,0.013763,0.013646,0.034244,pass
12,0.0,0.0,0.017976,0.0,0.0,0.008956,0.008877,0.0,0.007305,0.011036,0.029734,pass
13,0.0,0.0,0.035557,0.0,0.0,0.015017,0.021480,0.0,0.016502,0.019590,0.047495,pass
14,0.0,0.0,0.031314,0.0,0.0,0.009336,0.020151,0.0,0.014425,0.013388,0.031819,pass

[[       nan        nan 1.13201111        nan        nan 1.11185677
  1.22200544        nan 1.12923156 1.21799807 1.1990914 ]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 4,h 5,h 2,h 8,h 1,rz 0,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.377345,0.365934,0.353201,0.338823,0.327478,0.323708,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 4,h 5,h 2,h 8,h 1,rz 0,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.492625,0.467651,0.452913,0.434711,0.427195,0.420747,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,rz 0,h 8,h 4,h 1,h 5,h 2,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.005049,0.002758,0.001507,0.000828,0.000784,0.000762,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_ry_inGap_3_.qasm

100%|██████████| 10/10 [00:00<00:00, 14.85it/s]
100%|██████████| 10/10 [00:00<00:00, 17.08it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,ry 2,h 1,h 0,pass/fail
0,0.0,0.0,0.026408,0.0,0.0,0.011940,0.013566,0.0,0.029168,0.006363,0.013469,fail
1,0.0,0.0,0.019728,0.0,0.0,0.010913,0.011969,0.0,0.034753,0.005779,0.008380,fail
2,0.0,0.0,0.023197,0.0,0.0,0.014590,0.019288,0.0,0.031077,0.006471,0.011049,fail
3,0.0,0.0,0.016049,0.0,0.0,0.008476,0.014291,0.0,0.033086,0.006045,0.009458,fail
4,0.0,0.0,0.032716,0.0,0.0,0.011951,0.020143,0.0,0.036526,0.006955,0.013410,fail
5,0.0,0.0,0.018997,0.0,0.0,0.006481,0.013900,0.0,0.030252,0.004896,0.009687,fail
6,0.0,0.0,0.021585,0.0,0.0,0.011580,0.015351,0.0,0.031027,0.005659,0.008632,fail
7,0.0,0.0,0.020258,0.0,0.0,0.007670,0.008817,0.0,0.031352,0.005320,0.012384,fail
8,0.0,0.0,0.018295,0.0,0.0,0.008457,0.012108,0.0,0.030944,0.005704,0.008427,fail
9,0.0,0.0,0.030436,0.0,0.0,0.012712,0.011208,0.0,0.029745,0.005788,0.010072,fail
10,0.0,0.0,0.021033,0.0,0.0,0.013013,0.016238,0.0,0.023049,0.005281,0.008202,pass
11,0.0,0.0,0.029781,0.0,0.0,0.013912,0.016583,0.0,0.031160,0.006870,0.007705,pass
12,0.0,0.0,0.020859,0.0,0.0,0.010678,0.009438,0.0,0.037010,0.006701,0.010838,pass
13,0.0,0.0,0.019237,0.0,0.0,0.007032,0.009357,0.0,0.023564,0.004905,0.006396,pass
14,0.0,0.0,0.025501,0.0,0.0,0.009487,0.012741,0.0,0.032343,0.006381,0.007769,pass
15,0.0,0.0,0.023855,0.0,0.0,0.008587,0.012367,0.0,0.023528,0.004828,0.010728,pass
16,0.0,0.0,0.019374,0.0,0.0,0.008817,0.017401,0.0,0.032177,0.007065,0.010681,pass
17,0.0,0.0,0.013711,0.0,0.0,0.008085,0.013714,0.0,0.022212,0.004687,0.005359,pass
18,0.0,0.0,0.019374,0.0,0.0,0.007769,0.014349,0.0,0.029549,0.005971,0.013087,pass
19,0.0,0.0,0.019609,0.0,0.0,0.007787,0.015200,0.0,0.031135,0.005773,0.010348,pass

[[       nan        nan 1.43699771        nan        nan 1.39259118
  1.43220286        nan 1.14886375 1.17922673 1.28318452]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 0,ry 2,h 5,h 8,h 4,h 1,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.535331,0.526672,0.524014,0.517424,0.505851,0.502207,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 0,h 5,h 8,h 4,ry 2,h 1,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.707063,0.706448,0.703308,0.686971,0.677941,0.650261,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,ry 2,h 8,h 4,h 0,h 5,h 1,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.009827,0.005076,0.001951,0.001092,0.001087,0.000346,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_h_inGap_1_.qasm

100%|██████████| 10/10 [00:00<00:00, 16.56it/s]
100%|██████████| 10/10 [00:00<00:00, 17.08it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,h 2,h 1,h 0,pass/fail
0,0.0,0.0,0.021138,0.0,0.0,0.008348,0.012054,0.0,0.009317,0.012298,0.008028,fail
1,0.0,0.0,0.028911,0.0,0.0,0.013067,0.013920,0.0,0.012084,0.014416,0.009689,fail
2,0.0,0.0,0.024353,0.0,0.0,0.011416,0.015835,0.0,0.015252,0.015563,0.010272,fail
3,0.0,0.0,0.025017,0.0,0.0,0.013247,0.014823,0.0,0.009431,0.014685,0.010121,fail
4,0.0,0.0,0.026457,0.0,0.0,0.014002,0.016278,0.0,0.012480,0.015364,0.010649,fail
5,0.0,0.0,0.026435,0.0,0.0,0.014329,0.017677,0.0,0.010344,0.012804,0.008735,fail
6,0.0,0.0,0.019561,0.0,0.0,0.008791,0.013797,0.0,0.009365,0.012889,0.008616,fail
7,0.0,0.0,0.020151,0.0,0.0,0.014281,0.017808,0.0,0.009707,0.009504,0.005940,fail
8,0.0,0.0,0.028712,0.0,0.0,0.013894,0.016545,0.0,0.011438,0.020379,0.013795,fail
9,0.0,0.0,0.022004,0.0,0.0,0.012122,0.012410,0.0,0.010369,0.010561,0.006617,fail
10,0.0,0.0,0.028561,0.0,0.0,0.011702,0.013633,0.0,0.009020,0.012695,0.008413,pass
11,0.0,0.0,0.023566,0.0,0.0,0.011606,0.013366,0.0,0.008956,0.011332,0.007560,pass
12,0.0,0.0,0.028581,0.0,0.0,0.007024,0.012850,0.0,0.010063,0.012584,0.008856,pass
13,0.0,0.0,0.013416,0.0,0.0,0.008448,0.012227,0.0,0.007179,0.007109,0.004307,pass
14,0.0,0.0,0.023693,0.0,0.0,0.012819,0.014234,0.0,0.009254,0.012902,0.008682,pass
15,0.0,0.0,0.020562,0.0,0.0,0.011074,0.011661,0.0,0.009171,0.010303,0.007143,pass
16,0.0,0.0,0.030896,0.0,0.0,0.011004,0.012836,0.0,0.012216,0.009380,0.006630,pass
17,0.0,0.0,0.020632,0.0,0.0,0.010885,0.016576,0.0,0.006242,0.013692,0.008977,pass
18,0.0,0.0,0.016067,0.0,0.0,0.004487,0.013873,0.0,0.007379,0.008911,0.005845,pass
19,0.0,0.0,0.029401,0.0,0.0,0.009586,0.016647,0.0,0.010125,0.014015,0.009441,pass

[[       nan        nan 1.19103679        nan        nan 1.1602727
  1.17817382        nan 1.38920286 1.47182199 1.49193862]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 5,h 1,h 2,h 0,h 4,h 8,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.555963,0.5508,0.55061,0.549338,0.522909,0.5077,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 0,h 1,h 2,h 5,h 4,h 8,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.754233,0.75347,0.741837,0.717231,0.676928,0.658872,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 4,h 1,h 5,h 2,h 0,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.005757,0.002253,0.001896,0.00151,0.001195,0.000848,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_h_inGap_8_.qasm

100%|██████████| 10/10 [00:00<00:00, 16.52it/s]
100%|██████████| 10/10 [00:00<00:00, 17.72it/s]

,cz 10,cz 9,h 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.032193,0.0,0.0,0.0,0.006405,0.013950,0.0,0.006349,0.009432,fail
1,0.0,0.0,0.025217,0.0,0.0,0.0,0.004351,0.005793,0.0,0.006247,0.008239,fail
2,0.0,0.0,0.023912,0.0,0.0,0.0,0.007813,0.011753,0.0,0.010022,0.008645,fail
3,0.0,0.0,0.027175,0.0,0.0,0.0,0.007124,0.014111,0.0,0.010732,0.015314,fail
4,0.0,0.0,0.025201,0.0,0.0,0.0,0.006375,0.007864,0.0,0.005616,0.006325,fail
5,0.0,0.0,0.024411,0.0,0.0,0.0,0.008789,0.009400,0.0,0.006262,0.010488,fail
6,0.0,0.0,0.028360,0.0,0.0,0.0,0.009043,0.012200,0.0,0.008619,0.015367,fail
7,0.0,0.0,0.019311,0.0,0.0,0.0,0.007439,0.010706,0.0,0.008056,0.009582,fail
8,0.0,0.0,0.025309,0.0,0.0,0.0,0.008421,0.010587,0.0,0.006741,0.010920,fail
9,0.0,0.0,0.023745,0.0,0.0,0.0,0.008555,0.014100,0.0,0.009860,0.014981,fail
10,0.0,0.0,0.015595,0.0,0.0,0.0,0.005061,0.007151,0.0,0.004523,0.009540,pass
11,0.0,0.0,0.015665,0.0,0.0,0.0,0.006291,0.006358,0.0,0.005567,0.007183,pass
12,0.0,0.0,0.023946,0.0,0.0,0.0,0.006202,0.008425,0.0,0.008268,0.007743,pass
13,0.0,0.0,0.012152,0.0,0.0,0.0,0.008166,0.014901,0.0,0.009228,0.010295,pass
14,0.0,0.0,0.018596,0.0,0.0,0.0,0.008373,0.012759,0.0,0.007955,0.012125,pass
15,0.0,0.0,0.024683,0.0,0.0,0.0,0.005883,0.011723,0.0,0.006993,0.017892,pass
16,0.0,0.0,0.014841,0.0,0.0,0.0,0.004642,0.007732,0.0,0.006008,0.004613,pass
17,0.0,0.0,0.032804,0.0,0.0,0.0,0.008681,0.016929,0.0,0.011556,0.010294,pass
18,0.0,0.0,0.027600,0.0,0.0,0.0,0.007373,0.015182,0.0,0.009815,0.013292,pass
19,0.0,0.0,0.030976,0.0,0.0,0.0,0.007096,0.011725,0.0,0.011186,0.010252,pass

[[       nan        nan 1.26330603        nan        nan        nan
  1.21688344 1.27745093        nan 1.36701453 1.4060784 ]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 8,h 4,h 0,h 3,h 1,cz 10,cz 9,h 7,cz 6,cz 5,cz 2
sum,0.540254,0.523036,0.514266,0.494585,0.491877,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 8,h 0,h 4,h 1,h 3,cz 10,cz 9,h 7,cz 6,cz 5,cz 2
sum,0.71088,0.695041,0.682154,0.659978,0.652537,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 3,h 0,h 1,h 4,cz 10,cz 9,h 7,cz 6,cz 5,cz 2
sum,0.006356,0.001207,0.001182,0.000611,0.000549,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_cswap_inGap_6_.qasm

100%|██████████| 6/6 [00:00<00:00,  6.73it/s]
100%|██████████| 10/10 [00:01<00:00,  6.86it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,cswap 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.028783,0.0,0.0,0.047644,0.012432,0.014354,0.0,0.009738,0.008683,fail
1,0.0,0.0,0.022560,0.0,0.0,0.045467,0.011348,0.013327,0.0,0.006258,0.007298,fail
2,0.0,0.0,0.019549,0.0,0.0,0.056730,0.014756,0.017124,0.0,0.009989,0.011020,fail
3,0.0,0.0,0.034910,0.0,0.0,0.053812,0.015149,0.016870,0.0,0.007524,0.011794,fail
4,0.0,0.0,0.027697,0.0,0.0,0.048935,0.013129,0.013625,0.0,0.007996,0.008088,fail
5,0.0,0.0,0.030291,0.0,0.0,0.045081,0.012600,0.014940,0.0,0.005624,0.011705,fail
6,0.0,0.0,0.032108,0.0,0.0,0.042571,0.013142,0.014581,0.0,0.008975,0.008417,pass
7,0.0,0.0,0.027415,0.0,0.0,0.033785,0.012530,0.014968,0.0,0.008687,0.007505,pass
8,0.0,0.0,0.026882,0.0,0.0,0.047416,0.013980,0.015698,0.0,0.009460,0.008970,pass
9,0.0,0.0,0.022794,0.0,0.0,0.051210,0.013373,0.015690,0.0,0.006836,0.008635,pass
10,0.0,0.0,0.015029,0.0,0.0,0.033301,0.009093,0.010135,0.0,0.004109,0.004549,pass
11,0.0,0.0,0.019858,0.0,0.0,0.038429,0.009928,0.011895,0.0,0.006979,0.009578,pass
12,0.0,0.0,0.019845,0.0,0.0,0.037788,0.010418,0.012206,0.0,0.008165,0.007512,pass
13,0.0,0.0,0.014592,0.0,0.0,0.045702,0.012476,0.014506,0.0,0.006032,0.007357,pass
14,0.0,0.0,0.018318,0.0,0.0,0.031878,0.008956,0.011058,0.0,0.008985,0.008664,pass
15,0.0,0.0,0.027939,0.0,0.0,0.038464,0.012776,0.014380,0.0,0.007306,0.009283,pass

[[       nan        nan 1.2788319         nan        nan 1.14348409
  1.14457301 1.13854621        nan 1.27164884 1.20778138]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,cswap 5,h 8,h 0,h 4,h 3,h 1,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.426329,0.421518,0.42132,0.404993,0.400434,0.384218,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 8,h 0,cswap 5,h 4,h 3,h 1,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.556281,0.548536,0.548204,0.520879,0.514412,0.506366,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,cswap 5,h 8,h 3,h 4,h 0,h 1,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.013844,0.00431,0.001327,0.001031,0.000565,0.000366,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_p_inGap_1_.qasm

100%|██████████| 4/4 [00:00<00:00, 15.94it/s]
100%|██████████| 10/10 [00:00<00:00, 16.39it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,h 2,h 1,p 0,pass/fail
0,0.0,0.0,0.023451,0.0,0.0,0.011957,0.016682,0.0,0.012444,0.013616,0.023762,fail
1,0.0,0.0,0.020793,0.0,0.0,0.009563,0.019168,0.0,0.010799,0.010658,0.022464,fail
2,0.0,0.0,0.020670,0.0,0.0,0.009066,0.017930,0.0,0.011379,0.013464,0.022893,fail
3,0.0,0.0,0.031802,0.0,0.0,0.011377,0.015798,0.0,0.012394,0.016592,0.026473,fail
4,0.0,0.0,0.024819,0.0,0.0,0.011677,0.015401,0.0,0.008750,0.011862,0.019760,pass
5,0.0,0.0,0.018696,0.0,0.0,0.008606,0.008341,0.0,0.008889,0.012486,0.021258,pass
6,0.0,0.0,0.018502,0.0,0.0,0.015543,0.012875,0.0,0.009852,0.012589,0.020024,pass
7,0.0,0.0,0.015660,0.0,0.0,0.007060,0.013194,0.0,0.007248,0.007671,0.013331,pass
8,0.0,0.0,0.013789,0.0,0.0,0.005066,0.005902,0.0,0.007421,0.006023,0.009905,pass
9,0.0,0.0,0.018022,0.0,0.0,0.007114,0.010020,0.0,0.005748,0.012665,0.023697,pass
10,0.0,0.0,0.029985,0.0,0.0,0.013894,0.015997,0.0,0.010919,0.009342,0.015077,pass
11,0.0,0.0,0.022049,0.0,0.0,0.014394,0.017943,0.0,0.009438,0.013671,0.021615,pass
12,0.0,0.0,0.017987,0.0,0.0,0.007848,0.009454,0.0,0.005133,0.009472,0.015883,pass
13,0.0,0.0,0.016251,0.0,0.0,0.006848,0.007631,0.0,0.005478,0.007974,0.014137,pass

[[       nan        nan 1.31526703        nan        nan 1.13979629
  1.10197903        nan 1.05870971 1.22159479 1.10775323]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 2,h 4,p 0,h 1,h 8,h 5,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.373468,0.3734,0.353677,0.343674,0.330682,0.299704,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 4,h 2,p 0,h 1,h 8,h 5,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.476269,0.472316,0.451624,0.448632,0.439415,0.385104,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,p 0,h 4,h 1,h 2,h 5,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.002229,0.002189,0.001176,0.000719,0.000542,0.00043,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_rx_inGap_4_.qasm

100%|██████████| 3/3 [00:00<00:00, 16.95it/s]
100%|██████████| 10/10 [00:00<00:00, 17.59it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,rx 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.030107,0.0,0.0,0.014812,0.017094,0.0,0.0,0.011643,0.017583,fail
1,0.0,0.0,0.035846,0.0,0.0,0.014957,0.024240,0.0,0.0,0.011804,0.018904,fail
2,0.0,0.0,0.023127,0.0,0.0,0.014184,0.013175,0.0,0.0,0.007841,0.013836,fail
3,0.0,0.0,0.029166,0.0,0.0,0.014138,0.015124,0.0,0.0,0.011555,0.010351,pass
4,0.0,0.0,0.025121,0.0,0.0,0.009691,0.015653,0.0,0.0,0.010315,0.008548,pass
5,0.0,0.0,0.017726,0.0,0.0,0.012060,0.012575,0.0,0.0,0.009097,0.008968,pass
6,0.0,0.0,0.015938,0.0,0.0,0.008875,0.017074,0.0,0.0,0.008936,0.011918,pass
7,0.0,0.0,0.030369,0.0,0.0,0.014598,0.017692,0.0,0.0,0.011962,0.017139,pass
8,0.0,0.0,0.020821,0.0,0.0,0.010937,0.017843,0.0,0.0,0.014530,0.007648,pass
9,0.0,0.0,0.018453,0.0,0.0,0.006311,0.008056,0.0,0.0,0.007480,0.011035,pass
10,0.0,0.0,0.026075,0.0,0.0,0.012646,0.018807,0.0,0.0,0.012186,0.015638,pass
11,0.0,0.0,0.027108,0.0,0.0,0.012164,0.014571,0.0,0.0,0.013820,0.014739,pass
12,0.0,0.0,0.019467,0.0,0.0,0.013547,0.011138,0.0,0.0,0.011295,0.012158,pass

[[       nan        nan 1.20720819        nan        nan 1.02091488
  1.33407647        nan        nan 1.131819   1.1269869 ]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 0,h 8,h 5,h 4,h 1,cz 10,cz 9,cz 7,cz 6,rx 3,cz 2
sum,0.298714,0.278963,0.276573,0.268461,0.219612,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 0,h 8,h 4,h 5,h 1,cz 10,cz 9,cz 7,cz 6,rx 3,cz 2
sum,0.382876,0.363155,0.357998,0.347162,0.281753,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 4,h 0,h 5,h 1,cz 10,cz 9,cz 7,cz 6,rx 3,cz 2
sum,0.002457,0.000944,0.000812,0.00062,0.000315,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
3
Now evolving the following mutant:  AddGate_t_inGap_3_.qasm

100%|██████████| 4/4 [00:00<00:00, 15.50it/s]
100%|██████████| 10/10 [00:00<00:00, 16.88it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,tdg 2,h 1,h 0,pass/fail
0,0.0,0.0,0.030019,0.0,0.0,0.013204,0.019047,0.0,3.280372e-19,0.011847,0.013065,fail
1,0.0,0.0,0.029066,0.0,0.0,0.012027,0.019211,0.0,3.526629e-19,0.012434,0.016333,fail
2,0.0,0.0,0.026118,0.0,0.0,0.013287,0.014488,0.0,3.530723e-19,0.012293,0.015500,fail
3,0.0,0.0,0.020260,0.0,0.0,0.012875,0.016883,0.0,3.361731e-19,0.013155,0.010300,fail
4,0.0,0.0,0.032965,0.0,0.0,0.016915,0.014540,0.0,3.393605e-19,0.012481,0.016927,pass
5,0.0,0.0,0.025594,0.0,0.0,0.014113,0.011626,0.0,2.861985e-19,0.010872,0.008662,pass
6,0.0,0.0,0.021854,0.0,0.0,0.011032,0.012401,0.0,2.758487e-19,0.006747,0.014376,pass
7,0.0,0.0,0.021064,0.0,0.0,0.011702,0.012967,0.0,2.622697e-19,0.009300,0.008684,pass
8,0.0,0.0,0.023756,0.0,0.0,0.008097,0.015875,0.0,3.092014e-19,0.013788,0.014687,pass
9,0.0,0.0,0.016328,0.0,0.0,0.010280,0.013068,0.0,2.824245e-19,0.009445,0.016188,pass
10,0.0,0.0,0.016746,0.0,0.0,0.007148,0.008514,0.0,1.842482e-19,0.006248,0.008303,pass
11,0.0,0.0,0.028155,0.0,0.0,0.011142,0.015988,0.0,3.186749e-19,0.010333,0.017418,pass
12,0.0,0.0,0.020167,0.0,0.0,0.008924,0.011136,0.0,2.555640e-19,0.008410,0.011192,pass
13,0.0,0.0,0.015248,0.0,0.0,0.012448,0.012602,0.0,3.433539e-19,0.012933,0.010951,pass

[[       nan        nan 1.13854801        nan        nan 1.03417866
  1.10363091        nan 1.03090897 1.05813295 1.18357221]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 4,h 1,tdg 2,h 8,h 5,h 0,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.351052,0.330893,0.324087,0.32218,0.314919,0.302312,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 4,h 1,h 8,tdg 2,h 5,h 0,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.447909,0.418426,0.413885,0.407613,0.396339,0.391764,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 4,h 0,h 5,h 1,tdg 2,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.002634,0.001174,0.000738,0.000642,0.000603,4.691876e-37,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_rzz_inGap_14_.qasm

100%|██████████| 3/3 [00:00<00:00, 14.96it/s]
100%|██████████| 10/10 [00:00<00:00, 17.01it/s]

,rzz 10,cz 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.0,0.021682,0.0,0.0,0.012607,0.018320,0.0,0.013931,0.010485,fail
1,0.0,0.0,0.0,0.021599,0.0,0.0,0.012974,0.016717,0.0,0.007849,0.016132,fail
2,0.0,0.0,0.0,0.025006,0.0,0.0,0.015458,0.020409,0.0,0.013307,0.012109,fail
3,0.0,0.0,0.0,0.020653,0.0,0.0,0.012051,0.017531,0.0,0.009810,0.012665,pass
4,0.0,0.0,0.0,0.023606,0.0,0.0,0.011005,0.010868,0.0,0.007993,0.012662,pass
5,0.0,0.0,0.0,0.023326,0.0,0.0,0.010338,0.015925,0.0,0.007539,0.012439,pass
6,0.0,0.0,0.0,0.023608,0.0,0.0,0.010015,0.011199,0.0,0.008806,0.011062,pass
7,0.0,0.0,0.0,0.031666,0.0,0.0,0.010416,0.018560,0.0,0.010738,0.011956,pass
8,0.0,0.0,0.0,0.030004,0.0,0.0,0.015130,0.017558,0.0,0.010111,0.014652,pass
9,0.0,0.0,0.0,0.025351,0.0,0.0,0.013976,0.015445,0.0,0.009703,0.011561,pass
10,0.0,0.0,0.0,0.030856,0.0,0.0,0.011112,0.016578,0.0,0.007830,0.010584,pass
11,0.0,0.0,0.0,0.018498,0.0,0.0,0.010410,0.010413,0.0,0.007639,0.008564,pass
12,0.0,0.0,0.0,0.014707,0.0,0.0,0.006441,0.014294,0.0,0.012000,0.013458,pass

[[       nan        nan        nan 1.09856458        nan        nan
  1.13001224 1.10428775        nan 1.19115151 1.24970561]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,h 3,h 4,h 0,h 7,rzz 10,cz 9,cz 8,cz 6,cz 5,cz 2
sum,0.275716,0.272039,0.270114,0.244595,0.219882,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 1,h 3,h 4,h 0,h 7,rzz 10,cz 9,cz 8,cz 6,cz 5,cz 2
sum,0.357821,0.347141,0.346421,0.321013,0.28027,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 7,h 3,h 4,h 0,h 1,rzz 10,cz 9,cz 8,cz 6,cz 5,cz 2
sum,0.001438,0.000976,0.000541,0.000481,0.000398,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_rxx_inGap_3_.qasm

100%|██████████| 6/6 [00:00<00:00, 15.60it/s]
100%|██████████| 10/10 [00:00<00:00, 16.21it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,rxx 2,h 1,h 0,pass/fail
0,0.0,0.0,0.027444,0.0,0.0,0.011622,0.016134,0.0,0.023067,0.018829,0.022611,fail
1,0.0,0.0,0.014924,0.0,0.0,0.010080,0.014088,0.0,0.020658,0.012388,0.018194,fail
2,0.0,0.0,0.017961,0.0,0.0,0.010143,0.008314,0.0,0.017283,0.011901,0.020735,fail
3,0.0,0.0,0.028480,0.0,0.0,0.010596,0.015380,0.0,0.022599,0.020023,0.020884,fail
4,0.0,0.0,0.029816,0.0,0.0,0.012193,0.015594,0.0,0.025893,0.016830,0.024752,fail
5,0.0,0.0,0.028025,0.0,0.0,0.013364,0.014446,0.0,0.020606,0.022288,0.018889,fail
6,0.0,0.0,0.027429,0.0,0.0,0.011970,0.009701,0.0,0.027734,0.019130,0.020080,pass
7,0.0,0.0,0.027986,0.0,0.0,0.012801,0.015596,0.0,0.031074,0.022124,0.025097,pass
8,0.0,0.0,0.019923,0.0,0.0,0.010798,0.010646,0.0,0.026195,0.019144,0.019537,pass
9,0.0,0.0,0.024975,0.0,0.0,0.013574,0.019114,0.0,0.024788,0.022536,0.021114,pass
10,0.0,0.0,0.033917,0.0,0.0,0.017754,0.020538,0.0,0.030515,0.025054,0.027679,pass
11,0.0,0.0,0.027579,0.0,0.0,0.007656,0.018208,0.0,0.027526,0.019885,0.027848,pass
12,0.0,0.0,0.020003,0.0,0.0,0.010143,0.012000,0.0,0.025476,0.016824,0.020685,pass
13,0.0,0.0,0.023447,0.0,0.0,0.008901,0.017249,0.0,0.025281,0.018183,0.023779,pass
14,0.0,0.0,0.025159,0.0,0.0,0.011115,0.010596,0.0,0.016992,0.017181,0.018615,pass
15,0.0,0.0,0.018612,0.0,0.0,0.010253,0.011808,0.0,0.017022,0.012751,0.016691,pass

[[       nan        nan 1.21987414        nan        nan 1.17918576
  1.15301511        nan 1.19408598 1.30770691 1.17805394]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 5,h 8,h 4,h 0,h 1,rxx 2,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.371649,0.370627,0.365961,0.363102,0.346558,0.33996,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 8,h 5,h 4,h 0,h 1,rxx 2,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.483657,0.481209,0.471451,0.470041,0.459857,0.441446,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,rxx 2,h 0,h 1,h 4,h 5,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.003442,0.002707,0.002555,0.001689,0.001147,0.000756,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_h_inGap_5_.qasm

100%|██████████| 10/10 [00:00<00:00, 16.59it/s]
100%|██████████| 10/10 [00:00<00:00, 17.53it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.023848,0.0,0.0,0.012660,0.003602,0.014219,0.0,0.013130,0.011889,fail
1,0.0,0.0,0.028378,0.0,0.0,0.011760,0.003003,0.014781,0.0,0.011683,0.013058,fail
2,0.0,0.0,0.018678,0.0,0.0,0.009650,0.002948,0.005701,0.0,0.006173,0.010353,fail
3,0.0,0.0,0.022902,0.0,0.0,0.011103,0.003862,0.011712,0.0,0.008889,0.010196,fail
4,0.0,0.0,0.030632,0.0,0.0,0.015686,0.004682,0.016608,0.0,0.008752,0.015820,fail
5,0.0,0.0,0.023157,0.0,0.0,0.011749,0.003491,0.013393,0.0,0.010252,0.005385,fail
6,0.0,0.0,0.028053,0.0,0.0,0.015532,0.006142,0.011520,0.0,0.008030,0.010868,fail
7,0.0,0.0,0.019878,0.0,0.0,0.010318,0.002780,0.007520,0.0,0.006122,0.004430,fail
8,0.0,0.0,0.017572,0.0,0.0,0.012963,0.004619,0.008684,0.0,0.005816,0.006701,fail
9,0.0,0.0,0.026375,0.0,0.0,0.013699,0.004715,0.012633,0.0,0.007122,0.009466,fail
10,0.0,0.0,0.018742,0.0,0.0,0.009845,0.002637,0.012293,0.0,0.007192,0.010226,pass
11,0.0,0.0,0.014853,0.0,0.0,0.006417,0.001842,0.007035,0.0,0.007292,0.009123,pass
12,0.0,0.0,0.011630,0.0,0.0,0.007135,0.001838,0.004970,0.0,0.004501,0.008473,pass
13,0.0,0.0,0.026974,0.0,0.0,0.011733,0.005006,0.009466,0.0,0.012682,0.010139,pass
14,0.0,0.0,0.015147,0.0,0.0,0.007292,0.002223,0.006904,0.0,0.006739,0.011434,pass
15,0.0,0.0,0.036454,0.0,0.0,0.014410,0.006579,0.013766,0.0,0.011599,0.013724,pass
16,0.0,0.0,0.013492,0.0,0.0,0.009418,0.002801,0.008985,0.0,0.008056,0.009936,pass
17,0.0,0.0,0.025134,0.0,0.0,0.009128,0.003041,0.013342,0.0,0.008986,0.007951,pass
18,0.0,0.0,0.026302,0.0,0.0,0.011830,0.004109,0.014601,0.0,0.009521,0.012615,pass
19,0.0,0.0,0.029222,0.0,0.0,0.012516,0.004706,0.010502,0.0,0.007347,0.013019,pass

[[       nan        nan 1.2791398         nan        nan 1.25366729
  1.54143147 1.42227337        nan 1.52731012 1.61153461]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 5,h 3,h 4,h 8,h 1,h 0,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.556477,0.534091,0.53392,0.523528,0.506049,0.479312,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 4,h 5,h 3,h 1,h 8,h 0,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.739671,0.730886,0.723997,0.699272,0.690945,0.672419,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 5,h 3,h 0,h 1,h 4,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.005612,0.00155,0.00135,0.000953,0.000733,0.000158,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_y_inGap_3_.qasm

100%|██████████| 5/5 [00:00<00:00, 16.65it/s]
100%|██████████| 10/10 [00:00<00:00, 16.67it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,y 2,h 1,h 0,pass/fail
0,0.0,0.0,0.026786,0.0,0.0,0.013844,0.014865,0.0,0.031128,0.015249,0.016685,fail
1,0.0,0.0,0.026232,0.0,0.0,0.012885,0.013730,0.0,0.018914,0.009348,0.014847,fail
2,0.0,0.0,0.020163,0.0,0.0,0.011078,0.012022,0.0,0.022679,0.011694,0.011979,fail
3,0.0,0.0,0.016230,0.0,0.0,0.006616,0.013676,0.0,0.027478,0.012641,0.012213,fail
4,0.0,0.0,0.021494,0.0,0.0,0.010072,0.018341,0.0,0.011781,0.006466,0.009285,fail
5,0.0,0.0,0.014476,0.0,0.0,0.007893,0.011058,0.0,0.011029,0.005279,0.008490,pass
6,0.0,0.0,0.022636,0.0,0.0,0.009917,0.009774,0.0,0.024602,0.011598,0.008762,pass
7,0.0,0.0,0.021921,0.0,0.0,0.008943,0.011820,0.0,0.021465,0.010482,0.011593,pass
8,0.0,0.0,0.023335,0.0,0.0,0.011197,0.014255,0.0,0.015575,0.008283,0.015075,pass
9,0.0,0.0,0.017223,0.0,0.0,0.005673,0.005773,0.0,0.017309,0.007872,0.006650,pass
10,0.0,0.0,0.024533,0.0,0.0,0.010190,0.013508,0.0,0.013622,0.007560,0.015609,pass
11,0.0,0.0,0.010802,0.0,0.0,0.005384,0.009418,0.0,0.009440,0.005623,0.008886,pass
12,0.0,0.0,0.023693,0.0,0.0,0.010491,0.013164,0.0,0.023113,0.010548,0.015977,pass
13,0.0,0.0,0.021542,0.0,0.0,0.012046,0.011438,0.0,0.018445,0.008561,0.006384,pass
14,0.0,0.0,0.017633,0.0,0.0,0.004483,0.011526,0.0,0.016419,0.007414,0.007541,pass

[[       nan        nan 1.207608          nan        nan 1.27021492
  1.26255959        nan 1.38987524 1.37626653 1.28328483]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,y 2,h 4,h 5,h 0,h 8,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.399644,0.395693,0.393958,0.387278,0.382461,0.359265,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 1,y 2,h 4,h 5,h 0,h 8,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.537148,0.533184,0.518307,0.510259,0.505163,0.467727,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,y 2,h 8,h 4,h 0,h 1,h 5,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.002425,0.002366,0.001032,0.000828,0.000604,0.000584,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_p_inGap_8_.qasm

100%|██████████| 4/4 [00:00<00:00, 16.27it/s]
100%|██████████| 10/10 [00:00<00:00, 17.78it/s]

,cz 10,cz 9,h 8,p 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.011182,0.067092,0.0,0.0,0.006308,0.010711,0.0,0.006359,0.008528,fail
1,0.0,0.0,0.027415,0.164489,0.0,0.0,0.011822,0.019540,0.0,0.012558,0.015746,fail
2,0.0,0.0,0.034241,0.205447,0.0,0.0,0.009855,0.018369,0.0,0.014226,0.015139,fail
3,0.0,0.0,0.016929,0.101572,0.0,0.0,0.007435,0.010438,0.0,0.009247,0.011418,fail
4,0.0,0.0,0.022413,0.134478,0.0,0.0,0.011000,0.012818,0.0,0.008574,0.014643,pass
5,0.0,0.0,0.015508,0.093046,0.0,0.0,0.010231,0.016531,0.0,0.008034,0.008906,pass
6,0.0,0.0,0.023245,0.139468,0.0,0.0,0.012000,0.016009,0.0,0.009771,0.010164,pass
7,0.0,0.0,0.023956,0.143734,0.0,0.0,0.010186,0.010077,0.0,0.008810,0.009834,pass
8,0.0,0.0,0.028234,0.169402,0.0,0.0,0.010244,0.011411,0.0,0.008198,0.008790,pass
9,0.0,0.0,0.028367,0.170202,0.0,0.0,0.009814,0.012732,0.0,0.009485,0.010909,pass
10,0.0,0.0,0.017009,0.102054,0.0,0.0,0.007212,0.006941,0.0,0.006142,0.004724,pass
11,0.0,0.0,0.022988,0.137930,0.0,0.0,0.010714,0.015387,0.0,0.012756,0.011253,pass
12,0.0,0.0,0.020207,0.121243,0.0,0.0,0.007431,0.007972,0.0,0.007306,0.009530,pass
13,0.0,0.0,0.021148,0.126888,0.0,0.0,0.013396,0.012925,0.0,0.012752,0.012427,pass

[[       nan        nan 1.52578445 1.52578445        nan        nan
  1.33506268 1.32342791        nan 1.34236423 1.2391056 ]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 0,h 3,h 1,h 8,p 7,h 4,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.33439,0.324744,0.315828,0.28694,0.28694,0.257323,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 0,h 3,h 1,p 7,h 8,h 4,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.437977,0.432188,0.421817,0.396392,0.396392,0.343208,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,p 7,h 8,h 3,h 0,h 1,h 4,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.05434,0.001908,0.000846,0.00063,0.000439,0.000306,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
7
Now evolving the following mutant:  AddGate_rx_inGap_11_.qasm

100%|██████████| 2/2 [00:00<00:00, 16.81it/s]
100%|██████████| 10/10 [00:00<00:00, 16.95it/s]

,cz 10,rx 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.224083,0.0,0.026500,0.0,0.0,0.011113,0.015839,0.0,0.007440,0.012926,fail
1,0.0,0.242751,0.0,0.023427,0.0,0.0,0.005835,0.012254,0.0,0.009757,0.013884,fail
2,0.0,0.174655,0.0,0.027538,0.0,0.0,0.011904,0.014730,0.0,0.009710,0.011476,pass
3,0.0,0.288105,0.0,0.024637,0.0,0.0,0.011345,0.012824,0.0,0.009551,0.017138,pass
4,0.0,0.175623,0.0,0.013278,0.0,0.0,0.006412,0.008224,0.0,0.005339,0.008857,pass
5,0.0,0.256436,0.0,0.022644,0.0,0.0,0.010169,0.013530,0.0,0.011327,0.015341,pass
6,0.0,0.233972,0.0,0.020631,0.0,0.0,0.009904,0.019059,0.0,0.010841,0.014490,pass
7,0.0,0.206960,0.0,0.030433,0.0,0.0,0.013583,0.021879,0.0,0.010759,0.013930,pass
8,0.0,0.145929,0.0,0.035975,0.0,0.0,0.014902,0.016970,0.0,0.012456,0.009874,pass
9,0.0,0.166896,0.0,0.017820,0.0,0.0,0.009519,0.008272,0.0,0.005062,0.008783,pass
10,0.0,0.265507,0.0,0.020829,0.0,0.0,0.010168,0.013518,0.0,0.008503,0.013796,pass
11,0.0,0.233943,0.0,0.020915,0.0,0.0,0.009139,0.012126,0.0,0.006698,0.012934,pass

[[       nan 1.03998791        nan 1.06154335        nan        nan
  1.31144132 1.12761207        nan 1.13474356 1.03572248]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,rx 9,h 7,h 0,h 3,h 1,h 4,cz 10,cz 8,cz 6,cz 5,cz 2
sum,0.178531,0.175413,0.174737,0.166005,0.160056,0.136687,0.0,0.0,0.0,0.0,0.0

custom SCORES

,rx 9,h 7,h 0,h 3,h 1,h 4,cz 10,cz 8,cz 6,cz 5,cz 2
sum,0.224949,0.221965,0.219982,0.212802,0.205462,0.181502,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,rx 9,h 7,h 3,h 0,h 1,h 4,cz 10,cz 8,cz 6,cz 5,cz 2
sum,0.052539,0.001115,0.000369,0.000338,0.000141,0.000136,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
9
Now evolving the following mutant:  AddGate_rzz_inGap_2_.qasm

100%|██████████| 6/6 [00:00<00:00, 15.56it/s]
100%|██████████| 10/10 [00:00<00:00, 17.68it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,h 2,rzz 1,h 0,pass/fail
0,0.0,0.0,0.023235,0.0,0.0,0.010044,0.017013,0.0,0.009308,0.023957,0.011605,fail
1,0.0,0.0,0.017229,0.0,0.0,0.009263,0.015812,0.0,0.010718,0.015778,0.011726,fail
2,0.0,0.0,0.022335,0.0,0.0,0.012661,0.017221,0.0,0.008613,0.024834,0.014175,fail
3,0.0,0.0,0.024118,0.0,0.0,0.012711,0.016420,0.0,0.011250,0.016856,0.015042,fail
4,0.0,0.0,0.019744,0.0,0.0,0.008981,0.011532,0.0,0.009486,0.016352,0.008573,fail
5,0.0,0.0,0.024390,0.0,0.0,0.006151,0.010949,0.0,0.009231,0.018948,0.011702,fail
6,0.0,0.0,0.016134,0.0,0.0,0.008704,0.013113,0.0,0.008236,0.014931,0.008664,pass
7,0.0,0.0,0.024371,0.0,0.0,0.008220,0.013410,0.0,0.009097,0.018449,0.013429,pass
8,0.0,0.0,0.013987,0.0,0.0,0.009324,0.016934,0.0,0.010729,0.017082,0.010028,pass
9,0.0,0.0,0.028895,0.0,0.0,0.013873,0.018726,0.0,0.008761,0.017658,0.012674,pass
10,0.0,0.0,0.028115,0.0,0.0,0.011756,0.011722,0.0,0.010590,0.008132,0.011508,pass
11,0.0,0.0,0.012798,0.0,0.0,0.011807,0.008246,0.0,0.010044,0.016059,0.008139,pass
12,0.0,0.0,0.027884,0.0,0.0,0.011216,0.013836,0.0,0.013818,0.013872,0.011401,pass
13,0.0,0.0,0.020844,0.0,0.0,0.010541,0.016525,0.0,0.008578,0.016093,0.008242,pass
14,0.0,0.0,0.014476,0.0,0.0,0.008024,0.012635,0.0,0.009137,0.011288,0.007845,pass
15,0.0,0.0,0.022079,0.0,0.0,0.012014,0.017655,0.0,0.016211,0.012370,0.013840,pass

[[       nan        nan 1.11668091        nan        nan 1.27514815
  1.16164856        nan 1.15177152 1.27653665 1.23935187]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,rzz 1,h 0,h 8,h 4,h 5,h 2,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.444401,0.407759,0.384725,0.383806,0.361851,0.357773,0.0,0.0,0.0,0.0,0.0

custom SCORES

,rzz 1,h 0,h 4,h 8,h 5,h 2,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.586225,0.534098,0.495268,0.492129,0.477205,0.460791,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,rzz 1,h 4,h 0,h 5,h 2,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.002766,0.002217,0.001288,0.000869,0.000586,0.000563,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_rz_inGap_5_.qasm

100%|██████████| 5/5 [00:00<00:00, 16.76it/s]
100%|██████████| 10/10 [00:00<00:00, 16.34it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,rz 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.020223,0.0,0.0,0.011178,0.010405,0.014250,0.0,0.012681,0.014611,fail
1,0.0,0.0,0.028659,0.0,0.0,0.016855,0.015021,0.017325,0.0,0.010522,0.012679,fail
2,0.0,0.0,0.023901,0.0,0.0,0.012920,0.011767,0.015575,0.0,0.011188,0.014450,fail
3,0.0,0.0,0.022690,0.0,0.0,0.010881,0.009937,0.017655,0.0,0.014384,0.015719,fail
4,0.0,0.0,0.024840,0.0,0.0,0.010207,0.009336,0.015574,0.0,0.012339,0.008368,fail
5,0.0,0.0,0.021772,0.0,0.0,0.010033,0.009168,0.010720,0.0,0.009333,0.009198,pass
6,0.0,0.0,0.015273,0.0,0.0,0.009827,0.009075,0.010596,0.0,0.008796,0.008194,pass
7,0.0,0.0,0.018256,0.0,0.0,0.011901,0.010957,0.012021,0.0,0.006161,0.011243,pass
8,0.0,0.0,0.024800,0.0,0.0,0.013787,0.012497,0.015257,0.0,0.011403,0.012498,pass
9,0.0,0.0,0.019134,0.0,0.0,0.013218,0.012006,0.014311,0.0,0.008172,0.007602,pass
10,0.0,0.0,0.026868,0.0,0.0,0.016746,0.015075,0.015014,0.0,0.010273,0.011347,pass
11,0.0,0.0,0.031071,0.0,0.0,0.012539,0.011156,0.010791,0.0,0.008956,0.012375,pass
12,0.0,0.0,0.025571,0.0,0.0,0.011849,0.010820,0.009278,0.0,0.010119,0.012226,pass
13,0.0,0.0,0.029888,0.0,0.0,0.010991,0.009715,0.015397,0.0,0.009856,0.012850,pass
14,0.0,0.0,0.024865,0.0,0.0,0.010255,0.009414,0.016893,0.0,0.011436,0.012713,pass

[[       nan        nan 1.19100409        nan        nan 1.35835571
  1.33010713 1.09824679        nan 1.17683213 1.1939901 ]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,h 3,h 0,rz 4,h 5,h 8,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.392715,0.381557,0.37386,0.339445,0.338676,0.336246,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 1,h 3,h 0,h 5,rz 4,h 8,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.508255,0.486318,0.485456,0.453687,0.45232,0.436363,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 3,h 0,h 5,h 1,rz 4,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.002764,0.001259,0.000848,0.000752,0.000733,0.000624,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_rz_inGap_2_.qasm

100%|██████████| 5/5 [00:00<00:00, 14.64it/s]
100%|██████████| 10/10 [00:00<00:00, 17.54it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,h 2,rz 1,h 0,pass/fail
0,0.0,0.0,0.026645,0.0,0.0,0.016694,0.019053,0.0,0.012476,0.021869,0.012546,fail
1,0.0,0.0,0.030631,0.0,0.0,0.016268,0.024228,0.0,0.015045,0.027502,0.018218,fail
2,0.0,0.0,0.026675,0.0,0.0,0.012692,0.016881,0.0,0.009237,0.016444,0.005323,fail
3,0.0,0.0,0.027010,0.0,0.0,0.010448,0.016111,0.0,0.012662,0.023659,0.014600,fail
4,0.0,0.0,0.024509,0.0,0.0,0.014482,0.017463,0.0,0.010018,0.019343,0.012818,fail
5,0.0,0.0,0.022215,0.0,0.0,0.006004,0.012395,0.0,0.009168,0.017296,0.012195,pass
6,0.0,0.0,0.025761,0.0,0.0,0.012663,0.011297,0.0,0.007322,0.016392,0.011504,pass
7,0.0,0.0,0.018720,0.0,0.0,0.009930,0.015065,0.0,0.009907,0.020420,0.011568,pass
8,0.0,0.0,0.021368,0.0,0.0,0.007087,0.009335,0.0,0.010389,0.020705,0.009622,pass
9,0.0,0.0,0.019585,0.0,0.0,0.014327,0.014615,0.0,0.009220,0.017462,0.014110,pass
10,0.0,0.0,0.021322,0.0,0.0,0.010930,0.013708,0.0,0.007097,0.015475,0.012343,pass
11,0.0,0.0,0.027917,0.0,0.0,0.012702,0.016253,0.0,0.011922,0.023877,0.013138,pass
12,0.0,0.0,0.025378,0.0,0.0,0.012059,0.014011,0.0,0.007440,0.015564,0.008409,pass
13,0.0,0.0,0.029444,0.0,0.0,0.011549,0.014971,0.0,0.011948,0.025735,0.014390,pass
14,0.0,0.0,0.019475,0.0,0.0,0.010069,0.014168,0.0,0.011293,0.021858,0.010955,pass

[[       nan        nan 1.13054472        nan        nan 1.18257675
  1.29236611        nan 1.26561363 1.26368412 1.43435981]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 4,h 5,h 2,h 8,rz 1,h 0,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.408341,0.396755,0.383111,0.369474,0.358424,0.349429,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 4,h 5,h 2,h 0,h 8,rz 1,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.540272,0.514054,0.504329,0.47473,0.473901,0.471657,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,rz 1,h 4,h 5,h 0,h 2,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.003508,0.002279,0.001711,0.000975,0.000788,0.000693,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_rxx_inGap_7_.qasm

100%|██████████| 7/7 [00:00<00:00, 11.98it/s]
100%|██████████| 10/10 [00:00<00:00, 16.91it/s]

,cz 10,cz 9,h 8,cz 7,rxx 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.022107,0.0,0.051214,0.0,0.009650,0.013738,0.0,0.013080,0.013012,fail
1,0.0,0.0,0.026150,0.0,0.078675,0.0,0.012073,0.022669,0.0,0.012457,0.013791,fail
2,0.0,0.0,0.023468,0.0,0.061703,0.0,0.008461,0.013104,0.0,0.011328,0.013679,fail
3,0.0,0.0,0.017315,0.0,0.050667,0.0,0.012011,0.018105,0.0,0.009256,0.013806,fail
4,0.0,0.0,0.020326,0.0,0.089558,0.0,0.015828,0.015385,0.0,0.009519,0.020672,fail
5,0.0,0.0,0.029021,0.0,0.065931,0.0,0.012356,0.016880,0.0,0.007843,0.010680,fail
6,0.0,0.0,0.026280,0.0,0.070873,0.0,0.008842,0.021450,0.0,0.012686,0.012718,fail
7,0.0,0.0,0.024650,0.0,0.062040,0.0,0.010929,0.014504,0.0,0.012446,0.018856,pass
8,0.0,0.0,0.025064,0.0,0.066119,0.0,0.005581,0.015759,0.0,0.009704,0.009352,pass
9,0.0,0.0,0.023477,0.0,0.056201,0.0,0.008651,0.015235,0.0,0.007841,0.011592,pass
10,0.0,0.0,0.023034,0.0,0.068166,0.0,0.012742,0.010842,0.0,0.008503,0.012252,pass
11,0.0,0.0,0.029410,0.0,0.078878,0.0,0.013861,0.011463,0.0,0.012408,0.012610,pass
12,0.0,0.0,0.020376,0.0,0.046383,0.0,0.008610,0.011837,0.0,0.004999,0.011363,pass
13,0.0,0.0,0.028970,0.0,0.058017,0.0,0.008407,0.010720,0.0,0.010293,0.008223,pass
14,0.0,0.0,0.023183,0.0,0.069515,0.0,0.010251,0.011839,0.0,0.010340,0.011159,pass
15,0.0,0.0,0.021355,0.0,0.041527,0.0,0.011599,0.012097,0.0,0.012021,0.012321,pass
16,0.0,0.0,0.015608,0.0,0.040835,0.0,0.007235,0.007535,0.0,0.006863,0.007833,pass

[[       nan        nan 1.23366708        nan 1.33776721        nan
  1.39853516 1.30785668        nan 1.20202823 1.47120772]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 3,h 0,h 4,h 1,rxx 6,h 8,cz 10,cz 9,cz 7,cz 5,cz 2
sum,0.49897,0.459786,0.447356,0.443911,0.443643,0.411879,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 3,h 0,h 4,rxx 6,h 1,h 8,cz 10,cz 9,cz 7,cz 5,cz 2
sum,0.662115,0.628896,0.603767,0.592016,0.577309,0.538909,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,rxx 6,h 8,h 3,h 0,h 4,h 1,cz 10,cz 9,cz 7,cz 5,cz 2
sum,0.028943,0.003748,0.002067,0.00136,0.000884,0.000818,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
6
Now evolving the following mutant:  AddGate_rx_inGap_5_.qasm

100%|██████████| 4/4 [00:00<00:00, 15.29it/s]
100%|██████████| 10/10 [00:00<00:00, 16.08it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,rx 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.024744,0.0,0.0,0.008928,0.0,0.012343,0.0,0.010698,0.013694,fail
1,0.0,0.0,0.021766,0.0,0.0,0.014279,0.0,0.013631,0.0,0.011757,0.011197,fail
2,0.0,0.0,0.025498,0.0,0.0,0.011829,0.0,0.013282,0.0,0.010991,0.015590,fail
3,0.0,0.0,0.029478,0.0,0.0,0.011181,0.0,0.011237,0.0,0.009811,0.012229,fail
4,0.0,0.0,0.022154,0.0,0.0,0.009929,0.0,0.012357,0.0,0.011872,0.011589,pass
5,0.0,0.0,0.023979,0.0,0.0,0.010360,0.0,0.012439,0.0,0.006070,0.011587,pass
6,0.0,0.0,0.014762,0.0,0.0,0.012908,0.0,0.015821,0.0,0.009033,0.009440,pass
7,0.0,0.0,0.014121,0.0,0.0,0.007935,0.0,0.007711,0.0,0.004719,0.009950,pass
8,0.0,0.0,0.022280,0.0,0.0,0.009745,0.0,0.015256,0.0,0.011205,0.016582,pass
9,0.0,0.0,0.034957,0.0,0.0,0.013384,0.0,0.012616,0.0,0.012906,0.014929,pass
10,0.0,0.0,0.027490,0.0,0.0,0.010293,0.0,0.014329,0.0,0.011020,0.011029,pass
11,0.0,0.0,0.019612,0.0,0.0,0.006708,0.0,0.011450,0.0,0.007694,0.010132,pass
12,0.0,0.0,0.025194,0.0,0.0,0.007761,0.0,0.011257,0.0,0.006303,0.008109,pass
13,0.0,0.0,0.017211,0.0,0.0,0.006775,0.0,0.008278,0.0,0.007697,0.009340,pass

[[       nan        nan 1.16187248        nan        nan 1.23579989
         nan 1.07982794        nan 1.08717516 1.18305339]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,h 5,h 0,h 8,h 3,cz 10,cz 9,cz 7,cz 6,rx 4,cz 2
sum,0.328262,0.325437,0.318689,0.313958,0.293553,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 5,h 1,h 0,h 8,h 3,cz 10,cz 9,cz 7,cz 6,rx 4,cz 2
sum,0.425981,0.417482,0.412945,0.405153,0.3728,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 0,h 3,h 5,h 1,cz 10,cz 9,cz 7,cz 6,rx 4,cz 2
sum,0.00244,0.000676,0.000619,0.000521,0.000458,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_cswap_inGap_10_.qasm

100%|██████████| 5/5 [00:01<00:00,  2.89it/s]
100%|██████████| 10/10 [00:03<00:00,  2.89it/s]

,cz 10,cswap 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.288603,0.049613,0.041303,0.031917,0.0,0.012920,0.023270,0.0,0.010825,0.013713,fail
1,0.0,0.309804,0.049445,0.045459,0.036492,0.0,0.013999,0.026406,0.0,0.014004,0.014914,fail
2,0.0,0.330663,0.074535,0.053489,0.051530,0.0,0.014970,0.031209,0.0,0.010752,0.011057,fail
3,0.0,0.311266,0.051044,0.049383,0.038330,0.0,0.014930,0.028227,0.0,0.012049,0.016283,fail
4,0.0,0.282237,0.047853,0.042058,0.033317,0.0,0.012947,0.024768,0.0,0.007936,0.010471,fail
5,0.0,0.313827,0.069370,0.043868,0.041333,0.0,0.013500,0.025713,0.0,0.007665,0.008585,pass
6,0.0,0.283242,0.047549,0.037798,0.033298,0.0,0.010046,0.021334,0.0,0.006707,0.008847,pass
7,0.0,0.263621,0.055891,0.040810,0.034569,0.0,0.011847,0.023574,0.0,0.009536,0.008875,pass
8,0.0,0.235218,0.059452,0.038531,0.034211,0.0,0.011960,0.022873,0.0,0.010591,0.011772,pass
9,0.0,0.259670,0.049788,0.040455,0.031823,0.0,0.013165,0.024119,0.0,0.013158,0.011452,pass
10,0.0,0.174981,0.034070,0.026818,0.021917,0.0,0.008576,0.015329,0.0,0.006560,0.008719,pass
11,0.0,0.295317,0.067994,0.052445,0.046915,0.0,0.015339,0.030822,0.0,0.017591,0.014324,pass
12,0.0,0.207466,0.039020,0.030709,0.027120,0.0,0.008918,0.018076,0.0,0.009159,0.009903,pass
13,0.0,0.287506,0.053625,0.041932,0.034468,0.0,0.013284,0.023623,0.0,0.008392,0.011611,pass
14,0.0,0.237414,0.044138,0.036226,0.028700,0.0,0.011482,0.021472,0.0,0.011688,0.012067,pass

[[       nan 1.08586738 1.36766801 1.15431973 1.34482846        nan
  1.072893   1.16555841        nan 1.26010577 1.22541674]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 0,cswap 9,h 7,h 4,h 3,cz 6,h 1,cz 8,cz 10,cz 5,cz 2
sum,0.384939,0.373103,0.372924,0.37133,0.371048,0.364274,0.354792,0.343451,0.0,0.0,0.0

custom SCORES

,h 0,cz 6,h 7,h 3,cswap 9,h 4,h 1,cz 8,cz 10,cz 5,cz 2
sum,0.502866,0.486745,0.480543,0.479168,0.474388,0.47093,0.466561,0.460883,0.0,0.0,0.0

DSTAR SCORES

,cswap 9,cz 8,h 7,cz 6,h 3,h 4,h 0,h 1,cz 10,cz 5,cz 2
sum,0.306715,0.013449,0.00996,0.006881,0.003429,0.000951,0.000864,0.000605,0.0,0.0,0.0

ERROR GATE LOCATION:
9
Now evolving the following mutant:  AddGate_ry_inGap_13_.qasm

100%|██████████| 5/5 [00:00<00:00, 13.39it/s]
100%|██████████| 10/10 [00:00<00:00, 15.24it/s]

,ry 10,cz 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.237211,0.0,0.0,0.027326,0.0,0.0,0.012075,0.009964,0.0,0.007101,0.012748,fail
1,0.341310,0.0,0.0,0.031898,0.0,0.0,0.013366,0.014050,0.0,0.011646,0.015606,fail
2,0.471683,0.0,0.0,0.023701,0.0,0.0,0.010657,0.018537,0.0,0.009645,0.016465,fail
3,0.469688,0.0,0.0,0.026602,0.0,0.0,0.014989,0.018958,0.0,0.012835,0.011930,fail
4,0.347862,0.0,0.0,0.032321,0.0,0.0,0.012706,0.013360,0.0,0.010694,0.015284,fail
5,0.270145,0.0,0.0,0.014912,0.0,0.0,0.006494,0.010681,0.0,0.007141,0.010794,pass
6,0.302589,0.0,0.0,0.026792,0.0,0.0,0.011330,0.013518,0.0,0.006041,0.011955,pass
7,0.406773,0.0,0.0,0.020491,0.0,0.0,0.015968,0.018981,0.0,0.012544,0.014272,pass
8,0.296464,0.0,0.0,0.022281,0.0,0.0,0.009469,0.011389,0.0,0.010151,0.013461,pass
9,0.269226,0.0,0.0,0.016245,0.0,0.0,0.006714,0.010111,0.0,0.006931,0.008674,pass
10,0.378395,0.0,0.0,0.024037,0.0,0.0,0.011480,0.015980,0.0,0.012480,0.012445,pass
11,0.395184,0.0,0.0,0.023327,0.0,0.0,0.012182,0.017019,0.0,0.011166,0.012401,pass
12,0.392391,0.0,0.0,0.015370,0.0,0.0,0.008737,0.014056,0.0,0.009710,0.009122,pass
13,0.337954,0.0,0.0,0.026283,0.0,0.0,0.012513,0.014923,0.0,0.011822,0.012524,pass
14,0.386812,0.0,0.0,0.023522,0.0,0.0,0.010300,0.015860,0.0,0.010678,0.015648,pass

[[1.2627018         nan        nan 1.13928073        nan        nan
  1.17481075 1.26605909        nan 1.23596613 1.14287324]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 7,h 4,h 0,ry 10,h 1,h 3,cz 9,cz 8,cz 6,cz 5,cz 2
sum,0.399452,0.377511,0.372591,0.352161,0.344796,0.344404,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 7,h 4,h 0,ry 10,h 3,h 1,cz 9,cz 8,cz 6,cz 5,cz 2
sum,0.513224,0.488387,0.479047,0.46333,0.453413,0.451335,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,ry 10,h 7,h 3,h 0,h 4,h 1,cz 9,cz 8,cz 6,cz 5,cz 2
sum,0.413529,0.00386,0.00109,0.001013,0.000797,0.000529,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_y_inGap_6_.qasm

100%|██████████| 5/5 [00:00<00:00, 14.90it/s]
100%|██████████| 10/10 [00:00<00:00, 15.80it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,y 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.021943,0.0,0.0,0.039426,0.012441,0.013839,0.0,0.009035,0.011759,fail
1,0.0,0.0,0.024052,0.0,0.0,0.033870,0.010624,0.013416,0.0,0.008035,0.010538,fail
2,0.0,0.0,0.021669,0.0,0.0,0.039110,0.012187,0.012603,0.0,0.014142,0.014585,fail
3,0.0,0.0,0.020170,0.0,0.0,0.036304,0.009890,0.019411,0.0,0.012875,0.011713,fail
4,0.0,0.0,0.018583,0.0,0.0,0.031640,0.009634,0.015314,0.0,0.009625,0.015754,fail
5,0.0,0.0,0.027564,0.0,0.0,0.037259,0.011667,0.021757,0.0,0.012522,0.017173,pass
6,0.0,0.0,0.016910,0.0,0.0,0.024103,0.007572,0.011619,0.0,0.006588,0.006278,pass
7,0.0,0.0,0.021160,0.0,0.0,0.032995,0.009721,0.017553,0.0,0.014054,0.009968,pass
8,0.0,0.0,0.027301,0.0,0.0,0.042527,0.013595,0.015404,0.0,0.012838,0.015361,pass
9,0.0,0.0,0.019342,0.0,0.0,0.032380,0.009557,0.014262,0.0,0.007702,0.010100,pass
10,0.0,0.0,0.030236,0.0,0.0,0.025111,0.008446,0.018430,0.0,0.008160,0.009642,pass
11,0.0,0.0,0.021244,0.0,0.0,0.043797,0.011115,0.018471,0.0,0.010045,0.016837,pass
12,0.0,0.0,0.033588,0.0,0.0,0.042848,0.014808,0.015630,0.0,0.010619,0.010286,pass
13,0.0,0.0,0.022071,0.0,0.0,0.024607,0.008623,0.012929,0.0,0.009715,0.011893,pass
14,0.0,0.0,0.029700,0.0,0.0,0.033558,0.010292,0.016437,0.0,0.011143,0.013045,pass

[[       nan        nan 1.13008331        nan        nan 1.09303414
  1.13564937 1.3012736         nan 1.3164864  1.22408972]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 0,y 5,h 4,h 1,h 3,h 8,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.347958,0.347137,0.341983,0.341901,0.314597,0.299316,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 0,h 1,y 5,h 4,h 3,h 8,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.454441,0.454427,0.441995,0.439077,0.416941,0.383879,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,y 5,h 8,h 3,h 0,h 4,h 1,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.006092,0.002157,0.001078,0.000809,0.000588,0.000565,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_ry_inGap_6_.qasm

100%|██████████| 10/10 [00:00<00:00, 15.31it/s]
100%|██████████| 10/10 [00:00<00:00, 16.70it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,ry 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.019868,0.0,0.0,0.052910,0.003413,0.013714,0.0,0.008556,0.011883,fail
1,0.0,0.0,0.018424,0.0,0.0,0.056177,0.002877,0.014342,0.0,0.010565,0.009608,fail
2,0.0,0.0,0.026450,0.0,0.0,0.058717,0.003814,0.018596,0.0,0.011132,0.014117,fail
3,0.0,0.0,0.021622,0.0,0.0,0.040260,0.001728,0.009956,0.0,0.006881,0.011562,fail
4,0.0,0.0,0.026284,0.0,0.0,0.049049,0.004111,0.013495,0.0,0.009350,0.011591,fail
5,0.0,0.0,0.032695,0.0,0.0,0.060072,0.005756,0.012592,0.0,0.007672,0.012088,fail
6,0.0,0.0,0.018395,0.0,0.0,0.034659,0.001182,0.009616,0.0,0.008089,0.009786,fail
7,0.0,0.0,0.022580,0.0,0.0,0.053101,0.004017,0.014952,0.0,0.008165,0.010689,fail
8,0.0,0.0,0.021826,0.0,0.0,0.059255,0.003466,0.011081,0.0,0.011005,0.009800,fail
9,0.0,0.0,0.029696,0.0,0.0,0.060095,0.005362,0.010606,0.0,0.009006,0.009384,fail
10,0.0,0.0,0.022949,0.0,0.0,0.059762,0.005148,0.009185,0.0,0.009979,0.011934,pass
11,0.0,0.0,0.020283,0.0,0.0,0.048252,0.003515,0.014851,0.0,0.009222,0.010635,pass
12,0.0,0.0,0.028239,0.0,0.0,0.050886,0.003788,0.011920,0.0,0.009983,0.010700,pass
13,0.0,0.0,0.021876,0.0,0.0,0.039615,0.003161,0.008484,0.0,0.004987,0.009777,pass
14,0.0,0.0,0.026464,0.0,0.0,0.039720,0.003821,0.009637,0.0,0.005607,0.009571,pass
15,0.0,0.0,0.029474,0.0,0.0,0.054483,0.005878,0.010692,0.0,0.005344,0.011958,pass
16,0.0,0.0,0.020657,0.0,0.0,0.055606,0.004313,0.010065,0.0,0.006911,0.011444,pass
17,0.0,0.0,0.021695,0.0,0.0,0.044318,0.004290,0.008020,0.0,0.009286,0.009581,pass
18,0.0,0.0,0.028929,0.0,0.0,0.044017,0.004523,0.011704,0.0,0.011828,0.016066,pass
19,0.0,0.0,0.019849,0.0,0.0,0.038744,0.002530,0.008753,0.0,0.006602,0.008286,pass

[[       nan        nan 1.37465392        nan        nan 1.14620369
  1.61111267 1.44206964        nan 1.23114161 1.27745162]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 3,h 1,ry 5,h 0,h 8,h 4,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.555198,0.531358,0.524453,0.50126,0.497305,0.465814,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 3,h 1,ry 5,h 8,h 0,h 4,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.755357,0.694902,0.674735,0.668211,0.661344,0.653433,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,ry 5,h 8,h 3,h 0,h 1,h 4,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.026241,0.005524,0.001646,0.001208,0.000811,0.000127,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rxx_inGap_8_.qasm

100%|██████████| 7/7 [00:00<00:00, 16.09it/s]
100%|██████████| 10/10 [00:00<00:00, 16.71it/s]

,cz 10,cz 9,h 8,rxx 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.023630,0.107900,0.0,0.0,0.010653,0.016619,0.0,0.010252,0.012569,fail
1,0.0,0.0,0.021575,0.138265,0.0,0.0,0.011911,0.020945,0.0,0.012084,0.019668,fail
2,0.0,0.0,0.020572,0.082079,0.0,0.0,0.007962,0.013554,0.0,0.009721,0.009706,fail
3,0.0,0.0,0.024594,0.105488,0.0,0.0,0.010446,0.017223,0.0,0.012115,0.010002,fail
4,0.0,0.0,0.032268,0.126846,0.0,0.0,0.012230,0.013520,0.0,0.012623,0.015649,fail
5,0.0,0.0,0.026299,0.102642,0.0,0.0,0.011317,0.016003,0.0,0.009959,0.009962,fail
6,0.0,0.0,0.026404,0.128410,0.0,0.0,0.012559,0.016424,0.0,0.011073,0.014296,fail
7,0.0,0.0,0.020721,0.149180,0.0,0.0,0.013060,0.015031,0.0,0.010767,0.014483,pass
8,0.0,0.0,0.020638,0.048007,0.0,0.0,0.004984,0.013840,0.0,0.006199,0.011739,pass
9,0.0,0.0,0.020138,0.134252,0.0,0.0,0.011340,0.009172,0.0,0.007756,0.010059,pass
10,0.0,0.0,0.032887,0.122935,0.0,0.0,0.013500,0.018888,0.0,0.010364,0.010813,pass
11,0.0,0.0,0.021586,0.141577,0.0,0.0,0.013421,0.014422,0.0,0.011144,0.011321,pass
12,0.0,0.0,0.017304,0.121672,0.0,0.0,0.012111,0.014364,0.0,0.009699,0.008253,pass
13,0.0,0.0,0.008757,0.057835,0.0,0.0,0.004412,0.009433,0.0,0.004457,0.008301,pass
14,0.0,0.0,0.007599,0.066823,0.0,0.0,0.005725,0.009288,0.0,0.005163,0.005164,pass
15,0.0,0.0,0.017227,0.074554,0.0,0.0,0.006753,0.007432,0.0,0.004765,0.007030,pass
16,0.0,0.0,0.015988,0.088386,0.0,0.0,0.007860,0.009979,0.0,0.006782,0.013445,pass

[[       nan        nan 1.2881932  1.22261173        nan        nan
  1.14055694 1.2828797         nan 1.13535378 1.49891488]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,h 8,h 3,h 0,h 4,rxx 7,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.502361,0.489527,0.48399,0.477252,0.452747,0.440565,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 0,h 8,h 1,h 3,h 4,rxx 7,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.656092,0.647178,0.64495,0.639216,0.581843,0.575225,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,rxx 7,h 8,h 3,h 0,h 1,h 4,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.078284,0.00428,0.001834,0.001188,0.000856,0.000838,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
7
Now evolving the following mutant:  AddGate_t_inGap_11_.qasm

100%|██████████| 2/2 [00:00<00:00, 13.73it/s]
100%|██████████| 10/10 [00:00<00:00, 17.59it/s]

,cz 10,tdg 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,3.158321e-18,0.0,0.025776,0.0,0.0,0.013865,0.012254,0.0,0.010674,0.013955,fail
1,0.0,3.624424e-18,0.0,0.031535,0.0,0.0,0.012253,0.022445,0.0,0.010491,0.014654,fail
2,0.0,1.982182e-18,0.0,0.013015,0.0,0.0,0.007874,0.006351,0.0,0.005094,0.007395,pass
3,0.0,2.306038e-18,0.0,0.019846,0.0,0.0,0.008375,0.009699,0.0,0.006479,0.008244,pass
4,0.0,2.799363e-18,0.0,0.019075,0.0,0.0,0.007991,0.012667,0.0,0.005795,0.009617,pass
5,0.0,2.776581e-18,0.0,0.013974,0.0,0.0,0.010480,0.015954,0.0,0.009975,0.009587,pass
6,0.0,2.930664e-18,0.0,0.027695,0.0,0.0,0.007514,0.008525,0.0,0.009184,0.009563,pass
7,0.0,3.175742e-18,0.0,0.026809,0.0,0.0,0.009288,0.013266,0.0,0.010946,0.014772,pass
8,0.0,3.448851e-18,0.0,0.029301,0.0,0.0,0.015587,0.019637,0.0,0.012510,0.020730,pass
9,0.0,3.162094e-18,0.0,0.026017,0.0,0.0,0.010516,0.008319,0.0,0.008587,0.011123,pass
10,0.0,3.022317e-18,0.0,0.020403,0.0,0.0,0.012039,0.016206,0.0,0.011658,0.013661,pass
11,0.0,2.901289e-18,0.0,0.021560,0.0,0.0,0.011732,0.014496,0.0,0.011424,0.011894,pass

[[       nan 1.06871883        nan 1.10048457        nan        nan
  1.06169271 1.29369277        nan 1.00867928 1.02442065]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 3,h 7,h 4,h 0,tdg 9,h 1,cz 10,cz 8,cz 6,cz 5,cz 2
sum,0.217117,0.208401,0.204827,0.197041,0.192212,0.187603,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 3,h 7,h 4,h 0,tdg 9,h 1,cz 10,cz 8,cz 6,cz 5,cz 2
sum,0.287337,0.265737,0.259193,0.247505,0.243567,0.234911,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 7,h 3,h 0,h 4,h 1,tdg 9,cz 10,cz 8,cz 6,cz 5,cz 2
sum,0.001481,0.000567,0.000387,0.000325,0.000214,2.300282e-35,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
9
Now evolving the following mutant:  AddGate_rx_inGap_6_.qasm

100%|██████████| 5/5 [00:00<00:00, 15.84it/s]
100%|██████████| 10/10 [00:00<00:00, 16.46it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,rx 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.027255,0.0,0.0,0.026924,0.008641,0.013202,0.0,0.009456,0.012352,fail
1,0.0,0.0,0.023920,0.0,0.0,0.041401,0.013549,0.019625,0.0,0.011353,0.013222,fail
2,0.0,0.0,0.026979,0.0,0.0,0.039226,0.011957,0.015370,0.0,0.013532,0.018589,fail
3,0.0,0.0,0.029271,0.0,0.0,0.031600,0.009797,0.016564,0.0,0.010500,0.012441,fail
4,0.0,0.0,0.024647,0.0,0.0,0.037169,0.011453,0.016334,0.0,0.013124,0.011145,fail
5,0.0,0.0,0.022620,0.0,0.0,0.031516,0.009602,0.009056,0.0,0.007345,0.010724,pass
6,0.0,0.0,0.020158,0.0,0.0,0.038083,0.011937,0.009533,0.0,0.009562,0.014487,pass
7,0.0,0.0,0.021859,0.0,0.0,0.042398,0.012830,0.016731,0.0,0.006965,0.014908,pass
8,0.0,0.0,0.022477,0.0,0.0,0.038190,0.011471,0.017729,0.0,0.008586,0.012020,pass
9,0.0,0.0,0.024262,0.0,0.0,0.038840,0.011440,0.017104,0.0,0.011567,0.019663,pass
10,0.0,0.0,0.029741,0.0,0.0,0.038241,0.012992,0.016269,0.0,0.008496,0.014884,pass
11,0.0,0.0,0.015764,0.0,0.0,0.046448,0.012900,0.013914,0.0,0.012708,0.012180,pass
12,0.0,0.0,0.020396,0.0,0.0,0.035693,0.010273,0.009640,0.0,0.009919,0.012491,pass
13,0.0,0.0,0.021472,0.0,0.0,0.028545,0.008897,0.007627,0.0,0.006508,0.006047,pass
14,0.0,0.0,0.027094,0.0,0.0,0.039077,0.011666,0.018628,0.0,0.015261,0.015663,pass

[[       nan        nan 1.10813336        nan        nan 1.17403403
  1.2229204  1.20999255        nan 1.16723669 1.37190628]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,h 3,h 8,h 0,h 4,rx 5,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.374252,0.373149,0.369003,0.337372,0.327008,0.318641,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 3,h 1,h 8,h 0,h 4,rx 5,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.486026,0.483462,0.47123,0.453083,0.426984,0.412164,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,rx 5,h 8,h 3,h 0,h 1,h 4,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.005782,0.003338,0.00128,0.000894,0.000659,0.0006,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_h_inGap_4_.qasm

100%|██████████| 10/10 [00:00<00:00, 16.63it/s]
100%|██████████| 10/10 [00:00<00:00, 16.48it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.021901,0.0,0.0,0.010756,0.015264,0.007244,0.0,0.007977,0.007326,fail
1,0.0,0.0,0.017463,0.0,0.0,0.010079,0.013160,0.005833,0.0,0.005090,0.009549,fail
2,0.0,0.0,0.023066,0.0,0.0,0.012711,0.016416,0.007803,0.0,0.010863,0.013420,fail
3,0.0,0.0,0.023327,0.0,0.0,0.012206,0.017385,0.008834,0.0,0.005823,0.009728,fail
4,0.0,0.0,0.014410,0.0,0.0,0.008919,0.008391,0.002930,0.0,0.005234,0.009058,fail
5,0.0,0.0,0.023395,0.0,0.0,0.013325,0.015139,0.007742,0.0,0.007231,0.011993,fail
6,0.0,0.0,0.033554,0.0,0.0,0.014687,0.020933,0.010438,0.0,0.010579,0.011376,fail
7,0.0,0.0,0.022738,0.0,0.0,0.012397,0.019183,0.009815,0.0,0.011335,0.010041,fail
8,0.0,0.0,0.022480,0.0,0.0,0.009746,0.010447,0.004361,0.0,0.008642,0.008541,fail
9,0.0,0.0,0.021104,0.0,0.0,0.012053,0.014785,0.007092,0.0,0.008783,0.009791,fail
10,0.0,0.0,0.025430,0.0,0.0,0.012472,0.015417,0.007349,0.0,0.011208,0.014854,pass
11,0.0,0.0,0.032605,0.0,0.0,0.016541,0.018318,0.011077,0.0,0.011186,0.013225,pass
12,0.0,0.0,0.019268,0.0,0.0,0.009028,0.009629,0.004960,0.0,0.006173,0.006855,pass
13,0.0,0.0,0.029620,0.0,0.0,0.012417,0.022505,0.012367,0.0,0.011119,0.013832,pass
14,0.0,0.0,0.019355,0.0,0.0,0.004601,0.006772,0.003449,0.0,0.005644,0.009814,pass
15,0.0,0.0,0.029274,0.0,0.0,0.015887,0.018527,0.011262,0.0,0.009340,0.010006,pass
16,0.0,0.0,0.025418,0.0,0.0,0.015704,0.013804,0.007105,0.0,0.008515,0.011063,pass
17,0.0,0.0,0.019232,0.0,0.0,0.006013,0.010862,0.004552,0.0,0.008975,0.014300,pass
18,0.0,0.0,0.031373,0.0,0.0,0.014833,0.020568,0.012406,0.0,0.010554,0.011705,pass
19,0.0,0.0,0.020269,0.0,0.0,0.008427,0.012978,0.007064,0.0,0.005486,0.008895,pass

[[       nan        nan 1.50170168        nan        nan 1.25662549
  1.38533488 1.44783156        nan 1.3898107  1.33103611]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 4,h 5,h 1,h 8,h 3,h 0,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.502864,0.50205,0.480441,0.470117,0.46909,0.468133,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 4,h 5,h 1,h 8,h 3,h 0,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.677023,0.659773,0.647372,0.646611,0.638881,0.623908,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 4,h 5,h 0,h 1,h 3,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.00487,0.00225,0.00135,0.001005,0.000659,0.000516,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_h_inGap_15_.qasm

100%|██████████| 10/10 [00:01<00:00,  7.91it/s]
100%|██████████| 10/10 [00:01<00:00,  8.14it/s]

,h 10,cz 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.081253,0.303333,0.552132,0.063077,0.0,0.0,0.019856,0.018548,0.0,0.026212,0.023450,fail
1,0.089599,0.344454,0.650140,0.078480,0.0,0.0,0.031188,0.030148,0.0,0.017764,0.022777,fail
2,0.080550,0.314694,0.561467,0.066464,0.0,0.0,0.018413,0.021792,0.0,0.019050,0.017171,fail
3,0.052687,0.192839,0.374783,0.046841,0.0,0.0,0.018688,0.022874,0.0,0.016337,0.022145,fail
4,0.087301,0.339592,0.578343,0.062168,0.0,0.0,0.020288,0.033208,0.0,0.022357,0.021411,fail
5,0.063892,0.241990,0.486712,0.061221,0.0,0.0,0.019182,0.016865,0.0,0.010444,0.014898,fail
6,0.072669,0.243194,0.517211,0.086835,0.0,0.0,0.026836,0.019485,0.0,0.018295,0.014908,fail
7,0.077940,0.262446,0.546669,0.090634,0.0,0.0,0.027816,0.025721,0.0,0.022170,0.019259,fail
8,0.080924,0.264716,0.497054,0.064000,0.0,0.0,0.019251,0.020554,0.0,0.016938,0.011367,fail
9,0.070254,0.266953,0.534561,0.076673,0.0,0.0,0.024366,0.023353,0.0,0.015407,0.021392,fail
10,0.071454,0.229184,0.370491,0.048712,0.0,0.0,0.021274,0.018524,0.0,0.030645,0.016544,pass
11,0.064250,0.218440,0.344812,0.039567,0.0,0.0,0.015083,0.032746,0.0,0.022034,0.017423,pass
12,0.057763,0.227112,0.379590,0.032853,0.0,0.0,0.014989,0.018041,0.0,0.009520,0.018669,pass
13,0.083224,0.349318,0.534245,0.039835,0.0,0.0,0.018523,0.026443,0.0,0.014255,0.022456,pass
14,0.046697,0.188194,0.325504,0.040787,0.0,0.0,0.012009,0.025013,0.0,0.016656,0.024356,pass
15,0.040986,0.152325,0.270798,0.035158,0.0,0.0,0.010859,0.008989,0.0,0.010115,0.007492,pass
16,0.054604,0.215322,0.351797,0.041952,0.0,0.0,0.013233,0.022245,0.0,0.016025,0.018634,pass
17,0.043324,0.147291,0.283050,0.032533,0.0,0.0,0.017578,0.014361,0.0,0.010574,0.016633,pass
18,0.079812,0.301701,0.483659,0.047301,0.0,0.0,0.023567,0.025144,0.0,0.024641,0.026819,pass
19,0.059525,0.233337,0.405240,0.047391,0.0,0.0,0.021266,0.019530,0.0,0.015424,0.015278,pass

[[1.18349465 1.24162849 1.22689434 1.30147346        nan        nan
  1.38070493 1.42800706        nan 1.41707195 1.2421874 ]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 7,cz 8,h 4,h 10,cz 9,h 3,h 1,h 0,cz 6,cz 5,cz 2
sum,0.631659,0.585646,0.572925,0.557198,0.550828,0.524247,0.521257,0.505996,0.0,0.0,0.0

custom SCORES

,h 7,h 4,cz 8,h 10,cz 9,h 3,h 1,h 0,cz 6,cz 5,cz 2
sum,0.837181,0.770686,0.765277,0.722058,0.721809,0.711404,0.705922,0.663132,0.0,0.0,0.0

DSTAR SCORES

,cz 8,cz 9,h 10,h 7,h 3,h 4,h 0,h 1,cz 6,cz 5,cz 2
sum,2.042315,0.627638,0.054063,0.046604,0.005296,0.005018,0.003499,0.003364,0.0,0.0,0.0

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_rxx_inGap_12_.qasm

100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
100%|██████████| 10/10 [00:00<00:00, 16.28it/s]

,rxx 10,cz 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.385071,0.0,0.0,0.025181,0.0,0.0,0.009795,0.016711,0.0,0.014079,0.012501,fail
1,0.319373,0.0,0.0,0.021596,0.0,0.0,0.013626,0.007798,0.0,0.010743,0.015206,pass
2,0.395292,0.0,0.0,0.025044,0.0,0.0,0.011370,0.013683,0.0,0.013373,0.013326,pass
3,0.492142,0.0,0.0,0.025453,0.0,0.0,0.013173,0.016300,0.0,0.011351,0.015192,pass
4,0.396628,0.0,0.0,0.019822,0.0,0.0,0.013587,0.016284,0.0,0.009721,0.014594,pass
5,0.381530,0.0,0.0,0.035159,0.0,0.0,0.012425,0.017385,0.0,0.010602,0.018461,pass
6,0.245367,0.0,0.0,0.021346,0.0,0.0,0.011245,0.012617,0.0,0.011119,0.011923,pass
7,0.268385,0.0,0.0,0.019894,0.0,0.0,0.012489,0.010702,0.0,0.008341,0.010062,pass
8,0.504375,0.0,0.0,0.022470,0.0,0.0,0.012207,0.014227,0.0,0.011910,0.013359,pass
9,0.307481,0.0,0.0,0.021446,0.0,0.0,0.008585,0.013757,0.0,0.012329,0.013655,pass
10,0.415367,0.0,0.0,0.021700,0.0,0.0,0.011306,0.017364,0.0,0.008582,0.009443,pass

[[ 1. nan nan  1. nan nan  1.  1. nan  1.  1.]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,h 3,h 7,rxx 10,h 0,h 4,cz 9,cz 8,cz 6,cz 5,cz 2
sum,0.115257,0.106556,0.09718,0.093668,0.084626,0.075458,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 1,h 3,h 7,rxx 10,h 0,h 4,cz 9,cz 8,cz 6,cz 5,cz 2
sum,0.144072,0.133195,0.121475,0.117085,0.105783,0.094323,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,rxx 10,h 7,h 3,h 1,h 0,h 4,cz 9,cz 8,cz 6,cz 5,cz 2
sum,0.031376,0.000514,0.000245,0.000179,0.000138,0.000086,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_rz_inGap_8_.qasm

100%|██████████| 6/6 [00:00<00:00, 16.90it/s]
100%|██████████| 10/10 [00:00<00:00, 16.03it/s]

,cz 10,cz 9,h 8,rz 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.028639,0.028639,0.0,0.0,0.012228,0.016211,0.0,0.013161,0.014801,fail
1,0.0,0.0,0.024615,0.024615,0.0,0.0,0.010308,0.016750,0.0,0.008995,0.010893,fail
2,0.0,0.0,0.016924,0.016924,0.0,0.0,0.009166,0.009060,0.0,0.009856,0.012157,fail
3,0.0,0.0,0.024779,0.024779,0.0,0.0,0.009768,0.013411,0.0,0.010063,0.009035,fail
4,0.0,0.0,0.026952,0.026952,0.0,0.0,0.009432,0.014284,0.0,0.010348,0.011818,fail
5,0.0,0.0,0.025443,0.025443,0.0,0.0,0.012859,0.015557,0.0,0.012848,0.015031,fail
6,0.0,0.0,0.028263,0.028263,0.0,0.0,0.011480,0.016098,0.0,0.008321,0.013506,pass
7,0.0,0.0,0.026357,0.026357,0.0,0.0,0.009025,0.014395,0.0,0.011868,0.014472,pass
8,0.0,0.0,0.019500,0.019500,0.0,0.0,0.008197,0.010061,0.0,0.007806,0.009705,pass
9,0.0,0.0,0.024981,0.024981,0.0,0.0,0.009108,0.013539,0.0,0.011144,0.012849,pass
10,0.0,0.0,0.020718,0.020718,0.0,0.0,0.011478,0.013671,0.0,0.008784,0.010990,pass
11,0.0,0.0,0.019586,0.019586,0.0,0.0,0.008742,0.015134,0.0,0.009487,0.010281,pass
12,0.0,0.0,0.026620,0.026620,0.0,0.0,0.009970,0.016664,0.0,0.010058,0.012553,pass
13,0.0,0.0,0.019071,0.019071,0.0,0.0,0.007610,0.015431,0.0,0.010009,0.008534,pass
14,0.0,0.0,0.022223,0.022223,0.0,0.0,0.012117,0.013059,0.0,0.010989,0.012221,pass
15,0.0,0.0,0.019001,0.019001,0.0,0.0,0.006514,0.011922,0.0,0.008083,0.009943,pass

[[       nan        nan 1.16614617 1.16614617        nan        nan
  1.21005856 1.1785962         nan 1.20984447 1.22311488]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 4,h 1,h 8,rz 7,h 0,h 3,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.403545,0.403357,0.394336,0.394336,0.390569,0.378575,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 4,h 1,h 0,rz 7,h 8,h 3,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.525623,0.525357,0.509997,0.509299,0.509299,0.490122,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,rz 7,h 8,h 3,h 0,h 1,h 4,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.003487,0.003487,0.001184,0.000889,0.000699,0.000667,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
7
Now evolving the following mutant:  AddGate_z_inGap_4_.qasm

100%|██████████| 4/4 [00:00<00:00, 16.25it/s]
100%|██████████| 10/10 [00:00<00:00, 17.65it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,z 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.027213,0.0,0.0,0.015416,0.011751,0.025215,0.0,0.011020,0.011448,fail
1,0.0,0.0,0.039437,0.0,0.0,0.016571,0.019138,0.043079,0.0,0.013624,0.019217,fail
2,0.0,0.0,0.027039,0.0,0.0,0.013892,0.017047,0.038996,0.0,0.014004,0.020147,fail
3,0.0,0.0,0.023001,0.0,0.0,0.012044,0.011503,0.031191,0.0,0.011781,0.015380,fail
4,0.0,0.0,0.032864,0.0,0.0,0.016852,0.019021,0.043116,0.0,0.014108,0.014831,pass
5,0.0,0.0,0.024769,0.0,0.0,0.009137,0.010030,0.025472,0.0,0.006793,0.008949,pass
6,0.0,0.0,0.018653,0.0,0.0,0.010378,0.016938,0.040879,0.0,0.007895,0.010302,pass
7,0.0,0.0,0.022317,0.0,0.0,0.011168,0.011469,0.028677,0.0,0.009883,0.012515,pass
8,0.0,0.0,0.028089,0.0,0.0,0.013236,0.012511,0.025672,0.0,0.010309,0.012452,pass
9,0.0,0.0,0.025338,0.0,0.0,0.011433,0.020339,0.048582,0.0,0.011591,0.009521,pass
10,0.0,0.0,0.015201,0.0,0.0,0.011972,0.012301,0.031394,0.0,0.008306,0.013604,pass
11,0.0,0.0,0.025221,0.0,0.0,0.013037,0.011867,0.029027,0.0,0.008417,0.011959,pass
12,0.0,0.0,0.019204,0.0,0.0,0.008890,0.011896,0.027891,0.0,0.005735,0.007549,pass
13,0.0,0.0,0.020543,0.0,0.0,0.013459,0.011304,0.027184,0.0,0.010570,0.011862,pass

[[       nan        nan 1.35184461        nan        nan 1.14435208
  1.28791496 1.24432972        nan 1.11078421 1.21751206]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 0,h 1,h 8,h 5,h 4,z 3,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.368272,0.350112,0.334461,0.326354,0.301553,0.296929,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 0,h 8,h 1,h 5,h 4,z 3,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.480366,0.447496,0.447336,0.41972,0.398646,0.389298,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,z 3,h 8,h 0,h 4,h 5,h 1,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.004431,0.003217,0.001065,0.000854,0.000814,0.000621,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
3
Now evolving the following mutant:  AddGate_cswap_inGap_11_.qasm

100%|██████████| 4/4 [00:01<00:00,  2.11it/s]
100%|██████████| 10/10 [00:04<00:00,  2.36it/s]

,cswap 10,cz 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.589942,0.120482,0.093905,0.042237,0.107268,0.0,0.019273,0.046518,0.055964,0.022879,0.044652,fail
1,0.593876,0.127855,0.096508,0.049623,0.100651,0.0,0.021074,0.053209,0.062140,0.025290,0.051344,fail
2,0.404894,0.056518,0.035539,0.027041,0.058535,0.0,0.013269,0.030245,0.029565,0.015464,0.027273,fail
3,0.515016,0.084907,0.083484,0.045175,0.092891,0.0,0.018570,0.044354,0.051045,0.021233,0.042364,fail
4,0.509941,0.100235,0.088629,0.043852,0.102675,0.0,0.021218,0.048018,0.053562,0.022951,0.045309,pass
5,0.480684,0.090299,0.072434,0.034702,0.070744,0.0,0.016536,0.038985,0.040328,0.018537,0.037856,pass
6,0.402712,0.083259,0.076801,0.032368,0.091219,0.0,0.016674,0.035558,0.044896,0.016782,0.034652,pass
7,0.530168,0.117906,0.091969,0.025467,0.085557,0.0,0.018396,0.044632,0.050185,0.020862,0.042815,pass
8,0.384207,0.061559,0.044972,0.046007,0.062079,0.0,0.017579,0.035980,0.035517,0.020275,0.033738,pass
9,0.520066,0.070465,0.079336,0.036082,0.068766,0.0,0.016275,0.033814,0.038315,0.016790,0.032661,pass
10,0.444103,0.077766,0.046143,0.028414,0.058059,0.0,0.016875,0.029469,0.030122,0.015328,0.029346,pass
11,0.565645,0.105702,0.079728,0.043296,0.088604,0.0,0.020130,0.044310,0.049745,0.021963,0.042395,pass
12,0.522090,0.098282,0.075816,0.029315,0.089056,0.0,0.015324,0.037566,0.044194,0.017939,0.036266,pass
13,0.449063,0.086097,0.071402,0.036277,0.076664,0.0,0.017849,0.039879,0.042414,0.018256,0.037825,pass

[[1.12918859 1.31213385 1.24753194 1.20976094 1.19403721        nan
  1.16774255 1.22090699 1.25083907 1.19198499 1.23995095]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,cz 2,h 7,cz 6,h 3,h 1,h 0,cswap 10,cz 9,cz 8,h 4,cz 5
sum,0.316428,0.315618,0.311723,0.309891,0.30911,0.307583,0.304341,0.304185,0.298492,0.289855,0.0

custom SCORES

,cz 2,h 7,cz 6,h 3,cz 9,h 0,h 1,cz 8,cswap 10,h 4,cz 5
sum,0.415378,0.411073,0.404775,0.404478,0.403967,0.40293,0.401224,0.391587,0.390255,0.374474,0.0

DSTAR SCORES

,cswap 10,cz 9,cz 6,cz 8,cz 2,h 3,h 0,h 7,h 1,h 4,cz 5
sum,0.502421,0.031056,0.026939,0.020255,0.008915,0.006925,0.006274,0.006181,0.001719,0.001248,0.0

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_rxx_inGap_9_.qasm

100%|██████████| 5/5 [00:00<00:00, 15.46it/s]
100%|██████████| 10/10 [00:00<00:00, 15.52it/s]

,cz 10,cz 9,rxx 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.346168,0.100714,0.0,0.0,0.017000,0.022210,0.047379,0.022356,0.050747,fail
1,0.0,0.0,0.216269,0.054049,0.0,0.0,0.007960,0.013117,0.026075,0.013735,0.031447,fail
2,0.0,0.0,0.347496,0.111315,0.0,0.0,0.017893,0.021360,0.048423,0.018558,0.039837,fail
3,0.0,0.0,0.270913,0.091340,0.0,0.0,0.009816,0.015886,0.033903,0.016258,0.030887,fail
4,0.0,0.0,0.286161,0.095463,0.0,0.0,0.010091,0.018776,0.038778,0.016132,0.033124,fail
5,0.0,0.0,0.246466,0.068531,0.0,0.0,0.013764,0.017079,0.029862,0.012791,0.038854,pass
6,0.0,0.0,0.204544,0.060649,0.0,0.0,0.007051,0.013055,0.022288,0.007683,0.024022,pass
7,0.0,0.0,0.273476,0.074516,0.0,0.0,0.014032,0.017078,0.031409,0.011808,0.037958,pass
8,0.0,0.0,0.169235,0.042466,0.0,0.0,0.007698,0.011095,0.019315,0.009467,0.024978,pass
9,0.0,0.0,0.235996,0.066492,0.0,0.0,0.010673,0.011454,0.026470,0.011862,0.030039,pass
10,0.0,0.0,0.280427,0.091259,0.0,0.0,0.012582,0.009056,0.031380,0.012627,0.030367,pass
11,0.0,0.0,0.205350,0.073484,0.0,0.0,0.012001,0.015769,0.027118,0.013227,0.026547,pass
12,0.0,0.0,0.246764,0.080759,0.0,0.0,0.008975,0.014636,0.036140,0.016023,0.029710,pass
13,0.0,0.0,0.170631,0.059158,0.0,0.0,0.007291,0.012200,0.027596,0.015307,0.023495,pass
14,0.0,0.0,0.194853,0.073101,0.0,0.0,0.010243,0.012348,0.024482,0.010291,0.021752,pass

[[       nan        nan 1.18437009 1.22896304        nan        nan
  1.42553069 1.21565674 1.24442736 1.28424027 1.36386456]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,cz 2,h 3,rxx 8,h 7,h 0,h 4,cz 10,cz 9,cz 6,cz 5
sum,0.418205,0.413409,0.405778,0.397052,0.396118,0.392691,0.37565,0.0,0.0,0.0,0.0

custom SCORES

,h 1,cz 2,h 3,h 0,h 7,rxx 8,h 4,cz 10,cz 9,cz 6,cz 5
sum,0.552474,0.542023,0.5291,0.526585,0.517822,0.514616,0.509525,0.0,0.0,0.0,0.0

DSTAR SCORES

,rxx 8,h 7,cz 2,h 0,h 3,h 1,h 4,cz 10,cz 9,cz 6,cz 5
sum,0.297757,0.036043,0.007175,0.006546,0.001625,0.001479,0.000772,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_rx_inGap_13_.qasm

100%|██████████| 4/4 [00:00<00:00,  8.87it/s]
100%|██████████| 10/10 [00:01<00:00,  9.41it/s]

,rx 10,cz 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.509281,0.421068,0.0,0.042491,0.241818,0.0,0.028907,0.151593,0.0,0.038073,0.030672,fail
1,0.526450,0.454494,0.0,0.046892,0.288977,0.0,0.034286,0.156703,0.0,0.026265,0.034467,fail
2,0.570559,0.492999,0.0,0.058743,0.239288,0.0,0.039845,0.169833,0.0,0.030145,0.034120,fail
3,0.481518,0.404814,0.0,0.045225,0.257290,0.0,0.029326,0.143329,0.0,0.024035,0.028731,fail
4,0.545822,0.465058,0.0,0.049525,0.241265,0.0,0.032102,0.162470,0.0,0.021924,0.039211,pass
5,0.535482,0.451274,0.0,0.024960,0.309167,0.0,0.032338,0.159392,0.0,0.023782,0.034321,pass
6,0.366002,0.330762,0.0,0.035914,0.204223,0.0,0.034073,0.108944,0.0,0.025375,0.019566,pass
7,0.389453,0.342686,0.0,0.032230,0.192856,0.0,0.029493,0.115925,0.0,0.031546,0.017099,pass
8,0.389270,0.328626,0.0,0.037000,0.221194,0.0,0.022889,0.115870,0.0,0.014161,0.023234,pass
9,0.380486,0.316578,0.0,0.026205,0.197267,0.0,0.024976,0.113256,0.0,0.028433,0.028047,pass
10,0.398648,0.357744,0.0,0.046763,0.186099,0.0,0.037108,0.118662,0.0,0.026659,0.032257,pass
11,0.474508,0.421376,0.0,0.041472,0.254539,0.0,0.034987,0.141242,0.0,0.015892,0.020606,pass
12,0.439556,0.367537,0.0,0.048526,0.176965,0.0,0.020225,0.130839,0.0,0.024416,0.024329,pass
13,0.429189,0.358779,0.0,0.038548,0.202520,0.0,0.026300,0.127753,0.0,0.025379,0.035333,pass

[[1.09312606 1.11200155        nan 1.21526092 1.12511142        nan
  1.20410783 1.09312606        nan 1.28496953 1.07718259]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 7,h 1,rx 10,h 3,cz 9,cz 6,h 0,h 4,cz 8,cz 5,cz 2
sum,0.336557,0.332836,0.324384,0.324384,0.321625,0.319709,0.318388,0.310091,0.0,0.0,0.0

custom SCORES

,h 1,h 7,h 3,rx 10,cz 9,cz 6,h 0,h 4,cz 8,cz 5,cz 2
sum,0.439758,0.438808,0.413032,0.413032,0.411037,0.409635,0.404129,0.403437,0.0,0.0,0.0

DSTAR SCORES

,rx 10,cz 9,cz 6,h 3,h 7,h 4,h 0,h 1,cz 8,cz 5,cz 2
sum,0.522128,0.40629,0.170624,0.072948,0.008533,0.00408,0.003833,0.003315,0.0,0.0,0.0

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_cswap_inGap_13_.qasm

100%|██████████| 4/4 [00:01<00:00,  2.57it/s]
100%|██████████| 10/10 [00:03<00:00,  2.99it/s]

,cswap 10,cz 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.566395,0.035485,0.132065,0.077612,0.089964,0.0,0.019482,0.047460,0.0,0.016200,0.018074,fail
1,0.638708,0.034335,0.128615,0.080502,0.088392,0.0,0.021282,0.046397,0.0,0.021330,0.019086,fail
2,0.576817,0.033648,0.137341,0.075142,0.092553,0.0,0.018000,0.043840,0.0,0.016531,0.018599,fail
3,0.520723,0.031372,0.104427,0.070705,0.076139,0.0,0.018615,0.041531,0.0,0.017246,0.015401,fail
4,0.523867,0.033078,0.106862,0.070435,0.085717,0.0,0.019677,0.041055,0.0,0.016373,0.015083,pass
5,0.453648,0.021158,0.072379,0.052441,0.056805,0.0,0.014185,0.029172,0.0,0.007269,0.012710,pass
6,0.505609,0.026807,0.076514,0.060754,0.064850,0.0,0.017102,0.035198,0.0,0.011383,0.011869,pass
7,0.517929,0.026224,0.111643,0.063378,0.071687,0.0,0.017074,0.036175,0.0,0.013108,0.016482,pass
8,0.473755,0.019522,0.054304,0.044348,0.048235,0.0,0.012826,0.025630,0.0,0.008039,0.012181,pass
9,0.358165,0.020021,0.069767,0.044370,0.052685,0.0,0.011846,0.025804,0.0,0.010972,0.011116,pass
10,0.314108,0.021207,0.065828,0.047777,0.046319,0.0,0.011608,0.027641,0.0,0.007790,0.010622,pass
11,0.507088,0.022329,0.059850,0.056800,0.054715,0.0,0.015407,0.031185,0.0,0.013830,0.014220,pass
12,0.538999,0.031933,0.107452,0.072078,0.080327,0.0,0.019386,0.041257,0.0,0.010578,0.015595,pass
13,0.530686,0.031026,0.110939,0.068949,0.072498,0.0,0.017938,0.040942,0.0,0.018431,0.017192,pass

[[1.10952117 1.05266575 1.09337412 1.05937271 1.0667493         nan
  1.10012976 1.05920361        nan 1.19651855 1.07286804]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,cz 8,cz 6,h 3,cz 9,h 7,h 0,h 4,cswap 10,cz 5,cz 2
sum,0.377129,0.375525,0.353811,0.349177,0.347396,0.343347,0.341737,0.330074,0.327709,0.0,0.0

custom SCORES

,h 1,cz 8,cz 6,h 3,cz 9,h 7,h 0,h 4,cswap 10,cz 5,cz 2
sum,0.48994,0.478173,0.448168,0.441639,0.438819,0.43428,0.433396,0.420856,0.418608,0.0,0.0

DSTAR SCORES

,cswap 10,cz 8,cz 6,h 7,h 3,cz 9,h 4,h 1,h 0,cz 5,cz 2
sum,0.607778,0.052208,0.025992,0.020167,0.007412,0.004275,0.00144,0.001235,0.001224,0.0,0.0

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_rzz_inGap_7_.qasm

100%|██████████| 5/5 [00:00<00:00, 15.45it/s]
100%|██████████| 10/10 [00:00<00:00, 16.60it/s]

,cz 10,cz 9,h 8,cz 7,rzz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.024093,0.0,0.0,0.0,0.010094,0.013524,0.0,0.010838,0.010563,fail
1,0.0,0.0,0.022353,0.0,0.0,0.0,0.012956,0.022446,0.0,0.012408,0.015975,fail
2,0.0,0.0,0.025651,0.0,0.0,0.0,0.014198,0.013772,0.0,0.013254,0.013475,fail
3,0.0,0.0,0.021278,0.0,0.0,0.0,0.009301,0.011430,0.0,0.010767,0.011243,fail
4,0.0,0.0,0.033862,0.0,0.0,0.0,0.013580,0.016380,0.0,0.011571,0.015253,fail
5,0.0,0.0,0.024051,0.0,0.0,0.0,0.011147,0.016014,0.0,0.007908,0.013421,pass
6,0.0,0.0,0.025918,0.0,0.0,0.0,0.008404,0.020650,0.0,0.011210,0.011400,pass
7,0.0,0.0,0.015860,0.0,0.0,0.0,0.004281,0.010342,0.0,0.006116,0.007792,pass
8,0.0,0.0,0.025423,0.0,0.0,0.0,0.009637,0.011415,0.0,0.009758,0.007262,pass
9,0.0,0.0,0.014920,0.0,0.0,0.0,0.006104,0.008656,0.0,0.008339,0.008951,pass
10,0.0,0.0,0.023083,0.0,0.0,0.0,0.011181,0.009302,0.0,0.008154,0.014846,pass
11,0.0,0.0,0.019050,0.0,0.0,0.0,0.007709,0.012504,0.0,0.010776,0.012781,pass
12,0.0,0.0,0.017628,0.0,0.0,0.0,0.006375,0.015628,0.0,0.007180,0.012117,pass
13,0.0,0.0,0.021906,0.0,0.0,0.0,0.012648,0.017326,0.0,0.013929,0.011266,pass
14,0.0,0.0,0.022142,0.0,0.0,0.0,0.007373,0.016276,0.0,0.010929,0.014332,pass

[[       nan        nan 1.33066784        nan        nan        nan
  1.18067603 1.44717622        nan 1.1263138  1.20098513]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 4,h 1,h 8,h 0,h 3,cz 10,cz 9,cz 7,rzz 6,cz 5,cz 2
sum,0.414712,0.384221,0.377314,0.368106,0.359596,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 4,h 8,h 1,h 3,h 0,cz 10,cz 9,cz 7,rzz 6,cz 5,cz 2
sum,0.537122,0.502833,0.492409,0.489696,0.478629,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 3,h 0,h 4,h 1,cz 10,cz 9,cz 7,rzz 6,cz 5,cz 2
sum,0.003107,0.001171,0.000865,0.000711,0.00068,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
6
Now evolving the following mutant:  AddGate_ccx_inGap_12_.qasm

100%|██████████| 6/6 [00:01<00:00,  3.36it/s]
100%|██████████| 10/10 [00:02<00:00,  3.39it/s]

,ccx 10,cz 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.468763,0.0,0.0,0.025702,0.0,0.011126,0.010857,0.015400,0.024527,0.013244,0.011678,fail
1,0.516937,0.0,0.0,0.028974,0.0,0.014658,0.012582,0.016202,0.025240,0.014204,0.013828,fail
2,0.537981,0.0,0.0,0.030683,0.0,0.014296,0.012184,0.014677,0.028428,0.013442,0.012390,fail
3,0.436925,0.0,0.0,0.022704,0.0,0.011431,0.010666,0.013295,0.020467,0.012425,0.014392,fail
4,0.490832,0.0,0.0,0.027303,0.0,0.012979,0.010035,0.015090,0.025307,0.013040,0.012689,fail
5,0.497913,0.0,0.0,0.027066,0.0,0.012312,0.012220,0.015798,0.025744,0.013969,0.012387,fail
6,0.356747,0.0,0.0,0.020611,0.0,0.011107,0.010752,0.012485,0.021814,0.010044,0.009899,pass
7,0.519146,0.0,0.0,0.027436,0.0,0.015904,0.011983,0.015222,0.029544,0.011643,0.011015,pass
8,0.574836,0.0,0.0,0.037140,0.0,0.016965,0.014486,0.019320,0.032792,0.016327,0.015357,pass
9,0.523212,0.0,0.0,0.027267,0.0,0.014420,0.010161,0.015703,0.028447,0.012664,0.013517,pass
10,0.519928,0.0,0.0,0.019530,0.0,0.012688,0.010015,0.012628,0.020964,0.012148,0.012098,pass
11,0.460756,0.0,0.0,0.023761,0.0,0.012622,0.009056,0.013534,0.022882,0.012413,0.011608,pass
12,0.484511,0.0,0.0,0.020322,0.0,0.011245,0.008449,0.013486,0.020594,0.011248,0.009284,pass
13,0.477983,0.0,0.0,0.021654,0.0,0.015282,0.011684,0.013695,0.023885,0.011827,0.011299,pass
14,0.455638,0.0,0.0,0.026184,0.0,0.013418,0.010325,0.013439,0.023252,0.013327,0.014485,pass
15,0.435937,0.0,0.0,0.024225,0.0,0.012698,0.010377,0.012667,0.019439,0.011685,0.012751,pass

[[1.0944395         nan        nan 1.1333856         nan 1.1451294
  1.10139068 1.07462651 1.1392983  1.06099326 1.11616701]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 7,h 1,h 4,h 0,h 3,cz 2,ccx 10,cz 5,cz 9,cz 8,cz 6
sum,0.395634,0.394422,0.389822,0.389398,0.388853,0.380631,0.380167,0.360319,0.0,0.0,0.0

custom SCORES

,h 7,h 1,h 0,h 4,h 3,cz 2,ccx 10,cz 5,cz 9,cz 8,cz 6
sum,0.507736,0.499042,0.498056,0.497159,0.49332,0.489045,0.484184,0.463472,0.0,0.0,0.0

DSTAR SCORES

,ccx 10,h 7,cz 2,h 3,h 1,h 0,cz 5,h 4,cz 9,cz 8,cz 6
sum,0.804784,0.004223,0.00359,0.001332,0.001054,0.000978,0.000961,0.000769,0.0,0.0,0.0

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_t_inGap_6_.qasm

100%|██████████| 6/6 [00:00<00:00, 16.93it/s]
100%|██████████| 10/10 [00:00<00:00, 16.07it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,tdg 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.015163,0.0,0.0,5.502019e-19,0.010629,0.013942,0.0,0.008825,0.015808,fail
1,0.0,0.0,0.020239,0.0,0.0,5.591976e-19,0.010930,0.017837,0.0,0.014055,0.015536,fail
2,0.0,0.0,0.023228,0.0,0.0,5.110939e-19,0.008628,0.014585,0.0,0.009062,0.013576,fail
3,0.0,0.0,0.026740,0.0,0.0,5.678776e-19,0.013374,0.017076,0.0,0.009779,0.014262,fail
4,0.0,0.0,0.022790,0.0,0.0,6.580993e-19,0.013782,0.017235,0.0,0.012972,0.015800,fail
5,0.0,0.0,0.019734,0.0,0.0,4.518552e-19,0.009823,0.011134,0.0,0.006730,0.008568,fail
6,0.0,0.0,0.017722,0.0,0.0,3.807908e-19,0.009863,0.009279,0.0,0.005791,0.009215,pass
7,0.0,0.0,0.025853,0.0,0.0,4.861652e-19,0.009714,0.012923,0.0,0.011998,0.012108,pass
8,0.0,0.0,0.015345,0.0,0.0,3.832487e-19,0.007770,0.008850,0.0,0.005652,0.007971,pass
9,0.0,0.0,0.015464,0.0,0.0,4.948916e-19,0.007153,0.009724,0.0,0.009875,0.012087,pass
10,0.0,0.0,0.022022,0.0,0.0,5.901428e-19,0.011284,0.010725,0.0,0.011303,0.008388,pass
11,0.0,0.0,0.022600,0.0,0.0,5.369049e-19,0.012171,0.017983,0.0,0.009949,0.011859,pass
12,0.0,0.0,0.012939,0.0,0.0,3.500040e-19,0.005705,0.006424,0.0,0.005542,0.008507,pass
13,0.0,0.0,0.024723,0.0,0.0,4.856436e-19,0.013523,0.013820,0.0,0.011163,0.010678,pass
14,0.0,0.0,0.018349,0.0,0.0,5.991633e-19,0.008856,0.019479,0.0,0.009570,0.010882,pass
15,0.0,0.0,0.024674,0.0,0.0,6.326954e-19,0.012313,0.014021,0.0,0.008751,0.015444,pass

[[       nan        nan 1.2544696         nan        nan 1.19715166
  1.23119218 1.16571621        nan 1.37290101 1.13524795]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 0,h 3,h 1,h 4,tdg 5,h 8,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.438149,0.426947,0.406729,0.405796,0.400381,0.390413,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 0,h 3,h 1,h 4,tdg 5,h 8,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.562501,0.551372,0.546328,0.530699,0.52021,0.512853,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 3,h 0,h 4,h 1,tdg 5,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.002638,0.001377,0.001143,0.00074,0.00062,1.813159e-36,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_t_inGap_13_.qasm

100%|██████████| 4/4 [00:00<00:00, 14.52it/s]
100%|██████████| 10/10 [00:00<00:00, 15.95it/s]

,tdg 10,cz 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,6.238620e-18,0.0,0.0,0.032126,0.0,0.0,0.011311,0.019322,0.0,0.011416,0.015202,fail
1,5.628827e-18,0.0,0.0,0.020570,0.0,0.0,0.011053,0.017696,0.0,0.010873,0.012851,fail
2,5.106570e-18,0.0,0.0,0.019909,0.0,0.0,0.011288,0.015097,0.0,0.009352,0.008800,fail
3,5.973174e-18,0.0,0.0,0.024489,0.0,0.0,0.011904,0.017716,0.0,0.011510,0.016378,fail
4,5.518768e-18,0.0,0.0,0.022724,0.0,0.0,0.007313,0.014548,0.0,0.010321,0.013874,pass
5,4.300552e-18,0.0,0.0,0.015377,0.0,0.0,0.011029,0.011774,0.0,0.009408,0.008130,pass
6,3.041551e-18,0.0,0.0,0.014890,0.0,0.0,0.006157,0.009742,0.0,0.005108,0.006733,pass
7,5.973279e-18,0.0,0.0,0.022656,0.0,0.0,0.010277,0.012641,0.0,0.007108,0.012504,pass
8,5.550467e-18,0.0,0.0,0.023558,0.0,0.0,0.013109,0.014290,0.0,0.011226,0.015535,pass
9,4.308242e-18,0.0,0.0,0.014630,0.0,0.0,0.010994,0.007548,0.0,0.004499,0.010916,pass
10,6.271659e-18,0.0,0.0,0.028574,0.0,0.0,0.010490,0.015607,0.0,0.014626,0.016347,pass
11,6.203078e-18,0.0,0.0,0.031264,0.0,0.0,0.015172,0.017113,0.0,0.009537,0.013704,pass
12,5.019333e-18,0.0,0.0,0.027842,0.0,0.0,0.009210,0.018592,0.0,0.008298,0.013914,pass
13,4.147986e-18,0.0,0.0,0.017294,0.0,0.0,0.006182,0.009599,0.0,0.007501,0.009785,pass

[[1.08747422        nan        nan 1.3235208         nan        nan
  1.04524169 1.10676517        nan 1.06698744 1.23071217]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 3,h 1,tdg 10,h 4,h 7,h 0,cz 9,cz 8,cz 6,cz 5,cz 2
sum,0.346926,0.329939,0.313135,0.313126,0.307352,0.304747,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 3,h 1,h 7,h 0,tdg 10,h 4,cz 9,cz 8,cz 6,cz 5,cz 2
sum,0.442917,0.417949,0.409049,0.398511,0.398267,0.39495,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 7,h 3,h 0,h 4,h 1,tdg 10,cz 9,cz 8,cz 6,cz 5,cz 2
sum,0.002235,0.00118,0.000688,0.000506,0.000456,1.316434e-34,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_id_inGap_3_.qasm

100%|██████████| 4/4 [00:00<00:00, 14.76it/s]
100%|██████████| 10/10 [00:00<00:00, 16.13it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,id 2,h 1,h 0,pass/fail
0,0.0,0.0,0.022772,0.0,0.0,0.010184,0.013054,0.0,0.0,0.010565,0.012144,fail
1,0.0,0.0,0.027005,0.0,0.0,0.007695,0.013100,0.0,0.0,0.010826,0.011278,fail
2,0.0,0.0,0.022932,0.0,0.0,0.013107,0.015988,0.0,0.0,0.010233,0.014754,fail
3,0.0,0.0,0.027652,0.0,0.0,0.013700,0.019379,0.0,0.0,0.014845,0.014974,fail
4,0.0,0.0,0.018508,0.0,0.0,0.009015,0.012591,0.0,0.0,0.008302,0.012277,pass
5,0.0,0.0,0.030649,0.0,0.0,0.012058,0.017861,0.0,0.0,0.014980,0.010378,pass
6,0.0,0.0,0.022363,0.0,0.0,0.008815,0.012745,0.0,0.0,0.007734,0.010670,pass
7,0.0,0.0,0.018074,0.0,0.0,0.008629,0.012918,0.0,0.0,0.010182,0.009389,pass
8,0.0,0.0,0.015135,0.0,0.0,0.008668,0.009886,0.0,0.0,0.007250,0.012566,pass
9,0.0,0.0,0.025085,0.0,0.0,0.012195,0.010888,0.0,0.0,0.012435,0.014875,pass
10,0.0,0.0,0.023562,0.0,0.0,0.010601,0.011323,0.0,0.0,0.009232,0.012613,pass
11,0.0,0.0,0.015837,0.0,0.0,0.004908,0.010791,0.0,0.0,0.007395,0.009146,pass
12,0.0,0.0,0.022202,0.0,0.0,0.011157,0.013280,0.0,0.0,0.010367,0.011754,pass
13,0.0,0.0,0.019031,0.0,0.0,0.008288,0.014852,0.0,0.0,0.007186,0.012488,pass

[[       nan        nan 1.1021019         nan        nan 1.22634056
  1.25996587        nan        nan 1.27781478 1.1269344 ]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,h 4,h 8,h 5,h 0,cz 10,cz 9,cz 7,cz 6,cz 3,id 2
sum,0.328326,0.326102,0.322906,0.32143,0.313929,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 1,h 4,h 5,h 8,h 0,cz 10,cz 9,cz 7,cz 6,cz 3,id 2
sum,0.433212,0.428822,0.419976,0.411874,0.402374,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 4,h 0,h 1,h 5,cz 10,cz 9,cz 7,cz 6,cz 3,id 2
sum,0.002392,0.000917,0.000686,0.000527,0.000488,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_ry_inGap_7_.qasm

100%|██████████| 10/10 [00:00<00:00, 13.21it/s]
100%|██████████| 10/10 [00:00<00:00, 13.72it/s]

,cz 10,cz 9,h 8,cz 7,ry 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.024903,0.0,0.121289,0.078736,0.014710,0.019804,0.0,0.016130,0.021460,fail
1,0.0,0.0,0.024688,0.0,0.124365,0.087398,0.019716,0.020403,0.0,0.010672,0.019620,fail
2,0.0,0.0,0.021821,0.0,0.072046,0.049515,0.012855,0.017957,0.0,0.009289,0.016987,fail
3,0.0,0.0,0.021509,0.0,0.072908,0.059843,0.012677,0.018518,0.0,0.007561,0.008532,fail
4,0.0,0.0,0.014711,0.0,0.100238,0.072880,0.015053,0.016808,0.0,0.008665,0.011645,fail
5,0.0,0.0,0.020141,0.0,0.082352,0.057424,0.011117,0.010210,0.0,0.010414,0.017056,fail
6,0.0,0.0,0.022782,0.0,0.095540,0.064568,0.015029,0.013011,0.0,0.011907,0.021303,fail
7,0.0,0.0,0.032303,0.0,0.120913,0.081280,0.019021,0.024437,0.0,0.012734,0.021593,fail
8,0.0,0.0,0.027180,0.0,0.115192,0.083002,0.017525,0.018794,0.0,0.013683,0.021593,fail
9,0.0,0.0,0.020864,0.0,0.056187,0.039879,0.006418,0.011071,0.0,0.009176,0.012459,fail
10,0.0,0.0,0.017802,0.0,0.071758,0.043426,0.010704,0.018650,0.0,0.008608,0.016368,pass
11,0.0,0.0,0.026475,0.0,0.108545,0.074817,0.016093,0.020152,0.0,0.012134,0.015210,pass
12,0.0,0.0,0.021116,0.0,0.083503,0.062954,0.014328,0.015866,0.0,0.007373,0.008908,pass
13,0.0,0.0,0.022764,0.0,0.093896,0.070160,0.014002,0.007464,0.0,0.010310,0.014896,pass
14,0.0,0.0,0.025634,0.0,0.100979,0.080820,0.015986,0.020164,0.0,0.009232,0.006637,pass
15,0.0,0.0,0.025165,0.0,0.071364,0.042576,0.011145,0.019043,0.0,0.010754,0.021145,pass
16,0.0,0.0,0.021788,0.0,0.072540,0.049195,0.011752,0.014418,0.0,0.007985,0.016018,pass
17,0.0,0.0,0.023190,0.0,0.078698,0.057183,0.011508,0.017183,0.0,0.012520,0.013182,pass
18,0.0,0.0,0.026066,0.0,0.099934,0.067843,0.015646,0.023939,0.0,0.010141,0.015546,pass
19,0.0,0.0,0.021841,0.0,0.086664,0.052184,0.012430,0.024261,0.0,0.010556,0.020409,pass

[[       nan        nan 1.39900626        nan 1.29407769 1.295696
  1.36801142 1.42896604        nan 1.46332715 1.25362676]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 0,cz 5,ry 6,h 1,h 4,h 8,h 3,cz 10,cz 9,cz 7,cz 2
sum,0.53732,0.528756,0.525466,0.525297,0.518948,0.498987,0.485621,0.0,0.0,0.0,0.0

custom SCORES

,h 1,h 0,cz 5,h 4,ry 6,h 8,h 3,cz 10,cz 9,cz 7,cz 2
sum,0.717467,0.70572,0.700033,0.69643,0.695464,0.673509,0.659106,0.0,0.0,0.0,0.0

DSTAR SCORES

,ry 6,cz 5,h 8,h 0,h 3,h 4,h 1,cz 10,cz 9,cz 7,cz 2
sum,0.084982,0.042918,0.005211,0.002924,0.002873,0.00205,0.001203,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
6
Now evolving the following mutant:  AddGate_z_inGap_3_.qasm

100%|██████████| 4/4 [00:00<00:00, 15.18it/s]
100%|██████████| 10/10 [00:00<00:00, 15.40it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,z 2,h 1,h 0,pass/fail
0,0.0,0.0,0.020481,0.0,0.0,0.006828,0.011195,0.0,0.0,0.009606,0.009244,fail
1,0.0,0.0,0.025958,0.0,0.0,0.013763,0.016092,0.0,0.0,0.013815,0.010144,fail
2,0.0,0.0,0.021972,0.0,0.0,0.011526,0.015951,0.0,0.0,0.011305,0.011104,fail
3,0.0,0.0,0.027049,0.0,0.0,0.012000,0.018840,0.0,0.0,0.013144,0.012217,fail
4,0.0,0.0,0.024577,0.0,0.0,0.007524,0.014934,0.0,0.0,0.009151,0.013841,pass
5,0.0,0.0,0.022091,0.0,0.0,0.011473,0.014031,0.0,0.0,0.008613,0.011968,pass
6,0.0,0.0,0.021982,0.0,0.0,0.013461,0.016221,0.0,0.0,0.009768,0.013882,pass
7,0.0,0.0,0.020969,0.0,0.0,0.005376,0.011616,0.0,0.0,0.007309,0.009699,pass
8,0.0,0.0,0.013280,0.0,0.0,0.009124,0.008242,0.0,0.0,0.008375,0.011081,pass
9,0.0,0.0,0.023353,0.0,0.0,0.013445,0.014316,0.0,0.0,0.010394,0.011976,pass
10,0.0,0.0,0.016656,0.0,0.0,0.010306,0.010206,0.0,0.0,0.008466,0.007079,pass
11,0.0,0.0,0.032011,0.0,0.0,0.013302,0.014138,0.0,0.0,0.011539,0.014480,pass
12,0.0,0.0,0.019535,0.0,0.0,0.006427,0.011995,0.0,0.0,0.005842,0.007705,pass
13,0.0,0.0,0.023991,0.0,0.0,0.011504,0.016738,0.0,0.0,0.013090,0.011127,pass

[[       nan        nan 1.13342139        nan        nan 1.24786928
  1.21395713        nan        nan 1.15436568 1.14421009]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,h 4,h 8,h 5,h 0,cz 10,cz 9,cz 7,cz 6,cz 3,z 2
sum,0.340913,0.31915,0.304105,0.302051,0.274568,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 1,h 4,h 5,h 8,h 0,cz 10,cz 9,cz 7,cz 6,cz 3,z 2
sum,0.439298,0.416008,0.396281,0.390275,0.353109,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 4,h 1,h 5,h 0,cz 10,cz 9,cz 7,cz 6,cz 3,z 2
sum,0.00216,0.000933,0.00056,0.000474,0.000443,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_t_inGap_5_.qasm

100%|██████████| 5/5 [00:00<00:00, 13.70it/s]
100%|██████████| 10/10 [00:00<00:00, 13.89it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,tdg 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.023990,0.0,0.0,0.011613,0.005201,0.013803,0.0,0.008172,0.012663,fail
1,0.0,0.0,0.019231,0.0,0.0,0.014102,0.006426,0.016430,0.0,0.010896,0.012118,fail
2,0.0,0.0,0.024282,0.0,0.0,0.014421,0.006557,0.019449,0.0,0.010929,0.014458,fail
3,0.0,0.0,0.025439,0.0,0.0,0.011272,0.005141,0.012428,0.0,0.011362,0.017369,fail
4,0.0,0.0,0.021764,0.0,0.0,0.009226,0.004204,0.012995,0.0,0.007903,0.009320,fail
5,0.0,0.0,0.020043,0.0,0.0,0.011631,0.005322,0.013498,0.0,0.009731,0.014183,pass
6,0.0,0.0,0.022602,0.0,0.0,0.011228,0.005092,0.017563,0.0,0.009549,0.013786,pass
7,0.0,0.0,0.016209,0.0,0.0,0.013343,0.006176,0.013926,0.0,0.011284,0.012060,pass
8,0.0,0.0,0.011144,0.0,0.0,0.010135,0.004735,0.012265,0.0,0.011306,0.012473,pass
9,0.0,0.0,0.033728,0.0,0.0,0.012054,0.005299,0.015016,0.0,0.009197,0.013771,pass
10,0.0,0.0,0.025482,0.0,0.0,0.014588,0.006544,0.013449,0.0,0.011516,0.010115,pass
11,0.0,0.0,0.017605,0.0,0.0,0.008950,0.004154,0.015171,0.0,0.006702,0.010078,pass
12,0.0,0.0,0.019393,0.0,0.0,0.009582,0.004394,0.008535,0.0,0.008337,0.009822,pass
13,0.0,0.0,0.025664,0.0,0.0,0.013522,0.006125,0.012858,0.0,0.008371,0.013842,pass
14,0.0,0.0,0.020347,0.0,0.0,0.011468,0.005295,0.017597,0.0,0.007709,0.011921,pass

[[       nan        nan 1.10887235        nan        nan 1.18921054
  1.19095703 1.29478242        nan 1.15323269 1.31726465]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 8,h 0,h 3,h 1,h 5,tdg 4,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.350864,0.350716,0.349352,0.344579,0.3423,0.34127,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 0,h 3,h 8,h 5,h 1,tdg 4,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.466212,0.462436,0.44813,0.444066,0.443924,0.44288,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 3,h 0,h 5,h 1,tdg 4,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.002524,0.001097,0.000849,0.000719,0.000476,0.00015,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_s_inGap_1_.qasm

100%|██████████| 6/6 [00:00<00:00, 14.29it/s]
100%|██████████| 10/10 [00:00<00:00, 16.11it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,h 2,h 1,sdg 0,pass/fail
0,0.0,0.0,0.022486,0.0,0.0,0.009529,0.013825,0.0,0.010519,0.013718,0.012314,fail
1,0.0,0.0,0.024479,0.0,0.0,0.011475,0.014159,0.0,0.009594,0.013674,0.012207,fail
2,0.0,0.0,0.034277,0.0,0.0,0.013370,0.016193,0.0,0.014350,0.015401,0.013740,fail
3,0.0,0.0,0.027839,0.0,0.0,0.010487,0.017487,0.0,0.009689,0.008742,0.007854,fail
4,0.0,0.0,0.025727,0.0,0.0,0.012270,0.013966,0.0,0.013784,0.014779,0.013192,fail
5,0.0,0.0,0.030969,0.0,0.0,0.013421,0.017229,0.0,0.013638,0.017722,0.015871,fail
6,0.0,0.0,0.023327,0.0,0.0,0.012376,0.015376,0.0,0.009549,0.012679,0.011330,pass
7,0.0,0.0,0.024922,0.0,0.0,0.012887,0.015174,0.0,0.012290,0.012769,0.011417,pass
8,0.0,0.0,0.030752,0.0,0.0,0.014435,0.015232,0.0,0.012365,0.016983,0.015299,pass
9,0.0,0.0,0.018470,0.0,0.0,0.009957,0.011230,0.0,0.009225,0.008052,0.007196,pass
10,0.0,0.0,0.017921,0.0,0.0,0.007791,0.010202,0.0,0.006835,0.009306,0.008183,pass
11,0.0,0.0,0.013623,0.0,0.0,0.007528,0.010616,0.0,0.006965,0.008144,0.007232,pass
12,0.0,0.0,0.020649,0.0,0.0,0.009878,0.013707,0.0,0.006223,0.008790,0.007888,pass
13,0.0,0.0,0.024990,0.0,0.0,0.010149,0.012440,0.0,0.012003,0.010579,0.009519,pass
14,0.0,0.0,0.020020,0.0,0.0,0.006301,0.008303,0.0,0.008317,0.006807,0.006052,pass
15,0.0,0.0,0.024274,0.0,0.0,0.010657,0.015054,0.0,0.012840,0.010257,0.009155,pass

[[       nan        nan 1.2406009         nan        nan 1.14139017
  1.12992563        nan 1.20293609 1.26531685 1.26667501]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,sdg 0,h 1,h 8,h 2,h 4,h 5,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.4463,0.446048,0.430899,0.425562,0.421715,0.408974,0.0,0.0,0.0,0.0,0.0

custom SCORES

,sdg 0,h 1,h 8,h 2,h 4,h 5,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.587629,0.587146,0.564542,0.553543,0.540841,0.525674,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 4,h 1,sdg 0,h 2,h 5,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.004419,0.001407,0.001157,0.000928,0.00084,0.000816,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_p_inGap_13_.qasm

100%|██████████| 8/8 [00:00<00:00, 14.87it/s]
100%|██████████| 10/10 [00:00<00:00, 13.93it/s]

,p 10,cz 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.0,0.020848,0.0,0.0,0.009604,0.017904,0.0,0.010847,0.009713,fail
1,0.0,0.0,0.0,0.025510,0.0,0.0,0.013093,0.018129,0.0,0.012174,0.013104,fail
2,0.0,0.0,0.0,0.023726,0.0,0.0,0.010014,0.012880,0.0,0.012340,0.009360,fail
3,0.0,0.0,0.0,0.025995,0.0,0.0,0.015423,0.011671,0.0,0.011685,0.012676,fail
4,0.0,0.0,0.0,0.022793,0.0,0.0,0.007317,0.006863,0.0,0.009865,0.010782,fail
5,0.0,0.0,0.0,0.030877,0.0,0.0,0.012733,0.015945,0.0,0.014644,0.017584,fail
6,0.0,0.0,0.0,0.026803,0.0,0.0,0.013111,0.015399,0.0,0.009644,0.013889,fail
7,0.0,0.0,0.0,0.028829,0.0,0.0,0.014019,0.013020,0.0,0.009455,0.012912,fail
8,0.0,0.0,0.0,0.029410,0.0,0.0,0.011595,0.013006,0.0,0.010679,0.012096,pass
9,0.0,0.0,0.0,0.012724,0.0,0.0,0.007008,0.010922,0.0,0.003757,0.007135,pass
10,0.0,0.0,0.0,0.021992,0.0,0.0,0.012846,0.016510,0.0,0.009054,0.011712,pass
11,0.0,0.0,0.0,0.028688,0.0,0.0,0.008457,0.020320,0.0,0.014533,0.017382,pass
12,0.0,0.0,0.0,0.032358,0.0,0.0,0.012630,0.017230,0.0,0.011260,0.015170,pass
13,0.0,0.0,0.0,0.029201,0.0,0.0,0.012584,0.019755,0.0,0.011222,0.017826,pass
14,0.0,0.0,0.0,0.020463,0.0,0.0,0.011498,0.009492,0.0,0.008639,0.009384,pass
15,0.0,0.0,0.0,0.017459,0.0,0.0,0.012363,0.015416,0.0,0.009007,0.012627,pass
16,0.0,0.0,0.0,0.019004,0.0,0.0,0.008882,0.015770,0.0,0.010394,0.010977,pass
17,0.0,0.0,0.0,0.016805,0.0,0.0,0.010542,0.014229,0.0,0.007633,0.011676,pass

[[       nan        nan        nan 1.20271658        nan        nan
  1.29451165 1.29713488        nan 1.29229688 1.40644692]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,h 7,h 4,h 0,h 3,p 10,cz 9,cz 8,cz 6,cz 5,cz 2
sum,0.485218,0.473791,0.467871,0.442559,0.422791,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 1,h 4,h 7,h 0,h 3,p 10,cz 9,cz 8,cz 6,cz 5,cz 2
sum,0.64198,0.619287,0.616249,0.598167,0.559895,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 7,h 3,h 0,h 4,h 1,p 10,cz 9,cz 8,cz 6,cz 5,cz 2
sum,0.005126,0.001533,0.001231,0.00112,0.001015,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_rx_inGap_8_.qasm

100%|██████████| 5/5 [00:00<00:00, 15.32it/s]
100%|██████████| 10/10 [00:00<00:00, 15.83it/s]

,cz 10,cz 9,h 8,rx 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.023037,0.0,0.0,0.0,0.014189,0.013979,0.0,0.009977,0.016355,fail
1,0.0,0.0,0.030378,0.0,0.0,0.0,0.009296,0.016787,0.0,0.014035,0.012636,fail
2,0.0,0.0,0.027993,0.0,0.0,0.0,0.011878,0.017680,0.0,0.011519,0.014756,fail
3,0.0,0.0,0.017552,0.0,0.0,0.0,0.012024,0.009618,0.0,0.006960,0.011400,fail
4,0.0,0.0,0.024387,0.0,0.0,0.0,0.008345,0.016902,0.0,0.011085,0.013131,fail
5,0.0,0.0,0.016787,0.0,0.0,0.0,0.006183,0.009581,0.0,0.006159,0.008577,pass
6,0.0,0.0,0.016923,0.0,0.0,0.0,0.008137,0.011064,0.0,0.005534,0.009258,pass
7,0.0,0.0,0.020667,0.0,0.0,0.0,0.010392,0.013077,0.0,0.011633,0.010576,pass
8,0.0,0.0,0.027560,0.0,0.0,0.0,0.013072,0.018865,0.0,0.013363,0.012275,pass
9,0.0,0.0,0.016098,0.0,0.0,0.0,0.007141,0.012275,0.0,0.012143,0.007908,pass
10,0.0,0.0,0.018900,0.0,0.0,0.0,0.007017,0.011072,0.0,0.006281,0.009479,pass
11,0.0,0.0,0.026964,0.0,0.0,0.0,0.014304,0.013769,0.0,0.012565,0.012846,pass
12,0.0,0.0,0.026331,0.0,0.0,0.0,0.013953,0.016189,0.0,0.011799,0.014711,pass
13,0.0,0.0,0.023457,0.0,0.0,0.0,0.010348,0.015046,0.0,0.005536,0.011371,pass
14,0.0,0.0,0.016273,0.0,0.0,0.0,0.009264,0.010902,0.0,0.008482,0.008359,pass

[[       nan        nan 1.23142373        nan        nan        nan
  1.27295494 1.17918391        nan 1.30979625 1.1976749 ]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 0,h 8,h 1,h 3,h 4,cz 10,cz 9,rx 7,cz 6,cz 5,cz 2
sum,0.393215,0.370068,0.364284,0.362495,0.358308,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 0,h 8,h 1,h 4,h 3,cz 10,cz 9,rx 7,cz 6,cz 5,cz 2
sum,0.510951,0.483996,0.483569,0.472335,0.469357,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 3,h 0,h 4,h 1,cz 10,cz 9,rx 7,cz 6,cz 5,cz 2
sum,0.00292,0.001095,0.000913,0.000609,0.000564,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
7
Now evolving the following mutant:  AddGate_ccx_inGap_7_.qasm

100%|██████████| 5/5 [00:01<00:00,  4.73it/s]
100%|██████████| 10/10 [00:02<00:00,  4.84it/s]

,cz 10,cz 9,h 8,cz 7,ccx 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.026501,0.0,0.102955,0.042958,0.024561,0.013616,0.0,0.009183,0.006500,fail
1,0.0,0.0,0.018300,0.0,0.092582,0.030904,0.020704,0.011688,0.0,0.009233,0.013260,fail
2,0.0,0.0,0.020102,0.0,0.110512,0.044160,0.015969,0.011204,0.0,0.008427,0.007300,fail
3,0.0,0.0,0.017931,0.0,0.106548,0.045719,0.018252,0.011689,0.0,0.007847,0.011489,fail
4,0.0,0.0,0.027504,0.0,0.114824,0.057378,0.027519,0.015905,0.0,0.011433,0.015520,fail
5,0.0,0.0,0.023233,0.0,0.096558,0.038880,0.019670,0.013429,0.0,0.007736,0.008575,pass
6,0.0,0.0,0.022688,0.0,0.104979,0.038559,0.027105,0.013267,0.0,0.009228,0.012264,pass
7,0.0,0.0,0.014803,0.0,0.062174,0.021944,0.017342,0.007438,0.0,0.006182,0.007748,pass
8,0.0,0.0,0.014933,0.0,0.057291,0.027042,0.012084,0.007207,0.0,0.004470,0.005596,pass
9,0.0,0.0,0.026480,0.0,0.100817,0.039742,0.021000,0.013706,0.0,0.009445,0.016415,pass
10,0.0,0.0,0.019207,0.0,0.085383,0.025247,0.018450,0.009224,0.0,0.007708,0.011740,pass
11,0.0,0.0,0.015379,0.0,0.108508,0.047092,0.017591,0.013157,0.0,0.008404,0.006291,pass
12,0.0,0.0,0.013656,0.0,0.071798,0.028892,0.014234,0.010069,0.0,0.006278,0.004246,pass
13,0.0,0.0,0.019907,0.0,0.114916,0.033808,0.021613,0.014760,0.0,0.008943,0.013609,pass
14,0.0,0.0,0.025612,0.0,0.099272,0.033945,0.024403,0.011892,0.0,0.008599,0.012843,pass

[[       nan        nan 1.24633721        nan 1.08854038 1.29744456
  1.28588658 1.24061884        nan 1.23942801 1.43519099]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,cz 5,h 1,ccx 6,h 8,h 3,h 4,h 0,cz 10,cz 9,cz 7,cz 2
sum,0.397501,0.374629,0.369054,0.360305,0.359611,0.356096,0.352481,0.0,0.0,0.0,0.0

custom SCORES

,cz 5,h 1,h 0,h 8,h 3,h 4,ccx 6,cz 10,cz 9,cz 7,cz 2
sum,0.526434,0.49071,0.47895,0.472571,0.471146,0.470571,0.469486,0.0,0.0,0.0,0.0

DSTAR SCORES

,ccx 6,cz 5,h 8,h 4,h 3,h 0,h 1,cz 10,cz 9,cz 7,cz 2
sum,0.047134,0.009164,0.002343,0.002205,0.000803,0.000573,0.000419,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
6
Now evolving the following mutant:  AddGate_rzz_inGap_15_.qasm

100%|██████████| 7/7 [00:00<00:00, 17.25it/s]
100%|██████████| 10/10 [00:00<00:00, 17.36it/s]

,rzz 10,cz 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.0,0.024626,0.0,0.0,0.011124,0.015582,0.0,0.008768,0.013567,fail
1,0.0,0.0,0.0,0.020504,0.0,0.0,0.005677,0.012371,0.0,0.007600,0.008657,fail
2,0.0,0.0,0.0,0.026609,0.0,0.0,0.012733,0.015809,0.0,0.011274,0.010879,fail
3,0.0,0.0,0.0,0.028809,0.0,0.0,0.014937,0.022101,0.0,0.011179,0.014281,fail
4,0.0,0.0,0.0,0.028218,0.0,0.0,0.011412,0.018018,0.0,0.012096,0.011582,fail
5,0.0,0.0,0.0,0.021737,0.0,0.0,0.009127,0.013060,0.0,0.009952,0.007462,fail
6,0.0,0.0,0.0,0.026055,0.0,0.0,0.012343,0.019377,0.0,0.010894,0.015017,fail
7,0.0,0.0,0.0,0.029899,0.0,0.0,0.013569,0.012308,0.0,0.009179,0.011934,pass
8,0.0,0.0,0.0,0.029380,0.0,0.0,0.008963,0.016279,0.0,0.009047,0.013086,pass
9,0.0,0.0,0.0,0.018027,0.0,0.0,0.008580,0.012802,0.0,0.010923,0.013108,pass
10,0.0,0.0,0.0,0.014828,0.0,0.0,0.006400,0.010501,0.0,0.009081,0.008962,pass
11,0.0,0.0,0.0,0.025423,0.0,0.0,0.012513,0.015237,0.0,0.009289,0.012927,pass
12,0.0,0.0,0.0,0.018709,0.0,0.0,0.008183,0.012505,0.0,0.010354,0.010057,pass
13,0.0,0.0,0.0,0.023306,0.0,0.0,0.012946,0.011518,0.0,0.010515,0.009986,pass
14,0.0,0.0,0.0,0.024605,0.0,0.0,0.012563,0.017905,0.0,0.011948,0.013442,pass
15,0.0,0.0,0.0,0.017965,0.0,0.0,0.008398,0.014635,0.0,0.008632,0.012301,pass
16,0.0,0.0,0.0,0.020530,0.0,0.0,0.009408,0.013822,0.0,0.010273,0.014497,pass

[[       nan        nan        nan 1.1421916         nan        nan
  1.35170773 1.33004166        nan 1.17987669 1.29065849]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 3,h 7,h 4,h 1,h 0,rzz 10,cz 9,cz 8,cz 6,cz 5,cz 2
sum,0.45825,0.442246,0.432433,0.419657,0.403701,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 3,h 4,h 7,h 1,h 0,rzz 10,cz 9,cz 8,cz 6,cz 5,cz 2
sum,0.610623,0.578564,0.568529,0.543443,0.533962,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 7,h 3,h 0,h 4,h 1,rzz 10,cz 9,cz 8,cz 6,cz 5,cz 2
sum,0.004316,0.001896,0.000932,0.000843,0.000725,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_ry_inGap_1_.qasm

100%|██████████| 10/10 [00:00<00:00, 16.54it/s]
100%|██████████| 10/10 [00:00<00:00, 17.42it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,h 2,h 1,ry 0,pass/fail
0,0.0,0.0,0.027791,0.0,0.0,0.009649,0.018367,0.0,0.011662,0.018196,0.012173,fail
1,0.0,0.0,0.015447,0.0,0.0,0.011196,0.016522,0.0,0.010905,0.011988,0.007558,fail
2,0.0,0.0,0.027668,0.0,0.0,0.011295,0.015059,0.0,0.011529,0.011954,0.007810,fail
3,0.0,0.0,0.022653,0.0,0.0,0.009329,0.013233,0.0,0.010184,0.013320,0.008375,fail
4,0.0,0.0,0.021906,0.0,0.0,0.010817,0.016351,0.0,0.009551,0.012189,0.007581,fail
5,0.0,0.0,0.027595,0.0,0.0,0.015124,0.019495,0.0,0.010933,0.013368,0.008627,fail
6,0.0,0.0,0.030107,0.0,0.0,0.012343,0.017856,0.0,0.014670,0.015587,0.010637,fail
7,0.0,0.0,0.030790,0.0,0.0,0.009529,0.014451,0.0,0.014357,0.014678,0.009368,fail
8,0.0,0.0,0.021382,0.0,0.0,0.010718,0.010250,0.0,0.009597,0.012684,0.008375,fail
9,0.0,0.0,0.026972,0.0,0.0,0.015795,0.018773,0.0,0.009948,0.017866,0.012176,fail
10,0.0,0.0,0.031079,0.0,0.0,0.013371,0.017000,0.0,0.007652,0.015520,0.010276,pass
11,0.0,0.0,0.028843,0.0,0.0,0.014312,0.018057,0.0,0.006770,0.017211,0.011406,pass
12,0.0,0.0,0.031497,0.0,0.0,0.012120,0.018897,0.0,0.007121,0.013612,0.008794,pass
13,0.0,0.0,0.025480,0.0,0.0,0.010646,0.016375,0.0,0.011472,0.014955,0.010325,pass
14,0.0,0.0,0.022980,0.0,0.0,0.010310,0.017930,0.0,0.014033,0.012323,0.008690,pass
15,0.0,0.0,0.023620,0.0,0.0,0.010289,0.017819,0.0,0.007726,0.009576,0.006598,pass
16,0.0,0.0,0.021331,0.0,0.0,0.010588,0.014394,0.0,0.011381,0.015051,0.010248,pass
17,0.0,0.0,0.018374,0.0,0.0,0.009120,0.012746,0.0,0.010890,0.009382,0.005908,pass
18,0.0,0.0,0.015061,0.0,0.0,0.005854,0.010637,0.0,0.005691,0.009905,0.006623,pass
19,0.0,0.0,0.031970,0.0,0.0,0.014298,0.020129,0.0,0.010850,0.013895,0.009857,pass

[[       nan        nan 1.22031431        nan        nan 1.36407522
  1.21573965        nan 1.29439275 1.28294643 1.31378439]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 2,h 1,ry 0,h 5,h 8,h 4,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.547726,0.519028,0.510903,0.510778,0.502065,0.494408,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 2,h 1,h 5,ry 0,h 8,h 4,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.72497,0.6855,0.684963,0.678707,0.655235,0.644676,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 4,h 1,h 5,h 2,ry 0,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.006211,0.00253,0.001986,0.001326,0.001273,0.000851,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_t_inGap_4_.qasm

100%|██████████| 3/3 [00:00<00:00, 14.11it/s]
100%|██████████| 10/10 [00:00<00:00, 15.32it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,tdg 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.018046,0.0,0.0,0.009938,0.009409,0.004276,0.0,0.009687,0.007316,fail
1,0.0,0.0,0.023205,0.0,0.0,0.010759,0.018615,0.008244,0.0,0.010403,0.011898,fail
2,0.0,0.0,0.021742,0.0,0.0,0.011450,0.011010,0.004830,0.0,0.007925,0.010572,fail
3,0.0,0.0,0.017901,0.0,0.0,0.009787,0.011464,0.005082,0.0,0.012670,0.014392,pass
4,0.0,0.0,0.013352,0.0,0.0,0.007062,0.013857,0.006159,0.0,0.005432,0.013102,pass
5,0.0,0.0,0.022792,0.0,0.0,0.011758,0.019065,0.008441,0.0,0.010704,0.012432,pass
6,0.0,0.0,0.017796,0.0,0.0,0.010127,0.017713,0.007880,0.0,0.012547,0.011336,pass
7,0.0,0.0,0.021866,0.0,0.0,0.010705,0.015161,0.006757,0.0,0.007230,0.012996,pass
8,0.0,0.0,0.029350,0.0,0.0,0.016114,0.021583,0.009602,0.0,0.010450,0.012989,pass
9,0.0,0.0,0.019780,0.0,0.0,0.009453,0.012961,0.005717,0.0,0.003254,0.010531,pass
10,0.0,0.0,0.025168,0.0,0.0,0.012532,0.013788,0.006175,0.0,0.010956,0.011306,pass
11,0.0,0.0,0.019815,0.0,0.0,0.011758,0.010137,0.004567,0.0,0.010888,0.010952,pass
12,0.0,0.0,0.022846,0.0,0.0,0.009315,0.008745,0.003868,0.0,0.009417,0.012023,pass

[[       nan        nan 1.10513152        nan        nan 1.0685411
  1.43064737 1.42539157        nan 1.11403376 1.19836412]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,h 8,h 5,h 4,tdg 3,h 0,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.230461,0.230186,0.228387,0.212711,0.21263,0.196155,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 1,h 8,h 5,h 4,tdg 3,h 0,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.294647,0.293783,0.289397,0.288789,0.2884,0.254922,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 4,h 5,h 0,h 1,tdg 3,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.001236,0.000485,0.000332,0.000284,0.000254,0.000098,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
3
Now evolving the following mutant:  AddGate_t_inGap_7_.qasm

100%|██████████| 5/5 [00:00<00:00, 15.89it/s]
100%|██████████| 10/10 [00:00<00:00, 15.93it/s]

,cz 10,cz 9,h 8,cz 7,tdg 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.018386,0.0,8.717831e-19,0.0,0.011203,0.014386,0.0,0.008821,0.010338,fail
1,0.0,0.0,0.021699,0.0,8.366810e-19,0.0,0.006289,0.015037,0.0,0.007703,0.010329,fail
2,0.0,0.0,0.018526,0.0,9.381295e-19,0.0,0.010264,0.012000,0.0,0.010712,0.011336,fail
3,0.0,0.0,0.019599,0.0,9.982952e-19,0.0,0.007595,0.011139,0.0,0.008114,0.008512,fail
4,0.0,0.0,0.021956,0.0,9.574726e-19,0.0,0.011824,0.011966,0.0,0.009319,0.012813,fail
5,0.0,0.0,0.027181,0.0,9.277435e-19,0.0,0.010656,0.009642,0.0,0.007881,0.012519,pass
6,0.0,0.0,0.017270,0.0,8.141453e-19,0.0,0.008403,0.009126,0.0,0.007105,0.010228,pass
7,0.0,0.0,0.022017,0.0,9.546422e-19,0.0,0.010672,0.014528,0.0,0.012586,0.015507,pass
8,0.0,0.0,0.013752,0.0,6.886235e-19,0.0,0.005223,0.006054,0.0,0.007217,0.008758,pass
9,0.0,0.0,0.026821,0.0,9.960072e-19,0.0,0.011839,0.013821,0.0,0.012056,0.013045,pass
10,0.0,0.0,0.024136,0.0,9.180142e-19,0.0,0.013263,0.011975,0.0,0.008935,0.014496,pass
11,0.0,0.0,0.019315,0.0,8.731798e-19,0.0,0.009412,0.007981,0.0,0.012322,0.012067,pass
12,0.0,0.0,0.020033,0.0,9.342588e-19,0.0,0.011042,0.017694,0.0,0.009609,0.013973,pass
13,0.0,0.0,0.024713,0.0,9.898376e-19,0.0,0.009584,0.014407,0.0,0.011290,0.011130,pass
14,0.0,0.0,0.015602,0.0,6.837490e-19,0.0,0.006690,0.006676,0.0,0.006207,0.009232,pass

[[       nan        nan 1.09597475        nan 1.0845467         nan
  1.25324039 1.16514839        nan 1.19901644 1.20129449]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 3,tdg 6,h 4,h 8,h 1,h 0,cz 10,cz 9,cz 7,cz 5,cz 2
sum,0.365741,0.343907,0.3277,0.322069,0.31934,0.305984,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 3,tdg 6,h 4,h 1,h 8,h 0,cz 10,cz 9,cz 7,cz 5,cz 2
sum,0.472277,0.437153,0.430371,0.415063,0.410314,0.397878,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 3,h 0,h 4,h 1,tdg 6,cz 10,cz 9,cz 7,cz 5,cz 2
sum,0.001925,0.000815,0.000555,0.000437,0.000392,4.236346e-36,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
6
Now evolving the following mutant:  AddGate_h_inGap_7_.qasm

100%|██████████| 10/10 [00:00<00:00, 13.50it/s]
100%|██████████| 10/10 [00:00<00:00, 15.24it/s]

,cz 10,cz 9,h 8,cz 7,h 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.029364,0.0,0.029383,0.087590,0.017913,0.020516,0.0,0.012545,0.020471,fail
1,0.0,0.0,0.017811,0.0,0.020273,0.067425,0.013549,0.013269,0.0,0.009094,0.013685,fail
2,0.0,0.0,0.012126,0.0,0.015240,0.055979,0.009665,0.012353,0.0,0.007924,0.009190,fail
3,0.0,0.0,0.027280,0.0,0.016193,0.050136,0.010515,0.018995,0.0,0.009813,0.014204,fail
4,0.0,0.0,0.018719,0.0,0.017311,0.052245,0.010287,0.014557,0.0,0.010670,0.017816,fail
5,0.0,0.0,0.028643,0.0,0.024640,0.068997,0.016593,0.016292,0.0,0.008822,0.016416,fail
6,0.0,0.0,0.034648,0.0,0.029275,0.087727,0.018172,0.018653,0.0,0.015494,0.016050,fail
7,0.0,0.0,0.017530,0.0,0.017320,0.052045,0.012008,0.012888,0.0,0.007898,0.014157,fail
8,0.0,0.0,0.027565,0.0,0.023385,0.071716,0.013625,0.019477,0.0,0.015018,0.019143,fail
9,0.0,0.0,0.021713,0.0,0.016292,0.055516,0.010178,0.015317,0.0,0.012590,0.015326,fail
10,0.0,0.0,0.023977,0.0,0.019142,0.059469,0.011188,0.017114,0.0,0.014934,0.021294,pass
11,0.0,0.0,0.025534,0.0,0.019235,0.053288,0.012258,0.018651,0.0,0.012081,0.017152,pass
12,0.0,0.0,0.022010,0.0,0.018938,0.064682,0.012808,0.009447,0.0,0.010262,0.011999,pass
13,0.0,0.0,0.023344,0.0,0.016380,0.049091,0.010230,0.017968,0.0,0.008764,0.015417,pass
14,0.0,0.0,0.012914,0.0,0.015261,0.039051,0.010700,0.015079,0.0,0.007186,0.019042,pass
15,0.0,0.0,0.033453,0.0,0.022599,0.060932,0.014455,0.020178,0.0,0.010652,0.017727,pass
16,0.0,0.0,0.018994,0.0,0.010563,0.038172,0.007329,0.013555,0.0,0.008869,0.013605,pass
17,0.0,0.0,0.021983,0.0,0.023473,0.060983,0.013210,0.015551,0.0,0.010831,0.020021,pass
18,0.0,0.0,0.020104,0.0,0.017895,0.046770,0.010774,0.019343,0.0,0.010099,0.018602,pass
19,0.0,0.0,0.018995,0.0,0.019469,0.058669,0.013162,0.016794,0.0,0.008631,0.017594,pass

[[       nan        nan 1.4718878         nan 1.40380798 1.35094593
  1.37140429 1.26396005        nan 1.41026627 1.30842403]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,cz 5,h 6,h 4,h 1,h 8,h 3,h 0,cz 10,cz 9,cz 7,cz 2
sum,0.550095,0.533597,0.53297,0.517811,0.515425,0.497908,0.475684,0.0,0.0,0.0,0.0

custom SCORES

,cz 5,h 6,h 4,h 8,h 1,h 3,h 0,cz 10,cz 9,cz 7,cz 2
sum,0.735882,0.720864,0.715699,0.705087,0.700374,0.655243,0.631284,0.0,0.0,0.0,0.0

DSTAR SCORES

,cz 5,h 8,h 6,h 3,h 0,h 4,h 1,cz 10,cz 9,cz 7,cz 2
sum,0.040043,0.005421,0.004302,0.002592,0.002406,0.001736,0.001195,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
6
Now evolving the following mutant:  AddGate_h_inGap_12_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.47it/s]
100%|██████████| 10/10 [00:00<00:00, 12.19it/s]

,cz 10,cz 9,h 8,cz 7,h 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.030646,0.0,0.026045,0.076097,0.024505,0.035036,0.120034,0.037134,0.017786,fail
1,0.0,0.0,0.023461,0.0,0.019237,0.063324,0.027107,0.027429,0.090547,0.023643,0.021317,fail
2,0.0,0.0,0.019495,0.0,0.017531,0.053629,0.017316,0.029389,0.085670,0.022421,0.022778,fail
3,0.0,0.0,0.024262,0.0,0.023089,0.072212,0.018762,0.024553,0.117250,0.024309,0.027392,fail
4,0.0,0.0,0.025166,0.0,0.021339,0.067443,0.019864,0.023355,0.100252,0.025076,0.022795,fail
5,0.0,0.0,0.027487,0.0,0.025781,0.071543,0.026372,0.031698,0.115394,0.031477,0.024413,fail
6,0.0,0.0,0.022643,0.0,0.015585,0.051856,0.018296,0.021697,0.073112,0.019290,0.017732,fail
7,0.0,0.0,0.021347,0.0,0.018906,0.064917,0.017894,0.035246,0.102235,0.025674,0.024941,fail
8,0.0,0.0,0.026369,0.0,0.029462,0.094918,0.019214,0.036615,0.145740,0.034974,0.030691,fail
9,0.0,0.0,0.025989,0.0,0.024549,0.073928,0.025762,0.024752,0.113790,0.029548,0.023127,fail
10,0.0,0.0,0.024378,0.0,0.025325,0.074566,0.022950,0.029896,0.116318,0.031525,0.026467,pass
11,0.0,0.0,0.019103,0.0,0.015403,0.045759,0.011378,0.020114,0.069766,0.019076,0.014849,pass
12,0.0,0.0,0.020273,0.0,0.014014,0.035294,0.009771,0.021375,0.056046,0.019450,0.009948,pass
13,0.0,0.0,0.018667,0.0,0.018831,0.062967,0.021047,0.030878,0.090566,0.026744,0.018653,pass
14,0.0,0.0,0.030652,0.0,0.020058,0.055649,0.017622,0.030722,0.078711,0.025417,0.017481,pass
15,0.0,0.0,0.019418,0.0,0.019619,0.062606,0.020085,0.024605,0.093643,0.022739,0.024134,pass
16,0.0,0.0,0.026361,0.0,0.024083,0.068871,0.025304,0.043621,0.112558,0.032570,0.026108,pass
17,0.0,0.0,0.021078,0.0,0.023246,0.070023,0.019779,0.023988,0.100918,0.026354,0.020013,pass
18,0.0,0.0,0.021539,0.0,0.017500,0.043447,0.015821,0.020377,0.074156,0.020505,0.020620,pass
19,0.0,0.0,0.018679,0.0,0.010578,0.040374,0.020428,0.024837,0.062558,0.014539,0.017353,pass

[[       nan        nan 1.24140622        nan 1.32996428 1.3758913
  1.2602513  1.26358803 1.36970235 1.35749874 1.31737078]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,cz 2,cz 5,h 0,h 6,h 4,h 1,h 8,h 3,cz 10,cz 9,cz 7
sum,0.554392,0.552149,0.543565,0.540062,0.538704,0.533787,0.5286,0.517276,0.0,0.0,0.0

custom SCORES

,cz 2,cz 5,h 0,h 6,h 1,h 4,h 8,h 3,cz 10,cz 9,cz 7
sum,0.74423,0.742073,0.722584,0.719628,0.71494,0.70843,0.692652,0.680681,0.0,0.0,0.0

DSTAR SCORES

,cz 2,cz 5,h 3,h 1,h 8,h 0,h 6,h 4,cz 10,cz 9,cz 7
sum,0.104295,0.04507,0.008175,0.007308,0.005963,0.005323,0.004816,0.004543,0.0,0.0,0.0

ERROR GATE LOCATION:
6
Now evolving the following mutant:  AddGate_rz_inGap_4_.qasm

100%|██████████| 4/4 [00:00<00:00, 18.74it/s]
100%|██████████| 10/10 [00:00<00:00, 16.65it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,rz 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.028155,0.0,0.0,0.010274,0.015656,0.013981,0.0,0.011894,0.013338,fail
1,0.0,0.0,0.026499,0.0,0.0,0.011643,0.022334,0.019484,0.0,0.009730,0.011920,fail
2,0.0,0.0,0.023952,0.0,0.0,0.013934,0.016291,0.014522,0.0,0.011089,0.012539,fail
3,0.0,0.0,0.030354,0.0,0.0,0.009355,0.016939,0.015070,0.0,0.013874,0.010441,fail
4,0.0,0.0,0.020045,0.0,0.0,0.007819,0.010867,0.009604,0.0,0.007244,0.008288,pass
5,0.0,0.0,0.009923,0.0,0.0,0.006148,0.007256,0.006534,0.0,0.002884,0.007492,pass
6,0.0,0.0,0.031286,0.0,0.0,0.011085,0.012877,0.011472,0.0,0.010842,0.010188,pass
7,0.0,0.0,0.026375,0.0,0.0,0.011136,0.016332,0.014348,0.0,0.009805,0.013182,pass
8,0.0,0.0,0.009102,0.0,0.0,0.004651,0.005875,0.005154,0.0,0.004531,0.006666,pass
9,0.0,0.0,0.026889,0.0,0.0,0.010642,0.009751,0.008533,0.0,0.010464,0.012214,pass
10,0.0,0.0,0.028125,0.0,0.0,0.013502,0.014361,0.012590,0.0,0.006516,0.012890,pass
11,0.0,0.0,0.016086,0.0,0.0,0.006847,0.010784,0.009658,0.0,0.006894,0.012173,pass
12,0.0,0.0,0.018687,0.0,0.0,0.008046,0.009627,0.008564,0.0,0.007366,0.008970,pass
13,0.0,0.0,0.021130,0.0,0.0,0.008881,0.015356,0.013684,0.0,0.010165,0.013613,pass

[[       nan        nan 1.11432527        nan        nan 1.23291263
  1.25439271 1.23594127        nan 1.19119652 1.10598593]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 4,rz 3,h 1,h 8,h 5,h 0,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.386422,0.386389,0.377847,0.344147,0.337449,0.313413,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 4,rz 3,h 1,h 5,h 8,h 0,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.507603,0.505778,0.490369,0.44146,0.44002,0.400071,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 4,rz 3,h 0,h 1,h 5,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.002822,0.001233,0.00097,0.000567,0.000532,0.0005,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
3
Now evolving the following mutant:  AddGate_sx_inGap_9_.qasm

100%|██████████| 3/3 [00:00<00:00, 12.79it/s]
100%|██████████| 10/10 [00:00<00:00, 16.02it/s]

,cz 10,cz 9,sxdg 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.152211,0.126843,0.0,0.0,0.008460,0.015100,0.0,0.010117,0.010724,fail
1,0.0,0.0,0.147530,0.122942,0.0,0.0,0.011251,0.014862,0.0,0.009909,0.012938,fail
2,0.0,0.0,0.180067,0.150056,0.0,0.0,0.010703,0.014585,0.0,0.011170,0.014778,fail
3,0.0,0.0,0.128147,0.106789,0.0,0.0,0.009246,0.011924,0.0,0.006014,0.008971,pass
4,0.0,0.0,0.127467,0.106222,0.0,0.0,0.004234,0.011814,0.0,0.004721,0.010661,pass
5,0.0,0.0,0.164397,0.136997,0.0,0.0,0.009889,0.013252,0.0,0.008826,0.012727,pass
6,0.0,0.0,0.110203,0.091836,0.0,0.0,0.008838,0.010472,0.0,0.010732,0.011018,pass
7,0.0,0.0,0.160199,0.133499,0.0,0.0,0.012282,0.016986,0.0,0.012817,0.011990,pass
8,0.0,0.0,0.124980,0.104150,0.0,0.0,0.009196,0.013997,0.0,0.010188,0.011932,pass
9,0.0,0.0,0.126215,0.105179,0.0,0.0,0.010718,0.010345,0.0,0.007978,0.008884,pass
10,0.0,0.0,0.094693,0.078911,0.0,0.0,0.009637,0.012519,0.0,0.006693,0.007919,pass
11,0.0,0.0,0.162209,0.135174,0.0,0.0,0.010092,0.013560,0.0,0.012119,0.012575,pass
12,0.0,0.0,0.149031,0.124192,0.0,0.0,0.014487,0.012647,0.0,0.011424,0.014712,pass

[[       nan        nan 1.12586689 1.12586689        nan        nan
  1.10984286 1.01693064        nan 1.07414744 1.1533392 ]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,sxdg 8,h 7,h 3,h 0,h 1,h 4,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.262571,0.262571,0.258898,0.25656,0.254233,0.235703,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 7,sxdg 8,h 0,h 3,h 1,h 4,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.336476,0.336476,0.330535,0.324719,0.322503,0.301102,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,sxdg 8,h 7,h 3,h 0,h 1,h 4,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.052953,0.038776,0.000635,0.000475,0.000315,0.000299,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_sx_inGap_5_.qasm

100%|██████████| 3/3 [00:00<00:00, 15.63it/s]
100%|██████████| 10/10 [00:00<00:00, 15.43it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,sxdg 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.023651,0.0,0.0,0.012505,0.0,0.016487,0.0,0.009930,0.007942,fail
1,0.0,0.0,0.033955,0.0,0.0,0.016246,0.0,0.016941,0.0,0.013317,0.021627,fail
2,0.0,0.0,0.026515,0.0,0.0,0.011371,0.0,0.019864,0.0,0.012850,0.008551,fail
3,0.0,0.0,0.018174,0.0,0.0,0.005980,0.0,0.008131,0.0,0.006731,0.007472,pass
4,0.0,0.0,0.027067,0.0,0.0,0.010142,0.0,0.009789,0.0,0.007786,0.013449,pass
5,0.0,0.0,0.014586,0.0,0.0,0.007563,0.0,0.011989,0.0,0.008412,0.010370,pass
6,0.0,0.0,0.025170,0.0,0.0,0.015113,0.0,0.016181,0.0,0.012835,0.011182,pass
7,0.0,0.0,0.022337,0.0,0.0,0.011346,0.0,0.007813,0.0,0.009407,0.009549,pass
8,0.0,0.0,0.016990,0.0,0.0,0.010731,0.0,0.016542,0.0,0.010928,0.013805,pass
9,0.0,0.0,0.025612,0.0,0.0,0.009877,0.0,0.017195,0.0,0.012004,0.015957,pass
10,0.0,0.0,0.021672,0.0,0.0,0.009522,0.0,0.009095,0.0,0.009096,0.010496,pass
11,0.0,0.0,0.014798,0.0,0.0,0.007571,0.0,0.012056,0.0,0.008326,0.009389,pass
12,0.0,0.0,0.023369,0.0,0.0,0.010416,0.0,0.014892,0.0,0.010675,0.009982,pass

[[       nan        nan 1.21093314        nan        nan 1.21477665
         nan 1.11821549        nan 1.10674727 1.70201764]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 3,h 5,h 8,h 1,h 0,cz 10,cz 9,cz 7,cz 6,sxdg 4,cz 2
sum,0.30113,0.289933,0.286227,0.27285,0.254525,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 3,h 5,h 8,h 0,h 1,cz 10,cz 9,cz 7,cz 6,sxdg 4,cz 2
sum,0.385312,0.377983,0.372877,0.362826,0.348344,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 3,h 5,h 0,h 1,cz 10,cz 9,cz 7,cz 6,sxdg 4,cz 2
sum,0.002205,0.000909,0.00052,0.000467,0.000421,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_p_inGap_14_.qasm

100%|██████████| 5/5 [00:00<00:00, 14.35it/s]
100%|██████████| 10/10 [00:00<00:00, 16.57it/s]

,cz 10,cz 9,h 8,p 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.029423,0.0,0.0,0.0,0.013185,0.021187,0.0,0.015387,0.016275,fail
1,0.0,0.0,0.028379,0.0,0.0,0.0,0.010268,0.016103,0.0,0.013449,0.015972,fail
2,0.0,0.0,0.023348,0.0,0.0,0.0,0.016852,0.019486,0.0,0.013517,0.014529,fail
3,0.0,0.0,0.028172,0.0,0.0,0.0,0.012275,0.016570,0.0,0.013144,0.011450,fail
4,0.0,0.0,0.020497,0.0,0.0,0.0,0.011626,0.014859,0.0,0.012985,0.014728,fail
5,0.0,0.0,0.025028,0.0,0.0,0.0,0.010141,0.016593,0.0,0.008246,0.014062,pass
6,0.0,0.0,0.023388,0.0,0.0,0.0,0.009956,0.017475,0.0,0.008852,0.011924,pass
7,0.0,0.0,0.025917,0.0,0.0,0.0,0.010215,0.013526,0.0,0.013914,0.015419,pass
8,0.0,0.0,0.032249,0.0,0.0,0.0,0.012217,0.020302,0.0,0.011143,0.010438,pass
9,0.0,0.0,0.018210,0.0,0.0,0.0,0.010561,0.017866,0.0,0.011376,0.014608,pass
10,0.0,0.0,0.028260,0.0,0.0,0.0,0.012878,0.018682,0.0,0.011588,0.017047,pass
11,0.0,0.0,0.018825,0.0,0.0,0.0,0.010742,0.012626,0.0,0.014132,0.012774,pass
12,0.0,0.0,0.013475,0.0,0.0,0.0,0.009143,0.009902,0.0,0.011008,0.011224,pass
13,0.0,0.0,0.026436,0.0,0.0,0.0,0.016440,0.017760,0.0,0.013905,0.017226,pass
14,0.0,0.0,0.025561,0.0,0.0,0.0,0.009850,0.010238,0.0,0.006913,0.010291,pass

[[       nan        nan 1.13322173        nan        nan        nan
  1.31231207 1.20102068        nan 1.12345662 1.1154324 ]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,h 4,h 3,h 8,h 0,cz 10,cz 9,p 7,cz 6,cz 5,cz 2
sum,0.381391,0.364082,0.362721,0.353566,0.350791,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 1,h 4,h 3,h 8,h 0,cz 10,cz 9,p 7,cz 6,cz 5,cz 2
sum,0.48851,0.48353,0.471629,0.453733,0.448611,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 3,h 0,h 1,h 4,cz 10,cz 9,p 7,cz 6,cz 5,cz 2
sum,0.003218,0.001509,0.001036,0.000918,0.000806,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
7
Now evolving the following mutant:  AddGate_t_inGap_10_.qasm

100%|██████████| 4/4 [00:00<00:00, 14.57it/s]
100%|██████████| 10/10 [00:00<00:00, 16.96it/s]

,cz 10,tdg 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,2.903198e-18,0.0,0.024166,0.0,0.0,0.011620,0.015540,0.0,0.009103,0.013136,fail
1,0.0,3.061351e-18,0.0,0.020356,0.0,0.0,0.011826,0.018802,0.0,0.008545,0.010338,fail
2,0.0,2.678908e-18,0.0,0.025987,0.0,0.0,0.010128,0.014844,0.0,0.008147,0.007654,fail
3,0.0,3.160216e-18,0.0,0.027554,0.0,0.0,0.014659,0.020619,0.0,0.009477,0.015597,fail
4,0.0,2.999883e-18,0.0,0.017187,0.0,0.0,0.009719,0.011993,0.0,0.009205,0.008323,pass
5,0.0,2.390428e-18,0.0,0.012464,0.0,0.0,0.008785,0.008550,0.0,0.008848,0.008948,pass
6,0.0,3.104671e-18,0.0,0.021850,0.0,0.0,0.011104,0.018119,0.0,0.011072,0.015815,pass
7,0.0,2.034929e-18,0.0,0.016109,0.0,0.0,0.006650,0.011432,0.0,0.007182,0.005710,pass
8,0.0,2.553134e-18,0.0,0.022504,0.0,0.0,0.013474,0.013778,0.0,0.010388,0.011280,pass
9,0.0,2.674072e-18,0.0,0.023984,0.0,0.0,0.012020,0.016731,0.0,0.009341,0.012214,pass
10,0.0,2.395642e-18,0.0,0.017376,0.0,0.0,0.008596,0.009598,0.0,0.008856,0.011375,pass
11,0.0,3.257567e-18,0.0,0.023529,0.0,0.0,0.007827,0.009279,0.0,0.010521,0.008749,pass
12,0.0,2.373499e-18,0.0,0.017555,0.0,0.0,0.013468,0.015322,0.0,0.012339,0.011855,pass
13,0.0,3.213192e-18,0.0,0.023590,0.0,0.0,0.010878,0.015506,0.0,0.014755,0.011883,pass

[[       nan 1.07092629        nan 1.12393446        nan        nan
  1.21569599 1.18154186        nan 1.07476303 1.33522463]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 3,h 7,h 4,h 0,tdg 9,h 1,cz 10,cz 8,cz 6,cz 5,cz 2
sum,0.348829,0.333308,0.319946,0.305635,0.304213,0.256004,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 3,h 7,h 4,h 0,tdg 9,h 1,cz 10,cz 8,cz 6,cz 5,cz 2
sum,0.451868,0.426962,0.417186,0.407657,0.38566,0.324791,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 7,h 3,h 4,h 0,h 1,tdg 9,cz 10,cz 8,cz 6,cz 5,cz 2
sum,0.002292,0.00118,0.000567,0.000532,0.000303,3.483168e-35,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
9
Now evolving the following mutant:  AddGate_cswap_inGap_2_.qasm

100%|██████████| 5/5 [00:00<00:00, 12.09it/s]
100%|██████████| 10/10 [00:00<00:00, 13.13it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,h 2,cswap 1,h 0,pass/fail
0,0.0,0.0,0.025600,0.0,0.0,0.010808,0.017086,0.0,0.010702,0.030966,0.010430,fail
1,0.0,0.0,0.021707,0.0,0.0,0.010450,0.016128,0.0,0.014259,0.030743,0.006813,fail
2,0.0,0.0,0.021626,0.0,0.0,0.010373,0.017386,0.0,0.008663,0.026466,0.007815,fail
3,0.0,0.0,0.024637,0.0,0.0,0.011612,0.017287,0.0,0.011398,0.033249,0.007015,fail
4,0.0,0.0,0.031494,0.0,0.0,0.012219,0.014866,0.0,0.010238,0.030509,0.009898,fail
5,0.0,0.0,0.028627,0.0,0.0,0.013057,0.012084,0.0,0.011949,0.037275,0.010406,pass
6,0.0,0.0,0.025812,0.0,0.0,0.009203,0.014353,0.0,0.009559,0.040342,0.009080,pass
7,0.0,0.0,0.027198,0.0,0.0,0.012190,0.019729,0.0,0.012248,0.028936,0.010452,pass
8,0.0,0.0,0.026161,0.0,0.0,0.013954,0.018397,0.0,0.011384,0.028592,0.008995,pass
9,0.0,0.0,0.014731,0.0,0.0,0.008338,0.008812,0.0,0.005599,0.026898,0.005801,pass
10,0.0,0.0,0.016169,0.0,0.0,0.008500,0.012566,0.0,0.008941,0.021674,0.005678,pass
11,0.0,0.0,0.023297,0.0,0.0,0.009173,0.013529,0.0,0.010265,0.033121,0.006600,pass
12,0.0,0.0,0.022481,0.0,0.0,0.009404,0.016802,0.0,0.010875,0.025690,0.008218,pass
13,0.0,0.0,0.011564,0.0,0.0,0.009059,0.015497,0.0,0.009370,0.034186,0.007544,pass
14,0.0,0.0,0.023208,0.0,0.0,0.014510,0.017873,0.0,0.010764,0.031624,0.011809,pass

[[       nan        nan 1.25911964        nan        nan 1.10155347
  1.05046914        nan 1.29017523 1.09421466 1.24250348]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 8,h 4,h 2,h 5,h 0,cswap 1,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.363228,0.356086,0.353745,0.340572,0.33165,0.330093,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 8,h 2,h 4,h 0,h 5,cswap 1,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.477564,0.467843,0.4496,0.434669,0.434361,0.420391,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,cswap 1,h 8,h 4,h 5,h 2,h 0,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.004349,0.002997,0.00133,0.000602,0.000599,0.000346,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_ccx_inGap_14_.qasm

100%|██████████| 7/7 [00:02<00:00,  2.82it/s]
100%|██████████| 10/10 [00:03<00:00,  2.87it/s]

,ccx 10,cz 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.573166,0.0,0.0,0.019604,0.031753,0.043050,0.015047,0.013646,0.0,0.008381,0.011363,fail
1,0.687748,0.0,0.0,0.023536,0.043266,0.051426,0.017402,0.016360,0.0,0.010463,0.016514,fail
2,0.683085,0.0,0.0,0.024536,0.051932,0.081734,0.018214,0.017297,0.0,0.012255,0.015593,fail
3,0.719560,0.0,0.0,0.024999,0.047464,0.059547,0.019014,0.019417,0.0,0.012363,0.016362,fail
4,0.658035,0.0,0.0,0.021316,0.031543,0.048141,0.018145,0.017319,0.0,0.012580,0.017595,fail
5,0.694759,0.0,0.0,0.024530,0.046449,0.069365,0.019042,0.018750,0.0,0.012336,0.015545,fail
6,0.644977,0.0,0.0,0.022512,0.035574,0.052153,0.017651,0.016862,0.0,0.012799,0.019125,fail
7,0.534600,0.0,0.0,0.019359,0.034821,0.050546,0.013591,0.012310,0.0,0.010141,0.011551,pass
8,0.468937,0.0,0.0,0.017012,0.033071,0.047919,0.012797,0.011886,0.0,0.009648,0.015169,pass
9,0.559665,0.0,0.0,0.020141,0.039949,0.054732,0.013941,0.014593,0.0,0.010559,0.010606,pass
10,0.659533,0.0,0.0,0.020315,0.030988,0.039290,0.018237,0.015598,0.0,0.010505,0.014010,pass
11,0.626216,0.0,0.0,0.020505,0.041678,0.053491,0.016514,0.016173,0.0,0.009393,0.013978,pass
12,0.616911,0.0,0.0,0.021361,0.035419,0.049119,0.015922,0.016539,0.0,0.011965,0.014766,pass
13,0.433533,0.0,0.0,0.014189,0.026036,0.035033,0.011453,0.010829,0.0,0.007230,0.010873,pass
14,0.611863,0.0,0.0,0.021050,0.048943,0.071344,0.015254,0.014883,0.0,0.009061,0.010195,pass
15,0.553317,0.0,0.0,0.018831,0.026974,0.041873,0.014954,0.013037,0.0,0.010155,0.010276,pass
16,0.671806,0.0,0.0,0.021718,0.048709,0.069045,0.017948,0.014597,0.0,0.012430,0.015180,pass

[[1.08057618        nan        nan 1.08670002 1.26232787 1.41123706
  1.0705172  1.13595056        nan 1.10364465 1.1942805 ]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 0,h 3,h 7,h 4,ccx 10,h 1,cz 5,cz 6,cz 9,cz 8,cz 2
sum,0.469615,0.460026,0.452958,0.452577,0.448303,0.445382,0.441721,0.439954,0.0,0.0,0.0

custom SCORES

,h 0,cz 5,h 3,cz 6,h 7,h 4,ccx 10,h 1,cz 9,cz 8,cz 2
sum,0.609828,0.597564,0.590668,0.578796,0.576016,0.5737,0.56941,0.568267,0.0,0.0,0.0

DSTAR SCORES

,ccx 10,cz 5,cz 6,h 7,h 4,h 3,h 0,h 1,cz 9,cz 8,cz 2
sum,1.705979,0.021879,0.011258,0.003604,0.002168,0.002005,0.001763,0.000928,0.0,0.0,0.0

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_cswap_inGap_5_.qasm

100%|██████████| 4/4 [00:00<00:00,  8.27it/s]
100%|██████████| 10/10 [00:01<00:00,  8.45it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,cswap 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.021713,0.0,0.0,0.014165,0.048132,0.015747,0.0,0.006397,0.009603,fail
1,0.0,0.0,0.017272,0.0,0.0,0.011271,0.037056,0.013053,0.0,0.008761,0.007708,fail
2,0.0,0.0,0.023583,0.0,0.0,0.008010,0.045889,0.013889,0.0,0.004587,0.008965,fail
3,0.0,0.0,0.021057,0.0,0.0,0.009726,0.045998,0.014659,0.0,0.007022,0.008472,fail
4,0.0,0.0,0.027005,0.0,0.0,0.013339,0.053545,0.016098,0.0,0.007237,0.009576,pass
5,0.0,0.0,0.023778,0.0,0.0,0.012931,0.043528,0.014215,0.0,0.007386,0.007327,pass
6,0.0,0.0,0.018500,0.0,0.0,0.009899,0.045701,0.014654,0.0,0.007375,0.009896,pass
7,0.0,0.0,0.022398,0.0,0.0,0.010561,0.057711,0.014977,0.0,0.007121,0.009089,pass
8,0.0,0.0,0.015092,0.0,0.0,0.006484,0.033655,0.008359,0.0,0.002460,0.004581,pass
9,0.0,0.0,0.017341,0.0,0.0,0.008541,0.042228,0.012013,0.0,0.006210,0.008947,pass
10,0.0,0.0,0.021029,0.0,0.0,0.010091,0.029917,0.012842,0.0,0.004785,0.005323,pass
11,0.0,0.0,0.022742,0.0,0.0,0.010745,0.052243,0.014939,0.0,0.006561,0.007897,pass
12,0.0,0.0,0.025567,0.0,0.0,0.013902,0.034214,0.013507,0.0,0.006429,0.008719,pass
13,0.0,0.0,0.020261,0.0,0.0,0.012239,0.055782,0.016538,0.0,0.006672,0.009541,pass

[[       nan        nan 1.1280527         nan        nan 1.31244406
  1.08725978 1.09836879        nan 1.30920082 1.10543341]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,h 0,h 3,h 5,cswap 4,h 8,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.300745,0.300471,0.293353,0.284206,0.283049,0.281243,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 1,h 0,h 5,h 3,h 8,cswap 4,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.399179,0.383508,0.377457,0.373905,0.360557,0.359986,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,cswap 4,h 8,h 3,h 5,h 0,h 1,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.007049,0.00166,0.000795,0.000454,0.000296,0.000176,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_ry_inGap_8_.qasm

100%|██████████| 10/10 [00:00<00:00, 15.59it/s]
100%|██████████| 10/10 [00:00<00:00, 16.84it/s]

,cz 10,cz 9,h 8,ry 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.025449,0.127246,0.0,0.0,0.009470,0.013391,0.0,0.010765,0.010654,fail
1,0.0,0.0,0.023582,0.117908,0.0,0.0,0.006696,0.011713,0.0,0.009670,0.006697,fail
2,0.0,0.0,0.018858,0.094289,0.0,0.0,0.007707,0.014972,0.0,0.009262,0.013080,fail
3,0.0,0.0,0.022133,0.110666,0.0,0.0,0.007645,0.011695,0.0,0.007465,0.010314,fail
4,0.0,0.0,0.030458,0.152288,0.0,0.0,0.009593,0.008689,0.0,0.006832,0.012183,fail
5,0.0,0.0,0.025077,0.125385,0.0,0.0,0.007823,0.011132,0.0,0.008789,0.012870,fail
6,0.0,0.0,0.022637,0.113183,0.0,0.0,0.006998,0.009649,0.0,0.004394,0.011354,fail
7,0.0,0.0,0.028535,0.142676,0.0,0.0,0.008438,0.010379,0.0,0.010529,0.013376,fail
8,0.0,0.0,0.027684,0.138421,0.0,0.0,0.007969,0.010676,0.0,0.009237,0.012969,fail
9,0.0,0.0,0.028304,0.141521,0.0,0.0,0.005048,0.007998,0.0,0.005256,0.005245,fail
10,0.0,0.0,0.015836,0.079180,0.0,0.0,0.006009,0.007791,0.0,0.006298,0.008690,pass
11,0.0,0.0,0.013237,0.066183,0.0,0.0,0.006158,0.010423,0.0,0.008046,0.010841,pass
12,0.0,0.0,0.011403,0.057016,0.0,0.0,0.007058,0.012325,0.0,0.009334,0.014398,pass
13,0.0,0.0,0.026125,0.130624,0.0,0.0,0.007314,0.010949,0.0,0.009576,0.011841,pass
14,0.0,0.0,0.016188,0.080939,0.0,0.0,0.007239,0.010729,0.0,0.008788,0.011071,pass
15,0.0,0.0,0.020894,0.104472,0.0,0.0,0.005996,0.011137,0.0,0.009075,0.006205,pass
16,0.0,0.0,0.019804,0.099019,0.0,0.0,0.005747,0.011242,0.0,0.008272,0.008974,pass
17,0.0,0.0,0.020583,0.102914,0.0,0.0,0.010804,0.013059,0.0,0.014118,0.015117,pass
18,0.0,0.0,0.013925,0.069624,0.0,0.0,0.002876,0.005829,0.0,0.004375,0.007047,pass
19,0.0,0.0,0.023906,0.119528,0.0,0.0,0.009334,0.013798,0.0,0.009428,0.009511,pass

[[       nan        nan 1.20520485 1.20520485        nan        nan
  1.23965124 1.35743858        nan 1.30961284 1.23003529]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 8,ry 7,h 4,h 0,h 3,h 1,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.58147,0.58147,0.530335,0.51188,0.50692,0.484926,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 8,ry 7,h 4,h 3,h 0,h 1,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.756668,0.756668,0.694692,0.678948,0.669287,0.643693,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,ry 7,h 8,h 3,h 0,h 1,h 4,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.146353,0.006272,0.001204,0.00117,0.00067,0.000595,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
7
Now evolving the following mutant:  AddGate_p_inGap_4_.qasm

100%|██████████| 3/3 [00:00<00:00, 16.47it/s]
100%|██████████| 10/10 [00:00<00:00, 15.55it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,p 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.022273,0.0,0.0,0.015043,0.014504,0.013073,0.0,0.009518,0.014425,fail
1,0.0,0.0,0.018587,0.0,0.0,0.010572,0.015358,0.013569,0.0,0.007956,0.010424,fail
2,0.0,0.0,0.026732,0.0,0.0,0.009941,0.012313,0.011123,0.0,0.007275,0.012557,fail
3,0.0,0.0,0.025742,0.0,0.0,0.012325,0.015676,0.013822,0.0,0.011405,0.012808,pass
4,0.0,0.0,0.021560,0.0,0.0,0.007754,0.017357,0.015403,0.0,0.006569,0.011603,pass
5,0.0,0.0,0.028589,0.0,0.0,0.012632,0.019541,0.017198,0.0,0.013106,0.009655,pass
6,0.0,0.0,0.026800,0.0,0.0,0.015594,0.017651,0.015643,0.0,0.008884,0.014862,pass
7,0.0,0.0,0.019861,0.0,0.0,0.009027,0.010518,0.009314,0.0,0.011160,0.010737,pass
8,0.0,0.0,0.025834,0.0,0.0,0.010647,0.016740,0.014756,0.0,0.009965,0.013117,pass
9,0.0,0.0,0.019377,0.0,0.0,0.009355,0.011303,0.010195,0.0,0.008754,0.009890,pass
10,0.0,0.0,0.022014,0.0,0.0,0.007427,0.013988,0.012409,0.0,0.006730,0.009175,pass
11,0.0,0.0,0.023392,0.0,0.0,0.010886,0.009381,0.008530,0.0,0.012305,0.013237,pass
12,0.0,0.0,0.029878,0.0,0.0,0.013540,0.019754,0.017417,0.0,0.010014,0.012379,pass

[[       nan        nan 1.18649664        nan        nan 1.26923518
  1.09245166 1.07789196        nan 1.15370174 1.15690926]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 5,h 0,p 3,h 8,h 4,h 1,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.245652,0.241532,0.218988,0.21759,0.217305,0.200165,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 5,h 0,h 8,p 3,h 4,h 1,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.3236,0.311389,0.282132,0.278,0.276654,0.257897,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 4,p 3,h 0,h 5,h 1,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.001409,0.000564,0.000455,0.000449,0.000407,0.000198,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
3
Now evolving the following mutant:  AddGate_h_inGap_14_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.92it/s]
100%|██████████| 10/10 [00:01<00:00,  9.11it/s]

,cz 10,cz 9,h 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.026291,0.032363,0.090787,0.152925,0.030572,0.023098,0.0,0.018928,0.023615,fail
1,0.0,0.0,0.026885,0.044305,0.122856,0.191302,0.038768,0.033096,0.0,0.020805,0.031652,fail
2,0.0,0.0,0.018820,0.040680,0.114167,0.157250,0.025336,0.023120,0.0,0.021960,0.021310,fail
3,0.0,0.0,0.027106,0.032933,0.082861,0.125067,0.023321,0.016055,0.0,0.019338,0.021278,fail
4,0.0,0.0,0.025014,0.040263,0.113191,0.162797,0.031548,0.031693,0.0,0.019979,0.031650,fail
5,0.0,0.0,0.027391,0.042009,0.117285,0.174356,0.039561,0.025878,0.0,0.019239,0.032025,fail
6,0.0,0.0,0.027282,0.039355,0.093326,0.130867,0.028716,0.026672,0.0,0.013664,0.024443,fail
7,0.0,0.0,0.020952,0.047963,0.126648,0.179308,0.036671,0.027624,0.0,0.019264,0.033057,fail
8,0.0,0.0,0.023979,0.019976,0.047276,0.060550,0.013988,0.024658,0.0,0.008831,0.012780,fail
9,0.0,0.0,0.023025,0.047628,0.125559,0.188677,0.038296,0.025375,0.0,0.020179,0.025280,fail
10,0.0,0.0,0.028450,0.053328,0.142844,0.198320,0.041339,0.030824,0.0,0.025352,0.035268,pass
11,0.0,0.0,0.025562,0.029851,0.086399,0.111390,0.020127,0.030419,0.0,0.017921,0.022963,pass
12,0.0,0.0,0.019802,0.028695,0.075027,0.088188,0.016678,0.019195,0.0,0.015135,0.024065,pass
13,0.0,0.0,0.024623,0.026625,0.066224,0.082839,0.015780,0.021995,0.0,0.014773,0.018825,pass
14,0.0,0.0,0.016753,0.022178,0.055948,0.079904,0.017211,0.016991,0.0,0.010133,0.014542,pass
15,0.0,0.0,0.024841,0.033628,0.075580,0.093100,0.024808,0.024329,0.0,0.009028,0.019630,pass
16,0.0,0.0,0.021521,0.027614,0.073178,0.083255,0.017802,0.024129,0.0,0.009273,0.020308,pass
17,0.0,0.0,0.025865,0.037139,0.086828,0.115129,0.023194,0.020452,0.0,0.016890,0.022974,pass
18,0.0,0.0,0.020010,0.034483,0.084096,0.102627,0.025946,0.019804,0.0,0.012900,0.037137,pass
19,0.0,0.0,0.028494,0.027275,0.087439,0.126667,0.027127,0.023350,0.0,0.016138,0.020601,pass

[[       nan        nan 1.1100731  1.23784081 1.22489011 1.25600526
  1.28957275 1.28644045        nan 1.20535795 1.28582589]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,cz 5,h 4,cz 6,h 1,h 7,h 3,h 0,h 8,cz 10,cz 9,cz 2
sum,0.584791,0.571505,0.553653,0.552535,0.547057,0.526376,0.521055,0.511214,0.0,0.0,0.0

custom SCORES

,cz 5,h 4,cz 6,h 1,h 7,h 3,h 0,h 8,cz 10,cz 9,cz 2
sum,0.768416,0.755755,0.723194,0.719036,0.716349,0.695663,0.688551,0.653085,0.0,0.0,0.0

DSTAR SCORES

,cz 5,cz 6,h 7,h 4,h 3,h 0,h 8,h 1,cz 10,cz 9,cz 2
sum,0.209344,0.098681,0.014547,0.0092,0.006469,0.006457,0.005948,0.003271,0.0,0.0,0.0

ERROR GATE LOCATION:
7
Now evolving the following mutant:  AddGate_p_inGap_15_.qasm

100%|██████████| 6/6 [00:00<00:00, 16.02it/s]
100%|██████████| 10/10 [00:00<00:00, 17.29it/s]

,p 10,cz 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.0,0.033406,0.0,0.0,0.013254,0.022578,0.0,0.011601,0.012450,fail
1,0.0,0.0,0.0,0.023732,0.0,0.0,0.013026,0.011288,0.0,0.012043,0.012536,fail
2,0.0,0.0,0.0,0.030064,0.0,0.0,0.012204,0.022410,0.0,0.013778,0.013789,fail
3,0.0,0.0,0.0,0.028879,0.0,0.0,0.010447,0.018523,0.0,0.013534,0.013963,fail
4,0.0,0.0,0.0,0.032280,0.0,0.0,0.015023,0.015770,0.0,0.012526,0.011059,fail
5,0.0,0.0,0.0,0.020789,0.0,0.0,0.011931,0.016564,0.0,0.014566,0.015115,fail
6,0.0,0.0,0.0,0.020282,0.0,0.0,0.013568,0.014297,0.0,0.013306,0.010738,pass
7,0.0,0.0,0.0,0.029080,0.0,0.0,0.014844,0.022502,0.0,0.011936,0.015503,pass
8,0.0,0.0,0.0,0.029851,0.0,0.0,0.015618,0.020048,0.0,0.012430,0.013345,pass
9,0.0,0.0,0.0,0.018034,0.0,0.0,0.008852,0.013600,0.0,0.007829,0.016050,pass
10,0.0,0.0,0.0,0.022844,0.0,0.0,0.012743,0.015494,0.0,0.012212,0.015676,pass
11,0.0,0.0,0.0,0.013872,0.0,0.0,0.005987,0.008380,0.0,0.005231,0.010064,pass
12,0.0,0.0,0.0,0.023357,0.0,0.0,0.007891,0.015045,0.0,0.008465,0.012567,pass
13,0.0,0.0,0.0,0.015345,0.0,0.0,0.010933,0.016127,0.0,0.011808,0.008782,pass
14,0.0,0.0,0.0,0.026466,0.0,0.0,0.007504,0.021328,0.0,0.010045,0.010580,pass
15,0.0,0.0,0.0,0.013919,0.0,0.0,0.005580,0.013889,0.0,0.010891,0.010548,pass

[[       nan        nan        nan 1.18495403        nan        nan
  1.18784744 1.26449374        nan 1.11980573 1.14926122]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 7,h 1,h 4,h 3,h 0,p 10,cz 9,cz 8,cz 6,cz 5,cz 2
sum,0.44257,0.428363,0.42298,0.399984,0.389174,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 7,h 4,h 1,h 3,h 0,p 10,cz 9,cz 8,cz 6,cz 5,cz 2
sum,0.573676,0.548588,0.548284,0.526429,0.500989,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 7,h 3,h 0,h 1,h 4,p 10,cz 9,cz 8,cz 6,cz 5,cz 2
sum,0.004605,0.001863,0.001017,0.000998,0.000943,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_rzz_inGap_4_.qasm

100%|██████████| 6/6 [00:00<00:00, 15.16it/s]
100%|██████████| 10/10 [00:00<00:00, 15.53it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,rzz 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.021714,0.0,0.0,0.009192,0.011795,0.030065,0.0,0.006584,0.011760,fail
1,0.0,0.0,0.019802,0.0,0.0,0.012138,0.012065,0.034809,0.0,0.007644,0.009257,fail
2,0.0,0.0,0.021132,0.0,0.0,0.011665,0.019424,0.029024,0.0,0.008330,0.015222,fail
3,0.0,0.0,0.027683,0.0,0.0,0.014432,0.013406,0.038459,0.0,0.006784,0.011390,fail
4,0.0,0.0,0.019898,0.0,0.0,0.008729,0.016514,0.030440,0.0,0.007071,0.008139,fail
5,0.0,0.0,0.030417,0.0,0.0,0.014917,0.020400,0.031777,0.0,0.013621,0.015446,fail
6,0.0,0.0,0.018590,0.0,0.0,0.008451,0.012135,0.030594,0.0,0.008301,0.011328,pass
7,0.0,0.0,0.026990,0.0,0.0,0.010493,0.018027,0.024869,0.0,0.010173,0.010871,pass
8,0.0,0.0,0.025334,0.0,0.0,0.009208,0.016053,0.030925,0.0,0.010010,0.011317,pass
9,0.0,0.0,0.022647,0.0,0.0,0.013443,0.020194,0.021691,0.0,0.008942,0.012406,pass
10,0.0,0.0,0.021413,0.0,0.0,0.010996,0.011309,0.028391,0.0,0.009261,0.009860,pass
11,0.0,0.0,0.024059,0.0,0.0,0.012124,0.017165,0.024106,0.0,0.007437,0.011245,pass
12,0.0,0.0,0.018908,0.0,0.0,0.009125,0.012209,0.015940,0.0,0.006736,0.009046,pass
13,0.0,0.0,0.023218,0.0,0.0,0.011905,0.018552,0.030332,0.0,0.010834,0.011096,pass
14,0.0,0.0,0.021877,0.0,0.0,0.011548,0.014003,0.025235,0.0,0.010292,0.009587,pass
15,0.0,0.0,0.028399,0.0,0.0,0.010439,0.016945,0.030541,0.0,0.007453,0.011268,pass

[[       nan        nan 1.29761235        nan        nan 1.25928597
  1.30764432 1.18593124        nan 1.63340365 1.30135047]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,rzz 3,h 5,h 0,h 8,h 4,h 1,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.425579,0.397491,0.397313,0.377999,0.374121,0.358736,0.0,0.0,0.0,0.0,0.0

custom SCORES

,rzz 3,h 0,h 5,h 1,h 8,h 4,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.551756,0.526573,0.522629,0.505226,0.500623,0.496426,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,rzz 3,h 8,h 4,h 0,h 5,h 1,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.006045,0.003174,0.001423,0.00083,0.000827,0.000411,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
3
Now evolving the following mutant:  AddGate_x_inGap_3_.qasm

100%|██████████| 5/5 [00:00<00:00, 15.96it/s]
100%|██████████| 10/10 [00:00<00:00, 16.58it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,x 2,h 1,h 0,pass/fail
0,0.0,0.0,0.029689,0.0,0.0,0.012565,0.013276,0.0,0.023456,0.010849,0.017125,fail
1,0.0,0.0,0.029605,0.0,0.0,0.011054,0.011628,0.0,0.020198,0.008542,0.010090,fail
2,0.0,0.0,0.024595,0.0,0.0,0.014442,0.020294,0.0,0.023056,0.012699,0.016788,fail
3,0.0,0.0,0.030823,0.0,0.0,0.015923,0.021183,0.0,0.021730,0.012697,0.016531,fail
4,0.0,0.0,0.021283,0.0,0.0,0.009634,0.014947,0.0,0.025367,0.011605,0.011822,fail
5,0.0,0.0,0.025200,0.0,0.0,0.013584,0.018394,0.0,0.024128,0.011491,0.013262,pass
6,0.0,0.0,0.031690,0.0,0.0,0.010318,0.014606,0.0,0.019706,0.010152,0.014306,pass
7,0.0,0.0,0.013492,0.0,0.0,0.012226,0.015950,0.0,0.011435,0.007133,0.010901,pass
8,0.0,0.0,0.015786,0.0,0.0,0.006769,0.010362,0.0,0.011359,0.006343,0.009531,pass
9,0.0,0.0,0.018664,0.0,0.0,0.012169,0.013757,0.0,0.022717,0.012451,0.008049,pass
10,0.0,0.0,0.017620,0.0,0.0,0.007086,0.011624,0.0,0.008362,0.003725,0.009926,pass
11,0.0,0.0,0.028183,0.0,0.0,0.011528,0.016258,0.0,0.021601,0.012278,0.014196,pass
12,0.0,0.0,0.022508,0.0,0.0,0.009202,0.016239,0.0,0.022572,0.012206,0.015882,pass
13,0.0,0.0,0.025120,0.0,0.0,0.012979,0.015464,0.0,0.021384,0.012952,0.012859,pass
14,0.0,0.0,0.020088,0.0,0.0,0.013111,0.019029,0.0,0.022125,0.010396,0.012241,pass

[[       nan        nan 1.13324572        nan        nan 1.25146452
  1.30233931        nan 1.11445651 1.12597534 1.18338532]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 8,x 2,h 0,h 5,h 1,h 4,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.383792,0.380377,0.373916,0.368604,0.362612,0.349029,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 8,x 2,h 0,h 5,h 1,h 4,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.492525,0.486356,0.484538,0.483928,0.464685,0.462668,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,x 2,h 4,h 0,h 5,h 1,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.003544,0.002498,0.001284,0.001022,0.000792,0.000624,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_s_inGap_6_.qasm

100%|██████████| 6/6 [00:00<00:00, 14.37it/s]
100%|██████████| 10/10 [00:00<00:00, 18.02it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,sdg 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.021735,0.0,0.0,0.0,0.011345,0.012107,0.0,0.013317,0.013407,fail
1,0.0,0.0,0.030895,0.0,0.0,0.0,0.014058,0.014650,0.0,0.014693,0.015550,fail
2,0.0,0.0,0.029690,0.0,0.0,0.0,0.012957,0.016608,0.0,0.011797,0.017022,fail
3,0.0,0.0,0.018381,0.0,0.0,0.0,0.004797,0.014307,0.0,0.010565,0.012897,fail
4,0.0,0.0,0.023189,0.0,0.0,0.0,0.008594,0.015741,0.0,0.011109,0.015288,fail
5,0.0,0.0,0.028532,0.0,0.0,0.0,0.010009,0.010128,0.0,0.011776,0.011674,fail
6,0.0,0.0,0.025898,0.0,0.0,0.0,0.009363,0.011287,0.0,0.007259,0.012582,pass
7,0.0,0.0,0.021193,0.0,0.0,0.0,0.004470,0.011156,0.0,0.009741,0.013914,pass
8,0.0,0.0,0.020099,0.0,0.0,0.0,0.009854,0.009645,0.0,0.007466,0.007688,pass
9,0.0,0.0,0.018803,0.0,0.0,0.0,0.009742,0.018858,0.0,0.011785,0.015404,pass
10,0.0,0.0,0.019512,0.0,0.0,0.0,0.012774,0.012208,0.0,0.011863,0.011825,pass
11,0.0,0.0,0.025820,0.0,0.0,0.0,0.013794,0.013604,0.0,0.014272,0.014764,pass
12,0.0,0.0,0.021321,0.0,0.0,0.0,0.010655,0.016357,0.0,0.008924,0.011218,pass
13,0.0,0.0,0.017250,0.0,0.0,0.0,0.006431,0.009570,0.0,0.006083,0.006782,pass
14,0.0,0.0,0.026611,0.0,0.0,0.0,0.009130,0.015738,0.0,0.009936,0.013922,pass
15,0.0,0.0,0.020215,0.0,0.0,0.0,0.007671,0.013551,0.0,0.007718,0.011230,pass

[[       nan        nan 1.2161725         nan        nan        nan
  1.36571333 1.19279774        nan 1.20342583 1.18982207]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,h 0,h 8,h 4,h 3,cz 10,cz 9,cz 7,cz 6,sdg 5,cz 2
sum,0.435263,0.41838,0.412907,0.396798,0.387635,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 1,h 0,h 8,h 4,h 3,cz 10,cz 9,cz 7,cz 6,sdg 5,cz 2
sum,0.566215,0.54283,0.538448,0.532276,0.503227,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 0,h 3,h 1,h 4,cz 10,cz 9,cz 7,cz 6,sdg 5,cz 2
sum,0.003737,0.001204,0.001138,0.00088,0.000626,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_cswap_inGap_15_.qasm

100%|██████████| 6/6 [00:02<00:00,  2.65it/s]
100%|██████████| 10/10 [00:03<00:00,  2.83it/s]

,cswap 10,cz 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.503467,0.029342,0.107789,0.067352,0.070636,0.0,0.018306,0.039580,0.0,0.017435,0.017229,fail
1,0.540828,0.037583,0.142720,0.082485,0.091692,0.0,0.021338,0.048279,0.0,0.012724,0.019336,fail
2,0.622885,0.032908,0.115241,0.074400,0.092709,0.0,0.020522,0.043025,0.0,0.016794,0.015985,fail
3,0.481095,0.027298,0.088068,0.063792,0.061013,0.0,0.017600,0.037511,0.0,0.012694,0.014612,fail
4,0.485904,0.024880,0.087616,0.061029,0.064822,0.0,0.016626,0.035651,0.0,0.012745,0.009840,fail
5,0.525163,0.028908,0.106519,0.066218,0.075335,0.0,0.017905,0.038312,0.0,0.013408,0.013062,fail
6,0.627758,0.034177,0.123942,0.077157,0.090830,0.0,0.019368,0.044705,0.0,0.018756,0.018321,pass
7,0.433517,0.023192,0.084435,0.054406,0.058075,0.0,0.013594,0.031634,0.0,0.010726,0.012485,pass
8,0.412530,0.022697,0.065231,0.052970,0.055183,0.0,0.015973,0.031363,0.0,0.013872,0.012730,pass
9,0.560905,0.029927,0.115316,0.069977,0.083169,0.0,0.016043,0.040270,0.0,0.017164,0.016460,pass
10,0.575968,0.033915,0.108784,0.079070,0.083141,0.0,0.020837,0.045382,0.0,0.019936,0.017826,pass
11,0.506946,0.031488,0.137982,0.066649,0.088785,0.0,0.016930,0.039994,0.0,0.007390,0.011380,pass
12,0.614886,0.041647,0.159794,0.090954,0.107880,0.0,0.022244,0.055109,0.0,0.013573,0.016696,pass
13,0.309356,0.021251,0.060306,0.046512,0.045309,0.0,0.011663,0.027412,0.0,0.009596,0.010503,pass
14,0.449818,0.017615,0.067203,0.046673,0.044121,0.0,0.012333,0.026698,0.0,0.015306,0.013575,pass
15,0.578588,0.023870,0.110418,0.058163,0.078061,0.0,0.014333,0.033734,0.0,0.013905,0.012279,pass

[[1.18294003 1.24640243 1.32157593 1.19175814 1.21930479        nan
  1.1400983  1.19521971        nan 1.21922934 1.28813126]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 4,cz 9,h 7,h 3,h 0,cz 8,cswap 10,cz 6,h 1,cz 5,cz 2
sum,0.407441,0.392706,0.392582,0.391748,0.387675,0.385373,0.383899,0.383122,0.379609,0.0,0.0

custom SCORES

,h 4,cz 9,cz 8,h 0,h 7,h 3,cz 6,cswap 10,h 1,cz 5,cz 2
sum,0.523571,0.515073,0.512699,0.512518,0.509547,0.508804,0.499908,0.497432,0.495317,0.0,0.0

DSTAR SCORES

,cswap 10,cz 8,cz 6,h 7,h 3,cz 9,h 4,h 0,h 1,cz 5,cz 2
sum,0.901644,0.059693,0.030904,0.025962,0.009212,0.005212,0.002046,0.001321,0.001199,0.0,0.0

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_t_inGap_14_.qasm

100%|██████████| 7/7 [00:00<00:00, 14.41it/s]
100%|██████████| 10/10 [00:00<00:00, 16.78it/s]

,cz 10,cz 9,h 8,tdg 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.027971,1.900112e-18,0.0,0.0,0.013092,0.020334,0.0,0.011525,0.011236,fail
1,0.0,0.0,0.019914,1.704787e-18,0.0,0.0,0.012001,0.020107,0.0,0.013836,0.013028,fail
2,0.0,0.0,0.022802,1.696576e-18,0.0,0.0,0.010181,0.015630,0.0,0.011828,0.015333,fail
3,0.0,0.0,0.025479,1.677618e-18,0.0,0.0,0.009555,0.018884,0.0,0.011367,0.011532,fail
4,0.0,0.0,0.020828,1.785576e-18,0.0,0.0,0.010623,0.017091,0.0,0.008114,0.014072,fail
5,0.0,0.0,0.017707,1.809849e-18,0.0,0.0,0.007779,0.014517,0.0,0.013650,0.015030,fail
6,0.0,0.0,0.022167,1.934500e-18,0.0,0.0,0.008102,0.018881,0.0,0.012558,0.016462,fail
7,0.0,0.0,0.016868,1.243459e-18,0.0,0.0,0.007989,0.007058,0.0,0.006873,0.010938,pass
8,0.0,0.0,0.031223,1.920530e-18,0.0,0.0,0.010081,0.018758,0.0,0.012056,0.015898,pass
9,0.0,0.0,0.024461,1.695174e-18,0.0,0.0,0.015299,0.015046,0.0,0.012661,0.014473,pass
10,0.0,0.0,0.028912,2.029307e-18,0.0,0.0,0.011970,0.019081,0.0,0.013858,0.017815,pass
11,0.0,0.0,0.028413,1.594479e-18,0.0,0.0,0.013884,0.015431,0.0,0.009677,0.014850,pass
12,0.0,0.0,0.010009,9.538588e-19,0.0,0.0,0.001867,0.007963,0.0,0.006125,0.007085,pass
13,0.0,0.0,0.018005,9.479862e-19,0.0,0.0,0.008653,0.008732,0.0,0.006107,0.005757,pass
14,0.0,0.0,0.017877,1.665085e-18,0.0,0.0,0.010430,0.014437,0.0,0.010659,0.009864,pass
15,0.0,0.0,0.018499,1.807304e-18,0.0,0.0,0.011462,0.016998,0.0,0.010071,0.017905,pass
16,0.0,0.0,0.024013,1.779778e-18,0.0,0.0,0.010437,0.015712,0.0,0.009981,0.012747,pass

[[       nan        nan 1.24818348 1.08253896        nan        nan
  1.28471469 1.13467309        nan 1.16859268 1.19174162]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 3,h 1,tdg 7,h 0,h 8,h 4,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.473983,0.458024,0.444434,0.43162,0.418149,0.411371,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 3,h 1,tdg 7,h 0,h 8,h 4,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.608437,0.591834,0.564713,0.560215,0.548631,0.543494,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 3,h 0,h 1,h 4,tdg 7,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.003409,0.002204,0.001312,0.000968,0.000716,2.235365e-35,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
7
Now evolving the following mutant:  AddGate_p_inGap_10_.qasm

100%|██████████| 4/4 [00:00<00:00, 14.46it/s]
100%|██████████| 10/10 [00:00<00:00, 15.86it/s]

,cz 10,p 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.0,0.021794,0.0,0.0,0.007618,0.016287,0.0,0.012258,0.011749,fail
1,0.0,0.0,0.0,0.025787,0.0,0.0,0.011591,0.013814,0.0,0.011431,0.009495,fail
2,0.0,0.0,0.0,0.023381,0.0,0.0,0.009740,0.013918,0.0,0.009889,0.008787,fail
3,0.0,0.0,0.0,0.024709,0.0,0.0,0.011020,0.010130,0.0,0.009184,0.015317,fail
4,0.0,0.0,0.0,0.028522,0.0,0.0,0.012484,0.016472,0.0,0.008511,0.015087,pass
5,0.0,0.0,0.0,0.012667,0.0,0.0,0.010938,0.015917,0.0,0.009443,0.012337,pass
6,0.0,0.0,0.0,0.022694,0.0,0.0,0.010488,0.013366,0.0,0.012436,0.014361,pass
7,0.0,0.0,0.0,0.020874,0.0,0.0,0.009780,0.017164,0.0,0.010237,0.012930,pass
8,0.0,0.0,0.0,0.024016,0.0,0.0,0.009783,0.016231,0.0,0.009912,0.012268,pass
9,0.0,0.0,0.0,0.023377,0.0,0.0,0.008762,0.015710,0.0,0.010300,0.017390,pass
10,0.0,0.0,0.0,0.018788,0.0,0.0,0.007913,0.012959,0.0,0.008604,0.011262,pass
11,0.0,0.0,0.0,0.022416,0.0,0.0,0.009231,0.014346,0.0,0.013106,0.014270,pass
12,0.0,0.0,0.0,0.027341,0.0,0.0,0.015231,0.020099,0.0,0.011430,0.016593,pass
13,0.0,0.0,0.0,0.017658,0.0,0.0,0.007575,0.013428,0.0,0.009696,0.009792,pass

[[       nan        nan        nan 1.07815225        nan        nan
  1.16002065 1.20311367        nan 1.14659436 1.3510764 ]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 7,h 1,h 4,h 3,h 0,cz 10,p 9,cz 8,cz 6,cz 5,cz 2
sum,0.304663,0.292017,0.281169,0.258046,0.249659,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 7,h 1,h 4,h 3,h 0,cz 10,p 9,cz 8,cz 6,cz 5,cz 2
sum,0.386782,0.375723,0.362709,0.33566,0.333986,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 7,h 3,h 0,h 1,h 4,cz 10,p 9,cz 8,cz 6,cz 5,cz 2
sum,0.00217,0.000706,0.000497,0.000446,0.000389,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
9
Now evolving the following mutant:  AddGate_ccx_inGap_2_.qasm

100%|██████████| 7/7 [00:00<00:00, 11.21it/s]
100%|██████████| 10/10 [00:00<00:00, 11.95it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,h 2,ccx 1,h 0,pass/fail
0,0.0,0.0,0.026912,0.0,0.0,0.011714,0.012720,0.0,0.007247,0.034195,0.010408,fail
1,0.0,0.0,0.023217,0.0,0.0,0.012164,0.015313,0.0,0.013213,0.029390,0.010575,fail
2,0.0,0.0,0.030918,0.0,0.0,0.014257,0.018530,0.0,0.011174,0.034443,0.010553,fail
3,0.0,0.0,0.018449,0.0,0.0,0.009758,0.013135,0.0,0.011811,0.036161,0.007421,fail
4,0.0,0.0,0.023192,0.0,0.0,0.013866,0.015359,0.0,0.009745,0.027181,0.012732,fail
5,0.0,0.0,0.027639,0.0,0.0,0.014235,0.017586,0.0,0.010571,0.033503,0.012209,fail
6,0.0,0.0,0.030241,0.0,0.0,0.015015,0.020885,0.0,0.016701,0.030274,0.009938,fail
7,0.0,0.0,0.017355,0.0,0.0,0.006896,0.009228,0.0,0.007444,0.017867,0.006105,pass
8,0.0,0.0,0.009983,0.0,0.0,0.004638,0.009209,0.0,0.008026,0.020745,0.003843,pass
9,0.0,0.0,0.021661,0.0,0.0,0.009258,0.011709,0.0,0.008396,0.032732,0.009994,pass
10,0.0,0.0,0.016660,0.0,0.0,0.010575,0.011569,0.0,0.006492,0.023672,0.005842,pass
11,0.0,0.0,0.016760,0.0,0.0,0.010792,0.007490,0.0,0.005733,0.020349,0.005274,pass
12,0.0,0.0,0.025186,0.0,0.0,0.012154,0.016049,0.0,0.012941,0.030837,0.006948,pass
13,0.0,0.0,0.021529,0.0,0.0,0.010278,0.014586,0.0,0.009261,0.030182,0.005472,pass
14,0.0,0.0,0.026813,0.0,0.0,0.008581,0.011078,0.0,0.006316,0.031861,0.008125,pass
15,0.0,0.0,0.025380,0.0,0.0,0.012920,0.016340,0.0,0.011748,0.034810,0.006174,pass
16,0.0,0.0,0.018367,0.0,0.0,0.008637,0.009295,0.0,0.008098,0.027215,0.007835,pass

[[       nan        nan 1.1985767         nan        nan 1.15488495
  1.2877481         nan 1.45292187 1.12426565 1.20706208]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 0,h 4,h 5,h 2,h 8,ccx 1,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.529486,0.493422,0.489986,0.487894,0.474853,0.45446,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 0,h 2,h 4,h 5,h 8,ccx 1,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.689266,0.665112,0.652273,0.631455,0.61714,0.582194,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,ccx 1,h 8,h 4,h 5,h 2,h 0,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.006972,0.004529,0.001811,0.001167,0.000914,0.000772,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_rxx_inGap_6_.qasm

100%|██████████| 3/3 [00:00<00:00, 13.57it/s]
100%|██████████| 10/10 [00:00<00:00, 14.69it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,rxx 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.024517,0.0,0.0,0.089088,0.030413,0.013538,0.061589,0.034677,0.014684,fail
1,0.0,0.0,0.022464,0.0,0.0,0.070800,0.028675,0.014457,0.042064,0.030201,0.013866,fail
2,0.0,0.0,0.023187,0.0,0.0,0.080135,0.030770,0.018945,0.051190,0.035791,0.017323,fail
3,0.0,0.0,0.026316,0.0,0.0,0.095352,0.038868,0.015771,0.052368,0.038769,0.012516,pass
4,0.0,0.0,0.025056,0.0,0.0,0.055910,0.026262,0.010972,0.039357,0.019423,0.014306,pass
5,0.0,0.0,0.024384,0.0,0.0,0.083014,0.031147,0.014820,0.054626,0.034906,0.012508,pass
6,0.0,0.0,0.021758,0.0,0.0,0.078557,0.033946,0.011129,0.054168,0.027567,0.013146,pass
7,0.0,0.0,0.032423,0.0,0.0,0.095045,0.033527,0.016978,0.063861,0.041515,0.017863,pass
8,0.0,0.0,0.019175,0.0,0.0,0.077570,0.021259,0.012893,0.051836,0.034352,0.016343,pass
9,0.0,0.0,0.013384,0.0,0.0,0.055506,0.014157,0.009502,0.030408,0.022220,0.008332,pass
10,0.0,0.0,0.023307,0.0,0.0,0.083075,0.026045,0.014543,0.051470,0.035960,0.016235,pass
11,0.0,0.0,0.013772,0.0,0.0,0.072151,0.030058,0.016629,0.049445,0.028256,0.011473,pass
12,0.0,0.0,0.028093,0.0,0.0,0.087717,0.029782,0.010553,0.059933,0.033199,0.014406,pass

[[       nan        nan 1.0482049         nan        nan 1.11348934
  1.02728931 1.21081937 1.19324982 1.06658781 1.13290744]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 3,h 0,h 1,h 4,h 8,rxx 5,cz 2,cz 10,cz 9,cz 7,cz 6
sum,0.259721,0.250672,0.241506,0.23968,0.235589,0.234415,0.233791,0.0,0.0,0.0,0.0

custom SCORES

,h 3,h 0,h 1,cz 2,h 4,rxx 5,h 8,cz 10,cz 9,cz 7,cz 6
sum,0.33834,0.321669,0.305903,0.303533,0.301235,0.29967,0.297326,0.0,0.0,0.0,0.0

DSTAR SCORES

,rxx 5,cz 2,h 1,h 4,h 8,h 3,h 0,cz 10,cz 9,cz 7,cz 6
sum,0.015225,0.006836,0.003056,0.002458,0.001525,0.000703,0.000671,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_ccx_inGap_13_.qasm

100%|██████████| 5/5 [00:01<00:00,  3.76it/s]
100%|██████████| 10/10 [00:02<00:00,  3.99it/s]

,ccx 10,cz 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.553916,0.076144,0.0,0.033270,0.043794,0.0,0.016533,0.018043,0.0,0.009998,0.014048,fail
1,0.589803,0.095783,0.0,0.027518,0.052463,0.0,0.017763,0.016070,0.0,0.010587,0.016759,fail
2,0.555103,0.090781,0.0,0.026800,0.043886,0.0,0.011834,0.016151,0.0,0.006965,0.008548,fail
3,0.578115,0.089173,0.0,0.025630,0.047722,0.0,0.015416,0.017590,0.0,0.016387,0.010585,fail
4,0.536564,0.067697,0.0,0.019707,0.038609,0.0,0.010857,0.017049,0.0,0.009390,0.009667,fail
5,0.405610,0.060345,0.0,0.016159,0.031327,0.0,0.008211,0.010470,0.0,0.005831,0.006386,pass
6,0.549636,0.074863,0.0,0.026107,0.042829,0.0,0.013765,0.016617,0.0,0.009220,0.012751,pass
7,0.510292,0.091960,0.0,0.029371,0.050581,0.0,0.016392,0.012754,0.0,0.009397,0.012641,pass
8,0.543438,0.095756,0.0,0.030244,0.049055,0.0,0.015519,0.015536,0.0,0.011883,0.014896,pass
9,0.337759,0.058041,0.0,0.021598,0.034177,0.0,0.010445,0.009853,0.0,0.006374,0.010095,pass
10,0.535219,0.077554,0.0,0.017686,0.041278,0.0,0.010992,0.015011,0.0,0.010050,0.008450,pass
11,0.485085,0.061871,0.0,0.019216,0.035428,0.0,0.012095,0.016190,0.0,0.015478,0.010876,pass
12,0.568932,0.077876,0.0,0.028328,0.044256,0.0,0.016454,0.018205,0.0,0.010026,0.011236,pass
13,0.460991,0.062323,0.0,0.019380,0.032285,0.0,0.011295,0.015653,0.0,0.011445,0.012388,pass
14,0.574291,0.095316,0.0,0.027340,0.050553,0.0,0.014675,0.015481,0.0,0.013821,0.017012,pass

[[1.04816513 1.14141929        nan 1.25145791 1.15825821        nan
  1.22665669 1.06253388        nan 1.53642828 1.40577643]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 3,ccx 10,h 7,h 4,cz 9,cz 6,h 1,h 0,cz 8,cz 5,cz 2
sum,0.368066,0.361412,0.36086,0.357992,0.35694,0.35484,0.339982,0.33803,0.0,0.0,0.0

custom SCORES

,h 7,h 1,h 4,h 3,cz 9,cz 6,h 0,ccx 10,cz 8,cz 5,cz 2
sum,0.47376,0.470571,0.467775,0.465836,0.458795,0.45759,0.456829,0.456116,0.0,0.0,0.0

DSTAR SCORES

,ccx 10,cz 9,cz 6,h 7,h 3,h 4,h 0,h 1,cz 8,cz 5,cz 2
sum,0.793861,0.030585,0.009478,0.003375,0.001401,0.001022,0.000694,0.000557,0.0,0.0,0.0

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_ry_inGap_11_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.11it/s]
100%|██████████| 10/10 [00:00<00:00, 12.06it/s]

,cz 10,ry 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.048949,0.295636,0.063418,0.0,0.0,0.023074,0.020670,0.092448,0.026950,0.031942,fail
1,0.0,0.045544,0.241127,0.051237,0.0,0.0,0.028141,0.025818,0.091556,0.034207,0.034960,fail
2,0.0,0.056964,0.344389,0.052767,0.0,0.0,0.021927,0.040646,0.120902,0.042679,0.041896,fail
3,0.0,0.053673,0.308275,0.047701,0.0,0.0,0.026009,0.027212,0.107728,0.037577,0.037517,fail
4,0.0,0.047383,0.275165,0.057457,0.0,0.0,0.025346,0.029945,0.088013,0.032042,0.034470,fail
5,0.0,0.046569,0.273786,0.042069,0.0,0.0,0.019268,0.029630,0.091220,0.032971,0.032102,fail
6,0.0,0.040368,0.232130,0.054874,0.0,0.0,0.020730,0.020407,0.075712,0.022359,0.028297,fail
7,0.0,0.058809,0.329339,0.062259,0.0,0.0,0.030771,0.039919,0.117870,0.037074,0.045850,fail
8,0.0,0.053575,0.310285,0.052479,0.0,0.0,0.025848,0.038325,0.115937,0.030433,0.042321,fail
9,0.0,0.043609,0.249334,0.043924,0.0,0.0,0.020239,0.037894,0.097663,0.025621,0.034537,fail
10,0.0,0.039580,0.206198,0.050477,0.0,0.0,0.028014,0.027611,0.073277,0.029545,0.031288,pass
11,0.0,0.036318,0.207368,0.044991,0.0,0.0,0.014695,0.019633,0.060104,0.020388,0.025919,pass
12,0.0,0.038727,0.217126,0.038381,0.0,0.0,0.021606,0.028812,0.071476,0.023087,0.028920,pass
13,0.0,0.037366,0.211557,0.043683,0.0,0.0,0.023139,0.018976,0.072653,0.025608,0.028407,pass
14,0.0,0.028409,0.149783,0.042237,0.0,0.0,0.019859,0.022690,0.040101,0.017650,0.020733,pass
15,0.0,0.032428,0.167628,0.048623,0.0,0.0,0.023080,0.027576,0.060809,0.022459,0.025967,pass
16,0.0,0.040559,0.210426,0.039621,0.0,0.0,0.020704,0.031050,0.064827,0.025617,0.032353,pass
17,0.0,0.049614,0.289321,0.056989,0.0,0.0,0.019861,0.044356,0.092554,0.039377,0.038236,pass
18,0.0,0.038629,0.190958,0.043774,0.0,0.0,0.029141,0.036371,0.071253,0.034937,0.032773,pass
19,0.0,0.039456,0.223685,0.075809,0.0,0.0,0.027670,0.033113,0.078124,0.041124,0.032038,pass

[[       nan 1.18699646 1.20438089 1.20067931        nan        nan
  1.27492699 1.30918728 1.21017345 1.32580517 1.25998511]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,cz 2,cz 8,ry 9,h 0,h 1,h 7,h 3,h 4,cz 10,cz 6,cz 5
sum,0.59318,0.5796,0.565234,0.550913,0.535002,0.521524,0.516881,0.514478,0.0,0.0,0.0

custom SCORES

,cz 2,cz 8,ry 9,h 0,h 1,h 3,h 4,h 7,cz 10,cz 6,cz 5
sum,0.772643,0.754115,0.732966,0.724449,0.712329,0.686055,0.678458,0.67807,0.0,0.0,0.0

DSTAR SCORES

,cz 8,cz 2,h 7,ry 9,h 0,h 1,h 3,h 4,cz 10,cz 6,cz 5
sum,0.677201,0.09341,0.026608,0.023645,0.01286,0.010081,0.009367,0.005695,0.0,0.0,0.0

ERROR GATE LOCATION:
9
Now evolving the following mutant:  AddGate_rxx_inGap_5_.qasm

100%|██████████| 3/3 [00:00<00:00, 16.50it/s]
100%|██████████| 10/10 [00:00<00:00, 16.88it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,rxx 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.019889,0.0,0.0,0.015628,0.0,0.014450,0.0,0.012263,0.010994,fail
1,0.0,0.0,0.023906,0.0,0.0,0.011875,0.0,0.014603,0.0,0.009637,0.015992,fail
2,0.0,0.0,0.035911,0.0,0.0,0.012817,0.0,0.017540,0.0,0.012182,0.013859,fail
3,0.0,0.0,0.023625,0.0,0.0,0.013495,0.0,0.016713,0.0,0.010073,0.011149,pass
4,0.0,0.0,0.013433,0.0,0.0,0.007238,0.0,0.010639,0.0,0.007390,0.011063,pass
5,0.0,0.0,0.023862,0.0,0.0,0.012254,0.0,0.015011,0.0,0.007483,0.011493,pass
6,0.0,0.0,0.015901,0.0,0.0,0.008188,0.0,0.009854,0.0,0.007976,0.007591,pass
7,0.0,0.0,0.019905,0.0,0.0,0.012576,0.0,0.013189,0.0,0.008514,0.007760,pass
8,0.0,0.0,0.020142,0.0,0.0,0.007990,0.0,0.011964,0.0,0.006607,0.009127,pass
9,0.0,0.0,0.022353,0.0,0.0,0.010529,0.0,0.012192,0.0,0.007598,0.009250,pass
10,0.0,0.0,0.019686,0.0,0.0,0.009897,0.0,0.016858,0.0,0.009423,0.012842,pass
11,0.0,0.0,0.024649,0.0,0.0,0.016332,0.0,0.014494,0.0,0.009757,0.012058,pass
12,0.0,0.0,0.020142,0.0,0.0,0.007863,0.0,0.013428,0.0,0.008856,0.009403,pass

[[       nan        nan 1.35163139        nan        nan 1.16283626
         nan 1.12933681        nan 1.07943661 1.17459992]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,h 0,h 8,h 5,h 3,cz 10,cz 9,cz 7,cz 6,rxx 4,cz 2
sum,0.289428,0.286471,0.281247,0.274878,0.257514,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 8,h 0,h 1,h 5,h 3,cz 10,cz 9,cz 7,cz 6,rxx 4,cz 2
sum,0.376283,0.370593,0.367533,0.354788,0.330219,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 3,h 0,h 5,h 1,cz 10,cz 9,cz 7,cz 6,rxx 4,cz 2
sum,0.001983,0.000693,0.000538,0.000523,0.000377,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_id_inGap_6_.qasm

100%|██████████| 4/4 [00:00<00:00, 15.17it/s]
100%|██████████| 10/10 [00:00<00:00, 16.43it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,id 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.018346,0.0,0.0,0.0,0.010528,0.014456,0.0,0.011860,0.016952,fail
1,0.0,0.0,0.021108,0.0,0.0,0.0,0.006996,0.014863,0.0,0.009045,0.010480,fail
2,0.0,0.0,0.025700,0.0,0.0,0.0,0.010571,0.014987,0.0,0.008240,0.015024,fail
3,0.0,0.0,0.021321,0.0,0.0,0.0,0.009898,0.015052,0.0,0.006261,0.011427,fail
4,0.0,0.0,0.019007,0.0,0.0,0.0,0.009137,0.012446,0.0,0.010402,0.016175,pass
5,0.0,0.0,0.026487,0.0,0.0,0.0,0.011744,0.015054,0.0,0.010577,0.014090,pass
6,0.0,0.0,0.021104,0.0,0.0,0.0,0.012209,0.013995,0.0,0.012584,0.015079,pass
7,0.0,0.0,0.026275,0.0,0.0,0.0,0.017511,0.015529,0.0,0.009585,0.018293,pass
8,0.0,0.0,0.015330,0.0,0.0,0.0,0.008718,0.011101,0.0,0.008834,0.009930,pass
9,0.0,0.0,0.020553,0.0,0.0,0.0,0.010063,0.015349,0.0,0.006020,0.005003,pass
10,0.0,0.0,0.014768,0.0,0.0,0.0,0.007976,0.007728,0.0,0.005943,0.008693,pass
11,0.0,0.0,0.017561,0.0,0.0,0.0,0.006622,0.011436,0.0,0.010056,0.009073,pass
12,0.0,0.0,0.021875,0.0,0.0,0.0,0.008688,0.009856,0.0,0.007709,0.013226,pass
13,0.0,0.0,0.022980,0.0,0.0,0.0,0.009965,0.012332,0.0,0.011353,0.007534,pass

[[       nan        nan 1.18878663        nan        nan        nan
  1.11290986 1.01430623        nan 1.33987673 1.25844729]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 3,h 0,h 8,h 1,h 4,cz 10,cz 9,cz 7,cz 6,id 5,cz 2
sum,0.32228,0.315144,0.295725,0.275608,0.270167,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 0,h 3,h 8,h 1,h 4,cz 10,cz 9,cz 7,cz 6,id 5,cz 2
sum,0.414292,0.404002,0.383614,0.367928,0.345335,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 3,h 0,h 4,h 1,cz 10,cz 9,cz 7,cz 6,id 5,cz 2
sum,0.001778,0.000854,0.000705,0.000352,0.000306,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_ccx_inGap_6_.qasm

100%|██████████| 2/2 [00:00<00:00,  6.56it/s]
100%|██████████| 10/10 [00:01<00:00,  6.89it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,ccx 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.026659,0.0,0.0,0.060235,0.013867,0.009523,0.0,0.006594,0.009084,fail
1,0.0,0.0,0.027366,0.0,0.0,0.065937,0.018853,0.011481,0.0,0.009809,0.010844,fail
2,0.0,0.0,0.014834,0.0,0.0,0.035415,0.009559,0.007242,0.0,0.006398,0.005826,pass
3,0.0,0.0,0.024992,0.0,0.0,0.053875,0.018765,0.011557,0.0,0.007600,0.009034,pass
4,0.0,0.0,0.020124,0.0,0.0,0.053263,0.012502,0.008251,0.0,0.005184,0.008632,pass
5,0.0,0.0,0.020203,0.0,0.0,0.050961,0.012640,0.008021,0.0,0.006295,0.010414,pass
6,0.0,0.0,0.019044,0.0,0.0,0.041489,0.014293,0.008726,0.0,0.007356,0.009080,pass
7,0.0,0.0,0.019058,0.0,0.0,0.046882,0.014392,0.009664,0.0,0.004936,0.008028,pass
8,0.0,0.0,0.023795,0.0,0.0,0.055692,0.015832,0.008021,0.0,0.005763,0.007503,pass
9,0.0,0.0,0.017249,0.0,0.0,0.044191,0.012032,0.009085,0.0,0.006940,0.011548,pass
10,0.0,0.0,0.022292,0.0,0.0,0.058407,0.014883,0.009166,0.0,0.006892,0.006365,pass
11,0.0,0.0,0.013123,0.0,0.0,0.033596,0.009825,0.006372,0.0,0.004390,0.004559,pass

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

[[       nan        nan 1.01310303        nan        nan 1.04519207
  1.1523717  1.09322421        nan 1.19596749 1.08829291]]
BARINEL SCORES

,h 8,ccx 5,h 1,h 0,h 3,h 4,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.217194,0.210307,0.209876,0.197469,0.196097,0.19541,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 1,h 8,ccx 5,h 4,h 0,h 3,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.272627,0.272204,0.265259,0.251707,0.251195,0.249692,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,ccx 5,h 8,h 4,h 3,h 0,h 1,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.006435,0.00133,0.000502,0.000211,0.000191,0.00013,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rx_inGap_3_.qasm

100%|██████████| 2/2 [00:00<00:00, 14.11it/s]
100%|██████████| 10/10 [00:00<00:00, 16.14it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,rx 2,h 1,h 0,pass/fail
0,0.0,0.0,0.030201,0.0,0.0,0.012356,0.019053,0.0,0.009933,0.021893,0.016789,fail
1,0.0,0.0,0.029297,0.0,0.0,0.013765,0.017765,0.0,0.011664,0.026006,0.013900,fail
2,0.0,0.0,0.022763,0.0,0.0,0.008894,0.011479,0.0,0.008589,0.022116,0.011338,pass
3,0.0,0.0,0.022676,0.0,0.0,0.010804,0.015191,0.0,0.008288,0.017205,0.012097,pass
4,0.0,0.0,0.021847,0.0,0.0,0.013979,0.019794,0.0,0.010373,0.022931,0.016017,pass
5,0.0,0.0,0.016042,0.0,0.0,0.009892,0.015913,0.0,0.008269,0.019201,0.013292,pass
6,0.0,0.0,0.025164,0.0,0.0,0.009508,0.011245,0.0,0.008701,0.021224,0.006692,pass
7,0.0,0.0,0.029021,0.0,0.0,0.012866,0.014920,0.0,0.008365,0.018418,0.011155,pass
8,0.0,0.0,0.017632,0.0,0.0,0.009831,0.012999,0.0,0.007277,0.019885,0.008820,pass
9,0.0,0.0,0.028415,0.0,0.0,0.013820,0.017965,0.0,0.008725,0.017786,0.014527,pass
10,0.0,0.0,0.020080,0.0,0.0,0.009119,0.014969,0.0,0.010982,0.024951,0.014644,pass
11,0.0,0.0,0.029900,0.0,0.0,0.009573,0.014834,0.0,0.009348,0.021201,0.012324,pass

[[       nan        nan 1.01518524        nan        nan 1.05395777
  1.03498748        nan 1.08014725 1.08586542 1.09415386]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 8,h 0,h 4,rx 2,h 5,h 1,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.203038,0.202441,0.197813,0.195418,0.194343,0.189463,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 0,h 8,h 4,rx 2,h 5,h 1,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.257816,0.254569,0.248996,0.248189,0.245551,0.240895,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 1,h 4,h 0,h 5,rx 2,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.001585,0.001041,0.000631,0.000444,0.000324,0.000223,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_y_inGap_2_.qasm

100%|██████████| 6/6 [00:00<00:00, 16.56it/s]
100%|██████████| 10/10 [00:00<00:00, 17.06it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,h 2,y 1,h 0,pass/fail
0,0.0,0.0,0.027459,0.0,0.0,0.014178,0.015486,0.0,0.013663,0.027659,0.015249,fail
1,0.0,0.0,0.019636,0.0,0.0,0.013234,0.011865,0.0,0.009774,0.020288,0.012359,fail
2,0.0,0.0,0.024426,0.0,0.0,0.010259,0.011173,0.0,0.011203,0.023092,0.013205,fail
3,0.0,0.0,0.023433,0.0,0.0,0.012755,0.012140,0.0,0.009911,0.021870,0.014319,fail
4,0.0,0.0,0.026080,0.0,0.0,0.014020,0.014717,0.0,0.013223,0.028034,0.015714,fail
5,0.0,0.0,0.016359,0.0,0.0,0.009676,0.011978,0.0,0.008864,0.017873,0.013168,fail
6,0.0,0.0,0.008855,0.0,0.0,0.006421,0.007678,0.0,0.005235,0.010427,0.005219,pass
7,0.0,0.0,0.020099,0.0,0.0,0.008842,0.013238,0.0,0.010315,0.019013,0.008656,pass
8,0.0,0.0,0.015162,0.0,0.0,0.005421,0.008888,0.0,0.004460,0.007640,0.005825,pass
9,0.0,0.0,0.030739,0.0,0.0,0.014342,0.023184,0.0,0.013777,0.027032,0.018191,pass
10,0.0,0.0,0.015657,0.0,0.0,0.008743,0.007517,0.0,0.009198,0.022788,0.012250,pass
11,0.0,0.0,0.023929,0.0,0.0,0.011958,0.013334,0.0,0.009476,0.018534,0.008912,pass
12,0.0,0.0,0.024191,0.0,0.0,0.009375,0.017825,0.0,0.009165,0.018660,0.013317,pass
13,0.0,0.0,0.023878,0.0,0.0,0.008796,0.013977,0.0,0.006886,0.014059,0.011678,pass
14,0.0,0.0,0.032974,0.0,0.0,0.011957,0.014800,0.0,0.009258,0.019323,0.016014,pass
15,0.0,0.0,0.026263,0.0,0.0,0.012477,0.017650,0.0,0.011350,0.021786,0.017059,pass

[[       nan        nan 1.19915503        nan        nan 1.1476595
  1.20111231        nan 1.23016918 1.21169203 1.12226524]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,y 1,h 5,h 2,h 0,h 8,h 4,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.436421,0.42981,0.427831,0.417694,0.382561,0.359062,0.0,0.0,0.0,0.0,0.0

custom SCORES

,y 1,h 2,h 5,h 0,h 8,h 4,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.568623,0.559408,0.553129,0.534885,0.497248,0.46688,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,y 1,h 8,h 0,h 4,h 5,h 2,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.003118,0.003034,0.001154,0.000975,0.000901,0.000729,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_sx_inGap_4_.qasm

100%|██████████| 4/4 [00:00<00:00, 16.71it/s]
100%|██████████| 10/10 [00:00<00:00, 17.42it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,sxdg 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.023709,0.0,0.0,0.012367,0.016690,0.0,0.0,0.011750,0.013972,fail
1,0.0,0.0,0.028563,0.0,0.0,0.011014,0.014521,0.0,0.0,0.012034,0.010221,fail
2,0.0,0.0,0.022782,0.0,0.0,0.014697,0.019420,0.0,0.0,0.013582,0.014215,fail
3,0.0,0.0,0.018694,0.0,0.0,0.015454,0.016018,0.0,0.0,0.014850,0.013732,fail
4,0.0,0.0,0.022997,0.0,0.0,0.012700,0.017178,0.0,0.0,0.011587,0.014457,pass
5,0.0,0.0,0.023449,0.0,0.0,0.011745,0.011855,0.0,0.0,0.011371,0.015646,pass
6,0.0,0.0,0.024346,0.0,0.0,0.011874,0.011780,0.0,0.0,0.011451,0.014239,pass
7,0.0,0.0,0.020937,0.0,0.0,0.008765,0.013400,0.0,0.0,0.007281,0.011475,pass
8,0.0,0.0,0.034417,0.0,0.0,0.015526,0.015914,0.0,0.0,0.009047,0.017585,pass
9,0.0,0.0,0.029228,0.0,0.0,0.010294,0.014638,0.0,0.0,0.010305,0.015419,pass
10,0.0,0.0,0.019298,0.0,0.0,0.010341,0.018434,0.0,0.0,0.009207,0.011760,pass
11,0.0,0.0,0.023779,0.0,0.0,0.010246,0.013095,0.0,0.0,0.010010,0.016093,pass
12,0.0,0.0,0.024310,0.0,0.0,0.011922,0.015374,0.0,0.0,0.010119,0.012752,pass
13,0.0,0.0,0.012219,0.0,0.0,0.007893,0.010530,0.0,0.0,0.006195,0.008090,pass

[[       nan        nan 1.21870129        nan        nan 1.15474584
  1.16550453        nan        nan 1.13757392 1.090507  ]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,h 5,h 4,h 8,h 0,cz 10,cz 9,cz 7,cz 6,sxdg 3,cz 2
sum,0.350941,0.324753,0.319129,0.285183,0.274921,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 1,h 5,h 4,h 8,h 0,cz 10,cz 9,cz 7,cz 6,sxdg 3,cz 2
sum,0.450746,0.418504,0.412115,0.372071,0.349871,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 4,h 5,h 1,h 0,cz 10,cz 9,cz 7,cz 6,sxdg 3,cz 2
sum,0.002075,0.001072,0.000697,0.000666,0.000657,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
3
Now evolving the following mutant:  AddGate_rzz_inGap_12_.qasm

100%|██████████| 7/7 [00:00<00:00, 16.82it/s]
100%|██████████| 10/10 [00:00<00:00, 15.99it/s]

,rzz 10,cz 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.0,0.020713,0.0,0.0,0.009432,0.014412,0.0,0.007386,0.014760,fail
1,0.0,0.0,0.0,0.019881,0.0,0.0,0.009441,0.014763,0.0,0.011210,0.013501,fail
2,0.0,0.0,0.0,0.025195,0.0,0.0,0.017292,0.018040,0.0,0.012537,0.016951,fail
3,0.0,0.0,0.0,0.019501,0.0,0.0,0.008568,0.013731,0.0,0.009876,0.013464,fail
4,0.0,0.0,0.0,0.025953,0.0,0.0,0.012397,0.013166,0.0,0.010951,0.010515,fail
5,0.0,0.0,0.0,0.023351,0.0,0.0,0.009186,0.013015,0.0,0.012552,0.014235,fail
6,0.0,0.0,0.0,0.024029,0.0,0.0,0.009910,0.014804,0.0,0.010748,0.005586,fail
7,0.0,0.0,0.0,0.017351,0.0,0.0,0.014086,0.017370,0.0,0.008521,0.011090,pass
8,0.0,0.0,0.0,0.016961,0.0,0.0,0.010694,0.017386,0.0,0.010054,0.011873,pass
9,0.0,0.0,0.0,0.016307,0.0,0.0,0.008652,0.010888,0.0,0.007478,0.009980,pass
10,0.0,0.0,0.0,0.025901,0.0,0.0,0.012192,0.015920,0.0,0.012586,0.010901,pass
11,0.0,0.0,0.0,0.023867,0.0,0.0,0.005200,0.013090,0.0,0.006360,0.012319,pass
12,0.0,0.0,0.0,0.018173,0.0,0.0,0.009928,0.014532,0.0,0.008960,0.010953,pass
13,0.0,0.0,0.0,0.016663,0.0,0.0,0.005661,0.008304,0.0,0.007042,0.009090,pass
14,0.0,0.0,0.0,0.019927,0.0,0.0,0.010463,0.013842,0.0,0.007990,0.009555,pass
15,0.0,0.0,0.0,0.030933,0.0,0.0,0.013887,0.020579,0.0,0.011673,0.013088,pass
16,0.0,0.0,0.0,0.014138,0.0,0.0,0.006126,0.009716,0.0,0.005203,0.009114,pass

[[       nan        nan        nan 1.14529806        nan        nan
  1.58798222 1.2388725         nan 1.16744511 1.3330724 ]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,h 0,h 7,h 4,h 3,rzz 10,cz 9,cz 8,cz 6,cz 5,cz 2
sum,0.467088,0.451897,0.442038,0.44032,0.418506,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 4,h 1,h 0,h 7,h 3,rzz 10,cz 9,cz 8,cz 6,cz 5,cz 2
sum,0.615125,0.603413,0.602499,0.568604,0.548125,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 7,h 3,h 0,h 4,h 1,rzz 10,cz 9,cz 8,cz 6,cz 5,cz 2
sum,0.003495,0.001455,0.001115,0.000819,0.000799,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_id_inGap_2_.qasm

100%|██████████| 6/6 [00:00<00:00, 16.75it/s]
100%|██████████| 10/10 [00:00<00:00, 17.30it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,h 2,id 1,h 0,pass/fail
0,0.0,0.0,0.029186,0.0,0.0,0.008902,0.014074,0.0,0.007885,0.0,0.008001,fail
1,0.0,0.0,0.023386,0.0,0.0,0.006037,0.012719,0.0,0.010152,0.0,0.011224,fail
2,0.0,0.0,0.028699,0.0,0.0,0.009470,0.016533,0.0,0.008747,0.0,0.014180,fail
3,0.0,0.0,0.030039,0.0,0.0,0.012985,0.014177,0.0,0.012367,0.0,0.013433,fail
4,0.0,0.0,0.030715,0.0,0.0,0.011174,0.018025,0.0,0.012237,0.0,0.012068,fail
5,0.0,0.0,0.018766,0.0,0.0,0.009909,0.010050,0.0,0.012168,0.0,0.010120,fail
6,0.0,0.0,0.028809,0.0,0.0,0.011146,0.011224,0.0,0.010479,0.0,0.011217,pass
7,0.0,0.0,0.028733,0.0,0.0,0.010343,0.016486,0.0,0.009922,0.0,0.014108,pass
8,0.0,0.0,0.023457,0.0,0.0,0.008261,0.016676,0.0,0.011197,0.0,0.011846,pass
9,0.0,0.0,0.013911,0.0,0.0,0.010059,0.019481,0.0,0.010798,0.0,0.011126,pass
10,0.0,0.0,0.027049,0.0,0.0,0.010249,0.015057,0.0,0.009695,0.0,0.008209,pass
11,0.0,0.0,0.019537,0.0,0.0,0.007014,0.015480,0.0,0.011094,0.0,0.007036,pass
12,0.0,0.0,0.021065,0.0,0.0,0.014069,0.019822,0.0,0.012345,0.0,0.015234,pass
13,0.0,0.0,0.021987,0.0,0.0,0.011114,0.014885,0.0,0.011561,0.0,0.014850,pass
14,0.0,0.0,0.028140,0.0,0.0,0.007224,0.009731,0.0,0.007356,0.0,0.009100,pass
15,0.0,0.0,0.023228,0.0,0.0,0.007791,0.014813,0.0,0.010357,0.0,0.015698,pass

[[       nan        nan 1.14612539        nan        nan 1.33232556
  1.26378516        nan 1.16751741        nan 1.23259041]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 8,h 2,h 5,h 0,h 4,cz 10,cz 9,cz 7,cz 6,cz 3,id 1
sum,0.405315,0.377501,0.37546,0.368233,0.357717,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 8,h 5,h 2,h 0,h 4,cz 10,cz 9,cz 7,cz 6,cz 3,id 1
sum,0.52145,0.500518,0.487686,0.481703,0.470736,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 4,h 0,h 2,h 5,cz 10,cz 9,cz 7,cz 6,cz 3,id 1
sum,0.004146,0.00119,0.000779,0.000662,0.000561,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_id_inGap_4_.qasm

100%|██████████| 6/6 [00:00<00:00, 15.41it/s]
100%|██████████| 10/10 [00:00<00:00, 16.77it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,id 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.024223,0.0,0.0,0.009312,0.013607,0.0,0.0,0.010380,0.016328,fail
1,0.0,0.0,0.027072,0.0,0.0,0.012479,0.016642,0.0,0.0,0.008486,0.013968,fail
2,0.0,0.0,0.021997,0.0,0.0,0.010099,0.016288,0.0,0.0,0.007716,0.009556,fail
3,0.0,0.0,0.030632,0.0,0.0,0.011782,0.015615,0.0,0.0,0.011207,0.013283,fail
4,0.0,0.0,0.028246,0.0,0.0,0.008342,0.016649,0.0,0.0,0.013989,0.009458,fail
5,0.0,0.0,0.024645,0.0,0.0,0.014159,0.016602,0.0,0.0,0.011542,0.012611,fail
6,0.0,0.0,0.024570,0.0,0.0,0.006612,0.010315,0.0,0.0,0.007247,0.010491,pass
7,0.0,0.0,0.019858,0.0,0.0,0.010469,0.009592,0.0,0.0,0.009540,0.005936,pass
8,0.0,0.0,0.031004,0.0,0.0,0.014832,0.017975,0.0,0.0,0.013218,0.016914,pass
9,0.0,0.0,0.023195,0.0,0.0,0.009809,0.010505,0.0,0.0,0.006432,0.011883,pass
10,0.0,0.0,0.024523,0.0,0.0,0.013550,0.012026,0.0,0.0,0.010678,0.016151,pass
11,0.0,0.0,0.014035,0.0,0.0,0.007556,0.008149,0.0,0.0,0.008150,0.009028,pass
12,0.0,0.0,0.017825,0.0,0.0,0.010527,0.014378,0.0,0.0,0.010101,0.010244,pass
13,0.0,0.0,0.025161,0.0,0.0,0.012531,0.015166,0.0,0.0,0.010267,0.011686,pass
14,0.0,0.0,0.021981,0.0,0.0,0.012190,0.012554,0.0,0.0,0.011319,0.014359,pass
15,0.0,0.0,0.020926,0.0,0.0,0.013764,0.016763,0.0,0.0,0.013755,0.016508,pass

[[       nan        nan 1.17202894        nan        nan 1.28380991
  1.04706411        nan        nan 1.32552343 1.30267149]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 4,h 8,h 1,h 0,h 5,cz 10,cz 9,cz 7,cz 6,id 3,cz 2
sum,0.428151,0.412787,0.386034,0.379049,0.371725,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 4,h 8,h 1,h 0,h 5,cz 10,cz 9,cz 7,cz 6,id 3,cz 2
sum,0.540226,0.533737,0.513958,0.502492,0.49103,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 4,h 0,h 5,h 1,cz 10,cz 9,cz 7,cz 6,id 3,cz 2
sum,0.003952,0.001485,0.000924,0.000716,0.000657,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
3
Now evolving the following mutant:  AddGate_ccx_inGap_1_.qasm

100%|██████████| 6/6 [00:00<00:00, 16.33it/s]
100%|██████████| 10/10 [00:00<00:00, 15.28it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,h 2,h 1,ccx 0,pass/fail
0,0.0,0.0,0.030495,0.0,0.0,0.013304,0.016069,0.0,0.012676,0.018137,0.041178,fail
1,0.0,0.0,0.013361,0.0,0.0,0.009332,0.012591,0.0,0.008792,0.010139,0.033211,fail
2,0.0,0.0,0.029261,0.0,0.0,0.014392,0.017892,0.0,0.011579,0.013983,0.038712,fail
3,0.0,0.0,0.021354,0.0,0.0,0.006377,0.012704,0.0,0.009464,0.017464,0.034941,fail
4,0.0,0.0,0.026431,0.0,0.0,0.013611,0.011883,0.0,0.008130,0.010961,0.044071,fail
5,0.0,0.0,0.033570,0.0,0.0,0.015119,0.019594,0.0,0.010252,0.016148,0.039605,fail
6,0.0,0.0,0.021541,0.0,0.0,0.006454,0.015729,0.0,0.008886,0.011641,0.033946,pass
7,0.0,0.0,0.028066,0.0,0.0,0.010577,0.014111,0.0,0.011024,0.014020,0.033446,pass
8,0.0,0.0,0.021776,0.0,0.0,0.010090,0.012347,0.0,0.010743,0.009832,0.027299,pass
9,0.0,0.0,0.027642,0.0,0.0,0.011614,0.013334,0.0,0.011590,0.013401,0.038489,pass
10,0.0,0.0,0.023803,0.0,0.0,0.013407,0.018421,0.0,0.011861,0.012388,0.033680,pass
11,0.0,0.0,0.016007,0.0,0.0,0.006299,0.008782,0.0,0.006206,0.009883,0.029727,pass
12,0.0,0.0,0.021525,0.0,0.0,0.011502,0.014174,0.0,0.012088,0.016654,0.031491,pass
13,0.0,0.0,0.019842,0.0,0.0,0.013051,0.018124,0.0,0.010410,0.012022,0.033525,pass
14,0.0,0.0,0.024488,0.0,0.0,0.012167,0.021196,0.0,0.011410,0.011844,0.037207,pass
15,0.0,0.0,0.016594,0.0,0.0,0.008763,0.008516,0.0,0.007044,0.010141,0.020468,pass

[[       nan        nan 1.30391465        nan        nan 1.25752534
  1.29571173        nan 1.2490259  1.25325321 1.14115902]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,ccx 0,h 1,h 8,h 5,h 4,h 2,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.420544,0.416143,0.411098,0.409719,0.385331,0.375531,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 1,h 8,ccx 0,h 5,h 4,h 2,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.546526,0.545107,0.540521,0.538527,0.51015,0.492793,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,ccx 0,h 8,h 4,h 1,h 5,h 2,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.008497,0.003836,0.00134,0.001232,0.000852,0.000608,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_rx_inGap_14_.qasm

100%|██████████| 3/3 [00:00<00:00,  9.86it/s]
100%|██████████| 10/10 [00:00<00:00, 10.97it/s]

,cz 10,cz 9,h 8,rx 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.016176,0.111918,0.069020,0.108926,0.099939,0.014420,0.0,0.023842,0.020698,fail
1,0.0,0.0,0.017591,0.123480,0.068285,0.082679,0.110566,0.029565,0.0,0.017502,0.032282,fail
2,0.0,0.0,0.030167,0.202865,0.120307,0.169693,0.178907,0.032842,0.0,0.025089,0.029062,fail
3,0.0,0.0,0.031230,0.219971,0.132173,0.179575,0.192939,0.045497,0.0,0.030151,0.036337,pass
4,0.0,0.0,0.026417,0.154123,0.086362,0.128911,0.136101,0.032443,0.0,0.012484,0.026266,pass
5,0.0,0.0,0.024636,0.161963,0.101645,0.133975,0.142292,0.035004,0.0,0.023600,0.028057,pass
6,0.0,0.0,0.027088,0.133647,0.078092,0.107242,0.120056,0.030331,0.0,0.020754,0.033903,pass
7,0.0,0.0,0.020920,0.139946,0.093290,0.137676,0.126349,0.024452,0.0,0.023134,0.020238,pass
8,0.0,0.0,0.033418,0.185268,0.115028,0.171132,0.161992,0.034050,0.0,0.025971,0.031170,pass
9,0.0,0.0,0.018492,0.141430,0.085264,0.146180,0.125551,0.015186,0.0,0.020917,0.027296,pass
10,0.0,0.0,0.015925,0.099314,0.067606,0.113975,0.091303,0.019589,0.0,0.018024,0.017221,pass
11,0.0,0.0,0.019572,0.113759,0.065776,0.076827,0.102300,0.021986,0.0,0.015056,0.029241,pass
12,0.0,0.0,0.018149,0.106352,0.057869,0.082216,0.094799,0.020360,0.0,0.008468,0.026414,pass

[[       nan        nan 1.41554269 1.38865443 1.40102327 1.40902664
  1.37828487 1.28244066        nan 1.13296733 1.18043537]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,rx 7,h 4,h 0,cz 6,cz 5,h 3,h 8,cz 10,cz 9,cz 2
sum,0.250701,0.231391,0.231366,0.229049,0.225833,0.220437,0.215974,0.213268,0.0,0.0,0.0

custom SCORES

,h 1,rx 7,h 4,cz 6,cz 5,h 0,h 8,h 3,cz 10,cz 9,cz 2
sum,0.32171,0.311722,0.311089,0.304933,0.298087,0.296644,0.288741,0.285217,0.0,0.0,0.0

DSTAR SCORES

,rx 7,h 4,cz 5,cz 6,h 0,h 3,h 1,h 8,cz 10,cz 9,cz 2
sum,0.043107,0.035317,0.030515,0.01709,0.002055,0.0018,0.00138,0.001263,0.0,0.0,0.0

ERROR GATE LOCATION:
7
Now evolving the following mutant:  AddGate_rxx_inGap_2_.qasm

100%|██████████| 6/6 [00:00<00:00, 15.67it/s]
100%|██████████| 10/10 [00:00<00:00, 16.67it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,h 2,rxx 1,h 0,pass/fail
0,0.0,0.0,0.029606,0.0,0.0,0.012433,0.016008,0.0,0.011181,0.0,0.017695,fail
1,0.0,0.0,0.024757,0.0,0.0,0.012790,0.017509,0.0,0.013750,0.0,0.018684,fail
2,0.0,0.0,0.024398,0.0,0.0,0.011131,0.013523,0.0,0.012046,0.0,0.010264,fail
3,0.0,0.0,0.025772,0.0,0.0,0.010095,0.014194,0.0,0.014550,0.0,0.014290,fail
4,0.0,0.0,0.020268,0.0,0.0,0.012787,0.013404,0.0,0.011838,0.0,0.012211,fail
5,0.0,0.0,0.032785,0.0,0.0,0.014110,0.021652,0.0,0.013277,0.0,0.015773,fail
6,0.0,0.0,0.025639,0.0,0.0,0.010890,0.012598,0.0,0.005762,0.0,0.014503,pass
7,0.0,0.0,0.023740,0.0,0.0,0.009483,0.010202,0.0,0.011721,0.0,0.013603,pass
8,0.0,0.0,0.025559,0.0,0.0,0.007565,0.012388,0.0,0.007516,0.0,0.013242,pass
9,0.0,0.0,0.021622,0.0,0.0,0.010248,0.019014,0.0,0.010238,0.0,0.012530,pass
10,0.0,0.0,0.022363,0.0,0.0,0.009349,0.012854,0.0,0.010457,0.0,0.010795,pass
11,0.0,0.0,0.028369,0.0,0.0,0.012106,0.011566,0.0,0.010735,0.0,0.011770,pass
12,0.0,0.0,0.012527,0.0,0.0,0.003962,0.009221,0.0,0.005931,0.0,0.008067,pass
13,0.0,0.0,0.018634,0.0,0.0,0.009827,0.012632,0.0,0.012843,0.0,0.017429,pass
14,0.0,0.0,0.017336,0.0,0.0,0.008602,0.009189,0.0,0.008823,0.0,0.008476,pass
15,0.0,0.0,0.007214,0.0,0.0,0.006144,0.009708,0.0,0.007287,0.0,0.009746,pass

[[       nan        nan 1.2482556         nan        nan 1.15428108
  1.34917857        nan 1.13908205        nan 1.26074752]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 2,h 5,h 4,h 8,h 0,cz 10,cz 9,cz 7,cz 6,cz 3,rxx 1
sum,0.456324,0.454094,0.446489,0.437024,0.425283,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 4,h 2,h 5,h 8,h 0,cz 10,cz 9,cz 7,cz 6,cz 3,rxx 1
sum,0.597088,0.586272,0.585133,0.573404,0.559326,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 4,h 0,h 2,h 5,cz 10,cz 9,cz 7,cz 6,cz 3,rxx 1
sum,0.004003,0.001515,0.001292,0.000964,0.000884,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_rx_inGap_10_.qasm

100%|██████████| 4/4 [00:00<00:00, 11.86it/s]
100%|██████████| 10/10 [00:00<00:00, 13.16it/s]

,cz 10,rx 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.038442,0.193273,0.204221,0.0,0.0,0.017368,0.018422,0.0,0.014467,0.017322,fail
1,0.0,0.053683,0.292919,0.285193,0.0,0.0,0.023963,0.023576,0.0,0.018714,0.018020,fail
2,0.0,0.043482,0.252754,0.231000,0.0,0.0,0.014370,0.021829,0.0,0.016535,0.020119,fail
3,0.0,0.043443,0.239353,0.230793,0.0,0.0,0.020085,0.026261,0.0,0.018397,0.020318,fail
4,0.0,0.046862,0.250745,0.248955,0.0,0.0,0.012390,0.024397,0.0,0.019713,0.015072,pass
5,0.0,0.016128,0.087935,0.085682,0.0,0.0,0.006759,0.011198,0.0,0.006839,0.010557,pass
6,0.0,0.040745,0.233294,0.216459,0.0,0.0,0.014376,0.018375,0.0,0.012300,0.014385,pass
7,0.0,0.035747,0.189356,0.189904,0.0,0.0,0.008569,0.016195,0.0,0.016530,0.019134,pass
8,0.0,0.028504,0.177499,0.151430,0.0,0.0,0.013728,0.015751,0.0,0.013718,0.014796,pass
9,0.0,0.037705,0.206062,0.200310,0.0,0.0,0.014535,0.012261,0.0,0.013618,0.014940,pass
10,0.0,0.052237,0.298561,0.277512,0.0,0.0,0.015381,0.013464,0.0,0.015195,0.019213,pass
11,0.0,0.037178,0.240814,0.197508,0.0,0.0,0.012561,0.006882,0.0,0.008710,0.014645,pass
12,0.0,0.047797,0.294059,0.253919,0.0,0.0,0.017044,0.015146,0.0,0.008780,0.013822,pass
13,0.0,0.033331,0.198452,0.177071,0.0,0.0,0.012835,0.014369,0.0,0.013355,0.014850,pass

[[       nan 1.19928895 1.19766869 1.19928895        nan        nan
  1.26476574 1.16602703        nan 1.09898555 1.07250373]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 3,h 4,h 1,h 0,rx 9,h 7,cz 8,cz 10,cz 6,cz 5,cz 2
sum,0.378322,0.371566,0.345977,0.333544,0.322448,0.322448,0.310071,0.0,0.0,0.0,0.0

custom SCORES

,h 4,h 3,h 1,h 0,rx 9,h 7,cz 8,cz 10,cz 6,cz 5,cz 2
sum,0.489052,0.488606,0.441033,0.422976,0.419125,0.419125,0.402912,0.0,0.0,0.0,0.0

DSTAR SCORES

,cz 8,h 7,rx 9,h 3,h 4,h 0,h 1,cz 10,cz 6,cz 5,cz 2
sum,0.154946,0.150831,0.007326,0.001957,0.001391,0.001383,0.001124,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
9
Now evolving the following mutant:  AddGate_rz_inGap_7_.qasm

100%|██████████| 6/6 [00:00<00:00, 16.86it/s]
100%|██████████| 10/10 [00:00<00:00, 17.14it/s]

,cz 10,cz 9,h 8,cz 7,rz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.020070,0.0,0.0,0.0,0.011173,0.012824,0.0,0.011147,0.011256,fail
1,0.0,0.0,0.027577,0.0,0.0,0.0,0.012935,0.017714,0.0,0.014863,0.013864,fail
2,0.0,0.0,0.020448,0.0,0.0,0.0,0.006569,0.011557,0.0,0.009637,0.009916,fail
3,0.0,0.0,0.028227,0.0,0.0,0.0,0.012937,0.018938,0.0,0.015455,0.013270,fail
4,0.0,0.0,0.020721,0.0,0.0,0.0,0.009016,0.018588,0.0,0.007993,0.008280,fail
5,0.0,0.0,0.029357,0.0,0.0,0.0,0.012158,0.015669,0.0,0.012652,0.014859,fail
6,0.0,0.0,0.030306,0.0,0.0,0.0,0.012775,0.016442,0.0,0.012327,0.011732,pass
7,0.0,0.0,0.024571,0.0,0.0,0.0,0.009097,0.011201,0.0,0.009642,0.010441,pass
8,0.0,0.0,0.031375,0.0,0.0,0.0,0.010044,0.015071,0.0,0.012993,0.011397,pass
9,0.0,0.0,0.032229,0.0,0.0,0.0,0.014105,0.018539,0.0,0.013217,0.015361,pass
10,0.0,0.0,0.030263,0.0,0.0,0.0,0.013869,0.018988,0.0,0.014394,0.016367,pass
11,0.0,0.0,0.012127,0.0,0.0,0.0,0.006568,0.007271,0.0,0.003520,0.006770,pass
12,0.0,0.0,0.009946,0.0,0.0,0.0,0.005218,0.009321,0.0,0.006515,0.008381,pass
13,0.0,0.0,0.017013,0.0,0.0,0.0,0.011097,0.006861,0.0,0.007719,0.008529,pass
14,0.0,0.0,0.021323,0.0,0.0,0.0,0.010420,0.010423,0.0,0.008772,0.009072,pass
15,0.0,0.0,0.017093,0.0,0.0,0.0,0.006405,0.010709,0.0,0.008423,0.009620,pass

[[       nan        nan 1.20316363        nan        nan        nan
  1.19806077 1.19242123        nan 1.29245085 1.24783248]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 3,h 1,h 0,h 4,h 8,cz 10,cz 9,cz 7,rz 6,cz 5,cz 2
sum,0.432907,0.423862,0.398879,0.394123,0.392867,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 3,h 1,h 0,h 4,h 8,cz 10,cz 9,cz 7,rz 6,cz 5,cz 2
sum,0.561959,0.560817,0.523312,0.512169,0.511038,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 3,h 1,h 0,h 4,cz 10,cz 9,cz 7,rz 6,cz 5,cz 2
sum,0.003442,0.001483,0.000844,0.000836,0.000688,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
6
Now evolving the following mutant:  AddGate_ry_inGap_4_.qasm

100%|██████████| 10/10 [00:00<00:00, 14.92it/s]
100%|██████████| 10/10 [00:00<00:00, 13.14it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,ry 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.026741,0.0,0.0,0.010996,0.016502,0.052112,0.0,0.009738,0.013951,fail
1,0.0,0.0,0.019583,0.0,0.0,0.012816,0.019338,0.061092,0.0,0.010215,0.012364,fail
2,0.0,0.0,0.023533,0.0,0.0,0.012737,0.014030,0.045269,0.0,0.004888,0.009061,fail
3,0.0,0.0,0.023267,0.0,0.0,0.012480,0.014165,0.046686,0.0,0.009627,0.012768,fail
4,0.0,0.0,0.016786,0.0,0.0,0.008753,0.014622,0.048858,0.0,0.010275,0.012553,fail
5,0.0,0.0,0.027261,0.0,0.0,0.013616,0.020152,0.057579,0.0,0.011048,0.013796,fail
6,0.0,0.0,0.022456,0.0,0.0,0.009228,0.017226,0.051335,0.0,0.008433,0.008730,fail
7,0.0,0.0,0.023227,0.0,0.0,0.012558,0.015889,0.049752,0.0,0.010082,0.010938,fail
8,0.0,0.0,0.019371,0.0,0.0,0.013001,0.010218,0.033140,0.0,0.008636,0.009421,fail
9,0.0,0.0,0.020442,0.0,0.0,0.009956,0.016173,0.051017,0.0,0.007993,0.010290,fail
10,0.0,0.0,0.021693,0.0,0.0,0.016402,0.015383,0.047150,0.0,0.007760,0.012600,pass
11,0.0,0.0,0.025832,0.0,0.0,0.007145,0.013730,0.043684,0.0,0.007967,0.008658,pass
12,0.0,0.0,0.020501,0.0,0.0,0.010448,0.011234,0.034611,0.0,0.009360,0.014146,pass
13,0.0,0.0,0.020912,0.0,0.0,0.009374,0.008205,0.025603,0.0,0.005762,0.007073,pass
14,0.0,0.0,0.028031,0.0,0.0,0.012384,0.015442,0.046010,0.0,0.010190,0.009733,pass
15,0.0,0.0,0.031311,0.0,0.0,0.011893,0.016803,0.047558,0.0,0.010312,0.013234,pass
16,0.0,0.0,0.017533,0.0,0.0,0.011235,0.013328,0.041305,0.0,0.006306,0.010094,pass
17,0.0,0.0,0.032233,0.0,0.0,0.014257,0.018940,0.054470,0.0,0.013610,0.011039,pass
18,0.0,0.0,0.032151,0.0,0.0,0.013631,0.015765,0.044114,0.0,0.012366,0.014453,pass
19,0.0,0.0,0.023281,0.0,0.0,0.011194,0.014008,0.038043,0.0,0.011271,0.008412,pass

[[       nan        nan 1.22431324        nan        nan 1.17236015
  1.27291488 1.22961662        nan 1.2149522  1.22513064]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,ry 3,h 4,h 0,h 5,h 1,h 8,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.540402,0.525697,0.50992,0.496107,0.489318,0.467646,0.0,0.0,0.0,0.0,0.0

custom SCORES

,ry 3,h 4,h 0,h 5,h 1,h 8,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.706524,0.692989,0.666099,0.641511,0.637942,0.610782,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,ry 3,h 8,h 4,h 5,h 0,h 1,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.023684,0.004835,0.002471,0.001333,0.001283,0.000819,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
3
Now evolving the following mutant:  AddGate_rx_inGap_2_.qasm

100%|██████████| 3/3 [00:00<00:00, 13.81it/s]
100%|██████████| 10/10 [00:00<00:00, 15.42it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,h 2,rx 1,h 0,pass/fail
0,0.0,0.0,0.021761,0.0,0.0,0.013961,0.012217,0.0,0.010698,0.0,0.012236,fail
1,0.0,0.0,0.027396,0.0,0.0,0.012508,0.021923,0.0,0.014548,0.0,0.015618,fail
2,0.0,0.0,0.027808,0.0,0.0,0.015541,0.015639,0.0,0.012876,0.0,0.015487,fail
3,0.0,0.0,0.022396,0.0,0.0,0.008633,0.015162,0.0,0.010340,0.0,0.014475,pass
4,0.0,0.0,0.012405,0.0,0.0,0.006415,0.012127,0.0,0.008722,0.0,0.009394,pass
5,0.0,0.0,0.023397,0.0,0.0,0.007951,0.016065,0.0,0.014162,0.0,0.008407,pass
6,0.0,0.0,0.020093,0.0,0.0,0.009797,0.018764,0.0,0.010242,0.0,0.014464,pass
7,0.0,0.0,0.020877,0.0,0.0,0.008430,0.011346,0.0,0.008820,0.0,0.011578,pass
8,0.0,0.0,0.022745,0.0,0.0,0.008322,0.013328,0.0,0.009346,0.0,0.010575,pass
9,0.0,0.0,0.017653,0.0,0.0,0.011111,0.011508,0.0,0.008318,0.0,0.010758,pass
10,0.0,0.0,0.025483,0.0,0.0,0.013181,0.015869,0.0,0.012379,0.0,0.014006,pass
11,0.0,0.0,0.021791,0.0,0.0,0.007577,0.013797,0.0,0.008593,0.0,0.011319,pass
12,0.0,0.0,0.020305,0.0,0.0,0.005971,0.015969,0.0,0.009154,0.0,0.013148,pass

[[       nan        nan 1.08392272        nan        nan 1.10978523
  1.32124357        nan 1.14482881        nan 1.08103481]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 5,h 2,h 8,h 0,h 4,cz 10,cz 9,cz 7,cz 6,cz 3,rx 1
sum,0.324653,0.275852,0.270898,0.268424,0.256969,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 5,h 2,h 8,h 4,h 0,cz 10,cz 9,cz 7,cz 6,cz 3,rx 1
sum,0.414727,0.354802,0.344306,0.341849,0.340968,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 4,h 0,h 5,h 2,cz 10,cz 9,cz 7,cz 6,cz 3,rx 1
sum,0.001847,0.000788,0.000602,0.000572,0.000469,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_cswap_inGap_4_.qasm

100%|██████████| 6/6 [00:00<00:00,  9.83it/s]
100%|██████████| 10/10 [00:01<00:00,  9.56it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cswap 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.023193,0.0,0.0,0.011879,0.012103,0.068710,0.0,0.006597,0.007252,fail
1,0.0,0.0,0.027628,0.0,0.0,0.012530,0.018586,0.060158,0.0,0.007656,0.007698,fail
2,0.0,0.0,0.032766,0.0,0.0,0.012554,0.018360,0.057087,0.0,0.007626,0.008570,fail
3,0.0,0.0,0.013797,0.0,0.0,0.006075,0.010470,0.060265,0.0,0.007910,0.007845,fail
4,0.0,0.0,0.021994,0.0,0.0,0.011226,0.014940,0.059972,0.0,0.004657,0.008048,fail
5,0.0,0.0,0.034639,0.0,0.0,0.016080,0.018352,0.067351,0.0,0.008893,0.007855,fail
6,0.0,0.0,0.027306,0.0,0.0,0.015272,0.019081,0.054602,0.0,0.009828,0.010479,pass
7,0.0,0.0,0.023938,0.0,0.0,0.010063,0.016161,0.047999,0.0,0.006959,0.007531,pass
8,0.0,0.0,0.026369,0.0,0.0,0.010385,0.012362,0.055365,0.0,0.006410,0.009691,pass
9,0.0,0.0,0.022891,0.0,0.0,0.009159,0.011941,0.054885,0.0,0.005863,0.006796,pass
10,0.0,0.0,0.020436,0.0,0.0,0.008343,0.008547,0.052896,0.0,0.004636,0.006058,pass
11,0.0,0.0,0.023999,0.0,0.0,0.010604,0.010589,0.052107,0.0,0.005604,0.006344,pass
12,0.0,0.0,0.015268,0.0,0.0,0.006078,0.013919,0.060358,0.0,0.006323,0.007289,pass
13,0.0,0.0,0.027624,0.0,0.0,0.012495,0.015046,0.058918,0.0,0.009725,0.009855,pass
14,0.0,0.0,0.025065,0.0,0.0,0.010314,0.009371,0.047217,0.0,0.006610,0.006281,pass
15,0.0,0.0,0.018187,0.0,0.0,0.010017,0.013057,0.053386,0.0,0.004477,0.008481,pass

[[       nan        nan 1.34942635        nan        nan 1.37154279
  1.20152884 1.10364723        nan 1.23120383 1.08782482]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 4,cswap 3,h 5,h 8,h 1,h 0,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.416409,0.409912,0.406438,0.399943,0.394798,0.374928,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 5,h 4,h 8,cswap 3,h 1,h 0,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.545799,0.541491,0.534866,0.523011,0.516317,0.476892,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,cswap 3,h 8,h 4,h 5,h 0,h 1,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.021343,0.003807,0.001405,0.000811,0.000368,0.00031,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
3
Now evolving the following mutant:  AddGate_rxx_inGap_11_.qasm

100%|██████████| 6/6 [00:00<00:00,  8.95it/s]
100%|██████████| 10/10 [00:01<00:00,  8.43it/s]

,cz 10,rxx 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.163747,0.227415,0.057776,0.0,0.119244,0.019706,0.060042,0.139363,0.112219,0.092689,fail
1,0.0,0.226311,0.380382,0.079649,0.0,0.190718,0.051699,0.060114,0.166287,0.125260,0.115474,fail
2,0.0,0.186287,0.243110,0.045731,0.0,0.163117,0.036653,0.036672,0.142457,0.110373,0.095253,fail
3,0.0,0.192496,0.292828,0.058344,0.0,0.164831,0.039289,0.064106,0.151789,0.110001,0.108719,fail
4,0.0,0.223506,0.319745,0.055999,0.0,0.187825,0.050602,0.081603,0.172618,0.135754,0.118308,fail
5,0.0,0.207399,0.307791,0.062453,0.0,0.176037,0.045232,0.059651,0.146049,0.094140,0.119686,fail
6,0.0,0.203643,0.282456,0.056794,0.0,0.153692,0.032813,0.056460,0.150367,0.097577,0.125482,pass
7,0.0,0.123193,0.142452,0.033532,0.0,0.100536,0.020262,0.034940,0.096393,0.074314,0.070439,pass
8,0.0,0.223505,0.334998,0.055070,0.0,0.182960,0.049109,0.058176,0.164191,0.108660,0.122928,pass
9,0.0,0.198087,0.236752,0.032416,0.0,0.168542,0.040422,0.056843,0.153622,0.106104,0.112424,pass
10,0.0,0.166081,0.262447,0.057927,0.0,0.135024,0.033607,0.058471,0.137769,0.115489,0.085625,pass
11,0.0,0.199023,0.247354,0.042072,0.0,0.164920,0.035763,0.055437,0.150152,0.100536,0.119702,pass
12,0.0,0.124509,0.157251,0.028186,0.0,0.105201,0.027888,0.030973,0.093615,0.058700,0.072689,pass
13,0.0,0.203342,0.327752,0.063312,0.0,0.180764,0.043649,0.054529,0.147428,0.107280,0.103677,pass
14,0.0,0.234650,0.298614,0.057549,0.0,0.183643,0.034689,0.055289,0.175932,0.110933,0.140902,pass
15,0.0,0.186950,0.236426,0.042204,0.0,0.144829,0.029918,0.054792,0.139939,0.089557,0.106526,pass

[[       nan 1.13179704 1.28850473 1.32766455        nan 1.14228189
  1.27557342 1.35184074 1.12753341 1.18433377 1.10457471]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 7,h 1,h 3,cz 8,h 4,cz 5,cz 2,rxx 9,h 0,cz 10,cz 6
sum,0.434194,0.415082,0.412468,0.412137,0.411264,0.397232,0.394577,0.391724,0.380076,0.0,0.0

custom SCORES

,h 7,h 3,cz 8,h 4,h 1,cz 5,cz 2,rxx 9,h 0,cz 10,cz 6
sum,0.578309,0.551866,0.544897,0.542414,0.53798,0.510669,0.505801,0.502563,0.485032,0.0,0.0

DSTAR SCORES

,cz 8,rxx 9,cz 5,cz 2,h 1,h 0,h 3,h 7,h 4,cz 10,cz 6
sum,0.367959,0.183059,0.133448,0.113877,0.06787,0.059865,0.020132,0.020029,0.009316,0.0,0.0

ERROR GATE LOCATION:
9
Now evolving the following mutant:  AddGate_p_inGap_12_.qasm

100%|██████████| 7/7 [00:00<00:00, 16.78it/s]
100%|██████████| 10/10 [00:00<00:00, 15.61it/s]

,cz 10,cz 9,h 8,cz 7,p 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.023745,0.0,0.0,0.0,0.013918,0.012853,0.0,0.012176,0.013218,fail
1,0.0,0.0,0.024870,0.0,0.0,0.0,0.011252,0.013338,0.0,0.012240,0.016915,fail
2,0.0,0.0,0.033466,0.0,0.0,0.0,0.012572,0.020529,0.0,0.014701,0.016369,fail
3,0.0,0.0,0.022238,0.0,0.0,0.0,0.014275,0.018125,0.0,0.010201,0.015101,fail
4,0.0,0.0,0.032605,0.0,0.0,0.0,0.013444,0.016070,0.0,0.015749,0.014559,fail
5,0.0,0.0,0.014728,0.0,0.0,0.0,0.008731,0.014854,0.0,0.011165,0.011077,fail
6,0.0,0.0,0.027677,0.0,0.0,0.0,0.012548,0.020606,0.0,0.015717,0.015945,fail
7,0.0,0.0,0.018420,0.0,0.0,0.0,0.010693,0.013134,0.0,0.007804,0.013541,pass
8,0.0,0.0,0.020322,0.0,0.0,0.0,0.007777,0.015499,0.0,0.009171,0.010650,pass
9,0.0,0.0,0.025528,0.0,0.0,0.0,0.011470,0.020811,0.0,0.011311,0.011884,pass
10,0.0,0.0,0.020932,0.0,0.0,0.0,0.010939,0.016149,0.0,0.012776,0.013271,pass
11,0.0,0.0,0.023561,0.0,0.0,0.0,0.014779,0.018289,0.0,0.011081,0.011239,pass
12,0.0,0.0,0.015744,0.0,0.0,0.0,0.008940,0.008921,0.0,0.006933,0.009874,pass
13,0.0,0.0,0.029935,0.0,0.0,0.0,0.015673,0.017859,0.0,0.011571,0.009000,pass
14,0.0,0.0,0.019136,0.0,0.0,0.0,0.011048,0.017347,0.0,0.013302,0.008805,pass
15,0.0,0.0,0.020019,0.0,0.0,0.0,0.011535,0.014861,0.0,0.014259,0.014066,pass
16,0.0,0.0,0.025879,0.0,0.0,0.0,0.009420,0.012970,0.0,0.010270,0.015157,pass

[[       nan        nan 1.30632635        nan        nan        nan
  1.15203346 1.23944311        nan 1.19897964 1.14751939]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 0,h 1,h 8,h 4,h 3,cz 10,cz 9,cz 7,p 6,cz 5,cz 2
sum,0.467596,0.458764,0.449666,0.435846,0.42751,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 0,h 8,h 1,h 4,h 3,cz 10,cz 9,cz 7,p 6,cz 5,cz 2
sum,0.601739,0.596519,0.596276,0.561373,0.559978,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 3,h 0,h 1,h 4,cz 10,cz 9,cz 7,p 6,cz 5,cz 2
sum,0.004454,0.001893,0.001496,0.001189,0.001058,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
6
Now evolving the following mutant:  AddGate_s_inGap_3_.qasm

100%|██████████| 4/4 [00:00<00:00, 16.18it/s]
100%|██████████| 10/10 [00:00<00:00, 16.69it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,sdg 2,h 1,h 0,pass/fail
0,0.0,0.0,0.026216,0.0,0.0,0.014167,0.014755,0.0,0.0,0.010173,0.016366,fail
1,0.0,0.0,0.026514,0.0,0.0,0.009728,0.016111,0.0,0.0,0.013704,0.014220,fail
2,0.0,0.0,0.028957,0.0,0.0,0.011276,0.018180,0.0,0.0,0.012068,0.008714,fail
3,0.0,0.0,0.021374,0.0,0.0,0.006331,0.012650,0.0,0.0,0.009511,0.010970,fail
4,0.0,0.0,0.023106,0.0,0.0,0.011439,0.013915,0.0,0.0,0.010550,0.010839,pass
5,0.0,0.0,0.017296,0.0,0.0,0.006812,0.007148,0.0,0.0,0.006274,0.012547,pass
6,0.0,0.0,0.027272,0.0,0.0,0.010042,0.018249,0.0,0.0,0.011964,0.010206,pass
7,0.0,0.0,0.024396,0.0,0.0,0.009522,0.014289,0.0,0.0,0.010239,0.010265,pass
8,0.0,0.0,0.021179,0.0,0.0,0.010893,0.012859,0.0,0.0,0.010478,0.010156,pass
9,0.0,0.0,0.025738,0.0,0.0,0.011155,0.015639,0.0,0.0,0.006884,0.011047,pass
10,0.0,0.0,0.017603,0.0,0.0,0.006439,0.007188,0.0,0.0,0.003105,0.005878,pass
11,0.0,0.0,0.019492,0.0,0.0,0.010308,0.009329,0.0,0.0,0.008531,0.007768,pass
12,0.0,0.0,0.022240,0.0,0.0,0.009679,0.012370,0.0,0.0,0.005963,0.011993,pass
13,0.0,0.0,0.024126,0.0,0.0,0.013895,0.014615,0.0,0.0,0.008314,0.009681,pass

[[       nan        nan 1.12388125        nan        nan 1.36546273
  1.17867307        nan        nan 1.20588897 1.30225514]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,h 0,h 4,h 8,h 5,cz 10,cz 9,cz 7,cz 6,cz 3,sdg 2
sum,0.355799,0.333683,0.329402,0.316614,0.292915,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 1,h 0,h 4,h 8,h 5,cz 10,cz 9,cz 7,cz 6,cz 3,sdg 2
sum,0.463063,0.442318,0.426467,0.405573,0.392906,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 4,h 0,h 1,h 5,cz 10,cz 9,cz 7,cz 6,cz 3,sdg 2
sum,0.002515,0.000923,0.000616,0.000506,0.00042,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_ry_inGap_2_.qasm

100%|██████████| 10/10 [00:00<00:00, 16.90it/s]
100%|██████████| 10/10 [00:00<00:00, 17.44it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,h 2,ry 1,h 0,pass/fail
0,0.0,0.0,0.022842,0.0,0.0,0.014184,0.016663,0.0,0.013090,0.007817,0.011591,fail
1,0.0,0.0,0.025900,0.0,0.0,0.015184,0.017945,0.0,0.015206,0.009255,0.008775,fail
2,0.0,0.0,0.022949,0.0,0.0,0.009132,0.013360,0.0,0.012390,0.007184,0.008675,fail
3,0.0,0.0,0.028994,0.0,0.0,0.015227,0.020771,0.0,0.015835,0.009745,0.015147,fail
4,0.0,0.0,0.023727,0.0,0.0,0.012528,0.016340,0.0,0.013997,0.008383,0.013215,fail
5,0.0,0.0,0.024013,0.0,0.0,0.008404,0.016928,0.0,0.008880,0.005019,0.007872,fail
6,0.0,0.0,0.015234,0.0,0.0,0.010072,0.015688,0.0,0.010030,0.005874,0.011871,fail
7,0.0,0.0,0.015224,0.0,0.0,0.010932,0.012443,0.0,0.009616,0.005517,0.010359,fail
8,0.0,0.0,0.016823,0.0,0.0,0.011460,0.010649,0.0,0.011388,0.006364,0.013009,fail
9,0.0,0.0,0.030210,0.0,0.0,0.011434,0.016612,0.0,0.014125,0.008822,0.007563,fail
10,0.0,0.0,0.020876,0.0,0.0,0.008352,0.011052,0.0,0.008852,0.005325,0.009118,pass
11,0.0,0.0,0.017805,0.0,0.0,0.008305,0.009059,0.0,0.006379,0.003945,0.006234,pass
12,0.0,0.0,0.020899,0.0,0.0,0.010667,0.015432,0.0,0.006713,0.004141,0.009232,pass
13,0.0,0.0,0.020267,0.0,0.0,0.012396,0.013343,0.0,0.009622,0.006009,0.010099,pass
14,0.0,0.0,0.026166,0.0,0.0,0.013541,0.013300,0.0,0.009245,0.005808,0.010593,pass
15,0.0,0.0,0.013492,0.0,0.0,0.005887,0.010569,0.0,0.006771,0.004448,0.005022,pass
16,0.0,0.0,0.018403,0.0,0.0,0.009025,0.009459,0.0,0.007344,0.004524,0.004163,pass
17,0.0,0.0,0.023242,0.0,0.0,0.014579,0.015221,0.0,0.012817,0.008101,0.010924,pass
18,0.0,0.0,0.020287,0.0,0.0,0.010767,0.017644,0.0,0.012477,0.007715,0.010883,pass
19,0.0,0.0,0.029006,0.0,0.0,0.013362,0.015138,0.0,0.008355,0.005019,0.008655,pass

[[       nan        nan 1.33719473        nan        nan 1.28434261
  1.31965632        nan 1.27132755 1.31725727 1.40147293]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 2,ry 1,h 0,h 4,h 5,h 8,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.584416,0.573415,0.559983,0.547255,0.5259,0.517731,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 2,ry 1,h 0,h 4,h 5,h 8,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.770162,0.762249,0.756184,0.727802,0.694758,0.690808,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 4,h 2,h 5,h 0,ry 1,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.004999,0.002446,0.001538,0.001391,0.001158,0.000544,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_rxx_inGap_10_.qasm

100%|██████████| 6/6 [00:00<00:00,  9.84it/s]
100%|██████████| 10/10 [00:01<00:00,  9.11it/s]

,cz 10,rxx 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.224693,0.278918,0.128343,0.230454,0.0,0.024115,0.106398,0.0,0.019444,0.018252,fail
1,0.0,0.295958,0.347407,0.206440,0.326511,0.0,0.042421,0.128628,0.0,0.028964,0.026990,fail
2,0.0,0.261639,0.427057,0.192676,0.300070,0.0,0.034523,0.087883,0.0,0.016005,0.033996,fail
3,0.0,0.269431,0.399230,0.211867,0.274399,0.0,0.031558,0.100398,0.0,0.020201,0.031167,fail
4,0.0,0.242139,0.356181,0.181193,0.273160,0.0,0.028604,0.097701,0.0,0.023002,0.026436,fail
5,0.0,0.234435,0.298303,0.169472,0.258804,0.0,0.030124,0.100148,0.0,0.022796,0.020485,fail
6,0.0,0.165667,0.239919,0.135209,0.160057,0.0,0.019705,0.070476,0.0,0.017387,0.018832,pass
7,0.0,0.232590,0.316832,0.179227,0.263354,0.0,0.030517,0.086326,0.0,0.015124,0.028082,pass
8,0.0,0.193684,0.231411,0.098984,0.170014,0.0,0.021229,0.105419,0.0,0.018710,0.018185,pass
9,0.0,0.252872,0.312014,0.151261,0.269814,0.0,0.035856,0.106061,0.0,0.014640,0.018200,pass
10,0.0,0.134975,0.150466,0.095044,0.164535,0.0,0.027835,0.073452,0.0,0.016669,0.014323,pass
11,0.0,0.240239,0.340495,0.186907,0.223141,0.0,0.024649,0.105627,0.0,0.019234,0.025902,pass
12,0.0,0.226057,0.295677,0.127015,0.222530,0.0,0.029424,0.102142,0.0,0.015021,0.020305,pass
13,0.0,0.207981,0.219820,0.176791,0.226023,0.0,0.028259,0.093157,0.0,0.026072,0.020771,pass
14,0.0,0.261078,0.344037,0.171398,0.241469,0.0,0.025161,0.107742,0.0,0.014693,0.022595,pass
15,0.0,0.216201,0.286466,0.162300,0.203296,0.0,0.029085,0.080163,0.0,0.015207,0.020026,pass

[[       nan 1.16191421 1.21605284 1.16625028 1.1777504         nan
  1.33018507 1.24247539        nan 1.33256884 1.29651945]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,cz 6,cz 8,h 0,h 1,h 7,rxx 9,h 4,h 3,cz 10,cz 5,cz 2
sum,0.436859,0.43497,0.431566,0.430163,0.423442,0.417608,0.413213,0.400301,0.0,0.0,0.0

custom SCORES

,h 1,h 0,cz 8,cz 6,h 4,h 7,rxx 9,h 3,cz 10,cz 5,cz 2
sum,0.573469,0.571449,0.567207,0.565487,0.550625,0.546901,0.538914,0.524642,0.0,0.0,0.0

DSTAR SCORES

,cz 8,cz 6,rxx 9,h 7,h 3,h 4,h 0,h 1,cz 10,cz 5,cz 2
sum,0.508159,0.339736,0.287244,0.158747,0.055671,0.005838,0.003988,0.002755,0.0,0.0,0.0

ERROR GATE LOCATION:
9
Now evolving the following mutant:  AddGate_s_inGap_2_.qasm

100%|██████████| 7/7 [00:00<00:00, 16.55it/s]
100%|██████████| 10/10 [00:00<00:00, 16.56it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,h 2,sdg 1,h 0,pass/fail
0,0.0,0.0,0.028757,0.0,0.0,0.015331,0.012974,0.0,0.013455,0.011939,0.014360,fail
1,0.0,0.0,0.022255,0.0,0.0,0.006683,0.014444,0.0,0.009755,0.008656,0.007976,fail
2,0.0,0.0,0.020259,0.0,0.0,0.012048,0.018358,0.0,0.011857,0.010565,0.014244,fail
3,0.0,0.0,0.026077,0.0,0.0,0.012429,0.018789,0.0,0.012205,0.010861,0.014626,fail
4,0.0,0.0,0.029542,0.0,0.0,0.013320,0.021046,0.0,0.013693,0.012077,0.014137,fail
5,0.0,0.0,0.024872,0.0,0.0,0.006943,0.013139,0.0,0.007973,0.006971,0.009791,fail
6,0.0,0.0,0.025236,0.0,0.0,0.012710,0.020755,0.0,0.013652,0.012118,0.011608,fail
7,0.0,0.0,0.029449,0.0,0.0,0.013325,0.014280,0.0,0.011301,0.010018,0.016548,pass
8,0.0,0.0,0.020094,0.0,0.0,0.009204,0.009653,0.0,0.010212,0.009025,0.009933,pass
9,0.0,0.0,0.018121,0.0,0.0,0.008377,0.005330,0.0,0.008215,0.007236,0.006411,pass
10,0.0,0.0,0.022736,0.0,0.0,0.013610,0.012337,0.0,0.013684,0.012163,0.014713,pass
11,0.0,0.0,0.022969,0.0,0.0,0.009415,0.013242,0.0,0.009804,0.008723,0.014595,pass
12,0.0,0.0,0.023369,0.0,0.0,0.011809,0.019113,0.0,0.009352,0.008318,0.012598,pass
13,0.0,0.0,0.034216,0.0,0.0,0.018724,0.017317,0.0,0.008396,0.007413,0.014389,pass
14,0.0,0.0,0.022583,0.0,0.0,0.008730,0.012449,0.0,0.010011,0.008824,0.013669,pass
15,0.0,0.0,0.024842,0.0,0.0,0.012348,0.010250,0.0,0.009110,0.008152,0.013253,pass
16,0.0,0.0,0.022649,0.0,0.0,0.010440,0.013387,0.0,0.007333,0.006549,0.012704,pass

[[       nan        nan 1.16833203        nan        nan 1.35047832
  1.2327658         nan 1.16052968 1.15901809 1.1803278 ]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 4,h 2,sdg 1,h 8,h 5,h 0,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.484097,0.458811,0.458548,0.423413,0.40658,0.402407,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 4,h 2,sdg 1,h 8,h 5,h 0,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.633292,0.591927,0.591415,0.547085,0.543849,0.52115,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 4,h 0,h 2,h 5,sdg 1,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.004326,0.002004,0.001055,0.000961,0.000887,0.000756,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_rx_inGap_15_.qasm

100%|██████████| 8/8 [00:00<00:00,  8.45it/s]
100%|██████████| 10/10 [00:01<00:00,  8.20it/s]

,rx 10,cz 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.078340,0.292973,0.478285,0.442192,0.0,0.0,0.032626,0.028033,0.0,0.029025,0.030507,fail
1,0.055217,0.194250,0.329474,0.311675,0.0,0.0,0.027629,0.025836,0.0,0.022610,0.014030,fail
2,0.060471,0.230470,0.416587,0.341332,0.0,0.0,0.022140,0.026727,0.0,0.023065,0.013421,fail
3,0.074653,0.262147,0.481350,0.421382,0.0,0.0,0.032356,0.027260,0.0,0.030076,0.033635,fail
4,0.092992,0.351484,0.625089,0.524898,0.0,0.0,0.032817,0.039837,0.0,0.034857,0.033429,fail
5,0.050654,0.192955,0.390314,0.285916,0.0,0.0,0.011280,0.020832,0.0,0.021227,0.024029,fail
6,0.084053,0.326997,0.565528,0.474441,0.0,0.0,0.041246,0.030566,0.0,0.028201,0.024053,fail
7,0.092124,0.373393,0.695898,0.519999,0.0,0.0,0.018432,0.031726,0.0,0.027633,0.027221,fail
8,0.080973,0.295178,0.469320,0.457054,0.0,0.0,0.030969,0.041488,0.0,0.032034,0.023867,pass
9,0.063548,0.227876,0.391638,0.358700,0.0,0.0,0.022055,0.021719,0.0,0.022649,0.023726,pass
10,0.097272,0.330875,0.590620,0.549054,0.0,0.0,0.029895,0.043235,0.0,0.033927,0.023641,pass
11,0.036278,0.138226,0.234039,0.204775,0.0,0.0,0.012925,0.023814,0.0,0.011286,0.013958,pass
12,0.062372,0.259937,0.394599,0.352059,0.0,0.0,0.016951,0.035137,0.0,0.014649,0.023422,pass
13,0.074471,0.302654,0.587934,0.420352,0.0,0.0,0.019878,0.021319,0.0,0.021763,0.029991,pass
14,0.076066,0.249854,0.427199,0.429355,0.0,0.0,0.041006,0.026368,0.0,0.032241,0.020335,pass
15,0.061382,0.234115,0.438965,0.346473,0.0,0.0,0.020711,0.027499,0.0,0.021562,0.021559,pass
16,0.063907,0.237026,0.402676,0.360724,0.0,0.0,0.030649,0.024735,0.0,0.022251,0.020430,pass
17,0.080493,0.269073,0.482841,0.454348,0.0,0.0,0.029294,0.041194,0.0,0.025221,0.021792,pass

[[1.26411683 1.3427377  1.3979037  1.26411683        nan        nan
  1.50996014 1.38072496        nan 1.28685322 1.34322604]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,cz 8,h 0,cz 9,h 4,rx 10,h 7,h 3,cz 6,cz 5,cz 2
sum,0.477007,0.473977,0.473529,0.466438,0.462136,0.457885,0.457885,0.429567,0.0,0.0,0.0

custom SCORES

,cz 8,h 4,h 0,h 1,cz 9,rx 10,h 7,h 3,cz 6,cz 5,cz 2
sum,0.63962,0.636588,0.632543,0.630467,0.623014,0.602591,0.602591,0.577845,0.0,0.0,0.0

DSTAR SCORES

,cz 8,h 7,cz 9,rx 10,h 3,h 4,h 1,h 0,cz 6,cz 5,cz 2
sum,1.27703,0.92472,0.469345,0.039824,0.006414,0.005785,0.0057,0.00488,0.0,0.0,0.0

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_rxx_inGap_1_.qasm

100%|██████████| 6/6 [00:00<00:00, 15.60it/s]
100%|██████████| 10/10 [00:00<00:00, 16.67it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,h 2,h 1,rxx 0,pass/fail
0,0.0,0.0,0.017498,0.0,0.0,0.012483,0.014721,0.0,0.012429,0.010285,0.0,fail
1,0.0,0.0,0.020933,0.0,0.0,0.008266,0.015276,0.0,0.009862,0.010749,0.0,fail
2,0.0,0.0,0.023651,0.0,0.0,0.010325,0.014315,0.0,0.009124,0.015556,0.0,fail
3,0.0,0.0,0.024409,0.0,0.0,0.012205,0.017606,0.0,0.009663,0.014944,0.0,fail
4,0.0,0.0,0.026841,0.0,0.0,0.016771,0.011674,0.0,0.012423,0.017994,0.0,fail
5,0.0,0.0,0.033112,0.0,0.0,0.013316,0.022368,0.0,0.011555,0.018974,0.0,fail
6,0.0,0.0,0.026000,0.0,0.0,0.009077,0.014961,0.0,0.007231,0.010228,0.0,pass
7,0.0,0.0,0.022709,0.0,0.0,0.010999,0.015039,0.0,0.010115,0.016190,0.0,pass
8,0.0,0.0,0.019884,0.0,0.0,0.010204,0.015962,0.0,0.009581,0.012268,0.0,pass
9,0.0,0.0,0.028230,0.0,0.0,0.012947,0.015820,0.0,0.013016,0.013050,0.0,pass
10,0.0,0.0,0.029764,0.0,0.0,0.012668,0.019179,0.0,0.011542,0.018605,0.0,pass
11,0.0,0.0,0.010470,0.0,0.0,0.006492,0.009796,0.0,0.008929,0.010566,0.0,pass
12,0.0,0.0,0.012030,0.0,0.0,0.010301,0.014305,0.0,0.009886,0.012980,0.0,pass
13,0.0,0.0,0.015095,0.0,0.0,0.009867,0.012109,0.0,0.010947,0.013198,0.0,pass
14,0.0,0.0,0.017964,0.0,0.0,0.009611,0.014010,0.0,0.005594,0.008948,0.0,pass
15,0.0,0.0,0.020204,0.0,0.0,0.010526,0.018536,0.0,0.012581,0.014314,0.0,pass

[[       nan        nan 1.35662116        nan        nan 1.37154216
  1.39857791        nan 1.1463533  1.28633384        nan]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 8,h 5,h 1,h 2,h 4,cz 10,cz 9,cz 7,cz 6,cz 3,rxx 0
sum,0.419859,0.416718,0.404396,0.395528,0.390593,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 8,h 5,h 1,h 4,h 2,cz 10,cz 9,cz 7,cz 6,cz 3,rxx 0
sum,0.562256,0.559605,0.534443,0.527161,0.508882,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 4,h 1,h 5,h 2,cz 10,cz 9,cz 7,cz 6,cz 3,rxx 0
sum,0.003458,0.001497,0.001278,0.000882,0.000694,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_id_inGap_9_.qasm

100%|██████████| 6/6 [00:00<00:00, 15.85it/s]
100%|██████████| 10/10 [00:00<00:00, 16.27it/s]

,cz 10,cz 9,id 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.0,0.023022,0.0,0.0,0.008655,0.007084,0.0,0.009109,0.010286,fail
1,0.0,0.0,0.0,0.024639,0.0,0.0,0.009141,0.016060,0.0,0.008548,0.010548,fail
2,0.0,0.0,0.0,0.024121,0.0,0.0,0.010614,0.019529,0.0,0.010667,0.016892,fail
3,0.0,0.0,0.0,0.027822,0.0,0.0,0.012337,0.019300,0.0,0.011512,0.010192,fail
4,0.0,0.0,0.0,0.032080,0.0,0.0,0.015135,0.019220,0.0,0.009329,0.011002,fail
5,0.0,0.0,0.0,0.019289,0.0,0.0,0.011175,0.019700,0.0,0.011586,0.015608,fail
6,0.0,0.0,0.0,0.020274,0.0,0.0,0.008005,0.012209,0.0,0.009265,0.011321,pass
7,0.0,0.0,0.0,0.017580,0.0,0.0,0.012136,0.013332,0.0,0.012409,0.012107,pass
8,0.0,0.0,0.0,0.021426,0.0,0.0,0.012713,0.018005,0.0,0.009910,0.015433,pass
9,0.0,0.0,0.0,0.017139,0.0,0.0,0.010570,0.013049,0.0,0.013702,0.012075,pass
10,0.0,0.0,0.0,0.027927,0.0,0.0,0.012912,0.019121,0.0,0.011500,0.011192,pass
11,0.0,0.0,0.0,0.020510,0.0,0.0,0.011693,0.019005,0.0,0.011658,0.012854,pass
12,0.0,0.0,0.0,0.017774,0.0,0.0,0.006435,0.010212,0.0,0.007764,0.006045,pass
13,0.0,0.0,0.0,0.020083,0.0,0.0,0.008756,0.017413,0.0,0.010541,0.012282,pass
14,0.0,0.0,0.0,0.027516,0.0,0.0,0.014007,0.016442,0.0,0.013269,0.016346,pass
15,0.0,0.0,0.0,0.022064,0.0,0.0,0.010320,0.015871,0.0,0.010953,0.010458,pass

[[       nan        nan        nan 1.27492356        nan        nan
  1.35422984 1.17156135        nan 1.1442414  1.359904  ]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 7,h 3,h 4,h 0,h 1,cz 10,cz 9,id 8,cz 6,cz 5,cz 2
sum,0.415599,0.394805,0.384058,0.382897,0.353776,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 7,h 4,h 0,h 3,h 1,cz 10,cz 9,id 8,cz 6,cz 5,cz 2
sum,0.548064,0.514083,0.513073,0.51044,0.454977,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 7,h 3,h 0,h 4,h 1,cz 10,cz 9,id 8,cz 6,cz 5,cz 2
sum,0.003669,0.001654,0.000908,0.000736,0.000604,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_rzz_inGap_13_.qasm

100%|██████████| 3/3 [00:00<00:00, 13.32it/s]
100%|██████████| 10/10 [00:00<00:00, 15.42it/s]

,rzz 10,cz 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.0,0.023140,0.0,0.0,0.010872,0.015406,0.0,0.010306,0.011726,fail
1,0.0,0.0,0.0,0.022168,0.0,0.0,0.012333,0.020346,0.0,0.011963,0.012552,fail
2,0.0,0.0,0.0,0.026551,0.0,0.0,0.011472,0.013358,0.0,0.015130,0.013673,fail
3,0.0,0.0,0.0,0.027834,0.0,0.0,0.012820,0.012993,0.0,0.009885,0.016131,pass
4,0.0,0.0,0.0,0.016232,0.0,0.0,0.009563,0.008942,0.0,0.008229,0.008040,pass
5,0.0,0.0,0.0,0.021507,0.0,0.0,0.009119,0.013412,0.0,0.011869,0.015661,pass
6,0.0,0.0,0.0,0.019111,0.0,0.0,0.008388,0.015458,0.0,0.007537,0.010629,pass
7,0.0,0.0,0.0,0.022181,0.0,0.0,0.008714,0.017312,0.0,0.006075,0.012461,pass
8,0.0,0.0,0.0,0.022977,0.0,0.0,0.012825,0.012925,0.0,0.008756,0.014318,pass
9,0.0,0.0,0.0,0.019659,0.0,0.0,0.011483,0.008903,0.0,0.010849,0.011233,pass
10,0.0,0.0,0.0,0.017962,0.0,0.0,0.007724,0.015408,0.0,0.010333,0.008400,pass
11,0.0,0.0,0.0,0.021624,0.0,0.0,0.010451,0.011652,0.0,0.012555,0.011125,pass
12,0.0,0.0,0.0,0.025176,0.0,0.0,0.013198,0.017380,0.0,0.011072,0.013476,pass

[[       nan        nan        nan 1.10846308        nan        nan
  1.06698167 1.24289033        nan 1.21368456 1.08083101]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,h 3,h 7,h 4,h 0,rzz 10,cz 9,cz 8,cz 6,cz 5,cz 2
sum,0.27793,0.267636,0.251144,0.249543,0.238046,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 1,h 3,h 7,h 4,h 0,rzz 10,cz 9,cz 8,cz 6,cz 5,cz 2
sum,0.36226,0.350797,0.32074,0.316108,0.302368,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 7,h 3,h 0,h 1,h 4,rzz 10,cz 9,cz 8,cz 6,cz 5,cz 2
sum,0.001606,0.000769,0.000461,0.000452,0.000387,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_t_inGap_9_.qasm

100%|██████████| 5/5 [00:00<00:00, 14.08it/s]
100%|██████████| 10/10 [00:00<00:00, 15.78it/s]

,cz 10,cz 9,tdg 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,1.861115e-18,0.021707,0.0,0.0,0.013262,0.019253,0.0,0.010635,0.016443,fail
1,0.0,0.0,1.917413e-18,0.022022,0.0,0.0,0.013828,0.010793,0.0,0.013158,0.017132,fail
2,0.0,0.0,1.930542e-18,0.023081,0.0,0.0,0.014411,0.017503,0.0,0.012826,0.016549,fail
3,0.0,0.0,1.907768e-18,0.025074,0.0,0.0,0.012174,0.018363,0.0,0.010557,0.011583,fail
4,0.0,0.0,1.834676e-18,0.031531,0.0,0.0,0.015052,0.014471,0.0,0.010775,0.013264,fail
5,0.0,0.0,1.313546e-18,0.017326,0.0,0.0,0.009497,0.012580,0.0,0.008736,0.013055,pass
6,0.0,0.0,1.285501e-18,0.019338,0.0,0.0,0.009059,0.013482,0.0,0.008267,0.007940,pass
7,0.0,0.0,1.543289e-18,0.025247,0.0,0.0,0.009473,0.012948,0.0,0.010089,0.013375,pass
8,0.0,0.0,1.236382e-18,0.024151,0.0,0.0,0.009079,0.014630,0.0,0.008997,0.011095,pass
9,0.0,0.0,1.708641e-18,0.030998,0.0,0.0,0.009455,0.015463,0.0,0.011910,0.015852,pass
10,0.0,0.0,1.498899e-18,0.018040,0.0,0.0,0.012214,0.010674,0.0,0.009918,0.011458,pass
11,0.0,0.0,1.443878e-18,0.018686,0.0,0.0,0.005614,0.007370,0.0,0.006110,0.008391,pass
12,0.0,0.0,1.630144e-18,0.022617,0.0,0.0,0.010316,0.014694,0.0,0.012428,0.015714,pass
13,0.0,0.0,1.564089e-18,0.021713,0.0,0.0,0.012256,0.015374,0.0,0.006415,0.012485,pass
14,0.0,0.0,1.013136e-18,0.014831,0.0,0.0,0.006039,0.008818,0.0,0.006979,0.006719,pass

[[       nan        nan 1.02128733 1.27742471        nan        nan
  1.09507442 1.19758446        nan 1.13524334 1.1425915 ]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 4,tdg 8,h 0,h 1,h 3,h 7,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.424953,0.398983,0.392407,0.39209,0.389424,0.366911,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 4,h 3,h 0,h 1,tdg 8,h 7,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.541292,0.506015,0.504497,0.50337,0.500852,0.484086,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 7,h 3,h 0,h 4,h 1,tdg 8,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.002922,0.001261,0.001099,0.000927,0.00066,1.786622e-35,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_cswap_inGap_3_.qasm

100%|██████████| 4/4 [00:00<00:00, 11.16it/s]
100%|██████████| 10/10 [00:00<00:00, 10.74it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,cswap 2,h 1,h 0,pass/fail
0,0.0,0.0,0.017352,0.0,0.0,0.009103,0.015113,0.0,0.026555,0.008770,0.007010,fail
1,0.0,0.0,0.030439,0.0,0.0,0.011871,0.018116,0.0,0.027656,0.011247,0.006464,fail
2,0.0,0.0,0.011355,0.0,0.0,0.007966,0.009395,0.0,0.019590,0.007696,0.007558,fail
3,0.0,0.0,0.030869,0.0,0.0,0.012860,0.018991,0.0,0.029936,0.012216,0.008327,fail
4,0.0,0.0,0.021576,0.0,0.0,0.009137,0.016778,0.0,0.026509,0.010289,0.007077,pass
5,0.0,0.0,0.013509,0.0,0.0,0.007858,0.011868,0.0,0.021726,0.007900,0.006535,pass
6,0.0,0.0,0.021618,0.0,0.0,0.008428,0.011852,0.0,0.022613,0.008857,0.004177,pass
7,0.0,0.0,0.015466,0.0,0.0,0.006152,0.007761,0.0,0.022107,0.006579,0.004290,pass
8,0.0,0.0,0.023136,0.0,0.0,0.012947,0.011353,0.0,0.022982,0.007931,0.007268,pass
9,0.0,0.0,0.023209,0.0,0.0,0.009379,0.014358,0.0,0.024392,0.009530,0.007592,pass
10,0.0,0.0,0.025911,0.0,0.0,0.010881,0.013436,0.0,0.029028,0.009481,0.005633,pass
11,0.0,0.0,0.029969,0.0,0.0,0.016489,0.022721,0.0,0.029901,0.011513,0.008205,pass
12,0.0,0.0,0.009894,0.0,0.0,0.005910,0.009792,0.0,0.014991,0.005555,0.005582,pass
13,0.0,0.0,0.024924,0.0,0.0,0.009007,0.017586,0.0,0.031323,0.012186,0.008035,pass

[[       nan        nan 1.37173998        nan        nan 1.23064435
  1.23287939        nan 1.15429358 1.22378982 1.13454487]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 0,h 4,h 1,h 5,h 8,cswap 2,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.313162,0.309437,0.307733,0.302913,0.300825,0.296979,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 4,h 8,h 0,h 1,h 5,cswap 2,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.404812,0.403988,0.401986,0.401883,0.396108,0.382679,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,cswap 2,h 8,h 4,h 5,h 1,h 0,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.002535,0.001925,0.000918,0.000427,0.00039,0.000212,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_cswap_inGap_1_.qasm

100%|██████████| 6/6 [00:00<00:00, 15.69it/s]
100%|██████████| 10/10 [00:00<00:00, 13.84it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,h 2,h 1,cswap 0,pass/fail
0,0.0,0.0,0.022189,0.0,0.0,0.010714,0.010525,0.0,0.008400,0.009893,0.039514,fail
1,0.0,0.0,0.023233,0.0,0.0,0.012845,0.017830,0.0,0.012190,0.015894,0.034746,fail
2,0.0,0.0,0.014487,0.0,0.0,0.007722,0.011728,0.0,0.008113,0.011335,0.031190,fail
3,0.0,0.0,0.025961,0.0,0.0,0.017090,0.014674,0.0,0.011580,0.018410,0.033639,fail
4,0.0,0.0,0.036042,0.0,0.0,0.012841,0.019852,0.0,0.009380,0.014712,0.041841,fail
5,0.0,0.0,0.020989,0.0,0.0,0.010747,0.013757,0.0,0.011476,0.012407,0.039249,fail
6,0.0,0.0,0.022064,0.0,0.0,0.011743,0.013555,0.0,0.009233,0.013677,0.034770,pass
7,0.0,0.0,0.020072,0.0,0.0,0.008000,0.010858,0.0,0.006929,0.007620,0.028372,pass
8,0.0,0.0,0.024131,0.0,0.0,0.010457,0.015720,0.0,0.013113,0.013232,0.035094,pass
9,0.0,0.0,0.022569,0.0,0.0,0.008249,0.013589,0.0,0.008368,0.012121,0.031299,pass
10,0.0,0.0,0.028733,0.0,0.0,0.014274,0.020707,0.0,0.011909,0.015567,0.037749,pass
11,0.0,0.0,0.017993,0.0,0.0,0.012485,0.017724,0.0,0.011517,0.012103,0.032149,pass
12,0.0,0.0,0.026503,0.0,0.0,0.011981,0.014001,0.0,0.011872,0.016145,0.037551,pass
13,0.0,0.0,0.025853,0.0,0.0,0.010297,0.012498,0.0,0.008617,0.013076,0.033607,pass
14,0.0,0.0,0.023175,0.0,0.0,0.011319,0.018052,0.0,0.013753,0.015032,0.037553,pass
15,0.0,0.0,0.024455,0.0,0.0,0.009811,0.014369,0.0,0.009612,0.014120,0.033897,pass

[[       nan        nan 1.51330155        nan        nan 1.42495571
  1.3479255         nan 1.19631962 1.33644467 1.14018521]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 5,cswap 0,h 1,h 8,h 4,h 2,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.398498,0.391625,0.383811,0.377599,0.369054,0.368171,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 5,h 8,h 1,cswap 0,h 4,h 2,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.540459,0.520454,0.512047,0.503256,0.493418,0.478283,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,cswap 0,h 8,h 4,h 1,h 5,h 2,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.007644,0.003275,0.001269,0.001114,0.000848,0.000612,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_rxx_inGap_15_.qasm

100%|██████████| 5/5 [00:00<00:00,  5.18it/s]
100%|██████████| 10/10 [00:01<00:00,  6.17it/s]

,rxx 10,cz 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.287782,0.330464,0.514493,0.185753,0.254557,0.401086,0.270513,0.042189,0.0,0.037781,0.051113,fail
1,0.279518,0.236704,0.425019,0.188493,0.303399,0.467590,0.289271,0.073974,0.0,0.043571,0.051434,fail
2,0.456281,0.421920,0.737222,0.284361,0.463455,0.717316,0.460881,0.105275,0.0,0.077554,0.067477,fail
3,0.420004,0.460002,0.753541,0.355802,0.446696,0.659663,0.343424,0.072560,0.0,0.060513,0.073645,fail
4,0.299962,0.252656,0.456761,0.258489,0.326412,0.409442,0.288673,0.083618,0.0,0.039048,0.048188,fail
5,0.222331,0.270821,0.421902,0.204055,0.252454,0.374622,0.168583,0.030182,0.0,0.038757,0.032126,pass
6,0.223965,0.278258,0.375964,0.212913,0.213514,0.372728,0.181561,0.033079,0.0,0.024683,0.032673,pass
7,0.229794,0.194909,0.343298,0.161554,0.253864,0.353987,0.234619,0.066154,0.0,0.029194,0.032896,pass
8,0.317503,0.364926,0.598494,0.250783,0.283670,0.451305,0.280761,0.043820,0.0,0.037041,0.062465,pass
9,0.342676,0.377145,0.618335,0.307966,0.370827,0.492341,0.260575,0.063052,0.0,0.042555,0.050311,pass
10,0.251439,0.237774,0.399621,0.213390,0.286177,0.431574,0.231020,0.058472,0.0,0.030660,0.036091,pass
11,0.339359,0.251083,0.546348,0.257827,0.394401,0.463007,0.344505,0.114645,0.0,0.037859,0.059521,pass
12,0.299782,0.285959,0.545949,0.182680,0.336838,0.513150,0.298375,0.063207,0.0,0.072616,0.046211,pass
13,0.283196,0.316730,0.461844,0.284312,0.262278,0.425068,0.218638,0.064141,0.0,0.029324,0.040526,pass
14,0.396377,0.321246,0.678357,0.270709,0.447048,0.651626,0.372880,0.103640,0.0,0.076866,0.058551,pass

[[1.30848626 1.35155864 1.30504264 1.39760648 1.2913075  1.35082784
  1.39427445 1.39394574        nan 1.50026789 1.26166192]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 0,h 4,h 1,rxx 10,h 3,cz 9,cz 5,cz 6,cz 8,h 7,cz 2
sum,0.392689,0.389409,0.381208,0.374959,0.370935,0.369897,0.369559,0.366558,0.366508,0.351718,0.0

custom SCORES

,h 4,h 1,h 0,h 3,rxx 10,cz 9,cz 5,cz 8,cz 6,h 7,cz 2
sum,0.525145,0.524187,0.516549,0.500201,0.497616,0.494881,0.494361,0.486085,0.484893,0.474609,0.0

DSTAR SCORES

,cz 8,cz 5,cz 6,rxx 10,cz 9,h 4,h 7,h 3,h 0,h 1,cz 2
sum,0.834323,0.739767,0.397515,0.384492,0.366628,0.359825,0.220559,0.025281,0.015625,0.012327,0.0

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_z_inGap_2_.qasm

100%|██████████| 2/2 [00:00<00:00, 16.82it/s]
100%|██████████| 10/10 [00:00<00:00, 17.44it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,h 2,z 1,h 0,pass/fail
0,0.0,0.0,0.031649,0.0,0.0,0.015357,0.017617,0.0,0.007158,0.013971,0.015320,fail
1,0.0,0.0,0.028382,0.0,0.0,0.010461,0.014089,0.0,0.008757,0.020938,0.013512,fail
2,0.0,0.0,0.029416,0.0,0.0,0.010978,0.014276,0.0,0.008542,0.016872,0.015103,pass
3,0.0,0.0,0.025747,0.0,0.0,0.010849,0.015503,0.0,0.010127,0.019680,0.010630,pass
4,0.0,0.0,0.023038,0.0,0.0,0.008138,0.010187,0.0,0.009933,0.022456,0.018654,pass
5,0.0,0.0,0.024054,0.0,0.0,0.006905,0.014341,0.0,0.008975,0.019970,0.012409,pass
6,0.0,0.0,0.019078,0.0,0.0,0.012031,0.013679,0.0,0.010236,0.017504,0.010435,pass
7,0.0,0.0,0.020115,0.0,0.0,0.010593,0.007817,0.0,0.009782,0.020472,0.008674,pass
8,0.0,0.0,0.018857,0.0,0.0,0.011206,0.012834,0.0,0.010628,0.019496,0.007300,pass
9,0.0,0.0,0.033140,0.0,0.0,0.012615,0.013506,0.0,0.014262,0.026458,0.010543,pass
10,0.0,0.0,0.027973,0.0,0.0,0.008644,0.013244,0.0,0.010546,0.023747,0.011253,pass
11,0.0,0.0,0.017251,0.0,0.0,0.012560,0.014821,0.0,0.009020,0.018299,0.007076,pass

[[       nan        nan 1.05442077        nan        nan 1.18962819
  1.11127377        nan 1.10049322 1.19958874 1.0627259 ]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 0,h 8,h 5,h 4,z 1,h 2,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.204614,0.200973,0.198093,0.195824,0.145538,0.134912,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 0,h 5,h 8,h 4,z 1,h 2,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.258976,0.257007,0.25395,0.250227,0.189185,0.172029,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,z 1,h 4,h 0,h 5,h 2,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.00161,0.000553,0.000472,0.000394,0.000317,0.00012,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_sx_inGap_3_.qasm

100%|██████████| 5/5 [00:00<00:00, 16.56it/s]
100%|██████████| 10/10 [00:00<00:00, 16.73it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,sxdg 2,h 1,h 0,pass/fail
0,0.0,0.0,0.021791,0.0,0.0,0.013028,0.014093,0.0,0.022771,0.015457,0.011785,fail
1,0.0,0.0,0.023017,0.0,0.0,0.009372,0.014928,0.0,0.028977,0.019686,0.012028,fail
2,0.0,0.0,0.022368,0.0,0.0,0.010186,0.015858,0.0,0.035573,0.024075,0.011852,fail
3,0.0,0.0,0.023885,0.0,0.0,0.012047,0.014342,0.0,0.024979,0.017549,0.011523,fail
4,0.0,0.0,0.027909,0.0,0.0,0.010150,0.015998,0.0,0.030056,0.020570,0.015904,fail
5,0.0,0.0,0.024543,0.0,0.0,0.011533,0.014220,0.0,0.033046,0.023357,0.012563,pass
6,0.0,0.0,0.025137,0.0,0.0,0.012747,0.015238,0.0,0.036377,0.024732,0.013416,pass
7,0.0,0.0,0.019918,0.0,0.0,0.010555,0.016510,0.0,0.025286,0.016980,0.011505,pass
8,0.0,0.0,0.017297,0.0,0.0,0.010351,0.012500,0.0,0.027091,0.018722,0.011325,pass
9,0.0,0.0,0.009101,0.0,0.0,0.005052,0.007682,0.0,0.016972,0.011718,0.003918,pass
10,0.0,0.0,0.022339,0.0,0.0,0.011676,0.015825,0.0,0.036201,0.024743,0.011415,pass
11,0.0,0.0,0.018758,0.0,0.0,0.005707,0.009259,0.0,0.031367,0.022355,0.007108,pass
12,0.0,0.0,0.027046,0.0,0.0,0.013709,0.014857,0.0,0.034789,0.023255,0.015608,pass
13,0.0,0.0,0.028813,0.0,0.0,0.013264,0.016943,0.0,0.029711,0.021128,0.013731,pass
14,0.0,0.0,0.022418,0.0,0.0,0.011365,0.013530,0.0,0.032872,0.022032,0.009183,pass

[[       nan        nan 1.17294804        nan        nan 1.18902473
  1.06344231        nan 1.24944171 1.2366882  1.26039619]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 0,h 8,h 4,h 5,sxdg 2,h 1,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.364984,0.355835,0.355172,0.340817,0.319136,0.317723,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 0,h 8,h 4,h 5,sxdg 2,h 1,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.479991,0.460179,0.449599,0.442127,0.418822,0.415953,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,sxdg 2,h 8,h 1,h 4,h 0,h 5,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.003821,0.002714,0.001819,0.001101,0.000779,0.000588,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_ry_inGap_12_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.89it/s]
100%|██████████| 10/10 [00:00<00:00, 12.40it/s]

,cz 10,cz 9,h 8,cz 7,ry 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.005956,0.0,0.099475,0.079813,0.024084,0.033956,0.114400,0.029012,0.020239,fail
1,0.0,0.0,0.018958,0.0,0.075947,0.054205,0.015897,0.030658,0.074827,0.023272,0.016695,fail
2,0.0,0.0,0.031826,0.0,0.095552,0.062546,0.025560,0.034946,0.107891,0.031735,0.023697,fail
3,0.0,0.0,0.023054,0.0,0.101256,0.073414,0.024102,0.032639,0.127605,0.030895,0.026463,fail
4,0.0,0.0,0.020908,0.0,0.101705,0.079412,0.029068,0.022389,0.116078,0.026392,0.023933,fail
5,0.0,0.0,0.020034,0.0,0.100751,0.069735,0.016615,0.029787,0.109552,0.030700,0.020018,fail
6,0.0,0.0,0.022715,0.0,0.085671,0.061687,0.017454,0.021626,0.097586,0.022218,0.019935,fail
7,0.0,0.0,0.024577,0.0,0.100391,0.074847,0.022839,0.028478,0.119938,0.025024,0.030243,fail
8,0.0,0.0,0.021131,0.0,0.068860,0.044605,0.014799,0.028929,0.081305,0.021641,0.022295,fail
9,0.0,0.0,0.030511,0.0,0.122557,0.091365,0.025965,0.028392,0.144380,0.033710,0.026162,fail
10,0.0,0.0,0.025079,0.0,0.082819,0.059942,0.020218,0.019274,0.093774,0.021198,0.022839,pass
11,0.0,0.0,0.024431,0.0,0.062492,0.043095,0.020666,0.018245,0.063823,0.019247,0.017213,pass
12,0.0,0.0,0.023255,0.0,0.086280,0.058965,0.021783,0.018036,0.080820,0.024317,0.014507,pass
13,0.0,0.0,0.025373,0.0,0.071808,0.042308,0.012450,0.029105,0.067578,0.023514,0.018752,pass
14,0.0,0.0,0.021601,0.0,0.053691,0.034846,0.012312,0.014148,0.052488,0.016608,0.010713,pass
15,0.0,0.0,0.029741,0.0,0.092010,0.058675,0.021932,0.040723,0.091631,0.029236,0.023755,pass
16,0.0,0.0,0.031541,0.0,0.079704,0.055338,0.020796,0.028202,0.080435,0.024705,0.021141,pass
17,0.0,0.0,0.020576,0.0,0.084091,0.062126,0.017956,0.025349,0.095945,0.020413,0.025338,pass
18,0.0,0.0,0.027486,0.0,0.079975,0.052888,0.020999,0.036226,0.075610,0.026571,0.017585,pass
19,0.0,0.0,0.026745,0.0,0.071606,0.049648,0.020869,0.032486,0.066839,0.021842,0.022975,pass

[[       nan        nan 1.44881745        nan 1.28713725 1.32101388
  1.34333448 1.19759787 1.32026943 1.22760702 1.31673165]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,cz 2,cz 5,ry 6,h 1,h 0,h 4,h 3,h 8,cz 10,cz 9,cz 7
sum,0.587146,0.571848,0.554668,0.546737,0.541062,0.532487,0.527101,0.461979,0.0,0.0,0.0

custom SCORES

,cz 2,cz 5,ry 6,h 0,h 1,h 4,h 3,h 8,cz 10,cz 9,cz 7
sum,0.780944,0.760703,0.733151,0.719171,0.714532,0.711313,0.684915,0.62931,0.0,0.0,0.0

DSTAR SCORES

,cz 2,ry 6,cz 5,h 3,h 1,h 0,h 8,h 4,cz 10,cz 9,cz 7
sum,0.111049,0.084223,0.04548,0.008298,0.007373,0.005174,0.004705,0.004595,0.0,0.0,0.0

ERROR GATE LOCATION:
6
Now evolving the following mutant:  AddGate_rzz_inGap_8_.qasm

100%|██████████| 4/4 [00:00<00:00, 15.65it/s]
100%|██████████| 10/10 [00:00<00:00, 16.71it/s]

,cz 10,cz 9,h 8,rzz 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.018543,0.147487,0.0,0.0,0.008697,0.014714,0.0,0.009335,0.010967,fail
1,0.0,0.0,0.018688,0.150383,0.0,0.0,0.008521,0.012745,0.0,0.011110,0.012997,fail
2,0.0,0.0,0.029861,0.244680,0.0,0.0,0.010478,0.017078,0.0,0.014158,0.013466,fail
3,0.0,0.0,0.024660,0.205074,0.0,0.0,0.009251,0.011161,0.0,0.008751,0.010556,fail
4,0.0,0.0,0.024933,0.199191,0.0,0.0,0.007624,0.010425,0.0,0.006321,0.014121,pass
5,0.0,0.0,0.016593,0.128910,0.0,0.0,0.008030,0.016149,0.0,0.009097,0.014312,pass
6,0.0,0.0,0.024815,0.204732,0.0,0.0,0.007969,0.011078,0.0,0.010776,0.012064,pass
7,0.0,0.0,0.022001,0.174604,0.0,0.0,0.005722,0.011173,0.0,0.009289,0.010446,pass
8,0.0,0.0,0.022214,0.176571,0.0,0.0,0.007806,0.012449,0.0,0.007829,0.010169,pass
9,0.0,0.0,0.025090,0.200454,0.0,0.0,0.012570,0.015142,0.0,0.012359,0.012172,pass
10,0.0,0.0,0.017035,0.138840,0.0,0.0,0.009596,0.013937,0.0,0.009580,0.006910,pass
11,0.0,0.0,0.031471,0.247381,0.0,0.0,0.009047,0.015198,0.0,0.012984,0.009937,pass
12,0.0,0.0,0.014940,0.119110,0.0,0.0,0.003955,0.009092,0.0,0.005302,0.009720,pass
13,0.0,0.0,0.022309,0.175793,0.0,0.0,0.007328,0.014077,0.0,0.007407,0.015929,pass

[[       nan        nan 1.30182114 1.30910686        nan        nan
  1.13439219 1.22644617        nan 1.30625677 1.12252357]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,h 4,h 3,rzz 7,h 0,h 8,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.322816,0.316882,0.30202,0.297477,0.293015,0.292993,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 1,h 4,rzz 7,h 3,h 8,h 0,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.428237,0.406749,0.394835,0.394623,0.388349,0.375243,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,rzz 7,h 8,h 3,h 0,h 1,h 4,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.096944,0.001994,0.000751,0.000559,0.000459,0.000335,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
7
Now evolving the following mutant:  AddGate_rx_inGap_9_.qasm

100%|██████████| 4/4 [00:00<00:00, 14.54it/s]
100%|██████████| 10/10 [00:00<00:00, 16.96it/s]

,cz 10,cz 9,rx 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.136142,0.027228,0.0,0.0,0.015725,0.017524,0.0,0.011058,0.017700,fail
1,0.0,0.0,0.132499,0.026500,0.0,0.0,0.014959,0.013609,0.0,0.010694,0.015374,fail
2,0.0,0.0,0.150159,0.030032,0.0,0.0,0.011954,0.023533,0.0,0.014775,0.016622,fail
3,0.0,0.0,0.140835,0.028167,0.0,0.0,0.011407,0.019181,0.0,0.008451,0.011617,fail
4,0.0,0.0,0.086189,0.017238,0.0,0.0,0.006342,0.009676,0.0,0.006611,0.010460,pass
5,0.0,0.0,0.119146,0.023829,0.0,0.0,0.009178,0.008555,0.0,0.008140,0.011347,pass
6,0.0,0.0,0.074658,0.014932,0.0,0.0,0.008664,0.011494,0.0,0.006994,0.011783,pass
7,0.0,0.0,0.071413,0.014283,0.0,0.0,0.004483,0.005230,0.0,0.004364,0.005864,pass
8,0.0,0.0,0.115255,0.023051,0.0,0.0,0.013816,0.017052,0.0,0.011030,0.011932,pass
9,0.0,0.0,0.125898,0.025180,0.0,0.0,0.008722,0.013568,0.0,0.008270,0.010638,pass
10,0.0,0.0,0.154640,0.030928,0.0,0.0,0.015945,0.020652,0.0,0.013995,0.015972,pass
11,0.0,0.0,0.148219,0.029644,0.0,0.0,0.010243,0.015739,0.0,0.007917,0.012985,pass
12,0.0,0.0,0.100235,0.020047,0.0,0.0,0.006570,0.010405,0.0,0.008701,0.008727,pass
13,0.0,0.0,0.129312,0.025862,0.0,0.0,0.009447,0.012831,0.0,0.010171,0.014044,pass

[[       nan        nan 1.07326242 1.07326242        nan        nan
  1.16382744 1.27468216        nan 1.31398786 1.15473705]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 3,h 4,h 0,h 1,rx 8,h 7,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.370999,0.366519,0.350234,0.342898,0.332206,0.332206,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 3,h 4,h 1,h 0,rx 8,h 7,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.489225,0.473161,0.455539,0.451341,0.421343,0.421343,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,rx 8,h 7,h 3,h 0,h 4,h 1,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.061111,0.002965,0.001322,0.000914,0.000714,0.000495,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_rx_inGap_7_.qasm

100%|██████████| 6/6 [00:00<00:00, 15.22it/s]
100%|██████████| 10/10 [00:00<00:00, 17.24it/s]

,cz 10,cz 9,h 8,cz 7,rx 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.038304,0.0,0.068646,0.0,0.012561,0.021085,0.0,0.012344,0.014177,fail
1,0.0,0.0,0.031575,0.0,0.090596,0.0,0.016340,0.018222,0.0,0.012485,0.011780,fail
2,0.0,0.0,0.021478,0.0,0.049000,0.0,0.007580,0.016324,0.0,0.010781,0.010176,fail
3,0.0,0.0,0.019502,0.0,0.068745,0.0,0.011632,0.011284,0.0,0.008688,0.012115,fail
4,0.0,0.0,0.012170,0.0,0.057358,0.0,0.007633,0.013101,0.0,0.010775,0.009674,fail
5,0.0,0.0,0.021690,0.0,0.050719,0.0,0.008398,0.015624,0.0,0.008897,0.011700,fail
6,0.0,0.0,0.021660,0.0,0.069395,0.0,0.011964,0.011760,0.0,0.008174,0.011892,pass
7,0.0,0.0,0.011602,0.0,0.044518,0.0,0.007749,0.010461,0.0,0.005508,0.007105,pass
8,0.0,0.0,0.019748,0.0,0.067359,0.0,0.010215,0.011739,0.0,0.012568,0.012468,pass
9,0.0,0.0,0.023376,0.0,0.053580,0.0,0.009238,0.013293,0.0,0.012264,0.012833,pass
10,0.0,0.0,0.022402,0.0,0.081503,0.0,0.013943,0.012826,0.0,0.011948,0.011025,pass
11,0.0,0.0,0.027935,0.0,0.067169,0.0,0.011745,0.013413,0.0,0.007422,0.010832,pass
12,0.0,0.0,0.022492,0.0,0.072440,0.0,0.011393,0.016772,0.0,0.011225,0.012771,pass
13,0.0,0.0,0.015811,0.0,0.041491,0.0,0.005550,0.007360,0.0,0.003862,0.011521,pass
14,0.0,0.0,0.027383,0.0,0.083259,0.0,0.014217,0.017066,0.0,0.013929,0.016006,pass
15,0.0,0.0,0.025601,0.0,0.080734,0.0,0.014453,0.013969,0.0,0.009664,0.015006,pass

[[       nan        nan 1.58806739        nan 1.41164841        nan
  1.52846382 1.32277975        nan 1.17104505 1.22177713]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 3,h 8,h 1,rx 6,h 4,h 0,cz 10,cz 9,cz 7,cz 5,cz 2
sum,0.426399,0.398971,0.398477,0.36795,0.367356,0.364355,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 3,h 8,h 1,h 4,rx 6,h 0,cz 10,cz 9,cz 7,cz 5,cz 2
sum,0.567407,0.55737,0.515135,0.507729,0.497803,0.475645,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,rx 6,h 8,h 3,h 0,h 4,h 1,cz 10,cz 9,cz 7,cz 5,cz 2
sum,0.022259,0.003368,0.001493,0.000792,0.000673,0.000671,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
6
Now evolving the following mutant:  AddGate_p_inGap_6_.qasm

100%|██████████| 5/5 [00:00<00:00, 16.47it/s]
100%|██████████| 10/10 [00:00<00:00, 18.03it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,p 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.024867,0.0,0.0,0.0,0.009222,0.012594,0.0,0.008395,0.011626,fail
1,0.0,0.0,0.022313,0.0,0.0,0.0,0.013125,0.014572,0.0,0.014556,0.014413,fail
2,0.0,0.0,0.032610,0.0,0.0,0.0,0.011469,0.015181,0.0,0.014041,0.016981,fail
3,0.0,0.0,0.023692,0.0,0.0,0.0,0.010399,0.012400,0.0,0.008614,0.012286,fail
4,0.0,0.0,0.028682,0.0,0.0,0.0,0.011915,0.014330,0.0,0.010926,0.013013,fail
5,0.0,0.0,0.025018,0.0,0.0,0.0,0.008692,0.011336,0.0,0.009590,0.014150,pass
6,0.0,0.0,0.023971,0.0,0.0,0.0,0.012615,0.014340,0.0,0.007616,0.014329,pass
7,0.0,0.0,0.028013,0.0,0.0,0.0,0.006370,0.011080,0.0,0.012524,0.012949,pass
8,0.0,0.0,0.015136,0.0,0.0,0.0,0.009215,0.015050,0.0,0.007844,0.007187,pass
9,0.0,0.0,0.019814,0.0,0.0,0.0,0.011387,0.015224,0.0,0.009892,0.006955,pass
10,0.0,0.0,0.017607,0.0,0.0,0.0,0.010230,0.011156,0.0,0.004463,0.006966,pass
11,0.0,0.0,0.022377,0.0,0.0,0.0,0.010421,0.012215,0.0,0.007805,0.010921,pass
12,0.0,0.0,0.020902,0.0,0.0,0.0,0.015492,0.019047,0.0,0.011011,0.014048,pass
13,0.0,0.0,0.011059,0.0,0.0,0.0,0.009621,0.010749,0.0,0.008099,0.004841,pass
14,0.0,0.0,0.020190,0.0,0.0,0.0,0.008398,0.012574,0.0,0.011503,0.015200,pass

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

[[       nan        nan 1.23369758        nan        nan        nan
  1.16916884 1.09882933        nan 1.2873902  1.24273997]]
BARINEL SCORES

,h 8,h 0,h 1,h 4,h 3,cz 10,cz 9,cz 7,cz 6,p 5,cz 2
sum,0.393052,0.388471,0.384894,0.353973,0.342224,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 8,h 0,h 1,h 4,h 3,cz 10,cz 9,cz 7,cz 6,p 5,cz 2
sum,0.514278,0.509163,0.508772,0.457437,0.436236,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 3,h 0,h 1,h 4,cz 10,cz 9,cz 7,cz 6,p 5,cz 2
sum,0.003356,0.00093,0.000914,0.000628,0.000617,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_t_inGap_15_.qasm

100%|██████████| 3/3 [00:00<00:00, 16.46it/s]
100%|██████████| 10/10 [00:00<00:00, 17.00it/s]

,tdg 10,cz 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,6.017186e-18,0.0,0.0,0.024401,0.0,0.0,0.010396,0.019523,0.0,0.010464,0.013209,fail
1,5.432989e-18,0.0,0.0,0.017950,0.0,0.0,0.010306,0.014327,0.0,0.011037,0.014570,fail
2,6.750163e-18,0.0,0.0,0.029618,0.0,0.0,0.014566,0.017692,0.0,0.010963,0.015755,fail
3,4.444696e-18,0.0,0.0,0.017995,0.0,0.0,0.009580,0.015679,0.0,0.005926,0.008810,pass
4,4.297456e-18,0.0,0.0,0.020102,0.0,0.0,0.008334,0.008262,0.0,0.005933,0.006800,pass
5,5.707555e-18,0.0,0.0,0.021114,0.0,0.0,0.012060,0.013645,0.0,0.009464,0.013327,pass
6,5.015368e-18,0.0,0.0,0.019578,0.0,0.0,0.007946,0.011876,0.0,0.010663,0.012962,pass
7,5.893934e-18,0.0,0.0,0.026105,0.0,0.0,0.013956,0.015619,0.0,0.010721,0.015642,pass
8,5.796374e-18,0.0,0.0,0.031360,0.0,0.0,0.012102,0.014940,0.0,0.014461,0.015421,pass
9,3.778451e-18,0.0,0.0,0.012994,0.0,0.0,0.006494,0.010488,0.0,0.007219,0.009365,pass
10,3.389072e-18,0.0,0.0,0.015884,0.0,0.0,0.006585,0.008227,0.0,0.006825,0.007434,pass
11,4.771618e-18,0.0,0.0,0.016799,0.0,0.0,0.009390,0.014989,0.0,0.008983,0.005653,pass
12,3.205554e-18,0.0,0.0,0.016328,0.0,0.0,0.009411,0.008543,0.0,0.008651,0.011024,pass

[[1.11264359        nan        nan 1.23461493        nan        nan
  1.23902972 1.13632015        nan 1.01996954 1.08569182]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 3,h 0,tdg 10,h 4,h 1,h 7,cz 9,cz 8,cz 6,cz 5,cz 2
sum,0.296541,0.290275,0.282174,0.268965,0.267612,0.266326,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 3,h 0,tdg 10,h 4,h 7,h 1,cz 9,cz 8,cz 6,cz 5,cz 2
sum,0.380783,0.369063,0.360664,0.352279,0.348529,0.335851,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 7,h 3,h 0,h 4,h 1,tdg 10,cz 9,cz 8,cz 6,cz 5,cz 2
sum,0.001619,0.000851,0.00061,0.000402,0.000341,1.104174e-34,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_p_inGap_11_.qasm

100%|██████████| 6/6 [00:00<00:00, 15.83it/s]
100%|██████████| 10/10 [00:00<00:00, 16.45it/s]

,cz 10,p 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.0,0.024800,0.0,0.0,0.012431,0.019140,0.0,0.011461,0.017559,fail
1,0.0,0.0,0.0,0.021562,0.0,0.0,0.008933,0.017040,0.0,0.009917,0.012847,fail
2,0.0,0.0,0.0,0.024132,0.0,0.0,0.017036,0.017743,0.0,0.014661,0.015701,fail
3,0.0,0.0,0.0,0.017170,0.0,0.0,0.009805,0.012269,0.0,0.009232,0.011572,fail
4,0.0,0.0,0.0,0.022060,0.0,0.0,0.017094,0.015460,0.0,0.010128,0.010198,fail
5,0.0,0.0,0.0,0.022754,0.0,0.0,0.008372,0.014284,0.0,0.009916,0.012340,fail
6,0.0,0.0,0.0,0.024074,0.0,0.0,0.011914,0.011385,0.0,0.012084,0.008803,pass
7,0.0,0.0,0.0,0.018993,0.0,0.0,0.008968,0.011323,0.0,0.008925,0.005885,pass
8,0.0,0.0,0.0,0.023662,0.0,0.0,0.011262,0.015441,0.0,0.011423,0.011545,pass
9,0.0,0.0,0.0,0.021808,0.0,0.0,0.010931,0.016276,0.0,0.007036,0.012942,pass
10,0.0,0.0,0.0,0.019818,0.0,0.0,0.014589,0.013362,0.0,0.011009,0.012374,pass
11,0.0,0.0,0.0,0.030903,0.0,0.0,0.013347,0.016439,0.0,0.012062,0.013265,pass
12,0.0,0.0,0.0,0.023062,0.0,0.0,0.010530,0.012051,0.0,0.007708,0.014719,pass
13,0.0,0.0,0.0,0.013859,0.0,0.0,0.006684,0.008241,0.0,0.005677,0.008883,pass
14,0.0,0.0,0.0,0.018802,0.0,0.0,0.010477,0.011795,0.0,0.009159,0.010339,pass
15,0.0,0.0,0.0,0.022139,0.0,0.0,0.013610,0.020569,0.0,0.009982,0.010870,pass

[[       nan        nan        nan 1.12322907        nan        nan
  1.39222044 1.19706297        nan 1.34678635 1.31338028]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 0,h 3,h 1,h 4,h 7,cz 10,p 9,cz 8,cz 6,cz 5,cz 2
sum,0.422543,0.41206,0.407253,0.396118,0.378943,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 0,h 1,h 3,h 4,h 7,cz 10,p 9,cz 8,cz 6,cz 5,cz 2
sum,0.561282,0.544373,0.535375,0.533989,0.485353,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 7,h 3,h 0,h 4,h 1,cz 10,p 9,cz 8,cz 6,cz 5,cz 2
sum,0.002823,0.0015,0.001053,0.000888,0.0007,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
9
Now evolving the following mutant:  AddGate_rzz_inGap_3_.qasm

100%|██████████| 4/4 [00:00<00:00, 14.76it/s]
100%|██████████| 10/10 [00:00<00:00, 16.79it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,rzz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.028832,0.0,0.0,0.011760,0.011691,0.0,0.0,0.011406,0.012234,fail
1,0.0,0.0,0.028105,0.0,0.0,0.015608,0.019756,0.0,0.0,0.012882,0.016638,fail
2,0.0,0.0,0.031415,0.0,0.0,0.010264,0.016549,0.0,0.0,0.013303,0.013540,fail
3,0.0,0.0,0.021327,0.0,0.0,0.009826,0.016266,0.0,0.0,0.012131,0.013503,fail
4,0.0,0.0,0.023409,0.0,0.0,0.010738,0.011975,0.0,0.0,0.013617,0.012983,pass
5,0.0,0.0,0.020483,0.0,0.0,0.010122,0.017855,0.0,0.0,0.012549,0.013979,pass
6,0.0,0.0,0.015925,0.0,0.0,0.011329,0.011731,0.0,0.0,0.010421,0.011323,pass
7,0.0,0.0,0.018042,0.0,0.0,0.011907,0.014701,0.0,0.0,0.010432,0.011118,pass
8,0.0,0.0,0.018467,0.0,0.0,0.010768,0.015392,0.0,0.0,0.008974,0.009636,pass
9,0.0,0.0,0.025352,0.0,0.0,0.012055,0.018161,0.0,0.0,0.010697,0.011739,pass
10,0.0,0.0,0.014065,0.0,0.0,0.009751,0.013959,0.0,0.0,0.010856,0.007808,pass
11,0.0,0.0,0.028309,0.0,0.0,0.015119,0.023637,0.0,0.0,0.011389,0.017476,pass
12,0.0,0.0,0.019786,0.0,0.0,0.009118,0.011594,0.0,0.0,0.008380,0.007903,pass
13,0.0,0.0,0.025615,0.0,0.0,0.011687,0.014747,0.0,0.0,0.011818,0.010034,pass

[[       nan        nan 1.14570954        nan        nan 1.31551161
  1.22970414        nan        nan 1.07019176 1.19025385]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 8,h 0,h 1,h 5,h 4,cz 10,cz 9,cz 7,cz 6,cz 3,rzz 2
sum,0.343679,0.329083,0.313,0.296517,0.294764,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 8,h 0,h 1,h 5,h 4,cz 10,cz 9,cz 7,cz 6,cz 3,rzz 2
sum,0.442118,0.427006,0.396743,0.394035,0.385382,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 4,h 0,h 1,h 5,cz 10,cz 9,cz 7,cz 6,cz 3,rzz 2
sum,0.002858,0.000994,0.00076,0.000602,0.000548,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_x_inGap_2_.qasm

100%|██████████| 6/6 [00:00<00:00, 16.07it/s]
100%|██████████| 10/10 [00:00<00:00, 17.31it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,h 2,x 1,h 0,pass/fail
0,0.0,0.0,0.031184,0.0,0.0,0.015850,0.018679,0.0,0.017624,0.0,0.018056,fail
1,0.0,0.0,0.023889,0.0,0.0,0.011379,0.014893,0.0,0.010783,0.0,0.014889,fail
2,0.0,0.0,0.018566,0.0,0.0,0.007644,0.015870,0.0,0.008649,0.0,0.013629,fail
3,0.0,0.0,0.024748,0.0,0.0,0.012374,0.013641,0.0,0.013529,0.0,0.010084,fail
4,0.0,0.0,0.031454,0.0,0.0,0.011947,0.016745,0.0,0.013033,0.0,0.012705,fail
5,0.0,0.0,0.016937,0.0,0.0,0.011901,0.017701,0.0,0.013193,0.0,0.013318,fail
6,0.0,0.0,0.021542,0.0,0.0,0.012350,0.016948,0.0,0.013751,0.0,0.016149,pass
7,0.0,0.0,0.025355,0.0,0.0,0.015077,0.019143,0.0,0.012077,0.0,0.015526,pass
8,0.0,0.0,0.020047,0.0,0.0,0.009649,0.013944,0.0,0.012561,0.0,0.014692,pass
9,0.0,0.0,0.018341,0.0,0.0,0.007374,0.010176,0.0,0.008310,0.0,0.008440,pass
10,0.0,0.0,0.024703,0.0,0.0,0.011385,0.014565,0.0,0.011985,0.0,0.016635,pass
11,0.0,0.0,0.019767,0.0,0.0,0.012321,0.011563,0.0,0.012636,0.0,0.011676,pass
12,0.0,0.0,0.008178,0.0,0.0,0.005836,0.009228,0.0,0.004931,0.0,0.008299,pass
13,0.0,0.0,0.025444,0.0,0.0,0.012729,0.011281,0.0,0.011481,0.0,0.013691,pass
14,0.0,0.0,0.019500,0.0,0.0,0.011207,0.013288,0.0,0.010544,0.0,0.007332,pass
15,0.0,0.0,0.026555,0.0,0.0,0.013076,0.012435,0.0,0.011022,0.0,0.014299,pass

[[       nan        nan 1.28579168        nan        nan 1.3376077
  1.14916803        nan 1.37670842        nan 1.31027193]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 4,h 2,h 8,h 0,h 5,cz 10,cz 9,cz 7,cz 6,cz 3,x 1
sum,0.423852,0.41272,0.412052,0.394815,0.390417,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 2,h 4,h 8,h 0,h 5,cz 10,cz 9,cz 7,cz 6,cz 3,x 1
sum,0.554768,0.545621,0.544505,0.524144,0.520974,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 4,h 0,h 2,h 5,cz 10,cz 9,cz 7,cz 6,cz 3,x 1
sum,0.003469,0.001551,0.001116,0.000966,0.000827,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_p_inGap_5_.qasm

100%|██████████| 4/4 [00:00<00:00, 16.97it/s]
100%|██████████| 10/10 [00:00<00:00, 17.62it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,p 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.020915,0.0,0.0,0.009960,0.047007,0.016755,0.0,0.011014,0.012570,fail
1,0.0,0.0,0.031324,0.0,0.0,0.014034,0.057024,0.017916,0.0,0.014528,0.013657,fail
2,0.0,0.0,0.025220,0.0,0.0,0.012890,0.051762,0.012908,0.0,0.012085,0.012146,fail
3,0.0,0.0,0.020194,0.0,0.0,0.008169,0.036689,0.012198,0.0,0.007009,0.010625,fail
4,0.0,0.0,0.019066,0.0,0.0,0.008839,0.032955,0.010856,0.0,0.006497,0.011810,pass
5,0.0,0.0,0.008161,0.0,0.0,0.004809,0.020621,0.006947,0.0,0.004040,0.005241,pass
6,0.0,0.0,0.019000,0.0,0.0,0.007291,0.030791,0.013284,0.0,0.008760,0.008161,pass
7,0.0,0.0,0.027555,0.0,0.0,0.010908,0.045620,0.013181,0.0,0.008697,0.014061,pass
8,0.0,0.0,0.024202,0.0,0.0,0.007361,0.033773,0.013857,0.0,0.009207,0.008159,pass
9,0.0,0.0,0.023280,0.0,0.0,0.012739,0.057429,0.014912,0.0,0.006543,0.014506,pass
10,0.0,0.0,0.026369,0.0,0.0,0.011345,0.045207,0.012544,0.0,0.012275,0.013142,pass
11,0.0,0.0,0.020896,0.0,0.0,0.012000,0.052331,0.012024,0.0,0.011674,0.013880,pass
12,0.0,0.0,0.016992,0.0,0.0,0.006514,0.028476,0.009248,0.0,0.006187,0.008783,pass
13,0.0,0.0,0.022289,0.0,0.0,0.010730,0.043999,0.015080,0.0,0.010658,0.010434,pass

[[       nan        nan 1.28307295        nan        nan 1.24600785
  1.18502695 1.19888901        nan 1.30190466 1.11487018]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,p 4,h 3,h 5,h 8,h 0,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.345545,0.329772,0.328969,0.327447,0.319687,0.311746,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 1,h 5,h 3,p 4,h 8,h 0,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.458012,0.429447,0.427568,0.427469,0.422233,0.398635,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,p 4,h 8,h 3,h 0,h 5,h 1,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.008437,0.002266,0.000867,0.000584,0.000496,0.000488,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_x_inGap_1_.qasm

100%|██████████| 2/2 [00:00<00:00, 13.74it/s]
100%|██████████| 10/10 [00:00<00:00, 16.42it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,h 2,h 1,x 0,pass/fail
0,0.0,0.0,0.019088,0.0,0.0,0.012244,0.016568,0.0,0.008281,0.011827,0.0,fail
1,0.0,0.0,0.017841,0.0,0.0,0.010334,0.016215,0.0,0.010411,0.011477,0.0,fail
2,0.0,0.0,0.025046,0.0,0.0,0.014047,0.015231,0.0,0.011780,0.013701,0.0,pass
3,0.0,0.0,0.022114,0.0,0.0,0.009517,0.013220,0.0,0.011314,0.009223,0.0,pass
4,0.0,0.0,0.022122,0.0,0.0,0.011580,0.011820,0.0,0.012377,0.018046,0.0,pass
5,0.0,0.0,0.016948,0.0,0.0,0.010041,0.014049,0.0,0.009705,0.011422,0.0,pass
6,0.0,0.0,0.021043,0.0,0.0,0.008597,0.011360,0.0,0.008976,0.009037,0.0,pass
7,0.0,0.0,0.022924,0.0,0.0,0.008234,0.011660,0.0,0.010520,0.012537,0.0,pass
8,0.0,0.0,0.020311,0.0,0.0,0.009955,0.013291,0.0,0.011128,0.010534,0.0,pass
9,0.0,0.0,0.025043,0.0,0.0,0.012516,0.019155,0.0,0.009664,0.013659,0.0,pass
10,0.0,0.0,0.020606,0.0,0.0,0.010341,0.014839,0.0,0.011215,0.014390,0.0,pass
11,0.0,0.0,0.017079,0.0,0.0,0.005686,0.012116,0.0,0.008062,0.008067,0.0,pass

[[       nan        nan 1.03378015        nan        nan 1.08459361
  1.01074365        nan 1.11392897 1.01500649        nan]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 4,h 5,h 1,h 2,h 8,cz 10,cz 9,cz 7,cz 6,cz 3,x 0
sum,0.193381,0.183423,0.161925,0.151436,0.147616,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 4,h 5,h 1,h 2,h 8,cz 10,cz 9,cz 7,cz 6,cz 3,x 0
sum,0.242245,0.233158,0.203014,0.193609,0.185767,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 4,h 1,h 5,h 2,cz 10,cz 9,cz 7,cz 6,cz 3,x 0
sum,0.000616,0.000503,0.000256,0.000243,0.000166,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_cswap_inGap_14_.qasm

100%|██████████| 3/3 [00:00<00:00,  3.09it/s]
100%|██████████| 10/10 [00:03<00:00,  3.27it/s]

,cswap 10,cz 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.621095,0.121242,0.0,0.029137,0.030081,0.077289,0.051215,0.051484,0.0,0.015177,0.023138,fail
1,0.545353,0.110480,0.0,0.027212,0.027081,0.081182,0.048082,0.048975,0.0,0.013384,0.021341,fail
2,0.605038,0.117400,0.0,0.037143,0.034448,0.096305,0.059702,0.059134,0.0,0.015597,0.016602,fail
3,0.518976,0.105862,0.0,0.031843,0.029615,0.094147,0.052567,0.053926,0.0,0.014471,0.017191,pass
4,0.398586,0.058246,0.0,0.024160,0.021565,0.054114,0.042243,0.042365,0.0,0.012103,0.017073,pass
5,0.300849,0.059682,0.0,0.013648,0.015601,0.039246,0.028161,0.027662,0.0,0.006453,0.007568,pass
6,0.666459,0.129337,0.0,0.031388,0.033053,0.103368,0.058847,0.061180,0.0,0.018977,0.019913,pass
7,0.250863,0.044486,0.0,0.013859,0.012739,0.034290,0.023714,0.023795,0.0,0.006388,0.006232,pass
8,0.628911,0.130770,0.0,0.026214,0.025637,0.086527,0.040172,0.040173,0.0,0.011658,0.012997,pass
9,0.503008,0.084934,0.0,0.036116,0.036429,0.075271,0.066012,0.065584,0.0,0.017494,0.022502,pass
10,0.532360,0.109378,0.0,0.029070,0.026099,0.086321,0.046204,0.048111,0.0,0.013327,0.014620,pass
11,0.481801,0.109035,0.0,0.030957,0.034006,0.078946,0.057002,0.055987,0.0,0.013684,0.015982,pass
12,0.549968,0.115815,0.0,0.033810,0.036292,0.090756,0.062787,0.062982,0.0,0.016131,0.011759,pass

[[1.05182007 1.04183026        nan 1.19184836 1.12809221 1.13399336
  1.12645483 1.11158826        nan 1.05964722 1.13642808]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 0,cz 9,cswap 10,h 7,cz 5,cz 6,h 1,h 4,h 3,cz 8,cz 2
sum,0.295196,0.269245,0.268274,0.256454,0.255347,0.252614,0.252558,0.249721,0.248835,0.0,0.0

custom SCORES

,h 0,cz 9,cswap 10,h 7,cz 5,cz 6,h 4,h 1,h 3,cz 8,cz 2
sum,0.379064,0.339372,0.338818,0.332867,0.327738,0.323857,0.320046,0.319464,0.317986,0.0,0.0

DSTAR SCORES

,cswap 10,cz 9,cz 5,h 3,h 4,h 7,cz 6,h 0,h 1,cz 8,cz 2
sum,0.400696,0.030876,0.017342,0.007315,0.007269,0.002672,0.002566,0.001186,0.000623,0.0,0.0

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_cswap_inGap_12_.qasm

100%|██████████| 6/6 [00:02<00:00,  2.86it/s]
100%|██████████| 10/10 [00:03<00:00,  3.26it/s]

,cswap 10,cz 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.356461,0.0,0.0,0.011011,0.011171,0.006192,0.015024,0.012048,0.020357,0.014700,0.011160,fail
1,0.450507,0.0,0.0,0.029255,0.018705,0.010511,0.022895,0.016906,0.033440,0.021878,0.012364,fail
2,0.550532,0.0,0.0,0.028465,0.023090,0.013169,0.027592,0.018117,0.041989,0.027609,0.017569,fail
3,0.442613,0.0,0.0,0.021434,0.014796,0.008402,0.019998,0.013288,0.031780,0.019692,0.012846,fail
4,0.480178,0.0,0.0,0.027040,0.023378,0.014136,0.026858,0.016945,0.044945,0.027332,0.017732,fail
5,0.549422,0.0,0.0,0.027820,0.022739,0.013593,0.028259,0.018094,0.038149,0.027573,0.014432,fail
6,0.376535,0.0,0.0,0.027631,0.011946,0.006464,0.016058,0.015532,0.020434,0.014992,0.012585,pass
7,0.518087,0.0,0.0,0.021919,0.023354,0.013232,0.027029,0.016741,0.040746,0.027436,0.018969,pass
8,0.439357,0.0,0.0,0.027024,0.020638,0.012244,0.024964,0.017300,0.031168,0.024105,0.016753,pass
9,0.567630,0.0,0.0,0.032881,0.025054,0.013233,0.027132,0.020244,0.037456,0.027244,0.015100,pass
10,0.521266,0.0,0.0,0.028497,0.026227,0.014989,0.029948,0.016810,0.041180,0.030436,0.017943,pass
11,0.445791,0.0,0.0,0.024514,0.019459,0.011811,0.024259,0.015323,0.037121,0.024255,0.016157,pass
12,0.543570,0.0,0.0,0.020673,0.026682,0.014307,0.026457,0.017371,0.043998,0.026903,0.015418,pass
13,0.499531,0.0,0.0,0.027973,0.023404,0.013061,0.025345,0.017143,0.045627,0.025406,0.016628,pass
14,0.375635,0.0,0.0,0.020552,0.013570,0.009489,0.020150,0.015894,0.020920,0.020126,0.012360,pass
15,0.496242,0.0,0.0,0.025823,0.019677,0.009611,0.022735,0.014936,0.033355,0.022002,0.014563,pass

[[1.16732432        nan        nan 1.21032489 1.23174145 1.28502076
  1.20571879 1.13943229 1.28011524 1.19360537 1.2356407 ]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,cz 2,cswap 10,h 4,h 1,h 3,h 7,cz 5,h 0,cz 6,cz 9,cz 8
sum,0.374395,0.371677,0.365544,0.363603,0.363156,0.360299,0.357843,0.354953,0.351598,0.0,0.0

custom SCORES

,cz 2,cswap 10,h 4,cz 5,h 1,h 7,h 3,h 0,cz 6,cz 9,cz 8
sum,0.494212,0.480144,0.47573,0.472801,0.472102,0.469318,0.466604,0.464601,0.459867,0.0,0.0

DSTAR SCORES

,cswap 10,cz 2,h 7,h 4,h 1,cz 6,h 3,h 0,cz 5,cz 9,cz 8
sum,0.742538,0.006986,0.003361,0.003167,0.003085,0.002088,0.001476,0.001204,0.000712,0.0,0.0

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_rz_inGap_12_.qasm

100%|██████████| 4/4 [00:00<00:00, 16.71it/s]
100%|██████████| 10/10 [00:00<00:00, 17.19it/s]

,cz 10,cz 9,h 8,cz 7,rz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.025850,0.0,0.0,0.0,0.012396,0.014482,0.0,0.011433,0.016136,fail
1,0.0,0.0,0.025176,0.0,0.0,0.0,0.016077,0.016612,0.0,0.011328,0.013406,fail
2,0.0,0.0,0.016862,0.0,0.0,0.0,0.011907,0.012243,0.0,0.007428,0.012225,fail
3,0.0,0.0,0.024653,0.0,0.0,0.0,0.009880,0.015995,0.0,0.010674,0.013139,fail
4,0.0,0.0,0.028113,0.0,0.0,0.0,0.013231,0.016611,0.0,0.013254,0.013520,pass
5,0.0,0.0,0.016430,0.0,0.0,0.0,0.007966,0.015929,0.0,0.014391,0.015264,pass
6,0.0,0.0,0.025899,0.0,0.0,0.0,0.013652,0.020140,0.0,0.009854,0.012004,pass
7,0.0,0.0,0.027644,0.0,0.0,0.0,0.014235,0.022748,0.0,0.013242,0.013855,pass
8,0.0,0.0,0.017833,0.0,0.0,0.0,0.007644,0.009917,0.0,0.007407,0.009235,pass
9,0.0,0.0,0.024355,0.0,0.0,0.0,0.010028,0.012696,0.0,0.009262,0.012184,pass
10,0.0,0.0,0.022878,0.0,0.0,0.0,0.013488,0.018823,0.0,0.010532,0.019759,pass
11,0.0,0.0,0.026785,0.0,0.0,0.0,0.009561,0.016415,0.0,0.010460,0.013026,pass
12,0.0,0.0,0.035404,0.0,0.0,0.0,0.016907,0.022809,0.0,0.014333,0.015125,pass
13,0.0,0.0,0.015268,0.0,0.0,0.0,0.007371,0.011023,0.0,0.005425,0.006058,pass

[[       nan        nan 1.11732633        nan        nan        nan
  1.27948308 1.11996313        nan 1.11912676 1.17553085]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 4,h 0,h 8,h 1,h 3,cz 10,cz 9,cz 7,rz 6,cz 5,cz 2
sum,0.305825,0.296892,0.277775,0.274203,0.262018,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 4,h 0,h 8,h 1,h 3,cz 10,cz 9,cz 7,rz 6,cz 5,cz 2
sum,0.40365,0.384143,0.355367,0.35092,0.33538,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 3,h 0,h 4,h 1,cz 10,cz 9,cz 7,rz 6,cz 5,cz 2
sum,0.002019,0.000845,0.00073,0.000614,0.000406,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
6
Now evolving the following mutant:  AddGate_rz_inGap_13_.qasm

100%|██████████| 4/4 [00:00<00:00, 16.61it/s]
100%|██████████| 10/10 [00:00<00:00, 17.33it/s]

,rz 10,cz 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.0,0.029041,0.0,0.0,0.013047,0.007824,0.0,0.010845,0.015403,fail
1,0.0,0.0,0.0,0.026801,0.0,0.0,0.012702,0.016208,0.0,0.008911,0.012133,fail
2,0.0,0.0,0.0,0.025145,0.0,0.0,0.012072,0.017759,0.0,0.011220,0.014843,fail
3,0.0,0.0,0.0,0.027216,0.0,0.0,0.008673,0.018318,0.0,0.012468,0.010743,fail
4,0.0,0.0,0.0,0.014298,0.0,0.0,0.007828,0.009643,0.0,0.007316,0.007376,pass
5,0.0,0.0,0.0,0.017225,0.0,0.0,0.008138,0.012763,0.0,0.008173,0.009226,pass
6,0.0,0.0,0.0,0.023668,0.0,0.0,0.009340,0.011664,0.0,0.010592,0.014415,pass
7,0.0,0.0,0.0,0.020400,0.0,0.0,0.011331,0.013008,0.0,0.009953,0.014882,pass
8,0.0,0.0,0.0,0.024020,0.0,0.0,0.010165,0.022647,0.0,0.012088,0.013876,pass
9,0.0,0.0,0.0,0.024565,0.0,0.0,0.013172,0.017366,0.0,0.013380,0.011383,pass
10,0.0,0.0,0.0,0.026306,0.0,0.0,0.011998,0.016788,0.0,0.011800,0.012191,pass
11,0.0,0.0,0.0,0.017552,0.0,0.0,0.013494,0.012248,0.0,0.009898,0.012118,pass
12,0.0,0.0,0.0,0.019559,0.0,0.0,0.009927,0.016440,0.0,0.010405,0.015908,pass
13,0.0,0.0,0.0,0.019691,0.0,0.0,0.009354,0.012682,0.0,0.002954,0.007897,pass

[[       nan        nan        nan 1.07356039        nan        nan
  1.12247326 1.21898917        nan 1.14796063 1.15984182]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 7,h 1,h 0,h 4,h 3,rz 10,cz 9,cz 8,cz 6,cz 5,cz 2
sum,0.342975,0.310307,0.308147,0.307413,0.292709,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 7,h 1,h 0,h 4,h 3,rz 10,cz 9,cz 8,cz 6,cz 5,cz 2
sum,0.435026,0.399362,0.397497,0.393679,0.381911,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 7,h 3,h 0,h 4,h 1,rz 10,cz 9,cz 8,cz 6,cz 5,cz 2
sum,0.002783,0.000872,0.000685,0.000527,0.000461,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_rxx_inGap_13_.qasm

100%|██████████| 6/6 [00:00<00:00,  6.39it/s]
100%|██████████| 10/10 [00:01<00:00,  6.65it/s]

,rxx 10,cz 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.848119,0.456785,0.0,0.047721,0.295446,0.359231,0.154844,0.244542,0.0,0.025377,0.044774,fail
1,0.847831,0.471640,0.0,0.051020,0.293702,0.332047,0.225178,0.176161,0.0,0.022795,0.040451,fail
2,0.894423,0.527696,0.0,0.058149,0.304413,0.383684,0.183128,0.226553,0.0,0.031045,0.041561,fail
3,0.898051,0.501005,0.0,0.053348,0.310271,0.389643,0.186480,0.233936,0.0,0.032218,0.051348,fail
4,0.751088,0.478227,0.0,0.061981,0.264765,0.298603,0.153755,0.216255,0.0,0.023313,0.039411,fail
5,0.505308,0.314332,0.0,0.048636,0.164776,0.253327,0.100653,0.142572,0.0,0.023770,0.024966,fail
6,0.498388,0.348236,0.0,0.051549,0.164019,0.211827,0.151268,0.073446,0.0,0.016411,0.021468,pass
7,0.484493,0.249865,0.0,0.031085,0.164563,0.222252,0.125084,0.101197,0.0,0.018800,0.022211,pass
8,0.668189,0.402180,0.0,0.050276,0.232360,0.309574,0.149447,0.171191,0.0,0.031178,0.048744,pass
9,0.902041,0.547159,0.0,0.064390,0.305927,0.412290,0.166966,0.245599,0.0,0.028114,0.042023,pass
10,0.536006,0.310831,0.0,0.039322,0.190097,0.245054,0.127778,0.132859,0.0,0.027860,0.039185,pass
11,0.701314,0.385220,0.0,0.048347,0.243659,0.298463,0.136892,0.195678,0.0,0.026136,0.035429,pass
12,0.618701,0.265798,0.0,0.021836,0.221620,0.259945,0.130605,0.170407,0.0,0.024523,0.043937,pass
13,0.453562,0.323148,0.0,0.051191,0.153134,0.208738,0.090384,0.124913,0.0,0.018466,0.018556,pass
14,0.719095,0.468913,0.0,0.058498,0.241473,0.319957,0.192903,0.136072,0.0,0.027681,0.032339,pass
15,0.796038,0.447289,0.0,0.048157,0.278518,0.348150,0.145719,0.229074,0.0,0.023124,0.027068,pass

[[1.13561862 1.15146785        nan 1.15903912 1.13974407 1.15934319
  1.34563543 1.18325005        nan 1.21946662 1.27041814]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 3,cz 6,rxx 10,cz 9,h 0,cz 5,h 4,h 7,h 1,cz 8,cz 2
sum,0.439652,0.426608,0.426591,0.423138,0.422883,0.415542,0.414706,0.408469,0.395494,0.0,0.0

custom SCORES

,h 3,h 0,h 4,cz 6,rxx 10,cz 9,cz 5,h 7,h 1,cz 8,cz 2
sum,0.569707,0.557192,0.554217,0.548164,0.547702,0.544945,0.53598,0.526827,0.516066,0.0,0.0

DSTAR SCORES

,rxx 10,cz 9,cz 5,cz 6,h 3,h 4,h 7,h 0,h 1,cz 8,cz 2
sum,1.818843,0.775572,0.460196,0.325539,0.202844,0.135916,0.015925,0.00929,0.004025,0.0,0.0

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_ry_inGap_14_.qasm

100%|██████████| 1/1 [00:00<00:00, 16.48it/s]
100%|██████████| 10/10 [00:00<00:00, 17.76it/s]

,cz 10,cz 9,h 8,ry 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.032447,0.127813,0.0,0.0,0.012634,0.019796,0.0,0.010780,0.010559,fail
1,0.0,0.0,0.007905,0.061588,0.0,0.0,0.005097,0.006005,0.0,0.005829,0.007847,pass
2,0.0,0.0,0.025345,0.100389,0.0,0.0,0.009579,0.010004,0.0,0.012363,0.013901,pass
3,0.0,0.0,0.011271,0.079525,0.0,0.0,0.007648,0.007063,0.0,0.006306,0.006222,pass
4,0.0,0.0,0.017638,0.083749,0.0,0.0,0.007047,0.013256,0.0,0.007215,0.010979,pass
5,0.0,0.0,0.019502,0.103913,0.0,0.0,0.009703,0.017054,0.0,0.006892,0.008588,pass
6,0.0,0.0,0.025527,0.127254,0.0,0.0,0.012127,0.016862,0.0,0.011764,0.015354,pass
7,0.0,0.0,0.025505,0.133710,0.0,0.0,0.012832,0.019136,0.0,0.010273,0.011520,pass
8,0.0,0.0,0.020952,0.123800,0.0,0.0,0.011482,0.018629,0.0,0.012915,0.012167,pass
9,0.0,0.0,0.022714,0.095891,0.0,0.0,0.009500,0.013840,0.0,0.008474,0.013234,pass
10,0.0,0.0,0.030214,0.123312,0.0,0.0,0.011140,0.016917,0.0,0.014059,0.013844,pass

[[nan nan  1.  1. nan nan  1.  1. nan  1.  1.]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 8,h 3,h 4,ry 7,h 1,h 0,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.135751,0.124845,0.116131,0.110094,0.100873,0.085006,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 8,h 3,h 4,ry 7,h 1,h 0,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.169689,0.156057,0.145163,0.137618,0.126091,0.106257,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,ry 7,h 8,h 3,h 4,h 1,h 0,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.008035,0.000873,0.000344,0.000146,0.000106,0.0001,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
7
Now evolving the following mutant:  AddGate_rz_inGap_15_.qasm

100%|██████████| 5/5 [00:00<00:00, 16.87it/s]
100%|██████████| 10/10 [00:00<00:00, 16.97it/s]

,rz 10,cz 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.0,0.022415,0.0,0.0,0.008287,0.017476,0.0,0.007045,0.011463,fail
1,0.0,0.0,0.0,0.028197,0.0,0.0,0.010595,0.017019,0.0,0.010589,0.019493,fail
2,0.0,0.0,0.0,0.025761,0.0,0.0,0.011997,0.017823,0.0,0.010752,0.014628,fail
3,0.0,0.0,0.0,0.020211,0.0,0.0,0.011539,0.018793,0.0,0.011466,0.012716,fail
4,0.0,0.0,0.0,0.026044,0.0,0.0,0.012777,0.014589,0.0,0.010000,0.013749,fail
5,0.0,0.0,0.0,0.024170,0.0,0.0,0.008772,0.013708,0.0,0.011599,0.015426,pass
6,0.0,0.0,0.0,0.020264,0.0,0.0,0.012087,0.015525,0.0,0.007589,0.012072,pass
7,0.0,0.0,0.0,0.023600,0.0,0.0,0.012729,0.019685,0.0,0.009600,0.016357,pass
8,0.0,0.0,0.0,0.013850,0.0,0.0,0.008220,0.013307,0.0,0.008596,0.008443,pass
9,0.0,0.0,0.0,0.027409,0.0,0.0,0.013272,0.013394,0.0,0.013461,0.013168,pass
10,0.0,0.0,0.0,0.024937,0.0,0.0,0.010212,0.016427,0.0,0.007956,0.011683,pass
11,0.0,0.0,0.0,0.015662,0.0,0.0,0.007462,0.008316,0.0,0.007856,0.007606,pass
12,0.0,0.0,0.0,0.028406,0.0,0.0,0.014766,0.021549,0.0,0.014360,0.011526,pass
13,0.0,0.0,0.0,0.018511,0.0,0.0,0.011382,0.011878,0.0,0.003744,0.010254,pass
14,0.0,0.0,0.0,0.013309,0.0,0.0,0.007182,0.009707,0.0,0.005672,0.012511,pass

[[       nan        nan        nan 1.14970382        nan        nan
  1.15746513 1.09642051        nan 1.14997711 1.35272157]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 0,h 3,h 7,h 1,h 4,rz 10,cz 9,cz 8,cz 6,cz 5,cz 2
sum,0.377035,0.373916,0.368534,0.355361,0.342228,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 0,h 3,h 7,h 1,h 4,rz 10,cz 9,cz 8,cz 6,cz 5,cz 2
sum,0.504541,0.476408,0.474461,0.457526,0.441257,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 7,h 3,h 0,h 4,h 1,rz 10,cz 9,cz 8,cz 6,cz 5,cz 2
sum,0.002886,0.001428,0.001014,0.000597,0.000488,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_ry_inGap_9_.qasm

100%|██████████| 6/6 [00:00<00:00, 14.29it/s]
100%|██████████| 10/10 [00:00<00:00, 17.18it/s]

,cz 10,cz 9,ry 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.139172,0.027834,0.0,0.0,0.014123,0.013520,0.0,0.007428,0.010564,fail
1,0.0,0.0,0.107589,0.021518,0.0,0.0,0.010265,0.017967,0.0,0.011255,0.011190,fail
2,0.0,0.0,0.118301,0.023660,0.0,0.0,0.009099,0.015527,0.0,0.013075,0.013182,fail
3,0.0,0.0,0.145822,0.029164,0.0,0.0,0.010382,0.016588,0.0,0.013309,0.011347,fail
4,0.0,0.0,0.129685,0.025937,0.0,0.0,0.010949,0.015211,0.0,0.013185,0.011915,fail
5,0.0,0.0,0.078235,0.015647,0.0,0.0,0.012561,0.013230,0.0,0.009822,0.009939,fail
6,0.0,0.0,0.114799,0.022960,0.0,0.0,0.012634,0.017326,0.0,0.009184,0.018192,pass
7,0.0,0.0,0.104826,0.020965,0.0,0.0,0.012928,0.013601,0.0,0.009478,0.008363,pass
8,0.0,0.0,0.083398,0.016680,0.0,0.0,0.007570,0.009232,0.0,0.008692,0.014021,pass
9,0.0,0.0,0.099100,0.019820,0.0,0.0,0.009438,0.012568,0.0,0.005861,0.008209,pass
10,0.0,0.0,0.132842,0.026568,0.0,0.0,0.012362,0.006892,0.0,0.005581,0.008503,pass
11,0.0,0.0,0.074321,0.014864,0.0,0.0,0.008714,0.012085,0.0,0.007950,0.008560,pass
12,0.0,0.0,0.106437,0.021287,0.0,0.0,0.010535,0.011738,0.0,0.012152,0.016425,pass
13,0.0,0.0,0.147392,0.029478,0.0,0.0,0.011612,0.015979,0.0,0.012197,0.015779,pass
14,0.0,0.0,0.117880,0.023576,0.0,0.0,0.011006,0.013519,0.0,0.010291,0.011927,pass
15,0.0,0.0,0.152433,0.030487,0.0,0.0,0.015594,0.022319,0.0,0.009935,0.009334,pass

[[       nan        nan 1.21720509 1.21720509        nan        nan
  1.25762709 1.1712006         nan 1.17309285 1.16076631]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,h 3,ry 8,h 7,h 4,h 0,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.427074,0.404941,0.388075,0.388075,0.374804,0.363492,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 1,h 3,ry 8,h 7,h 4,h 0,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.552323,0.523507,0.506166,0.506166,0.492645,0.468974,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,ry 8,h 7,h 3,h 1,h 0,h 4,cz 10,cz 9,cz 6,cz 5,cz 2
sum,0.072431,0.003319,0.001381,0.000761,0.000759,0.000743,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_z_inGap_9_.qasm

100%|██████████| 5/5 [00:00<00:00, 15.00it/s]
100%|██████████| 10/10 [00:00<00:00, 15.38it/s]

,cz 10,cz 9,z 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.0,0.027476,0.0,0.0,0.011040,0.017109,0.0,0.009974,0.012217,fail
1,0.0,0.0,0.0,0.017972,0.0,0.0,0.009615,0.004998,0.0,0.007311,0.012083,fail
2,0.0,0.0,0.0,0.028950,0.0,0.0,0.012338,0.016126,0.0,0.015139,0.014161,fail
3,0.0,0.0,0.0,0.020756,0.0,0.0,0.010666,0.015333,0.0,0.012127,0.015268,fail
4,0.0,0.0,0.0,0.026170,0.0,0.0,0.013948,0.022654,0.0,0.011623,0.012830,fail
5,0.0,0.0,0.0,0.029821,0.0,0.0,0.009296,0.017197,0.0,0.012838,0.009499,pass
6,0.0,0.0,0.0,0.023232,0.0,0.0,0.011979,0.013835,0.0,0.009994,0.015758,pass
7,0.0,0.0,0.0,0.025605,0.0,0.0,0.009874,0.016196,0.0,0.009864,0.012665,pass
8,0.0,0.0,0.0,0.020804,0.0,0.0,0.008651,0.016437,0.0,0.008395,0.010597,pass
9,0.0,0.0,0.0,0.022686,0.0,0.0,0.011997,0.016117,0.0,0.007222,0.011178,pass
10,0.0,0.0,0.0,0.024117,0.0,0.0,0.011427,0.012569,0.0,0.008720,0.011131,pass
11,0.0,0.0,0.0,0.011793,0.0,0.0,0.007109,0.009225,0.0,0.004189,0.010411,pass
12,0.0,0.0,0.0,0.027360,0.0,0.0,0.010013,0.015036,0.0,0.008761,0.015540,pass
13,0.0,0.0,0.0,0.013967,0.0,0.0,0.008393,0.013772,0.0,0.007030,0.012722,pass
14,0.0,0.0,0.0,0.012701,0.0,0.0,0.007301,0.011840,0.0,0.005712,0.006880,pass

[[       nan        nan        nan 1.19309983        nan        nan
  1.21061426 1.48609437        nan 1.34750445 1.146946  ]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,h 4,h 7,h 0,h 3,cz 10,cz 9,z 8,cz 6,cz 5,cz 2
sum,0.404425,0.374932,0.363886,0.363832,0.348919,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 1,h 4,h 3,h 7,h 0,cz 10,cz 9,z 8,cz 6,cz 5,cz 2
sum,0.540666,0.488407,0.478551,0.472425,0.468156,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 7,h 3,h 0,h 4,h 1,cz 10,cz 9,z 8,cz 6,cz 5,cz 2
sum,0.002824,0.00113,0.000866,0.000651,0.000621,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_z_inGap_1_.qasm

100%|██████████| 6/6 [00:00<00:00, 16.37it/s]
100%|██████████| 10/10 [00:00<00:00, 16.43it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,h 2,h 1,z 0,pass/fail
0,0.0,0.0,0.029646,0.0,0.0,0.018783,0.018648,0.0,0.012270,0.015739,0.025292,fail
1,0.0,0.0,0.017041,0.0,0.0,0.011619,0.012080,0.0,0.010838,0.010560,0.020191,fail
2,0.0,0.0,0.022525,0.0,0.0,0.011065,0.014358,0.0,0.010604,0.015962,0.028410,fail
3,0.0,0.0,0.020893,0.0,0.0,0.009060,0.014403,0.0,0.008825,0.011102,0.020630,fail
4,0.0,0.0,0.031512,0.0,0.0,0.012959,0.015173,0.0,0.012476,0.017686,0.030092,fail
5,0.0,0.0,0.035538,0.0,0.0,0.016626,0.018360,0.0,0.014098,0.014030,0.020836,fail
6,0.0,0.0,0.029940,0.0,0.0,0.011295,0.019671,0.0,0.012700,0.013385,0.021669,pass
7,0.0,0.0,0.019881,0.0,0.0,0.011197,0.017301,0.0,0.010090,0.009327,0.015594,pass
8,0.0,0.0,0.017339,0.0,0.0,0.012443,0.012390,0.0,0.008338,0.009761,0.016921,pass
9,0.0,0.0,0.026126,0.0,0.0,0.012197,0.017145,0.0,0.010931,0.012247,0.016740,pass
10,0.0,0.0,0.023655,0.0,0.0,0.009762,0.020370,0.0,0.013023,0.010374,0.019700,pass
11,0.0,0.0,0.024257,0.0,0.0,0.010823,0.018478,0.0,0.009579,0.012607,0.018592,pass
12,0.0,0.0,0.016606,0.0,0.0,0.007763,0.011340,0.0,0.007240,0.007914,0.012382,pass
13,0.0,0.0,0.018834,0.0,0.0,0.011362,0.012321,0.0,0.009292,0.014222,0.024716,pass
14,0.0,0.0,0.020575,0.0,0.0,0.011349,0.006160,0.0,0.007494,0.012516,0.020644,pass
15,0.0,0.0,0.022671,0.0,0.0,0.009716,0.017279,0.0,0.008522,0.009306,0.015901,pass

[[       nan        nan 1.356791          nan        nan 1.40674341
  1.20281004        nan 1.22398839 1.24723775 1.24133117]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,z 0,h 1,h 5,h 8,h 2,h 4,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.443029,0.43245,0.426086,0.416816,0.41553,0.378947,0.0,0.0,0.0,0.0,0.0

custom SCORES

,z 0,h 5,h 1,h 8,h 2,h 4,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.580515,0.575935,0.567292,0.558199,0.542681,0.492897,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,z 0,h 4,h 1,h 5,h 2,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.003971,0.003422,0.001406,0.001184,0.001051,0.000783,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_z_inGap_6_.qasm

100%|██████████| 4/4 [00:00<00:00, 16.37it/s]
100%|██████████| 10/10 [00:00<00:00, 17.26it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,z 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.023105,0.0,0.0,0.0,0.008422,0.013807,0.0,0.011858,0.014476,fail
1,0.0,0.0,0.024899,0.0,0.0,0.0,0.012178,0.010784,0.0,0.013914,0.014183,fail
2,0.0,0.0,0.024020,0.0,0.0,0.0,0.010944,0.009073,0.0,0.006512,0.011471,fail
3,0.0,0.0,0.028605,0.0,0.0,0.0,0.009179,0.017740,0.0,0.011739,0.014209,fail
4,0.0,0.0,0.028861,0.0,0.0,0.0,0.010229,0.015527,0.0,0.009687,0.015485,pass
5,0.0,0.0,0.023383,0.0,0.0,0.0,0.012218,0.011252,0.0,0.010826,0.010384,pass
6,0.0,0.0,0.024768,0.0,0.0,0.0,0.013074,0.016129,0.0,0.009465,0.010959,pass
7,0.0,0.0,0.022734,0.0,0.0,0.0,0.013100,0.015525,0.0,0.006999,0.013590,pass
8,0.0,0.0,0.024895,0.0,0.0,0.0,0.008683,0.015908,0.0,0.013037,0.014793,pass
9,0.0,0.0,0.014975,0.0,0.0,0.0,0.006679,0.008221,0.0,0.005807,0.011519,pass
10,0.0,0.0,0.033155,0.0,0.0,0.0,0.013418,0.017820,0.0,0.013302,0.016172,pass
11,0.0,0.0,0.023740,0.0,0.0,0.0,0.013316,0.014171,0.0,0.009605,0.009093,pass
12,0.0,0.0,0.021648,0.0,0.0,0.0,0.007249,0.012338,0.0,0.008233,0.016149,pass
13,0.0,0.0,0.020284,0.0,0.0,0.0,0.009251,0.013499,0.0,0.006446,0.007375,pass

[[       nan        nan 1.13705142        nan        nan        nan
  1.19618067 1.38041719        nan 1.26426233 1.06562166]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,h 0,h 8,h 4,h 3,cz 10,cz 9,cz 7,cz 6,z 5,cz 2
sum,0.320334,0.302122,0.296776,0.275269,0.268017,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 1,h 0,h 8,h 3,h 4,cz 10,cz 9,cz 7,cz 6,z 5,cz 2
sum,0.421581,0.382608,0.381139,0.36051,0.357587,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 0,h 3,h 1,h 4,cz 10,cz 9,cz 7,cz 6,z 5,cz 2
sum,0.002389,0.000716,0.000638,0.000473,0.000404,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_h_inGap_9_.qasm

100%|██████████| 10/10 [00:00<00:00, 16.34it/s]
100%|██████████| 10/10 [00:00<00:00, 16.91it/s]

,cz 10,cz 9,h 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.018995,0.0,0.0,0.0,0.008393,0.011173,0.0,0.010850,0.009135,fail
1,0.0,0.0,0.016169,0.0,0.0,0.0,0.008071,0.011383,0.0,0.007675,0.010484,fail
2,0.0,0.0,0.029987,0.0,0.0,0.0,0.007198,0.012898,0.0,0.009318,0.012871,fail
3,0.0,0.0,0.025327,0.0,0.0,0.0,0.008193,0.013786,0.0,0.010538,0.010307,fail
4,0.0,0.0,0.018369,0.0,0.0,0.0,0.009366,0.013446,0.0,0.008612,0.010260,fail
5,0.0,0.0,0.029275,0.0,0.0,0.0,0.008412,0.014371,0.0,0.007843,0.011202,fail
6,0.0,0.0,0.027518,0.0,0.0,0.0,0.007467,0.014940,0.0,0.007785,0.009482,fail
7,0.0,0.0,0.033963,0.0,0.0,0.0,0.008060,0.013799,0.0,0.011967,0.014222,fail
8,0.0,0.0,0.026036,0.0,0.0,0.0,0.007091,0.010250,0.0,0.007734,0.013705,fail
9,0.0,0.0,0.023578,0.0,0.0,0.0,0.005750,0.008608,0.0,0.008618,0.007851,fail
10,0.0,0.0,0.022474,0.0,0.0,0.0,0.008733,0.013998,0.0,0.009705,0.015726,pass
11,0.0,0.0,0.019785,0.0,0.0,0.0,0.005964,0.006180,0.0,0.005142,0.009374,pass
12,0.0,0.0,0.024609,0.0,0.0,0.0,0.007287,0.009125,0.0,0.008946,0.010169,pass
13,0.0,0.0,0.021953,0.0,0.0,0.0,0.008399,0.014163,0.0,0.008079,0.009521,pass
14,0.0,0.0,0.025945,0.0,0.0,0.0,0.008032,0.008201,0.0,0.006325,0.011650,pass
15,0.0,0.0,0.021254,0.0,0.0,0.0,0.007186,0.009352,0.0,0.005592,0.010750,pass
16,0.0,0.0,0.026979,0.0,0.0,0.0,0.009840,0.012681,0.0,0.010696,0.009873,pass
17,0.0,0.0,0.025957,0.0,0.0,0.0,0.008792,0.011453,0.0,0.007428,0.007630,pass
18,0.0,0.0,0.015854,0.0,0.0,0.0,0.009188,0.013448,0.0,0.010868,0.012756,pass
19,0.0,0.0,0.019856,0.0,0.0,0.0,0.009097,0.012185,0.0,0.006127,0.006959,pass

[[       nan        nan 1.36278173        nan        nan        nan
  1.2007766  1.19849676        nan 1.31593364 1.29859251]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,h 3,h 8,h 0,h 4,cz 10,cz 9,h 7,cz 6,cz 5,cz 2
sum,0.535415,0.529446,0.525904,0.511949,0.485936,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 1,h 8,h 3,h 0,h 4,cz 10,cz 9,h 7,cz 6,cz 5,cz 2
sum,0.711558,0.705077,0.688081,0.678152,0.631811,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 3,h 0,h 1,h 4,cz 10,cz 9,h 7,cz 6,cz 5,cz 2
sum,0.006075,0.001537,0.001187,0.000821,0.000603,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_h_inGap_6_.qasm

100%|██████████| 10/10 [00:00<00:00, 16.42it/s]
100%|██████████| 10/10 [00:00<00:00, 15.99it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.020208,0.0,0.0,0.011624,0.003193,0.011572,0.0,0.008682,0.012173,fail
1,0.0,0.0,0.023053,0.0,0.0,0.011518,0.004101,0.012025,0.0,0.009097,0.012334,fail
2,0.0,0.0,0.019484,0.0,0.0,0.008443,0.001333,0.011351,0.0,0.008513,0.007767,fail
3,0.0,0.0,0.026186,0.0,0.0,0.012717,0.003969,0.014123,0.0,0.008852,0.012533,fail
4,0.0,0.0,0.029838,0.0,0.0,0.017509,0.007408,0.012141,0.0,0.007794,0.011880,fail
5,0.0,0.0,0.021428,0.0,0.0,0.011225,0.002434,0.009649,0.0,0.010722,0.008930,fail
6,0.0,0.0,0.028160,0.0,0.0,0.014733,0.005384,0.013087,0.0,0.009308,0.014104,fail
7,0.0,0.0,0.024684,0.0,0.0,0.013761,0.004851,0.013097,0.0,0.008614,0.013745,fail
8,0.0,0.0,0.016978,0.0,0.0,0.009126,0.002369,0.005447,0.0,0.008316,0.011091,fail
9,0.0,0.0,0.019031,0.0,0.0,0.010407,0.002454,0.014070,0.0,0.008657,0.014695,fail
10,0.0,0.0,0.024834,0.0,0.0,0.011951,0.004139,0.011085,0.0,0.007781,0.008346,pass
11,0.0,0.0,0.027256,0.0,0.0,0.010586,0.003641,0.014650,0.0,0.006224,0.010525,pass
12,0.0,0.0,0.020720,0.0,0.0,0.007463,0.001976,0.013091,0.0,0.009790,0.012767,pass
13,0.0,0.0,0.025777,0.0,0.0,0.010639,0.003273,0.011226,0.0,0.009689,0.011890,pass
14,0.0,0.0,0.023961,0.0,0.0,0.015706,0.006198,0.009653,0.0,0.007955,0.009888,pass
15,0.0,0.0,0.020309,0.0,0.0,0.008099,0.002667,0.008851,0.0,0.004542,0.006254,pass
16,0.0,0.0,0.023276,0.0,0.0,0.008267,0.002521,0.009028,0.0,0.009562,0.010176,pass
17,0.0,0.0,0.016414,0.0,0.0,0.007922,0.002910,0.006655,0.0,0.006337,0.007746,pass
18,0.0,0.0,0.022659,0.0,0.0,0.014913,0.003496,0.012668,0.0,0.009345,0.011817,pass
19,0.0,0.0,0.026661,0.0,0.0,0.011353,0.004061,0.010593,0.0,0.005170,0.006763,pass

[[       nan        nan 1.30268532        nan        nan 1.44626773
  1.97566327 1.21160184        nan 1.21080808 1.23222306]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 0,h 1,h 5,h 3,h 4,h 8,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.553573,0.536861,0.531063,0.520223,0.51806,0.496945,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 4,h 0,h 5,h 1,h 3,h 8,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.773938,0.724105,0.723078,0.699369,0.677799,0.658785,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 5,h 0,h 3,h 1,h 4,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.005128,0.00145,0.001409,0.001344,0.000778,0.00014,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rz_inGap_9_.qasm

100%|██████████| 5/5 [00:00<00:00, 16.70it/s]
100%|██████████| 10/10 [00:00<00:00, 16.91it/s]

,cz 10,cz 9,rz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.0,0.027025,0.0,0.0,0.015606,0.016496,0.0,0.010496,0.012194,fail
1,0.0,0.0,0.0,0.021867,0.0,0.0,0.009484,0.015327,0.0,0.012369,0.009988,fail
2,0.0,0.0,0.0,0.029699,0.0,0.0,0.011487,0.012174,0.0,0.012165,0.011293,fail
3,0.0,0.0,0.0,0.020970,0.0,0.0,0.011191,0.017633,0.0,0.012692,0.013989,fail
4,0.0,0.0,0.0,0.027593,0.0,0.0,0.009592,0.011199,0.0,0.008408,0.012590,fail
5,0.0,0.0,0.0,0.022204,0.0,0.0,0.008766,0.013492,0.0,0.010537,0.011622,pass
6,0.0,0.0,0.0,0.018319,0.0,0.0,0.009586,0.011503,0.0,0.009063,0.013062,pass
7,0.0,0.0,0.0,0.013536,0.0,0.0,0.006049,0.007436,0.0,0.006178,0.007161,pass
8,0.0,0.0,0.0,0.028917,0.0,0.0,0.013413,0.018023,0.0,0.011090,0.013415,pass
9,0.0,0.0,0.0,0.028537,0.0,0.0,0.009699,0.013793,0.0,0.011354,0.012014,pass
10,0.0,0.0,0.0,0.021636,0.0,0.0,0.008258,0.018547,0.0,0.012120,0.013606,pass
11,0.0,0.0,0.0,0.025979,0.0,0.0,0.013089,0.015373,0.0,0.010645,0.016699,pass
12,0.0,0.0,0.0,0.026619,0.0,0.0,0.012956,0.017203,0.0,0.010248,0.008899,pass
13,0.0,0.0,0.0,0.023533,0.0,0.0,0.011975,0.021353,0.0,0.011734,0.016541,pass
14,0.0,0.0,0.0,0.029147,0.0,0.0,0.014480,0.025192,0.0,0.014363,0.013196,pass

[[       nan        nan        nan 1.16784523        nan        nan
  1.3603453  1.21059335        nan 1.13059307 1.16467193]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 7,h 4,h 1,h 0,h 3,cz 10,cz 9,rz 8,cz 6,cz 5,cz 2
sum,0.347816,0.346311,0.343376,0.322408,0.31025,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 4,h 7,h 1,h 0,h 3,cz 10,cz 9,rz 8,cz 6,cz 5,cz 2
sum,0.464086,0.449365,0.440431,0.416283,0.404147,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 7,h 3,h 0,h 4,h 1,cz 10,cz 9,rz 8,cz 6,cz 5,cz 2
sum,0.003086,0.001028,0.000704,0.000644,0.000617,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_rzz_inGap_10_.qasm

100%|██████████| 5/5 [00:00<00:00, 15.40it/s]
100%|██████████| 10/10 [00:00<00:00, 16.68it/s]

,cz 10,rzz 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.0,0.029093,0.0,0.0,0.011999,0.020882,0.0,0.010273,0.011487,fail
1,0.0,0.0,0.0,0.017737,0.0,0.0,0.012794,0.015275,0.0,0.011110,0.012723,fail
2,0.0,0.0,0.0,0.024923,0.0,0.0,0.013122,0.013664,0.0,0.008817,0.014275,fail
3,0.0,0.0,0.0,0.029262,0.0,0.0,0.012649,0.019289,0.0,0.012255,0.016375,fail
4,0.0,0.0,0.0,0.018713,0.0,0.0,0.010048,0.013784,0.0,0.010104,0.015184,fail
5,0.0,0.0,0.0,0.030314,0.0,0.0,0.012837,0.011860,0.0,0.012542,0.011945,pass
6,0.0,0.0,0.0,0.026161,0.0,0.0,0.012637,0.013972,0.0,0.012031,0.012584,pass
7,0.0,0.0,0.0,0.027602,0.0,0.0,0.012943,0.013250,0.0,0.011811,0.017504,pass
8,0.0,0.0,0.0,0.012603,0.0,0.0,0.007125,0.006820,0.0,0.006348,0.007342,pass
9,0.0,0.0,0.0,0.023198,0.0,0.0,0.010956,0.015896,0.0,0.013985,0.011481,pass
10,0.0,0.0,0.0,0.020013,0.0,0.0,0.011056,0.015048,0.0,0.009723,0.012154,pass
11,0.0,0.0,0.0,0.016610,0.0,0.0,0.007448,0.010646,0.0,0.007350,0.012438,pass
12,0.0,0.0,0.0,0.023209,0.0,0.0,0.010291,0.014264,0.0,0.008844,0.013888,pass
13,0.0,0.0,0.0,0.021822,0.0,0.0,0.007516,0.012326,0.0,0.011556,0.009563,pass
14,0.0,0.0,0.0,0.019008,0.0,0.0,0.012366,0.018073,0.0,0.011269,0.013460,pass

[[       nan        nan        nan 1.22203064        nan        nan
  1.08247392 1.25957083        nan 1.16579389 1.16895541]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 3,h 4,h 0,h 7,h 1,cz 10,rzz 9,cz 8,cz 6,cz 5,cz 2
sum,0.385462,0.365608,0.364046,0.351861,0.332614,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 3,h 0,h 4,h 7,h 1,cz 10,rzz 9,cz 8,cz 6,cz 5,cz 2
sum,0.506842,0.470434,0.464549,0.459358,0.429553,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 7,h 3,h 0,h 4,h 1,cz 10,rzz 9,cz 8,cz 6,cz 5,cz 2
sum,0.002746,0.001339,0.000958,0.00072,0.000541,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
9
Now evolving the following mutant:  AddGate_s_inGap_4_.qasm

100%|██████████| 5/5 [00:00<00:00, 14.33it/s]
100%|██████████| 10/10 [00:00<00:00, 15.95it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,sdg 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.027536,0.0,0.0,0.013955,0.013958,0.012363,0.0,0.011555,0.011177,fail
1,0.0,0.0,0.026342,0.0,0.0,0.013767,0.015810,0.013828,0.0,0.011753,0.013244,fail
2,0.0,0.0,0.024476,0.0,0.0,0.012450,0.015514,0.013888,0.0,0.010943,0.011814,fail
3,0.0,0.0,0.023609,0.0,0.0,0.012063,0.014901,0.013193,0.0,0.010549,0.010890,fail
4,0.0,0.0,0.025486,0.0,0.0,0.014057,0.016884,0.014918,0.0,0.011423,0.011299,fail
5,0.0,0.0,0.028232,0.0,0.0,0.012446,0.018046,0.015895,0.0,0.010601,0.012755,pass
6,0.0,0.0,0.017256,0.0,0.0,0.010593,0.012805,0.011398,0.0,0.009888,0.009730,pass
7,0.0,0.0,0.019650,0.0,0.0,0.011391,0.013555,0.011926,0.0,0.010214,0.011191,pass
8,0.0,0.0,0.024860,0.0,0.0,0.011497,0.013518,0.012079,0.0,0.011665,0.015772,pass
9,0.0,0.0,0.031864,0.0,0.0,0.015911,0.017298,0.015218,0.0,0.015066,0.016887,pass
10,0.0,0.0,0.021396,0.0,0.0,0.010105,0.015232,0.013402,0.0,0.009738,0.009321,pass
11,0.0,0.0,0.008511,0.0,0.0,0.007192,0.008317,0.007529,0.0,0.005624,0.008226,pass
12,0.0,0.0,0.019721,0.0,0.0,0.011362,0.016253,0.014380,0.0,0.012744,0.010207,pass
13,0.0,0.0,0.021218,0.0,0.0,0.009776,0.012577,0.011267,0.0,0.009609,0.010829,pass
14,0.0,0.0,0.011994,0.0,0.0,0.007869,0.009418,0.008406,0.0,0.006581,0.009259,pass

[[       nan        nan 1.08026654        nan        nan 1.06023142
  1.09539078 1.09383339        nan 1.04520367 1.1334336 ]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 8,h 5,h 4,sdg 3,h 1,h 0,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.383709,0.380044,0.359981,0.359484,0.35595,0.338491,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 8,h 5,h 4,sdg 3,h 1,h 0,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.487336,0.480778,0.458562,0.457788,0.44896,0.434406,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 4,sdg 3,h 5,h 0,h 1,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.003121,0.001156,0.000908,0.00086,0.000667,0.00062,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
3
Now evolving the following mutant:  AddGate_ccx_inGap_15_.qasm

100%|██████████| 2/2 [00:00<00:00,  3.38it/s]
100%|██████████| 10/10 [00:03<00:00,  2.82it/s]

,ccx 10,cz 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.634773,0.107559,0.263717,0.060729,0.0,0.0,0.013545,0.016692,0.0,0.014016,0.012931,fail
1,0.784165,0.132416,0.209748,0.058326,0.0,0.0,0.015435,0.020014,0.0,0.013209,0.014912,fail
2,0.652168,0.164253,0.329444,0.059236,0.0,0.0,0.013922,0.018980,0.0,0.017110,0.016133,pass
3,0.439143,0.074486,0.128690,0.033548,0.0,0.0,0.008773,0.012689,0.0,0.012978,0.013014,pass
4,0.605781,0.088930,0.171344,0.049671,0.0,0.0,0.010907,0.013842,0.0,0.009643,0.012002,pass
5,0.454735,0.085424,0.151771,0.033296,0.0,0.0,0.008719,0.011199,0.0,0.009510,0.010618,pass
6,0.585225,0.137940,0.263141,0.052431,0.0,0.0,0.012246,0.012503,0.0,0.009820,0.014372,pass
7,0.489236,0.086568,0.163392,0.039566,0.0,0.0,0.009129,0.011101,0.0,0.011235,0.009828,pass
8,0.623216,0.140298,0.243062,0.045881,0.0,0.0,0.012738,0.014947,0.0,0.009425,0.013100,pass
9,0.651331,0.135076,0.246188,0.052139,0.0,0.0,0.012763,0.017260,0.0,0.017057,0.013246,pass
10,0.611297,0.139539,0.286083,0.051952,0.0,0.0,0.012701,0.017700,0.0,0.011811,0.014638,pass
11,0.507879,0.080931,0.096199,0.034222,0.0,0.0,0.008163,0.010694,0.0,0.009039,0.007250,pass

[[1.10528389 1.10358453 1.11398808 1.02018175        nan        nan
  1.06521481 1.09050333        nan 1.02966537 1.07112152]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 7,h 4,h 3,ccx 10,h 1,cz 8,h 0,cz 9,cz 6,cz 5,cz 2
sum,0.208505,0.208425,0.206654,0.201584,0.187947,0.18547,0.183125,0.174728,0.0,0.0,0.0

custom SCORES

,h 4,h 3,h 7,ccx 10,cz 8,h 1,h 0,cz 9,cz 6,cz 5,cz 2
sum,0.263929,0.262994,0.261683,0.257286,0.237123,0.236327,0.232162,0.222935,0.0,0.0,0.0

DSTAR SCORES

,ccx 10,cz 8,cz 9,h 7,h 3,h 4,h 0,h 1,cz 6,cz 5,cz 2
sum,0.264223,0.054952,0.018379,0.005781,0.000629,0.000398,0.000365,0.00035,0.0,0.0,0.0

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_rz_inGap_14_.qasm

100%|██████████| 7/7 [00:00<00:00, 17.00it/s]
100%|██████████| 10/10 [00:00<00:00, 16.86it/s]

,cz 10,cz 9,h 8,rz 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.025201,0.0,0.0,0.0,0.010217,0.013436,0.0,0.010062,0.009746,fail
1,0.0,0.0,0.025871,0.0,0.0,0.0,0.011685,0.016004,0.0,0.012439,0.011385,fail
2,0.0,0.0,0.020522,0.0,0.0,0.0,0.013519,0.017191,0.0,0.013785,0.011602,fail
3,0.0,0.0,0.026619,0.0,0.0,0.0,0.015977,0.017727,0.0,0.013993,0.013504,fail
4,0.0,0.0,0.025731,0.0,0.0,0.0,0.016076,0.018112,0.0,0.010251,0.010960,fail
5,0.0,0.0,0.032205,0.0,0.0,0.0,0.012872,0.016379,0.0,0.011295,0.011263,fail
6,0.0,0.0,0.025875,0.0,0.0,0.0,0.013736,0.016558,0.0,0.015561,0.013694,fail
7,0.0,0.0,0.017913,0.0,0.0,0.0,0.008316,0.016834,0.0,0.006599,0.009384,pass
8,0.0,0.0,0.015353,0.0,0.0,0.0,0.006191,0.008961,0.0,0.005503,0.008583,pass
9,0.0,0.0,0.024200,0.0,0.0,0.0,0.009148,0.013836,0.0,0.008824,0.013335,pass
10,0.0,0.0,0.024140,0.0,0.0,0.0,0.011008,0.014454,0.0,0.008466,0.012306,pass
11,0.0,0.0,0.016685,0.0,0.0,0.0,0.006293,0.009470,0.0,0.006385,0.005165,pass
12,0.0,0.0,0.021143,0.0,0.0,0.0,0.009642,0.013456,0.0,0.008949,0.008828,pass
13,0.0,0.0,0.024608,0.0,0.0,0.0,0.012011,0.014462,0.0,0.012140,0.014280,pass
14,0.0,0.0,0.023175,0.0,0.0,0.0,0.010351,0.014092,0.0,0.006868,0.009034,pass
15,0.0,0.0,0.023675,0.0,0.0,0.0,0.012511,0.009406,0.0,0.007574,0.011499,pass
16,0.0,0.0,0.018824,0.0,0.0,0.0,0.012068,0.010503,0.0,0.011700,0.013555,pass

[[       nan        nan 1.23850787        nan        nan        nan
  1.1961356  1.09857194        nan 1.24649067 1.16683583]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,h 4,h 3,h 8,h 0,cz 10,cz 9,rz 7,cz 6,cz 5,cz 2
sum,0.512852,0.490978,0.479104,0.464656,0.436703,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 1,h 4,h 3,h 8,h 0,cz 10,cz 9,rz 7,cz 6,cz 5,cz 2
sum,0.672668,0.637797,0.610686,0.608525,0.564094,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 3,h 4,h 1,h 0,cz 10,cz 9,rz 7,cz 6,cz 5,cz 2
sum,0.004596,0.001869,0.001247,0.001078,0.00095,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
7
Now evolving the following mutant:  AddGate_t_inGap_2_.qasm

100%|██████████| 4/4 [00:00<00:00, 15.62it/s]
100%|██████████| 10/10 [00:00<00:00, 16.36it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,h 2,tdg 1,h 0,pass/fail
0,0.0,0.0,0.023115,0.0,0.0,0.009170,0.015270,0.0,0.009527,0.004237,0.013129,fail
1,0.0,0.0,0.021720,0.0,0.0,0.008997,0.014504,0.0,0.011203,0.004968,0.011641,fail
2,0.0,0.0,0.023777,0.0,0.0,0.012735,0.016148,0.0,0.007844,0.003471,0.009057,fail
3,0.0,0.0,0.026323,0.0,0.0,0.010074,0.019939,0.0,0.015213,0.006704,0.015155,fail
4,0.0,0.0,0.018610,0.0,0.0,0.009145,0.010521,0.0,0.008853,0.003890,0.011849,pass
5,0.0,0.0,0.031706,0.0,0.0,0.011073,0.015163,0.0,0.013538,0.005968,0.012204,pass
6,0.0,0.0,0.019431,0.0,0.0,0.008859,0.011991,0.0,0.007921,0.003463,0.009580,pass
7,0.0,0.0,0.020329,0.0,0.0,0.011253,0.018497,0.0,0.009304,0.004171,0.015180,pass
8,0.0,0.0,0.021144,0.0,0.0,0.010024,0.014194,0.0,0.007363,0.003243,0.010512,pass
9,0.0,0.0,0.020176,0.0,0.0,0.008992,0.012452,0.0,0.006850,0.003029,0.012238,pass
10,0.0,0.0,0.024397,0.0,0.0,0.011860,0.019541,0.0,0.010797,0.004808,0.009001,pass
11,0.0,0.0,0.024198,0.0,0.0,0.016448,0.017708,0.0,0.010711,0.004811,0.012120,pass
12,0.0,0.0,0.028038,0.0,0.0,0.012698,0.017032,0.0,0.012840,0.005696,0.011897,pass
13,0.0,0.0,0.022087,0.0,0.0,0.009202,0.017382,0.0,0.010116,0.004472,0.016763,pass

[[       nan        nan 1.10909742        nan        nan 1.24318076
  1.21097282        nan 1.38976285 1.38368385 1.23759191]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 2,tdg 1,h 4,h 8,h 0,h 5,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.308185,0.307958,0.2989,0.292064,0.287585,0.272208,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 2,tdg 1,h 4,h 0,h 8,h 5,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.415261,0.414487,0.38939,0.376563,0.373046,0.35681,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 4,h 0,h 2,h 5,tdg 1,cz 10,cz 9,cz 7,cz 6,cz 3
sum,0.002131,0.001044,0.000582,0.000468,0.000409,0.000093,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_ry_inGap_10_.qasm

100%|██████████| 6/6 [00:00<00:00, 15.59it/s]
100%|██████████| 10/10 [00:00<00:00, 17.14it/s]

,cz 10,ry 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.188701,0.0,0.021229,0.0,0.0,0.014497,0.019596,0.0,0.011436,0.013766,fail
1,0.0,0.270515,0.0,0.030433,0.0,0.0,0.012527,0.019292,0.0,0.016008,0.015473,fail
2,0.0,0.171704,0.0,0.019317,0.0,0.0,0.008095,0.015119,0.0,0.011611,0.013296,fail
3,0.0,0.235867,0.0,0.026535,0.0,0.0,0.009506,0.020042,0.0,0.010770,0.008527,fail
4,0.0,0.272490,0.0,0.030655,0.0,0.0,0.015088,0.016284,0.0,0.014011,0.012812,fail
5,0.0,0.210915,0.0,0.023728,0.0,0.0,0.011433,0.014951,0.0,0.011691,0.014771,fail
6,0.0,0.258667,0.0,0.029100,0.0,0.0,0.011600,0.015333,0.0,0.010078,0.013302,pass
7,0.0,0.164675,0.0,0.018526,0.0,0.0,0.009050,0.014875,0.0,0.008118,0.011097,pass
8,0.0,0.199311,0.0,0.022423,0.0,0.0,0.012443,0.012578,0.0,0.010701,0.015333,pass
9,0.0,0.152234,0.0,0.017126,0.0,0.0,0.008208,0.012798,0.0,0.008019,0.008842,pass
10,0.0,0.154240,0.0,0.017352,0.0,0.0,0.007597,0.011609,0.0,0.010336,0.009418,pass
11,0.0,0.110288,0.0,0.012407,0.0,0.0,0.009257,0.011395,0.0,0.006857,0.007861,pass
12,0.0,0.126847,0.0,0.014270,0.0,0.0,0.010176,0.015316,0.0,0.006747,0.011439,pass
13,0.0,0.203978,0.0,0.022948,0.0,0.0,0.012529,0.009156,0.0,0.012905,0.010828,pass
14,0.0,0.173490,0.0,0.019518,0.0,0.0,0.011507,0.016554,0.0,0.011715,0.009123,pass
15,0.0,0.232550,0.0,0.026162,0.0,0.0,0.009967,0.016153,0.0,0.011387,0.017638,pass

[[       nan 1.21089299        nan 1.21089299        nan        nan
  1.27244671 1.14215143        nan 1.27167236 1.18049973]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,h 3,ry 9,h 7,h 4,h 0,cz 10,cz 8,cz 6,cz 5,cz 2
sum,0.438123,0.436772,0.431858,0.431858,0.410111,0.406379,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 1,ry 9,h 7,h 3,h 4,h 0,cz 10,cz 8,cz 6,cz 5,cz 2
sum,0.577411,0.562591,0.562591,0.561487,0.540573,0.526312,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,ry 9,h 7,h 3,h 0,h 1,h 4,cz 10,cz 8,cz 6,cz 5,cz 2
sum,0.234433,0.003721,0.001807,0.001011,0.000936,0.000829,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
9
Now evolving the following mutant:  AddGate_ccx_inGap_10_.qasm

100%|██████████| 2/2 [00:00<00:00,  2.79it/s]
100%|██████████| 10/10 [00:03<00:00,  3.20it/s]

,cz 10,ccx 9,cz 8,h 7,cz 6,cz 5,h 4,h 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.351890,0.105318,0.032615,0.0,0.0,0.009202,0.013030,0.0,0.010166,0.013642,fail
1,0.0,0.385067,0.140763,0.039372,0.0,0.0,0.009629,0.012298,0.0,0.009582,0.010952,fail
2,0.0,0.241367,0.061337,0.021334,0.0,0.0,0.006579,0.008122,0.0,0.008414,0.004861,pass
3,0.0,0.396546,0.169435,0.040762,0.0,0.0,0.010734,0.012039,0.0,0.011991,0.008783,pass
4,0.0,0.330630,0.106108,0.035455,0.0,0.0,0.009270,0.012192,0.0,0.009712,0.011992,pass
5,0.0,0.404596,0.083522,0.037932,0.0,0.0,0.010038,0.012704,0.0,0.010495,0.010100,pass
6,0.0,0.303531,0.114909,0.035590,0.0,0.0,0.008760,0.010978,0.0,0.011257,0.009706,pass
7,0.0,0.314800,0.106168,0.032749,0.0,0.0,0.008847,0.011537,0.0,0.010110,0.010524,pass
8,0.0,0.288731,0.120720,0.028259,0.0,0.0,0.007644,0.010307,0.0,0.004922,0.007688,pass
9,0.0,0.338193,0.099157,0.030902,0.0,0.0,0.009495,0.011246,0.0,0.009430,0.009777,pass
10,0.0,0.340324,0.111540,0.033533,0.0,0.0,0.009007,0.011463,0.0,0.008354,0.008675,pass
11,0.0,0.424166,0.181331,0.038339,0.0,0.0,0.011126,0.013800,0.0,0.012530,0.015019,pass

[[       nan 1.0450185  1.14403688 1.0938678         nan        nan
  1.02264497 1.02889905        nan 1.02957006 1.10936984]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 0,h 3,ccx 9,h 7,cz 8,h 4,h 1,cz 10,cz 6,cz 5,cz 2
sum,0.202056,0.181286,0.17888,0.176942,0.175734,0.170677,0.168846,0.0,0.0,0.0,0.0

custom SCORES

,h 0,h 3,cz 8,ccx 9,h 7,h 4,h 1,cz 10,cz 6,cz 5,cz 2
sum,0.258095,0.227918,0.225995,0.225613,0.22533,0.214313,0.212306,0.0,0.0,0.0,0.0

DSTAR SCORES

,ccx 9,cz 8,h 7,h 3,h 0,h 1,h 4,cz 10,cz 6,cz 5,cz 2
sum,0.100895,0.019198,0.002219,0.000303,0.000288,0.000186,0.00017,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
9
Now evolving the following mutant:  AddGate_p_inGap_3_.qasm

100%|██████████| 7/7 [00:00<00:00, 15.85it/s]
100%|██████████| 10/10 [00:00<00:00, 16.26it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,p 2,h 1,h 0,pass/fail
0,0.0,0.0,0.019260,0.0,0.0,0.014020,0.014337,0.0,0.0,0.011022,0.009584,fail
1,0.0,0.0,0.026163,0.0,0.0,0.012697,0.019702,0.0,0.0,0.013073,0.019281,fail
2,0.0,0.0,0.023754,0.0,0.0,0.012755,0.016879,0.0,0.0,0.013654,0.014498,fail
3,0.0,0.0,0.025512,0.0,0.0,0.010713,0.016854,0.0,0.0,0.011068,0.014773,fail
4,0.0,0.0,0.021541,0.0,0.0,0.014904,0.014993,0.0,0.0,0.009329,0.020254,fail
5,0.0,0.0,0.026688,0.0,0.0,0.013703,0.023346,0.0,0.0,0.011035,0.012951,fail
6,0.0,0.0,0.018610,0.0,0.0,0.010824,0.016663,0.0,0.0,0.009241,0.013449,fail
7,0.0,0.0,0.006153,0.0,0.0,0.004540,0.008900,0.0,0.0,0.004326,0.006594,pass
8,0.0,0.0,0.015242,0.0,0.0,0.008742,0.013550,0.0,0.0,0.010253,0.014283,pass
9,0.0,0.0,0.034249,0.0,0.0,0.018162,0.017359,0.0,0.0,0.014078,0.012254,pass
10,0.0,0.0,0.021124,0.0,0.0,0.009431,0.017054,0.0,0.0,0.008162,0.009512,pass
11,0.0,0.0,0.020088,0.0,0.0,0.010850,0.011552,0.0,0.0,0.010590,0.011116,pass
12,0.0,0.0,0.024547,0.0,0.0,0.014606,0.019324,0.0,0.0,0.009864,0.014158,pass
13,0.0,0.0,0.023532,0.0,0.0,0.011280,0.012742,0.0,0.0,0.010750,0.012224,pass
14,0.0,0.0,0.017004,0.0,0.0,0.009369,0.008649,0.0,0.0,0.006068,0.010230,pass
15,0.0,0.0,0.017589,0.0,0.0,0.012757,0.014946,0.0,0.0,0.011348,0.010556,pass
16,0.0,0.0,0.032954,0.0,0.0,0.014248,0.018702,0.0,0.0,0.015590,0.018316,pass

[[       nan        nan 1.15656339        nan        nan 1.16416218
  1.33108918        nan        nan 1.21872547 1.35297923]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 0,h 4,h 5,h 1,h 8,cz 10,cz 9,cz 7,cz 6,cz 3,p 2
sum,0.467747,0.462332,0.440159,0.437014,0.431883,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 0,h 4,h 1,h 5,h 8,cz 10,cz 9,cz 7,cz 6,cz 3,p 2
sum,0.62596,0.616183,0.570164,0.568263,0.556758,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 4,h 0,h 5,h 1,cz 10,cz 9,cz 7,cz 6,cz 3,p 2
sum,0.003618,0.00211,0.001542,0.001129,0.000866,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_id_inGap_1_.qasm

100%|██████████| 5/5 [00:00<00:00, 15.37it/s]
100%|██████████| 10/10 [00:00<00:00, 16.54it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,cz 3,h 2,h 1,id 0,pass/fail
0,0.0,0.0,0.018223,0.0,0.0,0.008991,0.014334,0.0,0.010865,0.012574,0.0,fail
1,0.0,0.0,0.028969,0.0,0.0,0.014623,0.018573,0.0,0.011656,0.015087,0.0,fail
2,0.0,0.0,0.028394,0.0,0.0,0.012987,0.016092,0.0,0.013381,0.012809,0.0,fail
3,0.0,0.0,0.024496,0.0,0.0,0.009836,0.013727,0.0,0.012721,0.014883,0.0,fail
4,0.0,0.0,0.028020,0.0,0.0,0.013514,0.018140,0.0,0.008812,0.016371,0.0,fail
5,0.0,0.0,0.013297,0.0,0.0,0.008443,0.012273,0.0,0.006361,0.012663,0.0,pass
6,0.0,0.0,0.024282,0.0,0.0,0.011801,0.019974,0.0,0.013593,0.014108,0.0,pass
7,0.0,0.0,0.018232,0.0,0.0,0.007903,0.011766,0.0,0.006655,0.012127,0.0,pass
8,0.0,0.0,0.021918,0.0,0.0,0.013921,0.016711,0.0,0.010836,0.013788,0.0,pass
9,0.0,0.0,0.028169,0.0,0.0,0.010118,0.011667,0.0,0.006096,0.011427,0.0,pass
10,0.0,0.0,0.026926,0.0,0.0,0.008946,0.012723,0.0,0.009825,0.010209,0.0,pass
11,0.0,0.0,0.014373,0.0,0.0,0.006989,0.013273,0.0,0.010309,0.008469,0.0,pass
12,0.0,0.0,0.021042,0.0,0.0,0.008557,0.013497,0.0,0.009302,0.008573,0.0,pass
13,0.0,0.0,0.024001,0.0,0.0,0.009236,0.017772,0.0,0.012589,0.009876,0.0,pass
14,0.0,0.0,0.022261,0.0,0.0,0.010602,0.013128,0.0,0.009147,0.008950,0.0,pass

[[       nan        nan 1.1307178         nan        nan 1.21954688
  1.14837674        nan 1.16493181 1.1412512         nan]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 1,h 5,h 2,h 8,h 4,cz 10,cz 9,cz 7,cz 6,cz 3,id 0
sum,0.394271,0.383158,0.377492,0.373908,0.361574,0.0,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 1,h 5,h 2,h 8,h 4,cz 10,cz 9,cz 7,cz 6,cz 3,id 0
sum,0.506762,0.499977,0.487431,0.479604,0.46538,0.0,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,h 8,h 4,h 1,h 5,h 2,cz 10,cz 9,cz 7,cz 6,cz 3,id 0
sum,0.003147,0.001272,0.001007,0.000705,0.000647,0.0,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_ccx_inGap_4_.qasm

100%|██████████| 3/3 [00:00<00:00,  8.82it/s]
100%|██████████| 10/10 [00:01<00:00,  9.11it/s]

,cz 10,cz 9,h 8,cz 7,cz 6,h 5,h 4,ccx 3,cz 2,h 1,h 0,pass/fail
0,0.0,0.0,0.027224,0.0,0.0,0.013764,0.016570,0.061041,0.0,0.005468,0.010590,fail
1,0.0,0.0,0.024979,0.0,0.0,0.014664,0.016319,0.052073,0.0,0.008647,0.011291,fail
2,0.0,0.0,0.025034,0.0,0.0,0.010516,0.018886,0.050253,0.0,0.009784,0.008884,fail
3,0.0,0.0,0.027386,0.0,0.0,0.009836,0.017988,0.058809,0.0,0.005094,0.008274,pass
4,0.0,0.0,0.027771,0.0,0.0,0.013732,0.015184,0.062882,0.0,0.010334,0.009874,pass
5,0.0,0.0,0.017217,0.0,0.0,0.010693,0.012578,0.060062,0.0,0.009548,0.011073,pass
6,0.0,0.0,0.007181,0.0,0.0,0.004185,0.005917,0.028538,0.0,0.003392,0.003153,pass
7,0.0,0.0,0.032096,0.0,0.0,0.012564,0.021037,0.055542,0.0,0.008972,0.009469,pass
8,0.0,0.0,0.017959,0.0,0.0,0.012118,0.009594,0.056135,0.0,0.007422,0.007442,pass
9,0.0,0.0,0.020735,0.0,0.0,0.016010,0.010390,0.054220,0.0,0.009626,0.004370,pass
10,0.0,0.0,0.021218,0.0,0.0,0.012780,0.014008,0.049846,0.0,0.007212,0.009931,pass
11,0.0,0.0,0.018021,0.0,0.0,0.007465,0.009287,0.050047,0.0,0.006251,0.005884,pass
12,0.0,0.0,0.017679,0.0,0.0,0.009770,0.010533,0.055058,0.0,0.008864,0.007509,pass

[[       nan        nan 1.05742702        nan        nan 1.12962987
  1.09429132 1.12092771        nan 1.22814762 1.10100867]]
BARINEL SCORES

d:\GitHub\heisenberg-SBFL-experiment\heisenbergUtilities.py:326: RuntimeWarning: invalid value encountered in divide
  dstar_boost = max_fail.values/avg_fail.values

,h 4,h 0,h 8,h 5,h 1,ccx 3,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.290395,0.285537,0.271482,0.262962,0.237528,0.235228,0.0,0.0,0.0,0.0,0.0

custom SCORES

,h 4,h 0,h 8,h 5,h 1,ccx 3,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.369839,0.364131,0.34325,0.337225,0.310458,0.301146,0.0,0.0,0.0,0.0,0.0

DSTAR SCORES

,ccx 3,h 8,h 4,h 5,h 0,h 1,cz 10,cz 9,cz 7,cz 6,cz 2
sum,0.007558,0.00186,0.000857,0.000488,0.000308,0.000186,0.0,0.0,0.0,0.0,0.0

ERROR GATE LOCATION:
3

,Program,path_to_mutant,best_exam_score,worst_exam_score,avg_exam_score
0,AddGate_ccx_inGap_4_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_graphst...,0.545455,0.545455,0.545455
1,AddGate_id_inGap_1_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_graphst...,0.545455,1.0,0.772727
2,AddGate_p_inGap_3_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_graphst...,0.545455,1.0,0.772727
3,AddGate_ccx_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_graphst...,0.272727,0.272727,0.272727
4,AddGate_ry_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_graphst...,0.272727,0.363636,0.318182
...,...,...,...,...,...
187,AddGate_y_inGap_9_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_graphst...,0.272727,0.363636,0.318182
188,AddGate_ry_inGap_15_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_graphst...,0.181818,0.181818,0.181818
189,AddGate_sx_inGap_1_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_graphst...,0.545455,1.0,0.772727
190,AddGate_p_inGap_7_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_graphst...,0.545455,1.0,0.772727
191,AddGate_ccx_inGap_11_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_graphst...,0.272727,0.272727,0.272727

,Program,path_to_mutant,best_exam_score,worst_exam_score,avg_exam_score
0,AddGate_ccx_inGap_4_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_graphst...,0.545455,0.545455,0.545455
1,AddGate_id_inGap_1_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_graphst...,0.545455,1.0,0.772727
2,AddGate_p_inGap_3_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_graphst...,0.545455,1.0,0.772727
3,AddGate_ccx_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_graphst...,0.363636,0.363636,0.363636
4,AddGate_ry_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_graphst...,0.181818,0.272727,0.227273
...,...,...,...,...,...
187,AddGate_y_inGap_9_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_graphst...,0.363636,0.363636,0.363636
188,AddGate_ry_inGap_15_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_graphst...,0.272727,0.272727,0.272727
189,AddGate_sx_inGap_1_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_graphst...,0.545455,1.0,0.772727
190,AddGate_p_inGap_7_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_graphst...,0.545455,1.0,0.772727
191,AddGate_ccx_inGap_11_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_graphst...,0.363636,0.363636,0.363636