<h1 style="text-align: center;">HEISENBERG-BASED FAULT LOCALIZATION (HBFL)</h1>

<h2 style="text-align: center;">Download Initial Dependencies</h2>

In [22]:
import numpy as np
import pandas as pd
import json
import math
from tqdm import tqdm
from qiskit.quantum_info import SparsePauliOp, Operator, Pauli, Clifford
import qiskit.qasm2 as q2
from qiskit import QuantumCircuit
from IPython.display import display

from heisenbergUtilities import *

In [23]:
# from qiskit_aer import AerSimulator
# simulator = AerSimulator()

# print(simulator.available_devices())

<h3>Download MQT Benchmark circuits.</h3>

We'll run this experiment on 11 different quantum circuits, including DJ, GHZ, GraphState, Grover No-Ancilla, QAOA, QFT, QGAN, QPE Exact, QPE Inexact, RealAmpRandom, and VQE.

<h3>Generate mutants.</h3>

We'll start with mutants that add an unnecessary gate, then add mutants that replace a certain gate later. Missing code in SBFL is still a more recent topic even in classical programs.

The mutants were downloaded from QMutBench, choosing specifically mutants that added a gate at any location with 0-10% survival scores

<h2 style="text-align: center;">CONTROL PANEL</h2>

In [ ]:
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
#-------------------------------------------------------------------------GENERAL PARAMETERS---------------------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
ALG_NAME = "realamprandom"
ORIGINAL_QASM = f"{ALG_NAME}_5_qubits.qasm"                                                 #| The original algorithm QASM circuit file name.                           
ORIGINAL_QASM_FOLDER = "SBFL_circuits/MQTBench/"                                            #| The folder containing the original QASM circuit file.                    
QASM_MUTANT_FOLDER = f"SBFL_circuits/QMutBenchMutants/Mutants_{ALG_NAME}_5_qubits/"         #| The folder containing all mutants related to the original QASM circuit.  
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
#-------------------------------------------------------------------------SB-QOPS PARAMETERS---------------------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
RUNS = 10                                                                                   #| Number of times SB-QOPS will run to find a failing or passing test case.            
SHOTS = 20000                                                                               #| Number of shots for SB-QOPS to use to create the compact program specification.     
EPOCH = 80                                                                                  #| Number of epochs SB-QOPS will run to navigate the search space of test cases.       
SBQOPS_TOL = 0.1                                                                            #| Tolerance value SB-QOPS uses to determine if a test case is failing or passing.     
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
#---------------------------------------------------------------------HEISENBERG SBFL PARAMETERS-----------------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
LAMBDA_WEIGHT = 1                                                                           #| The amount to weigh the "weight difference" in the heuristic            #
LAMBDA_COMP = 1                                                                             #| The amount to weigh the "composition difference" in the heuristic       #
LAMBDA_SUPPORT = 1                                                                          #| The amount to weigh the "support overlap" in the heuristic              #
LAMBDA_DIAMETER = 1                                                                         #| The amount to weigh the "diameter difference" in the heuristic          #
LAMBDA_PHASE = 1                                                                            #| The amount to weigh the "phase" in the heuristic                        #
CUSTOM_WEIGHT = 0.25                                                                        #| The amount of weight the "dstar boost" has in the custom heuristic (WIP)#
ATOL = 1e-4                                                                                 #| The tolerance value used to prune negligible magnitudes during Pauli propagation.   
MAX_TERMS = 100                                                                             #| The maximum number of terms to keep during Pauli propagation. If None, use all.     
SEARCH_STEP = 3                                                                             #| The search step size used during Pauli propagation. If None, pauli-prop uses 4.     
VERBOSE = 1                                                                                 #| A boolean value to determine if the program should print out detailed information.  
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#

Generate the linked list of all gates found in a given circuit

In [25]:
"""
LinkedListNode: A class that holds information related to a gate in a quantum circuit. 

PROPERTIES:
    - value (String): The name of the quantum gate
    - depth (int): The depth of the gate in the circuit
    - count (Int): The probability that the gate will meaningfully change the Pauli string.
    - next (LinkedListNode): The next gate in the circuit

"""

class LinkedListNode:
    def __init__(self, name="Initial", depth=0, count=0,  next=None):
        self.value = name
        self.depth = depth
        self.next = next
        self.count = count

class LinkedList:
    def __init__(self):
        self.head = None

    def append(self, name, depth):
        new_node = LinkedListNode(name, depth)
        if not self.head:
            self.head = new_node
            return
        last_node = self.head
        while last_node.next:
            last_node = last_node.next
        last_node.next = new_node

    def mark(self, depth):
        current_node = self.head
        while current_node:
            if current_node.depth == depth:
                current_node.count += 1
                return
            current_node = current_node.next

    def reset(self):
        current_node = self.head
        while current_node:
            current_node.count = 0
            current_node = current_node.next

<h3>Load correct circuit</h3>
Here we want to load the correct version of the circuit from MQT. We use this both to generate a PS_compact from/for SB-QOPS and to check results from SBFL.

In [26]:
correct_circuit = load_program(ORIGINAL_QASM, ORIGINAL_QASM_FOLDER).copy()
correct_list = LinkedList()
correct_list = construct_list(correct_list, correct_circuit, inverse=False)

<h2 style="text-align: center;"> SB-QOPS </h2>

This is where we will use SB-QOPS on a provided circuit and its mutants

For a single mutant, it took about 2 minutes to generate a 20 test suite (10 fail, 10 pass) on an RTX 4090 SUPER. It can only be run on a Linux environment since the AER Simulator does not support Windows

Expect this cell to take up to a few hours, BUT this cell should only need to be run once per algorithm with mutants under test. After it saves to the csv file at the end, this cell can be commented out as to not accidentally run it again. 

In the future if we want to test this methodology on higher qubit circuits or other algorithms, we'll likely either want to reduce the number of tests in the suite or the number of mutants we're analyzing

In [27]:
# import QOPS as qops
# from QOPS_test import get_compact_program_specification_Z
# from pathlib import Path

# ga_result = pd.DataFrame(columns=['Program',"path_to_mutant",'catch_avg','avg_fitness','failing_testcases', 'passing_testcases'])
# program_history = {}

# #program_specification = The compact program specification. SB-QOPS needs this to generate failing test cases.
# # In a public-use environment, this would be provided by the user.
# program_specification = get_compact_program_specification_Z(correct_circuit, shots=SHOTS)

# #mutants = A python list of qiskit QuantumCircuit variables with a mutation in them
# mutants = []
# mutants_names = []
# root = Path(QASM_MUTANT_FOLDER)
# for qasm_mutant in root.rglob("*.qasm"):
#     mutants.append(load_program(qasm_mutant.name, QASM_MUTANT_FOLDER))
#     mutants_names.append(qasm_mutant.name)

# for mutant_index,mutant in enumerate(mutants):
#     tester = qops.Circuit_Tester(CUT=mutant)
#     tester.set_applicable_families_Z(program_specification)
#     mutants_per_run = []
#     fitness_per_run = []
#     failing_testcases_per_run = []
#     history_per_run = []

#     print("NOW RUNNING TO FIND FAILING TESTS")
#     #For a predefined number of attempts, try to find a set of failing test cases (output is above predefined tolerance)
#     for runs in range(RUNS):
#         killed = 0
#         pauli = {}
#         fitness = 0
#         for i in range(len(tester.applicable_families)):
#             best_function,testcase, history = tester.run_mealoneplusone(i, EPOCH)
#             if best_function > SBQOPS_TOL:
#                 killed = 1
#                 pauli = testcase
#                 fitness = best_function
#                 break
#         mutants_per_run.append(killed)
#         failing_testcases_per_run.append(pauli)
#         fitness_per_run.append(fitness)
#         history_per_run.append(history)

#     avg_score = np.mean(mutants_per_run)
#     avg_fitness = np.mean(fitness_per_run)

#     #Here is our new, modified algorithm from the SB-QOPS method that attempts to find passing test cases as well. We'll need them for SBFL
#     passing_testcases_per_run = []

#     print("NOW RUNNING TO FIND PASSING TESTS")
#     for runs in range(RUNS):
#         pauli = {}
#         fitness = 0
#         for i in range(len(tester.applicable_families)):
#             best_function, testcase, history = tester.run_reverse_mealoneplusone(i,EPOCH)
#             if best_function < SBQOPS_TOL:
#                 pauli = testcase
#                 break
#         passing_testcases_per_run.append(pauli)

#     #Replace static program file with "program_name" when ready to test fully
#     """
#     ga_result: A pandas dataframe with the following columns
#         Program: Name of the mutant quantum circuit file
#         Path_To_Mutant: Path to the mutant file
#         Catch_Avg: The average number of times the mutant was identified by SB-QOPS
#         Avg_Fitness: The average fitness of the search algorithm used. Higher usually indicates higher Catch_Avg
#         Failing_Testcases: A list of dicts indicating the set of Pauli strings and the weights that should be applied to generate a failing test case
#         Passing_Testcases: A list of dicts indicating the set of Pauli strings and the weights that should be applied to generate a passing test case
#     """
#     ga_result = pd.concat([pd.DataFrame([[mutants_names[mutant_index],QASM_MUTANT_FOLDER,avg_score,avg_fitness,json.dumps(failing_testcases_per_run), json.dumps(passing_testcases_per_run)]],columns=ga_result.columns),ga_result],ignore_index=True)
#     ga_result.to_csv(f'realamprandom_ga_result', index=False)

ga_result is a slightly altered pandas Dataframe with similar structure found in SB-QOPS. The differences are changing the column "Program" to be the name of the mutant file instead of the original quantum circuit, changing "Mutant" to be the path to the mutant file instead of being an arbitrary index value, and adding a passing_testcases column that returns Pauli strings and coefficients that generate passing tests.

Now we want to run SBFL using Heisenberg evolution trees on each circuit placed in ga_result

Evolution analysis can vary widely in runtime. Some of the simplest circuits take seconds to analyze and only took upwards of 3-4 minutes to get results on the whole dataset (GHZ was the fastest taking 3 minutes to run). Other, more complex algorithms can take upwards of 6-10 minutes PER MUTANT (RealAmpRandom took longest so far with 14 hours).

The runtime of this code segment is directly tied to the depth of the circuit being analyzed and the number of 2-branching gates such as rotation or phase gates that exist in the circuit.

This is something to note in the final paper. Regardless of accuracy this methodology takes a long time to run. If results are promising, then we'll want to look into the tradeoffs between EXAM and hyperparameters to speed this up. Primarily the atol, max_terms, and search_step parameters in the evolve_pauli_exact method in HeisenbergUtilities.py

<h2 style="text-align: center;">HEISENBERG EVOLUTIONS (PAULI PROPAGATION)</h2>

In [ ]:
from heisenbergTree import *

LAMBDAS = [LAMBDA_WEIGHT, LAMBDA_COMP, LAMBDA_SUPPORT, LAMBDA_DIAMETER, LAMBDA_PHASE]
ga_result = pd.read_csv(f'{ALG_NAME}_ga_result.csv')
custom_sbfl_result = pd.DataFrame(columns=['Program','path_to_mutant','best_exam_score', 'worst_exam_score', 'avg_exam_score'])
barinel_sbfl_result = pd.DataFrame(columns=['Program','path_to_mutant','best_exam_score', 'worst_exam_score', 'avg_exam_score'])
dstar_sbfl_result = pd.DataFrame(columns=['Program','path_to_mutant','best_exam_score', 'worst_exam_score', 'avg_exam_score'])
mutant_num = 0

#For each mutant of a circuit, run the SBFL implementation
for mutant, path in zip(ga_result.loc[:,"Program"], ga_result.loc[:,"path_to_mutant"]):
    print("Now evolving the following mutant: ", mutant)

    #Extract the raw test cases found for each mutant
    raw_failing_testcases = format_test_case(ga_result, mutant, mutant_num, "failing_testcases")
    raw_passing_testcases = format_test_case(ga_result, mutant, mutant_num, "passing_testcases")

    circuit_inverse = load_program(mutant,path).copy().inverse()  # Invert to track backward evolution of the operator
    forward_mutant = load_program(mutant, path).copy()

    #Create the linked list of operations in the inverse circuit
    operation_list = LinkedList()
    operation_list = construct_list(operation_list, circuit_inverse, True)

    forward_list = LinkedList()
    forward_list = construct_list(forward_list, forward_mutant, False)

    #Create list of nodes in linked list. Somewhere down the road remove the linked list implementation. It's unnecessary and giving me a headache
    node_list = []
    node = operation_list.head
    while node:
        node_list.append(node)
        node = node.next

    #Perform Pauli propagation (Heisenberg evolution) for all test cases. Returns a dataframe with all counts for all operations
    global_frame_fail = heisenberg_evolve(circuit_inverse, 
                                          operation_list, 
                                          raw_failing_testcases, 
                                          "fail", 
                                          LAMBDAS,
                                          atol = ATOL, 
                                          max_terms = MAX_TERMS, 
                                          search_step = SEARCH_STEP)
    
    global_frame_pass = heisenberg_evolve(circuit_inverse, 
                                          operation_list, 
                                          raw_passing_testcases, 
                                          "pass", 
                                          LAMBDAS,
                                          atol = ATOL, 
                                          max_terms = MAX_TERMS, 
                                          search_step = SEARCH_STEP)

    global_frame = pd.concat([global_frame_fail, global_frame_pass], ignore_index=True)

    global_frame = global_frame.drop(["Initial"],axis=1)
    if VERBOSE:
        display(global_frame)

    custom_scores = custom_sbfl(global_frame, CUSTOM_WEIGHT)
    barinel_scores = barinel(global_frame)
    dstar_scores = dstar(global_frame)

    if VERBOSE:
        print("BARINEL SCORES")
        display(barinel_scores)
        print("custom SCORES")
        display(custom_scores)
        print("DSTAR SCORES")
        display(dstar_scores)
    
    # Here is where analysis of the methodology begins. 
    # We first extract the position of the erroneous gate by comparing it to the original MQT gate
    # NOTE: This method is intended for single-added gates for now. Other types of mutants will require other methods later
    error_gate_location = find_erroneous_gate(forward_mutant, correct_circuit)

    if VERBOSE:
        print("ERROR GATE LOCATION:")
        print(error_gate_location)

    #Calculate best, worst, and average EXAM for Barinel, custom, and DStar
    barinel_best_exam, barinel_worst_exam, barinel_average_exam = calc_exams(barinel_scores, error_gate_location, circuit_inverse)
    custom_best_exam, custom_worst_exam, custom_average_exam = calc_exams(custom_scores, error_gate_location, circuit_inverse)
    dstar_best_exam, dstar_worst_exam, dstar_average_exam = calc_exams(dstar_scores, error_gate_location, circuit_inverse)

    # Here we store the results from the HBFL analysis for both barinel and custom into a csv file for later analysis.
    barinel_sbfl_result = pd.concat([pd.DataFrame([[mutant,QASM_MUTANT_FOLDER,barinel_best_exam, barinel_worst_exam, barinel_average_exam]],columns=barinel_sbfl_result.columns),barinel_sbfl_result],ignore_index=True)
    barinel_sbfl_result.to_csv(f'{ALG_NAME}_barinel_sbfl_result.csv', index=False)

    custom_sbfl_result = pd.concat([pd.DataFrame([[mutant,QASM_MUTANT_FOLDER,custom_best_exam, custom_worst_exam, custom_average_exam]],columns=custom_sbfl_result.columns),custom_sbfl_result],ignore_index=True)
    custom_sbfl_result.to_csv(f'{ALG_NAME}_custom_sbfl_result.csv', index=False)

    dstar_sbfl_result = pd.concat([pd.DataFrame([[mutant,QASM_MUTANT_FOLDER,dstar_best_exam, dstar_worst_exam, dstar_average_exam]],columns=dstar_sbfl_result.columns),dstar_sbfl_result],ignore_index=True)
    dstar_sbfl_result.to_csv(f'{ALG_NAME}_dstar_sbfl_result.csv', index=False)

    mutant_num += 1

if VERBOSE:
    display(barinel_sbfl_result)
    display(custom_sbfl_result)

Now evolving the following mutant:  AddGate_y_inGap_23_.qasm

100%|██████████| 10/10 [04:40<00:00, 28.04s/it]
100%|██████████| 10/10 [04:13<00:00, 25.32s/it]

,ry 50,ry 49,cx 48,ry 47,cx 46,ry 45,cx 44,ry 43,cx 42,ry 41,...,cx 8,cx 7,ry 6,cx 5,cx 4,ry 3,cx 2,ry 1,ry 0,pass/fail
0,0.040046,0.060627,0.420566,0.001399,0.218567,0.038191,0.432583,0.025413,0.523796,0.080516,...,0.094984,0.111335,0.027139,0.082006,0.095371,0.001926,0.101612,0.020682,0.029594,fail
1,0.035517,0.064796,0.422031,0.001238,0.248344,0.048772,0.419573,0.015335,0.498364,0.074936,...,0.060920,0.064028,0.014138,0.052703,0.053210,0.001003,0.052266,0.009650,0.014398,fail
2,0.035658,0.077400,0.479073,0.001681,0.241146,0.045745,0.423289,0.025509,0.527322,0.088054,...,0.070342,0.079529,0.019359,0.061889,0.070535,0.001355,0.069675,0.013731,0.020752,fail
3,0.033624,0.084255,0.489182,0.001380,0.185995,0.058632,0.334929,0.024204,0.385035,0.077549,...,0.076204,0.083788,0.019914,0.065909,0.071035,0.001410,0.074178,0.014653,0.020882,fail
4,0.036369,0.065003,0.386233,0.001303,0.212496,0.042108,0.371681,0.034535,0.444656,0.075320,...,0.089976,0.103560,0.024381,0.078136,0.090586,0.001789,0.091440,0.018401,0.028054,fail
5,0.040434,0.065673,0.422706,0.001556,0.208896,0.040093,0.425827,0.029284,0.507840,0.085026,...,0.099130,0.115660,0.028332,0.087266,0.099928,0.002004,0.106132,0.021225,0.030585,fail
6,0.038776,0.070684,0.448831,0.001357,0.189106,0.051699,0.374689,0.035774,0.439129,0.082156,...,0.108740,0.126465,0.029017,0.093942,0.105108,0.002086,0.115254,0.023179,0.033665,fail
7,0.031398,0.069880,0.435966,0.000847,0.241824,0.045211,0.392198,0.027037,0.413748,0.082234,...,0.059216,0.064121,0.014694,0.052367,0.056354,0.001053,0.057414,0.010582,0.017030,fail
8,0.038289,0.080585,0.482930,0.001145,0.224087,0.049471,0.377842,0.025644,0.430048,0.077044,...,0.085914,0.095219,0.021396,0.074902,0.079858,0.001534,0.085195,0.016180,0.024136,fail
9,0.041226,0.073251,0.440880,0.001129,0.237298,0.043542,0.384499,0.030060,0.467135,0.070601,...,0.088827,0.098776,0.023494,0.078726,0.086511,0.001662,0.087868,0.016836,0.025886,fail
10,0.017192,0.028231,0.215919,0.000584,0.132897,0.017400,0.221969,0.011114,0.253822,0.044319,...,0.039748,0.046548,0.010125,0.032170,0.039032,0.000734,0.040475,0.008350,0.011897,pass
11,0.014163,0.036600,0.228482,0.000748,0.071683,0.019304,0.160463,0.015372,0.178943,0.042713,...,0.041859,0.050038,0.011781,0.036282,0.042937,0.000825,0.046603,0.009374,0.012848,pass
12,0.028228,0.063568,0.347680,0.000815,0.149961,0.034436,0.250018,0.027257,0.312666,0.060961,...,0.067296,0.079005,0.019626,0.059580,0.070252,0.001402,0.075325,0.015006,0.022052,pass
13,0.030596,0.067524,0.424899,0.000879,0.206774,0.025297,0.353400,0.026884,0.403372,0.072734,...,0.064699,0.076374,0.017156,0.058575,0.065132,0.001192,0.073672,0.013689,0.020096,pass
14,0.028452,0.060768,0.390459,0.001455,0.114607,0.049178,0.317369,0.033477,0.324224,0.088194,...,0.092168,0.108027,0.026405,0.080905,0.091406,0.001845,0.102177,0.020707,0.029952,pass
15,0.031845,0.069999,0.433721,0.001025,0.215262,0.042596,0.370250,0.024209,0.415835,0.075794,...,0.069509,0.078608,0.017490,0.059415,0.064875,0.001272,0.070286,0.013884,0.021145,pass
16,0.018861,0.049718,0.301270,0.001017,0.087589,0.028187,0.212293,0.018204,0.203728,0.052580,...,0.057529,0.067518,0.015074,0.050443,0.054969,0.001078,0.062955,0.012173,0.017397,pass
17,0.017131,0.034155,0.208440,0.000564,0.087750,0.021177,0.185367,0.013340,0.197625,0.036160,...,0.039016,0.045791,0.010132,0.033649,0.037754,0.000714,0.042075,0.008091,0.011497,pass
18,0.033247,0.053723,0.343567,0.000817,0.236466,0.032714,0.366496,0.030156,0.422582,0.072185,...,0.065472,0.074532,0.018047,0.059253,0.068278,0.001287,0.067769,0.012925,0.020575,pass
19,0.030753,0.044808,0.286000,0.000978,0.191864,0.036967,0.292342,0.024658,0.310836,0.058677,...,0.084215,0.093106,0.020741,0.071420,0.078037,0.001527,0.082941,0.016385,0.025551,pass

[[1.1102042  1.18309576 1.10464804 1.28971028 1.12486931 1.26507586
  1.09873314 1.31138093 1.13718697 1.10977914 1.20332557 1.08380185
  1.12553337 1.09629911 1.09571237 1.137053   1.31006808 1.13963491
  1.14750316 1.2203225  1.20370445 1.19955801 1.25230801 1.19899141
  1.2434697  1.2367944  1.24352106 1.23195681 1.1980962  1.21790235
  1.22155859 1.19743394 1.22992033 1.34712325 1.220934   1.25296411
  1.23360043 1.27230231 1.23744718 1.2634121  1.27692209 1.28684571
  1.30344157 1.34183111 1.30787322 1.29068123 1.30004003 1.31857758
  1.37038413 1.40377796 1.37417358]]
BARINEL SCORES

,cx 35,cx 42,cx 34,ry 45,cx 27,ry 21,cx 36,ry 26,cx 40,ry 50,...,cx 23,cx 4,ry 41,cx 7,ry 0,cx 2,ry 1,ry 17,ry 28,ry 43
sum,0.609163,0.605306,0.604506,0.601339,0.600832,0.599244,0.598678,0.597744,0.597523,0.597191,...,0.570079,0.568895,0.567651,0.567067,0.559328,0.558711,0.558396,0.55749,0.556959,0.548369

custom SCORES

,cx 34,ry 45,ry 47,ry 26,cx 35,ry 21,cx 27,cx 42,cx 40,cx 29,...,cx 18,cx 39,cx 23,ry 17,ry 30,cx 48,ry 37,ry 28,ry 43,ry 41
sum,0.802492,0.791524,0.786503,0.783563,0.782326,0.781699,0.78093,0.777393,0.777277,0.776001,...,0.748849,0.746054,0.745657,0.745241,0.743157,0.742735,0.739207,0.73133,0.728149,0.725142

DSTAR SCORES

,cx 42,cx 48,cx 44,cx 36,cx 39,cx 40,cx 34,cx 35,cx 27,cx 38,...,ry 0,ry 6,ry 12,ry 1,ry 14,ry 10,ry 21,ry 3,ry 47,ry 30
sum,1.651032,1.487864,1.217665,0.849855,0.63829,0.525578,0.51428,0.500647,0.490316,0.451774,...,0.005888,0.004842,0.002763,0.002691,0.00209,0.000331,0.000048,0.000025,0.000017,3.243115e-13

ERROR GATE LOCATION:
22
Now evolving the following mutant:  AddGate_y_inGap_9_.qasm

100%|██████████| 10/10 [04:27<00:00, 26.70s/it]
100%|██████████| 10/10 [04:29<00:00, 26.99s/it]

,ry 50,ry 49,cx 48,ry 47,cx 46,ry 45,cx 44,ry 43,cx 42,ry 41,...,y 8,cx 7,ry 6,cx 5,cx 4,ry 3,cx 2,ry 1,ry 0,pass/fail
0,0.042964,0.086087,0.519809,0.001598,0.253897,0.055519,0.404350,0.033811,0.480921,0.096562,...,0.066994,0.124545,0.029808,0.092146,0.108452,0.002158,0.114651,0.023396,0.033974,fail
1,0.028740,0.080921,0.442064,0.001428,0.148999,0.046526,0.308897,0.027903,0.345065,0.077361,...,0.035052,0.062768,0.016050,0.049012,0.056756,0.001114,0.054181,0.010553,0.016122,fail
2,0.025668,0.089934,0.495311,0.001463,0.140016,0.045230,0.261819,0.031813,0.306550,0.081113,...,0.043297,0.079849,0.020146,0.062047,0.071404,0.001422,0.076097,0.014974,0.021463,fail
3,0.027055,0.048644,0.365958,0.001080,0.162734,0.030915,0.302556,0.020802,0.361739,0.071502,...,0.042274,0.080029,0.017935,0.055408,0.066685,0.001259,0.071641,0.014584,0.020704,fail
4,0.036800,0.084727,0.510762,0.001699,0.210967,0.058578,0.410996,0.031418,0.491036,0.093689,...,0.054383,0.100905,0.024945,0.079093,0.086130,0.001808,0.089798,0.018405,0.027397,fail
5,0.036459,0.064203,0.408528,0.001180,0.144979,0.045413,0.332122,0.036363,0.380584,0.079951,...,0.069901,0.130200,0.030797,0.093303,0.109281,0.002207,0.118291,0.024524,0.034945,fail
6,0.044270,0.086642,0.539063,0.001541,0.269033,0.059038,0.470664,0.035666,0.529968,0.099158,...,0.062654,0.115740,0.028173,0.090726,0.100911,0.002007,0.106501,0.020997,0.030660,fail
7,0.032995,0.074513,0.444056,0.001201,0.167953,0.046589,0.346068,0.034380,0.419583,0.084163,...,0.051907,0.100171,0.024400,0.075064,0.087434,0.001743,0.090678,0.018488,0.028276,fail
8,0.036452,0.071344,0.433829,0.001157,0.209057,0.049346,0.386680,0.032238,0.467078,0.084074,...,0.057906,0.105235,0.026197,0.077058,0.091370,0.001859,0.097468,0.020414,0.029339,fail
9,0.038604,0.077574,0.500135,0.001112,0.245297,0.036360,0.406045,0.031583,0.497514,0.087239,...,0.050566,0.098599,0.023051,0.075304,0.085762,0.001621,0.091433,0.017867,0.027003,fail
10,0.034172,0.056922,0.366557,0.001065,0.225986,0.046024,0.371443,0.025787,0.435339,0.072111,...,0.040842,0.079267,0.019027,0.064576,0.068858,0.001356,0.069069,0.013395,0.020985,pass
11,0.034717,0.059972,0.364263,0.000991,0.261178,0.034662,0.376061,0.024662,0.447867,0.068375,...,0.036081,0.072744,0.016843,0.058027,0.064829,0.001216,0.065229,0.012539,0.019392,pass
12,0.035358,0.058539,0.407142,0.000901,0.201836,0.036232,0.367003,0.029868,0.420779,0.076190,...,0.056183,0.105201,0.023510,0.077496,0.086465,0.001705,0.095782,0.019062,0.027611,pass
13,0.033714,0.082277,0.441723,0.000975,0.203478,0.045719,0.324780,0.025023,0.371907,0.070725,...,0.038893,0.071343,0.016837,0.059113,0.062889,0.001208,0.065737,0.011981,0.019303,pass
14,0.030093,0.062580,0.390819,0.000285,0.158447,0.032008,0.299986,0.018473,0.335223,0.057811,...,0.038610,0.069710,0.014874,0.054777,0.055605,0.001050,0.063619,0.011640,0.017038,pass
15,0.039441,0.054223,0.357603,0.001029,0.239412,0.047222,0.432830,0.025066,0.542658,0.075467,...,0.046026,0.086804,0.021351,0.068334,0.075816,0.001510,0.075075,0.015054,0.022695,pass
16,0.036407,0.051108,0.345090,0.001257,0.208512,0.034080,0.407915,0.018833,0.488612,0.071609,...,0.047886,0.088876,0.021397,0.068272,0.076585,0.001485,0.080347,0.015688,0.021941,pass
17,0.024110,0.061525,0.373604,0.000921,0.154542,0.042900,0.245632,0.021850,0.306508,0.064769,...,0.029708,0.055722,0.013838,0.046367,0.049250,0.000993,0.049427,0.009740,0.014985,pass
18,0.031757,0.054862,0.349871,0.000929,0.182058,0.046692,0.318345,0.024869,0.309265,0.067645,...,0.050349,0.096155,0.021606,0.073568,0.080236,0.001545,0.089830,0.017620,0.026257,pass
19,0.024189,0.054813,0.316405,0.000786,0.173177,0.055443,0.285102,0.015926,0.337496,0.067840,...,0.022824,0.037597,0.010111,0.033249,0.034420,0.000709,0.031502,0.006127,0.009524,pass

[[1.26483437 1.17624259 1.15690869 1.26235933 1.37758634 1.24680294
  1.29652441 1.15080472 1.23823298 1.15999665 1.17386325 1.27218371
  1.25538535 1.19862311 1.25769823 1.23034791 1.31596844 1.26963376
  1.21107243 1.22524901 1.2590667  1.24606332 1.26187326 1.22605406
  1.23672866 1.21693629 1.27573227 1.19007943 1.28437015 1.24906836
  1.24741172 1.20939648 1.29999626 1.21809644 1.24259431 1.24048114
  1.2412036  1.24408617 1.24230488 1.24579039 1.25767577 1.27694911
  1.30672365 1.30455931 1.27522472 1.24543892 1.26455533 1.28339568
  1.29884422 1.33135598 1.29483475]]
BARINEL SCORES

,ry 47,ry 1,ry 18,ry 43,ry 0,ry 6,ry 3,ry 11,cx 2,cx 4,...,ry 37,cx 38,ry 33,ry 45,cx 36,cx 39,ry 50,cx 42,cx 44,cx 46
sum,0.595602,0.58099,0.578833,0.578357,0.574692,0.57378,0.573736,0.570694,0.570511,0.568864,...,0.535612,0.532826,0.532767,0.529365,0.524922,0.523214,0.519323,0.517182,0.514244,0.492971

custom SCORES

,ry 47,ry 1,ry 18,ry 0,ry 3,ry 6,cx 2,y 8,cx 7,cx 4,...,cx 38,cx 40,ry 37,ry 45,cx 36,cx 39,ry 50,cx 44,cx 42,cx 46
sum,0.783568,0.774366,0.766953,0.760724,0.757819,0.756705,0.755763,0.753114,0.751389,0.748704,...,0.700052,0.69885,0.696111,0.694369,0.68997,0.68962,0.683537,0.680926,0.67728,0.662748

DSTAR SCORES

,cx 48,cx 42,cx 44,cx 36,cx 39,cx 40,cx 34,cx 35,cx 27,cx 38,...,ry 0,ry 6,ry 1,ry 13,ry 15,ry 11,ry 22,ry 3,ry 47,ry 30
sum,1.583238,1.308887,0.981327,0.734423,0.59526,0.481647,0.472178,0.450509,0.433409,0.424791,...,0.007141,0.00573,0.003349,0.002953,0.002287,0.00039,0.000047,0.00003,0.000018,3.298423e-13

ERROR GATE LOCATION:
8
Now evolving the following mutant:  AddGate_x_inGap_36_.qasm

100%|██████████| 10/10 [04:02<00:00, 24.22s/it]
100%|██████████| 10/10 [04:18<00:00, 25.85s/it]

,ry 50,ry 49,cx 48,ry 47,cx 46,ry 45,cx 44,ry 43,cx 42,ry 41,...,cx 8,cx 7,ry 6,cx 5,cx 4,ry 3,cx 2,ry 1,ry 0,pass/fail
0,0.027049,0.058789,0.384233,0.001054,0.167483,0.028880,0.315155,0.018471,0.340417,0.063504,...,0.060697,0.070384,0.016412,0.052269,0.059518,0.001214,0.062023,0.012572,0.018561,fail
1,0.035149,0.070830,0.453093,0.000934,0.240291,0.027205,0.380031,0.032914,0.400660,0.084974,...,0.080593,0.091355,0.019815,0.069301,0.077798,0.001470,0.080986,0.015384,0.024628,fail
2,0.029564,0.079079,0.443480,0.001328,0.197100,0.051989,0.331067,0.026836,0.356081,0.075515,...,0.073108,0.080603,0.018459,0.063103,0.069492,0.001348,0.071260,0.013967,0.021662,fail
3,0.031397,0.073416,0.448818,0.001285,0.203849,0.045461,0.346496,0.024886,0.417111,0.080284,...,0.062584,0.070260,0.016886,0.053918,0.062732,0.001181,0.062527,0.012004,0.017833,fail
4,0.039145,0.070983,0.452339,0.001488,0.232431,0.036323,0.415613,0.031285,0.517104,0.081267,...,0.092121,0.108389,0.025325,0.080435,0.093384,0.001809,0.098955,0.019532,0.027382,fail
5,0.029546,0.049336,0.372555,0.000885,0.200143,0.037488,0.330963,0.014354,0.385945,0.063396,...,0.060804,0.066543,0.013912,0.052938,0.053538,0.001000,0.055624,0.010326,0.015891,fail
6,0.040898,0.062409,0.453382,0.001031,0.236836,0.050610,0.454891,0.030868,0.527657,0.091865,...,0.098562,0.112035,0.026643,0.086092,0.094688,0.001908,0.100098,0.020030,0.030611,fail
7,0.038778,0.087081,0.511591,0.001104,0.251283,0.046056,0.408690,0.032425,0.503478,0.084294,...,0.088076,0.102370,0.023979,0.073924,0.088383,0.001770,0.090333,0.018742,0.027678,fail
8,0.036735,0.073025,0.434952,0.001519,0.233222,0.049778,0.377318,0.027793,0.465881,0.087525,...,0.093053,0.105674,0.025963,0.079003,0.092830,0.001911,0.094126,0.019739,0.029145,fail
9,0.038124,0.064646,0.428625,0.001061,0.270483,0.037316,0.427888,0.022399,0.497617,0.072767,...,0.074246,0.083159,0.017719,0.064514,0.070141,0.001311,0.070797,0.013113,0.020582,fail
10,0.029717,0.077562,0.443300,0.001097,0.152342,0.058023,0.294240,0.031290,0.336700,0.078369,...,0.076450,0.085839,0.021645,0.066852,0.074446,0.001563,0.076790,0.015926,0.023770,pass
11,0.013788,0.041408,0.251896,0.000773,0.084009,0.032688,0.179206,0.014208,0.192644,0.050175,...,0.031560,0.035019,0.008873,0.028151,0.030222,0.000634,0.031306,0.006334,0.009465,pass
12,0.024891,0.052111,0.318911,0.001215,0.118450,0.038454,0.254368,0.021416,0.307790,0.062349,...,0.066033,0.074946,0.018658,0.058767,0.064448,0.001307,0.067452,0.013579,0.020257,pass
13,0.025716,0.085733,0.459609,0.001724,0.128871,0.047042,0.287387,0.028448,0.307365,0.075307,...,0.070118,0.082222,0.020577,0.061619,0.071602,0.001427,0.078676,0.015899,0.021978,pass
14,0.022991,0.062008,0.337876,0.001111,0.119852,0.035405,0.247643,0.018184,0.324679,0.059312,...,0.044121,0.049749,0.012939,0.039312,0.045351,0.000903,0.043087,0.008606,0.012446,pass
15,0.023609,0.058056,0.317132,0.000714,0.141183,0.028963,0.226346,0.017162,0.254496,0.046747,...,0.043934,0.049113,0.011180,0.038243,0.043789,0.000806,0.042579,0.007812,0.012507,pass
16,0.046738,0.067131,0.435351,0.001255,0.223117,0.046588,0.439824,0.039455,0.531431,0.082668,...,0.117389,0.136673,0.032915,0.103732,0.116983,0.002347,0.124446,0.024944,0.037047,pass
17,0.030614,0.053122,0.363979,0.000694,0.209476,0.035914,0.373457,0.008206,0.446151,0.068656,...,0.045309,0.048122,0.011563,0.041691,0.041702,0.000757,0.043487,0.007639,0.011864,pass
18,0.026910,0.058415,0.320532,0.001268,0.144318,0.035813,0.288373,0.017517,0.280501,0.058208,...,0.057185,0.061830,0.014405,0.052275,0.052608,0.001054,0.054439,0.009825,0.015270,pass
19,0.029379,0.077982,0.478151,0.001022,0.176026,0.045363,0.289000,0.032147,0.324977,0.082573,...,0.067654,0.075909,0.017888,0.060738,0.067751,0.001274,0.068832,0.013029,0.020757,pass

[[1.18070519 1.26278123 1.16719827 1.29899597 1.21123469 1.26460091
  1.20083743 1.25513705 1.19597279 1.1696699  1.29624759 1.20826046
  1.21060944 1.27524865 1.139069   1.14705704 1.24974577 1.28873042
  1.18982433 1.20474101 1.24771866 1.19229496 1.20531771 1.26904959
  1.25420678 1.25054623 1.28531618 1.35761665 1.29678669 1.24252741
  1.27832573 1.26694615 1.26503557 1.33137711 1.25184403 1.23525109
  1.28541647 1.30396308 1.33657767 1.28050988 1.30515023 1.2311072
  1.25741324 1.25772731 1.29892692 1.27449467 1.24180593 1.28043552
  1.27232822 1.28886285 1.30829982]]
BARINEL SCORES

,cx 46,cx 38,cx 42,cx 44,cx 26,cx 40,x 35,ry 12,cx 7,cx 36,...,cx 22,ry 37,ry 29,ry 17,cx 19,ry 43,cx 24,ry 49,ry 47,ry 45
sum,0.598569,0.57515,0.571594,0.568107,0.565821,0.562905,0.562781,0.561597,0.560165,0.558766,...,0.536859,0.536846,0.536015,0.535849,0.534926,0.534877,0.533194,0.521187,0.518098,0.504203

custom SCORES

,cx 46,ry 12,cx 38,cx 40,cx 26,cx 42,ry 0,cx 44,ry 1,cx 7,...,cx 24,cx 19,ry 32,ry 43,ry 41,cx 48,ry 29,ry 47,ry 49,ry 45
sum,0.779821,0.749251,0.74922,0.745322,0.743236,0.742496,0.740457,0.738658,0.736501,0.736299,...,0.704525,0.704357,0.70276,0.702713,0.700156,0.698173,0.695787,0.68635,0.685723,0.663607

DSTAR SCORES

,cx 42,cx 48,cx 44,cx 36,cx 39,cx 40,cx 26,cx 38,cx 46,cx 33,...,ry 0,ry 6,ry 12,ry 1,ry 14,ry 10,ry 21,ry 3,ry 47,ry 29
sum,1.462817,1.399552,1.114127,0.736024,0.54417,0.455166,0.440352,0.437708,0.433726,0.417614,...,0.005375,0.004137,0.002517,0.002386,0.001763,0.000284,0.000042,0.000022,0.000014,2.799145e-13

ERROR GATE LOCATION:
35
Now evolving the following mutant:  AddGate_y_inGap_10_.qasm

100%|██████████| 10/10 [04:34<00:00, 27.40s/it]
100%|██████████| 10/10 [04:01<00:00, 24.17s/it]

,ry 50,ry 49,cx 48,ry 47,cx 46,ry 45,cx 44,ry 43,cx 42,ry 41,...,cx 8,cx 7,ry 6,cx 5,cx 4,ry 3,cx 2,ry 1,ry 0,pass/fail
0,0.035407,0.079491,0.470580,0.001713,0.165653,0.055385,0.346938,0.029596,0.420453,0.084745,...,0.087319,0.098001,0.024228,0.075655,0.084328,0.001680,0.087632,0.017506,0.025169,fail
1,0.036584,0.092141,0.487908,0.001612,0.205033,0.061717,0.344658,0.032206,0.395650,0.084088,...,0.086634,0.098225,0.023715,0.075975,0.086679,0.001696,0.090514,0.017662,0.025883,fail
2,0.031948,0.070582,0.417743,0.001193,0.201174,0.041008,0.349832,0.028094,0.411017,0.078343,...,0.078599,0.092711,0.021265,0.065605,0.079472,0.001562,0.083675,0.017039,0.024930,fail
3,0.035188,0.079429,0.443592,0.001837,0.188578,0.058461,0.319282,0.029409,0.383386,0.080659,...,0.088174,0.098004,0.023967,0.076901,0.085965,0.001736,0.087369,0.017459,0.025290,fail
4,0.032951,0.079579,0.458555,0.001106,0.194007,0.042380,0.340547,0.030992,0.433830,0.077496,...,0.068325,0.078122,0.018109,0.060486,0.068574,0.001265,0.070043,0.013267,0.019996,fail
5,0.045941,0.082339,0.521462,0.001595,0.272393,0.054011,0.496463,0.030879,0.626073,0.095885,...,0.099600,0.113286,0.027349,0.088443,0.097751,0.001956,0.099888,0.019761,0.029220,fail
6,0.032124,0.095203,0.509243,0.001602,0.165132,0.050860,0.280177,0.036651,0.337749,0.081731,...,0.086825,0.102852,0.024834,0.074795,0.090757,0.001813,0.094178,0.019171,0.028037,fail
7,0.039136,0.070246,0.435480,0.001680,0.219205,0.048295,0.401028,0.032788,0.466526,0.080452,...,0.096188,0.110732,0.025990,0.085600,0.095863,0.001832,0.101812,0.019666,0.028726,fail
8,0.038405,0.085347,0.492157,0.001427,0.201049,0.040311,0.370471,0.034211,0.446924,0.083894,...,0.089996,0.105605,0.024674,0.079350,0.091666,0.001756,0.097266,0.018876,0.027816,fail
9,0.033625,0.067664,0.442420,0.001051,0.183316,0.032877,0.378834,0.026499,0.414665,0.081699,...,0.077573,0.092632,0.020947,0.068335,0.077728,0.001475,0.086878,0.016766,0.024437,fail
10,0.045323,0.063365,0.443836,0.001372,0.244420,0.041098,0.428642,0.028667,0.517724,0.078121,...,0.117899,0.137096,0.031008,0.102049,0.114820,0.002206,0.126674,0.024939,0.036388,pass
11,0.035326,0.064934,0.421084,0.001161,0.187071,0.037772,0.342973,0.027158,0.428822,0.077337,...,0.088265,0.102340,0.024358,0.077611,0.087696,0.001729,0.095654,0.019085,0.026735,pass
12,0.013925,0.033965,0.230122,0.000920,0.076767,0.017462,0.195011,0.010764,0.155598,0.042865,...,0.034140,0.037655,0.007228,0.030810,0.028389,0.000532,0.031920,0.005520,0.008521,pass
13,0.034148,0.082468,0.485934,0.001343,0.219612,0.043011,0.346275,0.034401,0.447132,0.080392,...,0.075972,0.087556,0.020931,0.067018,0.076770,0.001502,0.079069,0.015843,0.024136,pass
14,0.032686,0.071955,0.413556,0.001154,0.191252,0.043762,0.356983,0.017419,0.430643,0.073051,...,0.062217,0.067612,0.016013,0.052348,0.056868,0.001165,0.057026,0.011352,0.016625,pass
15,0.044785,0.069008,0.438949,0.000956,0.227262,0.037352,0.426708,0.025471,0.513384,0.077133,...,0.096334,0.111087,0.025267,0.080654,0.092534,0.001776,0.100069,0.019764,0.028836,pass
16,0.032601,0.056879,0.376773,0.001346,0.191941,0.041202,0.352060,0.022394,0.380848,0.067025,...,0.081884,0.093989,0.020995,0.070027,0.079151,0.001508,0.083397,0.016358,0.024316,pass
17,0.033951,0.080685,0.479285,0.001343,0.158349,0.050497,0.317991,0.033056,0.367755,0.081721,...,0.083152,0.096475,0.024030,0.074714,0.084580,0.001689,0.089236,0.017592,0.025403,pass
18,0.034382,0.066765,0.444393,0.001466,0.183935,0.037305,0.371478,0.029468,0.405574,0.078202,...,0.095260,0.112418,0.025683,0.084251,0.094196,0.001843,0.104158,0.020605,0.029681,pass
19,0.022997,0.041914,0.275697,0.000469,0.132943,0.017745,0.255052,0.018675,0.288805,0.050577,...,0.049588,0.057601,0.012638,0.043460,0.046957,0.000880,0.053627,0.010087,0.014845,pass

[[1.27150859 1.1870374  1.11444037 1.23955452 1.36500951 1.27171698
  1.36833512 1.17728074 1.44380369 1.15665234 1.3073387  1.20230009
  1.25948837 1.196411   1.22211164 1.25076475 1.32335324 1.16292615
  1.25670712 1.19355187 1.16833475 1.24941902 1.11766036 1.23734952
  1.22871364 1.23525419 1.26949748 1.15256899 1.27079193 1.23082445
  1.22826046 1.13760679 1.11126523 1.16861488 1.12999043 1.20614348
  1.16718245 1.12445675 1.17788903 1.16247471 1.13009533 1.12275901
  1.15916819 1.14410712 1.16339708 1.17744228 1.13825154 1.16650877
  1.13218268 1.11536384 1.1259804 ]]
BARINEL SCORES

,ry 45,ry 47,ry 49,ry 43,ry 26,ry 30,ry 11,cx 32,ry 41,ry 28,...,cx 2,cx 7,cx 8,ry 50,cx 21,cx 40,ry 13,cx 44,cx 38,cx 24
sum,0.569266,0.562351,0.559306,0.557131,0.541065,0.540658,0.540248,0.540152,0.539914,0.538591,...,0.522797,0.522793,0.522666,0.522554,0.521786,0.521007,0.51803,0.516739,0.514692,0.51182

custom SCORES

,ry 45,ry 47,ry 49,ry 43,cx 42,cx 32,ry 26,cx 34,cx 46,cx 27,...,cx 38,cx 24,cx 8,cx 7,ry 18,ry 0,cx 2,y 9,ry 1,ry 13
sum,0.750252,0.736617,0.725285,0.721106,0.713377,0.709856,0.707269,0.706678,0.702667,0.699739,...,0.676755,0.674258,0.67413,0.672326,0.672088,0.671839,0.670772,0.669954,0.669713,0.663656

DSTAR SCORES

,cx 48,cx 42,cx 44,cx 36,cx 39,cx 34,cx 27,cx 35,cx 40,cx 32,...,ry 0,ry 6,ry 1,ry 13,ry 15,ry 11,ry 22,ry 3,ry 47,ry 30
sum,1.562807,1.34923,0.982893,0.778093,0.609837,0.501603,0.498999,0.479044,0.473482,0.417111,...,0.006579,0.005413,0.003089,0.002662,0.002168,0.000383,0.000048,0.000028,0.000022,3.875806e-13

ERROR GATE LOCATION:
9
Now evolving the following mutant:  AddGate_x_inGap_32_.qasm

100%|██████████| 10/10 [04:10<00:00, 25.09s/it]
100%|██████████| 10/10 [04:03<00:00, 24.39s/it]

,ry 50,ry 49,cx 48,ry 47,cx 46,ry 45,cx 44,ry 43,cx 42,ry 41,...,cx 8,cx 7,ry 6,cx 5,cx 4,ry 3,cx 2,ry 1,ry 0,pass/fail
0,0.032635,0.067400,0.410218,0.001335,0.226065,0.047137,0.342664,0.028446,0.442593,0.084879,...,0.065757,0.073654,0.018151,0.056700,0.067953,0.001302,0.064194,0.012880,0.019421,fail
1,0.043280,0.067270,0.460123,0.001094,0.265920,0.042721,0.459894,0.036638,0.549457,0.086372,...,0.099737,0.115896,0.027459,0.086791,0.099919,0.001956,0.105062,0.021197,0.032482,fail
2,0.037372,0.072494,0.480244,0.001557,0.240576,0.046696,0.424282,0.026633,0.487054,0.087574,...,0.085473,0.098261,0.023552,0.076914,0.086105,0.001645,0.092103,0.017819,0.025730,fail
3,0.025374,0.056789,0.375147,0.000818,0.173681,0.038860,0.294169,0.018693,0.350190,0.070511,...,0.048484,0.050788,0.012357,0.041792,0.043195,0.000875,0.042922,0.008324,0.012603,fail
4,0.036630,0.058826,0.388819,0.000799,0.241354,0.045255,0.375098,0.029970,0.431670,0.073658,...,0.079611,0.088227,0.020084,0.069341,0.075343,0.001468,0.077370,0.015051,0.023283,fail
5,0.027960,0.070798,0.441656,0.001187,0.150962,0.046801,0.327861,0.034580,0.351523,0.088153,...,0.077416,0.090277,0.022548,0.068551,0.078005,0.001636,0.081810,0.016868,0.025278,fail
6,0.042135,0.084208,0.512030,0.001304,0.278943,0.048923,0.454776,0.024405,0.546830,0.087118,...,0.082028,0.092392,0.021216,0.069740,0.079473,0.001475,0.083386,0.016137,0.022985,fail
7,0.044744,0.091789,0.554562,0.001306,0.238447,0.063443,0.454085,0.033400,0.525104,0.101482,...,0.100177,0.112821,0.027750,0.086829,0.098231,0.001945,0.101760,0.020178,0.029418,fail
8,0.037668,0.076314,0.478951,0.001359,0.228391,0.058012,0.394422,0.032162,0.467144,0.092503,...,0.087167,0.097804,0.024158,0.077297,0.085394,0.001722,0.089473,0.017757,0.025474,fail
9,0.036002,0.067818,0.452110,0.001117,0.225317,0.064468,0.387459,0.028307,0.496412,0.093932,...,0.071250,0.075490,0.019968,0.062516,0.067796,0.001369,0.065037,0.013148,0.019732,fail
10,0.022096,0.054133,0.369288,0.000987,0.144865,0.039860,0.290248,0.010995,0.305800,0.069647,...,0.041697,0.043083,0.010194,0.037520,0.034735,0.000711,0.036935,0.006854,0.010031,pass
11,0.029934,0.042768,0.320312,0.001171,0.135394,0.034443,0.330871,0.018586,0.364215,0.063875,...,0.077808,0.091199,0.021062,0.068731,0.074285,0.001458,0.083792,0.016537,0.022979,pass
12,0.022288,0.050796,0.305676,0.000919,0.094813,0.033605,0.245213,0.014419,0.271549,0.054115,...,0.061073,0.070900,0.017616,0.054324,0.059490,0.001238,0.067196,0.013491,0.018284,pass
13,0.037426,0.060445,0.391205,0.001203,0.211852,0.041652,0.405304,0.029746,0.477009,0.083401,...,0.086993,0.100927,0.024979,0.075369,0.088131,0.001740,0.094356,0.019115,0.027533,pass
14,0.021857,0.061761,0.381780,0.000937,0.120777,0.025559,0.235978,0.014805,0.282333,0.056141,...,0.036920,0.041147,0.009300,0.032469,0.034790,0.000633,0.033188,0.005913,0.008939,pass
15,0.028370,0.058399,0.342266,0.001075,0.183412,0.038294,0.288427,0.030696,0.317853,0.064370,...,0.068762,0.077622,0.017270,0.060417,0.067443,0.001243,0.069428,0.013301,0.020729,pass
16,0.028004,0.060812,0.380455,0.001146,0.189492,0.029803,0.314748,0.020678,0.367257,0.068840,...,0.053800,0.060573,0.013709,0.048611,0.053513,0.000967,0.054915,0.010012,0.015955,pass
17,0.031379,0.048948,0.329815,0.000788,0.186641,0.022112,0.330892,0.020474,0.384522,0.063346,...,0.072027,0.085872,0.019706,0.061047,0.072430,0.001406,0.080502,0.016205,0.022757,pass
18,0.030286,0.058408,0.379580,0.000860,0.170757,0.038254,0.302173,0.024552,0.359656,0.060400,...,0.087329,0.103204,0.022818,0.074792,0.085065,0.001652,0.094555,0.019046,0.027262,pass
19,0.020953,0.077044,0.413093,0.001600,0.119427,0.040858,0.198558,0.022226,0.253714,0.065694,...,0.055667,0.065247,0.015793,0.048824,0.058074,0.001154,0.058765,0.011784,0.016912,pass

[[1.22990033 1.28608695 1.21778391 1.31076357 1.22901087 1.28341342
  1.17478504 1.24943755 1.18214271 1.17160572 1.27537343 1.20680951
  1.2329347  1.22329747 1.21225649 1.31236644 1.41992049 1.24813669
  1.25932829 1.3070463  1.32043354 1.2932866  1.29069456 1.26631717
  1.29909395 1.31709435 1.29833231 1.26567589 1.28463651 1.26231019
  1.28686179 1.2507121  1.29729597 1.30525927 1.28201422 1.27653077
  1.26676169 1.28590664 1.33813392 1.27090092 1.28050107 1.26255371
  1.25677031 1.29404407 1.2773709  1.24669597 1.27869681 1.27080176
  1.30818087 1.33013198 1.37397631]]
BARINEL SCORES

,ry 45,cx 46,ry 43,ry 12,ry 37,cx 42,cx 39,cx 40,cx 38,ry 50,...,cx 5,ry 29,ry 0,cx 30,cx 13,cx 7,ry 1,ry 17,cx 2,ry 47
sum,0.593224,0.593051,0.585985,0.584298,0.582238,0.578691,0.578253,0.57672,0.575402,0.571658,...,0.553381,0.552797,0.552626,0.552383,0.552346,0.547645,0.54647,0.543877,0.543842,0.526384

custom SCORES

,ry 45,ry 12,cx 46,ry 43,cx 40,ry 37,cx 35,cx 34,cx 38,cx 39,...,cx 9,cx 13,ry 1,cx 8,cx 48,cx 5,cx 7,cx 2,ry 17,ry 47
sum,0.783562,0.779765,0.775267,0.769023,0.760603,0.7603,0.753564,0.75278,0.75276,0.752713,...,0.730447,0.729912,0.728189,0.727878,0.72732,0.725855,0.724814,0.721703,0.721352,0.698875

DSTAR SCORES

,cx 42,cx 48,cx 44,cx 36,cx 39,cx 40,cx 35,cx 38,cx 46,cx 34,...,ry 0,ry 6,ry 12,ry 1,ry 14,ry 10,ry 21,ry 3,ry 47,ry 29
sum,1.614155,1.523317,1.184088,0.777015,0.676732,0.521394,0.481629,0.467706,0.445717,0.442316,...,0.005484,0.004639,0.002715,0.002506,0.002019,0.000326,0.000044,0.000024,0.000014,3.112500e-13

ERROR GATE LOCATION:
31
Now evolving the following mutant:  AddGate_x_inGap_27_.qasm

100%|██████████| 10/10 [04:22<00:00, 26.21s/it]
100%|██████████| 10/10 [03:56<00:00, 23.62s/it]

,ry 50,ry 49,cx 48,ry 47,cx 46,ry 45,cx 44,ry 43,cx 42,ry 41,...,cx 8,cx 7,ry 6,cx 5,cx 4,ry 3,cx 2,ry 1,ry 0,pass/fail
0,0.039576,0.071615,0.476866,0.001605,0.225536,0.058237,0.433326,0.034076,0.503006,0.097490,...,0.096878,0.108562,0.026096,0.085247,0.092996,0.001819,0.097548,0.019130,0.028365,fail
1,0.037348,0.059010,0.439770,0.001320,0.214936,0.035292,0.420710,0.034270,0.492628,0.087653,...,0.099311,0.117378,0.027347,0.087428,0.099215,0.001941,0.108173,0.021605,0.031284,fail
2,0.037245,0.093504,0.523635,0.001614,0.238755,0.041545,0.402821,0.023813,0.476273,0.081948,...,0.065494,0.072246,0.017418,0.056280,0.063777,0.001268,0.061496,0.011784,0.018110,fail
3,0.032491,0.075646,0.460982,0.001371,0.172661,0.046723,0.342557,0.025470,0.368718,0.081631,...,0.078600,0.089192,0.021082,0.067399,0.075567,0.001484,0.080199,0.015918,0.022782,fail
4,0.024512,0.068391,0.425894,0.001356,0.137463,0.043740,0.268792,0.023144,0.306935,0.077001,...,0.063508,0.072258,0.018232,0.054150,0.061932,0.001316,0.064633,0.013550,0.020019,fail
5,0.033163,0.091094,0.523725,0.001341,0.225487,0.043135,0.379077,0.036495,0.438378,0.093334,...,0.067259,0.077743,0.019393,0.058236,0.072383,0.001388,0.069382,0.013942,0.021560,fail
6,0.038935,0.066668,0.427397,0.001373,0.246055,0.047223,0.440094,0.033757,0.504448,0.086635,...,0.095578,0.109744,0.025734,0.082807,0.094270,0.001898,0.096848,0.019683,0.029392,fail
7,0.031622,0.070434,0.440017,0.001364,0.183713,0.045721,0.328446,0.030343,0.370522,0.085594,...,0.087399,0.101232,0.023873,0.074719,0.085673,0.001710,0.095140,0.019140,0.027359,fail
8,0.033522,0.064610,0.408171,0.001153,0.202003,0.033872,0.351418,0.029654,0.410388,0.075999,...,0.088292,0.104420,0.023746,0.078114,0.088505,0.001721,0.097808,0.019115,0.027760,fail
9,0.040148,0.055277,0.401034,0.001351,0.245616,0.034186,0.430901,0.020010,0.513934,0.072142,...,0.088775,0.101090,0.023131,0.076928,0.085212,0.001658,0.088644,0.017413,0.025833,fail
10,0.017982,0.034874,0.224807,0.000626,0.086321,0.025146,0.196317,0.018078,0.201893,0.045872,...,0.059028,0.069322,0.016460,0.052256,0.057953,0.001173,0.066275,0.013349,0.019219,pass
11,0.032310,0.067185,0.427356,0.001432,0.209556,0.032556,0.369503,0.012292,0.424105,0.075153,...,0.060320,0.068126,0.015521,0.054311,0.058996,0.001077,0.062203,0.011136,0.016802,pass
12,0.018344,0.049093,0.280707,0.000624,0.119613,0.021177,0.204275,0.011841,0.238734,0.037771,...,0.037857,0.043034,0.008434,0.032852,0.034220,0.000632,0.037284,0.006871,0.010870,pass
13,0.027780,0.049031,0.316049,0.000710,0.136057,0.018396,0.239177,0.021932,0.290661,0.053573,...,0.079739,0.094644,0.021111,0.068426,0.078482,0.001527,0.089630,0.017864,0.025747,pass
14,0.023266,0.041913,0.306468,0.000916,0.111296,0.026363,0.254144,0.022466,0.273497,0.059075,...,0.075539,0.089793,0.020950,0.066884,0.073844,0.001490,0.084959,0.017020,0.024431,pass
15,0.027399,0.030694,0.231732,0.000579,0.126267,0.029712,0.253941,0.021045,0.294291,0.049587,...,0.068293,0.077388,0.018213,0.059445,0.064142,0.001293,0.068552,0.013730,0.020689,pass
16,0.026794,0.040780,0.293318,0.001163,0.132799,0.028366,0.282938,0.029507,0.317745,0.069363,...,0.086128,0.100888,0.024327,0.077470,0.085467,0.001789,0.092631,0.019007,0.028101,pass
17,0.036360,0.061725,0.382108,0.001390,0.155126,0.051105,0.344858,0.032535,0.384976,0.081607,...,0.103875,0.119557,0.029897,0.090448,0.103445,0.002126,0.110334,0.022778,0.033239,pass
18,0.033128,0.073439,0.455967,0.001031,0.216750,0.051395,0.345575,0.025667,0.392836,0.075701,...,0.066602,0.071390,0.015015,0.057560,0.058515,0.001100,0.060089,0.011074,0.017609,pass
19,0.027308,0.058084,0.363297,0.001037,0.132315,0.034279,0.278638,0.029391,0.284456,0.070886,...,0.074021,0.086225,0.020574,0.066709,0.074558,0.001414,0.082869,0.015975,0.023704,pass

[[1.15180891 1.30546535 1.15676579 1.16556635 1.17604355 1.35537076
  1.15870776 1.25398558 1.17196544 1.16138939 1.25086014 1.16631589
  1.13758158 1.2480849  1.14454942 1.29872314 1.3177574  1.22463473
  1.18331795 1.20028287 1.14384913 1.16091632 1.17394138 1.16373796
  1.15691023 1.16076763 1.20792552 1.24595913 1.22034218 1.18006239
  1.19958717 1.18342848 1.19788857 1.22411212 1.19623217 1.17962
  1.18681177 1.21708289 1.28442076 1.20920712 1.15537255 1.19746327
  1.19493949 1.23055414 1.20975043 1.21208074 1.21062963 1.1980242
  1.25801082 1.26139967 1.23913573]]
BARINEL SCORES

,cx 46,ry 47,ry 49,cx 42,cx 48,cx 44,ry 41,ry 45,cx 38,cx 40,...,cx 23,ry 30,cx 8,cx 7,cx 13,ry 17,cx 5,ry 1,ry 0,cx 2
sum,0.594666,0.592936,0.585617,0.585601,0.579756,0.578323,0.575733,0.574303,0.56935,0.567867,...,0.539523,0.538974,0.538798,0.537622,0.537522,0.535575,0.535226,0.535111,0.53389,0.532528

custom SCORES

,ry 49,cx 46,ry 45,ry 47,cx 42,cx 48,cx 44,cx 40,cx 34,ry 41,...,ry 1,cx 9,cx 7,cx 13,cx 2,cx 8,ry 17,ry 0,cx 5,ry 30
sum,0.776743,0.769504,0.768901,0.765713,0.757177,0.747417,0.74585,0.745448,0.743167,0.742896,...,0.703858,0.703477,0.703015,0.701075,0.700009,0.699756,0.699476,0.699281,0.697411,0.6931

DSTAR SCORES

,cx 48,cx 42,cx 44,cx 36,cx 39,cx 40,cx 34,cx 27,cx 38,cx 35,...,ry 0,ry 6,ry 1,ry 12,ry 14,ry 10,ry 21,ry 3,ry 47,ry 30
sum,1.543327,1.467599,1.129727,0.731235,0.585154,0.490696,0.47942,0.457974,0.441719,0.435607,...,0.006236,0.005014,0.002891,0.002748,0.00206,0.000343,0.000047,0.000026,0.000019,2.995310e-13

ERROR GATE LOCATION:
26
Now evolving the following mutant:  AddGate_h_inGap_28_.qasm

100%|██████████| 10/10 [04:26<00:00, 26.65s/it]
100%|██████████| 10/10 [04:22<00:00, 26.30s/it]

,ry 50,ry 49,cx 48,ry 47,cx 46,ry 45,cx 44,ry 43,cx 42,ry 41,...,cx 8,cx 7,ry 6,cx 5,cx 4,ry 3,cx 2,ry 1,ry 0,pass/fail
0,0.034184,0.058435,0.396788,0.001559,0.213467,0.039802,0.390597,0.024232,0.440389,0.077700,...,0.086833,0.100211,0.023938,0.076959,0.086072,0.001771,0.089183,0.017138,0.025232,fail
1,0.034689,0.084803,0.480972,0.001671,0.182997,0.042411,0.334704,0.024222,0.411965,0.077270,...,0.081421,0.094347,0.023453,0.071788,0.086274,0.001771,0.083473,0.016286,0.025036,fail
2,0.032840,0.063290,0.410224,0.001197,0.199279,0.047761,0.382029,0.015751,0.450043,0.075100,...,0.067882,0.077012,0.018889,0.059582,0.065862,0.001382,0.067284,0.012922,0.019535,fail
3,0.039827,0.061121,0.385157,0.001404,0.221044,0.047859,0.370448,0.037773,0.419132,0.076518,...,0.117367,0.140052,0.031796,0.100319,0.118847,0.002385,0.125475,0.025237,0.037570,fail
4,0.037593,0.076879,0.451536,0.001449,0.165478,0.039306,0.342608,0.039121,0.363681,0.077716,...,0.117033,0.140587,0.032552,0.100017,0.119016,0.002475,0.126894,0.025595,0.037947,fail
5,0.021704,0.058301,0.357194,0.001384,0.135652,0.041658,0.251962,0.019893,0.295267,0.069345,...,0.064585,0.077581,0.018388,0.054527,0.066481,0.001386,0.070204,0.014451,0.021017,fail
6,0.033089,0.084032,0.461404,0.001330,0.168330,0.046697,0.342254,0.028344,0.427822,0.078588,...,0.073799,0.087772,0.021776,0.065366,0.079507,0.001648,0.076424,0.014906,0.023062,fail
7,0.039584,0.071682,0.449973,0.001630,0.218442,0.051415,0.424584,0.029448,0.505357,0.092482,...,0.093842,0.109165,0.027757,0.083351,0.098880,0.002066,0.096815,0.019042,0.028948,fail
8,0.044851,0.079332,0.505121,0.001408,0.212035,0.043924,0.423492,0.030123,0.506521,0.084798,...,0.114945,0.136140,0.032585,0.100726,0.116644,0.002401,0.122686,0.024332,0.036141,fail
9,0.036876,0.055659,0.347476,0.000649,0.199211,0.045741,0.376549,0.024879,0.380161,0.067446,...,0.089787,0.101283,0.023369,0.078789,0.084837,0.001725,0.090488,0.017327,0.026840,fail
10,0.020126,0.052259,0.299119,0.000965,0.117525,0.031589,0.212116,0.016591,0.248562,0.053062,...,0.041565,0.048390,0.011653,0.036296,0.043423,0.000859,0.041851,0.008063,0.013010,pass
11,0.035385,0.072491,0.456859,0.001134,0.222664,0.038218,0.383011,0.026424,0.443879,0.074204,...,0.076115,0.085878,0.020597,0.068946,0.076335,0.001559,0.075945,0.014214,0.022423,pass
12,0.037336,0.073572,0.489737,0.000938,0.232102,0.034083,0.407628,0.024845,0.455165,0.080397,...,0.084464,0.097209,0.021122,0.073649,0.080221,0.001579,0.085145,0.016089,0.024569,pass
13,0.026034,0.060507,0.379867,0.000886,0.167225,0.025848,0.289502,0.021193,0.343233,0.058234,...,0.062817,0.075496,0.016351,0.054137,0.064878,0.001257,0.066291,0.012843,0.019650,pass
14,0.037497,0.083613,0.484410,0.001445,0.194743,0.064491,0.394422,0.031411,0.453175,0.084438,...,0.099297,0.118521,0.028111,0.086871,0.099450,0.002039,0.107075,0.021339,0.030717,pass
15,0.024983,0.034648,0.290316,0.000607,0.164193,0.022061,0.334138,0.022118,0.358304,0.067555,...,0.051197,0.061712,0.014181,0.044338,0.052391,0.000975,0.054869,0.010453,0.015543,pass
16,0.039319,0.064062,0.435107,0.001293,0.244469,0.047707,0.427397,0.021009,0.518984,0.080136,...,0.092531,0.109247,0.024717,0.080136,0.091378,0.001824,0.096062,0.018735,0.027916,pass
17,0.025337,0.058176,0.353532,0.001386,0.098149,0.026085,0.252199,0.021819,0.281324,0.061931,...,0.074031,0.088815,0.021961,0.065242,0.078615,0.001657,0.079387,0.015789,0.023315,pass
18,0.035722,0.036828,0.268034,0.000846,0.157937,0.032911,0.335380,0.026312,0.382445,0.065528,...,0.094022,0.110247,0.026543,0.083627,0.095311,0.001972,0.099362,0.019548,0.029948,pass
19,0.033989,0.055968,0.360503,0.001428,0.163908,0.035389,0.336740,0.029282,0.360605,0.068851,...,0.101845,0.119429,0.028927,0.090708,0.104774,0.002189,0.108009,0.021227,0.031637,pass

[[1.26255556 1.22275953 1.18968161 1.22151138 1.1537155  1.15132744
  1.16668828 1.42889197 1.20590586 1.19029536 1.23484457 1.22493082
  1.22575346 1.19989331 1.24488476 1.22596447 1.220159   1.24926889
  1.19877168 1.21728403 1.24787447 1.19717234 1.38715362 1.352596
  1.16765106 1.20272022 1.25666732 1.3018646  1.25625747 1.22162422
  1.25726976 1.24568385 1.25842341 1.34505109 1.24074018 1.24995534
  1.2453647  1.28842756 1.2954202  1.27569505 1.24798185 1.29064432
  1.29330935 1.32112039 1.28032426 1.27272047 1.29025551 1.30181512
  1.33723799 1.36698054 1.34883735]]
BARINEL SCORES

,ry 47,ry 45,ry 17,ry 10,ry 25,ry 14,h 27,ry 3,cx 29,ry 6,...,ry 50,cx 40,ry 41,ry 30,cx 48,ry 37,cx 38,cx 42,cx 46,cx 44
sum,0.555952,0.554781,0.549373,0.546985,0.545879,0.545477,0.544391,0.544363,0.54351,0.543036,...,0.529441,0.528178,0.52808,0.52802,0.526562,0.524493,0.522422,0.52204,0.520797,0.519018

custom SCORES

,ry 17,h 27,ry 28,ry 1,ry 47,ry 0,ry 43,ry 3,cx 2,ry 10,...,ry 30,cx 40,cx 34,ry 41,cx 48,cx 38,ry 37,cx 42,cx 46,cx 44
sum,0.734107,0.728477,0.72753,0.727055,0.725727,0.723379,0.721829,0.721528,0.718217,0.717642,...,0.692746,0.691233,0.69114,0.685222,0.683173,0.682513,0.681827,0.679422,0.67101,0.670401

DSTAR SCORES

,cx 48,cx 42,cx 44,cx 36,cx 39,cx 26,cx 34,cx 35,cx 40,cx 32,...,ry 43,ry 6,ry 1,ry 12,ry 14,ry 10,ry 21,ry 3,ry 47,ry 30
sum,1.304667,1.274249,0.990387,0.748159,0.584928,0.51627,0.50493,0.474637,0.464295,0.396213,...,0.00732,0.006341,0.003451,0.002925,0.002571,0.000415,0.000056,0.000036,0.000019,3.335233e-13

ERROR GATE LOCATION:
27
Now evolving the following mutant:  AddGate_y_inGap_36_.qasm

100%|██████████| 10/10 [04:18<00:00, 25.89s/it]
100%|██████████| 10/10 [04:01<00:00, 24.17s/it]

,ry 50,ry 49,cx 48,ry 47,cx 46,ry 45,cx 44,ry 43,cx 42,ry 41,...,cx 8,cx 7,ry 6,cx 5,cx 4,ry 3,cx 2,ry 1,ry 0,pass/fail
0,0.031035,0.079405,0.473739,0.001346,0.210105,0.048634,0.361864,0.030300,0.445758,0.085216,...,0.057789,0.064363,0.015868,0.050781,0.056850,0.001126,0.054823,0.010886,0.016215,fail
1,0.045744,0.079796,0.525892,0.000934,0.286293,0.046858,0.448892,0.036553,0.551062,0.089351,...,0.104455,0.120126,0.027681,0.090404,0.102754,0.002008,0.108920,0.021723,0.032926,fail
2,0.031959,0.085717,0.493294,0.001609,0.198399,0.035432,0.369364,0.018295,0.426157,0.085692,...,0.049579,0.054993,0.013737,0.043615,0.050085,0.000949,0.047374,0.008581,0.013028,fail
3,0.040181,0.060565,0.413569,0.001262,0.202398,0.047777,0.368151,0.033365,0.443479,0.077980,...,0.110169,0.128784,0.030148,0.093939,0.107877,0.002193,0.117709,0.024144,0.034308,fail
4,0.029410,0.079787,0.486085,0.001384,0.161828,0.049591,0.323637,0.024008,0.378767,0.078646,...,0.063737,0.072115,0.017297,0.059111,0.062205,0.001216,0.064516,0.012211,0.018004,fail
5,0.050301,0.072598,0.502097,0.001444,0.271725,0.052618,0.483180,0.040212,0.583178,0.101134,...,0.129527,0.148773,0.036271,0.113389,0.127669,0.002580,0.136978,0.027693,0.040483,fail
6,0.038404,0.076389,0.479918,0.001124,0.201798,0.037337,0.392064,0.029150,0.445395,0.084927,...,0.098756,0.116125,0.027680,0.084885,0.098622,0.001982,0.108517,0.022078,0.031488,fail
7,0.034154,0.068655,0.439801,0.001561,0.195620,0.050496,0.359810,0.026903,0.373316,0.084843,...,0.089572,0.101749,0.024998,0.078540,0.088514,0.001778,0.094901,0.019012,0.027098,fail
8,0.033718,0.063931,0.436134,0.000894,0.220980,0.037666,0.388927,0.030547,0.466062,0.079965,...,0.080892,0.095734,0.022211,0.071239,0.080921,0.001578,0.088652,0.017827,0.026203,fail
9,0.035051,0.057680,0.424657,0.001049,0.218465,0.036451,0.406010,0.025221,0.425033,0.085802,...,0.081435,0.092650,0.021440,0.072227,0.078700,0.001457,0.087867,0.016654,0.024921,fail
10,0.018620,0.058158,0.324394,0.000859,0.115015,0.019539,0.188669,0.022861,0.185015,0.053956,...,0.046965,0.054059,0.011608,0.038713,0.046665,0.000851,0.047898,0.009146,0.013900,pass
11,0.028961,0.056214,0.370868,0.001459,0.132996,0.023257,0.319204,0.018996,0.336667,0.069290,...,0.074281,0.088798,0.020439,0.063446,0.073687,0.001448,0.080644,0.015980,0.022277,pass
12,0.013293,0.054374,0.310360,0.000824,0.062701,0.037960,0.160453,0.018835,0.181372,0.061476,...,0.032546,0.036856,0.009990,0.029540,0.033932,0.000682,0.033706,0.006843,0.010089,pass
13,0.020636,0.058359,0.331310,0.000753,0.112398,0.030565,0.220138,0.017685,0.251101,0.056550,...,0.043890,0.049518,0.012263,0.037091,0.042132,0.000887,0.043802,0.009020,0.013538,pass
14,0.023832,0.046736,0.344204,0.001008,0.113040,0.034535,0.268375,0.019864,0.294707,0.061392,...,0.063558,0.073577,0.016886,0.055423,0.060084,0.001199,0.064803,0.013022,0.019523,pass
15,0.024600,0.048221,0.293528,0.000662,0.149740,0.034053,0.290990,0.017021,0.327177,0.055385,...,0.044697,0.047469,0.011626,0.039078,0.040235,0.000817,0.039748,0.007798,0.011455,pass
16,0.035016,0.067769,0.430294,0.001118,0.198407,0.019319,0.374076,0.019247,0.431227,0.066761,...,0.071318,0.084271,0.018730,0.063028,0.070201,0.001329,0.077641,0.014558,0.020847,pass
17,0.016933,0.035802,0.250388,0.000432,0.090839,0.022231,0.184031,0.012324,0.202440,0.041099,...,0.036768,0.041947,0.009287,0.031536,0.034401,0.000627,0.037321,0.007067,0.010128,pass
18,0.030575,0.062434,0.380796,0.001254,0.136201,0.047034,0.311905,0.031204,0.349124,0.073141,...,0.095663,0.111097,0.026812,0.083552,0.093328,0.001920,0.103230,0.021034,0.029577,pass
19,0.033102,0.048942,0.305065,0.000693,0.201139,0.042039,0.316479,0.022912,0.398081,0.061562,...,0.066093,0.071915,0.017343,0.059253,0.064210,0.001205,0.064540,0.012355,0.019705,pass

[[1.35964592 1.18307647 1.12485843 1.27582626 1.32077686 1.18813576
  1.23832111 1.36520076 1.28504001 1.18485159 1.40988121 1.33463174
  1.33153502 1.32065478 1.32789317 1.30233972 1.42031802 1.44337452
  1.39361697 1.41229701 1.40296672 1.39162572 1.43901025 1.44736275
  1.38391156 1.45397358 1.46947618 1.49947027 1.44692554 1.48924643
  1.46887546 1.48411598 1.45249748 1.52864342 1.4704039  1.45974136
  1.52148814 1.48118561 1.50179632 1.4820368  1.51532097 1.48478732
  1.49585019 1.49459051 1.52828497 1.49563583 1.49461153 1.5293724
  1.50483095 1.53165516 1.52953125]]
BARINEL SCORES

,cx 46,ry 1,ry 0,ry 3,ry 27,cx 38,cx 42,cx 2,ry 10,ry 6,...,ry 25,cx 30,ry 45,cx 26,ry 41,cx 34,cx 48,ry 47,ry 49,cx 33
sum,0.622861,0.607488,0.607451,0.606046,0.605807,0.605639,0.605488,0.605389,0.605386,0.604946,...,0.591585,0.590055,0.587821,0.5877,0.586972,0.585504,0.583203,0.581863,0.57432,0.573676

custom SCORES

,ry 1,ry 0,ry 3,ry 6,ry 10,cx 2,ry 17,cx 4,cx 46,ry 14,...,cx 36,cx 26,y 35,cx 44,cx 33,ry 47,ry 45,ry 41,cx 48,ry 49
sum,0.840104,0.83973,0.837764,0.836079,0.834724,0.833142,0.832229,0.830367,0.828526,0.827983,...,0.793226,0.791032,0.784563,0.781774,0.780684,0.767452,0.762424,0.760841,0.747209,0.744186

DSTAR SCORES

,cx 48,cx 42,cx 44,cx 36,cx 39,cx 40,cx 38,cx 34,cx 26,cx 33,...,ry 0,ry 6,ry 1,ry 12,ry 14,ry 10,ry 21,ry 3,ry 47,ry 29
sum,1.638335,1.589524,1.205036,0.832863,0.682456,0.524395,0.500071,0.479473,0.463899,0.459543,...,0.006887,0.005547,0.003231,0.002871,0.002222,0.000373,0.00005,0.000028,0.000016,3.401358e-13

ERROR GATE LOCATION:
35
Now evolving the following mutant:  AddGate_h_inGap_43_.qasm

100%|██████████| 10/10 [04:45<00:00, 28.52s/it]
100%|██████████| 10/10 [04:34<00:00, 27.41s/it]

,ry 50,ry 49,cx 48,ry 47,cx 46,ry 45,cx 44,ry 43,h 42,cx 41,...,cx 8,cx 7,ry 6,cx 5,cx 4,ry 3,cx 2,ry 1,ry 0,pass/fail
0,0.033527,0.062708,0.426572,0.001332,0.214874,0.042080,0.365949,0.028670,0.087379,0.491395,...,0.137154,0.161211,0.035907,0.122362,0.137799,0.002564,0.158499,0.030701,0.045189,fail
1,0.041853,0.074738,0.489526,0.001966,0.175714,0.048500,0.406116,0.039284,0.117858,0.508591,...,0.195600,0.236849,0.057402,0.168614,0.205816,0.004154,0.230899,0.047712,0.070083,fail
2,0.035370,0.067261,0.419973,0.000730,0.233839,0.035464,0.381517,0.024707,0.075134,0.498011,...,0.128339,0.150658,0.031800,0.109996,0.125591,0.002362,0.143118,0.027649,0.043095,fail
3,0.031713,0.047457,0.322554,0.000931,0.130700,0.036477,0.313071,0.026677,0.079995,0.393516,...,0.148603,0.176437,0.038585,0.122269,0.146741,0.002889,0.165862,0.033963,0.050771,fail
4,0.034316,0.076612,0.442241,0.001143,0.159437,0.045315,0.301804,0.031856,0.095413,0.393531,...,0.150867,0.181045,0.041267,0.126249,0.154059,0.003044,0.174225,0.035349,0.052269,fail
5,0.031462,0.066891,0.421718,0.001455,0.167748,0.050317,0.327523,0.019235,0.056953,0.426087,...,0.111463,0.128515,0.027462,0.092351,0.105750,0.001935,0.122401,0.023707,0.032395,fail
6,0.039748,0.075147,0.428975,0.001572,0.185983,0.045902,0.338039,0.038310,0.115539,0.431556,...,0.192175,0.233466,0.055033,0.161815,0.204576,0.004081,0.226523,0.047396,0.070552,fail
7,0.036035,0.059160,0.370494,0.001027,0.158660,0.040265,0.357261,0.031222,0.094074,0.431811,...,0.161814,0.194690,0.045174,0.140992,0.164235,0.003279,0.191192,0.038091,0.057146,fail
8,0.040362,0.085341,0.495770,0.001435,0.297430,0.054823,0.432903,0.034781,0.106178,0.590674,...,0.128883,0.147323,0.035322,0.117311,0.134746,0.002584,0.139085,0.027016,0.043599,fail
9,0.034363,0.063371,0.470853,0.001213,0.178501,0.042589,0.409882,0.029243,0.088431,0.523352,...,0.159892,0.193594,0.043179,0.137561,0.161665,0.003192,0.185622,0.038093,0.056576,fail
10,0.030061,0.048537,0.318156,0.001264,0.180436,0.037240,0.311737,0.024416,0.075121,0.375585,...,0.126895,0.147614,0.034395,0.111846,0.128988,0.002604,0.135944,0.027935,0.044664,pass
11,0.037254,0.069176,0.455706,0.001386,0.198889,0.049529,0.353748,0.023184,0.069386,0.488017,...,0.135686,0.157938,0.035467,0.114308,0.132512,0.002557,0.150154,0.029771,0.042456,pass
12,0.023195,0.058978,0.352572,0.001018,0.122893,0.042726,0.255968,0.027893,0.085849,0.324817,...,0.099436,0.116529,0.026749,0.091304,0.102569,0.001976,0.108222,0.021137,0.034557,pass
13,0.028987,0.064555,0.411922,0.001056,0.126335,0.049557,0.285208,0.028305,0.087215,0.343582,...,0.147255,0.173438,0.040392,0.131591,0.147956,0.003070,0.163101,0.033586,0.053642,pass
14,0.037494,0.044491,0.327405,0.000899,0.209420,0.036268,0.386684,0.025604,0.078074,0.481526,...,0.132655,0.152913,0.036060,0.116722,0.133318,0.002641,0.141586,0.028022,0.045190,pass
15,0.020114,0.048460,0.326773,0.001078,0.098376,0.030985,0.190052,0.017098,0.050782,0.251302,...,0.103777,0.123322,0.026020,0.086690,0.099898,0.001875,0.121887,0.023985,0.032695,pass
16,0.035856,0.064797,0.392354,0.001068,0.188174,0.047893,0.371699,0.023940,0.072110,0.472474,...,0.111940,0.130399,0.033199,0.096606,0.117453,0.002486,0.117050,0.025072,0.040389,pass
17,0.029767,0.064956,0.357834,0.001157,0.174693,0.054525,0.283091,0.030659,0.093617,0.388339,...,0.112881,0.127064,0.030872,0.105280,0.113975,0.002255,0.120746,0.023356,0.038060,pass
18,0.037496,0.071498,0.429294,0.001209,0.220350,0.046746,0.363769,0.030232,0.093280,0.450869,...,0.146058,0.170922,0.039310,0.128885,0.149743,0.002987,0.157123,0.032031,0.053000,pass
19,0.030715,0.063482,0.375791,0.001149,0.166685,0.039234,0.339693,0.025689,0.078939,0.399087,...,0.119631,0.142900,0.032382,0.109167,0.120634,0.002329,0.138011,0.026926,0.039873,pass

[[1.16664629 1.25744011 1.15599706 1.53561338 1.56304952 1.24108546
  1.19123641 1.29231028 1.28532222 1.25982936 1.24999274 1.25074068
  1.14226926 1.24396103 1.31814167 1.14285836 1.31248855 1.38183384
  1.1776199  1.27002484 1.28203385 1.29433022 1.31187358 1.32907423
  1.24048828 1.36848249 1.38565387 1.3823431  1.36442926 1.37270771
  1.32489562 1.35405206 1.34981734 1.38109676 1.336322   1.31364548
  1.38035311 1.31585049 1.24919066 1.3463693  1.40831988 1.29860085
  1.29126925 1.31306641 1.39619131 1.29751049 1.33562124 1.38099192
  1.32896962 1.36444477 1.35240492]]
BARINEL SCORES

,ry 17,ry 1,cx 2,cx 18,ry 27,cx 7,cx 22,cx 4,cx 11,cx 13,...,cx 35,cx 48,cx 31,ry 47,ry 49,cx 46,cx 38,ry 32,ry 29,ry 45
sum,0.567518,0.562636,0.562046,0.559608,0.557734,0.555554,0.553809,0.552713,0.551834,0.551547,...,0.534656,0.533651,0.531664,0.531537,0.531213,0.530179,0.529691,0.522352,0.520839,0.504009

custom SCORES

,ry 17,ry 1,cx 2,cx 18,ry 6,ry 27,cx 22,ry 10,cx 7,ry 0,...,cx 31,ry 49,cx 44,ry 50,ry 29,cx 48,cx 35,cx 38,ry 32,ry 45
sum,0.763467,0.754557,0.748782,0.74845,0.743502,0.743051,0.742717,0.740851,0.737924,0.737744,...,0.700471,0.698205,0.696063,0.691938,0.689373,0.687876,0.687415,0.680953,0.676135,0.660389

DSTAR SCORES

,cx 41,cx 48,cx 44,cx 35,cx 33,cx 26,cx 34,cx 38,cx 37,cx 28,...,ry 1,ry 32,ry 12,ry 43,ry 14,ry 10,ry 21,ry 3,ry 47,ry 29
sum,1.572903,1.337868,1.004929,0.847454,0.730399,0.717829,0.57945,0.571699,0.567794,0.523984,...,0.011904,0.010532,0.009995,0.009009,0.005493,0.001043,0.000097,0.00009,0.000016,6.493986e-13

ERROR GATE LOCATION:
42
Now evolving the following mutant:  AddGate_ry_inGap_53_.qasm

100%|██████████| 10/10 [04:28<00:00, 26.84s/it]
100%|██████████| 10/10 [04:04<00:00, 24.42s/it]

,ry 50,ry 49,cx 48,ry 47,ry 46,cx 45,ry 44,cx 43,ry 42,cx 41,...,cx 8,cx 7,ry 6,cx 5,cx 4,ry 3,cx 2,ry 1,ry 0,pass/fail
0,0.032770,0.051488,0.333195,0.102646,0.003965,0.466928,0.063904,0.402125,0.034687,0.480723,...,0.049388,0.050600,0.014012,0.042854,0.049084,0.000925,0.044971,0.008025,0.014192,fail
1,0.032189,0.062601,0.399995,0.121470,0.004558,0.490392,0.065770,0.356000,0.052227,0.402433,...,0.059723,0.063909,0.017131,0.051314,0.060335,0.001165,0.057198,0.011126,0.019023,fail
2,0.028020,0.051458,0.340419,0.113453,0.004217,0.447370,0.054420,0.271570,0.049360,0.339754,...,0.058203,0.061895,0.015588,0.051689,0.056168,0.001058,0.055078,0.010243,0.017861,fail
3,0.039415,0.070173,0.449924,0.120148,0.004207,0.503564,0.065036,0.447237,0.038418,0.515445,...,0.063936,0.067170,0.015889,0.055092,0.060704,0.001073,0.059384,0.010646,0.018301,fail
4,0.040187,0.068276,0.415562,0.125398,0.004817,0.497897,0.074963,0.374246,0.046575,0.458680,...,0.072335,0.074370,0.020248,0.063816,0.070101,0.001348,0.067720,0.012621,0.021794,fail
5,0.040310,0.070341,0.440006,0.121373,0.004450,0.499849,0.083813,0.411131,0.041060,0.525485,...,0.067644,0.067305,0.018731,0.057177,0.063977,0.001217,0.058268,0.011048,0.018175,fail
6,0.021779,0.060363,0.339258,0.153032,0.005373,0.416987,0.066871,0.224241,0.046905,0.246381,...,0.046861,0.048740,0.015038,0.040720,0.046470,0.000960,0.044129,0.008769,0.014858,fail
7,0.036603,0.068299,0.434146,0.143758,0.005165,0.520748,0.069300,0.372952,0.029078,0.466548,...,0.054151,0.054050,0.015376,0.045870,0.051995,0.000974,0.047370,0.009099,0.014777,fail
8,0.028853,0.064063,0.372854,0.135867,0.005025,0.461726,0.075618,0.311476,0.037349,0.349891,...,0.048608,0.048957,0.013508,0.040710,0.047369,0.000878,0.042002,0.007864,0.013510,fail
9,0.028192,0.069071,0.407161,0.119869,0.004002,0.392104,0.061410,0.304512,0.043639,0.351063,...,0.062238,0.064279,0.015660,0.053800,0.057180,0.001078,0.057422,0.010334,0.018065,fail
10,0.019941,0.041600,0.242783,0.089006,0.003043,0.273951,0.042944,0.197966,0.032122,0.246940,...,0.040235,0.041068,0.011971,0.034480,0.038715,0.000761,0.036280,0.007168,0.011830,pass
11,0.028440,0.061522,0.375916,0.068108,0.002491,0.368535,0.048443,0.321596,0.030046,0.363546,...,0.048178,0.050634,0.011042,0.043139,0.044178,0.000769,0.044645,0.007665,0.013198,pass
12,0.040930,0.076124,0.457118,0.112152,0.003630,0.415811,0.066574,0.450904,0.031719,0.515823,...,0.067280,0.067778,0.018510,0.060011,0.063505,0.001215,0.062178,0.011301,0.019509,pass
13,0.033629,0.085833,0.452083,0.167011,0.005429,0.436184,0.075377,0.340526,0.048798,0.412681,...,0.056071,0.056756,0.017285,0.048355,0.053766,0.001081,0.050353,0.009905,0.016312,pass
14,0.032795,0.067293,0.457091,0.121983,0.004172,0.434007,0.051590,0.352212,0.034501,0.438499,...,0.045269,0.047411,0.012276,0.040514,0.042080,0.000780,0.041284,0.007602,0.012884,pass
15,0.033709,0.054886,0.409895,0.086364,0.003530,0.437910,0.043610,0.349963,0.031805,0.399618,...,0.052514,0.056253,0.013428,0.047635,0.050611,0.000880,0.050297,0.008849,0.015248,pass
16,0.031402,0.052573,0.357318,0.114009,0.003940,0.423927,0.067187,0.369240,0.041780,0.383399,...,0.060425,0.062735,0.016460,0.051615,0.058193,0.001105,0.056266,0.010746,0.017897,pass
17,0.021384,0.045795,0.278854,0.104265,0.003486,0.319022,0.055596,0.277910,0.023411,0.307973,...,0.032313,0.032215,0.009779,0.027990,0.030702,0.000602,0.027864,0.005347,0.008793,pass
18,0.031838,0.057066,0.340586,0.074311,0.002709,0.314147,0.045597,0.318975,0.022391,0.342275,...,0.048330,0.049132,0.012659,0.039862,0.045059,0.000824,0.042807,0.008266,0.013328,pass
19,0.031859,0.053564,0.342984,0.130538,0.004503,0.442198,0.061518,0.367423,0.049862,0.425697,...,0.059615,0.062396,0.017245,0.052691,0.058054,0.001129,0.057303,0.010656,0.018588,pass

[[1.22776397 1.10576189 1.14411111 1.21742555 1.17362149 1.1085499
  1.23055173 1.28683085 1.24558506 1.27039168 1.07033202 1.15796988
  1.19579388 1.14872747 1.12867715 1.2082971  1.35883959 1.11802151
  1.20442062 1.18730914 1.18464542 1.18739828 1.16478997 1.16863352
  1.19840324 1.17267224 1.17396815 1.20066882 1.16981351 1.20701634
  1.19681553 1.23674099 1.19676749 1.18576607 1.22467863 1.21004875
  1.19658681 1.23697375 1.21218852 1.23640261 1.26552392 1.2613686
  1.24055285 1.23687135 1.25624089 1.26861059 1.24429036 1.26269717
  1.26924885 1.26497346 1.27783848]]
BARINEL SCORES

,ry 46,ry 44,cx 45,ry 42,ry 47,ry 40,ry 12,ry 32,ry 3,ry 36,...,cx 19,cx 34,cx 37,ry 29,cx 41,cx 23,ry 50,ry 49,cx 48,cx 43
sum,0.553484,0.549481,0.548572,0.547577,0.540707,0.540129,0.539126,0.538881,0.538575,0.538146,...,0.524959,0.52426,0.522971,0.519001,0.518811,0.518273,0.517654,0.516178,0.514247,0.509438

custom SCORES

,ry 44,ry 42,ry 46,ry 3,ry 0,ry 47,cx 4,cx 9,ry 10,ry 12,...,cx 20,cx 41,cx 33,ry 50,cx 23,cx 43,cx 37,ry 29,cx 48,ry 49
sum,0.718523,0.718091,0.715879,0.70859,0.707361,0.705274,0.70464,0.704005,0.703877,0.702506,...,0.684047,0.683584,0.680536,0.676543,0.673842,0.673328,0.673158,0.673066,0.661336,0.658871

DSTAR SCORES

,cx 45,cx 41,cx 48,cx 39,cx 43,cx 35,cx 38,cx 37,cx 31,cx 26,...,ry 17,ry 0,ry 6,ry 14,ry 1,ry 46,ry 10,ry 21,ry 3,ry 29
sum,1.59149,1.236576,1.127607,0.943299,0.905019,0.86558,0.718908,0.51181,0.2709,0.234638,...,0.003325,0.002867,0.002562,0.001215,0.000987,0.000209,0.000198,0.000023,0.000011,2.614139e-13

ERROR GATE LOCATION:
47
Now evolving the following mutant:  AddGate_x_inGap_26_.qasm

100%|██████████| 10/10 [04:22<00:00, 26.27s/it]
100%|██████████| 10/10 [04:09<00:00, 24.95s/it]

,ry 50,ry 49,cx 48,ry 47,cx 46,ry 45,cx 44,ry 43,cx 42,ry 41,...,cx 8,cx 7,ry 6,cx 5,cx 4,ry 3,cx 2,ry 1,ry 0,pass/fail
0,0.029816,0.043544,0.340772,0.000850,0.167091,0.024761,0.336315,0.020595,0.373151,0.066623,...,0.084326,0.098685,0.022142,0.071830,0.079454,0.001586,0.090922,0.018401,0.026069,fail
1,0.027075,0.058465,0.400689,0.001392,0.141433,0.054011,0.337420,0.029122,0.367540,0.084054,...,0.080057,0.091855,0.022363,0.071231,0.076613,0.001595,0.082430,0.016874,0.024773,fail
2,0.032129,0.088418,0.527302,0.001725,0.179241,0.034832,0.342213,0.025339,0.382741,0.084686,...,0.082325,0.100729,0.022937,0.069246,0.084987,0.001675,0.093192,0.018884,0.026465,fail
3,0.023908,0.050901,0.346146,0.000712,0.157972,0.027478,0.308186,0.020882,0.319172,0.066386,...,0.058895,0.069967,0.015879,0.051188,0.059103,0.001130,0.066338,0.012961,0.018214,fail
4,0.033916,0.057672,0.370147,0.000652,0.199663,0.039588,0.367322,0.031979,0.428089,0.077269,...,0.078522,0.089435,0.021407,0.067761,0.076150,0.001513,0.082360,0.016510,0.023974,fail
5,0.035243,0.072697,0.441240,0.001453,0.219950,0.047911,0.343598,0.026875,0.396620,0.075696,...,0.085682,0.095153,0.021362,0.074182,0.080958,0.001519,0.086497,0.016569,0.024486,fail
6,0.034947,0.065486,0.432694,0.001448,0.231422,0.047226,0.407951,0.027827,0.473751,0.082113,...,0.083310,0.095090,0.022299,0.071823,0.081573,0.001582,0.084042,0.016859,0.025270,fail
7,0.038792,0.075503,0.470546,0.001437,0.218810,0.049636,0.409427,0.027400,0.480751,0.085668,...,0.091902,0.106039,0.025246,0.079743,0.090058,0.001799,0.096307,0.019314,0.027648,fail
8,0.035277,0.058061,0.417359,0.000914,0.195796,0.053417,0.349414,0.034990,0.407858,0.081562,...,0.100754,0.114104,0.026858,0.087379,0.095688,0.001951,0.101067,0.020800,0.031486,fail
9,0.041127,0.066130,0.454793,0.001309,0.210814,0.056482,0.438353,0.034059,0.479099,0.096133,...,0.108954,0.126578,0.030539,0.095832,0.107789,0.002171,0.116916,0.023591,0.034281,fail
10,0.037023,0.086481,0.472316,0.001176,0.186208,0.058889,0.310875,0.037944,0.395251,0.082644,...,0.097961,0.111615,0.027717,0.083968,0.097289,0.002011,0.101212,0.020922,0.030866,pass
11,0.037285,0.070910,0.423783,0.001253,0.225410,0.039468,0.354103,0.035929,0.437864,0.073191,...,0.093503,0.108929,0.026528,0.081163,0.096266,0.001944,0.098306,0.020389,0.030309,pass
12,0.024936,0.056279,0.371938,0.000996,0.112979,0.023644,0.280164,0.021861,0.331666,0.062840,...,0.062692,0.075476,0.017995,0.054538,0.063052,0.001290,0.067623,0.013740,0.019800,pass
13,0.032817,0.070634,0.454051,0.000837,0.184333,0.048756,0.365880,0.031609,0.413636,0.083499,...,0.071125,0.079197,0.019220,0.064478,0.068626,0.001346,0.069859,0.013427,0.020976,pass
14,0.032484,0.085068,0.496506,0.001498,0.170385,0.046237,0.340627,0.032432,0.344093,0.080008,...,0.098697,0.116365,0.026927,0.084979,0.098367,0.001953,0.108643,0.021916,0.031762,pass
15,0.040700,0.063393,0.431285,0.001478,0.204160,0.030931,0.444017,0.023580,0.538038,0.081188,...,0.099643,0.118022,0.027974,0.086426,0.098815,0.001967,0.107264,0.021665,0.030432,pass
16,0.020710,0.048326,0.295501,0.000591,0.127208,0.032026,0.231000,0.024532,0.212687,0.059129,...,0.050837,0.055419,0.013050,0.045051,0.048136,0.000931,0.050373,0.009617,0.015704,pass
17,0.021864,0.054174,0.333821,0.001162,0.121052,0.039003,0.277398,0.020040,0.309758,0.072434,...,0.054774,0.065117,0.014798,0.044098,0.053469,0.001062,0.057329,0.011925,0.016684,pass
18,0.028150,0.041340,0.325634,0.000681,0.166578,0.029465,0.337947,0.019886,0.457016,0.068387,...,0.058352,0.069020,0.016991,0.050486,0.058240,0.001179,0.060455,0.012604,0.017729,pass
19,0.025737,0.044941,0.322767,0.000804,0.169617,0.034116,0.282092,0.026581,0.322435,0.071185,...,0.063569,0.072234,0.016652,0.056212,0.062406,0.001185,0.066525,0.012909,0.019654,pass

[[1.23789817 1.38830337 1.25497528 1.45094205 1.20395099 1.29742564
  1.2042001  1.25381438 1.17006023 1.2013811  1.26634021 1.27246204
  1.22425234 1.29739626 1.20101319 1.29279171 1.30811945 1.28555554
  1.26488198 1.29300909 1.2993922  1.25855996 1.32464807 1.23936639
  1.2931857  1.25218548 1.33878333 1.33729679 1.34419488 1.28882839
  1.30497089 1.30775808 1.32381739 1.3160198  1.31025647 1.2934937
  1.29821143 1.3156208  1.2922648  1.31481998 1.32997106 1.28955059
  1.27472836 1.2816242  1.32186906 1.2946533  1.29495895 1.31413125
  1.29896693 1.30508578 1.30510843]]
BARINEL SCORES

,cx 46,cx 2,ry 45,cx 8,cx 5,ry 1,ry 47,cx 7,cx 23,cx 44,...,cx 42,cx 27,cx 32,ry 41,cx 34,ry 26,cx 48,ry 30,ry 49,ry 43
sum,0.535411,0.533325,0.532283,0.532249,0.531911,0.531848,0.531601,0.531264,0.530365,0.530309,...,0.522,0.521775,0.521586,0.5214,0.519818,0.519583,0.516858,0.51662,0.506092,0.504221

custom SCORES

,ry 47,cx 23,cx 2,ry 1,ry 45,cx 5,cx 13,cx 22,cx 8,ry 0,...,cx 32,ry 50,ry 30,cx 27,ry 49,cx 36,cx 48,ry 41,cx 42,ry 43
sum,0.724431,0.707679,0.706518,0.705375,0.704932,0.704071,0.703787,0.702643,0.701867,0.701533,...,0.686523,0.686261,0.684442,0.683442,0.681744,0.680104,0.679019,0.678,0.674692,0.662271

DSTAR SCORES

,cx 48,cx 42,cx 44,cx 36,cx 39,cx 40,cx 34,cx 35,cx 38,cx 27,...,ry 0,ry 6,ry 1,ry 12,ry 14,ry 10,ry 21,ry 3,ry 47,ry 30
sum,1.267569,1.226672,1.002037,0.663179,0.53612,0.439897,0.430605,0.419972,0.406187,0.398872,...,0.006742,0.005229,0.003216,0.002582,0.002086,0.000338,0.000046,0.000027,0.000014,2.979411e-13

ERROR GATE LOCATION:
25
Now evolving the following mutant:  AddGate_x_inGap_34_.qasm

100%|██████████| 10/10 [03:54<00:00, 23.45s/it]
100%|██████████| 10/10 [03:56<00:00, 23.60s/it]

,ry 50,ry 49,cx 48,ry 47,cx 46,ry 45,cx 44,ry 43,cx 42,ry 41,...,cx 8,cx 7,ry 6,cx 5,cx 4,ry 3,cx 2,ry 1,ry 0,pass/fail
0,0.031705,0.058627,0.389704,0.001813,0.148053,0.037155,0.348985,0.027549,0.372149,0.078825,...,0.088283,0.100983,0.023297,0.076465,0.083517,0.001671,0.088553,0.017505,0.025824,fail
1,0.038390,0.075562,0.445329,0.001430,0.212471,0.054769,0.412866,0.030172,0.470186,0.086758,...,0.091889,0.104628,0.025742,0.081264,0.090371,0.001831,0.097044,0.019342,0.027536,fail
2,0.035550,0.072445,0.457087,0.001766,0.220992,0.043951,0.384892,0.029233,0.483138,0.089236,...,0.082404,0.095607,0.023411,0.070365,0.085025,0.001678,0.084528,0.017470,0.025547,fail
3,0.031953,0.085767,0.503578,0.001572,0.195373,0.036291,0.414573,0.021706,0.461892,0.084522,...,0.050431,0.058271,0.013866,0.044306,0.051226,0.000969,0.048407,0.008865,0.013125,fail
4,0.028192,0.088241,0.498648,0.001508,0.163994,0.046317,0.335555,0.017730,0.354589,0.071989,...,0.051753,0.056394,0.013988,0.047736,0.048782,0.001006,0.049168,0.009058,0.013719,fail
5,0.031264,0.081182,0.442575,0.001687,0.153465,0.039106,0.298834,0.029991,0.333313,0.074510,...,0.081564,0.095051,0.023082,0.071176,0.082873,0.001706,0.084157,0.017173,0.025014,fail
6,0.040305,0.067299,0.453363,0.001568,0.262631,0.040379,0.469894,0.013935,0.536815,0.078164,...,0.077270,0.086269,0.018355,0.068118,0.069638,0.001293,0.076847,0.013992,0.019710,fail
7,0.035720,0.071768,0.436253,0.001465,0.209606,0.038102,0.403806,0.015357,0.493674,0.076118,...,0.056390,0.062340,0.015612,0.049940,0.054696,0.001081,0.052856,0.009996,0.014663,fail
8,0.038231,0.050856,0.385590,0.001393,0.215645,0.041491,0.434689,0.020546,0.474880,0.080674,...,0.083446,0.095095,0.022811,0.076413,0.081217,0.001570,0.088164,0.016576,0.024036,fail
9,0.035943,0.069652,0.454456,0.001660,0.189912,0.045748,0.356479,0.033904,0.444540,0.087635,...,0.103543,0.122975,0.029483,0.089071,0.104828,0.002142,0.112095,0.023201,0.032582,fail
10,0.024164,0.068436,0.407844,0.000835,0.164198,0.023972,0.243709,0.013796,0.274360,0.056961,...,0.038753,0.041270,0.008321,0.033472,0.034793,0.000584,0.034556,0.005917,0.009696,pass
11,0.037302,0.055954,0.374291,0.001272,0.231361,0.030370,0.402742,0.021626,0.478493,0.069618,...,0.088429,0.102284,0.023027,0.076056,0.085185,0.001670,0.092184,0.018138,0.026724,pass
12,0.034888,0.070440,0.425046,0.001270,0.194006,0.026060,0.327122,0.025999,0.405838,0.066957,...,0.081242,0.094985,0.022217,0.071358,0.081969,0.001597,0.086487,0.016950,0.024125,pass
13,0.027951,0.043812,0.297582,0.000985,0.097692,0.030713,0.304053,0.022974,0.357373,0.062442,...,0.081825,0.099255,0.024331,0.071683,0.083009,0.001726,0.091467,0.019007,0.026295,pass
14,0.039318,0.048475,0.367763,0.001425,0.214401,0.037659,0.408144,0.020648,0.479483,0.075345,...,0.096002,0.112576,0.026036,0.082109,0.094692,0.001850,0.101095,0.020311,0.028632,pass
15,0.025076,0.036619,0.274486,0.000460,0.155246,0.019131,0.297025,0.010689,0.339630,0.049751,...,0.046969,0.055125,0.011924,0.041700,0.045094,0.000801,0.052097,0.009590,0.013889,pass
16,0.029785,0.075543,0.456199,0.001492,0.215460,0.034387,0.362871,0.021832,0.464924,0.077985,...,0.047679,0.054471,0.013149,0.042805,0.049926,0.000899,0.046608,0.008785,0.013201,pass
17,0.035323,0.062259,0.378719,0.001253,0.191431,0.032406,0.347661,0.026476,0.416305,0.065338,...,0.086107,0.100028,0.022819,0.073275,0.083718,0.001630,0.090634,0.018094,0.025495,pass
18,0.026250,0.064764,0.388065,0.001555,0.160904,0.026684,0.300318,0.013540,0.346784,0.056667,...,0.047967,0.055327,0.011837,0.042957,0.047151,0.000863,0.045819,0.008188,0.012062,pass
19,0.013925,0.043334,0.243121,0.000338,0.079634,0.019413,0.162627,0.016930,0.146173,0.041003,...,0.034395,0.040369,0.008852,0.029496,0.033866,0.000630,0.038170,0.007206,0.010687,pass

[[1.16067404 1.22319417 1.12743565 1.14311876 1.33170514 1.29384111
  1.21716193 1.41196486 1.21309328 1.10381534 1.14435207 1.13106255
  1.11823126 1.15806172 1.13901926 1.14861917 1.20090189 1.16411414
  1.15381793 1.15186832 1.19540564 1.21687279 1.19477587 1.31696778
  1.16505557 1.22106993 1.19623339 1.21019489 1.23000843 1.24395019
  1.22298639 1.20204116 1.23047152 1.41977006 1.25896084 1.30974973
  1.32191084 1.28481263 1.22404887 1.3130339  1.36190364 1.34555344
  1.35002541 1.40124679 1.40630818 1.31985318 1.39366567 1.43313095
  1.43377234 1.51463994 1.46924854]]
BARINEL SCORES

,ry 45,ry 47,ry 41,ry 21,ry 25,x 33,ry 14,ry 37,cx 28,ry 49,...,cx 15,cx 4,ry 17,cx 9,ry 0,cx 7,ry 1,cx 46,cx 2,ry 29
sum,0.601202,0.593055,0.565139,0.563607,0.563246,0.562902,0.560623,0.559847,0.559724,0.558776,...,0.540818,0.540519,0.540066,0.539798,0.537511,0.537324,0.536782,0.536422,0.535149,0.529233

custom SCORES

,ry 45,ry 47,ry 43,ry 3,ry 14,ry 10,ry 6,ry 1,ry 21,ry 25,...,cx 42,cx 48,cx 39,cx 30,ry 32,ry 50,cx 40,cx 36,cx 38,ry 29
sum,0.795667,0.762539,0.747488,0.746505,0.745897,0.744211,0.741459,0.740039,0.738882,0.735187,...,0.708979,0.708632,0.706412,0.706163,0.701299,0.698672,0.697593,0.695705,0.693893,0.690235

DSTAR SCORES

,cx 48,cx 42,cx 44,cx 36,cx 39,cx 34,cx 26,cx 40,cx 35,cx 38,...,ry 0,ry 6,ry 1,ry 12,ry 14,ry 10,ry 21,ry 47,ry 3,ry 29
sum,1.465525,1.428381,1.132845,0.713563,0.553649,0.517535,0.487972,0.460719,0.456168,0.391792,...,0.004826,0.004321,0.002316,0.001973,0.001872,0.000305,0.000049,0.000025,0.000022,2.817854e-13

ERROR GATE LOCATION:
33
Now evolving the following mutant:  AddGate_y_inGap_31_.qasm

100%|██████████| 10/10 [04:07<00:00, 24.79s/it]
100%|██████████| 10/10 [04:09<00:00, 24.93s/it]

,ry 50,ry 49,cx 48,ry 47,cx 46,ry 45,cx 44,ry 43,cx 42,ry 41,...,cx 8,cx 7,ry 6,cx 5,cx 4,ry 3,cx 2,ry 1,ry 0,pass/fail
0,0.037149,0.064187,0.403503,0.001517,0.205090,0.044651,0.354862,0.036950,0.404285,0.079681,...,0.107923,0.125066,0.028903,0.093360,0.106535,0.002073,0.115151,0.022914,0.033522,fail
1,0.034049,0.058745,0.361760,0.001411,0.187418,0.038584,0.332859,0.034655,0.351879,0.069542,...,0.097530,0.112480,0.024770,0.084679,0.094158,0.001802,0.103349,0.019895,0.029259,fail
2,0.028882,0.079681,0.473362,0.001778,0.160929,0.048563,0.295082,0.036969,0.328148,0.088831,...,0.082646,0.094078,0.023427,0.074122,0.084191,0.001659,0.086568,0.017179,0.026396,fail
3,0.030030,0.044771,0.346321,0.001139,0.158779,0.033426,0.340628,0.029022,0.375050,0.078221,...,0.085845,0.102149,0.023649,0.075292,0.084906,0.001696,0.094973,0.018929,0.027898,fail
4,0.037715,0.071451,0.452586,0.000988,0.225174,0.028687,0.390036,0.022731,0.432687,0.067858,...,0.072342,0.081018,0.017144,0.063297,0.068205,0.001233,0.069052,0.012487,0.019725,fail
5,0.035682,0.069814,0.459740,0.001074,0.210054,0.031952,0.347163,0.027276,0.389652,0.078043,...,0.080388,0.091170,0.019916,0.068361,0.076878,0.001375,0.082471,0.015458,0.023207,fail
6,0.037282,0.053689,0.368117,0.001163,0.209370,0.022622,0.365370,0.019760,0.459343,0.060742,...,0.078807,0.091685,0.019921,0.065721,0.076527,0.001389,0.081807,0.015753,0.022216,fail
7,0.028803,0.076804,0.440851,0.001461,0.152027,0.035759,0.271321,0.033811,0.324640,0.076838,...,0.078315,0.092591,0.022271,0.068502,0.082857,0.001591,0.086096,0.017083,0.024853,fail
8,0.031560,0.065741,0.438735,0.001276,0.192977,0.041878,0.367009,0.021628,0.411799,0.087404,...,0.070738,0.080237,0.018786,0.059101,0.068635,0.001287,0.073001,0.014229,0.020183,fail
9,0.035936,0.072460,0.474948,0.001199,0.224688,0.049744,0.376079,0.039413,0.464229,0.088651,...,0.097621,0.114637,0.027266,0.084067,0.098703,0.001980,0.104954,0.021605,0.031449,fail
10,0.046976,0.066431,0.465603,0.001483,0.249112,0.039767,0.492031,0.026214,0.565985,0.090785,...,0.107851,0.124606,0.029144,0.095110,0.103976,0.002048,0.115536,0.022547,0.032643,pass
11,0.036570,0.067998,0.423553,0.001538,0.175578,0.053103,0.360295,0.038492,0.434257,0.086912,...,0.091992,0.106168,0.025937,0.084108,0.092535,0.001820,0.098446,0.019026,0.027867,pass
12,0.026276,0.058518,0.323082,0.001008,0.152834,0.037318,0.280774,0.023317,0.322056,0.061369,...,0.062238,0.072422,0.018121,0.054661,0.064651,0.001293,0.067727,0.013584,0.019517,pass
13,0.019910,0.040519,0.261968,0.000483,0.129508,0.024392,0.231652,0.008052,0.271976,0.043445,...,0.037987,0.043284,0.009461,0.031909,0.035087,0.000693,0.037441,0.007397,0.010895,pass
14,0.027373,0.061858,0.390103,0.000789,0.204540,0.031478,0.340130,0.026432,0.381273,0.071767,...,0.051988,0.059356,0.013248,0.045403,0.050907,0.000953,0.052840,0.010059,0.016015,pass
15,0.036709,0.071869,0.448057,0.001616,0.172651,0.050888,0.331947,0.033884,0.421468,0.082433,...,0.099683,0.116689,0.028328,0.086278,0.101303,0.002046,0.104041,0.021365,0.030693,pass
16,0.028582,0.059948,0.394879,0.000949,0.210260,0.024711,0.365218,0.017212,0.424303,0.071111,...,0.046915,0.052419,0.011840,0.042239,0.046043,0.000811,0.046220,0.008003,0.013042,pass
17,0.032619,0.074542,0.443862,0.000920,0.209717,0.047938,0.352050,0.030222,0.429823,0.080808,...,0.075949,0.087011,0.021255,0.064796,0.075337,0.001525,0.079812,0.016545,0.024179,pass
18,0.027091,0.055420,0.391118,0.000977,0.168189,0.040389,0.318253,0.022989,0.308860,0.078998,...,0.074208,0.083770,0.019099,0.064659,0.069558,0.001332,0.079503,0.015274,0.022840,pass
19,0.034977,0.082547,0.450338,0.001734,0.196723,0.045934,0.335222,0.025950,0.369959,0.070441,...,0.089876,0.104115,0.023686,0.075859,0.089518,0.001725,0.095565,0.018775,0.026934,pass

[[1.1188537  1.2121655  1.12548972 1.36706104 1.16881921 1.32346404
  1.13369159 1.30412033 1.17773551 1.14500439 1.14519527 1.12801612
  1.15945441 1.09690826 1.12095223 1.14294167 1.10663282 1.17503242
  1.20686496 1.16098988 1.12408663 1.20983986 1.21233348 1.26505229
  1.14685328 1.21815447 1.20882296 1.20632655 1.18114395 1.23432425
  1.20395935 1.26216401 1.1977909  1.30750962 1.22086778 1.20929443
  1.27682956 1.23139182 1.17086775 1.22678433 1.28752082 1.25112912
  1.26647054 1.26956066 1.27858511 1.26761587 1.26587239 1.2889851
  1.28312643 1.30537824 1.29573073]]
BARINEL SCORES

,y 30,ry 43,ry 12,cx 34,cx 9,cx 7,ry 33,cx 2,cx 4,cx 8,...,ry 37,ry 50,cx 48,cx 39,ry 41,cx 46,ry 49,cx 44,cx 42,ry 45
sum,0.54589,0.544551,0.544245,0.537413,0.536895,0.53686,0.536739,0.535917,0.535874,0.535663,...,0.516886,0.515291,0.513842,0.513129,0.512466,0.50756,0.506821,0.502398,0.500746,0.487008

custom SCORES

,ry 43,ry 47,ry 1,ry 0,cx 2,cx 7,cx 4,cx 8,cx 9,ry 12,...,ry 49,ry 50,ry 41,ry 37,cx 48,cx 39,cx 46,cx 42,ry 45,cx 44
sum,0.722091,0.712237,0.709575,0.708644,0.70783,0.707254,0.705461,0.705264,0.704827,0.703555,...,0.660409,0.659424,0.65916,0.658631,0.658423,0.657834,0.655872,0.648183,0.648143,0.644789

DSTAR SCORES

,cx 48,cx 42,cx 44,cx 36,cx 39,cx 34,cx 40,cx 26,cx 35,cx 38,...,ry 0,ry 6,ry 12,ry 1,ry 14,ry 10,ry 21,ry 3,ry 47,ry 29
sum,1.272659,1.115372,0.882816,0.677252,0.522359,0.475042,0.464518,0.43963,0.43769,0.398891,...,0.006546,0.00501,0.003056,0.003035,0.001923,0.000328,0.000042,0.000026,0.000017,3.375678e-13

ERROR GATE LOCATION:
30
Now evolving the following mutant:  AddGate_y_inGap_45_.qasm

100%|██████████| 10/10 [04:01<00:00, 24.18s/it]
100%|██████████| 10/10 [03:51<00:00, 23.12s/it]

,ry 50,ry 49,cx 48,ry 47,cx 46,ry 45,y 44,cx 43,ry 42,cx 41,...,cx 8,cx 7,ry 6,cx 5,cx 4,ry 3,cx 2,ry 1,ry 0,pass/fail
0,0.042359,0.075759,0.477953,0.001157,0.282846,0.055617,0.322951,0.450113,0.040096,0.530981,...,0.108572,0.122778,0.029224,0.093905,0.106925,0.002141,0.110564,0.022447,0.034280,fail
1,0.033569,0.063572,0.394121,0.001379,0.181633,0.044175,0.243683,0.356355,0.032125,0.367993,...,0.081836,0.091115,0.022657,0.074169,0.080655,0.001599,0.082452,0.016027,0.024871,fail
2,0.033072,0.082081,0.481848,0.001631,0.174887,0.051769,0.284494,0.336478,0.028248,0.373560,...,0.085004,0.095935,0.022510,0.073165,0.080846,0.001591,0.086609,0.017136,0.024164,fail
3,0.033006,0.074091,0.464033,0.001488,0.182442,0.054197,0.300421,0.340279,0.035810,0.399840,...,0.094320,0.108576,0.027420,0.081814,0.094508,0.002005,0.097672,0.020661,0.030447,fail
4,0.035614,0.088155,0.480976,0.001390,0.260114,0.043053,0.216379,0.403687,0.033088,0.479196,...,0.070344,0.078723,0.019075,0.060174,0.071918,0.001386,0.069274,0.013725,0.021004,fail
5,0.029881,0.072464,0.370769,0.001414,0.165045,0.048115,0.272794,0.283200,0.041617,0.319039,...,0.080113,0.091812,0.022553,0.069260,0.083208,0.001677,0.081042,0.016522,0.025173,fail
6,0.029939,0.070164,0.446496,0.001215,0.200594,0.047807,0.275059,0.356823,0.034891,0.431363,...,0.071812,0.083646,0.020324,0.062801,0.072913,0.001455,0.075642,0.015496,0.023191,fail
7,0.031497,0.038409,0.314833,0.000918,0.186711,0.028013,0.190068,0.341710,0.030484,0.362801,...,0.088861,0.104687,0.023509,0.076206,0.086990,0.001675,0.098900,0.019757,0.029280,fail
8,0.033696,0.077922,0.449550,0.001111,0.217252,0.047080,0.248799,0.351569,0.030478,0.429799,...,0.076479,0.086630,0.020507,0.064941,0.075585,0.001460,0.079401,0.015843,0.022953,fail
9,0.036405,0.092055,0.525693,0.001469,0.269390,0.056032,0.300096,0.408777,0.032953,0.504160,...,0.068488,0.074574,0.018129,0.057935,0.067487,0.001293,0.064067,0.012753,0.019375,fail
10,0.032985,0.067640,0.455170,0.001539,0.195927,0.030215,0.157367,0.349674,0.027012,0.353256,...,0.084052,0.097662,0.022203,0.075230,0.083397,0.001544,0.093940,0.017586,0.026020,pass
11,0.040577,0.067718,0.428370,0.001406,0.212097,0.041743,0.238250,0.414519,0.020664,0.486725,...,0.084667,0.095789,0.021679,0.074629,0.080046,0.001503,0.085280,0.015763,0.023028,pass
12,0.024898,0.063838,0.369512,0.001229,0.121945,0.048504,0.247849,0.283343,0.010360,0.321976,...,0.044797,0.046627,0.011886,0.041952,0.039274,0.000814,0.039581,0.007222,0.010834,pass
13,0.019265,0.063502,0.356096,0.001174,0.122480,0.029034,0.147768,0.236612,0.020344,0.237589,...,0.047713,0.055710,0.012719,0.044135,0.048846,0.000925,0.052775,0.009858,0.014989,pass
14,0.023990,0.046278,0.280602,0.000904,0.119031,0.038093,0.206296,0.222080,0.021272,0.265293,...,0.067491,0.077340,0.019935,0.059219,0.068806,0.001414,0.071961,0.014921,0.021544,pass
15,0.036231,0.076582,0.453233,0.001664,0.183087,0.049258,0.273012,0.341337,0.037506,0.344811,...,0.112339,0.130242,0.030641,0.098084,0.110849,0.002215,0.123011,0.024761,0.036236,pass
16,0.018484,0.021911,0.206818,0.000360,0.117630,0.021336,0.164136,0.251059,0.014306,0.273737,...,0.041693,0.046561,0.010256,0.035640,0.036724,0.000714,0.040989,0.007930,0.011162,pass
17,0.034722,0.064923,0.399691,0.000828,0.151632,0.028211,0.167777,0.369218,0.026837,0.391857,...,0.090089,0.109005,0.025091,0.077014,0.090791,0.001765,0.101969,0.020250,0.029092,pass
18,0.034583,0.047236,0.311343,0.001003,0.183885,0.030765,0.188176,0.335034,0.024736,0.343753,...,0.089299,0.100682,0.023174,0.079132,0.084975,0.001658,0.094741,0.018092,0.027096,pass
19,0.035818,0.061705,0.395402,0.001152,0.199169,0.050952,0.259566,0.381687,0.027839,0.423531,...,0.084000,0.094457,0.023619,0.075257,0.081068,0.001645,0.088016,0.017380,0.025114,pass

[[1.24939447 1.25300669 1.19305622 1.23808888 1.33360678 1.17749696
  1.21650427 1.24032486 1.224775   1.2646231  1.14371176 1.21385266
  1.2308441  1.23642545 1.18633729 1.24556596 1.19829122 1.1572223
  1.25305501 1.26548281 1.2069651  1.26609289 1.23435666 1.23734986
  1.22393369 1.22173867 1.22259774 1.22972803 1.21135686 1.23835694
  1.25170414 1.28011937 1.22549154 1.29132689 1.24725821 1.24425795
  1.29316301 1.26834627 1.24791968 1.27531223 1.28023518 1.29111919
  1.31470856 1.30826735 1.2936001  1.31451594 1.30232194 1.31464623
  1.3074907  1.3175641  1.34568546]]
BARINEL SCORES

,ry 42,cx 46,y 44,ry 45,ry 49,ry 40,cx 41,cx 48,cx 37,cx 31,...,cx 5,cx 22,cx 18,cx 33,cx 24,cx 2,ry 17,cx 20,cx 13,cx 23
sum,0.595427,0.568945,0.564246,0.563833,0.558259,0.556817,0.549482,0.546514,0.541594,0.541591,...,0.51967,0.518466,0.518268,0.516899,0.516774,0.516289,0.514808,0.514722,0.512774,0.502994

custom SCORES

,ry 42,cx 46,y 44,ry 49,ry 45,cx 41,ry 40,ry 14,cx 31,ry 3,...,cx 34,ry 17,cx 30,cx 18,cx 20,cx 22,cx 13,cx 24,cx 33,cx 23
sum,0.777743,0.758633,0.735848,0.733134,0.729812,0.723203,0.716026,0.713091,0.712934,0.709796,...,0.682877,0.681004,0.677448,0.677051,0.675792,0.675478,0.675368,0.674726,0.666441,0.657631

DSTAR SCORES

,cx 48,cx 41,cx 43,cx 35,y 44,cx 38,cx 39,cx 37,cx 26,cx 34,...,ry 0,ry 6,ry 12,ry 1,ry 14,ry 10,ry 21,ry 3,ry 47,ry 29
sum,1.421712,1.311461,0.998863,0.713356,0.584858,0.581831,0.423793,0.416482,0.408823,0.398959,...,0.006346,0.005003,0.003026,0.002859,0.002135,0.000355,0.000044,0.000026,0.000017,3.048733e-13

ERROR GATE LOCATION:
44
Now evolving the following mutant:  AddGate_ry_inGap_33_.qasm

100%|██████████| 10/10 [04:35<00:00, 27.51s/it]
100%|██████████| 10/10 [04:19<00:00, 25.91s/it]

,ry 50,ry 49,cx 48,ry 47,cx 46,ry 45,cx 44,ry 43,cx 42,ry 41,...,cx 8,cx 7,ry 6,cx 5,cx 4,ry 3,cx 2,ry 1,ry 0,pass/fail
0,0.027255,0.056908,0.365893,0.001171,0.140271,0.036326,0.294870,0.026084,0.316013,0.069804,...,0.076616,0.088872,0.020585,0.068372,0.075855,0.001485,0.082323,0.015834,0.023477,fail
1,0.031119,0.064019,0.372128,0.001286,0.196697,0.027024,0.334611,0.024875,0.429936,0.067477,...,0.083620,0.098012,0.021041,0.070884,0.086007,0.001539,0.088294,0.016705,0.024936,fail
2,0.032779,0.069977,0.399822,0.001178,0.159113,0.026910,0.324222,0.028827,0.371820,0.069982,...,0.091095,0.107280,0.022861,0.075431,0.091083,0.001646,0.096004,0.017957,0.027116,fail
3,0.037199,0.051061,0.372141,0.001455,0.156201,0.041061,0.354196,0.038863,0.378658,0.084002,...,0.119993,0.140472,0.032518,0.104064,0.118311,0.002344,0.129247,0.025687,0.038777,fail
4,0.023505,0.054168,0.332701,0.001413,0.114668,0.039774,0.246380,0.031964,0.260630,0.071664,...,0.074956,0.086139,0.020337,0.065805,0.074299,0.001517,0.077323,0.015540,0.024160,fail
5,0.039624,0.074830,0.436815,0.001485,0.192274,0.045948,0.389829,0.021254,0.436968,0.072754,...,0.106423,0.121370,0.026226,0.088366,0.100656,0.001921,0.106701,0.020742,0.030735,fail
6,0.031397,0.058582,0.380488,0.001240,0.144992,0.048417,0.306658,0.028346,0.350209,0.077757,...,0.087812,0.100581,0.023972,0.075881,0.086397,0.001756,0.088480,0.017969,0.027464,fail
7,0.026520,0.063475,0.392689,0.001177,0.128704,0.039023,0.287738,0.016682,0.329567,0.069420,...,0.064665,0.072647,0.015393,0.052813,0.059429,0.001046,0.062189,0.011392,0.016715,fail
8,0.031941,0.082484,0.450047,0.001503,0.193555,0.054204,0.305361,0.029993,0.352668,0.077482,...,0.085324,0.095225,0.022213,0.072413,0.086346,0.001669,0.083235,0.016408,0.025652,fail
9,0.038370,0.077113,0.460754,0.001479,0.219572,0.045410,0.387733,0.028409,0.439875,0.086500,...,0.100347,0.114818,0.025721,0.083255,0.099314,0.001862,0.103009,0.019838,0.030381,fail
10,0.025805,0.060947,0.363439,0.001295,0.116143,0.028755,0.275217,0.022143,0.318614,0.059273,...,0.059666,0.070027,0.016088,0.052297,0.059667,0.001114,0.062410,0.011727,0.017580,pass
11,0.034222,0.062506,0.384245,0.001005,0.191764,0.033981,0.328005,0.020047,0.433930,0.067048,...,0.072219,0.081871,0.018427,0.061434,0.070965,0.001284,0.073997,0.013832,0.020831,pass
12,0.039139,0.059498,0.395244,0.000968,0.242385,0.046777,0.404064,0.035327,0.457603,0.085449,...,0.096714,0.107591,0.025703,0.083969,0.094038,0.001910,0.095716,0.019109,0.030116,pass
13,0.042543,0.061337,0.450367,0.000681,0.224477,0.044108,0.482907,0.020637,0.543897,0.084781,...,0.089447,0.102337,0.022242,0.076033,0.080696,0.001515,0.092780,0.017445,0.025840,pass
14,0.038460,0.072225,0.466263,0.001282,0.244454,0.032544,0.411498,0.028615,0.494248,0.081443,...,0.078463,0.088617,0.018654,0.064645,0.076314,0.001373,0.072944,0.013375,0.021446,pass
15,0.041054,0.060778,0.419265,0.001081,0.195501,0.040469,0.426061,0.021923,0.491268,0.074024,...,0.103133,0.119525,0.024302,0.083987,0.093922,0.001698,0.103323,0.019573,0.028559,pass
16,0.043049,0.050852,0.379379,0.001182,0.238830,0.044343,0.449830,0.031386,0.540179,0.081523,...,0.111346,0.127446,0.029042,0.094064,0.107102,0.002097,0.111908,0.022217,0.033959,pass
17,0.035626,0.068969,0.423214,0.001447,0.221449,0.029171,0.398996,0.022270,0.459176,0.076479,...,0.082489,0.094677,0.020466,0.068785,0.081632,0.001451,0.084569,0.015500,0.023629,pass
18,0.033168,0.038013,0.301425,0.000535,0.152157,0.037798,0.329905,0.029935,0.373003,0.066979,...,0.077943,0.088953,0.020381,0.064713,0.071976,0.001430,0.075931,0.015160,0.023250,pass
19,0.033532,0.051884,0.347077,0.000664,0.177685,0.034566,0.351232,0.019772,0.422496,0.065719,...,0.072769,0.082172,0.016732,0.056993,0.066729,0.001201,0.064503,0.012260,0.018907,pass

[[1.23938568 1.26389138 1.16249918 1.1223623  1.3339329  1.34135103
  1.20630333 1.41167476 1.19976365 1.15821318 1.29750163 1.19910302
  1.23280198 1.26765601 1.26495421 1.26773962 1.32673187 1.2783611
  1.26576226 1.23033395 1.31171643 1.2499862  1.2554807  1.37972096
  1.22904033 1.34466903 1.30865593 1.43381306 1.4111129  1.38889557
  1.37464426 1.31285586 1.33065396 1.42359844 1.32666649 1.31896107
  1.35866874 1.37595791 1.42548478 1.34842218 1.35010381 1.31775927
  1.34694375 1.36990074 1.40853336 1.37417481 1.34796958 1.39664423
  1.4097589  1.44250507 1.43930903]]
BARINEL SCORES

,ry 47,ry 10,ry 27,ry 3,ry 49,ry 1,ry 0,cx 2,cx 4,ry 43,...,cx 34,ry 37,cx 39,cx 36,cx 38,ry 50,cx 40,cx 44,cx 46,cx 42
sum,0.568966,0.528296,0.528162,0.526889,0.526463,0.526422,0.52463,0.52243,0.52221,0.522037,...,0.480898,0.479306,0.477583,0.474661,0.470117,0.46584,0.460143,0.455841,0.450862,0.447074

custom SCORES

,ry 47,ry 1,ry 0,ry 3,ry 27,ry 10,cx 2,ry 43,ry 6,ry 17,...,cx 35,ry 37,cx 36,cx 39,cx 38,ry 50,cx 40,cx 46,cx 44,cx 42
sum,0.728613,0.716263,0.713406,0.710858,0.710341,0.70661,0.706555,0.706274,0.704808,0.698484,...,0.63518,0.631205,0.624767,0.620751,0.615007,0.610179,0.609402,0.601217,0.593311,0.58117

DSTAR SCORES

,cx 48,cx 42,cx 44,cx 36,cx 39,cx 31,cx 34,cx 26,cx 35,cx 40,...,ry 33,ry 6,ry 1,ry 12,ry 14,ry 10,ry 21,ry 3,ry 47,ry 29
sum,1.127728,0.924845,0.753603,0.598781,0.477129,0.46398,0.432552,0.408497,0.400947,0.381213,...,0.006884,0.005219,0.003121,0.002286,0.001926,0.000383,0.000048,0.000028,0.000018,3.625662e-13

ERROR GATE LOCATION:
33
Now evolving the following mutant:  AddGate_x_inGap_31_.qasm

100%|██████████| 10/10 [04:19<00:00, 25.97s/it]
100%|██████████| 10/10 [04:00<00:00, 24.04s/it]

,ry 50,ry 49,cx 48,ry 47,cx 46,ry 45,cx 44,ry 43,cx 42,ry 41,...,cx 8,cx 7,ry 6,cx 5,cx 4,ry 3,cx 2,ry 1,ry 0,pass/fail
0,0.033964,0.062020,0.397580,0.001232,0.196754,0.044413,0.330370,0.033738,0.393683,0.078398,...,0.092063,0.105152,0.025066,0.081118,0.091382,0.001810,0.095522,0.019273,0.029142,fail
1,0.036764,0.067936,0.459147,0.001344,0.214995,0.042485,0.379151,0.021786,0.419247,0.078395,...,0.084200,0.095476,0.021173,0.072453,0.079203,0.001474,0.086853,0.016630,0.024353,fail
2,0.044305,0.073191,0.456087,0.001164,0.247186,0.043064,0.448946,0.029043,0.518683,0.081758,...,0.107820,0.124308,0.028813,0.090770,0.104199,0.002089,0.112380,0.022554,0.032547,fail
3,0.036502,0.075487,0.423494,0.000939,0.250942,0.043147,0.368330,0.033054,0.417178,0.074482,...,0.078755,0.088656,0.020132,0.068515,0.078492,0.001486,0.079490,0.015337,0.024303,fail
4,0.042393,0.070189,0.475159,0.001426,0.237581,0.059399,0.428439,0.041685,0.534958,0.103558,...,0.114153,0.132531,0.033236,0.098810,0.116295,0.002346,0.122582,0.025289,0.036611,fail
5,0.028075,0.053551,0.364502,0.001242,0.135756,0.026547,0.319188,0.016003,0.364608,0.071121,...,0.062819,0.074181,0.017509,0.055436,0.061979,0.001229,0.067167,0.013032,0.018246,fail
6,0.030006,0.063736,0.401513,0.001353,0.143849,0.035719,0.306015,0.027661,0.375646,0.070628,...,0.078647,0.093119,0.022074,0.069316,0.079462,0.001562,0.084680,0.016799,0.023324,fail
7,0.038786,0.082656,0.492534,0.001174,0.260646,0.039716,0.384565,0.028701,0.457290,0.079241,...,0.078693,0.087626,0.020043,0.069457,0.076963,0.001467,0.077335,0.014744,0.022992,fail
8,0.020381,0.069164,0.384496,0.001515,0.128070,0.035085,0.219076,0.021771,0.266322,0.060201,...,0.048260,0.056096,0.013477,0.042964,0.050514,0.000987,0.048323,0.009501,0.013692,fail
9,0.027309,0.071648,0.403904,0.001252,0.155047,0.049770,0.287727,0.029826,0.324997,0.073114,...,0.076040,0.086807,0.020825,0.062810,0.074156,0.001530,0.077520,0.016230,0.024154,fail
10,0.036158,0.061746,0.389547,0.000593,0.231730,0.036802,0.389184,0.026979,0.469597,0.072491,...,0.069231,0.077755,0.018255,0.062481,0.067231,0.001327,0.069220,0.013255,0.020628,pass
11,0.024697,0.036719,0.291518,0.000624,0.161854,0.018572,0.255399,0.019407,0.312401,0.059966,...,0.057659,0.067429,0.015060,0.049012,0.056134,0.001030,0.063983,0.012413,0.017621,pass
12,0.035078,0.063606,0.423582,0.001116,0.147835,0.057484,0.335188,0.034377,0.350545,0.083197,...,0.104979,0.120605,0.028307,0.088624,0.098887,0.002022,0.109433,0.022473,0.032064,pass
13,0.026512,0.073263,0.397567,0.001214,0.143711,0.042711,0.274507,0.020794,0.338674,0.070114,...,0.059579,0.067502,0.017102,0.052703,0.059474,0.001197,0.063334,0.012820,0.017798,pass
14,0.036402,0.054688,0.385134,0.001424,0.241997,0.035353,0.395361,0.022290,0.459809,0.072432,...,0.074974,0.083517,0.019312,0.066854,0.072699,0.001370,0.072687,0.013673,0.020912,pass
15,0.032056,0.057577,0.364196,0.001246,0.149565,0.034517,0.356896,0.029225,0.374883,0.070373,...,0.085467,0.100651,0.024194,0.076288,0.085533,0.001746,0.091164,0.018506,0.027523,pass
16,0.032699,0.055891,0.382691,0.001047,0.216527,0.041031,0.408628,0.028580,0.491771,0.084934,...,0.063033,0.070501,0.017667,0.057169,0.062699,0.001217,0.062560,0.012229,0.018736,pass
17,0.023410,0.066447,0.344499,0.001326,0.155481,0.029455,0.255885,0.028901,0.308659,0.067649,...,0.050623,0.058601,0.015044,0.044562,0.055166,0.001085,0.053062,0.010530,0.015960,pass
18,0.024081,0.051403,0.322308,0.001032,0.161507,0.040230,0.274239,0.023027,0.323516,0.066283,...,0.063389,0.074071,0.017360,0.051608,0.063445,0.001290,0.064811,0.013841,0.020259,pass
19,0.024508,0.075691,0.433442,0.001315,0.137989,0.034819,0.273944,0.019371,0.342415,0.064887,...,0.051059,0.057749,0.014507,0.046015,0.051550,0.000974,0.051959,0.009933,0.014734,pass

[[1.30891898 1.19864582 1.15661337 1.19849724 1.32252104 1.41647947
  1.29311766 1.47158875 1.31355078 1.34334889 1.39794116 1.31394752
  1.30822269 1.41803808 1.28304803 1.41164681 1.35139071 1.34771833
  1.36522179 1.34476334 1.32994907 1.30621721 1.35453032 1.39658084
  1.33884254 1.31912186 1.42010811 1.41168847 1.47310144 1.34482431
  1.37868744 1.40180193 1.44934353 1.53692165 1.41431758 1.40399408
  1.46589742 1.43457363 1.38092947 1.44180269 1.4727176  1.3909818
  1.38964808 1.40399827 1.49478243 1.3884695  1.43106378 1.46814646
  1.43900719 1.49295013 1.46819224]]
BARINEL SCORES

,x 30,cx 2,ry 1,cx 7,ry 0,cx 8,cx 4,cx 9,ry 27,ry 3,...,cx 38,ry 45,cx 40,cx 46,cx 39,ry 43,ry 37,ry 41,cx 42,cx 44
sum,0.553868,0.548144,0.548074,0.548066,0.547333,0.547108,0.547065,0.547044,0.546789,0.54654,...,0.532671,0.530602,0.530142,0.529931,0.529353,0.528269,0.522624,0.519744,0.519143,0.518874

custom SCORES

,ry 1,ry 17,ry 0,ry 3,ry 6,cx 2,cx 4,ry 10,cx 7,x 30,...,cx 36,cx 38,cx 46,cx 39,ry 47,ry 49,ry 41,cx 42,cx 48,cx 44
sum,0.752636,0.75058,0.74823,0.747141,0.746509,0.74534,0.742786,0.742396,0.740437,0.738022,...,0.707688,0.706884,0.705142,0.703239,0.696797,0.696574,0.694293,0.689623,0.686828,0.686615

DSTAR SCORES

,cx 48,cx 42,cx 44,cx 36,cx 39,cx 26,cx 40,cx 35,cx 34,cx 38,...,ry 0,ry 6,ry 1,ry 12,ry 14,ry 10,ry 21,ry 3,ry 47,ry 29
sum,1.320333,1.204316,0.911811,0.695108,0.540304,0.436556,0.42824,0.426732,0.421929,0.386964,...,0.006093,0.004853,0.00283,0.002481,0.001965,0.000334,0.000044,0.000026,0.000016,3.245874e-13

ERROR GATE LOCATION:
30
Now evolving the following mutant:  AddGate_x_inGap_30_.qasm

100%|██████████| 10/10 [04:36<00:00, 27.68s/it]
100%|██████████| 10/10 [04:16<00:00, 25.65s/it]

,ry 50,ry 49,cx 48,ry 47,cx 46,ry 45,cx 44,ry 43,cx 42,ry 41,...,cx 8,cx 7,ry 6,cx 5,cx 4,ry 3,cx 2,ry 1,ry 0,pass/fail
0,0.038379,0.076548,0.477384,0.001600,0.222212,0.053022,0.371123,0.035637,0.477299,0.089520,...,0.100746,0.118105,0.028169,0.086751,0.101907,0.002045,0.107442,0.021938,0.031224,fail
1,0.045360,0.072208,0.466039,0.001185,0.242071,0.058039,0.436603,0.031778,0.554500,0.094512,...,0.103485,0.116294,0.029643,0.091870,0.102513,0.002080,0.107329,0.021472,0.031140,fail
2,0.037519,0.055792,0.354115,0.001114,0.221177,0.047788,0.348554,0.019735,0.442014,0.069400,...,0.070381,0.073935,0.017138,0.060307,0.064198,0.001201,0.061568,0.011547,0.018031,fail
3,0.030477,0.083371,0.498948,0.000970,0.183904,0.038587,0.284247,0.028900,0.354116,0.080765,...,0.060806,0.068594,0.017222,0.053631,0.063436,0.001212,0.061578,0.012021,0.018848,fail
4,0.037540,0.064127,0.441479,0.000971,0.219126,0.045370,0.378957,0.043734,0.403108,0.091122,...,0.114091,0.134535,0.030555,0.098523,0.113299,0.002224,0.126565,0.025328,0.037497,fail
5,0.042606,0.090494,0.533081,0.001564,0.257474,0.053358,0.456918,0.028928,0.545003,0.098809,...,0.087846,0.100115,0.024378,0.075698,0.089254,0.001713,0.091500,0.017988,0.026275,fail
6,0.042408,0.067400,0.497476,0.001358,0.244118,0.030555,0.427395,0.027774,0.497452,0.084647,...,0.100973,0.117632,0.026062,0.087271,0.097445,0.001863,0.105327,0.020521,0.030294,fail
7,0.036515,0.080879,0.464448,0.001413,0.168116,0.050949,0.333146,0.038589,0.389140,0.082388,...,0.102461,0.119757,0.028799,0.088102,0.102442,0.002095,0.107808,0.022045,0.031782,fail
8,0.042829,0.094329,0.558350,0.001035,0.223370,0.061347,0.387403,0.046203,0.477449,0.098158,...,0.114987,0.133441,0.031825,0.097410,0.114218,0.002287,0.122633,0.025453,0.036834,fail
9,0.034426,0.054302,0.367363,0.000806,0.208109,0.027332,0.381758,0.029530,0.420743,0.076749,...,0.089767,0.106433,0.023789,0.077505,0.088644,0.001725,0.100817,0.020072,0.029061,fail
10,0.027332,0.071223,0.421242,0.001141,0.184503,0.041118,0.329036,0.019445,0.358741,0.071243,...,0.044485,0.047233,0.010597,0.039809,0.040802,0.000718,0.040337,0.006889,0.011151,pass
11,0.021344,0.048142,0.280229,0.001079,0.124820,0.036297,0.215096,0.021499,0.240916,0.050015,...,0.065281,0.075852,0.017223,0.056649,0.064092,0.001276,0.067993,0.013862,0.020855,pass
12,0.030803,0.047699,0.310819,0.000876,0.159370,0.031862,0.288144,0.021931,0.328555,0.056006,...,0.082911,0.095303,0.021020,0.071248,0.077745,0.001527,0.086685,0.016942,0.024691,pass
13,0.025477,0.053584,0.307832,0.000975,0.128061,0.052941,0.261296,0.039540,0.261684,0.075786,...,0.080742,0.092362,0.022771,0.068970,0.080232,0.001655,0.083936,0.017682,0.026511,pass
14,0.017411,0.038306,0.232090,0.000739,0.096616,0.026480,0.204491,0.013357,0.210797,0.045595,...,0.034750,0.037781,0.008796,0.031424,0.032278,0.000598,0.034154,0.006183,0.010076,pass
15,0.032465,0.065116,0.388142,0.000886,0.179640,0.043997,0.285117,0.032441,0.370291,0.072612,...,0.088945,0.102999,0.024741,0.075507,0.089675,0.001815,0.093528,0.019548,0.028767,pass
16,0.039652,0.091018,0.508076,0.001618,0.214870,0.046820,0.388788,0.034985,0.479577,0.085694,...,0.092460,0.108975,0.025449,0.082687,0.095796,0.001805,0.101600,0.019393,0.028686,pass
17,0.020681,0.082409,0.424572,0.001201,0.111070,0.056627,0.211142,0.024991,0.263224,0.077358,...,0.045532,0.047947,0.013846,0.040748,0.045385,0.000974,0.043280,0.008959,0.013547,pass
18,0.034186,0.064197,0.383138,0.001316,0.200319,0.046915,0.375889,0.030194,0.421644,0.077110,...,0.073038,0.081442,0.020805,0.066288,0.073613,0.001462,0.073507,0.014344,0.021997,pass
19,0.035234,0.074179,0.433227,0.001439,0.169193,0.040073,0.320785,0.022339,0.389551,0.069109,...,0.081012,0.092389,0.021835,0.071498,0.079152,0.001549,0.083630,0.016053,0.023139,pass

[[1.1688913  1.27566627 1.19851422 1.33133854 1.17585215 1.31548525
  1.20048735 1.39666514 1.21578902 1.14089347 1.22594653 1.15971617
  1.13982602 1.19560882 1.17592425 1.22997153 1.23784564 1.16945821
  1.19567908 1.11090054 1.15610817 1.21065992 1.19010012 1.26171647
  1.14056814 1.20830115 1.20164041 1.20755186 1.16486861 1.216197
  1.16029831 1.18494479 1.15868673 1.28392034 1.15898812 1.19114838
  1.23704593 1.17060507 1.22747717 1.18647907 1.21370163 1.20188486
  1.21609847 1.23558244 1.23555175 1.20580808 1.21850871 1.24002528
  1.2751273  1.28300463 1.2886217 ]]
BARINEL SCORES

,cx 38,ry 1,ry 17,cx 2,cx 40,cx 46,cx 7,ry 0,cx 23,cx 4,...,cx 28,cx 19,cx 32,cx 34,ry 41,ry 43,cx 48,ry 49,ry 45,ry 47
sum,0.586754,0.586521,0.585986,0.583445,0.582808,0.582649,0.581918,0.5815,0.581363,0.580001,...,0.568568,0.567969,0.564761,0.562998,0.559983,0.559242,0.558056,0.537656,0.524293,0.516028

custom SCORES

,ry 1,ry 17,cx 2,ry 0,cx 7,cx 40,ry 3,ry 27,ry 6,cx 23,...,cx 19,cx 39,ry 30,cx 32,cx 31,cx 48,ry 41,ry 49,ry 45,ry 47
sum,0.774649,0.774075,0.769437,0.768833,0.76167,0.76143,0.759269,0.758397,0.758199,0.75687,...,0.736222,0.735212,0.733708,0.733579,0.730056,0.725266,0.719704,0.709123,0.696718,0.687781

DSTAR SCORES

,cx 48,cx 42,cx 44,cx 36,cx 39,cx 40,cx 35,cx 26,cx 38,cx 34,...,ry 0,ry 6,ry 1,ry 12,ry 14,ry 10,ry 21,ry 3,ry 47,ry 30
sum,1.585415,1.561062,1.124742,0.898441,0.724456,0.572186,0.5508,0.528669,0.51804,0.508354,...,0.008294,0.006513,0.003881,0.003443,0.002573,0.000439,0.000055,0.000034,0.000014,4.255382e-13

ERROR GATE LOCATION:
29
Now evolving the following mutant:  AddGate_y_inGap_4_.qasm

100%|██████████| 10/10 [04:41<00:00, 28.16s/it]
100%|██████████| 10/10 [04:21<00:00, 26.14s/it]

,ry 50,ry 49,cx 48,ry 47,cx 46,ry 45,cx 44,ry 43,cx 42,ry 41,...,cx 8,ry 7,cx 6,cx 5,ry 4,y 3,cx 2,ry 1,ry 0,pass/fail
0,0.038118,0.074204,0.467164,0.001105,0.262834,0.035820,0.425796,0.024561,0.514371,0.080288,...,0.076710,0.017316,0.060817,0.067133,0.001220,0.036889,0.067336,0.012545,0.019599,fail
1,0.039580,0.079654,0.519739,0.001490,0.242270,0.047590,0.423907,0.031116,0.518201,0.094301,...,0.099457,0.023826,0.077754,0.086787,0.001710,0.047717,0.087244,0.017050,0.025894,fail
2,0.039317,0.070684,0.420507,0.001612,0.212963,0.049356,0.433740,0.026751,0.513707,0.082584,...,0.099906,0.024791,0.076660,0.087772,0.001745,0.047845,0.090792,0.017874,0.025544,fail
3,0.037153,0.083869,0.503290,0.001504,0.244925,0.035003,0.374336,0.035419,0.443564,0.081014,...,0.105596,0.023949,0.078855,0.092188,0.001731,0.050277,0.097925,0.019039,0.028251,fail
4,0.030055,0.049525,0.320686,0.000711,0.181386,0.030730,0.313652,0.018599,0.360563,0.062805,...,0.062823,0.015622,0.050329,0.055389,0.001111,0.031543,0.055311,0.010725,0.016256,fail
5,0.026875,0.074846,0.419325,0.000944,0.144879,0.046819,0.302356,0.015878,0.368349,0.072483,...,0.045100,0.012041,0.036392,0.040767,0.000795,0.022066,0.040030,0.007677,0.011544,fail
6,0.035006,0.072902,0.423691,0.000921,0.185295,0.035979,0.307324,0.027440,0.374142,0.069302,...,0.093645,0.022510,0.071065,0.083038,0.001596,0.045287,0.087104,0.017136,0.025461,fail
7,0.035203,0.070037,0.438558,0.001434,0.203837,0.050106,0.394226,0.030046,0.460202,0.088264,...,0.098136,0.024476,0.075376,0.086262,0.001744,0.047533,0.088460,0.017885,0.026992,fail
8,0.028767,0.057547,0.385570,0.001199,0.141219,0.040106,0.304751,0.019670,0.355497,0.074788,...,0.073437,0.017738,0.056421,0.061825,0.001195,0.033630,0.066811,0.012950,0.018306,fail
9,0.033905,0.065809,0.416027,0.000966,0.244564,0.046305,0.366731,0.032596,0.423360,0.083971,...,0.081054,0.019946,0.066061,0.073041,0.001413,0.041168,0.073872,0.014273,0.022456,fail
10,0.029322,0.072911,0.450419,0.000901,0.155361,0.034444,0.321536,0.028897,0.343976,0.077759,...,0.092181,0.020563,0.065672,0.075183,0.001470,0.040658,0.087109,0.017330,0.025335,pass
11,0.022457,0.054006,0.348384,0.001160,0.121383,0.019339,0.261341,0.010280,0.319723,0.051586,...,0.049751,0.010875,0.035701,0.040364,0.000759,0.021454,0.041153,0.007874,0.011053,pass
12,0.022287,0.051188,0.309928,0.000959,0.126222,0.030237,0.235463,0.025115,0.281021,0.061010,...,0.066922,0.015932,0.047826,0.058896,0.001169,0.032462,0.058863,0.011946,0.017862,pass
13,0.026393,0.053880,0.343464,0.000929,0.160359,0.038753,0.283476,0.018169,0.304650,0.055737,...,0.067167,0.014824,0.055003,0.055705,0.001090,0.032558,0.059144,0.011138,0.017138,pass
14,0.032940,0.069022,0.418367,0.001115,0.172968,0.051883,0.334286,0.022305,0.375451,0.071792,...,0.097896,0.021822,0.070540,0.079911,0.001582,0.043143,0.086925,0.017694,0.024949,pass
15,0.026694,0.070687,0.409187,0.001275,0.166853,0.044017,0.287622,0.021214,0.343412,0.063720,...,0.073914,0.017239,0.058273,0.062891,0.001250,0.034701,0.064870,0.012829,0.019077,pass
16,0.037536,0.072929,0.429611,0.001513,0.193596,0.052390,0.378220,0.030226,0.417913,0.078083,...,0.113463,0.026347,0.087039,0.094191,0.001898,0.052673,0.102626,0.020570,0.029935,pass
17,0.021783,0.021284,0.198350,0.000625,0.111250,0.021132,0.245266,0.015960,0.286069,0.049212,...,0.070226,0.016283,0.050587,0.056898,0.001152,0.030592,0.065464,0.013329,0.018181,pass
18,0.031871,0.067523,0.414262,0.001171,0.190259,0.052244,0.367459,0.023351,0.402702,0.069202,...,0.075893,0.018250,0.063822,0.064257,0.001282,0.036146,0.067733,0.012921,0.019117,pass
19,0.035744,0.073568,0.421979,0.001708,0.175145,0.051446,0.368533,0.030352,0.432244,0.079271,...,0.098638,0.024647,0.074520,0.086251,0.001770,0.047399,0.086142,0.017713,0.025868,pass

[[1.1506384  1.1997098  1.2046183  1.35624738 1.27331365 1.19924373
  1.1893656  1.35146478 1.19622922 1.19398956 1.22443735 1.1767003
  1.18345968 1.15696384 1.14953253 1.22675397 1.34687806 1.17518677
  1.20949759 1.25065689 1.25647718 1.27907584 1.29352925 1.29855377
  1.29809628 1.23695638 1.23498975 1.17817594 1.2777198  1.2205039
  1.1998477  1.1975667  1.21622692 1.20697124 1.20078427 1.21961773
  1.20200476 1.17695825 1.20486503 1.2349956  1.24860136 1.22412522
  1.26331961 1.22597812 1.21366272 1.25562373 1.22361402 1.24462395
  1.29721344 1.29384446 1.28236305]]
BARINEL SCORES

,cx 46,cx 40,ry 37,cx 42,ry 41,cx 39,ry 50,cx 23,cx 44,ry 13,...,ry 0,ry 45,cx 9,cx 2,ry 47,ry 18,cx 24,cx 8,ry 1,ry 22
sum,0.567459,0.5538,0.553283,0.552608,0.545753,0.545334,0.545127,0.542455,0.541873,0.540964,...,0.513741,0.513474,0.51197,0.511816,0.511384,0.510313,0.50992,0.509079,0.506557,0.503396

custom SCORES

,cx 46,cx 40,ry 43,cx 42,cx 34,ry 37,ry 41,cx 39,ry 28,cx 44,...,ry 15,cx 6,ry 4,ry 1,cx 8,cx 9,ry 45,cx 24,ry 18,ry 22
sum,0.748097,0.723323,0.71857,0.717869,0.717468,0.713315,0.708659,0.705757,0.705259,0.702994,...,0.674467,0.672806,0.672779,0.670408,0.669861,0.668649,0.667419,0.667356,0.665477,0.664195

DSTAR SCORES

,cx 42,cx 48,cx 44,cx 36,cx 39,cx 40,cx 34,cx 35,cx 27,cx 38,...,ry 0,ry 7,ry 13,ry 1,ry 15,ry 11,ry 22,ry 4,ry 47,ry 30
sum,1.389326,1.354443,1.016515,0.671168,0.562283,0.468743,0.436591,0.398714,0.396235,0.382557,...,0.004754,0.004014,0.002387,0.002135,0.001667,0.000287,0.000037,0.00002,0.000014,2.845820e-13

ERROR GATE LOCATION:
3
Now evolving the following mutant:  AddGate_z_inGap_38_.qasm

100%|██████████| 10/10 [04:26<00:00, 26.60s/it]
100%|██████████| 10/10 [04:06<00:00, 24.67s/it]

,ry 50,ry 49,cx 48,ry 47,cx 46,ry 45,cx 44,ry 43,cx 42,ry 41,...,cx 8,cx 7,ry 6,cx 5,cx 4,ry 3,cx 2,ry 1,ry 0,pass/fail
0,0.028622,0.065780,0.417284,0.001308,0.202749,0.026608,0.337233,0.029497,0.354329,0.075398,...,0.073224,0.086751,0.018644,0.062002,0.073273,0.001391,0.077889,0.015386,0.023443,fail
1,0.024969,0.066894,0.383186,0.001159,0.130673,0.027812,0.263457,0.025883,0.267943,0.060610,...,0.059891,0.070108,0.015883,0.054096,0.059864,0.001145,0.065373,0.012208,0.018631,fail
2,0.031606,0.068657,0.416392,0.001410,0.132473,0.031736,0.325203,0.023305,0.370417,0.066549,...,0.075754,0.090885,0.020843,0.066052,0.075840,0.001476,0.082816,0.016109,0.022564,fail
3,0.033350,0.077265,0.462236,0.001004,0.205422,0.044457,0.352105,0.023226,0.424619,0.072472,...,0.062471,0.069100,0.016406,0.056355,0.061463,0.001145,0.061085,0.011099,0.017888,fail
4,0.032105,0.078371,0.459419,0.001231,0.215308,0.044125,0.371735,0.028776,0.447174,0.084575,...,0.074409,0.086052,0.020056,0.062163,0.074436,0.001489,0.075624,0.015573,0.022845,fail
5,0.026751,0.078666,0.434988,0.001472,0.135193,0.039130,0.267487,0.033766,0.321100,0.072859,...,0.078244,0.093802,0.022485,0.068066,0.081867,0.001646,0.085921,0.017568,0.025654,fail
6,0.036435,0.059019,0.384797,0.001038,0.179150,0.046432,0.400458,0.034349,0.401196,0.083930,...,0.106943,0.124521,0.029314,0.092773,0.104784,0.002064,0.117003,0.023593,0.034502,fail
7,0.047492,0.092715,0.557175,0.001547,0.278103,0.056146,0.486312,0.040865,0.539789,0.101909,...,0.111805,0.126641,0.030288,0.099776,0.109691,0.002169,0.118057,0.023041,0.034316,fail
8,0.034136,0.069630,0.447682,0.001259,0.191602,0.053728,0.329083,0.024598,0.384279,0.078482,...,0.087953,0.098479,0.023654,0.078619,0.083949,0.001678,0.091330,0.017797,0.025505,fail
9,0.048564,0.089214,0.537711,0.001571,0.266560,0.068019,0.473873,0.046513,0.558302,0.099124,...,0.121141,0.137936,0.033783,0.106440,0.120917,0.002425,0.124345,0.025085,0.038239,fail
10,0.019180,0.032698,0.194749,0.000402,0.105480,0.020721,0.161351,0.013735,0.192420,0.035302,...,0.047622,0.054391,0.012426,0.040802,0.046208,0.000878,0.051229,0.010131,0.014288,pass
11,0.021236,0.032727,0.236333,0.000775,0.127379,0.021471,0.205073,0.013574,0.242160,0.040235,...,0.051950,0.057822,0.012249,0.043949,0.046216,0.000902,0.049070,0.009601,0.014361,pass
12,0.029657,0.064297,0.376637,0.001600,0.173629,0.050516,0.335218,0.025851,0.390342,0.077341,...,0.071625,0.080945,0.020785,0.063602,0.070732,0.001495,0.072684,0.015020,0.021989,pass
13,0.033154,0.040273,0.307874,0.001015,0.190582,0.039695,0.373710,0.025349,0.427396,0.074617,...,0.090618,0.104461,0.024829,0.078784,0.088428,0.001750,0.095889,0.019385,0.028443,pass
14,0.028848,0.049785,0.283792,0.001103,0.153750,0.026087,0.297048,0.019960,0.290053,0.056326,...,0.073175,0.084500,0.019471,0.062670,0.072384,0.001386,0.079894,0.015575,0.022329,pass
15,0.027147,0.069950,0.395512,0.001050,0.156238,0.039985,0.280470,0.018232,0.310498,0.057856,...,0.059174,0.064889,0.013998,0.051011,0.053541,0.001043,0.054171,0.010135,0.015448,pass
16,0.027102,0.049168,0.329859,0.000980,0.169174,0.036351,0.322979,0.023580,0.376799,0.074969,...,0.056314,0.064573,0.015216,0.049075,0.055033,0.001075,0.058391,0.011578,0.017959,pass
17,0.038290,0.078896,0.477089,0.001531,0.195144,0.049276,0.391165,0.027613,0.449754,0.080434,...,0.102094,0.118007,0.027489,0.088930,0.097897,0.001979,0.107970,0.021642,0.030810,pass
18,0.030359,0.066172,0.410136,0.000738,0.159495,0.038863,0.299886,0.022962,0.336844,0.067560,...,0.065749,0.072681,0.016228,0.057767,0.060024,0.001153,0.064966,0.012211,0.018801,pass
19,0.031656,0.069070,0.417189,0.001032,0.154912,0.047379,0.302452,0.025142,0.385612,0.071770,...,0.071165,0.080545,0.019259,0.063189,0.069177,0.001358,0.071080,0.013829,0.020232,pass

[[1.41162771 1.24248327 1.23792782 1.20871509 1.43556918 1.55225712
  1.34826612 1.49666173 1.37203567 1.28041052 1.42148732 1.43133123
  1.38648832 1.38455776 1.3975467  1.40654925 1.46070781 1.40512562
  1.48533278 1.4631762  1.36836855 1.43764834 1.39723316 1.36598215
  1.33715    1.40202531 1.43813881 1.44859482 1.42100903 1.43935153
  1.41186914 1.46568055 1.41405971 1.41236055 1.4295486  1.43365656
  1.50724918 1.41069609 1.51323182 1.43285855 1.46781129 1.41406815
  1.42212279 1.40139416 1.46020756 1.42615674 1.42913849 1.45827235
  1.38246551 1.4135785  1.45070537]]
BARINEL SCORES

,ry 43,ry 27,ry 49,cx 48,ry 0,cx 4,ry 10,ry 3,ry 1,cx 2,...,ry 29,ry 32,ry 36,ry 50,cx 42,cx 40,ry 45,cx 23,cx 33,cx 34
sum,0.589963,0.576604,0.574341,0.567572,0.562925,0.561912,0.561781,0.560828,0.560576,0.560475,...,0.547213,0.546938,0.545635,0.545507,0.544657,0.542694,0.541957,0.541324,0.537347,0.536801

custom SCORES

,ry 43,ry 27,ry 12,ry 10,ry 0,ry 3,ry 6,cx 4,ry 14,cx 15,...,cx 26,cx 30,ry 36,cx 40,ry 41,cx 44,cx 34,cx 42,ry 47,cx 33
sum,0.810707,0.773512,0.770244,0.767928,0.767084,0.765288,0.764113,0.762675,0.761311,0.759019,...,0.737068,0.736869,0.736272,0.735552,0.733553,0.73335,0.732828,0.73148,0.728841,0.726107

DSTAR SCORES

,cx 48,cx 42,cx 44,cx 35,cx 39,cx 26,cx 40,cx 33,cx 38,cx 34,...,ry 0,ry 6,ry 1,ry 12,ry 14,ry 10,ry 21,ry 3,ry 47,ry 29
sum,1.508495,1.235496,1.003138,0.735922,0.569684,0.441491,0.427357,0.425848,0.410445,0.400898,...,0.006809,0.005257,0.003106,0.002852,0.002064,0.000359,0.000046,0.000028,0.000017,3.226387e-13

ERROR GATE LOCATION:
37
Now evolving the following mutant:  AddGate_y_inGap_1_.qasm

100%|██████████| 10/10 [04:26<00:00, 26.62s/it]
100%|██████████| 10/10 [03:55<00:00, 23.57s/it]

,ry 50,ry 49,cx 48,ry 47,cx 46,ry 45,cx 44,ry 43,cx 42,ry 41,...,cx 8,ry 7,cx 6,cx 5,ry 4,cx 3,ry 2,ry 1,y 0,pass/fail
0,0.033628,0.072097,0.433124,0.001368,0.228597,0.031395,0.396641,0.020615,0.451177,0.067850,...,0.060465,0.013135,0.048208,0.052839,0.000892,0.051214,0.008938,0.014081,0.025365,fail
1,0.047630,0.073164,0.493154,0.001059,0.284932,0.047829,0.466786,0.040449,0.561513,0.102043,...,0.119446,0.028749,0.095064,0.105073,0.002036,0.109972,0.021281,0.032718,0.054944,fail
2,0.030770,0.050523,0.363602,0.000943,0.184705,0.039577,0.363024,0.020327,0.406600,0.072615,...,0.072134,0.016433,0.056698,0.059668,0.001138,0.063380,0.011997,0.017897,0.031243,fail
3,0.032709,0.071038,0.438323,0.001644,0.149461,0.053064,0.323988,0.025182,0.401481,0.079933,...,0.102831,0.024672,0.075971,0.086531,0.001724,0.092876,0.018905,0.026341,0.043705,fail
4,0.022421,0.056432,0.383148,0.000836,0.147642,0.037883,0.269590,0.019572,0.299016,0.067411,...,0.046410,0.010100,0.040521,0.037554,0.000722,0.039379,0.006900,0.010864,0.019681,fail
5,0.040830,0.074413,0.460350,0.001100,0.239626,0.044710,0.404784,0.022906,0.460409,0.069567,...,0.097772,0.021577,0.074430,0.080595,0.001537,0.086638,0.016566,0.024360,0.042750,fail
6,0.033052,0.072419,0.439521,0.001702,0.175691,0.053164,0.355582,0.028238,0.399562,0.084262,...,0.103215,0.024761,0.075450,0.087181,0.001776,0.093423,0.019123,0.026853,0.044257,fail
7,0.042800,0.068794,0.435562,0.001370,0.263272,0.044379,0.415154,0.033069,0.532061,0.087096,...,0.111373,0.027692,0.083101,0.099898,0.001990,0.098975,0.020468,0.030672,0.051042,fail
8,0.036766,0.079925,0.477652,0.001539,0.202419,0.060649,0.409616,0.037728,0.479521,0.099610,...,0.110722,0.028353,0.082393,0.099056,0.002026,0.100235,0.020968,0.031297,0.050621,fail
9,0.031832,0.066165,0.416350,0.001158,0.161412,0.045831,0.340035,0.017075,0.407114,0.075165,...,0.069919,0.017383,0.055188,0.059939,0.001188,0.062546,0.012057,0.017021,0.029969,fail
10,0.017077,0.046890,0.284725,0.000636,0.109094,0.020425,0.202411,0.019674,0.226924,0.049559,...,0.050375,0.011703,0.034923,0.042492,0.000854,0.045759,0.009467,0.014094,0.022256,pass
11,0.026477,0.071408,0.392089,0.001312,0.158791,0.042583,0.276055,0.017440,0.360146,0.066874,...,0.052906,0.014163,0.044196,0.049295,0.000976,0.047443,0.009285,0.013356,0.022832,pass
12,0.024176,0.054277,0.296204,0.000972,0.131395,0.031582,0.218844,0.017990,0.242624,0.054468,...,0.066829,0.015479,0.050847,0.057299,0.001107,0.061671,0.012035,0.017517,0.030015,pass
13,0.020839,0.048071,0.289631,0.001002,0.109249,0.027542,0.251365,0.020651,0.239725,0.053432,...,0.053029,0.012462,0.041878,0.046018,0.000840,0.049873,0.009185,0.014037,0.023399,pass
14,0.025851,0.031459,0.271416,0.000861,0.118899,0.020303,0.253226,0.021243,0.263444,0.053371,...,0.091731,0.019971,0.068567,0.073823,0.001405,0.085878,0.016669,0.023987,0.040103,pass
15,0.030104,0.074386,0.401802,0.001026,0.155276,0.052871,0.313446,0.024350,0.408998,0.068641,...,0.063114,0.016909,0.053686,0.055824,0.001191,0.054321,0.010836,0.015671,0.026814,pass
16,0.040159,0.054133,0.389761,0.001186,0.216755,0.043066,0.422243,0.032132,0.500572,0.078045,...,0.127947,0.030283,0.093037,0.106614,0.002172,0.117777,0.024538,0.034172,0.055275,pass
17,0.020788,0.055832,0.321025,0.000954,0.109530,0.029376,0.222517,0.019016,0.283204,0.055769,...,0.042230,0.011167,0.032226,0.039906,0.000759,0.037301,0.007297,0.011212,0.018841,pass
18,0.031388,0.053060,0.329596,0.001226,0.151618,0.039880,0.305392,0.023498,0.325794,0.067326,...,0.094190,0.022882,0.069779,0.081592,0.001630,0.085974,0.017451,0.025496,0.042551,pass
19,0.025365,0.042109,0.335582,0.001049,0.107991,0.027633,0.274018,0.017988,0.281107,0.061791,...,0.093748,0.020406,0.068129,0.073977,0.001450,0.085756,0.017071,0.024013,0.040212,pass

[[1.35145312 1.16683619 1.13609355 1.33805922 1.39826325 1.32282949
  1.24635754 1.52544132 1.27661407 1.26675189 1.32544882 1.36991424
  1.379507   1.40618158 1.29736058 1.18630438 1.19423388 1.32389027
  1.26329127 1.2712428  1.3354165  1.24861748 1.47373014 1.22529287
  1.28326976 1.30316246 1.30868349 1.41228777 1.26633355 1.30505663
  1.32372811 1.35907697 1.27679754 1.35606467 1.39368915 1.290995
  1.35631375 1.50145189 1.3476449  1.37189907 1.38934884 1.34206026
  1.33565037 1.35064114 1.38370564 1.36754409 1.35473287 1.37698653
  1.35370314 1.40963148 1.39601266]]
BARINEL SCORES

,cx 46,cx 42,ry 45,cx 44,cx 40,ry 50,cx 39,ry 37,cx 27,cx 34,...,cx 5,ry 28,y 0,cx 8,ry 4,ry 7,ry 1,ry 18,cx 3,ry 2
sum,0.598222,0.584047,0.577619,0.577543,0.57592,0.573385,0.573156,0.573123,0.572147,0.57187,...,0.550708,0.550183,0.549785,0.548513,0.548308,0.548199,0.54528,0.543823,0.543147,0.540147

custom SCORES

,cx 46,ry 13,ry 37,cx 42,cx 39,ry 45,cx 38,ry 50,cx 40,ry 43,...,ry 22,ry 15,ry 4,ry 7,cx 8,cx 3,cx 48,ry 49,ry 2,ry 18
sum,0.807341,0.777313,0.774602,0.770448,0.76945,0.768642,0.76758,0.767111,0.766757,0.764453,...,0.736754,0.736714,0.734011,0.733304,0.731668,0.730124,0.728335,0.72726,0.722947,0.717412

DSTAR SCORES

,cx 42,cx 48,cx 44,cx 36,cx 39,cx 40,cx 34,cx 35,cx 27,cx 38,...,ry 1,ry 7,ry 13,ry 2,ry 15,ry 11,ry 22,ry 4,ry 47,ry 30
sum,1.473165,1.415464,1.101025,0.744735,0.608954,0.494596,0.487254,0.483998,0.441085,0.413006,...,0.005285,0.004453,0.002497,0.002439,0.001921,0.000304,0.000044,0.000023,0.000016,3.167910e-13

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_y_inGap_53_.qasm

100%|██████████| 10/10 [04:18<00:00, 25.84s/it]
100%|██████████| 10/10 [04:16<00:00, 25.69s/it]

,ry 50,ry 49,cx 48,y 47,ry 46,cx 45,ry 44,cx 43,ry 42,cx 41,...,cx 8,cx 7,ry 6,cx 5,cx 4,ry 3,cx 2,ry 1,ry 0,pass/fail
0,0.033542,0.075390,0.457959,0.397467,0.001580,0.161631,0.046911,0.321342,0.039317,0.314145,...,0.103897,0.121524,0.028489,0.092505,0.103469,0.002060,0.114071,0.022607,0.033233,fail
1,0.028920,0.060079,0.403453,0.482896,0.001669,0.104616,0.032612,0.316878,0.021520,0.328289,...,0.087770,0.106660,0.024145,0.075222,0.087169,0.001729,0.097084,0.019435,0.026931,fail
2,0.049389,0.074785,0.493447,0.442378,0.001651,0.295164,0.048393,0.515648,0.023998,0.605797,...,0.101075,0.113099,0.025734,0.088227,0.095835,0.001816,0.101596,0.019177,0.028265,fail
3,0.040868,0.067866,0.481164,0.381511,0.001408,0.232023,0.051565,0.422320,0.027614,0.516637,...,0.094770,0.107267,0.026282,0.085267,0.092793,0.001825,0.098986,0.019266,0.027552,fail
4,0.035817,0.049888,0.359100,0.287824,0.000906,0.179431,0.038028,0.325061,0.030945,0.362534,...,0.104448,0.120465,0.026972,0.090648,0.099133,0.001962,0.111283,0.021981,0.032200,fail
5,0.034619,0.088517,0.493389,0.454941,0.001828,0.227005,0.051573,0.402608,0.024152,0.490738,...,0.066614,0.073319,0.018023,0.059674,0.064701,0.001304,0.063311,0.012198,0.018059,fail
6,0.034250,0.073920,0.437739,0.344135,0.001273,0.174454,0.042608,0.357455,0.021165,0.412667,...,0.072764,0.082928,0.019517,0.064261,0.070387,0.001361,0.074450,0.014348,0.020320,fail
7,0.036484,0.077486,0.482468,0.334661,0.001325,0.220006,0.045948,0.424388,0.027839,0.514458,...,0.072610,0.081733,0.020550,0.067606,0.072532,0.001423,0.075153,0.014189,0.021039,fail
8,0.032799,0.076504,0.430857,0.348767,0.001314,0.162961,0.048903,0.330416,0.031486,0.346599,...,0.085476,0.097116,0.023308,0.072413,0.082764,0.001716,0.085907,0.017622,0.026390,fail
9,0.040802,0.091950,0.546841,0.504553,0.001953,0.181653,0.062331,0.400657,0.032840,0.458401,...,0.108385,0.125610,0.030796,0.092923,0.106485,0.002187,0.113479,0.023427,0.032857,fail
10,0.030036,0.063446,0.377923,0.269335,0.001016,0.171583,0.049769,0.346378,0.027293,0.406438,...,0.075295,0.087329,0.021388,0.064749,0.074344,0.001517,0.081917,0.016877,0.024132,pass
11,0.030640,0.044278,0.333916,0.226279,0.000653,0.193865,0.031537,0.345658,0.023499,0.412602,...,0.067011,0.077522,0.017599,0.057657,0.065098,0.001242,0.069955,0.013848,0.020815,pass
12,0.032951,0.079191,0.462419,0.432588,0.001699,0.186813,0.048470,0.351232,0.030337,0.383933,...,0.083547,0.094863,0.022536,0.073406,0.080829,0.001645,0.084287,0.016608,0.025020,pass
13,0.018941,0.043745,0.272323,0.250471,0.000987,0.098943,0.029152,0.216720,0.018630,0.253230,...,0.044344,0.051181,0.012892,0.038924,0.044506,0.000923,0.044053,0.009118,0.013052,pass
14,0.033613,0.066007,0.451468,0.407052,0.001555,0.193619,0.026418,0.390847,0.026263,0.461371,...,0.083050,0.100321,0.022478,0.072303,0.083814,0.001596,0.091788,0.017984,0.025523,pass
15,0.042990,0.064884,0.407218,0.244237,0.000871,0.270591,0.046917,0.430885,0.023041,0.538922,...,0.082470,0.092620,0.021369,0.071033,0.080353,0.001512,0.081664,0.015937,0.023574,pass
16,0.030432,0.061595,0.373998,0.238359,0.000855,0.195387,0.032317,0.336532,0.030931,0.364104,...,0.074272,0.086753,0.020352,0.064327,0.075451,0.001445,0.082818,0.016401,0.023959,pass
17,0.032826,0.070765,0.441821,0.312365,0.001214,0.179570,0.053756,0.346623,0.028821,0.414136,...,0.078545,0.090316,0.022936,0.068618,0.078770,0.001685,0.080197,0.016898,0.024814,pass
18,0.037877,0.048492,0.349133,0.230181,0.000606,0.217109,0.038247,0.354242,0.029420,0.425897,...,0.095948,0.110501,0.025441,0.079773,0.091710,0.001817,0.102573,0.021009,0.030143,pass
19,0.030729,0.061745,0.355626,0.345856,0.001316,0.146298,0.032571,0.275854,0.024672,0.355049,...,0.077713,0.093481,0.022320,0.069321,0.082393,0.001560,0.088060,0.017077,0.024030,pass

[[1.34394934 1.24866936 1.19230613 1.2679978  1.30998828 1.5222923
  1.32937968 1.3510048  1.3997978  1.39255224 1.15163877 1.32787261
  1.2411889  1.26666501 1.22761959 1.26236868 1.23627578 1.20751574
  1.22869783 1.19559656 1.1985323  1.17743385 1.20769117 1.25487116
  1.2036358  1.19560461 1.20931603 1.20964356 1.16208775 1.23084871
  1.18719415 1.21037745 1.176641   1.31924147 1.19149209 1.18582459
  1.28225681 1.19271762 1.26719031 1.21285065 1.24977602 1.18117758
  1.20722125 1.21984062 1.2630786  1.17811486 1.21659445 1.2578786
  1.21959104 1.27146721 1.24540891]]
BARINEL SCORES

,ry 46,y 47,ry 21,cx 23,ry 25,cx 33,cx 28,cx 26,cx 34,cx 19,...,cx 38,ry 36,ry 0,cx 39,cx 43,cx 37,ry 29,cx 41,ry 42,cx 45
sum,0.58048,0.573705,0.558558,0.555534,0.554994,0.554637,0.552428,0.550768,0.550504,0.549362,...,0.53217,0.532001,0.531665,0.530678,0.529244,0.528117,0.52759,0.519997,0.516521,0.511228

custom SCORES

,ry 46,y 47,ry 21,ry 44,cx 23,cx 33,ry 25,ry 49,ry 14,cx 34,...,cx 18,cx 38,ry 42,ry 0,cx 37,ry 36,cx 15,cx 22,ry 40,ry 29
sum,0.770586,0.755569,0.730433,0.728066,0.723534,0.72207,0.720882,0.720804,0.72067,0.720647,...,0.698863,0.697301,0.697277,0.6972,0.695354,0.695275,0.693361,0.69316,0.686175,0.68289

DSTAR SCORES

,cx 48,cx 41,y 47,cx 43,cx 35,cx 38,cx 33,cx 26,cx 34,cx 39,...,ry 0,ry 6,ry 1,ry 12,ry 14,ry 10,ry 21,ry 3,ry 46,ry 29
sum,1.521443,1.35026,1.222029,1.087554,0.810773,0.626436,0.559746,0.533056,0.529332,0.505156,...,0.006957,0.005823,0.003341,0.002814,0.002407,0.000397,0.000059,0.00003,0.000022,3.498882e-13

ERROR GATE LOCATION:
47
Now evolving the following mutant:  AddGate_ry_inGap_52_.qasm

100%|██████████| 10/10 [04:15<00:00, 25.53s/it]
100%|██████████| 10/10 [04:34<00:00, 27.46s/it]

,ry 50,ry 49,cx 48,ry 47,cx 46,ry 45,ry 44,cx 43,ry 42,cx 41,...,cx 8,cx 7,ry 6,cx 5,cx 4,ry 3,cx 2,ry 1,ry 0,pass/fail
0,0.037924,0.084854,0.509497,0.001728,0.253649,0.293782,0.054927,0.415646,0.033494,0.470142,...,0.087394,0.097096,0.022653,0.078149,0.084366,0.001655,0.085808,0.016466,0.025088,fail
1,0.042552,0.072469,0.443049,0.000834,0.250442,0.241685,0.038897,0.441344,0.025759,0.497423,...,0.088919,0.100973,0.023031,0.075780,0.085046,0.001654,0.091642,0.017786,0.025830,fail
2,0.026782,0.061403,0.346823,0.000955,0.132973,0.211573,0.036095,0.285530,0.022739,0.251250,...,0.068593,0.078403,0.017952,0.060393,0.066023,0.001273,0.075279,0.014215,0.020692,fail
3,0.034092,0.064860,0.441175,0.001112,0.212175,0.302209,0.051640,0.391723,0.033310,0.471423,...,0.085515,0.098619,0.023497,0.075356,0.083128,0.001696,0.088202,0.017977,0.026604,fail
4,0.028149,0.074042,0.410209,0.001125,0.185244,0.182331,0.034262,0.316842,0.022260,0.365955,...,0.046938,0.052109,0.013084,0.040194,0.048417,0.000931,0.045269,0.008555,0.013646,fail
5,0.037987,0.075110,0.462860,0.001586,0.181257,0.301402,0.053149,0.370268,0.024452,0.429596,...,0.089598,0.100761,0.024998,0.079679,0.087016,0.001734,0.092155,0.018159,0.025705,fail
6,0.033102,0.077898,0.477260,0.001218,0.172965,0.323860,0.055065,0.341666,0.041993,0.380221,...,0.100798,0.116096,0.027400,0.087886,0.098191,0.002019,0.104627,0.021470,0.032242,fail
7,0.028168,0.057576,0.357843,0.001103,0.186004,0.234874,0.040511,0.354274,0.023570,0.383352,...,0.053362,0.057146,0.013703,0.048525,0.048754,0.000985,0.050216,0.009280,0.014838,fail
8,0.024103,0.063821,0.408678,0.000877,0.156679,0.229014,0.042831,0.288681,0.028828,0.336709,...,0.064847,0.075680,0.017986,0.056365,0.064797,0.001269,0.071117,0.014334,0.020447,fail
9,0.035738,0.070855,0.456415,0.001566,0.181711,0.272292,0.045548,0.334573,0.035295,0.375826,...,0.102133,0.118522,0.027726,0.087625,0.100947,0.001973,0.109804,0.021904,0.031975,fail
10,0.035508,0.063924,0.418428,0.000788,0.219914,0.291022,0.047315,0.394580,0.024896,0.433539,...,0.074962,0.084218,0.019189,0.065500,0.070490,0.001363,0.076633,0.014765,0.021452,pass
11,0.034482,0.065935,0.430421,0.001410,0.207652,0.177135,0.027843,0.351573,0.020393,0.427920,...,0.070899,0.081907,0.018212,0.062229,0.068326,0.001299,0.074071,0.013993,0.019514,pass
12,0.023635,0.051679,0.310485,0.000864,0.130368,0.184762,0.036056,0.227685,0.014038,0.294048,...,0.052849,0.059384,0.014473,0.046827,0.051367,0.001002,0.054954,0.010783,0.015138,pass
13,0.033480,0.060711,0.363750,0.001610,0.210708,0.203334,0.031498,0.301456,0.019300,0.364779,...,0.069977,0.078376,0.017786,0.059047,0.069773,0.001276,0.067674,0.012942,0.019667,pass
14,0.032018,0.046394,0.311880,0.000395,0.172409,0.183852,0.027826,0.329666,0.023420,0.394020,...,0.061837,0.069028,0.015734,0.054675,0.057597,0.001083,0.060769,0.011309,0.017738,pass
15,0.030262,0.071571,0.406367,0.001291,0.146232,0.255713,0.041038,0.284697,0.032504,0.335888,...,0.082046,0.095087,0.022992,0.070048,0.081849,0.001692,0.084462,0.017584,0.026118,pass
16,0.033369,0.054337,0.341109,0.000876,0.208409,0.168166,0.030811,0.358233,0.025313,0.453218,...,0.072747,0.085425,0.019801,0.063156,0.074034,0.001420,0.078119,0.015369,0.022754,pass
17,0.024212,0.039230,0.278437,0.000645,0.146527,0.123279,0.017113,0.277225,0.017631,0.334952,...,0.050864,0.060704,0.014173,0.041922,0.051482,0.001002,0.053466,0.011019,0.016328,pass
18,0.030512,0.061518,0.383129,0.001106,0.170629,0.276253,0.046941,0.318077,0.028367,0.364017,...,0.082126,0.096112,0.022504,0.070611,0.081211,0.001618,0.088508,0.018047,0.025878,pass
19,0.041822,0.072594,0.485073,0.000904,0.224072,0.197220,0.032623,0.421452,0.030982,0.502679,...,0.091804,0.107966,0.025906,0.080325,0.093478,0.001825,0.099802,0.019675,0.028532,pass

[[1.29494424 1.20721218 1.18108362 1.42725271 1.32585181 1.24896827
  1.2157694  1.24654291 1.43960578 1.25551774 1.13420253 1.24205934
  1.16752985 1.20640928 1.14810707 1.24365328 1.35916054 1.31570513
  1.27766957 1.22021959 1.23839739 1.27718979 1.18766879 1.2815612
  1.22319217 1.21336728 1.2597691  1.2846419  1.27273892 1.26065176
  1.24002928 1.21526985 1.29766162 1.37635061 1.25389146 1.25321907
  1.28083775 1.29731228 1.25771853 1.28650287 1.26162837 1.29499166
  1.29594835 1.32367333 1.30763597 1.27380184 1.31666936 1.32942717
  1.34874129 1.36774215 1.36003735]]
BARINEL SCORES

,ry 44,ry 45,ry 42,ry 47,ry 49,ry 40,cx 48,ry 12,ry 27,ry 14,...,cx 26,cx 30,ry 32,cx 35,cx 33,cx 46,ry 50,cx 39,cx 41,ry 29
sum,0.571883,0.557189,0.551893,0.550368,0.544546,0.54289,0.536351,0.536152,0.533245,0.532891,...,0.51399,0.513295,0.512745,0.512682,0.510743,0.510157,0.507175,0.504941,0.503612,0.502699

custom SCORES

,ry 42,ry 47,ry 44,ry 45,ry 49,ry 0,ry 12,ry 27,ry 14,ry 3,...,ry 32,cx 38,cx 30,cx 35,ry 50,cx 26,cx 37,ry 29,cx 39,cx 41
sum,0.750521,0.746747,0.745703,0.731167,0.708891,0.705645,0.704733,0.704092,0.703527,0.703425,...,0.676525,0.673707,0.672211,0.672081,0.671365,0.671167,0.669939,0.663209,0.661732,0.661686

DSTAR SCORES

,cx 48,cx 41,cx 43,cx 35,ry 45,cx 38,cx 39,cx 26,cx 34,cx 37,...,ry 0,ry 6,ry 12,ry 1,ry 14,ry 10,ry 21,ry 3,ry 47,ry 29
sum,1.355439,1.128843,0.945029,0.648272,0.557491,0.539569,0.38908,0.382863,0.376023,0.37344,...,0.005503,0.004411,0.002606,0.002528,0.001857,0.000305,0.000043,0.000023,0.000015,2.660036e-13

ERROR GATE LOCATION:
45
Now evolving the following mutant:  AddGate_z_inGap_40_.qasm

100%|██████████| 10/10 [04:20<00:00, 26.05s/it]
100%|██████████| 10/10 [03:45<00:00, 22.56s/it]

,ry 50,ry 49,cx 48,ry 47,cx 46,ry 45,cx 44,ry 43,cx 42,ry 41,...,cx 8,cx 7,ry 6,cx 5,cx 4,ry 3,cx 2,ry 1,ry 0,pass/fail
0,0.040315,0.065391,0.439237,0.001101,0.227787,0.042160,0.403319,0.033545,0.500119,0.088834,...,0.092280,0.106213,0.025283,0.078149,0.091820,0.001832,0.092178,0.018852,0.028040,fail
1,0.032005,0.079734,0.494734,0.001625,0.172059,0.040185,0.347131,0.023393,0.401835,0.086123,...,0.083945,0.100416,0.023862,0.071042,0.085367,0.001702,0.092556,0.018724,0.026500,fail
2,0.031420,0.081376,0.468888,0.001339,0.138807,0.044460,0.318752,0.014265,0.360510,0.067879,...,0.063620,0.071634,0.017027,0.055421,0.059876,0.001166,0.063075,0.011914,0.016734,fail
3,0.041278,0.092263,0.542400,0.001732,0.246169,0.046740,0.418652,0.035951,0.505787,0.093278,...,0.102199,0.118838,0.028329,0.087556,0.103263,0.002045,0.108690,0.021923,0.031749,fail
4,0.027290,0.078888,0.441720,0.001516,0.125015,0.032006,0.285644,0.030106,0.342218,0.077410,...,0.055921,0.065272,0.016600,0.050134,0.059199,0.001172,0.057018,0.011072,0.016592,fail
5,0.042867,0.094088,0.557727,0.001624,0.222658,0.054473,0.421877,0.031010,0.540783,0.090634,...,0.091222,0.106422,0.025859,0.080377,0.093458,0.001825,0.095105,0.018705,0.026688,fail
6,0.039621,0.085353,0.500128,0.001537,0.213738,0.054811,0.370566,0.030234,0.435442,0.081691,...,0.101762,0.115073,0.027305,0.088096,0.098951,0.001963,0.103786,0.020587,0.029663,fail
7,0.042056,0.080592,0.495532,0.001241,0.245775,0.058845,0.448143,0.027706,0.570617,0.093585,...,0.090435,0.101807,0.025294,0.076709,0.088699,0.001805,0.088207,0.018301,0.027216,fail
8,0.048141,0.074570,0.490547,0.001286,0.255926,0.050524,0.496098,0.035308,0.605263,0.099176,...,0.115420,0.132917,0.031787,0.101123,0.113226,0.002257,0.120929,0.023975,0.034999,fail
9,0.032323,0.077785,0.493308,0.000691,0.175221,0.036597,0.340345,0.019834,0.380786,0.069591,...,0.058784,0.064328,0.013782,0.053048,0.052190,0.000951,0.055444,0.009701,0.015708,fail
10,0.032265,0.081907,0.440494,0.000889,0.156425,0.055589,0.343101,0.028726,0.383320,0.079608,...,0.070436,0.076760,0.020446,0.062232,0.067673,0.001459,0.067540,0.013910,0.020923,pass
11,0.020219,0.019558,0.181113,0.000670,0.096610,0.025221,0.227369,0.015126,0.268936,0.045996,...,0.062867,0.075418,0.017845,0.053595,0.061134,0.001270,0.069699,0.014692,0.019936,pass
12,0.024919,0.052998,0.327003,0.001268,0.136001,0.032854,0.266546,0.022017,0.309560,0.065300,...,0.062268,0.072382,0.016897,0.052708,0.061238,0.001242,0.064293,0.012981,0.018467,pass
13,0.013205,0.051206,0.265956,0.000472,0.070644,0.034915,0.130691,0.017818,0.163932,0.049089,...,0.028300,0.030595,0.008523,0.025173,0.028953,0.000609,0.027419,0.005680,0.008851,pass
14,0.032504,0.047627,0.326196,0.001373,0.173552,0.045303,0.318730,0.029673,0.384722,0.069690,...,0.082302,0.092871,0.022386,0.075073,0.080364,0.001608,0.082995,0.016367,0.024446,pass
15,0.034815,0.039436,0.317066,0.000916,0.188953,0.043872,0.359298,0.027062,0.382824,0.075320,...,0.097959,0.110715,0.025185,0.087974,0.091386,0.001792,0.103356,0.020153,0.029061,pass
16,0.035841,0.093645,0.501129,0.001345,0.189612,0.042066,0.375443,0.020392,0.451118,0.075422,...,0.061396,0.069196,0.016929,0.052669,0.061492,0.001150,0.061230,0.011717,0.016740,pass
17,0.021583,0.042777,0.286861,0.000690,0.123809,0.025745,0.227423,0.010491,0.284402,0.045254,...,0.041738,0.046296,0.010377,0.036103,0.037377,0.000734,0.039379,0.007558,0.010708,pass
18,0.026293,0.058593,0.348138,0.001560,0.130736,0.026508,0.262685,0.028630,0.302175,0.061771,...,0.071985,0.085575,0.020932,0.064956,0.075544,0.001490,0.079184,0.015781,0.023653,pass
19,0.034845,0.037269,0.310155,0.000641,0.210579,0.036104,0.368604,0.017250,0.416302,0.067859,...,0.073778,0.081353,0.018748,0.065183,0.068433,0.001275,0.075308,0.014134,0.021139,pass

[[1.27587615 1.1615245  1.13261862 1.26501511 1.26498302 1.27702343
  1.28839018 1.27780409 1.30350125 1.16924807 1.29030588 1.19823876
  1.2587792  1.23891907 1.28554487 1.22082953 1.25617286 1.28664505
  1.2452425  1.2667277  1.30507753 1.29470779 1.27578409 1.32637515
  1.25351007 1.27411982 1.31890238 1.3341214  1.32750575 1.28780125
  1.32772479 1.33090953 1.31235491 1.38666713 1.32018715 1.2972931
  1.32446984 1.3615181  1.26856182 1.3390312  1.33300951 1.33473003
  1.34901217 1.35226717 1.35189264 1.36348223 1.33829154 1.35023901
  1.37891386 1.37980349 1.37851507]]
BARINEL SCORES

,ry 49,z 39,cx 48,cx 33,cx 26,cx 40,ry 25,ry 47,cx 42,cx 30,...,cx 2,ry 1,ry 14,cx 38,ry 43,cx 19,cx 5,ry 36,cx 23,ry 45
sum,0.606746,0.601611,0.598447,0.594741,0.591699,0.586442,0.583954,0.582223,0.581099,0.580403,...,0.566753,0.566478,0.566171,0.564891,0.564355,0.563372,0.563003,0.562677,0.559194,0.555866

custom SCORES

,cx 33,ry 49,z 39,cx 26,cx 40,cx 42,ry 25,cx 30,cx 48,ry 17,...,ry 14,cx 35,cx 19,cx 23,ry 32,ry 43,ry 36,cx 38,ry 41,ry 45
sum,0.786047,0.782934,0.781829,0.777125,0.775614,0.770465,0.769961,0.769771,0.7679,0.766683,...,0.75364,0.751806,0.750821,0.745703,0.745525,0.744639,0.743514,0.74266,0.738882,0.73333

DSTAR SCORES

,cx 48,cx 42,cx 44,cx 35,cx 38,cx 33,cx 40,cx 26,cx 34,cx 37,...,ry 0,ry 6,ry 1,ry 12,ry 14,ry 10,ry 21,ry 3,ry 47,ry 29
sum,1.822592,1.615368,1.151141,0.85851,0.646495,0.641808,0.590464,0.572579,0.554918,0.455951,...,0.006323,0.005432,0.002979,0.002836,0.002269,0.000378,0.000055,0.000028,0.000019,3.644515e-13

ERROR GATE LOCATION:
39
Now evolving the following mutant:  AddGate_ry_inGap_34_.qasm

100%|██████████| 10/10 [04:29<00:00, 27.00s/it]
100%|██████████| 10/10 [04:21<00:00, 26.12s/it]

,ry 50,ry 49,cx 48,ry 47,cx 46,ry 45,cx 44,ry 43,cx 42,ry 41,...,cx 8,cx 7,ry 6,cx 5,cx 4,ry 3,cx 2,ry 1,ry 0,pass/fail
0,0.036579,0.067392,0.421277,0.001811,0.211148,0.047705,0.401700,0.025080,0.479346,0.084716,...,0.096871,0.110162,0.024920,0.082704,0.095528,0.001839,0.095703,0.018649,0.028929,fail
1,0.031032,0.051774,0.360151,0.001375,0.170179,0.041313,0.292592,0.024715,0.325742,0.067380,...,0.095912,0.111785,0.023608,0.078818,0.090330,0.001699,0.101284,0.020050,0.029164,fail
2,0.034273,0.059305,0.376758,0.001056,0.190806,0.031470,0.382556,0.022474,0.406303,0.072431,...,0.084565,0.095777,0.021395,0.071707,0.080719,0.001591,0.083871,0.016288,0.025437,fail
3,0.024369,0.049453,0.352735,0.001130,0.108438,0.029335,0.261097,0.018337,0.275998,0.060227,...,0.075259,0.091303,0.019552,0.061821,0.072439,0.001356,0.084331,0.016699,0.024077,fail
4,0.031751,0.069045,0.391815,0.001492,0.184471,0.034242,0.298606,0.031083,0.328015,0.072805,...,0.089624,0.102775,0.021914,0.071835,0.087725,0.001666,0.088511,0.017504,0.026909,fail
5,0.044644,0.082876,0.524501,0.001587,0.229882,0.038078,0.447615,0.029110,0.585157,0.087954,...,0.127637,0.150444,0.033309,0.108629,0.125200,0.002426,0.135347,0.027039,0.039247,fail
6,0.034707,0.060427,0.380750,0.001073,0.195708,0.047593,0.363317,0.028931,0.436205,0.080569,...,0.077364,0.085317,0.020968,0.067917,0.074993,0.001492,0.076216,0.014806,0.022866,fail
7,0.034218,0.069722,0.425316,0.001200,0.175147,0.044968,0.377224,0.029637,0.443026,0.080527,...,0.082841,0.095303,0.021280,0.070011,0.079859,0.001531,0.081727,0.015995,0.024469,fail
8,0.042050,0.063675,0.429337,0.001436,0.204010,0.046225,0.433770,0.029779,0.490576,0.083716,...,0.118153,0.136878,0.030373,0.099757,0.112852,0.002156,0.121834,0.023791,0.035451,fail
9,0.030988,0.064041,0.403355,0.001150,0.151230,0.036453,0.317101,0.031365,0.363102,0.071116,...,0.082024,0.095220,0.022015,0.070423,0.079627,0.001597,0.083500,0.016778,0.025213,fail
10,0.044524,0.065543,0.434527,0.001008,0.253498,0.046653,0.414904,0.038387,0.476771,0.084406,...,0.110680,0.124118,0.029053,0.097079,0.107471,0.002110,0.113691,0.022002,0.033985,pass
11,0.020187,0.050501,0.330915,0.000816,0.134858,0.025813,0.228845,0.021727,0.250280,0.060606,...,0.052244,0.060746,0.014201,0.044559,0.052790,0.001025,0.055963,0.011035,0.016903,pass
12,0.028306,0.053282,0.340850,0.001643,0.171678,0.022546,0.281872,0.022293,0.333489,0.057756,...,0.084150,0.096994,0.020628,0.071999,0.083381,0.001566,0.084774,0.016048,0.024392,pass
13,0.041587,0.072464,0.426221,0.001672,0.224411,0.045217,0.390888,0.027256,0.418673,0.074400,...,0.113866,0.127408,0.027986,0.097360,0.108599,0.002074,0.113902,0.021562,0.033152,pass
14,0.019671,0.063845,0.336607,0.000851,0.109744,0.035822,0.204149,0.011087,0.196304,0.054409,...,0.041003,0.042102,0.009681,0.033238,0.036078,0.000692,0.036087,0.006699,0.010600,pass
15,0.019267,0.045055,0.272920,0.001084,0.122255,0.026261,0.222207,0.017449,0.281061,0.053981,...,0.055633,0.065815,0.014310,0.045592,0.056496,0.001042,0.057301,0.011467,0.016803,pass
16,0.033349,0.053821,0.369403,0.001014,0.197037,0.030686,0.384633,0.035036,0.440161,0.079677,...,0.096802,0.115547,0.024996,0.081117,0.095942,0.001784,0.106019,0.020829,0.030527,pass
17,0.026502,0.062626,0.342466,0.001074,0.148152,0.052218,0.286101,0.017870,0.303291,0.058059,...,0.062113,0.066525,0.014299,0.049638,0.055366,0.001060,0.052553,0.010029,0.015790,pass
18,0.025925,0.060784,0.397559,0.000795,0.164835,0.038694,0.307517,0.028630,0.353024,0.078347,...,0.069278,0.081695,0.018949,0.057430,0.068816,0.001366,0.074329,0.015448,0.022899,pass
19,0.038634,0.079192,0.494500,0.001089,0.234437,0.044861,0.389546,0.038624,0.475897,0.096271,...,0.093410,0.107044,0.026447,0.081361,0.098039,0.001947,0.096307,0.019354,0.030683,pass

[[1.29549683 1.29958633 1.28996944 1.36057598 1.26238308 1.20049297
  1.25186821 1.1594536  1.41565471 1.15509935 1.31858871 1.19521432
  1.24139429 1.20638328 1.27263705 1.28006368 1.38236541 1.20579916
  1.36683835 1.32703273 1.29092886 1.25072949 1.36240014 1.3084449
  1.39263454 1.36620238 1.35910974 1.33691916 1.28321659 1.35556143
  1.33678236 1.29344177 1.32973194 1.39825882 1.33443285 1.3174869
  1.32430063 1.35717157 1.31368581 1.36721403 1.39869354 1.37727878
  1.3720693  1.39952957 1.39174301 1.3862405  1.39224319 1.39770737
  1.42123127 1.44132937 1.39292714]]
BARINEL SCORES

,cx 34,cx 23,ry 32,ry 21,ry 17,cx 20,cx 24,ry 1,cx 30,cx 7,...,ry 27,cx 39,ry 37,ry 41,ry 12,cx 48,ry 45,ry 49,ry 43,cx 46
sum,0.558448,0.557397,0.554344,0.554112,0.553671,0.55025,0.548839,0.548419,0.548217,0.547625,...,0.529269,0.528448,0.527528,0.521766,0.520926,0.520483,0.518672,0.51229,0.511491,0.508391

custom SCORES

,cx 34,ry 17,ry 1,ry 32,cx 23,ry 21,cx 2,cx 7,cx 26,cx 24,...,ry 33,ry 12,cx 48,ry 37,cx 39,ry 49,ry 45,ry 41,cx 46,ry 43
sum,0.751443,0.747214,0.746032,0.743768,0.743696,0.741896,0.740395,0.739229,0.736296,0.735322,...,0.694439,0.692009,0.688335,0.686628,0.68635,0.678731,0.674338,0.672439,0.668837,0.659753

DSTAR SCORES

,cx 42,cx 48,cx 44,cx 36,cx 39,cx 31,cx 34,cx 40,cx 35,cx 26,...,ry 43,ry 6,ry 1,ry 12,ry 14,ry 10,ry 21,ry 3,ry 47,ry 29
sum,1.26289,1.202703,0.975142,0.71095,0.538179,0.511776,0.51095,0.466733,0.445341,0.437748,...,0.007133,0.005615,0.003466,0.002371,0.002122,0.000392,0.000054,0.00003,0.000018,3.883545e-13

ERROR GATE LOCATION:
33
Now evolving the following mutant:  AddGate_y_inGap_24_.qasm

100%|██████████| 10/10 [04:27<00:00, 26.73s/it]
100%|██████████| 10/10 [04:04<00:00, 24.45s/it]

,ry 50,ry 49,cx 48,ry 47,cx 46,ry 45,cx 44,ry 43,cx 42,ry 41,...,cx 8,cx 7,ry 6,cx 5,cx 4,ry 3,cx 2,ry 1,ry 0,pass/fail
0,0.031760,0.069192,0.415589,0.001558,0.144150,0.045069,0.332605,0.031135,0.363904,0.083464,...,0.090143,0.105766,0.025663,0.076179,0.090917,0.001822,0.097692,0.020088,0.028875,fail
1,0.039691,0.079754,0.455009,0.001382,0.230222,0.050259,0.377962,0.033051,0.465577,0.079919,...,0.089439,0.101604,0.025071,0.076964,0.091930,0.001785,0.090402,0.018159,0.027082,fail
2,0.036232,0.061204,0.422943,0.001035,0.244386,0.036794,0.395893,0.026230,0.480526,0.077242,...,0.076359,0.085391,0.019184,0.067054,0.072643,0.001366,0.074733,0.014332,0.021666,fail
3,0.039555,0.081136,0.509161,0.001233,0.242987,0.053377,0.429887,0.024229,0.524582,0.086016,...,0.085278,0.094559,0.021929,0.070341,0.078102,0.001604,0.079551,0.016323,0.024179,fail
4,0.039816,0.077150,0.487968,0.001420,0.252737,0.053013,0.408023,0.036661,0.482763,0.088646,...,0.101975,0.115584,0.027675,0.090266,0.100659,0.001988,0.106911,0.021196,0.031351,fail
5,0.034106,0.088702,0.510343,0.001051,0.209144,0.057899,0.375503,0.032795,0.413507,0.091788,...,0.079435,0.090175,0.022082,0.068649,0.079103,0.001559,0.084466,0.016998,0.024824,fail
6,0.033535,0.067378,0.409720,0.001254,0.143176,0.048959,0.297310,0.023684,0.369951,0.072074,...,0.085115,0.096324,0.023890,0.073237,0.082197,0.001673,0.087097,0.017795,0.025356,fail
7,0.030903,0.093995,0.499566,0.001647,0.148500,0.045005,0.290135,0.028783,0.346436,0.079186,...,0.073776,0.083813,0.021328,0.065139,0.073917,0.001506,0.078673,0.015618,0.022283,fail
8,0.034126,0.047908,0.371536,0.001080,0.205884,0.028248,0.407342,0.019201,0.447898,0.073766,...,0.073508,0.084823,0.018345,0.064591,0.069451,0.001276,0.077092,0.014373,0.021018,fail
9,0.034102,0.056448,0.408664,0.000902,0.198266,0.046553,0.361543,0.029130,0.455157,0.078421,...,0.092421,0.108695,0.025850,0.078886,0.091511,0.001845,0.099718,0.020837,0.029316,fail
10,0.026296,0.057949,0.373710,0.000815,0.152806,0.037371,0.272743,0.021077,0.297306,0.066055,...,0.055466,0.060561,0.013882,0.050100,0.051338,0.000961,0.054421,0.010015,0.015599,pass
11,0.039069,0.060427,0.398835,0.001041,0.200094,0.056519,0.408445,0.024697,0.495915,0.077194,...,0.091126,0.101683,0.024543,0.080833,0.085382,0.001733,0.089664,0.017915,0.026600,pass
12,0.025075,0.047665,0.292373,0.000880,0.123927,0.033862,0.282511,0.020579,0.278985,0.062198,...,0.059162,0.066923,0.016052,0.052741,0.057043,0.001118,0.061556,0.011767,0.018330,pass
13,0.033573,0.077850,0.455796,0.001488,0.173284,0.057366,0.316042,0.038713,0.390914,0.087843,...,0.092585,0.106543,0.025498,0.078012,0.092412,0.001837,0.094432,0.019659,0.029381,pass
14,0.032688,0.066134,0.404677,0.001382,0.179552,0.056219,0.375015,0.023926,0.407202,0.075070,...,0.087035,0.099356,0.022592,0.074765,0.081350,0.001626,0.088286,0.017700,0.025228,pass
15,0.027782,0.047744,0.308268,0.000921,0.166632,0.038297,0.294355,0.023364,0.358178,0.064519,...,0.067655,0.078254,0.018621,0.058606,0.068265,0.001350,0.069733,0.014253,0.021281,pass
16,0.031764,0.062849,0.406837,0.001135,0.195334,0.040457,0.368956,0.028513,0.433735,0.083494,...,0.066808,0.079018,0.018828,0.057465,0.069510,0.001295,0.072020,0.014055,0.019937,pass
17,0.022919,0.037821,0.269474,0.000717,0.144376,0.023476,0.228959,0.017465,0.258861,0.051954,...,0.060595,0.071053,0.016288,0.051342,0.060067,0.001146,0.068388,0.013678,0.019382,pass
18,0.027700,0.046060,0.316622,0.001073,0.140306,0.026350,0.273209,0.026750,0.297682,0.057013,...,0.073876,0.087286,0.019977,0.065399,0.073350,0.001440,0.078997,0.015548,0.023540,pass
19,0.016084,0.057279,0.336537,0.000911,0.146562,0.026927,0.263835,0.014465,0.301454,0.059961,...,0.022848,0.025252,0.005267,0.019023,0.021564,0.000373,0.019987,0.003455,0.005207,pass

[[1.12529414 1.30030885 1.13649478 1.31086434 1.25151189 1.24467743
  1.16937726 1.28679229 1.20585218 1.13245066 1.10964025 1.14288281
  1.15473414 1.13533579 1.14625119 1.14443463 1.17867842 1.19340934
  1.17612754 1.12716351 1.2319287  1.14504561 1.27964742 1.17641502
  1.17926537 1.1383011  1.15097987 1.1583096  1.1612409  1.16723392
  1.14866369 1.21376551 1.15960713 1.17346276 1.18099433 1.16256831
  1.1965772  1.17496678 1.16770142 1.16904408 1.21303744 1.21303885
  1.20331527 1.19561254 1.19796031 1.23430785 1.21213201 1.21029286
  1.21997663 1.20623632 1.22487222]]
BARINEL SCORES

,ry 12,ry 49,ry 14,ry 10,ry 3,cx 29,ry 1,ry 6,ry 21,ry 26,...,ry 47,ry 33,cx 44,ry 37,cx 31,ry 43,ry 41,cx 34,ry 45,ry 30
sum,0.563967,0.562698,0.561992,0.560789,0.560462,0.560436,0.560035,0.559954,0.55972,0.559067,...,0.547979,0.545024,0.543795,0.543685,0.543369,0.543236,0.541857,0.539748,0.539635,0.524517

custom SCORES

,ry 49,ry 28,ry 10,ry 14,ry 3,ry 1,ry 12,cx 46,ry 6,ry 47,...,ry 45,cx 22,cx 39,cx 25,cx 44,cx 34,ry 37,cx 31,ry 41,ry 30
sum,0.745619,0.734834,0.730853,0.730108,0.730042,0.728919,0.728603,0.727913,0.727655,0.727561,...,0.707553,0.707437,0.705632,0.705373,0.70277,0.698795,0.698001,0.696485,0.695264,0.686059

DSTAR SCORES

,cx 48,cx 42,cx 44,cx 36,cx 39,cx 40,cx 35,cx 34,cx 27,cx 38,...,ry 0,ry 6,ry 1,ry 12,ry 14,ry 10,ry 21,ry 3,ry 47,ry 30
sum,1.486719,1.399763,1.032894,0.77026,0.595578,0.493184,0.476439,0.448908,0.440729,0.423089,...,0.00642,0.005242,0.003046,0.002869,0.002179,0.000351,0.000046,0.000027,0.000016,2.985267e-13

ERROR GATE LOCATION:
23
Now evolving the following mutant:  AddGate_y_inGap_5_.qasm

100%|██████████| 10/10 [04:15<00:00, 25.52s/it]
100%|██████████| 10/10 [04:21<00:00, 26.16s/it]

,ry 50,ry 49,cx 48,ry 47,cx 46,ry 45,cx 44,ry 43,cx 42,ry 41,...,cx 8,ry 7,cx 6,cx 5,y 4,ry 3,cx 2,ry 1,ry 0,pass/fail
0,0.042097,0.073538,0.482405,0.001240,0.216824,0.060565,0.424968,0.024566,0.497585,0.091429,...,0.124006,0.028804,0.091202,0.101214,0.056280,0.002082,0.111126,0.022735,0.032168,fail
1,0.025087,0.065520,0.398488,0.001672,0.171804,0.032226,0.301093,0.022711,0.350519,0.076446,...,0.077302,0.018464,0.056648,0.068481,0.036819,0.001335,0.071677,0.014269,0.019925,fail
2,0.035917,0.063176,0.399294,0.001193,0.187675,0.032305,0.323112,0.032459,0.398090,0.071560,...,0.111060,0.026263,0.081004,0.096403,0.052357,0.001867,0.103476,0.020843,0.030239,fail
3,0.037474,0.063267,0.399775,0.001084,0.229365,0.029861,0.432484,0.021573,0.504114,0.075334,...,0.071777,0.016730,0.057004,0.061095,0.034381,0.001166,0.061378,0.011455,0.017914,fail
4,0.029297,0.067813,0.392608,0.001278,0.146740,0.049394,0.282778,0.021846,0.357122,0.074477,...,0.077324,0.018590,0.056463,0.065756,0.036271,0.001323,0.066201,0.013702,0.020513,fail
5,0.037280,0.063411,0.411525,0.001338,0.179503,0.042535,0.371259,0.026453,0.383433,0.075124,...,0.112746,0.026191,0.085428,0.095002,0.053998,0.001885,0.102007,0.020129,0.029902,fail
6,0.026932,0.057477,0.362199,0.000932,0.152176,0.030474,0.306917,0.016959,0.348317,0.060281,...,0.067990,0.015651,0.051325,0.056569,0.031575,0.001118,0.063410,0.012122,0.017108,fail
7,0.032698,0.069060,0.406131,0.001595,0.211056,0.040717,0.347133,0.037133,0.398890,0.085588,...,0.100907,0.024492,0.073242,0.090497,0.049715,0.001788,0.092242,0.018932,0.027859,fail
8,0.035117,0.040033,0.340507,0.000866,0.178214,0.027718,0.384034,0.019720,0.494966,0.074534,...,0.092645,0.021900,0.066659,0.076003,0.040078,0.001511,0.083960,0.017076,0.023470,fail
9,0.037883,0.052482,0.384641,0.001611,0.213009,0.024141,0.420941,0.023290,0.469534,0.072742,...,0.124333,0.026891,0.089354,0.100676,0.055480,0.001969,0.114056,0.022503,0.031932,fail
10,0.024595,0.063320,0.370219,0.000915,0.147916,0.028988,0.287136,0.027119,0.333174,0.069983,...,0.071134,0.017703,0.052483,0.063674,0.034148,0.001247,0.068906,0.013700,0.019436,pass
11,0.035833,0.061036,0.399398,0.001200,0.207175,0.049804,0.414094,0.029496,0.471623,0.080268,...,0.103315,0.024497,0.079780,0.086478,0.047686,0.001735,0.096833,0.019141,0.027451,pass
12,0.033660,0.075044,0.426600,0.001195,0.215425,0.043041,0.373330,0.021633,0.425363,0.076959,...,0.077342,0.017987,0.058592,0.066273,0.037589,0.001320,0.066567,0.013317,0.020072,pass
13,0.033433,0.055501,0.394394,0.000825,0.205715,0.048140,0.373418,0.021581,0.435375,0.076533,...,0.085834,0.020261,0.068359,0.072260,0.039966,0.001422,0.078668,0.015345,0.021842,pass
14,0.024440,0.055795,0.357514,0.000984,0.141826,0.029460,0.286434,0.019022,0.285173,0.059382,...,0.054043,0.011196,0.042509,0.044640,0.025221,0.000773,0.045833,0.007900,0.012848,pass
15,0.025625,0.075883,0.428754,0.001336,0.156244,0.038226,0.262098,0.029548,0.285659,0.072256,...,0.069937,0.016333,0.052491,0.061596,0.035079,0.001211,0.061032,0.012045,0.018435,pass
16,0.026765,0.071405,0.427368,0.001020,0.205952,0.027875,0.360261,0.024395,0.402704,0.072349,...,0.056362,0.012210,0.043106,0.049294,0.026622,0.000875,0.049498,0.009154,0.014481,pass
17,0.025566,0.052379,0.290156,0.000943,0.124536,0.039700,0.256696,0.017673,0.296234,0.057950,...,0.057777,0.014592,0.046188,0.050478,0.028105,0.001010,0.050747,0.009944,0.014451,pass
18,0.030080,0.077233,0.418862,0.001477,0.131981,0.059221,0.285841,0.035659,0.332766,0.077842,...,0.094336,0.024193,0.072858,0.082209,0.046244,0.001739,0.085177,0.017512,0.025224,pass
19,0.034144,0.050034,0.345527,0.000967,0.179150,0.036255,0.351297,0.023539,0.393666,0.064223,...,0.093402,0.021319,0.072386,0.078297,0.043418,0.001494,0.085856,0.016444,0.023901,pass

[[1.2389362  1.19423239 1.21281219 1.30522023 1.21590846 1.63716526
  1.20310964 1.5051409  1.19953669 1.20696344 1.23112371 1.25616112
  1.21875537 1.27278693 1.24563033 1.34886647 1.20638711 1.29500835
  1.24693903 1.21075897 1.19896038 1.2964379  1.23277337 1.23004992
  1.24657626 1.26272861 1.33796395 1.18671766 1.33450508 1.29180148
  1.26691117 1.19902964 1.32345151 1.23652992 1.21264655 1.34358474
  1.26836689 1.28208117 1.25370103 1.24899282 1.25160967 1.32156133
  1.29501757 1.28601635 1.28756436 1.24694725 1.25918699 1.29800573
  1.31169527 1.3083403  1.28144514]]
BARINEL SCORES

,ry 1,ry 18,ry 0,cx 2,cx 8,ry 3,ry 7,cx 5,cx 9,cx 12,...,cx 32,cx 44,ry 37,cx 46,cx 39,ry 41,cx 48,ry 43,ry 49,ry 45
sum,0.563685,0.563411,0.558877,0.557876,0.557035,0.555748,0.55403,0.553344,0.552022,0.552013,...,0.529815,0.525135,0.524668,0.523658,0.523117,0.516983,0.507579,0.497024,0.491282,0.480035

custom SCORES

,ry 18,ry 1,cx 2,ry 0,cx 8,ry 3,cx 9,ry 7,cx 24,ry 15,...,cx 42,ry 37,cx 39,ry 43,cx 44,cx 46,ry 45,ry 41,cx 48,ry 49
sum,0.749823,0.748058,0.740817,0.73792,0.737378,0.736089,0.734405,0.732154,0.727426,0.727207,...,0.694639,0.691615,0.687397,0.684046,0.683083,0.682838,0.676509,0.672977,0.661478,0.637958

DSTAR SCORES

,cx 42,cx 48,cx 44,cx 36,cx 39,cx 34,cx 40,cx 27,cx 35,cx 38,...,ry 43,ry 7,ry 1,ry 13,ry 15,ry 11,ry 22,ry 3,ry 47,ry 30
sum,1.292778,1.141593,0.9752,0.666728,0.507669,0.4851,0.479206,0.451983,0.423979,0.390795,...,0.005938,0.004928,0.002979,0.0024,0.001918,0.000324,0.000045,0.000026,0.000016,3.012805e-13

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_ry_inGap_48_.qasm

100%|██████████| 10/10 [04:24<00:00, 26.49s/it]
 60%|██████    | 6/10 [02:33<01:41, 25.29s/it]