<h1 style="text-align: center;">HEISENBERG-BASED FAULT LOCALIZATION (HBFL)</h1>

<h2 style="text-align: center;">Download Initial Dependencies</h2>

In [15]:
import numpy as np
import pandas as pd
import json
import math
from tqdm import tqdm
from qiskit.quantum_info import SparsePauliOp, Operator, Pauli, Clifford
import qiskit.qasm2 as q2
from qiskit import QuantumCircuit
from IPython.display import display

from heisenbergUtilities import *

In [16]:
# from qiskit_aer import AerSimulator
# simulator = AerSimulator()

# print(simulator.available_devices())

<h2 style="text-align: center;">CONTROL PANEL</h2>

In [17]:
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
#-------------------------------------------------------------------------GENERAL PARAMETERS---------------------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
ALG_NAME = "qft"
ORIGINAL_QASM = f"{ALG_NAME}_5_qubits.qasm"                                                 #| The original algorithm QASM circuit file name.                           
ORIGINAL_QASM_FOLDER = "SBFL_circuits/MQTBench/"                                            #| The folder containing the original QASM circuit file.                    
QASM_MUTANT_FOLDER = f"SBFL_circuits/QMutBenchMutants/Mutants_{ALG_NAME}_5_qubits/"         #| The folder containing all mutants related to the original QASM circuit.  
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
#-------------------------------------------------------------------------SB-QOPS PARAMETERS---------------------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
RUNS = 10                                                                                   #| Number of times SB-QOPS will run to find a failing or passing test case.            
SHOTS = 20000                                                                               #| Number of shots for SB-QOPS to use to create the compact program specification.     
EPOCH = 80                                                                                  #| Number of epochs SB-QOPS will run to navigate the search space of test cases.       
SBQOPS_TOL = 0.1                                                                            #| Tolerance value SB-QOPS uses to determine if a test case is failing or passing.     
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
#---------------------------------------------------------------------HEISENBERG SBFL PARAMETERS-----------------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
LAMBDA_PHASE = 2                                                                        #| The hyperparameter used to weight the phase change of the Pauli propagation
LAMBDA_CHANGE = 1                                                                         #| The hyperparameter used to weight the change of string of the Pauli propagation
LAMBDA_SIMILARITY = 1                                                                       #| The hyperparameter used to weight the similarity difference between current and target Pauli
ATOL = 1e-4                                                                                 #| The tolerance value used to prune negligible magnitudes during Pauli propagation.   
MAX_TERMS = 100                                                                             #| The maximum number of terms to keep during Pauli propagation. If None, use all.     
SEARCH_STEP = 3                                                                             #| The search step size used during Pauli propagation. If None, pauli-prop uses 4.     
VERBOSE = 1                                                                                 #| A boolean value to determine if the program should print out detailed information.  
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#

Generate the linked list of all operations that take place in the inverse circuit

In [18]:
"""
LinkedListNode: A class that holds information related to a gate in a quantum circuit. 

PROPERTIES:
    - value (String): The name of the quantum gate
    - depth (int): The depth of the gate in the circuit
    - count (Int): The probability that the gate will meaningfully change the Pauli string.
    - next (LinkedListNode): The next gate in the circuit

"""

class LinkedListNode:
    def __init__(self, name="Initial", depth=0, count=0,  next=None):
        self.value = name
        self.depth = depth
        self.next = next
        self.count = count

class LinkedList:
    def __init__(self):
        self.head = None

    def append(self, name, depth):
        new_node = LinkedListNode(name, depth)
        if not self.head:
            self.head = new_node
            return
        last_node = self.head
        while last_node.next:
            last_node = last_node.next
        last_node.next = new_node

    def mark(self, depth):
        current_node = self.head
        while current_node:
            if current_node.depth == depth:
                current_node.count += 1
                return
            current_node = current_node.next

    def reset(self):
        current_node = self.head
        while current_node:
            current_node.count = 0
            current_node = current_node.next

<h3>Download MQT Benchmark circuits.</h3>

We'll start with DJ, RealAmpRandom, and GHZ since SB-QOPS caught those mutants 100% of the time for 5 qubit circuits

<h3>Generate mutants.</h3>

We'll start with mutants that add an unnecessary gate, then add mutants that replace a certain gate later.

The mutants were downloaded from QMutBench, choosing specifically mutants that added a gate anywhere with 0-10% survival scores

In [19]:
correct_circuit = load_program(ORIGINAL_QASM, ORIGINAL_QASM_FOLDER).copy()
correct_list = LinkedList()
correct_list = construct_list(correct_list, correct_circuit, inverse=False)

<h2 style="text-align: center;"> SB-QOPS </h2>

This is where we will use SB-QOPS on a provided circuit and its mutants

For a single mutant, it took about 2 minutes to generate a 20 test suite (10 fail, 10 pass) on an RTX 4090 SUPER. It can only be run on a Linux environment since the AER Simulator does not support Windows

There are 113 mutants for the DJ algorithm in use: 226 minutes or 3 3/4 hours

There are 89 mutants for the GHZ algorithm in use: 178 minutes or about 3 hours

There are 125 mutants for the RealAmpRandom algorithm in use: 250 minutes or just over 4 hours

BUT this cell should only need to be run once per algorithm with mutants under test. After it saves to the csv file at the end, this cell can be commented out as to not accidentally run it again. 

In the future if we want to test this methodology on higher qubit circuits or other algorithms, we'll likely either want to reduce the number of tests in the suite or the number of mutants we're analyzing

In [20]:
# import QOPS as qops
# from QOPS_test import get_compact_program_specification_Z
# from pathlib import Path

# ga_result = pd.DataFrame(columns=['Program',"path_to_mutant",'catch_avg','avg_fitness','failing_testcases', 'passing_testcases'])
# program_history = {}

# #program_specification = The compact program specification. SB-QOPS needs this to generate failing test cases.
# # In a public-use environment, this would be provided by the user.
# program_specification = get_compact_program_specification_Z(correct_circuit, shots=SHOTS)

# #mutants = A python list of qiskit QuantumCircuit variables with a mutation in them
# mutants = []
# mutants_names = []
# root = Path(QASM_MUTANT_FOLDER)
# for qasm_mutant in root.rglob("*.qasm"):
#     mutants.append(load_program(qasm_mutant.name, QASM_MUTANT_FOLDER))
#     mutants_names.append(qasm_mutant.name)

# for mutant_index,mutant in enumerate(mutants):
#     tester = qops.Circuit_Tester(CUT=mutant)
#     tester.set_applicable_families_Z(program_specification)
#     mutants_per_run = []
#     fitness_per_run = []
#     failing_testcases_per_run = []
#     history_per_run = []

#     print("NOW RUNNING TO FIND FAILING TESTS")
#     #For a predefined number of attempts, try to find a set of failing test cases (output is above predefined tolerance)
#     for runs in range(RUNS):
#         killed = 0
#         pauli = {}
#         fitness = 0
#         for i in range(len(tester.applicable_families)):
#             best_function,testcase, history = tester.run_mealoneplusone(i, EPOCH)
#             if best_function > SBQOPS_TOL:
#                 killed = 1
#                 pauli = testcase
#                 fitness = best_function
#                 break
#         mutants_per_run.append(killed)
#         failing_testcases_per_run.append(pauli)
#         fitness_per_run.append(fitness)
#         history_per_run.append(history)

#     avg_score = np.mean(mutants_per_run)
#     avg_fitness = np.mean(fitness_per_run)

#     #Here is our new, modified algorithm from the SB-QOPS method that attempts to find passing test cases as well. We'll need them for SBFL
#     passing_testcases_per_run = []

#     print("NOW RUNNING TO FIND PASSING TESTS")
#     for runs in range(RUNS):
#         pauli = {}
#         fitness = 0
#         for i in range(len(tester.applicable_families)):
#             best_function, testcase, history = tester.run_reverse_mealoneplusone(i,EPOCH)
#             if best_function < SBQOPS_TOL:
#                 pauli = testcase
#                 break
#         passing_testcases_per_run.append(pauli)

#     #Replace static program file with "program_name" when ready to test fully
#     """
#     ga_result: A pandas dataframe with the following columns
#         Program: Name of the mutant quantum circuit file
#         Path_To_Mutant: Path to the mutant file
#         Catch_Avg: The average number of times the mutant was identified by SB-QOPS
#         Avg_Fitness: The average fitness of the search algorithm used. Higher usually indicates higher Catch_Avg
#         Failing_Testcases: A list of dicts indicating the set of Pauli strings and the weights that should be applied to generate a failing test case
#         Passing_Testcases: A list of dicts indicating the set of Pauli strings and the weights that should be applied to generate a passing test case
#     """
#     ga_result = pd.concat([pd.DataFrame([[mutants_names[mutant_index],QASM_MUTANT_FOLDER,avg_score,avg_fitness,json.dumps(failing_testcases_per_run), json.dumps(passing_testcases_per_run)]],columns=ga_result.columns),ga_result],ignore_index=True)
#     ga_result.to_csv(f'realamprandom_ga_result', index=False)

ga_result is a slightly altered pandas Dataframe with similar structure found in SB-QOPS's results folder. The differences are changing the column "Program" to be the name of the mutant file instead of the original quantum circuit, changing "Mutant" to be the path to the mutant file instead of being an arbitrary index value, and adding a passing_testcases column that returns Pauli strings and coefficients that generate passing tests.

Now we want to run SBFL using Heisenberg evolution trees on each circuit placed in ga_result

Evolution analysis tends to take about 5 minutes for 10 failing tests on a very complex algorithm such as QNN, so about 10 minutes for 20 total tests

DJ was a relatively small algorithm with few to no branching gates, so it only ended up taking about 5-6 minutes to evolve and analyze all 113 DJ mutants

About 890 minutes for GHZ, or 14.8 hours to evolve and analyze all 89 GHZ mutants

About 1250 minutes for RealAmpRandom, or 20.8 hours to evolve and analyze all 125 RealAmpRandom mutants

The runtime of this code segment is directly tied to the depth of the circuit being analyzed and the number of 2-branching gates such as rotation or phase gates that exist in the circuit.

This is something to note in the final paper. Regardless of accuracy this methodology takes a long time to run. If results are promising, then we'll want to look into the tradeoffs between EXAM and hyperparameters to speed this up. Primarily the atol, max_terms, and search_step parameters in the evolve_pauli_exact method in HeisenbergUtilities.py

<h2 style="text-align: center;">HEISENBERG EVOLUTIONS (PAULI PROPAGATION)</h2>

In [21]:
from heisenbergTree import *

ga_result = pd.read_csv(f'{ALG_NAME}_ga_result.csv')
tarantula_sbfl_result = pd.DataFrame(columns=['Program','path_to_mutant','exam_score'])
barinel_sbfl_result = pd.DataFrame(columns=['Program','path_to_mutant','exam_score'])
dstar_sbfl_result = pd.DataFrame(columns=['Program','path_to_mutant','exam_score'])
mutant_num = 0

#For each mutant of a circuit, run the SBFL implementation
for mutant, path in zip(ga_result.loc[:,"Program"], ga_result.loc[:,"path_to_mutant"]):
    print("Now evolving the following mutant: ", mutant)

    #Extract the raw test cases found for each mutant
    desired_failing_testcases = ga_result.loc[(ga_result["Program"] == mutant), ["failing_testcases"]]
    desired_passing_testcases = ga_result.loc[(ga_result["Program"] == mutant), ["passing_testcases"]]

    dict_failing_testcases = desired_failing_testcases.to_dict()
    dict_passing_testcases = desired_passing_testcases.to_dict()

    string_failing_testcases = dict_failing_testcases['failing_testcases'][mutant_num]
    string_passing_testcases = dict_passing_testcases['passing_testcases'][mutant_num]

    list_failing_testcases = json.loads(string_failing_testcases)
    list_passing_testcases = json.loads(string_passing_testcases)

    #Remove empty tests
    raw_failing_testcases = remove_null_tests(list_failing_testcases)
    raw_passing_testcases = remove_null_tests(list_passing_testcases)

    circuit_inverse = load_program(mutant,path).copy().inverse()  # Invert to track backward evolution of the operator
    forward_mutant = load_program(mutant, path).copy()

    #Create the linked list of operations in the inverse circuit
    operation_list = LinkedList()
    operation_list = construct_list(operation_list, circuit_inverse, True)

    forward_list = LinkedList()
    forward_list = construct_list(forward_list, forward_mutant, False)

    #Create list of nodes in linked list. Somewhere down the road remove the linked list implementation. It's unnecessary and giving me a headache
    node_list = []
    node = operation_list.head
    while node:
        node_list.append(node)
        node = node.next

    #Perform Pauli propagation (Heisenberg evolution) for all test cases. Returns a dataframe with all counts for all operations
    global_frame_fail = heisenberg_evolve(circuit_inverse, 
                                          operation_list, 
                                          raw_failing_testcases, 
                                          "fail", 
                                          LAMBDA_PHASE, 
                                          LAMBDA_CHANGE, 
                                          LAMBDA_SIMILARITY, 
                                          atol = ATOL, 
                                          max_terms = MAX_TERMS, 
                                          search_step = SEARCH_STEP)
    
    global_frame_pass = heisenberg_evolve(circuit_inverse, 
                                          operation_list, 
                                          raw_passing_testcases, 
                                          "pass", 
                                          LAMBDA_PHASE, 
                                          LAMBDA_CHANGE, 
                                          LAMBDA_SIMILARITY, 
                                          atol = ATOL, 
                                          max_terms = MAX_TERMS, 
                                          search_step = SEARCH_STEP)

    global_frame = pd.concat([global_frame_fail, global_frame_pass], ignore_index=True)

    global_frame = global_frame.drop(["Initial"],axis=1)
    if VERBOSE:
        display(global_frame)

    tarantula_scores = tarantula(global_frame)
    barinel_scores = barinel(global_frame)
    dstar_scores = dstar(global_frame)

    if VERBOSE:
        print("BARINEL SCORES")
        display(barinel_scores)
        print("TARANTULA SCORES")
        display(tarantula_scores)
        print("DSTAR SCORES")
        display(dstar_scores)
    
    # Here is where analysis of the methodology begins. 
    # We first extract the position of the erroneous gate by comparing it to the original MQT gate
    # NOTE: This method is intended for single-added gates for now. Other types of mutants will require other methods later
    error_gate_location = find_erroneous_gate(forward_mutant, correct_circuit)

    if VERBOSE:
        print("ERROR GATE LOCATION:")
        print(error_gate_location)

    # Calculate the EXAM score for Barinel by counting the number of gates we would have to observe before we reach the erroneous gate.
    gates_observed = 0
    barinel_exam_score = 0
    for col_name, col_date in barinel_scores.items():
        gates_observed += 1

        #Extract depth from column name
        gate_depth = int(col_name.split()[1])

        if gate_depth == error_gate_location:
            barinel_exam_score = gates_observed/(circuit_inverse.size())
            break

    # Calculate the EXAM score for Tarantula by counting the number of gates we would have to observe before we reach the erroneous gate.
    gates_observed = 0
    tarantula_exam_score = 0
    for col_name, col_date in tarantula_scores.items():
        gates_observed += 1

        #Extract depth from column name
        gate_depth = int(col_name.split()[1])

        if gate_depth == error_gate_location:
            tarantula_exam_score = gates_observed/(circuit_inverse.size())
            break

    # Calculate the EXAM score for DStar by counting the number of gates we would have to observe before we reach the erroneous gate.
    gates_observed = 0
    dstar_exam_score = 0
    for col_name, col_date in dstar_scores.items():
        gates_observed += 1

        #Extract depth from column name
        gate_depth = int(col_name.split()[1])

        if gate_depth == error_gate_location:
            dstar_exam_score = gates_observed/(circuit_inverse.size())
            break

    # Here we store the results from the HBFL analysis for both barinel and tarantula into a csv file for later analysis.
    barinel_sbfl_result = pd.concat([pd.DataFrame([[mutant,QASM_MUTANT_FOLDER,barinel_exam_score]],columns=barinel_sbfl_result.columns),barinel_sbfl_result],ignore_index=True)
    barinel_sbfl_result.sort_values(by=['exam_score'], ascending=False)
    barinel_sbfl_result.to_csv(f'{ALG_NAME}_barinel_sbfl_result.csv', index=False)

    tarantula_sbfl_result = pd.concat([pd.DataFrame([[mutant,QASM_MUTANT_FOLDER,tarantula_exam_score]],columns=tarantula_sbfl_result.columns),tarantula_sbfl_result],ignore_index=True)
    tarantula_sbfl_result.sort_values(by=['exam_score'], ascending=False)
    tarantula_sbfl_result.to_csv(f'{ALG_NAME}_tarantula_sbfl_result.csv', index=False)

    dstar_sbfl_result = pd.concat([pd.DataFrame([[mutant,QASM_MUTANT_FOLDER,dstar_exam_score]],columns=dstar_sbfl_result.columns),dstar_sbfl_result],ignore_index=True)
    dstar_sbfl_result.sort_values(by=['exam_score'], ascending=False)
    dstar_sbfl_result.to_csv(f'{ALG_NAME}_dstar_sbfl_result.csv', index=False)

    mutant_num += 1

if VERBOSE:
    display(barinel_sbfl_result)
    display(tarantula_sbfl_result)

Now evolving the following mutant:  AddGate_swap_inGap_2_.qasm

100%|██████████| 10/10 [00:27<00:00,  2.79s/it]
100%|██████████| 10/10 [00:28<00:00,  2.85s/it]

,swap 17,swap 16,h 15,cp 14,cp 13,cp 12,cp 11,h 10,cp 9,cp 8,cp 7,h 6,cp 5,cp 4,h 3,swap 2,cp 1,h 0,pass/fail
0,0.393206,0.181854,0.248567,0.348279,0.118600,0.036331,0.012451,0.251162,0.323315,0.114945,0.037600,0.275747,0.350704,0.129532,0.322153,0.189299,0.407668,0.204961,fail
1,0.615940,0.322683,0.325194,0.491316,0.170919,0.051847,0.016656,0.355000,0.506835,0.164590,0.060238,0.366473,0.476551,0.181669,0.401399,0.270595,0.514582,0.257597,fail
2,0.642780,0.325768,0.377003,0.571659,0.193524,0.061905,0.017545,0.373172,0.477899,0.165902,0.054448,0.459401,0.577969,0.204169,0.475172,0.280655,0.545148,0.290363,fail
3,0.534969,0.343645,0.367399,0.571376,0.188290,0.065172,0.017823,0.399148,0.530893,0.195922,0.064500,0.422147,0.550027,0.189684,0.449587,0.281856,0.540144,0.277630,fail
4,0.616170,0.285635,0.254444,0.368546,0.136406,0.035294,0.012629,0.295494,0.396582,0.128379,0.044883,0.384137,0.466618,0.170183,0.348359,0.235903,0.422108,0.221783,fail
5,0.512517,0.276398,0.360068,0.539790,0.183813,0.059220,0.016964,0.396784,0.506067,0.177463,0.061126,0.440843,0.520877,0.184964,0.508357,0.238097,0.579278,0.316582,fail
6,0.567234,0.328166,0.370217,0.567947,0.188535,0.060416,0.018191,0.381126,0.487729,0.173744,0.059544,0.438053,0.532498,0.188935,0.440029,0.254755,0.512599,0.275375,fail
7,0.610808,0.287032,0.347996,0.532385,0.174686,0.055031,0.017026,0.400215,0.529095,0.177455,0.063732,0.381271,0.474646,0.173799,0.415325,0.268025,0.510209,0.265845,fail
8,0.582942,0.311960,0.330539,0.511246,0.168902,0.054658,0.016332,0.387104,0.532122,0.181227,0.063354,0.374155,0.484328,0.182087,0.431539,0.274910,0.525842,0.273019,fail
9,0.730636,0.383497,0.537270,0.835564,0.304057,0.090632,0.027054,0.509326,0.682492,0.229797,0.080442,0.575726,0.698496,0.249645,0.571013,0.351633,0.672973,0.355128,fail
10,0.203918,0.113344,0.304575,0.447832,0.164690,0.050603,0.014477,0.315919,0.402744,0.143603,0.045339,0.391545,0.486592,0.168049,0.372915,0.212672,0.402011,0.230378,pass
11,0.462817,0.233754,0.214540,0.307252,0.108305,0.032948,0.009761,0.279357,0.406611,0.136349,0.047344,0.329370,0.425491,0.162333,0.364491,0.207441,0.437028,0.227751,pass
12,0.491663,0.234682,0.352295,0.519964,0.197170,0.054674,0.016847,0.380331,0.514535,0.166394,0.059875,0.471529,0.571231,0.213991,0.452487,0.268578,0.511682,0.284448,pass
13,0.439766,0.237572,0.237672,0.356979,0.140338,0.037205,0.011733,0.315757,0.432942,0.150683,0.050735,0.407672,0.502051,0.190245,0.380963,0.241323,0.446881,0.244689,pass
14,0.451729,0.221107,0.289958,0.426076,0.155207,0.044148,0.014254,0.359983,0.480269,0.171983,0.056167,0.441410,0.557082,0.202155,0.407645,0.241812,0.463886,0.258936,pass
15,0.699631,0.353900,0.471573,0.715763,0.237103,0.074385,0.023033,0.470747,0.606649,0.206949,0.070350,0.537315,0.672769,0.242792,0.515187,0.305486,0.590099,0.322741,pass
16,0.225865,0.132333,0.285920,0.445047,0.168375,0.047726,0.014298,0.274360,0.357228,0.123284,0.041079,0.347419,0.410812,0.148978,0.307082,0.178865,0.336508,0.193043,pass
17,0.256606,0.141055,0.321245,0.484760,0.170924,0.050535,0.015558,0.331804,0.427605,0.148352,0.050595,0.394798,0.479416,0.179796,0.378792,0.193742,0.430330,0.242965,pass
18,0.406142,0.212219,0.373393,0.535703,0.181054,0.057501,0.017574,0.398195,0.522080,0.178100,0.063335,0.415834,0.476847,0.178519,0.464966,0.235784,0.521802,0.293747,pass
19,0.493071,0.267853,0.200897,0.295942,0.102584,0.030566,0.009801,0.295802,0.426789,0.152250,0.053265,0.317157,0.414098,0.160438,0.343123,0.216036,0.417269,0.220424,pass

BARINEL SCORES

,swap 16,swap 17,cp 12,cp 14,cp 11,h 15,swap 2,cp 1,cp 13,cp 7,h 10,h 3,h 0,cp 9,cp 8,cp 5,h 6,cp 4
sum,0.586517,0.584319,0.542927,0.540654,0.539586,0.535508,0.534764,0.534381,0.529243,0.522954,0.52275,0.52247,0.520843,0.52071,0.519997,0.506729,0.50391,0.500996

TARANTULA SCORES

,swap 16,swap 17,cp 12,cp 14,cp 11,h 15,swap 2,cp 1,cp 13,cp 7,h 10,h 3,h 0,cp 9,cp 8,cp 5,h 6,cp 4
sum,0.586517,0.584319,0.542927,0.540654,0.539586,0.535508,0.534764,0.534381,0.529243,0.522954,0.52275,0.52247,0.520843,0.52071,0.519997,0.506729,0.50391,0.500996

DSTAR SCORES

,swap 17,cp 14,cp 1,cp 5,cp 9,h 3,h 6,h 10,h 15,swap 16,h 0,swap 2,cp 4,cp 13,cp 8,cp 7,cp 12,cp 11
sum,2.386461,1.960425,1.879352,1.75674,1.696525,1.360856,1.206595,1.046879,0.948603,0.764088,0.598939,0.569015,0.290344,0.287345,0.252388,0.033017,0.031056,0.002938

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_h_inGap_11_.qasm

100%|██████████| 10/10 [00:36<00:00,  3.69s/it]
100%|██████████| 10/10 [00:33<00:00,  3.39s/it]

,h 17,swap 16,swap 15,h 14,cp 13,cp 12,cp 11,cp 10,h 9,cp 8,cp 7,cp 6,h 5,cp 4,cp 3,h 2,cp 1,h 0,pass/fail
0,0.430636,0.502929,0.267924,0.410844,0.770679,0.187571,0.057533,0.017224,0.374165,0.471777,0.170368,0.055270,0.410221,0.559854,0.200101,0.377390,0.492576,0.432670,fail
1,0.495712,0.459046,0.315024,0.683961,0.878252,0.294113,0.099127,0.026513,0.512988,0.595280,0.222825,0.066673,0.555166,0.737966,0.258287,0.597843,0.714372,0.550509,fail
2,0.542120,0.715934,0.375274,0.701139,0.943450,0.315953,0.100481,0.028978,0.520908,0.656487,0.225205,0.072792,0.493684,0.657554,0.237461,0.563438,0.735203,0.568848,fail
3,0.781667,0.590183,0.387249,0.831652,1.258541,0.362551,0.122549,0.031512,0.678441,0.783788,0.292514,0.090635,0.748669,0.991122,0.352890,0.793212,0.986361,0.669773,fail
4,0.607212,0.752034,0.346754,0.646531,1.006148,0.302330,0.094075,0.026868,0.526543,0.672929,0.232375,0.077271,0.484371,0.643755,0.238809,0.574848,0.783446,0.542089,fail
5,0.482303,0.468441,0.230842,0.618825,0.772280,0.261137,0.083738,0.024438,0.444803,0.524405,0.183009,0.059670,0.435322,0.553442,0.206416,0.504049,0.633413,0.539551,fail
6,0.475128,0.289550,0.203992,0.541480,0.818008,0.246274,0.081348,0.021192,0.438547,0.545817,0.205840,0.061647,0.466350,0.614520,0.213766,0.529350,0.658162,0.459600,fail
7,0.677692,0.572123,0.307382,0.721728,1.097836,0.311983,0.103338,0.028010,0.592428,0.686513,0.257314,0.080519,0.653218,0.858798,0.308697,0.673601,0.839672,0.653059,fail
8,0.581136,0.593247,0.302160,0.630193,0.928524,0.289940,0.089743,0.026057,0.510436,0.634586,0.223007,0.073334,0.580290,0.767978,0.282811,0.617794,0.797100,0.614984,fail
9,0.579498,0.562326,0.338459,0.409118,0.935428,0.183384,0.061654,0.016033,0.428923,0.535760,0.192218,0.063354,0.508400,0.690652,0.256009,0.547194,0.695555,0.555228,fail
10,0.497732,0.655434,0.430527,0.803511,0.993203,0.370694,0.118335,0.032164,0.588893,0.696888,0.252398,0.079191,0.668299,0.872461,0.312864,0.685278,0.877714,0.626848,pass
11,0.454036,0.179260,0.107231,0.518813,0.629340,0.228357,0.070782,0.020413,0.371641,0.422334,0.152143,0.049049,0.394124,0.493535,0.173492,0.398724,0.489932,0.375634,pass
12,0.380657,0.541310,0.266815,0.361986,0.783270,0.163738,0.051747,0.015083,0.379284,0.464433,0.167074,0.056242,0.455363,0.583862,0.216737,0.528045,0.687720,0.490664,pass
13,0.508591,0.679737,0.390016,0.579071,1.067785,0.275934,0.083615,0.025378,0.525966,0.685705,0.225706,0.076695,0.495496,0.659840,0.240501,0.521008,0.695384,0.574685,pass
14,0.621312,0.640987,0.386213,0.503188,1.109006,0.226482,0.075543,0.021743,0.526351,0.659853,0.236055,0.076581,0.546602,0.730242,0.271481,0.654079,0.857507,0.648855,pass
15,0.325662,0.222008,0.175816,0.447596,0.547787,0.201882,0.062177,0.017088,0.336473,0.383195,0.136627,0.043247,0.382546,0.464582,0.168530,0.395190,0.490613,0.360905,pass
16,0.497702,0.483930,0.316842,0.782499,0.918062,0.334497,0.111044,0.030062,0.560339,0.628415,0.229368,0.069527,0.537471,0.674157,0.230902,0.637456,0.777601,0.560974,pass
17,0.364905,0.374178,0.223235,0.439126,0.622445,0.189008,0.061611,0.017226,0.347765,0.391666,0.140058,0.046778,0.362872,0.451370,0.161984,0.403392,0.500654,0.393843,pass
18,0.370441,0.313146,0.215586,0.597217,0.675345,0.262270,0.086246,0.023211,0.425049,0.479556,0.176912,0.054970,0.462314,0.571595,0.205112,0.531848,0.655191,0.467992,pass
19,0.586383,0.332802,0.289025,0.644920,0.947749,0.289104,0.091274,0.025121,0.530390,0.609026,0.212393,0.071437,0.637168,0.789187,0.302336,0.653993,0.810006,0.637324,pass

BARINEL SCORES

,swap 16,h 17,cp 7,cp 13,cp 8,cp 4,cp 6,cp 3,cp 11,swap 15,h 9,h 14,h 0,cp 10,cp 12,h 5,cp 1,h 2
sum,0.554541,0.550957,0.533379,0.531496,0.529764,0.529357,0.529228,0.528032,0.523803,0.523293,0.522662,0.521794,0.520915,0.520385,0.52013,0.51914,0.517405,0.516523

TARANTULA SCORES

,swap 16,h 17,cp 7,cp 13,cp 8,cp 4,cp 6,cp 3,cp 11,swap 15,h 9,h 14,h 0,cp 10,cp 12,h 5,cp 1,h 2
sum,0.554541,0.550957,0.533379,0.531496,0.529764,0.529357,0.529228,0.528032,0.523803,0.523293,0.522662,0.521794,0.520915,0.520385,0.52013,0.51914,0.517405,0.516523

DSTAR SCORES

,cp 13,cp 1,cp 4,h 14,cp 8,h 17,h 2,swap 16,h 0,h 5,h 9,swap 15,cp 12,cp 3,cp 7,cp 11,cp 6,cp 10
sum,4.839406,3.195216,3.073183,2.448275,2.418744,2.187764,2.167147,2.101811,2.061531,1.905308,1.732618,0.738673,0.605274,0.53153,0.407469,0.07385,0.046277,0.005957

ERROR GATE LOCATION:
17
Now evolving the following mutant:  AddGate_ry_inGap_5_.qasm

100%|██████████| 10/10 [00:09<00:00,  1.04it/s]
100%|██████████| 10/10 [00:10<00:00,  1.09s/it]

,swap 17,swap 16,h 15,ry 14,cp 13,cp 12,cp 11,cp 10,h 9,cp 8,cp 7,cp 6,h 5,cp 4,cp 3,h 2,cp 1,h 0,pass/fail
0,0.471289,0.241202,0.329804,0.233207,0.0,6.379727e-19,3.144814e-19,3.072193e-22,0.205600,0.345120,0.122420,0.041068,0.254741,0.387667,0.149637,0.277814,0.400727,0.278571,fail
1,0.460521,0.251315,0.354122,0.250402,0.0,6.701632e-19,3.303493e-19,3.227208e-22,0.209453,0.322302,0.104095,0.037030,0.231293,0.314576,0.117335,0.260432,0.370511,0.294174,fail
2,0.495415,0.307425,0.431303,0.304977,0.0,7.010377e-19,3.455685e-19,3.375886e-22,0.227019,0.361288,0.120985,0.043732,0.241175,0.351264,0.134282,0.269109,0.406780,0.289223,fail
3,0.652299,0.306765,0.584668,0.413423,0.0,8.187618e-19,4.035993e-19,3.942793e-22,0.260053,0.445940,0.160011,0.051160,0.314269,0.491748,0.172671,0.342341,0.499021,0.301963,fail
4,0.570051,0.268085,0.334292,0.236380,0.0,6.886560e-19,3.394652e-19,3.316262e-22,0.182561,0.279754,0.093405,0.031655,0.229016,0.328610,0.124632,0.277129,0.405525,0.281965,fail
5,0.393397,0.235164,0.288270,0.203838,0.0,6.470089e-19,3.189357e-19,3.115708e-22,0.230255,0.358781,0.114210,0.043117,0.260054,0.345450,0.125341,0.256736,0.344052,0.296092,fail
6,0.543384,0.354365,0.346855,0.245263,0.0,7.288136e-19,3.592604e-19,3.509643e-22,0.251675,0.409961,0.138929,0.047425,0.278256,0.394104,0.136183,0.290843,0.398327,0.310217,fail
7,0.363175,0.213575,0.393749,0.278423,0.0,5.534938e-19,2.728385e-19,2.665381e-22,0.184607,0.303127,0.107369,0.035425,0.210290,0.318919,0.110159,0.216521,0.307738,0.215193,fail
8,0.425337,0.248460,0.368030,0.260236,0.0,6.193992e-19,3.053258e-19,2.982751e-22,0.238622,0.382845,0.127771,0.043110,0.253968,0.355255,0.123664,0.276245,0.368608,0.273319,fail
9,0.269355,0.211506,0.249254,0.176249,0.0,5.793664e-19,2.855921e-19,2.789971e-22,0.185005,0.303195,0.105561,0.035883,0.257371,0.364200,0.136003,0.256302,0.324361,0.268306,fail
10,0.413664,0.172955,0.275451,0.194774,0.0,5.530536e-19,2.726215e-19,2.663261e-22,0.241800,0.397160,0.128432,0.045728,0.240177,0.330020,0.125336,0.268003,0.374736,0.248175,pass
11,0.458383,0.202738,0.288213,0.203798,0.0,6.222966e-19,3.067540e-19,2.996704e-22,0.257499,0.403756,0.145875,0.046795,0.298208,0.442509,0.164410,0.305897,0.421514,0.306147,pass
12,0.631933,0.322617,0.423760,0.299643,0.0,7.476032e-19,3.685225e-19,3.600125e-22,0.320021,0.509501,0.170723,0.058373,0.313396,0.424658,0.153105,0.353558,0.477981,0.362074,pass
13,0.579673,0.271323,0.429863,0.303959,0.0,6.967164e-19,3.434384e-19,3.355077e-22,0.301339,0.480023,0.153485,0.056601,0.288617,0.389733,0.143764,0.325130,0.454151,0.335758,pass
14,0.307536,0.140758,0.204506,0.144608,0.0,3.867365e-19,1.906373e-19,1.862351e-22,0.133475,0.215793,0.080463,0.025744,0.175107,0.263098,0.103631,0.185787,0.255233,0.190635,pass
15,0.446961,0.234087,0.233476,0.165092,0.0,5.031930e-19,2.480432e-19,2.423154e-22,0.204063,0.335021,0.114979,0.038096,0.222248,0.321162,0.108836,0.231725,0.312967,0.237746,pass
16,0.449070,0.222190,0.306964,0.217057,0.0,5.021573e-19,2.475327e-19,2.418166e-22,0.186833,0.300311,0.097061,0.034597,0.224354,0.318898,0.122273,0.215603,0.289547,0.249735,pass
17,0.398995,0.195423,0.242315,0.171342,0.0,4.254982e-19,2.097445e-19,2.049010e-22,0.146233,0.257746,0.083932,0.029999,0.171350,0.256517,0.092150,0.168335,0.249983,0.173147,pass
18,0.535424,0.266228,0.257138,0.181824,0.0,5.841148e-19,2.879327e-19,2.812837e-22,0.186548,0.311021,0.103353,0.038072,0.223731,0.328773,0.119895,0.242636,0.355354,0.257590,pass
19,0.433976,0.201991,0.264824,0.187259,0.0,5.333863e-19,2.629267e-19,2.568552e-22,0.166150,0.245465,0.085858,0.029105,0.208571,0.300373,0.110787,0.241964,0.334847,0.263226,pass

BARINEL SCORES

,h 15,ry 14,cp 12,cp 11,cp 10,swap 16,cp 1,cp 4,h 2,h 0,h 5,cp 3,cp 7,cp 8,cp 6,h 9,swap 17,cp 13
sum,0.55705,0.55705,0.544671,0.544671,0.544671,0.541859,0.520358,0.519641,0.517563,0.517005,0.516816,0.516651,0.506485,0.504055,0.503996,0.503576,0.499388,NaN

TARANTULA SCORES

,h 15,ry 14,cp 12,cp 11,cp 10,swap 16,cp 1,cp 4,h 2,h 0,h 5,cp 3,cp 7,cp 8,cp 6,h 9,swap 17,cp 13
sum,0.55705,0.55705,0.544671,0.544671,0.544671,0.541859,0.520358,0.519641,0.517563,0.517005,0.516816,0.516651,0.506485,0.504055,0.503996,0.503576,0.499388,NaN

DSTAR SCORES

,swap 17,cp 1,h 15,cp 4,cp 8,h 0,h 2,swap 16,ry 14,h 5,h 9,cp 3,cp 7,cp 6,cp 12,cp 11,cp 10,cp 13
sum,1.471711,1.082009,1.047843,0.996998,0.916805,0.625037,0.591556,0.568941,0.56113,0.517808,0.389492,0.157295,0.127859,0.016127,4.415168e-36,1.072835e-36,1.023859e-42,0.0

ERROR GATE LOCATION:
14
Now evolving the following mutant:  AddGate_h_inGap_2_.qasm

100%|██████████| 10/10 [00:26<00:00,  2.67s/it]
100%|██████████| 10/10 [00:25<00:00,  2.52s/it]

,swap 17,swap 16,h 15,cp 14,cp 13,cp 12,cp 11,h 10,cp 9,cp 8,cp 7,h 6,cp 5,cp 4,h 3,h 2,cp 1,h 0,pass/fail
0,0.542038,0.315819,0.358890,0.548678,0.208815,0.057939,0.018544,0.411151,0.562195,0.186387,0.065837,0.474179,0.564572,0.212300,0.491642,0.303715,0.0,0.428051,fail
1,0.657069,0.402192,0.493281,0.757468,0.262349,0.082911,0.023400,0.474042,0.628419,0.214255,0.074276,0.535427,0.659757,0.246271,0.569419,0.368344,0.0,0.392721,fail
2,0.424055,0.258852,0.283396,0.428682,0.139768,0.046737,0.013588,0.316331,0.391757,0.140862,0.046914,0.379409,0.466943,0.172398,0.382408,0.244551,0.0,0.300574,fail
3,0.444318,0.206099,0.256287,0.396775,0.143545,0.041327,0.013497,0.304720,0.427353,0.142582,0.051864,0.365815,0.474354,0.174677,0.359811,0.223850,0.0,0.374124,fail
4,0.687011,0.391922,0.381386,0.582148,0.202520,0.064274,0.017587,0.425488,0.576137,0.204974,0.066073,0.502300,0.634787,0.230689,0.527359,0.327299,0.0,0.264176,fail
5,0.657079,0.352484,0.404562,0.616505,0.209410,0.068407,0.020007,0.417006,0.563416,0.199126,0.066215,0.441852,0.568922,0.209971,0.487957,0.296166,0.0,0.293816,fail
6,0.392516,0.214103,0.271721,0.412469,0.134446,0.043102,0.013972,0.322712,0.418872,0.150663,0.051564,0.363347,0.448117,0.163816,0.385621,0.237466,0.0,0.295769,fail
7,0.679164,0.334989,0.360762,0.561700,0.186767,0.061074,0.017330,0.380454,0.520727,0.179794,0.059210,0.375223,0.483826,0.170197,0.412907,0.250636,0.0,0.215953,fail
8,0.782124,0.403870,0.401913,0.601931,0.195154,0.064596,0.018216,0.459143,0.602927,0.208549,0.071706,0.452017,0.554994,0.200038,0.534722,0.325063,0.0,0.391404,fail
9,0.538747,0.218160,0.364564,0.586506,0.213704,0.058424,0.019482,0.378386,0.526225,0.177578,0.059747,0.405786,0.484938,0.174259,0.358258,0.224135,0.0,0.219998,fail
10,0.539881,0.279408,0.320935,0.508265,0.172274,0.054951,0.015894,0.389949,0.531359,0.188266,0.061521,0.439167,0.557956,0.207885,0.457705,0.288394,0.0,0.352844,pass
11,0.423280,0.185671,0.181473,0.270610,0.095913,0.028259,0.008597,0.203827,0.280424,0.089644,0.032227,0.253720,0.322009,0.118746,0.262287,0.155128,0.0,0.221307,pass
12,0.145638,0.099739,0.156262,0.229509,0.082834,0.025593,0.007732,0.168406,0.246987,0.085654,0.029092,0.180773,0.239134,0.089572,0.184711,0.120775,0.0,0.142760,pass
13,0.331570,0.208017,0.269792,0.385887,0.138453,0.041800,0.012347,0.293398,0.368605,0.134342,0.043305,0.376629,0.459259,0.160876,0.382382,0.246983,0.0,0.276160,pass
14,0.456244,0.295736,0.334431,0.543664,0.177578,0.059762,0.016889,0.436971,0.598650,0.208572,0.070950,0.427467,0.561437,0.194592,0.428628,0.285337,0.0,0.388925,pass
15,0.611153,0.281813,0.377953,0.589894,0.191960,0.061042,0.019341,0.400815,0.517841,0.181295,0.060586,0.461652,0.579641,0.206998,0.439346,0.284907,0.0,0.378833,pass
16,0.676976,0.355641,0.393213,0.611444,0.208741,0.064698,0.019433,0.466332,0.607262,0.217275,0.072967,0.533286,0.655762,0.226545,0.509498,0.326864,0.0,0.396824,pass
17,0.276846,0.164347,0.269411,0.390878,0.132559,0.043804,0.012318,0.308444,0.389982,0.138631,0.048452,0.343841,0.387632,0.142279,0.367866,0.248291,0.0,0.274314,pass
18,0.466369,0.217073,0.255950,0.369258,0.130377,0.037782,0.012714,0.280254,0.379224,0.122123,0.044432,0.302760,0.374774,0.138060,0.313653,0.190432,0.0,0.319018,pass
19,0.512008,0.290194,0.329326,0.508505,0.184324,0.055052,0.016149,0.413905,0.597212,0.199357,0.067007,0.422094,0.542791,0.196957,0.428723,0.277780,0.0,0.289850,pass

BARINEL SCORES

,swap 17,swap 16,cp 13,cp 14,cp 12,cp 11,h 15,h 3,cp 4,h 10,cp 7,h 2,cp 9,cp 8,h 6,cp 5,h 0,cp 1
sum,0.566583,0.565818,0.555909,0.554791,0.554661,0.553951,0.553207,0.544376,0.537406,0.536345,0.536219,0.536005,0.535975,0.535551,0.534465,0.532969,0.510917,NaN

TARANTULA SCORES

,swap 17,swap 16,cp 13,cp 14,cp 12,cp 11,h 15,h 3,cp 4,h 10,cp 7,h 2,cp 9,cp 8,h 6,cp 5,h 0,cp 1
sum,0.566583,0.565818,0.555909,0.554791,0.554661,0.553951,0.553207,0.544376,0.537406,0.536345,0.536219,0.536005,0.535975,0.535551,0.534465,0.532969,0.510917,NaN

DSTAR SCORES

,swap 17,cp 14,cp 5,cp 9,h 3,h 6,h 10,h 15,swap 16,h 0,h 2,cp 4,cp 13,cp 8,cp 7,cp 12,cp 11,cp 1
sum,2.332956,2.094095,1.943308,1.875512,1.476685,1.342664,1.132116,0.992589,0.775645,0.773777,0.631544,0.327029,0.312343,0.281639,0.035731,0.033103,0.003041,0.0

ERROR GATE LOCATION:
3
Now evolving the following mutant:  AddGate_h_inGap_3_.qasm

100%|██████████| 10/10 [00:19<00:00,  1.93s/it]
100%|██████████| 10/10 [00:20<00:00,  2.08s/it]

,swap 17,swap 16,h 15,cp 14,cp 13,cp 12,cp 11,h 10,cp 9,cp 8,cp 7,h 6,h 5,cp 4,cp 3,h 2,cp 1,h 0,pass/fail
0,0.459344,0.253543,0.481012,0.723035,0.260183,0.077872,0.022853,0.491674,0.622325,0.210251,0.074317,0.556654,0.335624,0.0,5.105604e-19,0.378022,0.470007,0.364248,fail
1,0.404582,0.141964,0.286369,0.435613,0.143315,0.045181,0.014554,0.336725,0.466887,0.160308,0.053745,0.364709,0.188545,0.0,4.109528e-19,0.293752,0.401372,0.263614,fail
2,0.388776,0.129102,0.422063,0.631803,0.221684,0.070409,0.020963,0.391243,0.518208,0.181120,0.060327,0.440288,0.257017,0.0,4.541216e-19,0.374716,0.483753,0.350801,fail
3,0.430054,0.181929,0.184291,0.279145,0.110310,0.030298,0.009106,0.315008,0.443177,0.144212,0.053799,0.374087,0.197059,0.0,3.943090e-19,0.236584,0.335927,0.247002,fail
4,0.616274,0.299391,0.386235,0.585874,0.191592,0.061441,0.019028,0.389432,0.518775,0.190381,0.062380,0.442514,0.229304,0.0,5.122087e-19,0.359411,0.502177,0.291122,fail
5,0.616137,0.341128,0.393695,0.612348,0.224158,0.065165,0.020378,0.357469,0.495242,0.168574,0.057577,0.454465,0.238174,0.0,4.953831e-19,0.269806,0.407447,0.267642,fail
6,0.410021,0.277646,0.307293,0.460197,0.154382,0.052069,0.014663,0.392720,0.542419,0.190323,0.062224,0.429553,0.226316,0.0,4.442706e-19,0.297282,0.386338,0.267595,fail
7,0.619967,0.365389,0.462482,0.723863,0.259183,0.080316,0.022819,0.448210,0.601936,0.206651,0.067528,0.494427,0.288864,0.0,5.406492e-19,0.362157,0.487299,0.325282,fail
8,0.383848,0.232694,0.282965,0.445047,0.155600,0.048670,0.014785,0.287953,0.384200,0.141793,0.047135,0.404393,0.201788,0.0,4.105301e-19,0.292781,0.399861,0.278302,fail
9,0.613267,0.299902,0.338633,0.485614,0.170199,0.053774,0.015474,0.373477,0.504466,0.176238,0.058891,0.442106,0.232079,0.0,4.710094e-19,0.375985,0.525356,0.291655,fail
10,0.606083,0.331193,0.331289,0.527801,0.188248,0.057066,0.016429,0.455830,0.650296,0.216962,0.075646,0.461551,0.255978,0.0,5.035643e-19,0.257831,0.358715,0.288202,pass
11,0.697998,0.366832,0.398065,0.630185,0.223697,0.065353,0.019649,0.482059,0.657838,0.223146,0.075111,0.533398,0.303933,0.0,5.396765e-19,0.322771,0.432388,0.330498,pass
12,0.477362,0.201354,0.315013,0.475524,0.153303,0.047749,0.015466,0.328397,0.414494,0.147855,0.047656,0.375892,0.199845,0.0,3.997915e-19,0.316901,0.422046,0.273517,pass
13,0.499117,0.270222,0.266423,0.397264,0.145105,0.042274,0.013014,0.351627,0.471406,0.163487,0.055637,0.421915,0.226064,0.0,4.428433e-19,0.319216,0.440024,0.310146,pass
14,0.605598,0.262020,0.346543,0.541047,0.197557,0.055467,0.016994,0.357698,0.454711,0.155018,0.051477,0.416156,0.248283,0.0,4.287268e-19,0.262416,0.351304,0.280936,pass
15,0.475263,0.331880,0.299572,0.449089,0.147072,0.049546,0.014440,0.423576,0.559769,0.192904,0.069265,0.466544,0.240268,0.0,5.009164e-19,0.336288,0.441612,0.380016,pass
16,0.392591,0.296414,0.212654,0.332849,0.113365,0.039542,0.010832,0.348497,0.493997,0.174249,0.057823,0.325300,0.183197,0.0,4.173251e-19,0.278884,0.370439,0.298753,pass
17,0.726490,0.342222,0.365900,0.582862,0.209649,0.057381,0.018863,0.411173,0.546325,0.179847,0.062120,0.479095,0.257315,0.0,5.072406e-19,0.306892,0.434700,0.334554,pass
18,0.275278,0.143947,0.166294,0.254626,0.097902,0.028399,0.008206,0.205059,0.306577,0.098994,0.034086,0.208905,0.122442,0.0,2.483773e-19,0.166635,0.236039,0.128596,pass
19,0.342182,0.223232,0.232137,0.356321,0.124881,0.037097,0.011485,0.319046,0.449738,0.146537,0.054284,0.318756,0.178941,0.0,3.578988e-19,0.160988,0.224059,0.228676,pass

BARINEL SCORES

,cp 12,h 15,cp 11,h 2,cp 1,cp 14,cp 13,h 6,h 5,cp 3,cp 8,h 0,h 10,cp 7,cp 9,swap 17,swap 16,cp 4
sum,0.549443,0.547164,0.545695,0.542859,0.542425,0.542042,0.541506,0.523523,0.519356,0.516553,0.510212,0.508047,0.50676,0.506273,0.504577,0.492247,0.476698,NaN

TARANTULA SCORES

,cp 12,h 15,cp 11,h 2,cp 1,cp 14,cp 13,h 6,h 5,cp 3,cp 8,h 0,h 10,cp 7,cp 9,swap 17,swap 16,cp 4
sum,0.549443,0.547164,0.545695,0.542859,0.542425,0.542042,0.541506,0.523523,0.519356,0.516553,0.510212,0.508047,0.50676,0.506273,0.504577,0.492247,0.476698,NaN

DSTAR SCORES

,cp 14,cp 9,swap 17,cp 1,h 6,h 10,h 15,h 2,h 0,swap 16,h 5,cp 13,cp 8,cp 7,cp 12,cp 11,cp 3,cp 4
sum,1.991516,1.731796,1.617837,1.411675,1.384123,1.046409,0.971656,0.824964,0.675776,0.498379,0.46945,0.308116,0.267747,0.033781,0.032677,0.003006,2.156669e-36,0.0

ERROR GATE LOCATION:
6
Now evolving the following mutant:  AddGate_h_inGap_10_.qasm

100%|██████████| 10/10 [00:31<00:00,  3.15s/it]
100%|██████████| 10/10 [00:28<00:00,  2.89s/it]

,h 17,swap 16,swap 15,h 14,cp 13,cp 12,cp 11,cp 10,h 9,cp 8,cp 7,cp 6,h 5,cp 4,cp 3,h 2,cp 1,h 0,pass/fail
0,0.565452,0.358377,0.215546,0.504098,0.564559,0.231030,0.058784,0.017758,0.453088,0.686361,0.198923,0.065996,0.419106,0.469835,0.176389,0.473943,0.601688,0.459050,fail
1,0.672490,0.630703,0.334697,0.643986,0.756853,0.314891,0.074025,0.023148,0.662245,0.954775,0.289139,0.097025,0.575903,0.672616,0.236910,0.550868,0.702709,0.606078,fail
2,0.564036,0.677617,0.341850,0.463643,0.539746,0.270113,0.057508,0.016101,0.488491,0.802393,0.218077,0.073263,0.453217,0.536168,0.192251,0.485277,0.654312,0.476586,fail
3,0.556632,0.330440,0.208508,0.563961,0.637621,0.246209,0.065535,0.019527,0.489574,0.711638,0.204992,0.068703,0.456318,0.487653,0.178386,0.480665,0.573473,0.484930,fail
4,0.615792,0.449858,0.273332,0.539051,0.606308,0.255233,0.066415,0.018253,0.562852,0.824776,0.257588,0.084837,0.485653,0.593660,0.207296,0.509619,0.651959,0.507831,fail
5,0.570802,0.443730,0.187762,0.527144,0.654611,0.285875,0.069864,0.019866,0.509197,0.727747,0.217365,0.071675,0.452990,0.514610,0.189320,0.511876,0.653067,0.446331,fail
6,0.789771,0.448841,0.241988,0.557440,0.615530,0.274226,0.065013,0.018079,0.572505,0.830807,0.254634,0.083958,0.520202,0.582766,0.208556,0.500300,0.635396,0.474834,fail
7,0.642331,0.460873,0.304942,0.523567,0.606255,0.276703,0.062314,0.018676,0.520479,0.763606,0.236686,0.078235,0.467854,0.530994,0.191595,0.419061,0.556321,0.420384,fail
8,0.677667,0.604042,0.324727,0.546241,0.658626,0.292265,0.064361,0.019264,0.589937,0.846119,0.258143,0.085995,0.522764,0.587195,0.212211,0.490252,0.617315,0.524016,fail
9,0.450813,0.321646,0.165542,0.440903,0.545844,0.227568,0.056853,0.017597,0.450989,0.640842,0.197550,0.067635,0.382500,0.453131,0.168734,0.413649,0.528173,0.448453,fail
10,0.502161,0.269896,0.186927,0.399485,0.481349,0.233925,0.053735,0.015101,0.475540,0.613380,0.215025,0.072475,0.375288,0.447993,0.163525,0.380144,0.489247,0.396925,pass
11,0.368355,0.693799,0.293435,0.488155,0.579235,0.230116,0.056973,0.017884,0.496958,0.752440,0.223053,0.075626,0.430282,0.511872,0.190691,0.482503,0.649313,0.470330,pass
12,0.246990,0.322732,0.114740,0.133261,0.176624,0.126375,0.015302,0.006059,0.295604,0.373932,0.132294,0.046583,0.222138,0.271506,0.095431,0.196653,0.259232,0.268238,pass
13,0.297268,0.360967,0.218257,0.331002,0.422887,0.163319,0.047181,0.012773,0.335595,0.457888,0.152955,0.049381,0.278110,0.341807,0.117339,0.316161,0.405288,0.298942,pass
14,0.324200,0.381895,0.237786,0.360559,0.445895,0.151544,0.047977,0.013666,0.371473,0.514372,0.172274,0.055443,0.308722,0.385594,0.133512,0.356953,0.470043,0.353600,pass
15,0.635550,0.577828,0.298479,0.705000,0.817933,0.293932,0.083897,0.024256,0.636489,0.861881,0.277816,0.093219,0.547376,0.607099,0.223679,0.555470,0.700255,0.517951,pass
16,0.563517,0.697970,0.391206,0.630281,0.727004,0.278602,0.074898,0.021941,0.694863,0.886316,0.310557,0.105196,0.560932,0.635086,0.230560,0.560797,0.729878,0.547687,pass
17,0.504485,0.266783,0.057939,0.513789,0.607601,0.213068,0.059252,0.020283,0.462078,0.603605,0.204866,0.068768,0.386651,0.438201,0.163904,0.384251,0.494126,0.431344,pass
18,0.478886,0.427178,0.243457,0.448678,0.493435,0.217150,0.051144,0.014490,0.438074,0.728740,0.191228,0.062607,0.418532,0.471837,0.171174,0.418816,0.524355,0.412023,pass
19,0.512977,0.446217,0.195396,0.499721,0.518770,0.213086,0.050354,0.016306,0.437633,0.672014,0.195066,0.064580,0.395590,0.449441,0.165876,0.413532,0.555465,0.400916,pass

BARINEL SCORES

,h 17,cp 12,h 5,cp 8,cp 4,h 2,cp 11,cp 3,h 0,h 14,cp 13,cp 1,swap 15,cp 10,h 9,cp 7,cp 6,swap 16
sum,0.579287,0.557661,0.546933,0.546462,0.543457,0.543267,0.542305,0.542291,0.541946,0.540739,0.539943,0.539174,0.537348,0.536336,0.532938,0.529259,0.528359,0.515312

TARANTULA SCORES

,h 17,cp 12,h 5,cp 8,cp 4,h 2,cp 11,cp 3,h 0,h 14,cp 13,cp 1,swap 15,cp 10,h 9,cp 7,cp 6,swap 16
sum,0.579287,0.557661,0.546933,0.546462,0.543457,0.543267,0.542305,0.542291,0.541946,0.540739,0.539943,0.539174,0.537348,0.536336,0.532938,0.529259,0.528359,0.515312

DSTAR SCORES

,cp 8,h 17,cp 13,cp 1,cp 4,h 14,h 9,h 0,h 2,h 5,swap 16,cp 12,swap 15,cp 7,cp 3,cp 6,cp 11,cp 10
sum,3.684854,2.582764,2.505838,2.495441,2.023978,1.943252,1.917686,1.667468,1.662402,1.611255,1.546269,0.589953,0.551926,0.450789,0.330145,0.056502,0.03894,0.003488

ERROR GATE LOCATION:
17
Now evolving the following mutant:  AddGate_swap_inGap_5_.qasm

100%|██████████| 10/10 [00:26<00:00,  2.67s/it]
100%|██████████| 10/10 [00:26<00:00,  2.69s/it]

,swap 17,swap 16,h 15,swap 14,cp 13,cp 12,cp 11,cp 10,h 9,cp 8,cp 7,cp 6,h 5,cp 4,cp 3,h 2,cp 1,h 0,pass/fail
0,0.503069,0.312408,0.478667,0.371261,0.871080,0.016544,0.005057,0.001428,0.259524,0.417439,0.148938,0.045402,0.394578,0.561423,0.195745,0.384795,0.499754,0.355759,fail
1,0.572041,0.300174,0.463126,0.440645,0.841468,0.016040,0.004874,0.001447,0.252404,0.407854,0.141901,0.044954,0.326061,0.463031,0.165678,0.348716,0.488864,0.301464,fail
2,0.597543,0.273840,0.317131,0.412036,0.598495,0.010338,0.003381,0.001009,0.178222,0.268142,0.093918,0.031826,0.215450,0.313745,0.113384,0.246314,0.355612,0.269273,fail
3,0.350695,0.190293,0.346334,0.387054,0.615503,0.011313,0.003800,0.001073,0.190092,0.289380,0.103898,0.034238,0.210821,0.324825,0.120829,0.243494,0.368114,0.229879,fail
4,0.438976,0.303297,0.447597,0.419107,0.804831,0.015705,0.004789,0.001361,0.244221,0.401923,0.144383,0.043197,0.391758,0.586558,0.202159,0.361031,0.492013,0.328516,fail
5,0.639049,0.319085,0.396571,0.494373,0.674542,0.012523,0.004092,0.001142,0.217664,0.322027,0.123490,0.036854,0.270158,0.418341,0.143447,0.331259,0.464017,0.304306,fail
6,0.838729,0.451791,0.476581,0.469945,0.855210,0.017004,0.004918,0.001422,0.259440,0.433868,0.148218,0.045192,0.377726,0.539973,0.185469,0.387516,0.529325,0.345509,fail
7,0.566573,0.253432,0.316715,0.419912,0.563370,0.010238,0.003179,0.001025,0.176263,0.267309,0.100630,0.033002,0.250187,0.383441,0.137232,0.240614,0.344920,0.269673,fail
8,0.564979,0.312593,0.450747,0.330854,0.822112,0.014975,0.004614,0.001441,0.242782,0.375376,0.136016,0.044566,0.297682,0.425159,0.152205,0.313854,0.438529,0.302128,fail
9,0.591602,0.325639,0.290485,0.362974,0.574036,0.009979,0.003388,0.000939,0.164482,0.257599,0.099381,0.030402,0.254609,0.383410,0.131874,0.291984,0.397317,0.288283,fail
10,0.458060,0.289211,0.289365,0.455376,0.475595,0.008650,0.003041,0.000786,0.161100,0.230374,0.091801,0.024495,0.268470,0.407470,0.130870,0.326003,0.429405,0.270259,pass
11,0.446013,0.260805,0.323178,0.456750,0.538816,0.009618,0.003196,0.000885,0.179778,0.255243,0.098892,0.029546,0.303898,0.427153,0.155610,0.336670,0.430541,0.344922,pass
12,0.532566,0.275811,0.336683,0.400787,0.610940,0.011445,0.003445,0.000998,0.187645,0.296605,0.096290,0.033042,0.313837,0.424619,0.166219,0.319767,0.461256,0.293896,pass
13,0.348597,0.205637,0.271283,0.395296,0.481725,0.009124,0.002797,0.000778,0.153907,0.244926,0.090074,0.026657,0.342127,0.490321,0.180120,0.342357,0.441248,0.338733,pass
14,0.743475,0.299482,0.385155,0.409086,0.714100,0.012786,0.004055,0.001167,0.212879,0.327903,0.118287,0.036781,0.319457,0.464626,0.162198,0.337423,0.455743,0.334473,pass
15,0.349049,0.201453,0.435076,0.413614,0.734154,0.013123,0.004195,0.001262,0.235418,0.334454,0.128528,0.040305,0.319968,0.442062,0.157887,0.384824,0.488524,0.391834,pass
16,0.402364,0.219571,0.332893,0.237681,0.599063,0.010987,0.003557,0.001073,0.176868,0.271465,0.094812,0.032816,0.195038,0.285246,0.107877,0.220127,0.332638,0.212205,pass
17,0.364055,0.264710,0.305365,0.446005,0.532118,0.009393,0.003185,0.000896,0.171184,0.250234,0.098316,0.028968,0.291546,0.435125,0.153139,0.320775,0.425017,0.322565,pass
18,0.605277,0.284399,0.402867,0.361123,0.755597,0.013728,0.004102,0.001236,0.221946,0.350464,0.122318,0.039405,0.362738,0.497857,0.183595,0.368708,0.482862,0.375730,pass
19,0.521754,0.326132,0.400399,0.411703,0.706712,0.013657,0.004250,0.001204,0.217596,0.347740,0.124539,0.038194,0.343723,0.513086,0.179789,0.347321,0.474827,0.317388,pass

BARINEL SCORES

,cp 12,cp 10,swap 17,cp 8,cp 6,cp 11,cp 13,cp 7,swap 16,h 15,h 9,swap 14,cp 4,cp 1,cp 3,h 5,h 2,h 0
sum,0.544808,0.544346,0.542745,0.541849,0.541275,0.540239,0.540085,0.538383,0.536628,0.533597,0.532506,0.507457,0.500702,0.497523,0.495315,0.494068,0.488038,0.48328

TARANTULA SCORES

,cp 12,cp 10,swap 17,cp 8,cp 6,cp 11,cp 13,cp 7,swap 16,h 15,h 9,swap 14,cp 4,cp 1,cp 3,h 5,h 2,h 0
sum,0.544808,0.544346,0.542745,0.541849,0.541275,0.540239,0.540085,0.538383,0.536628,0.533597,0.532506,0.507457,0.500702,0.497523,0.495315,0.494068,0.488038,0.48328

DSTAR SCORES

,cp 13,swap 17,cp 4,cp 1,swap 14,h 15,cp 8,h 2,swap 16,h 5,h 0,h 9,cp 3,cp 7,cp 6,cp 12,cp 11,cp 10
sum,3.228579,2.171282,1.34555,1.32928,1.206582,1.177242,0.917154,0.745629,0.733109,0.684055,0.679349,0.400613,0.206989,0.139148,0.014696,0.001793,0.000177,0.000015

ERROR GATE LOCATION:
14
Now evolving the following mutant:  AddGate_h_inGap_1_.qasm

100%|██████████| 10/10 [00:28<00:00,  2.87s/it]
100%|██████████| 10/10 [00:28<00:00,  2.81s/it]

,swap 17,swap 16,h 15,cp 14,cp 13,cp 12,cp 11,h 10,cp 9,cp 8,cp 7,h 6,cp 5,cp 4,h 3,cp 2,h 1,h 0,pass/fail
0,0.630668,0.342497,0.316982,0.512598,0.167966,0.052741,0.016378,0.458300,0.627597,0.209421,0.073462,0.466622,0.578470,0.215860,0.463643,0.588863,0.517091,0.348821,fail
1,0.441300,0.243955,0.339623,0.501311,0.184146,0.053639,0.016719,0.345595,0.463065,0.166763,0.054638,0.444581,0.575177,0.203826,0.393870,0.512224,0.381988,0.260237,fail
2,0.585911,0.302820,0.357588,0.531793,0.189210,0.055172,0.016831,0.409850,0.554005,0.176385,0.064811,0.421431,0.479961,0.183173,0.453241,0.569365,0.456833,0.315688,fail
3,0.659306,0.413608,0.479976,0.754204,0.266139,0.081240,0.023977,0.558871,0.766532,0.263661,0.088615,0.595515,0.737856,0.258213,0.574862,0.724641,0.550751,0.379652,fail
4,0.513561,0.252150,0.263061,0.386630,0.137062,0.041503,0.013036,0.378854,0.548908,0.189801,0.064359,0.437630,0.586932,0.211283,0.431759,0.553707,0.494958,0.337208,fail
5,0.305866,0.200960,0.360558,0.526829,0.186658,0.057782,0.017666,0.386788,0.543231,0.181628,0.062441,0.382087,0.465258,0.175214,0.426293,0.554780,0.404144,0.279329,fail
6,0.596124,0.330462,0.398474,0.639489,0.228361,0.064764,0.020894,0.405107,0.536377,0.193164,0.062344,0.509075,0.627836,0.228092,0.455410,0.569444,0.454407,0.313951,fail
7,0.600779,0.330476,0.278201,0.446143,0.147448,0.046617,0.014705,0.390262,0.534103,0.182539,0.065693,0.428930,0.554434,0.207435,0.421791,0.556747,0.483090,0.327497,fail
8,0.425933,0.230186,0.446447,0.680407,0.233332,0.070353,0.022648,0.394180,0.504898,0.169914,0.058033,0.435367,0.529911,0.198176,0.425519,0.535786,0.465024,0.324972,fail
9,0.462304,0.325414,0.425918,0.647901,0.231625,0.073541,0.020506,0.468178,0.634033,0.215416,0.071857,0.507432,0.610762,0.214278,0.531171,0.640549,0.474884,0.326023,fail
10,0.711999,0.344520,0.349169,0.515501,0.189477,0.055421,0.016083,0.420784,0.567149,0.192815,0.064247,0.490245,0.587339,0.216854,0.512548,0.638674,0.459056,0.321858,pass
11,0.413177,0.211886,0.380064,0.572853,0.188153,0.060141,0.019379,0.327517,0.395568,0.149562,0.048294,0.446888,0.569293,0.204544,0.434819,0.545051,0.412078,0.290624,pass
12,0.447141,0.242337,0.252843,0.379587,0.129296,0.039461,0.013314,0.302453,0.403250,0.134607,0.050148,0.351645,0.427399,0.165906,0.376905,0.482592,0.435134,0.303640,pass
13,0.424958,0.250776,0.242782,0.372549,0.144462,0.041724,0.011582,0.354259,0.469336,0.159034,0.054539,0.455290,0.527114,0.198280,0.442514,0.531088,0.443714,0.309602,pass
14,0.162609,0.134441,0.368054,0.542499,0.202790,0.060394,0.018142,0.350642,0.451689,0.167450,0.053253,0.464253,0.562777,0.202562,0.440241,0.522217,0.409894,0.298915,pass
15,0.491240,0.275913,0.308707,0.497467,0.178228,0.052946,0.015744,0.338397,0.470931,0.153910,0.054952,0.401452,0.501426,0.186156,0.368935,0.472879,0.370708,0.257643,pass
16,0.604823,0.300411,0.339291,0.530497,0.194995,0.054606,0.016626,0.397710,0.558581,0.184200,0.064797,0.415501,0.499517,0.188057,0.431618,0.577297,0.401182,0.282827,pass
17,0.504279,0.220054,0.325127,0.503581,0.182829,0.051302,0.016712,0.365430,0.493655,0.169942,0.058285,0.407862,0.483913,0.179396,0.390752,0.526957,0.370907,0.262298,pass
18,0.320635,0.164454,0.273486,0.374453,0.122680,0.039048,0.013167,0.298161,0.365833,0.131381,0.044638,0.339327,0.397191,0.148843,0.349874,0.443708,0.355911,0.251592,pass
19,0.572362,0.246800,0.360287,0.533621,0.191637,0.055614,0.017239,0.474560,0.640879,0.208984,0.075432,0.511517,0.596730,0.226431,0.512356,0.621441,0.561204,0.397311,pass

BARINEL SCORES

,swap 16,cp 9,cp 8,cp 7,cp 12,cp 14,cp 11,h 10,h 15,cp 13,swap 17,cp 5,h 1,cp 4,cp 2,h 6,h 0,h 3
sum,0.55415,0.542541,0.541217,0.539548,0.539122,0.538502,0.537167,0.536167,0.534006,0.533464,0.528786,0.527245,0.526024,0.522245,0.519887,0.519337,0.51915,0.517934

TARANTULA SCORES

,swap 16,cp 9,cp 8,cp 7,cp 12,cp 14,cp 11,h 10,h 15,cp 13,swap 17,cp 5,h 1,cp 4,cp 2,h 6,h 0,h 3
sum,0.55415,0.542541,0.541217,0.539548,0.539122,0.538502,0.537167,0.536167,0.534006,0.533464,0.528786,0.527245,0.526024,0.522245,0.519887,0.519337,0.51915,0.517934

DSTAR SCORES

,cp 9,cp 2,cp 5,cp 14,swap 17,h 1,h 6,h 3,h 10,h 15,h 0,swap 16,cp 4,cp 13,cp 8,cp 7,cp 12,cp 11
sum,2.202591,2.194447,2.179372,2.136369,1.860799,1.542363,1.499903,1.46937,1.29174,1.018622,0.795743,0.713058,0.368492,0.331661,0.325904,0.042001,0.033949,0.00331

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_h_inGap_8_.qasm

100%|██████████| 10/10 [00:26<00:00,  2.61s/it]
100%|██████████| 10/10 [00:28<00:00,  2.84s/it]

,swap 17,h 16,swap 15,h 14,cp 13,cp 12,cp 11,cp 10,h 9,cp 8,cp 7,cp 6,h 5,cp 4,cp 3,h 2,cp 1,h 0,pass/fail
0,0.568458,0.447655,0.311911,0.613694,0.752797,0.246365,0.077585,0.026205,0.601889,0.713877,0.236167,0.091733,0.614429,0.733399,0.297788,0.555723,0.874170,0.512703,fail
1,0.544494,0.486809,0.301526,0.761201,0.889930,0.294636,0.092404,0.027828,0.724063,0.782712,0.275501,0.098265,0.717884,0.755317,0.328691,0.703074,0.981496,0.629913,fail
2,0.703102,0.514012,0.387931,0.843189,1.037515,0.341503,0.102077,0.033442,0.778163,0.886339,0.297094,0.113335,0.728041,0.795462,0.359907,0.677643,1.062936,0.639745,fail
3,0.477484,0.470504,0.306047,0.531937,0.612425,0.194887,0.064053,0.024326,0.582808,0.628055,0.221713,0.081465,0.604571,0.674384,0.284660,0.571302,0.857425,0.528838,fail
4,0.568473,0.547264,0.299736,0.623123,0.737771,0.245474,0.071467,0.026976,0.693494,0.783486,0.264002,0.097613,0.581212,0.647539,0.316565,0.604435,0.908969,0.570642,fail
5,0.467955,0.442272,0.253416,0.644550,0.765947,0.267265,0.079036,0.025284,0.597986,0.721142,0.245590,0.095167,0.694043,0.781868,0.312638,0.648230,0.938270,0.576691,fail
6,0.546072,0.545566,0.374149,0.787216,0.930078,0.329519,0.097980,0.032577,0.741075,0.845261,0.284520,0.109622,0.802497,0.857355,0.365442,0.771785,1.083715,0.675130,fail
7,0.391636,0.470693,0.239194,0.583399,0.615820,0.205315,0.066725,0.021994,0.518547,0.548305,0.190202,0.079932,0.572483,0.607748,0.275308,0.674908,0.848318,0.556969,fail
8,0.507123,0.445364,0.309574,0.595680,0.688300,0.250387,0.069803,0.025117,0.691738,0.758319,0.245923,0.086504,0.706804,0.717040,0.306546,0.645078,0.919215,0.570437,fail
9,0.329574,0.458259,0.235184,0.749212,0.862576,0.310559,0.087154,0.026589,0.643303,0.710916,0.240653,0.094440,0.724030,0.759049,0.326329,0.644432,0.928680,0.589418,fail
10,0.628670,0.341031,0.367668,0.565433,0.758881,0.263903,0.080154,0.027403,0.692453,0.796672,0.277549,0.086261,0.634111,0.719950,0.290611,0.638174,0.862307,0.517545,pass
11,0.374300,0.285439,0.238080,0.536221,0.683005,0.233700,0.073931,0.021309,0.515420,0.612136,0.205109,0.072245,0.496188,0.565707,0.232720,0.508037,0.705173,0.422619,pass
12,0.662906,0.369848,0.307621,0.486584,0.622671,0.221500,0.064114,0.022719,0.549508,0.608812,0.205016,0.071710,0.529403,0.590116,0.250694,0.539704,0.720729,0.448191,pass
13,0.516259,0.447531,0.274484,0.648653,0.735296,0.255567,0.078688,0.024446,0.729425,0.825683,0.276127,0.093085,0.713509,0.788523,0.321246,0.670383,0.945149,0.581880,pass
14,0.499764,0.532751,0.243036,0.545822,0.589546,0.197728,0.059197,0.021955,0.610045,0.678518,0.224468,0.085835,0.605678,0.646310,0.285162,0.601677,0.871186,0.558657,pass
15,0.592101,0.424725,0.256166,0.883801,1.036595,0.357420,0.102271,0.027540,0.727863,0.791342,0.258524,0.096590,0.779629,0.800395,0.332846,0.698681,1.027616,0.652044,pass
16,0.728077,0.331476,0.349410,0.610413,0.789041,0.276843,0.084075,0.026069,0.636280,0.769957,0.249201,0.085364,0.657736,0.761100,0.292811,0.630456,0.873846,0.516975,pass
17,0.662177,0.578909,0.329596,1.074411,1.249216,0.419658,0.124429,0.035673,0.900900,0.989385,0.330185,0.124879,0.898892,0.956464,0.429478,0.883853,1.206445,0.787833,pass
18,0.429416,0.387431,0.232576,0.554025,0.622294,0.213329,0.063462,0.020500,0.498204,0.537155,0.177749,0.070119,0.496764,0.496096,0.226984,0.516125,0.724841,0.463152,pass
19,0.521350,0.402305,0.298466,0.618785,0.757983,0.280140,0.082532,0.025668,0.732175,0.835332,0.288165,0.092989,0.802252,0.870258,0.331530,0.706930,0.977316,0.620535,pass

BARINEL SCORES

,h 16,cp 6,cp 10,cp 3,cp 1,h 0,swap 15,h 14,h 5,cp 4,h 2,cp 13,cp 7,h 9,cp 11,cp 8,cp 12,swap 17
sum,0.540704,0.518882,0.516287,0.514575,0.513336,0.512306,0.510275,0.507884,0.504934,0.504621,0.503979,0.501545,0.500928,0.499271,0.498591,0.497754,0.496867,0.476181

TARANTULA SCORES

,h 16,cp 6,cp 10,cp 3,cp 1,h 0,swap 15,h 14,h 5,cp 4,h 2,cp 13,cp 7,h 9,cp 11,cp 8,cp 12,swap 17
sum,0.540704,0.518882,0.516287,0.514575,0.513336,0.512306,0.510275,0.507884,0.504934,0.504621,0.503979,0.501545,0.500928,0.499271,0.498591,0.497754,0.496867,0.476181

DSTAR SCORES

,cp 1,cp 13,cp 4,cp 8,h 14,h 5,h 9,h 2,h 0,swap 17,h 16,cp 3,swap 15,cp 12,cp 7,cp 6,cp 11,cp 10
sum,4.674697,3.491377,3.123982,3.120721,2.74362,2.739135,2.603935,2.574472,2.198424,1.668562,1.653266,0.775236,0.706543,0.567157,0.500863,0.082622,0.060421,0.007128

ERROR GATE LOCATION:
16
Now evolving the following mutant:  AddGate_h_inGap_5_.qasm

100%|██████████| 10/10 [00:09<00:00,  1.04it/s]
100%|██████████| 10/10 [00:10<00:00,  1.01s/it]

,swap 17,swap 16,h 15,h 14,cp 13,cp 12,cp 11,cp 10,h 9,cp 8,cp 7,cp 6,h 5,cp 4,cp 3,h 2,cp 1,h 0,pass/fail
0,0.329648,0.247363,0.289514,0.0,0.0,6.248915e-19,3.080331e-19,3.009200e-22,0.175137,0.272722,0.097787,0.031099,0.231416,0.322354,0.112634,0.278996,0.360166,0.263425,fail
1,0.599963,0.282343,0.343675,0.0,0.0,6.595335e-19,3.251095e-19,3.176020e-22,0.241559,0.407384,0.130191,0.046308,0.264341,0.386741,0.143763,0.258777,0.379593,0.278887,fail
2,0.464513,0.236964,0.476638,0.0,0.0,6.059966e-19,2.987191e-19,2.918210e-22,0.269562,0.439688,0.153014,0.052419,0.239512,0.324068,0.122945,0.282946,0.394213,0.286234,fail
3,0.567023,0.355446,0.455911,0.0,0.0,7.911270e-19,3.899770e-19,3.809716e-22,0.267253,0.436896,0.151925,0.051900,0.295392,0.415202,0.164284,0.337059,0.481896,0.354284,fail
4,0.514339,0.293687,0.418879,0.0,0.0,7.150067e-19,3.524544e-19,3.443155e-22,0.287522,0.474880,0.160738,0.057743,0.344869,0.494638,0.185269,0.331398,0.433662,0.357623,fail
5,0.401703,0.159520,0.391497,0.0,0.0,6.792708e-19,3.348388e-19,3.271066e-22,0.252422,0.418844,0.127829,0.048300,0.285956,0.398937,0.152067,0.264077,0.378781,0.296986,fail
6,0.592694,0.350194,0.385092,0.0,0.0,7.721647e-19,3.806298e-19,3.718402e-22,0.279608,0.452831,0.144658,0.052735,0.326972,0.458750,0.171577,0.315267,0.426412,0.357371,fail
7,0.382012,0.245517,0.177704,0.0,0.0,6.035934e-19,2.975345e-19,2.906638e-22,0.165990,0.251799,0.085610,0.032700,0.260305,0.360501,0.142393,0.262156,0.345780,0.316495,fail
8,0.807392,0.393951,0.527633,0.0,0.0,8.786181e-19,4.331048e-19,4.231034e-22,0.245946,0.424035,0.142833,0.048711,0.316485,0.481564,0.177702,0.338517,0.490460,0.344322,fail
9,0.300430,0.154685,0.261795,0.0,0.0,4.903049e-19,2.416902e-19,2.361091e-22,0.247554,0.390694,0.129735,0.045896,0.220295,0.292654,0.108692,0.221176,0.300551,0.241726,fail
10,0.368427,0.228256,0.297185,0.0,0.0,5.570604e-19,2.745966e-19,2.682556e-22,0.231450,0.377590,0.131824,0.043955,0.241982,0.347805,0.122059,0.236356,0.320236,0.242025,pass
11,0.439287,0.252908,0.284126,0.0,0.0,6.141299e-19,3.027283e-19,2.957377e-22,0.178567,0.251558,0.081800,0.030547,0.231857,0.315268,0.121706,0.261534,0.353872,0.305586,pass
12,0.359758,0.127535,0.400992,0.0,0.0,5.658644e-19,2.789364e-19,2.724952e-22,0.171544,0.251459,0.083184,0.030878,0.207651,0.281552,0.107916,0.259424,0.363937,0.265941,pass
13,0.192672,0.077530,0.132193,0.0,0.0,3.010537e-19,1.484010e-19,1.449741e-22,0.097867,0.146839,0.043998,0.017272,0.109994,0.136778,0.057876,0.131447,0.183022,0.152699,pass
14,0.480756,0.216270,0.277935,0.0,0.0,7.099390e-19,3.499563e-19,3.418751e-22,0.326789,0.538470,0.176603,0.064036,0.341516,0.454803,0.169859,0.343093,0.454284,0.369817,pass
15,0.746042,0.351790,0.549777,0.0,0.0,8.259202e-19,4.071280e-19,3.977265e-22,0.313853,0.500129,0.174682,0.056400,0.313716,0.469661,0.160583,0.357709,0.514130,0.329602,pass
16,0.479872,0.216924,0.221334,0.0,0.0,6.767477e-19,3.335951e-19,3.258916e-22,0.271163,0.424038,0.144196,0.050581,0.306961,0.428285,0.152826,0.331893,0.438141,0.348594,pass
17,0.752595,0.351090,0.388440,0.0,0.0,7.115670e-19,3.507589e-19,3.426591e-22,0.231041,0.387935,0.125491,0.042832,0.284574,0.438498,0.156276,0.282964,0.429887,0.281322,pass
18,0.337667,0.157248,0.298166,0.0,0.0,5.762192e-19,2.840407e-19,2.774816e-22,0.234667,0.376775,0.135052,0.046205,0.268583,0.394408,0.141109,0.269347,0.357648,0.281989,pass
19,0.735653,0.368404,0.288138,0.0,0.0,7.609842e-19,3.751185e-19,3.664562e-22,0.240469,0.367766,0.121129,0.045609,0.282716,0.405442,0.150699,0.318008,0.449617,0.377414,pass

BARINEL SCORES

,h 15,swap 16,cp 3,cp 8,cp 6,cp 7,cp 12,cp 10,cp 11,h 5,cp 4,h 9,h 0,h 2,cp 1,swap 17,h 14,cp 13
sum,0.542965,0.536675,0.524877,0.522866,0.522037,0.520918,0.519856,0.519856,0.519856,0.518232,0.517278,0.514286,0.511761,0.508676,0.508066,0.5034,NaN,NaN

TARANTULA SCORES

,h 15,swap 16,cp 3,cp 8,cp 6,cp 7,cp 12,cp 11,cp 10,h 5,cp 4,h 9,h 0,h 2,cp 1,swap 17,h 14,cp 13
sum,0.542965,0.536675,0.524877,0.522866,0.522037,0.520918,0.519856,0.519856,0.519856,0.518232,0.517278,0.514286,0.511761,0.508676,0.508066,0.5034,NaN,NaN

DSTAR SCORES

,swap 17,cp 8,cp 1,cp 4,h 15,h 0,h 2,h 5,swap 16,h 9,cp 3,cp 7,cp 6,cp 12,cp 11,cp 10,h 14,cp 13
sum,1.651731,1.156838,1.149113,1.132743,1.058016,0.740532,0.653094,0.616325,0.599014,0.481184,0.193488,0.156341,0.020986,4.651932e-36,1.130366e-36,1.078763e-42,0.0,0.0

ERROR GATE LOCATION:
15
Now evolving the following mutant:  AddGate_h_inGap_4_.qasm

100%|██████████| 10/10 [00:14<00:00,  1.48s/it]
100%|██████████| 10/10 [00:15<00:00,  1.56s/it]

,swap 17,swap 16,h 15,cp 14,cp 13,cp 12,cp 11,h 10,h 9,cp 8,cp 7,cp 6,h 5,cp 4,cp 3,h 2,cp 1,h 0,pass/fail
0,0.451330,0.263818,0.316786,0.462908,0.173341,0.052762,0.013843,0.383493,0.136072,0.0,5.852900e-19,2.884954e-19,0.347942,0.457091,0.168619,0.367963,0.476190,0.328566,fail
1,0.645021,0.318136,0.425965,0.637112,0.235619,0.069089,0.020224,0.496314,0.182180,0.0,6.854985e-19,3.378983e-19,0.333833,0.431481,0.147250,0.349029,0.466315,0.313526,fail
2,0.496823,0.249599,0.326038,0.479419,0.158793,0.049636,0.016546,0.382837,0.137485,0.0,5.906874e-19,2.911556e-19,0.348492,0.463744,0.178308,0.325936,0.436144,0.352678,fail
3,0.672432,0.379309,0.358330,0.528118,0.177338,0.056465,0.016680,0.437475,0.150345,0.0,6.446781e-19,3.177582e-19,0.310639,0.410027,0.159240,0.372665,0.504118,0.352643,fail
4,0.474832,0.182316,0.282826,0.412377,0.144618,0.043217,0.013328,0.359775,0.121750,0.0,5.150874e-19,2.538917e-19,0.316723,0.408312,0.151745,0.278753,0.349361,0.308924,fail
5,0.700154,0.349177,0.450502,0.675563,0.239977,0.073753,0.020875,0.527137,0.190689,0.0,7.064746e-19,3.482296e-19,0.375699,0.499615,0.182846,0.398123,0.515142,0.374926,fail
6,0.290396,0.195152,0.282539,0.435518,0.155927,0.045823,0.014461,0.304424,0.120718,0.0,4.124426e-19,2.033059e-19,0.267726,0.333894,0.124797,0.209727,0.283661,0.203637,fail
7,0.630561,0.291909,0.253428,0.403560,0.137648,0.041367,0.012821,0.357752,0.107852,0.0,5.714854e-19,2.816841e-19,0.240541,0.310079,0.120133,0.243981,0.352840,0.272531,fail
8,0.679041,0.252625,0.274671,0.416544,0.141765,0.041017,0.013506,0.387395,0.116815,0.0,5.539138e-19,2.730184e-19,0.256627,0.331212,0.129315,0.274649,0.383408,0.285178,fail
9,0.745074,0.382511,0.449584,0.656177,0.225618,0.071472,0.020289,0.480193,0.190322,0.0,6.717421e-19,3.310971e-19,0.359897,0.451654,0.171888,0.401909,0.521083,0.378904,fail
10,0.467681,0.251520,0.361298,0.543563,0.196728,0.057152,0.017648,0.389108,0.154829,0.0,5.424953e-19,2.674059e-19,0.343938,0.414157,0.158259,0.331287,0.444342,0.319065,pass
11,0.730933,0.338014,0.351173,0.556614,0.196356,0.060065,0.017097,0.402738,0.150493,0.0,6.146872e-19,3.029772e-19,0.313912,0.397119,0.151479,0.360046,0.491349,0.331776,pass
12,0.428294,0.258602,0.411404,0.596243,0.209166,0.064868,0.019170,0.346733,0.175514,0.0,5.140101e-19,2.533658e-19,0.323766,0.408013,0.148672,0.340818,0.449797,0.303193,pass
13,0.535525,0.330330,0.400672,0.607055,0.230608,0.063257,0.020814,0.434133,0.170729,0.0,6.166025e-19,3.039275e-19,0.314390,0.375773,0.143565,0.328088,0.467060,0.335047,pass
14,0.239467,0.162845,0.230092,0.340778,0.130625,0.038806,0.010654,0.310336,0.099856,0.0,4.131289e-19,2.036376e-19,0.253312,0.338319,0.119975,0.269774,0.353703,0.243405,pass
15,0.359374,0.201415,0.292007,0.441035,0.148952,0.048281,0.014579,0.302117,0.122292,0.0,4.652096e-19,2.293109e-19,0.209551,0.284033,0.103166,0.250259,0.331451,0.265703,pass
16,0.267720,0.187512,0.274828,0.408709,0.144045,0.045329,0.013195,0.374159,0.118880,0.0,5.003390e-19,2.466218e-19,0.257499,0.330032,0.127512,0.288049,0.362921,0.320917,pass
17,0.631565,0.427353,0.470663,0.722092,0.254985,0.077645,0.022981,0.503703,0.198616,0.0,7.117087e-19,3.508091e-19,0.427563,0.555097,0.209158,0.398474,0.552096,0.372327,pass
18,0.530614,0.250731,0.353254,0.543279,0.179460,0.055064,0.017251,0.445433,0.148412,0.0,5.911454e-19,2.913793e-19,0.304341,0.415697,0.150275,0.297472,0.396187,0.322001,pass
19,0.606134,0.334188,0.209541,0.332072,0.118768,0.034463,0.011387,0.348930,0.088472,0.0,5.599925e-19,2.760053e-19,0.207753,0.275564,0.112864,0.242243,0.358150,0.291090,pass

BARINEL SCORES

,swap 17,cp 4,cp 3,cp 7,cp 6,h 5,h 10,swap 16,h 2,h 0,h 15,cp 1,h 9,cp 14,cp 12,cp 13,cp 11,cp 8
sum,0.546696,0.519219,0.518455,0.51779,0.51779,0.516527,0.516265,0.510883,0.509182,0.505337,0.504851,0.504779,0.504534,0.500777,0.49985,0.497355,0.496635,NaN

TARANTULA SCORES

,swap 17,cp 4,cp 3,cp 7,cp 6,h 5,h 10,swap 16,h 2,h 0,h 15,cp 1,h 9,cp 14,cp 12,cp 13,cp 11,cp 8
sum,0.546696,0.519219,0.518455,0.51779,0.51779,0.516527,0.516265,0.510883,0.509182,0.505337,0.504851,0.504779,0.504534,0.500777,0.49985,0.497355,0.496635,NaN

DSTAR SCORES

,swap 17,cp 14,cp 1,h 10,cp 4,h 15,h 2,h 5,h 0,swap 16,cp 13,cp 3,h 9,cp 12,cp 11,cp 7,cp 6,cp 8
sum,2.262163,1.728429,1.29437,1.22303,1.216945,0.876153,0.792432,0.769813,0.767558,0.643959,0.271506,0.206005,0.185051,0.028126,0.0026,3.525153e-36,8.564603e-37,0.0

ERROR GATE LOCATION:
10
Now evolving the following mutant:  AddGate_ry_inGap_1_.qasm

100%|██████████| 10/10 [00:28<00:00,  2.83s/it]
100%|██████████| 10/10 [00:28<00:00,  2.89s/it]

,swap 17,swap 16,h 15,cp 14,cp 13,cp 12,cp 11,h 10,cp 9,cp 8,cp 7,h 6,cp 5,cp 4,h 3,cp 2,h 1,ry 0,pass/fail
0,0.657977,0.351291,0.496995,0.770071,0.269320,0.082569,0.024797,0.462714,0.617781,0.214263,0.069900,0.527590,0.653652,0.231586,0.524656,0.677909,0.445815,0.427240,fail
1,0.415652,0.283156,0.503847,0.728027,0.255028,0.079943,0.022568,0.474883,0.591849,0.207475,0.066367,0.544232,0.631961,0.225302,0.606073,0.704408,0.520499,0.496282,fail
2,0.748082,0.374161,0.435020,0.676677,0.240010,0.074396,0.020338,0.489062,0.679870,0.228710,0.078585,0.539238,0.678701,0.247821,0.562163,0.717593,0.484090,0.462837,fail
3,0.564499,0.336767,0.403830,0.635987,0.216385,0.067473,0.020726,0.434281,0.569930,0.204969,0.067005,0.480143,0.605178,0.210653,0.471691,0.599771,0.453762,0.433496,fail
4,0.680046,0.384567,0.486880,0.739505,0.248343,0.080327,0.022802,0.486988,0.629755,0.215612,0.075014,0.526742,0.641374,0.228237,0.568386,0.692987,0.540975,0.515697,fail
5,0.552172,0.308550,0.433794,0.655073,0.235904,0.066403,0.021752,0.429110,0.558227,0.190430,0.065059,0.532022,0.652592,0.238676,0.477842,0.603866,0.504418,0.481995,fail
6,0.739776,0.394449,0.477563,0.724739,0.254597,0.075293,0.022332,0.546114,0.730697,0.250706,0.085448,0.569049,0.690921,0.243726,0.583803,0.719407,0.554430,0.529290,fail
7,0.410568,0.249597,0.320751,0.474486,0.159020,0.050537,0.016253,0.347781,0.424085,0.147095,0.050026,0.420694,0.505502,0.193127,0.425477,0.519561,0.492422,0.468308,fail
8,0.693312,0.347406,0.425344,0.646887,0.220674,0.066247,0.020778,0.458300,0.600229,0.203527,0.072011,0.504393,0.622782,0.228699,0.481652,0.620513,0.486531,0.465100,fail
9,0.592596,0.349656,0.516013,0.792012,0.263395,0.081266,0.025702,0.516455,0.694855,0.234848,0.079451,0.530808,0.660899,0.243629,0.544479,0.703201,0.510553,0.488908,fail
10,0.559016,0.275730,0.402246,0.579616,0.209748,0.062815,0.018654,0.419311,0.541118,0.188545,0.064376,0.508852,0.609885,0.229284,0.544298,0.669495,0.515343,0.493679,pass
11,0.553522,0.271993,0.402243,0.568193,0.190052,0.058417,0.019395,0.464142,0.594096,0.204823,0.074916,0.533516,0.628945,0.243388,0.558561,0.684808,0.603942,0.577771,pass
12,0.555238,0.231005,0.407765,0.622311,0.215778,0.060186,0.020603,0.391555,0.498617,0.166616,0.057235,0.435486,0.498849,0.184090,0.410358,0.526278,0.409266,0.392356,pass
13,0.315760,0.165861,0.237903,0.353126,0.120838,0.037407,0.011636,0.282054,0.384262,0.135464,0.047490,0.299489,0.370405,0.133978,0.291583,0.371454,0.281223,0.270557,pass
14,0.410943,0.198937,0.230442,0.347605,0.130166,0.039592,0.011687,0.253053,0.355634,0.120974,0.040011,0.353691,0.471984,0.174038,0.363453,0.484368,0.345992,0.332368,pass
15,0.672521,0.337478,0.454874,0.694848,0.238848,0.073994,0.021834,0.510167,0.713712,0.245435,0.083250,0.541861,0.688976,0.254801,0.528950,0.672481,0.502352,0.483116,pass
16,0.432630,0.237314,0.383059,0.567046,0.194835,0.059729,0.019762,0.355231,0.477414,0.167536,0.057107,0.415363,0.523400,0.196362,0.410954,0.538687,0.414698,0.398979,pass
17,0.544334,0.270462,0.287724,0.441871,0.139846,0.046877,0.013471,0.349534,0.459055,0.176836,0.055631,0.382968,0.497966,0.173550,0.413937,0.527524,0.367568,0.353218,pass
18,0.502495,0.299144,0.341431,0.538224,0.179330,0.054927,0.017960,0.438354,0.600698,0.209251,0.073573,0.467248,0.589265,0.213224,0.409260,0.520246,0.466740,0.447236,pass
19,0.627942,0.323718,0.278863,0.433883,0.163438,0.046761,0.013765,0.392893,0.575785,0.190315,0.066204,0.390710,0.492961,0.176579,0.384425,0.520157,0.379831,0.364763,pass

BARINEL SCORES

,cp 12,cp 14,cp 13,h 15,swap 16,cp 11,h 3,h 10,h 6,cp 2,cp 5,cp 9,swap 17,h 1,cp 8,ry 0,cp 4,cp 7
sum,0.572619,0.570755,0.56993,0.567714,0.56409,0.563701,0.548653,0.546424,0.544493,0.543219,0.541435,0.539694,0.539196,0.538066,0.537382,0.536874,0.536546,0.53352

TARANTULA SCORES

,cp 12,cp 14,cp 13,h 15,swap 16,cp 11,h 3,h 10,h 6,cp 2,cp 5,cp 9,swap 17,h 1,cp 8,ry 0,cp 4,cp 7
sum,0.572619,0.570755,0.56993,0.567714,0.56409,0.563701,0.548653,0.546424,0.544493,0.543219,0.541435,0.539694,0.539196,0.538066,0.537382,0.536874,0.536546,0.53352

DSTAR SCORES

,cp 14,cp 2,cp 5,cp 9,swap 17,h 3,h 6,h 1,ry 0,h 10,h 15,swap 16,cp 13,cp 4,cp 8,cp 12,cp 7,cp 11
sum,3.091957,2.772925,2.617691,2.44578,2.415855,1.922552,1.868892,1.745298,1.611503,1.557589,1.50823,0.905646,0.473758,0.43832,0.372704,0.049791,0.047316,0.004676

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_h_inGap_7_.qasm

100%|██████████| 10/10 [00:35<00:00,  3.56s/it]
100%|██████████| 10/10 [00:36<00:00,  3.62s/it]

,swap 17,h 16,swap 15,h 14,cp 13,cp 12,cp 11,cp 10,h 9,cp 8,cp 7,cp 6,h 5,cp 4,cp 3,h 2,cp 1,h 0,pass/fail
0,0.396639,0.471000,0.218573,0.424751,0.526590,0.190548,0.077890,0.017464,0.422611,0.505209,0.228409,0.054112,0.422037,0.673288,0.189948,0.384489,0.484914,0.408335,fail
1,0.467883,0.337194,0.238292,0.325238,0.422692,0.160465,0.059366,0.013349,0.433732,0.542970,0.214410,0.063536,0.458522,0.598420,0.198075,0.369396,0.460865,0.387548,fail
2,0.238124,0.344763,0.097296,0.413643,0.482264,0.170213,0.052028,0.015328,0.362920,0.402763,0.179584,0.045629,0.414690,0.561726,0.178503,0.361137,0.415395,0.389424,fail
3,0.597002,0.578742,0.239203,0.595511,0.668360,0.232455,0.082707,0.020908,0.553336,0.638206,0.285681,0.072620,0.598434,0.825185,0.266245,0.521955,0.623805,0.573446,fail
4,0.553892,0.400149,0.308736,0.552901,0.627927,0.218774,0.068221,0.019409,0.607724,0.733031,0.279322,0.085729,0.600429,0.847368,0.272979,0.520159,0.638750,0.530269,fail
5,0.674975,0.517347,0.328591,0.457191,0.501120,0.157517,0.068568,0.014938,0.480454,0.556189,0.262138,0.061852,0.479464,0.742864,0.220862,0.444936,0.539079,0.482254,fail
6,0.544405,0.466312,0.270796,0.524240,0.599629,0.216366,0.075714,0.018560,0.453468,0.534883,0.256117,0.060880,0.524912,0.763404,0.238876,0.462807,0.558754,0.453194,fail
7,0.375795,0.447277,0.228026,0.479349,0.585210,0.220951,0.071454,0.018854,0.459578,0.524577,0.223249,0.059409,0.571697,0.699442,0.242504,0.462722,0.532832,0.519226,fail
8,0.656147,0.534956,0.331593,0.661700,0.746048,0.250050,0.081464,0.022077,0.534098,0.604748,0.272529,0.068556,0.563243,0.805209,0.261250,0.498390,0.608001,0.491834,fail
9,0.657748,0.436155,0.341008,0.523356,0.680125,0.247958,0.091277,0.021291,0.551356,0.668902,0.272965,0.076677,0.567143,0.806842,0.255197,0.481453,0.610550,0.503168,fail
10,0.368482,0.368493,0.241151,0.337557,0.384770,0.132506,0.053433,0.011845,0.428895,0.520175,0.206049,0.058517,0.375660,0.581998,0.174052,0.338276,0.413967,0.388811,pass
11,0.434073,0.289703,0.255521,0.535117,0.689466,0.248219,0.070514,0.021654,0.439322,0.536389,0.211905,0.061556,0.511061,0.666003,0.231404,0.404503,0.513485,0.399411,pass
12,0.488424,0.414187,0.253861,0.590254,0.673780,0.242624,0.073379,0.020443,0.479239,0.532492,0.245174,0.056932,0.564684,0.732073,0.241284,0.471518,0.530475,0.460570,pass
13,0.588453,0.467414,0.289907,0.566330,0.653933,0.232372,0.077242,0.019087,0.543112,0.628361,0.271332,0.067855,0.532004,0.826896,0.236506,0.484703,0.585600,0.451522,pass
14,0.629890,0.427769,0.341558,0.492685,0.591418,0.192255,0.069539,0.017120,0.500938,0.607771,0.255446,0.069587,0.540771,0.720250,0.252027,0.450480,0.557456,0.449622,pass
15,0.307721,0.328351,0.173145,0.412855,0.487180,0.160954,0.055571,0.015382,0.430284,0.519315,0.195302,0.057310,0.394108,0.590375,0.190844,0.344320,0.444581,0.312987,pass
16,0.469867,0.351484,0.249729,0.455691,0.580065,0.191011,0.070852,0.018425,0.412944,0.481019,0.223944,0.057480,0.485040,0.640052,0.226216,0.395111,0.487915,0.411001,pass
17,0.428112,0.414849,0.218416,0.577297,0.723872,0.244013,0.080969,0.023178,0.474793,0.551390,0.241716,0.062400,0.464157,0.702565,0.212976,0.415353,0.513496,0.435154,pass
18,0.654285,0.511483,0.353587,0.737716,0.849401,0.282964,0.087921,0.025319,0.660264,0.739093,0.305971,0.082973,0.598891,0.901168,0.264314,0.556959,0.646741,0.552328,pass
19,0.314954,0.393737,0.185693,0.465407,0.582014,0.211587,0.070781,0.017711,0.478358,0.553872,0.212702,0.060568,0.493341,0.665416,0.218270,0.412580,0.491569,0.405299,pass

BARINEL SCORES

,h 16,h 0,swap 17,cp 1,h 2,h 5,cp 7,cp 4,cp 3,cp 11,cp 6,swap 15,cp 8,h 9,cp 12,h 14,cp 10,cp 13
sum,0.533314,0.526206,0.524289,0.513495,0.513303,0.511853,0.510824,0.510346,0.508371,0.506424,0.505382,0.503829,0.501828,0.500573,0.491292,0.489484,0.489274,0.484409

TARANTULA SCORES

,h 16,h 0,swap 17,cp 1,h 2,h 5,cp 7,cp 4,cp 3,cp 11,cp 6,swap 15,cp 8,h 9,cp 12,h 14,cp 10,cp 13
sum,0.533314,0.526206,0.524289,0.513495,0.513303,0.511853,0.510824,0.510346,0.508371,0.506424,0.505382,0.503829,0.501828,0.500573,0.491292,0.489484,0.489274,0.484409

DSTAR SCORES

,cp 4,cp 13,cp 8,cp 1,swap 17,h 5,h 14,h 9,h 0,h 16,h 2,swap 15,cp 7,cp 3,cp 12,cp 11,cp 6,cp 10
sum,3.15017,2.103195,2.081763,1.972509,1.815042,1.807918,1.620244,1.590271,1.573962,1.47172,1.423381,0.538982,0.494981,0.441138,0.351398,0.049578,0.039605,0.003257

ERROR GATE LOCATION:
16
Now evolving the following mutant:  AddGate_h_inGap_12_.qasm

100%|██████████| 10/10 [00:19<00:00,  1.91s/it]
100%|██████████| 10/10 [00:19<00:00,  1.91s/it]

,h 17,swap 16,swap 15,h 14,cp 13,cp 12,cp 11,cp 10,h 9,cp 8,cp 7,cp 6,h 5,cp 4,cp 3,h 2,cp 1,h 0,pass/fail
0,0.388010,0.515738,0.299233,0.039607,0.053835,0.018174,0.004907,0.001597,0.305235,0.464106,0.157682,0.057485,0.359695,0.491816,0.179846,0.347993,0.459488,0.409400,fail
1,0.632358,0.560350,0.236135,0.041776,0.045550,0.014266,0.004021,0.001442,0.334894,0.533957,0.185301,0.060963,0.358336,0.521192,0.193363,0.352430,0.513855,0.355824,fail
2,0.665313,0.458697,0.247033,0.061223,0.063297,0.021655,0.006179,0.001836,0.218525,0.298910,0.092921,0.038900,0.328259,0.445988,0.167455,0.342977,0.476713,0.407374,fail
3,0.488437,0.293770,0.189317,0.054112,0.059584,0.022298,0.006037,0.001577,0.251658,0.371283,0.127087,0.047782,0.286309,0.357751,0.142524,0.327526,0.448424,0.386294,fail
4,0.559873,0.683330,0.347026,0.024530,0.026926,0.009506,0.002811,0.001475,0.250108,0.408978,0.139038,0.045668,0.277936,0.406411,0.144414,0.346151,0.521032,0.282958,fail
5,0.642419,0.578002,0.280200,0.042292,0.050825,0.016013,0.004462,0.001572,0.352028,0.543197,0.180468,0.063997,0.386824,0.530796,0.192722,0.386169,0.511575,0.422436,fail
6,0.612097,0.428461,0.216823,0.047833,0.050101,0.016757,0.005060,0.001490,0.251966,0.365408,0.127847,0.045156,0.307619,0.426165,0.169329,0.342385,0.480265,0.369133,fail
7,0.596801,0.609483,0.397985,0.044422,0.056115,0.019002,0.005310,0.001927,0.319781,0.498325,0.161656,0.057462,0.366433,0.489185,0.195425,0.384670,0.531249,0.432500,fail
8,0.613297,0.640632,0.293236,0.052542,0.062577,0.020537,0.005502,0.001739,0.314586,0.457035,0.159120,0.054795,0.339441,0.449441,0.167693,0.408951,0.553695,0.436289,fail
9,0.726150,0.714701,0.361176,0.048740,0.055837,0.020771,0.005313,0.001991,0.393009,0.605088,0.207567,0.078081,0.458390,0.627438,0.233591,0.460281,0.615439,0.527858,fail
10,0.305800,0.325669,0.133983,0.027098,0.031296,0.010228,0.003014,0.000924,0.224602,0.343935,0.116581,0.041515,0.251508,0.343391,0.132090,0.256511,0.342860,0.287572,pass
11,0.460907,0.489608,0.201314,0.043819,0.046414,0.017148,0.004523,0.001416,0.269008,0.437083,0.134040,0.053017,0.338110,0.448516,0.174915,0.326699,0.468135,0.368713,pass
12,0.625095,0.331356,0.254722,0.054363,0.059798,0.021357,0.006337,0.001843,0.307274,0.454914,0.161340,0.057259,0.365739,0.478542,0.192198,0.406841,0.546732,0.442061,pass
13,0.445210,0.387012,0.191991,0.047443,0.052824,0.018221,0.005403,0.001543,0.350360,0.541020,0.178066,0.064128,0.370705,0.483521,0.188641,0.377444,0.504307,0.420313,pass
14,0.591922,0.489049,0.244827,0.039347,0.041174,0.013682,0.004163,0.001434,0.242147,0.362397,0.122499,0.042622,0.302251,0.437859,0.167211,0.313996,0.460283,0.323480,pass
15,0.499100,0.657574,0.322093,0.050123,0.060785,0.020593,0.005529,0.001780,0.383017,0.593665,0.191455,0.071724,0.385195,0.520411,0.208889,0.388605,0.561601,0.458400,pass
16,0.549426,0.259951,0.216678,0.023905,0.025229,0.008640,0.002837,0.001142,0.207794,0.317485,0.110942,0.034072,0.301959,0.425746,0.154175,0.307449,0.402580,0.275181,pass
17,0.341477,0.651840,0.351850,0.035082,0.049169,0.015626,0.004596,0.001643,0.320428,0.479662,0.170165,0.057382,0.303854,0.425709,0.157189,0.354909,0.502316,0.371517,pass
18,0.456403,0.376446,0.263719,0.036589,0.047040,0.016053,0.004656,0.001544,0.239368,0.348222,0.118486,0.043505,0.312586,0.413292,0.155198,0.338996,0.448951,0.366251,pass
19,0.325509,0.797217,0.423426,0.041113,0.059576,0.020886,0.005262,0.001931,0.380331,0.592029,0.194514,0.076445,0.405542,0.568157,0.211950,0.377143,0.528213,0.471139,pass

BARINEL SCORES

,h 17,swap 16,h 14,cp 13,cp 12,swap 15,cp 10,h 2,cp 1,cp 11,h 0,cp 4,h 5,cp 7,cp 3,h 9,cp 8,cp 6
sum,0.56289,0.535001,0.533994,0.525724,0.52423,0.524079,0.522687,0.517553,0.517502,0.517097,0.515704,0.510818,0.509681,0.506684,0.506221,0.505701,0.504207,0.503948

TARANTULA SCORES

,h 17,swap 16,h 14,cp 13,cp 12,swap 15,cp 10,h 2,cp 1,cp 11,h 0,cp 4,h 5,cp 7,cp 3,h 9,cp 8,cp 6
sum,0.56289,0.535001,0.533994,0.525724,0.52423,0.524079,0.522687,0.517553,0.517502,0.517097,0.515704,0.510818,0.509681,0.506684,0.506221,0.505701,0.504207,0.503948

DSTAR SCORES

,h 17,swap 16,cp 1,cp 4,cp 8,h 0,h 2,h 5,h 9,swap 15,cp 3,cp 7,cp 6,cp 13,h 14,cp 12,cp 11,cp 10
sum,2.404154,2.036141,1.769597,1.548711,1.428343,1.178228,1.017694,0.902394,0.692555,0.652647,0.271757,0.205909,0.028726,0.026281,0.020091,0.003152,0.000245,0.000028

ERROR GATE LOCATION:
17
Now evolving the following mutant:  AddGate_cswap_inGap_5_.qasm

100%|██████████| 10/10 [00:48<00:00,  4.84s/it]
100%|██████████| 10/10 [00:47<00:00,  4.77s/it]

,swap 17,swap 16,h 15,cswap 14,cp 13,cp 12,cp 11,cp 10,h 9,cp 8,cp 7,cp 6,h 5,cp 4,cp 3,h 2,cp 1,h 0,pass/fail
0,0.371589,0.211176,0.379713,0.729197,0.144655,0.151843,0.015334,0.004951,0.245488,0.388165,0.126655,0.042901,0.262152,0.343633,0.128288,0.239487,0.352127,0.225785,fail
1,0.641726,0.345489,0.365642,1.127789,0.194401,0.158607,0.021273,0.006207,0.360715,0.536935,0.186312,0.063281,0.365100,0.505070,0.181573,0.344300,0.499254,0.368000,fail
2,0.522917,0.296222,0.408516,0.887231,0.153539,0.151934,0.016380,0.004986,0.247248,0.386099,0.128773,0.041595,0.277959,0.384520,0.137568,0.252288,0.362266,0.244535,fail
3,0.611448,0.296704,0.402216,1.032984,0.195458,0.162962,0.020243,0.006267,0.312709,0.486411,0.158603,0.053717,0.306357,0.410167,0.149195,0.286860,0.419763,0.300229,fail
4,0.822408,0.390650,0.440325,1.222336,0.207089,0.171428,0.021702,0.006685,0.315102,0.483942,0.166170,0.056262,0.322422,0.452046,0.168192,0.307184,0.489344,0.288817,fail
5,0.587858,0.269128,0.439730,1.012772,0.186868,0.158448,0.020286,0.006102,0.312828,0.493603,0.162160,0.054219,0.300471,0.414048,0.148436,0.294379,0.414645,0.310297,fail
6,0.714379,0.385026,0.469552,1.465279,0.254864,0.189157,0.026044,0.008096,0.358164,0.565770,0.189808,0.062894,0.362021,0.504194,0.182484,0.351414,0.538288,0.347881,fail
7,0.753135,0.432402,0.564142,1.222377,0.220565,0.207258,0.024317,0.007026,0.337711,0.527987,0.174070,0.057035,0.364865,0.508709,0.177585,0.350868,0.503340,0.336539,fail
8,0.635412,0.403909,0.471841,1.120164,0.211469,0.180005,0.022568,0.006189,0.319330,0.483356,0.159258,0.051868,0.323298,0.432982,0.152578,0.342781,0.477973,0.316651,fail
9,0.565661,0.300323,0.327642,1.024125,0.172197,0.134748,0.019416,0.005478,0.279913,0.456267,0.147547,0.049663,0.289709,0.418160,0.149704,0.273779,0.409350,0.268475,fail
10,0.745741,0.371847,0.355957,1.267288,0.204462,0.138994,0.020167,0.005947,0.315714,0.486364,0.156438,0.051895,0.337149,0.455914,0.166669,0.343146,0.496434,0.361728,pass
11,0.548601,0.241628,0.246660,1.053317,0.168582,0.106654,0.017843,0.005236,0.287022,0.442798,0.145263,0.049885,0.290835,0.406586,0.143735,0.288999,0.426647,0.313939,pass
12,0.415203,0.194745,0.276921,0.873465,0.130866,0.102711,0.014863,0.004318,0.245266,0.385151,0.131161,0.043028,0.264152,0.384291,0.136884,0.247138,0.352800,0.284946,pass
13,0.607141,0.298153,0.422435,0.927733,0.171835,0.153262,0.017323,0.005240,0.290702,0.435267,0.135203,0.046604,0.289997,0.361011,0.128871,0.306457,0.413836,0.307779,pass
14,0.677964,0.313476,0.281073,1.186939,0.194928,0.123497,0.020733,0.005969,0.306726,0.466481,0.155852,0.053251,0.303125,0.426083,0.150572,0.323489,0.481644,0.330052,pass
15,0.525241,0.272682,0.396792,0.945279,0.166728,0.144594,0.017454,0.005412,0.267129,0.444387,0.134446,0.047138,0.286126,0.385679,0.143285,0.287897,0.412189,0.292857,pass
16,0.463843,0.250418,0.309565,0.766245,0.143052,0.124993,0.014819,0.004325,0.257691,0.405642,0.124631,0.041660,0.261355,0.339264,0.117379,0.248967,0.321981,0.274354,pass
17,0.484882,0.242925,0.244415,0.735851,0.123860,0.097984,0.012253,0.003620,0.185371,0.296486,0.089471,0.030141,0.207537,0.271748,0.100989,0.233397,0.330655,0.208531,pass
18,0.598771,0.355906,0.404262,1.011251,0.200462,0.163784,0.021513,0.005924,0.305165,0.458949,0.155605,0.049374,0.308411,0.421377,0.144923,0.321360,0.449688,0.298798,pass
19,0.535524,0.288405,0.301531,1.014358,0.156184,0.110570,0.015663,0.004684,0.261430,0.398685,0.132304,0.044397,0.264874,0.356955,0.125360,0.276033,0.400231,0.288734,pass

BARINEL SCORES

,h 15,cp 12,cp 10,cp 11,swap 16,cp 7,cp 13,cp 6,cp 3,cp 4,cp 8,h 9,h 5,swap 17,cswap 14,cp 1,h 2,h 0
sum,0.568566,0.568068,0.550201,0.545941,0.540645,0.540373,0.538887,0.538383,0.536966,0.534502,0.532581,0.531575,0.530127,0.526359,0.525757,0.52223,0.514058,0.503811

TARANTULA SCORES

,h 15,cp 12,cp 10,cp 11,swap 16,cp 7,cp 13,cp 6,cp 3,cp 4,cp 8,h 9,h 5,swap 17,cswap 14,cp 1,h 2,h 0
sum,0.568566,0.568068,0.550201,0.545941,0.540645,0.540373,0.538887,0.538383,0.536966,0.534502,0.532581,0.531575,0.530127,0.526359,0.525757,0.52223,0.514058,0.503811

DSTAR SCORES

,cswap 14,swap 17,cp 8,cp 1,cp 4,h 15,swap 16,h 5,h 9,h 2,h 0,cp 13,cp 12,cp 7,cp 3,cp 6,cp 11,cp 10
sum,5.94477,2.484775,1.625998,1.416167,1.385176,1.376709,0.864817,0.786395,0.750121,0.719267,0.697693,0.32312,0.246458,0.225164,0.218558,0.027211,0.004235,0.000382

ERROR GATE LOCATION:
14
Now evolving the following mutant:  AddGate_swap_inGap_4_.qasm

100%|██████████| 10/10 [00:27<00:00,  2.75s/it]
100%|██████████| 10/10 [00:26<00:00,  2.67s/it]

,swap 17,swap 16,h 15,cp 14,cp 13,cp 12,cp 11,h 10,swap 9,cp 8,cp 7,cp 6,h 5,cp 4,cp 3,h 2,cp 1,h 0,pass/fail
0,0.574002,0.275176,0.277182,0.411822,0.155041,0.042014,0.013920,0.391026,0.270821,0.614512,0.011281,0.004024,0.226700,0.289308,0.115874,0.297069,0.444834,0.305306,fail
1,0.451738,0.236509,0.367451,0.548188,0.198461,0.061777,0.017546,0.423570,0.246762,0.631608,0.012480,0.004244,0.251354,0.319158,0.120832,0.349660,0.494491,0.316393,fail
2,0.422677,0.209724,0.254774,0.367828,0.135123,0.040396,0.011843,0.356822,0.206602,0.537605,0.010187,0.003580,0.205465,0.259421,0.100225,0.266956,0.371553,0.284549,fail
3,0.360976,0.209458,0.283899,0.431929,0.168693,0.050306,0.013360,0.367585,0.296681,0.552507,0.011114,0.003618,0.216593,0.290056,0.110765,0.300913,0.434293,0.242048,fail
4,0.484623,0.224533,0.390144,0.604069,0.205038,0.065078,0.018447,0.409239,0.226490,0.579124,0.011594,0.003836,0.235041,0.297560,0.112009,0.316288,0.442526,0.271502,fail
5,0.499187,0.237102,0.339080,0.523839,0.175247,0.054202,0.017378,0.378272,0.262518,0.512182,0.010702,0.003549,0.220687,0.280577,0.105317,0.301345,0.431137,0.301183,fail
6,0.688132,0.336726,0.425290,0.674267,0.242902,0.072682,0.020676,0.517765,0.343714,0.751635,0.014593,0.005024,0.299789,0.374729,0.141467,0.372705,0.511479,0.377060,fail
7,0.450495,0.200517,0.345777,0.518248,0.185021,0.054894,0.017021,0.391550,0.275565,0.547708,0.010562,0.003660,0.229541,0.271298,0.107328,0.314122,0.457761,0.316414,fail
8,0.609148,0.291702,0.211394,0.340492,0.114363,0.035565,0.010360,0.380758,0.242591,0.599656,0.011340,0.003962,0.212652,0.288343,0.111516,0.276313,0.408468,0.294205,fail
9,0.319359,0.133072,0.234870,0.346840,0.117571,0.036423,0.012011,0.292520,0.257940,0.412394,0.008281,0.002845,0.172854,0.219391,0.087394,0.259305,0.378519,0.271340,fail
10,0.308197,0.221093,0.356214,0.549507,0.193736,0.061707,0.018790,0.361926,0.172822,0.499377,0.010220,0.003402,0.212070,0.269247,0.095923,0.294742,0.390974,0.310969,pass
11,0.325127,0.150106,0.222828,0.325467,0.107548,0.032628,0.011281,0.243096,0.230888,0.324183,0.006798,0.002305,0.145582,0.183399,0.069529,0.228091,0.325228,0.241095,pass
12,0.741011,0.348190,0.337316,0.510069,0.202418,0.055079,0.016208,0.379685,0.342407,0.598008,0.011188,0.003905,0.230851,0.293211,0.109867,0.307393,0.469343,0.286735,pass
13,1.005749,0.459074,0.465231,0.728341,0.258828,0.071944,0.023516,0.584328,0.350399,0.859238,0.016703,0.005766,0.337516,0.421624,0.155808,0.403971,0.585300,0.417900,pass
14,0.844788,0.401580,0.401136,0.630859,0.207412,0.064673,0.020475,0.438719,0.410926,0.596157,0.011307,0.003966,0.252483,0.298738,0.116340,0.367824,0.555925,0.401506,pass
15,0.482547,0.253932,0.260989,0.382717,0.134051,0.044091,0.012354,0.388939,0.322964,0.566464,0.011569,0.003797,0.226514,0.302353,0.112018,0.332661,0.464349,0.335422,pass
16,0.532077,0.296528,0.358071,0.533429,0.176233,0.055729,0.017863,0.365156,0.338716,0.501923,0.010058,0.003364,0.216074,0.268225,0.099297,0.327978,0.468662,0.365593,pass
17,0.687708,0.322885,0.487621,0.742977,0.248633,0.078230,0.023958,0.472991,0.317173,0.655368,0.013368,0.004567,0.280376,0.349601,0.130537,0.415534,0.590711,0.395887,pass
18,0.757705,0.364917,0.315528,0.458109,0.162111,0.047370,0.015070,0.379447,0.303679,0.558260,0.010660,0.003812,0.227304,0.275908,0.107127,0.332911,0.492371,0.349426,pass
19,0.413324,0.248410,0.355930,0.552829,0.179049,0.058111,0.017650,0.415363,0.283199,0.560847,0.011581,0.003818,0.235212,0.305141,0.113811,0.312809,0.438660,0.333788,pass

BARINEL SCORES

,cp 8,cp 3,cp 6,cp 7,cp 4,h 10,h 5,h 2,cp 1,cp 13,cp 12,cp 14,h 15,h 0,cp 11,swap 9,swap 17,swap 16
sum,0.500834,0.500555,0.497665,0.497081,0.493375,0.492408,0.489934,0.478895,0.477805,0.475815,0.47404,0.468238,0.467791,0.464296,0.462689,0.461117,0.443519,0.434314

TARANTULA SCORES

,cp 8,cp 3,cp 6,cp 7,cp 4,h 10,h 5,h 2,cp 1,cp 13,cp 12,cp 14,h 15,h 0,cp 11,swap 9,swap 17,swap 16
sum,0.500834,0.500555,0.497665,0.497081,0.493375,0.492408,0.489934,0.478895,0.477805,0.475815,0.47404,0.468238,0.467791,0.464296,0.462689,0.461117,0.443519,0.434314

DSTAR SCORES

,cp 8,cp 14,swap 17,cp 1,h 10,h 15,h 2,h 0,cp 4,swap 9,swap 16,h 5,cp 13,cp 3,cp 12,cp 11,cp 7,cp 6
sum,2.095146,1.474556,1.467421,1.294939,1.089203,0.722375,0.700322,0.660827,0.644012,0.528964,0.424265,0.417015,0.242744,0.111443,0.024932,0.002287,0.001243,0.000146

ERROR GATE LOCATION:
9
Now evolving the following mutant:  AddGate_ry_inGap_4_.qasm

100%|██████████| 10/10 [00:15<00:00,  1.53s/it]
100%|██████████| 10/10 [00:14<00:00,  1.50s/it]

,swap 17,swap 16,h 15,cp 14,cp 13,cp 12,cp 11,h 10,ry 9,cp 8,cp 7,cp 6,h 5,cp 4,cp 3,h 2,cp 1,h 0,pass/fail
0,0.765734,0.380195,0.427900,0.645489,0.226554,0.063944,0.021246,0.474927,0.426147,0.0,6.937902e-19,3.419740e-19,0.373819,0.453235,0.177545,0.343999,0.452050,0.392240,fail
1,0.538249,0.282211,0.372517,0.595326,0.197345,0.066199,0.018614,0.419574,0.375390,0.0,6.051466e-19,2.982912e-19,0.207232,0.292577,0.101448,0.265142,0.356760,0.279525,fail
2,0.769158,0.373679,0.424991,0.620383,0.222861,0.065000,0.019229,0.501647,0.449408,0.0,7.104938e-19,3.502133e-19,0.425485,0.567240,0.214225,0.377365,0.516256,0.360502,fail
3,0.677876,0.314775,0.454971,0.688379,0.240980,0.071470,0.021841,0.490158,0.440518,0.0,6.759752e-19,3.331996e-19,0.364151,0.447164,0.159966,0.382861,0.486244,0.365676,fail
4,0.370579,0.189823,0.300741,0.454127,0.157352,0.049951,0.015073,0.334776,0.302671,0.0,4.888643e-19,2.409675e-19,0.260163,0.364572,0.133323,0.250391,0.321778,0.285366,fail
5,0.534477,0.213057,0.283076,0.443200,0.138478,0.047635,0.013194,0.386476,0.331941,0.0,4.997399e-19,2.463301e-19,0.155110,0.222184,0.084103,0.241104,0.345316,0.215899,fail
6,0.601648,0.340231,0.397030,0.597306,0.219775,0.069694,0.018680,0.403677,0.370867,0.0,6.529131e-19,3.218264e-19,0.360593,0.472849,0.169086,0.382934,0.509314,0.331392,fail
7,0.465999,0.234770,0.434030,0.637398,0.219785,0.072796,0.020325,0.466903,0.425967,0.0,6.228262e-19,3.070057e-19,0.357051,0.460204,0.180250,0.399103,0.515409,0.375738,fail
8,0.572086,0.293543,0.456988,0.658166,0.236576,0.070416,0.020882,0.512376,0.460743,0.0,6.289168e-19,3.100014e-19,0.377752,0.459606,0.168476,0.380432,0.480629,0.377289,fail
9,0.551360,0.270409,0.206535,0.338548,0.110451,0.037601,0.010087,0.363816,0.298075,0.0,5.134428e-19,2.530745e-19,0.184120,0.260206,0.096279,0.236215,0.336983,0.236276,fail
10,0.446717,0.239592,0.347430,0.513921,0.184040,0.054459,0.016669,0.357558,0.324122,0.0,5.037317e-19,2.482945e-19,0.297197,0.367105,0.135587,0.305973,0.411117,0.277005,pass
11,0.447046,0.261095,0.278089,0.395278,0.128684,0.040887,0.012785,0.320866,0.289850,0.0,5.031157e-19,2.479868e-19,0.188393,0.267021,0.094035,0.232850,0.334536,0.246069,pass
12,0.783641,0.378120,0.465177,0.703018,0.251570,0.073185,0.022067,0.498924,0.455924,0.0,7.068616e-19,3.484210e-19,0.321257,0.408946,0.148069,0.371459,0.531248,0.331072,pass
13,0.553674,0.239839,0.397123,0.587794,0.223695,0.064890,0.018478,0.419206,0.380712,0.0,5.979748e-19,2.947527e-19,0.329937,0.407142,0.143765,0.389703,0.523443,0.328359,pass
14,0.269098,0.170525,0.128062,0.200233,0.076372,0.024029,0.006085,0.167464,0.144787,0.0,3.135805e-19,1.545627e-19,0.191494,0.268072,0.101073,0.171427,0.230185,0.176483,pass
15,0.214781,0.138081,0.234862,0.332714,0.109897,0.038403,0.010443,0.222178,0.208912,0.0,3.476028e-19,1.713412e-19,0.190039,0.257373,0.101272,0.233446,0.303956,0.221161,pass
16,0.577133,0.296460,0.490651,0.739710,0.263971,0.077239,0.023558,0.471440,0.436592,0.0,6.627015e-19,3.266631e-19,0.407220,0.507692,0.184134,0.391202,0.514451,0.352218,pass
17,0.337136,0.207724,0.290615,0.418023,0.158957,0.042890,0.013672,0.359374,0.314912,0.0,4.916118e-19,2.423157e-19,0.333273,0.431338,0.158089,0.267199,0.328828,0.322519,pass
18,0.526252,0.295872,0.323872,0.506446,0.184446,0.052365,0.015821,0.315201,0.290863,0.0,4.587850e-19,2.261371e-19,0.250284,0.303545,0.108976,0.229839,0.311161,0.208813,pass
19,0.357745,0.154410,0.256065,0.396165,0.135053,0.040046,0.013204,0.287214,0.253766,0.0,4.302270e-19,2.120678e-19,0.247058,0.331819,0.120432,0.231542,0.312465,0.241818,pass

BARINEL SCORES

,swap 17,h 10,ry 9,swap 16,cp 6,cp 7,cp 12,h 0,cp 14,cp 11,h 15,h 2,cp 13,cp 3,cp 1,cp 4,h 5,cp 8
sum,0.564377,0.560132,0.555949,0.548439,0.548429,0.548428,0.54733,0.543405,0.542258,0.539748,0.539223,0.535741,0.534375,0.534039,0.531971,0.529788,0.526567,NaN

TARANTULA SCORES

,swap 17,h 10,ry 9,swap 16,cp 6,cp 7,cp 12,h 0,cp 14,cp 11,h 15,h 2,cp 13,cp 3,cp 1,cp 4,h 5,cp 8
sum,0.564377,0.560132,0.555949,0.548439,0.548429,0.548428,0.54733,0.543405,0.542258,0.539748,0.539223,0.535741,0.534375,0.534039,0.531971,0.529788,0.526567,NaN

DSTAR SCORES

,swap 17,cp 14,h 10,cp 1,cp 4,ry 9,h 15,h 2,h 0,h 5,swap 16,cp 13,cp 3,cp 12,cp 11,cp 7,cp 6,cp 8
sum,2.355738,2.17959,1.412892,1.352675,1.180712,1.150175,1.069366,0.828455,0.816006,0.736675,0.675809,0.331281,0.195153,0.035958,0.003162,3.711379e-36,9.017312e-37,0.0

ERROR GATE LOCATION:
9
Now evolving the following mutant:  AddGate_cswap_inGap_4_.qasm

100%|██████████| 10/10 [00:45<00:00,  4.53s/it]
100%|██████████| 10/10 [00:45<00:00,  4.57s/it]

,swap 17,swap 16,h 15,cp 14,cp 13,cp 12,cp 11,h 10,cswap 9,cp 8,cp 7,cp 6,h 5,cp 4,cp 3,h 2,cp 1,h 0,pass/fail
0,0.676317,0.358378,0.392368,0.608405,0.215736,0.062284,0.019805,0.415558,0.927335,0.189974,0.128004,0.022122,0.318764,0.472883,0.162787,0.326886,0.468035,0.309453,fail
1,0.612005,0.338348,0.326393,0.498248,0.181117,0.053767,0.016515,0.422852,0.862984,0.178674,0.136269,0.021025,0.312641,0.451689,0.154898,0.320139,0.441004,0.307544,fail
2,0.421212,0.188060,0.235767,0.344942,0.131624,0.035322,0.011092,0.306983,0.642327,0.137004,0.099215,0.015512,0.250101,0.353036,0.123354,0.252896,0.348823,0.239507,fail
3,0.368007,0.133514,0.335846,0.487376,0.178059,0.050292,0.016479,0.358210,0.641149,0.152031,0.112550,0.017294,0.292651,0.395247,0.133526,0.273842,0.347544,0.263729,fail
4,0.560471,0.253479,0.356465,0.537903,0.194276,0.057902,0.018350,0.478128,0.804107,0.183107,0.151303,0.021918,0.318693,0.453199,0.159637,0.327015,0.457981,0.335927,fail
5,0.600559,0.284242,0.386141,0.608189,0.203301,0.062830,0.019627,0.433932,0.864802,0.195229,0.135625,0.022096,0.316643,0.439989,0.164721,0.311038,0.432486,0.298805,fail
6,0.497755,0.235676,0.361004,0.554078,0.203226,0.062244,0.017049,0.418700,0.754292,0.169715,0.130888,0.020179,0.279533,0.410281,0.143509,0.294857,0.419604,0.248163,fail
7,0.658285,0.351905,0.328673,0.536790,0.190687,0.057193,0.016952,0.482495,0.899044,0.193060,0.154726,0.023111,0.343661,0.484852,0.169265,0.329520,0.459598,0.313291,fail
8,0.725124,0.340266,0.397632,0.594983,0.196134,0.061252,0.018701,0.455477,0.812429,0.175489,0.138053,0.020244,0.344780,0.486035,0.169481,0.330684,0.440572,0.319421,fail
9,0.712361,0.297727,0.278061,0.422817,0.136814,0.044485,0.012836,0.388216,0.669830,0.136355,0.123723,0.016655,0.286492,0.408902,0.146937,0.280174,0.390462,0.260854,fail
10,0.429386,0.260002,0.252307,0.406987,0.135552,0.044287,0.013060,0.333615,0.736524,0.146099,0.110214,0.017423,0.262800,0.380503,0.134146,0.253878,0.362489,0.252520,pass
11,0.458728,0.240430,0.308953,0.457941,0.158952,0.051205,0.014906,0.333338,0.606458,0.132705,0.102197,0.014915,0.255537,0.353243,0.122658,0.266015,0.352241,0.250185,pass
12,0.610888,0.327819,0.412696,0.626246,0.226885,0.064455,0.019814,0.393770,0.820784,0.175654,0.126302,0.020897,0.340526,0.486728,0.170473,0.333053,0.463935,0.305073,pass
13,0.619175,0.272383,0.331265,0.499395,0.170478,0.053163,0.015917,0.343566,0.718213,0.146083,0.107149,0.016780,0.280132,0.391993,0.143922,0.286562,0.398241,0.274722,pass
14,0.530637,0.322514,0.353807,0.541145,0.187061,0.057648,0.017632,0.408262,0.863060,0.181767,0.128626,0.021083,0.311474,0.450364,0.154211,0.294834,0.405506,0.284749,pass
15,0.546036,0.290564,0.231933,0.358629,0.118031,0.038150,0.011456,0.276270,0.613539,0.119160,0.084908,0.014000,0.212171,0.306377,0.110757,0.216899,0.306312,0.221798,pass
16,0.785245,0.339124,0.394023,0.606372,0.214110,0.061925,0.019159,0.494757,0.872481,0.191379,0.150588,0.022669,0.347354,0.484149,0.169556,0.335775,0.461894,0.320265,pass
17,0.768676,0.422075,0.400105,0.613341,0.198751,0.064500,0.019290,0.467679,0.909751,0.190207,0.145130,0.022217,0.325999,0.463909,0.159758,0.328601,0.457279,0.315083,pass
18,0.387896,0.212386,0.299892,0.475423,0.159464,0.053900,0.014820,0.382176,0.671434,0.151371,0.121288,0.017965,0.228137,0.330589,0.122085,0.238921,0.343258,0.222469,pass
19,0.407707,0.167941,0.334857,0.478782,0.172651,0.048128,0.015852,0.332648,0.667095,0.152563,0.100213,0.017046,0.263701,0.383679,0.127300,0.273242,0.370334,0.261202,pass

BARINEL SCORES

,cp 7,h 10,h 5,cp 6,cp 4,cp 3,cp 8,h 2,cp 1,h 0,cswap 9,swap 17,cp 13,cp 11,cp 14,h 15,cp 12,swap 16
sum,0.526888,0.524883,0.520039,0.519681,0.519349,0.519241,0.518748,0.518662,0.517509,0.516827,0.512989,0.512646,0.51246,0.508351,0.506311,0.505843,0.504705,0.493468

TARANTULA SCORES

,cp 7,h 10,h 5,cp 6,cp 4,cp 3,cp 8,h 2,cp 1,h 0,cswap 9,swap 17,cp 13,cp 11,cp 14,h 15,cp 12,swap 16
sum,0.526888,0.524883,0.520039,0.519681,0.519349,0.519241,0.518748,0.518662,0.517509,0.516827,0.512989,0.512646,0.51246,0.508351,0.506311,0.505843,0.504705,0.493468

DSTAR SCORES

,cswap 9,swap 17,cp 14,cp 4,cp 1,h 10,h 15,h 5,h 2,h 0,swap 16,cp 13,cp 8,cp 3,cp 7,cp 12,cp 6,cp 11
sum,3.550912,2.188147,1.790651,1.352363,1.270794,1.257453,0.867037,0.731834,0.723782,0.660276,0.601877,0.285512,0.252549,0.20457,0.153627,0.028454,0.003933,0.002758

ERROR GATE LOCATION:
9
Now evolving the following mutant:  AddGate_swap_inGap_3_.qasm

100%|██████████| 10/10 [00:28<00:00,  2.84s/it]
100%|██████████| 10/10 [00:29<00:00,  2.92s/it]

,swap 17,swap 16,h 15,cp 14,cp 13,cp 12,cp 11,h 10,cp 9,cp 8,cp 7,h 6,swap 5,cp 4,cp 3,h 2,cp 1,h 0,pass/fail
0,0.334802,0.159465,0.290274,0.418796,0.146239,0.047154,0.013957,0.319038,0.442482,0.151507,0.050920,0.341948,0.211068,0.421002,0.009446,0.203729,0.263269,0.245990,fail
1,0.668621,0.321979,0.276715,0.447249,0.151070,0.045553,0.014920,0.338350,0.478968,0.159665,0.055724,0.379144,0.233875,0.507920,0.010918,0.222960,0.308704,0.340032,fail
2,0.641709,0.285004,0.392753,0.625411,0.223020,0.065518,0.020084,0.412331,0.552056,0.195711,0.062735,0.454840,0.292199,0.559558,0.011812,0.267437,0.329523,0.303159,fail
3,0.722493,0.291193,0.426668,0.613752,0.198769,0.062789,0.019936,0.455019,0.593532,0.196208,0.068512,0.500734,0.217862,0.627701,0.013369,0.300075,0.370087,0.419653,fail
4,0.504774,0.198270,0.258883,0.376950,0.143660,0.037402,0.012897,0.316793,0.436794,0.140193,0.052213,0.364768,0.213602,0.425645,0.009331,0.207694,0.261064,0.281274,fail
5,0.494287,0.273394,0.287889,0.445376,0.160459,0.052316,0.013531,0.345739,0.477397,0.166597,0.054215,0.392982,0.298606,0.494570,0.010437,0.235212,0.299565,0.250406,fail
6,0.468683,0.203749,0.192314,0.276364,0.095579,0.029797,0.009365,0.283710,0.390821,0.140588,0.045801,0.340573,0.213055,0.467118,0.009320,0.203134,0.262898,0.288776,fail
7,0.563149,0.292963,0.275812,0.410998,0.156047,0.045620,0.012845,0.318992,0.421256,0.147295,0.047104,0.409187,0.236721,0.525148,0.010722,0.243163,0.302713,0.303644,fail
8,0.474916,0.224623,0.277217,0.443325,0.163415,0.045882,0.014172,0.306753,0.436141,0.147120,0.050781,0.393215,0.218570,0.506494,0.011324,0.223358,0.313566,0.262365,fail
9,0.437716,0.199838,0.251304,0.368677,0.127006,0.040293,0.011759,0.272138,0.372875,0.124171,0.043302,0.315880,0.204030,0.414710,0.008998,0.191820,0.257563,0.277029,fail
10,0.611661,0.334271,0.391355,0.592112,0.212202,0.064438,0.018660,0.480244,0.653357,0.226913,0.077406,0.524338,0.295172,0.638661,0.013418,0.306992,0.374250,0.355709,pass
11,0.512639,0.335823,0.327975,0.480507,0.179104,0.051653,0.015911,0.350005,0.478492,0.164616,0.056346,0.417656,0.236727,0.523629,0.011328,0.246873,0.318189,0.350645,pass
12,0.339939,0.221100,0.329699,0.494056,0.163649,0.057449,0.015817,0.338752,0.463644,0.165593,0.053551,0.332693,0.235349,0.412207,0.009088,0.203802,0.256983,0.199011,pass
13,0.347875,0.184938,0.260477,0.383107,0.141366,0.042305,0.012413,0.289152,0.410470,0.140971,0.046755,0.316686,0.165432,0.386532,0.008734,0.188036,0.241479,0.216584,pass
14,0.593105,0.283449,0.377509,0.555042,0.183733,0.057011,0.017670,0.426211,0.572648,0.195813,0.069388,0.514352,0.222425,0.668314,0.014662,0.299887,0.401188,0.405620,pass
15,0.434854,0.281154,0.475721,0.708041,0.263799,0.077949,0.023063,0.480432,0.640920,0.225302,0.075087,0.544878,0.265903,0.628468,0.014052,0.322931,0.386530,0.363402,pass
16,0.755788,0.415499,0.553004,0.849831,0.302640,0.086306,0.027754,0.577713,0.793505,0.266318,0.091150,0.607225,0.392973,0.698236,0.015898,0.352066,0.446080,0.382358,pass
17,0.401688,0.250630,0.276383,0.465778,0.157811,0.050576,0.015047,0.363213,0.507122,0.170109,0.062410,0.341395,0.223716,0.398231,0.009372,0.201566,0.263686,0.290870,pass
18,0.354062,0.153714,0.216761,0.307206,0.113713,0.034344,0.009607,0.332748,0.457112,0.151802,0.053138,0.366062,0.132284,0.442132,0.009003,0.216012,0.244631,0.306303,pass
19,0.539132,0.278335,0.338922,0.497107,0.180819,0.050377,0.016027,0.378208,0.496755,0.166363,0.058723,0.432834,0.226254,0.487874,0.010724,0.251045,0.297553,0.325270,pass

BARINEL SCORES

,swap 17,swap 5,cp 4,h 0,cp 1,cp 3,swap 16,h 2,h 6,cp 9,h 10,cp 8,cp 11,cp 14,h 15,cp 12,cp 7,cp 13
sum,0.520604,0.494019,0.483662,0.481887,0.4789,0.476121,0.472209,0.47027,0.469556,0.456745,0.456143,0.455743,0.454818,0.45359,0.452299,0.452101,0.452076,0.451853

TARANTULA SCORES

,swap 17,swap 5,cp 4,h 0,cp 1,cp 3,swap 16,h 2,h 6,cp 9,h 10,cp 8,cp 11,cp 14,h 15,cp 12,cp 7,cp 13
sum,0.520604,0.494019,0.483662,0.481887,0.4789,0.476121,0.472209,0.47027,0.469556,0.456745,0.456143,0.455743,0.454818,0.45359,0.452299,0.452101,0.452076,0.451853

DSTAR SCORES

,swap 17,cp 4,cp 9,cp 14,h 6,h 10,h 0,cp 1,h 15,swap 16,swap 5,h 2,cp 8,cp 13,cp 7,cp 12,cp 11,cp 3
sum,1.894352,1.60303,1.368835,1.278138,1.052745,0.809696,0.669513,0.666236,0.633601,0.471378,0.441559,0.419683,0.207342,0.205907,0.026521,0.021101,0.002023,0.001104

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_cswap_inGap_3_.qasm

100%|██████████| 10/10 [00:46<00:00,  4.62s/it]
100%|██████████| 10/10 [00:41<00:00,  4.15s/it]

,swap 17,swap 16,h 15,cp 14,cp 13,cp 12,cp 11,h 10,cp 9,cp 8,cp 7,h 6,cswap 5,cp 4,cp 3,h 2,cp 1,h 0,pass/fail
0,0.727068,0.380445,0.415178,0.649715,0.237687,0.070196,0.019771,0.480127,0.654329,0.212931,0.073768,0.563518,0.958137,0.223920,0.159462,0.384202,0.537782,0.380120,fail
1,0.583485,0.334461,0.438812,0.671617,0.228391,0.073068,0.020977,0.397227,0.518884,0.181387,0.058936,0.456118,0.867541,0.191724,0.133675,0.336481,0.477342,0.321184,fail
2,0.584127,0.233635,0.384429,0.555726,0.192157,0.060047,0.018593,0.352620,0.449269,0.156050,0.051950,0.449481,0.755292,0.173899,0.130742,0.313278,0.455808,0.307313,fail
3,0.777672,0.396184,0.367368,0.569687,0.197416,0.058641,0.018319,0.433549,0.615214,0.206729,0.071373,0.471612,0.912397,0.200850,0.139433,0.330762,0.481559,0.331003,fail
4,0.348510,0.221124,0.309258,0.434556,0.163062,0.046366,0.013717,0.300229,0.380566,0.132908,0.043666,0.432784,0.584106,0.143725,0.119131,0.274956,0.374388,0.258294,fail
5,0.641179,0.356655,0.400958,0.623497,0.213144,0.066245,0.020126,0.416206,0.559131,0.195528,0.066320,0.478649,0.897386,0.196746,0.138735,0.333867,0.469192,0.329027,fail
6,0.584071,0.297038,0.261807,0.362806,0.122350,0.037902,0.011785,0.322185,0.436265,0.149999,0.051390,0.382487,0.655803,0.149282,0.112911,0.285007,0.421863,0.280225,fail
7,0.517924,0.308188,0.378428,0.561870,0.211402,0.060942,0.018114,0.396937,0.532453,0.177376,0.060221,0.471023,0.766723,0.176307,0.133743,0.344957,0.473729,0.319583,fail
8,0.687903,0.366881,0.369465,0.582863,0.195046,0.063620,0.018311,0.447427,0.626731,0.216553,0.074020,0.465856,0.938416,0.203254,0.134864,0.334252,0.488966,0.336044,fail
9,0.517877,0.308239,0.324485,0.468782,0.174184,0.050514,0.014549,0.377497,0.509023,0.169741,0.059235,0.474140,0.712185,0.169804,0.133695,0.317250,0.444078,0.302362,fail
10,0.531210,0.279522,0.391836,0.583167,0.188882,0.065248,0.018243,0.475312,0.631986,0.225650,0.073436,0.465065,0.871697,0.196473,0.132365,0.359637,0.511236,0.352780,pass
11,0.444425,0.225373,0.268579,0.392370,0.138900,0.043903,0.012555,0.364257,0.508388,0.170709,0.061024,0.408115,0.693401,0.155437,0.119542,0.298579,0.422559,0.288834,pass
12,0.788597,0.398860,0.399403,0.620358,0.221172,0.067316,0.018888,0.473814,0.638889,0.217153,0.075695,0.510569,0.883500,0.202234,0.145911,0.373328,0.522733,0.354763,pass
13,0.436799,0.293744,0.298184,0.421193,0.135581,0.046092,0.014424,0.336084,0.425673,0.157371,0.054394,0.395865,0.588018,0.135156,0.111723,0.279745,0.390360,0.289895,pass
14,0.593120,0.284239,0.251675,0.385303,0.125658,0.039758,0.012666,0.352039,0.484987,0.155927,0.058088,0.374449,0.623469,0.143017,0.107794,0.269140,0.390546,0.291839,pass
15,0.725594,0.355053,0.497854,0.752228,0.268886,0.078556,0.024794,0.494833,0.647455,0.219297,0.075915,0.589251,0.939113,0.220942,0.162854,0.384244,0.542139,0.388545,pass
16,0.458603,0.239771,0.279340,0.425648,0.140612,0.043853,0.013809,0.302497,0.402692,0.143137,0.047337,0.326421,0.583600,0.126960,0.098203,0.256439,0.357067,0.235567,pass
17,0.606095,0.298906,0.353276,0.543482,0.201986,0.056261,0.017860,0.432539,0.627698,0.206166,0.069838,0.466412,0.822962,0.186232,0.136701,0.336951,0.468964,0.317935,pass
18,0.370469,0.222703,0.247961,0.379809,0.146015,0.041656,0.012056,0.345095,0.463039,0.160911,0.053033,0.421183,0.655863,0.151978,0.114833,0.281409,0.377592,0.263835,pass
19,0.474683,0.261203,0.337853,0.531762,0.179781,0.056234,0.017169,0.356921,0.486160,0.165628,0.057949,0.393540,0.704737,0.164735,0.118014,0.269806,0.380358,0.271728,pass

BARINEL SCORES

,swap 16,cp 13,swap 17,h 15,cswap 5,cp 12,cp 14,cp 4,cp 11,cp 3,h 6,cp 1,h 2,h 0,h 10,cp 9,cp 8,cp 7
sum,0.528329,0.525441,0.523695,0.523238,0.52211,0.521602,0.521195,0.520831,0.517519,0.517113,0.516384,0.514527,0.511449,0.508796,0.499403,0.498344,0.496859,0.493605

TARANTULA SCORES

,swap 16,cp 13,swap 17,h 15,cswap 5,cp 12,cp 14,cp 4,cp 11,cp 3,h 6,cp 1,h 2,h 0,h 10,cp 9,cp 8,cp 7
sum,0.528329,0.525441,0.523695,0.523238,0.52211,0.521602,0.521195,0.520831,0.517519,0.517113,0.516384,0.514527,0.511449,0.508796,0.499403,0.498344,0.496859,0.493605

DSTAR SCORES

,cswap 5,swap 17,cp 14,cp 9,h 6,cp 1,h 10,h 15,h 2,swap 16,h 0,cp 13,cp 4,cp 8,cp 3,cp 7,cp 12,cp 11
sum,3.729629,2.309762,1.99814,1.821385,1.503898,1.48904,1.105101,0.999843,0.808215,0.797726,0.767342,0.318673,0.28649,0.273823,0.158779,0.035117,0.032755,0.002988

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_h_inGap_9_.qasm

100%|██████████| 10/10 [00:39<00:00,  3.98s/it]
100%|██████████| 10/10 [00:35<00:00,  3.58s/it]

,h 17,swap 16,swap 15,h 14,cp 13,cp 12,cp 11,cp 10,h 9,cp 8,cp 7,cp 6,h 5,cp 4,cp 3,h 2,cp 1,h 0,pass/fail
0,0.482677,0.459358,0.245757,0.526364,0.615946,0.212942,0.075845,0.019605,0.671927,0.802431,0.281588,0.091277,0.572301,0.831507,0.261874,0.508489,0.631109,0.516601,fail
1,0.576009,0.535825,0.343358,0.554837,0.646936,0.212326,0.088080,0.019091,0.582390,0.634219,0.287501,0.070797,0.574304,0.879390,0.260998,0.545254,0.648892,0.556459,fail
2,0.552419,0.463091,0.246993,0.652172,0.714521,0.246324,0.077924,0.022103,0.625727,0.709379,0.283376,0.079729,0.607106,0.864224,0.275149,0.549312,0.655474,0.562096,fail
3,0.563883,0.399235,0.263801,0.413185,0.539175,0.179521,0.093312,0.016097,0.592040,0.672895,0.289978,0.075616,0.553839,0.836742,0.250624,0.506200,0.607977,0.531987,fail
4,0.632906,0.306292,0.165677,0.554499,0.618964,0.208867,0.077098,0.018371,0.687209,0.756854,0.276675,0.084393,0.593657,0.895039,0.265839,0.585627,0.678398,0.606050,fail
5,0.586993,0.885029,0.392628,0.728807,0.856623,0.276127,0.100195,0.025011,0.734833,0.859798,0.365787,0.097536,0.667925,1.050555,0.306561,0.626039,0.775010,0.623608,fail
6,0.505105,0.565507,0.296255,0.470483,0.570998,0.183614,0.073942,0.017177,0.555440,0.616098,0.243823,0.068621,0.508541,0.732019,0.229721,0.460313,0.563545,0.518276,fail
7,0.505776,0.600765,0.285578,0.535144,0.587161,0.213269,0.071399,0.017214,0.577609,0.672024,0.271359,0.074896,0.545522,0.823698,0.243458,0.503686,0.609007,0.511617,fail
8,0.618362,0.491019,0.283549,0.658310,0.741099,0.244127,0.091588,0.022429,0.553751,0.602411,0.280975,0.066327,0.527907,0.859373,0.243143,0.516028,0.619190,0.486324,fail
9,0.515524,0.517384,0.281728,0.596207,0.745297,0.242637,0.092966,0.022023,0.505562,0.546934,0.256797,0.059562,0.487323,0.808867,0.222772,0.476551,0.589659,0.438697,fail
10,0.289923,0.391192,0.239541,0.630443,0.767988,0.272693,0.072047,0.024712,0.570161,0.697192,0.255971,0.080207,0.526600,0.747601,0.239473,0.471753,0.579522,0.473109,pass
11,0.389837,0.323255,0.159886,0.408987,0.455768,0.155161,0.050920,0.013532,0.398486,0.458697,0.195737,0.048283,0.429020,0.576867,0.193964,0.381175,0.438731,0.363404,pass
12,0.518089,0.645037,0.315824,0.657980,0.769937,0.265270,0.091470,0.024009,0.654503,0.774519,0.321748,0.087177,0.642591,0.923507,0.286663,0.577948,0.688136,0.636990,pass
13,0.406237,0.758781,0.384544,0.511746,0.682529,0.239391,0.084062,0.020445,0.716249,0.879179,0.307996,0.100936,0.702238,0.903910,0.316195,0.579123,0.720490,0.601809,pass
14,0.256580,0.438476,0.249279,0.373783,0.487691,0.170885,0.057825,0.015124,0.434316,0.523210,0.204486,0.060976,0.422287,0.615411,0.185836,0.373407,0.456042,0.420070,pass
15,0.471976,0.348195,0.212080,0.431669,0.472500,0.160518,0.063199,0.014264,0.546605,0.613761,0.226773,0.070365,0.501023,0.698671,0.230918,0.445487,0.531017,0.438551,pass
16,0.635800,0.728151,0.429846,0.555260,0.694357,0.224849,0.102997,0.020375,0.845599,0.978958,0.380234,0.110494,0.763197,1.077937,0.338303,0.693349,0.810603,0.738852,pass
17,0.428227,0.449017,0.269253,0.319045,0.464350,0.164208,0.077143,0.014288,0.430819,0.497801,0.221486,0.055607,0.516771,0.650365,0.233646,0.415896,0.505773,0.442728,pass
18,0.530848,0.754647,0.369684,0.783164,0.898206,0.319697,0.087974,0.026455,0.820209,0.969322,0.365708,0.107916,0.782763,1.070944,0.340672,0.706744,0.825030,0.704597,pass
19,0.571885,0.638377,0.414718,0.893265,1.072812,0.378906,0.112308,0.032230,0.814100,0.911719,0.375865,0.102346,0.896023,1.152461,0.389491,0.769748,0.885614,0.772919,pass

BARINEL SCORES

,h 17,cp 11,h 14,cp 4,cp 7,cp 1,cp 13,h 9,h 2,cp 10,h 0,swap 16,cp 12,cp 8,cp 6,cp 3,swap 15,h 5
sum,0.55181,0.51291,0.505538,0.504816,0.498407,0.497555,0.495172,0.494132,0.493587,0.4922,0.488976,0.48824,0.485581,0.484789,0.482565,0.481655,0.479544,0.476986

TARANTULA SCORES

,h 17,cp 11,h 14,cp 4,cp 7,cp 1,cp 13,h 9,h 2,cp 10,h 0,swap 16,cp 12,cp 8,cp 6,cp 3,swap 15,h 5
sum,0.55181,0.51291,0.505538,0.504816,0.498407,0.497555,0.495172,0.494132,0.493587,0.4922,0.488976,0.48824,0.485581,0.484789,0.482565,0.481655,0.479544,0.476986

DSTAR SCORES

,cp 4,cp 8,cp 13,cp 1,h 9,h 17,h 14,h 5,h 0,h 2,swap 16,cp 7,swap 15,cp 3,cp 12,cp 11,cp 6,cp 10
sum,3.998369,2.729874,2.627084,2.474442,2.282375,2.116484,2.080018,1.96458,1.836773,1.806855,1.763152,0.626435,0.6033,0.513856,0.398921,0.0657,0.054598,0.003885

ERROR GATE LOCATION:
17
Now evolving the following mutant:  AddGate_h_inGap_6_.qasm

100%|██████████| 10/10 [00:26<00:00,  2.66s/it]
100%|██████████| 10/10 [00:26<00:00,  2.63s/it]

,swap 17,h 16,swap 15,h 14,cp 13,cp 12,cp 11,cp 10,h 9,cp 8,cp 7,cp 6,h 5,cp 4,cp 3,h 2,cp 1,h 0,pass/fail
0,0.295774,0.328579,0.174020,0.457307,0.564048,0.208229,0.059605,0.017720,0.389349,0.483684,0.163433,0.064839,0.450820,0.514265,0.209788,0.422782,0.582435,0.349310,fail
1,0.536287,0.621293,0.313932,0.514358,0.566182,0.191462,0.055998,0.024855,0.637555,0.712621,0.240178,0.091363,0.634519,0.676862,0.305200,0.603155,0.878368,0.544026,fail
2,0.409165,0.461846,0.191538,0.563107,0.657436,0.230984,0.071709,0.022397,0.531891,0.584075,0.202900,0.075029,0.533680,0.555760,0.248620,0.571203,0.731282,0.461377,fail
3,0.294229,0.456208,0.174685,0.346243,0.428340,0.154826,0.046816,0.016765,0.532236,0.624593,0.216241,0.070357,0.511232,0.565645,0.236090,0.471382,0.677610,0.414437,fail
4,0.635806,0.473328,0.269108,0.466467,0.632171,0.218526,0.064182,0.025509,0.524919,0.592613,0.206989,0.072552,0.539861,0.606932,0.249188,0.474783,0.698216,0.407826,fail
5,0.379278,0.433617,0.210212,0.375680,0.456648,0.150579,0.050503,0.018935,0.440361,0.528002,0.185190,0.071054,0.501272,0.589223,0.229761,0.473900,0.694238,0.402433,fail
6,0.781215,0.407971,0.417148,0.501794,0.703896,0.251026,0.074186,0.029228,0.514969,0.659441,0.216720,0.088696,0.563854,0.652971,0.267431,0.536337,0.790767,0.437290,fail
7,0.555518,0.439081,0.253636,0.373639,0.488299,0.184166,0.053483,0.022393,0.394075,0.482575,0.167209,0.066847,0.456026,0.528053,0.224330,0.444803,0.632156,0.362122,fail
8,0.376652,0.254130,0.236505,0.383838,0.506822,0.174378,0.058029,0.016836,0.408251,0.515140,0.180846,0.064497,0.450031,0.522359,0.197413,0.478296,0.640778,0.365769,fail
9,0.455697,0.593247,0.254911,0.445217,0.492537,0.177612,0.048097,0.021030,0.618806,0.686646,0.228911,0.080635,0.591586,0.611335,0.273378,0.538530,0.795195,0.488118,fail
10,0.533668,0.349063,0.274973,0.402162,0.519618,0.170142,0.057942,0.019482,0.549986,0.653256,0.234246,0.071929,0.522439,0.620259,0.232603,0.546790,0.729628,0.428613,pass
11,0.275403,0.438148,0.149216,0.377562,0.423419,0.145811,0.049430,0.015945,0.404179,0.457558,0.167321,0.060027,0.443447,0.502280,0.202890,0.503134,0.635170,0.397947,pass
12,0.382649,0.299022,0.189010,0.355610,0.473896,0.179796,0.052740,0.017834,0.362494,0.454543,0.154702,0.058671,0.398236,0.485679,0.197336,0.406373,0.527440,0.303306,pass
13,0.686511,0.335286,0.368862,0.426042,0.602813,0.208089,0.064289,0.023813,0.574239,0.668159,0.226501,0.071968,0.520973,0.581630,0.237537,0.547702,0.740013,0.432604,pass
14,0.579151,0.446054,0.307468,0.460474,0.587552,0.205469,0.062358,0.023703,0.518003,0.577776,0.192427,0.073108,0.534025,0.573018,0.245379,0.545117,0.737836,0.453056,pass
15,0.587186,0.444373,0.330200,0.571162,0.698917,0.249440,0.074552,0.025827,0.636532,0.714669,0.251687,0.079807,0.686821,0.772728,0.290468,0.640304,0.879221,0.526775,pass
16,0.529804,0.347903,0.271241,0.399801,0.549478,0.191612,0.059847,0.020868,0.388719,0.458391,0.160227,0.060684,0.430230,0.491798,0.198278,0.477947,0.601115,0.360021,pass
17,0.383143,0.520449,0.232211,0.506567,0.592095,0.194650,0.060985,0.020852,0.585966,0.605828,0.215085,0.071169,0.618397,0.644806,0.257260,0.592047,0.808355,0.524785,pass
18,0.502952,0.416438,0.239151,0.535669,0.667782,0.227113,0.071495,0.022732,0.452931,0.503216,0.169214,0.068744,0.512150,0.551428,0.226193,0.523403,0.682971,0.429593,pass
19,0.475251,0.498498,0.238172,0.527510,0.628598,0.217746,0.065895,0.024104,0.564250,0.639007,0.233054,0.083656,0.608543,0.666822,0.275042,0.582504,0.789682,0.500539,pass

BARINEL SCORES

,h 16,cp 6,cp 3,cp 8,cp 10,cp 7,cp 1,h 5,h 9,cp 4,cp 12,h 0,h 14,swap 15,cp 13,swap 17,cp 11,h 2
sum,0.521838,0.515947,0.50814,0.505904,0.500587,0.500517,0.499636,0.497983,0.497762,0.497138,0.493886,0.492751,0.492497,0.489717,0.488978,0.488809,0.484643,0.483134

TARANTULA SCORES

,h 16,cp 6,cp 3,cp 8,cp 10,cp 7,cp 1,h 5,h 9,cp 4,cp 12,h 0,h 14,swap 15,cp 13,swap 17,cp 11,h 2
sum,0.521838,0.515947,0.50814,0.505904,0.500587,0.500517,0.499636,0.497983,0.497762,0.497138,0.493886,0.492751,0.492497,0.489717,0.488978,0.488809,0.484643,0.483134

DSTAR SCORES

,cp 1,cp 8,cp 4,cp 13,h 5,h 9,h 2,swap 17,h 16,h 14,h 0,swap 15,cp 3,cp 7,cp 12,cp 6,cp 11,cp 10
sum,2.960015,2.189731,2.134115,1.918817,1.792639,1.657491,1.636929,1.491379,1.417121,1.346198,1.24786,0.494305,0.48204,0.336087,0.314478,0.051994,0.031963,0.004553

ERROR GATE LOCATION:
15

,Program,path_to_mutant,exam_score
0,AddGate_h_inGap_6_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.777778
1,AddGate_h_inGap_9_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.055556
2,AddGate_cswap_inGap_3_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.277778
3,AddGate_swap_inGap_3_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.111111
4,AddGate_cswap_inGap_4_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.611111
5,AddGate_ry_inGap_4_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.166667
6,AddGate_swap_inGap_4_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.888889
7,AddGate_cswap_inGap_5_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.833333
8,AddGate_h_inGap_12_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.055556
9,AddGate_h_inGap_7_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.055556
10,AddGate_ry_inGap_1_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.888889
11,AddGate_h_inGap_4_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.388889
12,AddGate_h_inGap_5_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.055556
13,AddGate_h_inGap_8_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.055556
14,AddGate_h_inGap_1_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.722222
15,AddGate_swap_inGap_5_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.666667
16,AddGate_h_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.055556
17,AddGate_h_inGap_3_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.444444
18,AddGate_h_inGap_2_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.444444
19,AddGate_ry_inGap_5_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.111111
20,AddGate_h_inGap_11_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.111111
21,AddGate_swap_inGap_2_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.388889

,Program,path_to_mutant,exam_score
0,AddGate_h_inGap_6_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.777778
1,AddGate_h_inGap_9_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.055556
2,AddGate_cswap_inGap_3_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.277778
3,AddGate_swap_inGap_3_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.111111
4,AddGate_cswap_inGap_4_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.611111
5,AddGate_ry_inGap_4_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.166667
6,AddGate_swap_inGap_4_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.888889
7,AddGate_cswap_inGap_5_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.833333
8,AddGate_h_inGap_12_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.055556
9,AddGate_h_inGap_7_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.055556
10,AddGate_ry_inGap_1_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.888889
11,AddGate_h_inGap_4_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.388889
12,AddGate_h_inGap_5_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.055556
13,AddGate_h_inGap_8_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.055556
14,AddGate_h_inGap_1_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.722222
15,AddGate_swap_inGap_5_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.666667
16,AddGate_h_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.055556
17,AddGate_h_inGap_3_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.444444
18,AddGate_h_inGap_2_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.444444
19,AddGate_ry_inGap_5_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.111111
20,AddGate_h_inGap_11_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.111111
21,AddGate_swap_inGap_2_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_qft_5_q...,0.388889